### ISSUE TITLE
Add "Glow Effect" on lights when a connection was set on the "Toggleable Largue Faith Plate"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1001]

**Comment by LautaroL20** [comment]
This effect should be only when there is a connection only though.

**Comment by TeamSpen210** [comment]
Should this be added to all faith plates? It looks quite nice:
![620_20161120160350_1](https://cloud.githubusercontent.com/assets/8453732/20460768/2ae6527e-af3b-11e6-9ebc-9f830095cdff.png)

**Comment by LautaroL20** [comment]
Absolutely, yes!

**Comment by LautaroL20** [comment]
This also would fit well on the Overgrown Style and BTS too.

**Comment by ZombiePwner1** [comment]
It should be malfunctioning in overgrown style where it turns off and on.

**Comment by TeamSpen210** [comment]
This is implemented now.
