### ISSUE TITLE
Add rusty effects on "Hoopy", and "Metal Pillars" from the overgrown elevator corridors

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1002]
Hoopy and the pillars from the elevator corridos needs rusty effects:

![20161113090024_1](https://cloud.githubusercontent.com/assets/12244376/20245723/df09efd8-a985-11e6-8642-9565772e64ba.jpg)

![20161113094723_1](https://cloud.githubusercontent.com/assets/12244376/20245755/856a7b68-a986-11e6-97cf-e325ea667093.jpg)

**Comment by ZombiePwner1** [comment]
The ring has a name.

**Comment by Luke18033** [comment]
I don't think there's a rusted version of Hoopy...

**Comment by LautaroL20** [comment]
Well, TeamSpen210 would recompile the model with a $detail settings to get rusted effects on them, as he done with the actual catwalk item, take a look at this beauty:

![20161116220526_1](https://cloud.githubusercontent.com/assets/12244376/20372312/eccf8f7c-ac48-11e6-9b08-a63314149b5f.jpg)

**Comment by ZombiePwner1** [comment]
There is no rusted version of hoopy since u know being valve they don't have a rusted model for all models.

**Comment by Luke18033** [comment]
@ZombiePwner1 There were no rusted versions of catwalks either, so @TeamSpen210 added it.

**Comment by Luke18033** [comment]
Making a rusted version of Hoopy actually wouldn't make much sense, Hoopy isn't rusted when he appears in GLaDOS' ruined chamber.

**Comment by ZombiePwner1** [comment]
Valve didn't bother to make rusted models for the pillars in fact half of clean items were used in overgrown.

**Comment by ZombiePwner1** [comment]
Actually hoopy is made out of metal since at the end of P1 hoopy is seen falling on the parking lot and when it lands it makes a metal sound.

**Comment by Luke18033** [comment]
Hoopy isn't really a significant enough model to need a rusted version. I'm honestly not sure about the rusted stuff in general, the catwalks look okay but most of the other rusted models just look kind of bad.

**Comment by LautaroL20** [comment]
Yep, I have to admit that by the issue´s time (2016) I was a kind of fundamentalist of the "rusted model effect", probably due to some immaturity taste or something...
