### ISSUE TITLE
 Overgrown High energy pellets and catchers are using their clean model

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1015]
![20161118172448_1](https://cloud.githubusercontent.com/assets/18079316/20425100/fb8d542e-adb3-11e6-8630-3a61f07d08a8.jpg)

**Comment by Luke18033** [comment]
Bump

**Comment by Luke18033** [comment]
TspenAddons actually had variants for both of these, which could be used.

**Comment by TeamSpen210** [comment]
I even made skins for the infinite launchers and timed catchers... The only thing is those catchers had neat partially-collapsed orientations, which I'd want to replicate.
