### ISSUE TITLE
Overgrown CO-OP Dissasemble room is missing its "Rusty Visuals" on Metal Pillars 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1017]
![20161118100737_1](https://cloud.githubusercontent.com/assets/12244376/20431129/26f4cde6-ad77-11e6-8956-48d9a32427e2.jpg)

**Comment by Luke18033** [comment]
Since when has there been a co-op label?

**Comment by LautaroL20** [comment]
I maded that lavel. I found it useful.

**Comment by ZombiePwner1** [comment]
How did you make that label?

**Comment by ZombiePwner1** [comment]
@LautaroL20 It's called label not lavel.

**Comment by ZombiePwner1** [comment]
I already have this.
![20161125181523_1](https://cloud.githubusercontent.com/assets/18079316/20624253/d44d83e6-b346-11e6-84f4-54e1a9140b5a.jpg)





![20161125182056_1](https://cloud.githubusercontent.com/assets/18079316/20624256/db26e478-b346-11e6-98d5-f030b29a4b88.jpg)

**Comment by LautaroL20** [comment]
Awesome!
