### ISSUE TITLE
Add Rusty visuals on Triple Wallpipes

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1018]
![20161118101431_1](https://cloud.githubusercontent.com/assets/12244376/20431283/02560148-ad78-11e6-8952-6871a6456f73.jpg)

**Comment by Luke18033** [comment]
You must really like rusted versions of items...

**Comment by LautaroL20** [comment]
Yes, don´t you?

**Comment by Luke18033** [comment]
I don't use BEE2 much anymore, trying to learn Hammer.

**Comment by Luke18033** [comment]
I agree, these look a lot nicer than the originals.
![20161123191313_1](https://cloud.githubusercontent.com/assets/19228201/20586159/383c737c-b1b6-11e6-98af-c77803cb0728.jpg)

**Comment by LautaroL20** [comment]
Do not forget to add the rusted models from Metal Pillars and Wallpipes, i wanna test them out!
