### ISSUE TITLE
Overgrown Large Observation´s Plants dissapear in a "Mysterious way" when you watch them from up

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1019]
Note that this also happened with the original instance from the PRL22 packages too, i wanted to make sure that i didn´t broken it. It looks like there is a leak somewhere.

__________________________________________________________________________________________________

GIF:

![gif](https://cloud.githubusercontent.com/assets/12244376/20432499/2d43ff44-ad7e-11e6-8f4f-4a528a5df1bb.gif)

**Comment by ZombiePwner1** [comment]
It's not to do with leaks models don't disappear because of leaks it's a game bug since i've sometimes gotten this issue in the regular campaign maps.

**Comment by LautaroL20** [comment]
Wait until TeamSpen says if its fixeable or not.

**Comment by Luke18033** [comment]
This is probably a valve bug.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Is this a valve bug?

**Comment by LautaroL20** [comment]
Ill figure out if this has to do only with that plant model in particular, or all the entirely vines catalogue are being affected too.

**Comment by LautaroL20** [comment]
This has to do with the invisible material file configuration from the observation´s glass. It also happens with the triggers editor models when you put a cube thru them, they will dissapear in a mysterious way when watching it from certain angles.
