### ISSUE TITLE
Overgrown Single Catwalk is missing its "Rusty Visuals" on its pillars

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1021]
![20161118102403_1](https://cloud.githubusercontent.com/assets/12244376/20473227/fd4f62de-af9d-11e6-81d6-3ae3461c4623.jpg)

**Comment by ZombiePwner1** [comment]
There are so many clean models in overgrown which need rusting.

**Comment by ZombiePwner1** [comment]
@LautaroL20 I can fix this thankfully.

**Comment by ZombiePwner1** [comment]
@LautaroL20 This has been fixed


![20170205113332_1](https://cloud.githubusercontent.com/assets/18079316/22623474/1445f4d2-eb97-11e6-8c20-ddd84625580a.jpg)

**Comment by Luke18033** [comment]
Fixed now?
