### ISSUE TITLE
80´s Old Aperture´s Track Platform is having a wrong "Lighting Origin"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1030]
![20161122221128_1](https://cloud.githubusercontent.com/assets/12244376/20548526/e8a917ec-b102-11e6-95a7-9ecd3db4a9bc.jpg)

**Comment by TeamSpen210** [comment]
It's not actually a wrong lighting position, it's a brush instead of a compiled model. I'll want to switch to the latter.
