### ISSUE TITLE
[PRL 23] 1/4 thick wall has missing icon in the editor.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1033]
![20161123154148_1](https://cloud.githubusercontent.com/assets/18079316/20553945/7099a33e-b193-11e6-88d0-ab2de2a29c06.jpg)

**Comment by LautaroL20** [comment]
Fixed via: c4c892e032a4ac70805c2be608f038dcf967c12f

**Comment by LautaroL20** [comment]
Wich other icons are missing in the PeTi palette?

**Comment by ZombiePwner1** [comment]
I fixed those icons it turns out when I installed prl 23 I did something wrong causing things to mess up.
