### ISSUE TITLE
Overgrown SP Exit Corridors: N°1, 2 and 4 causes "Failure to compile"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1040]
| Could not open instance file instances/bee2/over/elevator_sp/elevator_exit/exit_stairs.vmf

**Comment by Luke18033** [comment]
Lol, I had this same problem and was just about to report it!

**Comment by LautaroL20** [comment]
Yep, it also happens with corridor 1 too. Im unsure if other corridors also are causing problems though. Thanks for the tip!

**Comment by ZombiePwner1** [comment]
How do you guys make these labels?

**Comment by ZombiePwner1** [comment]
Oh wait nvm i found the way to make labels.

**Comment by LautaroL20** [comment]
Making new lavels are pretty easy, but take care to not making useless ones...

**Comment by LautaroL20** [comment]
Ok, it looks like the problem are affecting the SP Exit Corridors: N°1, 2 and 4. But the number 3 Floor bts is the only that don´t cause failures.

**Comment by TeamSpen210** [comment]
Yep, `exit_stairs.vmf` is the instance for the staircase in the exit for non Floor BTS corridors.

**Comment by ZombiePwner1** [comment]
I can use those corridors perfectly fine without compile issues.
