### ISSUE TITLE
A "Mysterious Cave Johnson Portrait" always appears in the mandatory observation room

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1044]
Even without being selected "Multiverse cave", and having set the "voice" to none, it will always appear there.
_______________________________________________________________________________________________________

![20161123202319_1](https://cloud.githubusercontent.com/assets/12244376/20581982/7662e37a-b1bb-11e6-9129-2698d85626ba.jpg)

**Comment by ZombiePwner1** [comment]
That's obviously a new thing Spencer added

**Comment by LautaroL20** [comment]
Yep, its a good idea actually, but it should only take effect when cave´s lines are enabled.

**Comment by ZombiePwner1** [comment]
i don't think so having cave johnson lines in clean style would be abit weird considering there are no prerecorded messages in clean.

**Comment by LautaroL20** [comment]
Im talking about the Workshop Multiverse Cave. Its an ammount of voicelines that valve did when you play a PeTi map.

**Comment by ZombiePwner1** [comment]
Well you could've said that in your previous sentence.

**Comment by LautaroL20** [comment]
Well, its obvios that cave doesn´t take any choreographic role unless you play a PeTi Workshop map.

**Comment by LautaroL20** [comment]
(Respect to the Clean style).

**Comment by TeamSpen210** [comment]
This should only happen if you have chosen a Cave line, and I thought I fixed that..
