### ISSUE TITLE
Implement "Rusty / Dirty Visuals" on the Sendificator in-game model

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1045]

**Comment by TeamSpen210** [comment]
Is this the editor model, or ingame model?

**Comment by LautaroL20** [comment]
The suggestion goes for the in-game model. Next time, ill attach a screenshot on the post.

**Comment by Luke18033** [comment]
Everything doesn't need to be rusted, some things can just be dirty...

**Comment by LautaroL20** [comment]
> Some things can just be dirty.

Or maybe they can have both Dirty / Rusty.

**Comment by TeamSpen210** [comment]
HMW has created several rusty skins for it already - the actual Sendificator maps are Overgrown to begin with.

**Comment by Luke18033** [comment]
@TeamSpen210 - Where can I download those maps?

**Comment by TeamSpen210** [comment]
Search for "Sendificator" on the workshop. I should make the "More Info" link or otherwise link to them.

**Comment by Luke18033** [comment]
That would link to the Sendificator wiki page, which could then have a link to the maps.
