### ISSUE TITLE
Anti-Bridge/Funnel Field

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1046]
A custom fizzler which blocks light bridges and excursion funnels, but not anything else.

**Comment by ZombiePwner1** [comment]
Great idea. The color for this should be a mix between of dark blue and light blue.

**Comment by Luke18033** [comment]
I just realized it should block lasers too.

**Comment by LautaroL20** [comment]
Ummm... Honestly i can't imagine a puzzle concept taking advantage of this rare item. Alternatively i could use, for example, a 90° angled panel that would block these and once closed, i can walk through it.

**Comment by Luke18033** [comment]
The player would still be able to move through (even if floating in the funnel), allowing to create some interesting puzzles.

**Comment by ellingtonvengaboysmuseum** [comment]
i might be able to do this with a bit of work, but i think i can only make it block physics, lasers, funnels, paint, bridges etc.

**Comment by ellingtonvengaboysmuseum** [comment]
lets call this new fizzler the "Non Solid Energy Repulsion Field"

**Comment by Luke18033** [comment]
That's okay, but Light Bridges are solid.

**Comment by TeamSpen210** [comment]
I don't think this is doable, at least while still allowing players and objects through.

**Comment by Luke18033** [comment]
@TeamSpen210 If that's the case then issue closed.

**Comment by Luke18033** [comment]
Actually, see [here](https://www.youtube.com/watch?v=JKMm_G2GrT4&feature=youtu.be). To make this custom fizzler work, we could just intentionally make this happen at the location of the fizzler.

**Comment by TeamSpen210** [comment]
I don't know why that happened.

**Comment by Luke18033** [comment]
I should have linked to the original issue, #887. You added a commit to fix it, so just un-fix it for this fizzler.

**Comment by TeamSpen210** [comment]
That won't work - the fix I used was to ensure the panel is solid to everything. That can't work for the fizzler.

**Comment by Endermage77** [comment]
Perhaps you could implement some sort of logic that creates an invisible panel where a bridge/funnel is that players can't touch but still blocks the bridge/funnel?
Or, failing that, just an invisible panel that blocks everything.

**Comment by Luke18033** [comment]
@Endermage77 - If it was made so that it blocks everything, then I would just be a suggesting the Closed Solid Field (#776), and therefore this would be a duplicate. I'd like a fizzler that blocks light bridges, lasers, and excursion funnels, but nothing else. This doesn't appear to be possible though.
