### ISSUE TITLE
Catwalk is using a clean model on the wall.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1051]
![20161124155329_1](https://cloud.githubusercontent.com/assets/18079316/20590476/359f1914-b25e-11e6-8f45-e02f0b0bcad9.jpg)

**Comment by Luke18033** [comment]
That's strange.  I have an overgrown test with catwalks and they're not doing this.

**Comment by LautaroL20** [comment]
Yep, thats weird, it was a bug thats supposed to have been fixed already. I also don´t have that problem anymore. Here is the old post about this issue: https://github.com/TeamSpen210/BEE2-items/issues/1000

**Comment by Luke18033** [comment]
@ZombiePwner1 Are you using Pr23?

**Comment by LautaroL20** [comment]
Maybe give us the .p2c puzzle file so we can use your exact catwalk positions into the editor?

**Comment by ZombiePwner1** [comment]
@Luke18033 I am using prl 23 u dummy if i wasn't then how would i get the rusted walkways?

**Comment by ZombiePwner1** [comment]
Fixed it myself by changing it to the rusted version.
