### ISSUE TITLE
Portal Stories Mel Gun and Potato Gun stylevars

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1052]
A drop-down to use the gun from PS:M or Potato Gun.

**Comment by LautaroL20** [comment]
A stylevar to use the potatos gun too.

**Comment by Luke18033** [comment]
Create a separate issue, don't rename mine...

**Comment by LautaroL20** [comment]
Why, so that later you say my post is a duplicate of this? Better to merge identical suggestions in one post.

**Comment by Luke18033** [comment]
@LautaroL20 No...Potato Gun is different than Mel Gun, they should be separate issues

**Comment by TeamSpen210** [comment]
I'd probably add this as a dropdown to choose from all of them.

**Comment by Luke18033** [comment]
TeamSpen210 mentioned on Discord that he has a different way of implementing POTaTOS he thought of, so I'll remove that part.

**Comment by Luke18033** [comment]
And actually, the Mel gun would also be a problem when enabled at the same time as other gun variants, or when used in Tag, so I'll just go ahead and close this

**Comment by TeamSpen210** [comment]
Also, Anna has said they (Prism Studios) don't want people to use the really core parts of Mel (the gun, Mel, Virgil, AEGIS) anywhere else.
