### ISSUE TITLE
"Flickering Excursion Funnel" stylevar

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1053]
Add a stylevar to disable random Excursion Funnel shut-off in Overgrown.

**Comment by LautaroL20** [comment]
Thats how the tractor beam is supposed to work in Overgrown style, some items are supposed to be a bit damaged to fit with the overgrown athmospere.

**Comment by Luke18033** [comment]
It looks terrible though...

**Comment by LautaroL20** [comment]
I don´t think so, it fits with all the damaged athmosprere...

**Comment by ZombiePwner1** [comment]
This is not a bug as @LautaroL20 said it's intentional.

**Comment by Luke18033** [comment]
PS:M doesn't do this in Overgrown maps. @TeamSpen210 please remove it or add an alternate version

**Comment by LautaroL20** [comment]
Do not remove it, add an aditional stylevar option but do not remove this effect. Fits pretty well with the damaged athmospere.

**Comment by Luke18033** [comment]
@TeamSpen210 I noticed that you called the stylevar "Flicking Overgrown Funnel", did you mean "flick**er**ing"?

**Comment by Luke18033** [comment]
I think it'd actually be a good idea to make this off by default, I've heard a lot of people in various places complaining that the flickering funnel looks bad.

**Comment by LautaroL20** [comment]
And i think that tastes are tastes, so thats why the option should still remain there.

**Comment by Luke18033** [comment]
Which it would still be there, it would just start off.
