### ISSUE TITLE
Overgrown Exit 3 Door doesn't close

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1056]
When the overgrown exit door is deactivated, it doesn't close. This is the only thing preventing me from releasing my map!

UPDATE: I am waiting for decorations (BenVlodgi/BEE2.4#414) to be released before I release this map.

**Comment by LautaroL20** [comment]
:(

**Comment by Luke18033** [comment]
Oh btw I'm using exit 3 (flooded)

**Comment by LautaroL20** [comment]
I have tested this in the dev version as well as with PRL23 and that SP Exit Door always closes, be it activated or deactivate. IDK why do you experience this issue...

**Comment by ZombiePwner1** [comment]
Works for me case closed

**Comment by Luke18033** [comment]
@ZombiePwner1 It's only on exit 3 (floor BTS)

**Comment by LautaroL20** [comment]
Me and ZombiePwner1 we are using the SP Exit N°3 "floor BTS, and we haven´t this problem...

**Comment by Luke18033** [comment]
Huh. Test it with a weighted button, that was what I had the problem with.

**Comment by LautaroL20** [comment]
Well, i doubt that buttons connections can cause problems on this. Ill gonna test this later.

**Comment by Luke18033** [comment]
@LautaroL20 @ZombiePwner1 Tested it with several items, this happens with everything.

**Comment by Luke18033** [comment]
See, this is a real bug: 398f371
