### ISSUE TITLE
Overgrown Exit Stairs corridor are making floor textures too dark under the stair platform

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1060]
![20161124211526_1](https://cloud.githubusercontent.com/assets/12244376/20611615/b1059c30-b28c-11e6-92a6-800cd1946141.jpg)

**Comment by ZombiePwner1** [comment]
Disable the shadows on them.

**Comment by LautaroL20** [comment]
Now fixed.

**Comment by Luke18033** [comment]
Wait I thought exit stair instance was missing

**Comment by ZombiePwner1** [comment]
We fixed it @Luke18033.
