### ISSUE TITLE
Implement "Rusty Visuals" on Overgrown Doors

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1061]
Door needs more dirt and moss as all it really has is black marks on it's sides.

**Comment by LautaroL20** [comment]
Uhmm, it wouldn´t make much sence adding "Broken Glass" to the "Bendy figure"... Unless bendy were a glass character.

**Comment by ZombiePwner1** [comment]
The bendy figure on the door is made of glass and it should have broken glass.

**Comment by Konclan** [comment]
IMO doors don't need to be touched, there is only so much you can rust before you're overdoing it

**Comment by LautaroL20** [comment]
This is not a good suggestion. The door actually has a bit of damaged details so this is not really necesary.
