### ISSUE TITLE
Trigger Once not working properly, it activates connected items even if not all other inputs are active

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#1062]
Connecting a trigger to an AND gate activates the gate even though not all connections are active. Trigger once keeps the AND gate active until another signal turns on and off.

__________________________________________________________________________________________

![20161127204855_1](https://cloud.githubusercontent.com/assets/12244376/20652984/8239a65e-b4e3-11e6-9177-4a646ef466c8.jpg)

**Comment by Luke18033** [comment]
I am using triggers + and gates and not having this problem.

**Comment by LautaroL20** [comment]
So, anyone is getting this bug? Ill have to look into this.

**Comment by LautaroL20** [comment]
Yes, AND Gate aren´t working properly. Try connecting a trigger once, button pedestal and a weighted button, youll gonna see how the AND Gate will send the output even when not all connections got pressed:
![20161127204855_1](https://cloud.githubusercontent.com/assets/12244376/20652984/8239a65e-b4e3-11e6-9177-4a646ef466c8.jpg)

**Comment by Luke18033** [comment]
With some experimentation with other items, I've discovered that this is not a bug with AND Gates, but a bug with triggers. They activate the item they are connected to even if not all inputs are active.

**Comment by LautaroL20** [comment]
I thought this bug was fixed a time ago.

**Comment by TeamSpen210** [comment]
It should be, I found a fault in the logic.

**Comment by Luke18033** [comment]
So, should this be closed?

**Comment by LautaroL20** [comment]
Probably...
