### ISSUE TITLE
The SP Entry Corridor N°7 "Tiltled" is having a stretching nodraw bar on its roof

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1063]
I have tried to fix this but i always end up making some leak even when i make sure to link all the walls togheter. 

___________________________________________________________________________________________________

![20161125022648_1](https://cloud.githubusercontent.com/assets/12244376/20615380/1a2cbc04-b2b8-11e6-8689-b5c9a480d81b.jpg)

**Comment by TeamSpen210** [comment]
This is actually because the worldportals are misaligned.
