### ISSUE TITLE
Overgrown coop disassembles rooms BTS lights are floating in a mysterious way.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1065]
![20161125194754_1](https://cloud.githubusercontent.com/assets/18079316/20624508/4894009e-b348-11e6-91f2-8403a4e71d2a.jpg)

**Comment by LautaroL20** [comment]
LOL

**Comment by LautaroL20** [comment]
Well, it is impossible to notice this unless you were using cheats. This is how they actually looks when you aren´t cheating:

![20161125190120_1](https://cloud.githubusercontent.com/assets/12244376/20635864/cf592ba6-b341-11e6-91da-ce0460bd910e.jpg)

**Comment by TeamSpen210** [comment]
Still should fix it though.

**Comment by ZombiePwner1** [comment]
The side i mentioned is the side where the lights are floating the other side isn't floating.
