### ISSUE TITLE
Many rusty wallpipes from the SP Entrance corridor N°6 and COOP Exit Dissasemble room are still showing as clean ones

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1068]
![20161125221009_1](https://cloud.githubusercontent.com/assets/12244376/20637173/f24ed122-b35c-11e6-87aa-8c98199d0220.jpg)
![20161118101431_1](https://cloud.githubusercontent.com/assets/12244376/20431283/02560148-ad78-11e6-8952-6871a6456f73.jpg)

**Comment by LautaroL20** [comment]
Well, this is because the instances are still using the VPK´s Valve Models. I will have to change the model name of each one through hammer.

**Comment by ZombiePwner1** [comment]
Atleast i made sure to completely change every single wall pipe in every instance or corridor.

**Comment by LautaroL20** [comment]
I fixed this already. Now all the Wallpipes are set to the actual rusty skin now.
