### ISSUE TITLE
Add "Rusty Visuals" on the "Pipe_12_corner, and Pipe_12_128"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1072]
![screenie](https://cloud.githubusercontent.com/assets/12244376/20637979/e61bfc1c-b376-11e6-9a07-5659018f6fc5.png)

**Comment by ZombiePwner1** [comment]
Don't forget not everything is made out of metal it could be made out of plastic. Also plastic doesn't rust.

**Comment by LautaroL20** [comment]
Well, if you look them in-game, they looks like metal.

**Comment by Byzarru** [comment]
Even plastic would be worn out though.

**Comment by Luke18033** [comment]
@LautaroL20 Why does *everything* need to be rusted?

**Comment by LautaroL20** [comment]
If you like to have unstyled things, you still will be able to manually get back to the original Valve models.

**Comment by Luke18033** [comment]
Not really needed, not every prop needs a dirty skin

**Comment by LautaroL20** [comment]
> Luke18033 said: "not every prop needs a dirty skin"

Seeing at the time that this issue was opened, probably not every prop had a dirty skin and thats why this suggestion was made.
