### ISSUE TITLE
The Overgrown SP Entry corridor N°2 is having "Worldportals Missaligned" causing "Two stretching Nodraw Bars"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1075]
![20161127204024_1](https://cloud.githubusercontent.com/assets/12244376/20653008/31a61c30-b4e4-11e6-81d8-58e1c36f8d81.jpg)

**Comment by ZombiePwner1** [comment]
@LautaroL20 Thats not a world portal issue it's to do with the brushes Spencer's obviously moved them accidently revealing nodraw

**Comment by TeamSpen210** [comment]
It's either the worldportal or the brushes.
