### ISSUE TITLE
Large Faith Plate needs a proper "Selection Mesh", its a bit difficult to find the "Grip" point

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1076]
![faith plate](https://cloud.githubusercontent.com/assets/12244376/20653313/bc87efa8-b4ea-11e6-94fe-55f5d9ffd23e.jpg)

**Comment by ZombiePwner1** [comment]
Quite a few items have glitchy hit boxes for their editor models which need fixing.

**Comment by TeamSpen210** [comment]
Turn on `puzzlemaker_drawselectionmeshes` to see the actual shape.
