### ISSUE TITLE
Autosave Item

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1077]
An invisible item which will autosave the map when activated. This would be useful to have, for example, a buttton that auto-saves the map. Auto-Respawn would set whether it is retriggerable, and a timer widget would allow enabling dangerous save mode. This would probably use the compiler to connect everything to a single autosave entity, instead of duplicating it for each item in the map.

The autosave message (#983) would be used for this once it's implemented.

When combined with a Trigger Once, this would have the same functionality as a Trigger Autosave or Save Point, so it could possibly replace them later on. (Although I'm not sure what else the Sphere variant of triggers could be used for.)

**Comment by TeamSpen210** [comment]
I'll add this to those items. Start Enabled isn't really needed, they'd activate multiple times normally.

**Comment by ZombiePwner1** [comment]
There is no point for this just connect a button to a trigger auto save and make sure the connection visibility is non visible.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Trigger autosave has a "Fake" connection, it does not have any imputs.......

Also, this item could be really useful for intrincate situations where the player could never reach a trigger autosave. I could provide an example of this but its hard to tell.

**Comment by Byzarru** [comment]
I tried connecting to a trigger autosave and it kept my map from compiling. This is an item I'd love to see.

**Comment by LautaroL20** [comment]
> I tried connecting to a trigger autosave and it kept my map from compiling.

Well, trigger autosave isn´t supposed to work with any connections. So, failures to compile can happens.

**Comment by Luke18033** [comment]
Actually, Start Enabled is needed - you could have a button which is only supposed to autosave the game the first time it is pressed.

**Comment by Luke18033** [comment]
Maybe this should also have a timer property, to enable the dangerous save mode?

**Comment by LautaroL20** [comment]
That could also be surpassed by the player, you are at the edge of a boxel then you jump into goo by accident just a half second before the saving process got done and it would make this useless. The most efficient behavior to prevent this, would be editting the logic of the trigger to make it respawning the player always in the center of the boxel, no matter the spot where you had been before it got activated.

**Comment by TeamSpen210** [comment]
That's not how the dangerous timer works. It saves the game immediately, but writes it to a temporary location. After the timer has elapsed if you're still alive it moves the autosave data to the proper location. So it ensures you have at least that many seconds alive after it triggers. So in that situation either you're on safe ground for that time so it saves, or you fall into the goo and it discards the autosave.

**Comment by Konclan** [comment]
Moving to #3886
