### ISSUE TITLE
Large Faith Plate is being packed as a "Mysterious Nodraw Square" when its placed in some walls

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1080]
They´re being packed as a "Mysterious Nodraw Square" when placed in some walls (This doesn´t happens in all the walls):

![20161128011217_1](https://cloud.githubusercontent.com/assets/12244376/20656161/73b16a0c-b508-11e6-81b4-f3a8340f2e19.jpg)

_______________________________________________________________________

Map editor screen, in case you want to replicate the bug:

![20161128011527_1](https://cloud.githubusercontent.com/assets/12244376/20656169/920747ba-b508-11e6-9ec3-0480d4cefdb5.jpg)

**Comment by ZombiePwner1** [comment]
:( I love these faith plates and they are broken on the walls.
