### ISSUE TITLE
Old aperture Gel Droppers In-game and editor Models needs to be reescaled to prevent it from "Crossing the wall"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1081]
![20161128015637_1](https://cloud.githubusercontent.com/assets/12244376/20657421/6e58f726-b514-11e6-87f5-8cec643f2ccf.jpg)

**Comment by ZombiePwner1** [comment]
This is why you don't place underground gel droppers like this.

**Comment by Luke18033** [comment]
This is now implemented
