### ISSUE TITLE
The "Monitor Screen" doesn´t work well, image is being generated inside its hole instead of being in the screen

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1083]
![20161128015706_1](https://cloud.githubusercontent.com/assets/12244376/20657558/79e1135c-b515-11e6-95da-b78d9e36a69d.jpg)

**Comment by Jadeygaming** [comment]
Same happens with original : 
![20161127225132_1](https://cloud.githubusercontent.com/assets/22718537/20658776/4100fb22-b4f4-11e6-9986-092578b54ee8.jpg)


![20161127225137_1](https://cloud.githubusercontent.com/assets/22718537/20658782/463daea0-b4f4-11e6-9199-15a80207da69.jpg)

**Comment by LautaroL20** [comment]
Well, looks like this happens in other styles aswell.

**Comment by Luke18033** [comment]
It doesn't happen in Overgrown, monitors in my map work fine.

**Comment by Jadeygaming** [comment]
Can Someone Fix This! I love monitors!

**Comment by ZombiePwner1** [comment]
This is actually pretty easy to fix i fixed it myself.
![20161205091717_1](https://cloud.githubusercontent.com/assets/18079316/20871013/ce138296-bacb-11e6-8823-a34bfd5354b2.jpg)

**Comment by Jadeygaming** [comment]
When should bug fix come out?

**Comment by LautaroL20** [comment]
Well, it will come out with the PRL24.

**Comment by Jadeygaming** [comment]
Oh...
