### ISSUE TITLE
Overgrown Large Faith Plate needs a "Lighting Origin"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1084]
![20161128031031_1](https://cloud.githubusercontent.com/assets/12244376/20657919/5215faec-b518-11e6-857d-c5e4c7dc598c.jpg)

**Comment by ZombiePwner1** [comment]
Add light strips to it you dummy.

**Comment by LautaroL20** [comment]
No need to insult here, we should keep respect on github. Anyways try placing light strips, youll not gonna see a significant difference...

**Comment by ZombiePwner1** [comment]
Lol @LautaroL20 you know I'm joking

**Comment by LautaroL20** [comment]
I have tried to add a lighting origin but unfortunately it didn´t work:

![20161221225230_1](https://cloud.githubusercontent.com/assets/12244376/21412631/73afb01a-c7d0-11e6-8d77-3e60f23257e5.jpg)

**Comment by TeamSpen210** [comment]
Actually it's both Clean and Overgrown, and the faith plate was using a lighting origin inside the wall.
