### ISSUE TITLE
Counters

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1085]
### Counter ###
This would use timer logic to set a number to count to, add one to the count when it receives an input, and sends an output when it reaches its count number as set by the timer. Counters could come in an invisible variety, like timers and triggers, or a visible version that displays either the number the counter is at or the fraction of the current count to the count number.

*(See #3072 for object triggers and #2877 for intangible scaffolds)*

**Comment by Byzarru** [comment]
New item, too.

**Comment by Jadeygaming** [comment]
I like it. Bravo!

**Comment by Luke18033** [comment]
The scaffold wouldn't need to be invisible and non-collision, it could literally just generate nothing into the compiled chamber. So the editor would not show a "invalid position", but you would still be placing floating items.

**Comment by Byzarru** [comment]
"Scaffold" would probably be the best way to describe it in the editor, though. But yeah.

**Comment by Flametusk** [comment]
The scaffold shouldn't collide with anything in the editor, although maybe it could be used to split glass/grating into different squares? Like how it seems to do when glass intersects grating.

**Comment by Endermage77** [comment]
The counter should count backwards when reversed, yes?

**Comment by Luke18033** [comment]
Combined issue. Object triggers and intangible scaffolds now have their own issues so I'll repurpose this just for counters.

**Comment by Konclan** [comment]
Moving to #3886
