### ISSUE TITLE
Typo In Song From PS: Mel 

### ISSUE THREAD

**Issue by TheReviewers** [BEEmod/BEE2-items#1086]
AEGIS is misspelled AGIS in the description...

_______________________________________________________________________________

While we're at it:
- "Skototrophism" should be spelled "Skototropism"
- "Halted Production" should be listed as "System Corruption (Alternate)"
- Halted Production should be added to the listing
- "System Corruption (Alternate)" should be listed as "System Corruption 2"

This is based on the listings in BEE2 and not what actually gets exported.

**Comment by Byzarru** [comment]
While we're at it:
- "Skototrophism" should be spelled "Skototropism"
- "Halted Production" should be listed as "System Corruption (Alternate)"
- "System Corruption (Alternate)" should be listed as "System Corruption 2"
