### ISSUE TITLE
Bee2.4 makes a permanet "Complete empty slot" after the dropdown bar is diplayed.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1087]
![beemod](https://cloud.githubusercontent.com/assets/12244376/20687915/3112a964-b59d-11e6-9612-75bf096c81bd.png)

**Comment by LautaroL20** [comment]
This bug may also happens in the public release too.

**Comment by GiovanH** [comment]
This is

1. An issue with https://github.com/BEEmod/BEE2.4, not the items package
2. No longer present
