### ISSUE TITLE
Overgrown departure elevator screens are missing their broken glass and dirt.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1089]
Departure: No dirt or broken glass is present.

![20161129151927_1](https://cloud.githubusercontent.com/assets/18079316/20700350/c551b246-b647-11e6-953f-493a79c126d3.jpg)

![20161129152205_1](https://cloud.githubusercontent.com/assets/18079316/20700353/cacd901e-b647-11e6-8c30-076c236be9e9.jpg)

Arrival elevator: Broken glass and dirt is present.

![20161129152140_1](https://cloud.githubusercontent.com/assets/18079316/20700372/e3d562d0-b647-11e6-92a0-68062ac5d020.jpg)

![20161129152146_1](https://cloud.githubusercontent.com/assets/18079316/20700378/f7f260ce-b647-11e6-8680-541a206d8848.jpg)

**Comment by LautaroL20** [comment]
Ill gonna tunning up some overgrown corridors to give a nice overgrown feeling in the upcoming days.

**Comment by ZombiePwner1** [comment]
This has nothing to do with the corridors.

**Comment by LautaroL20** [comment]
Well, i will also be adding over details to the entrance areas too.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 This is an idea aswell you should make more dirt and broken glass on the entrance since quite a few screens are still clean most of them need to be dirty. Only like 3 or 4 are can be clean.

**Comment by LautaroL20** [comment]
There is not an actuall curved broken glass to implement on elev screens., unless someone edit it on 3d max.

**Comment by ZombiePwner1** [comment]
Look at the departure elevator and look at the screens they have cracked glass on them.

**Comment by LautaroL20** [comment]
Ah, thats a decal texture, i was talking about the mdl.
