### ISSUE TITLE
Angled panels bug

### ISSUE THREAD

**Issue by SPAHI4** [BEEmod/BEE2-items#1091]
I cant go through portal placed on 45' angled panel (with start enabled option)  placed on floor   without noclip.
Panels with 30', 60', and 45' with turned off "start enabled" works ok.
Clean style

**Comment by TeamSpen210** [comment]
Do you have something connected to the panel?

**Comment by SPAHI4** [comment]
No. If something connected all fine.

**Comment by Konclan** [comment]
Angled panels on the floor at 30 and 40 degrees in clean style

**Comment by libbybapa** [comment]
You can come out the portal in the panel but cannot go in it.

**Comment by libbybapa** [comment]
The simple workaround until the bug is patched is to hide a connectable object (e.g. relay) where it cannot be seen or activated, connect it to the panel and set connection visibility to none.

**Comment by LautaroL20** [comment]
@libbybapa - Original Clean actually works the exactly same as the beemod´s clean.

**Comment by ZombiePwner1** [comment]
@LautaroL20 True Also come online. @libbybapa It's most likely to do with an invisible clip that the panel has.

**Comment by Luke18033** [comment]
Should now be fixed.
