### ISSUE TITLE
Typo in some item descriptions

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1098]
- The crusher description says that Crushers appear in Chapter 10 of SP, but there is no chapter 10.
- The overgrown Excursion Funnel description is shown twice in the popup window.

**Comment by Byzarru** [comment]
Crushers appear in Chapter 9 and the Mass and Velocity Co-Op course.

**Comment by Luke18033** [comment]
I know, but it says chapter 10

**Comment by Byzarru** [comment]
That's the correction that should be made.
