### ISSUE TITLE
Portal 1 Gun broken

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1099]
When Use P1 Gun is enabled, the sounds will be changed but not the model.

**Comment by ZombiePwner1** [comment]
Are you using portal 1 style?

**Comment by Luke18033** [comment]
Yes, it wouldn't even change the sound if I wasn't.

**Comment by ZombiePwner1** [comment]
Seems @TeamSpen210 has broken the model files.

**Comment by Luke18033** [comment]
@TeamSpen210 Are you going to fix this?

**Comment by Luke18033** [comment]
Strange thing is, sometimes it's changed while other times it isn't. I'm not sure exactly what causes this.
