### ISSUE TITLE
Add itemvar to moving items to allow setting speed.

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2-items#1100]
A stylevar to make items move at their original speeds. This would be implemented as a stylevar (as opposed to being always on) to prevent breaking maps originally made in other styles.

**Comment by Jadeygaming** [comment]
What do you mean?

**Comment by LautaroL20** [comment]
Lol, what does this means?

**Comment by TeamSpen210** [comment]
I'd assume make piston platforms, track platforms, and panels move slowly instead of matching P2 speeds.. That would be a good idea, although I'd actually want to change speeds on many items.

**Comment by LautaroL20** [comment]
Well, then this option should goes for other styles aswell.

**Comment by Luke18033** [comment]
@LautaroL20 It wouldn't affect Clean though...

**Comment by LautaroL20** [comment]
Why not? Clean also have track platforms, panels etc...

**Comment by TeamSpen210** [comment]
But those are already with the correct speed, since PeTI is Clean by default. Maybe panels might be slightly different, but not much really.

**Comment by Luke18033** [comment]
Actually, what would probably be better is to give moving items an ICP option, to allow setting their speed. That way you have more control over it, and can also configure it to only affect certain items (instead of applying to all moving items).

**Comment by Luke18033** [comment]
I think this was meant to apply to angled panels too, since in P1 they move way slower... I don't really remember though, I'll probably just make a separate issue for that.
