### ISSUE TITLE
Fix Caroline and P1 GLaDOS voice lines

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1101]
P1 GLaDOS and Caroline don't have any lines (nor are they going to in the future), so they should be removed.

**Comment by TeamSpen210** [comment]
There are actually lines for these, but I haven't gotten around to implementing that.

**Comment by ZombiePwner1** [comment]
That's odd with Caroline since I've used her lines before.

**Comment by Luke18033** [comment]
@TeamSpen210 Oh, but I thought you weren't going to because they couldn't be translated.

**Comment by TeamSpen210** [comment]
It's just some P2 GLaDOS lines kinda matching her original dialog.
