### ISSUE TITLE
High Energy Pellet launcher/catcher editor models not modeled on the back

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1109]
![20161201083154_1](https://cloud.githubusercontent.com/assets/19228201/20802436/e33bdcc8-b7a0-11e6-9d69-a142149e70e3.jpg)

**Comment by Luke18033** [comment]
Although I do like how the catcher actually shows the `EmbeddedVoxels` in use. You should implement that for more items.

**Comment by ZombiePwner1** [comment]
It's not modeled on the back since your not supposed to see it's back.

**Comment by Luke18033** [comment]
The editor model, not the in-game model. You can move the camera behind them and it's not modeled.

**Comment by TeamSpen210** [comment]
I believe Rantis/August made these models from those, which is why they're missing backs.

**Comment by ZombiePwner1** [comment]
Also the fizzler editor models aren't styled for P1

**Comment by Luke18033** [comment]
@ZombiePwner1 Does it really matter?
