### ISSUE TITLE
"Clean Portal Gun" stylevar

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1111]
A stylevar to use a cleaner Portal Gun, see [here](http://gamebanana.com/skins/144944).

This is also compatible with co-op.

**Comment by ZombiePwner1** [comment]
That's actually the portal gun i use aside from that mine has a hand on it.

**Comment by Luke18033** [comment]
This stylevar shouldn't be available in Overgrown.

**Comment by ZombiePwner1** [comment]
True.

**Comment by Luke18033** [comment]
I just realized that this is issue #1111.

**Comment by TheDarkBomber** [comment]
Yes. Did you post this issue at 11:11? (#1111 at 11:11)

**Comment by Luke18033** [comment]
@TheDarkBomber No

**Comment by Luke18033** [comment]
Not really necessary, this would probably just be annoying for people who use custom portal guns.
