### ISSUE TITLE
Portal 1 lighting improvements

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1112]
In Portal 1 style, the large observation room emits very little light compared to other styles, and even BEE2.2.

**Comment by ZombiePwner1** [comment]
Use the ceiling light that provides alot of light.

**Comment by Luke18033** [comment]
Ceiling light isn't in BEE2.4

**Comment by ZombiePwner1** [comment]
I mean't square lights.

**Comment by Luke18033** [comment]
Oh, I have those and there still isn't much light.

**Comment by ZombiePwner1** [comment]
Oh now i remember put the observation rooms on the ceiling they make a huge square light that makes loads of light.

**Comment by Luke18033** [comment]
Yes that works, the other items should still create more light though to match their Portal 2 versions.

**Comment by Byzarru** [comment]
I find that Portal 1 lights generate plenty. It's not supposed to match Portal 2, it's supposed to resemble Portal 1.

**Comment by ZombiePwner1** [comment]
@Byzarru The actual portal 1 chambers weren't this dark.

**Comment by LautaroL20** [comment]
This bug was also affecting the P1 square lights, wich is solved now, but i did not test the light strips.

**Comment by Luke18033** [comment]
![20170131174655_1](https://cloud.githubusercontent.com/assets/19228201/22493406/c34001a0-e7e4-11e6-9279-2282b76f157d.jpg)
I mean, seriously, the Large Observation Room should be emitting *way* more light than this.

**Comment by Luke18033** [comment]
Was looking at an old BEE2.2 map. Here's a screenshot from it:
![portal2_HQpJDwNJTJ](https://user-images.githubusercontent.com/19228201/77239538-24376580-6b99-11ea-9b34-719a397a253e.jpg)

Now here's the exact same map, recompiled in 2.4:
![image](https://user-images.githubusercontent.com/19228201/77239532-1c77c100-6b99-11ea-927d-a2efa165b60f.png)

This is definitely an issue for the large obs room.

**Comment by Luke18033** [comment]
Note that the BEE2.4 screenshot is on full lighting mode - in fact the BEE2.2 map may have even been compiled on fast originally, making the issue even worse.

**Comment by ZombiePwner1** [comment]
Oh yeah portal 1 definitely still has issues with it's lighting. Should be matching up with the original portal 1. I've also seen that the coop starting room elevator is quite dark aswell.

**Comment by Luke18033** [comment]
Small observation rooms on walls are also dark.
![image](https://user-images.githubusercontent.com/19228201/77239782-98730880-6b9b-11ea-8b3d-b94f6e68f6b7.png)
Ceiling-mounted rooms emit a reasonable amount of light, but only in the area directly below them (though this is somewhat expected).
![image](https://user-images.githubusercontent.com/19228201/77239804-dd973a80-6b9b-11ea-939d-9ac9765f0a14.png)
Floor-mounted rooms are also fine, though I really doubt the usefulness of this variant in general (since they only really end up lighting the ceiling).
![image](https://user-images.githubusercontent.com/19228201/77239860-6b732580-6b9c-11ea-8b06-8ac63e7c6226.png)
Light holes are also about what you'd expect, though they seem to be emitting pure white light which looks pretty bad. For this style, I'd expect it to be a bit more orange-ish.
![image](https://user-images.githubusercontent.com/19228201/77239894-efc5a880-6b9c-11ea-9b14-1d1b603afa85.png)
I haven't tested square lights. They probably have similar issues.

**Comment by ZombiePwner1** [comment]
@Luke18033 Definitely true.

**Comment by ZombiePwner1** [comment]
![image](https://user-images.githubusercontent.com/18079316/77240007-fe06d980-6c1b-11ea-9842-29c77b286e2f.png)

Barely any light despite there being 2 observation rooms.

**Comment by TeamSpen210** [comment]
Checked the large obs room, it was totally messed up. Fixed.
![image](https://user-images.githubusercontent.com/8453732/77504711-d5494300-6eac-11ea-94df-69091f871991.png)

**Comment by ZombiePwner1** [comment]
@TeamSpen210 What was the issue with it?

**Comment by TeamSpen210** [comment]
The `light_spot` was rotated sideways, pointing at the wall. Additionally instancing breaks those rather badly anyway, so I replaced it with point lights.

**Comment by Luke18033** [comment]
Have you checked small rooms yet, anything wrong with those?

**Comment by TeamSpen210** [comment]
Did the same things to them anyway.
