### ISSUE TITLE
High Energy Pellets deflect off of non-static P1 angled panels in the completely wrong direction

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2-items#1113]
When a High Energy Pellet hits a static panel it's fine, only the non-static panel has this problem.

**Comment by ZombiePwner1** [comment]
Show a picture of it.

**Comment by Luke18033** [comment]
I haven't actually looked at it yet, I just assumed the angle was wrong because pellets weren't deflecting at the right angle. i should probably check the instance in Hammer.

**Comment by Luke18033** [comment]
No, nothing is wrong in the instance, I don't think it's a problem with the instance, but some strange physics bug. I'll have to test this out.

**Comment by ZombiePwner1** [comment]
Test it out then send a screenshot.

**Comment by TeamSpen210** [comment]
Which angle and type?

**Comment by HugoBDesigner** [comment]
I was going to post this issue. For 45° panels, for example, they go at a very off angle (maybe 30° or something like that).
![20170314115033_1](https://cloud.githubusercontent.com/assets/6296061/23907073/ba0b17ba-08ae-11e7-9682-b2ed5f960829.jpg)
In this picture, the pellet hit the panel from the side, so it should have been redirected completely downwards, but instead goes at an angle. This doesn't happen with 45° blocks, only with angled panels.

**Comment by Luke18033** [comment]
Still an issue

**Comment by Luke18033** [comment]
Still an issue. Maybe we should try adding a separate clip at the extended position, which is enabled/disabled without moving?
