### ISSUE TITLE
Disable Force Placement on auto-generated placement helpers

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1114]
Nearly every auto-generated placement helper currently has the "force placement" option enabled, which forces portals to align to the helper no matter what and is generally annoying. This should only be enabled for the Portal Magnet item, and even then should be toggleable with a property. This is currently being done in the geometry branch (by switching everything to use compiler-generated placement helpers with the option off), but some items still contain force placement helpers within their instances, or otherwise don't behave as they should.

Here's a list of every instance in the packages containing a force placement helper. Some of these won't need to be changed, or might not be used anymore.
- [x] catwalk\resources\instances\50s\items\catwalk\end_wall.vmf
- [x] catwalk\resources\instances\50s\items\catwalk\single_wall.vmf
- [x] catwalk\resources\instances\clean\items\catwalk\end_wall.vmf
- [x] catwalk\resources\instances\clean\items\catwalk\single_wall.vmf
- [x] catwalk\resources\instances\over\items\catwalk\end_wall.vmf
- [x] catwalk\resources\instances\over\items\catwalk\single_wall.vmf
- [x] catwalk\resources\instances\p1\items\catwalk\end_wall.vmf
- [x] catwalk\resources\instances\p1\items\catwalk\single_wall.vmf
- [x] panels\resources\instances\50s\items\panel_covered.vmf
- [x] panels\resources\instances\clean\items\panel_covered.vmf
- [x] panels\resources\instances\over\items\covered_pan\panel.vmf
- [x] panels\resources\instances\p1\items\covered_pan\common.vmf
- [x] styles\bts_style\resources\instances\bts\items\faith_plate_target.vmf
- [x] styles\bts_style\resources\instances\bts\items\panel_angled.vmf
- [x] styles\bts_style\resources\instances\bts\static_panel\00_surf.vmf
- [x] styles\bts_style\resources\instances\bts\static_panel\30_surf.vmf
- [x] styles\oldAp\resources\instances\50s\items\faith_plate_target.vmf
- [x] styles\oldAp\resources\instances\50s\items\panel_angled.vmf
- [x] styles\oldAp\resources\instances\70s\static_panel\30_surf.vmf
- [x] styles\oldAp\resources\instances\70s\static_panel\45_surf.vmf
- [x] styles\oldAp\resources\instances\70s\static_panel\60_surf.vmf
- [x] styles\oldAp\resources\instances\70s\static_panel\90_surf.vmf
- [x] styles\oldAp\resources\instances\80s\items\faith_plate_target.vmf
- [x] styles\oldAp\resources\instances\80s\static_panel\90_surf.vmf
- [x] styles\overgrown\resources\instances\over\elevator_coop\exit_corridor_3.vmf
- [x] styles\overgrown\resources\instances\over\items\panel_angled.vmf
- [x] styles\overgrown\resources\instances\over\static_panel\00_surf.vmf
- [x] styles\overgrown\resources\instances\over\static_panel\30_surf.vmf
- [x] styles\overgrown\resources\instances\over\static_panel\45_surf.vmf
- [x] styles\p1_style\resources\instances\p1\items\angled_pan\common.vmf
- [x] styles\p1_style\resources\instances\p1\items\pist_plat\pist_dynamic_brush.vmf
- [x] styles\p1_style\resources\instances\p1\items\pist_plat\static_0_brush.vmf
- [x] styles\p1_style\resources\instances\p1\items\pist_plat\static_top_brush.vmf
- [x] tspen\ditch\resources\instances\clean\items\tspen\flat_grate_black.vmf
- [x] tspen\ditch\resources\instances\clean\items\tspen\flat_grate_white.vmf
- [x] valve\clean_style\resources\instances\clean\elevator_coop\door_exit_4.vmf
- [x] valve\geometry\resources\instances\clean\items\pist_plat\pist_dynamic_brush.vmf
- [x] valve\geometry\resources\instances\clean\items\pist_plat\static_0_brush.vmf
- [x] valve\geometry\resources\instances\clean\items\pist_plat\static_top_brush.vmf
- [x] valve\geometry\resources\instances\clean\static_panel\45_surf.vmf
- [x] valve\test_elements\resources\instances\clean\items\faith_plate_target.vmf
- [x] wom_plates\resources\instances\clean\items\cond_plate\plate_helper.vmf

<details>
<summary>Original suggestion</summary>
Remove automatic placement helpers entirely, and allow the mapper to choose which items have them with the Portal Magnet item.
</details>

**Comment by Flametusk** [comment]
Except the portal magnet takes up an extra palette slot, so it seems a waste just to have it for something that is already default if that's all it's used for, right? (Thinking of light bridges, faith plates, funnels, and lasers)

**Comment by Luke18033** [comment]
It should be added as a stylevar

**Comment by Byzarru** [comment]
Which items use a placement helper?

**Comment by TeamSpen210** [comment]
Of the top of my head:

* Angled Panels
* Gel Droppers
* Flip Panels
* Diversity Vents (this must be here though)
* Faith Plate Targets
* Autoportals (from the shape of the frame)

Diversity Vents and angled panels would keep theirs - vents break if you put your portal off-center, and the panel one needs to move to match the position of the surface.

**Comment by Byzarru** [comment]
I've never noticed any portal magnets before save for angled panels.

**Comment by Luke18033** [comment]
For angled panels, couldn't the compiler just parent the `info_placement_helper` to the angled panel? For lasers, funnels, and bridges, there's an option on the entities to create a placement helper automatically. Just turn that off.

**Comment by Luke18033** [comment]
This doesn't need to be a stylevar, just removing them is fine.

**Comment by Luke18033** [comment]
I've been thinking about this more - automatic placement helpers shouldn't be removed, they're actually quite useful for aligning portals. What should be changed is the Force Placement keyvalue - it's currently enabled for all of the auto placement helpers. Placement helpers are meant to help with portal alignment (as the name implies), not force portals to a specific location no matter what. Force Placement does have its uses, but it shouldn't be necessary for things like angled panels, or even the placement helper item, at least not without an option to disable it.

**Comment by TeamSpen210** [comment]
Indeed, I misunderstood that when originally making the item. I think I'd turn it on for explicit helpers only.

**Comment by Luke18033** [comment]
Why can't diversity vents have force placement disabled, how do they break?

**Comment by TeamSpen210** [comment]
Note that the idea of the compiler support now present is intended to allow the implicit helper to be removed/disregarded if a Force Placement helper is also present.

For diversity vents, the problem is that the portal code just duplicates the point_push across the portal directly. If the portal isn't centered underneath it, it gets spawned with the same offset leading to objects getting sucked to some point next to the portal, which looks stupid. Thinking about it, maybe some VScript could be used to move this around or otherwise fix the problem. (This is also what causes the loud misplaced sound from funnels.)

**Comment by Luke18033** [comment]
Yeah, here's how I imagine it should/does work:
- Items such as angled panels will generate a non-forced placement helper automatically.
- The Portal Magnet item can also be used to put non-forced placement helpers in arbitrary locations.
- By enabling a specific property on the Portal Magnet item, forced placement would be enabled. This would override (and remove) any non-forced placement helpers already present in other items on the tile.

As for diversity vents, it's already possible to place portals on walls or other places near the vent that aren't affected by the helper so I'm not sure how useful it is. It'd probably be better to do what you mentioned, and try to fix the problem with VScript.

**Comment by Luke18033** [comment]
I don't see anything in the `addPlacementHelper` condition that would set whether or not it's a forced helper, is it a hardcoded exception for the Portal Magnet item or something?

**Comment by TeamSpen210** [comment]
Yeah, currently it's coded that force placement = snap to angles.

**Comment by Luke18033** [comment]
Ah, so specifying an `upDir` in the result is what enables force placement?
```
"addPlacementHelper"
	{
	"offset" "16 0 0"
	"upDir"  "0 1 0"
	}
```

**Comment by TeamSpen210** [comment]
Yep, obviously I need to separate this.

**Comment by Luke18033** [comment]
Also should implement support for offset helpers.
