### ISSUE TITLE
New Item: Laser Firing Cube

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#1119]
New Item: Laser Firing Cube

A Laser cube that fires a always on laser out of it at all times. could be used to create some interesting laser puzzles.

here is my idea, use the laser cube model and attach a push button on the top to toggle the laser on and off and design a template from the whole thing to give it a cube dropper.

**Comment by Luke18033** [comment]
The Blue Portals mod for Portal 1 had something like this.

**Comment by Konclan** [comment]
UCP
