### ISSUE TITLE
Allow setting Funnel speed via ICP

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1120]
New Item: Fast excursion Funnel

a fast excursion funnel to reduce wait times in very large maps with excursion funnels that may be very long.

**Comment by Luke18033** [comment]
I think Excursion Funnels have an option to increase the speed, I see it in a lot of maps.

**Comment by Luke18033** [comment]
This should probably just be a timer or something, not a separate item.

**Comment by TeamSpen210** [comment]
Unfortunately you can't set this on multiple funnels - the speed functions correctly, but all the visual effects on screen use the same speed (swapping as funnels move in and out of the screen). I'll make the setting apply to the whole map.

**Comment by ZombiePwner1** [comment]
This can be added aslong as you don't make the funnel too fast.

**Comment by Endermage77** [comment]
Who doesn't want to funnel at 200 mph?

**Comment by HugoBDesigner** [comment]
Actually, I second the idea of changing the speed of the funnel like you do for pellets, but in such a way that it doesn't go ridiculously slow or fast, but just within an acceptable range.
Also, I feel like Zero Gravity funnels should be their own thing, but that could cause issues/conflicts with other funnels

**Comment by Endermage77** [comment]
Maybe the Zero-G funnel could be an alternative deactivation mode to simply turning off the funnel, and as a new item?

**Comment by HugoBDesigner** [comment]
The issue is in the rendering: if you have a Zero Funnel and a regular funnel on the same map, the funnel animation gets wonky

**Comment by TeamSpen210** [comment]
It's any funnel with different speeds, if they're visible at the same time. Valve probably did some shortcuts in the shaders, probably global vars for the set speed instead of properly passing it through.

**Comment by LautaroL20** [comment]
Yay, this will be implemented in next pre-release.
