### ISSUE TITLE
I have a few items to add to your bee2-items after bug fixing them

### ISSUE THREAD

**Issue by mario2582** [BEEmod/BEE2-items#1126]
@TeamSpen210 or @BenVlodgi, or whoever is admin, i wish to Request to become bee2-items Collaborator 

i have a few items to add to your bee2-items after bug fixing them which are below, checkmarked ones are nearly ready...

- [x] pink Liquid Coloring Excision Field to replace current paint fizzler...
- [x] A Force Field that blocks everything
- [ ] Paint Fields (Opposite of a Paint fizzler)
- [ ] Physics Field that becomes solid to players when a cube comes close enough to touch it
- [x] a open variant to the BTS bottomless pit
- [x] Early solid wall P1 Bottomless pit
- [x] a early Open P1 bottomless pit
- [x] early open clean style bottomless pit (just wall sections and v pillars)
- [ ] early open overgrown style bottomless pit (just wall sections and v pillars)
- [x] corrections to bts wall textures to make them match pit walls

**Comment by LautaroL20** [comment]
Just make a "Pull Request".

**Comment by Jadeygaming** [comment]
Yeah Make "Pull Request"

**Comment by Luke18033** [comment]
@ellingtonvengaboysmuseum Physics Field and Force Field are already being developed and pull-requested by @TheDarkBomber. His versions are known as the Physics Repulsion Field and the Closed Solid Field.

**Comment by Luke18033** [comment]
@TheDarkBomber is already developing the Force Field (as the Closed Solid Field) and the Physics Field (as the Physics Repulsion Field). What would the paint field do, generate paint?
