### ISSUE TITLE
1970's style a mysterious floating clock is on the light bridge.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1129]
![20161203090031_1](https://cloud.githubusercontent.com/assets/18079316/20855310/0037379a-b937-11e6-8b69-8366de77afe6.jpg)

**Comment by LautaroL20** [comment]
LOL!

**Comment by Jadeygaming** [comment]
What?

**Comment by MrKrunk** [comment]
There needs to be a name for the clock.
So far, this is the best bug that's ever happened.

**Comment by TheDarkBomber** [comment]
That's not a clock. That's a speedometer.

**Comment by TeamSpen210** [comment]
This should be moved towards the bridge, so it's on the side. It'd leak if placed there, so it needs to be moved after the map starts (which is what's not working).
