### ISSUE TITLE
Show WIP Items Option Does Nothing

### ISSUE THREAD

**Issue by TheReviewers** [BEEmod/BEE2-items#1134]
...

**Comment by LautaroL20** [comment]
It doesn´t and never will, unless you are using the DEV Version. The public pre-releases only contains the finished items.

**Comment by ZombiePwner1** [comment]
@LautaroL20 It should show WIP items in the real releases.

**Comment by TheReviewers** [comment]
@LautaroL20 And where to find the DEV Version?

**Comment by Jadeygaming** [comment]
@TheReviewers Only DEVs can have it.

**Comment by Byzarru** [comment]
https://github.com/TeamSpen210/BEE2-items/tree/dev

**Comment by TeamSpen210** [comment]
Actually it works perfectly, except that I never actually add items marked as WIP. I'll probably be removing it entirely.

**Comment by LautaroL20** [comment]
@Jadeygaming - Well, actually i have the DEV Version, although i am not the owner of beemod. You have to download Github for windows, then clone the repro, then build the Python executalbe (this is kinda complicated). I needed the help of TeamSpen210 in order to get this version.

**Comment by TheReviewers** [comment]
@TeamSpen210  That's a shame...
