### ISSUE TITLE
Fan

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1137]
New item suggestion!

This is the antithesis of the Pneumatic Diversity Vent. The Fan (Aperture Science Air Circulator and Repulsion Device) blows objects and players away from it. 

The fan as a testing element is used in this map: [Ventura 3 by Skyferret](http://steamcommunity.com/sharedfiles/filedetails/?id=683881532).

This video from Blue Portals also exemplifies it pretty well: [Blue Portals: Turret Update](https://www.youtube.com/watch?v=Fsg4_Nw_7pQ)

**Comment by Jadeygaming** [comment]
Nice Idea (This Also Shows Up In Batcature Labs by Batcat).

**Comment by ellingtonvengaboysmuseum** [comment]
you could make three versions of this

- fan that is for aesthetic looks and doesn't blow things around
- high powered fan that blows stuff away from it
- giant fan as seen in the underground coop course

**Comment by Endermage77** [comment]
Would this item be reversible?

**Comment by Byzarru** [comment]
~No, then it'd act as a Pneumatic Diversity Vent. ~ That idea sucks, but it might be interesting to see items get pulled in without getting destroyed.

**Comment by Endermage77** [comment]
The thing about vents though, is that they are generally designed to go somewhere, and if they don't, it is generally rather difficult to retrieve items from them.
You also can't turn off a vent. Or reverse it.

**Comment by Byzarru** [comment]
True. My objection to this is that it would be a little difficult to distinguish the function of the fan (whether or not it was repulsing) while in ALL THE MAPS it is used to push things away. You could conceivably set up a PDV with grating in front of it to keep it from destroying items (and TeamSpen make this switchable), and that would relegate the functions to those two different items.

**Comment by Endermage77** [comment]
I suppose that is a valid argument.

Still, there's no time like the present to start training our testing community to learn the ways of the reversible fan.
If you like.

**Comment by Byzarru** [comment]
That would probably be the only distinguishing mark.

**Comment by Endermage77** [comment]
And possibly some lights and having the fan spin the other way 'round.

**Comment by Konclan** [comment]
#3884
