### ISSUE TITLE
Glass Panel's glass isn´t being displayed - Add command "$mostlyopaque" in the QC to fix it

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1138]
![20161205033813_1](https://cloud.githubusercontent.com/assets/12244376/20875862/cbc8ad10-ba9c-11e6-8bf3-baed740b7a7a.jpg)

**Comment by Konclan** [comment]
I don't get it

**Comment by ZombiePwner1** [comment]
The glass on the panel in the in-game screenshot is generating inside the panel when it's supposed to generate on the front of the panel.

**Comment by LautaroL20** [comment]
TeamSpen210 Said hes planning on making a Glass Panel Model version that do not have the glass transparency bug. Here is the suggestion for this: https://github.com/TeamSpen210/BEE2-items/issues/993

**Comment by ZombiePwner1** [comment]
Alright

**Comment by LautaroL20** [comment]
Not sure if this also happens with the Overgrown Glass panel though...

**Comment by ZombiePwner1** [comment]
It doesn't the overgrown glass panel is completely fine.

**Comment by LautaroL20** [comment]
![20161205033813_1](https://cloud.githubusercontent.com/assets/12244376/20875872/e1c42982-ba9c-11e6-83b0-609d91269a5a.jpg)

**Comment by ZombiePwner1** [comment]
I was using original clean your using the regular clean style.

**Comment by LautaroL20** [comment]
That doesn´t have anything to do. Both versions of Clean Style despite the textures, they´re almost the same thing, using the exactly same data. And btw, i was using original clean u wheely, looks like you need a pair of glasses...

**Comment by Luke18033** [comment]
This is fixed now, isn't it?

**Comment by LautaroL20** [comment]
Yes, now people who downloads PRL27 will be able to enjoy from this ehnancement. By the way, this post seems to be a duplicate from one of mine....
