### ISSUE TITLE
Sometimes glass panels and piston platforms have weird opaque glass that doesn't block the panel itself and is perfectly visible through other glass 

### ISSUE THREAD

**Issue by Flametusk** [BEEmod/BEE2-items#1141]
Pretty much as the title suggests, sometimes the glass is opaque and the entire panel is completely visible through regular glass.

**Comment by Luke18033** [comment]
This is a Valve bug, but a custom model could fix it.

**Comment by LautaroL20** [comment]
Well, as for the Glass Panel, TeamSpen210 only have to add the command "$mostlyopaque" in the QC file of the model to fix it. He already did thit with the Square Lights. For more details, see: https://github.com/TeamSpen210/BEE2-items/issues/864

**Comment by LautaroL20** [comment]
Ive fixed this issue since a year ago already on all glass panels.
