### ISSUE TITLE
Add Start Enabled to 1/4 Wall to make it go on the inner 4 positions

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#1146]
I find the 1/4 wall very useful and think that it could be even more useful if its position adjustment allowed all 8 positions of a strip light rather than just the 4 of the perimeter.  I don't know if that is possible, but if so, it sure would be useful.

**Comment by Flametusk** [comment]
Yes, this. This is a good idea.

**Comment by Byzarru** [comment]
This would be useful for a variety of items, like pedestal buttons and signs.

**Comment by LautaroL20** [comment]
Unfortunately, the feature `HANDLE_8_POSITIONS` does not work with barrier type. If you test this by yourself, youll found that the barrier model goes totally crazy into the editor, and thats why this wasn´t implement before.

**Comment by libbybapa** [comment]
Wait a second before closing this out...  Ok, so the 'handle 8 positions' doesn't work with barriers.  How about using something like start reversed so that the 1/4 wall  appears in the middle 4 positions?  You could still use the 4 position gizmo.

**Comment by Flametusk** [comment]
That sounds like it would work.

**Comment by LautaroL20** [comment]
The "Start Reserved" option on this item is already taken by the feature that makes it to be portalable.

**Comment by libbybapa** [comment]
How about 'start enabled' then?

**Comment by libbybapa** [comment]
I felt valid for a second there...

**Comment by TheDarkBomber** [comment]
That will work.

**Comment by Luke18033** [comment]
Yeah, `HANDLE_8_POSITIONS` doesn't work with glass. This happened:
![20161206085556_1](https://cloud.githubusercontent.com/assets/19228201/20934987/e8f65662-bb91-11e6-9860-ef49f2370754.jpg)

**Comment by TheDarkBomber** [comment]
@Luke18033 What did you do to the glass?

**Comment by Luke18033** [comment]
I added `HANDLE_8_POSITIONS`, and when you move it to the inner positions that happens.

**Comment by TheDarkBomber** [comment]
You get diagonal glass? Does it work?

**Comment by Luke18033** [comment]
I don't know. I'll test

**Comment by Luke18033** [comment]
In-game this happened:
![20161206090221_1](https://cloud.githubusercontent.com/assets/19228201/20935260/cf889ea0-bb92-11e6-9e14-ce68ba25ac60.jpg)

**Comment by TheDarkBomber** [comment]
That's interesting. What happens if you put `HANDLE_8_POSITIONS` onto other items, like fizzlers?

**Comment by Luke18033** [comment]
@TheDarkBomber I don't want to spam this issue. I'll put the images on MessAround

**Comment by Byzarru** [comment]
Would it work on [signs](https://github.com/TeamSpen210/BEE2-items/issues/1093) and pedestal buttons?

**Comment by ZombiePwner1** [comment]
The pedestal buttons i want the handle_8_positions on.

**Comment by Jadeygaming** [comment]
@Luke18033  What Is MessAround?

**Comment by Luke18033** [comment]
@Byzarru It should work with pedestal buttons. Signage already has it. I've only once gotten glass to rotate diagonally without `HANDLE_8_DIRECTIONS`.

@Jadeygaming [MessAround](https://gitter.im/TheDarkBomber/MessAround) is @TheDarkBomber's Gitter chat room

**Comment by Byzarru** [comment]
Signage uses the four-way rotation, unless you're talking about a dev version I'm not using.

**Comment by Luke18033** [comment]
@Byzarru Oh yeah right, it doesn't have `HANDLE_8_DIRECTIONS`. I'll try adding it.

**Comment by Byzarru** [comment]
@Luke18033 Could you make a mention on #1093 when you do and if it works?
