### ISSUE TITLE
Rocket turrets trip wire is mysteriously facing backwards.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1147]
![20161206201336_1](https://cloud.githubusercontent.com/assets/18079316/20925247/c1d100b4-bbf0-11e6-86f3-b111b2d1bb2e.jpg)

And it's still not styled.

**Comment by Luke18033** [comment]
Lol

**Comment by Jadeygaming** [comment]
Rocket Tripwire?

**Comment by Luke18033** [comment]
@Jadeygaming He means the laser on the rocket turret.

**Comment by ZombiePwner1** [comment]
@Jadeygaming You don't know what the rocket trip wire is for?

**Comment by Jadeygaming** [comment]
There Were Rocket Tripwires In The Old BEE 2 That Just Faced 1 Direction.

**Comment by Luke18033** [comment]
Shouldn't be an issue anymore.
