### ISSUE TITLE
Dissasemble machines are having a "Small Visible Nodraw"

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1148]
![69a5b190-bbf1-11e6-9c03-3bc74ec2505c](https://cloud.githubusercontent.com/assets/12244376/20926371/c52b4982-bb9a-11e6-85f6-b8830a744433.jpg)

![6ea0ed86-bbf1-11e6-9e89-1b384a9bb325](https://cloud.githubusercontent.com/assets/12244376/20926404/e717c9d0-bb9a-11e6-88c8-9cbe1d55d123.jpg)

Notice how in the screenshots there is a little area that looks abit wrong.

**Comment by LautaroL20** [comment]
That was hard to see! But i highlighted the areas for those who can´t see it:


![69a5b190-bbf1-11e6-9c03-3bc74ec2505c](https://cloud.githubusercontent.com/assets/12244376/20926371/c52b4982-bb9a-11e6-85f6-b8830a744433.jpg)
