### ISSUE TITLE
More nodraw inside the coop disassemble rooms.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1149]
![20161206202252_1](https://cloud.githubusercontent.com/assets/18079316/20925413/d2fe3464-bbf1-11e6-9108-3c8f22d888fe.jpg)

![20161206202434_1](https://cloud.githubusercontent.com/assets/18079316/20925456/06d86c3c-bbf2-11e6-89c6-26afe8f2c254.jpg)

Little white area in the screenshots. Happens on the otherwise aswell. The disassemble rooms needs maintenance work. Also i guess you can call me the 3rd great bee2 bug finder.

**Comment by LautaroL20** [comment]
I fixed this while i was changing the triple wallpipes skin to rusted. So this is fixed for next release.

**Comment by TheDarkBomber** [comment]
We are not going to add a 3rd great BEE2 bug finder. We already have the 2nd and 1st.

**Comment by ZombiePwner1** [comment]
@TheDarkBomber You will add it okay? i'm quite good at finding bugs myself so.
