### ISSUE TITLE
Overgrown Catwalk: "hanging_stair_64.mdl" is missing its Rusty Visuals

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1151]
Its the only catwalk left to styling:

![26f4cde6-ad77-11e6-8956-48d9a32427e2](https://cloud.githubusercontent.com/assets/12244376/20936518/a5af4ca8-bbc1-11e6-987b-76b03c1e422f.jpg)

**Comment by ZombiePwner1** [comment]
Use the underground catwalk model as a place holder for now.

**Comment by Luke18033** [comment]
@LautaroL20 Why do you always put things in quotes which don't need to?
