### ISSUE TITLE
Add HANDLE_8_POSITIONS to Square Lights

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1156]
I previously suggested adding `HANDLE_5_POSITIONS`, but that is not possible.

The actual positioning would end up working like `HANDLE_5_POSITIONS`, allowing placement in the center of the block and offset in 4 directions.

**Comment by TeamSpen210** [comment]
This can't be done, unfortunately.

**Comment by Luke18033** [comment]
Why?

**Comment by TeamSpen210** [comment]
The 5-direction handle is hardcoded to only work with the laser items due to how it works internally.

**Comment by Flametusk** [comment]
Well then, couldn't you use the 8-direction one instead? And have the 4 idle ones to be the middle?

**Comment by Luke18033** [comment]
@TeamSpen210 Is it because it needs a separate model? If so, that should be quite easy to do.

**Comment by TeamSpen210** [comment]
No, the laser items are actually two of them (`ITEM_LASER_EMITTER_CENTER` / `ITEM_LASER_EMITTER_OFFSET`). When you move the item it swaps to the other item, which only works for the actual Valve items the way it's coded. (knowing the link for those three items).

**Comment by Luke18033** [comment]
How about use `HANDLE_6_POSITIONS`?

**Comment by TeamSpen210** [comment]
The other problem is that it won't have correct collisions - so antlines will probably go through it, and you could place other items on top of it.

**Comment by Luke18033** [comment]
I don't really care that you could put stuff on top of it, I actually would like that better. The antlines might be a problem though.

**Comment by Luke18033** [comment]
@LautaroL20 You realize I was suggesting an 8-way handle, not a 4-way one, right? I don't think this is a very good idea anyway though.

**Comment by LautaroL20** [comment]
Yep, specially since some items goes nuts with the 8-positions. (Ex Glass item).

**Comment by Luke18033** [comment]
This would actually work fine with an 8-way handle, there are just a few other problems that would get in the way - for example if offset towards a ledge, the textures would conflict on the side.
