### ISSUE TITLE
Non Voxel Embedded Square Light

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1159]
a version of the square light that is not embedded in the voxel. a sample image below of a light array that could be used for this in a underground / bts combo test is included...

![ab178cbc-bbcd-11e6-9d41-00f8881861a1](https://cloud.githubusercontent.com/assets/11165643/20971495/9ef39628-bc5f-11e6-840a-a84174630cc4.jpg)

**Comment by Luke18033** [comment]
This would probably be a "non-embedded" alternate version like the floor button has.

**Comment by Byzarru** [comment]
For the square light? The square light doesn't look like this in BTS or Old Aperture.
For the Observation Room? The observation room has two models, and mapmakers will want some kind of design consistency.
As its own item? Yes, let's add every light there is to the party.

**Comment by TeamSpen210** [comment]
Square lights have to be embedded, or otherwise be in the wall.
