### ISSUE TITLE
Voluntary Contribution: Some New Styles

### ISSUE THREAD

**Issue by Electricianfromhell** [BEEmod/BEE2-items#1163]
i intend to create some New Styles using underground and bts resources as template as a voluntary contribution. i will be adding pull requests for the list of following styles below when complete, Most of these will be BTS.

- [ ] Wheatley BTS (the bts with the modern yellow and grey metal wall textures and a open bottomless pit)
- [x] Rework current BTS so bottomless pits match.
- [ ] Underground / BTS combintation (uses underground bts cement textures, 80's tile floor textures on ceilings, underground light arrays etc.)
- [ ] Overgrown BTS (Combination of BTS and overgrown, still thinking on how to do this, any suggestions?)
- [ ] Portal 1 Underground Combo

**Comment by Luke18033** [comment]
I don't think P1 Underground is going to be implemented.

**Comment by Luke18033** [comment]
Doesn't look like this really went anywhere.
