### ISSUE TITLE
Connected Aerial Faith Plates renders as a leak

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1166]
This map was made by me in PR23 and played by someone else, and a connected AFP appears as a leak while the others render just fine. I currently have AFPs set as "mechanical plates" in clean.
https://www.youtube.com/watch?v=ayYVima77V4

**Comment by ZombiePwner1** [comment]
Not sure would could be causing the faithplates to become leaks.

**Comment by TheDarkBomber** [comment]
Because Mechanical Plates aren't meant to be used in Clean Style, therefore the bug would occur.

**Comment by TeamSpen210** [comment]
Nope, In everything other than Old Aperture, they're identical. Actually I've fixed it so they won't appear in those styles.

**Comment by Luke18033** [comment]
Don't think this is an issue anymore.
