### ISSUE TITLE
Sound Emitter

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1169]
I would like to suggest a Local Sound Emitter and a Global Sound Emitter which plays a sound once when an input is made. This, paired with triggers and a proposed counter (#1085) could bring some maps to life.

A possible listing of sounds:
1. True
2. False
3. Door Buzzer
4. Klaxon
5. Override Button 
6. Personality Core
7. Rumble
8. Explosion
9. Aperture Jingle 
10. Investment Opportunity
11. An Accent Beyond
12. The Part Where He Kills You

**Comment by Byzarru** [comment]
The predefined list would be:
1. door_open_chime_01 / og_test_chamber_oos_01
2. hackbuzzer.wav / og_test_chamber_neg_01.wav
3. button_synth_negative.wav
4. alarm_sweep_lg_01.wav 
5. amb_container_alarm_01.wav
6. sphere_rail_start_01.wav
7. terrain_rumble1.wav
8. explode_1.wav
9. aperture_logo_bells_01_01.wav
10. sp_a3_03_b3.wav
11. sp_a2_bts1_x1.wav
12. sp_a4_finale1_b1p3.wav

Or the ICP can be used to assign individual sounds, which would probably be more beneficial.

**Comment by Konclan** [comment]
Better left to a UCP
