### ISSUE TITLE
BTS has no observation room ceiling variant

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1170]
![image](https://cloud.githubusercontent.com/assets/22107242/21078406/6af3cd9e-bf33-11e6-99a3-dc14f08bef24.png)

**Comment by LautaroL20** [comment]
This style is pretty much in WIP Stage yet. Many of the corridors are leaked.

**Comment by Byzarru** [comment]
> Many of the corridors are leaked.

All but Entry 1 and Exit 1

**Comment by GiovanH** [comment]
This is no longer the case.

**Comment by GiovanH** [comment]
This is no longer the case.

**Comment by LautaroL20** [comment]
> This is no longer the case.

Did u do a pull request for this?

**Comment by Luke18033** [comment]
Definitely not fixed, the item still has `InvalidSurface` set. Though the current variant should work fine on floors and ceilings without any modifications.

**Comment by GiovanH** [comment]
My mistake, I compiled a map that already had a floor obs room and saw the instance worked, but I missed that the editoritems wasn't set properly.
