### ISSUE TITLE
Clean Faith plate automatic portal magnets are backwards.

### ISSUE THREAD

**Issue by Flametusk** [BEEmod/BEE2-items#1171]
I created a test where the faith plates are used, and you need to portal through the floor where you land. Without the portal magnet that I put down, the automatic portal magnet faces away from the faith plate, making it so that the player and the gel bombs don't get high enough to solve the test.

**Comment by Byzarru** [comment]
I have a similar problem with my latest map. The AFP magnet is apparently perpendicular to the portal magnet I placed, and portals will prefer the AFP target the first time and my magnet afterwards.

**Comment by Luke18033** [comment]
The fact that it is backwards for one person but sideways for another means that this is likely a problem with rotating it, and not a problem with the instance.

**Comment by Flametusk** [comment]
I'm talking about without the portal magnet, or if you have a deactivated panel with no connections.
