### ISSUE TITLE
Bombs for throwing at you.

### ISSUE THREAD

**Issue by Flametusk** [BEEmod/BEE2-items#1173]
I think it would be nice to have both the music (Bombs For Throwing at You) and the bombs themselves, which would be able to destroy gel tubes, which would also be a new item. Maybe, if wheatley and the cores are implemented, they could also be used for custom boss fights without hammer.

**Comment by Byzarru** [comment]
Not to mention the exploding variants of Futbols.

**Comment by Luke18033** [comment]
@Flametusk I don't think the boss battle part would be implemented. Everything else probably would, but the gel tube would probably just be part of vactubes in some way.

**Comment by TeamSpen210** [comment]
Bomb Droppers will be implemented, which will fit well with Breakable Glass. Destroyable tubes may be doable, it's somewhat difficult though (we can't do it the same way Valve does, since they need to work properly in all situations and interact with lots of other items).

**Comment by ZombiePwner1** [comment]
The bomb models are actually using futbol models.

**Comment by TeamSpen210** [comment]
No they're not.

**Comment by Luke18033** [comment]
![image](https://cloud.githubusercontent.com/assets/19228201/21122255/e8618f5c-c085-11e6-9d9c-2b858d1ea5ed.png)
This is the model which I think is used by the bombs. But it's name implies that it would be used for the Anger Core, which never appears in Portal 2.

**Comment by Luke18033** [comment]
I don't know if I should post this here, but I also found this with the rest of the PeTI movement handle models:
![image](https://cloud.githubusercontent.com/assets/19228201/21122517/65619032-c087-11e6-882e-03573a39516e.png)
I can't think of any items that have this or properties which would add this to items. It also seems to have the same function as `HANDLE_4_DIRECTIONS`.

**Comment by TeamSpen210** [comment]
It's probably an earlier version of the handle design, or something like that.

**Comment by ReikaKalseki** [comment]
Did these get implemented? I have been searching for them but cannot find them in the [menu](http://i.imgur.com/nH3Lo2s.png). Yet [this page](http://steamcommunity.com/sharedfiles/filedetails/?id=125711076) implies they were.

**Comment by TeamSpen210** [comment]
It was in the earlier version of the mod, we basically changed how the items are stored entirely so items need to be ported over.

**Comment by ReikaKalseki** [comment]
OK; while I am here, how feasible would "FX" blocks (hooked up to triggers or other inputs) (eg particles, sounds, etc) be? For example, making landing from a faith plate (secret trigger at target) cause the camera to shake or "collapse" noises, or a button trigger a wall panel to explode (exposing something)?

**Comment by TeamSpen210** [comment]
Those are all doable, but it would really be better to do that sort of thing in Hammer - there you have full control and can set up everything exactly how you want.

**Comment by ReikaKalseki** [comment]
There is a reason I am using BEEMod instead of Hammer....

**Comment by Byzarru** [comment]
@ReikaKalseki See #1169.

**Comment by Luke18033** [comment]
Bombs and breakable vactubes are already mentioned in other issues, and Bombs For Throwing At You doesn't really make sense to have playing in a test chamber. Seems like these were suggested with the intent of recreating the Wheatley boss fight...
