### ISSUE TITLE
add panel

### ISSUE THREAD

**Issue by ILIA-NENASHEV** [BEEmod/BEE2-items#1174]
![91d1c050-bfe3-11e6-931e-afa6b19cd47a](https://cloud.githubusercontent.com/assets/24510029/21083161/7b745422-bffb-11e6-9d58-3513a0207ab8.jpg)
![91d1f9f8-bfe3-11e6-827a-dfa3df0ea916](https://cloud.githubusercontent.com/assets/24510029/21083164/7b760d44-bffb-11e6-867e-9f7d9db28b83.jpg)
![91d2b820-bfe3-11e6-9bc2-fee444683b89](https://cloud.githubusercontent.com/assets/24510029/21083162/7b75e274-bffb-11e6-9f22-e299307400fe.jpg)
![91d27bda-bfe3-11e6-8531-fd865fac3ea0](https://cloud.githubusercontent.com/assets/24510029/21083163/7b75dfc2-bffb-11e6-95ee-a3d3ade5a808.jpg)

**Comment by Luke18033** [comment]
I don't think this would work very well. Also @ILIA-NENASHEV please post more than just screenshots.

**Comment by TeamSpen210** [comment]
Please be more specific with the kind of panel you want, and keep in mind they need to be feasibly done in Old Aperture, not just Modern Aperture.

**Comment by Luke18033** [comment]
For Old Aperture, maybe a wooden panel attached to ropes or something, I don't know.

**Comment by ILIA-NENASHEV** [comment]
TeamSpen210 you can add this element

**Comment by ZombiePwner1** [comment]
@ILIA-NENASHEV Do. It close a issue unless it's a valve bug or invalid.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Even "Valve Bugs" sometimes are fixeable.
