### ISSUE TITLE
Reconstruction Panels

### ISSUE THREAD

**Issue by ILIA-NENASHEV** [BEEmod/BEE2-items#1175]
![91d159d0-bfe3-11e6-8348-31a2f320ad0a](https://cloud.githubusercontent.com/assets/24510029/21083174/d122ad92-bffb-11e6-9a60-c480379e352b.jpg)
![portal2 2012-01-29 01-27-53-44](https://cloud.githubusercontent.com/assets/24510029/21083179/dd31e77e-bffb-11e6-8977-64613145365c.jpg)

**Comment by Luke18033** [comment]
What's this even supposed to be? And what's the second screenshot from, is it the beta?

**Comment by Jadeygaming** [comment]
What does rekonstrukcija paneli mean?

**Comment by LautaroL20** [comment]
Thats how is called in Croatian language.

**Comment by ILIA-NENASHEV** [comment]
TeamSpen210 вы можете добавить этот элемент

**Comment by FantomekYT** [comment]
Lautaro thats Polish and it means Reconstruction panels

**Comment by LautaroL20** [comment]
Nope, it is Croatian: 

![img](https://cloud.githubusercontent.com/assets/12244376/21203234/5e01beca-c230-11e6-9a2d-d902fe88ece4.png)

**Comment by I-love-bee-2** [comment]
@LautaroL20 я Русский

**Comment by Luke18033** [comment]
These would be auto decorations probably
