### ISSUE TITLE
GEL IN the Pneumatic Diversity Vent

### ISSUE THREAD

**Issue by ILIA-NENASHEV** [BEEmod/BEE2-items#1177]
![default](https://cloud.githubusercontent.com/assets/24510029/21083482/a4a6ac3a-c002-11e6-8b2a-08d55a8f7bc9.PNG)

**Comment by Luke18033** [comment]
What?

**Comment by Byzarru** [comment]
Gels currently don't work in diversity vents.

**Comment by TeamSpen210** [comment]
It's not possible to impement gels in that fashion, where you can suck up gel and deposit it elsewhere. It is possible (and I probably will) to have a tube functioning as effectively an extension of a gel dropper (only spawning that particular gel).

**Comment by ILIA-NENASHEV** [comment]
TeamSpen210 вы можете добавить этот элемент

**Comment by ZombiePwner1** [comment]
@ILIA-NENASHEV Next time when you make a issue please provide a description other than screenshots please :)

**Comment by Luke18033** [comment]
Duplicate of #662.
