### ISSUE TITLE
Add more items in the Bottomless Pit skybox

### ISSUE THREAD

**Issue by ILIA-NENASHEV** [BEEmod/BEE2-items#1180]
you can not add more elements into the abyss. like 8 Glowe
![default](https://cloud.githubusercontent.com/assets/24510029/21095361/0f317170-c06c-11e6-8de4-f57a7da140a9.PNG)

**Comment by Luke18033** [comment]
8 glow? What? And why is the screenshot so blurred?

**Comment by TheDarkBomber** [comment]
@Luke18033 This is a suggestion to improve the look of the bottomless pits.

**Comment by Konclan** [comment]
This issue is too generic and doesn't really provide any examples. Pits are getting redone anyways.
