### ISSUE TITLE
reset old black plates on a new white plate

### ISSUE THREAD

**Issue by I-love-bee-2** [BEEmod/BEE2-items#1184]
Reset old black panel on the new white panel or as it is called rekanstrukschiya
![default](https://cloud.githubusercontent.com/assets/24528675/21111523/0d973f60-c0b3-11e6-9bfb-5e26d0bfe7fb.PNG)

**Comment by Luke18033** [comment]
This should probably be an item of some kind, it might break some chambers if the panels aren't portalable right from the start. This would also be part of Reconstructing style, which hasn't been implemented yet.

**Comment by I-love-bee-2** [comment]
@Luke18033  and will restore the style in general?

**Comment by Luke18033** [comment]
???

**Comment by ellingtonvengaboysmuseum** [comment]
make it a item like the cutout tile with a arrow showing the direction they will fall...

**Comment by Luke18033** [comment]
Why an arrow showing the direction they would fall wouldn't they always fall down?
