### ISSUE TITLE
Old aperture and portal 1 style laser redirection cube and sphere 

### ISSUE THREAD

**Issue by Flametusk** [BEEmod/BEE2-items#1185]
And, possibly, frankenturrets as well? Anyways, I think that the models for those time periods shouldn't be just overgrown or clean, but have their own.

**Comment by Luke18033** [comment]
Portal 1 should be using the sphere from Portal 1. The reflection cube should stay the same as Clean, see #1164. For Old Aperture, however, they should be styled. The sphere could just be a simple wooden ball or something, and the reflection cube could be a prototype, maybe with lots of mirrors.

**Comment by TheDarkBomber** [comment]
There was no sphere from Portal 1.

**Comment by Konclan** [comment]
There was a sphere in portal 1, in the bonus map for the companion cube chamber

**Comment by TeamSpen210** [comment]
Someone will need to design and make a model for these, first before I can use it.

**Comment by ZombiePwner1** [comment]
@TheDarkBomber if you play the portal 1 companion cube advanced chamber then you will see it is a ball.

**Comment by Luke18033** [comment]
Reepblue and HMW actually made P1 reflection cube models, one of which you could shrink down and use with their permission. Reepblue's in included in his [Portal 2 Demo Map](https://forums.thinking.withportals.com/downloads.php?view=detail&df_id=280) and HMW's in [Try Anything Twice](https://forums.thinking.withportals.com/downloads.php?view=detail&df_id=281).

**Comment by Luke18033** [comment]
@Flametusk, frankenturrets can't have their models changed.

**Comment by TeamSpen210** [comment]
HMW's stuff is all under a Creative Commons license, so we're free to use it (with credits).

**Comment by ZombiePwner1** [comment]
@Luke18033 Those models look nice. It's a shame we can't changed the franken cube model.

**Comment by ZipZoptheCat** [comment]
The 50s style sphere could be a bowling ball. That'd be funny.

The 50s style redirection could just be steel girders forming a cube around the lenses?

**Comment by Endermage77** [comment]
I second the bowling ball idea.

**Comment by TeamSpen210** [comment]
A  bowling ball would be difficult to pick up, and is probably going to shatter after falling out of the dropper.

**Comment by ZipZoptheCat** [comment]
Well are there any sphere models you could reuse from gmod files or somewhere?

**Comment by ZipZoptheCat** [comment]
It's a shame, the bowling ball would be such an easy skin to make. Just add three block spots to a wallpaper style design.

**Comment by Endermage77** [comment]
Indeed, a storage cube I'd guess is roughly 3-ish times the size of a bowling ball in length, width, and height.

**Comment by ZipZoptheCat** [comment]
So basically a Medicine Ball is the only thing time period appropriate with both the right size, shape, weight and durability unless something entirely new is created.

**Comment by Endermage77** [comment]
If I remember correctly, the largest medicine ball I can think of is roughly 1.25 to 1.5 times the size of a bowling ball.

**Comment by ZipZoptheCat** [comment]
Medicine Balls are often shoulder width. Not sure if that's enough and yeah, yoga balls are way too light and I don't think they were popularized till the 60s or 70s.

Are there any rough metal balls of any description already in the source code?

**Comment by Endermage77** [comment]
A sphere shape is probably very easy to find, all you'd really need is a good texture.

**Comment by ZipZoptheCat** [comment]
That'd be a heck of a rescaling job but if it could be done might look pretty good.

**Comment by DrMeepster** [comment]
Frankenturret could be remodeled by packing a new model in the map to override the portal 2 model

**Comment by TeamSpen210** [comment]
... No, no it can't. You can't override any files in the VPK.

**Comment by DrMeepster** [comment]
Thought you could, based on [this map](https://steamcommunity.com/sharedfiles/filedetails/?id=338379916) and how any spheres spawned look like Wheatly, but I just checked with `ent_text` and it seems to just change the model of any sphere spawned.

**Comment by DrMeepster** [comment]
There appears to be a real way to style frankenturrets. I was able to use the `SetModel` script function to change the model of a frankenturret. An important note is that the script needs to be executed after the map loads and a prop needs to be in the map with the new model, otherwise the game crashes.
![monsterbox](https://user-images.githubusercontent.com/19316085/77598006-ddf64500-6ebd-11ea-9156-ed65907eb8ec.jpg)
I know it was using it because of `ent_text` and the box was screaming "Oh, Fiddlesticks, what now?" repeatedly just like I set it to in the animation of `monster_b`

**Comment by TeamSpen210** [comment]
Does that work when it swaps between on and off the button? Those are seperate models.

**Comment by DrMeepster** [comment]
It switches to the alternate model when it gets on the button. I tried making a script that switches the model in a think function but it will still flash the box model before going back to mine.

**Comment by DrMeepster** [comment]
I made an old aperture sphere model:
![](https://cdn.discordapp.com/attachments/315249214680465409/714910515436060672/unknown.png)
Editor Model:
![editor](https://user-images.githubusercontent.com/19316085/82964029-32c74200-9f79-11ea-9518-ff9cffdd7e2f.png)
