### ISSUE TITLE
Locked out of Start Room 

### ISSUE THREAD

**Issue by ajrocks33** [BEEmod/BEE2-items#1188]
Not Sure if this is the games fault or mod but i locked my self out of the sp entry 7 room XD i went in the room then out style was over grown.
 Here's some pictures
![20161212152255_1](https://cloud.githubusercontent.com/assets/12651151/21121049/1ca6d1a2-c07f-11e6-89c5-fb8cdbff413f.jpg)
![20161212152257_1](https://cloud.githubusercontent.com/assets/12651151/21121051/1e128fa4-c07f-11e6-877e-8e412bbc7de0.jpg)
![20161212152315_1](https://cloud.githubusercontent.com/assets/12651151/21121052/1fca8a86-c07f-11e6-9573-4912dbcb1a6d.jpg)

**Comment by Luke18033** [comment]
@TeamSpen210 Maybe enable an invisible `func_brush` when the player is through the door.

**Comment by Flametusk** [comment]
That would also make it so that when you get far enough from the door for it to start closing, and then immediately go backwards, you don't get locked in the entrance room.

**Comment by ajrocks33** [comment]
it even turns on when you in the middle of the door
