### ISSUE TITLE
Overgrown + Wheatley Combo

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#1189]
New Style: Overgrown + Wheatley Combo

think about it, in a parallel universe like PTI wheatly somehow takes over glados position before she is even reactivated and goes mad with power and the facility goes from overgrown into TOTAL CHAOS with wheatley tearing apart aperture and overgrown bottomless pits and all!

**Comment by Luke18033** [comment]
I don't know if this would work very well. A lot of it wouldn't make sense without custom Wheatley lines anyway.

**Comment by Luke18033** [comment]
@TeamSpen210 Is this going to be implemented? Does it even make sense to implement?

**Comment by Luke18033** [comment]
I don't think this would really work as its own style, we'd probably just add an Overgrown bottomless pit option if anything.

**Comment by Konclan** [comment]
The bottomless pit should just adapt to the style anyways.

**Comment by Luke18033** [comment]
Yeah. With the chamber exteriors system I don't think bottomless pits would be tied to the skybox anymore, they'd be under style properties or something.
