### ISSUE TITLE
Custom style option

### ISSUE THREAD

**Issue by Flametusk** [BEEmod/BEE2-items#1196]
It could maybe bring up a wizard to choose textures and models, but would just use the 'clean' editor textures. It could allow for things like a 'transition'style, which could be for between portal and portal 2.

**Comment by LautaroL20** [comment]
There was an item called "Wall Feature" that meets this funtion, but i don´t know if its gonna be implemented since it doesn´t appear on the list: https://github.com/TeamSpen210/BEE2-items/issues/95

**Comment by TheDarkBomber** [comment]
Wall feature didn't really change the style though.

**Comment by LautaroL20** [comment]
Well, he mentioned "textures" and that item meets that function. If he wants to change the whole Style through a simple wizard, then he should definitelly contact Valve to Re-Code the PeTi Editor, or just use Hammer Editor.

**Comment by Byzarru** [comment]
It would be really nice in BTS to have test chambers tucked away in the maintenance areas, or, as you said, to have transitions in the clean areas. This could work to make office areas in Old Aperture, too.

**Comment by Byzarru** [comment]
Though, if you're going for an all-out retexturing and remodeling of everything and using a wizard to configure models and textures you've collected into BEE, you might as well just go into Hammer and retexture everything.

**Comment by Luke18033** [comment]
@LautaroL20 I think he means a wizard to add styles to BEE2 style chooser.

**Comment by TheDarkBomber** [comment]
Creating styles? See my WASP repository.

**Comment by Endermage77** [comment]
I think he actually means a wizard that can mix and match various bits of existing styles to create new and interesting combinations.

**Comment by Flametusk** [comment]
Yeah, that. Like having, say old aperture cubes and buttons with 80s textured in a broken enrichment sphere.

**Comment by Endermage77** [comment]
Don't forget to name & save!

**Comment by Endermage77** [comment]
That said, the name "Style Mixer" would perhaps suit this issue better as a title.

**Comment by Luke18033** [comment]
Styles are more than just simple texture swaps, I don't think this can be reasonably implemented.
