### ISSUE TITLE
Will there be a wall skybox?

### ISSUE THREAD

**Issue by I-love-bee-2** [BEEmod/BEE2-items#1197]

**Comment by Byzarru** [comment]
Wall skyboxes? Like in Wheatley or Underground where the walls are torn away?

**Comment by Luke18033** [comment]
There's a skybox label?

**Comment by LautaroL20** [comment]
@Luke18033 - Unfortunately from some time ago there is seems to be a guy who is also a collaborator wich is literally playing with all these labels, changing their colours and whats more, making lot of new ones too.....

**Comment by Luke18033** [comment]
Well, some of them are useful. "Skybox" isn't one of those though.

**Comment by LautaroL20** [comment]
Id say not only Skybox, but some others like "Missing Texture", "Confirmed" and "Original Clean" are pretty much useless too. I have deleted the missing texture one, now thinking if i should also delete "Confirmed".... 

Ill going to restore the "Original Clean" label to simply "Clean" since they works exactly the same.

**Comment by Luke18033** [comment]
@LautaroL20 Don't delete Confirmed. It's used to mark something which has been confirmed by TeamSpen or BenVlodgi. Missing Texture has a use too. Original Clean items work identically to Clean's, so that label is not needed.

**Comment by LautaroL20** [comment]
There is already a label "Missing Icon" wich can be used instead of a "Missing Texture" one.

**Comment by Luke18033** [comment]
Missing Texture is referring to a custom texture not being packed. It has nothing to do with icons.

**Comment by Luke18033** [comment]
And besides, there's no limit to how many labels we can have. More specific labels are always better.

**Comment by LautaroL20** [comment]
I know, but be careful to not end up with a messy labels list. Labels always have to be clear and useful. Also, as for the Missing Texture, it will be better rename to "Texture not packed" .

**Comment by Luke18033** [comment]
@LautaroL20 Why did you change them all to the same color?

**Comment by LautaroL20** [comment]
Because these are derivative from the original "Bug" label.

**Comment by TheDarkBomber** [comment]
And the Skybox label is useful, for issues relating to Skyboxes. Like the Stylevar label.

**Comment by Byzarru** [comment]
Why is this closed? The thread title is "Will there be a wall skybox?", not "Skybox label"

**Comment by LautaroL20** [comment]
The question isn´t answered yet so.

**Comment by Luke18033** [comment]
The question isn't answered, because nobody knows what @I-love-bee-2 is referring to by "wall skybox". Until a better description is provided, this issue is closed.

**Comment by ZombiePwner1** [comment]
@Luke18033 Clearly I-love-bee-2 doesn't know how to speak English properly
