### ISSUE TITLE
water level control, or the acid slurry

### ISSUE THREAD

**Issue by I-love-bee-2** [BEEmod/BEE2-items#1199]

**Comment by Luke18033** [comment]
What?

**Comment by TheDarkBomber** [comment]
Water level control.

**Comment by Luke18033** [comment]
@I-love-bee-2 If you are referring to Goo which can be filled or drained, then this is a duplicate of #584.

**Comment by I-love-bee-2** [comment]
this element will be added?

**Comment by TheDarkBomber** [comment]
Maybe????????????????????????????????????????????**???????????????**

**Comment by I-love-bee-2** [comment]
@TheDarkBomber When draining slurry occurs dirty wall must be

**Comment by LautaroL20** [comment]
@Luke18033 - Nope, its not a duplicate..... With "water level control" he probably means a static resizeable version of Deadly Goo from a 1/4 or 2/4 of a block.

**Comment by TheDarkBomber** [comment]
@LautaroL20 Probably.

**Comment by Luke18033** [comment]
@I-love-bee-2 I don't understand what this suggestion is supposed to be...what does "water level control" refer to? If it refers to drainable/fillable goo, then this is a duplicate of #584. If it refers to multiple water levels within a block, could you explain that?

**Comment by Luke18033** [comment]
This suggestion is incredibly vague and hasn't been touched in over 2 years, so I'm going to close it.
