### ISSUE TITLE
Force Deflection Field has no fade when switched on/off

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1202]
The Force Deflection Field does not fade on and off when input in the 70s style. Instead, it simply disappears and reappears. All other fizzlers have the proper animations.

**Comment by Byzarru** [comment]
I haven't tried this for the Death Fizzler, but I assume it works.

**Comment by ZombiePwner1** [comment]
i don't remember seeing the deflection field fading when it's turned off or on.

**Comment by TeamSpen210** [comment]
The Force Deflection Field isn't a 'real' fizzler - it's a fake one, to allow you to fire portal shots through it. Only actual fizzlers can have the fade-in effect though, so it doesn't have one. I figured out a way to solve this for Physlers, so I'll do the same for this one.
