### ISSUE TITLE
Worldportal in Entry Corridor causing incorrect door rendering

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1207]
It doesn´t matter if you try adding better lighting on the area, the door´s circle will keep looking totally black when it starts opening:

![20161216132149_1](https://cloud.githubusercontent.com/assets/12244376/21278525/70423066-c3ba-11e6-87f6-2631ed51a74a.jpg)

**Comment by Luke18033** [comment]
I think that means the map is leaked.

**Comment by LautaroL20** [comment]
No, if this would be due to a leak, it must look as a white circle instead. This may be caused by shadows generated from the door´s model or so.

**Comment by TheDarkBomber** [comment]
Unpacked Texture?

**Comment by TeamSpen210** [comment]
It's to do with the precise position of the worldportal in relation to the two door models - I need to check how exactly they're aligned. This happens in vanilla PeTI as well.

**Comment by Luke18033** [comment]
That's clean...

**Comment by TeamSpen210** [comment]
It'll affect Overgrown too, or I'll need to check it doesn't at least.

**Comment by LautaroL20** [comment]
It could happens in overgrown too, but not sure.
