### ISSUE TITLE
Clean elevators screens is "Mysteriously" getting a bit stretched 

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1209]
![20161217114500_1](https://cloud.githubusercontent.com/assets/18079316/21284162/651f998c-c44e-11e6-85b9-e9bbeef01443.jpg)

**Comment by LautaroL20** [comment]
This should only happens when you are using Overgrown Style, so this is really mysterious.

**Comment by LautaroL20** [comment]
I think you may have mixed up files, try re-exporting all again from scratch.

**Comment by ZombiePwner1** [comment]
There is no way this has something to do with the files it's most likely the way the screens get created since this doesn't happen all the time it happens randomly on exports.

**Comment by LautaroL20** [comment]
Im saying that due to a strange mixed up after some re-exports with beemod, clean style may be used the overgrown instances on the screens video.

**Comment by TeamSpen210** [comment]
Screens have several scale setups in the script, which are randomly chosen whenever you start the map. In Overgrown it uses every variant, but Clean should only use the non-'broken' ones. I must have mixed up something in the script.

**Comment by TeamSpen210** [comment]
Actually, this is an issue with a specific scale type - it has multiple videos, with some 'blank' screens in between. The problem is that the script just uses the right edge of the screen to get the background colour, which messes up if the video affects the border.
