### ISSUE TITLE
 Implement "Start Reversed" option on Protuding pedestal buttons to have control over the "Facing inwards" feature.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1216]
![20161218141244_1](https://cloud.githubusercontent.com/assets/18079316/21291913/135d7572-c52c-11e6-8776-3248c42079d2.jpg)

![20161218141106_1](https://cloud.githubusercontent.com/assets/18079316/21291910/f938f3c4-c52b-11e6-9ee1-d848f4befe69.jpg)

**Comment by LautaroL20** [comment]
If the block next to the button is empty, the button will rotate to face inwards. But instead, itll be better to having control over this by adding the option "Start Inverted".

**Comment by Luke18033** [comment]
I don't have this issue. Maybe something with the square light?

**Comment by LautaroL20** [comment]
Try placing it below any item that opens a boxel inside the wall.

**Comment by Luke18033** [comment]
@LautaroL20 It doesn't really matter why this is happening. Just add Start Reversed.

**Comment by LautaroL20** [comment]
@Luke18033 - Just click "Sync" on the github app.
