### ISSUE TITLE
Clean COOP Exit Door inside disassemble room disappears in a "Mysterious Way" if another person is still in the hall way.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1221]
![20161219103038_1](https://cloud.githubusercontent.com/assets/18079316/21299402/47c2a6b6-c5d6-11e6-907b-164501debf78.jpg)

![20161219103140_1](https://cloud.githubusercontent.com/assets/18079316/21299412/5ccd47dc-c5d6-11e6-8653-bff8c50fd7bb.jpg)
In this 2nd screenshot atlas is in the disassemble room now but something else happens the door in the disassemble room has appear but the fizzler and the exit door at the hall way has mysteriously disappeared

![20161219103610_1](https://cloud.githubusercontent.com/assets/18079316/21299476/fdd7bdce-c5d6-11e6-9a2b-f5d28b60f42a.jpg)

**Comment by Luke18033** [comment]
@ZombiePwner1 If that's Co-op, then why is the portal gun the SP gun with a human hand holding it?

**Comment by LautaroL20** [comment]
Thats because he loves using custom models. This makes me think he may broken something? Ill gonna test this myself then.

**Comment by ZombiePwner1** [comment]
That portal gun model is made to have a hand the coop guns are just a skin of the original model and because of that it's impossible to add a robot hand to the coop guns.
