### ISSUE TITLE
BTS Style is having "Massive Leaks" in almost the Entry / Exit corridors

### ISSUE THREAD

**Issue by Jazz63540** [BEEmod/BEE2-items#1222]
Whenever I build a chamber in the behind the scenes style, the view through the entry door is very glitchy. I 
have already attempted 'verify integrity of game cache':

![fe5ab83c-c57c-11e6-8301-4bd3cd9de83a](https://cloud.githubusercontent.com/assets/22215605/21314504/67300354-c5ef-11e6-88bc-c925af6b72cb.jpg)
![fe55bd00-c57c-11e6-90e0-9594e67c52f5](https://cloud.githubusercontent.com/assets/22215605/21314505/674a8a80-c5ef-11e6-99ec-28665b8d1b38.jpg)

**Comment by Byzarru** [comment]
The only entries and exits I can recall that don't have leaks are 1 and 1 respectively.

**Comment by Jazz63540** [comment]
Just tried them and got the same result:

![20161219183955_1](https://cloud.githubusercontent.com/assets/22215605/21324670/af2e54dc-c61a-11e6-8214-b899e850d438.jpg)
![20161219183951_1](https://cloud.githubusercontent.com/assets/22215605/21324671/af31c266-c61a-11e6-881e-c7fdb50f99c5.jpg)

**Comment by Byzarru** [comment]
2 then? I know one of the sets works. But BTS is still deep into development, so it'll be a while.

**Comment by LautaroL20** [comment]
BTS Style is pretty leaked atm, id suggest to use another style for the moment.
