### ISSUE TITLE
Protruding Pedestal Button unstyled and missing it's base, in all styles except for Clean

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1225]
![20161219111849_1](https://cloud.githubusercontent.com/assets/19228201/21325898/48ff153a-c5dd-11e6-84b6-ffe1284eb495.jpg)

**Comment by Luke18033** [comment]
@LautaroL20 Please fix this!

**Comment by Luke18033** [comment]
I am attempting to make styled instances for this item, but the base isn't included in the instance - likely the reason it's not being generated.

**Comment by Luke18033** [comment]
@LautaroL20?

**Comment by TheDarkBomber** [comment]
It's just simply unstyled.

**Comment by ZombiePwner1** [comment]
@Luke18033 If it's a duplicate then add the label you wheely.

**Comment by Luke18033** [comment]
I did, but @TheDarkBomber removed them...

**Comment by ZombiePwner1** [comment]
And art therapy buttons aren't missing their base since i checked the protuding buttons for art therapy and their base was there.
