### ISSUE TITLE
Retractable Protruding Pedestal Button

### ISSUE THREAD

**Issue by Flametusk** [BEEmod/BEE2-items#1226]
It could retract into the wall, maybe pulled in by the base?

**Comment by TeamSpen210** [comment]
That's really not needed? It's kinda unrelated to the item's purpose.

**Comment by Luke18033** [comment]
This could be useful, but we don't need it for this release.

**Comment by Luke18033** [comment]
This should work by having the button tilt outward, and then retract into a 64x64 hole which gets covered by glass. Extension would do the same, but in reverse.

**Comment by Flametusk** [comment]
Or, it could be a 64x64 base, which pulls in the button with glass walls the height of the button.

**Comment by Luke18033** [comment]
By the way, check the README if you want to install the dev version

**Comment by Luke18033** [comment]
This doesn't seem very useful
