### ISSUE TITLE
In-Air Music Bug

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1227]
This was originally the first issue I ever opened, BenVlodgi/BEE2.4#316. Even though it was reported back in Pr19, this is still a bug now, and needs to be fixed. I opened another issue here because it is related to the packages and not the actual program. It's probably going to be a duplicate anyway...

When certain things occur in P1 style, the in-air music (which should be disabled on P1 style anyway) will play very loudly. Examples of this are a HEP hitting a Positronic Energy Orb, or walking through a paint field. This only occurs when previewing, and not when publishing.

**Comment by Byzarru** [comment]
In PR22, this was an issue in Overgrown.

**Comment by TeamSpen210** [comment]
I figured out why the speed gel music plays suddenly, and have fixed it for the next release.

**Comment by Luke18033** [comment]
So does that mean I'll get it in the dev version? Also, the in-air/speed gel music should be disabled in Portal 1, since it didn't have it.

**Comment by Luke18033** [comment]
Or make custom tracks to go with the P1 music. Disabling it would probably be easier.

**Comment by LautaroL20** [comment]
>  So does that mean I'll get it in the dev version?

Just stand on the "dev" branch then click "Sync", youll get all the fixes.

**Comment by TeamSpen210** [comment]
You'll need to rebuild VBSP & VRAD to get the fix.
