### ISSUE TITLE
BTS Retractable Pedestal Button unstyled

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1228]
Note: This post has been edited several times, so some of the comments may not make sense anymore.

In BTS, the Retractable Pedestal Button is completely unstyled. It would be identical to the original, but the power would turn off when deactivated, like the main Old Aperture version. ~~The alternate version would change it to a button/lever mounted on the side of a retracting piston.~~

~~The Old Aperture Retractable Pedestal Button doesn't retract - it just gets disabled. This could cause compatibility issues, as the button would still be extended even when off. An alternate version should be available which actually retracts. This would be done using a pulley system, which would pull a box containing the button out of the floor. The sdes of this box would be open, and the top would be made of glass, forming the door covering the button. The pulleys would be positioned differently on walls and ceilings. For 1980s, the button would be pushed up out of the surface like on other styles. However, the hole would be square, and an Old Aperture button would still be used.~~ (Not really necessary IMO)

**Comment by Byzarru** [comment]
Several ideas for BTS:
- A red button (like a clean old aperture pedestal button) that retracts from the ground.
- An override button with a plastic covering on it that flips out when activated. 
- A standard override button built on an embedded rail (like the unstationary scaffolds).

**Comment by Byzarru** [comment]
Also, 40s-60s Old Aperture buttons could have doors that flip open as part of the pulley system, keeping in line with the style of the item overall (a hole in the ground covered by something to keep people from falling in or pressing the button) and the aesthetic of Old Aperture (mechanical items).

**Comment by Luke18033** [comment]
@Byzarru That still wouldn't work - the ropes would clip through it.

**Comment by Byzarru** [comment]
Are you thinking of a stand that pulls the button up? A pulley system could easily be implemented underground.
![image](https://cloud.githubusercontent.com/assets/22107242/21337736/71fab7c0-c635-11e6-9181-820fa7e8584f.png)
Of course, why bother adding ropes if everything _is_ underground.

I also thought we didn't have an animator?

**Comment by Luke18033** [comment]
We shouldn't need an animator if func_doors and such are used.

**Comment by Luke18033** [comment]
Oh, I have an idea. I'll edit the original post.

**Comment by TeamSpen210** [comment]
I orginally did have it as a retractable button, actually one with two glass box-halves which slid over the button to hide it. I switched it to be a 'locking' button since it's far 'simpler' - it's just electrics, instead of lots of complicated and expensive motors and wires. 

See the developer commentary in `sp_a3_jump_intro` near the moving platform - Valve's design aesthetic for test elements was to make them in the simplest way possible, stuff cobbled together that does the job.

**Comment by Luke18033** [comment]
@TeamSpen210 Well then in that case, only 1950s and 1960s buttons should actually retract. 1970s buttons would still just lock, and 1980s buttons would retract like modern buttons.

**Comment by Luke18033** [comment]
Or you can keep the locking version as an alternate version.

**Comment by Luke18033** [comment]
@TeamSpen210 What about BTS?

**Comment by Luke18033** [comment]
One reason the Old Aperture button should retract is for compatibility - let's say you have a faith plate that launches the player against the button, but then later it gets retracted so you can launch past. Switching to Old Aperture would break this design. The pulley system wouldn't have collision, allowing the player to launch past. I've previously suggested keeping the locking button as an alternate version, but really it should be the other way around. The BTS variant would also need an alternate version, maybe use Byzarru's third suggestion.

**Comment by Luke18033** [comment]
Bump. Actually, I could probably develop this myself.

**Comment by TeamSpen210** [comment]
For BTS, I reckon going with the current sort of button, but maybe with a glass cover, or alternatively when disabled turning off all the lights (out of power). I'm not really convinced that Old Aperture buttons should move, especially since we have a design that doesn't need that. In Old Aperture we should limit the number of 'motors' used as much as possible, especially also directions. For this sort of thing, I'd actually think adding a small roof above the button (on pillars in the corners) would be best - then it retracts down with that forming the ceiling.

**Comment by Luke18033** [comment]
The retracting Old Ap button would be an alternate version.

**Comment by Luke18033** [comment]
BTS would need an alternate retracting version as well. Turning off the power would probably make more sense for the main version.

**Comment by TeamSpen210** [comment]
![img_2441](https://cloud.githubusercontent.com/assets/8453732/25928685/ecde50fc-3640-11e7-824b-cbf8135cd1fa.JPG)
These retracting versions should be alternates.

**Comment by Luke18033** [comment]
I don't think this is really necessary anymore.

**Comment by Luke18033** [comment]
Actually, the BTS variant is still missing.

**Comment by ZombiePwner1** [comment]
We should just remove BTS style entirely and focus on Art Therapy for now.

**Comment by Luke18033** [comment]
I think our number one priority right now regarding styles should be improving and fixing the existing ones, not adding yet another new one.

**Comment by The-Queen55142** [comment]
I'm sure a lot of people would be upset if BTS is just removed, it may not be a good "puzzle" style or anything. but using Items provided by both BEE and User-created packages. They can make something interesting out of BTS.

This is also why styles like Portal 1 BTS have been brought up and planned for the distant future, people want it, it's really not that big of a deal if it's added, and it makes people happy, what do you have to lose?

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
