### ISSUE TITLE
Overgrown Repulsion Gel and Propulsion Gel cause compile failure

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1229]
In Overgrown style, Repulsion Gel and Propulsion Gel cause compile failure. It's not a missing instance though (I've looked in the console). I can't figure out what this error is, but here's the console anyway:

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr23 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (13 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "ITEM_BEE2_FIZZLER_OUT_RELAY" not a valid item!
[INFO] cond.core.res_goo_debris(): GooDebris: 0/0 locations
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[ERROR] cond.core.check_all(): Error in <BEE2_OVERGROWN>/items/mandatory/entry_door:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 463, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 353, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 342, in test_result
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1580, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 353, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 340, in test_result
ValueError: "skipCondition" is not a valid condition result!

**Comment by TeamSpen210** [comment]
I changed the compiler to crash if it tries to execute a command it doesn't know, instead of printing a message and quitting. This exposes an incorrectly named config file.
