### ISSUE TITLE
Change Adhesion Gel pipe in the 1960s sphere area to Reflection Gel

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1231]
![20161220091927_1](https://cloud.githubusercontent.com/assets/19228201/21360636/983b7234-c695-11e6-818c-07b3eed6a918.jpg)

**Comment by LautaroL20** [comment]
I was about to rename this to "Make the Grey Adhesion Gel Overlay" for the tube model, but since im not sure if this would imply to rework the entirely model or its just a VMF/VTF Texture it wouldn´t.

**Comment by ZombiePwner1** [comment]
Make it a reflection gel pipe instead don't remove it.
