### ISSUE TITLE
Flamethrowers set to start enabled permanently turn off after the player is killed

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1232]
The title says it all.

**Comment by TheDarkBomber** [comment]
Single Player label is useless. We have a CO-OP label, so any issue that isn't labelled CO-OP would be Single Player.

**Comment by Luke18033** [comment]
No it's not, it's for issues that only apply to Single Player. In this case, the player needs to be killed to make the glitch happen. Death only restarts the map in Single Player, so the label is used.

**Comment by TheDarkBomber** [comment]
Single Player will be overused, though.

**Comment by Luke18033** [comment]
It won't through. If there is a bug "spheres are not round" then it would apply to single player and co-op, so neither would be used.

**Comment by Luke18033** [comment]
Stop deleting it...it is useful, for single-player only issues. Like issues related to SP corridors or, in this case, restarting the map upon death, which only happens in SP.

**Comment by Luke18033** [comment]
Please stop deleting it. It IS useful.

**Comment by Luke18033** [comment]
Stop, I'm gonna have to ask @TeamSpen210 if you should still be a collaborator with all of the deleting stuff you're doing...

**Comment by ZombiePwner1** [comment]
@Luke18033 He did it to my compile error label aswell so your not the only one.

**Comment by Luke18033** [comment]
@ZombiePwner1 IK

**Comment by ZombiePwner1** [comment]
@Luke18033 There you go @TheDarkBomber Is a contributor now.
