### ISSUE TITLE
60's coop exit door mysteriously closes when 2nd player is in dissassemble area leaving mate stuck in the test.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1234]
![20161221131850_1](https://cloud.githubusercontent.com/assets/18079316/21378267/31ca86f2-c780-11e6-9300-f8d65d3f1e59.jpg)

![20161221131854_1](https://cloud.githubusercontent.com/assets/18079316/21378270/366d60a8-c780-11e6-86c1-c76126188cbd.jpg)

![20161221132204_1](https://cloud.githubusercontent.com/assets/18079316/21378312/7f1728b6-c780-11e6-98f1-e1a5bb781135.jpg)

**Comment by TeamSpen210** [comment]
Walk back over, the door will reopen.

**Comment by ZombiePwner1** [comment]
But it's still mysterious.

**Comment by ZombiePwner1** [comment]
It still shouldn't happen anyway.

**Comment by TeamSpen210** [comment]
Basically there's a trigger in the exit door, that holds it open while you're inside. But if you go through the worldportal, you leave the trigger but are still past the door.

**Comment by Luke18033** [comment]
Seems fixed now.
