### ISSUE TITLE
Large faithplates off version no longer works.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1235]
![20161221171241_1](https://cloud.githubusercontent.com/assets/18079316/21383481/ee2c17dc-c7a0-11e6-90af-0c7f4a89496b.jpg)

Faith plate is enabled but in the 2nd screenshot you can clearly see start enabled is not ticked so the faith plate should be off.

![20161221171250_1](https://cloud.githubusercontent.com/assets/18079316/21383490/01687868-c7a1-11e6-98a7-a269faedea95.jpg)

**Comment by Luke18033** [comment]
I don't think that has anything to do with Co-op. Try it in SP.

**Comment by LautaroL20** [comment]
Fath plates works pretty normal, try syncing github.

**Comment by ZombiePwner1** [comment]
I was talking about the start enabled @LautaroL20 u wheely

**Comment by LautaroL20** [comment]
I was talking that they works pretty normal, having the option disabled or enabled.

**Comment by ZombiePwner1** [comment]
It's mean't to turn off when start enabled is disabled.

**Comment by TeamSpen210** [comment]
This only occurs if it's set to start disabled, and you don't have any items connected. That's rather useless, so I didn't account for it in the item.

**Comment by TeamSpen210** [comment]
I could make it functional, but that would be very pointless.

**Comment by LautaroL20** [comment]
Yep, just leave as it is now.

**Comment by Luke18033** [comment]
Don't leave it as it is, what if you want to have a broken faith plate in an Overgrown chamber? It would just become a giant nodraw.
