### ISSUE TITLE
BTS Style is having "Massive Leaks" and Incorrect Entry Door placements.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1241]
Moved from the BenVlodgi´s section: https://github.com/BEEmod/BEE2.4/issues/244

Massive leaks on the BTS Style corridors:

![image](https://cloud.githubusercontent.com/assets/17777059/16370849/2c7417e8-3c86-11e6-87f0-2088bc242574.png)
![20160315185602_1](https://cloud.githubusercontent.com/assets/17092818/13766949/85320756-ea23-11e5-96ff-e3761478f2f2.jpg)

![20160315190049_1](https://cloud.githubusercontent.com/assets/17092818/13766981/b5acffbc-ea23-11e5-985f-02babb680cea.jpg)

**Comment by Byzarru** [comment]
Also see #1222.

**Comment by Luke18033** [comment]
Should be fixed? These corridors still aren't implemented, but TeamSpen replaced them with copies of the existing ones for now which would stop the leak.
