### ISSUE TITLE
Make new variants for Entry and Exit Corridors for Old Aperture

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1243]
Moved from the BenVlodgi´s section: https://github.com/BEEmod/BEE2.4/issues/215

Original post by @Kalethars:

"While the current 50s to 80s style's elevator is outside the chamber and inside the sphere, it is weird that the location of entry and exit is fixed and not correct. I hope to see a new entry and exit style like bts inside the building and that will let me feel better. :)"

**Comment by Byzarru** [comment]
Wouldn't this be a feature of the Old Aperture BTS style?

**Comment by LautaroL20** [comment]
Idk, i was just sorting out some issues into the correct place. If you read the post youll see this was originally made by another user.

**Comment by Byzarru** [comment]
I noticed. I've made a few notes about external entrances on #1245, if you want to have a squiz.

**Comment by Konclan** [comment]
Merging with #530
