### ISSUE TITLE
Mashy Spike Plate editor model is missing its "Grip Point" being literally impossible to manipulate it

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1248]
![20161221202340_1](https://cloud.githubusercontent.com/assets/12244376/21411915/ed4f36da-c7ca-11e6-8bf5-7b9947c52945.jpg)

**Comment by Luke18033** [comment]
The 1960s Flamethrower (which uses the same editor model) doesn't have this problem.

**Comment by LautaroL20** [comment]
Well that means i can fix this eaily by re-using the "grip" file from that model also for the clean one.

**Comment by LautaroL20** [comment]
@Luke18033 - Nope, the 60´s Flamethrower is also missing the grip point, and is unstyled too.
