### ISSUE TITLE
Futbol Spawner is missing its Editor Model

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1249]
![20161221203007_1](https://cloud.githubusercontent.com/assets/12244376/21411982/55ff1e0c-c7cb-11e6-8bba-3904955f9255.jpg)

**Comment by ZombiePwner1** [comment]
This is a duplicate of https://github.com/BEEmod/BEE2-items/issues/718

**Comment by Luke18033** [comment]
And it's the same image...
