### ISSUE TITLE
Overgrown: Implement "Rusty Visuals" on the "elevator_hole.mdl"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1250]
![20161217122942_1](https://cloud.githubusercontent.com/assets/12244376/21412081/39a81a32-c7cc-11e6-89f9-00c862f63514.jpg)

**Comment by Luke18033** [comment]
Again this really just isn't needed, most people don't pay enough attention to the entrance/exit to notice if a random prop is clean - it's never been an issue for Valve's maps or any other community maps. And actually I'm pretty sure this model does have a light flickering animation, we should just be using that if we're not already.
