### ISSUE TITLE
Aperture tag paint gun activation fields sign model packs as mysterious blue error for people who don't have beemod installed.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1252]
![20161222021033_1](https://cloud.githubusercontent.com/assets/12244376/21416591/ce8107ec-c7f2-11e6-85dc-e2e4828ff0ab.jpg)

**Comment by LautaroL20** [comment]
Yep we were testing it and here is a screenshot:

![20161222021033_1](https://cloud.githubusercontent.com/assets/12244376/21416591/ce8107ec-c7f2-11e6-85dc-e2e4828ff0ab.jpg)

**Comment by TeamSpen210** [comment]
How funny, that I just fixed this 45 minutes ago (e7e433b)...

**Comment by LautaroL20** [comment]
And also the only way to get the model pack will be using Beemod with AT. Since the AT Compiler can´t pack models.

**Comment by TeamSpen210** [comment]
BEE2.4 replaces that [compiler](https://github.com/BenVlodgi/Tag-Intermediate-Compiler) with its own. I've reimplemented the features of that in the compiler, so it works perfectly fine. The original items don't need a packed model.
