### ISSUE TITLE
Heli-Bomber

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1254]
![20161222203150_1](https://cloud.githubusercontent.com/assets/18079316/21425886/9ef9236c-c886-11e6-82a2-1690c483214f.jpg)

![20161222203742_1](https://cloud.githubusercontent.com/assets/18079316/21425888/a25b6330-c886-11e6-9fbe-7472c9385bc5.jpg)

A bomb disguised as a helicopter this can be used to get cubes off ledges that portals are impossible to use.

**Comment by Byzarru** [comment]
This should be a console system, like the ball or crane in Batcat's maps.

**Comment by Byzarru** [comment]
Also, could you link to this map?

**Comment by Luke18033** [comment]
[Into the Multiverse Part 5](https://steamcommunity.com/sharedfiles/filedetails/?id=429340907)

**Comment by Konclan** [comment]
UCP

**Comment by guymancool** [comment]
i got the actual thing in the editor but i cant figure out with the buttons
