### ISSUE TITLE
Gravity portal gun.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1255]
![20161222204010_1](https://cloud.githubusercontent.com/assets/18079316/21425917/e29748ec-c886-11e6-99da-12cdbbc09274.jpg)

![20161222204017_1](https://cloud.githubusercontent.com/assets/18079316/21425920/e56f3dc2-c886-11e6-950d-b9d17ee63a47.jpg)

![20161222204022_1](https://cloud.githubusercontent.com/assets/18079316/21425922/e830f4e2-c886-11e6-9275-e127b5c7ea3b.jpg)

A portal gun that can switch between portals and gravity mode gravity mode allows you to grab objects from really far away be using right click and once held u can use left click to launch it very far.

**Comment by Byzarru** [comment]
I first saw this and thought "what a crappy idea. You can't be sure that people will read the workshop description and know that this 'Portal Gun' is a Gravity Gun." I have issues (demonstrated in #1150) with false appearances (super turrets looking exactly like regular turrets, or special guns looking exactly like portal guns), However, I think this would do well as a custom fizzler (or if TeamSpen210 figures out how to make custom gun models work somehow) that enables and disables the gravity gun while adjusting portal functionality accordingly (like the fizzlers in ApTag).

**Comment by Byzarru** [comment]
And that red dropper is exactly what bomb droppers should look like.

**Comment by TeamSpen210** [comment]
Bomb droppers will be a more bare vactube.

**Comment by Luke18033** [comment]
I don't think that looks very good, except in BTS. I'd like the red dropper.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Perhaps it can be a stylervar for the bomb droppers model. You can switch between the vactube or red dropper.

**Comment by Luke18033** [comment]
We came up with a better design on Gitter - a cube dropper with red lights.

**Comment by Konclan** [comment]
UCP
