### ISSUE TITLE
Portal 2: Back-Stock

### ISSUE THREAD

**Issue by ilia227** [BEEmod/BEE2-items#1258]
http://www.moddb.com/mods/back-stock

**Comment by TheDarkBomber** [comment]
Unrelated to BEE. This will be closed and locked.

**Comment by Luke18033** [comment]
Stop posting these...

**Comment by LautaroL20** [comment]
Isn´t that the BenVlodgi´s mod or im on drugs?

**Comment by TeamSpen210** [comment]
It is indeed.
