### ISSUE TITLE
what will be the new style

### ISSUE THREAD

**Issue by ilia227** [BEEmod/BEE2-items#1259]

**Comment by TheDarkBomber** [comment]
More than one.

**Comment by LautaroL20** [comment]
Next style that will come out is "Art Therapy", but not in a near future i guess. You can ascertain this by going to the branches section.

**Comment by Flametusk** [comment]
How will art therapy work?

**Comment by LautaroL20** [comment]
Like any other style, each one have their own custom visuals and thats all.
