### ISSUE TITLE
Art therapy draw bridge is unstyled.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1264]
![20161223100747_1](https://cloud.githubusercontent.com/assets/18079316/21445740/bb91d606-c8f7-11e6-80f8-ce193541717a.jpg)

**Comment by Luke18033** [comment]
This also looks styled.

**Comment by Luke18033** [comment]
Should probably switch this to a template as well.

**Comment by Luke18033** [comment]
This is actually fixed already.
