### ISSUE TITLE
Art therapy coop exit causes the game to mysteriously crash.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1266]
Why?

**Comment by Luke18033** [comment]
When does it crash? When you go through? When it opens? Immediately when you compile the map?

**Comment by ZombiePwner1** [comment]
It only crashes the game when i try to copy the clean coop_exit.vmf to the art therapy files. I'm unsure why this happens.

**Comment by Luke18033** [comment]
This is probably caused by something being incompatible between that instance and the style.
