### ISSUE TITLE
Art therapy crusher is unstyled.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1268]
![20161223104209_1](https://cloud.githubusercontent.com/assets/18079316/21446064/8119e09a-c8fc-11e6-9569-00f471452979.jpg)

**Comment by Luke18033** [comment]
Also styled.

**Comment by ZombiePwner1** [comment]
@Luke18033 It's not styled the back of the crusher needs to be styled not the actual crusher model itself.

**Comment by TeamSpen210** [comment]
Art Therapy is partially-clean, so most things look ok there. But these shpulduse the yellow bckpanels textures.

**Comment by Luke18033** [comment]
This should probably actually be switched to use a template, so it can match the style automatically.
