### ISSUE TITLE
Art therapy track platform is unstyled.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1269]
![20161223104311_1](https://cloud.githubusercontent.com/assets/18079316/21446083/ad5e5ff0-c8fc-11e6-8334-b5dc9d8fa074.jpg)

**Comment by Luke18033** [comment]
Looks pretty styled to me.

**Comment by Konclan** [comment]
We're getting art therapy? and so soon?

**Comment by Endermage77** [comment]
Art Therapy is its own branch. You can download it right now and throw the files in with BEE2's.

**Comment by TeamSpen210** [comment]
I haven't really touched them in a while, I should just include Art Therapy. What it's mainly waiting on is good designs for entry/exit corridors and elevtors in SP.

**Comment by ZombiePwner1** [comment]
@Endermage77 Refurbished as far as i know doesn't work correctly at the moment since i've tried it before and it didn't work.

**Comment by TeamSpen210** [comment]
Indeed, it's just a few configs..

**Comment by Luke18033** [comment]
Nobody ever answered my question, what about this is unstyled? Just the wall textures?

**Comment by TeamSpen210** [comment]
Yes, but also I think track plats looked different in Art Therapy.

**Comment by TeamSpen210** [comment]
This is fixed though, the wall styles will change.
