### ISSUE TITLE
Art Therapy Pneumatic diversity vent is unstyled

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1271]
![20161223115221_1](https://cloud.githubusercontent.com/assets/18079316/21446835/5d8f8d3c-c906-11e6-8700-e0e5267b0265.jpg)

**Comment by Luke18033** [comment]
What would it be styled as?

**Comment by LautaroL20** [comment]
Clean Pneumatic diversity vent does completely fit well on both the BTS and Art Therapy, even Valve used the same model for those styles. If you would say Overgrown style, then this would be another scenario.

**Comment by ZombiePwner1** [comment]
Fair Enough then. btw come online.
