### ISSUE TITLE
Art Therapy a mysterious black shadow appears in the angled 30 and 45 degree panel

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1272]
![20161223114221_1](https://cloud.githubusercontent.com/assets/18079316/21446845/8f1125be-c906-11e6-90d4-3b6c62f1e085.jpg)

**Comment by Luke18033** [comment]
Where did you get that angled panel model? It isn't on the repo as far as I'm aware.
