### ISSUE TITLE
Art Therapy exit door logic is broken.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1273]
![20161223120528_1](https://cloud.githubusercontent.com/assets/18079316/21446935/2c2174d4-c908-11e6-9eb8-be4d7fa84f21.jpg)

Door is closed.

![20161223120532_1](https://cloud.githubusercontent.com/assets/18079316/21446940/313210fa-c908-11e6-89a6-474695695034.jpg)

I stepped on the button.

![20161223120534_1](https://cloud.githubusercontent.com/assets/18079316/21446942/376dbb7c-c908-11e6-82c1-a105ea0e7a47.jpg)

I let go of the button and the door opens wtf? i didn't even activate the 2nd button.

**Comment by Luke18033** [comment]
Has Art Therapy been merged into `dev`? Or did you just download the separate branch?

**Comment by ZombiePwner1** [comment]
I downloaded a sperate branch and i had to do other things since art therapy was quite hard to get.

**Comment by Luke18033** [comment]
Will be fixed with the introduction of proper SP support
