### ISSUE TITLE
1970's laser field trigger does not deactivate when deactivated.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1275]
![20161223184313_1](https://cloud.githubusercontent.com/assets/18079316/21452157/d54a3500-c93f-11e6-9b4d-6f9ca4706de0.jpg)

![20161223184316_1](https://cloud.githubusercontent.com/assets/18079316/21452158/d9b9ddc0-c93f-11e6-91f3-a6276bf90ca0.jpg)

The laser field is off yet i still die when i walk through it wtf?

**Comment by TeamSpen210** [comment]
Yay, missing/wrong output.

**Comment by LautaroL20** [comment]
Nice find!
