### ISSUE TITLE
is there any trigger that can detect paint?

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1277]
@TeamSpen210 or @BenVlodgi 

is there any trigger that can detect paint? any at all?

i would like to use this with a custom fizzler that will become a specific paint field when it detects a certain paint hitting a trigger.

**Comment by Byzarru** [comment]
No. #1107.

**Comment by TeamSpen210** [comment]
No, there isn't.
