### ISSUE TITLE
certain Art Thearpy and BTS textures should have square frames implemented

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#1278]
Add Square beams in bts where ever those yellow 2x2 textures spawn, look at the image, if possible by some coding or something, square beams should be added and embedded into the voxel where ever those 2x2 yellow gridded textures show up in BTS... this way it will match how they look in real bts in the original game...

you see those yellow padded tiled walls in the photo below, they should have square frames inserted into them automatically to make them look more like the original game along with similar textures a square frame could fit in... like the cutout tile except with no tiles on the surface and only the wall and square frame.

![preview0045](https://user-images.githubusercontent.com/11165643/32252584-650ed8c2-be6c-11e7-8072-aec24af6954d.jpg)

**Comment by Luke18033** [comment]
The only problem with this is that it would block gel. Maybe just make them non-solid.

**Comment by ZombiePwner1** [comment]
Who changed the color of the art therapy label back to yellow? it was orange for a reason.

**Comment by Luke18033** [comment]
@ZombiePwner1 I changed it to yellow. Why should it be orange, all of the other style labels are yellow.

**Comment by ZombiePwner1** [comment]
@Luke18033 It's orange because it's in developement and i will change it to yellow when it's released.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed and art therapy isn't really being developed right now
