### ISSUE TITLE
Build Art Therapy Tests in giant art therapy styled enclosure

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1279]
Build Art Therapy Tests in giant art therapy styled enclosure as seen in the photo below, this will be challenging to implement. will have to be the same way as new pit generation...

![mp_coop_2paints_1bridge0001](https://cloud.githubusercontent.com/assets/11165643/21462754/a6ef2632-c92d-11e6-816e-7bbc3db7954b.jpg)

**Comment by TeamSpen210** [comment]
That's implemented :)

**Comment by Flametusk** [comment]
How does it work?

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 - if implemented already... how does generation for this work?

**Comment by Flametusk** [comment]
Maybe it's a sky box thing? Like the bts sky boxes?

**Comment by Flametusk** [comment]
Also, what do you mean, 'new pit generation'?

**Comment by ZombiePwner1** [comment]
@Flametusk Art therapy already has it's own skybox.
