### ISSUE TITLE
new item: embedded floor button

### ISSUE THREAD

**Issue by mario2582** [BEEmod/BEE2-items#1280]
i saw this in art therapy and got a idea... embedded floor button.

![mp_coop_paint_crazy_box0000](https://cloud.githubusercontent.com/assets/11165643/21468477/0d279052-c9e1-11e6-8035-3ff10947de8d.jpg)

**Comment by Flametusk** [comment]
Maybe it could be a 'start reversed' thing on regular floor buttons? No... that wouldn't Work, as these would need to be embedded into the vowel. Also, stupid autoincorrect.

**Comment by LautaroL20** [comment]
What purpose would have this item?

**Comment by Flametusk** [comment]
It would look cool.

**Comment by Flametusk** [comment]
Just like... the monitors.

**Comment by Flametusk** [comment]
Also, is there a destroy able tracking camera item?

**Comment by LautaroL20** [comment]
Well, I was referring to a logical behavior rather than just esthetic visual.

**Comment by Byzarru** [comment]
Possibly to stop unintended solutions?

**Comment by Luke18033** [comment]
This would be added as an alternate version, like 1950s buttons. It would be embedded by default, but could be made non-embedded if needed.

**Comment by TheDarkBomber** [comment]
That was in Radelite's addons for BEE2.2.5.

**Comment by TeamSpen210** [comment]
This would also have a trigger to ensure cubes press the button always.

**Comment by Luke18033** [comment]
This is just the trigger button.
