### ISSUE TITLE
Smart Antline routing

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1281]
![image](https://cloud.githubusercontent.com/assets/22107242/21469071/57656d58-c9fd-11e6-8278-f2cb96f68cb5.png)
Why do antlines bow down like this?
They should try to make as straight a path as possible, like this:
![image](https://cloud.githubusercontent.com/assets/22107242/21469073/8addcd60-c9fd-11e6-86ca-19c3d1874f23.png)

**Comment by Flametusk** [comment]
Yes. This. Also, how do the antline magnets work?

**Comment by TeamSpen210** [comment]
Magnets are an AND gate effectively, but they let you position antlines to point at a particular position. You'll usually want to hide antlines on their input or output, then you place it near that item to direct antlines.

Unfortunately changing antline routing is rather difficult (knowing where I can move them to, doing the actual movement) so it's unlikely I'll implement stuff for that.

**Comment by Byzarru** [comment]
Would it be possible to make flat-out antline items?

**Comment by Flametusk** [comment]
Maybe. It would just be an instance, right? Or maybe it would be the little circles, that would be connected?

**Comment by Byzarru** [comment]
Something like signage that lights up and use some sort of something to determine positioning.

**Comment by Luke18033** [comment]
Something like this is already going to be implemented - see #494.

**Comment by TheDarkBomber** [comment]
@Luke18033 No it isn't.

**Comment by Luke18033** [comment]
@TheDarkBomber Yes it is. Although it was originally changing antline routing, it's now turned into "light-strip-sized antline", which is what #494 is. So this is a duplicate.

**Comment by TheDarkBomber** [comment]
It's not! Just because the same way it is performed, does not mean that the issue itself has changed!

**Comment by Byzarru** [comment]
That's about placing antlines on grating. This is about fixing antlines so they will always move in an aesthetically pleasing way and possible solutions to that problem.
