### ISSUE TITLE
Rexaura Deflector causes visible nodraw

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1283]
![20161225135627_1](https://cloud.githubusercontent.com/assets/22107242/21472690/b3ac26ee-caaa-11e6-9cb4-a182b3582632.jpg)

**Comment by Byzarru** [comment]
![20161225234128_1](https://cloud.githubusercontent.com/assets/22107242/21476233/df31202a-cafb-11e6-9a47-b959d2fbc112.jpg)
This is clean. All around issue.

**Comment by Flametusk** [comment]
It's also a duplicate. And fixed for the next release, I'm pretty sure.

**Comment by ZombiePwner1** [comment]
Actually it's not a leak it's nodraw placed under the platform.

**Comment by Byzarru** [comment]
It still needs to be fixed, this wasn't a problem in the last release. Also, @Flametusk, what is this a duplicate of?

**Comment by Flametusk** [comment]
Oh, I must have said it on the steam thing.

**Comment by TheDarkBomber** [comment]
Nodraw counts as a leak.

**Comment by TeamSpen210** [comment]
It's not a leak.

**Comment by Luke18033** [comment]
Fixed now? I've used cube deflectors recently and this want a problem.
