### ISSUE TITLE
Reflection Cube Holder

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1284]
An item like the Rexaura cube holder, but which is instead used to place Reflection Cubes in. This would be centered in the voxel. It could be used to hold Reflection Cubes in place. This would not destroy cubes when a laser was reflected.

**Comment by TeamSpen210** [comment]
What would this be really useful for?

**Comment by Luke18033** [comment]
I don't know, probably not a good idea. Although you could use it to reflect center-placed lasers.

**Comment by Luke18033** [comment]
I know. Instead, add a "Reflection Cube Pedestal" which is a 64x64x32 block with a reflection cube signage. This would still allow reflection cubes to reflect center-placed lasers, but the direction would be unrestricted. Start Enabled would increase the height to 64 units instead of 32, to allow interacting with top-placed lasers. It would have a 4-way rotation handle to determine which side the signage should go on.
