### ISSUE TITLE
Portal 1 Hole Light´s Glow Effect "Dissapear in a Mysterious Way" when placing a portal on a portalable surface

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1286]
Feel free to call me the Second Great Bee2 Bug Finder.

![20161226002902_1](https://cloud.githubusercontent.com/assets/12244376/21474778/81ed4be4-cb02-11e6-8990-18f9599c3a34.jpg)

**Comment by LautaroL20** [comment]
This happens when you place a portal on any portalable surfaces, idk if a leak could be related on this.

**Comment by LautaroL20** [comment]
But their Glow Effect returns once you walk trhough a fizzler.

**Comment by LautaroL20** [comment]
It looks like you fixed it, the glow effect is a bit smaller though.

**Comment by ZombiePwner1** [comment]
Isn't the glow effect a texture?

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Yes.
