### ISSUE TITLE
Visible "Leaks" when placing portals on floor and ceilling from the Portal 1 Entrance 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1288]
![20161226000045_1](https://cloud.githubusercontent.com/assets/12244376/21474842/4a9d2866-cb03-11e6-898e-c2e5ed953abb.jpg)

**Comment by Luke18033** [comment]
Something with the world portals, probably.

**Comment by TeamSpen210** [comment]
I dont think I can fix this (other thn removing portalable surfaces).
