### ISSUE TITLE
Aperture Tag & Mel Music Error

### ISSUE THREAD

**Issue by Alfe5** [BEEmod/BEE2-items#1291]
@TeamSpen210 I am using pr23 and I can hear the tracks from Tag and Mel perfectly fine. However, when i published my map to the workshop, no one else can hear the songs. I own Mel and Tag and they are downloaded on my computer. Any fixes?

**Comment by TheDarkBomber** [comment]
Pack them into the BSP and re-upload.

**Comment by Alfe5** [comment]
@TheDarkBomber Can you link me on how to do that?

**Comment by TheDarkBomber** [comment]
[PakRat](https://developer.valvesoftware.com/wiki/Pakrat)

**Comment by Alfe5** [comment]
How do I do it with a Peti map though?

**Comment by TheDarkBomber** [comment]
Open the published map in Portal 2, then open the Developer Console, and look at the path. That is your map, that you load with PakRat.

**Comment by Alfe5** [comment]
ok thank you

**Comment by Luke18033** [comment]
It would be quite annoying to do that for every map though. This should be fixed, but use TheDarkBomber's solution until then.

**Comment by ZombiePwner1** [comment]
You don't always need to use pakrat you can actually use bee2 itself i published custom content on one of my hammer maps using bee2

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment]
This seems to be fixed now, finally.........
