### ISSUE TITLE
Overgrown cameras can be painted with Conversion Gel?

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1296]
When a camera knocked down from above a door is put under Conversion Gel, it's texture permanently darkens. Here is a screenshot:
![camera](https://cloud.githubusercontent.com/assets/19228201/21510949/c314c5a0-cc4e-11e6-9193-034c9fd6e12d.jpg)
Objects can't even be painted with Conversion Gel, so why does this happen? And if this is intentional, the texture should get brighter, not darker.

**Comment by TeamSpen210** [comment]
I don't control this, it's part of the camera entity. Ask Valve why they even added this ability.... You can paint doors, laser relays and other things too for some reason.

**Comment by ZombiePwner1** [comment]
This goes for clean cameras aswell.
