### ISSUE TITLE
Add additional styled UI elements

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1297]
Additional UI elements should have custom textures for the various styles. These would include:
- [ ] Cracked check-boxes (Overgrown)
- [ ] Styled panels for GUI backgrounds
	- This would affect all Workshop maps, but it shouldn't be too much of an issue (things like the employee badge already do that)
- [X] Styled heart and error signs
- [ ] The New Chamber icon should show a styled chamber, instead of always Clean.
- [ ] We should also see if we can change the Community Test Chambers menu background.

**Comment by TeamSpen210** [comment]
They aren't textures - I can't put imagery there. I can change colours and text, and maybe add some additional icons to the dialog though.

**Comment by TeamSpen210** [comment]
Any suggestions for what I should add, if anything?

**Comment by Luke18033** [comment]
I don't know, although you should change more of the UI in Overgrown - cracked check-boxes, undo button hanging off the top bar (if possible). You should also try to change the GUI backgrounds to match the wall texture for the current style.

**Comment by TeamSpen210** [comment]
@HugoBDesigner made them.

**Comment by HugoBDesigner** [comment]
I also made the overgrown UI stuff (extrude buttons, timers, checkmarks, preview/undo/redo/play buttons, etc), but if you have any suggestions on changes, improvements or new textures, feel free to let me know!

**Comment by Endermage77** [comment]
Say Luke18033, does all of this striking-out of every single mention of the PMP imply that you've abandoned the project idea entirely, now?

**Comment by Luke18033** [comment]
Yep, I won't be making it for various reasons. Join the [Discord](https://discord.me/beemod), we can discuss it there.

**Comment by Luke18033** [comment]
Superseded by newer issues
