### ISSUE TITLE
Use Rectangular Blue Recessed Lights for White P1 Light Strips

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1299]
Square and Hole lights only makes the wall chekered when placed on Metal Walls, but on White Walls they doesn´t do the same:

![20161227221526_1](https://cloud.githubusercontent.com/assets/12244376/21511658/1302656c-cc82-11e6-96d6-1fb9aaa10c9b.jpg)

**Comment by TeamSpen210** [comment]
Portal 1 doesn't actually have smaller grid sizes for the walls (only floor textures).

**Comment by LautaroL20** [comment]
Well, the P1 Metal wallls becomes checkered when placing the small hole light, and the hole light isn´t smaller than the chekered portion where the light is placed.

**Comment by TeamSpen210** [comment]
I meant for white/concrete walls. I'd have to reuse floor textures, which wouldn't look that good. I should make the recessed lights at the base of white rooms instead for light strips on white walls.

**Comment by ZombiePwner1** [comment]
@LautaroL20 P1 concrete textures don't have a checkered variant for the wall.

**Comment by ZombiePwner1** [comment]
Light strips look wrong on concrete walls.

**Comment by Luke18033** [comment]
This would now be fixed with the addition of a 4x4 white wall texture.
