### ISSUE TITLE
Deadly Goo at the bottom of Enrichment Spheres doesn't kill the player

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1303]

**Comment by ZombiePwner1** [comment]
@Luke18033 That's because you were in the goo long enough the goo has been coded to kill you if you stay underwater for long enough.

**Comment by Luke18033** [comment]
Why would they do that? There's always an instant-kill trigger.

**Comment by ZombiePwner1** [comment]
I know that but i've played around with water in portal 2 before and if you stay in it long enough you will start to drown.

**Comment by Luke18033** [comment]
Did it instant-kill you, or slowly damage you? If it slowly damages you, that's probably a leftover from previous games that actually had swimmable water. I got killed instantly, and only when going near the bottom - if I stayed above or near the surface I wouldn't die.

**Comment by ZombiePwner1** [comment]
It slowly damages you if you stay underwater long enough.

**Comment by Luke18033** [comment]
That's not what happened to me.

**Comment by ZombiePwner1** [comment]
Try it in aperture tag after escaping the ALSSER there is swimmable water and stay underwater.

You will start to drown after abit underwater.

**Comment by Luke18033** [comment]
I know, that's not what happened. It killed me instantly once I was deep enough.

**Comment by Luke18033** [comment]
Looks like this has been fixed now.
