### ISSUE TITLE
BEE causes TWTM to crash

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1304]
I loaded BEEMOD to TWTM and made a map in the puzzle maker with some of the BEE items. After compiling and loading, the map would crash. I did manage to find a long list of errors but I was unable to copy them. Will do if I try this again.

**Comment by Byzarru** [comment]
This is probably a BEE issue itself. Moving the discussion there.

**Comment by ZombiePwner1** [comment]
This could probably be fixed.

**Comment by TeamSpen210** [comment]
Moved to BEE2.4..

**Comment by Byzarru** [comment]
[Here.](https://github.com/BEEmod/BEE2.4/issues/461)
