### ISSUE TITLE
Overgrown SP Entry 2: Worldportal behind player isn't open when starting at entry door.

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1308]
![20161230202150_1](https://cloud.githubusercontent.com/assets/19228201/21575796/4fabc60e-cece-11e6-88a3-9dcbdcc2c058.jpg)

**Comment by ZombiePwner1** [comment]
Most likely a leak.

**Comment by Luke18033** [comment]
No, it has to do with the world portals.
