### ISSUE TITLE
Allow Catwalks to be placed on Goo and Barriers

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1309]
The title says it all

**Comment by Byzarru** [comment]
I suggested 'intangible scaffolds' (#1085) as an alternative to something like this (they'd look really sloppy on grating and glass; it'd be helpful to allow catwalks on goo though), but catwalks should definitely be able to be placed on the 1/4 wall.

**Comment by Luke18033** [comment]
To allow them on the 1/4 wall, they would also have to be allowed on glass and gratings.

**Comment by Luke18033** [comment]
It turns out they can already do this, it's just glitchy.
