### ISSUE TITLE
Add indentations for drawbridges

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1315]
![20170101125618_1](https://cloud.githubusercontent.com/assets/22107242/21583002/9ea16b00-d032-11e6-8e1e-e7051faa5964.jpg)
Drawbridges look unnatural, like they are just stuck on the wall rather than a deliberate part of the puzzle. The half-panel size area the drawbridge connects to should be recessed (like angled panels).

**Comment by TheDarkBomber** [comment]
New Item: Embedded Angled Panel

**Comment by Byzarru** [comment]
It still looks unnatural. Even without embedding, an overlay would suffice.
