### ISSUE TITLE
Add corner slopes

### ISSUE THREAD

**Issue by Flametusk** [BEEmod/BEE2-items#1317]
There would be two variants: Inside corner and outside corner, and with the three angles. It would be useful if someone wanted to create, say, a pyramid.

**Comment by TeamSpen210** [comment]
Inside corners can be made with two Angled Blocks already, but outside corners are desirable.

**Comment by libbybapa** [comment]
Thumbs UP!  I've wanted this for a while.

**Comment by Luke18033** [comment]
You can make inside corners, but the textures collide on the back.
![20170113163804_1](https://cloud.githubusercontent.com/assets/19228201/21950470/fa0e71fa-d9af-11e6-9128-e24fca0b0bc5.jpg)
You should add compiler logic to detect Angled Blocks placed like this, and replace one of the textures with nodraw.

**Comment by libbybapa** [comment]
I was going to bring that up as an Issue.  It shows up in 'Clean'.  I don't think it is an issue with 'Original Clean' because all textures for wall are the same.  That texture overlap occurs with the 1/4 wall also.

**Comment by TeamSpen210** [comment]
What I need to do is ensure surfaces in the same block facing the same direction get the same random texture chosen. Then they're both the same, and nothing will be problematic?
