### ISSUE TITLE
Portal Magnet Enhancement

### ISSUE THREAD

**Issue by libbybapa** [BEEmod/BEE2-items#1318]
There have been a couple times when I had a portalable surface in the floor and I wanted to add a portal magnet that would center the portal but allow more than one angle.  Most notably under a light bridge where I wanted both the light bridge at the top and the light bridge at the bottom at different times in the puzzle.  I was wondering if it would be possible to modify the magnet tool so that you could stack them on the floor rotated at the 4 different angles and it would open the portal magnet in the orientation that most closely matched the angle the player was shooting from?  Alternatively would it be possible to add 'start reversed' or the like in order to enable the centered portals but oriented 180° apart depending on where the player was shooting from?

**Comment by Byzarru** [comment]
Additionally, there should be portal magnet capability for off-centered targets (like when there are half and two-third size panels, or voxel wide portalable spaces not centered on-voxel).

**Comment by TeamSpen210** [comment]
I can't do that, but I can add a checkbox which unlocks the rotation completely, so they can be placed in any orientation (but at one position).

**Comment by libbybapa** [comment]
Big thumbs UP for this also.  I think that this will work for the option of portals 180° apart on the floor that I requested simply by making the portalable surface 1/2 voxel by 1 voxel.  Thanks!  :)
