### ISSUE TITLE
BEE2.4 Geometry Build Error

### ISSUE THREAD

**Issue by FriskRD** [BEEmod/BEE2-items#1320]
Hi, i have a problem rebuilding the tests.When i click/press F6 it's not completing the geometry bar.Can anyone help me?

**Comment by TeamSpen210** [comment]
Open the developer console, and copy-paste the red error message that appears here.

**Comment by FriskRD** [comment]
ok

**Comment by FriskRD** [comment]
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr23 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Games/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Games/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Using random SP Entry (6)
[INFO] vbsp.mod_entryexit(): Using random SP Exit (4)
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (22 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "ITEM_BEE2_FIZZLER_OUT_RELAY" not a valid item!
[INFO] cond.core.res_goo_debris(): GooDebris: 0/0 locations
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: RAND
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 1/6 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "ENTRY_GEN_ANIMAL_KING"
 | 	"Choreo" "npc/announcer/prehub46.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "EXIT_GEN_TECH_DIFF"
 | 	"Choreo" "ann_apoc/exit_tech_diff.vmf"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 2/4 quotes..
[INFO] voiceLine.add_voice(): 2 Mid quotes
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CUBE_BUTTON_TESTING"
 | 	"Target" "@cube_picked_up"
 | 	"Choreo" "npc/announcer/prehub11.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CUBE_FIZZLE"
 | 	"Target" "@cube_fizzled"
 | 	"Choreo" "npc/announcer/testchamber09.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['floorbutton', 'buttonacceptscube', 'cubedropperstandard', 'buttonacceptsball', 'weightedbutton', 'cubedropper', 'cubestandard', 'spawn_dual', 'cube']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=4424, misses=311, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'multiversecave': True, 'rexcubepelletfizzle': False, 'nomidvoices': False, 'fixfizzlerbump': False, 'allowgoomist': True, 'bee_show_trigger': False, 'bee2_goo_debris': True, 'unlockdefault': False}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/over/global_ents.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_4.vmf', 'instances/BEE2/over/items/cube/cache_box.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/base.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_on.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_rusty.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_rusty_on.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/on_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/on_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/triple_wallpipe_nocull.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/catwalk_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator_corner.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator_corner.vtf"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_stair_128.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_32b.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_end_cap.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/walkway_destroyed_64a.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/metal_box_rusty.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_overgrown/wrecked_dropper_128.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/triple_wallpipe_nocull/straight_c.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/change_models.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_rand.nut"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/screens/elevator_video_overlay1.vmt" as "materials/BEE2/overgrown/lightboard_overlay.vmt"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Games\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Games/Portal 2/portal2/" "C:/Program Files (x86)/Games/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Can't find steam.dll relative to executable path: C:\Program Files (x86)\Games\Portal 2\bin.
 | Valve Software - vbsp.exe (May 30 2013)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Games\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Games/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/over/elevator_sp/elevator_exit/exit_stairs.vmf
 | 
 |_

[ERROR] vbsp.run_vbsp(): VBSP failed! (1)


NSIS unpaused the game
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Games/Portal 2/portal2/puzzles\76561197960408296\autosave.p2c

**Comment by TeamSpen210** [comment]
Oh, you need to select the 3rd Overgrown exit in the compile pane, I broke theothers.

**Comment by FriskRD** [comment]
ok thanks ^_^

**Comment by FriskRD** [comment]
anyway... is there another way? i don't want the same exit on all chambers.

**Comment by TeamSpen210** [comment]
Go to C:/Program Files (x86)/Games/Portal 2/sdk_content\maps\instances/bee2/over/elevator_sp/elevator_exit/`, and rename `exit_stair.vmf` to `exit_stairs.vmf`.

**Comment by FriskRD** [comment]
ok.anyway now i discovered a new problem.after getting the cube on button,it opens the door.but when i get it off,the door not closes.

**Comment by FriskRD** [comment]
the vmf modifing didn't work...it again don't complete geometry.

**Comment by LautaroL20** [comment]
Do not forget to put the modified instance´s name inside the overgrown´s package, so you don´t lose it after exporting again with beemod.

**Comment by Luke18033** [comment]
@FriskRD That's another issue with the door not closing. Add another door in front (with the Door item), and set the actual door to start open. Connect all of your inputs to the "fake" door. It won't look as nice, but it's the best option.

Alternatively, you can get the development version (see the README) - this has both of these issues fixed. However, you may experience other issues while using this.

**Comment by FriskRD** [comment]
did'n mork LautaroL20

**Comment by LautaroL20** [comment]
@FriskRD - Well, this will be fixed with the pre-release 24 that shoudn´t take long to come out...
