### ISSUE TITLE
Unlock default items causes disappearing Exit door

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1321]
I can't reliably replicate this issue, but it has been a problem for me since at least PR22. I have "unlock default items" enabled. The exit door will randomly remove itself from a map after restarting Portal 2. The map compiles just fine and the door can be replaced without issue.

**Comment by Luke18033** [comment]
I've never had this problem.

**Comment by Luke18033** [comment]
I have had something similar though, where the exit door will randomly disappear when changing chamber geometry (+/-).

**Comment by Byzarru** [comment]
I usually remove the observation rooms, if that helps.

**Comment by Luke18033** [comment]
Oh, I usually copy the observation rooms.

**Comment by LautaroL20** [comment]
@Byzarru - Are you having this issue into the Editor?

**Comment by Byzarru** [comment]
What do you mean? I'll have this issue after restarting Portal 2 and opening the editor, but not while I'm in the editor.

**Comment by LautaroL20** [comment]
Well, ill take a look into this after finish some editor models and meshes.

**Comment by Luke18033** [comment]
I just had this problem, it was even causing leaks in my map...

It's likely a Valve bug though, since the exit door was never intended to be copyable or deletable.

**Comment by Luke18033** [comment]
@Byzarru - Do you experience this issue in single player maps? I've never had this problem until now, when I happened to be making my first BEE2 Co-op map.

**Comment by Byzarru** [comment]
I only make single player maps!

**Comment by Luke18033** [comment]
Aright, so that means this is an issue on both modes.

**Comment by TeamSpen210** [comment]
When you unlock default items, it makes the door deleteable. That's what happens if you box-select and press +/-.

**Comment by Luke18033** [comment]
That would explain my other issue, but what about the other bug? I keep the exit door in a separate room until I need it. Sometimes, when reloading the map, the door will disappear. I only have this issue in Co-op maps, but @Byzarru says otherwise.

**Comment by TeamSpen210** [comment]
I'm not sure about that, other than a bug in the game code. Maybe keep the stylevar off unless you need it.

**Comment by Luke18033** [comment]
That's the thing, I usually do need it to have more than one large observation room.

**Comment by Luke18033** [comment]
Not really an actual issue, this is the exact reason unlock default items is a stylevar.

**Comment by Konclan** [comment]
I've had this very rarely but it does happen, no clue what causes it.

**Comment by Luke18033** [comment]
It would be a Valve bug, if anything.
