### ISSUE TITLE
3x1 centered large observation room

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1322]
A variant of the large observation room centered in between two voxels. This would have the embed space of a small observation room.

**Comment by Byzarru** [comment]
Redundant if #1165 is implemented.

**Comment by Luke18033** [comment]
No, that would always have to be aligned to the voxel grid. This item would be like the large observation room, but offset by 64 units.

**Comment by Byzarru** [comment]
Ah, I didn't see the title.

**Comment by TheDarkBomber** [comment]
What about a brighter observation room?

**Comment by Flametusk** [comment]
That also sounds like a good idea. Oh! And how about a modular observation room! It has the same collision area as the faith plate! And it can go on floors or ceilings as well!

**Comment by TheDarkBomber** [comment]
Ok!

**Comment by Byzarru** [comment]
Really, the entire build-a-room should have this kind of setup with room sizes and brightness.

**Comment by Luke18033** [comment]
This would be implemented with resizeable observation rooms (you'd be able to combine a 128x128 room and two 64x128 rooms to make this)
