### ISSUE TITLE
Cube Dropper compile failure

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1323]
Looks like something with the Cube Colorizer. What does that even do?
```
[ERROR] cond.core.check_all(): Error in condition:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 463, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 348, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 515, in check_flag
ValueError: "coloredcube" is not a valid condition flag!


```

**Comment by TeamSpen210** [comment]
It lets you colour cubes, so they have a coloured stripe on them to make it possible to tell different droppers and cubes apart (for puzzles where you need to fizzle cubes strategically).

**Comment by Luke18033** [comment]
But what if I don't want that? The puzzle only has 1 cube.

**Comment by TeamSpen210** [comment]
It only does something when you have that item attached to the cube - except that your compiler version doesn't have the code for it, so it errors out.
