### ISSUE TITLE
Cube Painter

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1325]
A variant of the Cube Cleaner which paints cubes instead of cleaning them. This would use button type:

- Weighted = Cleansing Gel
- Cube = Repulsion Gel
- Sphere = Propulsion Gel

**Comment by ZombiePwner1** [comment]
Perhaps a gel type property can be added to the cube cleaner

**Comment by ZombiePwner1** [comment]
But i don't see the point of this since all you can do is paint cubes and there really isn't a need for painting cubes otherside from cleaning them.

**Comment by TeamSpen210** [comment]
It would just be for painting Bounce/Speed Gel, Conversion Gel just cleans cubes. Reflection Gel can paint cubes, but that's a leftover from the Adhesion Gel code.

**Comment by Luke18033** [comment]
Have Button Type on the Cube Cleaner. Standard is Repulsion Gel, Cube is Propulsion Gel, and Sphere is Cleansing Gel.

**Comment by Endermage77** [comment]
Cube painters are a lot tidier than using a whole dropper for the sole purpose of painting cubes.
