### ISSUE TITLE
Funnel Music does not sync with base track

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1326]
This is my code:
```
"Music"
{
"ID" "ZACK_EXURBIA_CONTINUE_B"
"Name" "Continue to Next Level Outro with Funnel"
"ShortName" "Next Level B"
"Group" "Exurb1a"
"Icon" "music/p1/self_esteem_fund.png"
"Authors" "Exurb1a"
"Description" "Continue to Next Level Outro by Exurb1a with funnel track"
"Loop_Len" "1:50"
"Sample" "p1/self_esteem_fund.ogg"
"SoundScript"
{
"Base" "BEE2/music/p1/continue.mp3"
"tBeam" "BEE2/music/p1/mustest.mp3"
}
"Pack" "BEE2/music/p1/continue.mp3"
"Pack" "BEE2/music/p1/mustest.mp3"
}
```
The tbeam music is the same length as the base (it's a pitched down version of the original) but does not line up with the base while playing. Additionally, the tractor beam music does not loop.

**Comment by TeamSpen210** [comment]
You can't use an MP3 and have it loop - that's the issue. You have to make it a WAV.

**Comment by Byzarru** [comment]
Blah... Will it align as well or do I need some more package trickery?

**Comment by Byzarru** [comment]
This issue's not over. Will it align, or what do I need to do to make it so?

**Comment by TeamSpen210** [comment]
It should align correctly, you might want to make both WAVs to be sure (and give them looping points).

**Comment by Byzarru** [comment]
How would that be implemented with the tbeam track? Currently, as it is, the base track will loop (is the issue in having tractor beam and gel music being an mp3?) but not the tractor beam music. When I enter a tractor beam, the music starts from a random point and continues normally.

**Comment by TeamSpen210** [comment]
Looping points are set as an [option](https://developer.valvesoftware.com/wiki/Looping_a_Sound) inside the WAV file itself (which MP3s can't do). Usually you put the start and end to cover the entire sound, but you don't have to - piston movement sounds for example have the loop start in a bit, so they play a start portion once then loop the rest of the sound.

For MP3s I do a trick to make them loop - The `loop_len` value tells the compiler the length of the track, and then after that time is elapsed logic in the map re-triggers the sound to play again. I can't do that for gel or funnel music though. I do need to double check how I implemented those - it may or may not be set to start them at a random point, if so I need to add an option to make tbeam music match the base track.

**Comment by Byzarru** [comment]
Then there should be mp3 capability, too. WAV is nifty for snippets, but mp3 uses less space and is more useful for music tracks (compare 1.69 MB for a mp3 and 18.7 MB for a WAV with the same music content).

**Comment by TeamSpen210** [comment]
That's something you'll need to take up with Valve. I think you can compress WAVs a bit though.

**Comment by TeamSpen210** [comment]
In the `SoundScript` block, add a `sync_funnel` option set to `1`, and that will make it sync in the next version.
