### ISSUE TITLE
Implement Portal Stories: Mel BSOD elevator video.

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1327]
This is slightly different than the BSOD in the vanilla game, as it has different text. This would be better for Overgrown tests, while the vanilla BSOD is better for Wheatley tests.

**Comment by Byzarru** [comment]
And PS:Mel menu videos, too, if they are in the proper format.

**Comment by TeamSpen210** [comment]
Unfortunately, you can't pack video into maps.

**Comment by Luke18033** [comment]
:(

**Comment by Luke18033** [comment]
Couldn't you implement this as a custom animated model, which gets generated over the screens?

**Comment by TeamSpen210** [comment]
It'd just be a texture, which could work for this specific video but not others. The difficulty is that I'd need to special-case add this video, and you'd only have one on the list. It'd be a bit odd.
