### ISSUE TITLE
New style: Outside

### ISSUE THREAD

**Issue by Flametusk** [BEEmod/BEE2-items#1329]
The sky box would be the sky, and There would be cliffs and stuff maybe?

**Comment by ZombiePwner1** [comment]
I don't think it's possible to generate cliffs in the PeTi

**Comment by ZombiePwner1** [comment]
And how would an outside style work? there would need to be bumpy ground which will make it more realistic but the problem is the PeTi needs to be flat.

**Comment by Flametusk** [comment]
...The sloped blocks?

**Comment by ZombiePwner1** [comment]
The sloped blocks wouldn't look very nice for cliffs

**Comment by Flametusk** [comment]
Maybe the same way that the textures are done?

**Comment by ZombiePwner1** [comment]
Afraid that won't work either.

**Comment by ZombiePwner1** [comment]
i will close this for now until spencer takes a look.

**Comment by Flametusk** [comment]
Then I have no idea. Maybe just a very overgrown area, also using some old aperture textures,  with the sky showing? As a sky box?

**Comment by ZombiePwner1** [comment]
Having a mix of overgrown and old aperture textures wouldn't feel right. And it can break the style between them.

**Comment by TheDarkBomber** [comment]
Still needs the `New Style` label.

**Comment by LautaroL20** [comment]
> ZombiePwner1 Said: "i will close this for now until Spencer takes a look."

Why did you close the issue? He didn´t replied yet...

**Comment by Luke18033** [comment]
This isn't a style that really works in the puzzlemaker.
