### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1330]
Moved from BenVlodgi/BEE2.4#465

From @G3neralGrant:

I have some suggestions.
- [x] cool light strip.
- [ ] ~~combine all light strips (like square lights).~~ (Not possible)
- [ ] ~~Tractor beam picture half blue and half orange.~~ (Not really necessary)
- [ ] deadly goo and deadly pit separate items and combine them (place deadly goo and have it not turn into a pit). (Making them separate items is possible, but combining them is not.)
- [ ] ~~combine reflection gel with the other gels.~~ (Not possible)
- [ ] ~~combine compressed smoke field, force deflection field, and matter inquisition field.~~ (Not possible)
- [ ] ~~combine death fizzler with fizzler and laser field.~~ (Not possible, but this is kind of already done)
- [ ] ~~combine all unstationary scaffold items.~~ (Not possible)
- [ ] ~~combine laser catcher and laser relay.~~ (Not possible)
- [ ] ~~combine turret and rocket turret.~~ (Not possible)
- [x] make ditch picture not sphere button picture.
- [ ] add spinney blade wall/floor. (Already being done via #95)
- [x] make cooperative spawn room picture not a cube dropper.
- [ ] make able to move square lights around on the surface its on like light strips.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Has made the cool light strip already so that can be checked off.

**Comment by Byzarru** [comment]
Shredder (Spinny Blade Wall) is going to be ported from TSpen addons.

**Comment by Byzarru** [comment]
There needs to be a "Moved from BEE2.4" label, there's a bunch of this kind of issue.

**Comment by Luke18033** [comment]
- Cool light strip is in development and will likely be included in the next release.
- Combining the light strips would be nice, not sure if it would work quite right though. (Button Type is only possible on items with the floor button class.)
- Tractor beam doesn't need a combined icon, those are only for items with a "type" option like Button Type.
- Bottomless pit as a separate item would be nice.
- Reflection gel can't be combined with the other gels.
- That wouldn't be possible. Button Type can only be added to the button class, but fizzler logic only works with the fizzler class.
- Death Fizzler or Paint Fizzler could be added to Laserfield/Fizzler with Start Reversed. Button Type couldn't be used, see above.
- Unstationary Scaffold items couldn't be combined. The Piston Emitter uses the piston platform class, which can't have Button Type.
- Laser Catcher and Laser Relay might be able to be combined.
- Turret and Rocket Turret might be able to be combined.
- A proper Ditch icon would be nice.
- Shredder will be ported from tspenAddons, see #95.
- Cooperative spawn room doesn't really need a proper icon.
- Square lights should be able to have an 8-direction handle added.

**Comment by ZombiePwner1** [comment]
@Luke18033 I just said @LautaroL20 Made the cool light strip it's already finished and i think he will include it in the next release.

**Comment by TeamSpen210** [comment]
None of the combinations are possible.

**Comment by Luke18033** [comment]
Even the light strips?

**Comment by TeamSpen210** [comment]
No, it breaks collisions.

**Comment by Luke18033** [comment]
How?

**Comment by TeamSpen210** [comment]
The item doesn't occupy any space in the editor.

**Comment by Luke18033** [comment]
Why does that happen? Does light strip-sized collision only work with the light strip class? And who cares about collisions anyway? It's just more invalid positions.

**Comment by Endermage77** [comment]
Then what kind of light would it be if it were both Enabled and Reversed?

**Comment by LautaroL20** [comment]
@Endermage77 - Indeed, that would be pretty unintuitive. Anyways i am pretty sure many of us are using my cold light strip alonside the warm and neutral ones in one item under "ButtonType".

**Comment by Endermage77** [comment]
Perhaps it could be a negative-brightness light of some sort?

**Comment by Luke18033** [comment]
@TeamSpen210 - Couldn't you combine the laser items by switching them to the button class? It's only the item type which makes the 5-position handle work and the class doesn't matter, right?

**Comment by TeamSpen210** [comment]
I don't know, but also you'd lose the laser's beam preview effect. Additionally it'd break all existing maps with those items.

**Comment by Luke18033** [comment]
Most of these are invalid or already implemented
