### ISSUE TITLE
Bottomless pit will finish ?

### ISSUE THREAD

**Issue by love-portal** [BEEmod/BEE2-items#1332]
Bottomless pit will finish ?

**Comment by LautaroL20** [comment]
Yep :)

**Comment by TheDarkBomber** [comment]
Needs `Skybox` label.

**Comment by LautaroL20** [comment]
@TheDarkBomber - Well, i didn´t delete it, idk why its not anymore, someone else must deleted it....

**Comment by TheDarkBomber** [comment]
[It exists](https://github.com/BEEmod/BEE2-items/labels/Skybox)
