### ISSUE TITLE
128-unit extending panel

### ISSUE THREAD

**Issue by love-portal** [BEEmod/BEE2-items#1333]
![maxresdefault](https://cloud.githubusercontent.com/assets/24913073/21640835/e33061ce-d288-11e6-9188-c245f1a3d23a.jpg)
panel that will climb to 1 cubic

**Comment by Luke18033** [comment]
This is a good idea, although Portalable Piston Platform from tspenAddons (#95) will be usable for this same purpose. The panel arms definitely look better though.

**Comment by Luke18033** [comment]
What would be a better idea is to have a 2x2 of panels, with a configurable height via piston platform logic. Inputs would allow it to change between heights.

**Comment by Luke18033** [comment]
Not really any different than a piston platform
