### ISSUE TITLE
BEE2.4 Doesn't execute in MAC OSX

### ISSUE THREAD

**Issue by Kenkenkon** [BEEmod/BEE2-items#1334]
(Duplicate of #1313, but it was closed because I've missed the name (i think))
I put all the packages inside BEE2 Folder, but when I run the application, a console message appears, saying that there's an image missing.

**Comment by LautaroL20** [comment]
Could you upload a screen showing the full bug message? It would be helpful to identify the cause.

**Comment by Luke18033** [comment]
Moved to BEEmod/BEE2.4#466.

**Comment by Kenkenkon** [comment]
@LautaroL20 As this was moved, Im posting the image there.
