### ISSUE TITLE
Protruding Pedestal Editor Models needs their base - I tried arranging it and finally got it working :)

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1335]
I FIXED IT >:D 

![20170109143434_1](https://cloud.githubusercontent.com/assets/12244376/21776447/4a630e84-d679-11e6-9626-0f506ad6fdde.jpg)

**Comment by TheDarkBomber** [comment]
Yes, the main issue is the colour of the pedestal button! Not the fact that the base is far away from the pedestal button, making it look like it's floating! Also `Development Version` label needed!

**Comment by LautaroL20** [comment]
@TheDarkBomber - You clearly didn´t understand what i meant, i said the main issue is the button becoming off-colour because im pretty sure ill find a way to get the block on the right position.......

**Comment by TheDarkBomber** [comment]
Main issue currently is the base.

**Comment by LautaroL20** [comment]
Thats your point of view, but actually i think its harder to find out the reason of pedestal model becoming grayish when i link the base to it on Blender.

**Comment by TeamSpen210** [comment]
It's because of 'smoothing groups', blender when importing makes all the surfaces join together. Go to the wrench icon on the model, choose 'add modifier', and add 'edge split'. Adjust the angle so curved surfaces join, but actual corners don't.

**Comment by LautaroL20** [comment]
That fixed the base´s position, but the pedestal model remains graysh / displaying wrong shadows.

**Comment by LautaroL20** [comment]
This is because the base must be done separately from the pedestal model. It looks like when you try to connect standalone models in one piece, weird things happens like shadow problems in this case. Anyways im solving this on Autodesk 3ds max for now.

**Comment by LautaroL20** [comment]
Finally, this looks really fine, isnt it?

![20170109143434_1](https://cloud.githubusercontent.com/assets/12244376/21776447/4a630e84-d679-11e6-9626-0f506ad6fdde.jpg)

**Comment by TheDarkBomber** [comment]
🎉 Congratulations! 🎉
