### ISSUE TITLE
Gravity wall

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1336]
This is seen in Portal: Prelude.
![20170105151600_1](https://cloud.githubusercontent.com/assets/19228201/21701350/fa69d9ca-d359-11e6-8413-a3d686f8a409.jpg)
- This would be placed like the cutout tile, by placing two corners and connecting them.
- It wouldn't collide or embed, it's just a red border added to the edges of wall sections. Additionally, it wouldn't work correctly since it is sized with connections.
- It wouldn't be placeable on the floor - it would have no use being there. It would be placeable on the ceiling, however.
- Placing multiple Gravity Walls next to each other would make them join into one, allowing for oddly-shaped gravity walls.

**Comment by Byzarru** [comment]
And TWTM (at least the buttons are antigravity).

**Comment by Luke18033** [comment]
For that, you would place the gravity wall over the button.

**Comment by Byzarru** [comment]
There's also a gravity item in Blue portals, which might be a better testing implementation of the concept.

**Comment by Byzarru** [comment]
Also, at least here there is an indication of the anti-gravity feature while TWTM had none.

**Comment by Luke18033** [comment]
Blue Portals has magnets, which are similar but not the same. The old Portal: Project Beta had a reverse-gravity chamber though, which probably used something similar to this.

**Comment by Luke18033** [comment]
Portal: Project-Beta gravity ceiling:
![20170105182038_1](https://cloud.githubusercontent.com/assets/19228201/21705260/c630da5e-d373-11e6-9d3e-f6042135c938.jpg)

**Comment by ellingtonvengaboysmuseum** [comment]
Can't be done in standard hammer without complex coding...

**Comment by Byzarru** [comment]
When I see this I'm thinking of the worldportal system most hammer maps (that I've seen) use, and that's not practical for PTI.

**Comment by TheDarkBomber** [comment]
Maybe you would like the Adhesion Wall from Timex?

**Comment by TheDarkBomber** [comment]
@Byzarru [Your wish will be granted](https://github.com/TheDarkBomber/BEE2-items-TheDarkBomber-Contributions/tree/bluePortals)

**Comment by Luke18033** [comment]
But is the gravity wall also being added? Because I would like to see that in BEE2.4.

**Comment by Luke18033** [comment]
@Byzarru The only worldportals that have been confirmed are Worldportal Doors from tspenAddons, on #95. Those can't be used for gravity-changing, at least not in the way that I would like. I did open an issue for a resizeable worldportal, but it hasn't been confirmed.

**Comment by Konclan** [comment]
Why can't there just be a gate world portal that's always open

**Comment by Luke18033** [comment]
According to the Portal Wiki, this is called the "Localized Gravitational Field".

**Comment by Luke18033** [comment]
Another reason why worldportals wouldn't work is the 4-portal limit - you wouldn't be able to have any gravity zones in Co-op.

**Comment by Luke18033** [comment]
Since we can now pack particles, if this gets implemented I'd recommend adding some particles to indicate the volume it affects. Maybe something similar to fizzler particles, but red and not as densely packed, and moving in the direction of the gravity.

**Comment by Konclan** [comment]
UCP
