### ISSUE TITLE
Remove radios from P1 corridors

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1338]
Radios appear in most, if not all, of the P1 exit corridors. While they are a nice touch, their appeal is quickly lost. As such, radios should be an option rather than a default 'easter egg'.

**Comment by TeamSpen210** [comment]
They're there originally because Carl wasn't able to pack custom content, and so that's the only P1 music available in Portal 2.

**Comment by Byzarru** [comment]
They're really out of place.

**Comment by Luke18033** [comment]
Why not just get rid of them entirely? They're really not necessary, except maybe for the ERV.

**Comment by Byzarru** [comment]
They make a fun easter egg, but they'd probably be better suited as a user-placeable item to be abused at the user's discretion.

**Comment by Byzarru** [comment]
New item: Radio

**Comment by Luke18033** [comment]
This isn't going to be a stylevar by the looks of things.
