### ISSUE TITLE
Embed 1970s Buttons

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1339]
1970s Floor Buttons aren't embedded in BEE2.4 maps, but they are in the original game. Screenshot from a 1970s map (`sp_a3_speed_flings`):
![20170106092240_1](https://cloud.githubusercontent.com/assets/19228201/21726520/dd501104-d3f1-11e6-8d1c-ffb6609d53bc.jpg)
Screenshot from a BEE2.4 map:
![20170106110330_1](https://cloud.githubusercontent.com/assets/19228201/21729444/f8d7f3e8-d3ff-11e6-959d-9a6e862bf143.jpg)

**Comment by TheDarkBomber** [comment]
Compare with screenshot from BEE2.4 70s

**Comment by Luke18033** [comment]
Updated original post

**Comment by TeamSpen210** [comment]
That's `sp_a3_bomb_flings`, and it's a bit inconsistent with the other map since that is on the surface. I prefer to actually have a difference.
