### ISSUE TITLE
Override vanilla cave textures with a fixed version

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1340]
I know this is a Valve bug, but couldn't you fix it for BEE2 maps using a custom texture?
![20170106094036_1](https://cloud.githubusercontent.com/assets/19228201/21727091/6854581c-d3f4-11e6-8cab-7d5918a00dd2.jpg)

**Comment by Konclan** [comment]
Turn your shader detail down to medium, it fixes it

**Comment by Luke18033** [comment]
I've tried that before, it makes Goo look terrible, at least in Aperture Tag.

**Comment by TheDarkBomber** [comment]
Turn your goo usage down, it fixes it.

**Comment by Luke18033** [comment]
No, I'm referring to Goo in the campaign. I can't control how much goo is used in those, without decompiling the maps.

**Comment by TeamSpen210** [comment]
It's fixed in BEE2.4, check the 80s shaft.

**Comment by Luke18033** [comment]
Well I should have checked an actual BEE2 map before posting this...

**Comment by Byzarru** [comment]
BEE2.4: The mod that lets you use new items in the puzzle makers and makes cave walls look good!
