### ISSUE TITLE
Don't make monitor extend until you look at it

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1342]
~~This would toggle the monitor on and off. In Clean style, it would also extend/retract it into the wall. Start Enabled would also be added.~~

On Clean-like styles, Monitors wouldn't extend until you looked at them. After this point they would not retract.

**Comment by Byzarru** [comment]
Also Cameras.

**Comment by TheDarkBomber** [comment]
@Byzarru Cameras have inputs.

**Comment by TeamSpen210** [comment]
Why would you want to toggle the screen?

**Comment by Luke18033** [comment]
One way it could be useful is in a multi-chamber/multi-room map. You could have a `trigger_once` at the entrance of each chamber, to make the monitor extend out when you enter. Normally, all of them would extend out when entering the first chamber.

**Comment by TeamSpen210** [comment]
I have a better idea - make screens detect when the player can see them, and open only then. Should they close also though?

**Comment by TeamSpen210** [comment]
It feels a bit weird giving connections to a non-test device like this, and also in Old Aperture, Overgrown and BTS the monitor won't move anyway.

**Comment by TeamSpen210** [comment]
Implemented by 00d975869326835d21f640ff2258f47a0e8d1e2f
