### ISSUE TITLE
BTS Monitor Camera unstyled

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1343]
Notice the clean textures on the base.
![20170106190326_1](https://cloud.githubusercontent.com/assets/19228201/21738928/ee2a4322-d442-11e6-83d1-ed89ea30a4e4.jpg)

**Comment by Luke18033** [comment]
Shouldn't the base be using a brush template?

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
