### ISSUE TITLE
Portal 1 Stairs Antlines Issue

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1346]
I connected a button to some stairs, and this happened:
![20170106204213_1](https://cloud.githubusercontent.com/assets/19228201/21739480/bf1706d4-d450-11e6-9d41-17fbfbcf1b8a.jpg)

**Comment by TeamSpen210** [comment]
Makes sense.

**Comment by ZombiePwner1** [comment]
Illuminati confirmed.

**Comment by TheDarkBomber** [comment]
Yes, since I am a member of the [REDACTED].

**Comment by Luke18033** [comment]
Why does it make sense? The antlines don't even touch the stairs.

**Comment by TheDarkBomber** [comment]
Makes sense.

**Comment by Jadeygaming** [comment]
@Luke18033 @TeamSpen210 Was being sarcastic...

**Comment by TheDarkBomber** [comment]
@Jadeygaming Doesn't make sense.

**Comment by TeamSpen210** [comment]
Fixed by bd8db1a.
