### ISSUE TITLE
Allow barriers to anchor on other barriers

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1348]

**Comment by Luke18033** [comment]
@TeamSpen210 I tried to add this and it didn't work, is this not possible?

**Comment by Byzarru** [comment]
That's the entire point of my Intangible Scaffold idea, a 'barrier' that lets barriers and triggers attach to it. Keeping my fingers crossed that this is possible.

**Comment by TeamSpen210** [comment]
This definitely works fine, I thought this was done already. You do have to place the item initially on a block (so it places in the right or orientation), then delete the block and add the supporting barrier.

**Comment by Luke18033** [comment]
That doesn't work.
![20170107183028_1](https://cloud.githubusercontent.com/assets/19228201/21746828/02b25a30-d508-11e6-95aa-d90ff1df10ad.jpg)
Stupid Valve...

**Comment by TeamSpen210** [comment]
Works fine:
![image](https://cloud.githubusercontent.com/assets/8453732/21747167/739c6f18-d5aa-11e6-9659-5a935021563e.png)

Add `"CanAnchorOnBarriers" "1"`to the item.

**Comment by Luke18033** [comment]
I did.

**Comment by TeamSpen210** [comment]
If you put it in the right place (check the commit), the other glass will highlight blue when you try moving a glass item.

**Comment by Luke18033** [comment]
That is where I put it. The problem was that I only added it for the clean version, but was using 1980s.

**Comment by LautaroL20** [comment]
This would be nice to use when Breakable Glass comes out.

**Comment by TheDarkBomber** [comment]
Is it possible to create a non-solid barrier item, which can be used to create Floating Vactubes, without any Invalid Position errors?

**Comment by Luke18033** [comment]
That should be possible.

**Comment by TheDarkBomber** [comment]
Yes, we could make Floating Vactubes with that, maybe even Floating Catwalks.

**Comment by TeamSpen210** [comment]
It can't be non-solid, but it can be nonexistent in the compiled map.

**Comment by TheDarkBomber** [comment]
Then make it non-existant in the compiled map.

**Comment by TeamSpen210** [comment]
Set all the instances to "", that will make the compiler delete them.

**Comment by TheDarkBomber** [comment]
The name? (like `.vmf`)

**Comment by TeamSpen210** [comment]
Yes.

**Comment by TheDarkBomber** [comment]
So it could be easily created.

**Comment by libbybapa** [comment]
Big Thumbs UP for this!
