### ISSUE TITLE
Implement Motion Sensor above BTS Doors when Triggers are connected

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1350]
![20170107100445_1](https://cloud.githubusercontent.com/assets/19228201/21743925/f86bdc00-d4c0-11e6-8880-c953a9c8eccf.jpg)

**Comment by Byzarru** [comment]
~The point of triggers is that they are invisible. This should instead be a user-placeable item.~ I see what you mean.

**Comment by Luke18033** [comment]
The point of this is that it provides an explanation to what's detecting you if there's a trigger to open the door. It would probably be better to have the compiler detect if a connected trigger is in front of the door, and add the sensor on that side if it is.

**Comment by TeamSpen210** [comment]
I would like to do this, it would be nice.

**Comment by TheDarkBomber** [comment]
The point of triggers is that they are invisible. This should instead be a stylevar.

**Comment by Luke18033** [comment]
It doesn't really need to be a stylevar. It would only be generated when a trigger was placed in front of the door, and connected to it.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
