### ISSUE TITLE
Use compiler to embed light strips when possible

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1355]
This wouldn't use `EmbeddedVoxels`, it would instead use compiler logic to carve out space in the wall.

**Comment by TeamSpen210** [comment]
Um, what would that even do?

**Comment by Flametusk** [comment]
Make it so that you can have more than one light strip in the test that looks like it's from the first portal withough causing those huge appearance glitches.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Lol, i wonder the same...

**Comment by Luke18033** [comment]
@TeamSpen210 - Well, you said something about actual embedded light holes which would replace Worldportal Light Holes in a future release, so this would do exactly that.

**Comment by TeamSpen210** [comment]
When thosw are implemented, they'd replace the existing item wherever possible.

**Comment by Luke18033** [comment]
So this wouldn't be a stylevar.

**Comment by Luke18033** [comment]
You'd want to do this for all styles so they don't light the surface they're placed on.

**Comment by Luke18033** [comment]
Basically implemented with the tiling system setting the tiles to nodraw, but maybe it'd still be good to do this to prevent the light from spreading directly onto the light strip's surface?

**Comment by TeamSpen210** [comment]
That can be done with `light_spot`, except we need to manually spawn them to work around an instancing bug.

**Comment by Luke18033** [comment]
Or you can just set a target entity.
