### ISSUE TITLE
Beginning entry door glitch

### ISSUE THREAD

**Issue by TheManOfGan** [BEEmod/BEE2-items#1358]
the door glitches and i see some strange things

In between  the door  (https://cloud.githubusercontent.com/assets/24685304/21793766/1361b9e6-d6a9-11e6-8362-16886a305447.png)
looking at the door open  (https://cloud.githubusercontent.com/assets/24685304/21793778/34fc1eb6-d6a9-11e6-9840-722d7ef1b3ac.png)
looking through the door  (https://cloud.githubusercontent.com/assets/24685304/21793776/2f2329e4-d6a9-11e6-8dd8-82b9480306c3.png)

**Comment by TeamSpen210** [comment]
Which styles is his?

**Comment by G3neralGrant** [comment]
it is clean style

**Comment by Luke18033** [comment]
@TeamSpen210 Looks like Clean.

**Comment by Luke18033** [comment]
Lol, commented at the same time.

**Comment by LautaroL20** [comment]
@G3neralGrant - Thats clearly a leak somewhere, wich corridors where you using to build your map?

**Comment by G3neralGrant** [comment]
the entrance and exit are 1.Corridor

**Comment by G3neralGrant** [comment]
in any map that does this, all reflections are wierd

(https://cloud.githubusercontent.com/assets/24685304/21872557/e9065226-d81d-11e6-83fe-e86094ed4529.png)
(https://cloud.githubusercontent.com/assets/24685304/21872565/f926c212-d81d-11e6-8ee4-fa4d8ed14d31.png)
(https://cloud.githubusercontent.com/assets/24685304/21872567/fb378d5c-d81d-11e6-9183-9842488be387.png)
(https://cloud.githubusercontent.com/assets/24685304/21872569/fc8495d8-d81d-11e6-8ca5-f3d12b62d4b9.png)
(https://cloud.githubusercontent.com/assets/24685304/21872570/fdd05562-d81d-11e6-855d-5278a8c5dee3.png)

**Comment by LautaroL20** [comment]
That looks like the env_cubemaps are missing in your map, wich is pretty weird...

**Comment by ZombiePwner1** [comment]
That is very strange with the cube maps missing since your map is clean style so that doesn't make much sense with the cubemaps missing.

**Comment by Luke18033** [comment]
No idea what would be causing this leak, not really helpful.
