### ISSUE TITLE
Players can get "Stagnant Forever" when jumping on a wall placed Pedestal Button - Noclip will become your best friend...

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1359]
Noclip will become your best friend :) This happens at least in P1 Style....

________________________________________________________________________________________________

GIF:
![GIF](https://cloud.githubusercontent.com/assets/12244376/21807249/9a898d54-d71c-11e6-9b1a-426bf8932510.gif)

**Comment by ZombiePwner1** [comment]
I think this will be most likely to do with the P1 button collisons or it might be the player clip.

**Comment by LautaroL20** [comment]
Button colissions doesn´t have to do with the issue, this is probably its player clip...

**Comment by TeamSpen210** [comment]
It is a problem with the button collisions, switching the model causes this.

**Comment by ZombiePwner1** [comment]
:D i was right :D

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Ok?

**Comment by ZombiePwner1** [comment]
Look what happened when i crouched on a button.
![20170111062543_1](https://cloud.githubusercontent.com/assets/18079316/21827498/dabc8f52-d7c6-11e6-9863-d4122e85e62f.jpg)

**Comment by LautaroL20** [comment]
@ZombiePwner1 - You got stuck in a mysterious position.

**Comment by ZombiePwner1** [comment]
Very

**Comment by ZombiePwner1** [comment]
![20170111063009_1](https://cloud.githubusercontent.com/assets/18079316/21827617/73d77bb6-d7c7-11e6-8cb3-dd7bd3b5fe48.jpg)


This is how it looks in coop.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - I posted an issue related to that long time ago. Its something similar to the 70´s old ap Coop missing cubemaps.

**Comment by Luke18033** [comment]
Fixed by using a prop_dynamic
