### ISSUE TITLE
P1 Hole Lights prevent dirty tiles from generating in goo

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1360]
![20170110165012_1](https://cloud.githubusercontent.com/assets/12244376/21822407/c89b24a8-d755-11e6-9a6e-d337b9df8259.jpg)

**Comment by Luke18033** [comment]
Still an issue

**Comment by TeamSpen210** [comment]
This isn’t that easy to fix since the holes are actually a model.

**Comment by Luke18033** [comment]
I think this was more referring to the surrounding tiles, which are textures and can easily be changed

**Comment by Luke18033** [comment]
Now fixed
![image](https://user-images.githubusercontent.com/19228201/91385537-fc05ff80-e7e5-11ea-8590-687f1e873af7.png)

**Comment by LautaroL20** [comment]
It looks pretty good now!
