### ISSUE TITLE
Portal 1 cutout tiles are unstyled.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1362]
![20170111060110_1](https://cloud.githubusercontent.com/assets/18079316/21826696/7548ee7a-d7c3-11e6-81c4-bf94637c3ac1.jpg)

**Comment by Konclan** [comment]
What would portal 1 cutout tiles even be? I guess it would just be 1 square indents instead of tiles..

**Comment by ZombiePwner1** [comment]
Probably

**Comment by LautaroL20** [comment]
LOL, nice find, it looks like i wasn´t use the cutout tile for a while, thats why i didnt report this before...

**Comment by Flametusk** [comment]
I mean, why not at least have them have maybe a few tiles of the opposite colour where the cut out bits would be? Also, what exactly is the point of the cutout tiles?

**Comment by SomePeople27** [comment]
What about we can make them reveal orange glow below the floor?

**Comment by LautaroL20** [comment]
That can work.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Indeed and i'm waiting for you.

**Comment by Endermage77** [comment]
@Flametusk The purpose of cutout tiles is to make a floor that is unportalable and ungellable, as the broken-up pattern of the floor makes it impossible to lay down gel or portals.
