### ISSUE TITLE
Portal 1 protuding pedestal buttons are missing their base, and therefore they´re floating in a "Mysterious Way"

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1363]
![20170111060323_1](https://cloud.githubusercontent.com/assets/18079316/21826775/ccaea718-d7c3-11e6-9f57-427cce3ab58f.jpg)

**Comment by LautaroL20** [comment]
Id say they re floating in a mysterious way?

**Comment by Luke18033** [comment]
Duplicate of #1225.
