### ISSUE TITLE
Portal 1 camera wire spazzes out when passed through a portal.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1364]
![20170111061030_1](https://cloud.githubusercontent.com/assets/18079316/21827019/c15ee5ca-d7c4-11e6-8010-24684ed07d19.jpg)

![20170111061237_1](https://cloud.githubusercontent.com/assets/18079316/21827068/fbf91426-d7c4-11e6-9016-2b43d97f6243.jpg)

**Comment by Byzarru** [comment]
Some people just don't want to let go.

**Comment by LautaroL20** [comment]
Indeed xD...

**Comment by Luke18033** [comment]
I don't think this is fixable.
