### ISSUE TITLE
Portal 1 cubes mysteriously sink into the floor.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1365]
![20170111062013_1](https://cloud.githubusercontent.com/assets/18079316/21827324/1d0ddbb4-d7c6-11e6-9ea3-84ef8ac612c3.jpg)

**Comment by TeamSpen210** [comment]
They retain the original collisions of the Portal 2 cubes - I'll shrink the model to match.

**Comment by Konclan** [comment]
I think Alive and Kicking did this as well so cubes worked better, so this is actually great (I hated the size of portal 1 cubes too)

**Comment by Luke18033** [comment]
@Konclan Is Alive and Kicking released yet? All I've been able to find is a demo.

**Comment by Konclan** [comment]
No, I've just been looking through screenshots and such

**Comment by Konclan** [comment]
https://www.youtube.com/watch?v=w1Svcwg-vq0
