### ISSUE TITLE
Players can get "Mysteriously" stuck on P1 cubes.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1366]
![20170111062240_1](https://cloud.githubusercontent.com/assets/18079316/21827405/65a917b2-d7c6-11e6-96a4-9a40a0558cf0.jpg)

Also the P1 cubes have really glitchy collison when jumping over it.

**Comment by LautaroL20** [comment]
Lol, nice find! Does this also happens with the rest of the cubes aswell? I didnt tryied to jump on the P1 Cubes yet...

**Comment by ZombiePwner1** [comment]
This only happens with the companion and weighted cubes the sphere cubes collison is completely fine.
