### ISSUE TITLE
P1 buttons base makes a "Mysterious" glass sound when jumping on it.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1367]
![20170111062425_1](https://cloud.githubusercontent.com/assets/18079316/21827472/afb8f53e-d7c6-11e6-845c-ddb8f10a20f5.jpg)

**Comment by LautaroL20** [comment]
Im seriously start to think on calling you the Third Great Beemod Bug Finder.

**Comment by TeamSpen210** [comment]
This isn't really an error - those orange hazard lines are set by Valve to be a 'glass' material type.

**Comment by LautaroL20** [comment]
Ok, this is intentional then.
