### ISSUE TITLE
P1 Coop cubes Mysteriously turn invisible if glitched out.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1368]
![20170111063324_1](https://cloud.githubusercontent.com/assets/18079316/21827751/f0ba0536-d7c7-11e6-95ca-81619cc8b631.jpg)

Look on P-Body's screen it says pick up? wtf?

**Comment by TeamSpen210** [comment]
Well, how exactly did you do this, what did you do, can you do it again?

**Comment by ZombiePwner1** [comment]
If you pass the cube through the chamberlock door when it's closed the cube dropper will open and a invisible cube comes out and it stays like that until you pick it up.

**Comment by LautaroL20** [comment]
Thats why i always record small GIFS. I hate explaining things mostly because my english is terrible.

**Comment by TeamSpen210** [comment]
From the other issue, I figured out why this would be happening - I make the cubes invisible before they switch model, so you don't see the Portal 2 cubes for a split second. That mustn't be switching it back to visible.

**Comment by ZombiePwner1** [comment]
It's weird tho since the cube becomes visible when you pick it up.

**Comment by TeamSpen210** [comment]
That's because in Coop the held objects are 'fake', and don't replicate a lot of things with the real model. Pick up a FrankenTurret and pay attention to their heads.
