### ISSUE TITLE
Portal 1 sphere cubes mysteriously turn purple without cubemaps.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1369]
![20170111063937_1](https://cloud.githubusercontent.com/assets/18079316/21827948/cce79ca8-d7c8-11e6-91bb-6431efa56bcb.jpg)

**Comment by LautaroL20** [comment]
From now, i oficially call you the Third Great Beemod Bug Finder. Those missing cubemaps gived a nice purple effect on that ball.

**Comment by ZombiePwner1** [comment]
Strangely the ball turns normal when holding it.

![20170111064215_1](https://cloud.githubusercontent.com/assets/18079316/21828017/2b0d84a0-d7c9-11e6-89d9-73e0830f8c62.jpg)

**Comment by Byzarru** [comment]
That is how the ball appears for me in normal Portal 1... hm...

**Comment by ZombiePwner1** [comment]
@Byzarru It's missing cubemaps coop in P1 style doesn't pack cubemaps for some reason.

**Comment by Byzarru** [comment]
I'm talking about Portal 1 proper, not the style in BEE.

**Comment by ZombiePwner1** [comment]
Actually for some reason in the P1 advanced companion cube chamber i could see purple reflections on the ball.
