### ISSUE TITLE
P1 coop exit door is missing their blue lights

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1370]
![20170111064554_1](https://cloud.githubusercontent.com/assets/18079316/21828105/b30ab59e-d7c9-11e6-827e-11eab52a70d3.jpg)

**Comment by Luke18033** [comment]
What? I don't understand what the problem is.

**Comment by LautaroL20** [comment]
@Luke18033 - My friend ZombiePwner told me that the issue are the blue lights not working on the door, ill fix the title.
