### ISSUE TITLE
P1 protuding pedestal buttons are missing their P1 push sound.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1372]
![20170111065520_1](https://cloud.githubusercontent.com/assets/18079316/21828353/ffb6f3ac-d7ca-11e6-88f5-0ed72a827b02.jpg)

**Comment by LautaroL20** [comment]
I don´t think a screenshot could actually "show" the wrong song....

**Comment by ZombiePwner1** [comment]
Fixed.
