### ISSUE TITLE
P1 coop players can get stuck inside the entry door.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1373]
![20170111065742_1](https://cloud.githubusercontent.com/assets/18079316/21828418/51641270-d7cb-11e6-990c-aaf5a5be43e1.jpg)

**Comment by LautaroL20** [comment]
Well, a fix for this would be adding the same killing logic that the Piston Platform have when they decreases.

**Comment by ZombiePwner1** [comment]
The trigger to close the door is way too close.
