### ISSUE TITLE
P1 franken cubes start spazzing out in the cube dropper.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1374]
![20170111071128_1](https://cloud.githubusercontent.com/assets/18079316/21828758/449da6f8-d7cd-11e6-9f30-6c712d0613b4.jpg)

**Comment by LautaroL20** [comment]
LEL, they actually get stuck?

**Comment by ZombiePwner1** [comment]
Yes.

**Comment by LautaroL20** [comment]
:(
