### ISSUE TITLE
Overgrown compile error

### ISSUE THREAD

**Issue by G3neralGrant** [BEEmod/BEE2-items#1377]
Whenever I compile any map, even a new one that I didn't do anything to, it gives me an error.

here is what was in the console

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr23 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_GLADOS_CLEAN'}
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Using random SP Exit (4)
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 3
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (61 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "ITEM_BEE2_FIZZLER_OUT_RELAY" not a valid item!
[INFO] cond.core.res_goo_debris(): GooDebris: 0/0 locations
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] cond.core.steal_from_brush(): Steal: {'additional': (), 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x041C63B0>, <srctools.vmf.Solid object at 0x041C63D0>, <srctools.vmf.Solid object at 0x03873D70>, <srctools.vmf.Solid object at 0x03DFF830>, <srctools.vmf.Solid object at 0x03DFF850>, <srctools.vmf.Solid object at 0x03DFF050>, <srctools.vmf.Solid object at 0x03DFFCD0>, <srctools.vmf.Solid object at 0x03DFFD50>, <srctools.vmf.Solid object at 0x03DFF090>, <srctools.vmf.Solid object at 0x03DFF0D0>, <srctools.vmf.Solid object at 0x03DFF0F0>], detail=None, overlay=[], orig_ids={1259: 1259, 1260: 1260, 1261: 1261, 1241: 1241, 1391: 1391, 1382: 1382, 1319: 1319, 1320: 1320, 1321: 1321, 1322: 1322, 1323: 1323, 1324: 1324, 1201: 1201, 1202: 1202, 1203: 1203, 1204: 1204, 1205: 1205, 1206: 1206, 1207: 1207, 1208: 1208, 1209: 1209, 1210: 1210, 1211: 1211, 1212: 1212, 1213: 1213, 1214: 1214, 1215: 1215, 1216: 1216, 1217: 1217, 1218: 1218, 1219: 1219, 1220: 1220, 1383: 1383, 1251: 1251, 1238: 1238, 1239: 1239, 1240: 1240, 1380: 1380, 1242: 1242, 1243: 1243, 1381: 1381, 1250: 1250, 1379: 1379, 1252: 1252, 1253: 1253, 1254: 1254, 1255: 1255, 1384: 1384, 1385: 1385, 1386: 1386, 1387: 1387, 1388: 1388, 1389: 1389, 1390: 1390, 1393: 1393, 1392: 1392, 1256: 1256, 1394: 1394, 1395: 1395, 1396: 20, 1257: 1257, 1258: 1258}), 'rem_brush': True, 'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x043717B0>, solid=<srctools.vmf.Solid object at 0x042EAED0>, normal=Vec(0, 0, -1), color=<MAT_TYPES.white: 1>)}
[INFO] cond.core.steal_from_brush(): New IDS: {'6729': ['1319', '1384', '1390', '1205', '1210', '1215', '1220', '1255', '1261', '20', '1243']}
[INFO] cond.core.steal_from_brush(): Steal: {'additional': (), 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x03DFF130>, <srctools.vmf.Solid object at 0x03DFF150>, <srctools.vmf.Solid object at 0x03DFF170>, <srctools.vmf.Solid object at 0x03DFF190>, <srctools.vmf.Solid object at 0x03DFF1B0>, <srctools.vmf.Solid object at 0x03DFF1D0>, <srctools.vmf.Solid object at 0x03DFF070>, <srctools.vmf.Solid object at 0x03DFF0B0>, <srctools.vmf.Solid object at 0x03DFF270>, <srctools.vmf.Solid object at 0x03DFF210>, <srctools.vmf.Solid object at 0x03DFF290>], detail=None, overlay=[], orig_ids={1259: 67, 1260: 66, 1261: 65, 1241: 79, 1391: 76, 1382: 29, 1319: 21, 1320: 22, 1321: 23, 1322: 24, 1323: 25, 1324: 26, 1201: 43, 1202: 42, 1203: 41, 1204: 40, 1205: 39, 1206: 48, 1207: 47, 1208: 46, 1209: 45, 1210: 44, 1211: 53, 1212: 52, 1213: 51, 1214: 50, 1215: 49, 1216: 58, 1217: 57, 1218: 56, 1219: 55, 1220: 54, 1383: 28, 1251: 63, 1238: 82, 1239: 81, 1240: 80, 1380: 31, 1242: 78, 1243: 77, 1381: 30, 1250: 64, 1379: 32, 1252: 62, 1253: 61, 1254: 60, 1255: 59, 1384: 27, 1385: 38, 1386: 37, 1387: 36, 1388: 35, 1389: 34, 1390: 33, 1393: 74, 1392: 75, 1256: 70, 1394: 73, 1395: 72, 1396: 71, 1257: 69, 1258: 68}), 'rem_brush': True, 'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x043689F0>, solid=<srctools.vmf.Solid object at 0x042EA390>, normal=Vec(0, 0, -1), color=<MAT_TYPES.white: 1>)}
[INFO] cond.core.steal_from_brush(): New IDS: {'6567': ['21', '27', '33', '39', '44', '49', '54', '59', '65', '71', '77']}
[INFO] cond.core.steal_from_brush(): Steal: {'additional': (), 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x03DFF250>, <srctools.vmf.Solid object at 0x03DFF2B0>, <srctools.vmf.Solid object at 0x03DFF2D0>, <srctools.vmf.Solid object at 0x03DFF2F0>, <srctools.vmf.Solid object at 0x03DFF310>, <srctools.vmf.Solid object at 0x03DFF330>, <srctools.vmf.Solid object at 0x03DFF350>, <srctools.vmf.Solid object at 0x03DFF1F0>, <srctools.vmf.Solid object at 0x03DFF4F0>, <srctools.vmf.Solid object at 0x03DFF510>, <srctools.vmf.Solid object at 0x03DFF230>], detail=None, overlay=[], orig_ids={1259: 135, 1260: 134, 1261: 133, 1241: 147, 1391: 144, 1382: 96, 1319: 83, 1320: 84, 1321: 86, 1322: 89, 1323: 90, 1324: 92, 1201: 111, 1202: 110, 1203: 109, 1204: 108, 1205: 107, 1206: 116, 1207: 115, 1208: 114, 1209: 113, 1210: 112, 1211: 121, 1212: 120, 1213: 119, 1214: 118, 1215: 117, 1216: 126, 1217: 125, 1218: 124, 1219: 123, 1220: 122, 1383: 95, 1251: 131, 1238: 150, 1239: 149, 1240: 148, 1380: 98, 1242: 146, 1243: 145, 1381: 97, 1250: 132, 1379: 100, 1252: 130, 1253: 129, 1254: 128, 1255: 127, 1384: 93, 1385: 106, 1386: 105, 1387: 104, 1388: 103, 1389: 102, 1390: 101, 1393: 142, 1392: 143, 1256: 138, 1394: 141, 1395: 140, 1396: 139, 1257: 137, 1258: 136}), 'rem_brush': True, 'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x04362C30>, solid=<srctools.vmf.Solid object at 0x042EA290>, normal=Vec(0, 0, -1), color=<MAT_TYPES.white: 1>)}
[INFO] cond.core.steal_from_brush(): New IDS: {'6648': ['83', '93', '101', '107', '112', '117', '122', '127', '133', '139', '145']}
[INFO] vbsp.set_elev_videos(): Elevator type: BSOD
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 1/15 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_1"
 | 	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "GENERIC_5"
 | 	"Choreo" "scenes/npc/glados/dlc1_leaderboard07.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 0/9 quotes..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=8004, misses=315, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'unlockdefault': True, 'fixfizzlerbump': False, 'multiversecave': False, 'allowgoomist': True, 'rexcubepelletfizzle': True, 'bee2_goo_debris': True, 'nomidvoices': False, 'bee_show_trigger': True, 'restartonexit': False}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_2.vmf', 'instances/BEE2/over/global_ents.vmf', 'instances/BEE2/logic/goo_fade.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: True
[INFO] vbsp.change_brush(): Creating Bottomless Pits...
[INFO] bottomlessPit.make_bottomless_pit(): Pit instances: {<CONN_TYPES.all: 5>: ['instances/BEE2/bts/sky/pillar_1.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf'], <CONN_TYPES.corner: 3>: ['instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_2.vmf', 'instances/BEE2/bts/sky/corner_3.vmf'], <CONN_TYPES.side: 1>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.straight: 2>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.triple: 4>: ['instances/BEE2/bts/sky/triple_1.vmf', 'instances/BEE2/bts/sky/triple_2.vmf']}
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/base.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/catwalk_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator_corner.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator_corner.vtf"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_stair_128.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_32b.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_end_cap.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/walkway_destroyed_64a.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_bsod.nut"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/screens/elevator_video_overlay1.vmt" as "materials/BEE2/overgrown/lightboard_overlay.vmt"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/over/elevator_sp/elevator_exit/exit_stairs.vmf
 | 
 |_

[INFO] BEE2_config.save(): Saving changes in config "C:\Games\game stuff\BEE2.4_pr23_win\config/compile.cfg"!
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

**Comment by ZombiePwner1** [comment]
Rename the exit_stairs to exit_stair.vmf @TeamSpen210 accidently renamed it incorrectly.

**Comment by G3neralGrant** [comment]
****instances/bee2/over/elevator_sp/elevator_exit/exit_stairs.vmf** doesnt exist, but **instances/over/elevator_sp/elevator_exit/exit_stair.vmf** does. and its spelled correctly

**Comment by Luke18033** [comment]
Whoops, @ZombiePwner1 meant the opposite.
