### ISSUE TITLE
P1 vactubes are unstyled.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1379]
![20170111145408_1](https://cloud.githubusercontent.com/assets/18079316/21838618/02e4f536-d80e-11e6-92ec-03d702c2bcd0.jpg)

**Comment by TeamSpen210** [comment]
The slight difficulty is that the Portal 1 vactube models only have a few versions - straight, corner and t-bend.

**Comment by ZombiePwner1** [comment]
Well i'm sure switching the straight models to the P1 variant won't be that hard the corners and that i'm not too sure of.

**Comment by Luke18033** [comment]
Straight sections and 1-voxel wide turns could be made easily, but there aren't any 2- or 3-voxel wide tube models.
