### ISSUE TITLE
P1 Turrets are missing their P1 counter part

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1381]
![20170111151743_1](https://cloud.githubusercontent.com/assets/18079316/21839155/31295588-d811-11e6-8669-890bb100758f.jpg)

**Comment by Luke18033** [comment]
I don't think this is easily changeable.

**Comment by TheDarkBomber** [comment]
They look styled to me.

**Comment by Luke18033** [comment]
They're pretty similar, the only difference I've noticed is that the "eye" looks different.

**Comment by TheDarkBomber** [comment]
Well, the image blocks the eye from view.

**Comment by ZombiePwner1** [comment]
The difference between the turrets is the P1 turret is very clean and the P2 has some small black spots on it.

**Comment by TeamSpen210** [comment]
There are lots of minor and major differences between the two turrets - significantly the interior is completely different.

**Comment by TheDarkBomber** [comment]
That one is definitely a P1 turret.

**Comment by ZombiePwner1** [comment]
@TheDarkBomber The turret in the picture is not a P1 turret i will take a screenshot of a P1 turret so you can see the difference.

**Comment by ZombiePwner1** [comment]
Here is a comparison between the 2 turrets:

![20170113085019_1](https://cloud.githubusercontent.com/assets/18079316/21914328/8543139a-d96d-11e6-823a-1c8e29d06c21.jpg)





![20170113085043_1](https://cloud.githubusercontent.com/assets/18079316/21914330/8f317a54-d96d-11e6-90a7-70580975bff0.jpg)


Here you can see the eye and the interior of the turret is alot different.

**Comment by Luke18033** [comment]
This should be easily changeable actually, the turret has an "unused" model which lets you set a custom model if SmartEdit is off.

**Comment by TeamSpen210** [comment]
Does it really?

**Comment by Luke18033** [comment]
It has the variant, but I'm not sure if it works. This is just based on information from the Valve Developer Community.

**Comment by Luke18033** [comment]
I'll see if it works later.

**Comment by TeamSpen210** [comment]
It does indeed.
