### ISSUE TITLE
P1 Franken Cubes animation mysteriously freezes after being placed on a button.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1383]
![20170111152748_1](https://cloud.githubusercontent.com/assets/18079316/21839407/97331dfe-d812-11e6-9e2a-47ca980b81a3.jpg)

**Comment by TeamSpen210** [comment]
That's intentional behavior, the cube switches to the box animation when placed on a button to ensure it doesn't jump off. It's coded into the entity.

**Comment by ZombiePwner1** [comment]
But that's strange since in wheatley's tests whenever a franken cube was put a button it would still make chirping sounds and the cube just becomes silent on here.

**Comment by LautaroL20** [comment]
Well, it looks like its intentional.
