### ISSUE TITLE
BEE2.4 Is not packing any songs from Aperture Tag, PS: Mel, and P1 too

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1384]
Moved from the Blodgy´s section (https://github.com/BEEmod/BEE2.4/issues/473) 

Original post by @Alfe5:

"I am using pr 23 and the songs render for me but when I post the map and have a friend play it, they can;t hear the music. I own both games and I hear it but no one else can, even if they own the games too. please fix this in a future update."

**Comment by Jadeygaming** [comment]
Yeah I'd Get On To A Map That Says The Music Is From PS:M But Not Hear A THING

**Comment by LautaroL20** [comment]
Recently ive played the latest @Byzarru map in a 100% clean P2 clean install just to see if this is real, and it is. Currently Bee2.4 doesn´t pack any of these songs.

**Comment by LautaroL20** [comment]
Ill see if this is the same for P1 songs.

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment]
This seems to be fixed now, finally.........

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment]
Isn´t this a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1291
