### ISSUE TITLE
Announcer "Deadly" lines not combined

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1385]
![image](https://cloud.githubusercontent.com/assets/19228201/21856635/86ff4aec-d7d7-11e6-8692-a07798e24c59.png)

**Comment by TheDarkBomber** [comment]
This should go on the BEE2.4 repository. Also needs `BEE2.4 Issue` label.

**Comment by Luke18033** [comment]
No, voice lines are part of the packages.

**Comment by TeamSpen210** [comment]
Actually the first is Propulsion Gel, it's named wrong.
