### ISSUE TITLE
Warm square lighting broken on catwalks

### ISSUE THREAD

**Issue by G3neralGrant** [BEEmod/BEE2-items#1388]
The lighting just cuts off
(https://cloud.githubusercontent.com/assets/24685304/21876896/da1e5e8e-d83b-11e6-9d9a-3953cb7a0c8e.png)
(https://cloud.githubusercontent.com/assets/24685304/21876917/06c9f1d2-d83c-11e6-876c-c38a69328d50.png)

**Comment by Luke18033** [comment]
This looks like a Valve bug.

**Comment by ZombiePwner1** [comment]
You might need to add some extra lighting near there or just remove the warm light entirely. My guess is it's to do with the shadows on the catwalk.

**Comment by TeamSpen210** [comment]
Nope, this is to do with fast lighting. Each prop only has one light value computed for it, so you get the sharp change between the two models. In full compile, all the vertexes (corners) on static props get their own lighting - making it look perfect.

Full compile is always used when publishing.
