### ISSUE TITLE
Items Suggestion

### ISSUE THREAD

**Issue by Konata-Chan** [BEEmod/BEE2-items#1389]
Well..My Suggestion of this program.i have no idea If everything is possible...

1. Vertical Security Door (This door was used in the BEE Alpha)
![vertical door](https://cloud.githubusercontent.com/assets/25024629/21879218/e7e923b6-d875-11e6-84df-96222d5911cb.png)

2.Angled Panel
![panels](https://cloud.githubusercontent.com/assets/25024629/21879334/e5337058-d876-11e6-9b43-890929c489f7.png)

3. Movable Crusher  (this is appears when Chell Escaped for wheatley and this try to kill chell with he.)
Idea:Mashy Spike Plate using A root to move

4. ChamberLock Overgrown,P1 And BTS Style

5. Plataform With Cube (This Appear in the overgrown and when you grab the cube.the plataform hides.)
![panel with cube](https://cloud.githubusercontent.com/assets/25024629/21879487/f3fa7bd0-d877-11e6-9485-f9384684917c.png)

6. Crusher cause damage when deactivated 
(Usually Glados in coop uses it like a floor In one of the cameras)

7. Mechanical Plataform (It would be interesting and useful in test chambers.)
![plataform](https://cloud.githubusercontent.com/assets/25024629/21880337/35b24b98-d87d-11e6-8d6d-3bed377ec43b.png)
Idea:The Plataform Can Connect With Triggers,Pedestal Button and others.

8. Destroyed Panels (This appears in Wheatley Chambers)

9. Glass With Hole
![glass](https://cloud.githubusercontent.com/assets/25024629/21880328/2dc8adaa-d87d-11e6-8438-442d383bd888.png)

Thanks For Extended Portal 2 Puzzle maker! Sorry for my bad english.

**Comment by ZombiePwner1** [comment]
Vertical security doors are already going to be added into bee2.4 all of the old items in BEE2 alpha will be added back to bee2.4

**Comment by Konata-Chan** [comment]
@ZombiePwner1 Ok Thanks For The Information!

**Comment by Luke18033** [comment]
1. This is already going to be implemented, see #95.
2. This would probably be implemented as an angled panel, not a drawbridge.
3. This could maybe be done by connecting two crushers. Input B would move it between positions. Input A or generic input would toggle it.
4. What? The Chamberlock item is already styled for those.
5. Not sure how well this would work. Could be part of BEEmod/BEE2.4#414.
6. This would make sense. A separate Spike Floor item should probably be added, which wouldn't have holes between the crushers.
7. See my comment on #1333.
8. See BEEmod/BEE2.4#414.
9. This is already going to be implemented, see #95.

**Comment by Konata-Chan** [comment]
@Luke18033 Ok.I was confused by the icon of the Chamber Lock.Thanks For reply

**Comment by Luke18033** [comment]
Large glass panels are already covered by #466. Moving crushers are more of a Hammer thing. Glass holes are now implemented. It's also generally not a good idea to combine unrelated issues, since it makes it more difficult to track what is and isn't done.
