### ISSUE TITLE
Add Some More Partial Blocks

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#1390]
I would love to see some more partial blocks added.  A 1X1X1, 1X1X2, and 1X1X3 partial blocks would be very useful.  The 1X1X2 and 1X1X3 blocks would poke out from the face of the voxel onto which they are mounted.  Each block could be positioned in all 16 positions of the face of the voxel.  

I would also love to see the already implemented 2X2X2 block allow the very CENTER position.  As it is right now it allows all 8 positions around the perimeter of the voxel, but not the center.  I have noticed that when it is initially inserted it is not in any of the 8 selectable positions.  Instead it is offset to the edge of one side, but not at one of the corners or in the center...  How about making the initial insertion position the very center of the voxel and then keeping the 8 selectable positions?

**Comment by Luke18033** [comment]
The 1x1 blocks couldn't be positioned on all 16 tiles, there's no handle for it. I have previously suggested center-positioned 2x2x1 and 2x2x2 blocks.

**Comment by libbybapa** [comment]
Ok, so no handle for 16 positions... then it would seem possible to split the 1X1 blocks into two objects each with each objects handling 8 positions for a total of all 16 positions, no?  OR... just do the 8 positions on one half of the voxel and then the user can rotate the object around a corner twice to get the other 8 positions.  ;-)

**Comment by TeamSpen210** [comment]
I can't change how the positions work, I can only offset the model and item appropriately. The initial placement point is a editor bug which can be useful.

**Comment by Konclan** [comment]
Moving to #3885
