### ISSUE TITLE
Curved Blocks

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1391]
These would come in two variants - Concave and Convex. They'd act much like the current angled blocks.
![image](https://cloud.githubusercontent.com/assets/22107242/21912192/fe275a3e-d8e9-11e6-9004-5ef685d0ddc2.png)
They should also have corner variants as well.

**Comment by Luke18033** [comment]
I think this has been suggested before.

**Comment by Byzarru** [comment]
I just ran a search, none like it.

**Comment by Luke18033** [comment]
It was one of those lists of suggestions, with Curved Blocks being one of them. I can't remember anything else about it.

**Comment by Luke18033** [comment]
I'm not sure if the Concave versions would be possible, I don't think Source allows concave geometry.

**Comment by TeamSpen210** [comment]
It doesn't, for individual shapes. You create concave geometry by using multiple brushes. Here's the brushes forming door frames as an example:
![image](https://cloud.githubusercontent.com/assets/8453732/21918768/9371ce7e-d9a0-11e6-97af-c92ced90bb19.png)

**Comment by TheDarkBomber** [comment]
Concave Johnson.

**Comment by Konclan** [comment]
Is that just an alternate reality where all people are spoons?

**Comment by TheDarkBomber** [comment]
Convex Johnson.

**Comment by LautaroL20** [comment]
TheDarkBomber Has shown that comedy is not his thing... lol

**Comment by TheDarkBomber** [comment]
@LautaroL20 Then, why do programmers need glasses?

**Comment by Konclan** [comment]
So they can take them off to avoid your 'comedy' :3

**Comment by TheDarkBomber** [comment]
To C#. #CoolCaveJohnson

**Comment by LautaroL20** [comment]
@Konclan - Hehe, yes i think so.

**Comment by TheDarkBomber** [comment]
Concave Johnson.

Tier 1 - Heimlich Counter Maneuver
Tier 2 - The Take-A-Wish Foundation
Tier 3 - Portals

**Comment by LautaroL20** [comment]
@TheDarkBomber - Heh, you can keep trying it all the day, but you´re not good at comedy. Just admit it.

**Comment by TheDarkBomber** [comment]
Why are programmers afraid of the jungle?
`¡uoɥʇʎd ɟo ǝsnɐɔǝq`

**Comment by Konclan** [comment]
A single python? dang...

**Comment by Jadeygaming** [comment]
@TheDarkBomber I get the second one. Python is a pain in the A**

**Comment by TeamSpen210** [comment]
Why?

**Comment by TheDarkBomber** [comment]
@Jadeygaming I wasn't saying that Python was a bad programming language, there are pythons in the jungle.

**Comment by Byzarru** [comment]
So curved blocks. They're cool.

**Comment by Byzarru** [comment]
If I get around to learning how to make items, I'll try my hand at this.

**Comment by Luke18033** [comment]
Already been suggested on BEEmod/BEE2.4#46.

**Comment by LautaroL20** [comment]
Luke18033 Said: "Already been suggested on BEEmod/BEE2.4#46."

We do not like pilled-up suggestions, ive exposed the reasons before. I will re-open this suggestion until someone decide to split @jccreszMinecraft´s suggestions into individual posts....

**Comment by Luke18033** [comment]
> We do not like pilled-up suggestions

And by "we" you mean "you", because nobody else cares if people combine their suggestions/bugs into one issue.

**Comment by LautaroL20** [comment]
> Andby "we" you mean "you".

Me and TeamSpen210.

**Comment by Konclan** [comment]
Moving to #3885
