### ISSUE TITLE
Clean CO-OP Exit doesn´t open when an input is connected.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1392]
![20170112201739_1](https://cloud.githubusercontent.com/assets/12244376/21912414/8bc73d5e-d904-11e6-8d0e-e3fef4298843.jpg)

**Comment by LautaroL20** [comment]
I feel bad for the cammera :(

**Comment by ZombiePwner1** [comment]
Why does it look like there is multiple cameras in the cameras position.

**Comment by LautaroL20** [comment]
Probably by a duplicated instance on the same .vmf file, idk....

**Comment by ZombiePwner1** [comment]
But that's strange those if there was duplicates in the instance file texture overlaps would most likely be visible.

**Comment by LautaroL20** [comment]
Yep, but sometimes they are so close to one another that you don´t notice the difference.

**Comment by Luke18033** [comment]
Both players need to stand within the 128-unit space in front of the door. Have you done that yet?

**Comment by LautaroL20** [comment]
Yes.... Do not offence, but it looks like you need a pair of glasses, the post´s screenshot is showing what you´re asking.

**Comment by Luke18033** [comment]
You're the one who needs glasses, since you couldn't see that I already have them.

**Comment by LautaroL20** [comment]
Then you should give them a little cleaning.

**Comment by ZombiePwner1** [comment]
lol :D

**Comment by TeamSpen210** [comment]
Which exit is this? All of them?

**Comment by LautaroL20** [comment]
It is the Co-op Exit Corridor N°1. I didn´t test others but i should.
