### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TheManOfGan** [BEEmod/BEE2-items#1394]
I have some more

1.move signage choosing menu so that rhe right click menu doesnt cover it.
2.make crusher extend to how much you want.
3.change signage look if you change it in the right click menu (it stays at cube dropper the whole time).
4.make track platform able to do turns
5.move signage anywhere on a surface
6.Add railings (like the ones on catwalks)
7.make pellet catcher have bigger area to grab in editor
8.give turned off faith plates beeps
9.toggleable square lights,light strips and observation rooms
10.longer samples of music
11.ability to turn off faith plate target

**Comment by Byzarru** [comment]
5 - That's something that may hopefully be implemented (#1093)
6 - #1274

**Comment by ZombiePwner1** [comment]
I have already suggested to add handrails.

**Comment by ZombiePwner1** [comment]
Number 4 on your suggestion though make track platform able to do turns i don't think that will be possible since it would require coding to make it turn or something and we don't have access to the source code to the game.

**Comment by Luke18033** [comment]
I just commented here earlier, did somebody delete it?

**Comment by Luke18033** [comment]
1. This would be possible.
2. This is probably possible, but I'm not sure how it would work.
3. Not possible.
4. Not possible. Use the Unstationary Scaffold for this.
5. You wouldn't be able to move it *anywhere* on the surface, but signages may be given 8-positioning, see #1093.
6. This is going to be implemented, see #1274.
7. The pellet catcher grip area should be the same size as the actual model. If not, it's a bug.
8. What? Faith plates already beep when turning on/off.
9. This could be done, but it wouldn't work very well.
"*Darkness shouldn't be part of a puzzle.*" - TeamSpen210
10. This would be nice, I always hated how short they were. How about something like 30 seconds?
11. Why would you want this? Players wouldn't know where they would launch to. If you really want to get rid of it, hide it under the floor or something.

**Comment by TeamSpen210** [comment]
For 7, I fixed the rotation of the pellet catcher model - it was off by 90 degrees. That will probably make it better. 8 would be very annoying. For 10, I can make them longer, I just keep them short to reduce file size.

**Comment by Luke18033** [comment]
For 10, why not just play the track itself?

**Comment by Luke18033** [comment]
Combined issue, and most of these things have already been suggested elsewhere.
