### ISSUE TITLE
Cube Coloriser is missing a proper Editor Model

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1395]
![sin titulo](https://cloud.githubusercontent.com/assets/12244376/21945082/24966c54-d9b8-11e6-804b-63f8111a1049.png)

**Comment by TheDarkBomber** [comment]
That could be the model of the Decorations Blacklist item, though! And I think that's intentional.

**Comment by LautaroL20** [comment]
I don´t think a missing cube on the model would be intentional...

**Comment by TheDarkBomber** [comment]
It's supposed to go above a cube dropper.

**Comment by LautaroL20** [comment]
Those droppers are the singular co-op checkpoint editor models. See this: https://github.com/BEEmod/BEE2-items/issues/256

**Comment by TheDarkBomber** [comment]
A **cube** dropper

**Comment by LautaroL20** [comment]
Well, updated the post´s screenshot to prevent confusions.

**Comment by TheDarkBomber** [comment]
No, keep the same one.

**Comment by Konclan** [comment]
What is this item even?

**Comment by LautaroL20** [comment]
@Konclan -This item helps distinguish multiple cubes, in puzzles where certain ones may need to be respawned.

**Comment by TheDarkBomber** [comment]
But how do you do it? And what does it look like when you do it?

**Comment by LautaroL20** [comment]
Try it yourself and youll see, i didn´t use it yet.

**Comment by TheDarkBomber** [comment]
Then use it!

**Comment by LautaroL20** [comment]
@TheDarkBomber - No, i don´t have to.

**Comment by TheDarkBomber** [comment]
USE IT! USE IT! **_USE IT!!!!!!!!!!!!!!!!_**

**Comment by Luke18033** [comment]
@TheDarkBomber Stop thumbs-down-ing everybody's posts, it's really annoying...

**Comment by TeamSpen210** [comment]
It's indeed a placeholder (one of the movement handles), I'm not sure what would be a good design for the model actually. It is supposed to go on the cube (but you can put it on the dropper). Here's a picture of what it does:
![620_20170114085049_1](https://cloud.githubusercontent.com/assets/8453732/21948407/d0e423c4-da36-11e6-82fa-45c22bf2052d.png)

**Comment by LautaroL20** [comment]
@TeamSpen210 - Well, you can use the actual palette icon as an example, i wouldn´t have a problem if the model would look exactly as this:

![cube_coloriser](https://cloud.githubusercontent.com/assets/12244376/21948489/63b644c4-d9ca-11e6-9244-b005208cd32d.png)

**Comment by TeamSpen210** [comment]
I might make a floor circle looking like that rainbow - it can't actually be the cube, you place it on top of the actual cube item. It needs to be something that's bigger than a cube, so you can still see and click on it when they're in the same square.

**Comment by Konclan** [comment]
OMG I NEED THIS

**Comment by TeamSpen210** [comment]
There's a total of 28 colours (plus normal cubes). It might get a bit hard to tell apart if you have that many though.

**Comment by LautaroL20** [comment]
A floor circle looking as a rainbow would be intuitive, since the actual placeholder gives a missing model feeling.

**Comment by Luke18033** [comment]
@TeamSpen210 I was just about to suggest that exact same model...

**Comment by Konclan** [comment]
Hey have you guys every though of adding a cube dropper that sprays a cube with gel on it's way out?
I don't see the direct use of it but it could be fun

**Comment by Luke18033** [comment]
There should also be numbers on the model, showing what number uses what color.

**Comment by Alfe5** [comment]
work 24/7 on this one item plz!!!!

**Comment by Byzarru** [comment]
Is this an item that paints cubes or does it color cubes straight from the dropper?

**Comment by TeamSpen210** [comment]
See a previous picture for what it does. You place it on top of a cube to make it painted, it doesn't transfer to others. It's intended to allow players to tell which dropper a cube came from, and not get them mixed up - in puzzles where they need to fizzle cubes to move them around.
