### ISSUE TITLE
Remove Annoying Repulsion Gel/ Funnel SFX

### ISSUE THREAD

**Issue by TheReviewers** [BEEmod/BEE2-items#1399]
Its annoying that everytime i fling, i have to hear some random music.. i don't mind it when the music is meant for it. but when its p1 music with p2 music? its annoying D:

**Comment by TheReviewers** [comment]
@TeamSpen210 Maybe an option to disable it?

**Comment by TeamSpen210** [comment]
I should remove it from some tracks where it doesn't match too well.

**Comment by ZombiePwner1** [comment]
I actually encountered this issue in some styles where the SFX wasn't even mean't to play. For example in one of the styles can't remember which one it was but when i was sliding on propulsion gel or whatever i heard the classical music SFX like wtf? i didn't even have any music selected.

**Comment by TheReviewers** [comment]
I Know Right D:

**Comment by Konclan** [comment]
Duplicate of #1104

**Comment by TeamSpen210** [comment]
@ZombiePwner1, that's definitely a bug. Can you reproduce it?

**Comment by ZombiePwner1** [comment]
I can try i just need to remeber which style it was.

**Comment by Luke18033** [comment]
Was it Portal 1? That style has a lot of issues with item SFX.

**Comment by ZombiePwner1** [comment]
Portal 1 style i had a few issues with SFX since i could hear one of the wheatley SFX's playing yet i had no music set.
