### ISSUE TITLE
Add music trigger to swap out music mid chamber.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1400]
Moved from: https://github.com/BEEmod/BEE2.4/issues/478

Original post by Alfe5:

"I feel like a lot of portal 2 music is situational and doesn't fit for the entire chamber. I believe a lot of map creators would love it of there were a simple music trigger to change the music. However, you should probably flesh out music bugs first before implementing it."

**Comment by Byzarru** [comment]
Duplicate of #550.

**Comment by Luke18033** [comment]
I wish this would be added though, it would work really well for some maps.

**Comment by Byzarru** [comment]
I've suggested a sound effect item (issue still open!), if it's any consolation,

**Comment by TheDarkBomber** [comment]
You should let people move issues themselves.

**Comment by LautaroL20** [comment]
@TheDarkBomber - As usual with these issues, no actions are taken by the author itself, so i must move it.
