### ISSUE TITLE
Signage that Shows the Connection Symbols

### ISSUE THREAD

**Issue by libbybapa** [BEEmod/BEE2-items#1401]
I'd like a signage item that allows you to manually place the stock connection items (e.g. X, square, dot, moon, etc...).  This would be useful and remove confusion/clutter when a single button/catcher/relay activates several objects.

**Comment by TheDarkBomber** [comment]
See #1093.

**Comment by libbybapa** [comment]
Ok.  I see that the connection signage is included in the list of items there, so this is a repeat.  Sorry about that.

**Comment by Byzarru** [comment]
TeamSpen already made the item; it's going in PR24. :)
