### ISSUE TITLE
Cube Coloriser not working correctly on Overgrown or Portal 1.

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1402]
Cubes are using their Clean version, and the entire model is colored instead of just the circle in the center.
![20170115085201_1](https://cloud.githubusercontent.com/assets/19228201/21964403/1bf832c8-db00-11e6-8d49-dcd67f9ecabb.jpg)
The droppers are styled correctly.

**Comment by TheDarkBomber** [comment]
That would be better. I'd say you should also label this `Enhancement`.

**Comment by ZombiePwner1** [comment]
It appears that the cubes are not using their overgrown model which can be changed in the cube type properties in hammer orso.

**Comment by Luke18033** [comment]
@TeamSpen210 just needs to make a colorisable dirty cube model.

**Comment by Luke18033** [comment]
Updated comment 274555535

**Comment by Byzarru** [comment]
This is also the case in P1, they use a colorized Clean model as above.

**Comment by Luke18033** [comment]
Fixed in Portal 1, but I think Overgrown still has the issue. I'll need to check.

**Comment by Luke18033** [comment]
Not fixed in Portal 1, actually.

**Comment by Luke18033** [comment]
Bump

**Comment by Luke18033** [comment]
Wait, the models already exist for this. Why haven't you styled it?

**Comment by TeamSpen210** [comment]
They're there, but aren't being used because I didn't commit the script.

**Comment by Luke18033** [comment]
I think 1980s also had this problem, I assume you've fixed it there too?
