### ISSUE TITLE
Combined Items using wrong names

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1403]
Combined items (like buttons) show their name as the icon being used, and not the name of the item:

![20170115174522_1](https://cloud.githubusercontent.com/assets/12244376/21966043/bfd2ed6c-db4a-11e6-88ef-cbd23962eef3.jpg)

**Comment by LautaroL20** [comment]
![20170115174522_1](https://cloud.githubusercontent.com/assets/12244376/21966043/bfd2ed6c-db4a-11e6-88ef-cbd23962eef3.jpg)

**Comment by Luke18033** [comment]
@LautaroL20 - Don't edit my post, I'll do it myself.

**Comment by LautaroL20** [comment]
@Luke18033 - Only thing i done was attaching a detailed screen, but if you preffer boring and unintuitive posts its ok.

**Comment by TheDarkBomber** [comment]
The difference between a Development Version Bug and a Development Bug, is that a Development Bug is a bug that somebody made developing something, and a Development Version Bug is a bug in the Development Version.

**Comment by Luke18033** [comment]
@TheDarkBomber - All bugs are made while developing something.
