### ISSUE TITLE
BTS Wheatley

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1404]
This would use a different set of lines where Wheatley is helping you get through BTS areas and reach GLaDOS, rather than trying to get you to test. On Monitors, Wheatley would be attached to his management rail, with BTS textures behind him.

**Comment by ZombiePwner1** [comment]
This is a duplicate of https://github.com/BEEmod/BEE2-items/issues/827

**Comment by TheDarkBomber** [comment]
Still needs `BTS` label.
