### ISSUE TITLE
Suggestion Signs

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1406]
_From @PortalTurret on January 15, 2017 18:31_

i would ask if you guys could make a custom sign where you can type stuff on or like the in the original game like "Control Room" or others can you guys try to make it?

_Copied from original issue: BEEmod/BEE2.4#481_

**Comment by TheDarkBomber** [comment]
Did you move this using the Github Issue Mover?

**Comment by Luke18033** [comment]
Yes.

**Comment by TheDarkBomber** [comment]
I could tell because it gave a specific time.

**Comment by TheReviewers** [comment]
Interesting Idea

**Comment by Luke18033** [comment]
I'm not really sure what's being suggested here, custom text overlays aren't really possible to implement.

**Comment by Konclan** [comment]
I think they actually are possible, just not worth the time, also they'd be very out of place.
