### ISSUE TITLE
"Prevent Automatic Property Changing" stylevar

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1407]
A stylevar which prevents item properties from being changed automatically when other items are connected to them. I find this really annoying, since I usually like to have angled panels retract when activated and I have to manually adjust all of the settings after connecting items.

**Comment by TheDarkBomber** [comment]
I agree.

**Comment by TeamSpen210** [comment]
I can't do this, it's coded into the item types.

**Comment by TheDarkBomber** [comment]
Then recode the item types.

**Comment by ZombiePwner1** [comment]
@TheDarkBomber You can't always change everything the item types in my guess is in the source code.

**Comment by ZombiePwner1** [comment]
Hahaha very funny emoji not.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - He just loves emojis, specially for thumbs-downing comments.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Dummy bomber

**Comment by Jadeygaming** [comment]
@ZombiePwner1 It would be TheDummyBomber

**Comment by TheDarkBomber** [comment]
@ZombiePwner1 Your username is incorrect.

Fixed version:

>ZombieKiller1

**Comment by Luke18033** [comment]
@TheDarkBomber - ZombiePwner1 is a valid name...

**Comment by TheDarkBomber** [comment]
Not in the English Language.

**Comment by ZombiePwner1** [comment]
@TheDarkBomber Do not make fun of my name >:(
