### ISSUE TITLE
Use a custom Piston Platform top model to fix translucency layering problems

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1408]
![20170115131417_1](https://cloud.githubusercontent.com/assets/19228201/21966238/b6f75604-db24-11e6-84c9-6b9545ad4cce.jpg)

**Comment by LautaroL20** [comment]
This is likely a Valve bug, and probably isn´t fixeable. See the glass that splits the separated Co-op checkpoint, it also have this same problem:

![20170115183138_1](https://cloud.githubusercontent.com/assets/12244376/21966390/fcce7406-db50-11e6-8b39-90dc1fd08111.jpg)

**Comment by Luke18033** [comment]
It can be fixed with a custom model though.

**Comment by ZombiePwner1** [comment]
I don't think a custom model can fix this.

**Comment by LautaroL20** [comment]
@Luke18033 - Hows supposed a custom model would fix the piston platform´s wong render through the PeTi glass?

**Comment by Luke18033** [comment]
#993

**Comment by ZombiePwner1** [comment]
@LautaroL20 lol

**Comment by LautaroL20** [comment]
That issue is for a different scenario, where the command `$mostlyopaque` is only aplicable to the decompiled .mdl file. The PeTi glass isn´t a model, its generated entirely by the compiler and not by a standalone .mdl file.

**Comment by ZombiePwner1** [comment]
The PeTi glass itself is a texture only models it generates is on the edges.

**Comment by Luke18033** [comment]
You add it to the piston model, not the glass...

**Comment by LautaroL20** [comment]
That wouldn´t change anything, this is to do with the PeTi glass texture, and not with the piston platform model.

**Comment by Luke18033** [comment]
Let's ask @TeamSpen210.

**Comment by TeamSpen210** [comment]
It would be the same issue actually, mainly that the engine isn't always good at ordering transparent textures. It's a surprisingly difficult thing to do actually.

**Comment by LautaroL20** [comment]
And since its actually impossible to implement `$mostlyopaque` on a PeTi glass texture, thats why this doesn´t have any solution.

**Comment by TeamSpen210** [comment]
You'd do it on the model instead and see if it helps

**Comment by Luke18033** [comment]
This happens on other styles as well.

**Comment by Luke18033** [comment]
Is this still an issue? Don't piston platform tops use a custom model now?

**Comment by TeamSpen210** [comment]
Just the panel versions, and those wouldn't have an issue since they're entirely opaque.

**Comment by Luke18033** [comment]
Still an issue, unsurprisingly
![image](https://user-images.githubusercontent.com/19228201/86869906-40014180-c08c-11ea-9210-e2b5f38a9abe.png)

**Comment by Luke18033** [comment]
Placing things in separate visleaves will generally allow the engine to sort them correctly. That would work for the Separated Checkpoint example above (I ended up doing that to fix this exact issue in the P1 version), but not really for piston platforms since they're placed freestanding in the middle of a room. We could try using a model with `$mostlyopaque`, I still don't think that will 100% fix it though.

**Comment by Luke18033** [comment]
Though that did give me an idea - why don't we just generate hint brushes as part of glass, so it's always in its own visleaves? Seems like that would solve most of these problems.

**Comment by Luke18033** [comment]
[Now implemented.](https://github.com/BEEmod/BEE2.4/commit/8a7104e4ebd65b469a8d82a116ac6cd5ad3a20cf)

**Comment by Luke18033** [comment]
This can still happen, I'm not sure why though since these are now in separate visleaves...I doubt there's anything more we can try.
![image](https://user-images.githubusercontent.com/19228201/141884833-3e56e58e-92d5-45a3-ade1-87393bc7513b.png)
