### ISSUE TITLE
Glass item is using a wrong selection mesh, it makes the item totally unconfortable to handle rotation

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1410]
For some "Mysterious Reason" its using the Track Platform´s selection mesh:

![20170115222649_1](https://cloud.githubusercontent.com/assets/12244376/21968300/012aa530-db72-11e6-8480-8a4a63845176.jpg)

**Comment by Byzarru** [comment]
Is this the current or the dev version? That screencap is horrifying.

**Comment by ZombiePwner1** [comment]
I don't think you can change the selection mesh.

**Comment by LautaroL20** [comment]
@Byzarru - Thats just the drawded selection meshes lines.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Yes, selection meshes are totally changeable, there is even a folder where those files are and it is the "puzzlemaker" foler (Portal 2\bee2\models\puzzlemaker).

**Comment by ZombiePwner1** [comment]
I don't think the selection mesh is an actual model yes it's attached to the PeTi model but it's just a bunch of lines.

**Comment by LautaroL20** [comment]
I never said that the selection mesh were a model....

**Comment by LautaroL20** [comment]
Well, id say its a "Pseudo-Model". Actually its a bunch of polygon lines much less complex than the actual model is.

**Comment by TheDarkBomber** [comment]
I don't think something the player can't see normally will be a problem.

**Comment by TeamSpen210** [comment]
This is important, it defines what area of the screen is clickable to select the model. If it's wrong, you won't be able to click on items easily, or they will prevent you from clicking on other items.

**Comment by Luke18033** [comment]
@TeamSpen210 Like catwalks and triggers.

**Comment by LautaroL20** [comment]
This is invalid. I figured out that this was to do with another folder (Portal 2\portal2_dlc2\models\puzzlemaker), folder that Beemod doesn´t touch. Probably i mixed up meshes when i was making my Protruding Buttons Editor Models.
