### ISSUE TITLE
Ping Sensor

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1411]
This would be an item which would output when a Co-op player pinged it. It would appear as a 64x64 unit pad in the center of the voxel, with a blue0 target on it, which would turn orange when active. A timer property would allow configuring the amount of time the output would stay active. In SP, this would constantly blink between blue and orange, being unusable in that mode.

**Comment by TheDarkBomber** [comment]
This has already been suggested.

**Comment by Luke18033** [comment]
I just did a search, nothing like it.

**Comment by TheDarkBomber** [comment]
Duplicate of #702

**Comment by Luke18033** [comment]
Oh, I only searched for "ping sensor" and "ping detector"

**Comment by TheDarkBomber** [comment]
You should of just searched for "ping"
