### ISSUE TITLE
Overgrown Cutout Tile not working properly

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1412]
![20170116141706_1](https://cloud.githubusercontent.com/assets/19228201/22000940/ee2e251c-dbf6-11e6-93f2-5948affb88fd.jpg)

**Comment by ZombiePwner1** [comment]
I told @TeamSpen210 about this on steam and he said that he changed them abit i just don't exactly remember what.

**Comment by Luke18033** [comment]
Cutout tiles are going to be remade
