### ISSUE TITLE
Implement icons for Unstationary Scaffold items

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1415]
These items are just using the Piston Platform icon, they need their own.

**Comment by Luke18033** [comment]
Now implemented in dev.

**Comment by HTiago** [comment]
Can I?

**Comment by TeamSpen210** [comment]
They're actually your icons already, from the start of the issue (#2470).

**Comment by HTiago** [comment]
Ew, misunderstood.¯\_ (ツ) _/¯
