### ISSUE TITLE
Batcature style

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1416]
This would appear as the style seen in the [Batcature maps by Batcat](https://steamcommunity.com/workshop/filedetails/?id=625605733), where test chambers are built on airships. Test elements appear much simpler (like they are made of brushes), and antlines are solid lines. The "elevator" area would look like the lobby area from Part 1. The skybox would be the sky from Parts 1 and 2. All items that appear in the series would be styled, while items that don't and custom items would have custom versions made. As seen in the maps, fizzlers would only generate emitters on the side the item was placed on (preferably the floor).

I will post corridor ideas here later.

**Comment by ZombiePwner1** [comment]
The skybox is a custom made one batcature told me

**Comment by Luke18033** [comment]
@ZombiePwner1 - We'd pack it into the map.

**Comment by ZombiePwner1** [comment]
No basically what i mean is that it's a custom background batcature made himself and i asked him if i could have it but i was unable to get it.

**Comment by Luke18033** [comment]
We'd probably be able to get it from him, and if not, we could probably extract it from the map somehow.

**Comment by ZombiePwner1** [comment]
Extracting it from the map i don't think that's even possible. Perhaps @TeamSpen210 will know if it's possible or not.

**Comment by TeamSpen210** [comment]
You can extract things from the map fairly easily, but it'd be better to ask him, so we get permission to use it.

**Comment by ZombiePwner1** [comment]
Yes indeed.

**Comment by Byzarru** [comment]
I think we should probably invite high-profile mappers such as Batcat to make their own BEE themes based on their styles or to at least give their assets and direction.

**Comment by TheDarkBomber** [comment]
Actually, they are split into different styles.

This would be three styles:
* Batcature 1 Style
* Batcature Airship Style
* Batcature Space Style

**Comment by Luke18033** [comment]
@TheDarkBomber - I was going to suggest having three different styles, but how would the sky work for Airship and Space styles?

**Comment by Byzarru** [comment]
Those are essentially the same style, just in space and in an airship. The corridors can be either Batcature 1, Airship, or Space, using the same lame trick Old Aperture uses in making things look like they take place in a test chamber in the middle of a sphere/airship/space.

**Comment by Byzarru** [comment]
Also, TeamSpen confirmed that corridors can define the observation rooms, so the motif you choose influences the environment.

Entries:
1. Batcature 1
2. Batcature 1 B
3. Batcature BTS
4. Batcature Airship
5. Batcature Airship B
6. Space
7. Space B

Exit:
1. Batcature 1
2. Batcature BTS
3. Batcature Airship
4. Space

HRV can be the intro to the Batcature labs mappack.

**Comment by Byzarru** [comment]
Airship pits would be a skybox setting, like BTS.

**Comment by TheReviewers** [comment]
If you play batcature 1, at the end.. you can see my name x)

**Comment by Konclan** [comment]
There is a chance this just shouldn't be added
