### ISSUE TITLE
Vactube selection meshes facing the wrong way

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#1418]
![20170118165113_1](https://cloud.githubusercontent.com/assets/16567080/22086476/74c62950-dd9e-11e6-9853-cf1d9e837f2e.jpg)

**Comment by Luke18033** [comment]
Those are Vactubes, not PDVs.

**Comment by LautaroL20** [comment]
Well, id say it has "deform dimensions" instead of having a wrong way.

**Comment by TeamSpen210** [comment]
It's rotated 90 degrees.
