### ISSUE TITLE
Make Antlines on Partial Blocks Optional

### ISSUE THREAD

**Issue by libbybapa** [BEEmod/BEE2-items#1419]
I noticed with PR23 antlines are now appearing on partial blocks.  While I can understand that being desirable in some instances, oftentimes it is *not*.  Antline layout is very important to me and sometimes the way to get it just right is to hide the start or end of an antline behind partial blocks.  Please make the appearance of antlines on partial blocks *optional* using 'start enabled' or the like.  Otherwise, I'd rather have that off than on.

**Comment by TheDarkBomber** [comment]
@TeamSpen210 said that it is difficult/impossible to control the position of antlines.

**Comment by libbybapa** [comment]
Did youbother to read what I wrote?  Prior to PR23 the antlines did NOT appear on partial blocks, now they do.  I'd like to be able to make it so they don't any more...

**Comment by TheDarkBomber** [comment]
So, an Stylevar (itemvar) or Start Enabled?

**Comment by Luke18033** [comment]
Looks like somebody didn't read the comment again...

**Comment by TheDarkBomber** [comment]
@Luke18033 Read the last part of the comment.

Hint:

>but I'd be ok with just knowing what I would need to change so they no longer appear on any partial blocks.

**Comment by libbybapa** [comment]
I'm not sure how to make it more clear...

IF it is possible to have a setting on individual partial blocks (e.g. start enabled) so that antlines will not appear on that individual block, THEN that would be BEST.

IF it is not possible to have such a setting on individual blocks, THEN it would be next best to have that as an option to turn them off on all partial blocks in a given map (maybe an option in compile setting or a style).  

IF it is not even possible to turn antlines off/on for all blocks in a given map, THEN I would like to know what code I would need to change in the partial blocks package so that I can turn them off for all partial blocks that I use on any map.

**Comment by TheDarkBomber** [comment]
Well, in the meantime, you could use an Antline Router.

**Comment by LautaroL20** [comment]
Thats what the Antline Router Strips is for.... to having control over antline clutter.

**Comment by libbybapa** [comment]
I do use antline routers.  They are very helpful, but do not do what I am asking for.

**Comment by libbybapa** [comment]
It is NOT what antline router strips are for.  WTF?

**Comment by TheDarkBomber** [comment]
Antline Magnet/Routers. A magnet forces all antlines to meet there, and a router prevents an antline from being on the face it is placed on.

**Comment by libbybapa** [comment]
PLEASE DO NOT CLOSE THIS ISSUE WITHOUT OFFERING AN ADEQUATE SOLUTION TO TURNING OFF ANTLINES ON PARTIAL BLOCKS!!!!!

I know EXACTLY how antline routers, router strips, and magnets work...  Look at this following screenshot.  Previously, the partial blocks did not show antlines.  There were two 'corner' segments behind the partial blocks and the antline made a cleaner corner.  Now it jogs less effectively and there's a disconnected corner piece on top of the partial block.  There is no way for me to eliminate that extra nonsensical antline part without ruining the antline layout REGARDLESS of using routers or magnets.
![20170120161027_1](https://cloud.githubusercontent.com/assets/19520567/22168691/9d01e6c8-df2b-11e6-9fb2-1a12584225c2.jpg)

There are many other times where I have HIDDEN an unwanted part of an antline behind a partial block in order to make a cleaner antline layout.  Most notably I have done that with pedestal buttons and light bridges when the beginning of the antline is a weird frickin' BLOB...  Now it is not possible to use that technique because the antline just blobs onto the partial block instead.

**Comment by TheDarkBomber** [comment]
I was just stating a way to prevent it "while you wait".

**Comment by libbybapa** [comment]
Having the antlines show up on partial blocks the way they do now is WORSE THAN WHEN THEY DIDN'T.

**Comment by TeamSpen210** [comment]
Yep, that's wrong. It should really be on the sides, but that's complicated to figure out. I'll add a checkbox to control this (it needs to be handled by the compiler).

**Comment by libbybapa** [comment]
I'd really like the option so they do not show up on the partial blocks like they did not previously.

**Comment by libbybapa** [comment]
...in other words, in that screenshot, I would prefer both of the antline corner segments that are showing on the partial blocks to be turned off entirely (not show up on the side of the partial block).

**Comment by TeamSpen210** [comment]
I'll add `Start Enabled` to the partial blocks to control whether they move over the antlines.

**Comment by libbybapa** [comment]
AWESOME!  TeamSpen, you're the best!

**Comment by LautaroL20** [comment]
Where is the "Start Enabled" to get back those antlines over blocks? This post was about making antlines OPTIONAL, NOT REMOVING THEM ENTIRELY! This has downgraded the quality, since antlines over partial blocks make it looks realistic.

**Comment by TeamSpen210** [comment]
There is, you might need to update compiler though.

**Comment by libbybapa** [comment]
Start enabled is present for me and works perfectly.  Thanks TeamSpen210!

**Comment by LautaroL20** [comment]
@TeamSpen210 @libbybapa ![20170122181457_1](https://cloud.githubusercontent.com/assets/12244376/22186113/361e3f92-e0cf-11e6-91b0-95253d483ec9.jpg)

**Comment by libbybapa** [comment]
I see what you mean.  It has been added to the Partial Flat blocks, the Angled blocks and the Outside Corner blocks, but is missing from the Partial blocks.

**Comment by Luke18033** [comment]
I'd assume that means that antlines don't appear on Partial Blocks, only on Flat Blocks and Angled Blocks (both types).

**Comment by LautaroL20** [comment]
Oh come on, people.... Call things as they are, Partial Blocks are one thing, and Flat blocks are another different. So, in conclusion, the post title is wronger than believing the Earth is plane.
