### ISSUE TITLE
generation of vacuum tubes etc in wheatley style

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#142]
use a item like the catwalk that connects one end to the other to generate vactubes etc breaking into the chamber in wheatley style

![sp_a4_laser_catapult0005](https://cloud.githubusercontent.com/assets/11165643/11431073/6e5960da-945e-11e5-834d-1263ec7ba1b6.jpg)

![sp_a4_tb_wall_button0010](https://cloud.githubusercontent.com/assets/11165643/11431111/15597744-945f-11e5-87bf-48bc4825af00.jpg)

same thing with a metal beam like this...

![sp_a4_laser_platform0002](https://cloud.githubusercontent.com/assets/11165643/11431076/7c37f98c-945e-11e5-9e4e-eada7a687ad9.jpg)

**Comment by Konclan** [comment]
How would this work, It may interfere with the test chamber
