### ISSUE TITLE
The "Right" and "Left" Positions from the Protuding pedestal buttons causes "Failure To Compile"

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1422]
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting Coop Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: COOP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (154 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "item_bee2_fizzler_out_relay" not a valid item!
[INFO] cond.core.res_goo_debris(): GooDebris: 0/4 locations
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.catwalks.res_make_catwalk(): Connections: {<srctools.vmf.Entity object at 0x05530B10>: [False, False, False, False], <srctools.vmf.Entity object at 0x05530BD0>: [False, False, False, False]}
[INFO] cond.catwalks.res_make_catwalk(): Markers: {'catw48': <srctools.vmf.Entity object at 0x05530B10>, 'catw49': <srctools.vmf.Entity object at 0x05530BD0>}
[INFO] cond.catwalks.res_make_catwalk(): Finished catwalk generation!
[INFO] cond.core.retexture_template(): Mat: anim_wp/framework/squarebeams, replacement: anim_wp/framework/squarebeams_rusty_01
[INFO] cond.core.retexture_template(): Mat: anim_wp/framework/squarebeams, replacement: anim_wp/framework/squarebeams_rusty_01
[INFO] cond.core.retexture_template(): Mat: anim_wp/framework/squarebeams, replacement: anim_wp/framework/squarebeams_rusty_01
[INFO] cond.core.retexture_template(): Mat: anim_wp/framework/squarebeams, replacement: anim_wp/framework/squarebeams_rusty_01
[INFO] cond.core.steal_from_brush(): Steal: {'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x05603C90>, solid=<srctools.vmf.Solid object at 0x055B97F0>, normal=Vec(0, 0, -1), color=<MAT_TYPES.white: 1>), 'rem_brush': False, 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x0551C270>], detail=None, overlay=[], orig_ids={1: 1027, 2: 1028, 3: 1029, 4: 1030, 5: 1031, 6: 1032}), 'additional': [], 'transfer_overlays': False}
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] cond.vactubes.res_make_vactubes(): Markers: dict_keys(['vac71', 'vac66'])
[INFO] cond.vactubes.res_make_vactubes(): Outputs: set()
[INFO] cond.vactubes.res_make_vactubes(): Outputs: {'vac71', 'it12695'}
[INFO] cond.core.steal_from_brush(): Steal: {'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x05855510>, solid=<srctools.vmf.Solid object at 0x057EEC30>, normal=Vec(0, 0, -1), color=<MAT_TYPES.white: 1>), 'rem_brush': True, 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x04E51410>, <srctools.vmf.Solid object at 0x04E514B0>, <srctools.vmf.Solid object at 0x04E51430>, <srctools.vmf.Solid object at 0x04E51470>, <srctools.vmf.Solid object at 0x04E51490>, <srctools.vmf.Solid object at 0x0551C2F0>, <srctools.vmf.Solid object at 0x04E4BED0>, <srctools.vmf.Solid object at 0x04E39D90>, <srctools.vmf.Solid object at 0x04E39E50>, <srctools.vmf.Solid object at 0x04E39FB0>, <srctools.vmf.Solid object at 0x04E39E30>], detail=None, overlay=[], orig_ids={1259: 1908, 1260: 1907, 1261: 1906, 1241: 1920, 1391: 1917, 1382: 1870, 1319: 1862, 1320: 1863, 1321: 1864, 1322: 1865, 1323: 1866, 1324: 1867, 1201: 1884, 1202: 1883, 1203: 1882, 1204: 1881, 1205: 1880, 1206: 1889, 1207: 1888, 1208: 1887, 1209: 1886, 1210: 1885, 1211: 1894, 1212: 1893, 1213: 1892, 1214: 1891, 1215: 1890, 1216: 1899, 1217: 1898, 1218: 1897, 1219: 1896, 1220: 1895, 1383: 1869, 1251: 1904, 1238: 1923, 1239: 1922, 1240: 1921, 1380: 1872, 1242: 1919, 1243: 1918, 1381: 1871, 1250: 1905, 1379: 1873, 1252: 1903, 1253: 1902, 1254: 1901, 1255: 1900, 1384: 1868, 1385: 1879, 1386: 1878, 1387: 1877, 1388: 1876, 1389: 1875, 1390: 1874, 1393: 1915, 1392: 1916, 1256: 1911, 1394: 1914, 1395: 1913, 1396: 1912, 1257: 1910, 1258: 1909}), 'additional': (), 'transfer_overlays': True}
[ERROR] cond.core.check_all(): Error in condition:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 522, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 354, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 343, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1651, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 354, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 343, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\brushes.py", line 586, in res_import_template
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1103, in import_template
KeyError: 'single'

**Comment by LautaroL20** [comment]
@TeamSpen210 - We did not notice this bug because we tested only the "Middle" position wich works fine, this problem is entirely related to the "Right" and "Left" positions only.

**Comment by TeamSpen210** [comment]
Which style is this? I don't get this issue.

**Comment by ZombiePwner1** [comment]
This goes for every style.

**Comment by LautaroL20** [comment]
@TeamSpen210 - ZombiePwner1 clearly didn´t test it well since this only happens in Overgrown, rest of the styles works fine.

**Comment by LautaroL20** [comment]
Nice, this seems to be fixed now.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Figured out this only happens in overgrown.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - This was fixed since a long time ago, was something to do with the brush templates.
