### ISSUE TITLE
Overgrown observation room 128 ceiling causes a compile error.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1423]
4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/BEE2/over/items/observation_room_128_ceil.vmf
 | 
 |_

[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

**Comment by LautaroL20** [comment]
Thats because its missing the instance, someone must forgot to put it.

**Comment by Luke18033** [comment]
Whoops - Pr24 added the ability for Overgrown observation rooms on floor/ceiling, but didn't include the instances.

**Comment by ZombiePwner1** [comment]
Ummm @Luke18033 The observation rooms were always placeable on the ceilings and floors since last release.

**Comment by Luke18033** [comment]
Not in Overgrown.

**Comment by TeamSpen210** [comment]
There isn't actually an instance for these, it needs to be made.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 As I said before I'm working on one.

**Comment by LautaroL20** [comment]
Well, you mentioned it many times already....Hopefully it will look good at least.

**Comment by Konclan** [comment]
This is fixed now

**Comment by LautaroL20** [comment]
So, did someone the styled versions of the ceilling small observation?
