### ISSUE TITLE
Overgrown P-Body is missing her portal gun.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1424]
![20170121163508_1](https://cloud.githubusercontent.com/assets/18079316/22173237/af90ca58-dff7-11e6-9031-fd79abedea79.jpg)

**Comment by LautaroL20** [comment]
It looks like you broke some files onto your game folder, because it works pretty normal for me:

![20170121100345_1](https://cloud.githubusercontent.com/assets/12244376/22174595/f2c0cde6-dfc0-11e6-8adc-81acf38aba7d.jpg)

**Comment by TheDarkBomber** [comment]
**His** portal gun.

**Comment by ZombiePwner1** [comment]
@LautaroL20 I did not break any game files you wheely how does breaking the game files have anything to do with the portal gun missing?

**Comment by TheDarkBomber** [comment]
Nope. In fact, robots don't have genders. So, Fixed Version:

>Overgrown P-Body is missing their portal gun.

**Comment by ZombiePwner1** [comment]
@TheDarkBomber You are a wheely.

**Comment by TheDarkBomber** [comment]
So, I'm a bike move?

**Comment by LautaroL20** [comment]
LOL

**Comment by LautaroL20** [comment]
@ZombiePwner1 - You broke your game files or mixed them up because you love using lots of mods that changes skins....

**Comment by ZombiePwner1** [comment]
@LautaroL20 If i broke my game files atlas's portal gun wouldn't be appearing either the coop guns use the exact same model as the single player gun just a different skin.

**Comment by TheDarkBomber** [comment]
Can anybody replicate this in-game?

**Comment by LautaroL20** [comment]
I meant you mixed up files because you love using lots of mods, so p-body´s gun got swapped. Ill close this until someone who do not have mixed up mods report this too.

**Comment by LautaroL20** [comment]
@TheDarkBomber - I already did and didn´t get this problem.

**Comment by TheDarkBomber** [comment]
So this should be labeled `Unreplicatable`.
