### ISSUE TITLE
Overgrown everything disappears when standing ontop of vactubes.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1428]
![20170121164300_1](https://cloud.githubusercontent.com/assets/18079316/22173282/c6768f36-dff8-11e6-9e39-2ef35d4545e9.jpg)

![20170121164317_1](https://cloud.githubusercontent.com/assets/18079316/22173284/c9cd34e6-dff8-11e6-97ce-1d073db2513a.jpg)

**Comment by TeamSpen210** [comment]
Something's wrong with your graphics, or something's very wrong with the map.

**Comment by ZombiePwner1** [comment]
It's definitely not to do with my graphics.

**Comment by Luke18033** [comment]
Should now be fixed.
