### ISSUE TITLE
Overgrown CO-OP Exit door not connecting their worldportals properly

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1429]
![20170121164723_1](https://cloud.githubusercontent.com/assets/18079316/22173297/877f03d4-dff9-11e6-9a79-c709ea0b74e1.jpg)

![20170121164733_1](https://cloud.githubusercontent.com/assets/18079316/22173299/89ceac02-dff9-11e6-9a0b-efbe72c9ebcb.jpg)

![20170121164740_1](https://cloud.githubusercontent.com/assets/18079316/22173300/8c26ee24-dff9-11e6-884a-8d9ada47c9a8.jpg)

**Comment by LautaroL20** [comment]
That looks like worldportals are not joining properly.

**Comment by LautaroL20** [comment]
This doesn´t happens to me, so this was probably fixed a time ago already:
![20170315115509_1](https://cloud.githubusercontent.com/assets/12244376/23954555/61a43b10-0976-11e7-98bb-5baef95e4237.jpg)
