### ISSUE TITLE
Overgrown Co-op exit didn't appear after compile

### ISSUE THREAD

**Issue by TheDarkBomber** [BEEmod/BEE2-items#1431]
@SW50000 commented on [Sat Jan 21 2017](https://github.com/BEEmod/BEE2.4/issues/490)

![20170121000134_1](https://cloud.githubusercontent.com/assets/20195894/22172455/ecfba33a-df6c-11e6-9af9-1694fcc1e4b1.jpg)
It Didn't appear, but the entrance appeared fine

**Comment by LautaroL20** [comment]
I guess this is absolutely fixed, specially with the new VScript system that was recently implemented.
