### ISSUE TITLE
Portal 1 30 degress angled panel is completely broken with portals.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1432]
![20170121211721_1](https://cloud.githubusercontent.com/assets/18079316/22174681/23f81c58-e01f-11e6-8a08-089207d92a3f.jpg)

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Tested this again and it seems to be fixed.

**Comment by TeamSpen210** [comment]
It appears fixed, but it actually isn't.

**Comment by Luke18033** [comment]
Seems to work fine for me, what do you mean it isn't actually fixed?

**Comment by FrozenDragon0** [comment]
Has this been fixed?

**Comment by Luke18033** [comment]
Should be?

**Comment by Luke18033** [comment]
I'm still not sure how it could "appear fixed, but it actually isn't". I know I haven't had any problems with this recently.
