### ISSUE TITLE
Suggestion: Give a option to switch between all 3 lightstrips ingame

### ISSUE THREAD

**Issue by SW50000** [BEEmod/BEE2-items#1436]

**Comment by Luke18033** [comment]
I would like this too, but @TeamSpen210 refuses to do it because of stupid item collisions...

**Comment by SW50000** [comment]
Okay then

**Comment by Luke18033** [comment]
I'll probably be doing it anyway though :)

**Comment by Byzarru** [comment]
What do item collisions have to do with grouping the light switch?

**Comment by TeamSpen210** [comment]
If it's converted to the button type (which is needed for that property), it loses the collisions since it's not a light strip item class.

**Comment by Endermage77** [comment]
I am curious, though, as to why being able to collide with light strips is important.
