### ISSUE TITLE
Pr 24's connections signs have missing textures/packages

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1437]
Original post by: @Alfe5

"I placed the brand new items into the editor today only to find missing textures for connection signs. I am using the clean test chambers atm. Please look into this as i find this item very helpful."

**Comment by Byzarru** [comment]
They work. Try re-starting.
![20170121220827_1](https://cloud.githubusercontent.com/assets/22107242/22180071/5226e8a0-e02b-11e6-8ef8-a1e203404d6c.jpg)

**Comment by Luke18033** [comment]
They also work for me, case closed.
