### ISSUE TITLE
Players still can´t go through portals on the Static 30° and 45° Degrees Angled Panels 

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#1438]
Players still can't walk through 30* and 45* angled static panels.
![20170121125521_1](https://cloud.githubusercontent.com/assets/16567080/22176886/24886e20-dfd9-11e6-980d-c00383507e65.jpg)

**Comment by Konclan** [comment]
What are these titles? I'm not getting stuck in the panel I just can't go through portals on the panel

**Comment by LautaroL20** [comment]
Well, the description said "can't walk" when it should said "players can´t go trhough portals" wich is slightly different. Title is fixed now.

**Comment by TheDarkBomber** [comment]
It's Degrees.

**Comment by libbybapa** [comment]
As an easy temporary workaround you can add an invisible AND gate and connect it TO the angled panel.  Turn off connection visibility.

**Comment by quat1024** [comment]
Some more details:

* Floor panels: 30 and 45 degree panels are affected.

* Wall panels facing upwards: 30 and 45 degree panels are affected.

* Wall panels facing downwards: 45 degree panels are affected.

* Haven't tested wall panels placing sideways because lol who uses those.

* Ceiling panels: 30 and 45 degree panels are affected.

All dynamic panels are unaffected.

**Comment by LautaroL20** [comment]
@quat1024 - Basically, the 30° and 45° Static Versions heh

**Comment by quat1024** [comment]
Except 30 degree wall panels facing downwards for some reason lol

**Comment by Konclan** [comment]
Isn't this fixed in next release?

**Comment by LautaroL20** [comment]
@Konclan - You should ask @TeamSpen210

**Comment by LautaroL20** [comment]
@Konclan @quat1024 - Ive figured why it does happens, and it will be fixed in next pre-release 25.

**Comment by LautaroL20** [comment]
What did Valve actually used for the PeTi Angled Panels? We should use the same clip type as those.
