### ISSUE TITLE
Players are getting "Stagnant Forever" on all the singular CO-OP Droppers

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1439]
This is pretty strange since i make sure to test this item many times before PRL24 came out, but this is what happens right now, GIF: 

![gif](https://cloud.githubusercontent.com/assets/12244376/22177217/4ab58618-dff8-11e6-8932-1b654ac165e2.gif)

**Comment by TeamSpen210** [comment]
It's not broken in Overgrown style...

**Comment by LautaroL20** [comment]
Well, the small problem is that the map i was planning on publish with this new item is entirely focusedo on Clean Style where this is broken, and it woudln´t fit well if i turn the map into Overgrown.

**Comment by TeamSpen210** [comment]
Delete the clip in the dropper, that'll fix it.

**Comment by LautaroL20** [comment]
Alright, thanks.
