### ISSUE TITLE
Reduce the player´s fall from the Singular Co-op Droppers 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1440]
Please, make the player´s droppers to re-spawn from the second top block of it like the standard separated co-op checkpoint does. It is not necesary to have that long fall wich also is wasting lot of space into the editor...... This would help mappers A LOT to not having to redesing those areas because the long item´s collisions:
![20170121164606_1](https://cloud.githubusercontent.com/assets/12244376/22177283/9ba6bae6-dff9-11e6-990f-1194490c39f8.jpg)

**Comment by LautaroL20** [comment]
@TeamSpen210 - When you´ll gonna implement the left Styled versions, do not forget to check first the already fixed instances that makes the player to fall directly from the "Second top block" from its dropper as the ordinary checkpoint does. This reduces significantly the unnecesary long fall and also help mappers with a smaller item´s collisions.

**Comment by TeamSpen210** [comment]
There's more than just clean style...

**Comment by LautaroL20** [comment]
Well, im going to upload the left instances in a few minutes, just giving them a last revision.

**Comment by TeamSpen210** [comment]
This is desirable to make it harder to see the player spawning, and the top of the tube. The actual spawns in the campaign would be this tall, it's just that the spawn room is short.

**Comment by LautaroL20** [comment]
I tried putting tons of light strips under the player dropper and it still was hard to see that, so maybe we should use a block_lgith clip for it, but it isnt really needed.

**Comment by TeamSpen210** [comment]
Check the drop distance in the original droppers as well.

**Comment by LautaroL20** [comment]
I make sure to do that before start to re-arrainging the fall on the singular checkpoint droppers, and it should be the same now.

Fixed via: https://github.com/BEEmod/BEE2-items/commit/bfaffa2c2b8494c9a1a49b3393afc34e5fe665e9

**Comment by TeamSpen210** [comment]
They also need to be taller so both players can be on top of one another if spawning simultaneously. Also realistically, you shouldn't have items above the droppers anyway. The tube should continue quite a further distance, it's just that we don't make tht. You wouldn't have rooms above it for example.

Can you show me an example where this actually matters?

**Comment by LautaroL20** [comment]
Sure, i made this for a reason (If you readed the post´s description youll understand) but here are another screenshots that shows the conflict im refering to, its pretty much annoying to having to redesing many puzzle areas because of this:

![20170123172957_1](https://cloud.githubusercontent.com/assets/12244376/22221417/b6b6c972-e191-11e6-8728-22cdfb644bc1.jpg)
![20170123172917_1](https://cloud.githubusercontent.com/assets/12244376/22221455/e69dc5be-e191-11e6-99bb-da4bd84473b1.jpg)

**Comment by TeamSpen210** [comment]
In your second screenshot, that looks pretty unrealistic. It should need a bigger space.

**Comment by LautaroL20** [comment]
> It should need a bigger space.

With my fix thats not needed anymore. I have too many relevant things from the 3rd top block from that co-op dropper wich i can´t re-desing, since it would break the puzzle idea. Im pretty sure i am not the only one who could experience this scenario....

**Comment by TeamSpen210** [comment]
No, the item should require that space even if it doesn't use it. You shouldn't be able to  get away with that small an area.

**Comment by LautaroL20** [comment]
> You shouldn't be able to get away with that small an area.

It was actually almost the same short fall that uses the ordinary checkpoint or the default PeTi co-op Spawn. I don´t understand why you wouldn´t listen my petition when there was another guy who requested an unrealistic thing on an item that could be solved by simply using the Antline Routers (https://github.com/BEEmod/BEE2-items/issues/1419) 

Personally i will not sync Github today, i don´t want to lose the small effort ive spend on those instances to fix this trouble. I will save this somewhere so i can use my instances when i get back to work on my co-op map... I feel bad for those people who feel unnecesary that long fall and doesn´t have knowledge to edit them on Hammer btw.

**Comment by ZombiePwner1** [comment]
@LautaroL20 lol you wheely can i chat to you on steam?

**Comment by Luke18033** [comment]
I agree with @LautaroL20, the space needs to be smaller. And I disagree with Valve, for making "invalid positions" a thing at all.

@TeamSpen210 - What if the tube curves off to the side?

**Comment by Luke18033** [comment]
Updated comment 274658829

**Comment by Luke18033** [comment]
Maybe make this an "optional embed" like cube droppers have now? So the tube would extend further upwards if the space was available, otherwise would just go up 2 blocks.

**Comment by LautaroL20** [comment]
That sounds good and reasonable so i hope Spencer would not oppose to that. We should open a suggestion for that or just re-open this and re-edit the original post description. I really dislike when an item takes too much boxel space in the editor...
