### ISSUE TITLE
Flat Blocks Error in Goo or On Antline Routers

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#1441]
As the title says with PR24, the partial flat blocks now give a position error when placed on antline routers and still give an error when placed in goo.

**Comment by Luke18033** [comment]
Stupid Valve...

**Comment by Luke18033** [comment]
I've fixed this already.

**Comment by libbybapa** [comment]
Nice!  I'm downloading the source right now in order to eliminate the lines that cause the goo issue.  Does anything else need to be changed to eliminate the antline router issue?

**Comment by Luke18033** [comment]
Removing `OccupiedVoxels` should eliminate all placement errors, except for floating.

**Comment by libbybapa** [comment]
Yup, that fixed it for both issues.  Thanks!

**Comment by LautaroL20** [comment]
@Luke18033 - Partial Blocks is not a Valve´s item.

**Comment by Luke18033** [comment]
@LautaroL20 - Errors are a valve feature. That is what I'm referring to.

**Comment by LautaroL20** [comment]
@Luke18033 - But partial block´s editoritems code in particular was performed by Carl Kenner and TeamSpen210, not Valve.
