### ISSUE TITLE
Cubes mysteriously become invisible when respawned out of the dropper with the cube coloriser.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1443]
![20170122092516_1](https://cloud.githubusercontent.com/assets/18079316/22179113/cdf1346e-e084-11e6-99aa-f5ad57a8b930.jpg)

![20170122092611_1](https://cloud.githubusercontent.com/assets/18079316/22179114/d4c9f956-e084-11e6-98d4-ac420dba83d9.jpg)

**Comment by Luke18033** [comment]
Don't use the Cube Coloriser on Overgrown. See #1402.
