### ISSUE TITLE
Add option on Partial Blocks to allow its TemplateBrush from transferring overlays

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1447]

**Comment by Luke18033** [comment]
Not sure what this means but block items can't transfer antlines anymore so I'd assume it's not relevant

**Comment by LautaroL20** [comment]
> Luke18033 said: "block items can't transfer antlines anymore"

Then that is a bug, unless Spencer did that on purpose.

**Comment by Luke18033** [comment]
It was sorta intentional, the old way it was done wasn't very good, although it will be brought back at some point probably. But regardless, the feature doesn't exist right now so it's pointless to have issues open about it.

**Comment by LautaroL20** [comment]
If that feature could be brought back at some point, then issue #3051 should stay open then. As fot this one, agreed.
