### ISSUE TITLE
PRL24 BUG - turrets do not shoot wheatley monitors 

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1448]
turrets do not shoot wheatley monitors

![preview0076](https://cloud.githubusercontent.com/assets/11165643/22185941/51e7cd96-e0bc-11e6-80dc-4a6d341b306e.jpg)

**Comment by Luke18033** [comment]
That's strange... Do you have the latest release?

**Comment by LautaroL20** [comment]
@Luke18033 - Thats why i written "PRLXX" on post titles in the past, it is useful, at least for using it the fist week release.

**Comment by TheDarkBomber** [comment]
It said "Pre release 24" anyway.

**Comment by ZombiePwner1** [comment]
How do you even get wheatley in the monitors?

**Comment by Luke18033** [comment]
Select Wheatley in the voice line chooser.

**Comment by TeamSpen210** [comment]
Try placing a camera in the map, does that change anything? (Wheatley interrupts the camera feed every once in a while...)
