### ISSUE TITLE
BTS Cube Colorizer doesn't work

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#1450]
BTS Cube Colorizer doesn't work

![preview0082](https://cloud.githubusercontent.com/assets/11165643/22185953/8366c32c-e0bc-11e6-88f1-c095a143f4b0.jpg)

**Comment by Luke18033** [comment]
Is this still an issue?

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
