### ISSUE TITLE
BTS bottomless pit texture mismatch

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#1451]
Pit inside skybox is using Modern Metal BTS Textures, area above is using Cement textures
![preview0080](https://cloud.githubusercontent.com/assets/11165643/22185961/97d7d58a-e0bc-11e6-912a-da1b6dd74ce7.jpg)

**Comment by Konclan** [comment]
Pits are being redone, this would be fixed when they are styled #87
