### ISSUE TITLE
Button Colorizer

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1452]
A Button Colorizer that works with the colorized cubes. it would make it so colorized buttons would only work with their matching colorized cubes, creating a new interesting test element. eg if you placed a yellow cube on a green button it wouldn't do anything, but if you placed a green cube on a green button it would activate the button.

**Comment by Luke18033** [comment]
This would be interesting.

**Comment by ZombiePwner1** [comment]
I'm afraid i already asked @TeamSpen210 about this and doing this will be a pain in the butt.

**Comment by Luke18033** [comment]
This would have to be implemented by re-creating the button from separate entities, and then adding a filter.

**Comment by Luke18033** [comment]
Updated comment 274361536

**Comment by Byzarru** [comment]
@TheDarkBomber is working on Blue Portals items, and I'm trying to get him to add the music cubes from the BP2 video. They have the same function, except there are only three.

**Comment by TheDarkBomber** [comment]
This can be done using `rendercolor`.

**Comment by LautaroL20** [comment]
Colorizer? Maybe you meant coloriser.

**Comment by TheDarkBomber** [comment]
Technically, coloriser isn't even a word.

**Comment by LautaroL20** [comment]
Well, then lets call it Kolorizer then.

**Comment by Luke18033** [comment]
Who cares? Just call it "coloriser". If somebody accidentally writes "colorizer", it's fine...

**Comment by TheDarkBomber** [comment]
It's Coloriser/Colouriser.
