### ISSUE TITLE
BTS Cold Fluorescent lights are too bright

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1453]
BTS Cold Fluorescent lights are too bright

![preview0081](https://cloud.githubusercontent.com/assets/11165643/22186024/75d09c50-e0bd-11e6-97e7-6ed4184962fb.jpg)

**Comment by Luke18033** [comment]
I don't see anything wrong in this screenshot.

**Comment by TeamSpen210** [comment]
They aren't actually brighter, it's a bit of an illusion since they're a different colour.

**Comment by LautaroL20** [comment]
Thats because TeamSpen210 preffer using the "Triple Light" format on them, and is same for the rest of styled lights. You can check this by open the light instance on hammer editor.

**Comment by TeamSpen210** [comment]
That's used on all lights. It makes the light radius actually rectangular, instead of a single point at the middle of the light (which looks obviously fake).
