### ISSUE TITLE
enhancement: have entire cube model colorised by cube coloriser

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1454]
instead of just the circle like seen in the clean style in Pre Release 24... have the entire cube model colorized by the cube coloriser in every style. this looks better when the whole cube is colorized

**Comment by Luke18033** [comment]
No, this would look terrible.

**Comment by Byzarru** [comment]
I'm looking at this with Blue Portals in mind, which adds colored cubes to the mix. This would make it confusing.

**Comment by TheDarkBomber** [comment]
Actually, see #1402. They look good.

**Comment by TheDarkBomber** [comment]
Anyway, this wouldn't be invalid either way, since opinions don't change the possibility that this feature could be added.

**Comment by Luke18033** [comment]
Nope, it's invalid.
