### ISSUE TITLE
Implement non-static Half Panel

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1456]
The half panel has always been static-only since it originally appeared in the tspenAddons. Is there a reason for this? And can you add a non-static version?

**Comment by LautaroL20** [comment]
There is a reason, and it is because there is not an animated model for it.

**Comment by Luke18033** [comment]
Yes there is. It just uses the vanilla panel model in a "90 degree idle end" animation. It should be pretty easy  to implement the "90 degree" and "90 degree idle" animations as well.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Come online and i agree with @Luke18033

**Comment by TeamSpen210** [comment]
The reason is that originally it didn't have a compiler, so it couldn't be static.

**Comment by TeamSpen210** [comment]
The reason is that originally it didn't have a compiler, so it couldn't be static.
