### ISSUE TITLE
Connection Signage Unstyled in P1

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1460]
![20170122162758_1](https://cloud.githubusercontent.com/assets/22107242/22187019/a5278462-e0c4-11e6-8448-5177dde6a071.jpg)

**Comment by Luke18033** [comment]
That looks pretty styled to me.

**Comment by Byzarru** [comment]
P1 styled signage has a frame around it.

**Comment by Luke18033** [comment]
Not always.
![20170122153056_1](https://cloud.githubusercontent.com/assets/19228201/22187262/d8629694-e0b7-11e6-83e8-34f88d1b31b2.jpg)

**Comment by Byzarru** [comment]
Oh yeah, that's right.
Then
REMOVE COLLISIONS ON SIGNAGE

**Comment by Byzarru** [comment]
That is a screenshot from Portal, and not BEE.

**Comment by Luke18033** [comment]
@Byzarru I agree that collisions should be removed from signage. That way, 8-positioning could properly be implemented. Who cares about collisions? If not blocking antlines is the problem, then just use a router.

**Comment by Luke18033** [comment]
Updated comment 274372207

**Comment by Luke18033** [comment]
Not actually an issue, only indicator panels and the exit signs should have signage.

**Comment by Luke18033** [comment]
Only those should have **frames**.
