### ISSUE TITLE
1960s Cold Light Strip causes failure to compile

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1463]
```
 Could not open instance file instances/BEE2/items/60s/light_strip_cold.vmf
 ```

**Comment by LautaroL20** [comment]
This is pretty weird, since 60´s should be using the 50´s instance.

**Comment by TheDarkBomber** [comment]
It's not missing. I had this problem, and the instance was in the specified path.

**Comment by Luke18033** [comment]
It's not using the 50's instance though.

**Comment by TheDarkBomber** [comment]
I even tried to use the normal light strip instance copied & renamed to `light_strip_cold`. Hint: It didn't work.

**Comment by LautaroL20** [comment]
@Luke18033 @TheDarkBomber - This was probably TeamSpen210´s fault, since he was the last one on rewoking the config code for this item after i re-skinned everything, and it worked well on all the styles.
