### ISSUE TITLE
Overgrown p-body's screen mysteriously gets bugged.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1465]
![20170123104033_1](https://cloud.githubusercontent.com/assets/18079316/22189624/a6473dd0-e158-11e6-9b7e-8186f450eb14.jpg)

![20170123104322_1](https://cloud.githubusercontent.com/assets/18079316/22189647/cb51f6d8-e158-11e6-9de9-93e9db5dba56.jpg)

And p-body is for some mysterious reason upside down.

**Comment by Luke18033** [comment]
Strange, he looks fine from Atlas' view, but he's not. Unnecessary `point_viewcontrol` maybe?

**Comment by ZombiePwner1** [comment]
It's possible to control p-body but you need to keep her inside atlas's view. https://github.com/BEEmod/BEE2-items/issues/1465

**Comment by ZombiePwner1** [comment]
And because of this strange bug it also causes this to happen.

![20170123104723_1](https://cloud.githubusercontent.com/assets/18079316/22189732/5ff8cc12-e159-11e6-9f4c-e7da69327e0a.jpg)

**Comment by ZombiePwner1** [comment]
And it's possible to control p-body just fine when in third person mode.


![20170123105327_1](https://cloud.githubusercontent.com/assets/18079316/22189854/3af8f6ca-e15a-11e6-9881-7e0a94fa5004.jpg)

**Comment by ZombiePwner1** [comment]
Now i'm getting this issue in clean style.

**Comment by Luke18033** [comment]
Seems to be fixed.
