### ISSUE TITLE
Portal Magnets are Not Working At All

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#1466]
As the title says, the portal magnets do not appear to be doing anything at all anymore.  I tried with both start enabled checked and with it unchecked.  Regardless of which way it is set, the portals do not center OR respect the rotation of the magnet.  See this vid.

https://youtu.be/ZsTz7a8QZDc

  All the single portalable surfaces have magnets on them.  The ones on the floor in front of the exit do not have start enabled checked, all the rest do.  Regardless, none of the portals center on the surface and none respect the orientation of the magnets.

**Comment by Luke18033** [comment]
I have this same problem, it's strange.

**Comment by Luke18033** [comment]
Ah, I found the problem:
![force-placement-off](https://cloud.githubusercontent.com/assets/19228201/22190699/f31dcfd6-e0d9-11e6-96e8-f66b0f957a62.png)
Force Placement was disabled in the commit that added Start Enabled, which means that portals will only align with the first portal shot.

**Comment by Luke18033** [comment]
Updated comment 274392473

**Comment by libbybapa** [comment]
You can see in the video I posted that the first shot on the *walls* goes to the correct location, but the first shot on the floor is totally wild each time.

**Comment by libbybapa** [comment]
I feel like I don't understand.  The 'start enabled' option is supposed to still force the placement at the center of the voxel, but allow 360° of rotation for portals placed in the floor/ceiling.  I don't see why an additional 'start reversed' option would be necessary.

**Comment by libbybapa** [comment]
...also, is there a way for me to update the code you posted above?  Where is that code located?

**Comment by libbybapa** [comment]
TeamSpen210, am I correct that there is no need for 'start reversed'.  Just fix the magnet to function with forced placement AND forced angle when 'start enabled' is checked and forced placement but no forced angle when 'start enabled' is not checked?  If so, then the current title does not make sense and should be changed back to the original.

**Comment by TeamSpen210** [comment]
Yes.
