### ISSUE TITLE
Catwalk ignores multiple items in one voxel

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1469]
![20170123175403_1](https://cloud.githubusercontent.com/assets/18079316/22199249/0ecec472-e195-11e6-85b0-db728da33951.jpg)

![20170123175407_1](https://cloud.githubusercontent.com/assets/18079316/22199253/1171882c-e195-11e6-9a7c-94f5832a0c91.jpg)

**Comment by ZombiePwner1** [comment]
@TeamSpen210 is this gonna be fixed?

**Comment by TeamSpen210** [comment]
I can't replicate this. Are you using two items overlapping? The compiler doesn't notice that at all, we'll want to tweak that.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Definitely not an overlap.
