### ISSUE TITLE
Implement custom staircase catwalks

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1471]
![20170123180427_1](https://cloud.githubusercontent.com/assets/18079316/22199541/72adcd5c-e196-11e6-9397-c5c7863286af.jpg)

Here is my own custom model that fits with the staircases so there for we could have a feature to add staircases connecting to this model.

**Comment by ZombiePwner1** [comment]
Okay so this is how it could work.


![20170123182319_1](https://cloud.githubusercontent.com/assets/18079316/22200196/137be974-e199-11e6-99d5-a861dba1f789.jpg)


I've made 2 blocks that are like the brushes from the puzzlemaker and this is how it would work.

**Comment by TeamSpen210** [comment]
Unfortunately, these are too short and don't align the stairs back to their 128 unit space. Extending them would just replicate the L and T junctions. Additionally I'm using modified catwalk stairs, which don't have the loops at the start/end. Those won't join to the landings at all.

**Comment by Luke18033** [comment]
@ZombiePwner1 Can you send me this model? I need it for a Hammer map I'm working on.

**Comment by ZombiePwner1** [comment]
@Luke18033 It depends you gotta add me as a friend on steam first and you must also credit me on your map to use my custom model.

**Comment by ZombiePwner1** [comment]
I have a bunch of custom rusted catwalk models that i can use for my future hammer overgrown maps that you might use aswell you just need permission to use them aswell as credit me.

**Comment by Luke18033** [comment]
I'm already using lots of custom models made by other people, who I'll be crediting in the description. I'll add your username.

**Comment by ZombiePwner1** [comment]
My steam name is >:FrozenDragon:<

**Comment by ZombiePwner1** [comment]
Or you can use the link on my github profile.
