### ISSUE TITLE
Cold Light Strip does not block portals

### ISSUE THREAD

**Issue by Konata-Chan** [BEEmod/BEE2-items#1474]
![20170123175218_1](https://cloud.githubusercontent.com/assets/25024629/22223399/946d87ea-e199-11e6-8982-aaf85ff7b290.jpg)

**Comment by LautaroL20** [comment]
Now fixed. What happened here its that the `func_noportal_volume` was an unit upper than it should be onto the grid.

**Comment by Konata-Chan** [comment]
@LautaroL20 Thanks for fix.

**Comment by Konclan** [comment]
Don't close this item, it'll be closed once the update is released. This is to let people know of the item and to make sure the same issue isn't reported multiple times
