### ISSUE TITLE
Aperture tag single player droppers do not work properly. And cubemaps fail to pack.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1475]
![20170124090604_1](https://cloud.githubusercontent.com/assets/18079316/22229757/8e4d8eca-e214-11e6-8702-5c34e3688b8b.jpg)

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Is this fixed yet?

**Comment by ZombiePwner1** [comment]
Figured out this cause happens when the entrance is removed.

**Comment by LautaroL20** [comment]
Lol, why the hell would you want to publish a map removing the entrance door anywhays? It makes sense that many things would gone weird without it wheels...
