### ISSUE TITLE
Infinite-fling stand

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1477]
_From @TeamSpen210 on September 12, 2014 10:7_

- Like in coop, two portals with placement helpers and fizzler in middle.  
- Attaches to wall, occupies + shape and is embedded as nook.
- Takes up 2 high area
- Players can control fizzler

Art therapy uses rail platform models to hold up the portal surfaces.

_Copied from original issue: BEEmod/tspenAddons#10_

**Comment by Byzarru** [comment]
Wouldn't this be easily constructed in the puzzlemaker anyway?

**Comment by TeamSpen210** [comment]
It would, but this would look much better.
