### ISSUE TITLE
Cube Funnel

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1478]
_From @TeamSpen210 on September 12, 2014 10:3_

- A set of vphysics clips to guide a cube/ball into a button
- It should take up 128x128x64 units as an octogonal cone
- Have a player trigger 3³ blocks around it to prevent players from noticing it easily.
- The model should have the cone shape as either editor/glass or a wireframe, with the the trigger as an thin block ~16 units high at the base.

_Copied from original issue: BEEmod/tspenAddons#9_

**Comment by Luke18033** [comment]
This would be useful for one of my maps, where you have to drop a cube onto a button, but it will often miss.

**Comment by quat1024** [comment]
An invisible variant of this would be super useful for maps where you have to drop a cube onto a light bridge (ex. Perambulation)

of course then you'd have to figure out how to place it free-floating which is always **super fun** in PTI lol. Not sure if extending the piston platform base is possible, or you could use the Angle property as a distance selector (like the custom fields from way back in the day, when they didn't extend the barrierhazard thingie)

**Comment by libbybapa** [comment]
I don't understand the desire/need.  Placing a funnel over a button and then placing the dropper 1 voxel to the side with an angled block or angled panel below it works fine.  Here's an example:  http://steamcommunity.com/sharedfiles/filedetails/?id=772385098

You can even add a timer to the spawning button so the funnel only stays on long enough to place the cube like in this map by Jade BGE:   http://steamcommunity.com/sharedfiles/filedetails/?id=527583403

The same can be done easily onto a light bridge.

**Comment by TeamSpen210** [comment]
This is more general, as an item to adjust flung cubes. That's a rather large contraption, and wouldn't fit in most cases.

**Comment by Luke18033** [comment]
This has basically been replaced by the trigger button.
