### ISSUE TITLE
Cores as a Futbol stylevar/variant?

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1481]
This idea is fairly simple, and probably a little silly because cores aren't that common, but to my mind its sort of makes sense of seeing the cores and their plugs as a sort of indestructible futbol.

- Futbol holders that spawn cores would be replaced with some sort of management rail that cores appear on.
- Futbol holders that don't spawn cores would be replaced with a kind of core plug and pretty much function while cores are plugged in.

There are definitely not enough textures to do all of the styles without custom models, but this would be a rather interesting gimmick for maps.

**Comment by Endermage77** [comment]
Oh, and I am currently unsure how to add a label to this comment thingy, so if anybody can help with that it would be appreciated.

**Comment by Luke18033** [comment]
@Endermage77 - I don't think this would work very well. What would it be on Old Aperture?

You need to be a member of the BEEmod organization to add labels.

**Comment by Byzarru** [comment]
~Cores wouldn't be a good alternative to Futbols (the exploding variant should be used, tho). If cores are to be implemented, they should be their own item, attached to management rails.~ I see what you mean now, but no. This would really only make sense in a couple of styles. The important mechanic is being able to throw the Futbol, and that's not something you would do with a Core.

@Luke18033 ~The key is that everything in the workshop is technically part of the multiverse, where anything is possible as long as there is an Aperture. Still, I don't expect that a lot of people have this mentality after delving the workshop a while.~ Agreed. They'd use Wi-Fi.
