### ISSUE TITLE
What happens if you try to merge branches?

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1483]
By this, I mean downloading multiple branches from the repository and attempting to merge them into the regular BEE2 editor's files.
Would anything aside from "Not Much" or "Breaks the Editor" happen?
And if yes, what?
Is there any combinations that actually yields something good?
Oh, and what exactly is the difference between the "vpk" and "vpk-cache" folders, and why the distinction?
I ask for those BEE2 users who don't actually want to bother getting themselves a github account to ask for themselves.

**Comment by Luke18033** [comment]
The branches should work fine together, but some outdated branches might not. Non-matching versions don't go well together.

The best way to test out different branches is through GitHub Desktop. See the README for how to do this.

**Comment by TeamSpen210** [comment]
Not much, you'd get the different features. That's what git is for, to allow you to actually properly merge in changes. The VPK folder here is the source files for some of those textures, the vpk-cache is a copy of the files extracted from in the zips or packages.
