### ISSUE TITLE
Conductive Plate Causes Compile Error

### ISSUE THREAD

**Issue by libbybapa** [BEEmod/BEE2-items#1486]
VBSP failed.

Valve Software - vbsp.exe (Aug 26 2015)
8 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/clean/items/cond_plate/plate_black.vmf

**Comment by Luke18033** [comment]
Put it on a white surface, that should fix it.

**Comment by libbybapa** [comment]
I tried various things (e.g. white or black surface, etc...).  I finally tried reinstalling the packages and it works fine now.  It must have been an issue on my local machine.
