### ISSUE TITLE
Descriptions for non-master branches

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1487]
At the time of this writing, the purpose of the other branches and exactly what they contain is still not all that well-defined. Currently, the only way to tell what is in a branch is with an educated guess based on what the title is.

I think that (correct me if I'm wrong) that the various branches are for testing out features before properly adding them into the master branch, either by individual feature or by author or by entire sets of features if need be,

But still, it would be nice to know exactly what the stuff in a branch does.

**Comment by TeamSpen210** [comment]
That's about it. The exception is `dev`, which has the changes that the next release will contain. `master` is the current release.
