### ISSUE TITLE
Game sometimes crashes after being minimized

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1492]
Around half of the time, when Portal 2 is minimized and reopened, the game crashes.
I dunno if this bug is BEE2's modifications to the game or just the game itself, but it is rather annoying when it happens half-way through a test chamber.

**Comment by ZombiePwner1** [comment]
It is a bug with the game itself and you don't minimize it.

**Comment by Luke18033** [comment]
Set the game to Borderless Window mode, that'll fix this problem.
