### ISSUE TITLE
Personality core / Core Rails / Core plug

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1493]
@jccreszMinecraft commented on [Wed Apr 13 2016](https://github.com/BEEmod/BEE2.4/issues/283)

A item set oriented around cores.

If the Personality core is hooked to a set of rails, it will follow the rails in the order it is hooked to other railing items. ~~If the personality core is not hooked to anything, it will spawn off a rail and fall to the ground. Core plugs will activate an output. Inputs can be made to unlock the core plug.~~

---

@Konclan commented on [Wed Apr 13 2016](https://github.com/BEEmod/BEE2.4/issues/283#issuecomment-209702254)

Oh, and you can pick the core's saying with a timer setting (Like how signage works) so you can select from a bunch of preset sayings. I don't know about core plugs though. I just imagine the core would come by a hole in the wall, say something, then leave (also emit an output once it's done). And then it would start by being activated by a trigger or something

---

@Konclan commented on [Wed Apr 13 2016](https://github.com/BEEmod/BEE2.4/issues/283#issuecomment-209702444)

I also think the core would be like an observation room sized thing

---

@TeamSpen210 commented on [Wed Apr 13 2016](https://github.com/BEEmod/BEE2.4/issues/283#issuecomment-209706209)

I'm not sure how well this would work in 1950s styles (since cores shouldn't be around in that time period). Which core it is would probably actually get set by the chosen voicelines. For Cave, Caroline and GLaDOS, perhaps it'll just not appear. (I might make a GLaDOS-core reskin..)

AI-wise: For each track point it should calculate the distance to the closest player. Then it should move to the track closest to a player, and turn to face that player. That'll work in SP and Coop quite nicely.

---

@jccreszMinecraft commented on [Wed Apr 13 2016](https://github.com/BEEmod/BEE2.4/issues/283#issuecomment-209707645)

I would say make the item unavailable in certain themes unless items are unlocked.

---

@TeamSpen210 commented on [Wed Apr 13 2016](https://github.com/BEEmod/BEE2.4/issues/283#issuecomment-209710895)

I can't (and won't) really do that. I could disallow putting it on the palette, but what should happen if you load a map which already contains them? It's actually not styles I want to switch on, but the voiceline that's chosen. 

---

@jccreszMinecraft commented on [Wed Apr 13 2016](https://github.com/BEEmod/BEE2.4/issues/283#issuecomment-209715056)

Maybe for the core, the start reversed/start enabled and cube subtypes can determine the core type

---

@TeamSpen210 commented on [Wed Apr 13 2016](https://github.com/BEEmod/BEE2.4/issues/283#issuecomment-209720348)

I'll just set it via the quote set that's selected, and also add an option to turn off voice lines entirely.

---

@SpyyZ158 commented on [Thu Apr 14 2016](https://github.com/BEEmod/BEE2.4/issues/283#issuecomment-210051085)

Maybe BTS 1980 like in Portal Stories Mel where is like Virgil out of track and as Mel you put him on?

---

@Konclan commented on [Thu Apr 14 2016](https://github.com/BEEmod/BEE2.4/issues/283#issuecomment-210055646)

I don't think having the person carry the core is a good idea

---

@SpyyZ158 commented on [Thu Apr 14 2016](https://github.com/BEEmod/BEE2.4/issues/283#issuecomment-210055961)

I meant tracks 

---

@PandaVoxel commented on [Thu Dec 22 2016](https://github.com/BEEmod/BEE2.4/issues/283#issuecomment-268757461)

@TeamSpen210 Are you going to add this in a future release as it sounds like a brilliant idea.

---

@TeamSpen210 commented on [Thu Dec 22 2016](https://github.com/BEEmod/BEE2.4/issues/283#issuecomment-268757947)

Perhaps a core on a management rail, but definitely not one that can be carried around.

---

@PandaVoxel commented on [Thu Dec 22 2016](https://github.com/BEEmod/BEE2.4/issues/283#issuecomment-268761428)

@TeamSpen210  When will the next release be out?

**Comment by Luke18033** [comment]
It looks like ZenHub doesn't do a very good job of moving issues with comments, I'll stick with the gitHub Issue Mover.

**Comment by Endermage77** [comment]
Perhaps the personality core on the rail would be determined by the timer, and the voicelines (if it isn't too complicated) would follow some logic similar to the main voice's response lines.
As for the Old Aperture problem, perhaps you can just have the management rail they spawn in on curve up sharply, indicating that they rode a management rail all the way down here, for some reason or another.

**Comment by Byzarru** [comment]
See #914.

**Comment by Byzarru** [comment]
Also, remember that PTI takes place in a multiverse. Anything is possible; the problem is that a lot of players won't suspend disbelief for an [egregious](http://tvtropes.org/pmwiki/pmwiki.php/JustForFun/Egregious) anachronism. It's ultimately up to the map designer to have the sense to not use items in inappropriate situations.

**Comment by Luke18033** [comment]
Why is this still open? It's been said multiple times that cores aren't going to be added.
