### ISSUE TITLE
Moon Base Style, Moon 3D Skybox, and Low Gravity stylevar

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1494]
_From @corrupt21 on April 6, 2016 9:1_

Kinda like this : https://steamcommunity.com/sharedfiles/filedetails/?id=78097284

_Copied from original issue: BEEmod/BEE2.4#275_

**Comment by Luke18033** [comment]
_From @Konclan on April 6, 2016 16:26_

I would really love to see this as well

**Comment by Endermage77** [comment]
And perhaps we can have a window item that lets players see outside, via putting the test chamber in a moon-skybox and the windows are placed like observation rooms.

**Comment by Luke18033** [comment]
@Endermage77 - See #1352.

**Comment by Endermage77** [comment]
Well, the thing with that version of the outside-chamber-window is that it uses a world-portal to view a separate skybox, which as has been said multiple times is a bit of a problem what with the whole rendering issue. What I mean is literally putting the entire test chamber inside of the skybox, and the window lets you see the skybox outside.
Incidentally, should I suggest this as a separate topic?

**Comment by Luke18033** [comment]
No, we could just make a custom 3D moon skybox.

**Comment by Endermage77** [comment]
Yes. And then we can put the test chamber in the skybox so we can see it with the windows.

**Comment by Luke18033** [comment]
You don't really put the map inside the skybox, it's kind of the other way around. I understand what you mean though.

**Comment by Luke18033** [comment]
The outside chamber environment system would help for this. But I think custom styles like this would be better for UCPs to implement.
