### ISSUE TITLE
Jazz Song not playing after the Voice of Announcer

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1496]
_From @SpyyZ158 on March 6, 2016 14:5_

I don't know if this is bug but when I am playing my or other's map where is announcer saying that hes gonna play Smooth Jazz then sound doesn't appear.

_Copied from original issue: BEEmod/BEE2.4#225_

**Comment by Luke18033** [comment]
_From @TeamSpen210 on March 6, 2016 19:31_

He's supposed to then play 'spark' sound FX, like the audio system is damaged.

**Comment by Luke18033** [comment]
_From @BenVlodgi on March 9, 2016 19:20_

perhaps we could get a selection of multiple jazz pieces, that the puzzler designer (human) could chose from.

**Comment by Luke18033** [comment]
_From @SpyyZ158 on March 9, 2016 20:44_

Sounds great :)

**Comment by Luke18033** [comment]
_From @towergame on March 24, 2016 18:34_

Maybe a bit of classical music too?

**Comment by Luke18033** [comment]
_From @Konclan on April 13, 2016 22:25_

oh btw https://www.youtube.com/watch?v=nDifsWZ_s5s&list=LLJ3LVjZCCyxu4ulMWcJ0TfA&index=7 is the actual song for the smooth jazz chamber, Perhaps you can have this as a normal music option. Though I don't know if people would ever be able to hear it unless they have BEE2.4 installed :/

**Comment by Luke18033** [comment]
We could just pack it. Really though it should just use the broken version from the campaign.

**Comment by TeamSpen210** [comment]
The intention is to have it not exactly copy the campaign wherever possible, so we use a different variation on the line.
