### ISSUE TITLE
Space Skybox

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1497]
Fairly simple generic Space skybox, sans cores.
Oh, and for those themes that expose themselves to the skybox, this does not produce much light, so it can simulate it being nighttime outside, for instance.

And perhaps one or two variants that feature various objects like the (non-portalable) moon or maybe even Earth.
These objects in the skybox are merely decorative and do not affect the test proper in any way.

**Comment by Konclan** [comment]
This is too far into custom themes, would make a cool UCP though
