### ISSUE TITLE
Offset Laser Emitter and Catcher models

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2-items#1499]
~This would be positioned towards the outer edge of the voxel. The model wouldn't be changed if it was placed in the center (is there any way you could make Start Reversed only appear on the `_OFFSET` versions)?~

Cube Type could be used to switch between center, and offset in 4 directions. This would work in all 5 positions, and would also be present on #1479 (although in that case the editor model wouldn't change, since it already uses Button Type).

Like this:
![20170126074141_1](https://cloud.githubusercontent.com/assets/19228201/22337984/1c1c897c-e39b-11e6-897f-0d05e8d4a522.jpg)
![20170126074255_1](https://cloud.githubusercontent.com/assets/19228201/22337991/1f1a96f0-e39b-11e6-9f99-3b71df47c39c.jpg)

**Comment by Byzarru** [comment]
What if I want an off center laser that sits on the edge of the voxel but faces the center?

**Comment by Konclan** [comment]
I don't think you need that... at that point just use a normal laser

**Comment by quat1024** [comment]
I don't think "Start Reversed" is the best property for this just because "Start Enabled" is a commonly used property on lasers and it will be confusing having both

**Comment by Endermage77** [comment]
This would probably work best as a direct item variant of the regular laser.

**Comment by Luke18033** [comment]
No. I hate splitting similar items, I prefer to combine them if possible. Having Start Reversed won't be that confusing, players will figure out what it does.

**Comment by Byzarru** [comment]
Use button type so you can switch between top, middle, and bottom and start reversed to put the laser in the next left corner.

**Comment by Luke18033** [comment]
What would probably be a better idea is to use Cube Type to switch between center, and offset in 4 directions.

**Comment by Luke18033** [comment]
The cube type thing seems needlessly complex. Maybe we should go back to using Start Reversed for this, but rather than having it offset towards the voxel edge, we have it always offset down to line up with reflection cubes. Not sure what it should do on floors though.
