### ISSUE TITLE
Missing (?) Pedestal Button Toggle from old BEE

### ISSUE THREAD

**Issue by quat1024** [BEEmod/BEE2-items#1500]
I'm using a super old version of BEE and one of my favorite items is a pedestal button that's otherwise identical to the regular one, but when you set its timer to Infinity, it acts like a toggle instead of an infinite button.

I really liked this button mode, but I can't find it anywhere in the new BEE. Can it make a comeback (pls)

**Comment by Flametusk** [comment]
You can literally connect a pedestal button with a timer to a toggle latch, and then connect that to what you want to toggle.

**Comment by quat1024** [comment]
It's not as good, because the toggle button only took up 1 item slot and
you wouldn't have to do any PTI magic to make the antline look ok

**Comment by Flametusk** [comment]
Put the toggle over what you are activating.

**Comment by Luke18033** [comment]
@TeamSpen210 - Why are you reopening this? You can just use a toggle latch, and maybe an antline magnet if the connection looks bad.

**Comment by quat1024** [comment]
TSpen and I talked over Discord which is probs why he reopened the issue

![](https://puu.sh/tCOvS.png)

**Comment by TheDarkBomber** [comment]
I think there should be the Toggled Pedestal Button. It's always a good idea to allow as many functions as possible into one item slot.

**Comment by TeamSpen210** [comment]
I might add it to the default item.

**Comment by TheDarkBomber** [comment]
This isn't implemented, this is confirmed.

**Comment by Luke18033** [comment]
Is this still planned? Having it as a separate item definitely doesn't make sense now that we have 3 different pedestal buttons already (4 if you count retracting), and all of them would probably need toggle variants. I guess it could be an item property but that would still be kind of weird having it override the timer.
