### ISSUE TITLE
Reduce embed space of observation rooms (both sizes)

### ISSUE THREAD

**Issue by quat1024** [BEEmod/BEE2-items#1501]
The 1x1 observation rooms have this *massive* 3x3x2 hitbox. Everyone who'se used PTI for any amount of time knows how goddamn annoying they are to place (and they intersect with like, literally everything)

BUT if I edit my editoritems.txt to give them just a 1x1 hitbox, maps still compile just fine. There are some edge cases if you do *really* stupid things with the observation rooms, but in general it would be really useful if I could use the smaller hitbox without having to fix up my editoritems.txt every time I re-export my Bee2 items.

**Comment by Konclan** [comment]
100% agree

**Comment by Luke18033** [comment]
The only reason this hasn't been implemented is because the walls would stick out of the sides. You'd have to be really stupid to place an observation room so that this is visible and not notice it. I think reducing the embed space to 1x1 would work fine. I'd do it myself, but I guarantee you it would get reverted...

**Comment by TeamSpen210** [comment]
Actually the problem is that in styles other than Clean, the space is used. So if you switched styles, you'd get maps that can't compile anymore.

**Comment by TeamSpen210** [comment]
@quat1024, unzip the `geometry` package, and in `items/` there's the `editoritems.txt` file you can edit. Re-zip, and the changes will persist.

**Comment by Luke18033** [comment]
It appears that this wouldn't be possible, case closed. Although I never really switch styles once I've started on a map, unless it's a test map.

**Comment by quat1024** [comment]
(It could maybe be a stylevar for Clean style only, unless having all P2C files work in all styles is a goal you're after)

**Comment by TeamSpen210** [comment]
It is. There's actually a lot of things with items to ensure that happens, like nonsolid surfaces or clips on items.

**Comment by quat1024** [comment]
> @quat1024, unzip the geometry package, and in items/ there's the editoritems.txt file you can edit. Re-zip, and the changes will persist.

Thanks! This worked great, I was hoping it would be super easy like this.

The full process I followed - 

* Extract packages/geometry.zip
* Open packages/geometry/items/obs_room/editoritems.txt
* Scroll down to the bottom where it says "EmbeddedVoxels"
* Set both Pos1 and Pos2 to `0 0 0`
* While I've got the file open might as well restore my old editoritems hax - I like to add the following in the "Voxel" group, to let antlines pass through observation rooms: 
```
"CollideType"		"COLLIDE_NOTHING"
"CollideAgainst"	"COLLIDE_NOTHING"
```
* and I also like to delete the DesiredFacing line and replace MovementHandle with this because it's ABSOLUTELY HILARIOUS:
```
"MovementHandle"		"HANDLE_4_DIRECTIONS"
```
* Save and re-zip everything into `geometry.zip`
* Delete the old geometry.zip and replace it with the new one I just made
* Open Beemod and go to File - Options and click Reset Package Caches
* Wait until Bee's finished restarting and extracting, and then click export
