### ISSUE TITLE
Whoops...

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1503]
I may have pushed a button I shouldn't have in the github desktop and I dunno what it did and I think I may have done something to the dev branch.

I am really sorry.
I hope I didn't break anything.

**Comment by Luke18033** [comment]
You're not a member of BEEmod, you wouldn't be able to do anything that would affect this copy of the repo. Clone it again, that should fix it.

**Comment by Endermage77** [comment]
Phew, thanks for clearing that up. I thought I had messed things up real bad there and I felt terrible.

**Comment by TeamSpen210** [comment]
Git is designed to make it almost impossible to actually loose data. You'd have to do a lot of things in the command line to delete stuff after they've been committed.

**Comment by TheDarkBomber** [comment]
But it is possible to delete a commit from a repository's history, it is known as **the nuclear option**.

**Comment by Luke18033** [comment]
@TheDarkBomber - I think that option exists, but I also think that's just you trying to be funny as usual calling it "the nuclear option"...
