### ISSUE TITLE
Submit proposals for BEESigns

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1504]
I am currently working on an additional set of signage for BEE exclusive items (#1093) and I need some designs for some of the items. If you are interested, submit your suggestions here and I'll re-post them with the other proposals on the original post on the BEESigns thread. After all of the designs have been filled, I'll open a survey to choose which designs will make it in the final item.

You can submit any drawing, it doesn't have to look like the finals. I will rework all of the designs once the survey is closed.

Example: These are three valid variants of a potential Closed Solid Field sign:
![image](https://cloud.githubusercontent.com/assets/22107242/22355578/fd88f0e4-e3f0-11e6-9bbe-d3875f1a4244.png) ![image](https://cloud.githubusercontent.com/assets/22107242/22355573/f462f9ce-e3f0-11e6-89dd-f465eec27bf5.png) ![image](https://cloud.githubusercontent.com/assets/22107242/22355593/16b5adb4-e3f1-11e6-8565-72205e05cabd.png)
If any of these designs are chosen, they will be redrawn to look something like this:
![image](https://cloud.githubusercontent.com/assets/22107242/22355623/49a6d0ae-e3f1-11e6-9cda-9d7f188c909a.png)

If you have an idea for an item that should be included in the signage, please list it on the original thread: #1093 22-26 still need to be filled.

Current Listing:

3. Citranium ^ (Ap:Tag)
4. Portrait of a Lady (for Art Therapy) ^(P2)
5. Rexaura HEP Deflector *
6. Rexaura Positronic Energy Orb *
7. Sendificator *
8. Futbol *
9. Turret Fire ^(P2)
10. Fire Hazard (if #1073 or a similar item is made)
11. Shredder ^(P2)
12. Material Emancipation Grill *
13. Compressed Smoke Field *
14. Force Deflection Field *
15. Closed Solid Field *°(TheDarkBomber)
16. Physics Repulsion Field 
17. Matter Inquisition Field
18. Liquid Coloring Excision Field
19. Cube Shower (as per #585)
20. Specialty Gel
21. Bumbleball
22. Josepezdj's Mechanism Sign ^
23. Autoportal °
24. 
25. 
26. 

(*) refers to custom icons being made/prototyped by Byzarru.
° refers to custom icons being made/prototyped by someone else.
^ refers to icons taken from P1, P2, or a mod

**Comment by Luke18033** [comment]
@Byzarru - Can you make a template for the signages?

**Comment by Luke18033** [comment]
Updated comment 275572698

**Comment by TeamSpen210** [comment]
Actually it might be best to make all the signs in white/black greyscale, and use that to generate the sign textures. That's what I've done for the 50s signs - using a back texture, then a front one.

**Comment by Byzarru** [comment]
@Luke18033 I think I posted the original .pptx file on the original thread, but here's the background: 
![image](https://cloud.githubusercontent.com/assets/22107242/22360625/355cce8e-e417-11e6-9776-ae7644a4aa3e.png)
It doesn't matter what the background or the format is for now, as long as it is clearly identifiable as something I can remake in the Portal 2 style. I'm probably going to end up doing as TeamSpen said, making bw textures and adjusting them to fit the appropriate style.

**Comment by TeamSpen210** [comment]
@Byzarru,
![image](https://cloud.githubusercontent.com/assets/8453732/22361689/f45a99d4-e4a7-11e6-81c6-50918454f4c9.png)

**Comment by TeamSpen210** [comment]
![image](https://cloud.githubusercontent.com/assets/8453732/22363378/bf399ac6-e4b5-11e6-91bd-0b723d9dc02d.png)

**Comment by TeamSpen210** [comment]
One sign to add is Josepezdj's "mechanism" sign. It's a pair of overlapping gears, for panels or things like that. For BTS it'll be a "automatically moving" warning.

**Comment by quat1024** [comment]
"Turret Fire" (no.9 on your list) is already implemented as sign 15, unless you're referring to a different Turret Fire sign

**Comment by TeamSpen210** [comment]
That would be burning turrets via laser.

**Comment by libbybapa** [comment]
Signs to differentiate orange or blue auto-portals would have been handy in this map:  http://steamcommunity.com/sharedfiles/filedetails/?id=845831911

It would also be very handy to have the X/check mark that lights up as a single placeable and connectable object.  This would be especially handy when using the manually placed connection signage.

**Comment by Byzarru** [comment]
I think a blue/orange differentiation icon would be great, but the signs strictly need to be black and white (though they'll be colored a bit in bp style) and symbolic.

Ed. Though the co-op exit signs are colorized...

**Comment by Byzarru** [comment]
Turret fire might probably go in the bpsigns item I'm doing for the blue portals pack.

**Comment by Alfe5** [comment]
I made a signage for Konclan; its of an auto portal. https://drive.google.com/open?id=0B9EiOVGlQRWNdUZEbGhBRWRBTE0 here is a link.

**Comment by Alfe5** [comment]
Konclan keeps wanting me to make more signage so here is one for a laser cube dispenser https://drive.google.com/open?id=0B9EiOVGlQRWNWVh6ems5aWpUYkE

**Comment by TeamSpen210** [comment]
You can attach the PNGs to the comments here..

**Comment by awesomedoctorx3** [comment]
Signage for flip panels and angled panels.
Maybe a conversion gel one, with it being a splotch of gel with a portal on it.

**Comment by TeamSpen210** [comment]
There's already Jose's 'mechanism' sign (two interlocking gears).

**Comment by WhoozYerBuddy** [comment]
Dr. A's suggestion of signage for flip and angled panels is a very good one.  The NEED for that signage is because a closed angled panel looks exactly like a flip panel until someone activates it.  Being able to communicate to the player what it is prior to them activating it so that they can factor that information into their thinking would be a really good thing.

**Comment by WhoozYerBuddy** [comment]
Please add signage for differentiating Death Fizzler inputs.  The red triangle with exclamation mark like on the emitters would work for the laser input.  A light blue rectangle for the fizzler side would work also.

**Comment by Byzarru** [comment]
Or you could just use laserfield and MEG signage...

**Comment by WhoozYerBuddy** [comment]
Laserfield is not listed as an option.  Are there plans to include signage that is not on the 'current listing'?  If so you might want to update the list.

**Comment by Byzarru** [comment]
Read #1093

**Comment by WhoozYerBuddy** [comment]
Why two threads with differing 'current listings'?  Seems either they should be updated to show the same items or one thread closed.

**Comment by Byzarru** [comment]
I did decide I won't be fielding proposals for designs anymore and never bothered to close this issue, but why post here months after this thread died?

**Comment by WhoozYerBuddy** [comment]
Why post here?  Because I did a search for open issues with the keyword "signage" and this showed up before the other one.
