### ISSUE TITLE
Turret Detector

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1509]
This was one of RADELITE's items that he implemented into BEE2 alpha in his own pack.
Is this on the to-do list?

**Comment by Byzarru** [comment]
Actually, are all of the items from the addons pack going to be added?

**Comment by TheDarkBomber** [comment]
Are the Radelite's addons going to be implemented?

**Comment by Luke18033** [comment]
@TeamSpen210 - Add Radelite Addon items to the list at #95.

**Comment by TeamSpen210** [comment]
Implemented as #2620
