### ISSUE TITLE
Gel Floor + Unpaintable Tiles

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1510]
This item is basically placed like cutout tiles, but instead it places gel.
This would be really handy for, say, racing maps, so we don't have to manually place every single blob by hand or use a paint gun to paint the entire thing as we go.
Also, it would cut down on the item count, I think.

See below about unpaintable tiles.

**Comment by TheDarkBomber** [comment]
And maybe make an unpaintable tile?

**Comment by TeamSpen210** [comment]
That's unrelated. The thing is that this item would literally replicate the normal gel item.

**Comment by Endermage77** [comment]
Actually, TheDarkBomber has a point. Unpaintable tiles would be extremely useful in say, limiting the use of conversion gel in a test.

**Comment by TeamSpen210** [comment]
It'd be good, if someone can have textures.

**Comment by Byzarru** [comment]
Glass is already unpaintable, and there's work underway to make it a more versatile item.

**Comment by Endermage77** [comment]
Yeah, but glass is also unportalable.
The unpaintable tiles could be portalable or not.
I suppose the main problem is distinguishing paintable and unpaintable tiles.

**Comment by Byzarru** [comment]
There's the paint fizzler and the lcef, but they aren't very flexible.

**Comment by Byzarru** [comment]
Make the tiles pink, because the LCEF is pink.

**Comment by Luke18033** [comment]
Are unpaintable tiles fully implemented now?

**Comment by TeamSpen210** [comment]
Indeed.
