### ISSUE TITLE
The Impossible Wishlist

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1511]
Got anything that you'd love to see but is quite frankly not possible/won't be done/would take forever to do?
Put it here!
.

**Comment by Flametusk** [comment]
Have an option to switch between regular and glass panels, a way to choose what side of a flip panel pre-placed gel is placed on.

**Comment by Byzarru** [comment]
An export option that builds your test chamber in a Michigan salt mine and notifies you when your chamber is complete as well as sends you plane tickets from the nearest airport to Lansing.

**Comment by Endermage77** [comment]
Unlimted world portals with no limitations!

**Comment by Byzarru** [comment]
A pedestal button that wipes your hard drive.

**Comment by ZombiePwner1** [comment]
This has nothing to do with beemod and these impossible suggestions are pretty much pointless.

**Comment by Endermage77** [comment]
There's no reason to dash our impossible hopes and dreams...

**Comment by Byzarru** [comment]
@Endermage77 Might I direct you to [this page](https://gitter.im/TheDarkBomber/MessAround), then.

**Comment by Luke18033** [comment]
Actually you'll want to use the #flood channel [here](https://discord.me/beemod), we're not using Gitter anymore.

**Comment by Byzarru** [comment]
thanks for bumping please

**Comment by Luke18033** [comment]
Wat? You can't really bump a thread on GitHub, issues are sorted by their issue number.

**Comment by ZombiePwner1** [comment]
@Byzarru Do not delete comments you can easily lose collaborator permissions that way.

**Comment by Luke18033** [comment]
It's fine in this case, he was just merging my comment into his.
