### ISSUE TITLE
BTS: Something? Crashes the game

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1517]
When I put <s>a bottomless pit</s> Idunnowhat into a level with BTS theme,
the game <b>compiles</b> fine, but when it tries to load the level it crashes, then shows this message with the title of Engine Error:

portalnum > numareaportals

Then, sometimes, it shows this Application Error message from GameBarPresenceWriter.exe:

The instruction at 0x00007FF6FBCF3BE4 referenced memory at 0x00007FFCC3703040. The memory could not be read.
Click on OK to terminate the program
Click on CANCEL to debug the program

If there is a fix for this, let me know.

**Comment by Endermage77** [comment]
![20170130153535_1](https://cloud.githubusercontent.com/assets/25313980/22446491/e60936ae-e701-11e6-9ce2-d3cb886c9516.jpg)
This is the Test Chamber I created that caused this bug.

**Comment by Luke18033** [comment]
That looks like an areaportal leak. It shouldn't be crashing though...

**Comment by Endermage77** [comment]
It turns out it isn't actually the bottomless pit. The game still crashed when it is removed.

**Comment by Luke18033** [comment]
Set it to entry 1, exit 1. All of the others are broken.

**Comment by Endermage77** [comment]
That actually sounds about right.
