### ISSUE TITLE
BTS Bottomless Pit crash

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1518]
It appears that when you have a bottomless pit, maxing out the height of the chamber it is in by lowering the "floor" will crash the game, without any error messages.

Miiiight just be goo pits in general and not just the bottomless pit.

**Comment by TeamSpen210** [comment]
This is very strange, since the editor has no idea pits exist. It thinks it's a goo pool.

**Comment by Luke18033** [comment]
Probably a Valve bug.
