### ISSUE TITLE
P1 CSFi does not appear

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1519]
![20170130195324_1](https://cloud.githubusercontent.com/assets/22107242/22450024/86ad6518-e729-11e6-9195-17352f5623b5.jpg)
The field does not appear or operate normally. Passing through it will erase portals.

**Comment by ZombiePwner1** [comment]
What field is this?

**Comment by Byzarru** [comment]
Closed Solid Field.

**Comment by Byzarru** [comment]
I reverted the CSFi back to its Clean model and it works just fine. It's a problem with the P1 model itself.

**Comment by TheDarkBomber** [comment]
I do not know how to fix this. The files appear to be correct.

**Comment by Luke18033** [comment]
It's just the Clean CSFi with P1 emitters, right?

**Comment by TheDarkBomber** [comment]
Yes.

**Comment by Luke18033** [comment]
Hmm. Maybe you're forgetting to pack the texture?

**Comment by TheDarkBomber** [comment]
No, it's being packed. It also acts like a normal fizzler in P1 style.

**Comment by TheDarkBomber** [comment]
Does anybody know how to fix this?

**Comment by Luke18033** [comment]
Nope.

**Comment by Luke18033** [comment]
It needs to be fixed before Pr25 though.

**Comment by Luke18033** [comment]
@TheDarkBomber - It's probably an issue in the VBSP config.
