### ISSUE TITLE
Remove sparks from Physics Repulsion Field

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1523]
_From @Luke18033 on December 6, 2016 21:8_

The original version didn't have this, neither do any of the other physics-blocking fizzlers.

_Copied from original issue: TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#7_

**Comment by Byzarru** [comment]
I actually find this quite useful in a test I'm making right now. It's a good cue for location.

**Comment by Luke18033** [comment]
How? It's just some random spark effects, which Felix Griffin's original version did *not* have.

**Comment by Byzarru** [comment]
Random spark effects? I'm only getting them when an item is touching the field.

**Comment by Luke18033** [comment]
I know, but they are:

"*Annoying, annoying, annoying, annoying, annoying, annoying...*" - Wheatley (Lego Dimensions)

**Comment by Luke18033** [comment]
Bump

**Comment by TeamSpen210** [comment]
What would be ideal is to hack it into having the fizzler glow effects around cubes placed on the field. I haven't quite figured out how to do that though, I'd basically need to use hidden variables on the field to send in the positioning.

**Comment by Luke18033** [comment]
Whether intentional or not, these seem to have been removed, so this issue can be closed.
