### ISSUE TITLE
Use Start Enabled to silence Pedestal Button and Delayer sounds

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1524]
The title says it all.

**Comment by Byzarru** [comment]
Also for timers.

**Comment by Luke18033** [comment]
This is now done automatically when connections are hidden, isn't it?

**Comment by TeamSpen210** [comment]
It is, not 100% sure for pedestal buttons though.

**Comment by Luke18033** [comment]
This exists for pedestal buttons now as well.
