### ISSUE TITLE
Implement the Scalable Cube

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1525]
This is seen in the Portal 2 In Motion DLC. Since the required motion controls aren't present in the main game, this would be given new controls:

- Left click + move mouse: scale cube
- Right click + move mouse: rotate cube

Also add a stylevar to show help text, like with the Sphere Cannon.

**Comment by TeamSpen210** [comment]
I don't think it's possible to recreate that, it has special code to allow resizing it.

**Comment by TheDarkBomber** [comment]
Maybe the ECHO device could be added. It was in the BP Extended Play, and it is originally from PUNT.

**Comment by Luke18033** [comment]
That has nothing to do with the Scalable Cube.

**Comment by TheDarkBomber** [comment]
As "motion controls" for regular cubes.

**Comment by Luke18033** [comment]
Not really...
