### ISSUE TITLE
PRF not packing

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1526]
I am making a map with extensive use of the Physics Repulsion Field. I sent it to someone else to play it, and the PRF appears as a white block to them. The CSFi looks fine.

![image](https://cloud.githubusercontent.com/assets/22107242/22494193/1938b8de-e7fb-11e6-9458-180665548a75.png)

**Comment by Luke18033** [comment]
I don't really like the name "Physler", it's pronounced just like "Fizzler" which can be confusing.

**Comment by Byzarru** [comment]
Let's discuss the difference between written communication and verbal communication! 

Let's not. I'm just using 'Physler' as a convenient abbreviation. (When I first saw it, I pronounced it "fize-ler")

**Comment by Flametusk** [comment]
I thought it was pronounced fizzler on purpose. So...

**Comment by ZombiePwner1** [comment]
@Byzarru It's appearing white as it's missing the texture lol.

**Comment by TeamSpen210** [comment]
I prefer Physler for everything. Actually that's the reason for this, everyone wanting different names.
