### ISSUE TITLE
Aperture tag coop causes a compile error.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1527]
x86)/Steam/steamapps/common/Aperture Tag/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Aperture Tag/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Jun  4 2014)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Aperture Tag\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Aperture Tag/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/clean/elevator_coop/entry_fizz_tag.vmf
 | 
 |_

[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

**Comment by TeamSpen210** [comment]
@ZombiePwner1, don't add styles unless you've actually checked it applies, and isn't a different issue.
