### ISSUE TITLE
Lifeform Sensor

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1529]
I had a idea for a Laser Trip Wire Field, it would be a fizzler that would be a grid of green lasers that would activate whatever it is connected to when a player passes through it. 

@TeamSpen210 - have you implemented the ability for fizzlers to have a trigger that would send outputs yet

**Comment by TheDarkBomber** [comment]
Yes, he has.
And this would be the Lifeform Sensor, which was a BEE2.2 item, so this will already be implemented (but different).

**Comment by Luke18033** [comment]
It was originally from Portal Pro.

**Comment by TheDarkBomber** [comment]
This is confirmed. See #490.

**Comment by Luke18033** [comment]
@TheDarkBomber - ***The Lifeform Sensor isn't a Rexaura item!!!!***

**Comment by TheDarkBomber** [comment]
No, @TeamSpen210 said it would be at the bottom comment.

**Comment by Luke18033** [comment]
Since this would require the Fizzler Output Relay to work, how about adding a timed variant as well? So you walk through the field, and *x* seconds later the output turns back off.

**Comment by TeamSpen210** [comment]
That's implemented for the Rexaura one, and I'd implement it for this too. I need to play Portal Pro to figure out what it looks like and functions though.
