### ISSUE TITLE
New Item: T-Flip Flop Plate

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1531]
Similar to the Conductive Plate, except the logic would be a t-flip flop and the plate would activate and stay activated if a cube touched it, and would deactivate if a cube touched it again. a delay would coded in the logic to prevent it from looping between on and off instantly when a cube touched it.

**Comment by TheDarkBomber** [comment]
Use the SR latch.

**Comment by Luke18033** [comment]
Not the SR latch, but the toggle latch.
