### ISSUE TITLE
Migrate bottomless pit files into skybox package

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1532]
A Suggestion for long term: Migrate all the Source files for bottomless pits into their own package so each one can call upon the style and resources needed etc when used. would be useful for making new pits without having to extract the packages of and modify every style and also could make some pits compatible across multiple styles. This would also make voluntary contributions for bottomless pits easier... this will definitly be long term because it will involve a lot of rewiring and changes to the bee2

**Comment by TeamSpen210** [comment]
Pits are seperate to their style...

**Comment by ellingtonvengaboysmuseum** [comment]
i was talking about moving the source files for bottomless pits from each style package that has one to a 3D skybox package etc.

**Comment by TeamSpen210** [comment]
No.
