### ISSUE TITLE
[Mysterious] PRF appearance/action discongruity

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1533]
![20170203170101_1](https://cloud.githubusercontent.com/assets/22107242/22612583/38488c84-ea37-11e6-9ca6-d62cfced7146.jpg)
This PRF is on. It works. It just doesn't want to show it. It's a bit shy.
It usually blinks out once another PRF shuts off. Sometimes, it will dim, and sometimes, it will appear as it normally should.

Ed. Waiting for the "Mysterious" label

**Comment by TeamSpen210** [comment]
Does this still happen?

**Comment by Luke18033** [comment]
Yep, and I won't be able to release my next map until it's fixed.

**Comment by Luke18033** [comment]
Now fixed I think?
