### ISSUE TITLE
Quicksand

### ISSUE THREAD

**Issue by mario2582** [BEEmod/BEE2-items#1535]
@TeamSpen210 or @BenVlodgi have you implemented what would be required to create a custom goo pit yet (adding custom triggers etc and setting position and thickness etc

i created a custom item in hammer a few years back that was a custom goo pit with custom textures, it had several triggers in it to simulate quicksand. they are in order

- a invisible trigger push that was tied to players only and just strong enough for players to slowly sink through it
- a invisible trigger push that was tied to physics and cubes only and just strong enough for cubes to slowly sink through it
- a invisible piston platform that was set 1/4 of a voxel from the surface of the pit that slowly lowered if a player or cube was in  the pool and activated it's trigger and standing on it. this gives the player a chance to jump back out before it's too late. if the player jumped off it, and it deactivated, it would lower to the bottom of the pit to simulate real quicksand and the player would sink faster from struggling.
- at the bottom was a thin trigger hurt that was positioned at the right point so the player would touch it and die when completely submerged under the quicksand.

is there any trigger to detect player movement that only activates when a player moves in it.

this item is complex and long term, but lets see if we can get it done...

**Comment by ZombiePwner1** [comment]
@ellingtonvengaboysmuseum I don't think quick sand will be possible to implement.

**Comment by ellingtonvengaboysmuseum** [comment]
if it can do it in hammer, and teamspen can create custom goo pits, it might be able to be done in bee2

**Comment by ZombiePwner1** [comment]
Do not be too sure i don't think it's possible to create quicksand in hammer.

**Comment by Byzarru** [comment]
It shouldn't be "Quicksand." It doesn't fit the aesthetic. Maybe "Foam Pit?"

**Comment by Byzarru** [comment]
Is this something that will kill the player when they are submerged or once they hit the bottom? I can think of an interesting application of this item.

**Comment by ellingtonvengaboysmuseum** [comment]
it will kill them when they go under completely

**Comment by Byzarru** [comment]
It should probably only be quicksand in Old Aperture. In P1 and later, it should be some sort of science gook.

**Comment by TeamSpen210** [comment]
How is this related to Portal?

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 - it's a liquid the player can enter without immediate death like water, but unlike water if the player stays in it too long and goes under it becomes deadly.

**Comment by Luke18033** [comment]
Doesn't seem particularly useful.
