### ISSUE TITLE
Fizzler brushes with texture between fizzlers.

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1536]
Sides of Fizzler textured underground, valve makes this invisible in the regular game. this doesn't look right

![preview0114](https://cloud.githubusercontent.com/assets/11165643/22615116/cefc4c8c-ea5b-11e6-9b43-140c9b347c9c.jpg)

especially on the one i'm working on now...

![preview0113](https://cloud.githubusercontent.com/assets/11165643/22615118/d2234654-ea5b-11e6-960c-18724fc275cd.jpg)

**Comment by TeamSpen210** [comment]
This is intentional, so you can see fizzlers from side on.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 This needs to have nodraw applied to them.

**Comment by TeamSpen210** [comment]
Maybe between fizzlers.

**Comment by TeamSpen210** [comment]
Those fizzlers are also wrong.

**Comment by ZombiePwner1** [comment]
yes we need the nodraw texture applied to them.

**Comment by TheDarkBomber** [comment]
![](https://cloud.githubusercontent.com/assets/11165643/22615118/d2234654-ea5b-11e6-960c-18724fc275cd.jpg)
This is the PRF, you are not working on it. You must have got confused with the one from the Development Version.
