### ISSUE TITLE
Reversible Sendificator

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1537]
Why not add a "Start Reversed" tag to the Sendificator that, if enabled by default or by activation, teleports whatever the connected laser is touching to the sendificator pad instead of the other way around?

**Comment by TeamSpen210** [comment]
I don't want to alter this item, and it'd be confusing.

**Comment by Luke18033** [comment]
@Byzarru suggested this before on Gitter, but as a separate item called the Grabificator.

**Comment by Byzarru** [comment]
Yes! The GRABIFICATOR. It would teleport any item the laser touches to you!
(Or maybe it can be a total opposite of the Sendificator and use the HEP to hit items)

**Comment by Endermage77** [comment]
We could do that.
But if we wanted to use the laser still without confusion, I suppose having the Grabificator as a separate item would be ideal, in addition to perhaps making it look different.

**Comment by Byzarru** [comment]
The biggest problem with using the laser is the reflection cube: What if you want to grab a reflection cube?

**Comment by Endermage77** [comment]
Sounds good.

**Comment by Byzarru** [comment]
In this case, I propose two items. One is the "**Pullificator**," which 'pulls' the farthest item connected to a laser. The other is the "**Grabificator**," which 'grabs' whatever item is hit by a specialized HEP.

**Comment by Endermage77** [comment]
But isn't the current Sendificator already yellowish-green?
How about purple and orange? Those would stand out a bit more when compared to the standard.

**Comment by Byzarru** [comment]
The beam is green, but not the accents on the Sendificator itself. The beams should be different colors, though.

**Comment by King0191** [comment]
If I could suggest,
Perhaps for the Grabificator there could be a Blue HEP and then an alternate Red HEP. The Red Hep would act as such. 
You put an item into the Grabificator's slot and the Red HEP is set out and you press a button, the HEP explodes and the item appears in its location. (Similar to how the Displacement Device works with the player in the mod Portal 2: Displacement

**Comment by ZipZoptheCat** [comment]
Sendificator is indeed an mspaint adventures reference and as such the opposite device should be named appearifier to be in keeping with that reference.

Also I can see wanting to use re direct cubes as part of the puzzle and it being frusterating if you can't. Last object hit seems like the best solution because you can always make sure the cube is facing a different direction.

**Comment by Konclan** [comment]
#2951
