### ISSUE TITLE
permission granted to migrate mel resources into bee2

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1540]
i asked the creators of portal stories Mel for permission to use the resources from mel in bee2 so they would work in the original portal 2 because Mel doesn't have the PTI editor. they said we can use them and recommended it. there is no point in making music files for mel that only work with mel if it doesn't have PTI available.

what needs to be done here

- [ ] port the music so the files come with bee2 and get packed into maps made with the original p2
- [ ] port the voice lines of each character
- [ ] port Mel's portal gun with a new style var (if possible)

**Comment by Luke18033** [comment]
The voice lines couldn't be done well - they wouldn't be translated to the user's chosen language, and there wouldn't be subtitles. Everything else would work though. Possibly also a Mel player model, but I don't know if that would be possible.

**Comment by TeamSpen210** [comment]
The other main reason for not including the music files is that they're big files. Reusing them from the mod keeps the file sizes down.

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 - one problem, the mel mod doesn't have PTI.

**Comment by ZombiePwner1** [comment]
@ellingtonvengaboysmuseum PS:M does have the puzzlemaker actually.

**Comment by TeamSpen210** [comment]
It's broken though, it wouldn't work and wouldn't do anything different.

**Comment by ZombiePwner1** [comment]
![20170127190857_1](https://cloud.githubusercontent.com/assets/18079316/22623456/b7ca6fe4-eb96-11e6-82b6-ec089866edf9.jpg)




![20170128081019_1](https://cloud.githubusercontent.com/assets/18079316/22623459/bef5b62a-eb96-11e6-88f6-d2ee41b7b578.jpg)

**Comment by ZombiePwner1** [comment]
Yes it might be broken but i actually managed to fix the compiling.
![20170127205107_1](https://cloud.githubusercontent.com/assets/18079316/22623468/d2664d14-eb96-11e6-9078-f0dfbd8aada3.jpg)

**Comment by TeamSpen210** [comment]
What I mean is the current feature - when PS:Mel is also installed, the BEE2 extracts the music and lets you use it.

**Comment by Byzarru** [comment]
If using PS:Mel resources is okay, what about using the turrets? (#205)
And apparently adding the PS:Mel gun is impossible. (#14)

**Comment by ZombiePwner1** [comment]
@Byzarru The mel gun is impossible since you can't pack pak01 files into a map.

**Comment by TeamSpen210** [comment]
No it's not, mostly..

**Comment by TeamSpen210** [comment]
This has been done already.
