### ISSUE TITLE
BTS mysteriously plays GLaDOS voicelines even if you don't have any voicelines selected.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1542]
@TeamSpen210 What's going on here?

**Comment by Luke18033** [comment]
BTS is very broken, that's what's going on :P

**Comment by Flametusk** [comment]
What else is new?

**Comment by TeamSpen210** [comment]
This would be because the logic is still in the spawn room and exit, since they're still the original StyleChanger Clean.
