### ISSUE TITLE
Universal Colourizer

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1544]
While being able to color cubes is nice, the Colourizer could potentially have other applications, such as:
- Laser
- Light Bridge
- NOT the Excursion Funnel becasue it changes colors with polarity (to avoid confusion)
- HEPs
- Futbols
- Buttons (For cube-button matching)
- Turrets
- Laser Relay/Laser Catcher/HEP Catcher/Futbol Holder (For aforesaid matching)
- Glass/Grating if it wasn't too much of a bother
- Faithplate/Target for being able  to tell which goes where when there's a lot of them
And generally usable for the sake of distinguishment.
I realize that probably at least some of the items above won't be done, but what items that can would be nice.

**Comment by Byzarru** [comment]
* NOT HEPs because there are two variants (yellow and green).

**Comment by TeamSpen210** [comment]
I can't colour any of the beams and whatnot.
