### ISSUE TITLE
New Style: The Under

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#1547]
a variant of a BTS / Underground style. i call it "The Under"

it takes place at the bottom of the modern testing tracks in the sealed off area wheatley was talking about in the tube ride. it takes place between the bottom of the modern tests and top of the underground testing tracks. 

it would use a combo of textures from 80's style, portal 1 bts, and the current bts. gel tubes would be underground versions and cube droppers would be overgrown variants.

it would have bottomless pits similar to the ones in bts, except they would be glowing red hot due what is below them. glados says this is where the nuclear reactor is that powers modern aperture which is why test subjects can't enter this area due to radiation levels.

**Comment by Endermage77** [comment]
I would imagine that this style would sort of segway into the Reconstructing style rather than stand all by itself. 

That aside, we only ever go through The Under twice in all of Portal (Including Mel, TWTM, & Tag.)

**Comment by Luke18033** [comment]
The sealed-off area Wheatley was talking about *is* Old Aperture.

**Comment by ellingtonvengaboysmuseum** [comment]
@Luke18033 - this style takes place between old aperture and that area above where the bottom of the test chambers are. the explanation will be glados discovered some stuff in the area that seals off old aperature

**Comment by TheDarkBomber** [comment]
So, the 1980s.

**Comment by Endermage77** [comment]
Not exactly the 1980's.

Do you remember that bit after you open the masssive vault door in the ceiling and there's giant stilts as far as the eye can see supporting modern Aperture above?

Or the Junkyard zone in Mel?

THAT is the Under zone.

**Comment by ellingtonvengaboysmuseum** [comment]
@Endermage77 - not exactly, it's between test shafts of the 1980's and the area where the bottom of modern aperture, it's in a area that is completely sealed off and no where near a vault door.

**Comment by Flametusk** [comment]
It's like the ending test of the momentum course in the co-open, with the giant fan.

**Comment by TheDarkBomber** [comment]
So, it's JUST underneath modern aperture, like @Endermage77 said. Ok, then.

**Comment by ThatOneRetro** [comment]
*cough cough*

**Comment by Luke18033** [comment]
We're not doing new custom styles
