### ISSUE TITLE
New Custom Style: Freezer

### ISSUE THREAD

**Issue by Electricianfromhell** [BEEmod/BEE2-items#1548]
I had a idea for this one myself a while back. i will definitely need help creating it. it is a variant of clean style except the test chamber is a freezer and all the clean wall textures would be altered and have a frosy overlay added to them. 

@TeamSpen210 i will definity need your help creating this one...

i need to know what i need to extract the image files from portal 2 used for the clean style

i will need to know what to do to setup the custom textures with the coding in the vbsp for the style.

i will need to know what i would need to extract testing element models to create custom frosty skins for them.

**Comment by Konclan** [comment]
What about holiday themes

**Comment by ellingtonvengaboysmuseum** [comment]
here are some preview textures of the frozen clean textures

![portal_2_wall_texture_white ice](https://cloud.githubusercontent.com/assets/11165643/22630130/006fcc14-ebc2-11e6-8acb-a789dcfb0f7d.jpg)

![dark texture ice](https://cloud.githubusercontent.com/assets/11165643/22630131/03ade0c8-ebc2-11e6-8673-c9d2e739ad95.jpg)

**Comment by Endermage77** [comment]
That's some spooky dark wall texture.

If you've got a non-ice-coloured version of that we can start doing the Aperture Science Halloween Testing Initiative!

**Comment by ZombiePwner1** [comment]
Ummmmmm i don't see the point of this type of style unless it can be like a christmas themed style.

**Comment by Luke18033** [comment]
Doesn't look like this really went anywhere.
