### ISSUE TITLE
New Stylevar: Wall and Ceiling texture picker for overriding default

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1549]
i just though of this. a Wall and Ceiling texture picker for overriding the default style wall and ceiling textures chosen.

this would come in handy for creating styles like reconstructing or making a mixture of textures from different styles such as overgrown and clean textures for some reason if needed.

**Comment by TeamSpen210** [comment]
It's a lot more complicated than that.
