### ISSUE TITLE
Trigger Multiple causes compile failure

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1550]
_From @BlackTiger63 on February 5, 2017 18:40_

I'm using Bee mod 2.4 residing in D:\BEE2.4 directory.
Installed like it should be with additional items, no problem there.

Until yesterday afternoon my map compiled fine. Then yesterday evening I finished the map and then it starts compiling and just at the end of the first line (building geonometry) it says "there was an error building the puzzle".
I already tried removing vrad and vbsp files and verify cache but problem persists. Maybe I used too many items in the puzzle? So I removed a few and made a hallway smaller but the same problem occurs.

This is what I got from the developpers console where the error occurs:

> [INFO] vbsp.run_vbsp(): Arguments: "D:\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "D:/Steam/steamapps/common/Portal 2/portal2/" "D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 6 threads
 | materialPath: D:\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/BEE2/logic/bee/trigger_multiple.vmf
 | 
 |_
[INFO] BEE2_config.save(): Saving changes in config "D:\BEE2.4\config/compile.cfg"!
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

How can I fix this?

_Copied from original issue: BEEmod/BEE2.4#515_

**Comment by Luke18033** [comment]
It's a missing instance for the Trigger Multiple, but triggers shouldn't use instances anymore...

**Comment by Luke18033** [comment]
_From @BlackTiger63 on February 5, 2017 18:50_

You're surely correct, but I have no clue how to fix this. Or what's causing it. Because it went fine yesterday afternoon. I did make some multiple trigger things yesterday evening. But I don't know anything about instances or such, I'm no programmer. :)

**Comment by Luke18033** [comment]
Neither do I. Remove any Trigger Multiples in the map for now.

**Comment by TheDarkBomber** [comment]
Is the instance named trigger_multiple_ghost instead? Because that might be the problem.

**Comment by BlackTiger63** [comment]
I don't know how can I find out? I do have trigger ghost files (multiple, autosave and once) in this directory:
D:\Steam\SteamApps\common\Portal 2\sdk_content\maps\instances\bee2\logic\BEE

Strange thing happened. I removed 1 multiple trigger, and 3 trigger once. Tried compiling and I got passed the geonometry and the second bar was building so I cancelled the build.
After that I exited, discarding changes. Launched the editor again, same file, removed the same triggers and got the same error again.

Do I need to delete the trigger_multiple(once and autosave)_ghost.vmf files?

**Comment by TheDarkBomber** [comment]
Just rename it from `trigger_multiple_ghost` to `trigger_multiple`

**Comment by TeamSpen210** [comment]
No. That's not the issue, the ghost instance is for something else. There's a problem with the compiler generating the triggers.

**Comment by BlackTiger63** [comment]
Tried that, exported again. Same error occurs. :(
Strange thing is, they're all called ghost again so that won't help indeed.

**Comment by BlackTiger63** [comment]
An addition. If I remove all 3 multiple triggers, I get the same error but for the "once" triggers, like this:

> ConVarRef gpu_level doesn't point to an existing ConVar
| Could not open instance file instances/BEE2/logic/bee/trigger_once.vmf

After that I removed 3 of the 8 "once" triggers and then it will compile. Very odd.
I need at least 2 multiple triggers though and 2 of the once which were removed.

**Comment by ReikaKalseki** [comment]
I just started getting this too, on a level which WAS able to handle the triggers fine until a minute ago.

**Comment by BlackTiger63** [comment]
I still have the test map which caused this error. I released the map minus 1 multiple and minus 2 or 3 single triggers and then it compiled again.
The map is big though, I don't know if the combination of map and amount of triggers also can cause these errors.

**Comment by TeamSpen210** [comment]
I need to ensure the trigger code can't leave behind instances without connections, or with bad ones.

**Comment by BlackTiger63** [comment]
So why is this closed again since it's not solved?
Do I need to provide other information or why is it closed?

**Comment by Luke18033** [comment]
It's not...

**Comment by BlackTiger63** [comment]
Ah no sorry, it was the referenced one which was closed, sorry, my mistake.

**Comment by Luke18033** [comment]
I think this was fixed with the connections overhaul.
