### ISSUE TITLE
"Fire" Gel

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1552]
A red gel that, when contacted with, deals fire damage to whatever touches it.

For all intents and purposes, this would only affect players and turrets.

Failing that, just some sort of damage/kill gel of any kind.

**Comment by TheDarkBomber** [comment]
Can't add custom gels. But the Fire Cube will be added as part of the BP Pack. (#1514)

**Comment by Luke18033** [comment]
Gel is supposed to help the player anyway. A deadly gel wouldn't make much sense.

**Comment by Endermage77** [comment]
I suppose what I'm asking for here is some sort of deadly gel, yes. It would mainly serve as a map obstacle, say, a more other-object-in-the-same-spot-friendly sort of hazard that would be mainly placed manually.
And I suppose fire gel in particular would be handier for the player as it could theoretically set fire to and destroy turrets.

**Comment by TeamSpen210** [comment]
Unfortunately it can't be implemented.
