### ISSUE TITLE
Voiceline: The Underground AI

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1555]
I'm certain at least one person here aside from myself remembers [this  short youtube show](https://www.youtube.com/watch?v=NVIlcXn64bo) that machinima ran for 6 episodes and then just stopped? 

Anyways, in Epsiode 2 they introduce the old AI mainframe which is unique to this show.
<b>If a person to obtain permission from to implement him as a voiceline can be found and approves</b>, he could serve as another voice to listen to during the test chambers.

If the response to this is "Absolutely no way," I understand.

**Comment by Byzarru** [comment]
Can't because the voicelines can't be dubbed and subtitled correctly. There aren't too many of his lines that are related to testing, anyway.

**Comment by Endermage77** [comment]
Actually, in terms of voicelines it seems that the voice actor for the Mainframe happens to be good old Harry Callaghan.
Perhaps if he isn't too busy doing his stuff and accepted the request he could do a few lines...

**Comment by Byzarru** [comment]
It still wouldn't make it into BEE, for the simple reason above. That's for any voice line. Now, music is another story. Can you pry some custom tracks from him? ;P

**Comment by Endermage77** [comment]
Not me, no. I'm just a humble commentor.
