### ISSUE TITLE
Linked Cube Can Be Different Type?

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#1559]
It's a bit of an oddity and I'm not sure whether it is a good or bad thing...  You can have the dropperless cube be of one type and the dropper set to drop a different type.  Seems like they should have to be the same type.

**Comment by TeamSpen210** [comment]
I'll make it force both cubes to be the same, it's just that the code doesn't right now recognise easily the type of the cube.

**Comment by libbybapa** [comment]
It's certainly easy enough for the map maker to match the types so it's not a pressing issue.  I just thought it was funny when I fizzled a reflective cube and a standard one popped out.

**Comment by TheDarkBomber** [comment]
That would be a Cube Transmuter.

**Comment by libbybapa** [comment]
No one said anything about a Cube Transmuter?  I'm not asking for this functionality, I'm pointing out a minor bug.

**Comment by TheDarkBomber** [comment]
Ok.
