### ISSUE TITLE
help needed with custom fizzler texture

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1560]
@TeamSpen210 - i need help to make the custom grid texture in the fizzler on the right not be stretched out horizontally and be like the one on the left. what do i put in the vbsp config to fix this...

![preview0019](https://cloud.githubusercontent.com/assets/11165643/22706331/d6c1e696-ed3c-11e6-8978-ccb1da34032c.jpg)

**Comment by TheDarkBomber** [comment]
What fizzler is this?

**Comment by ellingtonvengaboysmuseum** [comment]
@TheDarkBomber - the force field, it won't let anything pass through including, lasers, players, cubes, HEP's, light bridges, paint, turrets and their bullets too, funnels, portals and portal shots, pretty much everything.

**Comment by TheDarkBomber** [comment]
Oh, you mean the Closed Solid Field, that is already going to be implemented in the next Pre-release, PR25, that already has a wiki page on it located [here](https://github.com/BEEmod/BEE2-items/wiki/Closed-Solid-Field)?

**Comment by Luke18033** [comment]
So, the Closed Solid Field?

**Comment by ellingtonvengaboysmuseum** [comment]
paint doesn't adhere to the force field, because painting fizzlers becomes really glitchy. good luck with the CSF, the force field also makes HEP's explode on contact...

**Comment by Luke18033** [comment]
No need to create duplicate fizzlers, case closed.

**Comment by ellingtonvengaboysmuseum** [comment]
@TheDarkBomber - and it also reflects lasers off it with a invisible layer of reflection gel

**Comment by TheDarkBomber** [comment]
Ok, that should just be a separate fizzler. And it's the Close/Open fight!

**Comment by ellingtonvengaboysmuseum** [comment]
@TheDarkBomber - don't close it, i need @TeamSpen210 help with the grid texture issue...

**Comment by TheDarkBomber** [comment]
There's already a texture for the Closed Solid Field. CASE CLOSED!!

**Comment by Luke18033** [comment]
If you need help with development, don't open an issue. See the [BEE-Development chat](https://gitter.im/BEEmod/BEE-Development).

**Comment by Konclan** [comment]
@ellingtonvengaboysmuseum Do you have discord? I know teamspen is on that, talk to him personally

**Comment by Luke18033** [comment]
I found this texture in Portal Project Beta's files, is this what you're using?
![image](https://user-images.githubusercontent.com/19228201/27088837-a52bbaf6-500d-11e7-84f6-cb05afaf2560.png)

**Comment by Luke18033** [comment]
Does this work correctly now? Using a hexagon design for the CSFi could look nice, currently it's just a recolored MIF I think.
