### ISSUE TITLE
Many Portal 1 and Rexaura Bugs.

### ISSUE THREAD

**Issue by Alfe5** [BEEmod/BEE2-items#1562]
* [x] When "Pellets Destroy Cubes" is ticked, only the first weighted cube acts accordingly. Other cubes are not fizzled.
* [x] Particle effects of the Positronic Energy Orb are not centered.
* [x] White Hole Lights give off a fraction of light they are supposed to have.
* [x] ~Angled wall panels when extending outwards sometimes don't kill you and you get stuck.~ They shouldn't do this. If they do, it's a bug.
* [x] Corridor 1 has a weird lighting glitch.
* [x] Energy Pellets move way too fast to create any Rexaura item based puzzles.

(All bugs were found in the most recent version of Bee2)

**Comment by Luke18033** [comment]
I've previously opened an issue about P1 lights being too dark (#1112). HEP speed is probably a Valve bug - HEPs are already fully implemented into vanilla Portal 2, all BEE2 does is pack the texture. But then, BEE2.4 does make it so HEPs can pass through grating, so maybe I'm wrong?

**Comment by Luke18033** [comment]
Also, angled panels should never kill you, only fizzle cubes.

**Comment by TeamSpen210** [comment]
The speed is an option on the entity. I'll need to do some analysis on Rexaura and Portal 1 maps, to see what speeds they use.

**Comment by TeamSpen210** [comment]
When moving outwards, angled panels never hurt you.

**Comment by Alfe5** [comment]
panels do hurt you if you stand in their way. I tested it plenty of times

**Comment by Luke18033** [comment]
Piston panels, but not angled panels...

**Comment by Alfe5** [comment]
angled panels in 1x1 voxel corridors coming out of the wall squash you. I will record evidence tomorrow

**Comment by TeamSpen210** [comment]
Energy pellets are way way too fast. Here's a list of the speeds in Portal 1:

Chamber | Launcher Name | Speed
---- | ----- | --------
3 |  ceiling_energy_ball_launcher_lvl4 | 200
3 |  energy_ball_launcher_a03_2 | 200
4 |  energy_ball_launcher_lvl5 | 200
7 |  launcher_energyball_rm6 | 300
8 |  energy_ball_launcher_lvl7 | 200
9 |  energy_ball_launcher_lvl7a | 200
10 |  energy_ball_launcher_a_rm8 | 400
10 |  energy_ball_launcher_rm8 | 400
10 |  ball_launcher_b_rm8 | 400
10 advanced |  energy_ball_launcher_a_rm8 | 175
13 |  energy_ball_launcher3_lab5 | 350
13 |  energy_ball_launcher2_rm8 | 400
13 |  energy_ball_launcher1_rm8 | 400
14 |  energy_ball_launcher | 250
14 |  lab4_energy_ball_launcher1 | 225
15 |  energy_ball_launcher_rm8 | 400
15 |  launcher_energyball_rm6 | 400

All Rexaura pellets have a speed of 300. But the BEEmod ones have a speed of 500.

**Comment by TeamSpen210** [comment]
I'll make it match Rexaura (300), and eventually let you set the speed.

**Comment by HugoBDesigner** [comment]
I would really appreciate if you could allow for a slightly greater range of speeds, mostly slower pellets (100). Additionally, would be nice to have their lifetime easier to adjust. Right now, at "3 seconds", they still last too long for some puzzles, so a broader timing range would be appreciated

**Comment by TeamSpen210** [comment]
If you edit the properties in the right-click window, you can give them a default of 1 or 2 seconds and get those that way.

**Comment by HugoBDesigner** [comment]
Actually, disregard the timing issue. I figured my problem was the lifespan increase when the pellet went through a portal, not necessarily the lifespan it has when launched. My bad

**Comment by TeamSpen210** [comment]
That can also be changed actually, maybe I should make pellets which start with <6 seconds not go above their original value.

**Comment by HugoBDesigner** [comment]
Oh, that'd be quite handy actually!
For curiosity, how much does going through portals add to the lifespan? If I'm not mistaken, it was 20 seconds in Portal 1 (although, thinking about it, that value seems a little too high).

**Comment by TeamSpen210** [comment]
6 seconds.
