### ISSUE TITLE
Pr24 bugs

### ISSUE THREAD

**Issue by goodDOS** [BEEmod/BEE2-items#1563]
1# 3 kinds of droppers will stuck the player
http://csyeah.qiniudn.com/img/1.gif

2# ATLAS can not be born from the coop checkpoint
http://csyeah.qiniudn.com/img/2.gif

3# Open the portal on the cold light
http://csyeah.qiniudn.com/img/5.gif

4# Trigger+logic=Not working
http://csyeah.qiniudn.com/img/4.gif

5# Cube can be passed from the coop checkpoint
http://csyeah.qiniudn.com/img/3.gif

Hope to fix :smiley:

**Comment by LautaroL20** [comment]
Hey, it was a while since i saw you posting issues, nice to see you again. There are some bugs from your list that are fixed for next release, though id like to split those bugs that aren´t fixed in separate posts. 

BTW, nice bug find on the Standart checkpoint!

**Comment by LautaroL20** [comment]
Issues has been splitted into separated posts:

https://github.com/BEEmod/BEE2-items/issues/1564

https://github.com/BEEmod/BEE2-items/issues/1565

https://github.com/BEEmod/BEE2-items/issues/1566
