### ISSUE TITLE
ATLAS Keeps mysteriously respawning from the default Spawn Room instead of the Standart Checkopint

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1564]
Original post from @goodDOS:

"ATLAS Respawn Logic from the Co-op dropper of the Standart Checkpoint is not working",

GIF: http://csyeah.qiniudn.com/img/2.gif

**Comment by ZombiePwner1** [comment]
@LautaroL20 The cubemaps in that gif are broken as seen from atlas's view when he was drowning.

**Comment by LautaroL20** [comment]
True, ill give it a check then.

**Comment by ZombiePwner1** [comment]
@LautaroL20 I found the fix for this >:D Also come on steam.

**Comment by LautaroL20** [comment]
What was the cause?

**Comment by ZombiePwner1** [comment]
@LautaroL20 Come online and i will tell you.

**Comment by LautaroL20** [comment]
This is still an issue.

**Comment by Luke18033** [comment]
@FrozenDragon0 Do you still have the fix for this, could you post it here/say what it was?

**Comment by Konclan** [comment]
I thought I fixed this, isn’t the problem that the standard checkpoint uses two pbody spawn points.

**Comment by Luke18033** [comment]
I talked to FrozenDragon on Discord and he said that was what he remembered the issue being, so probably.

**Comment by FrozenDragon0** [comment]
Checked the instance and it is infact Atlas's info_coop_spawn entity being set to red instead of blue.
