### ISSUE TITLE
Make the Catwalk item to generate "Railways Supports" on walls

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1567]
Do not get confused with the actual bottom support wich is also being placed on the wall. This one looks slightly different:

![20170207095012_1](https://cloud.githubusercontent.com/assets/12244376/22788107/5a52d660-eebd-11e6-8340-ec34fbbcdfcc.jpg)

**Comment by ZombiePwner1** [comment]
This is a duplicate of https://github.com/BEEmod/BEE2-items/issues/1472

**Comment by ZombiePwner1** [comment]
And the rail supports are part of the catwalk model you wheely.
