### ISSUE TITLE
1x4x1 slope

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#1569]
I've had many situations in maps where I just need a really small slope block but there is none that currently exits, there can be more slope variants to this one but I badly need this one specifically

**Comment by TeamSpen210** [comment]
I'm not too sure what angle you want exactly. How would it place, and what handle type should it have (8-position or 4-direction)?

**Comment by Konclan** [comment]
It would be 4-direction and the surface size of a light strip sloped away from the center of the block. Maybe a different variant would be towards the center.

**Comment by Konclan** [comment]
I could draw a picture of what I mean

**Comment by TeamSpen210** [comment]
I get what you mean. It'd need 4 variants really for the different heights though...

**Comment by libbybapa** [comment]
I would really like to see this, especially with the different heights.

**Comment by Konclan** [comment]
Merging with #3885
