### ISSUE TITLE
Half wall tile texture isn't properly aligned to the metal.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1573]
![20170211141652_1](https://cloud.githubusercontent.com/assets/18079316/22851682/d378995a-f064-11e6-9846-99bbce477130.jpg)

**Comment by TeamSpen210** [comment]
Looks correct.

**Comment by ZombiePwner1** [comment]
The edge of the tile texture isn't aligned to the metal.

**Comment by TeamSpen210** [comment]
It's like that.

**Comment by ZombiePwner1** [comment]
This is what it looks like on the right side.

![20170211141853_1](https://cloud.githubusercontent.com/assets/18079316/22851691/0ec9af8a-f065-11e6-902f-377b8fe1efa7.jpg)

**Comment by TeamSpen210** [comment]
That's how all textures work.

**Comment by ZombiePwner1** [comment]
It looks abit weird though on the left side.
