### ISSUE TITLE
Colored cubes turn white when held in coop.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1578]
![20170211180350_1](https://cloud.githubusercontent.com/assets/18079316/22853913/d6b1cfa0-f09c-11e6-9ffc-59c432a841dc.jpg)

![20170211180348_1](https://cloud.githubusercontent.com/assets/18079316/22853914/d87e0f06-f09c-11e6-8883-d485d7ce33c2.jpg)

**Comment by Luke18033** [comment]
I think this is a Valve bug, since held cubes are viewmodels in Co-op.

**Comment by TeamSpen210** [comment]
Indeed.

**Comment by TeamSpen210** [comment]
Try picking up a frankenturret.
