### ISSUE TITLE
Old Aperture Pedestal Button Editor Model (With Animations)

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1580]
It would be nice.

**Comment by Endermage77** [comment]
I wonder how many other styled items we could apply the same idea to...
That would take practically forever, though.

**Comment by TeamSpen210** [comment]
The objective is all of them, or at least all items with major changes. (For example Overgrown doesn't really need too many models.)

**Comment by LautaroL20** [comment]
> Endermage77: "Thatwould take practically forever, though."

We would do it for the Original PeTi items at least... A Clean style pedestal button editor model really don´t fit well into the retro puzzlemaker.

**Comment by LautaroL20** [comment]
@TeamSpen210 - I will try to port a static version of the Old Ap Pedestal Button, but since im still a rookie with making animations, feel free to implement them.

**Comment by LautaroL20** [comment]
Done, here it is (https://github.com/BEEmod/BEE2-items/commit/b47c3bd1ac99fffa3913e2aefb8b27008377c4c3) if you want to do any improvements on it, here are their resources: https://github.com/BEEmod/resource-src/commit/88c7a5c08cafd3acb697ffec312d51de7772750b

**Comment by TeamSpen210** [comment]
This has been implemented.
