### ISSUE TITLE
Error Compiling Chamber

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#1581]
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 7
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 4
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (157 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "item_bee2_fizzler_out_relay" not a valid item!
[INFO] cond.core.res_goo_debris(): GooDebris: 1/9 locations
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.core.retexture_template(): Mat: anim_wp/framework/squarebeams, replacement: anim_wp/framework/squarebeams_rusty_01
[INFO] cond.core.steal_from_brush(): Steal: {'additional': (), 'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x0426E930>, solid=<srctools.vmf.Solid object at 0x04735710>, normal=Vec(0, -1, 0), color=<MAT_TYPES.white: 1>), 'rem_brush': True, 'transfer_overlays': True, 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x04724D30>, <srctools.vmf.Solid object at 0x04724CF0>], detail=None, overlay=[], orig_ids={67: 787, 68: 786, 69: 785, 70: 779, 71: 773, 72: 752, 73: 793, 74: 792, 75: 791, 76: 790, 77: 789, 78: 788})}
[INFO] cond.core.steal_from_brush(): Steal: {'additional': (), 'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x048A6750>, solid=<srctools.vmf.Solid object at 0x04735770>, normal=Vec(0, -1, 0), color=<MAT_TYPES.white: 1>), 'rem_brush': True, 'transfer_overlays': True, 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x04184550>, <srctools.vmf.Solid object at 0x041844F0>], detail=None, overlay=[], orig_ids={67: 799, 68: 798, 69: 797, 70: 796, 71: 795, 72: 794, 73: 805, 74: 804, 75: 803, 76: 802, 77: 801, 78: 800})}
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[ERROR] cond.core.check_all(): Error in condition:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 522, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 354, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 343, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1651, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 354, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 343, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\brushes.py", line 586, in res_import_template
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1103, in import_template
KeyError: 'single'

**Comment by Konclan** [comment]
![20170212131233_1](https://cloud.githubusercontent.com/assets/16567080/22865217/03ae1db4-f125-11e6-96c1-f3ea693eb696.jpg)
![capture](https://cloud.githubusercontent.com/assets/16567080/22865219/069557a4-f125-11e6-95c7-80181e895cdb.PNG)

**Comment by Luke18033** [comment]
Is this the dev version?

**Comment by Konclan** [comment]
I don't have the dev version, I've don't know how to get the dev version

**Comment by TheDarkBomber** [comment]
I think @Luke18033 asked because there was this line: `[WARNING] instanceLocs.resolve(): "item_bee2_fizzler_out_relay" not a valid item!`

**Comment by TeamSpen210** [comment]
That's harmless, I often have code for WIP things in the compiler - it only takes effect if you actually have the items. It's a warning - something that might want to be fixed, but the compiler can continue without.

**Comment by Konclan** [comment]
Why is this still open?
