### ISSUE TITLE
3x1 Observation Room

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1582]
Ive maded the model for it, now we need to do the instances. I do not have idea how it should be arranged for Old Aperture in a way that do not leak the mandatory observation room.

![20170213112411_1](https://cloud.githubusercontent.com/assets/12244376/22887176/cd50aeec-f1df-11e6-8dc5-fc85d1c0bdc8.jpg)
![20170213113546_1](https://cloud.githubusercontent.com/assets/12244376/22887377/9947c77e-f1e0-11e6-92ee-8dd451fc1d05.jpg)

**Comment by Byzarru** [comment]
But isn't there going to be a 'connecting' observation room, so this would be unnecessary?

**Comment by LautaroL20** [comment]
I do not have idea how that will gonna work, and when it would be maded. But this one is pretty easy to do and it would be ready in a few days.

**Comment by TheDarkBomber** [comment]
Why not just have it as an Old Aperture style of the Observation Room?

**Comment by TeamSpen210** [comment]
That's what would be used - we can't have multiple copies of the worldportal obs room items and have it work. Or I should implement the resizable one.

**Comment by Luke18033** [comment]
This will be replaced by resizeable observation rooms.
