### ISSUE TITLE
Panel Arms

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1583]
_From @XdplayerdX on February 14, 2017 15:41_

Can You Add this,is like a panel but have more angles and can move for any direction
Examples:
http://half-life.wikia.com/wiki/Aperture_Science_Multitasking_Arm
https://www.youtube.com/watch?v=Kyc4JK24EuI
In gmod have one of then https://steamcommunity.com/sharedfiles/filedetails/?id=862644776&searchtext=
thank you this is the best addon for portal 2 !!!

_Copied from original issue: BEEmod/BEE2.4#520_

**Comment by Luke18033** [comment]
Great idea, but what would it be in Old Aperture or P1?

Open issues related to items or styles on the [BEE2.4 Default Pack repository](https://github.com/BEEmod/BEE2-items).

**Comment by XdplayerdX** [comment]
It's like a panel but,can move follow one rail,can ben angled,and can support other itens(cubes,turrets,cameras(like whetley and turrets or cubes)) and can make everything like this addon:
http://images.akamai.steamusercontent.com/ugc/159152387699546569/E006DCAFA804B9FEDE0DC934FAD6CF691365D4CB/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|637:358&composite-to%3D%2A%2C%2A%7C637%3A358&background-color=black

http://images.akamai.steamusercontent.com/ugc/159152387699247680/9CC5771EFC607C69858BA78780ABC08B6259DB7F/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|268:268&composite-to%3D%2A%2C%2A%7C268%3A268&background-color=black
Well you can remove that of the Old Aperture or portal 1 or you can use the old aperture panel textures and models,with some editions.

Thanks For Everything And Sorry for my bad english !

**Comment by Luke18033** [comment]
I know what it is. The problem is Old Aperture and Portal 1 - they don't have panel arms. Portal 1 could use some sort of piston panel, but what about Old Aperture?

**Comment by Konclan** [comment]
I'm confused as to what this item is, its like an angled panel + a unstationary scaffold and allows items to be attached to them?

**Comment by Luke18033** [comment]
It's just a panel arm, like what's used for Stairs. But they can be placed individually.

**Comment by Konclan** [comment]
Still lost, how is that different form an angled panel?

**Comment by XdplayerdX** [comment]
Its like this:
https://www.youtube.com/watch?v=Kyc4JK24EuI

http://images.akamai.steamusercontent.com/ugc/159152387699546569/E006DCAFA804B9FEDE0DC934FAD6CF691365D4CB/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|637:358&composite-to%3D%2A%2C%2A%7C637%3A358&background-color=black

http://images.akamai.steamusercontent.com/ugc/159152387699247680/9CC5771EFC607C69858BA78780ABC08B6259DB7F/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|268:268&composite-to%3D%2A%2C%2A%7C268%3A268&background-color=black

The Panel in Old Aperture: http://imgur.com/a/9q4mT

**Comment by TeamSpen210** [comment]
What specifically do you want it to do? How should it move?

**Comment by XdplayerdX** [comment]
Well,for make that more easy you can make various panels with diferent functions like: http://imgur.com/a/gLIAM
1 move for up and down
2 move for the sides
3 move for front and back 
4 move at diagonal using front and back + sides + up down
5 this is a solid surface,in can drop everythink (a cube for example) 
6 in the chapter the escape,you can view a Multitasking Arm moving in a rail (with whetley)
7 Technical it's one piston+angled panel+Track Platform+Piston Platform+Flip Panel
I'm like make test chambers like behinde the scenes : https://cazzablackabertay.files.wordpress.com/2015/09/portal2-h-1024x576.jpg
http://www.gamesmediapro.co.uk/wp-content/uploads/2011/05/sp_a2_bts20020_tga_jpgcopy.jpg
http://i.gyazo.com/dc652e1e75280bc8e1af5f19a54e91ab.png

**Comment by XdplayerdX** [comment]
That Have Some Images Of The Model And Some Poses Of The Panel:
http://imgur.com/a/gLIAM

**Comment by XdplayerdX** [comment]
http://imgur.com/a/4OybW

**Comment by TeamSpen210** [comment]
I'm well aware what they look like. I want specific item suggestions - one item, how it is placed, how it will move, how it should look in othe styles, etc. There are hundreds of animations for panels.

**Comment by TeamSpen210** [comment]
Additionally, all items work in all styles, so it must be reasonable in all of them.

**Comment by XdplayerdX** [comment]
It's placed in the floor,walls,ceiling,you use one bar for difine the angle,the pose,and the portabilite,that
can ben divised (or not,you is a developer) in 3 items:
1Multitasking Arm : can move around,can be angled and you can use at any direction using the tiny circle,
you can place some tipe of itens in this Multitasking Arm (like cameras,laser,portal spawners,excurse funnels,etc...).

2 rail Multitasking Arm: you can make basic every thar i mentioned up,you use the arrows for difine the track,if you shoot one portal that portal move with the panel(like destroy the neurotoxin generator in The Escape).

**Comment by XdplayerdX** [comment]
https://i.ytimg.com/vi/IcLHaU6EVo8/maxresdefault.jpg
https://i.ytimg.com/vi/WZMzJvGmylQ/maxresdefault.jpg

**Comment by XdplayerdX** [comment]
Oh,in the portal 1 style you use pistons for the Multitasking Arm,and a track for the rail Multitasking Arm
in old aperture,use motors and gears for Multitasking Arm,and motors and one track for the rail Multitasking Arm

**Comment by XdplayerdX** [comment]
you can choose the the height with the since arrow of the piston plataform,the angle with the since controls of the angled panel,and can move the panel with arrows

**Comment by TeamSpen210** [comment]
Most of those things can't be mixed and matched.

**Comment by XdplayerdX** [comment]
the piston plataform have height and direction you can use,and the track plataform have movements,you can create 2 (or 3) diferent panels:
Multitasking Arm Moving Panel
Multitasking Arm Track Panel
Multitasking Arm angle and position panel

**Comment by Byzarru** [comment]
It could be pulleys and rails in Old Aperture.

**Comment by Luke18033** [comment]
Those sliders to adjust the angle of the panel can't be done, the panels can only use preset animations. Maybe use the ICP to choose the animation? It still wouldn't make much sense in P1 or Old Aperture.

**Comment by Luke18033** [comment]
Updated comment 279859054

**Comment by Luke18033** [comment]
Updated comment 279859054

**Comment by XdplayerdX** [comment]
Yes,you can't make a ''New Animation'' and put that to portal 2 files ?

**Comment by XdplayerdX** [comment]
And Whats it ICP ?

**Comment by TeamSpen210** [comment]
I'd have to create hundreds, one for each position...

**Comment by Luke18033** [comment]
ICP is Item Configuration Pane, BEEmod/BEE2.4#467.

**Comment by XdplayerdX** [comment]
well Up,down,left,right,diagnals = 9*9=81 ,you it's right it's harder maker everything,
what is Item configuration pane ?

**Comment by Luke18033** [comment]
See the issue.

**Comment by XdplayerdX** [comment]
If You use a custom ICP like the mini hud in this images :
http://imgur.com/a/gLIAM
use this to difine to location ,it's more easy than make 81 animations

**Comment by Luke18033** [comment]
That's the thing, it's not possible to do that!

**Comment by Luke18033** [comment]
Updated comment 279869945

**Comment by XdplayerdX** [comment]
What is the max possible that we can do ?

**Comment by TeamSpen210** [comment]
I can only reuse what's already in the editor. There's the ability to mix-and-match simple properties like checkboxes, but I can't add more, or do things like have the piston and track platform handles on the same item, attach multiple things to each other, or do other custom rotations.

**Comment by XdplayerdX** [comment]
well,the Multitasking Arm not as possible now ?
(
Are you forecast to release the next version of the beemod ?

**Comment by Luke18033** [comment]
The arm is still possible, but it wouldn't be able to move to any angle or position - it could only use the animations Valve has made. Additionally, the ICP only allows for 29 different configs, so you could only use 29 different animations in the map.

**Comment by Luke18033** [comment]
The next release won't be for a while, development on Pr25 just started recently.

**Comment by Luke18033** [comment]
Updated comment 279869945

**Comment by XdplayerdX** [comment]
what animations we can use to make the panel like the original ?
well i questioned everything...

**Comment by Luke18033** [comment]
I have plans to make PuzzleMaker Plus, which will allow things like custom movement handles or item properties. I'm not developing that yet though, so that won't be for a while.

We can use any animations that Valve made, but you'll only be able to have 29 different ones per map.

**Comment by XdplayerdX** [comment]
Do you have any predictions of when it will launch?(the next release,and the PM Plus )
It takes about 1 month, a year?

**Comment by Luke18033** [comment]
The next release: Probably within a couple of months.
PuzzleMaker Plus: nine-nine-nine-nine-nine-nine...

**Comment by XdplayerdX** [comment]
Well thank's for all help :) !
I'm wating the next update !

**Comment by XdplayerdX** [comment]
Better Mod !

**Comment by Luke18033** [comment]
The Multitasking Arm (or the ICP, for that matter) are *not* going to be in the next release, if that's what you are waiting for. But expect other new features - the Radiative Flux Field from Rexaura is in, and @LautaroL20 is developing Breakable Glass.

**Comment by XdplayerdX** [comment]
I'm Know, i'm wating you next release because i know that will be Fantastic :)

**Comment by Endermage77** [comment]
I think what you're thinking of is the old Living Panel item from the BEE2 alpha.
I personally don't know how that item worked. but it's the closest thing I can think of.

**Comment by XdplayerdX** [comment]
have one link ?
i dont know that item

**Comment by XdplayerdX** [comment]
i can't find the living panels in any site
Have you a Link ?
Or Image ?

**Comment by Endermage77** [comment]
I'm not certain whether it was part of the regular pack or Tspen's stuff or what, but one of the items I had was called a Living Panel. It's kinda similar to one panel in one of the more difficult Wheatley chambers:
What it did was simple: When it was activated, it performed an animation determined by a timer number. It came in small, medium, and large variations.

Unfortunately, I no longer have my copy of that particular version.
What it had on it was: The BEE2.5 alpha, Tspen210's addon, and Radelite's addon.

**Comment by XdplayerdX** [comment]
i cant download more The Tspean210's addon,the page has not found

**Comment by XdplayerdX** [comment]
I'm downloaded the bee alpha and i see the living panel but i can't compile,i get a error

**Comment by Luke18033** [comment]
There wasn't a medium version, only small and large. The large one was kind of weird...

**Comment by XdplayerdX** [comment]
i can't test that panel,that give-me a compile error

**Comment by LautaroL20** [comment]
> Luke18033:  "and Lautaro is developing Breakable Glass."

Nope, only things i contributed on this item was doing its suggestion to implement this (https://github.com/BEEmod/BEE2-items/issues/898), and once Spencer started to develop it, ive implement its Breakable Glass Palette Icon.

-------------------------------------------------------------------------------------------

Ill gonna implement two new addons though, Co-op Grates and a Half-Grate to walk a half block out. I even finished their Editor Models for them:

![half-grate](https://cloud.githubusercontent.com/assets/12244376/22964414/53b6c5ae-f337-11e6-8da0-7369bfe2f146.jpg)
![CO-OP Grates](https://cloud.githubusercontent.com/assets/12244376/22964394/38dbf4a2-f337-11e6-8d29-1d95a01a4a23.png)

**Comment by XdplayerdX** [comment]
Cool

**Comment by Luke18033** [comment]
@LautaroL20 What do Co-op Grates do?

**Comment by LautaroL20** [comment]
Prevents you from grabbing cubes through it.

**Comment by XdplayerdX** [comment]
What is this and what it do ?
![](https://cloud.githubusercontent.com/assets/12244376/22964394/38dbf4a2-f337-11e6-8d29-1d95a01a4a23.png)

**Comment by XdplayerdX** [comment]
Hey you are a brazilian ?
![](https://cloud.githubusercontent.com/assets/12244376/22964414/53b6c5ae-f337-11e6-8da0-7369bfe2f146.jpg)

**Comment by LautaroL20** [comment]
@XdplayerdX - Ive mentioned its funtion just adobe your comment, it looks like you don´t read them....

No, im from Argentina.

**Comment by Luke18033** [comment]
Instead of making a separate "co-op grate", you should just improve the current grating to work better in Co-op.

**Comment by LautaroL20** [comment]
Unfortunately, not possible. The PeTi grate are actually just a pair of clips (`player_clip` and `func_clip_vphysics`) and a specific `func_brush` that only works well on the SP Mode. My addon does not use those clips and works using another variant from the `func_brush`. 

So, merging this would break many things on the Vanilla Grating. Thats why this should be maded separately.

**Comment by TeamSpen210** [comment]
Specifically grating textures by default allow you to portal through them. The issue is that they also block things like funnels, bridges and paint bombs. That's why you'd need the clips.

**Comment by Luke18033** [comment]
For Old Aperture, maybe just make it brown like BEE2.2 did? P1 could probably use pistons somehow.

**Comment by Luke18033** [comment]
Whatever you use though, you'll need a custom model that:
1. Doesn't clip when placed at the edge of a voxel (I assume this will have 8 positions).
2. Has attachment points for the different parts of the arm, if the vanilla model doesn't already.

**Comment by Luke18033** [comment]
@XdplayerdX
- [BEE2.2](https://github.com/BEEmod/BEE2.2/releases)
- [TSpenAddons](https://github.com/BEEmod/tspenAddons/releases)

Not sure about Radelite's Addons, I think I got them from ModDB.

**Comment by Luke18033** [comment]
We could also reimplement the original living panel item from BEE2.2, which was a lot more confusing but allowed for more animations per map.

**Comment by XdplayerdX** [comment]
I tried using this but the game has crashed after I put in the editor.

**Comment by Luke18033** [comment]
We'd obviously fix that for the 2.4 version.

**Comment by TeamSpen210** [comment]
Doesn't seem like this suggestion went anywhere.
