### ISSUE TITLE
Some Ideas of Some Itens

### ISSUE THREAD

**Issue by XdplayerdX** [BEEmod/BEE2-items#1585]
1- Breakable Glass
One Glass that can break.

2-Bomb/Bomb Dropper
Esplosive bomb: http://half-life.wikia.com/wiki/Aperture_Science_Bomb

3-One Cut Gel that make um grab into any surface: https://theportalwiki.com/wiki/Adhesion_Gel

4-Contraption Cube: http://combineoverwiki.net/wiki/Contraption_Cube

That is some iten that i'm really like for portal 2 BEE 2 Mod

**Comment by Luke18033** [comment]
- Breakable Glass: Already going to be implemented. (#898)
- Bomb Dropper: Already going to be implemented. (#95)
- Adhesion Gel: This can be re-created using some tricks with rotating the map, but that won't work in PeTI.
- Contraption Cube: Already going to be implemented. (#850)
