### ISSUE TITLE
Remove Signage collision and add 8-position handle

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#1586]
The signage does not have CollideNothing added.  As is, it gives an error when set on a side with glass, or set in a corner with another signage item.  When CollideNothing is added, it does not cause any errors any more and compiles just fine.  Adding that would give more options for signage placement.

![20170214205448_1](https://cloud.githubusercontent.com/assets/19520567/22960001/df05ecce-f2f7-11e6-90c5-64e7e884f538.jpg)

**Comment by libbybapa** [comment]
On a similar note, it looks like the handle_8_ positions would work but the offsets are incorrect and place the signage off the voxel where it no longer shows up in the outer two positions.  Can handle_8_positions be added as well?

**Comment by Byzarru** [comment]
YES

**Comment by libbybapa** [comment]
I already changed it for mine, I just think other people might like it too.  :)

**Comment by Byzarru** [comment]
The only objection I have to this is the P1 style, which has the frames around the signs. No other style has this feature, though, and all maps with signage make them non-colliding and portalable. This could easily be a style variant, though. I like the frames. Some people don't.

As for Handle 4 Positions, I've suggested that in #1093.

**Comment by TeamSpen210** [comment]
I probably will drop the signs from everything except the exit door ones - Portal 1 doesn't include them there anyway.

**Comment by libbybapa** [comment]
The connection signage does not collide.  Only the signage that shows dots, cube, etc...

**Comment by Luke18033** [comment]
Bump.

**Comment by Luke18033** [comment]
Actually, I was looking at some of the BEE2.2 items today and I found a "Dice Signage" item. And guess what it had? 8-position handle and no collisions. So why can't we reimplement this into 2.4, just with more signs?

**Comment by LautaroL20** [comment]
While i was updating one of my old maps in order to solve the Glass Panel´s transparency bug, i wanted to add the signage item closely to a Pedestal Button, but i noticed its not possible since it can not be moved inwards, and therefore, the signage gets buried under the base...... So, if there is an item that deserves having the `handle_8_positions` this is it, i will definitelly gonna implement this, today.

**Comment by Luke18033** [comment]
Finally, somebody's actually implementing this! One thing is that you'll need to redo the model and the instance, since the current ones appear extremely offset when the handle is added.

**Comment by TeamSpen210** [comment]
The model source is in `resource-src`, you can just add a `$origin` command.

**Comment by LautaroL20** [comment]
The Connection Signage causes failure to compile: https://github.com/BEEmod/BEE2-items/issues/2162

**Comment by LautaroL20** [comment]
As for the model, i just used the command `Upaxis Z` and then `$Origin "47.5 0 0"`, that allows the model to work with the 8 positions feature.

**Comment by LautaroL20** [comment]
This is now implemented:

![GIF](https://user-images.githubusercontent.com/12244376/29692833-75a66df6-8908-11e7-8b4f-74d430327b3c.gif)
