### ISSUE TITLE
Closed Solid Fields cause a Build Error in 50's Style

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1591]
Placing any closed solid fields anywhere in the level in the 50's style throws a General Build Error.

**Comment by TheDarkBomber** [comment]
Log?

**Comment by Endermage77** [comment]
Here:
///Start


[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/crusher_back.vmt
patch, (*insert*), 
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_under_bee2_paint_fizz.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_under_bee2_paint_fizz.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_under_faith_targ.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_under_faith_targ.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561197988464710\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 47 (ms)

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_CAVE_50s'}
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (15 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cond.fizzler.fizzler_out_relay(): Item classes: defaultdict(<class 'list'>, {'itempistonplatform': ['item_bee2_scaffold_pist', 'item_piston_platform', 'item_rex_pellet_destroyer'], 'itemrailplatform': ['item_bee2_conveyor', 'item_rail_platform'], 'itempanelflip': ['item_panel_flip'], 'itemturret': ['item_turret'], 'itembuttonfloor': ['item_128x64x64', 'item_autoportal', 'item_bee2_angled_block', 'item_bee2_angled_block_corner', 'item_bee2_coop_checkpoint_single', 'item_bee2_half_wall', 'item_bee2_partial_flat_block', 'item_bee2_portalgun', 'item_bee2_scaffold_slot', 'item_bee2_small_window', 'item_bee2_vactube', 'item_bee_logic', 'item_button_floor', 'item_draw_bridge', 'item_high_energy_pellet_catcher', 'item_lautaro_protruding_pedestal', 'item_logic_gate', 'item_rex_cube_deflector', 'item_square_light', 'item_triggers', 'item_tspen_button_pedestal_retract', 'item_tspen_ditch', 'item_tspen_logic_delayer', 'item_tspen_logic_inputs_sr', 'item_tspen_panel_half_static', 'item_tspen_sp_checkpoint', 'item_vent', 'item_wom_conductor'], 'itemtbeam': ['item_tbeam'], 'itementrancedoor': ['item_entry_door'], 'itembarrierextent': ['item_barrier_extent'], 'itemrailplatformextent': ['item_rail_platform_extent'], 'itemexitdoor': ['item_exit_door'], 'itemangledpanel': ['item_panel_angled', 'item_panel_clear'], 'itemcatapulttarget': ['item_catapult_target'], 'itemstairs': ['item_panel_stairs'], 'itembarrier': ['item_barrier', 'item_bee2_quart_wall'], 'itemlaseremitter': ['item_laser_emitter_center', 'item_laser_emitter_offset'], 'itempedestalbutton': ['item_button_pedestal'], 'itempaintdropper': ['item_dropper_paint'], 'itemlightstrip': ['door', 'item_bee2_scaffold_wall', 'item_light_panel', 'item_light_panel_cold', 'item_light_panel_warm', 'item_tag_gun_activator', 'item_tspen_ant_router_strip'], 'itemcoopentrancedoor': ['item_coop_entry_door'], 'itembarrierhazard': ['item_barrier_hazard', 'item_bee2_paint_fizzler', 'item_fr_comp_smoke_field', 'item_fr_force_deflection_field', 'item_fr_matter_inquisition_field', 'item_lp[INFO] cond.fizzler.fizzler_out_relay(): Fizzler data: {'model': 'instances/bee2/50s/items/tdb/csfi_model.vmf', 'fizz_id': 'item_tdb_csfi', 'fizz_bases': {'instances/bee2/50s/items/fr/fdf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/50s/items/fr/mif_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/50s/items/paint_fizz/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/50s/items/tdb/csfi_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/50s/items/fizzler/fizzler_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/50s/items/fr/csf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/50s/items/physler/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/50s/items/death_fizz/base.vmf': ItemConnections(in_act=('branch_fizz', 'ToggleTest'), in_deact=('branch_las', 'ToggleTest'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/rex/pellet_field_base.vmf': ItemConnections(in_act=(None, ''), in_deact=(None, ''), out_act=('out', 'OnUser2'), out_deact=('out', 'OnUser1'))}, 'fizz_by_name': {}, 'base': 'instances/bee2/50s/items/tdb/csfi_base.vmf', 'relay_file': ['instances/bee2/logic/fizzler_out_relay.vmf'], 'pos_to_name': {}, 'fizz_models': {'instances/bee2/50s/items/paint_fizz/model.vmf', 'instances/bee2/50s/items/fizzler/fizzler_model.vmf', 'instances/bee2/50s/items/fr/fdf_model.vmf', 'instances/bee2/50s/items/tdb/csfi_model.vmf', 'instan[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 1/6 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"Name" "Welcome to Aperture Science"
 | 	"Bullseye" "cave_a3_03_lift_shaft"
 | 	"Choreo" "npc/cavejohnson/fifties_intro01.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "EXIT": 1/7 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"Name" "Glorious Contribution to Science"
 | 	"Bullseye" "cave_transition01_dummy_exit"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/cavejohnson/fifties_outro02.vcd"
 | 		"1" "npc/cavejohnson/fifties_outro05.vcd"
 | 		}
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 2/2 quotes..
[INFO] voiceLine.add_voice(): Using microphones...
[INFO] voiceLine.add_voice(): 1 Mid quotes
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CAVE_LOITER"
 | 	"Quote_Name" "@cave_catwalks"
 | 	"Bullseye" "cave_crazy_box_2nd_chamber"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/cavejohnson/fifties_fifth_test_intro01.vcd"
 | 		"2" "npc/cavejohnson/fifties_fifth_test_intro03.vcd"
 | 		}
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['observationgrate', 'fizzler', 'tdb_ff', 'spawn_dual', 'obsworldportal']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3087, misses=312, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'funnelallowswitchedlights': True, 'nomidvoices': False, 'bee_show_trigger': False, 'allowgoomist': True, 'multiversecave': True, 'unlockdefault': True, 'rexcubepelletfizzle': False, 'fixfizzlerbump': False, 'retro_voice_pre_line': False, 'restartonexit': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/50s/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.clump_walls(): Clumping: 160 clumps (+ 0 special)
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "File"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/fourthreaper/player_clip_electric.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/thedarkbomber/50s_csfi.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/thedarkbomber/50s_csfi_center.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/thedarkbomber/50s_csfi_left.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/thedarkbomber/50s_csfi_right.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/effect.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_danger.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_danger.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty_danger.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty_danger.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/underground_woodwall003c.vmt"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/cust_fizz.mdl"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "D:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 8 threads
 | materialPath: D:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
 | "materials/dev_measuregeneric01b.vtf": cached version doesn't exist
 | Could not open instance file instances/BEE2/50s/items/tdb/csfi_model.vmf
 | 
 |_

[INFO] BEE2_config.save(): Saving changes in config "D:\E\Mods\Portal 2 Modding\BEE2 Mod\BEE2.4_pr24_win\config/compile.cfg"!
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)


An error occurred while attempting to download a file from the UGC server!


///End
The Start and End bits not being part of the log.
Now, looking at this myself, my best guess is that some file or other was missing.

**Comment by TeamSpen210** [comment]
Add a \`\`\` at the beginning and end to format it nicely.
