### ISSUE TITLE
New Item - One Way Field

### ISSUE THREAD

**Issue by libbybapa** [BEEmod/BEE2-items#1592]
I've had the thought that it would be interesting to have a specialty type of field that was a one-way field.  It would allow players and cubes to go through it one direction but prevent the player or cubes from travelling back through it in the other direction.  The effect would basically be one-way grating.  Visually it could look much like the force deflection field, but it would have 'light particles' emitting from the one side kind of like a funnel has and that emission of light would show which direction would allow travel.

**Comment by TeamSpen210** [comment]
This wouldn't be possible, unless it was to basically push things in the other direction (which could probably be cheated).

**Comment by libbybapa** [comment]
Ok.  Thanks.

**Comment by libbybapa** [comment]
In thinking about this just a little bit more it seems odd to me that it wouldn't be possible.  The functionality I'm talking about is exactly how this bug makes the static panels behave (with portals):  https://github.com/BEEmod/BEE2-items/issues/1438#issuecomment-280475377

What issue makes it impossible to have a field give the same functionality?

**Comment by TeamSpen210** [comment]
That's a bug specific to portals - the game doesn't detect some types of collision on the other side of the portal, but when you're on the same side, it collides with you and blocks you from going through.

**Comment by TeamSpen210** [comment]
It's also why grating or light bridges do the same thing.

**Comment by libbybapa** [comment]
I see.  Ok, thanks.
