### ISSUE TITLE
[puzzlebreaking] Cannot pass through portals on 30 and 45 degree static angled panels

### ISSUE THREAD

**Issue by quat1024** [BEEmod/BEE2-items#1593]
I'm using the Clean Original Textures style and the regular angled panel items.

I cannot enter portals placed on angled panels. I can exit from them just fine, but I can't go in them. I just float on top of the portal like this:

![](https://puu.sh/u61G6.png)

Obviously this makes mapping with angled panels impossible, especially "No Elements" maps :(

In case this is somehow positional (don't think it is), the layout in that screenshot is like this, based off of the default room https://puu.sh/u61Sz.png

**Comment by TeamSpen210** [comment]
Try attaching some connection to the item, so it uses the non-static variation.

**Comment by quat1024** [comment]
That fixed it. All the animated panels seem to work fine.

I also just tried the 60 and 90 degree static panels, and they are unaffected.

**Comment by quat1024** [comment]
I also tried downwards facing panels placed along the wall, and panels on the ceiling. In those cases only the 45 degree panels weren't enterable. For upwards facing wall panels, I can't enter the 45 and 30 degree versions.

The 60 degree static panel also appears to be missing a placement helper.

**Comment by quat1024** [comment]
I just noticed this is a duplicate: https://github.com/BEEmod/BEE2-items/issues/1438

This one has more detail though :smirk:

**Comment by Luke18033** [comment]
Add your detail there in a comment, that's what I do when I open a duplicate issue.
