### ISSUE TITLE
60 degree static panels are missing placement helpers

### ISSUE THREAD

**Issue by quat1024** [BEEmod/BEE2-items#1594]
A 60 degree panel with nothing connected to it doesn't have a placement helper.

A 60 degree panel that does have a connection to it (i.e. the vanilla angled panels) does.

I'm using the Original Clean theme.

**Comment by Luke18033** [comment]
I actually dislike the automatic placement helpers on items like angled panels, just use the placement helper item for that...

**Comment by quat1024** [comment]
But you can't place placement helpers on panels :stuck_out_tongue: 

They are really useful for things like aligning funnels and bridges, and having centered portals just looks nicer anyways. I don't see a reason why *only* 60 degree panels shouldn't have them anyways.

**Comment by TeamSpen210** [comment]
Original Clean only affects the texturing, it still uses the same items.

**Comment by TeamSpen210** [comment]
I have been removing them from 90 degree panels, but they should be on all others.

**Comment by libbybapa** [comment]
Is it or will it be possible to place the independant portal magnet on a 90° panel?

**Comment by TeamSpen210** [comment]
I'll need to implement that.

**Comment by libbybapa** [comment]
As quat says, it's nice to have that ability when the map has an angled panel with a funnel or bridge aimed at it.

**Comment by Luke18033** [comment]
Funnels, light bridges and lasers have automatic placement helpers which would stay on.

**Comment by libbybapa** [comment]
Ok.  Carry on.  :)

**Comment by Luke18033** [comment]
I think automatic placement helpers should be removed from all items except for lasers, light bridges, and funnels, unless absolutely necessary. Angled panels would use the compiler to parent the placement helper to the panel.

**Comment by LautaroL20** [comment]
> Luke18033: "Angled panels would use the compiler to parent the placement helper to the panel."

Yes. At least for the Flip-Panel and Static Panels i am totally agree, should be optional and would be maded via Compiler feature. Its a totally annoyance having to deal with the automatic Helpers on Flip-Panels....

**Comment by quat1024** [comment]
The issue title has nothing to do with the bug anymore, good job guys

This is a bug about 60 degree static panels having no placement helpers. **Only 60 deg. statics have this issue,** there is probably a placement helper misaligned or missing somewhere in the vmf. This bug has nothing to do with the finer retails of parenting helpers to panels

**Comment by Luke18033** [comment]
Should be fixed with the tiling system
