### ISSUE TITLE
Remove random chance of Clean button model on Overgrown

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1598]
![20170217155046_1](https://cloud.githubusercontent.com/assets/19228201/23087412/06181b92-f529-11e6-950d-f06d79756351.jpg)
I don't know if this is intentional, but it looks really out of place.

**Comment by TeamSpen210** [comment]
It randomly uses all button models, those are more rare though.

**Comment by Flametusk** [comment]
All? Meaning it has a (really low) chance of even using, say, buttons from the 50s or portal 1?

**Comment by TeamSpen210** [comment]
Not those of course.

**Comment by Luke18033** [comment]
Alright, well then it's not a bug, but a suggestion.
