### ISSUE TITLE
Turret Dropper causes Build Error

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1601]
Whenever there is a turret dropper, the game loads up to the end of Geometry and then throws a General Error. The log below was printed:

[PORTAL2 PUZZLEMAKER]  New chamber!
[PORTAL2 PUZZLEMAKER] (Save Changes) (  Untitled puzzle has unsaved changes.	 )
[PORTAL2 PUZZLEMAKER]  Discarding existing puzzle 
Unknown command "cl_puzzlemaker_activate"
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.1.100, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 2776 )
Opened Steam Socket NS_CLIENT ( socket 3116 )
Network: IP 192.168.1.100, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\newchamber/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\newchamber/c-1904_2096_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\newchamber/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\newchamber/c-2032_-2032_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\newchamber
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker\newchamber_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF d:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 32 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation canceled
eigenvector unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF d:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 34 (ms)

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "d:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "d:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'use_screenshot': '1', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (12 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cond.fizzler.fizzler_out_relay(): Item classes: defaultdict(<class 'list'>, {'itembuttonfloor': ['item_128x64x64', 'item_autoportal', 'item_bee2_angled_block', 'item_bee2_angled_block_corner', 'item_bee2_coop_checkpoint_single', 'item_bee2_half_wall', 'item_bee2_partial_flat_block', 'item_bee2_portalgun', 'item_bee2_rocket_turret', 'item_bee2_scaffold_slot', 'item_bee2_small_window', 'item_bee2_vactube', 'item_bee_logic', 'item_button_floor', 'item_draw_bridge', 'item_high_energy_pellet_catcher', 'item_high_energy_pellet_emitter', 'item_lautaro_protruding_pedestal', 'item_logic_gate', 'item_rex_cube_deflector', 'item_square_light', 'item_triggers', 'item_tspen_button_pedestal_retract', 'item_tspen_ditch', 'item_tspen_logic_delayer', 'item_tspen_logic_inputs_sr', 'item_tspen_panel_half_static', 'item_tspen_sp_checkpoint', 'item_vent', 'item_wom_conductor'], 'itemcatapulttarget': ['item_catapult_target'], 'itempistonplatformextent': ['item_piston_platform_extent'], 'itemtbeam': ['item_tbeam'], 'itembarrierextent': ['item_barrier_extent'], 'itemangledpanel': ['item_panel_angled', 'item_panel_clear'], 'itemcatapult': ['item_bee2_camera', 'item_catapult', 'item_tspen_large_catapult'], 'itembarrierhazardextent': ['item_barrier_hazard_extent'], 'itemexitdoor': ['item_exit_door'], 'itemcubedropper': ['item_dropper_cube'], 'itempaintsplat': ['item_paint_splat', 'item_paint_splat_reflection'], 'itemlightbridge': ['item_light_bridge'], 'itempaintdropper': ['item_dropper_paint'], 'itembase': ['item_point_light', 'item_indicator_toggle', 'item_indicator_panel', 'item_indicator_panel_timer', 'item_placement_helper', 'item_bee2_catwalk', 'item_bee2_cube_coloriser', 'item_bee2_cutout_tile', 'item_bee2_fizzler_out_relay', 'item_bee2_futbol', 'item_bee2_monitor', 'item_bee2_signage', 'item_bee2_signage_antline', 'item_bee2_special_marker', 'item_bee2_turret_dropper', 'item_crusher', 'item_high_energy_pellet_inf', 'item_hmw_sendificator', 'item_laser_catcher_center', 'item_laser_catcher_offset', 'item_laser_relay_center', 'i[INFO] cond.fizzler.fizzler_out_relay(): Fizzler data: {'model': 'instances/bee2/clean/items/tdb/csfi_model.vmf', 'relay_file': ['instances/bee2/logic/fizzler_out_relay.vmf'], 'fizz_id': 'item_tdb_csfi', 'fizz_bases': {'instances/bee2/clean/items/tdb/csfi_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/csf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/barrier_hazard_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/death_fizz/base.vmf': ItemConnections(in_act=('branch_fizz', 'ToggleTest'), in_deact=('branch_las', 'ToggleTest'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/mif_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/fdf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/rex/pellet_field_base.vmf': ItemConnections(in_act=(None, ''), in_deact=(None, ''), out_act=('out', 'OnUser2'), out_deact=('out', 'OnUser1')), 'instances/bee2/clean/items/paint_fizz/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/physler/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, ''))}, 'marker_inst': [], 'pos_to_name': {}, 'fizz_models': {'instances/bee2/clean/items/rex/pellet_field_model.vmf', 'instances/bee2/clean/items/fr/mif_model.vmf', 'instances/bee2/clean/items/barrier_hazard_model.vmf', 'instances/bee2/clean/items/tdb/csfi_model.vmf', 'instances/bee2/clean/items/pain[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[ERROR] cond.core.check_all(): Error in <BEE2_TURRET_DROPPER>/items/turret_dropper:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 522, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 354, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 341, in test_result
ValueError: "OppositeWallDist" is not a valid condition result!

[PORTAL2 PUZZLEMAKER]  Saved puzzle: d:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561197988464710\autosave.p2c
[

It seems to me that the attempt to determine the distance to the floor confused the compiler.

If anybody is wondering how I got the turret dropper, there is a turr_dropper branch over on the Code page above, from which I manually downloaded and installed.

**Comment by Luke18033** [comment]
Do you have the application development version as well? That also includes the compiler, so new items that require the compiler to work will cause a build error without it.

You don't need to say "general build error", there are only two types of errors: General and Too Many Entities. Too Many Entities only appears in specific cases, so just "build error" or "compile error" is fine.

**Comment by TeamSpen210** [comment]
You'd need the specific compiler version with the functionality for it to work.

**Comment by LautaroL20** [comment]
@Luke18033 - I think that the "Too many Items" issue does not happen anymore when you use Bee2.4

**Comment by Endermage77** [comment]
So, does this mean like redownloading Dev over the turret dropper or...?

**Comment by Byzarru** [comment]
You download the dev version of BEE2.4 itself, I think.

**Comment by Endermage77** [comment]
The interesting thing is, turret droppers aside, everything else works as expected.

**Comment by Luke18033** [comment]
You need the development version of the BEE2.4 application to make it work.
