### ISSUE TITLE
[Game Crash] Gel on BTS Buttons(?)

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1602]
_From @ReikaKalseki on February 18, 2017 6:51_

I converted [one of my older maps](http://steamcommunity.com/sharedfiles/filedetails/?id=545151069) to a Wheatley style via BeeMod's BTS style. At one point in the map, you can get gel into an excursion funnel, where it can be carried through an emancipation grill and onto (what was in clean style) a pedestal button (now a red "elevator button"). The game immediately crashed. Perhaps the new button type does not have a "painted" skin?

_Copied from original issue: BEEmod/BEE2.4#524_

**Comment by Luke18033** [comment]
Put issues about items or styles on the [BEE2-items repository](https://github.com/BEEmod/BEE2-items).

**Comment by ReikaKalseki** [comment]
As an alternative, in case this crash cannot be fixed, could we get a "wheatley" option for styles? That way the test elements would remain "clean" themed but the map creator could create bottomless pits and other similar items.

**Comment by Luke18033** [comment]
@ReikaKalseki - Wheatley style is planned. Until it is added, you can create a "fake" Wheatley style with the following settings:

- Style: Clean
- Music: Anything, but preferrably FrankenTurrets or TEST.
- Voice Pack: Wheatley (duh)
- Skybox: 3D Factory

You may also want to set the default cube type to Frankenturret.

**Comment by TeamSpen210** [comment]
The Skybox option also controls whether goo or pits are used, it's not part of the style.

**Comment by ReikaKalseki** [comment]
Oh. That is good to know. I still would like the "damaged clean" skins for a proper Wheatley test, though.

**Comment by Luke18033** [comment]
That's planned.

**Comment by Luke18033** [comment]
This is actually a duplicate of #347.
