### ISSUE TITLE
Help with BEE2.4's Catawalks

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1607]
I know how you can connect 2 of them, using the "Connect To..." button, but is there any way to have them floating above ground? If I remove the block under them, they have an "Invalid Position" error. Can somebody help?

**Comment by TeamSpen210** [comment]
No, you can't. But the connected parts can, and you can also attach them to walls or ceilings as well. In that case it stays in the normal orientation, although the editor model does rotate.

**Comment by hop193** [comment]
OK, thanks.
