### ISSUE TITLE
Improvements to Conductive Plate

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#1608]
The conductive plate is a surprisingly versatile object.  I have a map where a shortcut is introduced because a portal can be shot off-center on the plate by shooting the corners of the plate.  Please allow the conductive plate to use the 1/2 wall object and respect the dark corners so that a portal shot cannot be shot off-center. 

![20170219094322_1](https://cloud.githubusercontent.com/assets/19520567/23104280/f2f48996-f687-11e6-8e3d-0aef88f10ee8.jpg)

It also seems like it would be easy to add the option (start enabled) to have the portal magnet that is built into the plate force the orientation of the portal as well.

**Comment by TheDarkBomber** [comment]
Also a Conductive Plate should allow being connected to each other, so a cube on one conductive plate activates all of the conductive plate.

**Comment by libbybapa** [comment]
Having that sort of connection would be very confusing to the player unless some sort of special visual cue was used to denote the fact that connected plates acted as OR gates.  Oh wait, there already is that special visual cue - the visible OR gate.  There's no need to add that functionality.  It already exists.  

The original properties I proposed would be helpful, though.

**Comment by libbybapa** [comment]
OR, if your intention IS to confuse the player, then use the invisible OR gate.

**Comment by TeamSpen210** [comment]
Conductive plates already can be connected together, functioning as AND gates.

**Comment by libbybapa** [comment]
Yes, there is no need to change the way they are connected and I would definitely prefer it if it was not changed.  The logic gates (visible or invisible) accomplish all the functions perfectly fine as is.  

Being able to eliminate the off-center portal shots and being able to force portal direction as outlined in my initial post, would be be beneficial, though.

**Comment by libbybapa** [comment]
In order to eliminate the shortcut I mentioned in my initial post I ended up adding partial blocks as shown:  
![20170220112353_1](https://cloud.githubusercontent.com/assets/19520567/23137419/1f0c5374-f75f-11e6-8ee2-52510e8a88b9.jpg)

That eliminates the shortcut but the appearance would be a lot better without the additional blocks.

**Comment by Luke18033** [comment]
Don't add an automatic placement helper. Instead, use the compiler to move a Portal Magnet placed over the plate to the correct position.

**Comment by libbybapa** [comment]
There already is an automatic placement helper.  It is ignored if someone shoots the corner of the plate.  Great, allow it to respect the Portal Magent AND allow it to respect the 1/2 Wall object to adjust how much of the surface is portalable (make the corners black).

**Comment by TeamSpen210** [comment]
I'll resize it so it covers the whole surface.

**Comment by Luke18033** [comment]
Just remove it, and use my suggesion.

**Comment by Luke18033** [comment]
If conductive plates have been updated for the tiling system, then this is basically implemented.

**Comment by TeamSpen210** [comment]
Yep they have.
