### ISSUE TITLE
Sendificator does not recognise CSFi

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1609]
![20170219113708_1](https://cloud.githubusercontent.com/assets/22107242/23105233/4685ad88-f6a1-11e6-997b-a11dbdd35380.jpg)

**Comment by awesomedoctorx3** [comment]
I'm not entirely sure that that is a bug, Closed Solid Fields are designed to block EVERYTHING, correct? If you want lasers to pass through it, use glass. And if you want the CSFi to turn off as a sort of "checkpoint" then have a corridor that opens between the glass room and the other area.

**Comment by Byzarru** [comment]
> Closed Solid Fields are designed to block EVERYTHING
And so it should block lasers (which it does) and therefore the sendificator should send the item to where the laser hits (the CSFi) but instead ignores the CSFi (and the angled panel, see #1074) and sends items past it. In essence, the CSFi is a wall. It should act like a wall in all cases.

**Comment by TeamSpen210** [comment]
The Sendificator is assuming the field is glass-like, because it's too thin. This is difficult to solve.

**Comment by Luke18033** [comment]
I thought of a potential solution to this and #1074, spawn in a `point_laser_target` on the other side of the glass/field/panel to see if the laser is passing through it or not.
