### ISSUE TITLE
Can make some Itens

### ISSUE THREAD

**Issue by XdplayerdX** [BEEmod/BEE2-items#1610]
1 - Doors :
Doors are one Func_Door_Rotating visible in bts maps that opens and closes if the player press E
and have one option of start locked (can use start reversed portal 2 option),with this the door only open when are activated.

![](http://www.portalprelude.com/images/screenshots/screenshot26.jpg)

![](http://selmiak.bplaced.net/games/pc/portal2/img/c06extra2.jpg)
![](http://vignette2.wikia.nocookie.net/half-life/images/f/f6/Speaker_system_open_door.jpg/revision/latest?cb=20091201184134&path-prefix=en )

2 - Colorfull Light's
it's a light but have more colors variations (You can use Portal 2 button hud to control the colors).

![](http://media.moddb.com/images/articles/1/110/109545/auto/1354979386.jpg)

![](http://media.moddb.com/images/mods/1/17/16996/2012-08-21_00002.jpg)

3 - BTS Door
It's one door that opens and closes when have one imput,like a trigger or one button,have the option of start closed(You can Use Strat Reversed For This),with this the door starts closed and open when are activated.

![](https://fraxial.files.wordpress.com/2011/05/portal2_chap5.png)

![](https://i.ytimg.com/vi/AC8qM7cTlP4/maxresdefault.jpg)

4 - Elevators
It's a plataform that move for up or down,like portal 1 and 2 exit elevators but are individually and can been placed in the chamber,You can use arrows to go for up or down ( like piston plataform or track plataform arrows),the player can activate the elevetor with one trigger or one button.

![](https://tagn.files.wordpress.com/2012/07/2012-07-17_00001.jpg)

![](http://media.moddb.com/images/mods/1/21/20161/elevator2.jpg)

![](https://i.ytimg.com/vi/rf_VGsoXcN8/maxresdefault.jpg)

![](http://vignette2.wikia.nocookie.net/half-life/images/2/21/Elevator_tchmb8.jpg/revision/latest?cb=20110327214237&path-prefix=en)

![](http://images.akamai.steamusercontent.com/ugc/267211594259204085/E2536F3F3551785F3F725E33A623243BAE7F5229/)

5 - Supplementary Edge
A Simple Plataform.

![](http://www.portalprelude.com/images/news/patch_2.jpg)

![](http://media.moddb.com/cache/images/mods/1/19/18283/thumb_620x2000/sp_a52_chamb130000.jpg)

**Comment by Byzarru** [comment]
I've suggested colored lights before (#1414), and the elevator (several variants) has been suggested as as well. I think that edge platforms will be added, but I won't say for sure.

**Comment by hop193** [comment]
I'm pretty sure BEE2.2.5 had the BTS doors, or at least the addons did.

**Comment by Luke18033** [comment]
- BTS Doors: Maybe, but what would it be on other styles like Clean? Maybe it could be a style-exclusive item as discussed on Gitter.
- Colored lights: Already been suggested (#1414).
- Vertical Security Door: Already being implemented via #95.
- Mid-chamber elevators: Already been suggested (#942 and #1193).
- Half-grating: @LautaroL20 is developing this. See [here](https://github.com/BEEmod/BEE2-items/issues/1583#issuecomment-279938159).

**Comment by Endermage77** [comment]
For the BTS Doors:
Clean: Office door.
Portal 1/P1BTS: Has BTS doors already in the game (not BEE2).
50's: Pushbar doors.
60's: Pushbar doors.
70's: Hooray! More pushbar doors.
80's: You could use either the modern door or the retro pushbar door.
Art Therapy: Office Door.
Refurbished: Pushbar door again.
Overgrown: A rustier, dingier offfice door.

That's all the styles we have right now, right?
Now for some not-yet-implemented styles...
TWTM: Some sort of glass door, to fit with the asthetic.
P2Beta: See the door in the 6th image down on #741.
Batcature Airship: I'm not certain, but this could be some sort of wooden door, maaybe?
Batcature1: P1 Office doors.
Batcature Space/Space/Moon Base: Some sort of small airlock.
The Under Zone/Pre-GlaDOS 1990's: Regular office doors.
New 1950's: Pushbar doors, cleaned up.

**Comment by Byzarru** [comment]
Probably the biggest justification for adding office items in testing styles is that they can be used to make makeshift offices and observation rooms. Or Rattmann dens!

**Comment by Endermage77** [comment]
Also, if I remember correctly, #3 on your list has already been implemented into the BTS theme as the entry/exit "elevator."
And in the BEE2Alpha, this same door was called the Vertical Security Door and was used for the clean styles.

**Comment by Luke18033** [comment]
Most of these aren't going to be implemented or have already been suggested elsewhere.

**Comment by valerakianskij-hub** [comment]
So, how do I get all these things?
(I'm writing through a translator, please reply in Russian)
