### ISSUE TITLE
Pulse Activator

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#1618]
A logic item that is only active for a certain amount of time before turning off, the length of duration can be changed via a timer option. When a connection is broke to the item however, it shuts off immediately. This will allow for a constant signal from one item to not be constant to another for say an or gate that will always remain on if one signal is constant but that or gate is connected to a cube dropper so a new signal wont spawn a cube. This item would release the constant signal so the non-constant can still apply.

**Comment by Luke18033** [comment]
Can't you already do this with delayers and logic gates?

**Comment by libbybapa** [comment]
As mentioned, I think that can be done using the delayer and logic gates.  I'm not totally sure, though.  Maybe I haven't had enough coffee yet, but I read that three or four times and it still doesn't make sense to me.  Can you provide a better description please?

**Comment by Konclan** [comment]
When you activate it with a signal it will only output for the time allotted or until the input is shut off.

**Comment by libbybapa** [comment]
That can already be done but is slightly complicated.  I'll make an example vid.

**Comment by libbybapa** [comment]
https://youtu.be/kQx3g8NONkI

The setup is as follows.  You need two additional AND gates (visible or invisible) between the activating object (button) and the deactivation delayer.  One of the AND gates is start enabled and connected to the second one.  The button is connected to both AND gates.  The second AND gate is connected to the deactivation delayer which is in turn connected to whatever object you want on for the limited time.  **The button is also connected directly to the object. 

Whenever the button is depressed the two AND gates connected in that manner create a single pulse.  That pulse turns on the deactivation delayer (and object it is connected to) for the time set on the delayer as long as the button remains depressed.  If the button stops being pressed, the object shuts off immediately.

**Comment by libbybapa** [comment]
Am I correct that it functions the way you were looking for?

**Comment by Konclan** [comment]
This is what I intend the function to be, yes. An item for this would help clear up logic so I don't have to use 2 different items. I don't really care if this is added or not I just thought it would be helpful for convenience sake.

**Comment by Konclan** [comment]
Moving to #3886
