### ISSUE TITLE
New Item: Standing Fizzler, Laser Field, and Door

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1620]
Wouldn't it be cool to have fizzlers, laser fields, and doors all on a thin wall? The door would be really useful, too, instead of having bulky walls.
The same could also be used as standalone walls, or ones that could float, if possible.

The way you would switch (for the fizzlers, etc.) would be Normal, Cube, and Sphere options.

Normal = Fizzler
Cube = Laser Field
Sphere = Door

**Comment by Luke18033** [comment]
Standing door is already implemented, the original BEE door is exactly that. Standing Fizzler and Laserfield have already been suggested: #257

**Comment by hop193** [comment]
Oh ok then. Thanks you.
