### ISSUE TITLE
The Half Glass Door´s Arm_64x64_rail" and "Telescope_arm_trans" models are clipping the floor/wall

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1621]
They needs to be downscaled a bit to prevent this:

![image](https://cloud.githubusercontent.com/assets/12244376/23229096/bfd48bb8-f91d-11e6-8712-26a05f7a2ebf.jpg)

**Comment by Luke18033** [comment]
🏳️‍⚧️

**Comment by LautaroL20** [comment]
> Luke18033 said: "transgender_flag"

Yep, it seems that Valve was gay friendly since a long time if we play attention to their P2 file names such as: `Telescope_arm_trans`, an interesting coincidence.
