### ISSUE TITLE
Request: Cake

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#1625]
It would be cool for the Cake item to appear in BEE2.4. If this is possible, it would also be interesting to see a cake icon for the Signage item as 19 on the timer. Thanks!

**Comment by Byzarru** [comment]
Cake as a sign will be included as option 26 as per #1093.

**Comment by Byzarru** [comment]
As far as cake, I think it might be a better idea to introduce a 'prop' item which includes various timer-pickable (or ICP selectable) items, with cake as one of the choices.

**Comment by Endermage77** [comment]
And we must warn the user that, as a rule, the player and the cake should never be in the same room at the same time, ever.

**Comment by libbybapa** [comment]
If you add cake, make sure to add the option to connect a trigger so I can fizzle it when the player gets close.  :-P

**Comment by hop193** [comment]
@Byzarru | The "Prop" idea is interesting, it would work well.
@libbybapa | Haha, that would be funny.

**Comment by ZombiePwner1** [comment]
This item would be completely pointless as there is no use for it.

**Comment by libbybapa** [comment]
The point would be entertainment.  Is there any real point to playing this game other than entertainment?

**Comment by Luke18033** [comment]
This would be part of #1626.

**Comment by Byzarru** [comment]
Cake is quite important in Rexaura.

**Comment by TheDarkBomber** [comment]
It would be decorative.

**Comment by Konclan** [comment]
Better left for UCPs
