### ISSUE TITLE
Prop

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1626]
This is based on my comment on #1625. This would be an assortment of prop items with customizable properties in the ICP and selectable with the timer option. By default, this item would include props like lamps, computers, radios, etc. but can be set to load models like cakes, monitors, and cameras. The model itself can be selected in the ICP, as well as its ability to be picked up, destroyed, weight, and material.

**Comment by TheDarkBomber** [comment]
There should be an `Itemvar` label, for items that use the ICP.

**Comment by TeamSpen210** [comment]
This would really be more suitable for Hammer, and couldn't really style correctly.

**Comment by Byzarru** [comment]
What about a set of premade models with preset parameters (liftable, destroyable, and weighted) that can be switched out? Some models would have styled variants as well (like computer chassis, radios, and lamps). In Clean, this item would likely be relegated to Rattman Dens and the like, but it would work wonders in the offices and industrial areas of BTS or in offices within Old Aperture. BTS right now looks very unnatural; it needs some decor to make it seem more like an actual maintenance area.

**Comment by Byzarru** [comment]
I think it was on Gitter that i suggested Furniture. That should be a separate item (if this is implemented), because it would need a different positioning system (I imagine that "Props" would use 8 positions while "Furniture" would use 4 positions).

**Comment by Luke18033** [comment]
I don't think the ICP would really be needed, there aren't that many props in the base game.

@TheDarkBomber - It would be ICP, not Itemvar.

**Comment by King0191** [comment]
Could we do something similar to the Signage item where you modify what specific items/props are what number? Cause I'm sure things like chairs, tables, Cake, etc. are all things people will want, among a ton more! 

Plus it would save people the trouble of figuring out what item is what. Since they can change it!

**Comment by TeamSpen210** [comment]
No.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the corresponding label after closing an issue.
