### ISSUE TITLE
Request: Some new styles

### ISSUE THREAD

**Issue by andremiles1** [BEEmod/BEE2-items#1628]
Hello.
I really want 2 new styles:
1- A Rattman inspired one, where he is really inside Aperture Labs and BTS hiding, and the windows are actually reversed - in normal puzzles we see observation rooms but on this style I imagine seeing puzzle chambers. He goes into the test chambers by these broken windows, take some objects like bridges or cubes to "solve" something inside Aperture to get to a place / activate or deactivate something to hide even more. Just like the ending of Portal 1.
The end of these puzzles is always he getting into a Rattman den, a safe place for him to rest and will always have a Companion Cube lying in there.

2- An outside (simulated) like chamber. You're still on Aperture but you can see the sky and the ground is grass and everything. Random trees, some of the puzzle elements are made from wood and the water don't warm you. But everything is fake, designed to make you feel outside (just like I think Portal 2 ending really is)

I know these styles are totally new and need so much time to make, but please consider my request.
Thank you so much, not only for this, but entirely for BeeMod. I love this mod so much <3
[Sorry, I know my english is terrible]

**Comment by Byzarru** [comment]
Rattman was already suggested before, and it was decided that it would be a specialized rehash of Overgrown. I've suggested adding props and overlay items to simulate Rattman areas, and Radelite has made a Rattman style in his addon pack for BEE2.2.

**Comment by Byzarru** [comment]
As far as the styles actually being developed:
Rattmann - Solid no. 
Outside - It's a no as well unless some juicy assets and methods are made up to suit outdoor testing (which I hope comes along). The closest to outdoors that BEE will get that I know of is the Stage style.

**Comment by Endermage77** [comment]
Imagine how funny it would be if the player were told they were going outside for once.
They exit the elevator, the door opens, and what you actually get is the same old chambers painted like dirt and sky.
I could totally see that being something GlaDOS would drop on a test subject.

**Comment by Luke18033** [comment]
Both of these would be difficult to reasonably implement in the Puzzlemaker.
