### ISSUE TITLE
Implement feature to have cracked lightstrips in overgrown.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1629]
![20170226160305_1](https://cloud.githubusercontent.com/assets/18079316/23338144/3f7152e4-fc3d-11e6-8f9e-7d6e508c95e2.jpg)

**Comment by TeamSpen210** [comment]
This isn't really a thing, that's a texture placed on top which shouldn't really even be possible to place like that.
