### ISSUE TITLE
Sticky Gel?

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1630]
Is the unused sticky gel possible to implement? It would be cool to have the unused sign graphics for it, too!

**Comment by TeamSpen210** [comment]
It isn't really, not without remaking every single item to have a sticky gel version among other things.

**Comment by hop193** [comment]
Ah, i see.

**Comment by ZombiePwner1** [comment]
@hop193 In hammer it's possible to do but puzzlemaker maps unfortunately not everything in the map has to be rotated which isn't possible to do in PeTI.

**Comment by Luke18033** [comment]
It's possible, but would require lots of work and really isn't worth it. Use Hammer if you want adhesion gel.
