### ISSUE TITLE
New items: Surf platform, Surf move platform, Death zone

### ISSUE THREAD

**Issue by goodDOS** [BEEmod/BEE2-items#1632]
Surf platform and Surf move platform
![Image](http://p1.bpimg.com/4851/6e72bc55d20b5d7a.png)

Death zone
![Image](http://p1.bpimg.com/4851/dfaad0794065efb0.png)

![Image](http://p1.bpimg.com/4851/9b7df7df38aa3836.png)

**Comment by Luke18033** [comment]
- Surf platform: Looks like the Portalable Piston Platform, which will be implemented via #95.
- Moving surf platform: Looks like a Portalable Track Platform, which has been suggested before.
- Hurt trigger: No. It's not very realistic to just randomly die or get hurt. In the situation you're using it, there's going to be a separate item added to do exactly that - see #1.
