### ISSUE TITLE
Sticky Gel (Not Adhesion Gel)

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1633]
This is NOT the mauve-colored adhesion gel, which has already been said time and again not to work well with the PTI.

Instead, this gel is simply what it sounds like: sticky.
Properties:
- Players cannot jump while standing on it
- Players move slower while standing on it
- Players fall slower when contacting it on the wall
- Objects stick to it regardless of gravity
- Objects resist being moved when pushed while on it
- Objects painted with sticky gel also have the properties listed above

I'm still not quite sure what color it would be, though.

**Comment by TheDarkBomber** [comment]
Can't add new gels.

**Comment by Luke18033** [comment]
You can, but they would need to replace Reflection Gel so you couldn't have both in the same map. It would be an alternate version of Reflection Gel, if anything.

**Comment by TheDarkBomber** [comment]
Or you can add it as a wall surface instead of a gel.

**Comment by Byzarru** [comment]
It it were a wall surface, it'd be a duplicate of #1336.

**Comment by Luke18033** [comment]
No, the gravity wall is different.

**Comment by Byzarru** [comment]
@TheDarkBomber Aren't you working on an item like this already?

**Comment by TheDarkBomber** [comment]
No.

**Comment by Endermage77** [comment]
I would be alright with not having this and reflection gel together.

**Comment by TheDarkBomber** [comment]
Actually, I think a brown would be a better colour.

**Comment by hop193** [comment]
The Cut Content color was sorta Purple.

**Comment by Endermage77** [comment]
Well, I suggested slimy green because sticky purple is already used by people who have managed to successfully replicate adhesion gel in their own maps.

**Comment by HelloIamapersonthatisalive** [comment]
How about like a yellowish white, like real glue

**Comment by Endermage77** [comment]
May cause confusion for people who have no sense of color and can't distinguish any shades of white, due to the presence of Conversion Gel.

**Comment by Luke18033** [comment]
Adding new gels involves some pretty hacky stuff which wouldn't work very well in the Puzzlemaker.

But you did totally just predict Minecraft honey blocks.
