### ISSUE TITLE
Physics Destruction Field

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1634]
A variant of the Physics Repulsion Field which destroys physics objects instead of blocking them. It does not block portal shots, fizzle portals, or kill the player. This would be a recolor of the PRF, but I'm not sure what color it should be.

**Comment by TheDarkBomber** [comment]
Either Red or Blue.

**Comment by Byzarru** [comment]
Blue. A deep cerulean, to be exact.

**Comment by TheDarkBomber** [comment]
That's not exact. Exact would be the RGB values.

**Comment by Byzarru** [comment]
#2A52BE

**Comment by TheDarkBomber** [comment]
That's the hex value. The RGB value is `42 82 190`. You divide this value by 1000 to get the colour value to put in the VMT, which is `0.042 0.082 0.190`.

**Comment by TeamSpen210** [comment]
Nope, you divide by 255.

**Comment by TheDarkBomber** [comment]
Not according to this: http://steamcommunity.com/sharedfiles/filedetails/?id=608136553

**Comment by TeamSpen210** [comment]
That's wrong. `[]` specifies a normal value, where 1 is maximum and 0 is minimum. `{}` can also be used to get 0-255 colours directly. Have you actually authored VMTs?

**Comment by TheDarkBomber** [comment]
So, in the VMT we would put [0.042 0.082 0.190]?

**Comment by libbybapa** [comment]
To be clear, this would be a matter inquisition field that allows portal shots through it.

**Comment by TeamSpen210** [comment]
@TheDarkBomber, no those are wrong numbers. It'd give nearly black. Put either `{42 82 190}`, or `[0.16 0.32 0.74]`.

**Comment by Luke18033** [comment]
One issue is that it's not possible to fizzle objects while still blocking portal shots.

**Comment by Luke18033** [comment]
*while *not* blocking portal shots.

**Comment by TeamSpen210** [comment]
It is actually possible, but it might give some incompatibility issues.

**Comment by HugoBDesigner** [comment]
Wouldn't it just be a matter of making a trigger that executes "Dissolve" on whatever triggered it?

**Comment by Luke18033** [comment]
Problem is that that will only work on cubes, it needs to be able to fizzle turrets as well. Additionally there are radios in some of the P1 corridors, which would also need to be fizzled.

**Comment by Luke18033** [comment]
One thing we could do is enable cube-fizzling and portal-blocking only when physics objects are nearby. That way it would only block portal shots when necessary. Alternatively we could just make it block portal shots all the time, it's not a big deal.

**Comment by TeamSpen210** [comment]
There's the `env_entity_dissolver` entity, which lets you trigger the visual effect on any arbitrary entity (non-brush). That would work, but I'm not sure how firing it on cubes would....

**Comment by HugoBDesigner** [comment]
If firing it on cubes becomes a problem, couldn't you just add a filter?

**Comment by Luke18033** [comment]
A while ago I tested this in Hammer. Dissolving a cube using an `env_entity_dissolver` does not fire the `OnFizzled` output. This would need to use multiple triggers probably, with filters to make sure cubes had their `Dissolve` input fired, everything else used the entity. Then there's still the glow effect to worry about...

**Comment by Luke18033** [comment]
We don't need more fizzlers
