### ISSUE TITLE
3D Factory Skybox may cause weird crashes when using it in styles other than BTS

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1635]
Original post by @ReikaKalseki (https://github.com/BEEmod/BEE2.4/issues/537)

![](http://i.imgur.com/2o8nrds.png)

"The map i am running is NOT BTS styled - I am getting this in clean style maps (though with the factory skybox) - and similarly worked until moments earlier. It has started bleeding into other styles and maps, including 1950s with the sphere interior skybox and clean with the corresponding skybox."

**Comment by ReikaKalseki** [comment]
For reference: I have been using it fine for a long time on several maps.

**Comment by Luke18033** [comment]
Should be fixed.
