### ISSUE TITLE
ICP parameters for Radios

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1637]
This came to me when I found all of the radio loops for Blue Portals at once. Radios should have a library of music to choose from in the ICP. Some tracks are short loops, like in BP, and some tracks are full songs, like elsewhere. This would include the Still Alive remixes, Exile Vilify, and the high energy loops from Blue Portals.

**Comment by TheDarkBomber** [comment]
Itemvars.

**Comment by KaziPlays** [comment]
Radios were removed for an undefined time. :(

**Comment by Luke18033** [comment]
Radios were removed permanently, unless we find a better place for them.
