### ISSUE TITLE
Portal 1 Elevator using wrong stop sound

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1639]
The Portal 1 elevator sound error has been fixed in the dev version. However, a new sound issue has been introduced: the elevator now uses the Old Aperture stop sound. This needs to be fixed.

**Comment by LautaroL20** [comment]
> A new sound issue has been introduced: the P1 elevator now uses the Old Aperture stop sound. 

LOL, thats really weird.

**Comment by TeamSpen210** [comment]
That sound is actually set in Portal 1, but it might not be triggered.
