### ISSUE TITLE
Darkness as a Testing Element

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1640]
While darkness in most situations is merely an annoying blunder on the map-maker's part, sometimes it can make for an interesting puzzle element.
So, may I suggest the following:
- <s>A "fizzler" type item, preferably black, that absorbs light passing through it</s> No
- A negative-brightness light, preferably toggleable
- For that matter, a regular toggleable light
- <s>An invisible block like the trigger that absorbs light</s> No
- A differnt-colored turret that can't see in the dark
- A light detector that activates when in light, "Start Reversed" makes it enable when in darkness

Further items will pend as I think.

**Comment by TeamSpen210** [comment]
This sort of thing I don't think is possible practically.

**Comment by Konclan** [comment]
What about something that works with light from blue portals?

**Comment by TeamSpen210** [comment]
That's not actually light, it's a set of sprites or beams.

**Comment by Endermage77** [comment]
You mean that there isn't any sort of way to measure the light level in an area?
At the very least can we have the toggleable light?
I wouldn't mind dropping the light-absorbers.

**Comment by TeamSpen210** [comment]
There might be in code, but I don't know of a way to do that in Hammer. Toggleable lights I don't think would be a good idea - due to the way they work it's very easy to get invalid light setups, and break things.

**Comment by TeamSpen210** [comment]
See #333.
