### ISSUE TITLE
Laser blocking Fizzler

### ISSUE THREAD

**Issue by andremiles1** [BEEmod/BEE2-items#1642]
I named it "Courage Enforcer Field"
It's made to block only lasers from Thermal Discouragement Beam, not Turret lasers (the laser they use to find a target), just to be clear. They destroy pellets too.

The player can pass through it. It block portals but don't reset then when you pass, and don't destroy cubes. In my mind, they have this color (#00ffcc).

It's open for discussion but I can see this fizzler blocking Light Bridges as well.

**Comment by TeamSpen210** [comment]
Unfortunately I don't believe this is possible without just blocking everything.

**Comment by TheDarkBomber** [comment]
And then it would just be the Closed Solid Field.
