### ISSUE TITLE
Texture missing on protruding pedestal button editor model.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1643]
![20170303073212_1](https://cloud.githubusercontent.com/assets/18079316/23531893/b4924070-ffe3-11e6-90cc-fa0421c50133.jpg)

**Comment by Luke18033** [comment]
This is a development version issue, the release version displays the texture fine.

**Comment by ZombiePwner1** [comment]
@Luke18033 I don't even have the development version you wheely.

**Comment by ZombiePwner1** [comment]
Actually i'm starting to think there is something wrong with my beemod. Every so often the error where it says resart when reaching exit keeps on correcting itself from time to time and i'm starting to think my beemod keeps switching from the dev version to the regular then back to the dev version.

**Comment by TeamSpen210** [comment]
That would be something different - that stylevar is redefined in each package using it, I only fixed some of them so depending on which it happened to load first it would or would not display.

**Comment by LautaroL20** [comment]
> Luke18033: "This is a development version issue, the release version displays the texture fine."

Thats wrong, the public release had a missing texture on its base´s frames because someone removed the required materials (https://github.com/BEEmod/BEE2-items/pull/1421/commits/6404e08c7be8c4f4bf5a04af1bcd0621b7b84d6f) wich wasn´t really duplicated btw... But its fixed on the Development Version since a time ago.

**Comment by TeamSpen210** [comment]
That material was already present in that folder, it's best if we don't have duplicates.
