### ISSUE TITLE
Coop checkpoint is completely broken.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1644]
When atlas is killed he respawns at the map's starting area and when p-body respawns she respawns in atlas's dropper.

**Comment by TeamSpen210** [comment]
Sounds about right.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Indeed.

**Comment by LautaroL20** [comment]
Sounds about duplicated: https://github.com/BEEmod/BEE2-items/issues/1564
