### ISSUE TITLE
Bug:  Force Deflection Field Resets to Center

### ISSUE THREAD

**Issue by libbybapa** [BEEmod/BEE2-items#1649]
I have noticed that whenever the geometry is changed in the map, any force deflection fields in the map reset to the center position.

**Comment by TheDarkBomber** [comment]
Screenshot?

**Comment by libbybapa** [comment]
I thought the description was fairly straightforward, but if a screenshot or six help I'm happy to oblige.

![20170303113403_1](https://cloud.githubusercontent.com/assets/19520567/23563795/7a3bda90-0005-11e7-9aa0-317921f14076.jpg)
![20170303113406_1](https://cloud.githubusercontent.com/assets/19520567/23563796/7a3d0992-0005-11e7-8ae5-c4c8d4cc86fb.jpg)
![20170303113409_1](https://cloud.githubusercontent.com/assets/19520567/23563797/7a3d4baa-0005-11e7-8887-950b1fb95b5e.jpg)
![20170303113415_1](https://cloud.githubusercontent.com/assets/19520567/23563799/7a3df9ce-0005-11e7-8619-13d146ba34e4.jpg)
![20170303113418_1](https://cloud.githubusercontent.com/assets/19520567/23563800/7a3e9aaa-0005-11e7-852a-47ea1ff71883.jpg)
![20170303113421_1](https://cloud.githubusercontent.com/assets/19520567/23563798/7a3e0c7a-0005-11e7-8759-5a617ac29d72.jpg)

**Comment by libbybapa** [comment]
As I said, changes in geometry cause any force deflection fields to reset to the center of voxel position.  Other special fizzlers are not affected.

**Comment by libbybapa** [comment]
I reinstalled the fr_fizzlers packages and the issue is fixed.  It must have been something with my own machine/installation.  Closed.
