### ISSUE TITLE
Puzzlemaker´s Exit Door isn´t open by default

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1653]
![20170303230857_1](https://cloud.githubusercontent.com/assets/12244376/23575090/7076c9aa-0066-11e7-92af-95406663a2d9.jpg)

**Comment by TheDarkBomber** [comment]
You have the wall feature?

**Comment by Luke18033** [comment]
This isn't an issue with BEE2.4, the default chamber is hardcoded into the game. I actually have the same problem with a BEE2.2 map I'm working on.

**Comment by LautaroL20** [comment]
@TheDarkBomber - Yes, i get it back for my build version so i can use it for my latest SP chamber im going to release soon, and this one doesn´t take any space.

**Comment by TheDarkBomber** [comment]
If you re-implemented the wall feature, why not put them into PR25?

**Comment by LautaroL20** [comment]
Not sure, since there is a decorative item in the works thats being developed by Spencer, but if i do it would be excluding the "cross wall" since its already in beemod.

**Comment by LautaroL20** [comment]
Well, i tested this a day ago and aparently its fixed now.

**Comment by LautaroL20** [comment]
Nope, it still happens. Ill gonna check the editoritems.txt to see whats going on here....

**Comment by ZombiePwner1** [comment]
@LautaroL20 See you finally fixed this. Also come on steam.
