### ISSUE TITLE
Laser Cube is floating in a "mysterious way"

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1655]
The laser cube floats, at least when taking the cube under it away.
![20170304104319_1](https://cloud.githubusercontent.com/assets/25728252/23575459/7fa57fc2-005a-11e7-88e5-6c48d4bd66cf.jpg)
![20170304104326_1](https://cloud.githubusercontent.com/assets/25728252/23575461/82d58908-005a-11e7-8416-475c6d052987.jpg)

**Comment by TeamSpen210** [comment]
I can't fix this as far as I know.

**Comment by hop193** [comment]
Alright, thanks for the info.

**Comment by Konclan** [comment]
Actually there is a way, apperently the map ignition fixes this problem somehow, I'm going to look into the map file itself to see what they did

**Comment by TheDarkBomber** [comment]
No, do not fix this. It's unfixable.

**Comment by TeamSpen210** [comment]
There is a way to fix it...

**Comment by TheDarkBomber** [comment]
NO, DON'T FIX IT.

**Comment by TeamSpen210** [comment]
Why?

**Comment by TeamSpen210** [comment]
There'll be an option to disable the fix.

**Comment by TheDarkBomber** [comment]
Make it a stylevar. Also, Item Configs should be called Itemvars.

**Comment by ZombiePwner1** [comment]
Seems this only happens when the cube is redirecting a laser.

**Comment by libbybapa** [comment]
It is a well-known Valve glitch and should definitely be fixed.  The shortcuts that it creates are very irritating.

**Comment by TheDarkBomber** [comment]
Make it a stylevar!!!!!!

**Comment by libbybapa** [comment]
I don't really care if it is a stylevar as long as there is some way to eliminate it, just as Teamspen asked previously, my own curiosity makes me ask why do you want this to glitch to be preserved?????????

**Comment by Luke18033** [comment]
It doesn't really need to be a stylevar...

**Comment by ZombiePwner1** [comment]
@TheDarkBomber If this was a stylevar it would be a waste of space.

**Comment by Byzarru** [comment]
If there is an item causing a break in logic, it should be fixed.

**Comment by libbybapa** [comment]
The 'Style Properties' window has the option 'Prevent Portal Bump (fizzler)'.  I would imagine this as a similar check box.

**Comment by quat1024** [comment]
How can this reasonably be fixed, other than having a giant trigger cover the map and constantly wake any sleeping laser cubes? (or spamming an ent_fire). Which is obviously a sort of crappy solution.

It's fixed for platforms, and that's how platforms do it \\\_(-.-)\_/

> It doesn't really need to be a stylevar...

Why not? A number of maps use it, and it's an interesting bug anyways, might as well leave it.

Imo fixing this bug is like trying to put logic in place to fix the excursion funnel glitch. Everyone knows it's cheating

**Comment by TeamSpen210** [comment]
I'd do it with a entity called `point_entity_finder`, which lets you send inputs to entities matching a filter. Then set it to random and run every second or so. Then it'll only affect one cube at a time to prevent lag. The only issue is that waking the cube can make it jump a bit/move, so it'd need to be a stylevar regardless.

**Comment by hop193** [comment]
So, this is gonna be fixed, or...

**Comment by Luke18033** [comment]
This is implemented in 4.36.0
