### ISSUE TITLE
Allow observation rooms to be placed in corners with eachother to form a big corner observation room.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1656]
![20170304132720_1](https://cloud.githubusercontent.com/assets/18079316/23576372/756938e4-00de-11e7-8940-bc3f287aad9d.jpg)

**Comment by Flametusk** [comment]
They should also do this on inside corners as well, like in TS_Mind_Swept's test Both Sides (Remake)

I don't include a picture because I'm on mobile, and I also don't know how to include a picture.

**Comment by TeamSpen210** [comment]
Duplicate of #1165.
