### ISSUE TITLE
Protuding pedestal buttons can be mysteriously placed on observation rooms.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1657]
![20170304133709_1](https://cloud.githubusercontent.com/assets/18079316/23576428/c050535a-00df-11e7-99ae-789149fb1ec0.jpg)

**Comment by Luke18033** [comment]
They don't have `OccupiedVoxels`, and they don't need it. Adding that would actually prevent placement in goo, making this item far less useful.

**Comment by ZombiePwner1** [comment]
But it looks weird on observation rooms.

**Comment by Luke18033** [comment]
Then don't put it there...

**Comment by Byzarru** [comment]
ahem ahem **Sturgeon's Law** cough cough
