### ISSUE TITLE
Spheres easily roll off floor buttons in BTS

### ISSUE THREAD

**Issue by quat1024** [BEEmod/BEE2-items#1662]
In this map: http://steamcommunity.com/sharedfiles/filedetails/?id=864740498

Head down the light bridge, cross the fizzler to the left, and try to place a sphere on top of the button. It rolls off and won't stay put, unless you balance it without it rolling. Which is possible, but *super* frustrating, lol

**Comment by TeamSpen210** [comment]
I must have forgotten to fix that (it's fixed in Old Aperture styles for example.)
