### ISSUE TITLE
Suggestion: Allow to choose Different Elevator models from a different style

### ISSUE THREAD

**Issue by SW50000** [BEEmod/BEE2-items#1663]
Some multi-part maps change styles between parts, here's an example from DFD Part 4 and
Portal Stories: Mel
![20170304213400_1](https://cloud.githubusercontent.com/assets/20195894/23584285/6911985e-0122-11e7-86d0-3ac173373f6d.jpg)

![20170304213006_1](https://cloud.githubusercontent.com/assets/20195894/23584286/7374269a-0122-11e7-9fd2-05823338cc2a.jpg)

**Comment by ZombiePwner1** [comment]
Not sure what use this would have but still might get added. And @SW50000 i remember commenting on your screenshots.

**Comment by SW50000** [comment]
@ZombiePwner1 Yeah, flooding my notifications, lol.

**Comment by SW50000** [comment]
Oh and By that I meant, some map series's made in PeTI might switch styles on another part, and this was for a smother transition between parts.

**Comment by TheDarkBomber** [comment]
What about styles that have different sized elevators, or no elevators (like BPDC style)?

**Comment by Byzarru** [comment]
Then this option wouldn't be available. Not to mention the Vacuum Delivery System and Extended Relaxation Vault stylevars that may be added.

**Comment by SW50000** [comment]
@Byzarru 
Okay

**Comment by Luke18033** [comment]
I don't think this would be too useful, or really make much sense.
