### ISSUE TITLE
Players can get stagnant for ever on the wall features camera.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1664]
![20170305161358_1](https://cloud.githubusercontent.com/assets/18079316/23585668/f1de4ff0-01be-11e7-8254-b1a134a78eef.jpg)

![20170305161623_1](https://cloud.githubusercontent.com/assets/18079316/23585673/1baa5f2c-01bf-11e7-825c-2e64d19d2ab0.jpg)

**Comment by Luke18033** [comment]
The wall feature isn't in BEE2.4...

**Comment by Byzarru** [comment]
This is Lautaro's addons, I think.

**Comment by ZombiePwner1** [comment]
@Luke18033 This is one of @LautaroL20's items and it's still a bug that needs to be fixed.

**Comment by Luke18033** [comment]
Don't put it here though...

**Comment by Luke18033** [comment]
@TeamSpen210 already said he isn't going to include the wall feature, BEEmod/BEE2.4#414 would replace it.

**Comment by LautaroL20** [comment]
Uhmm, there will be a small complaint with the future TSpen´s decoration item, and if you play atention to the post´s description, it says: "decorations are decorative 'items' **automatically generated**" that aparently means youll have no control on wich wall it will display in the map. 

Thats why ive got back the original features for my version, and @ZombiePwner1 just asked for it on Steam. As for the bug, its easily fixeable by placing a player clip texture covering the camera.

**Comment by Luke18033** [comment]
I understand that the wall feature is a useful item. I am just pointing out that since it isn't actually in BEE2.4, this issue shouldn't be reported here.

I think there should be a way to manually place decorations, but @TeamSpen210 doesn't want that for some reason...
