### ISSUE TITLE
Coop exit door has duplicate cameras.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1666]
![20170305170426_1](https://cloud.githubusercontent.com/assets/18079316/23585945/d7c848b2-01c5-11e7-92ed-22fad16a239f.jpg)

**Comment by hop193** [comment]
Looks so weird.

**Comment by TeamSpen210** [comment]
OH, is this Original Clean?

**Comment by LautaroL20** [comment]
https://github.com/BEEmod/BEE2-items/issues/1392
