### ISSUE TITLE
Allow p-body to have a paint gun aswell in aperture tag.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1669]

**Comment by Luke18033** [comment]
You can't really make maps that require two paint guns...

**Comment by ZombiePwner1** [comment]
You can actually p-body can have cleansing gel and reflection gel.

**Comment by TeamSpen210** [comment]
That would be a bit odd, actually now I think about it it really doesn't offer that much more puzzle complexity, not like 4 portals do. Cleansing gel isn't that useful (using Propulsion is usually sufficent), and neither is reflection gel overall.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Well then propulsion gel and reflection gel then. I mean atlas already has propulsion gel but perhaps p-body can have it aswell.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 If you don't add this to beemod i'm fine with that but i would atleast like to have this for myself since have reflection gel in the paint gun would be a cool feature.

**Comment by Byzarru** [comment]
I could imagine a few crafty people would be able to make good puzzles with two Propulsion/Repulsion Gel guns. Read: Few, but I imagine it _is_ possible.

**Comment by quat1024** [comment]
Maybe Blue gets repulsion-only and Orange gets propulsion-only? ;]

Would maybe allow for some crazy "Confinement" style puzzles

**Comment by TeamSpen210** [comment]
The other problem is that we'd want to alter the gun to show the matching gel colours in the tubes.

**Comment by Byzarru** [comment]
Both players should have access to the same paint guns.

**Comment by quat1024** [comment]
Any reason why? It would lead to interesting asymmetrical maps

**Comment by Byzarru** [comment]
That could be achieved with the CO-OP separation checkpoint and the individual Paint fizzlers. This way, the mapper can control whether or not each player gets a special gel or both, and it's not up to whether someone is hosting/joining to determine what gel a player can use.

**Comment by quat1024** [comment]
True, but if both players are in the same puzzle it would be impossible to
ensure 2 people don't both have the same gel (which might be important).

And, who is hosting already matters, because the other guy gets the portal
gun :P

**Comment by Flametusk** [comment]
How about conversion gel and repulsion gel, while the other has a portal gun?

**Comment by TeamSpen210** [comment]
It's possible to ensure it - have a dropdown after the checkpoint, no gun fizzlers to swap, and maybe some paint/normal fizzlers to stop you bouncing up.

**Comment by TeamSpen210** [comment]
The other problem is what to do with the fizzler signage.

**Comment by ZombiePwner1** [comment]
@Flametusk The whole point of this suggestion is to allow both bots have a paint gun not a portal gun.

**Comment by Luke18033** [comment]
I don't think this is a very good idea.

**Comment by ZombiePwner1** [comment]
@Luke18033 Not everyone has to use it it's a stylevar option so it wouldn't take away p-body's portal gun in aperture tag all the time.

**Comment by Luke18033** [comment]
It's useless though, you might as well just make the map singleplayer.

**Comment by ZombiePwner1** [comment]
@Luke18033 It's called cleansing gel and reflection gel u wheely >:D

**Comment by Luke18033** [comment]
It's called we can't change the colors of the paint gun you wheely >:D

**Comment by ZombiePwner1** [comment]
@Luke18033 And you just ruined it.

**Comment by Luke18033** [comment]
Fine, you can keep this open, but it's not going to be added...

**Comment by ellingtonvengaboysmuseum** [comment]
Banned and Closed

**Comment by Luke18033** [comment]
As you can see I was trying to close it, but *somebody* wouldn't let me...
