### ISSUE TITLE
BTS Large Observation Room

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/BEE2-items#1673]
The BTS observtion room will be a reversed one. It looks into a randomly generated test chamber section.

The chambers have all-white wall and black wall variant (random).
They're small spaces, like an alcove where you 'collect' a test element or something - that way there isn't much to render or make.

Chambers (in rough order of priority):

* Funnel beaming past, into l bend on right
	* Gel dripping into funnel (grey, white, orange, blue)
* Speed Gel runway
* Turrets guarding a cube (small chance for companion)
* Faith Plate with a cube (muffled faint sound?)
* Random bunch of laser relays (say 8 positions randomly chosen)
* Cube dropper with cube on floor and pedestal button, fizzler
* Button on ceiling with drop below

**Comment by Luke18033** [comment]
It's funny that you opened this, I was thinking about this exact design earlier!

**Comment by TeamSpen210** [comment]
Carl Kenner was going to implement it at some point.

**Comment by andremiles1** [comment]
This is an awesome idea.
I've suggested something like this on a request that (I think) got deleted haha

**Comment by TeamSpen210** [comment]
Does anyone have suggestions for other variants?

**Comment by Byzarru** [comment]
Will large obs rooms mesh with the 1*1 obs rooms or does the large obs room stand alone?
Large obs room chambers should be selectable via timer and ICP (infinity is random) so mappers can further customize their maps.

**Comment by Konclan** [comment]
Turret shooting range like in portal stories mel

**Comment by Endermage77** [comment]
There's two different designs I can think of for these reversed BTS obs rooms:
1. It's simply the "chamber" on the other side of  some glass that is directly in the test proper
2. The "chamber" and the glass looking out into it are in a small office space like those seen in all the normal observation rooms, which is its own room accessible via an openable door.

**Comment by SW50000** [comment]
These are some I thought of:
- test chamber entrance corridor
- Laserfield in the middle of a test chamber
- Funnel over goo (With a chance of it being reversed)

**Comment by Luke18033** [comment]
> test chamber entrance corridor

@SW50000 - Entry corridors don't usually have observation rooms...

**Comment by SW50000** [comment]
> Entry corridors don't usually have observation rooms...

I thought it would be a nice suggestion, and the testchamber sign would be there

**Comment by Endermage77** [comment]
It still would make no sense to have an entire observation room devoted to observing an entry corridor.
Generally, the test proper is a more important target for observation.

**Comment by TeamSpen210** [comment]
There are obs rooms in P1 corridors sometimes.

**Comment by SW50000** [comment]
> It still would make no sense to have an entire observation room devoted to observing an entry corridor.
Generally, the test proper is a more important target for observation.

> There are obs rooms in P1 corridors sometimes.

Why are we just talking about that one suggestion?

**Comment by TeamSpen210** [comment]
@Endermage77, it can't be a full room, because we can't allow you to stand on the room or place portals there.
A laserfield/fizzler would be good, perhaps with some antlines running off into the distance. The funnel could be with the other funnel idea I had.

**Comment by iEnderMan06** [comment]
I can start work on this if you need me to @TeamSpen210 if I'm correct the actual test elements won't actually have to work correct?

**Comment by TeamSpen210** [comment]
Yes, since you can't interact with them or anything. But they should look right so funnels meed to be real for example.

**Comment by Endermage77** [comment]
Well, when I said office, I meant embedded into the wall where the normal obs room would be, and what you see in the test chamber is just a door leading into it.
As opposed to jutting out into the test chamber, which would be a bit odd and not very helpful.

**Comment by TeamSpen210** [comment]
The problem then is how to reasonably prevent the player from walking inside - for example there could be turrets next to the observation room, and we don't want to give them a hiding place if the puzzle designer didn't want there to be.

**Comment by iEnderMan06** [comment]
I'll get to work then @TeamSpen210

**Comment by Endermage77** [comment]
Ah. then perhaps if that approach is being taken, the door could be locked with an activation signal or something. Start Open would do nicely here.

On the other hand, I understand if this approach isn't going to happen.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
