### ISSUE TITLE
BTS ignores disabled Restart when Reaching Exit

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1676]
The map restarting is determined by the spawn location, instead of the stylevar as it should be.

**Comment by Endermage77** [comment]
So, shouldn't this be called "Disabling Restart when Reaching Exit doesn't work on BTS"?

**Comment by Luke18033** [comment]
This also affects Portal 1, updated with more information

**Comment by Luke18033** [comment]
Actually seems to be fixed for P1 now.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
