### ISSUE TITLE
Implement a stylevar to make laserfields use the death fizzler texture in Aperture Tag

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1677]
If actual death fizzlers are present in the map, this is overridden to off.

**Comment by TeamSpen210** [comment]
I reckon this is just confusing, really.

**Comment by Luke18033** [comment]
Make it only work in Aperture Tag.

**Comment by ZombiePwner1** [comment]
This definitely should be implemented since the death fizzlers in aperture tag allow gel to go through unlike regular fizzlers.

**Comment by TeamSpen210** [comment]
Regular laserfields do too.
