### ISSUE TITLE
Confetti Dropper / Cannon

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#1679]
A dropper that spits out confetti when activated and plays the party noise maker noise, multiple activation or one time use (perhaps an option). If possible this item could be placed on the walls and floor and shoot out faster like a confetti explosion.

**Comment by ZombiePwner1** [comment]
@Konclan If i'm correct the Confetti is a particle.

**Comment by hop193** [comment]
That would be cool to see.

**Comment by Endermage77** [comment]
Surprise.

**Comment by HelloIamapersonthatisalive** [comment]
Ooh, I like

**Comment by TeamSpen210** [comment]
I don't actually know if the particle effect behaves correctly when sideways, it might need to be a certain orientation and distance from the floor.
