### ISSUE TITLE
Track platforms have mysterious texture overlaps on them.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1680]
![20170308181533_1](https://cloud.githubusercontent.com/assets/18079316/23699779/5f9f57aa-042b-11e7-9d6c-32fad62308ef.jpg)

**Comment by TeamSpen210** [comment]
Oh, it looks like there's two of them... actually give them a track to move with.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Should still fix it though.

**Comment by Luke18033** [comment]
Seems to be fixed
