### ISSUE TITLE
Players can get mysteriously stuck on track platforms if jumping on them.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1681]
![20170308181734_1](https://cloud.githubusercontent.com/assets/18079316/23699820/92ae8a08-042b-11e7-8488-34cdb7abe1b4.jpg)

**Comment by TeamSpen210** [comment]
Where specifically?

**Comment by ZombiePwner1** [comment]
On all the touchable parts ontop of the platforms.

**Comment by Luke18033** [comment]
I don't think this happens anymore
