### ISSUE TITLE
Active-Turret-Only Detector

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1683]
A variant of the (Not-Quite-Yet-Implemented) Turret Detector that only detects turrets that are active.
Reversing it makes it only detect inactive turrets.

**Comment by Luke18033** [comment]
This would be a Button Type option on the Turret Sensor with Weighted = Standard, Cube = Active-only and Sphere = Inactive-only.

**Comment by TeamSpen210** [comment]
I'm not sure if this is easily doable, it'd work better if it was attached to  a specific turret on a square.
