### ISSUE TITLE
Corner wall tile

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#1684]
![untitled drawing](https://cloud.githubusercontent.com/assets/16567080/23767233/7b4d9e6a-04cd-11e7-9d51-567e611ea6b7.png)

**Comment by TeamSpen210** [comment]
Suggestions for the other 3 button type options, or whatnot?

**Comment by Konclan** [comment]
One where it is just a tiny corner and one were it is in the center

**Comment by Konclan** [comment]
![untitled drawing](https://cloud.githubusercontent.com/assets/16567080/23772219/cdb2bde0-04df-11e7-8f9a-c0f9325c83c1.png)

**Comment by TeamSpen210** [comment]
I really need to finish the tiling rewrite, then I can give you a quarter tile item...

**Comment by Byzarru** [comment]
There also needs to be an item like this for the TWTM style, for the non-portalable white panels.

**Comment by Konclan** [comment]
No, white non-portable walls is a terrible idea

**Comment by Byzarru** [comment]
That's the design aesthetic that TWTM uses.

**Comment by Konclan** [comment]
TWTM was trash

**Comment by Byzarru** [comment]
So was Aperture Tag, and yet it's commanding full BEE support.

**Comment by TeamSpen210** [comment]
The Quarter Tile makes this unnecessary.

**Comment by Konclan** [comment]
Would still be nice to have a different size wall tile for speed, however its not necessary
