### ISSUE TITLE
Security Camera?

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#1685]
Kind of a dumb question, but is there an actual security camera? I'm aware of the screen camera, but that only focuses on one specific spot, rather than to follow the player. Plus, you can't take them off the wall. Is there an actual security camera that can be shot off the wall?

**Comment by Konclan** [comment]
I have requested an camera for decoration a while back

**Comment by Byzarru** [comment]
I think that is going to be implemented in Lautaro's addons as part of the Wall Features item. Can't say for sure, though. TeamSpen is working on adding decorations to BEE itself, but I don't know if it will be automatically generated or if you will be able to place individual items (which negates the need for the Wall Features item).

**Comment by TeamSpen210** [comment]
These would want to be a specific item.

**Comment by ZombiePwner1** [comment]
@Byzarru Lautaro does have a camera on his wall features item since he gave a few of his items to me. But a feature to place a camera was in the old beemod.

**Comment by Byzarru** [comment]
Read #1626.

**Comment by Konclan** [comment]
#912
