### ISSUE TITLE
Portal 1 Overgrown

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1687]
Simple. Uses Portal 1-like graphics, just overgrown style, rather than using Portal 2 Overgrown styles. Can be useful when trying to remake Portal 1 test chambers, overgrown. For example, it would also use the Portal 1 Antlines, just slightly dirtier to add a nice touch.

**Comment by Byzarru** [comment]
This was suggested before, but I think it wasn't going to be added because all of the original textures need to be re-made and mossed up.

**Comment by hop193** [comment]
Ah, I got it. Thanks for the info!

**Comment by TeamSpen210** [comment]
Portal 2 overgrown is more like P1 style in a number of aspects, like the use of pistons for panel supports.
