### ISSUE TITLE
[Dev] Death Fizzler showing all brushes on start

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#1688]
When the map first starts the death fizzle starts with showing all 3 textures.
![20170309194342_1](https://cloud.githubusercontent.com/assets/16567080/23778636/0e33e878-0501-11e7-86ce-e729e02e0cc1.jpg)
![20170309194352_1](https://cloud.githubusercontent.com/assets/16567080/23778637/0e3b294e-0501-11e7-8681-311c60c8d942.jpg)

**Comment by Konclan** [comment]
Actually this is kinda cool, could you make it so that there is a way to get a fizzler and laser field like that like an item or item varient of the death fizzler?

**Comment by Byzarru** [comment]
While I personally think that this mishmash is ugly, Portal 1 already does this and pulls it off quite nicely. I think that this could be a potential alternate model to the standard death fizzler, so it doesn't get confused with the red fizzler from ApTag in ApTag maps.

**Comment by quat1024** [comment]
> Actually this is kinda cool, could you make it so that there is a way to get a fizzler and laser field like that like an item or item varient of the death fizzler?

Oddly enough I kind of agree with this, one of the problems I have with death fizzlers is that it's not immediately obvious *which* component of the death fizzler is being turned off. If you're not familiar with the death fizzler texture, or haven't played that (crappy tbh) level in Portal Stories: Mel, it's pretty much guesswork.

Usually when I want to include a death fizzler I can clarify this by splitting it into a separate fizzler and laserfield but that is a lot wider and the antlines can get messy.
