### ISSUE TITLE
Unpaintable tiles.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1690]
How this would work is that if you place it will be a special tile that can't be painted. A trigger paint cleanser would be on the front of the tile to prevent paint.

**Comment by andremiles1** [comment]
Why don't you use glass?

**Comment by Byzarru** [comment]
See #1510.

> Yeah, but glass is also unportalable.
The unpaintable tiles could be portalable or not.
I suppose the main problem is distinguishing paintable and unpaintable tiles.

> There's the paint fizzler and the lcef, but they aren't very flexible.
Ed: Make the tiles pink, because the LCEF is pink.

**Comment by TeamSpen210** [comment]
There's a material property which makes it unpaintable. The question is what would be a logically unpaintable surface?

**Comment by ZombiePwner1** [comment]
The unpaintable tiles could use a special texture.

**Comment by Byzarru** [comment]
> Make the tiles pink, because the LCEF is pink.

**Comment by TheDarkBomber** [comment]
Duplicate of #1510.
