### ISSUE TITLE
Aperture tag 70's old aperture causes compile error.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1691]
ROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Jun  4 2014)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Aperture Tag\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Aperture Tag/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
 | Could not open instance file instances/BEE2/70s/items/tag_fizzler/sign_off.vmf
 | 
 |_

[INFO] BEE2_config.save(): Saving changes in config "C:\Users\Josh\Desktop\File folder\Prl 24\config/compile.cfg"!
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

Why @TeamSpen210 ????

**Comment by LautaroL20** [comment]
It looks like the sign_off.vmf is into the wrong folder or so...

**Comment by ZombiePwner1** [comment]
@LautaroL20 Found out this only happens if the start enabled property on the paint gun field item is off.

**Comment by TeamSpen210** [comment]
It's only used in that mode.
