### ISSUE TITLE
Old 70's aperture coop exit door mysteriously closes if one player walks in and out.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1692]
![20170310180521_1](https://cloud.githubusercontent.com/assets/18079316/23790978/4c8270a2-05bc-11e7-8076-47f97536d63e.jpg)

![20170310180525_1](https://cloud.githubusercontent.com/assets/18079316/23790980/4e96d90a-05bc-11e7-8ccf-fcd96a931b89.jpg)

![20170310180528_1](https://cloud.githubusercontent.com/assets/18079316/23790981/50aebc58-05bc-11e7-8ad6-667729777449.jpg)

**Comment by LautaroL20** [comment]
Isnt this AT? It should have the appropiate label if so.

**Comment by TeamSpen210** [comment]
They use the same logic, it just adds that fizzler.

**Comment by Luke18033** [comment]
Should be fixed now.
