### ISSUE TITLE
P1 Chamberlock Editor Model Missing

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1694]
This bug happens on the master version, as far as I know.

**Comment by Luke18033** [comment]
I don't have this issue.

**Comment by TeamSpen210** [comment]
It's because you have the original addons installed, so you have the model from there.

**Comment by Luke18033** [comment]
Why haven't you ported it over then?

**Comment by TeamSpen210** [comment]
I want to remake it.
