### ISSUE TITLE
Glass Item causes "Failure To Compile" on P1 Style

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1699]
VBSP failed.

[INFO] vbsp.main(): BEE VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'fizz_visiblity': '0'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 6
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 3
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: True
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (21 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cond.fizzler.fizzler_out_relay(): Fizzler data: {'marker_inst': [], 'pos_to_name': {}, 'fizz_by_name': {}, 'model': 'instances/bee2/p1/items/tdb/csfi_model.vmf', 'base': 'instances/bee2/p1/items/tdb/csfi_base.vmf', 'fizz_id': 'item_tdb_csfi', 'fizz_bases': {'instances/bee2/p1/items/fizzler/fizzler_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/paint_fizz/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/p1/items/fr/csf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/p1/items/fr/fdf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/p1/items/fr/mif_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/p1/items/death_fizz/base.vmf': ItemConnections(in_act=('branch_fizz', 'ToggleTest'), in_deact=('branch_las', 'ToggleTest'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/p1/items/physler/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/rex/pellet_field_base.vmf': ItemConnections(in_act=(None, ''), in_deact=(None, ''), out_act=('out', 'OnUser2'), out_deact=('out', 'OnUser1')), 'instances/bee2/p1/items/tdb/csfi_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, ''))}, 'fizz_models': {'instances/bee2/p1/items/physler/model.vmf', 'instances/bee2/p1/items/tdb/csfi_model.vmf', 'instances/bee2/p1/items/fizzler/fizzler_model.vmf', 'instances/bee2/p1/items/fr/mif_model.vmf', 'instances/bee2/p1/items/fr/csf_model.vmf', 'instances/bee2/clea[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['pack_p1_radio_clean', 'spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=5318, misses=335, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'blockplayergelbomb': True, 'doorcameras': True, 'p1_ported_pgun': True, 'restartonexit': False, 'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': False, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/p1/set_portalgun.vmf', 'instances/BEE2/p1/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Lautaro\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Lautaro\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
    exec(code, m.__dict__)
  File "vbsp_launch.py", line 7, in <module>
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\vbsp.py", line 3583, in main
    change_func_brush()
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\vbsp.py", line 2829, in change_func_brush
    grate_temp.apply(side, change_mat=False)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\template_brush.py", line 288, in apply
    mat, face.uaxis, face.vaxis, face.ham_rot = self[face.normal().as_tuple()]
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\template_brush.py", line 272, in __getitem__
    mat, axis_u, axis_v, rotation = self._axes[tuple(normal)]
ValueError: not enough values to unpack (expected 4, got 3)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Lautaro\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Lautaro\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
    exec(code, m.__dict__)
  File "vbsp_launch.py", line 7, in <module>
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\vbsp.py", line 3583, in main
    change_func_brush()
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\vbsp.py", line 2829, in change_func_brush
    grate_temp.apply(side, change_mat=False)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\template_brush.py", line 288, in apply
    mat, face.uaxis, face.vaxis, face.ham_rot = self[face.normal().as_tuple()]
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\template_brush.py", line 272, in __getitem__
    mat, axis_u, axis_v, rotation = self._axes[tuple(normal)]
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by TeamSpen210** [comment]
Fixed.
