### ISSUE TITLE
Cutout tiles cause leaks

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1700]
When placed in the corner of a map, sometimes they can leak.
![hammer_2017-03-11_17-08-34](https://cloud.githubusercontent.com/assets/6296061/23833736/9387595a-0728-11e7-8880-8bb30020021c.png)

**Comment by Luke18033** [comment]
I don't see it.

**Comment by HugoBDesigner** [comment]
It was on the outside. Should have taken another screenshot before fixing, sorry about that.

**Comment by Luke18033** [comment]
@TeamSpen210 What exactly is the status of cutout tiles on the geometry branch, are they working properly?

**Comment by TeamSpen210** [comment]
They do nothing.

**Comment by Luke18033** [comment]
What are you planning to do with them?

**Comment by Luke18033** [comment]
Cutout tiles are removed for now, when they're brought back this will be fixed.
