### ISSUE TITLE
Detached flip-panels

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1702]
Mostly for conversion gel-centered puzzles, they're flip-panels not attached to any walls, but instead placed on the floor. They could be accessed from both sides, one of them being portalable and the other not. Additionally (although I'm not too fond of this idea), they could support rotating portals placed on them previously.

**Comment by TeamSpen210** [comment]
So a wall sticking out of the floor? Rotating portals would be really annoying to do, since it's a global property sneaky players could use it elsewhere in the map while it's spinning.

**Comment by Konclan** [comment]
I think what he means is panels placed on a piston that can be rotated. Kinda like in the main campaign https://theportalwiki.com/wiki/Portal_2_Chapter_7_Enrichment_Sphere_5

**Comment by Konclan** [comment]
But my guess it would be more compact so you can see the flip panel from both sides

**Comment by HugoBDesigner** [comment]
Not exactly. I meant more like one seen in Conversion by Ben77:
https://youtu.be/JNjQML9Lvv8?t=918
You can access it from both sides

**Comment by Konclan** [comment]
#3889
