### ISSUE TITLE
Unconnected glass panel coats in gel

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1704]
The gel panel, when not connected and not set to "Start deployed" will result in a glass "wall" (in a similar fashion to how regular angled panels result in an extruded surface). The issue is that they can still get coated in gel in their corners, albeit mildly, but still defeating its purpose. To fix that, we currently have to use them connected to hidden inputs.

**Comment by ZombiePwner1** [comment]
Can you show a screenshot?

**Comment by HugoBDesigner** [comment]
Sure thing
![20170312200012_1](https://cloud.githubusercontent.com/assets/6296061/23836916/93a74e00-075e-11e7-8ae8-af9e3d094b7f.jpg)

**Comment by ZombiePwner1** [comment]
Well that's pretty weird. Nice portal gun btw.

**Comment by HugoBDesigner** [comment]
It's because there's some brushwork along with the model.
And thanks!

**Comment by TeamSpen210** [comment]
The brushwork is to make walking on the corner bits sound normal, but the middle sound like glass. I could have just made them nodraw... I've also made it impossible to paint the backpanels surface underneath the model.
