### ISSUE TITLE
Portal bumpers on Half Walls?

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1705]
I'm not sure whether or not half walls have portal bumpers, but from what I've seen, looks like they don't. It'd be quite useful so shooting portals from slightly-off angles would be easier. If they already have them, disregard/delete this issue.

**Comment by LautaroL20** [comment]
You mean the `func_noportal_volume` ?

**Comment by HugoBDesigner** [comment]
I guess so, yeah

**Comment by TeamSpen210** [comment]
Portal bumpers are different to noportal_volume. They don't currently, just the bare surfaces. I'm not sure if bumpers would help, what you want is a placement helper.  Maybe I should add those if it's on the floor.

**Comment by HugoBDesigner** [comment]
I was thinking of a scenario like my "Hard Asbestos Bridge" map. I couldn't have a placement helper there because portal orientation was important. Also because the placement of the portal wasn't exactly aligned with the editor's blocks, but rather offset by 1/4th of a block.

**Comment by Luke18033** [comment]
This should now be possible with the placement helper item, since you can offset them to the sides and disable orientation locking.
