### ISSUE TITLE
Error with latest version?

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1707]
It's very likely that I did something wrong when updating Beemod:

```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "BEE2.pyw", line 130, in <module>
  File "F:\Git\BEE2.4\src\packageLoader.py", line 388, in load_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 940, in parse
TypeError: unhashable type: 'list'
```

**Comment by TeamSpen210** [comment]
Which version exactly are you using?

**Comment by TeamSpen210** [comment]
Could you copy the lines before in the log?

**Comment by HugoBDesigner** [comment]
`[I] gameMan: Ap-Tag dir: c:\program files (x86)\steam\steamapps\common\aperture tag/aperturetag/sound/music
[I] gameMan: PS-Mel dir: c:\program files (x86)\steam\steamapps\common\Portal Stories Mel/portal_stories/pak01_dir.vpk
[I] BEE2: Loading Packages...
[D] packageLoader: Reading package "C:\Bee\packages\apTag"
[D] packageLoader: Checking subdir "C:\Bee\packages\apTag" for packages...
[D] packageLoader: Reading package "C:\Bee\packages\apTag\tagItems"
[D] packageLoader: Reading package "C:\Bee\packages\apTag\tagMusic"
[D] packageLoader: Reading package "C:\Bee\packages\apTag\tagVO"
[D] packageLoader: Reading package "C:\Bee\packages\bee1"
[D] packageLoader: Checking subdir "C:\Bee\packages\bee1" for packages...
[D] packageLoader: Reading package "C:\Bee\packages\bee1\beemod"
[D] packageLoader: Reading package "C:\Bee\packages\bee1\pellets"
[D] packageLoader: Reading package "C:\Bee\packages\bee1\portal"
[D] packageLoader: Reading package "C:\Bee\packages\beemod.zip"
[D] packageLoader: Reading package "C:\Bee\packages\blocks"
[D] packageLoader: Reading package "C:\Bee\packages\blocks.zip"
[D] packageLoader: Reading package "C:\Bee\packages\bts_style.zip"
[D] packageLoader: Reading package "C:\Bee\packages\buttons.zip"
[D] packageLoader: Reading package "C:\Bee\packages\catwalk"
[D] packageLoader: Reading package "C:\Bee\packages\catwalk.zip"
[D] packageLoader: Reading package "C:\Bee\packages\checkpoint.zip"
[D] packageLoader: Reading package "C:\Bee\packages\clean_style.zip"
[D] packageLoader: Reading package "C:\Bee\packages\cold_light_strip"
[D] packageLoader: Reading package "C:\Bee\packages\conveyor"
[D] packageLoader: Reading package "C:\Bee\packages\conveyor.zip"
[D] packageLoader: Reading package "C:\Bee\packages\cube_color"
[D] packageLoader: Reading package "C:\Bee\packages\deathfizzler"
[D] packageLoader: Reading package "C:\Bee\packages\deathfizzler.zip"
[D] packageLoader: Reading package "C:\Bee\packages\dis_beams.zip"
[D] packageLoader: Reading package "C:\Bee\packages\ditch.zip"
[D] packageLoader: Reading package "C:\Bee\packages\elevator_videos.zip"
[D] packageLoader: Reading package "C:\Bee\packages\extra"
[D] packageLoader: Checking subdir "C:\Bee\packages\extra" for packages...
[D] packageLoader: Reading package "C:\Bee\packages\extra\elevator_videos"
[D] packageLoader: Reading package "C:\Bee\packages\extra\music"
[D] packageLoader: Reading package "C:\Bee\packages\extra\voice_line"
[D] packageLoader: Reading package "C:\Bee\packages\fr_fizzlers"
[D] packageLoader: Reading package "C:\Bee\packages\fr_fizzlers.zip"
[D] packageLoader: Reading package "C:\Bee\packages\futbol"
[D] packageLoader: Reading package "C:\Bee\packages\futbol.zip"
[D] packageLoader: Reading package "C:\Bee\packages\geometry.zip"
[D] packageLoader: Reading package "C:\Bee\packages\Grided_wall"
[D] packageLoader: Reading package "C:\Bee\packages\hazards.zip"
[D] packageLoader: Reading package "C:\Bee\packages\hmw"
[D] packageLoader: Reading package "C:\Bee\packages\hmw.zip"
[D] packageLoader: Reading package "C:\Bee\packages\large_faith.zip"
[D] packageLoader: Reading package "C:\Bee\packages\melMusic"
[D] packageLoader: Reading package "C:\Bee\packages\melMusic.zip"
[D] packageLoader: Reading package "C:\Bee\packages\modified_ped"
[D] packageLoader: Reading package "C:\Bee\packages\monitors"
[D] packageLoader: Reading package "C:\Bee\packages\monitors.zip"
[D] packageLoader: Reading package "C:\Bee\packages\music.zip"
[D] packageLoader: Reading package "C:\Bee\packages\oldAp.zip"
[D] packageLoader: Reading package "C:\Bee\packages\overgrown.zip"
[D] packageLoader: Reading package "C:\Bee\packages\p1_music"
[D] packageLoader: Reading package "C:\Bee\packages\p1_music.zip"
[D] packageLoader: Reading package "C:\Bee\packages\p1_style.zip"
[D] packageLoader: Reading package "C:\Bee\packages\paintFizzler"
[D] packageLoader: Reading package "C:\Bee\packages\paintFizzler.zip"
[D] packageLoader: Reading package "C:\Bee\packages\panels"
[D] packageLoader: Reading package "C:\Bee\packages\pellets.zip"
[D] packageLoader: Reading package "C:\Bee\packages\portal.zip"
[D] packageLoader: Reading package "C:\Bee\packages\ret_ped_button.zip"
[D] packageLoader: Reading package "C:\Bee\packages\rexaura"
[D] packageLoader: Checking subdir "C:\Bee\packages\rexaura" for packages...
[D] packageLoader: Reading package "C:\Bee\packages\rexaura\rex_items"
[D] packageLoader: Reading package "C:\Bee\packages\rexaura\rex_music"
[D] packageLoader: Reading package "C:\Bee\packages\rex_items.zip"
[D] packageLoader: Reading package "C:\Bee\packages\rex_music.zip"
[D] packageLoader: Reading package "C:\Bee\packages\rocketTurret"
[D] packageLoader: Reading package "C:\Bee\packages\rocketTurret.zip"
[D] packageLoader: Reading package "C:\Bee\packages\scaffold"
[D] packageLoader: Reading package "C:\Bee\packages\scaffold.zip"
[D] packageLoader: Reading package "C:\Bee\packages\sendificator"
[D] packageLoader: Reading package "C:\Bee\packages\sendificator.zip"
[D] packageLoader: Reading package "C:\Bee\packages\signage"
[D] packageLoader: Reading package "C:\Bee\packages\signage.zip"
[D] packageLoader: Reading package "C:\Bee\packages\styles"
[D] packageLoader: Checking subdir "C:\Bee\packages\styles" for packages...
[D] packageLoader: Reading package "C:\Bee\packages\styles\bts_style"
[D] packageLoader: Reading package "C:\Bee\packages\styles\oldAp"
[D] packageLoader: Reading package "C:\Bee\packages\styles\overgrown"
[D] packageLoader: Reading package "C:\Bee\packages\styles\p1_style"
[D] packageLoader: Reading package "C:\Bee\packages\tagItems.zip"
[D] packageLoader: Reading package "C:\Bee\packages\tagMusic.zip"
[D] packageLoader: Reading package "C:\Bee\packages\tagVO.zip"
[D] packageLoader: Reading package "C:\Bee\packages\test_elements.zip"
[D] packageLoader: Reading package "C:\Bee\packages\timers.zip"
[D] packageLoader: Reading package "C:\Bee\packages\tspen"
[D] packageLoader: Checking subdir "C:\Bee\packages\tspen" for packages...
[D] packageLoader: Reading package "C:\Bee\packages\tspen\checkpoint"
[D] packageLoader: Reading package "C:\Bee\packages\tspen\cube_cleaner"
[D] packageLoader: Reading package "C:\Bee\packages\tspen\ditch"
[D] packageLoader: Reading package "C:\Bee\packages\tspen\large_faith"
[D] packageLoader: Reading package "C:\Bee\packages\tspen\ret_ped_button"
[D] packageLoader: Reading package "C:\Bee\packages\tspen\timers"
[D] packageLoader: Reading package "C:\Bee\packages\tspen\ts_logic"
[D] packageLoader: Reading package "C:\Bee\packages\ts_logic.zip"
[D] packageLoader: Reading package "C:\Bee\packages\vactubes"
[D] packageLoader: Reading package "C:\Bee\packages\vactubes.zip"
[D] packageLoader: Reading package "C:\Bee\packages\valve"
[D] packageLoader: Checking subdir "C:\Bee\packages\valve" for packages...
[D] packageLoader: Reading package "C:\Bee\packages\valve\buttons"
[D] packageLoader: Reading package "C:\Bee\packages\valve\clean_style"
[D] packageLoader: Reading package "C:\Bee\packages\valve\dis_beams"
[D] packageLoader: Reading package "C:\Bee\packages\valve\geometry"
[D] packageLoader: Reading package "C:\Bee\packages\valve\hazards"
[D] packageLoader: Reading package "C:\Bee\packages\valve\test_elements"
[D] packageLoader: Reading package "C:\Bee\packages\voice_line.zip"
[D] packageLoader: Reading package "C:\Bee\packages\wom_plates"
[D] packageLoader: Reading package "C:\Bee\packages\wom_plates.zip"
[I] packageLoader: Reading objects from "BEE2_OVERGROWN"...
[I] packageLoader: Reading objects from "APERTURE_TAG_VOICE"...
[I] packageLoader: Reading objects from "TSPEN_DITCH"...
[I] packageLoader: Reading objects from "BEE2_OLD_AP"...
[I] packageLoader: Reading objects from "BEE2_EXTRA_PANELS"...
[I] packageLoader: Reading objects from "BEEMOD_1"...
[I] packageLoader: Reading objects from "BEE2_MONITORS"...
[I] packageLoader: Reading objects from "LP_DEATH_FIZZ"...
[I] packageLoader: Reading objects from "TAG_MUSIC"...
[I] packageLoader: Reading objects from "VALVE_TEST_ELEM"...
[I] packageLoader: Reading objects from "BEE2_BLOCKS"...
[I] packageLoader: Reading objects from "LAUTARO_GRIDED_WALL"...
[I] packageLoader: Reading objects from "TSPEN_LARGE_FAITH"...
[I] packageLoader: Reading objects from "HMW_MOD"...
[I] packageLoader: Reading objects from "BEE2_CONVEYOR"...
[I] packageLoader: Reading objects from "PACK_WOM_CONDUCTOR"...
[I] packageLoader: Reading objects from "TSPEN_TIMERS"...
[I] packageLoader: Reading objects from "BEE2_MUSIC"...
[I] packageLoader: Reading objects from "TSPEN_PAINT_CLEANER"...
[I] packageLoader: Reading objects from "LAUTARO_COLD_LIGHT_STRIP"...
[I] packageLoader: Reading objects from "BEE2_CLEAN_STYLE"...
[I] packageLoader: Reading objects from "BEE2_ELEV_VIDEO"...
[I] packageLoader: Reading objects from "LAUTARO_MODIFIED_PED_BTN"...
[I] packageLoader: Reading objects from "BEE2_CUBE_COLORISER"...
[I] packageLoader: Reading objects from "HMW_SENDIFICATOR"...
[I] packageLoader: Reading objects from "VALVE_GEOMETRY"...
[I] packageLoader: Reading objects from "PACK_BEE2_FUTBOL"...
[I] packageLoader: Reading objects from "APERTURE_TAG_ITEMS"...
[I] packageLoader: Reading objects from "BEE2_VOICE_LINE"...
[I] packageLoader: Reading objects from "BEE2_SIGNAGE"...
[I] packageLoader: Reading objects from "PS_MEL_MUSIC"...
[I] packageLoader: Reading objects from "TSPEN_LOGIC"...
[I] packageLoader: Reading objects from "REX_ITEMS"...
[I] packageLoader: Reading objects from "BEE2_BTS"...
[I] packageLoader: Reading objects from "REX_MUSIC"...
[I] packageLoader: Reading objects from "BEE2_PAINT_FIZZLER"...
[I] packageLoader: Reading objects from "VALVE_LASERS"...
[I] packageLoader: Reading objects from "TSPEN_CHECKPOINT"...
[I] packageLoader: Reading objects from "FR_FIZZ"...
[I] packageLoader: Reading objects from "VALVE_HAZARDS"...
[I] packageLoader: Reading objects from "VALVE_BUTTONS"...
[I] packageLoader: Reading objects from "BEE2_PORTALS"...
[I] packageLoader: Reading objects from "BEE2_ROCKET_TURRET"...
[I] packageLoader: Reading objects from "BEE2_CATWALK"...
[I] packageLoader: Reading objects from "BEE2_PORTAL_1"...
[I] packageLoader: Reading objects from "BEE2_VACTUBES"...
[I] packageLoader: Reading objects from "BEE_PELLETS"...
[I] packageLoader: Reading objects from "BEE2_UNST_SCAFFOLD"...
[I] packageLoader: Reading objects from "BEE2_P1_MUSIC"...
[I] packageLoader: Reading objects from "TSPEN_RET_BUTTON"...
[D] packageLoader: Loading Style "BEE2_1960s"!
[D] packageLoader: Loading Style "BEE2_OVERGROWN"!
[D] packageLoader: Loading Style "BEE2_CLEAN"!
[D] packageLoader: Loading Style "BEE2_1980s"!
[D] packageLoader: Loading Style "BEE2_PORTAL_1"!
[D] packageLoader: Loading Style "BEE2_CLEAN_ORIGINAL"!
[D] packageLoader: Loading Style "BEE2_BTS"!
[D] packageLoader: Loading Style "BEE2_1970s"!
[D] packageLoader: Loading Style "BEE2_1950s"!
[D] packageLoader: Loading Skybox "VALVE_2D_BTS"!
[D] packageLoader: Loading Skybox "BEE2_PORTAL_1"!
[D] packageLoader: Loading Skybox "BEE2_SPHERE_INTERIOR"!
[D] packageLoader: Loading Skybox "BEE2_SPHERE_EXTERIOR"!
[D] packageLoader: Loading Skybox "VALVE_3D_FACTORY"!
[D] packageLoader: Loading Skybox "SKY_2D_OVERGROWN"!
[D] packageLoader: Loading Skybox "BEE2_CLEAN"!
[D] packageLoader: Loading Elevator "VALVE_BOTS_WAVE"!
[D] packageLoader: Loading Elevator "VALVE_MENU_ACT_2"!
[D] packageLoader: Loading Elevator "VALVE_LOAD_PBODY"!
[D] packageLoader: Loading Elevator "VALVE_APERTURE_APPEAR"!
[D] packageLoader: Loading Elevator "VALVE_MENU_ACT_5"!
[D] packageLoader: Loading Elevator "VALVE_INSERT_DISC"!
[D] packageLoader: Loading Elevator "VALVE_BLUESCREEN"!
[D] packageLoader: Loading Elevator "VALVE_POWER_CONNECTING"!
[D] packageLoader: Loading Elevator "VALVE_BOTS_LOAD"!
[D] packageLoader: Loading Elevator "VALVE_TURRET_CASE_OPTIONS"!
[D] packageLoader: Loading Elevator "VALVE_BLUEPRINTS"!
[D] packageLoader: Loading Elevator "VALVE_REMAIN_CALM"!
[D] packageLoader: Loading Elevator "VALVE_ATLAS_LOAD"!
[D] packageLoader: Loading Elevator "VALVE_SECURITY_DOWNLOADING"!
[D] packageLoader: Loading Elevator "VALVE_RADAR_CALIBRATING"!
[D] packageLoader: Loading Elevator "VALVE_LIGHTBRIDGE"!
[D] packageLoader: Loading Elevator "VALVE_EVAC_TRAINING"!
[D] packageLoader: Loading Elevator "VALVE_MENU_ACT_3"!
[D] packageLoader: Loading Elevator "VALVE_SPACE"!
[D] packageLoader: Loading Elevator "VALVE_LASER_PORTAL"!
[D] packageLoader: Loading Elevator "VALVE_FAITH_PLATE"!
[D] packageLoader: Loading Elevator "VALVE_ANIMAL_KING"!
[D] packageLoader: Loading Elevator "VALVE_SECURITY_SEARCHING"!
[D] packageLoader: Loading Elevator "VALVE_LASER_DANGER"!
[D] packageLoader: Loading Elevator "VALVE_POWER_CONNECTED"!
[D] packageLoader: Loading Elevator "VALVE_MENU_ACT_4"!
[D] packageLoader: Loading Elevator "VALVE_MENU_ACT_1"!
[D] packageLoader: Loading Elevator "VALVE_TURRET_DROPIN"!
[D] packageLoader: Loading Elevator "VALVE_RADAR_UNUSED"!
[D] packageLoader: Loading Elevator "VALVE_FIZZLER"!
[D] packageLoader: Loading Elevator "VALVE_CREDITS_BG"!
[D] packageLoader: Loading Elevator "VALVE_TURRET_EXPLODED"!
[D] packageLoader: Loading Elevator "VALVE_RADAR_FOUND"!
[D] packageLoader: Loading Elevator "VALVE_BLACK"!
[D] packageLoader: Loading Elevator "VALVE_SECURITY_UNUSED"!
[D] packageLoader: Loading Elevator "VALVE_APERTURE_LOGO"!
[D] packageLoader: Loading ItemConfig "ITEM_CUBE"!
[D] packageLoader: Loading Music "TAG_CERTIFIABLY_INSANE"!
[D] packageLoader: Loading Music "MEL_JUNKYARD_OUTSIDE"!
[D] packageLoader: Loading Music "VALVE_ROBO_ROOM_6"!
[D] packageLoader: Loading Music "MEL_TESTING_WITH_NATURE"!
[D] packageLoader: Loading Music "MEL_WAKING_SCIENCE"!
[D] packageLoader: Loading Music "MEL_TESTING_BEGINS"!
[D] packageLoader: Loading Music "VALVE_FRANKENTURRETS"!
[D] packageLoader: Loading Music "REX_SEVEN"!
[D] packageLoader: Loading Music "MEL_JUNKYARD_OFFICES"!
[D] packageLoader: Loading Music "MEL_TRANSITIONAL_PERIOD"!
[D] packageLoader: Loading Music "TAG_MOVING_PARTS"!
[D] packageLoader: Loading Music "VALVE_ACCENT_BEYOND"!
[D] packageLoader: Loading Music "VALVE_50_PERC"!
[D] packageLoader: Loading Music "TAG_LIFE_TEST_CONDITIONS"!
[D] packageLoader: Loading Music "VALVE_DAUGHTER_WORK"!
[D] packageLoader: Loading Music "TAG_GET_TO_IT"!
[D] packageLoader: Loading Music "TAG_ART_THERAPY"!
[D] packageLoader: Loading Music "VALVE_NINES_2"!
[D] packageLoader: Loading Music "VALVE_P1_NO_CAKE_FOR_YOU"!
[D] packageLoader: Loading Music "VALVE_FUTURE_STARTER"!
[D] packageLoader: Loading Music "TAG_TAKE_IT_SLOW"!
[D] packageLoader: Loading Music "VALVE_MUSIC_SPHERES_1"!
[D] packageLoader: Loading Music "VALVE_VIT_ORDER_1"!
[D] packageLoader: Loading Music "VALVE_REDEMPTION"!
[D] packageLoader: Loading Music "VALVE_TBEAM_INTRO"!
[D] packageLoader: Loading Music "VALVE_P1_YOU_CANT_ESCAPE"!
[D] packageLoader: Loading Music "TAG_BOOTS"!
[D] packageLoader: Loading Music "TAG_TRIALS"!
[D] packageLoader: Loading Music "VALVE_RATTMAN"!
[D] packageLoader: Loading Music "MEL_OUT_OF_ORDER_1"!
[D] packageLoader: Loading Music "VALVE_ROBO_ROOM_4"!
[D] packageLoader: Loading Music "MEL_OUT_OF_ORDER_2"!
[D] packageLoader: Loading Music "VALVE_TECHNICAL_DIFFICULTIES"!
[D] packageLoader: Loading Music "TAG_LIFE_SUPPORT"!
[D] packageLoader: Loading Music "VALVE_LASER_DANCE"!
[D] packageLoader: Loading Music "MEL_WELCOME_TO_THE_FUTURE"!
[D] packageLoader: Loading Music "REX_TWO"!
[D] packageLoader: Loading Music "VALVE_VIT_ORDER_2"!
[D] packageLoader: Loading Music "VALVE_CAUSE_SCIENCE"!
[D] packageLoader: Loading Music "TAG_SURE"!
[D] packageLoader: Loading Music "VALVE_P1_SELF_ESTEEM_FUND"!
[D] packageLoader: Loading Music "VALVE_IM_DIFFERENT"!
[D] packageLoader: Loading Music "VALVE_HAUNTED_PANELS"!
[D] packageLoader: Loading Music "REX_FIVE"!
[D] packageLoader: Loading Music "MEL_SYSTEM_CORRUPTION"!
[D] packageLoader: Loading Music "TAG_SLOW_2"!
[D] packageLoader: Loading Music "VALVE_COMEDY=TRAGEDY"!
[D] packageLoader: Loading Music "VALVE_SPACE_PHASE"!
[D] packageLoader: Loading Music "TAG_LIFE_TOO_SHORT"!
[D] packageLoader: Loading Music "VALVE_ROBO_ROOM_5"!
[D] packageLoader: Loading Music "MEL_ACCELERATION"!
[D] packageLoader: Loading Music "TAG_PULL_YOURSELF_TOGETHER"!
[D] packageLoader: Loading Music "VALVE_ROBO_ROOM_1"!
[D] packageLoader: Loading Music "MEL_FIRESTORM"!
[D] packageLoader: Loading Music "TAG_COMPLETE_THE_CIRCUIT"!
[D] packageLoader: Loading Music "VALVE_REUNION_PART_2"!
[D] packageLoader: Loading Music "VALVE_WHAT_HAS_HE_DONE"!
[D] packageLoader: Loading Music "TAG_STERILISED_ENVIRONS"!
[D] packageLoader: Loading Music "VALVE_P1_PARTY_ESCORT"!
[D] packageLoader: Loading Music "MEL_TROUBLED_WATER"!
[D] packageLoader: Loading Music "VALVE_LOVE_CONSTRUCT"!
[D] packageLoader: Loading Music "REX_FOUR"!
[D] packageLoader: Loading Music "VALVE_ROBO_ROOM_2"!
[D] packageLoader: Loading Music "VALVE_P1_STOP_DOING"!
[D] packageLoader: Loading Music "TAG_CONFRONTATION"!
[D] packageLoader: Loading Music "VALVE_P1_ANDROID_HELL"!
[D] packageLoader: Loading Music "VALVE_P1_BLOOD"!
[D] packageLoader: Loading Music "VALVE_MUSIC_SPHERES_2"!
[D] packageLoader: Loading Music "VALVE_SAW_DEER"!
[D] packageLoader: Loading Music "VALVE_P1_NOT_A_GOOD_PERSON"!
[D] packageLoader: Loading Music "MEL_ADJACENCY"!
[D] packageLoader: Loading Music "VALVE_ROBO_ROOM_3"!
[D] packageLoader: Loading Music "TAG_CONCERNED"!
[D] packageLoader: Loading Music "TAG_RIDE_IT_OUT"!
[D] packageLoader: Loading Music "VALVE_P1_DEGREES_KELVIN"!
[D] packageLoader: Loading Music "MEL_SKOTOTROPHISM"!
[D] packageLoader: Loading Music "MEL_INTERFACING"!
[D] packageLoader: Loading Music "TAG_GLITCH"!
[D] packageLoader: Loading Music "MEL_OBSCURATION"!
[D] packageLoader: Loading Music "TAG_BUILD_UP_TO_NOWHERE"!
[D] packageLoader: Loading Music "REX_ONE"!
[D] packageLoader: Loading Music "TAG_SYSTEM_LEAK"!
[D] packageLoader: Loading Music "VALVE_P1_PROCEDURAL_JIGGLE_BONE"!
[D] packageLoader: Loading Music "VALVE_REUNION_PART_1"!
[D] packageLoader: Loading Music "MEL_LONG_WAY_DOWN"!
[D] packageLoader: Loading Music "VALVE_CLASSICAL"!
[D] packageLoader: Loading Music "TAG_DEAD_SUBJECT"!
[D] packageLoader: Loading Music "TAG_RECONSTRUCTING_AMBIENCE"!
[D] packageLoader: Loading Music "VALVE_ROBO_GHOST"!
[D] packageLoader: Loading Music "MEL_HALTED_PRODUCTION"!
[D] packageLoader: Loading Music "REX_THREE"!
[D] packageLoader: Loading Music "REX_SIX"!
[D] packageLoader: Loading Music "VALVE_P1_SUBJECT_NAME"!
[D] packageLoader: Loading Music "MEL_LIVE_FIRE_EXERCISE"!
[D] packageLoader: Loading Music "TAG_RESONANCE"!
[D] packageLoader: Loading Music "MEL_NATURAL_LIGHT"!
[D] packageLoader: Loading Music "VALVE_NINES_1"!
[D] packageLoader: Loading Music "TAG_TIME_ESSENCE"!
[D] packageLoader: Loading Music "VALVE_THERE_SHE_IS"!
[D] packageLoader: Loading Music "TAG_ARRIVAL"!
[D] packageLoader: Loading Music "VALVE_CONTROL_GROUP"!
[D] packageLoader: Loading Music "MEL_APERTURE_CENTRAL"!
[D] packageLoader: Loading Music "VALVE_PETI"!
[D] packageLoader: Loading Music "TAG_PRECIOUS_TEST"!
[D] packageLoader: Loading Music "VALVE_ROBO_ROOM_PTI"!
[D] packageLoader: Loading Music "MEL_SYSTEM_CORRUPTION_ALT"!
[D] packageLoader: Loading Item "ITEM_TSPEN_FLIP_FLOP"!
[D] packageLoader: Loading Item "ITEM_LASER_RELAY_CENTER"!
[D] packageLoader: Loading Item "ITEM_BEE2_SCAFFOLD_PIST"!
[D] packageLoader: Loading Item "ITEM_BEE2_CONVEYOR"!
[D] packageLoader: Loading Item "ITEM_OBSERVATION_ROOM"!
[D] packageLoader: Loading Item "ITEM_REX_PELLET_DESTROYER"!
[D] packageLoader: Loading Item "ITEM_HIGH_ENERGY_PELLET_EMITTER"!
[D] packageLoader: Loading Item "ITEM_PANEL_CLEAR"!
[D] packageLoader: Loading Item "ITEM_SAVEPOINT"!
[D] packageLoader: Loading Item "ITEM_BEE2_CUTOUT_TILE"!
[D] packageLoader: Loading Item "ITEM_LAUTARO_PROTRUDING_PEDESTAL"!
`

**Comment by HugoBDesigner** [comment]
I tried adding files from the dev version into the latest release. Unsurprisingly, it didn't work.
