### ISSUE TITLE
Mirror

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1708]
Honestly, this is probably impossible, but I have to give it a try.
The mirror is an item that you could look into and be able to see everything, reflected.
You are also able to shoot into the mirror, and if you shot at a portable surface, a portal would be created.
The item would have the 4-way rotation system, in which the mirror would be in the center of the block.

**Comment by Byzarru** [comment]
This will be implemented in the Blue Portals pack.

**Comment by hop193** [comment]
Wait, WHAT? It's possible? Wow! Thanks!

**Comment by TeamSpen210** [comment]
Portals like that I don't think is possible, or looking into it. The Blue Portals one just reflects 'light'.

**Comment by hop193** [comment]
Oh, so is light going to be added too?

**Comment by Byzarru** [comment]
Fingers crossed, but it's not actual lighting. Instead, it acts more like a laser.

**Comment by TeamSpen210** [comment]
More like a laser, it couldn't light things.

**Comment by TheDarkBomber** [comment]
The BP Mirror will only reflect light. Hopefully the Felix Griffin Mirror will be added as well, as it reflects everything.

**Comment by hop193** [comment]
> The BP Mirror will only reflect light. Hopefully the Felix Griffin Mirror will be added as well, as it reflects everything.
Ah, I see. Thanks.
