### ISSUE TITLE
The "Stripes position" from the Square Lights doesn´t fit well on ceillings, add the "Handle_4_Directions"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1709]
The screenshot from adobe explains exactly what i mean:

![20170313091052_1](https://cloud.githubusercontent.com/assets/12244376/23854132/bf3d9932-07ce-11e7-829d-8f4816dfacd6.jpg)

**Comment by LautaroL20** [comment]
This would only be for Clean Style.

**Comment by Luke18033** [comment]
Did you add it to all styles, or just Clean? Items should keep the same properties across all styles.

**Comment by LautaroL20** [comment]
Clean only atm. But i can make it for all Styles if needed, but i think in this case is not really needed. The Clean stripes from Walls is a special case.

**Comment by TeamSpen210** [comment]
In this particular case it's fine that it changes to `HANDLE_NONE` - the item would remember its orientation fine, so there's no loss.
