### ISSUE TITLE
Squarebeams from the SP Exit Corridor N°3 are being displayed "Totally Black" even on "Published Maps"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1710]
Doesn´t matter if you are using "Fast" or "Full" lighting, or even when you publish the map. The mysterious black shadow just keeps appearing there....

![20170313114304_1](https://cloud.githubusercontent.com/assets/12244376/23860365/7d7bcfb6-07e5-11e7-949d-0eb10d4cd777.jpg)

**Comment by ZombiePwner1** [comment]
@LautaroL20 Someone is not disabling shadows on them that's why you wheely.

**Comment by TeamSpen210** [comment]
Or the collision is producing shadows.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - The squarebeam model does have already shadows dissabled you wheely, issue here is related to another thing and ive figure the cause for this, once i release my new chamber to the workshop, ill gonna get back to do some bugfixes for beemod.
