### ISSUE TITLE
Cubes phase through grating

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1714]
![20170313185445_1](https://cloud.githubusercontent.com/assets/6296061/23877120/8ad191a2-081f-11e7-8765-565f438bc01c.jpg)

**Comment by LautaroL20** [comment]
Uhmmm, this is weird. I remember having experienced this bug in some PeTi map so this is most likely a Valve bug and can´t be fixed.

**Comment by ZombiePwner1** [comment]
@LautaroL20 It should be possible to fix the grating might be missing a special clip for the cubes or something.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - I don´t think that the Grating would be missing any clips... This is a source engine bug that can´t be fixed by us.

**Comment by HugoBDesigner** [comment]
But it was working just fine before

**Comment by LautaroL20** [comment]
@HugoBDesigner - Yeah, its to do with the Source Engine where it works well most of the time but a few ones it works weird . Once i were playing with ZombiePwner1 a Co-op map then the Cube Physics start to working well for a few seconds.

**Comment by LautaroL20** [comment]
Unfortunately, we can´t fix the bug mostly because its to do with the mentioned problem were we haven´t control.
