### ISSUE TITLE
Broken breakable glass splits into square segments

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1715]
It may be expected/standard behavior, but it looks like a pixelated wall that is hard to see because of transparency.
![20170313185734_1](https://cloud.githubusercontent.com/assets/6296061/23877244/251124a8-0820-11e7-92db-bc175c8043fe.jpg)

**Comment by Luke18033** [comment]
Why did you close it?

**Comment by TeamSpen210** [comment]
Because it should be fixed.
