### ISSUE TITLE
New Item: Flat 'Wall' Item

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1716]
Same thing as this:
![capture](https://cloud.githubusercontent.com/assets/25728252/23878410/a9ec0c72-081d-11e7-988a-bd654e5e0c8a.PNG)
But when placed (on a floor), instead of it being 'pushed' out of the floor, it sits on its side, like a mini wall. This is very useful when using it in a scenario with doors to prevent the walls looking 'bulky'.

**Comment by HugoBDesigner** [comment]
Wouldn't that be the same as the 1/4th wall?
![image](https://cloud.githubusercontent.com/assets/6296061/23881290/6f334d78-0838-11e7-8c21-9112f2411d8e.png)

**Comment by Luke18033** [comment]
Indeed.

**Comment by TeamSpen210** [comment]
It is in that case the same, but people might want a center-placed one as well.

**Comment by HugoBDesigner** [comment]
I assume for "glass"-like items you can't have the light bridge positioning gizmo?
Actually, I think you already explained to me that it wasn't possible...

**Comment by libbybapa** [comment]
I proposed adding the center 4 positions to the 1/4 wall item here before it got closed, labelled invalid, reopened, and then spammed with off-topic posts.  

https://github.com/BEEmod/BEE2-items/issues/1146

**Comment by Endermage77** [comment]
I thought this issue was suggesting flat walls placed on face instead of on edge.

**Comment by hop193** [comment]
> It is, in that case, the same, but people might want a center-placed one as well.

> I would personally prefer having the 8 positions that adding...

Yes, the light strip movement is wanted.

**Comment by Byzarru** [comment]
Is the Intangible Scaffold working yet? Although I'd want an 8-positioned wall item like this, the ITS would greatly help in positioning angled tiles and panels and making arrangements with walls and glass. (And the ITS would also be able to do this, but it'd be a bit cumbersome to work with so a positionable wall item is more desirable).

**Comment by HugoBDesigner** [comment]
> Yes, the light strip movement is wanted.
I see what he means, and it's not necessary. You have the regular rotation (4 directions) plus a "Start Enabled" option to offset the wall by 1/4th. This offsets it inwards, which means 4 more directions along with the rotation. Thus 8 possible positions, doing what the light strip gizmo would do but without the light strip gizmo.

**Comment by libbybapa** [comment]
It's nice to be understood, lol.  :)  Apparently the handle_8_positions will not work with barriers.

**Comment by hop193** [comment]
Yay! Thanks!

**Comment by libbybapa** [comment]
I believe that Teamspen added 'start enabled' to the 1/4 wall object in order to give it the center 4 positions as was mentioned in the thread I linked.  I think that the 1/4 wall will be more useful than a 1/4x1x1 block standing on edge, as it will allow stretching.  I agree wholeheartedly, YAY!  :)

**Comment by TeamSpen210** [comment]
Indeed.
