### ISSUE TITLE
Portal 1 fizzlers, if not connected, don't show particles

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1721]
It still behaves as intended, but unless linked to something, the particles won't show up.
![20170313205207_1](https://cloud.githubusercontent.com/assets/6296061/23882695/10a04f28-0841-11e7-9ba2-9cc4d4b29dc9.jpg)

**Comment by ZombiePwner1** [comment]
:( Why must they be bugged? i like the portal 1 fizzlers design.

**Comment by hop193** [comment]
That sucks, but you can put a 'Trigger Once' at the start of the level to enable it which _should_ fix it.

**Comment by Endermage77** [comment]
Or a trigger once anywhere that starts enabled,

**Comment by Luke18033** [comment]
@Endermage77 - Start Enabled doesn't actually make the output start enabled, it makes it so both co-op players need to trigger it. What would be better is to use a NOT Gate, that way the output is on even before entering the chamber.

**Comment by HugoBDesigner** [comment]
I believe this has also been fixed.
