### ISSUE TITLE
Portal 1 stairs seem to be weirdly lit

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1722]
Appears to be self-lighting
![20170313205239_1](https://cloud.githubusercontent.com/assets/6296061/23882921/744e3f84-0842-11e7-9520-ebbcb6e23e80.jpg)

**Comment by TeamSpen210** [comment]
I'm forced to use static reflections here, so you actually get the shine effects on the pistons. Without them, they're basically pitch black. About 90% of the texture is reflection.

**Comment by HugoBDesigner** [comment]
Alright, so I guess we can dismiss this one

**Comment by ZombiePwner1** [comment]
@TeamSpen210 This wasn't how they properly looked in P1 but i don't think you can change that.

**Comment by TeamSpen210** [comment]
To do it properly, we need to build cubemaps for the lifts. That can't be done unfortunately - it involves taking screenshots, restarting the map, and some other ugliness. It might even crash the game doing it in PeTI. Maybe I could swap in some different ones depending, but that would really need something like logic to determine the 'average colour' in an area.
