### ISSUE TITLE
Pellet launchers inconsistent with timed buttons

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1723]
When linked to a timed pedestal button, the HEP launcher will sometimes fail to launch or launch further ahead on the timing.
![image](https://cloud.githubusercontent.com/assets/6296061/23882971/cc54d602-0842-11e7-91b0-aeeb893c5376.png)

**Comment by SW50000** [comment]
I tried this without the Development Version
The same thing happened

**Comment by TeamSpen210** [comment]
I should switch those to 'locking' buttons, so it is held down until a new pellet is launched.

**Comment by Luke18033** [comment]
Except with infinite pellets.

**Comment by TeamSpen210** [comment]
Those are more like a seperate item if anything. For those pressing the button will spawn or respawn the pellet immediately.
