### ISSUE TITLE
Improved Pellet Catcher trigger

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1724]
Increase the trigger area for pellet catchers so they're not so tricky to get when using something inconsistent to redirect the pellets, such as a cube. Also, at times, the catcher seems to arbitrarily allow for pellets to be caught at the outer edges but not on the inner edges:
![image](https://cloud.githubusercontent.com/assets/6296061/23883158/02ea455c-0844-11e7-8160-ef3017aef4a2.png)
![image](https://cloud.githubusercontent.com/assets/6296061/23883184/255f646e-0844-11e7-86b1-53277b703ade.png)

**Comment by ZombiePwner1** [comment]
@HugoBDesigner I don't think it's possible to change the radius of the catcher's pellet triggers.

**Comment by TeamSpen210** [comment]
It's just a cylindrical trigger. Currently it matches the shape of the inside of the white part of the model (do `showtriggers_toggle ` to see). Maybe it's hitting the side of the hole in the ceiling, or something. I might make the trigger a bit longer.

**Comment by TeamSpen210** [comment]
It should only really work though when hitting the center, not the sides like that.

**Comment by HugoBDesigner** [comment]
In that case, I guess #1725 would again be helpful.
But it appears that sometimes the pellet hits the catcher model, but at other times it does not.

**Comment by HugoBDesigner** [comment]
I checked the trigger, it's completely inside the model, but I assume the model has collisions.
Didn't hit:
![20170314132721_1](https://cloud.githubusercontent.com/assets/6296061/23911232/ec8befdc-08ba-11e7-8a75-f6ff605efbc1.jpg)
Did hit:
![20170314132840_1](https://cloud.githubusercontent.com/assets/6296061/23911239/f1bad1f8-08ba-11e7-9f47-f1fef9b77545.jpg)
Both seen from directly below it. The glow shows where the pellet hit exactly.

**Comment by HugoBDesigner** [comment]
I believe this has been fixed already?
