### ISSUE TITLE
White eyes on Portal 1 dead turrets

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1728]
![20170314002749_1](https://cloud.githubusercontent.com/assets/6296061/23884845/156fcf30-084e-11e7-8edf-f92f521cb157.jpg)

**Comment by Luke18033** [comment]
Uh oh, Herobrine is back...

**Comment by TeamSpen210** [comment]
So I must have forgotten the material for them so they can turn their eyes off. You may have noticed these are P1 turrets.

**Comment by Endermage77** [comment]
That actually looks kindof cool, if a bit weird if unexpected.
Perhaps this could be a stylevar?

**Comment by ZombiePwner1** [comment]
@Endermage77 It wouldn't be a stylevar as white eyes just look weird.
