### ISSUE TITLE
Additional wall tiles (half walls)

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1730]
Much like the half wall item, but instead containing some of the following variants: 1/4th, 1/8th and 3/8th (stripes),  1/4th (corner), 2/4th (opposing corners), 1/4th (side).
![image](https://cloud.githubusercontent.com/assets/6296061/23900520/690dcf94-0898-11e7-9180-12e38b6fa2de.png)
![image](https://cloud.githubusercontent.com/assets/6296061/23900341/88e0a5f4-0897-11e7-9af6-1166a2dc5d48.png)

**Comment by Konclan** [comment]
There is actually a problem with a tile like the one with in the middle of second row. A tile like pattern like that on the floor will allow players to place portals diagonally even with the black tiles on either side.

**Comment by HugoBDesigner** [comment]
Doesn't that already happen with normal blocks in a checkered pattern?

**Comment by Konclan** [comment]
Yes

**Comment by libbybapa** [comment]
![tile](https://cloud.githubusercontent.com/assets/19520567/23912354/94e26c8e-089c-11e7-97aa-4740e38d68f9.jpg)

**Comment by HugoBDesigner** [comment]
The second one would need a mirrored version as well, since you can only rotate the tiles.

**Comment by libbybapa** [comment]
Good point.  I would add one more also:

![tile2](https://cloud.githubusercontent.com/assets/19520567/23912805/1fc9cac6-089e-11e7-8e08-7dc530695f11.jpg)

**Comment by HugoBDesigner** [comment]
If these were added, it's likely that the triangle one would be discarded, since the most optimal gizmo/UI for these would be the buttons one, which only allows for 3 options.

**Comment by libbybapa** [comment]
They're all triangles.  :-P

**Comment by libbybapa** [comment]
I also wonder about using cube type (5 items) or timer (30?) like the signage items.

**Comment by HugoBDesigner** [comment]
Actually, you're right, cube type would do the trick. Also, I meant the bottom-right tile, with two white triangles (when I said triangle I was referring to the black part of it)

**Comment by libbybapa** [comment]
I knew what you meant.  I was just joking.

**Comment by TeamSpen210** [comment]
I'd prefer not adding the 1/8th tiles, those aren't used anywhere in either game.

**Comment by Luke18033** [comment]
This is basically now implemented with the quarter tile
