### ISSUE TITLE
Portal 1 cubes are extremely buggy

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1731]
They behave extremely weirdly around portals. Sometimes they fling out of them, sometimes they freeze, sometimes they flicker...
![20170314112551_1](https://cloud.githubusercontent.com/assets/6296061/23906927/46b54f9c-08ae-11e7-8f79-44531869b87c.jpg)
![20170314112750_1](https://cloud.githubusercontent.com/assets/6296061/23906936/4e340ce0-08ae-11e7-925f-ddde7f35d698.jpg)

**Comment by Luke18033** [comment]
I don't have this issue...

**Comment by ZombiePwner1** [comment]
@HugoBDesigner I've seen alot more weird things with these cubes. https://github.com/BEEmod/BEE2-items/issues/1376

**Comment by Luke18033** [comment]
Does this still happen?
