### ISSUE TITLE
Portal 1 light holes flicker depending on the view angle

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1732]
![image](https://cloud.githubusercontent.com/assets/6296061/23907244/46a08156-08af-11e7-9008-783c6c2e23ab.png)

**Comment by Luke18033** [comment]
Only use Development Version for issues that apply only to that version.

**Comment by HugoBDesigner** [comment]
Oh, sorry about that.

**Comment by ZombiePwner1** [comment]
@Luke18033 How's ur glass panels? Can't chat on steam due to some wheely maintenance.

**Comment by Luke18033** [comment]
I'm making P1 versions right now, and redesigning the triggers to prevent them from destroying or pushing cubes/players when they shouldn't.

**Comment by ZombiePwner1** [comment]
@Luke18033 Ahh nice can't wait to test them when prl 25 comes out.

**Comment by Luke18033** [comment]
@ZombiePwner1 - Why don't you get the dev version and try it out now?

**Comment by LautaroL20** [comment]
@Luke18033 - He tried it...but for some reason ends up fiddling everything he said.

**Comment by hop193** [comment]
Wait, is this a dev version only item, or is it from the light strip?

**Comment by TeamSpen210** [comment]
Light strip.

**Comment by Luke18033** [comment]
Now fixed.
