### ISSUE TITLE
P1 Pellet Catcher embed space becomes nodraw when viewed from a distance

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1733]
Seen from a distance:
![20170314133112_1](https://cloud.githubusercontent.com/assets/6296061/23911316/31e8daae-08bb-11e7-9136-394b14a7ccc1.jpg)
Closer:
![20170314133114_1](https://cloud.githubusercontent.com/assets/6296061/23911324/3bc02c6c-08bb-11e7-8259-7112d69cdb69.jpg)

**Comment by ZombiePwner1** [comment]
@HugoBDesigner There is a leak in your map somewhere that's causing nodraw behind the catcher.

**Comment by HugoBDesigner** [comment]
How would I find such a leak? Pointfile doesn't seem to work on this particular case...

**Comment by ZombiePwner1** [comment]
It's either a leak or a bug with the skybox itself.

**Comment by Luke18033** [comment]
That's not a skybox, it's the catcher's embed space.

**Comment by HugoBDesigner** [comment]
There's an exposed nodraw surface there to deflect the pellets.

**Comment by hop193** [comment]
Wait, how do you get this? Is this part of the dev version, or is it another item?

**Comment by HugoBDesigner** [comment]
It's part of the dev version

**Comment by TeamSpen210** [comment]
It's an update to the design, it happens on walls only.

**Comment by hop193** [comment]
> It's part of the dev version

> It's an update to the design, it happens on walls only.

Oh, OK. Thanks!

**Comment by HugoBDesigner** [comment]
Also been fixed, I believe
