### ISSUE TITLE
Pellet hitting the corner of a cube produces two pellets

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1734]
If the pellet hits right in the corner of a cube, it splits into two, flying in opposite directions.
![20170314152529_1](https://cloud.githubusercontent.com/assets/6296061/23916318/80b5289a-08ca-11e7-884b-daf572462f95.jpg)

**Comment by Konclan** [comment]
Oh I see what's happening here.. the pellet hits the cube and is supposed to disappear as another is spawned going in the reflected direction... That seems a little too jerry rigged for my taste

**Comment by TeamSpen210** [comment]
Okay, what? I really don't think it's possible to fix that. Perhaps there was actually two pellets overlapping originally, which reflected differently.
