### ISSUE TITLE
Splash Noise with Portals In Partial Blocks by Goo

### ISSUE THREAD

**Issue by libbybapa** [BEEmod/BEE2-items#1735]
This may be unavoidable...  

A splash sound is triggered when you go through a portal placed in portalable partial blocks in goo or the 1/4 wall flat as a floor over goo.  See the following video:  https://youtu.be/8AHEiStrWdA

Is there a way to eliminate the splash sound in those conditions?

**Comment by TeamSpen210** [comment]
It's a Valve bug, I think you briefly touch the water through the portal before teleporting.
