### ISSUE TITLE
Add "Gridded Surface" as a default feature on Carl Kenner´s Partial Blocks

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1737]
These would look much better on walls having this feature.

**Comment by TeamSpen210** [comment]
Note that you can also set these for other orientations, other than just the floor. See the flat partial blocks for an example.

**Comment by LautaroL20** [comment]
@TeamSpen210 - That was a nice ehnancement! Also i saw you fixed the template brush that wasn´t being rotated properly. However, gridded surfaces still not working for the 1/4 and 2/4 varieties:
![IMAGE](https://cloud.githubusercontent.com/assets/12244376/23941713/98fce658-0948-11e7-8fad-b062669d0567.jpg)

**Comment by TeamSpen210** [comment]
It's working fine for the 1/2 block, it makes the wall 2x2. That's what I'd want to do on the 1/4 block (both 1/2 and 1/4), but I don't have the infrastructure finished to enable that.

**Comment by LautaroL20** [comment]
There is a small problem if i implement the Flat Blocks´s checkered feature on Kenner´s block though. You can´t predict the exact placement when using the `handle_8_positions`, If you place a 4x1x1 block on floor closely but not as much to touching a wall, chekered wall woudn´t make much sense.

**Comment by TeamSpen210** [comment]
Turn off gridpos, then it will only activate if the surface is exactly at the position you specify.

**Comment by LautaroL20** [comment]
Unfortunately, your feature to make gridded surfaces also for others orientations seems to not work, every time getting a failure to compile that says:  `Could not open instance file instances/BEE2/logic/blocks/128x32x32_black.vmf` the compiler thinks i am using Flat Blocks when im not.......
 |
