### ISSUE TITLE
Imput A/B Editor models are being displayed as a "Mysterious White Texture" for the Clean Editor

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1740]
![20170315035736_1](https://cloud.githubusercontent.com/assets/12244376/23936976/c03bf372-0933-11e7-86c0-e206b5be9809.jpg)

**Comment by ZombiePwner1** [comment]
Illuminati confirmed.

**Comment by Luke18033** [comment]
Indeed, Illuminati confirmed:
![input_ab_illuminati](https://cloud.githubusercontent.com/assets/19228201/24128890/2a6bf33e-0d9c-11e7-9655-def317f04323.jpg)
