### ISSUE TITLE
Imput A/B Editor models aren´t using a proper selection mesh, they´re being a bit difficult to grab.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1741]
Ill improve selection meshes on Blender.

**Comment by LautaroL20** [comment]
![20170315054226_1](https://cloud.githubusercontent.com/assets/12244376/23940101/819ef754-0942-11e7-99a0-fd69a31cea4b.jpg)

**Comment by ZombiePwner1** [comment]
@LautaroL20 Nice also i'm waiting for you on steam.

**Comment by LautaroL20** [comment]
Both are fixed now:
![20170315060024_1](https://cloud.githubusercontent.com/assets/12244376/23940752/e96ce1aa-0944-11e7-90d5-d1912e453c6c.jpg)

**Comment by ZombiePwner1** [comment]
@LautaroL20 lol seems you didn't read my comment.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Ok.

**Comment by TeamSpen210** [comment]
Just as a note - be careful with the selection meshes - we'd want to keep them as simple as possible, with few concave parts. They don't need to exactly match - for the B 3 faces would probably be fine.

**Comment by LautaroL20** [comment]
Alright.
