### ISSUE TITLE
1/4 and 2/4 Partial Flat Blocks Varieties are missing its gridded surface 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1742]
![IMAGE](https://cloud.githubusercontent.com/assets/12244376/23941713/98fce658-0948-11e7-8fad-b062669d0567.jpg)

**Comment by TeamSpen210** [comment]
That's intentional, the 1/2 block uses 2x2 tiles. For the 1/4 block I'd want to use a combination of 4x4 and 2x2 tiles, but the infrastructure isn't complete yet to allow that.

**Comment by Endermage77** [comment]
Should this be labeled Intentional, then?
