### ISSUE TITLE
The SP Entry N°7 can leave you "Stagnant Forever" on entrance elevator´s area

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1744]
It looks like that there is a missing clip, or a defective one on that door....

GIF:
![gif](https://cloud.githubusercontent.com/assets/12244376/23945683/371cfb18-0956-11e7-8e03-1b21e1388b13.gif)

___________________________________________________________________________________________

Feel free to call me the Second Great Beemod Bug Finder.

**Comment by ZombiePwner1** [comment]
The trigger to close the door is too close.

**Comment by LautaroL20** [comment]
Yep, ill fix this aswell.
