### ISSUE TITLE
A light bridge that holds the player but not objects or paints

### ISSUE THREAD

**Issue by andremiles1** [BEEmod/BEE2-items#1747]
Player can walk normaly on them but objects pass through it like nothing.
With a different color, of course, to differentiate from the original. I think orange, since the original one is blue.
I don't know if this is possible but it would be an interesting new test element.

**Comment by Luke18033** [comment]
Not possible, light bridges are hardcoded into the game.

**Comment by Konclan** [comment]
What about a item placed like a fizzler that looks like a bridge with these properties? it'd look nicer than using an actual fizzler

**Comment by Konclan** [comment]
Maybe this item could be called fizzler strips, its as wide as a lightbridge but like the standing fizzler you can connect a fizzler to it to change the type

**Comment by Luke18033** [comment]
Maybe, but it couldn't go through portals.

**Comment by Luke18033** [comment]
I once had an idea for a fizzler which only blocks players. I called it the "Lifeform Deflection Field" or something.

**Comment by Konclan** [comment]
It couldn't go through portals but it would still be a nice smaller varient of a fizzler that I don't think anyone has ever done

**Comment by Konclan** [comment]
Actually I just realized this could be super useful for having a space to shoot a portal behind a fizzler but not enough to pass through it

**Comment by Byzarru** [comment]
How does the BP light item work then? I understand it's a bunch of textures and entities that string together, but I know nil about Hammer. Couldn't that mechanic be applied to a facsimile HLB with fizzler properties, so it would work with portals?

**Comment by TeamSpen210** [comment]
Not really, the difficulty is making it resizeable. I haven't looked at the logic for it, but it'd basically be a 'beam' sprite repeated for the distance. You can't make that solidn, not without potentially spawning hundreds of entities. Even then a bug I found means you can't gel those properly.

**Comment by libbybapa** [comment]
The already implemented compressed smoke field allows objects to pass but does not allow the player to pass.  Place it horizontally and it seems to satisfy the request.  A light bridge also allows portal shots and the CSF does not, but portal shots were not mentioned.

**Comment by andremiles1** [comment]
@libbybapa I've suggested a lightbridge because you can "take it" on your portals to navigate on test chambers.

**Comment by andremiles1** [comment]
And about turret shots?
You guys think this light bridge can block it too or not? If it's possible, this orange light bridge can't block turret shots in my imagination. Also, this light bridge works like excursion funnels, it can be changed to blue without turning it off.

**Comment by Endermage77** [comment]
It should probably be smoked purple, if anything, so it matches the Compressed Smoke Field.

**Comment by TeamSpen210** [comment]
I could implement the original suggestion, it'd basically have two bridges right next other, with an altered emitter model which is wide enough. You'd have the blue 'rail' in the center.

**Comment by Luke18033** [comment]
Wrong issue? That sounds like a double light bridge.

**Comment by Luke18033** [comment]
Not exactly sure what's being suggested here, we can't add custom light bridges, and as a fizzler this is nearly identical to the CSF.
