### ISSUE TITLE
Sendificator not working

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1749]
![20170316100357_1](https://cloud.githubusercontent.com/assets/12244376/23997384/edcb22ac-0a2f-11e7-875e-28b1e2ecc0d4.jpg)

**Comment by LautaroL20** [comment]
It also doesn´t work on Old Aperture.

**Comment by Luke18033** [comment]
Is the sendificator actually connected to the laser? Or is connection visibility just set to none?
