### ISSUE TITLE
80´s Reflection Cube Without Dropper Crashes the game

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1751]
![IMAGE](https://cloud.githubusercontent.com/assets/12244376/24000231/6d952146-0a39-11e7-8692-fa16e910562f.png)

**Comment by LautaroL20** [comment]
This is what happens if you place a "Reflection Cube" without its dropper.

**Comment by Luke18033** [comment]
Looks like it's trying to set the model to one that isn't loaded. That's the normal rusted cube model, not the reflection cube.

**Comment by TeamSpen210** [comment]
This will be fixed by not using any of that logic.
