### ISSUE TITLE
Put a "Timer Option" in the Observation Room´s menu, each number controls the brightness inside it

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1753]
This would be applied in both the observations. Each number controls the brightness inside it, until max that you can put a observation room with no light.

**Comment by TeamSpen210** [comment]
That's supposed to be like that, you shouldn't be able to see clearly inside.

**Comment by Luke18033** [comment]
You will also need to revert the commit.

**Comment by andremiles1** [comment]
Why don't put some "timer" on it, each number controls the brightness inside it, until max that you can put a observation room with no light?

**Comment by LautaroL20** [comment]
@andremiles1 - That was a really good suggestion! Thanks for sharing it with us.

**Comment by hop193** [comment]
> Why don't put some "timer" on it, each number controls the brightness inside it, until max that you can put a observation room with no light?

That would be interesting to see.
