### ISSUE TITLE
Old 50's 60's 70's and 80's aperture players can get stuck forever in enrichment sphere's goo if they fall due to "Missng Trigger Kill" on it

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1755]
![20170317164759_1](https://cloud.githubusercontent.com/assets/18079316/24035735/b95213a2-0b31-11e7-88f6-23a6926535eb.jpg)

No handrails therefore players can jump off and get trapped forever in the goo.

**Comment by TeamSpen210** [comment]
You should be killed...

**Comment by ZombiePwner1** [comment]
Well i'm not there is no death trigger for the goo. Add a handrail or something.

**Comment by TeamSpen210** [comment]
The hole in the handrail is very intentional. There's even an autosave before it in the corridor.

**Comment by Luke18033** [comment]
Duplicate of #1303.
