### ISSUE TITLE
Pedestal Button that can be placed in Right-Middle-Left Positions plus rotation toggle

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1758]
![20170317152636_1](https://cloud.githubusercontent.com/assets/12244376/24057468/36132e5a-0b26-11e7-9ea8-8d1ec4e5749c.jpg)

**Comment by Konclan** [comment]
This technically already exists

**Comment by Luke18033** [comment]
Basically, the Protruding Pedestal Button minus the protruding.

**Comment by Luke18033** [comment]
This could just be added to the original item.

**Comment by LautaroL20** [comment]
@Konclan - No, you still woudn´t be able to use my protruding ped buttons with a "Track Plataform" close to it because it will gonna say invalid position because floating, this is why this item would be useful:
![20170317160947_1](https://cloud.githubusercontent.com/assets/12244376/24059114/8b9fb4e6-0b2c-11e7-90ae-5e3e9b408a79.jpg)

**Comment by Luke18033** [comment]
Make sure the middle button has a 2-tile wide base, the original 3-tile base looks kind of weird since it's not aligned to the tile grid...

**Comment by Luke18033** [comment]
Maybe call this the "Pedestal Button Plus"

**Comment by TheDarkBomber** [comment]
Duplicate of #447.

**Comment by LautaroL20** [comment]
No it isn´t.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Lol BTW come online you wheely.

**Comment by TheDarkBomber** [comment]
It is.

**Comment by LautaroL20** [comment]
@TheDarkBomber - No its not. Can you see the label or do you need a pair of glasses? It says "New Item".

**Comment by TheDarkBomber** [comment]
So is #447.

**Comment by LautaroL20** [comment]
That one is just about giving a simple rotation toggle for Valve´s pedestal. This one is about a new button variant.

**Comment by TheDarkBomber** [comment]
Instead of opening a new issue, why not just edit that one?

**Comment by LautaroL20** [comment]
Because merging this in the PeTi´s pedestal would break the `ITEM_BUTTON_PEDESTAL` condition, and that implies breaking old puzzles files as well as the item´s collisions into the Editor.

**Comment by TheDarkBomber** [comment]
:man_facepalming: I said edit the issue. Not the item.

**Comment by LautaroL20** [comment]
Because this must be a separated issue since it has nothing to do with the konclan´s one anymore.... Issue #447 will also gonna be implemented.

**Comment by hop193** [comment]
> Duplicate of #477
It isn't.

**Comment by Luke18033** [comment]
That's why you don't give @TheDarkBomber admin access to anything, if he were a collaborator right now he'd probably be locking this or something...

**Comment by LautaroL20** [comment]
Indeed, this would have turned into a constant close-re-open annoyiance situation where all of you would had a massive list of notifications into your e-mail inboxes until someone flagged @TheDarkBomber to the Github Support.

**Comment by Luke18033** [comment]
> No, its not. Can you see the label or do you need a pair of glasses? It says "New Item".

> So is #447.

I think he does need glasses, #447 does NOT have the New Item label and never did.

**Comment by hop193** [comment]
> I think he does need glasses, #447 does NOT have the New Item label and never did.

Lol, he does.

**Comment by hop193** [comment]
So, any info about this?

**Comment by LautaroL20** [comment]
Glad to see you interesting, once i make the BTS Model Editor for the pedestal button, i will do it.

**Comment by LautaroL20** [comment]
This is now implemented. You can test it by using the Dev version, or just wait for the PRL26.
