### ISSUE TITLE
Upgrade to Light Strips

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1760]
Rather than having Original, Warm, and Cool Light Strips being separate items, couldn't they be chosen by one item? This is already done with Square Lights, so...

**Comment by Luke18033** [comment]
Everybody wants this, but guess why is not being implemented? *Because it would break collisions.* It would break STUPID ITEM COLLISIONS WHICH NOBODY CARES ABOUT AND WOULD BE PERFECTLY HAPPY IF THEY WERE GONE. And if not blocking antlines is such a *huge* problem, JUST USE THE ANTLINE ROUTER.

**Comment by TeamSpen210** [comment]
Oh, and also it'd break any maps which already have warm light strips in them.
Item collisions are important because you need to block antlines, and also I don't want to allow you to put things on top of each other.

**Comment by hop193** [comment]
> Everybody wants this, but guess why is not being implemented? Because it would break collisions. It would break STUPID ITEM COLLISIONS WHICH NOBODY CARES ABOUT AND WOULD BE PERFECTLY HAPPY IF THEY WERE GONE. And if not blocking antlines is such a huge problem, JUST USE THE ANTLINE ROUTER.

> Oh, and also it'd break any maps which already have warm light strips in them.
Item collisions are important because you need to block antlines, and also I don't want to allow you to put things on top of each other.

My apologies, I wasn't aware of the constant spam for this feature.

**Comment by Byzarru** [comment]
> STUPID ITEM COLLISIONS WHICH NOBODY CARES ABOUT AND WOULD BE PERFECTLY HAPPY IF THEY WERE GONE
Who's got two thumbs and is a nobody
👍 👎 This guy

**Comment by TheDarkBomber** [comment]
Just make them one item. Simple.

**Comment by Endermage77** [comment]
But so that it doesn't break current maps, try making it a NEW item instead of an item update.
