### ISSUE TITLE
1950s Rocket Turret not working 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1761]
Original post by @BaronVonMe (https://github.com/BEEmod/BEE2.4/issues/555)

___________________________________________________________________________

"It says in the description of the rocket turret that it should work in the 1950s but when I try to it is just a see through solid block."

**Comment by Luke18033** [comment]
See #1909.

**Comment by Luke18033** [comment]
#2540, whoops.
