### ISSUE TITLE
Remove the "Timer Sound & Symbol"  from Logic Gates when connected to a Cube Dropper 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1762]
EDITED: This would be a default feature affecting only Cube Droppers, so no need to add aditional options in the logic gates´s menu.

![20170320103954_1](https://cloud.githubusercontent.com/assets/12244376/24102138/bd820192-0d59-11e7-8017-d08c3a39cd92.jpg)

**Comment by Luke18033** [comment]
Also see #1524, which would affect the timer sign.

**Comment by LautaroL20** [comment]
Uhm, this one suggestion would be about a default feature id want to have for Logic Gates. Yours are about using an option in the item´s menu though.

**Comment by Luke18033** [comment]
Indeed, which is why I didn't close this.

**Comment by Luke18033** [comment]
The features are related, since both involve hiding the timer panel.

**Comment by LautaroL20** [comment]
Fixed title, it woudln´t make sense if it donesn´t remove the timer sound too.

**Comment by libbybapa** [comment]
Put and AND gate at the pedestal, connect the pedestal to the AND, connect the AND at the pedestal to the second AND at the dropper.  No more timer symbol.

**Comment by TeamSpen210** [comment]
Valve coded the dropper to do this, but we'd want it to apply to all items.

**Comment by hop193** [comment]
I would love for the start enabled feature to be added for PR25.

**Comment by TeamSpen210** [comment]
Actually, this is rather difficult - since we don't know for each timer sign what it's pointing to, only where it's coming from. If it's only pointing to one it's doable, but not otherwise.

**Comment by TeamSpen210** [comment]
Now done, by making all cube droppers "locking" items.
