### ISSUE TITLE
New Item: Antline Splitter

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1763]
Simple enough. When two connections from the same input connect to the Antline Splitter, one of the antlines from the input gets removed. It splits the single antline into two antlines, heading the opposite direction from each other. If there is 3 antlines connected, 2 get removed, if there is 4, 3 gets removed, etc.

**Comment by TeamSpen210** [comment]
It isn't possible to have two connections from one item to another. What would this do exactly?

**Comment by Byzarru** [comment]
Oh, I get it (one antline from an input branches off to connect to the outputs?). You can't use an item to relay signals like this, but the effect is achievable with AND gates and the antline magnet. Or just an antline magnet. Disable connection visibility on all of the outputs and connect your input to the AND gate. Place Antline Magnets by the outputs and connect the AND gate to the Antline Magnets.

**Comment by hop193** [comment]
> (one antline from an input branches off to connect to the outputs?)

Yes, this is what I mean.

> Or just an antline magnet. Disable connection visibility on all of the outputs and connect your input to the AND gate. Place Antline Magnets by the outputs and connect the AND gate to the Antline Magnets.

Seems possible, but having this item can remove that process.

**Comment by Byzarru** [comment]
Since you can't have multiple connections between two items, this would effectively just be an AND gate.

**Comment by Byzarru** [comment]
Since this item would effectively be a special AND gate, the likes of which have been suggested before, I think it's safe to close this.

**Comment by hop193** [comment]
> Since you can't have multiple connections between two items, this would effectively just be an AND gate.

I guess you are correct, but if you _were_ to use it, there would be a big gaping hole in between the antlines.

> ... the likes of which have been suggested before, I think it's safe to close this.

I guess... 😞
