### ISSUE TITLE
Reclined Fizzlers (Not the Recessed into a Wall)

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1765]
A Fizzler which is placeable upon a surface, useful for certain scenarios where you can not achieve it by using the flat blocks and the peti fizzler. These wouldn't be embedded boxels like the recessed fizzlers did though:

![20170322093919_1](https://cloud.githubusercontent.com/assets/12244376/24198280/fa987daa-0ee3-11e7-8168-4ad76592f65b.jpg)

**Comment by hop193** [comment]
Yes, this would be wonderful if it was added in PR25!

**Comment by Byzarru** [comment]
Something tells me you've already developed this item.

**Comment by LautaroL20** [comment]
Not yet, but i already performed their editor models which is something.

**Comment by Luke18033** [comment]
This would use the same compiler logic as the standing fizzlers (#257) to switch the type based on what kind of fizzler is connected.
