### ISSUE TITLE
Old aperture crushes do not kill players on the edge.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1768]
![20170323074821_1](https://cloud.githubusercontent.com/assets/18079316/24225899/0aba8f38-0f9e-11e7-91cf-2332651227a9.jpg)

**Comment by Luke18033** [comment]
This is intentional, Clean crushers behave the same way.

**Comment by FrozenDragon0** [comment]
@TeamSpen210 Changed I think so that it kills players on the edge aswell.
