### ISSUE TITLE
Matter Inquisition Field Editor Model displays wrong colour 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1771]
![20170324210811_1](https://cloud.githubusercontent.com/assets/12244376/24317624/c6bb2442-10d7-11e7-804b-91863bda9a16.jpg)

**Comment by ZombiePwner1** [comment]
@LautaroL20 It's not even using a yellow line it's using a green line.

**Comment by LautaroL20** [comment]
True.

**Comment by HugoBDesigner** [comment]
Is it not possible to modify the model to display the field color on the fizzler? If not, maybe have the color of the field show up on the sides of the fizzler emitter in the editor?

**Comment by TeamSpen210** [comment]
I can't change the blue field you see, that's rendered by the editor. I can change anything about the model though.

**Comment by HugoBDesigner** [comment]
Adding some yellow stripes to the emitter model would be helpful, I think.

**Comment by Endermage77** [comment]
Or even perhaps adding a yellow "slab" to the emitter's model that looks like part of the Matter Inquisition Field. It wouldn't stretch all the way across the room, of course.

**Comment by LautaroL20** [comment]
Now fixed.
