### ISSUE TITLE
Standing & Reclined Fizzlers will require a rescaled model

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1774]
![20170324221658_1](https://cloud.githubusercontent.com/assets/12244376/24318180/e2a7abbe-10df-11e7-84be-bd8c21ecc2a7.jpg)

**Comment by LautaroL20** [comment]
Model is now rescaled, here is a GIF:
![gif](https://cloud.githubusercontent.com/assets/12244376/24686905/0f628efc-198d-11e7-8817-dbd304c78c79.gif)

**Comment by TeamSpen210** [comment]
We also need the custom fizzler models to be rescaled. I should just do that with the existing model though.

**Comment by LautaroL20** [comment]
I will commit this to a separated branch, but how is it possible to tell Bee2.4 to swap to the "Cheaper" Static instance of the fizzler? I mean, ive maked two types: `standing_fizzler` and `standing_fizzler_static`

I am not sure how to perform a proper config in the .cfg files, tried to check into others config but these doesn´t fit with my addon very well.

**Comment by Luke18033** [comment]
They'll also need rescaled P1 particles, the default ones are 256x128.

**Comment by TeamSpen210** [comment]
Unfortunately you can't pack particles as far as I'm aware.
