### ISSUE TITLE
New Item: Dynamic Lightstrips

### ISSUE THREAD

**Issue by SW50000** [BEEmod/BEE2-items#1778]
This Item would be like the one in the instance file `light_panel_128_neutral_high`
Unlike the normal light strip, this has a light texture behind it, and a dynamic light.
This will still have a cool, normal, and warm one.

Like this but with some modifications:
![image](https://cloud.githubusercontent.com/assets/20195894/24376672/4cef8aa4-1302-11e7-8664-6689e8ae5b30.png)

**Comment by TheDarkBomber** [comment]
Wouldn't this just be a brighter version?

**Comment by SW50000** [comment]
Ah yeah, this wouldn't be needed then.

**Comment by TheDarkBomber** [comment]
You know, you can just edit the issue as a request to make the lightstrips brighter this way.

**Comment by SW50000** [comment]
But this takes up space in the wall

**Comment by TheDarkBomber** [comment]
We have a condition to handle that.

**Comment by SW50000** [comment]
Well, the single lightstrips have just the light texture behind it
But 4 lightstrips have a dynamic light on it.
P.S can you stop speaking Spanish on discord?

**Comment by SW50000** [comment]
I'll reopen this and see what everyone else thinks about this if it's useless or helpful.

**Comment by HugoBDesigner** [comment]
I personally don't think it'd make such a big difference, especially since you can already place 4 light strips on a voxel, or use the square lights.

**Comment by SW50000** [comment]
> I personally don't think it'd make such a big difference, especially since you can already place 4 light strips on a voxel, or use the square lights.

Yeah, that's what I thought, I'll let someone else close this since I'm never sure.
