### ISSUE TITLE
Add several variations of items (especially in Old Aperture)

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1779]
For Old Aperture and BTS levels, there are two different styles of doors that you could use: the push bar and sliding door for the former and the heavy security door and sliding door for the latter. Maybe add a "Start Reversed" option to change the type?
Same with vactubes, you could add the concrete ones that are meant for gel.

**Comment by Endermage77** [comment]
The push-bar door wouldn't really combo well with the sliding door because it would see better use in an Old Aperture BTS style as a manual door. And it wouldn't lock.

Also, we already use "Start Reversed" to determine which way the door faces (The running man side is forward).

**Comment by TeamSpen210** [comment]
The gel-specific pipes will be used when gel is made to flow through the pipes (via a special gel dropper item at the start). 

The push-bar door is really a seperate item - more for one-way exits. Maybe I should use it in Old Aperture chamberlocks?

The heavy security door will be the Old Aperture 'vertical door' variant.

**Comment by snorepion** [comment]
@Endermage77 
Oh yeah, I forgot. I suppose they'll have to be separate items.

@TeamSpen210 
Are the gel pipes currently implemented or are they for a future version?

Yeah, I think they'd be a good chamberlock (especially for the 50s).

**Comment by TeamSpen210** [comment]
Not currently implemented.

**Comment by snorepion** [comment]
Will they be in the next release, or are they just something you have in mind?

**Comment by TeamSpen210** [comment]
More having in mind.

**Comment by Luke18033** [comment]
The Clean/Overgrown/P1 variant of the push-bar could be a normal door with a pedestal button next to it. BTS would use its version of the same design, but the button would be attached to the door frame instead of standing in front. The button trigger would cover the door and not the button itself.

**Comment by snorepion** [comment]
Oh, also, you could use the Vitrified doors somewhere. Like the ones that you can't open in Old Aperture?

**Comment by TeamSpen210** [comment]
Those are used in the 60s corridors.

**Comment by snorepion** [comment]
Okay. Haven't used the 60s style much, so I didn't notice.
