### ISSUE TITLE
Any ideas on how should it look the BTS Variant from Protruding Ped Buttons?

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1781]
It would be interesting to listen some ideas if anyone got one.

**Comment by TheDarkBomber** [comment]
A circuit breaker standing on a small piece of unstable metal.

**Comment by ZombiePwner1** [comment]
@LautaroL20 As @TheDarkBomber said but the base that the button stands on could be like a plastic or concrete base.

**Comment by TeamSpen210** [comment]
If there's a wall behind them, then should not have a base and instead attach directly.

**Comment by Endermage77** [comment]
I thought this issue was asking about the retractable button, but why not put my suggestion here anyway?

It would be a circuit breaker in a glass emergency case that slides open.

**Comment by LautaroL20** [comment]
> I thought this issue was asking about the retractable button.

It looks like that someone needs a pair of glasses... Title says it pretty clear: "BTS Variant from Protruding Ped Buttons".

**Comment by Byzarru** [comment]
> I thought this issue was asking about the retractable button, but why not put my suggestion here anyway?

#1228.

**Comment by LautaroL20** [comment]
DarkBomber´s idea is interesting. I consider this answered.
