### ISSUE TITLE
Add the unused sp_intro_01_05_apple soundtrack.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1784]
Could be used for overgrown or something.

**Comment by Luke18033** [comment]
Which version, the used or unused one? There are two versions, with the unused one ending in .wav. I don't exactly understand how the used version works without an extension, but Valve found a way to do it.

**Comment by ZombiePwner1** [comment]
@Luke18033 It's unused soundtrack that's mean't to play in the first level after saying apple.

**Comment by Luke18033** [comment]
*Was* meant to play.

**Comment by Luke18033** [comment]
This doesn't loop, and isn't really music that should be playing in a test chamber.
