### ISSUE TITLE
Reimplement BEE2.2 Overgrown features

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1785]
![20170329203039_1](https://cloud.githubusercontent.com/assets/18079316/24454571/ea66e2ba-14be-11e7-8a82-1210d16cdbae.jpg)

Bent gel droppers with vines coming out of them.

![20170329203147_1](https://cloud.githubusercontent.com/assets/18079316/24454582/f40502e8-14be-11e7-80ec-92697b26d0e8.jpg)

Overgrown wall features.

![20170329203203_1](https://cloud.githubusercontent.com/assets/18079316/24454593/f91c0736-14be-11e7-91fb-26f832f1c681.jpg)

![20170329203210_1](https://cloud.githubusercontent.com/assets/18079316/24454595/ff6ea13e-14be-11e7-89c5-a9d6c1cc0c65.jpg)

Flickering antlines.

The old BEEmod had alot of overgrown features i would like to see get put into beemod.

**Comment by TeamSpen210** [comment]
I've killed the flickering antlines deliberately, since we now have some of them broken.

**Comment by ZombiePwner1** [comment]
Okay but what about the other features I mentioned?

**Comment by TheDarkBomber** [comment]
They'll probably be part of Overgrown Decorations.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 I've re-implemented the vines hanging from gel droppers.


![20170404155035_1](https://cloud.githubusercontent.com/assets/18079316/24646463/a0cd2972-194e-11e7-9c68-0360e4e1c3e0.jpg)

**Comment by Luke18033** [comment]
I noticed a bunch more things like this while looking at an old test map:
* Cracked laser items and tilted catchers/relays
![portal2_uLpAYk9DwA](https://user-images.githubusercontent.com/19228201/81522645-2481f080-9300-11ea-8c9d-46931a539452.jpg)
* Bent track platform rails with up/down platform movement and creaking sounds
	* With BEE2.4 we can use custom models for the rail and make the platform accurately match the shape.
![portal2_vQZOppjK47](https://user-images.githubusercontent.com/19228201/81522675-3d8aa180-9300-11ea-8dc0-b2bba7fce7c8.jpg)
* HEP with added particles
![portal2_SetxlmLd0m](https://user-images.githubusercontent.com/19228201/81522775-922e1c80-9300-11ea-9060-255cf00030af.jpg)
* Plants hanging from angled panels
	* With BEE2.4 should only appear when vertical like this, maybe limit to static panels
![portal2_OxSmpXs3F5](https://user-images.githubusercontent.com/19228201/81522791-a2de9280-9300-11ea-8df1-0ed9210e9b13.jpg)
* HEP catcher hanging out of wall, retracts when powered
![portal2_tJ7Ef6rd6j](https://user-images.githubusercontent.com/19228201/81522839-d1f50400-9300-11ea-9224-2f69d7d87934.jpg)
* Crusher with smash sounds, dust particles, and cracked surrouding wall
	* In BEE2.4 surrounding wall would be a template, have variants
	* The sounds and particles should only be added when there is an opposing surface
![portal2_k4C5lNTZBU](https://user-images.githubusercontent.com/19228201/81522902-010b7580-9301-11ea-9b3d-4ea25aed72bb.jpg)
* Gel dropper on wall becomes an exposed gel tube
![portal2_DSiu4tZm41](https://user-images.githubusercontent.com/19228201/81522918-0ec0fb00-9301-11ea-9590-bf1aec36543e.jpg)

**Comment by Konclan** [comment]
The exposed gel tube is a nice idea but it doesn't really have a logical reason for being. Also gel dropper don't embed into the wall so the pipe would have to be sticking out of the wall like that which I don't really think looks good.

**Comment by Luke18033** [comment]
Wall-mounted gel droppers actually do act like they have a 1-block embed space, so we can technically use that area.

**Comment by Luke18033** [comment]
I don't think most of these features are really needed
