### ISSUE TITLE
Make it so that people can add their own packages and items

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1786]
You could do this in BEE2.2.5, but I haven't seen a way to do it in the current release. BEE2.4 tends to screw up Hammer a lot, so I can't easily add instances there, and if you could add your own packages, Hammer wouldn't even be necessary. 
Of course, there might be a reason for this that I'm overlooking, or it would simply be too difficult to implement.

**Comment by TeamSpen210** [comment]
Um, it's designed to make it better for adding packages - they're just zip files. The whole point of them is that they're self-contained, so anyone could create a zip, and you just add it to the folder to install it.

**Comment by snorepion** [comment]
Oh yeah, looking through the folders, I can kind of see how the packages are designed. Are they automatically added to the program if you put the folder in, or do I need to edit some config file?

**Comment by TeamSpen210** [comment]
It's automatic. You can also just use a folder with the files inside instead. The `info.txt` file inside is the important one, it specifies what things are in the package.

**Comment by snorepion** [comment]
K, thanks. Apparently I'm an idiot!

**Comment by TheDarkBomber** [comment]
Don't forget WASP.

**Comment by snorepion** [comment]
Yeah, I'm very excited for that  to be released.
