### ISSUE TITLE
Retro Cube Editor Model can´t be grabbed when its including the Dropper 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1788]
When its including the dropper, the cube isn´t possible to grabb. Probably a bugged / missing Selection Mesh?

![20170330171151_1](https://cloud.githubusercontent.com/assets/12244376/24524234/340218f6-156c-11e7-9671-eaa3089516ec.jpg)

**Comment by Luke18033** [comment]
The cube editor model actually doesn't change its selection mesh when it floats up. 
![20170401142927_1](https://cloud.githubusercontent.com/assets/19228201/24582587/e6022a60-16e7-11e7-86b4-26a9191a2298.jpg)
Do `puzzlemaker_drawselectionmeshes 1` and see what it looks like.
