### ISSUE TITLE
Retro Pedestal Button is having issues on their textures

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1789]
![20170330171151_1](https://cloud.githubusercontent.com/assets/12244376/24524445/ec3a7670-156c-11e7-99fc-0e65870052c4.jpg)

**Comment by LautaroL20** [comment]
Well, since its a bug that isn´t on the public version, ill close this.

**Comment by Byzarru** [comment]
Dev issues are still issues, so I think it should be open until the release.

**Comment by Luke18033** [comment]
It's fixed now.
