### ISSUE TITLE
Trigger for portal placement

### ISSUE THREAD

**Issue by AvapXia** [BEEmod/BEE2-items#1792]
I have a suggestion for a new type of trigger, a portal trigger.

A blue trigger that can detect when a portal has been placed in the area.

I don't really know how this would work or if it can be done, but i thought of it while reading #1107  and if it can be done then you could have any input toggle whether the fire is on or off.

**Comment by Endermage77** [comment]
This is probably going to be implemented eventually; Radelite created this exact item (for one portal or the other or both) as part of his addons pack for BEE2.2.5.

**Comment by AvapXia** [comment]
Oh cool. I might check that out, can it be used with later versions of BEE2 or just 2.2.5?

**Comment by Luke18033** [comment]
The difference is that the BEE2.2 one was visible, while I assume this would be an invisible trigger.

**Comment by Luke18033** [comment]
Unlike the regular triggers, this should be placed flat against the surface as opposed to being a full voxel size. It would still be resizeable, but only in two directions.

**Comment by Konclan** [comment]
Moving to #3886
