### ISSUE TITLE
Grating Item is "broken", it doesn´t prevent you from walking through it anymore when placed upon a portalable surface

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1794]
GIF:
![gif](https://cloud.githubusercontent.com/assets/12244376/24824746/dff3e762-1be7-11e7-880b-82b82c46101b.gif)

This is a possible solution to this issue:

![Image](https://cloud.githubusercontent.com/assets/12244376/25383369/30f864fa-2992-11e7-9c76-67dfecadb8d5.png)

**Comment by LautaroL20** [comment]
Just an aditional note on this is that it doesn´t matter the grating position as well its upon a portalable surface, i mean that it can be upon a ceilling / floor or wall surface and the issue will still happens.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Well it's a good thing i don't have the development version.

**Comment by LautaroL20** [comment]
I wonder if this also affects the Glass item too. Ill have to test....

**Comment by TeamSpen210** [comment]
Ah, that's a good idea. Also on the walls this should just be disabled.

**Comment by LautaroL20** [comment]
> Also on the walls this should just be disabled.

What do you mean exactly? We would still need the aditional ordinary playerclip to still works, and also the bee2.4 one too, since without it wouldn´t do the grating sound.

**Comment by LautaroL20** [comment]
To still works on walls*

**Comment by TeamSpen210** [comment]
Well, you can't walk on walls so it wouldn't need to be a grating surfaceprop.

**Comment by LautaroL20** [comment]
I think it still needs too, heres why: 

![20170408053859_1](https://cloud.githubusercontent.com/assets/12244376/24827333/b2cdbe30-1c1d-11e7-9218-e02542024a46.jpg)

**Comment by TeamSpen210** [comment]
Not when attached to walls, when the surface is vertical.

**Comment by LautaroL20** [comment]
Well, thats why i asked what exactly you meant.
