### ISSUE TITLE
Portals can be placed on the Old Aperture observation room

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1796]
![20170402130148_1](https://cloud.githubusercontent.com/assets/19228201/24590626/4ae85b44-17a5-11e7-82a3-8b0135f6c638.jpg)
This can be done immediately, even without portal bumping.

**Comment by LautaroL20** [comment]
Is that a new observation variant? The one i knew was the grating type.

**Comment by Luke18033** [comment]
It's an alternate version.
![image](https://cloud.githubusercontent.com/assets/19228201/24591171/d292a0ae-17af-11e7-9b2d-83e9b0d4adea.png)
