### ISSUE TITLE
Both types of P1 Co-op Checkpoints are unstyled

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1800]
![20170402155456_1](https://cloud.githubusercontent.com/assets/19228201/24591734/31247784-17bd-11e7-90c9-d0301db7582d.jpg)

**Comment by ZombiePwner1** [comment]
This is a duplicate of https://github.com/BEEmod/BEE2-items/issues/640

**Comment by Luke18033** [comment]
That's specifically referring to the normal version though.

**Comment by ZombiePwner1** [comment]
@Luke18033 It's still a duplicate.
