### ISSUE TITLE
Player Detector 

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1803]
This works exactly like the detector that co-op exits use, except it only detects one player or the other (and the single player either way).

Edit: In the format of the Button Type:
Weighted --> Blue
Cube --> Orange
Sphere --> Both

It will probably look like the co-op exit detector, too.

Just put it on a wall at ground level, and it will activate whenever the correct player stands in the same voxel.

**Comment by ZombiePwner1** [comment]
This could be useful in coop maps with multiple rooms and there is a door that has a certain player on it.

**Comment by TeamSpen210** [comment]
I don't like restricting stuff to a *specific* player. The seperated coop checkpoint for example lets you choose which side you want to go to.

**Comment by TheDarkBomber** [comment]
Wouldn't this be a trigger with only one difference?

**Comment by Luke18033** [comment]
Test message to see if deleting still works correctly, Lautaro said it didn't.

**Comment by Endermage77** [comment]
This is a camera item like the one on the co-op exit door that outputs when one player or the other or both is standing in front of it.

We could possibly even have a stylevar for voiceline reactions while emoting in front of it (Like GlaDOS already does), because why not?

**Comment by iEnderMan06** [comment]
... We really don't need this... You can already do this system with a couple trigger multiples, However a prop_physics detector would be very nice.

**Comment by HugoBDesigner** [comment]
Yes, you can have triggers for sp, but for multiplayer there is no way of differentiating between the bots, which is the main reason behind this suggestion.

**Comment by iEnderMan06** [comment]
double trigger multiple plus button AND gate system

**Comment by HugoBDesigner** [comment]
Still doesn't differentiate between the bots

**Comment by Konclan** [comment]
Moving to #3886
