### ISSUE TITLE
Portal 1 dropper turrets are not using the Portal 1 turret model

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1806]
Notice how the left turret is using the wrong model.
![20170403135656_1](https://cloud.githubusercontent.com/assets/19228201/24631637/ee050252-1875-11e7-80f6-0466be17cc07.jpg)

**Comment by iEnderMan06** [comment]
My P1 Turrets don't even have that style,

**Comment by HugoBDesigner** [comment]
Here's probably why:
![image](https://cloud.githubusercontent.com/assets/6296061/24835009/9776e3d8-1ccb-11e7-92fb-2a2f3f90130e.png)

**Comment by iEnderMan06** [comment]
I see,
