### ISSUE TITLE
The Portal 1 door's surrounding brushes are too thin

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1807]
Screenshots from the original Portal 1:
![20170403144248_1](https://cloud.githubusercontent.com/assets/19228201/24633535/e39d4704-187d-11e7-97d8-99e7bc6ad1c6.jpg)
The door frame barely protrudes from the wall on both sides.
![20170403144333_1](https://cloud.githubusercontent.com/assets/19228201/24633558/007aaad8-187e-11e7-9b01-94c5bab5cbe9.jpg)
The surrounding brushes are 32 units thick.

In the BEE2 version, however, things are a bit wrong:
![20170403144659_1](https://cloud.githubusercontent.com/assets/19228201/24633689/a961f7c8-187e-11e7-9052-eb2ee2bfb485.jpg)
The door frame noticeably sticks further out from the wall.
![image](https://cloud.githubusercontent.com/assets/19228201/24633795/31929ea4-187f-11e7-9595-87e231d97b66.png)
The surrounding brushes are only 24 units thick.

I'm not sure whether or not this also applies to the Door and Chamberlock.

**Comment by TeamSpen210** [comment]
Nice catch! I'll want to double-check some other maps as well, it might just be that one. In Portal 2 the door frames are 24 units thick, so they stick out. You can't tell really because that door model covers the entire space.

**Comment by TeamSpen210** [comment]
The Door item has to be 32 thick. The chamberlock though has the 24 frames, which we'd want to swap.

**Comment by Luke18033** [comment]
I checked a few maps, they all have 32 unit frames (except where the thin door is used).
