### ISSUE TITLE
Which Items are these?

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1815]
A lot of these levels seems as if they were made in PeTi, So I wondered: "Where are these?" Any help finding them?

![20170402200712_1](https://cloud.githubusercontent.com/assets/25728252/24780988/24c318ec-1b0a-11e7-834b-57ddfd9e6c3a.jpg)
_This one is the most important. I see ones with this and a fizzler so much. Help?_

![20170321202706_1](https://cloud.githubusercontent.com/assets/25728252/24781007/5746d524-1b0a-11e7-9247-30dd160c06ac.jpg)
_There is an Old Aperture window in Clean Style. How do I get this?_

I never used  BEE2.2 Addons, so if any of these were from that, then I'm sorry. But I need help finding these (especially the first one)

**Comment by Luke18033** [comment]
The first is a paint fizzler (implemented), the second is the vanilla grating in Art therapy style (not implemented).

**Comment by TeamSpen210** [comment]
The first is the 'recessed fizzler' item. It hasn't returned because it doesn't work with the custom fizzlers, and also can be replaced by a 3/4 block and normal fizzler. The second is Art Therapy Style, which is being worked on.

**Comment by hop193** [comment]
@TeamSpen210:
> The first is the 'recessed fizzler' item. It hasn't returned because it doesn't work with the custom fizzlers, and also can be replaced by a 3/4 block and normal fizzler. The second is Art Therapy Style, which is being worked on.

OK, thanks!
