### ISSUE TITLE
Standing Fizzler: Use Cube Type to resize its height

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1822]
We will need a nice ammount of conditions though, so we can prevent texture overlaps.

**Comment by hop193** [comment]
What if you wanted to make it wider than one block? Then what?

**Comment by LautaroL20** [comment]
@hop193 - Ah, i forgot to mention it, but the main focus of the Standing Fizzler is to saving as space as possible in the map. This is why it will be like the Thin Wall respect to the width.

**Comment by LautaroL20** [comment]
This is becoming true.

**Comment by Endermage77** [comment]
I think he meant making standing fizzlers wider in terms of fizzler width and not thickness.

**Comment by TeamSpen210** [comment]
We should be able to let you place multiple next to each other, and have those join together. Not with existing conditions though, and I need to make some stuff to allow rereouting inputs.

**Comment by LautaroL20** [comment]
@TeamSpen210 - My suggestion about a new `bee2_visgroup_controller` entity would help a lot. This will make things much easier for me.

**Comment by Luke18033** [comment]
Now implemented in the geometry branch, though it still isn't possible to make it wider.
