### ISSUE TITLE
Glass / Grating Item: Make it to swap to the original PeTi Playerclip when attached to Ceilling / Floor 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1825]

**Comment by TeamSpen210** [comment]
I didn't implement this yet, it's only a small optimisation.

**Comment by TeamSpen210** [comment]
Implemented in PR28.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the "implemented" label when closing the issue.
