### ISSUE TITLE
Portalable Piston Platform

### ISSUE THREAD

**Issue by awesomedoctorx3** [BEEmod/BEE2-items#1826]
A portalable Piston Platform, like this one here:

![p2_lift_standalone_portable](https://cloud.githubusercontent.com/assets/27110077/24833856/2450435e-1ca3-11e7-911e-eacfed113d2f.png)

Maybe  a portalable track platform also?

**Comment by HugoBDesigner** [comment]
I very second this. Also non-portalable too. I'm surprised I haven't found other instances of this suggestion, especially since I wanted to ask this myself.

**Comment by awesomedoctorx3** [comment]
also, it should be gel-able.

**Comment by Luke18033** [comment]
Duplicate of #95 and #674.
