### ISSUE TITLE
Weighted/Armored Turret

### ISSUE THREAD

**Issue by awesomedoctorx3** [BEEmod/BEE2-items#1827]
A turret that has some sort of metal plating, so that it is not burnable by lasers and also heavy enough to push weighted buttons.

**Comment by iEnderMan06** [comment]
That would be far too hard to do, It'd require actual game code editing as far as I know, due to the buttons only accepting actual types of weights,

**Comment by HugoBDesigner** [comment]
As far as I'm concerned, making buttons work with turrets shouldn't be too difficult. I think having them not burn with laser could be an issue, but I haven't tested either.

**Comment by iEnderMan06** [comment]
Well, you could make a brush around it, and apply the invisible texture, I'll make some tests with that now, Then for the button it'd most likely just be a cube parented to it, but invisible.

**Comment by ZombiePwner1** [comment]
Actually in the portal 1 chamber with turrets there is a bug where turrets can actually activate buttons.

**Comment by awesomedoctorx3** [comment]
But P1 turrets are different from P2 turrets, right?

**Comment by TeamSpen210** [comment]
Indeed this isn't possible. The P1 buttons I think are a bug.
