### ISSUE TITLE
Bottomless Pits

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1832]
I've noticed several maps that looked like they were using BEE2.X. Are bottomless pits available in BEE2.4? Or was a part of BEE2.2.5? Or was it even included at all?

**Comment by LautaroL20** [comment]
> Are bottomless pits available in BEE2.4? Or was a part of BEE2.2.5?

Bottomless pit is only in the latest Beemod version (The 2.4)

**Comment by Luke18033** [comment]
They're only available in BTS style, or more specifically, maps using the BTS skybox.

**Comment by TeamSpen210** [comment]
The stylechanger compiler actually did include a form of bottomless pit, but it was never used.

**Comment by hop193** [comment]
Wait, it's only in BTS? I played a map (It's called something like Wheatley Laboratories" (it's semi-popular)) using Clean Style, and it had bottomless pits.

**Comment by Luke18033** [comment]
> or more specifically, maps using the BTS skybox.

**Comment by LautaroL20** [comment]
@hop193 - You can literally build a map using any Style and as well as it uses the BTS Skybox it will have the Bottomless pit on it.

**Comment by hop193** [comment]
>You can literally build a map using any Style and as well as it uses the BTS Skybox it will have the Bottomless pit on it.

Oh, sorry about that. My bad.
