### ISSUE TITLE
Fake checkmark item/antline router

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1833]
Perhaps even add this option to the already-existing antline router, that makes a checkmark be visible and turn on/off depending on input. So for example, if I have a test element that has a single connection, but still want to display it with more than just an antline, or if I have a set of laser relays but don't want a bunch of signage or antlines, I can set up a checkmarks row on the wall, each one toggled by one relay, which would be a good indicator of how many items are on.

To avoid creating new items unnecessarily, we could have it on an antline router (started disabled, perhaps?), then we could have "Start Reversed" to control whether the checkmark box is checked already or not, and maybe "Auto-drop first cube" to push it 1/4th of a block in, so along with the light strip positioning gizmo, we could position them anywhere on a single tile.

![image](https://cloud.githubusercontent.com/assets/6296061/24845354/cf9ff418-1d87-11e7-88cb-281ae8d1f680.png)

**Comment by hop193** [comment]
Not a bad idea! I like it.

**Comment by Endermage77** [comment]
I think I'd like a single checkmark box as a separate item, though.

**Comment by TeamSpen210** [comment]
That is taken care of by this, since you can just connect 1 thing to it (and maybe a dummy AND gate to force the checkmark to appear).

**Comment by HugoBDesigner** [comment]
Actually, this can already be done with an antline magnet plus antline routers.
