### ISSUE TITLE
Antline Router Improvement

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1835]
Maybe it's possible to add something to the Antline Router so when there is a connection to it (and it's selected antline) there is an option to have the antline itself disappear, but the X / Checkmark symbol is still there.
Example:
![20170410162002_1](https://cloud.githubusercontent.com/assets/25728252/24880778/9fb7d338-1e09-11e7-85e0-e83f8992457f.jpg)

**Comment by TeamSpen210** [comment]
This is indeed possible.

**Comment by HugoBDesigner** [comment]
Isn't this basically what I just suggested on issue #1833 ?

**Comment by TeamSpen210** [comment]
I'd say so.
