### ISSUE TITLE
Need help at performing a "Special config" for the "Wall Pillars" of the Reclined Fizzlers

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1836]
This screenshot explains what i mean:

![20170410213332_1](https://cloud.githubusercontent.com/assets/12244376/24888101/442aa5f8-1e37-11e7-8240-49312e8ff4f4.jpg)

**Comment by TeamSpen210** [comment]
Have a look at the configs for something like [monitors](https://github.com/BEEmod/BEE2-items/blob/dev/packages/monitors/items/monitor_clean.cfg#L53). We have a `PosIsSolid` config, which can either be used to check if a wall face is a some position, or determine the color of it (which is what we're doing here). You won't want `RemoveBrush`, but set the origin appropriately. Then as you can see set `colorVar` on in the template to the variable it sets, and it'll be recoloured to match. If there isn't a brush there it should probably keep the colour in the item, which you'd want to be black. So you'll need one template for each half.

**Comment by LautaroL20** [comment]
For some reason, the templates does not appear in-game, so probably i did something wrong in the config file, can you see someting that was set wrong in it? Here is the full config:

```
"Conditions" 
	{
	"Condition"
		{
		"instance"	"<ITEM_LAUTARO_RECLINED_FIZZLER>"		
		"Condition"
			{
			"Instvar"   "connectioncount = 0"
			"Result"
				{
				"suffix" "static"
				}
			}

		"Condition"
			{
			"posIsSolid"
				{
				"Pos"			"-128 -128 0"
				}
			"posIsSolid"
				{
				"Pos"			"128 128 0"
				}
			"Result"
				{
				"TemplateBrush"
					{
					"ID"        "LAUTARO_RECLINED_WALL_PILLAR_ONE_CLEAN"
					"colorVar"  "$color"
						}
					}
				}	

		"Condition"
			{
			"posIsSolid"
				{
				"Pos"			"-128 -128 0"
				}
			"posIsSolid"
				{
				"Pos"			"128 128 0"
				}
			"Result"
				{
				"TemplateBrush"
					{
					"ID"        "LAUTARO_RECLINED_WALL_PILLAR_TWO_CLEAN"
					"colorVar"  "$color"			
						}
					}
                }					
				
	"Condition"
		{
		"instance"	"<ITEM_LAUTARO_RECLINED_FIZZLER>"
		"Result"
			{
			"Pack" "CLEAN_OVER_RESCALED_FIZZLER"
			}
		}
	}
}	
```		

![20170411002130_1](https://cloud.githubusercontent.com/assets/12244376/24891665/ac54b8c4-1e4d-11e7-9203-524fa4e52414.jpg)

**Comment by LautaroL20** [comment]
Well, i fixed the template brush not appearing in game, still need to make it to change its colour so ill see if i can take the monitor´s example.

**Comment by TeamSpen210** [comment]
What you need to do is actually define the `$color` fixup value. That's what the `setVar` option does in `posIsSolid`, it sets it to either `"black"` or `"white"` depending on the tile colour. So you want two variables, one for each template.
