### ISSUE TITLE
Issues with 80s Old Aperture

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1838]
Lautaro and I found some issues in 80s Old Aperture.
- [x] Entry Corridor 2 spawns a 'mysterious' portal gun.
- [x] Entry Corridor 3 causes a leak.
- [x] Entry Corridor 4 door will not open.
- [x] Entry Corridor 5 causes a leak in other player's maps.
- [x] Cubes do not have proper gel coating textures. Speed Gel causes the ring to turn yellow.
- [x] Lone Companion Cubes spawn as spheres.
- [x] CSFI crashes the compiler.

**Comment by Endermage77** [comment]
Say, is the goo leak fixed yet?

**Comment by Konclan** [comment]
Thats a whole lot of tag...
