### ISSUE TITLE
An error ocurred while updating Portal 2 (Content file locked) 

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1839]
Yes, I know, this is sorta off topic, but after the update (4/11/2017), the game has an error upon launch:

![o no](https://cloud.githubusercontent.com/assets/25728252/24936424/2d30d2f8-1ef7-11e7-8e2e-21b3544b51fc.PNG)

I go into the bin file (before the lost file) and I get this error:

![o no o no](https://cloud.githubusercontent.com/assets/25728252/24936441/5e1bb0d6-1ef7-11e7-923c-dd472b58567e.PNG)

Any help? Because help is strongly appreciated. Thanks!

**Comment by ZombiePwner1** [comment]
Have you verified the game files? There is a known issue where bee2 can lock up the game files but i can't remember what causes it.

**Comment by TeamSpen210** [comment]
Right click, go to properties and check the security tab.

**Comment by hop193** [comment]
On what? The client.dll file? If I open the bin folder, the error message appears.

**Comment by hop193** [comment]
> Have you verified the game files? There is a known issue where bee2 can lock up the game files but i can't remember what causes it.

I'm sorry, I'm not very good with this, but how do you verify the game files? (I'm sorry)

**Comment by TeamSpen210** [comment]
On the bin folder.

**Comment by hop193** [comment]
Update: After some Steam Chatting with @ZombiePwner1, I was able to load up the game. The loading screen (which shows P-Body jumping into a portal with Atlas in the background) appeared, and the antline loading bar was filling up slowly. After about 5 minutes, it's just stuck there. Help?

**Comment by Luke18033** [comment]
Quit the game using the task manager, and relaunch it.

**Comment by hop193** [comment]
Got it, exported items in, and guess what? When I loaded the editor, I saw the untextured....texture. (The one with pink and black tiles) and when I placed the item in, the blue "ERROR" text appears. What did I d wrong now?

**Comment by Luke18033** [comment]
A few people have reported this same issue on Discord, and it seems to be a problem with the latest update to Windows.

**Comment by hop193** [comment]
Ugh.

**Comment by TeamSpen210** [comment]
Actually, check task manager for a `igfxEM` process, and try killing that. It's a program by Intel which decides it's a good idea to lock down access to any steam apps, so it messes with lots of things.

**Comment by hop193** [comment]
OK, I'll try that in a bit.

**Comment by hop193** [comment]
Tried it, didn't work :(

**Comment by hop193** [comment]
I got it to work, Re-Installed BEE2.
