### ISSUE TITLE
Allow Half / Center  / Cross Walls to work on Angled Panels

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#1840]
Placing a centered half wall on an angled panel doesn't change the panel and leaves the half wall

![20170414081113_1](https://cloud.githubusercontent.com/assets/16567080/25044085/2acb81f8-20ea-11e7-97d2-5f15cc85f49e.jpg)

**Comment by awesomedoctorx3** [comment]
this should be applied to flat half blocks as well.

**Comment by LautaroL20** [comment]
Fixed title.
