### ISSUE TITLE
Add signage key to description

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#1841]
![capture](https://cloud.githubusercontent.com/assets/16567080/25057270/e988ce54-2133-11e7-9bfa-4bb831ae5334.PNG)
![capture2](https://cloud.githubusercontent.com/assets/16567080/25057271/e998c070-2133-11e7-91b2-5f57ecb899d1.PNG)
And also maybe do this for the Cube Colorizer

**Comment by hop193** [comment]
Yes! I need this.

**Comment by TeamSpen210** [comment]
A bit of a rewrite, but this works now.
![image](https://user-images.githubusercontent.com/8453732/31867732-b3cb6fa2-b7d7-11e7-9958-16424eda653d.png)

**Comment by LautaroL20** [comment]
Congratulations.
