### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by benjaminpants** [BEEmod/BEE2-items#1842]
When I try to compile it does not work! :(
Yes I have started the editor before and I did run the style changer
Here is the dev log

> VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 4
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "item_bee2_fizzler_out_relay" not a valid item!
[INFO] cond.core.res_goo_debris(): GooDebris: 0/0 locations
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: FORCE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3591, misses=342, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'restartonexit': True, 'fixfizzlerbump': False, 'multiversecave': True, 'funnelallowswitchedlights': False, 'overfunnelflicker': True, 'bee_show_trigger': False, 'allowgoomist': True, 'bee2_goo_debris': True, 'nomidvoices': False, 'unlockdefault': False, 'rexcubepelletfizzle': False}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/over/global_ents.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_3.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/base.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/triple_wallpipe_nocull.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/catwalk_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/triple_wallpipe_nocull_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/triple_wallpipe_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/truss_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_a_overgrown.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_a_overgrown.vtf"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_a_overgrown_off.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_a_overgrown_off.vtf"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_aoff.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_b_overgrown.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_b_overgrown.vtf
 |_\"\" \"materials/models/elevator/elevator_main_aoff.vtf"

[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_b_overgrown_off.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_boff.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_c_overgrown.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_c_overgrown.vtf"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_c_overgrown_off.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_coff.vmt"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_stair_128.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_32b.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_end_cap.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_overgrown/truss_1024.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_overgrown/truss_512.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/triple_wallpipe/entrance_a.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/triple_wallpipe/straight_a.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/triple_wallpipe/straight_c.mdl"
[INFO] vbsp.make_packlist(): "models/elevator/elevator_b_skins.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_specific.nut"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/screens/elevator_video_overlay3.vmt" as "materials/BEE2/overgrown/lightboard_overlay.vmt"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): 
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
[

**Comment by Konclan** [comment]
What style are you using?

**Comment by ZombiePwner1** [comment]
There is a leak somewhere in your map.

**Comment by LautaroL20** [comment]
> There is a leak somewhere in your map.

Not sure, i think in Puzzlemaker you can compile even if there is a small leak somewhere. This is why you can see sometimes the Goo being leaked since it allows compiling leaked maps.

**Comment by benjaminpants** [comment]
I am using the overgrown style.
But I think it might be the items that are causing errors.

**Comment by benjaminpants** [comment]
Also ZombiePwner1 that is for HAMMER maps not PTI maps!

**Comment by Konclan** [comment]
Check if you have any observation rooms on the ceiling

**Comment by LautaroL20** [comment]
@benjaminpants - Did you have the Protruding Pedestal Buttons somewhere in your map?

**Comment by Luke18033** [comment]
> and I did run the style changer

Are you using BEE2.2?

**Comment by Endermage77** [comment]
Maybe he tried putting observation rooms on the floor or ceiling?

**Comment by LautaroL20** [comment]
I will going to use someone´s phrase: "As usual with these issues, no response from the author, ill gonna close this until we get a response."

And by the way, if this is a Bee2.2.5 thing related issue, we can no longer helps you since that version is totally abandoned a long time ago.
