### ISSUE TITLE
"start enabled" on laser catchers and laser nodes

### ISSUE THREAD

**Issue by awesomedoctorx3** [BEEmod/BEE2-items#1843]
Have the option that laser catchers and nodes can be checked to "start enabled" and need a laser to turn them off.

**Comment by ZombiePwner1** [comment]
i don't think this would be possible.

**Comment by TeamSpen210** [comment]
That's doable with a not gate.

**Comment by awesomedoctorx3** [comment]
True, but it would be easier for the player to understand what they're doing if it was, say, already spinning?

**Comment by TeamSpen210** [comment]
Not really, it'd still do the normal behaviour.
