### ISSUE TITLE
Glitch with Bounce Gel

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1844]
When you bounce on bounce gel, you know, the usual, you bounce. But, something interesting is when bouncing on this type of gel a second time (after landing on it from the first bounce) you bounce slightly higher. Now, this may not seem _that_ bad, but when you realize you can't bounce 2 blocks high until the second jump can be annoying. This was a glitch in the original PeTi, and I wonder if it was possible to fix.

**Comment by Konclan** [comment]
This is a game mechanic and cannot be fixed

**Comment by TeamSpen210** [comment]
You're supposed to do that, it's intended.

**Comment by hop193** [comment]
> You're supposed to do that, it's intended.

Really? Weird.
