### ISSUE TITLE
What will be in the future with the abyss

### ISSUE THREAD

**Issue by ILIA2001** [BEEmod/BEE2-items#1849]

**Comment by Luke18033** [comment]
\>:(

**Comment by Luke18033** [comment]
Please ask questions on [Discord](https://discord.gg/mZ4peDd).

**Comment by TheDarkBomber** [comment]
So they can't open question issues?

**Comment by HugoBDesigner** [comment]
I personally think generic questions like these could go there instead. Like "when will it be released?"

**Comment by Luke18033** [comment]
Additionally on Discord you can pin messages, so we don't have to worry about questions being lost as new messages are posted.
