### ISSUE TITLE
Turret Defect Detector

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1850]
I imagine that, at some point, there will be more kinds of turret than the standard, particularly the defective turret.
This item would work somewhat like the detector seen in chapter 5 of the campaign, in that there will be a master turret on a turret detector, and another turret detector that is also linked to the item.
The defect detector will output A and B outputs, A for if the test turret matches the master turret, and B for if it doesn't.
In terms of creating the defect detector in PTI, It could work something like this:
1. Have turret detector
2. Connect turret detector to this item
3. Connect this item to second turret detector

The first detector will be the base that detects the master turret.
This also implies that one could supposedly switch out the master turret as done in the campaign.

However, since neither of those currently exist, there is no rush.

**Comment by Endermage77** [comment]
Proposal Revised.

**Comment by iEnderMan06** [comment]
meh, Since this can be done with lasers, no real need anyway,

**Comment by Endermage77** [comment]
Eh? What? Lasers?

Elaborate on how lasers can be used to construct a turret defect detector.

**Comment by awesomedoctorx3** [comment]
what purpose would this item serve?

**Comment by TeamSpen210** [comment]
Indeed, I don't know why you'd want to specifically detect defective turrets. I'm not sure if I'd want to add those anyway - they don't really do anything, have some technical issues as a free-form item, and would be confusing in Old Aperture (where skeleton turrets are already used).

**Comment by Endermage77** [comment]
Well, the idea would be that it would be able to take any kind of turret to take as master turret and detected turret (eg. detecting a super-turret against a defective turret.) It's basically an advanced turret detector of sorts.

**Comment by iEnderMan06** [comment]
@Endermage77 I mean it like, We don't need it to be turrets, If you want it, make your maps in hammer,

**Comment by IceTudor** [comment]
What if, instead of doing that, it'd just be a conveyor belt with a launchpad on it? so that anything that isn't the master template gets thrown away. Not a turret necessarily, just an item.

**Comment by Endermage77** [comment]
The second detector could have A/B outputs, A for a match and B for a not match.
Then you could deal with defects however you like.
