### ISSUE TITLE
Portal Resetting Fizzler

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1851]
Simple: Resets portals upon walking through, but you can shoot portals through it.

**Comment by HugoBDesigner** [comment]
If I'm not mistaken, it's not possible to have portal cleansing without portal blocking.

**Comment by hop193** [comment]
Oh, that sucks. :(

**Comment by HugoBDesigner** [comment]
It is possible to clear portals through a command, but I dunno how that could be implemented efficiently into the game. I'll have to wait for someone with more knowledge (probably @TeamSpen210 ) to answer this one for you.

**Comment by hop193** [comment]
OK.


@TeamSpen210 @Luke18033 @ZombiePwner1

**Comment by iEnderMan06** [comment]
@hop193 Using a setup. I could get that working!

**Comment by Konclan** [comment]
What you could do is have a trigger that turns on the fizzler when a player touches it

**Comment by TeamSpen210** [comment]
This was implemented in the form of the Absolute Fizzler.

**Comment by Endermage77** [comment]
I don't think it was the Absolute Fizzler that did this. It was one of the other fizzlers, I believe.
