### ISSUE TITLE
Laserfield models pack as mysterious blue error

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1855]
![20170416182601_1](https://cloud.githubusercontent.com/assets/18079316/25070497/a85ea7be-22d2-11e7-9fd4-963105454b43.jpg)

**Comment by LautaroL20** [comment]
LOL

**Comment by TeamSpen210** [comment]
It mustn't be getting custom models.

**Comment by LautaroL20** [comment]
I have fixed this for next release.
