### ISSUE TITLE
Overgrown TWTM faithplates signages pack as mysterious white textures.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1856]
![20170416182703_1](https://cloud.githubusercontent.com/assets/18079316/25070500/cca7d03c-22d2-11e7-90fc-adf7e18bc045.jpg)

**Comment by Konclan** [comment]
♫♫ Please stop using the word mysterious to describe everything ♫♫

**Comment by Luke18033** [comment]
TWTM isn't supported yet.

**Comment by ZombiePwner1** [comment]
@Konclan I just like using that word because it's funny.

**Comment by Luke18033** [comment]
This is still an issue, it'll need to be fixed when we add TWTM support. Convert that issue to an Epic, and add this to it.

**Comment by Luke18033** [comment]
Adding TWTM support will probably fix this, if it still happens to begin with.
