### ISSUE TITLE
Overgrown cube droppers cubes get stuck in the dropper in a mysterious way.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1857]
![20170416201106_1](https://cloud.githubusercontent.com/assets/18079316/25071080/10851d9c-22e1-11e7-9793-f13d7af633d7.jpg)

**Comment by Konclan** [comment]
♫♫ she moves in mysterious ways ♫♫

**Comment by LautaroL20** [comment]
> Konclan: "♫♫ she moves in mysterious ways ♫♫"

Lol, whats the name of that song?

**Comment by Konclan** [comment]
U2 - Mysterious Ways

**Comment by Konclan** [comment]
Is this fixed?

**Comment by LautaroL20** [comment]
Hope so, we should give it a test with the PRL27 tho...

**Comment by Luke18033** [comment]
Should now be fixed
