### ISSUE TITLE
Idea for BTS coop spawn room.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1863]
It could be in a little BTS area with disassemble machines building the robots since there is a reversed animation for the disassembler animation.

**Comment by TeamSpen210** [comment]
I decided there's a bit of an issue with this. I reckon it'd take too much time for the players to respawn like that, it'd get rather annoying to watch the animation over and over. Instead I'm doing a spawn room similar to the first BTS Coop map - you drop a long distance in vactubes, then fall out into a room. After the first time you drop, you instead spawn just above the ceiling so it doesn't take long to respawn.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Well since you've made the coop spawn room BTS variant now this should have implemented label.

**Comment by Luke18033** [comment]
For the exit, you could have a room with a projector screen where GLaDOS says the end-of-course lines and then Atlas and P-body explode.

**Comment by ZombiePwner1** [comment]
@Luke18033 Good idea!

**Comment by ZombiePwner1** [comment]
@Luke18033 But it should depend wether if you have GLaDOS lines enabled.
