### ISSUE TITLE
The Cold Square Light from Old Aperture is not emmiting cold lighting

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1865]
![20170418064022_1](https://cloud.githubusercontent.com/assets/12244376/25124463/2d030796-2402-11e7-893a-76fb6f06a914.jpg)

**Comment by TeamSpen210** [comment]
That was fast.

**Comment by LautaroL20** [comment]
Well, considering i am making my Retro models for the Protruding Buttons, i decided to give a try to your Retro Lights.

**Comment by Luke18033** [comment]
#3828 would seem to indicate that this is fixed

**Comment by LautaroL20** [comment]
Yes, this is most likely fixed now. BTW that issue was actually a duplicate of this but nobody noticed it.

**Comment by Luke18033** [comment]
Oh that makes sense, you must not have tried using neutral lights when you opened this issue
