### ISSUE TITLE
The 50´s Retro Entrance Door´s selection mesh is not having a "Culling Backward" on its hole

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1867]
![20170418104931_1](https://cloud.githubusercontent.com/assets/12244376/25134067/fd74426a-2424-11e7-8d3a-0be7c0cd5f46.jpg)

**Comment by Luke18033** [comment]
If you look closely, you'll see that it's actually open on the outside but closed on the inside. That doesn't make much sense though, and should definitely be changed.

**Comment by TeamSpen210** [comment]
The original model does that too.

**Comment by Luke18033** [comment]
Also, I see that you've made Old Aperture protruding button models.

**Comment by Luke18033** [comment]
Oh really, it does?

**Comment by LautaroL20** [comment]
Yes, yesterday ive finish them, but now i have to perform their "Selection Meshes" which should be easier i guess. Anyways here are them fully textured:
![Image](https://cloud.githubusercontent.com/assets/12244376/25166262/dcbec4fa-24b0-11e7-9e3b-510beadbe967.jpg)
