### ISSUE TITLE
Missing Corridors

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1868]
Several of the entry/exit corridors are missing, using Clean versions or duplicates of other corridors. These are:

BTS:
- [ ] SP Entry 5
- [ ] SP Entry 6
- [ ] SP Entry 7
- [ ] SP Exit 2
- [ ] SP Exit 3
- [ ] SP Exit 4
- [ ] Co-op Entrance Room
- [ ] All Co-op Exits

Portal 1:
- [ ] SP Entry 2 (I am developing this)
- [ ] SP Entry 3
- [ ] SP Entry 4
- [ ] SP Entry 5
- [ ] SP Entry 6

This issue is simply a checklist of the corridors that need to be done - most of you are already aware that these are missing.

**Comment by ZombiePwner1** [comment]
I would like to make the BTS coop entrance room but i need plans on how it should look since my idea is basically 2 disassemble machines using a reversed animation that builds the robots instead of disassembling them.

**Comment by TeamSpen210** [comment]
See #530.

**Comment by Luke18033** [comment]
That's kind of different, it's about improving the existing corridors, not adding the missing ones.

**Comment by TeamSpen210** [comment]
Well remaking those chambers.
