### ISSUE TITLE
Use the "Button Type" property to select variations of the "Gridded Wall" item.

### ISSUE THREAD

**Issue by the8bitMoon** [BEEmod/BEE2-items#1871]
This would add possibilities to the editor, allowing for improved aesthetics in test chambers, especially in Original Clean style.

For instance:
- "Weighted" is the currently implemented "Gridded" 4x4 surface.
- "Cube" creates a 2x2 "cross" panel.
- "Sphere" creates either a single large white panel, or a 2x1 black panel.

![griddedwallenhancement](https://cloud.githubusercontent.com/assets/27790800/25206944/c8f6610a-2530-11e7-85c8-d0df84bee6a1.jpg)

**Comment by TeamSpen210** [comment]
This will conflict with another feature I'm somewhat working on.

**Comment by the8bitMoon** [comment]
What is the new feature, if you don't mind? There might be a way to make them both work

**Comment by TeamSpen210** [comment]
Based on the position of items and portal surfaces, tiles get the correct patterns generated automatically.

**Comment by the8bitMoon** [comment]
I don't think that it would necessarily conflict with automatically generating patterns, since it would just allow for a simple manual tweak.

**Comment by Luke18033** [comment]
Indeed, the point of the Gridded Wall is to override the normal surface texture.

**Comment by TeamSpen210** [comment]
Well the problem is that generates patterns everywhere, and would need to handle this too. I'm possibly going to remove the Gridded Wall once that's implemented, since then all items can generate 4x4 walls whenever they're needed.

**Comment by LautaroL20** [comment]
> TeamSpen210 said: "I'm possibly going to remove the Gridded Wall once that's implemented, since then all items can generate 4x4 walls whenever they're needed."

Instead, add an output in the item, so it generates gridded surfaces when intersecting the Flats and Partial Blocks, and Thin Walls too, unless there is another compiler way to make these intersected items to generate it.

![IMAGE](https://cloud.githubusercontent.com/assets/12244376/25391522/cfbd4000-29ac-11e7-8226-00d7b6fd2a86.jpg)

**Comment by TeamSpen210** [comment]
That's very difficult to do, and actually the gridded wall item and the condition for it won't work for those blocks.

**Comment by Konclan** [comment]
What if they always have a gridded wall?

**Comment by TeamSpen210** [comment]
Well then you can't use them to say make an offset corridor, without it looking really weird.

**Comment by Konclan** [comment]
Yeah I know, It was a stupid idea :P
