### ISSUE TITLE
Coop overgrown.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1873]
This style takes place in the course 3 test chambers in portal 2's coop campaign. Very low levels of vegetation mainly just plain overgrown levels without vegetation or very little vegetation.

**Comment by TeamSpen210** [comment]
That's Reconstructing then,

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Not exactly. this style doesn't have any reconstructing panels and such.

**Comment by Endermage77** [comment]
We could just write this off as a "More/Less Vegetation" stylevar for overgrown.

**Comment by ZombiePwner1** [comment]
Technically it'd be less vegetation since these overgrown coop chambers take place in ruined chambers but there are hardly any plants.

**Comment by Luke18033** [comment]
BEE2 Overgrown hardly has any plants to begin with. See #414.

**Comment by Nikita74RU** [comment]
Just use Overgrown style, with coop chamber.
