### ISSUE TITLE
The BTS CO-OP Compiling Process now becomes "Stagnant Forever" and sometimes frozen - Task Manager becomes your best friend

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1875]
![image](https://cloud.githubusercontent.com/assets/12244376/25228662/a48faa88-25a3-11e7-8ea3-9322b31ff5f9.png)

**Comment by LautaroL20** [comment]
*Task Manager.....My english logic became a bit mixed up.

**Comment by Luke18033** [comment]
You know there's a cancel button?

**Comment by LautaroL20** [comment]
You know you can´t do anything when it becomes also froozen.

**Comment by hop193** [comment]
froozen? Not trying to be rude, but I think it's frozen.

**Comment by LautaroL20** [comment]
Thats correct.
