### ISSUE TITLE
BTS Timer Indicator Panel doesn't appear

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1876]
**Suggestion:** Make it a **"Flicker Green Light"** when a Timerized Pedestal Button is pushed, so this prevents confusions.

![20170421075946_1](https://cloud.githubusercontent.com/assets/12244376/25274964/38881b88-2669-11e7-8547-e23ed19d93ea.jpg)

**Comment by TeamSpen210** [comment]
It's actually a bug, the timer does something entirely different. It actually should turn green and then gradually fade out, with only one light. But the compiler seems to be inserting the wrong instance.

**Comment by hop193** [comment]
Meh, not surprised. BTS is _heavily_ unfinished, and _should_ be finished in BEE2.4.1

**Comment by TeamSpen210** [comment]
Actually, it's got one, I broke the compiler so it was making all indicator panels checkmark ones. So you couldn't have timer ones anywhere.
