### ISSUE TITLE
Some Utilities items

### ISSUE THREAD

**Issue by XdplayerdX** [BEEmod/BEE2-items#1877]
1 - Non-Collidable Items :
It's normal items,but don't collide with other items in the edit mod:
![20170421145147_1](https://cloud.githubusercontent.com/assets/25773302/25290032/8bc6c252-26a2-11e7-9965-04bc9cb9ad91.jpg)
![20170421145314_1](https://cloud.githubusercontent.com/assets/25773302/25290033/8bd136ec-26a2-11e7-9ab4-3b46fd8bdfc8.jpg)
![20170421145319_1](https://cloud.githubusercontent.com/assets/25773302/25290034/8bd59ea8-26a2-11e7-89a4-1973ebd29413.jpg)
![20170421145331_1](https://cloud.githubusercontent.com/assets/25773302/25290035/8be6168e-26a2-11e7-8733-7c0eb42fafd3.jpg)
![20170421145123_1](https://cloud.githubusercontent.com/assets/25773302/25290036/8beb3fc4-26a2-11e7-82ab-c656a5078201.jpg)
![20170421145138_1](https://cloud.githubusercontent.com/assets/25773302/25290038/8c83189e-26a2-11e7-84f6-868f028a279c.jpg)

2- Double Items:
Normal Items,but have something doubled.Examples:

Double Piston plataform:
The same,but can ben extended more than the normal piston plataform.

Double Panel:
The same,but the size is of 2 blocks(if you want,you can make a option to define the size 
of  0.5>5 blocks).

3- More Decorative blocks:
Blocks like the windows,flat blocks,half walls.Examples:

Hollow Wall:
Like a Midle window,but don't have the glass.

Esposed Frame/wall:
An wall non-portable with esposed textures,find this in BTS/Undergound.It's like cutout tile,but
can placed in any place and have more textures and models options.

Air Duct:
A block at the exact size of the crounched player,see in half life/half life 2.

4-Adhesion Gel:
A gel that can placed in any place and make the player walk in any place.

![](http://media.moddb.com/cache/images/mods/1/18/17911/thumb_620x2000/Attraction_Gel.png)
https://youtu.be/taN5-hNaAuk

**Comment by TeamSpen210** [comment]
We can't implement 1 or 4. For 2, those really need to be decided one at a time. 'Air Duct' can be made with some 1/4 walls or flat blocks. The other two would be implemented in a different way.

**Comment by ZombiePwner1** [comment]
@XdplayerdX As for adhesion gel that cannot be implemented due to limitations of the puzzlemaker.

**Comment by XdplayerdX** [comment]
So Can add the shredder of the old beemod ?

**Comment by ZombiePwner1** [comment]
@XdplayerdX All of the old items from the original beemod will be re-implemented.

**Comment by hop193** [comment]
@ZombiePwner1 said:

> All of the old items from the original beemod will be re-implemented.
