### ISSUE TITLE
Some stripes from Template Brush doesn´t rotate

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1878]
![20170422171148_1](https://cloud.githubusercontent.com/assets/12244376/25307924/382c6136-2780-11e7-9b07-435d59d367e2.jpg)

**Comment by TeamSpen210** [comment]
My code currently doesn't have the ability to rotate the diagonal faces.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to add the "invalid" label.
