### ISSUE TITLE
Overgrown coop checkpoint's debris are floating in a mysterious way.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1880]
![20170423202212_1](https://cloud.githubusercontent.com/assets/18079316/25313522/98cbbc98-2862-11e7-902a-00c9d04a1db1.jpg)

**Comment by TeamSpen210** [comment]
Wow, these are floating high up.

**Comment by LautaroL20** [comment]
> TeamSpen210 Said: "Wow, these are floating high up."

*Insert the X Files Theme song here*
