### ISSUE TITLE
Mini bug with the Bee2 app

### ISSUE THREAD

**Issue by FyreDemon405** [BEEmod/BEE2-items#1883]
Not sure whether this is the highest priority on the list but it makes it LITERALLY UNUSEABLE.
you can scroll the item choser thing while exporting
LITERALLY UNPLAYABLE.

**Comment by LautaroL20** [comment]
Can you actually explain the issue in a more clear way? Not sure if i understand well, but it is not possible to do anything while you´re exporting, and there is no way the beemod´s developer can do anything about it since its to do with the "Python architecture".
