### ISSUE TITLE
Add this fix to the Grating / Glass Item for when it´s attached on walls and its facing up on Floor / Ceilling Surfaces

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1884]
![Image](https://cloud.githubusercontent.com/assets/12244376/25383369/30f864fa-2992-11e7-9c76-67dfecadb8d5.png)

________________________________________________________________________________

# This fix could also be adchieved alongside this: https://github.com/BEEmod/BEE2-items/issues/1825
# And all of these suggestions would definitelly fix: https://github.com/BEEmod/BEE2-items/issues/1794

**Comment by ZombiePwner1** [comment]
@LautaroL20 Definitely a good possible fix. Also i left a message for u on steam.

**Comment by LautaroL20** [comment]
This issue is totally assigned to TeamSpen210.

**Comment by LautaroL20** [comment]
YAY!
