### ISSUE TITLE
Overgrown Laserfield´s frames gets packed as "Mysterious Blue Errors" when its resized.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1887]
![Image](https://cloud.githubusercontent.com/assets/12244376/25591468/08da4378-2e8b-11e7-8529-199d3b01165a.jpg)

**Comment by ZombiePwner1** [comment]
HAHA LOL

**Comment by LautaroL20** [comment]
![Image](https://cloud.githubusercontent.com/assets/12244376/25591483/1c505212-2e8b-11e7-9338-4860cc1ebbdc.jpg)

**Comment by LautaroL20** [comment]
This issue now happens everytime its rezised:
![20170501161640_1](https://cloud.githubusercontent.com/assets/12244376/25591527/525b48bc-2e8b-11e7-950a-61246d67691c.jpg)

**Comment by LautaroL20** [comment]
Now fixed. However, the laserfield model looks darker than normal, ill see if i can make it look not too dark.

**Comment by ZombiePwner1** [comment]
This is actually sort of a duplicate of https://github.com/BEEmod/BEE2-items/issues/1855

**Comment by LautaroL20** [comment]
No wheels, thats about another unfinished game, this is beemod running on Portal 2.

**Comment by ZombiePwner1** [comment]
@LautaroL20 It's still on portal 2 wheels.
