### ISSUE TITLE
The Arms from the Overgrown 90° Angled Panel are overlapping in a "Mysterious Way"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1889]
![GIF](https://cloud.githubusercontent.com/assets/12244376/25395215/b809bb00-29b6-11e7-9aab-c036e943d823.gif)

**Comment by ZombiePwner1** [comment]
@LautaroL20 It's called texture overlaps you wheely. Obviously there is a small overlap.

**Comment by TeamSpen210** [comment]
There must be two models overlapping.

**Comment by Konclan** [comment]
This looks fixed

**Comment by Luke18033** [comment]
Probably fixed now
