### ISSUE TITLE
implement MovementHandle item var for all lightstrip / fizzler like items

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#189]
all fizzlers movement handle should be set to...

`"MovementHandle"        "HANDLE_8_POSITIONS"`

instead of 

`"MovementHandle"        "HANDLE_6_POSITIONS"`

also they need the 4x4 texture override like the lightstrip

doesn't that look better in game...

also there needs to be a way so when their first placed in PTI before being repositioned their not placed dead center on the voxel and instead placed in one of the positions a lightstrip is first placed...

![preview0140](https://cloud.githubusercontent.com/assets/11165643/11768508/67b1480a-a19d-11e5-83a3-e41ddb8d8b10.jpg)

**Comment by ellingtonvengaboysmuseum** [comment]
i will release a fix for this when i release my custom fizzlers - case closed

**Comment by EllingtonElectrician** [comment]
there should be a style var to choose between 

`"MovementHandle" "HANDLE_8_POSITIONS"`

and 

`"MovementHandle" "HANDLE_6_POSITIONS"`

for all fizzlers. Case Reopened since someone else will have to code this.

**Comment by Luke18033** [comment]
That's what the other issue is already for.
