### ISSUE TITLE
Reclined Fizzler´s Template Brush keeps generating into the wall despite the applied condition

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1892]
![Image](https://cloud.githubusercontent.com/assets/12244376/25459636/944ffc60-2ab5-11e7-8ae0-b2fd935df1d5.jpg)

```
		"Condition"
			{
			"PosIsSolid"
				{
				"Pos" "0 -64 64"  
				"Dir" "0 -1 0" 			
				"Type"   "None"		
				}
			"Result"
				{
    			"TemplateBrush"
					{
					"ID"     "LAUTARO_RECLINED_WALL_PILLAR_CLEAN:top_left"
					}
				}
			}	
````

**Comment by ZombiePwner1** [comment]
@LautaroL20 Didn't you make this item yourself? Plus use a normal fizzler you wheely! >:D

**Comment by Luke18033** [comment]
Still should be fixed, and stop calling each other wheelies please.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - I didn´t create the compiler conditions. I barely know a few funtions. You will never know so much as the author.....

**Comment by LautaroL20** [comment]
@Luke18033 - Also, we both usually use "Wheely" as a friendly type of insult-like, usually via personal Steam Chat. And since we don´t like obsenity words here, we use it from time to time when needed.

**Comment by Luke18033** [comment]
I understand, but you're saying it constantly and it's starting to get annoying.

**Comment by LautaroL20** [comment]
> you're saying it constantly and it's starting to get annoying.

Where? As far as i know the one who is using it constantly is ZombiePwner1.....

**Comment by Luke18033** [comment]
I was more referring to him.

**Comment by Luke18033** [comment]
Also, do the Standing and Reclined Fizzlers properly embed into their brush templates?

**Comment by LautaroL20** [comment]
Yes, i might want to re-scale the Valve´s fizzler again, this time not touching the vertical width. But i will not do it until @TeamSpen210 makes the Brush Template condition to not generate when detects a wall at a position...

**Comment by LautaroL20** [comment]
Now fixed.
