### ISSUE TITLE
Cube issues in 80s style

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1893]
There are a few issues with the Weighted Cube in Oldap 80's style. 
1. Blue-painted cubes turn into Companion Cubes rather than regular cubes with blue paint. Haven't tested orange paint.
2. If you disable the dropper, standard Weighted Cubes turn into Reflection Cubes without any interference. I haven't checked to see if they redirect lasers.

**Comment by TeamSpen210** [comment]
Cubes have been reimplemented from scratch, so this should be fixed.
