### ISSUE TITLE
BTS Suggestions (Not unrealistic like last time)

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2-items#1895]
So I understand, my last list was a "tiny" bit to unreasonable. Now, this is my more reasonable Ideas
(right now I am focusing on BTS!)
- A turret dropper or spawner so you could make a conveyor belt with turrets
- Once Again, a way to make a turret shoot at a specific thing. (like the test dummy) & let you pick if it ALSO shoots you
- I will say the office items are good BECAUSE of the fact you could have to go up into a office to shut something down (I understand if it is still a no.)
- A setting that you can turn on for BTS that has the vactubes carry random items
- Defective turrets (would be good for SOME puzzles)
Now, I would like to say thank you to the people who made BEEMOD, I really wanted to make something custom but I really do not understand HAMMER. Also, uploading hammer projects does not even work for my computer & I have to do a bunch of stuff to upload one.

**Comment by ZFM2004** [comment]
Also, maybe add neurotoxin if you ever get a chance (countdown clock 2 maybe)

**Comment by Luke18033** [comment]
- Already implemented in the next release.
- This could possibly be done.
- Already been suggested I think.
- Just place cubes and stuff in the vactubes, they don't occupy any space in the editor.
- Wouldn't really be useful.

Neurotoxin is already going to be added.

**Comment by snorepion** [comment]
It's really easy to change defective turrets in Hammer. You just have to edit the number for Turret Type in the instance properties, I think you can even make it the Oracle and Prima Donna turrets, IIRC. So just build your map and change the turrets to defective in Hammer.

**Comment by TeamSpen210** [comment]
No you can't. Defective turrets just act like normal turrets, to get them to play voice lines you need to manually trigger those lines.

**Comment by snorepion** [comment]
Oh. Yeah, I hadn't actually tried that, so I didn't know that they played regular lines. I'll just slither away in my own shame now.

**Comment by TeamSpen210** [comment]
So these have been suggested elsewhere.
