### ISSUE TITLE
Something "Mysterious" is happening with the fixed Overgrown Angled Panels when portalling on them

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1900]
![Image](https://cloud.githubusercontent.com/assets/12244376/25557026/15c20218-2cdf-11e7-9652-030ac0b05738.jpg)
![Image](https://cloud.githubusercontent.com/assets/12244376/25557066/b14f429a-2cdf-11e7-9c2e-1c906de4621d.jpg)

**Comment by Luke18033** [comment]
https://www.youtube.com/watch?v=GRWbIoIR04c

**Comment by TeamSpen210** [comment]
That's the model which fixes the collisions. But it should be invisible, whoops.

**Comment by ZombiePwner1** [comment]
@LautaroL20 That is really mysterious. Please insert the x files theme song.

**Comment by Luke18033** [comment]
I already did.

**Comment by Nikita74RU** [comment]
It's a huge antline piece

**Comment by Konclan** [comment]
What are you even commenting on closed issues for!

**Comment by LautaroL20** [comment]
It seems that Nikita74RU not only likes to open useless suggestions, but also leaving useless comments.

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment]
"It's a huge antline piece" is a totally valid, very introspective and important observation that provides further insight into the problem at hand and allows us to look at it through different lenses. Had there not been such a thorough and analytical observation, we might have been stuck in darkness for god knows how long. Thanks Nikita for their amazing effort and the amount of time spent into crafting such a useful response!

**Comment by TeamSpen210** [comment]
In reality, it's not actually a huge antline. It's part of the texture for panel arms.
