### ISSUE TITLE
Deadly goo transforms into walkable, panel-type, very glitchy things in 70's style

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1903]
![See this picture, the character is walking on the panels.](https://cloud.githubusercontent.com/assets/24462989/25637217/7ebde5b6-2f41-11e7-83ba-5aa514af87ee.png)
This picture has the player walking on what's supposed to be deadly goo.
Not pictured are the very weird visibility glitches that occur. When looking continuously at these things, a very bright light source seems to be visible and it expands outward until it fills up the entire goo area. This doesn't occur in my other 70s style test chambers, so I assume it probably has to do with some item I'm using. I have:
- Compressed Smoke Field (as you can see in the photo)
- 1x corner vactubes (but I've used those in all my Old Aperture test chambers and haven't had problems)
- Crusher
- Cube with dropper (present in other tests without problems)
- Catwalks
- Cutout tiles
- Regular floor buttons (present in other tests)
- Conversion gel & dropper (I've had this in other 70s tests without problems)
- Warm light strips
- 1/4 blocks
- Flat 1/4, and 1/2 blocks
- Glass
- Observation rooms, small and large
- Grating
- Corner and angled blocks of all types
- Matter Inquisition Field
- Fizzler
- Cold light strips
- Partial blocks, all types
And, of course, deadly goo. Most of those things I've used before without problems, although I haven't used a Matter Inquisition Field in 70s style and haven't used the corner blocks or cutout tiles before.

**Comment by awesomedoctorx3** [comment]
The issue is with the cutout tiles. They auto generate that panel grid on all of the areas they are placed on and this includes deadly goo.

**Comment by snorepion** [comment]
Ohhh, that makes sense. Thank you!
