### ISSUE TITLE
Rotating portalguns are broken on two walls (directional)

### ISSUE THREAD

**Issue by quat1024** [BEEmod/BEE2-items#1904]
Rotating portalguns on **floors, ceilings, and two walls** rotate as you'd expect.

Rotating portalguns on **the other two walls** rotate vertically, like this: 
![portal2_2017-05-02_18-02-45](https://cloud.githubusercontent.com/assets/2068021/25648509/a90ff0b2-2f9a-11e7-8af5-8e505d737c36.png)

For reference, these portal guns are placed on the six sides of the default chamber, with the camera in the default angle. Guns with X break like the above screenshot.

![image](https://cloud.githubusercontent.com/assets/2068021/25641496/60425218-2f62-11e7-8176-08df6fff6a7f.png)

**Comment by Luke18033** [comment]
[Insert the X Files theme song here]

**Comment by LautaroL20** [comment]
@Luke18033 - Here it is: https://www.youtube.com/watch?v=hAAlDoAtV7Y

**Comment by hop193** [comment]
@LautaroL20  |  You just _love_ the words: "Mysterious Way" don't you?

**Comment by LautaroL20** [comment]
@quat1024 - Not only those.... you missed another words i usually use aswell.

**Comment by TeamSpen210** [comment]
So Y axis is wrong.

**Comment by hop193** [comment]
@LautaroL20 did you just call me @quat1024?

**Comment by LautaroL20** [comment]
@hop193 - Lol, i probably got confused thought you were the post´s author for some reason...

**Comment by hop193** [comment]
Or maybe you clicked on it by accident, lol.

**Comment by TeamSpen210** [comment]
This doesn't appear to happen anymore.
