### ISSUE TITLE
VTF´s extension no longer works in Editoritems - Now they displays as "Mysterious Purple Textures"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1907]
![Image](https://cloud.githubusercontent.com/assets/12244376/25648400/e0748020-2fa1-11e7-9829-f38f581c3822.jpg)

**Comment by ZombiePwner1** [comment]
Lol btw @LautaroL20 its called black and purple checker boards you wheely.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - You don´t say.....Wheels!
