### ISSUE TITLE
"Chamberlocks will also generate an invalid position error even if the volume requirements are satisfied."

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1908]
Originallly posted by @TessilnTheMaskMaker:
(https://github.com/BEEmod/BEE2.4/issues/596)
___________________________________________________________________________________

"Chamberlocks will also generate an invalid position error even if the volume requirements are satisfied."

**Comment by TeamSpen210** [comment]
@TessilnTheMaskMaker, the chamberlock has some special positioning requirements. The editor model I've remade for it will help, but you need to create an empty space on the other side of the wall for the second door to open in. Basically, you need a 1 block thick wall that you place it onto. It'll the punch a hole through it to connect the two sides.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
