### ISSUE TITLE
When Rocket Turret fires, the rockets will be invisible in a "Mysterious Way"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1909]
Originallly posted by @TessilnTheMaskMaker:
(https://github.com/BEEmod/BEE2.4/issues/596)
___________________________________________________________________________________

"When Rocket Turrets fire the rockets will be invisible."

**Comment by Luke18033** [comment]
Placed the instance in a Hammer map, this doesn't seem to be an issue anymore.

**Comment by Luke18033** [comment]
Duplicate of #1238
