### ISSUE TITLE
Light bridge flickers when a angled panel opens

### ISSUE THREAD

**Issue by G3neralGrant** [BEEmod/BEE2-items#1912]
The Light bridge flickers when a angled panel opens and the light bridge is facing it.

**Comment by TeamSpen210** [comment]
That's not a bug, it's intentional/Valve's fault. Whenever a light bridge is enabled or moves, it does the extending effect. But if something is constantly moving in front of it, it keeps re-triggering and you don't see anything. This also happens with funnels.
