### ISSUE TITLE
The P1 Square Warm Light doesn´t lighting anything

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1914]
![Image](https://cloud.githubusercontent.com/assets/12244376/25727023/51b1e4a6-30fd-11e7-8392-990682222c95.jpg)

**Comment by TeamSpen210** [comment]
It's supposed to work like that. You can see the player lit up quite brightly. Lights generally can't light the surface around that corner, it'd make a big shadow. Maybe I should add a dimmer ambient light as well though.

**Comment by LautaroL20** [comment]
> TeamSpen210 said: "It's supposed to work like that."

Nope! Why the Neutral and Cold variants doesn´t beahve like that then? See screenshot:

![Image](https://cloud.githubusercontent.com/assets/12244376/25728023/dde7e696-3102-11e7-9d87-3b9b078bce7a.jpg)

**Comment by TeamSpen210** [comment]
You have walls close to it, so the light is able to reflect back onto the surface.

**Comment by LautaroL20** [comment]
> TeamSpen210 said: "You have walls close to it, so the light is able to reflect back onto the surface."

![Image](https://cloud.githubusercontent.com/assets/12244376/25728580/6ce8d1ea-3106-11e7-8ab8-5b9717e24e6a.jpg)

**Comment by TeamSpen210** [comment]
Ah, it is different then. I'll have to check the clips and brushes, there might be one blocking the light. Or maybe it's coming from the colour at the back of the hole.

**Comment by TeamSpen210** [comment]
This appears fixed.
