### ISSUE TITLE
Allow Static Half Panels to be moved half a block

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1916]
By including a "Start Enabled", we could move the Static Half Panel to the other half of the voxel. That way we could have a platform that stays in the middle of the voxel instead of the edge.

**Comment by TeamSpen210** [comment]
A better way (which allows keeping collisions) would be to turn it around with 'Reversed'.

**Comment by HugoBDesigner** [comment]
Reversed is currently being used to set portalability. Also, if I understand this correctly, that'd make it stand 1/4th blocks from the center, right?

**Comment by TeamSpen210** [comment]
More flip to face the other direction, so it sticks up in the middle of the block. The 'footprint' would be the same.

**Comment by HugoBDesigner** [comment]
Ah, I guess that could work too.

**Comment by ZipZoptheCat** [comment]
Why not just use the handle 8 selector?

**Comment by TeamSpen210** [comment]
Because that doesn't work properly for collisions.
