### ISSUE TITLE
Ability to Rotate the way Faith Plates are Facing using 4-Rotation System

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1917]
Example: A faith plate can be facing forward, but bounces you to the side.
Example: When using any faith plate that throws upwards, you can decide where it faces.

**Comment by snorepion** [comment]
...How would the animations work for that? It would be very ugly.

**Comment by Konclan** [comment]
I feel like that would get very messy very fast

**Comment by TeamSpen210** [comment]
Can't be done unfortunately.

**Comment by hop193** [comment]
> ...How would the animations work for that? It would be very ugly.

> I feel like that would get very messy very fast

Portal 2 Campaign did 

> Can't be done unfortunately.

Oh, OK.
