### ISSUE TITLE
Physics repulsion field editor icon is missing.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1920]
![20170507080742_1](https://cloud.githubusercontent.com/assets/18079316/25776828/60a20594-32fc-11e7-9c63-8ed384173d07.jpg)

**Comment by Luke18033** [comment]
I added this one too...

**Comment by LautaroL20** [comment]
Here´s why: 
![image](https://cloud.githubusercontent.com/assets/12244376/25777695/435b81ae-32bb-11e7-9fba-26b21cb95eaf.png)

**Comment by Luke18033** [comment]
Whoops. Probably around have tested in-game.

**Comment by Luke18033** [comment]
*should
