### ISSUE TITLE
Glass Door Editor model is misplaced

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1921]
![Image](https://cloud.githubusercontent.com/assets/12244376/25777855/c9b6505c-32c1-11e7-95f2-81c9d525e0ca.jpg)

**Comment by LautaroL20** [comment]
Ill fix it.

**Comment by Luke18033** [comment]
That's a bug with the editoritems code, not the model...

**Comment by ZombiePwner1** [comment]
@LautaroL20  @Luke18033 Turns out this is an issue in clean style since the panel is fine in overgrown.

**Comment by LautaroL20** [comment]
Do not offense, but it looks like that Luke18033 needs a pari of glasses...
Model needs also to be fixed, see screenshot:

![Image](https://cloud.githubusercontent.com/assets/12244376/25777021/3bb041b6-32a6-11e7-8003-8add045f6f96.jpg)

**Comment by Luke18033** [comment]
@ZombiePwner1, That would explain why I didn't notice it - I only tested Overgrown, Portal 1, and 1950s, assuming Clean wouldn't have any issues. Turns out I was wrong.

**Comment by Luke18033** [comment]
@LautaroL20, the `EmbeddedVoxels` are misplaced, not the model.

**Comment by LautaroL20** [comment]
The model must be in the half part of the block, not in the middle.

**Comment by Luke18033** [comment]
No it shouldn't, you need to actually use this item before trying to correct this issue...

**Comment by TeamSpen210** [comment]
The model is in the wrong place.

**Comment by LautaroL20** [comment]
Well, glad to know I was not the only one seeing it misplaced. Luke should really get a pair of glasses heheh.

**Comment by hop193** [comment]
I know this is off topic, but @LautaroL20 and @ZombiePwner1, how did you get shadows in your Puzzle Creators?

**Comment by LautaroL20** [comment]
Actually i just reedited the ZombiePwner1´s screenshot in Paint, personally i dont like these shadows. Idk the command he used, you can ask him.

**Comment by LautaroL20** [comment]
Since the selection mesh is alongside the same position as the "Incorrect Voxel Config" i bet the issue here is the model being misplaced, see: ![Image](https://cloud.githubusercontent.com/assets/12244376/25777855/c9b6505c-32c1-11e7-95f2-81c9d525e0ca.jpg)
