### ISSUE TITLE
Force deflection field is completely bugged when start enabled is off.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1923]
![20170507081609_1](https://cloud.githubusercontent.com/assets/18079316/25776871/aa72bc8a-32fd-11e7-955a-0d25e6e8669b.jpg)

The frame will be disabled as it's supposed to.

![20170507081630_1](https://cloud.githubusercontent.com/assets/18079316/25776873/acd872e4-32fd-11e7-9a20-b419e7796671.jpg)

The field itself will still be enabled but lets everything through it.

**Comment by Luke18033** [comment]
Duplicate of #1858.
