### ISSUE TITLE
Physics repulsion field's sparks remain active when the fizzler is deactivated when passing cubes through.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1925]
![20170507082225_1](https://cloud.githubusercontent.com/assets/18079316/25776905/800a42e6-32fe-11e7-8e0b-d456e0daebc3.jpg)

**Comment by Luke18033** [comment]
Those sparks shouldn't be there in the first place, they're annoying and were *not* there in the original.

**Comment by LautaroL20** [comment]
Looks like the sparks got mixed up from the Overgrown Versions

**Comment by Luke18033** [comment]
No, they're supposed to appear when an object touches the field, on all styles. It looks pretty bad though.

**Comment by ZombiePwner1** [comment]
@Luke18033 I find it annoying in all styles except for overgrown since the sparks would make more sense in overgrown.
