### ISSUE TITLE
PRL25 - Overgrown left and right protuding buttons now cause a new compile error.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1927]
src\template_brush.py", line 202, in visgrouped
ValueError: Unknown visgroup "single" for "lautaro_protruding_ped_base_over"! (valid: '', 'double')

**Comment by LautaroL20** [comment]
What the hell..... Why we are getting errors that in the Development Version were fixed a long time ago but in the RL25 that has been released today 07/05/2017 we are experienced past prl-24 bugs??? This literally doesn´t make sense.

**Comment by Konclan** [comment]
Fixed?

**Comment by LautaroL20** [comment]
Yes, this was fixed with the PRL27 and now can be closed.
