### ISSUE TITLE
The puzzlemaker sounds mysteriously keep playing while testing a map.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1931]

**Comment by ZombiePwner1** [comment]
This seems to be a bug specifically with 50's style.

**Comment by spygineer** [comment]
Same happening to me in Portal1 style too for some reason.

**Comment by snorepion** [comment]
Same happening in Clean.

**Comment by Luke18033** [comment]
I don't think this is a BEE2 issue.

**Comment by ZombiePwner1** [comment]
@Luke18033 After one year you decide to close this lmao.
