### ISSUE TITLE
1960´s Old aperture observation rooms editor model is a mysterious blue error.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1932]
![20170507093738_1](https://cloud.githubusercontent.com/assets/18079316/25777209/e69ccab0-3308-11e7-92e3-87084ae2319c.jpg)

**Comment by Luke18033** [comment]
Don't enable the budget bar, it doesn't actually allow you to make full use of the entity limit.

**Comment by ZombiePwner1** [comment]
@Luke18033 I know that i just like having it on.

**Comment by Luke18033** [comment]
PMP will have a proper budget bar which actually shows how close you are to the limit.

**Comment by ZombiePwner1** [comment]
@Luke18033 PMP?

**Comment by ZombiePwner1** [comment]
@Luke18033 What is PMP?

**Comment by Luke18033** [comment]
PuzzleMaker Plus, something which probably will never happen...

**Comment by Luke18033** [comment]
I think this issue might be fixed now.

**Comment by LautaroL20** [comment]
I can confirm that this issue still exists. I am testing PRL33.3 right now.

**Comment by LautaroL20** [comment]
This is fixed now.
