### ISSUE TITLE
Portal 1 drawbridge missing instances

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1933]
| materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/BEE2/p1/items/bee/drawbridge/white_static_down.vmf
 | 
 |_

**Comment by Luke18033** [comment]
Strange, I've used one before without any issues...

**Comment by Luke18033** [comment]
Still an issue, applies to all variants

**Comment by Luke18033** [comment]
It was set to use the 80s config...
