### ISSUE TITLE
Portal 1 grating is missing it's sound.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1934]

**Comment by ZombiePwner1** [comment]
![20170507100334_1](https://cloud.githubusercontent.com/assets/18079316/25777317/797fe33c-330c-11e7-9448-71adc4849357.jpg)

**Comment by ZombiePwner1** [comment]
![20170507100433_1](https://cloud.githubusercontent.com/assets/18079316/25777320/96bc055c-330c-11e7-9358-368d603d7533.jpg)

**Comment by LautaroL20** [comment]
Sound displays fine, try re-adding the gratings again. It may happens from time to time, but this is something that can´t be fixed.
