### ISSUE TITLE
Glass Door Model Editor is misplaced

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1936]
![Image](https://cloud.githubusercontent.com/assets/12244376/25777855/c9b6505c-32c1-11e7-95f2-81c9d525e0ca.jpg)

**Comment by Byzarru** [comment]
And, straight from Discord...
![](https://cdn.discordapp.com/attachments/293435914598744064/310586353438162945/unknown.png)
![](https://cdn.discordapp.com/attachments/293435914598744064/310586161368399872/unknown.png)

**Comment by LautaroL20** [comment]
Selection mesh and voxel configuration is probably fine, whats really misplaced is actually the Model Editor, here´s why:
![Image](https://cloud.githubusercontent.com/assets/12244376/25777855/c9b6505c-32c1-11e7-95f2-81c9d525e0ca.jpg)

**Comment by LautaroL20** [comment]
This now turned out into a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1921
