### ISSUE TITLE
PRL25 - Textures from Overgrown Rusted Pillars are beind displayed as Purple & Black Checkerboards

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1938]
![Image](https://cloud.githubusercontent.com/assets/12244376/25777638/97b719f4-32b9-11e7-985e-7dc81fa7b449.jpg)

**Comment by ZombiePwner1** [comment]
@LautaroL20 The VMT is loaded by the VTF's are missing.

**Comment by TeamSpen210** [comment]
This seems fixed.
