### ISSUE TITLE
Most of new items appear as Purple and Black Tiles

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1940]
![20170507001915_1](https://cloud.githubusercontent.com/assets/25728252/25777891/cf105374-32ba-11e7-8d75-1a367ae90d24.jpg)
Upon placing: Blue "ERROR" words appear.
![20170507002016_1](https://cloud.githubusercontent.com/assets/25728252/25777895/f3f3c3c4-32ba-11e7-8de0-65c1bb564525.jpg)
When I try to rebuild, it gives this message:
![20170507002112_1](https://cloud.githubusercontent.com/assets/25728252/25777901/157b93e6-32bb-11e7-89af-bf2b12fbc4b7.jpg)
Error log:
VBSP failed.

[INFO] cond.core.x(): No name for module "voiceLine"!
[INFO] vbsp.main(): BEE2.4.0p425 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'use_screenshot': '1', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (35 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cond.fizzler.fizzler_out_relay(): Fizzler data: {'marker_inst': [], 'pos_to_name': {}, 'fizz_by_name': {}, 'model': 'instances/bee2/clean/items/tdb/csfi_model.vmf', 'base': 'instances/bee2/clean/items/tdb/csfi_base.vmf', 'fizz_id': 'item_tdb_csfi', 'fizz_bases': {'instances/bee2/clean/items/barrier_hazard_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/paint_fizz/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/csf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/fdf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/mif_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/death_fizz/base.vmf': ItemConnections(in_act=('branch_fizz', 'ToggleTest'), in_deact=('branch_las', 'ToggleTest'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/physler/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/rex/pellet_field_base.vmf': ItemConnections(in_act=(None, ''), in_deact=(None, ''), out_act=('out', 'OnUser2'), out_deact=('out', 'OnUser1')), 'instances/bee2/clean/items/tdb/csfi_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, ''))}, 'fizz_models': {'instances/bee2/clean/items/fr/mif_model.vmf', 'instances/bee2/clean/items/physler/model.vmf', 'instances/bee2/clean/items/rex/pellet_field_model.vmf', 'instances/bee2/clean/items/fr/fdf_model.vmf', 'instances/bee2/clean/items[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: FORCE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 5/15 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "PELLET_1"
 | 	"Choreo"
 | 		{
 | 		"1" "scenes/npc/glados/mp_coop_paint_redirect07.vcd"
 | 		"2" "scenes/npc/glados/mp_coop_paint_redirect08.vcd"
 | 		}
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "EXIT": 2/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "DEADLY_1"
 | 	"Choreo" "scenes/npc/glados/mp_coop_wall_block03.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 1/9 quotes..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.anti_fizz_bump(): Adding Portal Bumpers to fizzlers...
[INFO] vbsp.anti_fizz_bump(): Done!
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'deadly', 'neurotoxin', 'neurotoxinvent', 'turret', 'pellet', 'pelletlauncher', 'glass', 'fizzler', 'physler', 'rexpelletfield', 'tdb_ff', 'neurotoxintimer', 'spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=6906, misses=340, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'blockplayergelbomb': True, 'doorcameras': True, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': True, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[INFO] cond.core.check_all(): Global instances: {'<ITEM_BEE2_NEUROTOXIN_TIMER:bee2_globals>', 'instances/BEE2/clean/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[WARNING] vbsp.make_packlist(): Packlist "<PACK_EXTRA>" does not exist!
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/pellet_sounds.txt"
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/rex_sounds.txt"
[INFO] vbsp.make_packlist(): "File"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/fourthreaper/player_clip_electric.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/phys_shield/clean_pshield_center.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/phys_shield/clean_pshield_left.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/phys_shield/clean_pshield_right.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/phys_shield/physics_shield.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/phys_shield/physler_flow.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/phys_shield/physler_noise.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/phys_shield/physler_ripples_dim.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/thedarkbomber/clean_csfi_center.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/thedarkbomber/clean_csfi_left.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/thedarkbomber/clean_csfi_right.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/thedarkbomber/closed_solid_field.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/glass_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/grate_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/effect.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_danger.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_danger.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty_danger.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty_danger.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/rex/beam_field.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/rex/beam_field_timer.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/rex/beam_field_toggle.vmt"
[INFO] vbsp.make_packlist(): "materials/effects/comball/comball.vtf"
[INFO] vbsp.make_packlist(): "materials/effects/eball_finite_life.vmt"
[INFO] vbsp.make_packlist(): "materials/effects/eball_infinite_life.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow1.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow1.vtf"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow2.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow2.vtf"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_sphere.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_sphere.vtf"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_tape.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_tape.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props/c_ball_launcher_clean.vmt"
[INFO] vbsp.make_packlist(): "materials/models/props/combine_ball_launcher_clean.vtf"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/cust_fizz.mdl"
[INFO] vbsp.make_packlist(): "models/effects/combineball.mdl"
[INFO] vbsp.make_packlist(): "models/props/clean/combine_ball_launcher.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/trig_touch_fx.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_specific.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/bee2/turret_dropper.nut"
[INFO] vbsp.make_packlist(): "sound/BEE2/claw_cable_lp.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/alyx_stunner2.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/hl1_bell.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_bounce1.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_bounce2.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_disintegrate4.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_disintegrate5.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_explosion2.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_flyby1.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_flyby2.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_loop4.wav"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 8 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | material "bee2/fizz/phys_shield/clean_pshield_right" not found.
 | Material not found!: BEE2/fizz/phys_shield/clean_pshield_right
 | material "bee2/fizz/phys_shield/clean_pshield_center" not found.
 | Material not found!: BEE2/fizz/phys_shield/clean_pshield_center
 | material "bee2/fizz/phys_shield/clean_pshield_left" not found.
 | Material not found!: BEE2/fizz/phys_shield/clean_pshield_left
 | material "bee2/rex/beam_field_timer" not found.
 | Material not found!: BEE2/REX/BEAM_FIELD_TIMER
 | material "bee2/fizz/thedarkbomber/paintable" not found.
 | Material not found!: BEE2/fizz/thedarkbomber/paintable
 | material "bee2/fizz/thedarkbomber/clean_csfi_right" not found.
 | Material not found!: BEE2/fizz/thedarkbomber/clean_csfi_right
 | material "bee2/fizz/thedarkbomber/clean_csfi_center" not found.
 | Material not found!: BEE2/fizz/thedarkbomber/clean_csfi_center
 | material "bee2/fizz/thedarkbomber/clean_csfi_left" not found.
 | Material not found!: BEE2/fizz/thedarkbomber/clean_csfi_left
 | material "bee2/fizz/thedarkbomber/player_clip_electric" not found.
 | Material not found!: BEE2/fizz/thedarkbomber/player_clip_electric
 | Could not open instance file instances/BEE2/clean/items/neuro/timer.vmf
 | 
 |_

[INFO] BEE2_config.save(): Saving changes in config "C:\Users\p0rta\Desktop\Steam Items\Games in a Series\Portal\Portal 2\BEE2.4\config/compile.cfg"!
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

Upon removing the items (and the one fizzler that didn't show "ERROR":
![20170507002224_1](https://cloud.githubusercontent.com/assets/25728252/25777908/63d21c22-32bb-11e7-9b7c-0c0932a7cd6d.jpg)
![20170507002319_1](https://cloud.githubusercontent.com/assets/25728252/25777909/6690894e-32bb-11e7-9a0f-a2d20352d3bf.jpg)
Help?

**Comment by ZombiePwner1** [comment]
Obviously u didn't do a full export disable preserve game directories and do another export.

**Comment by LautaroL20** [comment]
The problem here is that you (and for anyone who had a previous Beemod version) didn´t delete the "bee2" folder insisde the Portal 2 directory which contains all the bee materials & models, so the game keeps using the old resources.

Since the PRL25 doesn´t override / delete the files in those folders anymore, now you have to do it manually. This is something that definitelly must be in the Readme file to let know the rest of people.

**Comment by LautaroL20** [comment]
Ignore the copy paste from adove, ZombiePwner1 is the right.

**Comment by hop193** [comment]
I found out the issue? IDK, I re-installed BEE2 and everything worked.
