### ISSUE TITLE
PR25 - Compile Error

### ISSUE THREAD

**Issue by Konata-Chan** [BEEmod/BEE2-items#1941]
![20170507055239_1](https://cloud.githubusercontent.com/assets/25024629/25779228/c94f3d40-32e9-11e7-9779-892af604d0f0.jpg)

VBSP failed.

[INFO] cond.core.x(): No name for module "voiceLine"!
[INFO] vbsp.main(): BEE2.4.0p425 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "F:/Program Files (x86)/Steam2/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "F:/Program Files (x86)/Steam2/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'use_screenshot': '1', 'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 2
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 3
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cond.fizzler.fizzler_out_relay(): Fizzler data: {'marker_inst': [], 'pos_to_name': {}, 'fizz_by_name': {}, 'model': 'instances/bee2/clean/items/tdb/csfi_model.vmf', 'base': 'instances/bee2/clean/items/tdb/csfi_base.vmf', 'fizz_id': 'item_tdb_csfi', 'fizz_bases': {'instances/bee2/clean/items/barrier_hazard_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/paint_fizz/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/csf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/fdf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/mif_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/death_fizz/base.vmf': ItemConnections(in_act=('branch_fizz', 'ToggleTest'), in_deact=('branch_las', 'ToggleTest'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/physler/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/rex/pellet_field_base.vmf': ItemConnections(in_act=(None, ''), in_deact=(None, ''), out_act=('out', 'OnUser2'), out_deact=('out', 'OnUser1')), 'instances/bee2/clean/items/tdb/csfi_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, ''))}, 'fizz_models': {'instances/bee2/clean/items/death_fizz/model.vmf', 'instances/bee2/clean/items/tdb/csfi_model.vmf', 'instances/bee2/clean/items/barrier_hazard_model.vmf', 'instances/bee2/clean/items/physler/model.vmf', 'instances/bee2/clean/i[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: FORCE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 1/6 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "ENTRY_GEN_TECH_DIFF"
 | 	"File" "ann_apoc/entry_tech_diff.vmf"
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "EXIT_GEN_EVAC"
 | 	"Choreo" "npc/announcer/evacuationmisc01.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 0/4 quotes..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3271, misses=330, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'blockplayergelbomb': False, 'doorcameras': True, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': True, 'allowgoomist': False, 'funnelallowswitchedlights': False, 'enableshapesignageframe': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/clean/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_specific.nut"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "F:\Program Files (x86)\Steam2\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "F:/Program Files (x86)/Steam2/steamapps/common/Portal 2/portal2/" "F:/Program Files (x86)/Steam2/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): 
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

This happens in all styles.

**Comment by ZombiePwner1** [comment]
Clearly there is a leak or something in your map that's causing this.

**Comment by Konata-Chan** [comment]
@ZombiePwner1 Nope,The map is Empty and recently created

**Comment by ZombiePwner1** [comment]
@Konata-Chan Have you done a full export?

**Comment by Konata-Chan** [comment]
@ZombiePwner1 Yes

**Comment by ZombiePwner1** [comment]
@Konata-Chan Odd. Try asking @TeamSpen210 About it.

**Comment by Konata-Chan** [comment]
@ZombiePwner1 Okay

**Comment by ZombiePwner1** [comment]
@Konata-Chan The PRL25 is having almost the half part of the bugs that the previous release had. This is why you may be getting weird errors.

**Comment by Konata-Chan** [comment]
@ZombiePwner1 Uh,Ok.But is there any solution?

**Comment by hop193** [comment]
Try re-installing BEE2, that worked for me twice when I was having issues.

**Comment by Konata-Chan** [comment]
@hop193 I've done it 3 times and it's the same.

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
