### ISSUE TITLE
Neurotoxin Vent can be "Portallized"

### ISSUE THREAD

**Issue by CyberSquime** [BEEmod/BEE2-items#1942]
![20170507125028_1](https://cloud.githubusercontent.com/assets/20158146/25783092/2c562630-3324-11e7-9234-a80281beeccc.jpg)

**Comment by CyberSquime** [comment]
Issue persists in Overgrown
![20170507130922_1](https://cloud.githubusercontent.com/assets/20158146/25783227/8e078930-3326-11e7-8b65-0fe416b86a2d.jpg)

**Comment by hop193** [comment]
Yes, I am also experiencing this issue.
