### ISSUE TITLE
Co-op Droppers Editor Models are not using "Edge Split Modifier" and therefore, their shadows looks weird

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1946]
![20170507011935_1](https://cloud.githubusercontent.com/assets/12244376/25795367/69e3c886-33ab-11e7-8c9c-8a8ef94b0b7b.jpg)

**Comment by ZombiePwner1** [comment]
Does it matter? no

**Comment by Luke18033** [comment]
In your opinion...

**Comment by Luke18033** [comment]
I noticed this too, and it was really bugging me.

**Comment by LautaroL20** [comment]
Heh, i might know why its not using an Edge Split Modifier, heres why:

![20170523131443_1](https://cloud.githubusercontent.com/assets/12244376/26452784/96a02880-4137-11e7-8400-f78f477b04df.jpg)
