### ISSUE TITLE
Background music not playing after respawning from a Trigger Autosave

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1947]
Regardless of where it is or how many there are, the background music stops playing if the player dies after using a Trigger Autosave. The only death hazard in the test this is happening in is the green high energy pellet, but the issue has also happened in tests without them. The background track is "Resonance" from Aperture Tag, could that have anything to do with it?

**Comment by ZombiePwner1** [comment]
This a valve bug since there is issues with the background music not playing after dieing.

**Comment by Luke18033** [comment]
No it's not, still a duplicate of BEEmod/BEE2.4#421 though.

**Comment by snorepion** [comment]
Oh, sorry. I tried to search and couldn't find it, probably because it isn't in this repository.

**Comment by Luke18033** [comment]
Also @ZombiePwner1 you need to learn how to spell "dying".

**Comment by ZombiePwner1** [comment]
@Luke18033 Hehe sorry my spelling just gets messed up sometimes :/
