### ISSUE TITLE
Sequencer

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/BEE2-items#1948]
A logic item for triggering sequences of logic. You connect it to several items (and hide antlines for all but one of them). When activated, each item is enabled one by one (with say 0.1s delay). The order is determined based on the distance from the item each instance is - closest first. To allow sequneces longer than 9, if chained together the later ones are deleted and their outputs added to the first.

**Comment by ZipZoptheCat** [comment]
This would make it way easier to time crushers, among other things. Perhaps also use the timer item to set the delay between activiations for shorter or longer intervals?

**Comment by Konclan** [comment]
Moving to #3886
