### ISSUE TITLE
Closed Solid Field = Plagarism???

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1950]
after decompiling the files of this and comparing them very carefully, i may have evidence of plagiarism, this field was ripped off from my original prototype force field that should have come with bee2 (it was white and looked VERY Similar to this) someone removed my completed force field from the coding section shortly after i published the source code of it a few months ago... the source code in this is VERY similar to the final code in my ready to publish force field...

**Comment by Luke18033** [comment]
The CSFi looks nothing like your force field, wasn't that the one with the green hexagon texture? Also, you don't need to create useless labels and assign random people. I'm starting to agree with TDB that you shouldn't have collaborator perms...

**Comment by Luke18033** [comment]
Also, you should use [Discord](https://discord.me/beemod) for things like this.

**Comment by Luke18033** [comment]
@EllingtonElectrician Could you elaborate on what you think happened here? I may have found actual evidence of this, and TDB's being totally silent about it.
