### ISSUE TITLE
An Inverted Version of the 'Trigger Outputs'

### ISSUE THREAD

**Issue by ImDaveead** [BEEmod/BEE2-items#1956]
You could just use a trigger output then a not gate. It would be nice to have a `Start Enabled` option on the trigger items to reverse the output.
![The current drop down for the trigger](https://cloud.githubusercontent.com/assets/24465214/25976365/5d8f248e-3682-11e7-8777-ecc02dfb862b.png)

**Comment by Endermage77** [comment]
Isn't that what Start Reversed does?

**Comment by Luke18033** [comment]
It's called a NOT Gate.

**Comment by ImDaveead** [comment]
Then you would have to connect it to the not gate, which takes more space. Also it uses up more *things* in the test chamber.

**Comment by TeamSpen210** [comment]
Not significantly. Ideally I'd make the compiler have enough smarts to be able to eliminate the extra logic where possible. Then it won't cost anything.
