### ISSUE TITLE
Portal Gun breaks the overgrown '4: collapsed' enterance 

### ISSUE THREAD

**Issue by ImDaveead** [BEEmod/BEE2-items#1957]
If you set the style to overgrown and use `4: Collapsed` as your enterance, then add the orange portal gun (set it enabled by default). By the time the announcer opens the portal, the orange gun inside the chamber fires and kinda breaks some triggers.

![image](https://cloud.githubusercontent.com/assets/24465214/26021488/7e9fffe2-375c-11e7-8d66-96b8bd400ccc.png)

**Comment by TeamSpen210** [comment]
Whoops. I need to add the logic to disable portalguns as well before the doors open.

**Comment by hop193** [comment]
You could fix this by putting a 'Trigger Once' block right by the entrance door to trigger the Portal Gun.
