### ISSUE TITLE
Radiative Flux Rectangle sometimes uses the pellet registered texture when a pellet hasn't been shot into it

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1960]
If the Fizzler Output Relay setting is set to infinity, the RFR is sometimes red even when it's deactivated, turning blue upon activation for a second and then back to red. It's connected to an angled panel, if that changes anything.
The RFR with a timed output is always green without any registered color, connected to the same item.

**Comment by Luke18033** [comment]
Should be fixed.
