### ISSUE TITLE
Closed Solid Field in Overgrown style uses the "Purple Stripe" from Compressed Smoke Field

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1965]
![csficsf](https://cloud.githubusercontent.com/assets/24462989/26039316/b588c3ec-38d6-11e7-8ac1-e8284cac426e.png)

**Comment by Luke18033** [comment]
How about in the future we don't let TheDarkBomber make custom fizzlers?

**Comment by ZombiePwner1** [comment]
@Luke18033 agreed.
