### ISSUE TITLE
Allow usage of Portal Stories: Mel music in maps if installed like Aperture Tag

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1967]
I wasn't sure whether to put it in BEE2.4 or BEE2-items, but I just put it here. Anyway, if you own Aperture Tag and register it as one of your installed games, you can use tracks from it in your maps, even in vanilla P2. Is it possible for you to do the same with Portal Stories: Mel? It has some really great music.

**Comment by Endermage77** [comment]
PS: Mel music is already included by default, so there isn't really any need.

**Comment by snorepion** [comment]
You mean in BEE2? I'm not seeing it.

**Comment by Endermage77** [comment]
Of course, that may just be I have PS: Mel already installed on my machine...
Try installing it on steam or something; it is a free game.

In either case, this already happens.

**Comment by snorepion** [comment]
I do have it installed. It's on a different drive than P2 and Aperture Tag, which might be causing it.

**Comment by Endermage77** [comment]
Ah.
I have all three installed in my steam directory, so maybe that will fix your lack of music.

**Comment by HugoBDesigner** [comment]
![image](https://cloud.githubusercontent.com/assets/6296061/26082448/6041919a-39a6-11e7-93d8-2afb8cc84e93.png)

**Comment by snorepion** [comment]
Thanks. Looks like I've been missing out on a lot.

**Comment by TeamSpen210** [comment]
It needs to be in the same folder as one game you have loaded in the list.
