### ISSUE TITLE
Closed Solid Field displays missing texture with Observation Room lighting

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1972]
For replicate the bug, you must put all the lights, including the observation room in the following way (more or less, maybe no need to be exactly as in the pict):

![Image](https://cloud.githubusercontent.com/assets/12244376/26199016/e045ec3e-3b9e-11e7-8ca7-e964ddbba473.jpg)

**Comment by Byzarru** [comment]
I played with the CSFi when it was still in Dev. It only has this problem with the observation room lights. There's a bunch of texturing issues with this item.
