### ISSUE TITLE
Bug - portals can be put a bit under Sendificator edges

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1976]
![sendificatorportal](https://cloud.githubusercontent.com/assets/24462989/26268678/a7232dbc-3cad-11e7-82f0-d773e127da4e.png)

**Comment by TeamSpen210** [comment]
Portals are in general actually really buggy, it's easy to put portals under things if there's no collision brushes to block it.

**Comment by snorepion** [comment]
Oh, never knew that. It's not that big of an issue, since it only happens about 1/4 of the time if you're actively trying to get a portal under the Sendificator, but I thought I might as well bring it up. If it's a Valve bug, though, it's harder to fix.
