### ISSUE TITLE
Dissable the placement helper at the end of Light bridges, Funnels, and Lasers via an Itemvar

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1979]

**Comment by Luke18033** [comment]
Why would you want these off? They don't force placement like most of the other helpers do.

**Comment by LautaroL20** [comment]
Actually i can no longer remember anymore what was the final purpose of this suggestion, but yes, those elements do not forces the portal placement after all, so i think that this suggestion can be closed.
