### ISSUE TITLE
item: extended relaxation vault

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#198]
before i forget, the extended relaxation vault should be added as a item, this is a must if creating a short series of story based test chambers in PTI

**Comment by Luke18033** [comment]
An ERV would definitely be useful, but PeTI isn't really for story maps...

**Comment by ZombiePwner1** [comment]
How this should work is that whever it's placed down it disables the entry door or it could just delete the entry elevators.

**Comment by Luke18033** [comment]
Duplicate of #1245 (which was moved from BEEmod/BEE2.4#32).
