### ISSUE TITLE
2 Things

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2-items#1981]
ONE: Please show me a picture or explain IN DETAIL on how to make stairs on a catwalk
TWO: Can you please add a way to turn something on only to have it turned off later? Or explain how to do it. NOT THE MULTIPLE TRIGGER!!!!!!!!!!

**Comment by Luke18033** [comment]
You should really use our [Discord](https://discord.me/beemod) for this kind of thing.
