### ISSUE TITLE
Aperture 1980's glitch

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2-items#1982]
before you enter the corridor, lobby, office, etc. you will have the dual portal device even when u dont have it once you enter the corridor, office, lobby, etc. Please fix this!

**Comment by GiovanH** [comment]
"Starting the map with a portal gun" sounds like intended behavior. Are you requesting an entryway where you have to pick up the portal gun? 

Or is the player only supposed to have a single-portal gun? You didn't mention autoportals, but is this about autoportals?

**Comment by LautaroL20** [comment]
This issue probably makes reference to the portal gun being mysteriously on the ground near the entry door. If this is the case, I have reported an issue like this a long time ago but I think that that was fixed if I am correct.

**Comment by Luke18033** [comment]
Those are definitely fixed, 4.41 redid almost every Old Aperture corridor. I'm not sure if that's what this issue was referring to though, it's rather vague.
