### ISSUE TITLE
4 things

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2-items#1983]
2 Bugs:
- [ ] The Rocket Turrets Rocket Disappears in Portal 1 Style
- [ ] The Bottomless pit thing does not work on clean with 3D factory

2 Suggestions
- [ ] Let Rockets Break Glass & Vactubes
- [ ] For The BTS style, add a cube factory, turret factory, & tile factory entrances

**Comment by LautaroL20** [comment]
Please, next time split each bug or suggestion you´d like to open, we preffer to having them splitted so each issue can be closed separately as they are implemented.

Issues are now splitted:

https://github.com/BEEmod/BEE2-items/issues/1986
https://github.com/BEEmod/BEE2-items/issues/1987
https://github.com/BEEmod/BEE2-items/issues/1988
https://github.com/BEEmod/BEE2-items/issues/1989

**Comment by Luke18033** [comment]
Combining them is fine.

**Comment by Luke18033** [comment]
Just use checkboxes, that way it's easy to know what's been done and what hasn't.
- [ ] Check Box = `- [ ] Check Box`

**Comment by Luke18033** [comment]
- Rocket turrets are quite buggy at the moment.
- Works fine for me.
- This will be a separate item, adding this behavior to the original a. would increase the entity count and b. would definitely introduce lots of unintended solutions.
- BTS is currently very WIP and missing a lot of corridors. We could add those. Just keep in mind that we don't actually have much space available for corridors.

**Comment by snorepion** [comment]
I also think having cube factory and turret factory _items_ would be great. It would also be nice if they acted like droppers, releasing turret boxes and cubes from the bottom.

**Comment by TeamSpen210** [comment]
Combining is only really useful when the items are related to each other.
