### ISSUE TITLE
Rocket Turret Is Bugged As Hell!

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2-items#1984]
The rocket turret's rocket does not work at ALL!!!!! please fix it

__________________________________________________________________________________________

- "In some styles. like 1950's, the rocket turret doesn't show up either. It's just a black hole in the ground with an invisible collision mesh on top that you can stand on and collide into"

- "And if it appears in the map, its really buggy"

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1986

**Comment by LautaroL20** [comment]
Well, maybe its not since it doesn´t reffer to any style in particular.

**Comment by hop193** [comment]
I like how you said it was a duplicate, even though this post was first.

**Comment by ZFM2004** [comment]
I tried it in multiple styles

**Comment by vtipoman** [comment]
Same here. The visuals and sounds are present, but the rocket doesn't appear

**Comment by LautaroL20** [comment]
Yep, and it is very bugged if it appears...

**Comment by ZFM2004** [comment]
thank you for noticing

**Comment by LautaroL20** [comment]
anytime

**Comment by Endermage77** [comment]
In some styles. like 1950's, the rocket turret doesn't show up either.

**Comment by IceTudor** [comment]
For me the rocket turret does a muzzle flash and then no rocket, also aims wrongly, like offset to the right a bit. One level it didn't even hurt me, even if I restarted my Portal 2. It's incredibly broken. Has to be fixed ASAP

**Comment by Fazbear189** [comment]
I get that too.

**Comment by PGRedYT** [comment]
there is a rocket entity but for some reason whenever the rocket turret is present ingame, it completely breaks the entity, not letting it be able to spawn. (i have a bind key set to shoot rockets)

**Comment by ZombiePwner1** [comment]
@PGRedYT Funnily enough the rocket turret was set to play a major role during portal 2's development but it was then removed. I believe parts of it's code has been removed causing it to behave the way it is rather than it's portal 1 variant.

**Comment by PGRedYT** [comment]
so why does the turret break the rocket entity? and what use does it have in a puzzle if its broken?

**Comment by ZombiePwner1** [comment]
@PGRedYT Mostly a bug with the rocket turret not firing it's rockets properly we have tried to fix it but it's not easy.

**Comment by Luke18033** [comment]
Duplicate of #1238 pretty much

**Comment by Luke18033** [comment]
Literally 1984
