### ISSUE TITLE
The Rocket Turrets Rocket Disappears in a "Mysterous Way" in P1 Style

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1986]
Original report by @ZFM2004 - Source: https://github.com/BEEmod/BEE2-items/issues/1983

"The Rocket Turrets Rocket Disappears in Portal 1 Style"

**Comment by Luke18033** [comment]
Duplicate of #1984.

**Comment by LautaroL20** [comment]
@Luke18033 - Do not forget to apply the label.
