### ISSUE TITLE
The Bottomless pit thing does not work on clean with 3D factory

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1987]
Original issue by  @ZFM2004 - Source: https://github.com/BEEmod/BEE2-items/issues/1983

"The Bottomless pit thing does not work on clean with 3D factory"

**Comment by TeamSpen210** [comment]
What do you mean by it not working? Did you use it properly?

**Comment by LautaroL20** [comment]
Idk, we should ask @ZFM2004 since he was the one who reported this, i think i should test the issue myself though.

**Comment by Luke18033** [comment]
Not enough info
