### ISSUE TITLE
Sliding Panel

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#1990]
A panel located in the ground. Upon getting an activation, it slides into the direction chosen by the 4-Positing system, and reveals either a portable, or non-portable, wall, ~3/4 in the wall. (Portability is chosen by the type of wall, portable or non-portable) 
Start Reversed checkbox to change the outside of the sliding panel wall type, P or NP. 
Another use of Start Reversed is possible, allowing for when an activation is connected to the Panel, it remains closed, and when there is no activation to the panel, it opens.
If the second option for Start Reversed is chosen, the panel will always remain Non-Portable.

Need I say more?

**Comment by snorepion** [comment]
Isn't this basically just a Flip Panel?

**Comment by Luke18033** [comment]
Yes, but it looks much nicer. Flip panels seem out of place in non-Old Aperture styles.

**Comment by snorepion** [comment]
Good point.

**Comment by TheTored** [comment]
I know, old thread n stuff
How thick would the panel be? Like a really thin wall or 1/4 block?
And also, it would fix the flip panels being blocked by basically everything.

**Comment by snorepion** [comment]
@TheTored I'd imagine that it would be very thin, but idk.

**Comment by TheTored** [comment]
@snorepion That's what I thought too, it would be the most useful I think.

**Comment by hop193** [comment]
It would be very thin.

**Comment by Konclan** [comment]
UCP
