### ISSUE TITLE
Add output to cube droppers

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1991]
I don't know how feasible this would be, but could you add an output to cube droppers that activates forever? If the input is a floor button, you can't activate infinitely, but I don't want to make the floor button activate an extra pedestal button just for an infinite output.

**Comment by TeamSpen210** [comment]
I'm not sure what a cube dropper has to do with permanent activation. Just use a SR Latch.

**Comment by snorepion** [comment]
Ah, I forgot those existed.
