### ISSUE TITLE
60 Degree Angled Corner Block selection mesh is misplaced

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1992]
![20170521140816_1](https://cloud.githubusercontent.com/assets/19228201/26287388/6760d2b4-3e2f-11e7-8972-b6a2035c5386.jpg)

**Comment by LautaroL20** [comment]
Ill fix this one as well as the P1 Stairs mesh, once i finish the ones for the Large Glass Panel.

**Comment by LautaroL20** [comment]
Now fixed. If there is anyother bug related to selection meshes, feel free to post the issue so ill fix it.

PD: Yay, it finally got generated the auto-close commit!

**Comment by Luke18033** [comment]
P1 angled panels are also missing their selection meshes.
