### ISSUE TITLE
Portal 1 Stairs use Clean selection mesh

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1993]
They're close enough that this isn't a major problem, but it's still noticeable when trying to select it by the pistons.
![20170521141614_1](https://cloud.githubusercontent.com/assets/19228201/26287431/33c34710-3e30-11e7-933d-ff068b0ada44.jpg)

**Comment by LautaroL20** [comment]
I´ve completely remake deployed selection mesh position and also improved the contracted one:

![Remade meshes](https://user-images.githubusercontent.com/12244376/82130285-63042900-97a0-11ea-8d11-0e1425139257.jpg)
