### ISSUE TITLE
Angled panels use the lighting from their undeployed location when deployed

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1994]
If you have an angled panel in a small corridor, like this, the panel face uses the small area's lighting rather than the room lighting even when deployed.
![angledpanelcorridor](https://cloud.githubusercontent.com/assets/24462989/26287611/92a16e7c-3e3c-11e7-893a-1e2a05d40bb3.png)
Effect:
![angled-panel-lighting](https://cloud.githubusercontent.com/assets/24462989/26287622/b8c6f23e-3e3c-11e7-9fcb-dc72d88d86f2.png)

**Comment by Luke18033** [comment]
Unfortunately this isn't fixable.

**Comment by TeamSpen210** [comment]
It's not a bug. That's how brush lighting works. You'd have to redesign the engine to change that.

**Comment by Luke18033** [comment]
Couldn't this be fixed by making panels that start deployed actually start in that position, instead of extending to it on map spawn?

**Comment by TeamSpen210** [comment]
That could work, but it'd be rather complicated to do.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Well it's the only possible fix that we know of.
