### ISSUE TITLE
Portal 1 "Sphere" autoportal unstyled

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1995]
![20170521144203_1](https://cloud.githubusercontent.com/assets/19228201/26287624/5dd0d168-3e34-11e7-839d-cef39b8d4b0a.jpg)

**Comment by iEnderMan06** [comment]
As far as I know the "Sphere" autoportal isn't an actual item, like with death fizzlers

**Comment by TeamSpen210** [comment]
It is a kinda accidental item, we have to have 3 items, so it's a blank frame. So I don't tend to think about it too much...

**Comment by Luke18033** [comment]
I use it as a sort of "placement indicator" to indicate where portals should be placed without automatically placing them.

**Comment by TeamSpen210** [comment]
For that, I suggest using a undeployed angled panel, to give you a extended slab. The Autoportal frames are more suited to be used with a Portal Gun Pedestal.

**Comment by Luke18033** [comment]
Portal Pro uses them as placement indicators quite often, which is where I got the idea from.
