### ISSUE TITLE
Add an option to invert door walls' portalability

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1996]
Maybe with the "Auto-drop first cube" option, we could set whether the walls surrounding doors should have their portalability reversed. I know it's already possible to change their portalability with the floor's portalability, but in cases like user-made chamberlocks, the player has to choose to either leave the door as non-portalable against a portalable wall, or vice-versa, or run the risk of having the player portal through the door. Perhaps, although unlikely, it'd be nice to have only the "out-facing" face change portalability, so the "inside" doesn't look off too.

**Comment by hop193** [comment]
Yes! I need this!

**Comment by Endermage77** [comment]
Is this referring to door <b>frames</b> or the actual doors themselves?

**Comment by HugoBDesigner** [comment]
@Endermage77 Door frames, yes. So that they match the adjacent walls

**Comment by Endermage77** [comment]
May want to specify that, then.

**Comment by HugoBDesigner** [comment]
Also fixed

**Comment by Luke18033** [comment]
This is implemented?

**Comment by TeamSpen210** [comment]
It's not.

**Comment by HugoBDesigner** [comment]
Oops, my bad

**Comment by Luke18033** [comment]
Now implemented with the new tiling system (placing a quarter tile below the door will invert the portalability without affecting the rest of the tile)
