### ISSUE TITLE
Large Glass Panel: It can kill you in a "Mysterious Way"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1999]
Id suggest to get rid of the trigger kill, since the PeTi panels doesn´t do this at all, so this kind of things can disorient the player. 

GIF: ![GIF](https://cloud.githubusercontent.com/assets/12244376/26333516/a15b1618-3f34-11e7-80e3-69a22a586e84.gif)

**Comment by Luke18033** [comment]
The triggers are quite buggy at the moment, which is part of the reason it hasn't been merged. Here's what's supposed to happen:
- If a player or physics object is under the panel as it retracts, they'll be pushed out.
- If a wall blocks the player or object from being pushed out, they'll be fizzled/killed.

I haven't yet come up with a setup for the triggers that's able to make this work without things like this happening.

**Comment by iEnderMan06** [comment]
STOP IT PLEASE

**Comment by ZombiePwner1** [comment]
@iEnderMan06 stop what?
