### ISSUE TITLE
P1 Large Glass Panel: Their arms are crossing the hollow´s grate in a "Mysterious Way" 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2000]
Id suggest to using the clipping tool to make a small rectangle for it, so it looks more realistic and therefore it doesn´t look this way:

![20170522205438_1](https://cloud.githubusercontent.com/assets/12244376/26333288/d9a54f4a-3f32-11e7-829d-6da6c41abb80.jpg)

**Comment by Luke18033** [comment]
I'm sure I did that already, maybe GitHub didn't commit it?

**Comment by ZombiePwner1** [comment]
@LautaroL20 lol it's just a minor issue does it really matter?

**Comment by TeamSpen210** [comment]
It does. Stuff in instances will be used hundreds of times, so we should be as perfectionist as possible.

**Comment by iEnderMan06** [comment]
STOP IT PLEASE SPARE US ALL

**Comment by HugoBDesigner** [comment]
@iEnderMan06 Are you just going to randomly hop on random issues spamming?

**Comment by LautaroL20** [comment]
@HugoBDesigner - Yeah, hes being annoying with the spamm, and even i don´t get it why hes doing that....

**Comment by iEnderMan06** [comment]
I posted it twice that's all...

**Comment by iEnderMan06** [comment]
But the "Mysterious Way" is getting out of hand, let me solve it for myself.
done, right thanks guys.

**Comment by HugoBDesigner** [comment]
Still without reason. Keep in mind this is a page for discussing issues/features, not for random chatting.

**Comment by Luke18033** [comment]
[Here's the random chatting page.](https://discord.gg/gXQAu)

**Comment by LautaroL20** [comment]
@iEnderMan06 - Do not offence, but please go play Castlevania for the Nintendo NES or something else, when you open your own issue, call it whaetever. These are mine and if i like to giving it a small touch of pseudo-humor on the titles, ill do it.

**Comment by LautaroL20** [comment]
Well, i will fix this myself because seems easy and i really want this item to be available for everyone. Otherwise, this item could come with Half-Life 3...

**Comment by Luke18033** [comment]
Now fixed.

**Comment by LautaroL20** [comment]
Any commit reference?

**Comment by Luke18033** [comment]
I don't know, I just noticed there was now a hole there when working on these items earlier. Unless this is on the static variants, in which case I just redesigned those anyway.
