### ISSUE TITLE
P1 Large Glass Panel: Their animated arms are missing a small stretch

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2001]
![20170522210250_1](https://cloud.githubusercontent.com/assets/12244376/26333359/6a14bcfa-3f33-11e7-89bc-2ce4131aa753.jpg)

**Comment by Luke18033** [comment]
Whoops. I don't know how I didn't notice this.

**Comment by TeamSpen210** [comment]
Don't use arms like that. It's better to do like other panels, and use the motor-cylinders. I made a model version of those to give them nice smoothness.

**Comment by Luke18033** [comment]
The drawbridge uses them.

**Comment by LautaroL20** [comment]
Once you fix this, ill make the P1 Style versions for both the Large Glass Panels, since i need to see the actual in-game model appearance to have an idea of how it must be like.

**Comment by LautaroL20** [comment]
Well, i will fix this myself because seems easy and i really want this item to be available for everyone. Otherwise, this item could come with Half-Life 3...

**Comment by Luke18033** [comment]
I'm going to redesign this variant anyway whenever I get around to finishing this item.

**Comment by Luke18033** [comment]
Also, it wasn't quite HL3, but we did actually end up getting a new Half-Life game before I finished this item...

**Comment by LautaroL20** [comment]
Hehe, you are right. I was a big fan/enthusiastic of the Half-Life saga (played all them including the Gearbox expansions and the BM remake), I had the hope for many years on a HL2:EP3/HL3 release, but at this point all fans and I must admit that Valve will never make this come true...
