### ISSUE TITLE
Double Large 90° Degress Angled Panel

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2003]

**Comment by Luke18033** [comment]
The title is very confusing, are you referring to #1706?

**Comment by LautaroL20** [comment]
Oh well, i just were reading comments on Discord, and i thought no one had suggested it before.

So it makes this a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1706

**Comment by Endermage77** [comment]
Would it be a double-long panel or a double-wide panel?
Come to think of it, a 1.5-unit wide panel might could be an interesting addition.

**Comment by LautaroL20** [comment]
Long or wide is really ambiguous considering the item may be in the floor, wall or ceilling, but it will be a 128x256 panel to be precise.

**Comment by Endermage77** [comment]
In my context, a long panel would extend two blocks out from the wall, and a wide panel would be two blocks wide on the wall.
