### ISSUE TITLE
Numerals

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#2011]
![image](https://cloud.githubusercontent.com/assets/22107242/26523780/4a0fd660-42e4-11e7-8356-c0e21f3140a2.png)
These would be overlays with individual or dual numbers 0-9, A-Z with two font variants and two color variants (Black and White in Clean and Old Aperture, Blue and Yellow in BTS). Numbers would be determined through the ICS.

**Comment by Byzarru** [comment]
![image](https://cloud.githubusercontent.com/assets/22107242/26523807/dfe16cda-42e4-11e7-8974-24db1741ad06.png)

**Comment by TeamSpen210** [comment]
I don't think this is really necessary, ypu have the 1-4 dots in existing signage. I'm not sure there's much need for higher dot counts...

**Comment by Byzarru** [comment]
It's more for aesthetics. BTS is really bland and unnatural, and this kind of item would make it feel more like a maintenance area. Also, the existing dots and styled signage is small, this would take up a larger space.

**Comment by hop193** [comment]
Cool, but what does ICS stand for? My bad.

**Comment by Luke18033** [comment]
It's not the ICS, it's the ICP, or Item Configuration Pane. That was the original name for the "Items" tab in the Style Properties pane (it was originally going to be its own window).

**Comment by Byzarru** [comment]
ICS is ICP in the language of my people. It's a ~lazy~cultural thing.

**Comment by Konclan** [comment]
Merging with #1096
