### ISSUE TITLE
ChamberLock item has visible nodraw 

### ISSUE THREAD

**Issue by AddMGH** [BEEmod/BEE2-items#2014]
While testing my map I discovered that there was visible nodraw inside of them.
![why are you reading this 2017-05-28 17-22-09-482](https://cloud.githubusercontent.com/assets/26350889/26530465/1bd42474-43cd-11e7-9c3b-4cd4d7ee5cff.jpg)
![why are you reading this 2017-05-28 17-22-16-469](https://cloud.githubusercontent.com/assets/26350889/26530467/1bd7ff40-43cd-11e7-8aa2-4ed9200d3977.jpg)
![why are you reading this 2017-05-28 17-22-19-768](https://cloud.githubusercontent.com/assets/26350889/26530466/1bd7e744-43cd-11e7-9dcc-57929fe2fecf.jpg)
![why are you reading this 2017-05-28 17-22-26-864](https://cloud.githubusercontent.com/assets/26350889/26530468/1bdb6b6c-43cd-11e7-8917-c07e0ca7e291.jpg)
![why are you reading this 2017-05-28 17-22-30-079](https://cloud.githubusercontent.com/assets/26350889/26530469/1bdf3224-43cd-11e7-9c0c-2fa78a1735f2.jpg)
![why are you reading this 2017-05-28 17-22-33-135](https://cloud.githubusercontent.com/assets/26350889/26530470/1be3460c-43cd-11e7-9e93-a3c4552d278c.jpg)

**Comment by ZombiePwner1** [comment]
@iEnderMan06 Seems the door frame on the inside is missing causing the nodraw to appear.

**Comment by iEnderMan06** [comment]
@ZombiePwner1 I checked the instance and it is there, that's the strangest thing.

**Comment by ZombiePwner1** [comment]
@iEnderMan06 Then it seems to be either a world portal leak or just a leak in the map somewhere.

**Comment by Luke18033** [comment]
> world portal leak

It's called an areaportal leak, worldportals can't cause leaks.

**Comment by TeamSpen210** [comment]
Is this still happening? I can't replicate it.

**Comment by Luke18033** [comment]
Possibly fixed now? TeamSpen said he couldn't replicate it, and these frames would have had to be updated in 4.37 anyway.

**Comment by LautaroL20** [comment]
I will going to give this a test by placing this item in different spots and if I can´t replicate this, I will consider this fixed.

**Comment by Luke18033** [comment]
It should be fixed now, as I said the frames for these would have been remade in 4.37 for the tiling update.

**Comment by LautaroL20** [comment]
Yeah, that is the most likely.
