### ISSUE TITLE
Glass/Grating to Center

### ISSUE THREAD

**Issue by WhoozYerBuddy** [BEEmod/BEE2-items#2015]
I really like the new addition of 'Start Enabled' on the 1/4 walls so that they are offset to the center 4 positions.  Can you do the same for the Glass/Grating?  That would place one side of the frame at the center of the square offset to the side with the grip.

**Comment by Endermage77** [comment]
I second this.

**Comment by hop193** [comment]
I third this.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i forth this

**Comment by Luke18033** [comment]
Surprised this hasn't been implemented, it seems like a fairly easy change since the logic is already there for quarter walls...
