### ISSUE TITLE
Add "CanAnchorOnBarriers" to Half Grate

### ISSUE THREAD

**Issue by WhoozYerBuddy** [BEEmod/BEE2-items#2016]
It works, and would be useful, but the offsets are not correct when anchored to other barriers.
![20170528101810_1](https://cloud.githubusercontent.com/assets/29020282/26530883/e3abb6d2-4392-11e7-90af-eb0cd0391aad.jpg)
![20170528101926_1](https://cloud.githubusercontent.com/assets/29020282/26530884/e3af6548-4392-11e7-93e8-a37252e7ce6d.jpg)

**Comment by WhoozYerBuddy** [comment]
...and the frames look like shite in the clean style...  :-P

**Comment by LautaroL20** [comment]
I still remember that there was a problem related to this feature of `CanAnchorOnBarriers` that caused the puzzlemaker to not remember the latest position that the item was pointing for when it uses `handle_8_positions` see issue https://github.com/BEEmod/BEE2-items/issues/793 for more info.

**Comment by Luke18033** [comment]
We'll have to choose between this or #2019 - combining them causes the item to reset to the center of the voxel when chamber geometry is modified.

**Comment by LautaroL20** [comment]
Well, seeing the screenshots that shows how my Half-Grate is overlaping the vanilla grating at their edges, that does look bad and unrealistic so i would be choosing applying #2019 on my item instead of the current issue, so closing this.
