### ISSUE TITLE
Portal 1 GLaDOS monitor chamber is unstyled.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2021]
![20170529111813_1](https://cloud.githubusercontent.com/assets/18079316/26535548/20756774-4461-11e7-9a4f-438660842221.jpg)

The way this needs to be done is so it shows the portal 1 lair with portal 1 GLaDOS

**Comment by Luke18033** [comment]
Is this with the P1 GLaDOS voice pack selected?

**Comment by ZombiePwner1** [comment]
@Luke18033 No but this should still be fixed.

**Comment by Luke18033** [comment]
P1 GLaDOS would be used in monitors when the voice pack is selected, regardless of the style. We'll need to implement that first.

**Comment by TeamSpen210** [comment]
That'd be... Difficult. Since then I'd need to make every combination of voiceline  and style...

**Comment by Luke18033** [comment]
Why? You just put it in the `instances/voice` folder like all the other monitor chambers.

**Comment by TeamSpen210** [comment]
But you'd need to also make all the other combinations... P1 Wheatley, Overgrown GLaDOS, 60s GLaDOS... Currently, it's more like GLaDOS is always in a Clean core room elsewhere, just dropping you into a <style> chamber.

**Comment by Luke18033** [comment]
Oh, I see, you were referring to @ZombiePwner1's suggestion. I was suggesting to implement it the way it's done with the others currently.

**Comment by TeamSpen210** [comment]
So actually this is intentional.
