### ISSUE TITLE
Large glass panel has visible texture overlaps.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2025]
![20170529165512_1](https://cloud.githubusercontent.com/assets/18079316/26544799/ca4c30be-4495-11e7-82f4-8373d6d61064.jpg)

**Comment by Luke18033** [comment]
This is already fixed for the single panel - it uses the BTS Large Faith Plate model, which is resized so that it doesn't clip. The double panel doesn't have that though, it'll need to be custom-made.

**Comment by Luke18033** [comment]
This is actually a lot simpler than I originally thought, I think all you need to do is add some `$scale` parameters to the QC.
