### ISSUE TITLE
Large glass panel needs editor models in other styles.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#2026]

**Comment by LautaroL20** [comment]
> ZombiePwner1 Said: "aswell as animations in the editor."

Well, feel free to learn animations in Blender, since making them is not easy. Thats why i just maked them static.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Heres why it uses the glass panel 90 editor model.

This is the overgrown .txt

"ModelName"  "arm4_gls_90deg.3ds"

**Comment by Luke18033** [comment]
I don't think the Overgrown variants really need a unique editor model, and the OldAp/P1 versions are going to be redesigned anyway.
