### ISSUE TITLE
Portal 1 large glass panels arms are not solid.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2027]
![20170529202935_1](https://cloud.githubusercontent.com/assets/18079316/26549920/f5c2a3d2-44ad-11e7-9d0c-fd357435e795.jpg)

Gaben confirmed?

**Comment by Luke18033** [comment]
That's intentional - if they were solid, the added collision could break maps when switching styles. Notice that there's also an invisible clip where the arm is in other styles.
