### ISSUE TITLE
How do I add Bottomless Pits/ Skyboxes?

### ISSUE THREAD

**Issue by cuben7** [BEEmod/BEE2-items#2028]
Hey! I tend to be quite oblivious to literally everything ever, so sorry. Is there a link or file I haven't seen for skyboxes or bottomless pits? I'm looking for a way to add them to the PTI thing in portal 2 without any hammer related stuff and I'm having trouble finding the files/links on GitHub.
sorry bout dat

**Comment by iEnderMan06** [comment]
If you have BEE 2.4 installed you can select 2D or 3D Behind the Scenes skybox and that'll add bottomless pits. to add a skybox go onto your BEE2.4 application, and under "Export Options" there will be an option called "Skybox" it defaults to "Clean" click the three dots in a box icon to choose your skybox.

**Comment by cuben7** [comment]
Kay, thanks! I'll try it out.

**Comment by cuben7** [comment]
Can you add them to the map specifically, using a certain item? Or are they just automatically added regardless?

**Comment by iEnderMan06** [comment]
@cuben7 Automatically

**Comment by Endermage77** [comment]
The bottomless pits replace goo pits, in case that helps clarification. Ideally, you should make them no thicker than one block deep.

**Comment by cuben7** [comment]
Thanks! if goo makes a bottomless, pit, what makes a skybox?

**Comment by iEnderMan06** [comment]
@cuben7 The BEE application does.

**Comment by cuben7** [comment]
OK! Thanks for the help guys

**Comment by Luke18033** [comment]
> Ideally, you should make them no thicker than one block deep.

No, it's exactly the opposite...

**Comment by Endermage77** [comment]
Is it?
Do pardon my mistake.

**Comment by mikehowler** [comment]
THIS  DOSENT WORK

**Comment by mikehowler** [comment]
THIS SERIOUSLY DOSENT WORK WHY DOSENT THIS WORK

**Comment by Luke18033** [comment]
Please calm down. This issue is from 2017, bottomless pits were removed for now so they can be rewritten.

**Comment by ApetureScience-Helpsystem** [comment]
ad bottomless pit pleas

**Comment by FrozenDragon0** [comment]
> ad bottomless pit pleas

They will be re-added once they have been re-written.

**Comment by savoscott** [comment]
well rewrite the botmless pit faster
its been years

**Comment by FrozenDragon0** [comment]
> well rewrite the botmless pit faster its been years

That's not how it works...
And being impatient won't do anything.

**Comment by MapacheParches** [comment]
Anyone know anithing about wen we are gonna get them?

**Comment by Sebdet9** [comment]
It's been way too long wth

**Comment by vrad-exe** [comment]
No it hasn't, this is a free project worked on by basically 1 person in their spare time and this is a complicated feature. Also this is still a really old issue unrelated to the removal of bottomless pits, I don't know why everyone has started using it to ask about them being added back.
