### ISSUE TITLE
Add Linked Portal Door

### ISSUE THREAD

**Issue by XdplayerdX** [BEEmod/BEE2-items#2030]
add a linked portal door that go to a location that is linked
examples:

![](https://developer.valvesoftware.com/w/images/a/a1/Linked_portal_door_example.jpg)

https://youtu.be/rOSThfw7DSA
https://developer.valvesoftware.com/wiki/Linked_portal_door

**Comment by Luke18033** [comment]
Already going to be implemented - see #574.
