### ISSUE TITLE
Add a unistaler

### ISSUE THREAD

**Issue by XdplayerdX** [BEEmod/BEE2-items#2031]
i think that is good make a unistaler to reset portal 2 state if any error make the game corrupt.

**Comment by Luke18033** [comment]
Remove Portal 2/Aperture Tag from BEE2.4's game list, that'll remove all BEE-related files.

**Comment by ZombiePwner1** [comment]
@XdplayerdX An error won't make the game corrupt that'd be ridiculous.

**Comment by XdplayerdX** [comment]
sorry for my bad english,but i don't know that and i have unistaled the game because i can't make puzzles when i used a bee mod beta that the @Luke18033 has passed for me (i supose that i writed that in a good english...)

**Comment by iEnderMan06** [comment]
I advise you download this: https://app.grammarly.com/
