### ISSUE TITLE
Portal 1 Style Laser Catchers aren't styled

### ISSUE THREAD

**Issue by AddMGH** [BEEmod/BEE2-items#2034]
![why are you reading this 2017-06-02 17-40-49-984](https://cloud.githubusercontent.com/assets/26350889/26735707/f0473480-47ba-11e7-9140-d3b42e1c85df.jpg)
They should look more like this 
![why are you reading this 2017-06-02 17-46-06-820](https://cloud.githubusercontent.com/assets/26350889/26735812/5f3d7d90-47bb-11e7-95af-1195d1074641.jpg)

**Comment by Luke18033** [comment]
They're styled - note the orange glow behind it.

**Comment by iEnderMan06** [comment]
@Luke18033 That's not styled that's just Portal 1 style's backpanels texture...

**Comment by iEnderMan06** [comment]
Straight from the config file: "Behind" "metal/metalwall_bts_006b_gradient" which is this texture 
![why are you reading this 2017-06-02 17-58-38-665](https://cloud.githubusercontent.com/assets/26350889/26736331/83ec3418-47bd-11e7-8e80-607235e46745.jpg)
Plus there's not even a model for it, only the emmiter:
![why are you reading this 2017-06-02 18-00-57-640](https://cloud.githubusercontent.com/assets/26350889/26736348/91296592-47bd-11e7-96d6-0da017cc803c.jpg)
![why are you reading this 2017-06-02 18-01-18-906](https://cloud.githubusercontent.com/assets/26350889/26736347/91285b02-47bd-11e7-9752-73eb9264f129.jpg)

**Comment by Luke18033** [comment]
> Straight from the config file: "Behind" "metal/metalwall_bts_006b_gradient" which is this texture

Indeed, if it were unstyled you'd be seeing that, not the orange glow. So it is styled.

**Comment by iEnderMan06** [comment]
No, if I change the config texture it will just change that texture, it's not a styled item...

**Comment by Luke18033** [comment]
Set it to one of the Clean backpanel textures or a dev texture or something, see what happens.

**Comment by iEnderMan06** [comment]
Actually it seems to be using `"Pack" "PACK_P1_ORANGE_NOGLOW"`

**Comment by Luke18033** [comment]
No, that's something different.

**Comment by Luke18033** [comment]
Just trust me, it's styled.

**Comment by iEnderMan06** [comment]
If you call texture swapping styling sure.

**Comment by iEnderMan06** [comment]
It's just the vmf file.

**Comment by Luke18033** [comment]
Whatever, I'm not reopening the issue.

**Comment by iEnderMan06** [comment]
![why are you reading this 2017-06-02 18-24-33-729](https://cloud.githubusercontent.com/assets/26350889/26737155/e83031b0-47c0-11e7-864b-a42104e51e77.jpg)
And hell even this looks far better...
![why are you reading this 2017-06-02 18-25-35-290](https://cloud.githubusercontent.com/assets/26350889/26737173/f67298bc-47c0-11e7-9f13-12d90211d6c8.jpg)

**Comment by iEnderMan06** [comment]
@TeamSpen210 Is it correct for me to think that an orange glow behind a laser catcher + relay isn't really a styled item?

**Comment by TeamSpen210** [comment]
It is indeed a styled item, I made that model specially for it, and made the VMF.

**Comment by TeamSpen210** [comment]
I encountered issues with doing the catcher model, so I left it how it is now.

**Comment by iEnderMan06** [comment]
So at some point it will look much nicer?

**Comment by LautaroL20** [comment]
This is not properly implemented, see (https://github.com/BEEmod/BEE2-items/issues/2044)

**Comment by IceTudor** [comment]
I say the P2 beta version of the catcher would fit it more.
