### ISSUE TITLE
You can get "Stagnat Forever" on Portal 1 style protruding pedestal buttons by jumping on them

### ISSUE THREAD

**Issue by AddMGH** [BEEmod/BEE2-items#2035]
![why are you reading this 2017-06-02 17-45-51-117](https://cloud.githubusercontent.com/assets/26350889/26735896/cd32b91e-47bb-11e7-911c-ec2a54e286a7.jpg)

**Comment by iEnderMan06** [comment]
uhm how many times can you see the name @LautaroL20 in one sentance?

**Comment by iEnderMan06** [comment]
Because I think that's as many as you can.

**Comment by hop193** [comment]
@iEnderMan06 
One day walking in the @LautaroL20 park, some person named @LautaroL20 said to me: "@LautaroL20 is the greatest," which sounded as true as @LautaroL20, so I said: "Yeah, @LautaroL20 is so good, he may be @LautaroL20," which made us both look at each other in shock.
Does this prove you wrong?

**Comment by iEnderMan06** [comment]
:/

**Comment by Luke18033** [comment]
Still an issue

**Comment by Luke18033** [comment]
Now fixed
