### ISSUE TITLE
Vactubes in Portal 1 style don't generate at all

### ISSUE THREAD

**Issue by iEnderMan06** [BEEmod/BEE2-items#2036]
![why are you reading this 2017-06-02 17-55-07-541](https://cloud.githubusercontent.com/assets/26350889/26736676/10f8c474-47bf-11e7-8938-5ae0536b4de0.jpg)
![why are you reading this 2017-06-02 17-55-13-984](https://cloud.githubusercontent.com/assets/26350889/26736677/1154c3dc-47bf-11e7-9a5c-356e9a260aa7.jpg)

**Comment by Luke18033** [comment]
Strange, they should be using the Clean variant...

**Comment by Luke18033** [comment]
OH! Do you have them connected in a loop? That doesn't work currently.

**Comment by iEnderMan06** [comment]
Oh yeah, I forgot, lmao sorry.
