### ISSUE TITLE
Paint Fizzler variant: Liquid Coloring Excision Field

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#2037]
It is esentially a fizzler for paint. It block portals, but does not fizzle portals or cubes. Only paint will be destroyed when the field is active.

**Comment by Luke18033** [comment]
So, a paint fizzler?

**Comment by ZombiePwner1** [comment]
Like the description says it's a paint fizzler but it also blocks portals.

**Comment by Luke18033** [comment]
I don't think that's a very good idea.

**Comment by Luke18033** [comment]
It's been mentioned several times on Gitter and Discord that the LCEF should replace the current Paint Fizzler on non-P1 styles, not be a separate item.

**Comment by Endermage77** [comment]
We could make this a stylevar and call both variants the LCEF anyway?

**Comment by ellingtonvengaboysmuseum** [comment]
this is not being implemented. @TeamSpen210 said so himself. case closed...

**Comment by Luke18033** [comment]
No need to lock invalid issues.

**Comment by Luke18033** [comment]
What would be a better way to implement this is a "Paint Fizzler Blocks Portals" stylevar, that way this can also apply to the existing paint fizzler.

**Comment by Luke18033** [comment]
Btw @ellingtonvengaboysmuseum, you should join the [Discord](https://discord.me/beemod).

**Comment by TheDarkBomber** [comment]
@Luke18033 Why did you edit this issue instead of opening a new one?

**Comment by TeamSpen210** [comment]
This would be a seperate item, the LCEF would block portal shots, but the Paint Fizzler would not.

**Comment by Luke18033** [comment]
Now that we can properly implement Hazard Type on custom fizzlers, we should make this the Laserfield variant of the Paint Fizzler.

**Comment by TeamSpen210** [comment]
Other way around.

**Comment by Konclan** [comment]
We're not adding more fizzlers
