### ISSUE TITLE
Lasers are invisible when viewed through Overgrown windows

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2038]
_From @Te4mLuna on June 3, 2017 15:47_

To explain it in the easiest way: 
You can´t see the laser on the other side of broken glass
![20170603174540_1](https://cloud.githubusercontent.com/assets/19846848/26754966/a1442b34-4884-11e7-9e96-1651aa78ad6f.jpg)

_Copied from original issue: BEEmod/BEE2.4#655_

**Comment by Luke18033** [comment]
I think that would be a Valve bug.

**Comment by Te4mLuna** [comment]
I only happenes with these two glass walls though. The third in the back works just fine.
