### ISSUE TITLE
a cool coop suggestion

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2-items#2040]
you should have a atlas gun pedastal (with a dual, purple, & blue one) & a p-body one just like that
also add auto-portals for each robots gun colors

**Comment by iEnderMan06** [comment]
This'd require as far as I know too much work.

**Comment by Luke18033** [comment]
I don't understand what you mean by the first suggestion. In Co-op you either have a dual gun or no gun, single-color devices don't work.

**Comment by Luke18033** [comment]
Possibly you're referring to #1829?

**Comment by Luke18033** [comment]
Aaaand, no response. Since it's not exactly clear what this is a suggestion for, I'm going to close it.

**Comment by Endermage77** [comment]
I think he means adding portal gun pedestal items, for both Atlas and P-Body, that shoot their respective portals.

**Comment by Luke18033** [comment]
In that case it's a duplicate of my issue.
