### ISSUE TITLE
30 Degree Angled Panels kill you in a mysterious way

### ISSUE THREAD

**Issue by AddMGH** [BEEmod/BEE2-items#2041]
https://youtu.be/W_eNFmbW_P8

**Comment by LautaroL20** [comment]
That video is no longer available unfortunately, so I can not see what was exactly wrong with this panel. Could you please re-upload it?

**Comment by LautaroL20** [comment]
I highly doubt that this author will ever respond, and considering I tried to replicate this issue but it was not possible, I will close this.
