### ISSUE TITLE
Trap Faith Plate

### ISSUE THREAD

**Issue by DrMeepster** [BEEmod/BEE2-items#2042]
This would be a faith plate but instead of having it rotate based on the point it launches to, it could be rotated in four directions manually to trick the player, like in the first level of Chapter 9.

**Comment by iEnderMan06** [comment]
Can you give an example of where a player could successfully use this?

**Comment by DrMeepster** [comment]
It could be useful if you wanted to trick the player into thinking they're going one way but then unexpectedly fling them another way like in Chapter 9's first chamber.

**Comment by TeamSpen210** [comment]
Tricking the player is not something which is a good thing in a test chamber.
