### ISSUE TITLE
The new P1 Laser Catcher model looks "Unstyled"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2044]
![Image](https://cloud.githubusercontent.com/assets/12244376/26806564/eaabb9c8-4a27-11e7-8670-ef3052cb8e5a.jpg)

**Comment by TeamSpen210** [comment]
Make sure you've got the new copy of the script.

**Comment by LautaroL20** [comment]
You mean the latest version of the compiler? Because ive already synced Github, and also deleted old respuces before did a "Full Export".

**Comment by iEnderMan06** [comment]
Wouldn't this still be under mine?

**Comment by LautaroL20** [comment]
@Adam - Why you deleted your comment?

**Comment by Luke18033** [comment]
Lol, you mentioned the wrong person. @iEnderMan06 was who you meant to mention.

**Comment by Luke18033** [comment]
Whoops
