### ISSUE TITLE
Add Portal Pro Music

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2047]
_From @hop193 on May 6, 2017 18:40_

Add a few of Portal Pro's tracks.

'Nuff said.

_Copied from original issue: BEEmod/BEE2.4#601_

**Comment by Luke18033** [comment]
"A few"? We'd add all of them. These would be copied from the mod like the Tag and Mel music.

**Comment by hop193** [comment]
Alright, well, go ahead.

**Comment by Byzarru** [comment]
I am in the process of doing this right now. Once we get the proper permissions, I will start a pull request.

**Comment by Byzarru** [comment]
#2096, if merged, will cover this.
