### ISSUE TITLE
Stylevar for sv_player_collide_with_laser

### ISSUE THREAD

**Issue by quat1024** [BEEmod/BEE2-items#2048]
One of tuleby's new items is something that basically just runs the command sv_player_collide_with_laser 0 when the map starts. Kind of sucks that it takes up a whole item slot, though, for something "global" like laser collision.

This would totally work as a stylevar, right? Set the variable to 0 when walking through the entry door, and set it to 1 when leaving from the exit door.

**Comment by TeamSpen210** [comment]
I'll need to check if it resets after a level load. Because you could quit the map halfway through, and we can't detect that to my knowledge.

**Comment by TeamSpen210** [comment]
It does not reset, so that is a concern.

**Comment by Luke18033** [comment]
You could include logic to reenable laser collision at the start of maps with the option on, which would partially fix that issue. The problem is default PeTI maps and Hammer maps without the logic.

**Comment by Luke18033** [comment]
This is now implemented.
