### ISSUE TITLE
Overgrown destroyed ceilings?

### ISSUE THREAD

**Issue by harritron2k2** [BEEmod/BEE2-items#2052]
I haven't used this in a while, and I can't seem to find any item that makes an area in the ceiling with plants and sunlight. Is there any way to do this with the tools or will I need to export to hammer?

**Comment by Luke18033** [comment]
Currently there's no item like this, you'll need to use Hammer to make holes in the ceiling. Just *please* remember to full compile...

**Comment by harritron2k2** [comment]
Right, thanks for that.

**Comment by iEnderMan06** [comment]
Well, there is something I'd like to add to this - @Luke18033 @harritron2k2 There is an item actually in the works that does this :)

**Comment by Luke18033** [comment]
Are you referring to the Ceiling Light?

**Comment by iEnderMan06** [comment]
Nope

**Comment by ZombiePwner1** [comment]
@iEnderMan06 which item are you talking about?
