### ISSUE TITLE
A Few Suggestions

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2054]
_From @PorTalZ101 on June 10, 2017 18:5_

1. Maybe AEGIS Voicelines from Portal Stories: Mel
2. Diversity tubes e.g When you go in you come through the connected one at a certain velocity basically acting as a world portal
3. Cores I know it's impossible but My way might work there are cores you place around the map and you connect them to the core panels once placed in the panel the panel will activate something of your choice
4. Bottomless pit item
5. BTS Chambers style basically going around the outside of chambers on a catwalk above a bottomless pit and going through offices
6. BTS Old Aperture this would be cool going through the pumps and genorators and looking at the giant spheres
7. Portal Detector This would sense when a portal is on it activating something in your map

_Copied from original issue: BEEmod/BEE2.4#665_

**Comment by Luke18033** [comment]
This is a [BEE2-items](https://github.com/BEEmod/BEE2-items) issue.

**Comment by Luke18033** [comment]
1. We can't add custom voicelines unfortunately.
2. Already exists, it's called "Vactubes".
3. Already been suggested *many* times, please search before opening an issue.
4. Already exists, select the 3D Factory skybox (this is the default for BTS) and place goo at the bottom of the map.
5. This would be kind of hard to implement in PeTI.
6. Already been suggested.
7. Already going to be implemented, see #95.

**Comment by PorTalZ101** [comment]
Thanks for moving it I actually think it belongs here

**Comment by Endermage77** [comment]
People often make a mistake and put stuff on the wrong forum.

Don't worry about it too much; although do try to pay attention to which section you're posting under next time.
For your convenience:
BEE2 is for threads related to the actual BEE2 program and especially bugs with the BEE engine.

BEE2-items is to do with the items and styles and related stuff available in BEE2 as used in the actual game. That and the many, many, many, bugs, involving that stuff. 
For instance, not being able to enter portals on angled panels.

**Comment by PorTalZ101** [comment]
k thanks
