### ISSUE TITLE
Flip Activator/Fizzler/Pad

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2-items#2055]
This item would flip the player onto the roof making a chance for unique chambers (If this is possible)

**Comment by Luke18033** [comment]
What? Like, a gravity-changing button?

**Comment by PorTalZ101** [comment]
yes exactly like that

**Comment by PorTalZ101** [comment]
yes exactly like that

**Comment by Luke18033** [comment]
If Adhesion Gel can't be done in PeTi, neither can this.

**Comment by PorTalZ101** [comment]
@Luke18033 Ok I can understand

**Comment by iEnderMan06** [comment]
Well, this is a duplicate basically of the resizable world portal item.

**Comment by PorTalZ101** [comment]
adhesion gel was made it just made play testers sick

**Comment by Luke18033** [comment]
It was made by Valve, who has access to the source code. It's been replaced with Reflection Gel, and since we don't have the source code, we can't reimplement it properly. People have re-made adhesion gel using some tricks with rotating the map, but that won't work in PeTI.

**Comment by Luke18033** [comment]
Oh and also, I've used adhesion gel before, and it does NOT make me sick or disoriented. #ValvePlayTestersRuinEverything

**Comment by PorTalZ101** [comment]
Pity it would've been cool to see the communities come up with epic tests thats why I love BEE
