### ISSUE TITLE
How do you get Art Therapy And rotating Laser fields

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2-items#2057]
I'd like to know how to get Art Therapy
(Sorry if i'm Annoying)
Rotating Laser fields would help make a challenging chamber.

**Comment by Luke18033** [comment]
I've already suggested a rotating fizzler, which would also include a laserfield. See #1467.

**Comment by PorTalZ101** [comment]
@Luke18033 how do you get art therapy i'd like to know because I love that style

**Comment by Luke18033** [comment]
It hasn't been reimplemented yet.

**Comment by PorTalZ101** [comment]
@Luke18033 Ok thanks for letting me know but how come some people have it?

**Comment by PorTalZ101** [comment]
@Luke18033 Oh and so far it looks amazing

**Comment by Luke18033** [comment]
You can get it on the `art_therapy` branch, but it's extremely unfinished and might not even work in the latest BEE version.

**Comment by PorTalZ101** [comment]
it doesn't even exist
