### ISSUE TITLE
Portal 1 fizzlers cause a mysterious build error.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2058]
hreads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/p1/items/fizzler/fizzler_model.vmf

**Comment by ZombiePwner1** [comment]
No matter what i can't build a map in portal 1 style with fizzlers.

**Comment by iEnderMan06** [comment]
delete the BEE2 instances folder and re-export from BEEmod.

**Comment by TeamSpen210** [comment]
This has been rebuilt, so it won't happen for this reason.
