### ISSUE TITLE
A Few (NEW) Suggestions (Maybe Not New Some people MAY of suggested before) 

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2-items#2059]
Overgrown BTS style
Security door mostly seen in the loading screens in the BTS chapter
Friendly Turret (Noticeable by it's green eye and laser.) 
Wood planks(The friendly Turrets would shoot them and un-block what they're blocking.)
Broken tubes (These would leak gel out of them they can be placed on walls and ceilings with a skybox behind them.)
Skybox block
Rotating turret
Slightly Destroyed Style (Walls damaged every now and then, objects coming through the damaged walls, skybox would be the Aperture Abyss with chamber cubes randomly around the place.)
Incinerator Style you are doing test in an  Incinerator and goo is replaced with fire
Adhesion Gel (I know I know but it was made but it made some people sick)

AEGIS (I know yet again but even in English with no subtitles would be fine i.e if you have neurotoxin he would say organic lifeform detected draining oxygen)

**Comment by ZombiePwner1** [comment]
@PorTalZ101 Adhesion gel is not possible to do with the puzzlemaker due to the way people have remade it.

**Comment by PorTalZ101** [comment]
@ZombiePwner1 k but what about the others

**Comment by ZombiePwner1** [comment]
@PorTalZ101 I've suggested overgrown BTS awhile ago. Slighty destroyed style is pretty much reconstructing style.

**Comment by PorTalZ101** [comment]
@ZombiePwner1 what about the objects

**Comment by PorTalZ101** [comment]
Would Love AEGIS even in English with no subtitles would be fine

**Comment by PorTalZ101** [comment]
@ZombiePwner1 what reconstructed style?

**Comment by ZombiePwner1** [comment]
@PorTalZ101 Reconstructing style is a mix between overgrown and clean style. Seen in the single player campaign.

**Comment by PorTalZ101** [comment]
@ZombiePwner1 when will it be done

**Comment by Luke18033** [comment]
Overgrown BTS: Already been suggested.
Vertical Security Door: Already going to be implemented, see #95.
Friendly Turret: I don't think we can change the color of turrets' lasers without access to the source code. We could just make it a flashing laser though, like in the campaign. This doesn't really add any puzzle opportunities though so I don't think it'll be added.
Wood planks: This wouldn't make much sense outside of BTS.
Breakable vactubes: Already been suggested.
Skybox block: What exactly do you mean by this?
Rotating turret: I had an idea like this once, it would rotate in 360 degrees but couldn't fire upwards or downwards. The problem is it might be impossible without access to the source code.
Slightly Destroyed style: You mean like right after GLaDOS was destroyed?
Incinerator style: This is really the kind of thing you'll want to use Hammer for.
Adhesion gel: As @ZombiePwner1 said, we can't implement this in PeTI without access to the source code.

**Comment by PorTalZ101** [comment]
skybox block a block you place and it shows your selected skybox

**Comment by Endermage77** [comment]
Wooden Planks could probably be a special stylevar replacement for breakable glass.
The Skybox block used to be available in BEE2.2.5, although it didn't quite work properly.

**Comment by Luke18033** [comment]
You'd want a skybox tile, not a full block, that would just look bad...

**Comment by PorTalZ101** [comment]
@Luke18033 so use hammer

**Comment by Luke18033** [comment]
What? Doesn't that kind of defeat the purpose of BEE?

**Comment by PorTalZ101** [comment]
I dont have good hammer knowledge so I'll always use BEE

**Comment by PorTalZ101** [comment]
If you could, would you make a skybox tile
'cause i have no clue how to use hammer

**Comment by PorTalZ101** [comment]
By BEE is amazing I won't stop using it

**Comment by Luke18033** [comment]
Oh, I see. BEE2.2 already had a skybox tile which we could reimplement.

**Comment by PorTalZ101** [comment]
THX

**Comment by PorTalZ101** [comment]
I would like your opinion on this Chamber WIP/Chamber Manufacturing Style

**Comment by Endermage77** [comment]
Yeah, I meant skybox tile.

And wouldn't Chamber Manufacturing technically just be BTS?

**Comment by PorTalZ101** [comment]
You can look at if you want

**Comment by PorTalZ101** [comment]
It's different in the way you'll actually be in an unfinished chamber

**Comment by ellingtonvengaboysmuseum** [comment]
**Put these in individual issues instead,,,**

Overgrown BTS style - **Already Suggested**
Security door mostly seen in the loading screens in the BTS chapter - **In Process of being Implemented sometime in the future...**
Friendly Turret (Noticeable by it's green eye and laser.) - **Maybe**
Wood planks(The friendly Turrets would shoot them and un-block what they're blocking.) - Wouldn't be logical for bullets to be able to break wood, bombs would, also wood is not seen in aperture often,,,
Broken tubes (These would leak gel out of them they can be placed on walls and ceilings with a skybox behind them.) - Maybe
Skybox block - Not going to happen, Teamspen210 is overhauling Skybox Design
Rotating turret - Maybe
Slightly Destroyed Style (Walls damaged every now and then, objects coming through the damaged walls, skybox would be the Aperture Abyss with chamber cubes randomly around the place.) - **Maybe**
Incinerator Style you are doing test in an Incinerator and goo is replaced with fire - **Sometime in the Future**
Adhesion Gel (I know I know but it was made but it made some people sick) - **Not Possible**

AEGIS (I know yet again but even in English with no subtitles would be fine i.e if you have neurotoxin he would say organic lifeform detected draining oxygen) - **Long Term**

**# Case Closed and Locked...**

**Comment by Luke18033** [comment]
@ellingtonvengaboysmuseum What did I just say in #2061?

**Comment by Luke18033** [comment]
You can close the issues, just don't lock them. Also please don't delete other people's comments, that's a really easy way to lose your collaborator permissions.
