### ISSUE TITLE
Chamber WIP/Chamber Manufacturing Style

### ISSUE THREAD

**Issue by The-Apex-Typhon** [BEEmod/BEE2-items#2060]
The entrances would be an elevator or a catwalk into the chamber
Randomly generate holes in the walls with the skybox poking through
Choice to have a roof or not
Test elements would still be in construction e.g circle plates missing from cubes, droppers are vactubes, pedestal buttons would be the buttons from BTS.
Observation room would have no glass(Optional)
Yellow plates randomly on black walls
lights would be BTS lights
Fizzlers would be Old Apeture Style
The exit would be a metal Gate (Optional)
Skybox would be similar to 3D-factory but no walls just columns  
(A bit like Art Therapy but with the extra Features)

**Comment by PorTalZ101** [comment]
@Luke18033 what style if even is coming in the next update?

**Comment by Endermage77** [comment]
Ah, chamber <b>assembly</b>. Like that one bit in PS:Mel.
I imagine that this would basically be a Clean version of the open-style Old Aperture Chambers that are more or less nothing more than mid-air scaffolding.

**Comment by RedTronZ** [comment]
This kinda sounds like it would be a custom _"90s Aperture"_ style to me, like when the scientists at Aperture were constructing GLaDOS.

**Comment by Luke18033** [comment]
We're not doing new custom styles
