### ISSUE TITLE
Item Suggestions (Updated)

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2-items#2061]
Custom elements From Bring your Daughter To Work Day  http://steamcommunity.com/workshop/filedetails/?id=265054503
~Teleporter e.g put cube, player it goes to connected one when activated~
Audio Trigger (Select audio with timer, custom audio as well)
~I know it's not an item but Style Maker (You can: Texture Selection, Selection for Style of Elements, Elevator On/Off , Design hallway at start (Optional) e.g Hammer opens to Design, Select Skybox  IDK if suggested before)~
Flames ~or Lava (If possible) (Basically a re-textured Deadly Goo Item)~
Turret Button (Activates when a turret is placed on it)
~Funnel Detector~
~Object only Funnel (Only cubes ect. can be put in)~
~Laser on wall (Just a laser on a 1x1 wall)~
Hole in ceiling
Malfunctioning Living Panels (Slam against walls repeatedly, Rotate around, Try to get into wall, floor but gets stuck) 
Portal Pro Custom Items

**Comment by Endermage77** [comment]
1. Paint Gun is available in Aperture Tag. This mod has been worked to exclusively provide paint gun support for that.
2. If this becomes a thing, it would likely be a stylevar.
3. Flooding chambers is likely not possible.
4. Search around for time buttons. This has been talked about before, but I believe the consensus is still inconclusive.
5. What?
6. Before somebody comes around to give you an official answer, expect a flat "NO" for this one.
7. Define scaffolds in this case. Do you mean the Unstationary Scaffold, or catwalks, or literal structural scaffolding?
8. There is a breakable window item in the works (Dunno if it's already in fully) that is kinda like this. However, this item would probably have a couple problems on the drawing board (eg. what it is like in alternate styles).

**Comment by ellingtonvengaboysmuseum** [comment]
First... every single one of these should be listed as individual issues

Paint Gun is Locked to Aperture Tag Only

Terminals can only exist in BTS and Old Aperature somewhat, would be useless and ugly in the middle of a clean chamber...

Rising Liquids are too Buggy... Forget a Leaking Pipe...

Time Button is not possible and will not be made, teamspen210 already said this...

Explain more in a single issue...

Not going to happen

Explain More in a single topic

Would be Quite Hard to Do across all styles.


**Case CLOSED and LOCKED...**

**Comment by Luke18033** [comment]
@ellingtonvengaboysmuseum For the last time:

# Stop. Locking. Invalid. Issues.

If you don't stop doing this, I'm going to tell TeamSpen210 about it and you'll probably lose your collaborator permissions. Is that what you want?

**Comment by Luke18033** [comment]
Once again, don't delete other users' comments please.

**Comment by Luke18033** [comment]
1. Available in Aperture Tag as @Endermage77 said.
2. As @Endermage77 said this would probably be a global option.
3. I did have an idea for a Drainable Goo item but it's not really meant for this kind of thing.
4. @ellingtonvengaboysmuseum suggested this a lot I think. The only way I know of doing this requires you to enable cheats, and I don't think most players want to see "sv_cheats set to 1" appearing at the start of every BEE map with the item. I could be wrong though.
> *5. What?* - Endermage77
6. Not possible without the source code.
7. Be more specific, there are many kinds of scaffolding in Portal 2.
8. As @Endermage77 said, breakable glass is in development. However, this glass is intact at the beginning of the map and must be broken manually by the player. Pre-broken glass isn't a good idea - it wouldn't make sense in Clean, and in other styles it would mean that the test was meant to be solved years in the future. Destruction shouldn't be used as a test element.

**Comment by iEnderMan06** [comment]
Holy crap,  @ellingtonvengaboysmuseum can you please stop closing issues?

**Comment by PorTalZ101** [comment]
Updated Suggestions

**Comment by Luke18033** [comment]
If you're going to make a completely new set of suggestions, open a new issue.

**Comment by Luke18033** [comment]
Alright, since you don't seem to want to do that:
1. I haven't played this map yet, so I don't know what you're requesting. I'll play it soon though.
2. I don't think this would work very well, it would be better to use worldportal doors or autoportals.
3. Already been suggested. (#1169)
4. No, this really isn't necessary.
5. Lava doesn't really make sense in test chambers. A fire item has been suggested before.
6. I think Radelite made something like this for his old addons.
7. Don't think this is possible.
8. Also not possible.
9. What? Isn't this just a normal laser item?
10. Only really makes sense in Overgrown, where the Ceiling Light and (possibly) ceiling Cutout Tiles could be used to achieve this effect in future versions.
11. BEE2.2 had something like this. [Here](https://forums.thinking.withportals.com/post96952.html) is the original TWP thread for that item.
12. Did Portal Pro have anything custom besides the lifeform sensor?

**Comment by Endermage77** [comment]
For number 9 there, I think he means a laser mounted on a thin wall.

**Comment by Luke18033** [comment]
In that case it wouldn't be possible, since lasers need to embed 48 units and thin walls are 32 units thick.

**Comment by Luke18033** [comment]
Also for 11, #1583.

**Comment by Luke18033** [comment]
We don't allow combined issues anymore, most of these things have their own issues now.
