### ISSUE TITLE
Flux Field Issue: Won't make correct sound OR correct output.

### ISSUE THREAD

**Issue by PSIGuy** [BEEmod/BEE2-items#2065]
I'm creating a P1 style chamber and I'm having problems with the Rexaura Flux Field.  For some reason, it won't play the correct sound sound when an HEP goes through it, and instead plays the default error clip, "Oh fiddlesticks, what now?"  In addition to that the fizzler output relay also isn't performing it's output (it's connected to a victory lift, and there are 4 of them that do this).  The flux field, however, does change color when a HEP goes through it, as all the other flux fields for some reason.  I don't know if it's just me not setting up the outputs correctly or if BEE2 itself is to blame, but any help or suggestions would be appreciated.

**Comment by Luke18033** [comment]
I've already reported the sound error (#1615). Are you placing the relay directly on top of one of the emitters?

**Comment by PSIGuy** [comment]
Yes.  I'm putting them on four of them, actually.  They all control four separate victory lifts.

**Comment by Luke18033** [comment]
Maybe they need to go on the opposite emitter?

**Comment by PSIGuy** [comment]
Do you mean place the relays on the opposite side of the fields (the translucent side) or placing the relays on different emitters (they're in very close proximity to each other if that makes a difference).

**Comment by Luke18033** [comment]
I always place the relay on the translucent side of the field.

**Comment by PSIGuy** [comment]
Ok, I'll give that a try.  Before I do though, do you always connect the object you're trying to control directly to the fizzler output relay or do you put a logic gate or something else in between them?

**Comment by Luke18033** [comment]
I connect it directly but it would work either way.

**Comment by TeamSpen210** [comment]
I don't actually know if I set it up to work with multiple relays. But it should indeed work on any of the fizzler emitters, just make sure it's rotated the same.

**Comment by PSIGuy** [comment]
Ok I'm going to rebuild the entire puzzle and see if that makes a difference.  If it doesn't, I'll change the puzzle to make it work with just one relay.  Thanks for the help.

**Comment by PSIGuy** [comment]
I could also try to mess with the outputs in Hammer to see what's wrong as well.

**Comment by PSIGuy** [comment]
I figured out what I was doing wrong, and honestly I feel pretty stupid now.  On the victory lift, there is a "auto drop first cube" checkbox that's automatically checked when you place it into a level.  As it turns out, this checkbox makes it so that, when checked, it will only activate when the player is on it.  I had the box checked on all the victory lifts I was using, so that was the problem all long.  Sorry about that.  By the way @TeamSpen210 , the flux field IS set up to work with multiple relays.  The only problem now is the missing sound.
