### ISSUE TITLE
Duplicate Overgrown Positron Energy Orb

### ISSUE THREAD

**Issue by QuantiX999** [BEEmod/BEE2-items#2070]
Missing texture in the overgrown style:
![620_20170616160404_1](https://user-images.githubusercontent.com/19597328/27228186-375056d2-52af-11e7-9625-840e349ac9b7.png)
Closed solid field is missing textures...?
![620_20170616160425_1](https://user-images.githubusercontent.com/19597328/27228224-67c5d756-52af-11e7-8cb4-5add3a6da5b4.png)
Are there supposed to be two of them? I don't think so.
![620_20170616161321_1](https://user-images.githubusercontent.com/19597328/27228241-7ad6636a-52af-11e7-9d6a-e92cff14283e.png)

**Comment by Luke18033** [comment]
The first two bugs have already been reported (#1938 and #1918).
