### ISSUE TITLE
Cubes missing collision with Grating (Overgrown)

### ISSUE THREAD

**Issue by ImDaveead** [BEEmod/BEE2-items#2072]
I have only tested the Overgrown Style, but cubes just go right through grating, but not glass.![ezgif com-
video-to-gif 2](https://user-images.githubusercontent.com/24465214/27263092-3a9259e8-5431-11e7-82f6-5d1a48edc5ad.gif)

**Comment by ZombiePwner1** [comment]
Duplicate of https://github.com/BEEmod/BEE2-items/issues/1929
