### ISSUE TITLE
Angled Block´s diagonal face doesn´t rotate

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2075]
![20170624111953_1](https://user-images.githubusercontent.com/12244376/27509265-2c312c1a-58cf-11e7-8eab-1b362776ba8d.jpg)

**Comment by ZombiePwner1** [comment]
This wouldn't look right if it faced the correct way so this is intentional.

**Comment by Luke18033** [comment]
It looks very wrong currently.
