### ISSUE TITLE
Idea: De-Stylizer/Re-Stylizer

### ISSUE THREAD

**Issue by MisterSakamoto** [BEEmod/BEE2-items#2076]
When placed over an item, like a cube or button, it would put the default style version (maybe a different style version?) in the editor.

Example of de-styled item:
You place a button in the editor for the BTS style and place a de-stylizer on it. Instead of the 'weight checker' thing, it would have a regular test chamber button.

Example of re-styled item:
You place a cube in the editor for the regular style and place a re-stylizer on it. You change the cube type on the re-stylizer, and it would have a 1950s/portal/overgrown/etc. 1 cube instead

**Comment by TeamSpen210** [comment]
That would be inconsistent and odd in 99% of cases. It's also rather difficult to do - lots of items often expect that they only use a specific version of another item, or otherwise can't swap safely.

**Comment by Endermage77** [comment]
There isn't really any proper "default" style, unless you are thinking about the "Portal 2" style that's normally used in non-BEE2 test chambers.
If such a tool were to be implemented, it would likely see more traction as a "Restylizer" that can swap between any two styles.

**Comment by LautaroL20** [comment]
As TeamSpen210 said, this would be pretty much inconsistent and odd in 99% of cases, would cause many fiddles and its not much of a good idea to implement.
