### ISSUE TITLE
P1 Fizzler / Laserfield editor models are unstyled

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2079]

**Comment by TeamSpen210** [comment]
This might look reasonable if we simply remove the black shroud, and fix any holes.

**Comment by LautaroL20** [comment]
Now implemented.

![Portal 1 Fizz / Laserfield Editor Models](https://user-images.githubusercontent.com/12244376/28467464-65fa577c-6e06-11e7-8458-c69bffbec9d8.jpg)
