### ISSUE TITLE
Idea: Style merging map exits.

### ISSUE THREAD

**Issue by Reiid** [BEEmod/BEE2-items#2080]
This idea is based off of a few workshop maps that need to bridge many map styles together. This could help in making multi-style multi-map campaigns without hammer.

Examples would be:

Clean/Overgrown to BTS: A few opened panels in the exit hall leading to one of those security door rooms.

BTS to Clean/Overgrown: An elevator checkup point or something.

Clean/Overgrown to Old Aperture: Normal, but with old elevator going down.

Old Aperture to Clean/Overgrown: Normal, with a new elevator.

BTS to Old Aperture: One of the floor drop holes seen in co-op.

Old Aperture to BTS: I don't know here.

If you have ideas on how this could be improved, tell me!

**Comment by TheLoafLord** [comment]
Old Aperture BTS could be those little reception areas, or something like that where you exit the sphere. That wouldn't work but, because it'll look weird having test elements in an office/reception space. Maybe make it like those warehouse sections of the Old Aperture. TBH I don't know. I like your ideas but.

**Comment by Endermage77** [comment]
Old Aperture ---> BTS may involve a catwalk that splits away from the exit (Inaccessible due to decayed catwalk), and into a small office area with a lift like that one that you can use early on in chapter 6.

**Comment by ThatOneRetro** [comment]
It would still give a feeling of progress to a set of test chambers though, regardless of story

**Comment by Luke18033** [comment]
Puzzlemaker isn't really designed for series of maps, and seeing the exact same style transitions over and over would get pretty repetitive.
