### ISSUE TITLE
BEE 2.4 PRL25 CRASH!!! "PermissionError: [WinError 5] Zugriff veweigert: ´d:\\program files (x86\\steam\\steamapps\\common\\portal2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\bee\\drawbridge ´

### ISSUE THREAD

**Issue by Flo2912** [BEEmod/BEE2-items#2081]
![grafik](https://user-images.githubusercontent.com/19980844/27710033-8b911398-5d1e-11e7-839f-df2237f37408.png)

I get this Error everytime I try to export something with Bee 2.4 Pre 26 to Portal 2, had the same issue with Pre 24 as well. It seems that trying to export it breaks the folder that is named in the issu, since I can't open thix folder anymore, nor can I delet or rename it. When I restart my Computer, the folder is vanished and reapperas after the next export try, however than anoter folder takes its place of disfunction and it crashes again. And older version of Bee 2 seemed to work well, while it allways got an "Can't create File that already exists" error, so I had to unpack the packages all by myself (Only knew where to pack items and resources, as result it worked but hat some things like voice-lines missing), however since I startet pre26 this old application version doesn't want to launch at all.

**Comment by LautaroL20** [comment]
> Flo2912I Said: "I get this Error everytime I try to export something with Bee 2.4 Pre 26"

Pre-release 26 is not out yet... Also this section is related to Items only, you must report interface stuff related on this repository: https://github.com/BEEmod/BEE2.4/issues

This issue has been moved to: https://github.com/BEEmod/BEE2.4/issues/676
