### ISSUE TITLE
P2 Drawbridge is very buggy.

### ISSUE THREAD

**Issue by BluCodeGH** [BEEmod/BEE2-items#2082]
I have noticed a number of bugs with the drawbridge.

Firstly, the preview of the drawbridge in the editor does not update when the `Start enabled` box is checked or unchecked, as seen here:

![screenshot 1 (unchecked)](https://user-images.githubusercontent.com/22122986/27714490-327752b4-5cff-11e7-8b81-eca2358cf457.png)
![screenshot 2 (checked)](https://user-images.githubusercontent.com/22122986/27714491-35723024-5cff-11e7-9979-4e852c6affce.png)

Secondly, the `Start enabled` checkbox should be reversed, as when the bridge is to 'start enabled' it starts raised rather than lowered. If the checkbox's effect was reversed then it would agree with the `Connection missing` warning which only appears when it is unchecked, or *should* be raised, as can be seen above.

Thirdly, when the player dies or loads a quicksave the bridge's state is set to raised, whether it is powered or not. This can be updated by dis-powering and re-powering it, but that should not be necessary. This is documented below.

![Before reloading](https://user-images.githubusercontent.com/22122986/27714664-5f5471b2-5d00-11e7-9919-8460e6fe3517.jpg)
Above I have powered all three drawbridges and performed a quicksave, but not reloaded to it.

![After](https://user-images.githubusercontent.com/22122986/27714677-79abae5e-5d00-11e7-89ed-4d3d56c9bdfa.jpg)
This is after reloading the quicksave; the bridges are powered but raised.

One last undocumented issue: I have heard (but not tested) that is is possible to get stuck in a drawbridge by being on it and walking towards the end as it is raising. Hopefully you will be able to solve most if not all of these bugs in the next release.

**Comment by Luke18033** [comment]
We currently can't change models based on whether or not a property is enabled.

**Comment by BluCodeGH** [comment]
I see. Luckily that is the least important of the bugs. Any hope for the others?

**Comment by Luke18033** [comment]
Yes, those can and will be fixed.

**Comment by LautaroL20** [comment]
Those drawbridges doesn´t look good without an embedded boxel...

**Comment by Luke18033** [comment]
That's the point of the drawbridge - it doesn't embed, and retracts up instead of down. Possibly though it could be improved by switching the wall to a backpanel texture when on a non-portalable surface.

**Comment by Luke18033** [comment]
It turns out that it is indeed possible to change the model based on a property's state, meaning issue 1 is fixable.
