### ISSUE TITLE
Visible logic gates have incorrect textures.

### ISSUE THREAD

**Issue by BluCodeGH** [BEEmod/BEE2-items#2085]
The OR and XOR visible logic gates do not have the correct texture. There is a standard design for drawing logic gates which only the AND gate follows. The logic gates *should* look like this:

![corrrect gates](https://user-images.githubusercontent.com/22122986/27743575-78015fb0-5d8a-11e7-8904-68ddd6f3b037.png) 

But they instead look like this (left to right XOR, OR, AND):

![preview0004](https://user-images.githubusercontent.com/22122986/27743639-b359b148-5d8a-11e7-9944-d95779caf142.jpg)

This is hopefully an easy fix which should greatly improve the clearness of the logic gates.

**Comment by TeamSpen210** [comment]
According to [Wikipedia](https://de.wikipedia.org/wiki/Logikgatter#Typen_von_Logikgattern_und_Symbolik), these are actually old German designs for gates.

**Comment by BluCodeGH** [comment]
I see. Would it be possible to add an option to either have text labels (AND/OR/XOR) or to use the alternate designs?

**Comment by Konclan** [comment]
Text is never good in maps

**Comment by BluCodeGH** [comment]
True, but maybe the alternate symbols would be beneficial.

**Comment by Blacksilver42** [comment]
Might it be possible to make "Logic gate style" an option in the style settings?

**Comment by TeamSpen210** [comment]
That would make it the first time I make available more than 2 variants for an item.

**Comment by Endermage77** [comment]
There's always a first for everything, eh?
