### ISSUE TITLE
Force open Exit doors

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2090]
If the Portal 1 Exit door is set to Start Enabled, it changes to a door frame that does not close if you pass.

Having this option for other styles would be nice as a stylevar for the normal doors if you want to give the option of reentering the chamber to players.

**Comment by ZombiePwner1** [comment]
Actually this is a bug. start enabled is mean't to keep the door closed but start disabled keeps it open but the logic has been mixed up with the portal 1 exit door.

**Comment by TeamSpen210** [comment]
There's no real reason to have that - you've won by then, you have no real reason to walk back inside the chamber.
