### ISSUE TITLE
High Energy Deflector

### ISSUE THREAD

**Issue by TheLoafLord** [BEEmod/BEE2-items#2091]
A fizzler (Yellowish Orange, with a circle pattern.) that blocks HEPs, and HEPs only. Does not fizzle cubes or block portal shots or reset portals. HEPs bounce off it when active. When unactive, HEPs are not effected.

A variant of this could be a High Energy Deflection Detector (???.), a gate that detects when a HEP bounces off it. Requires use of the fizzler output item.

**Comment by hop193** [comment]
but the Closed Solid Feild is Gray...

**Comment by TheLoafLord** [comment]
closed solid field is light grey isn't it?

**Comment by ZombiePwner1** [comment]
@TheLoafLord It doesn't matter if it's light gray or not it would easily get mixed up with your field so i'd suggest you make it a different color.

**Comment by Luke18033** [comment]
I'm not sure if this is possible. I'll try making it in hammer once LB's stream is over.

**Comment by TeamSpen210** [comment]
You can just filter the pellet with a `func_clip_vphysics` - use `@filter_pellet`. I think this should have a circle motif or something reminding you of pellets...

**Comment by Luke18033** [comment]
That's what I was thinking.

**Comment by TheLoafLord** [comment]
uh how about pink? i dont think pink is used... so pink it is.

**Comment by Luke18033** [comment]
No, pink will be used for the Liquid Coloring Excision Field (a better-looking version of the paint fizzler) in a future version. It should be yellowish-orange, with a circle pattern.

**Comment by TheLoafLord** [comment]
ok, sounds good

**Comment by Konclan** [comment]
Why would this be useful? Pellets are barely used as they are and there are many ways to work around this problem in a test. Considering Pellets only move in directions you allow the player to move them.

**Comment by Konclan** [comment]
We're not adding more fizzlers
