### ISSUE TITLE
Glass frames are not solid

### ISSUE THREAD

**Issue by awesomedoctorx3** [BEEmod/BEE2-items#2092]
portal shots can be fired through the borders of glass panes, as seen here: 
https://youtu.be/6LS5tib7EWs
An easy fix would be to add nodraw brushes to the borders.

**Comment by ZombiePwner1** [comment]
The reason why this is because the glass borders models aren't solid because someone disabled their collisons.

**Comment by awesomedoctorx3** [comment]
They have never had collision, in default editor it behaves the same.

**Comment by ZombiePwner1** [comment]
@awesomedoctorx3 They do have collisions but valve edited the properties to make them non-solid all @TeamSpen210 needs to do is make them solid and that fixes this issue.

**Comment by TeamSpen210** [comment]
Long since fixed
