### ISSUE TITLE
Will there be an update of the bottomless pit?

### ISSUE THREAD

**Issue by vega227** [BEEmod/BEE2-items#2093]

**Comment by LautaroL20** [comment]
As for "Abyss", you mean Bottomless Pit?

**Comment by vega227** [comment]
@LautaroL20 Yes

**Comment by LautaroL20** [comment]
Well, i do not have idea then. I am also agree to the fact that the current Bee´s Bottomless Pit does require some improvements since actually it looks a bit mediocre.

**Comment by Luke18033** [comment]
Was using caps really necessary?

**Comment by Luke18033** [comment]
Also, it'd really be a good idea to use [Discord](https://discord.me/beemod) for questions like this, to avoid opening unnecessary issues.
