### ISSUE TITLE
Positronic Energy Attractor

### ISSUE THREAD

**Issue by TheLoafLord** [BEEmod/BEE2-items#2094]
An item that pulls HEP's toward it and destroys it. Basically an item variant of the Positronic Energy Orb. The energy orb on the claw will be red. Will have the ability to change its active state. When off, the energy orb will be blue. When on, the energy orb would be red. I choose those colours because they reminded me of magnets poles. When off, the PEA (What a acronym.) will obviously not attract HEP's and vise versa.

**Comment by Konclan** [comment]
UCP
