### ISSUE TITLE
Cube sendificator antlines display as mysterious white textures for those who don't have beemod

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2095]
I took this screenshot from the community but it should still be fixed

![sendtor_antlines](https://steamuserimages-a.akamaihd.net/ugc/838084056388723991/5172F49A5F91431CB92CC4A7514026E59343CD47/)

**Comment by Luke18033** [comment]
Updated issue: Image now embedded using markdown.
