### ISSUE TITLE
Radiative Flux Rectangle´s frames are being generated inside the Blocks

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2097]
![Image](https://user-images.githubusercontent.com/12244376/28490474-3c822a9a-6eb1-11e7-9e69-e17e61e3ca06.jpg)

**Comment by TeamSpen210** [comment]
Oops, I need to copy over the new instances.

**Comment by LautaroL20** [comment]
Fixed?

**Comment by TeamSpen210** [comment]
Should be.
