### ISSUE TITLE
The instance of the Standing Fizzler does not appear in the map anymore

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2099]
![Image](https://user-images.githubusercontent.com/12244376/28490542-e14abbae-6eb2-11e7-91a7-57f38796cf2e.jpg)

**Comment by ZombiePwner1** [comment]
@LautaroL20 LOL

**Comment by Luke18033** [comment]
Looks like the standing fizzlers still have quite a bit of work to be done.

**Comment by Luke18033** [comment]
I'm assuming this isn't a problem anymore?

**Comment by LautaroL20** [comment]
Wow, i do not have idea why i did not notice that i had this issue open because i fixed it since a long time ago.
