### ISSUE TITLE
Physics Repulsion Field, Death Fizzler, Closed Solid Field and the Paint Fizzler causes "Failure To Compile"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2100]
![Image](https://user-images.githubusercontent.com/12244376/28490600-8734e390-6eb4-11e7-9e3a-109cde282e01.jpg)

**Comment by TeamSpen210** [comment]
Yep, because I deleted the old code for them and haven't converted them.
