### ISSUE TITLE
Old Aperture Neurotoxin Screen Models Missing

### ISSUE THREAD

**Issue by HelloIamapersonthatisalive** [BEEmod/BEE2-items#2105]
![20170727135323_1](https://user-images.githubusercontent.com/22359596/28691791-0ad2ecd4-72d3-11e7-8595-1e1fa8cb7ec4.jpg)

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Spencer pls.

**Comment by TeamSpen210** [comment]
This is fixed in bc348d8fbd8b7c09c4cd5fed703d51068154e013.

**Comment by HelloIamapersonthatisalive** [comment]
Thank you very much!

**Comment by TeamSpen210** [comment]
Somehow I forgot to actually include them.
