### ISSUE TITLE
The fixed Glass Panel gets packed as a "Mysterious Blue Error"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2106]
![20170727233259_1](https://user-images.githubusercontent.com/12244376/28700123-2be60ca2-7324-11e7-9b37-cd9ef23e91c5.jpg)

**Comment by ZombiePwner1** [comment]
@LautaroL20 LOL U WHEELY

**Comment by LautaroL20** [comment]
Now fixed, it seems that the closing brakets are a truly mystery respect on how they works.
