### ISSUE TITLE
Closed Solid Field broken in P1 style

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#2108]
![20170728135417_1](https://user-images.githubusercontent.com/22107242/28732218-b159bc3a-739c-11e7-8afa-091703ff361f.jpg)
Specifically, the CSFi does not render a field, block player interaction, and will fizzle portals when passing through it.

**Comment by Luke18033** [comment]
Duplicate of #1519.
#DuplicatedYourOwnIssue
