### ISSUE TITLE
New Textures, Camera

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2110]
ORIGINAL POST BY @floriscnossen: https://github.com/BEEmod/BEE2.4/issues/700

_____________________________________________________________________________________________________

@floriscnossen has suggested:

"These are my suggestions. The second one is probably impossible to add in the mod, but I think it would be awesome.
1.	New textures for Atlas and P-body for Old Aperture (A bit like the old turrets maybe?)
2.	An addition to the camera item that, when activated, can also display its view on the full screen (in addition to only in-game monitors). 
This could be useful for cinematic shots or to give attention to things you wouldn’t normally notice.
The timer could be used to determine when to switch back to the normal first person view. (Infinity could mean: until it is deactivated)
The button type value could be used to select the place to display:
•	Weighted: Monitors in maps (current)
•	Cube: The full screen
•	Sphere: Only 1 player in Coop maybe? Start reversed determines which player"

**Comment by ZombiePwner1** [comment]
@floriscnossen It is not possible to change the textures of atlas and p-body for old aperture styles atleast from what i'm aware of i think if you try to do this the game will crash.

**Comment by TeamSpen210** [comment]
It is theoretically possible to pack and then swap those perhaps, but it's kinda pointless... I assume they're dropped in from Modern Aperture, not from Old Aperture. It doesn't make sense they'd be built there.

**Comment by floriscnossen** [comment]
@TeamSpen210 Yeah, you're right.

**Comment by Endermage77** [comment]
The camera view idea is fairly interesting: It would definitely be a boon for those mapmakers who are having trouble trying to point out things to the player that would not be immediately obvious.
Speaking of cameras, is the old detachable camera going to be coming back eventually?

**Comment by Luke18033** [comment]
The problem is that it's kinda unrealistic to have your view just randomly teleport somewhere, use Hammer if you want that sort of thing. The detachable non-screen camera is coming back eventually, in fact I'm surprised it still isn't implemented by now.

**Comment by TeamSpen210** [comment]
This doesn't seem too useful.
