### ISSUE TITLE
Beemod causes "Failure To Compile"

### ISSUE THREAD

**Issue by ThePootisBird** [BEEmod/BEE2-items#2111]
There is a bug in BEEMOD where when i try to rebuild a test with it, it has a error

can you fix this plz.

**Comment by Luke18033** [comment]
What's the error?

**Comment by Endermage77** [comment]
Press the ` key next to the 1 key on your keyboard to open the console.
And make sure the Dev Console Enabled option under Keyboard Control is enabled.

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
