### ISSUE TITLE
 Dynamic Camera

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2113]
A variant of the regular camera item that will pick a random object in front of it and lock onto it until it either gets destroyed, moves out of sight, gets deactivated (static objects), or the camera gets deactivated.
It will pick objects in this priority (More or less, can stand to take some leeway):
1. Players
2. The Exit Door(Or a random one if there is more than one visible)
3. Important Static Objects (Door, Piston, Scaffold, Portal Gun Pedestal, Autoportal, Neurotoxin Timer
4. Hazards (Turret, Rocket Turret, Crusher, Laser Grid, Goo)
5. Special Items (Franken, Companion, Reflective, HEP)
6. Standard Items (Cube, Sphere, Futbol)
7. Special static objects (Sendificator, Diversity Vent, PEO, Cube Deflector, Faith Plate, Conveyor)
8. Standard static objects (Fizzlers, Dropper, Gel Dropper, Laser Emitter, Funnel, Bridge)
9. Activators (Buttons, Laser/HEP Catchers. Futbol Socket, Pedestal Button, Conductive Plate)
10. Points of Interest (Portal Magnet, Surface Marker Entry Door, Signs, Neurotoxin Vent, another Camera, Monitor,)
If there is nothing to look at (somehow), then it will look at random points in its line of sight.
As an optional thing to do, it could possibly try to trace the  trajectory path of the faith plate it locks onto. Or simply glance between it and its landing spot.
It will NOT look at chamber geometry  or non-solid items (eg. Catwalk, walls, thin walls, glass, angled blocks, panels, lights, logic blocks, e.t.c.)
If the target is far away or hard to see properly, maybe perhaps it will try and zoom in on it for increased clarity on monitors?

Another idea would also be a camera variant that can be connected to a specific item and then track that one item as best it can the whole time.

**Comment by Konclan** [comment]
Similar to #912, I'm not sure its possible or even necessary to make a camera this complex

**Comment by Luke18033** [comment]
Yeah this seems like a huge amount of effort for something which isn't really useful. We'd basically have to reimplement the camera rotation logic ourselves using posecontrollers, since the specific camera entity is hardcoded to only look at players.

**Comment by Luke18033** [comment]
Also why are closed issues purple now...?

**Comment by FrozenDragon0** [comment]
> Also why are closed issues purple now...?

Might be a change that github has made possibly.

**Comment by Luke18033** [comment]
It is, just kinda weird.

**Comment by LautaroL20** [comment]
> > Also why are closed issues purple now...?
> 
> Might be a change that github has made possibly.

Interesting, at first I thought for a moment that this color change was due to a weird decision from the owner or from some member with high permissions from the BEEmod organization, but if we take a look to another Github repository from something else, it is the same... a really dumb decision from the Github team, red color for closed issues fitted really well.

**Comment by TeamSpen210** [comment]
See here for why: https://github.com/github/roadmap/issues/289
