### ISSUE TITLE
Deflecting Cubes not always fizzling after HEP impact

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#2114]
I had this issue reported for my latest map, which uses the Rexaura deflector.
> Not that it matters(?) but, in the second puzzle, *sometimes* the second cube is not destroyed after contact with the HEP!?!

The puzzle involves placing two cubes on the deflectors, but, after playing it myself and watching others play it, I have come across the occasional error that one or both of the cubes do not fizzle after HEP impact. From what I've seen, this usually happens if the cubes have respawned several times. I could not find any error in the logs, but I will post them here if I come across this issue again.

Here is a screenshot of the room:
![image](https://user-images.githubusercontent.com/22107242/28760314-a832f48e-756b-11e7-855a-08455386762f.png)

**Comment by TheLoafLord** [comment]
can you link me your level please?

**Comment by TeamSpen210** [comment]
This has been fixed.
