### ISSUE TITLE
Cooperative Exothermal Emancipation Grid

### ISSUE THREAD

**Issue by TheLoafLord** [BEEmod/BEE2-items#2120]
Don't ask what exothermal is. I just put it in the title to make it sound cool haha.

Anyways, this is a fizzler that can be configured to affect either ATLAS or P-Body. This would be toggled by fizzler and laserfield. Fizzler being ATLAS, and laserfield being P-Body. Colour would be blue circles for ATLAS, and orange circles for P-Body.

**Comment by y0sh100** [comment]
That sounds good and Nice!

**Comment by ZombiePwner1** [comment]
@TheLoafLord I'm not too sure if this is possible to do but @TeamSpen210 Might figure a way to do this.

**Comment by TheLoafLord** [comment]
ah sounds good to me

**Comment by IceTudor** [comment]
Seems useful!

**Comment by TeamSpen210** [comment]
I'm not sure if this is possible. Maybe using the logic for the Absolute Fizzler, but that won't trigger the gun properly.

**Comment by DrMeepster** [comment]
I think a better fancy word would be "Monoselective" instead of "Exothermal"

**Comment by Konclan** [comment]
@TeamSpen210 what if you used the Matter Inquisition Field logic to block portal shots and then detect when the certain coop player is walking through/near the fizzler and turn on the fizzler. It wouldn't work for if both players try going through at the same time but its probably close enough.

**Comment by TeamSpen210** [comment]
I'd want to do it properly, and not have that exact issue.

**Comment by Konclan** [comment]
Also I think those could work like the death fizzler where you can change which player it affects by inputs. This would allow for some pretty clever cooperative puzzles.

A name I could suggest (because Exothermal doesn't relate to its function) could be the Solitary Exclusion Fizzler

**Comment by Endermage77** [comment]
This sounds like a duplicate but I can't place my finger on where that other post was.

**Comment by Konclan** [comment]
We're not adding more fizzlers
