### ISSUE TITLE
Cubes can be sendificated into the Old Aperture laser embed space, blocking the laser from inside

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2125]
![20170802205046_1](https://user-images.githubusercontent.com/19228201/28905248-8ce20142-77c4-11e7-8b4a-121a628ec8af.jpg)
This can be done by aiming a reflection cube back at the emitter, and placing it directly in front.

**Comment by ZombiePwner1** [comment]
Lol spencer pls.

**Comment by TeamSpen210** [comment]
Technically it's working fine, that is indeed glass in the front. Except you shouldn't be teleporting into there.

**Comment by LautaroL20** [comment]
This is fairly easy to fix, all we need is a `func_brush` clip in that area.

**Comment by TheLoafLord** [comment]
wow...
