### ISSUE TITLE
Reepblue gel cube

### ISSUE THREAD

**Issue by ncrecc** [BEEmod/BEE2-items#2126]
Left click while holding them to fire a certain type of gel, and right click to fire cleansing gel. [A Little Higher](http://steamcommunity.com/workshop/filedetails/?id=74176112) was all about this with blue gel.
Weighted/Cube/Sphere could be used for Repulsion, Propulsion and Conversion.

**Comment by Endermage77** [comment]
Soo basically a handheld gel cannon. An interesting idea that hopefully doesn't coincide too much with Aperture Tag's paint gun.

**Comment by Byzarru** [comment]
Only by 20 days. Motanum's map came out on May 8, 2012 and Reepblue's map came out on May 28, 2012. This element allows an important mechanic that Aperture Tag never could provide: You can place portals wherever you want!

**Comment by TheLoafLord** [comment]
maybe we could make some kind of custom design for it? because lets face it, it could look more visually appealing.

**Comment by Endermage77** [comment]
I, for one, would certainly love to have this around so I can actually paint gel-run courses thoroughly without having to use a dropper or drop the use of the portal gun (until somebody takes a look at my Gel floor idea in #1510).

**Comment by Endermage77** [comment]
As for design, perhaps it could be a cube with glass panels, filled with the gel that it dispenses, and also features a nozzle on one side so it can spray the contained gel?

**Comment by King0191** [comment]
Was this ever implemented? And if so, Was it removed? Cause this seems like a cool idea that gained a lot of attention

**Comment by ncrecc** [comment]
This was in the original BEE2.2

**Comment by Konclan** [comment]
UCP
