### ISSUE TITLE
Gravity Manipulation Field

### ISSUE THREAD

**Issue by TheLoafLord** [BEEmod/BEE2-items#2128]
A box like field, similar to the Portal: Prelude's Electricity Field and Gravity Outline. Except it would be a gravity field, not an electric field.

Except instead of the 2 recesses, it has one. The face opposite from the recess is what face you will be pulled towards.

I'm not sure if this is possible but it would be nice.

**Comment by Endermage77** [comment]
It wouldn't be able to work very easily if you wanted it to affect players (Lots of crazy map and coding hacks go into that stuff), but if you just want it to pull in other stuff I'm sure it could work just fine.

Alternatively, you could make it work like an excursion funnel area, _maybe?_
