### ISSUE TITLE
Beemod has basically ruined my copy of Portal 2

### ISSUE THREAD

**Issue by TheLoafLord** [BEEmod/BEE2-items#2129]
I can't play Co-op Chambers, I can't play downloaded single player maps without getting an error, I've been 'locked' out of my own chamber list, because whenever I try to open it, Portal 2 crashes, I keep getting build errors, freezing, crashes, and so much more. And I believe Beemod is to blame. I still love Beemod, I'm just pissed off. I can't even access my chambers anymore.

**Comment by ZombiePwner1** [comment]
@TheLoafLord I'd love to help out however i'm unsure would could be causing your issues with portal 2 since i've never experienced this issue on my own copy of portal 2.

**Comment by ncrecc** [comment]
On steam, right click the game, properties, local files, verify integrity of game files.

**Comment by Endermage77** [comment]
Yeah, verifying game files should generally be your goto if Portal 2 starts acting up.

**Comment by TheLoafLord** [comment]
I've verified it and I STILL can't access my levels... I'm pretty frustrated.

**Comment by Byzarru** [comment]
Issue moved to [BEEmod/BEE2.4 #705](https://github.com/BEEmod/BEE2.4/issues/705) via [**ZenHub**](https://www.zenhub.com/)
