### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by TREVTRPD** [BEEmod/BEE2-items#2130]
VBSP failed.

Valve Software - vbsp.exe (Jun 28 2017)
4 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/clean/items/neuro/vent_white.vmf

**Comment by TREVTRPD** [comment]
Valve Software - vbsp.exe (Jun 28 2017)
4 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/clean/items/lautaro/protrude_ped_mid_white.vmf

**Comment by LautaroL20** [comment]
I will help you out through steam, i think i know why Bee´s compiler gone nuts.  The solution to this annoyance:  

You will have to manually delete the following folders from Portal 2: bee2 (located at "Portal 2\sdk_content\maps\instances"), bin and bee2 (located in the main Portal 2 folder). After this, verify the game cache files, then launch Bee PRL26 and make it to export the full resources. Now you should not get those weird issues anymore.
