### ISSUE TITLE
Thought of a possible way to implement pages.

### ISSUE THREAD

**Issue by PKYXYZ** [BEEmod/BEE2-items#2135]
So, I've heard adding a scroll bar or adding more items would be impossible due to the hardcoded limitations of portal but I think I have an idea that might work. (I've never worked with Portal 2 modding before so bare with me.)

Maybe you could add a 'Next Page' and 'Previous Page' Item. In the BeeMod application they'd work the same as normal items, just put them on the grid wherever you want to. But in game clicking these Items would clear all items in the editor panel (except the Next and Previous page items) and replace is with another BeeMod Pallete (Possibly though the already present "change defaults" option)

This was just an Idea I had, it's probably been suggested at least once or twice before, but I figured by the off chance it wasn't than I should probably post it.

**Comment by Luke18033** [comment]
Unfortunately, this isn't possible. The game needs to be restarted to update palette items.

**Comment by TeamSpen210** [comment]
If we could update them while it was running, I'd definitely do something like this, or probably actually write an application which displays left/right arrows onscreen with another window.
