### ISSUE TITLE
Make an option for 1500 Megawatt Aperture Science Heavy Duty Super-Colliding Super Button/Laser Catcher/Laser Relay/etc. stay active when activated once (permanently or on a timer)

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2136]

**Comment by Luke18033** [comment]
You can already do this - use an SR latch to turn on the output permanently, or a Deactivation Delayer to turn it on for an amount of time.

**Comment by TeamSpen210** [comment]
I specifically implemented the latter item as a seperate logic item, so it's combinable with any other item.
