### ISSUE TITLE
Raised panels

### ISSUE THREAD

**Issue by ncrecc** [BEEmod/BEE2-items#2138]
A tile that slightly extends out of whichever surface it's on, but not by a whole block.
![Rexaura](https://image.prntscr.com/image/d-w9JdkyQGOUo9Uv6aJc_A.png)
Optimally this would be able to overlap with the portal placement helper.

**Comment by Endermage77** [comment]
I believe most of the decorative elements can overlap fairly easily with most of the items (with some exceptions, especially fizzlers: they hate everybody). I approve of this motion.

**Comment by IceTudor** [comment]
Yes! Been waiting for theese.

**Comment by Endermage77** [comment]
They aren't actually in the mod, mind you.
They're simply a very good idea.
