### ISSUE TITLE
Cube Catcher not appearing

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2140]
_From @Byzarru on February 23, 2017 1:44_

![20170222185743_1](https://cloud.githubusercontent.com/assets/22107242/23241184/4de60ecc-f937-11e6-9ce7-0a19e568ac61.jpg)
It could be that this is overgrown and the style likes to act funny, but...
![20170222185756_1](https://cloud.githubusercontent.com/assets/22107242/23241195/58d49fec-f937-11e6-972f-cab81325d8c5.jpg)
This is in the same map.

_Copied from original issue: TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#20_

**Comment by Luke18033** [comment]
_From @TheDarkBomber on February 23, 2017 11:34_

I don't know why it would be not appearing.

**Comment by Luke18033** [comment]
Portal 2 styles should use a Clean dropper model.

**Comment by Luke18033** [comment]
_From @TheDarkBomber on February 23, 2017 18:43_

That won't work. We'll just change the base texture.

**Comment by Luke18033** [comment]
I know TDB won't answer, but I'll ask anyway - @TheDarkBomber, why wouldn't it work?

**Comment by LautaroL20** [comment]
Usually, when a model doesn´t shows up, its to do with something wrong on the URL patch of a Folder or the SMD file that doesn´t match with the final name of the model in the QC file. I had similar issues when i were compiling some of my models, and it had to do with this.

**Comment by Luke18033** [comment]
No, that wouldn't be causing it, the Cube Catcher just re-uses vanilla models (the P1 dropper parts, and a HEP catcher).

**Comment by Luke18033** [comment]
This doesn't seem to be an issue anymore, can you test it again @Byzarru?

**Comment by Byzarru** [comment]
I don't have git or any sort of connection to the dev branches, so not without re-downloading everything...

**Comment by Luke18033** [comment]
I might be able to help you get the dev version workng, I'll tell you how to do it in the #bee2-development channel on [Discord](discord.me/beemod).

**Comment by Luke18033** [comment]
I don't know why this would happen, besides some weird bug in the compiler (which would be unrelated to this particular item). The cube catcher needs to be completely rebuilt anyway.
