### ISSUE TITLE
Old Aperture Futbol spawners have strange collision on the ground.

### ISSUE THREAD

**Issue by mm2wood** [BEEmod/BEE2-items#2141]
It seems when placing a futbol spawner in any of the old Aperture styles that the collision is larger than it.
![20170810224825_1](https://user-images.githubusercontent.com/30917886/29200848-72d735a0-7e1e-11e7-8589-4778e38bad3a.jpg)

**Comment by LautaroL20** [comment]
For viewing the colliding lines from an in-game model, open developer console and type `vcollide_wireframe 1` , that will show the issue with exact precision.

**Comment by mm2wood** [comment]
![20170811201941_1](https://user-images.githubusercontent.com/30917886/29236629-bbe2031a-7ed2-11e7-98cd-f3d4ce60e742.jpg)
Here is how it looks with that enabled, it doesn't show the collision for the spawner. Those cubes in the other picture roughly show the size of it.

**Comment by ZombiePwner1** [comment]
@mm2wood It's to do with the play clips.

**Comment by mm2wood** [comment]
![0](https://user-images.githubusercontent.com/30917886/30000272-eeef4ae2-902a-11e7-9aae-6fa3bef0d846.png)
Modified the size of the clips, should I post the .vmf somewhere?

**Comment by TeamSpen210** [comment]
You could attach it here.

**Comment by mm2wood** [comment]
It says "We don't support that file type." when trying to attach the file here.
Is there somewhere else I should be attaching it?

**Comment by TeamSpen210** [comment]
You could zip it, or rename to txt.

**Comment by mm2wood** [comment]
[common.txt](https://github.com/BEEmod/BEE2-items/files/1272681/common.txt)

**Comment by TeamSpen210** [comment]
One thing is that it has to be big enough to enclose the futbol's spawn position.

**Comment by mm2wood** [comment]
[common.txt](https://github.com/BEEmod/BEE2-items/files/1272694/common.txt)
Just realized you could get stuck in that one I posted so here's one that you shouldn't be able to get stuck in.
