### ISSUE TITLE
Non-permanent gel

### ISSUE THREAD

**Issue by ncrecc** [BEEmod/BEE2-items#2142]
[Non-permanent](http://steamcommunity.com/sharedfiles/filedetails/?id=269742823)
Slap a timer onto the gel dropper and anything related to gel (paintgun activator, [gel cube](https://github.com/BEEmod/BEE2-items/issues/2126) maybe). Set it to N seconds, gel will disappear N seconds **after being placed**. Infinite would mean the gel never expires, like normal. Innovative came up with the concept.

**Comment by TeamSpen210** [comment]
The map you linked doesn't appear to have anything like that... It'd be very difficult to do, since we can't detect gel or where it has been placed.

**Comment by ncrecc** [comment]
Seems you're right. I guess my memory was just acting up.
