### ISSUE TITLE
Droppers broken & leaky goo in 60's style

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2143]
As seen in this image, droppers permanently hang open when activated and never drop anything. And goo has also leaked into the depths of mystery.
![20170811140023_1](https://user-images.githubusercontent.com/25313980/29232244-71db7d42-7e9f-11e7-9821-7c7479033263.jpg)
However, the goo outside of the chamber is simply missing for some reason:
![20170811140429_1](https://user-images.githubusercontent.com/25313980/29232256-8b2491e4-7e9f-11e7-93e7-ba1ef31dd296.jpg)
Mys-steer-e-us!

**Comment by Luke18033** [comment]
The missing goo in the sphere would also be caused by the leak, it's just that the enrichment sphere model covers up the nodraw. Do `r_drawstaticprops 0`, you'll see that there's nodraw there.

**Comment by Luke18033** [comment]
The dropper issue is fixed, don't know why the leak would happen.
