### ISSUE TITLE
Emergency Water Sprinkler

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2144]
When activated, this item sprays water everywhere, soon washing gel clean from every surface in sight.
As an additional idea (ICP, perhaps), the water could also short-circuits turrets on contact (would also apply to regular water too).

**Comment by ncrecc** [comment]
Would it wash gel higher than it? Gel in a completely different room?

**Comment by Endermage77** [comment]
No. It washes gel by spraying Cleansing Gel/water everywhere.

**Comment by Luke18033** [comment]
Possibly it could also extend out of the surface, and be covered by a couple of `func_door_rotating`s when it's retracted?

**Comment by HelloIamapersonthatisalive** [comment]
Hmm I like it

**Comment by Endermage77** [comment]
Good idea, Luke.
As a stylevar idea, the 70's version could skip this and simply have conventional fire sprinklers attached to things (To fit with the money-saving focus of that era.)

**Comment by Luke18033** [comment]
We'd probably want to do that for all the Old Aperture styles and BTS, it should only actually retract in Clean and Portal 1. (Possibly Overgrown as well)

**Comment by TeamSpen210** [comment]
I don't really see the point of this.

**Comment by Endermage77** [comment]
It's main function, in my mind, is to act as a gel-denial zone:
Wherever you put it will get constantly sprayed with water and gel cannot be reliably put there until you turn it off.
Or, conversely, perhaps the existing gel in a room presents a serious obstacle and can only really be cleaned out via a mechanism like this.

**Comment by seagemgames** [comment]
I like this idea, personally, it would make a really cool concept, like if an incinerator opened, it would set them off or something.

**Comment by Endermage77** [comment]
Or anything, really.
