### ISSUE TITLE
Something fishy is going on with the skyboxes.

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2147]
They are acting wrong. They are either messed up (see [https://github.com/BEEmod/BEE2-items/issues/2146](url)), or display standart goo instead.

**Comment by Luke18033** [comment]
BTS is the only skybox which uses a bottomless pit, and even then the pit will only appear on goo that's placed at the lowest part of the map. The glitchy goo texture would likely be caused by an areaportal leak, and would happen on all non-pit skyboxes.
