### ISSUE TITLE
Cube Catcher bugs

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2148]
![20170813165345_1](https://user-images.githubusercontent.com/19228201/29254358-dae41402-8048-11e7-96a8-2aa17dd6483e.jpg)
The base is using dev textures and the pellet catcher is using its overgrown model.
![20170813165354_1](https://user-images.githubusercontent.com/19228201/29254374-2cd99548-8049-11e7-9e0b-dde7df5c2531.jpg)
The entire instance is slightly misaligned, with visible nodraw underneath.
![20170813165441_1](https://user-images.githubusercontent.com/19228201/29254389-68493796-8049-11e7-83b6-675360a2c2d5.jpg)
The spotlight effect doesn't change color when a cube is placed in the catcher. In fact, looking at the instance it Hammer it doesn't even seem to have the ability to do so.
![20170813170751_1](https://user-images.githubusercontent.com/19228201/29254417-0365e260-804a-11e7-8efa-660d6d6c36ee.jpg)
Ceiling-placed cube catchers don't seem to emit a spotlight effect.

Additionally:
- The catcher uses dynamic lights for the inside, which could be a problem with multiple catchers near each other.
- The catcher is still set to use Portal 1 sounds which no longer exist in Portal 2, meaning there are numerous fiddlesticks errors.
- When a cube inside the dropper is fizzled by respawning it, the animation is glitchy and several fiddlesticks errors are heard.
- The kill trigger when a player falls into the catcher is glitchy when it is placed on walls. (And really should be disabled until the catcher closes, since the player can climb back out.)

**Comment by Luke18033** [comment]
Just in the last 15 minutes since I've opened this, I've discovered even more bugs:
- When a cube inside the dropper is fizzled by respawning it, the animation is glitchy and several fiddlesticks errors are heard.
- The kill trigger when a player falls into the catcher is glitchy when the catcher is placed on walls.

**Comment by TeamSpen210** [comment]
It's also using Overgrown models for the pellet catcher, and is generally mashing up moddls that don't really fit together.

**Comment by Luke18033** [comment]
I already mentioned the Overgrown catcher model. It might be a good idea to just remake this item from scratch, the current version is extremely buggy.

**Comment by Luke18033** [comment]
We should also make a custom pellet catcher model which doesn't include the black parts on the sides, that'll look nicer for this.

**Comment by Byzarru** [comment]
Anniversary Edition assets. They're coming one day.

**Comment by Luke18033** [comment]
Based on the trailers it looks like there they use a button base model instead of a HEP catcher model.

**Comment by Luke18033** [comment]
Blue Portals items are no longer being worked on
