### ISSUE TITLE
Lasers Are In Love

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2150]
I don't think they are supposed to auto-align like that.
![620_20170813200539_1](https://user-images.githubusercontent.com/28140988/29268356-1c676184-80f5-11e7-9d7c-d715ee8cf898.png)

**Comment by TeamSpen210** [comment]
They are. Valve added that bending behaviour to help with aiming.

**Comment by CreepiX987** [comment]
@TeamSpen210 could you add an option for them to not auto-align? Maybe via Auto-Respawn/etc.
