### ISSUE TITLE
Properties of the Heavy Cube?

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2151]
(Blue Portals)
I am not certain how this item would operate, but I would like to hazard a guess (though I could be wildly off-mark):
1. You can't pick up the heavy cube (it's too heavy for that)
2. The heavy cube can crush turrets, players, cubes, and other objects, by dropping on them
3. Repulsion gel and Propulsion gel have no effect because the mass is too great
4. Physics Repulsion Field and Compressed Smoke Field can't support the cube so it falls through instead 
5. Excursion funnels can't carry it due to the mass

**Comment by TeamSpen210** [comment]
We can't do 4 & 5, and I've actually tested 3 and that doesn't happen - it still bounces, and Propulsion Gel allows you to push it around. I'm not sure how 2 would work.

**Comment by Endermage77** [comment]
I would envision that if the heavy cube drops on your head, you would die, like in Portal 1; If it drops on top of a turret, the turret would simply explode, and other cubes would fizzle.

**Comment by TeamSpen210** [comment]
No, we can't apply that effect to cubes. It moght be possible to basically make it deadly when moving fast, but that's about it.

**Comment by Byzarru** [comment]
There is a chance the Heavy Cube might appear in the Anniversary Edition, so we can just use those properties. If not, we discussed custom properties before on Gitter: the Heavy Cube is too heavy to pick up, so you'd have to use funnels and gel to move it around.

![20170608224219_1](https://user-images.githubusercontent.com/22107242/29300425-e68ef144-813a-11e7-8ff7-28b5eca34e5b.jpg)
I recommend this as the Old Aperture model, as seen in PS:Mel.

**Comment by Konclan** [comment]
UCP
