### ISSUE TITLE
New style Rundown 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2154]
in an alternate universe chell dies the reactor blows up by wheatlys stupidy and the facility runs on little power thats left i imagine that this would be a dark version of wheatly style but the lights emit little light the large obsevation room turns into a hole with a large hanging light light strips rapidly blink test elements turn on and off by lack of power

**Comment by TheLoafLord** [comment]
erm...? not exactly diff from the other styles. you can do this with other styles i guess...

**Comment by BETTEREXTENEDEDITORMOD** [comment]
so..  this is not being added?

**Comment by TeamSpen210** [comment]
This sounds like your mod idea. You'd want to do that in Hammer.

**Comment by Endermage77** [comment]
This would probably be better off written as a duplicate of the Overgrown style with the Wheatley voiceline.
