### ISSUE TITLE
Exit corridors are missing their fizzlers

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#2155]
Exit corridors 1, 3 and 4 compile with exposed nodraw and a missing fizzler:
![image](https://user-images.githubusercontent.com/6296061/29492785-447cfd02-855d-11e7-9c8e-ed1d4312439f.png)
![image](https://user-images.githubusercontent.com/6296061/29492804-0e85f068-855e-11e7-9db5-4c419a85bc8c.png)
Corridor 2 gives me the following build error:
`Could not open instance file instances/bee2/clean/elevator_sp/exit_corridor_2/fizz_p2.vmf`

**Comment by TeamSpen210** [comment]
I accidentally basically overwrote the Clean configs with BTS ones while doing an exit for that.
