### ISSUE TITLE
The Physler doesn't have an editor icon for the overgrown style.

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2157]
![620_20170821190234_1](https://user-images.githubusercontent.com/28140988/29613696-e8d0d018-880f-11e7-958e-e7e86e6281df.png)

**Comment by LautaroL20** [comment]
@CreepiX987 - It shows correct for me, you are probably using an outdated pre-release, or maybe you still have old resources still present in the Portal 2´s subdirectories, try deleting the "materials" folder located at "Portal 2\bee2", then make Beemod to export the "Full Resources" to the game and see what happens.

As you can see, the icon displays fine for me when using Overgrown Style:

![Image](https://user-images.githubusercontent.com/12244376/29627526-bba59454-8808-11e7-8099-3a11baaafa04.jpg)
