### ISSUE TITLE
"AND" logic and trigger bug

### ISSUE THREAD

**Issue by sent44** [BEEmod/BEE2-items#2159]
Here proof:
http://plays.tv/video/599dcb2c6e1437e70d/-and-logic-and-trigger-bug
I don't know if someone report this before.

**Comment by Byzarru** [comment]
Here's how you find out:
![image](https://user-images.githubusercontent.com/22107242/29646999-58b6ad62-884c-11e7-9826-fffa44e54683.png)
Duplicate of #1062.

**Comment by Byzarru** [comment]
Handy reference picture:
