### ISSUE TITLE
[New item] Funnel Polarity inverter 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2160]
this is a fizzler type item but when a funnel passes through it it inverts the polarity

**Comment by TeamSpen210** [comment]
We can't do that, as far as I know. The only real way would be to like constantly scan for the locations of funnels, detect the funnel, then spawn in a wall to block it and then a reversed funnel. But it wouldn't work well, since that spot would then be solid also.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
how about make it 1x1 wide and tall?

**Comment by BETTEREXTENEDEDITORMOD** [comment]
could you make it like glass you couldn't go through it but it uses a grid type system so the funnel snaps to every 1x1 glass

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Hey Wheels, no need to make a "Not Possible" label, there is already an "Invalid" label which is about the same.
