### ISSUE TITLE
Use Portal: Still Alive forcefield texture for P1 Force Deflection FIelds

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2165]
It's similar to the light bridge texture, but more transparent and 128 units wide.
![20170825194525_1](https://user-images.githubusercontent.com/19228201/29738033-342dcd8a-89ce-11e7-9a58-643069753c40.jpg)
Blue Portals also has a unique FDF texture, which we'd want to include in that style.

**Comment by TheLoafLord** [comment]
what about theflashversion map pack texture?

**Comment by Luke18033** [comment]
That would also work, but this texture looks nicer IMO.

**Comment by Luke18033** [comment]
There's also a P1 laserfield texture present in both the mappack and Still Alive. Seen in this screenshot:
![stillalive_laserfield](https://i1.theportalwiki.net/img/2/23/Still_Alive_07.png)

**Comment by LautaroL20** [comment]
Interesting

**Comment by CreepiX987** [comment]
I really like this texture

_Sent from my HTC 620G_sm using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by christophermc0324** [comment]
I don't know how realistic it would be, but what if Still Alive had its own style?

**Comment by Luke18033** [comment]
No, Still Alive is nearly identical to normal P1. Probably we'd just have an item config option to switch the fields to use their original textures.

**Comment by TeamSpen210** [comment]
I'm definitely planning on this. In fact there's actually a rather similar laserfield texture already in Portal 2, which I'll probably use with modifications.

**Comment by TeamSpen210** [comment]
The forcefield texture is actually the Beta Light Bridge texture, so we don't want to use that.

**Comment by LincoCompany00** [comment]
Just an idea— what if for the Portal 1 Force Deflection Field, you used the beta light bridge texture for it, but orange instead of blue— like this? It looks great, in my opinion.
![Image](https://github.com/user-attachments/assets/5fb8ca71-55ea-46de-9cc2-15492ece0a7a)

**Comment by LincoCompany00** [comment]
Um, should I be suggesting this in a closed issue, or should I create a new issue for this idea?

**Comment by vrad-exe** [comment]
Probably make a new issue, I didn't even see your previous reply
