### ISSUE TITLE
Add 'square door' from Portal 1

### ISSUE THREAD

**Issue by TheLoafLord** [BEEmod/BEE2-items#2166]

**Comment by LautaroL20** [comment]
![wat](https://user-images.githubusercontent.com/19228201/27801407-b25bae6e-5fd2-11e7-9ff1-fc33a78a083f.jpg)

**Comment by mm2wood** [comment]
He's probably talking about this.
![20170826165832_1](https://user-images.githubusercontent.com/30917886/29745438-195a0d9a-8a80-11e7-8bd2-fda6e8441aa1.jpg)

**Comment by ncrecc** [comment]
Except without the dot on it.
The square door is also present in BEE2.2.5

**Comment by LautaroL20** [comment]
Ah i see, this definitelly should be implemented. Maybe as a variant of the current door item?

**Comment by Luke18033** [comment]
Well, assuming that's what the author is referring to, this would be a duplicate of #95, because this is already going to be implemented as the P1 vertical security door.
