### ISSUE TITLE
Use the Portal: Still Alive´s Laserfield texture for P1 Laserfield

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2167]
Use the P1 laserfield texture present in both the mappack and Still Alive:

![stillalive_laserfield](https://i1.theportalwiki.net/img/2/23/Still_Alive_07.png)

**Comment by Luke18033** [comment]
I kinda already suggested this in #2165, but whatever, I guess a separate issue is fine.

**Comment by TeamSpen210** [comment]
I'm definitely planning on this. In fact there's actually a rather similar texture already in Portal 2, which I'll probably use with modifications.
