### ISSUE TITLE
add portal 1 square door frame 

### ISSUE THREAD

**Issue by mariovct** [BEEmod/BEE2-items#2168]
![screenshot 2](https://user-images.githubusercontent.com/31172185/29754431-99826cb0-8b39-11e7-8225-b1f56b9fff3d.png)

**Comment by Luke18033** [comment]
I hate how we close [an issue](https://github.com/BEEmod/BEE2-items/issues/2166) for being a duplicate, just to then have somebody open the SAME issue 3 hours later.

**Comment by Luke18033** [comment]
Like, seriously, searching to see if your issue is a duplicate is NOT that hard!

**Comment by BETTEREXTENEDEDITORMOD** [comment]
NO i read that issue this is the door frames you see at the start of 1x1 hallways

**Comment by Luke18033** [comment]
Oh, sorry, I didn't realize, the name was so similar. It's usually a good idea to include an image of what you're referring to, that way things like this won't happen.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
ah thanks ill do that next time... btw is this being added?

**Comment by LautaroL20** [comment]
Maybe, but it could take a hell of time, who knows.

**Comment by LautaroL20** [comment]
Pls, include a screenshot on yor description, this looks like a duplicate of an already closed issue.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
it's just those rectangular archways you see in portal 1

**Comment by BETTEREXTENEDEDITORMOD** [comment]
![screenshot 2](https://user-images.githubusercontent.com/31172185/29753248-f81de3fc-8b21-11e7-9017-9d5cecb5cb2e.png)

**Comment by Endermage77** [comment]
What would this item translate into in other styles?
Enlarged vitrified door frames in 60's, maybe?
Although, from what I can currently think of, almost all of the other styles would probably use a door-less version of their original doors.

Better ideas would be appreciated.

**Comment by Endermage77** [comment]
Better ideas than the ones <b>I</b> postulated, I meant.

**Comment by TeamSpen210** [comment]
Ideally we'd want to detect these hallways perhaps, and generate them dynamically.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
there's a way to generate them how would that work you can't detect a hallway right?

**Comment by TeamSpen210** [comment]
We can.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
will this be a part of the decoration system you suggested if so will it be toggleable?

**Comment by Luke18033** [comment]
Another option for these would be to make them a static variant of P1 doors, generating when it's set to start open with no connections.
