### ISSUE TITLE
NEW STYLE portal 1 portal 2 mix

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2169]
the black walls still use portal 1 the orange glow everything still uses pistons  cubes are portal 2 doors are portal 1 fizzler is a mix between portal 1 and portal 2 aka fizzlers use portal 2 texures near the sides but uses portal 1 near the middle fizzler model is portal 2 cube droppers use portal 1 so on and so fourth : add on to your own liking

**Comment by ZombiePwner1** [comment]
This wouldn't be a very good style to implement mix between portal 1 and 2 fizzlers for example would look just wrong.
