### ISSUE TITLE
Some ideas for a Portal 1 BTS Style

### ISSUE THREAD

**Issue by TheLoafLord** [BEEmod/BEE2-items#2174]
- Observation rooms could be fans on ceiling, and on walls, well, I don't know about walls. On floor it could be maybe a lowered panel, with a white light underneath?

- Lifts could be pistons, and Track Platforms ?.

- Cut-out panels can be Rattmann remaints, like cans of beans and or cardboard beds. For Cut-Out panels on ceiling ?.

- Cube droppers could be broken Vac-Tubes.

I'll add more later.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
cutout panels on ceiling could be holes into a orange glow cube droppers would just be open vac tubes the wall obs should be a fan too the floor obs would be an orange glow closed off by a grating track platforms should be a floor piece that has a caution line on the front
