### ISSUE TITLE
allow closed solid field to accept gel 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2175]

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i think you can already do this right?

**Comment by TheDarkBomber** [comment]
It does block gel...

**Comment by Endermage77** [comment]
I think he means that he wants to be able to paint the CSF with gel like a light bridge.

**Comment by Endermage77** [comment]
Could such an idea actually be feasible, though, I wonder?

**Comment by Luke18033** [comment]
That's what TDB meant, gel already sticks to it.
