### ISSUE TITLE
heavy fog skyboxes

### ISSUE THREAD

**Issue by mariovct** [BEEmod/BEE2-items#2177]
![screenshot 7](https://user-images.githubusercontent.com/31172185/29847675-d04c1bda-8cd1-11e7-90c7-b7836398797a.png)

![screenshot 6](https://user-images.githubusercontent.com/31172185/29847673-cc6b00a8-8cd1-11e7-8c3b-0c0ada574e87.png)

![screenshot 5](https://user-images.githubusercontent.com/31172185/29847667-c824d42e-8cd1-11e7-9867-7ec7418e296e.png)
these skyboxes have really heavy fog an example of this is in ventura part 6 there's one part that has a really heavy yellow skybox in another part there's a really heavy blue skybox could you possibly add this as an option for heavy fog or no heavy fog just asking
![screenshot 4](https://user-images.githubusercontent.com/31172185/29847663-c227a24a-8cd1-11e7-9281-a3559c8e6071.png)

**Comment by Konclan** [comment]
#3891
