### ISSUE TITLE
Energy Displacement field 

### ISSUE THREAD

**Issue by mariovct** [BEEmod/BEE2-items#2178]
this fizzler type item will block lasers and destroy HEPs it would do nothing to the player or portals the color would be white this would be useful in puzzles  where you don't want to have a closed solid field to block lasers or HEPs

**Comment by TeamSpen210** [comment]
We can't block lasers like that, but we can block HEPs specifically.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 How did you make it so CSF blocks lasers and that stuff?

**Comment by TeamSpen210** [comment]
Specifically, the only way I know to block them is with 'normal' collisions - IE surfaces that collide with everything. The CSF is just basically like a panel or anything else.

**Comment by Luke18033** [comment]
According to [the VDC](https://developer.valvesoftware.com/wiki/Prop_tractor_beam), you can detect (or block) funnels by filtering to the `projected_tractor_beam_entity` classname.

**Comment by Luke18033** [comment]
Maybe something similar exists for lasers and light bridges?

**Comment by TeamSpen210** [comment]
I added that, but actually it's wrong - since it's not a solid object. Light bridges can be detected easily though.

**Comment by Luke18033** [comment]
We don't need more custom fizzlers like this
