### ISSUE TITLE
Red high energy pellet 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2181]
this red high energy pellet is destroyed when it passes through a fizzler or it get destroyed when it bounces off a surface a certain amount of times this is determined by the timer count

**Comment by ZombiePwner1** [comment]
We can't implement this unfortunately it is an entity part of the game's code and to implement this we'd need to modify the source code.

**Comment by Endermage77** [comment]
A fizzler that destroys pellets would likely be no problem, though.
See also the Reaxura Positronic Orb.

**Comment by ZombiePwner1** [comment]
@Endermage77 A fizzler that destroys pellets can be done easily but adding a new type of high energy pellet on the other hand we'd need to modify the source code.
