### ISSUE TITLE
Teleportation cube 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2183]
these two items are  A a teleportation cube and  B a transporter the teleportation cube will shine a beam of light wherever it points at. this is to help show where you are going to teleport the transporter teleports the player once they stand on it wherever the beam of light from the teleportation cube is shining. both the transporter and the teleportation cube can be turned on and off

**Comment by Luke18033** [comment]
Isn't this basically just the Sendificator?

**Comment by BETTEREXTENEDEDITORMOD** [comment]
yes i wanted to be like the sendificator but with players

**Comment by Luke18033** [comment]
That wouldn't work very well, you might end up getting your head stuck in the ceiling, for example. With cubes that's not a problem, since they'll just get pushed out, but that's not the case with players.

**Comment by ncrecc** [comment]
...Unless you just teleport the player a little bit below the laser. So they don't get stuck in the ceiling.
