### ISSUE TITLE
Add Explosive Futbol socket

### ISSUE THREAD

**Issue by MrYurihi** [BEEmod/BEE2-items#2186]
Currently the glass futbol item/socket is included, but not the explosive futbol item/socket

**Comment by ncrecc** [comment]
Explosive Futbol is just a bomb.
Unless you mean a futbol socket that generates bombs and lets you hold them.

**Comment by MrYurihi** [comment]
Yes

**Comment by TeamSpen210** [comment]
Well, you can't hold those so this doesn't make much sense.

**Comment by Endermage77** [comment]
Is there some sort of property that you could apply to bombs that could let you carry them around?
Or maybe you can create a customized futbol and apply bomb properties to it?

**Comment by TeamSpen210** [comment]
No.

**Comment by Luke18033** [comment]
There is `hot_potato`...
