### ISSUE TITLE
Stylevars, items, styles and music suggestions.

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2-items#2187]
1. In 1950's-1970 use the PS: Mel Old Aperture turret model for the turrets.
2. ~~Overgrown optional setting P2 items swapped with destroyed P1 items.~~
3. ~~Overgrown cube cleanser is a group of broken water pipes.~~
4. ~~P1 light bridge is the fizzler from Portal Still Alive PC (Optional).~~
5. Cutout Tile on the ceiling in Overgrown is a hole in the ceiling.
6. ~~Destructible Catwalk e.g when a crusher hits it it smashes.~~
7. ~~Portal Radio (e.g for a nice Easter egg!)~~
8. ~~Full Portal 2 soundtrack.~~
9. ~~Flood Damage style (Has water leaking from the roof, when you make a hole in the ground in a cutout tile area there's water peaking through, droppers are water pipes.)~~
10. BP (Blue Portal) Soundtrack.
11. Explosive cube (when the player picks it up it starts a timer when times out it explodes. (Color Red))
12. ~~Still Alive radio music.~~
13. ~~Portal 2 Soundtrack remixes (here: https://www.youtube.com/watch?v=ryuCsuggGRo&list=PLD862F82B0E01CC65)~~
14. ~~Ratman style (From the old BEE2 mod by radelite)~~

**Comment by Endermage77** [comment]
Flood damage is an interesting idea, but it would likely do better as a stylevar for Overgrown and maybe Old Aperture.

The explosive cube is already a thing in the "tuleby_items" branch. I have never messed with any of the items in there, so maybe it doesn't work, who knows.

**Comment by PorTalZ101** [comment]
And the others?

**Comment by Endermage77** [comment]
No. it is not.
You can, however, grab Githup Desktop and check it out for yourself (instructions are probably in the main BEE2 items page).

Amazingly, I am not actually a real part of the BEE2 dev team, but I'll still leave my two cents here:

1: Not a bad idea; I keep confusing these turrets for defective turrets and other people probably do too. I would probably wait and see if someone else with more officiality approves of the motion.
2: Not sure what to say, it does sound like a simple concept though.
3: Likely a stylevar than anything, we'll see though.
4: Reference image, please?
5: Absolutely yes please!
6: Again, not sure what to say.
7: Already slated as a part of the decoration feature thingymabobber. Probably.
8: Good idea. Copyrights may or may not be an issue.
9: Covered above
10: There's a BluePortals branch (like the tuleby_items branch) that has most or all of these and a couple of items.
11: Covered above
12: Interesting.
13: ???
14: Don't know if this is planned to be reimplemented or not.

**Comment by Luke18033** [comment]
@Endermage77 pretty much already answered them all, but I have a few extra notes:
4. We can't change light bridge textures, and I've already suggested using this as the P1 Force Deflection Field texture (#2165).
6. Not going to be implemented, there isn't really any point to this.
8. BEE pretty much includes the entire soundtrack, the only ones it doesn't include are the music tracks that are only meant to be used in specific places and wouldn't work well when looped (such as the core transfer music).
10. [`blue-portals`](https://github.com/BEEmod/BEE2-items/tree/blue_portals)
13. I'm not really sure what the point of this would be.
14. The original Ratman Style was really just a more glitchy version of Overgrown that was based on Old Aperture for some reason, there isn't really any point of it.

**Comment by ZombiePwner1** [comment]
@Luke18033 you wheely light bridge textures can be changed I changed mine to the beta light bridge look from 2010

**Comment by Luke18033** [comment]
I did that as well, that's not changing the texture, that's just replacing the one it already uses with your own.

**Comment by PorTalZ101** [comment]
what does github desktop do?

**Comment by Endermage77** [comment]
It's basically a sort of Github downloady thingy that you can get. With it, you can pick any branch of BEE2 items you like and merge it with your own files (fortunately, you can't overwrite their stuff since only devs can do that).

Someone else can probably explain it a lot better.

**Comment by TeamSpen210** [comment]
It's a git client, one of many (I don't actually use it).

**Comment by TheLoafLord** [comment]
I think TeamSpen (I think.) said that Rattmann style is 100% not getting added.

**Comment by TheLoafLord** [comment]
Plus, I'm pretty sure overgrown P1 items where given a thumbs down.

**Comment by TeamSpen210** [comment]
1. I'd like to, but we need permission for these first.
2. It's possible (actually a bunch of things in the aesthetic are based on their P1 designs), but we'd need to make said things.
3. They were originally, I nixed that so they can have inputs - it'd be stupid if antlines connected to some piping.
4. We can't pack in that change.
5. When I rebuild those for `tiling` I'll definitely do that.
6. Very difficult to do, it really needs to be intentionally designed for a area.
7. What would this be useful for?
8. Can you be specific, which music tracks? Several can't be used.
9. I don't really know why you'd want this.
10. BP (Blue Portal) Soundtrack.
11. One of Tuleby's items is this.
12. This isn't really suitable for background music.
13. Music for ingame is different to ones you upload places. You really need to make it for that purpose, looping the sounds, etc.
14. Overgrown is 900% better.
