### ISSUE TITLE
Combine+Aperture

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2-items#2190]
The CAperture style would have combine elements beamed in anywhere possible e.g doors, pellet catchers, glass ect, skybox would be the combine citadel and voice would be the announcer from the citadel 

CAperture Bts: combine citadel aesthetic with Aperture logos/ items

**Comment by ZombiePwner1** [comment]
Is combine even a source game?

**Comment by TeamSpen210** [comment]
Yes. Half Life. You may have heard of it.

**Comment by Endermage77** [comment]
I imagine this may look something like the early Portal beta, perhaps? When they reused a lot of the half-life stuff to create the levels?

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Lol u wheely, Combine is an alien race that makes its first appearance in the Half-Life 2 universe. It is probably one of the most known and best games from the 2004´s era.

**Comment by TheLoafLord** [comment]
Hang on a second, I thought the Combine stole from Aperture Science. The energy pellets are a product of Aperture Science, and the Combine have the identical 'Combine Ball'. I also believe the Combine stole from Black Mesa. So virtually, unless this style took place in some kind of Half-Life situation where the Combine have taken over an Aperture Science branch, this would not make sense.

**Comment by TeamSpen210** [comment]
We don't know who invented it first.

**Comment by Byzarru** [comment]
https://en.wikipedia.org/wiki/Multiple_discovery
https://en.wikipedia.org/wiki/List_of_multiple_discoveries
They both came up with the same technologies independently of each other, is what I'm trying to say.

**Comment by Nikita74RU** [comment]
Laser beam in CAperture should be blue and kill without forgiving

**Comment by SW50000** [comment]
@Nikita74RU From what I remember, changing laser color is not possible. I think lasers instantly killing players is possible but I think for many that would be very annoying to work and play with.

**Comment by ZombiePwner1** [comment]
@SW50000 Which laser are you talking about specifically? The laser item or laser fields?

**Comment by Endermage77** [comment]
I wonder if it is possible to swap out the laser's texture for the blue electric combine laser? Because if I'm not mistaken, the blue laser has an electric lightning-like texture and the discouragement beam is a solid red line.

**Comment by SW50000** [comment]
@ZombiePwner1 I'm talking about the Laser item.

**Comment by ZombiePwner1** [comment]
@SW50000 Ah alright yep changing the color isn't possible.

**Comment by Endermage77** [comment]
But what about changing the texture?

**Comment by TeamSpen210** [comment]
We can't really do either.

**Comment by CTB33391** [comment]
Eh, I don't really see this. Wouldn't look too good either due to how HL2 used more brushes (but still used props as well) for detailing as far as I know.

**Comment by Luke18033** [comment]
I don't think this is a style that really works in the puzzlemaker.
