### ISSUE TITLE
Rexaura Cube Module plays the correct beep sound when given a cube, along with zap, which is not included in the mod. Not supposed to play any sound when cube is manually removed either.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2194]
Original post by @MrKrunk https://github.com/BEEmod/BEE2-items/issues/2192

@MrKrunk says: 

" Rexaura Cube Module plays the correct beep sound when given a cube, along with zap, which is not included in the mod. Not supposed to play any sound when cube is manually removed either."

**Comment by TeamSpen210** [comment]
I've done those intentionally to a certain degree.
