### ISSUE TITLE
Portal Mod Elements and Existing Item Styles

### ISSUE THREAD

**Issue by MrKrunk** [BEEmod/BEE2-items#2198]
In multiple mods for Portal, there have been unique test elements. For example, in Factum Solus, there are Turbines, which would work essentially as a larger version of the Diversity Vent--only it pushes loose objects away. (I.E. Cubes and Turrets) And in Rexaura, which forever reason has not been implemented yet (apologies if it's already being worked on) are the Energy Pellet sensors. 

**(All images are taken from Google)**

![fieldexample](https://user-images.githubusercontent.com/17092818/30242723-abc3eca2-9550-11e7-8040-830c62c5dce2.jpg)

![sensor](https://user-images.githubusercontent.com/17092818/30242844-fc8c78aa-9552-11e7-8b65-edf876a1b334.jpg)

![turbineexample](https://user-images.githubusercontent.com/17092818/30242692-f750ec34-954f-11e7-949d-95940fe6b656.jpg)

There are also elements from Portal 2 in other mods which were re-styled in order to fit Portal 1. 

![funnel](https://user-images.githubusercontent.com/17092818/30242819-6c14c502-9552-11e7-9a41-0a87d1752210.png)

What I'm saying is that, if available from mods or someplace else, these 're-skins' should be applied to items in certain styles. Once again, if possible.

**Comment by TeamSpen210** [comment]
It's basically impossible to reskin the actual effects created by the P2 items. But we do have the pellet sensor already.

**Comment by Endermage77** [comment]
Say, is there any idea on when that and the lifeform sensor are going to get reimplemented?
pr27, maybe?

**Comment by TeamSpen210** [comment]
The pellet sensor is in there already.

**Comment by Byzarru** [comment]
Lifeform Sensor should use its appearance in [this map](http://steamcommunity.com/sharedfiles/filedetails/?id=225615358), so it fits with Mevious' design while being easily discernible from the laserfield. Turbines have been suggested repeatedly, though I've made an actual request for it in #1137.

**Comment by IceTudor** [comment]
Pellet Sensor is having fiddlestick errors, I need the sound files. If I need rexaura on its own... Well damnit again.
