### ISSUE TITLE
Timed and Charged Cubes

### ISSUE THREAD

**Issue by MrKrunk** [BEEmod/BEE2-items#2199]
A type of cube which, after a preset time, would fizzle itself. This particular cube would visually differentiate itself from other types by having a 'pie chart-like' countdown display. Full at the beginning, changes color at 3/4 of the way, and decreases clockwise. The countdown would only begin when picked up by the player. 

The charged cube would utilize the same countdown mechanic as the timed cube, however, would need to be charged at a station embedded in either a wall or ceiling. The cube would be stored away for a brief moment and not be retrievable by the player until the charging process is completed, which would shove the cube out of the hole. Unlike the timed cube, as soon as it recieves a full charge and is released from the station, the countdown begins. Visually, the charged cube would be blue, have the same clock display, but bear a lightning bolt symbol. Once the cube runs out of charge, it no longer activates buttons. In a nutshell, it only functions when charged.

As for the charging station, a hole would house a claw which would retract inside of the available space (preferably one or two voxels deep) once given an uncharged, chargeable cube (what a mouthful) and a panel would close off the area, which would be labeled especially for chargeable cubes. Once a few seconds have passed, it would open up again and the claw would open up, ready to recieve another cube. 

If the station has an input, the claw would extend out of the enclosed space, whether it be for a preset time or indefinitely. It would only be during that time that the station would accept a cube. If the input is not active, the panel would be hiding the machinery until otherwise.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
would this be possible to implement?

**Comment by MrKrunk** [comment]
I'm no expert at this modding stuff, I'm just suggesting things and reporting bugs. The different looks on the cubes and station are probably not though, but hey, it's worth a shot.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
instead of the recharging station it should just be a recharging button or something like that so it could be easier to implement

**Comment by MrKrunk** [comment]
Yeah, a pedestal button or something would be fine. I don't want to ask for too much, but maybe an object that only activates via a charged cube?

**Comment by Endermage77** [comment]
I'd like to see the P1 version of the charged cube be a glass cube embedded with an HEP that glows based on its charge.

**Comment by ZombiePwner1** [comment]
I think this might be possible not 100% sure but you should ask @TeamSpen210.

**Comment by TeamSpen210** [comment]
The first one is implemented (for Clean) actually, based on [Tuleby's](http://steamcommunity.com/sharedfiles/filedetails/?id=930032565) concepts. I can't make a cube that doesn't press buttons though, not without disabling other parts of it (it couldn't be painted).

**Comment by Endermage77** [comment]
Perhaps it could work a bit like the Futbol in that it is plugged into a socket instead of dropped onto a button?

**Comment by MrKrunk** [comment]
Yes, that would be good. I imagine it'd be a single voxel or so in either the ceiling, in a wall, or floor. Emits particles which look like elecricity (I.E the ones a pellet makes when it comes in contact with a HEP sensor) when active. Maybe something like the small laser compartments found in co-op mode. (couldn't find an image)

**Comment by Endermage77** [comment]
Perhaps it could be a charging port thingy like you see with the cores in the campaign, and the charge cube  has a plug on the side that can plug into the sockets.

**Comment by awesomedoctorx3** [comment]
@TeamSpen210 I personally don't like the fact that the exploding cube kills you, but this idea where it just fizzles seems much better, personally.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
if this cube is not possible then how would you make the timer cube from the bp pack?

**Comment by TeamSpen210** [comment]
What does that do?

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i got mixed up with the activation cube nevermind

**Comment by Kwinten06** [comment]
This is easy to do with a little script :)

**Comment by Konclan** [comment]
UCP
