### ISSUE TITLE
60° Angled Block is using the 45° Angled Block´s selection mesh...

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2201]
![20170910174851_1](https://user-images.githubusercontent.com/18079316/30247985-04ebaa5c-9652-11e7-98cf-1220fc0feacd.jpg)

**Comment by LautaroL20** [comment]
What bug was supposed to be here wheels? You do not have idea how much i hate unclear descriptions/titles..... This issue will be closed if the author do not reply in the upcoming 2 days.

**Comment by ZombiePwner1** [comment]
@LautaroL20 lol sorry for my shitty description. The weighted sloped block is using the selection mesh from the 2nd item rather than having it's own.

**Comment by LautaroL20** [comment]
Okay, now that i understand the issue, ill fix this in the next days then.

**Comment by LautaroL20** [comment]
Now fixed.
