### ISSUE TITLE
Block bullets trigger is slighty visible in closed solid field.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2202]
![20170910175534_1](https://user-images.githubusercontent.com/18079316/30247993-2797e732-9652-11e7-99ee-c5eb3d3e9d07.jpg)

**Comment by LautaroL20** [comment]
Lol, hope its fixeable...

**Comment by TeamSpen210** [comment]
Double-check with latest `dev`, I rebuilt it basically from scratch.
