### ISSUE TITLE
Signage Item does not work well on walls

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2203]
![Image](https://user-images.githubusercontent.com/12244376/30250605-84394506-9627-11e7-8ee0-067ab6ef3d08.jpg)

**Comment by TeamSpen210** [comment]
Note they do different things on walls, since there they should be always upright.

**Comment by LautaroL20** [comment]
This is now fixed.

**Comment by ZombiePwner1** [comment]
@LautaroL20 I'm waiting for u on steam :D
