### ISSUE TITLE
Visible Input Items for Death Fizzler

### ISSUE THREAD

**Issue by WhoozYerBuddy** [BEEmod/BEE2-items#2209]
The Death Fizzler is very useful but when the various states are used it can be confusing for the player to understand what connection does what without experimentation.  I'd like to see visible Inputs for the death fizzler like the visible logic gates.  On the item, instead of the logic icon, it should show an icon that represents fizzler or laser field so that at a glance a player can understand what each connection does.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
you could have a fizzler signage that shows the function of every fizzler 
with an image with it like the pysler could be a cube being stopped by the fizzler 
with a shock wave being created

**Comment by WhoozYerBuddy** [comment]
While signage for the other special fizzlers might be helpful, I think that having a tutorial room or tutorial map is more effective in showing the special fizzler properties.  They are already visually distinctive and recognizable at a glance.  There is already a topic I have seen discussing custom signage.  That isn't what this topic is about.  

Visible Input A and Input B items with death fizzler specific Icons on them is the topic here.  The reason I am specifically asking for visible Death Fizzler inputs is because, without experimentation, the player cannot tell if a Death Fizzler connection is affecting the laser field input or the fizzler input.  A Death Fizzler that with a default state of laser field or fizzler can be downright confusing when the one connection is activated and instead of turning off turns into a full on death fizzler.

**Comment by TeamSpen210** [comment]
A better thing would be to make the second signage item have these in the list, so you can put it on top of antlines. The Input A and B items are generic as well as the mechanism they use - we'd really want a system to allow signs for other items too - funnels for example.
