### ISSUE TITLE
Reflection Cube Lens Swapper - Vertical Cube

### ISSUE THREAD

**Issue by WhoozYerBuddy** [BEEmod/BEE2-items#2210]
I imagine something like the cube washer.  You stick a laser cube in it, and a normal laser cube is converted to a cube that has the lens point UP.  Stick the same cube back in and it would be swapped back.  I realize that cube tipping by the player is possible but somewhat gimmicky and the cube cannot be moved around easily afterward.  This would add legitimacy to vertical cube reflections.

**Comment by TeamSpen210** [comment]
It's coded into the cube entity that it rotates how it does, and I don't think it'd be possible to modify it to point a different direction.
There's a device in HMW's Sendificate series which rotates a cube to point upward. It'd be good to implement that both freeform and on the Sendificator.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
it could be some sort of claw that rotates the cube upwards
<img width="504" alt="capture 7" src="https://user-images.githubusercontent.com/31172185/30403854-6e92e50e-9898-11e7-8921-057fb0524e32.PNG">
it should look something like this

**Comment by Konclan** [comment]
UCP
