### ISSUE TITLE
Fix Reflection Gel

### ISSUE THREAD

**Issue by WhoozYerBuddy** [BEEmod/BEE2-items#2211]
![20170913093551_1](https://user-images.githubusercontent.com/29020282/30389681-6f5dbc28-9868-11e7-9636-e798af907cdc.jpg)

It would be great if it could be fixed to correctly reflect off gelled light bridges, coat cubes, and work with the sendificator.  Maybe that's all impossible.

**Comment by TeamSpen210** [comment]
It's impossible for us, it requires editing the game code. We could implement the behaviour for the sendificator with some math, but the problem is that it's impossible to tell whether a surface has gel on it or not.

**Comment by WhoozYerBuddy** [comment]
Bummer.  No way for the cubes to get coated and reflect the laser either?

**Comment by TeamSpen210** [comment]
It's invisible, but cubes are actually coatable in Reflection Gel. The only properties it has though are ones left over from Adhesion Gel - coated cubes will not be slippery on Propulsion Gel-coated surfaces, or vice-versa.

**Comment by WhoozYerBuddy** [comment]
Ok.  Thanks.
