### ISSUE TITLE
overgrown sylvar decay 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2212]
this is the workshop series decay [https://steamcommunity.com/sharedfiles/filedetails/?id=68627704](url)
as seen in the maps there's very little vegetation but there's dents molded walls
dead panels rusted floors and hanging lights
<img width="469" alt="capture 8" src="https://user-images.githubusercontent.com/31172185/30462584-6cc3d72c-997b-11e7-8de4-a0d02e7ea417.PNG">
<img width="479" alt="capture 9" src="https://user-images.githubusercontent.com/31172185/30462587-73bf306c-997b-11e7-8efd-ed75209825d6.PNG">

**Comment by Endermage77** [comment]
This looks more or less like the old Reconstructing style.

This could probably be replicated with a stylevar for less veggies and some fancy decorations.
Except for maybe that weird piston thing in the corner and that pillar thing the laser relay is sitting on. And the observation room maybe.

Aside from those things, you could pretty much replicate this exact setup right now.

**Comment by TeamSpen210** [comment]
Reconstructing Style is supposed to not have plants.
