### ISSUE TITLE
portal 1 light strip

### ISSUE THREAD

**Issue by mariovct** [BEEmod/BEE2-items#2215]
this is from the mod rexura
<img width="462" alt="capture 15" src="https://user-images.githubusercontent.com/31172185/30509751-866ec60e-9a6c-11e7-89de-59ce6964b236.PNG">

**Comment by ncrecc** [comment]
This would be better than the current P1 light strip.

**Comment by Endermage77** [comment]
The square hole also looks good.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
whynot add this as a separate item?

**Comment by IceTudor** [comment]
Why not the one from the original portal? about 1/32 of a voxel thin, still though, it's there, hard to notice but it does provide lots of light.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i only noticed it in rexura

**Comment by BETTEREXTENEDEDITORMOD** [comment]
you mean this? 
<img width="500" alt="capture 54" src="https://user-images.githubusercontent.com/31172185/31856175-db40dd1a-b66f-11e7-8673-a1c0425ba1b0.PNG">

**Comment by TeamSpen210** [comment]
We'd want to use these on white surfaces, the current ones on black surfaces.

**Comment by TeamSpen210** [comment]
The recessed strips are harder to do.

**Comment by IceTudor** [comment]
@BETTEREXTENEDEDITORMOD Yep those, look good to me.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
@TeamSpen210 are the recessed strips impossible? they do look nice

**Comment by King0191** [comment]
I doubt they're impossible, they'd just probably take up a bit of space in below, I don't know if it takes so much space that the voxel below would be unusable, I don't think its THAT recessed. But I'm not knowledgeable in that.

**Comment by Luke18033** [comment]
Recently people have been discussing making the light hole a separate item placed like the quarter tile, and introducing a new design for the light strip, with that Rexaura light being one of the proposed designs. Personally, I think it should just be a 4-tile wide light hole, possibly with glass on top. That solves the problem without straying too far from the official design.
