### ISSUE TITLE
"Prevent Portal Bump (fizzler)" does not function

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2216]
![20170916070716_1](https://user-images.githubusercontent.com/12244376/30511604-24e335b8-9ab3-11e7-9279-75a1e73a5bdd.jpg)

**Comment by TeamSpen210** [comment]
Adding noportal volumes isn't really a good solution. The best is in `tiling`, where the brush behind is swapped to nodraw.

**Comment by LautaroL20** [comment]
Nope, that will not help against this bug, actually i emulated the hollow that does the `tiling` feature using flat blocks and here are the results: 

![Image](https://user-images.githubusercontent.com/12244376/30515594-483d0630-9b01-11e7-941e-cfe18d6fbb63.jpg)
