### ISSUE TITLE
New items 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2221]
1. this item is based off the rexura cube deflector but with funnels this 
item will turn the direction the the funnel cubes and the player will turn asswell with 
the funnel this will have a holographic/mirror design when turned off it will disappear completely
2. funnel activation archway this archway will activate when the funnel passes through it

**Comment by TeamSpen210** [comment]
We can't do these.
Additionally, this isn't a test elements wishlist - BEE items should probably really be things which are already in the game.
