### ISSUE TITLE
Put all angled panels together using ButtonType.

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2222]
Weighted is normal panel, cube is glass panel, and sphere is grating panel. Portalability of the surface it is placed on affects only weighted.

**Comment by Endermage77** [comment]
Interesting.
This suggestion is so simple I feel like it should have been suggested years and years ago...
But I think this is actually the first time somebody brought this up.

Will someone please correct me on this?
That aside, it is a rather intriguing idea.

**Comment by TeamSpen210** [comment]
We can't do this.

**Comment by Luke18033** [comment]
We might be able to do this with Cube Type, but I'm not sure if it would work too well with the Angle option also present.
