### ISSUE TITLE
Add a styleVar for angled panels using fancy animations.

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2223]
Kinda like the double grating panel in BEE2.2, they will consist of 4 small panels instead of one big panel with 4 arms, and will move in a random order to look beautiful.

**Comment by Endermage77** [comment]
Soo basically a normal version of the Double Grating Panel thing?
It may serve better as a new item altogether.
And a glass version too, maybe?

**Comment by Luke18033** [comment]
It would also be a good idea to add sounds to the panel, regardless of whether this is on.

**Comment by ZombiePwner1** [comment]
The default puzzlemaker panels need sound as it is idk why valve didn't include sound for them.

**Comment by TeamSpen210** [comment]
We need custom animations for this.
