### ISSUE TITLE
Monitor Screen only working on Overgrown style

### ISSUE THREAD

**Issue by Axolotlus** [BEEmod/BEE2-items#2224]
Trying to make a map that makes use of the Monitor Screen + Screen Camera, but for some reason the model for the screen only appears when the style is set to Overgrown. With any other style, it's invisible (but still blocks portals). Assuming this is because the Overgrown style uses a different (shattered) model for it than the others, how do I fix this?

**Comment by Endermage77** [comment]
Is your camera active?
Did you point it at a really dark thing/nothing at all?
Are you sure you're using the right camera item?
Can I ask a fourth relevant question?

It would be appreciated if you could clarify the circumstances so that the devs can help you here more effectively. Answering the questions above would be a good start.
Except for that fourth one, to which the answer is probably "no."

**Comment by Axolotlus** [comment]
@Endermage77 Yes to all of them; like I said, it does work 100% in the Overgrown style, but if I change nothing but the style, it doesn't work. This is on a fresh installation of BEE2.4 pre-release 26 and BEE2-items pre-release 25.

**Comment by Endermage77** [comment]
Well.
I don't appear to have this problem, but then again, I'm still using pr25 for BEE2.4 instead of pr26, so maybe something broke between since and now.

**Comment by seagemgames** [comment]
Nope i'm using pr26 and its fine

**Comment by Axolotlus** [comment]
Update, I looked through the package files and noticed that there is also a separate monitor model for the Portal 1 style, but that appears to not work either, despite being in a similar vein to the Overgrown one.

**Comment by Axolotlus** [comment]
Another update, actually worthwhile this time: Apparently the monitor model actually _does_ appear. The problem is, it shows up behind the wall. Here's a screenshot I got of it through noclipping: https://steamuserimages-a.akamaihd.net/ugc/861734541708004186/0DDB1F47A7D99ADF8D8356A14811E7214617E04F/
I don't know why I'm the only one here getting this issue, especially since with this new finding, this seems like something that wouldn't be user-specific.

**Comment by TeamSpen210** [comment]
Oh, it's not opening up properly.

**Comment by TeamSpen210** [comment]
Turn on `developer 2`, and attach the console log to a comment here after walking in front. I can't replicate any problems with it.

**Comment by Axolotlus** [comment]
@TeamSpen210 Not sure where to start it at, so I just included the entire log for loading the level, which was just the base map with a camera and a screen put in. https://pastebin.com/Tmpzz4fP

**Comment by TeamSpen210** [comment]
Actually, different idea. Publish a map as friends only, then send me a request on Steam so I can play that. Basically, the monitors are supposed to deploy when you first can see them. Try placing it around a corner so it's not immediately visible?

**Comment by Axolotlus** [comment]
Solved by deleting the bee2 folder in sdk_content/maps/instances, then resetting package caches. The problem was that the instances I was using were really outdated.
