### ISSUE TITLE
make check mark boxes appear on chamberlock 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2225]
<img width="477" alt="capture 17" src="https://user-images.githubusercontent.com/31172185/30526837-2810dc9e-9bd6-11e7-9f4c-dae0df86cebb.PNG">

**Comment by TeamSpen210** [comment]
We can't force this.

**Comment by Luke18033** [comment]
I've added this to the FAQ since it's requested a lot, see [here](https://github.com/BEEmod/BEE2-items/wiki/FAQ#can-you-make-item-x-always-show-a-checkbox).
