### ISSUE TITLE
old aperture suggestions 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2226]
1. improved outside chamber looks 
it shouldn't look like this 
<img width="571" alt="capture 18" src="https://user-images.githubusercontent.com/31172185/30616072-df603f00-9d45-11e7-9e35-9e17b929c15c.PNG">
more like this 
<img width="459" alt="capture 19" src="https://user-images.githubusercontent.com/31172185/30616106-fd57ead0-9d45-11e7-94d5-50fa6caee417.PNG">
how the chamber looks from the inside should determinant how the chamber looks from the  outside               
  2. better decorations old aperture looks plain like this
<img width="460" alt="capture 21" src="https://user-images.githubusercontent.com/31172185/30616354-d1c8c88e-9d46-11e7-9f87-623496786e01.PNG">
i want more of this
<img width="149" alt="capture 20" src="https://user-images.githubusercontent.com/31172185/30616526-53b331a4-9d47-11e7-8921-2541cf5e3ca9.PNG">
<img width="456" alt="capture 22" src="https://user-images.githubusercontent.com/31172185/30616529-580bc3ba-9d47-11e7-8dcf-8c4c6708797e.PNG">
3. open enrichment sphere and for all styles in general
<img width="470" alt="capture 23" src="https://user-images.githubusercontent.com/31172185/30616673-e551b0a4-9d47-11e7-933a-ba69cc745cf0.PNG">

**Comment by ZombiePwner1** [comment]
This is a good idea but the problem is doing something like this in the puzzlemaker is actually quite difficult.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
but it's still doable right?

**Comment by ZombiePwner1** [comment]
Well this is closed so looks like it's not being added.

**Comment by TeamSpen210** [comment]
Not really, or it's very difficult.
