### ISSUE TITLE
portal 1 warm lighthole

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2227]
<img width="314" alt="capture 24" src="https://user-images.githubusercontent.com/31172185/30627315-30001960-9d84-11e7-9981-687e03599873.PNG">

**Comment by TeamSpen210** [comment]
That's already done....

**Comment by BETTEREXTENEDEDITORMOD** [comment]
it's red not a slight orange/yellow and the regular light hole is white
