### ISSUE TITLE
VERY odd HEP + excursion funnel physics

### ISSUE THREAD

**Issue by seagemgames** [BEEmod/BEE2-items#2228]
When you fire a HEP through an excursion funnel, it slows down. Fair enough, you slow down too. But, no matter which direction it goes, it still does it. I was told that the HEP isn't a physics object so it wouldn't be affected... but it is...
![image](https://user-images.githubusercontent.com/32136200/30651396-7ce1b646-9e1d-11e7-95ca-ff8dd5ff58cc.png)
![image](https://user-images.githubusercontent.com/32136200/30651454-a52f8088-9e1d-11e7-9f50-f8b77e29ddd0.png)

**Comment by TeamSpen210** [comment]
It is a physics object, and it is affected. But se can't do anything about that. It's Valve's weird interactions.
