### ISSUE TITLE
Logic gates AND build error

### ISSUE THREAD

**Issue by seagemgames** [BEEmod/BEE2-items#2229]
When you for example, place a Weighted button and then connect it to an AND gate, when you delete the button, the connection doesn't disappear and it causes build errors. You will have to remove the AND gate because the connections won't show up in remove. (no image)

**Comment by seagemgames** [comment]
Actually, I believe the AND gate is just generally broken in P1

**Comment by TeamSpen210** [comment]
Which AND gate?

**Comment by seagemgames** [comment]
![image](https://user-images.githubusercontent.com/32136200/30706314-daeccd84-9eef-11e7-85b3-7f376b078f92.png)
one of theeese

**Comment by seagemgames** [comment]
this***
![image](https://user-images.githubusercontent.com/32136200/30707665-27290c04-9ef4-11e7-8576-c9a6e449f14b.png)

**Comment by TeamSpen210** [comment]
These have been rebuilt, so any current errors are unrelated.
