### ISSUE TITLE
[New 3D Skybox] Open sky

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2231]
Basically a 3D sky skybox like in http://steamcommunity.com/sharedfiles/filedetails/?id=658759886 . If implemented together with https://github.com/BEEmod/BEE2-items/issues/2208 , we could make overgrown style look MUCH better! ~~or copy the Batcature part 2 style because I love it so much~~ (it could also have morning/day/evening/night versions instead of just day, but that would be too hard to make, right?)

**Comment by Endermage77** [comment]
Cue the bottomless pits into space!

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i would love to see a test chamber like this
<img width="685" alt="capture 25" src="https://user-images.githubusercontent.com/31172185/30682184-698f27c8-9e5d-11e7-82ec-f5478cf271f4.PNG">

**Comment by BETTEREXTENEDEDITORMOD** [comment]
something like this?
<img width="391" alt="capture 26" src="https://user-images.githubusercontent.com/31172185/30775728-4d991392-a04e-11e7-9858-b21b54ba96cf.PNG">

**Comment by CreepiX987** [comment]
No, just clean sky (maybe with sun), no ground.

**Comment by Konclan** [comment]
#3891

**Comment by ZeynAlex** [comment]
I have already did it in my ucp, I can give all my resources to BEEE 2.4 devs.
