### ISSUE TITLE
Custom music feature

### ISSUE THREAD

**Issue by EwokPilot** [BEEmod/BEE2-items#2233]
I think you should add a feature that allows people to import their own music and select funnel, running, and faith plate music for it. Also please tell me how I can mod the Portal Stories: Mel gun in on my own. I can't find info on that anywhere.

**Comment by Endermage77** [comment]
You can't do PS:Mel's portal gun, they specifically said they don't want anybody doing that.
Sorry about that, chap.
Also, alas, your suggestion has already been brought up before, and thus must be branded a duplicate.
See #1181.
