### ISSUE TITLE
Glass Door is weird

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2236]
Why is it like that?
![620_20170923125457_1](https://user-images.githubusercontent.com/28140988/30772266-d05a97f8-a060-11e7-9d15-3fcc8ef97809.png)

**Comment by LautaroL20** [comment]
I am not sure if its an issue of the PRL25 but this does not happens to me, see screenshot:
![Image](https://user-images.githubusercontent.com/12244376/30773954-980be12c-a051-11e7-8290-2bec9c361dcb.jpg)

**Comment by Luke18033** [comment]
Actually this has already been reported, see #1921. Considering that @LautaroL20 doesn't have the issue, it's probably been fixed in PR26.
