### ISSUE TITLE
Thinking with Time Machine

### ISSUE THREAD

**Issue by seagemgames** [BEEmod/BEE2-items#2237]
I think it would be really cool to either:
A - add TWTM items like the floor cube creator thingy (it constructs the cube infront of you)
or B - add TWTM style, where cube droppers can be placed anywhere and construct the cubes, and the doors are different

I do not mean:
ADD TWTM MECHANICS FRURURURURU!!!1!!!11!
I do mean:
Add TWTM Styled items/Unstyled items

**Comment by CreepiX987** [comment]
+ glass/neon test chamber signs, normal signage is glass/neon, and the light strips are a set of four light squares.

**Comment by Luke18033** [comment]
Duplicate of #589.
