### ISSUE TITLE
Cube Dissolver Editor Model is being displayed as a "Mysterious Blue Error"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2238]
![Image](https://user-images.githubusercontent.com/12244376/30826816-4c074118-a20e-11e7-9db1-a3e3fa5541f2.jpg)

**Comment by Luke18033** [comment]
Cube dissolver?

**Comment by LautaroL20** [comment]
It is one of the items maded by an user called "tubely (CZ)".

**Comment by TeamSpen210** [comment]
It's a trigger block which when the player touches it kills cubes sitting on the orange buttons, so your Portal Device will be deactivated.
