### ISSUE TITLE
Portal: SA items

### ISSUE THREAD

**Issue by seagemgames** [BEEmod/BEE2-items#2239]
Could you add:
![image](https://user-images.githubusercontent.com/32136200/30835269-62fc06d8-a24f-11e7-83f1-771995abd0f0.png)
A hole for portals,

![image](https://user-images.githubusercontent.com/32136200/30835288-7feb9ab0-a24f-11e7-9fbc-f540d28918a0.png)
This field, (from actual PSA) which probs is already in, but the style. (u can shoot portals but its solid)

![image](https://user-images.githubusercontent.com/32136200/30835341-ac4673e6-a24f-11e7-9381-20cd6a20b5c8.png)
This door (god i love this door)

![image](https://user-images.githubusercontent.com/32136200/30835348-bbb3d6fc-a24f-11e7-92c1-e9b9fb21f95e.png)
(havent checked) if the psa (p1) style hasnt got this lazer field, pls

Crusher (no img), change it in psa style to flat and slower pls, thats how it is in psa bonus maps

![image](https://user-images.githubusercontent.com/32136200/30835530-7fb58d34-a250-11e7-9c59-3fc43e85b46d.png)
(np for the **quality** images) add this zappy zap zoo thingy :D

**Comment by seagemgames** [comment]
![image](https://user-images.githubusercontent.com/32136200/30835614-ec1cfdcc-a250-11e7-963e-62fbb0884131.png)
possibly this but its kinda ugly

**Comment by BETTEREXTENEDEDITORMOD** [comment]
1 that's already in bee2 
2 it's called force deflection field 
3 this is going to be vertical security door for portal 1
4 teamspen has plans to do this
5 thats a good idea but in the portal 1 trailer the crusher still has spikes 
<img width="684" alt="capture 34" src="https://user-images.githubusercontent.com/31172185/30835985-66590176-a210-11e7-95db-5fd4e194dd5e.PNG"> the psa style is just portal 1 maybe a sylvar?
6 a floor that shocks you is going to be added
7 what is that?

**Comment by seagemgames** [comment]
7 is a light thingy

**Comment by seagemgames** [comment]
Maybe add this door too, like as a cube type of 3

**Comment by BETTEREXTENEDEDITORMOD** [comment]
why would you want that in portal 1 and for any style besides bts?

**Comment by Endermage77** [comment]
That  door a couple inches above this post I'm fairly certain is actually the Vertical Security Door for P2 /Overgrown and/or BTS.

**Comment by TeamSpen210** [comment]
Indeed. Actually, Portal 1 has an additional Vertical Security Door, which looks much more like the P2 one:
![P1 Vertical Security Door](https://user-images.githubusercontent.com/8453732/30897402-65a72c46-a399-11e7-8e00-c3caca480520.png)

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i like it but it could look cleaner when portal 1 bts comes out you could use this version
