### ISSUE TITLE
more elevator types 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2240]
<img width="439" alt="capture 38" src="https://user-images.githubusercontent.com/31172185/30888435-690b75b4-a2d5-11e7-96d0-fa93503980a2.PNG">

<img width="468" alt="capture 35" src="https://user-images.githubusercontent.com/31172185/30888433-63cff08e-a2d5-11e7-95ef-09e7028fa621.PNG">

<img width="458" alt="capture 39" src="https://user-images.githubusercontent.com/31172185/30888424-5b7ddbc6-a2d5-11e7-9e04-806a7b4651c4.PNG">
<img width="463" alt="capture 37" src="https://user-images.githubusercontent.com/31172185/30888422-55e3c9b4-a2d5-11e7-8629-13ddb64a6b51.PNG">

**Comment by BETTEREXTENEDEDITORMOD** [comment]
maybe this
<img width="469" alt="capture 40" src="https://user-images.githubusercontent.com/31172185/30889081-e523781a-a2d8-11e7-87cc-c00c3e347fe0.PNG">

**Comment by LautaroL20** [comment]
Thats actually an interesting suggestion,

**Comment by CreepiX987** [comment]
I really like the goopy goop one.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i don't think old aperture and bts need new elevator rooms

**Comment by IceTudor** [comment]
Huh, so one time when I was playing GMOD, with portal 2 props, I found this strange kind of elevator, its neither the Regular, Escape, P1 or Old aperture one, I have no idea what it is, it looks much more futuristic though, like a merge of P1 and P2's elevator

**Comment by Tjmcnee** [comment]
This will be very cool! They should do aperture vactubes at the start and beginning aswell!

**Comment by Fazbear189** [comment]
I really hope they add this.

**Comment by TeamSpen210** [comment]
These are also particular styles of entry elevator people have designed, I'm not going to be copying them without permission.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
but you get by point though you don't need to copy others designs you don't need to use the ones only shown in the pictures you can make other elevators yourself right?

**Comment by Fazbear189** [comment]
How do people make these? Probably hammer, which is very complicated for some reason.

**Comment by ZombiePwner1** [comment]
@Fazbear189 That's the whole point of hammer it's a complicated program which takes quite awhile to learn.

**Comment by Fazbear189** [comment]
why can't valve just add this?

**Comment by Fazbear189** [comment]
right now they could just update the level editor and everyone would be happy!!
