### ISSUE TITLE
add angles 35 50 55 65 70 75 80 85 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2241]
<img width="248" alt="capture 41" src="https://user-images.githubusercontent.com/31172185/30989590-1031eda4-a453-11e7-81da-2359c91c60bc.PNG">

**Comment by Luke18033** [comment]
Two reasons this wouldn't be possible:
* We can't add new options to those drop-down menus. We could possibly use Cube Type or something, but that would be confusing and wouldn't cause the model to change.
* We'd need to make a ton of new animations, two for each angle (extend and retract), plus if animations for #1200 are implemented we'd probably need hundreds.

This seems kind of pointless anyway, I can't think of any new puzzle opportunities this would provide.

**Comment by LautaroL20** [comment]
@Luke18033 - Do not forget to add the "Invalid" label.
