### ISSUE TITLE
Add place able holes in the wall and debris piles

### ISSUE THREAD

**Issue by EwokPilot** [BEEmod/BEE2-items#2242]
You should add an item that adds holes in the the panels when added. (Shows BTS areas behind broken panels in clean style, Debris and sky outside the roof in overgrown style, and show the sphere in 50's, 60's, 70's, and 80's style) this would make the environments a lot more varied if you allowed map makers to insert these. Also maybe add debris piles as and item that can be inserted into chambers.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
look here for the first bit #2235 
but placeable rubble is not being added

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to add the "duplicate" label.

**Comment by GrayGravity** [comment]
> look here for the first bit #2235
> but placeable rubble is not being added

why isn't rubble being added? that's just inconsiderate, like bruh, we need debris

**Comment by FrozenDragon0** [comment]
@GrayGravity Rubble is being added it's just not going to exist as an item. The plan for overgrown is to have the compiler automatically generate debris and foliage where suitable.

**Comment by GrayGravity** [comment]
@FrozenDragon0  ohhh, that makes sense. the only problem is that it might block portalable surfaces or get in the way of lasers or gels. an item might actually be better in this case, because you can decide where you want the debris to be

**Comment by FrozenDragon0** [comment]
@GrayGravity The compiler code can be adjusted to not generate debris/foliage in the way of gel laser items or portalable surfaces.
I'm not a coder or anything but @TeamSpen210 finds ways for this stuff.
