### ISSUE TITLE
1980s new button and doors 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2243]
<img width="191" alt="capture 42" src="https://user-images.githubusercontent.com/31172185/30995678-c1d52892-a470-11e7-871e-1ed33c1ad581.PNG">
you could replace the yellow with black and make the aperture white

**Comment by TeamSpen210** [comment]
That has nothing to do with 80s style, and wep don't have those models.

**Comment by Endermage77** [comment]
That looks more like 70's than 80's as is. Kinda nice, though.
If anybody wants to do some modeling/animating, that there's an idea if you can't think of any.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i found this while looking at f stop concept art and i thought this looked really nice i just added the 80s in the title because f stop took place in the 80s

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i found this one just now
<img width="335" alt="capture 43" src="https://user-images.githubusercontent.com/31172185/31042273-0810bdce-a559-11e7-9278-17e4f69ed437.PNG">

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to add the "invalid" label.
