### ISSUE TITLE
Trying to shoot gel through a Physics Repulsion Field crashes the game

### ISSUE THREAD

**Issue by axollyon** [BEEmod/BEE2-items#2245]
Only tested with Repulsion Gel so far, but it's probably the same for the others.

**Comment by Luke18033** [comment]
Does this still happen? The PRF is just a func_brush and a vphysics clip, I don't see how it could cause a crash.

**Comment by Luke18033** [comment]
It's possible this was caused by the sparking logic, which has been removed.

**Comment by Luke18033** [comment]
Seems fixed

![image](https://user-images.githubusercontent.com/19228201/236586649-932c5f0b-a7dc-46ce-ba54-6cb1d62979c9.png)
