### ISSUE TITLE
Portal 1 cubes sometimes get stuck when pulled through a portal by a tractor beam in a mysterious way

### ISSUE THREAD

**Issue by Axoonium** [BEEmod/BEE2-items#2248]
It seems to happen even more frequently with cubes coated in bounce gel in a "mysterious way".

**Comment by BETTEREXTENEDEDITORMOD** [comment]
is there a error log so the devs like @LautaroL20 or @TeamSpen210  can see what causing the issue

**Comment by Axolotlus** [comment]
@BETTEREXTENEDEDITORMOD No, it seems like it's just a hitbox problem.

**Comment by LautaroL20** [comment]
@BETTEREXTENEDEDITORMOD @Axolotlus - Why do you delete your own comment? No need to do that.

**Comment by Axolotlus** [comment]
@LautaroL20 He deleted his, so mine wasn't really necessary anymore.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Stop putting " in your sentences all the time u wheely.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - A pair of quotes do not hurt anyone i guess. It is mostly to higlight something i want, wheels.....

**Comment by ZombiePwner1** [comment]
@LautaroL20 It doesn't matter wheels only put quotes in when you need to not on the word mysterious all the time you wheely....

**Comment by LautaroL20** [comment]
@ZombiePwner1 - It is fun, and doesn´t hurt anyone, so deal with it wheels.

**Comment by ZombiePwner1** [comment]
@LautaroL20 lol it's not fun you wheely.

**Comment by Endermage77** [comment]
It may be amusing to Lautaro. Who knows?
Perhaps he'll relent about it if you forget about the quotes.

**Comment by ZombiePwner1** [comment]
Well the quotes just really bug me for some reason.

**Comment by Axolotlus** [comment]
Guys, please, this isn't even about the actual issue at this point.

**Comment by LautaroL20** [comment]
Well, that´s ZombiePwner1´s fault.

**Comment by ZombiePwner1** [comment]
@LautaroL20 u wheely

**Comment by Luke18033** [comment]
Not sure what the issue is here, can't reproduce this.
