### ISSUE TITLE
Overgrown Style doesn't function properly for me.

### ISSUE THREAD

**Issue by joshthesomeone** [BEEmod/BEE2-items#2251]
This maybe is just me but there's a lot of missing stuff in the Overgrown Style for me as the "Overgrown Sunlight" skybox doesn't load at all when selected.
![20171005203156_1](https://user-images.githubusercontent.com/32555458/31258308-471f12e2-aa0c-11e7-964a-d8c1c2110b8e.jpg)
 and there's missing textures everywhere. I might have downloaded it wrong, and I'm using the most recent version of BEE2.4 (pr26). help?

**Comment by LautaroL20** [comment]
Ah! The problem about the over trusses was that the material file is corrupted, the basetexture´s patch is unreadable: `"$basetexture" "models\\props_bts    russ"`

**Comment by TeamSpen210** [comment]
The problem is the backslashes, they're getting parsed so `\t` is a tab.

**Comment by TeamSpen210** [comment]
Fixed now.
