### ISSUE TITLE
Make a checkbox for the goo item to didplay actual goo or the selected skybox.

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2252]
The logic of bottomless pit skybox above something else shouldn't bother you, it's the creator's problem if their chamber makes sense or not.

**Comment by TeamSpen210** [comment]
No, it's not. Wherever possible I do want BEE to ensure things make sense.

**Comment by Endermage77** [comment]
I think that implimenting logic for this to happen automatically in the editor would be very nice for distinction, so that we can tell which goo will turn into a pit.

**Comment by TeamSpen210** [comment]
Cannot be done.
