### ISSUE TITLE
Portal 1 Co-op broken?

### ISSUE THREAD

**Issue by dnldrl** [BEEmod/BEE2-items#2255]
portal 1 styled maps definitely work on singleplayer, but when enabling co-op, two things happen-

-when testing the map out, only P-Body spawns in the elevator and Atlas is stuck in the world.
-the item for the co-op entrance usually has an orange and blue figure (representing P-Body and Atlas) but this time, only the orange figure was highlighted while the other one was colored grey.
(could have a connection between the previous observation?)

what's more interesting is that i haven't found any other issues that discussed this problem.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i also have these problems as well

**Comment by TeamSpen210** [comment]
I accidentally set an incorrect position, so ATLAS spawns with his head inside the ceiling and can't move.

**Comment by Tjmcnee** [comment]
I got this problem aswell!

**Comment by TeamSpen210** [comment]
I've fixed it for next release.
