### ISSUE TITLE
make track platforms cutaway a part of a fizzlers/laser-field so it can pass through 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2256]
<img width="469" alt="capture 47" src="https://user-images.githubusercontent.com/31172185/31314517-bc48cf16-abb7-11e7-9c0b-87a8f9eddb08.PNG">

**Comment by TeamSpen210** [comment]
One problem is that the fizzler item doesn't let them overlap, so I can't allow you to place it there. We'd have to do something special for that. Also it'd require the fizzlers to be offset halfway, which is tricky.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
you could create a track item that connects to the track platform that can overlay with the fizzler

**Comment by Endermage77** [comment]
Like the already-existing unstationary scaffolds?

**Comment by BETTEREXTENEDEDITORMOD** [comment]
yes

**Comment by Endermage77** [comment]
I would like to see tracks that function as scaffolds.

**Comment by TeamSpen210** [comment]
They're called Unstationary Scaffolds. We can't do the corner stuff reasonably.
