### ISSUE TITLE
Useful things that can be made with Bee2.4

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2257]
Cube only chamber-lock: Make a hole in a thin wall, add a Compressed Smoke Field, a 3x1 conveyor belt and then your cube chamberlock is ready!
Mega Light bridges: Use a FDF in a bridge fashion, works as a bigger light bridge, only problems are that turrets can shoot through it and you can't transport it with portals.
Cube launcher: Plop a cube dropper, carve a hole so that you can put a vactube in, now make the direction of the vactube go away from the dropper, now you have a cube launcher.
Customize-able Pneumatic Diversity Vent: add some vactubes heading into a hole, now make a matter inquisition field at the end out of the player's sight, you can now plop turrets and cubes to be desintegrated

**Comment by LautaroL20** [comment]
Please, split each suggestions into separated posts. Pilled-up suggestions in a single post will be closed because they must be shorted.

**Comment by IceTudor** [comment]
This isn't a suggestion, it's just a list of useful things you can create with the items BEE2.4 gives you.

**Comment by Byzarru** [comment]
It's not an issue, really.

**Comment by Endermage77** [comment]
I feel like stuff such as this could go in a special section in the wiki.
Some of these item combos would be really useful to people, who wouldn't be able to figure it out otherwise.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
you mean discord

**Comment by Byzarru** [comment]
"Hacks and Tricks with Default Pack Items"

**Comment by IceTudor** [comment]
@Endermage77 Was thinking the same. @Byzarru But suggestions and enhancements go in issues too.
