### ISSUE TITLE
New test elements, styles, ect.

### ISSUE THREAD

**Issue by Tjmcnee** [BEEmod/BEE2-items#2260]
Here's some suggestions:
Portal gun Emancipation Grill - Fizzles the Portal gun, can be helpful for me and others.
Mid-Chamber style Change - This could be done by an elevator or broken observation room to go from overgrown or clean to bts, for old aperture it can be a vault leading to clean or bts or overgrown or portal 1, like in Portal Stories: Mel.
Clean Old Aperture - Like old aperture but the buttons and walls and everything else is not dirty, like it was just invented.
Wall/Floor panel - Like in portal 1, There are panels lifted, and can you make it possible to put items on them?
Mid-Chamber Dialog - This sound familiar but this is different, like a beginning of another chamber while doing the test, like when doing wheatley's tests there's a test where he tells you to do it again.
No portal 1 entry doors - like in portal 1 itself, has no entrance doors, it's just the elevator.
Enterable obversation rooms - could be in BTS, where you can look into a chamber, and even broken one to escape back to the testing tracks, but that's a Mid-Chamber Style change.
Thanks! May edit it later.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
1. it can just deactivate the portal gun no need to fizzle it 
2. i don't think this is possible 
3. see here #549 
4. see #2138 
5. i think this is doable
6. see #970 
7. i don't think this is possible

**Comment by Endermage77** [comment]
The mid-chamber dialogue used  to exist in some capacity in BEE2.2.
I'll do some links for related topics later.

As for the enterable observation rooms, I myself talked about this in the past on #1673, but the idea was dismissed as being able to possibly break chamber designs.

**Comment by Tjmcnee** [comment]
I got another: Chamber screen, just like when you enter a chanmber it tells you what chamber you are in.

**Comment by LautaroL20** [comment]
It looks like ill have to create a new pre-made message for this kind of piled-up suggestions......

**Comment by LautaroL20** [comment]
You must split each suggestion into separated post, otherwise a good part of them, may never be implemented since its what happens to most of the piled-up suggestions here. Having a single suggestion per post will help developers treating it by separate and close it when it's finally done.
