### ISSUE TITLE
Laser Emittor Orb

### ISSUE THREAD

**Issue by Valmayu** [BEEmod/BEE2-items#2262]
A laser Emittor Orb and be placed on the floor and and emit lasers in any direction. Here's I drawing that explains it:
![img_1182](https://user-images.githubusercontent.com/31480378/31374123-4779740a-adcf-11e7-80bd-f79a2ccbd046.JPG)
Sorry for my bad handwriting! Hope you add it, it will be a great addition!

**Comment by BETTEREXTENEDEDITORMOD** [comment]
so.. a rotatable laser emitter that can raise/lower? and also your drawing is upside-down i was only able to read it because i have a laptop

**Comment by Luke18033** [comment]
That's a bug with GitHub displaying  the image, if you click on it it'll be the right way.

**Comment by Tjmcnee** [comment]
@BETTEREXTENEDEDITORMOD Basically yes, here’s an example I could use it for, there’s four chambers, and a main one. The laser orb aims the beam into each chamber, as you need that laser to go on the next one.

**Comment by Endermage77** [comment]
This sort of looks like it would function like the Rotating-Piston-Mounted Pellet Emitter in Chamber 18 in P1.
