### ISSUE TITLE
Models Are Misaligned... Again

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2267]
The glass door *still* is misaligned + the new signage is weird.
![20171010170824_1](https://user-images.githubusercontent.com/28140988/31391761-2321e054-ade0-11e7-9754-7a46c0d11dcc.jpg)

**Comment by Luke18033** [comment]
This would probably be caused by the game using old resources from past releases. To solve this issue, remove Portal 2 from BEE2.4's game list using the Uninstall from Selected Game option, and then re-add it. See if that fixes the models.

**Comment by LautaroL20** [comment]
Heh, i see that Luke18033 has came first than me with the premade message against "game using old resources". 

@CreepiX987 - Do what Luke has mention and that will solve your issue. This is not bug in the beemod.
