### ISSUE TITLE
A styleVar for various glass items to become completely transparent.

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2268]
![20171002141440_1](https://user-images.githubusercontent.com/28140988/31391896-7a68ead8-ade0-11e7-9cbe-ddffd8276c74.jpg)

**Comment by Endermage77** [comment]
I support this.
We need real glass! That hasn't been turned so blue you can't see through it.
However, 70's Cave may object to this unrestricted, budget-wasting usage of glass, and may use something else perhaps?

**Comment by ZombiePwner1** [comment]
Broke glass for glass panels in overgrown is a nice add on but it is also very annoying when you can't see crap through it.

**Comment by TeamSpen210** [comment]
That's kinda the point.

**Comment by CreepiX987** [comment]
But maybe make an optional setting for this?
