### ISSUE TITLE
styles that need to be completed

### ISSUE THREAD

**Issue by mario2582** [BEEmod/BEE2-items#227]
what needs to still be completed and some ideas for some new styles
- [ ] reconstructing
- [ ] underground outside testing spheres
- [ ] wheatley
- [ ] art therapy
- [ ] refurbished (old aperture with glados)
- [ ] ~~new underground~~ (custom style that takes place in 40's that will used edited textures and reskinned models to make things it in look like new.
- [ ] ~~garbage dump / incinerator~~ (hybrid of bts, underground, and art therapy, incinerator mechanical themed tests with jazzy music)
- [ ] thinking with time machine / state of the art (needs custom textures and cube dropper and button models etc extracted from thinking with time machine and packed into bee2, will need custom portal surface item due to white surfaces in TWTM being lit up and non portable)

**Comment by ZombiePwner1** [comment]
Art therapy is in the making and won't be released for awhile. Those other styles you mentioned such as 40's probably won't be made. 40's style won't be made since aperture wasn't made until 50's.

**Comment by LautaroL20** [comment]
@ellingtonvengaboysmuseum - Id suggest you to split a post per style.

**Comment by Luke18033** [comment]
@ZombiePwner1 One of the posters from Old Aperture says it was made in 1947.

**Comment by ZombiePwner1** [comment]
That's most likely for the shower curtain company back in the 1940's

**Comment by TheDarkBomber** [comment]
No, it was for Aperture Science in 1947, and before that, it was Aperture Curtains.

**Comment by Luke18033** [comment]
A 1940s style still wouldn't make much sense though, they wouldn't have had any test spheres set up yet. All that could be done is BTS.

**Comment by Luke18033** [comment]
Combined issue, and most of these now have their own posts.
