### ISSUE TITLE
What happen to the PS:M music?

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2271]
It's no longer in the music selection list.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Wheels, it displays perfectly fine in PRL27, see screenshot:
![IMAGE](https://user-images.githubusercontent.com/12244376/31485731-324f47fc-af0b-11e7-8d2d-ae0272826e2f.png)

**Comment by TeamSpen210** [comment]
We figured out why. He uninstalled the games.
