### ISSUE TITLE
Trying to place light strips is bugged.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2274]
![bls](https://user-images.githubusercontent.com/18079316/31415977-de6d6180-ae58-11e7-9005-e6ab2b24cde5.gif)

**Comment by Luke18033** [comment]
Are you talking about the wall textures glitching out in the back? That's a Valve bug caused by having `puzzlemaker_shadows` on, probably the reason it's off by default. I don't think we can fix that.

**Comment by ZombiePwner1** [comment]
@Luke18033 No the game wouldn't let me place the light strip on the floor it just kept placing it on the wall and refused to place it on the floor.

**Comment by Luke18033** [comment]
Probably because you're holding ALT (or at least the game thinks you are), which puts stuff on surfaces opposite the camera.

**Comment by ZombiePwner1** [comment]
@Luke18033 Nope i wasn't even holding down ALT.
