### ISSUE TITLE
Add Bumbleball and Bomb Cube droppers

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#2276]
These would be very useful. For example, I want to make a test where you have to keep a bumbleball in your sight or it will fizzle itself, but that permanently destroys it because of no auto-respawn feature existing, so obviously that won't work. The bumbleball mod actually comes with a dropper specifically made for it, so it shouldn't be too terribly hard to implement. I don't know about the bomb cube, but it'd be nice to have it respawn on exploding, fizzling, or both. Alternatively, you could give fizzleable items an output that activates on fizzling so that makeshift droppers could be possible via a chain reaction, though they would be finite and a waste of space.

**Comment by Endermage77** [comment]
Already slated for reimplementation. See #95, if you would be so kind.

**Comment by TeamSpen210** [comment]
They are respawnable, I need to put it in the documentation somewhere. Place the item underneath a regular cube dropper (with any cube type set). It'll then override the dropper.

**Comment by ZombiePwner1** [comment]
Didn't bumble balls already get added in prl 27??

**Comment by snorepion** [comment]
@TeamSpen210 Awesome, thanks. @ZombiePwner1 Yes, but there wasn't a dropper option that I saw.

**Comment by snorepion** [comment]
After adding the dropper for a bumbleball, it no longer moves around when not being looked at, which probably stems from the same issue as the bomb cube not exploding as outlined in another issue.
