### ISSUE TITLE
P1 Reflection Cube can not be picked up again once you leave it in the floor while the beam from the laser item is hitting it...... In a "Mysterious Way".

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2278]
![IMAGE](https://user-images.githubusercontent.com/12244376/31494860-8c02a0ee-af2b-11e7-9875-d0a2953a60d4.jpg)

**Comment by ZombiePwner1** [comment]
Illuminati confirmed.

**Comment by IceTudor** [comment]
P1 Reflection cube? Is it a package I missed? I have an unstyled clean cube.

**Comment by LautaroL20** [comment]
@IceTudor - Are you using PRL27?

**Comment by IceTudor** [comment]
Nope, PRL25. Bet it's just something new then, I only knew it got up to PRL26, tho I decided to get a more finished version.

**Comment by LautaroL20** [comment]
PRL26 was totally incomplete. PRL27 just came out a week ago with their own packages,

**Comment by ZombiePwner1** [comment]
This is actually happening in overgrown style aswell.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Is this fixed?

**Comment by TeamSpen210** [comment]
Should have been fixed in PR27.
