### ISSUE TITLE
P1 Cube dropper´s editor model is not using a proper selection mesh

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2279]
![IMAGE](https://user-images.githubusercontent.com/12244376/31494961-f1f2368a-af2b-11e7-81d6-b31d3d84e1e7.jpg)

**Comment by ZombiePwner1** [comment]
Dat selection mesh though.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Thats a default selection mesh that always appears when the game does not detect a custom one to display.

**Comment by Luke18033** [comment]
Is this still not fixed?

**Comment by LautaroL20** [comment]
Idk, i didnt test this for awhile.
