### ISSUE TITLE
Bomb Cubes don't work proberly when they drop out of a Cube Dropper

### ISSUE THREAD

**Issue by G7aD0S** [BEEmod/BEE2-items#2280]
If you place the cube into the map it will work fine but not if, they drop out of the Dopper. 
Then they **do not explode**
They just Disapear. 
They don't deal any damage or make a sound ( so it is not a graphical glitch )

Also the game cannot export if you change the time by hand you have to use the pre made times.
https://cl.ly/3W0R1N3g3y2v
( if that intended just add it to the item description )

**Comment by TeamSpen210** [comment]
Those timer values are for a different feature, which is why I used the preset times. For the dropper there's probably an entity not being captured in the template, so it's not being spawned with the other items.

**Comment by Tjmcnee** [comment]
I didn't know bombs existed in Beemod

**Comment by snorepion** [comment]
They were added in the last update.

**Comment by Axolotlus** [comment]
Can confirm that this happens. It's a shame, this really neuters the Bomb Cube's puzzle possibilities.

**Comment by Luke18033** [comment]
I don't have this issue in the dev version, I think it's been fixed.

**Comment by TeamSpen210** [comment]
I can't replicate it either.
