### ISSUE TITLE
seasonal styles 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2282]
since halloween is coming up why not make seasonal styles we could have a christmas style a haloween style an easter style and a thanksgiving style [maybe day of the dead] i found maps that uses seasonal styles [](url)https://steamcommunity.com/sharedfiles/filedetails/?id=201755717
[](url)https://steamcommunity.com/sharedfiles/filedetails/?id=824895555
[](url)https://steamcommunity.com/sharedfiles/filedetails/?id=792322440
[](url)https://steamcommunity.com/sharedfiles/filedetails/?id=105736289

**Comment by Endermage77** [comment]
Interesting idea.
Might be something to slate for a long-term project.

**Comment by TeamSpen210** [comment]
Styles are an immense amount of work, this requires lots of custom content, and isn't really relevant to Portal.
