### ISSUE TITLE
Vital Apparatus Denial Field

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2286]
A Field, which looks like the old fizzler from the old portal trailer version of the "Impossible" test. Would only destroy cubes (and turrets if not possible to let them live).

**Comment by Endermage77** [comment]
So, it's a fizzler. That does not kill turrets?

**Comment by IceTudor** [comment]
All it does is fizzle objects, not portals or portal shots and if possible, turrets included

**Comment by Blacksilver42** [comment]
i.e., fizzles everything but portals?

**Comment by HugoBDesigner** [comment]
i.e. Matter Inquisition Field

**Comment by Blacksilver42** [comment]
Yeah, I'm pretty sure this is a thing.

**Comment by HugoBDesigner** [comment]
![image](https://user-images.githubusercontent.com/6296061/31588085-9fdfbae6-b1cb-11e7-8dfc-1582e2081c8e.png)

**Comment by Endermage77** [comment]
So, that but it doesn't block portal shots or fizzle turrets?

**Comment by HugoBDesigner** [comment]
Seems like yet another case of people wanting a very oddly-specific puzzle element because of a puzzle they're working on

**Comment by IceTudor** [comment]
Still tho, it could be useful if you want people to use portals but not to lazily bring cubes by throwing them or something, since you CAN throw cubes across an acid/bottomless/fizzler field if you try hard enough, but you also dont want to block the portals, so I guess it's useful. I got the idea from the portal trailer, since it isn't shown to block portals or fizzle them.

**Comment by IceTudor** [comment]
And from before.
@HugoBDesigner The MIF blocks portal shots
@Blacksilver42 Nope.

**Comment by Blacksilver42** [comment]
There should be an "arbitrary-fizzler" tool.

**Comment by LautaroL20** [comment]
LOL, what teh hek is dis? People going nuts at giving insubstantial suggestions these days....

Ive laughted when readed the title tho.
