### ISSUE TITLE
Momentum Break Tube

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2288]
A green (or magenta too if you decide to add on from the "Optional:") funnel-type item that would stop an object that hits it and when released, will give back the object's momentum, think of it like flinging, but pausing, then resuming.
Optional: Input A would turn it on/off and Input B would turn it magenta, reversing the momentum the object had, flinging it backwards.

**Comment by Blacksilver42** [comment]
oooooooooooooooooo, I like it.

**Comment by CreepiX987** [comment]
I like this.

**Comment by IceTudor** [comment]
Thanks, I thought this would be extremely useful, for example, take this:
An aerial faith plate throws a cube into a green momentum break tube, you go to the other side and disable the tube, now the cube flings towards you.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i don't think you can modify the funnel without the source code but i think this could work as a fizzler

**Comment by Endermage77** [comment]
When you said "Tube" I thought you meant like one of them Diversity Transport Vent Tube Things.
It might work as one of those.

**Comment by IceTudor** [comment]
Dunno. Maybe it could work as a sort of cylinder shaped brush of some sort, that stops objects, it would be very hard, but possible, storing it as ID-Momentum and giving the ID "ID" a momentum of "Momentum" after doing it, else it sets any speed to 0.

**Comment by IceTudor** [comment]
Could still work as a fizzler. Though not as spectacular.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
yes at least i think. the funnel still would have been nice though

**Comment by IceTudor** [comment]
Yeah, I have a few ideas for the look of the thing, green would look like a green excursion funnel that stays in place, and magenta a magenta excursion funnel that moves 2 times faster backwards than the normal excursion funnel

**Comment by TeamSpen210** [comment]
We can't really make it look like a funnel. Maybe we can fake it a bit, but it wouldn't travel through portals.

**Comment by IceTudor** [comment]
Darn, could you make another Momentum Break Tube emitter at the other side? so it looks like its closed, like a fizzler?

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i have a question what if a cube flings into a break tube but it's facing sideways would it send any object in a sideways direction or would it just freeze it in place until it's turned off and send it in it original direction.  i have another idea what if you didn't have to turn it off in order for it to let go of an object?
what if it runs on a timer and when that timer runs out it lets go and flings an object. you could use the timer value for this

**Comment by IceTudor** [comment]
It doesn't redirect momentum into the cube's face, it just pauses when turned on and when turned off resumes resumes (or as described earlier reverses) its momentum. You can grab the object away from it, for the timer, just use a timed button.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
>It doesn't redirect momentum into the cube's face, it just pauses when turned on and when turned off resumes resumes (or as described earlier reverses) its momentum 

oh it would have been better if it redirected momentum based on the direction it was facing not just freeze anything in place and just resumes it momentum just forwards or backwards it would have been more versatile

**Comment by IceTudor** [comment]
Eh, a yellow and cyan version could work, but that's too much work tbh.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
for the timer it would be nice if it didn't rely on other items to let go of anything i think if it doesn't have a connection this would be a more viable option instead of holding an object forever

**Comment by IceTudor** [comment]
You could potentially make it so that start enabled would make it either directional or momentum based, and the timer could also be used to preset the angle, dunno.

**Comment by Endermage77** [comment]
"Start Open," maybe?

**Comment by IceTudor** [comment]
Maybe. Start open isn't used a lot.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i would like to have consistency between maps because these are two completely different modes if this would ever be added it would confuse players in one map its directional based and in another map its momentum based it could have those two same things at once you should settle with one option or make some changes in looks like directional would have brighter colors than momentum based. i personally would only have directional based because it would be way more useful than a momentum based funnel

**Comment by IceTudor** [comment]
So let's recap
Start open: Based on object direction
Start closed: Based on momentum direction
Start reversed: Magenta mode (Would reverse both of the above)
Timer value: 
Infinity = Nothing new
1 - Max (forgot value) = 1 - 360 in degrees, would override all of the above
Start enabled: Reverse on/off status

**Comment by Endermage77** [comment]
The timer goes up to 30 before it stops. And although it has been managed to squeeze in 1 and 2, you can't access them when you increment the value to 3 and above.

**Comment by IceTudor** [comment]
Huh, that would be a problem, have to remove it then. Sadly.

**Comment by Konclan** [comment]
How would we create a custom funnel?
