### ISSUE TITLE
Tool in Beemod to create a custom fizzler that can block / allow a specific set of items

### ISSUE THREAD

**Issue by Blacksilver42** [BEEmod/BEE2-items#2289]
A tool to create a Fizzler that can block/allow a specific set of items. Will probably have to set this up in the palette editor. Perhaps (at least in-world) they should have icons beside them showing what they allow/block?

[Enhancement]

**Comment by IceTudor** [comment]
Yes please. I'm tired of making 20,000 suggestions for fizzlers, it would be easier if we could set it. Here's a list of things I came up with:

Brushes/Triggers/whatever it uses.
Hurt: Hurts the player
Kill: Self explanatory
Fizzle: Fizzle objects
Portal Shot Block: Self explanatory
Portal Cleanse: trigger_portal_cleanser
Player block: Self explanatory
Object block: Again, Self explanatory
Solid: Self explanatory
Funnel Solid: Blocks excursion funnels
Liquid Killer: Blocks gel
Detect Objects: Self explanatory, needs relay.
Detect Players: Self explanatory, needs relay.

Textures:
Laserfield, Fizzler, Death Fizzler, Portal 1 Trailer fizzler, P1 Fizzler, P:SA Force Deflection Field, P:SA Laserfield, MIF, CSF, CSFi, FDF, Physler.

Colors:
Color picker/Hex.

Icon:
Icon Base: Laserfield/Fizzler/Custom (Import image)
Icon Tint/Color: Colorpicker/Hex

It would be useful for the editor to be like that, with check-boxes for B/T/Whatever it uses and a drop down for the icon base and ingame texture selection.

**Comment by CreepiX987** [comment]
I'd love custom fizzlers w/o using Hammer, but I believe that this would be really hard to make.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i think this would be really hard to implement i think it's not going to be added and it's going to be more trouble then it's worth

**Comment by LautaroL20** [comment]
Interesting.

**Comment by Byzarru** [comment]
Interesting idea, but the fizzlers that already exist have consistent color and appearance. An item like this will allow users to create a variety of fizzlers, sure, but there will likely be no consistency between what the different colors of fizzlers mean and will cause nothing but frustration from players. You also can't count on mappers making any sort of explanation of what each fizzler does in their description.

**Comment by Blacksilver42** [comment]
Perhaps if one sets up an existing fizzler the color/texture gets set to what it ought to be and is greyed-out-and-cant-change-it.

**Comment by TeamSpen210** [comment]
The same thing counts for any custom types, those would inevitably become very inconsistent.
