### ISSUE TITLE
Items in bottomless pits need pillars

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#229]
this happens when you place piston platforms and catwalks under goo in bottomless pits. these items need something to generate a special piller when placed in bottomless pits

![preview0117](https://cloud.githubusercontent.com/assets/11165643/12222455/1b233ba2-b78b-11e5-8550-73fe69d89274.jpg)

![preview0119](https://cloud.githubusercontent.com/assets/11165643/12222458/1e3be9d8-b78b-11e5-9143-ead0bf550ff3.jpg)

![preview0118](https://cloud.githubusercontent.com/assets/11165643/12222459/2122e098-b78b-11e5-91c5-04ab58e69c16.jpg)

**Comment by Konclan** [comment]
Catwalks don't seem to generate supports under them anymore but pistons still look bad
![20190828201546_1](https://user-images.githubusercontent.com/16567080/63902789-a4656600-c9d0-11e9-95ca-585b17218dee.jpg)

**Comment by Konclan** [comment]
Side note: You can't tell what's out of bounds
![20190828201752_1](https://user-images.githubusercontent.com/16567080/63902852-edb5b580-c9d0-11e9-9e74-25b34f323be1.jpg)

**Comment by Konclan** [comment]
![pit](https://user-images.githubusercontent.com/16567080/63902952-60269580-c9d1-11e9-90c8-1cf98299eb33.gif)

**Comment by Luke18033** [comment]
The embed space showing will be fixed with non-skybox pits. Not being able to tell what's out of bounds would still be a problem though, not sure how to deal with that.
