### ISSUE TITLE
Trigger Grate Freeze 

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2291]
When you place a trigger on a grate, and connect it to anything. It will freeze the game and loop the connecting sound over and over, I had to manually shut down and turn on my computer several times to see what was causing it, please remove the ability to put them on surfaces such as glass, 1x4 walls and gratings, they just freeze it,
1980's style. Tried a not gate and a crusher. You have to set it to NONE in the connection thingy, if you don't want it to freeze, antlines definitely freeze it, signage not sure.

**Comment by Luke18033** [comment]
This would be a Valve bug. And please use borderless window mode.
