### ISSUE TITLE
Remove portal 1 fizzlers from portal 1 SP exit's and entrances in aperture tag.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#2292]

**Comment by Luke18033** [comment]
I just moved the fizzlers into separate instances for #970, so this could be done pretty easily.

**Comment by Luke18033** [comment]
Now implemented
![portal2_igJ3dRvuQX](https://user-images.githubusercontent.com/19228201/92071844-aa6cf000-ed64-11ea-89bb-17f764e736c0.png)
![portal2_RIr5K72Fvm](https://user-images.githubusercontent.com/19228201/92071848-ab9e1d00-ed64-11ea-9ee4-92f78cec493c.png)
I'm not sure what's up with the missing texture in the exit there. It doesn't happen in P2, I'll need to look into it.

And on an unrelated note, P1 style is still way too dark. That's for a separate issue though.
