### ISSUE TITLE
If combined fizzler are set to be both laser & fizzler, it starts weird

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2293]
The combined fizzler are supposed to be in one of 4 states:
Completely off
Red fizzler
Blue fizzler
Red lasers

However, if its configured to start in the "Red fizzler" mode (start enabled + start reversed), it will also display the red lasers incorrectly, looking super weird and once you trigger one of its input, it will behave as it should.

![image](https://user-images.githubusercontent.com/18079316/31808918-f875ac4e-b5a7-11e7-99c2-35821c14b688.png)

**Comment by IceTudor** [comment]
Easy fix:
Make a trigger at the entry/not gate and connect it to the correct A/B input, now hook it up to your death fizzler.

**Comment by Fazbear189** [comment]
Please fix this people. I would rather have a fix then a work around. But that's coming from me, so it doesn't matter.

**Comment by HugoBDesigner** [comment]
It's not a workaround, using the A/B input is the only proper way to connect the death fizzler

**Comment by Fazbear189** [comment]
I know how to connect a death fizzler I am just wondering why nobody is fixing this. Or maybe it will be fixed in the next release? Because it really should be fixed.

**Comment by SpyyZ158** [comment]
hm and how to disable it , it just has three modes when I connect two inputs (first one is that trigger)

**Comment by SpyyZ158** [comment]
Is there any planning of fixing this? Becouse Its kinda annoying.

**Comment by Luke18033** [comment]
Of course we're going to fix it, if not we'd close the issue.

**Comment by TeamSpen210** [comment]
Should be fixed.
