### ISSUE TITLE
Compiler Error on everything. vbsp.exe error.

### ISSUE THREAD

**Issue by Jaxinator03** [BEEmod/BEE2-items#2294]
This might be something simple that I messed up but, every time I try and compile anything (Even the default portal 2 package) it always starts (the first 3 bars finish) then crashes with error (Copying compiler file vbsp.exe failed.Ensure the PORTAL 2 is not running.) this started when I upgraded to Ver27.

I have tried everything I could think of (Opening and closing Portal2, Removing all BEE2 files and reinstalling. reinstalling Portal2.) Nothing works

Here is the error code

[WARNING]` BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_cust_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\games.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\compile.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\config.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_cust_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\games.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[WARNING] packageLoader.get_config(): "VALVE_HAZARDS:items/fizzler.cfg" not in zip!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_80S" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_P1" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_WALL_REV" has no config!
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] packageLoader.get_config(): "VALVE_HAZARDS:items/fizzler.cfg" not in zip!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_80S" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_P1" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_WALL_REV" has no config!
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] packageLoader.get_config(): "VALVE_HAZARDS:items/fizzler.cfg" not in zip!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_80S" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_P1" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_WALL_REV" has no config!
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] packageLoader.get_config(): "VALVE_HAZARDS:items/fizzler.cfg" not in zip!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_80S" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_P1" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_WALL_REV" has no config!
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] packageLoader.get_config(): "VALVE_HAZARDS:items/fizzler.cfg" not in zip!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_80S" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_P1" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_WALL_REV" has no config!
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] packageLoader.get_config(): "VALVE_HAZARDS:items/fizzler.cfg" not in zip!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_80S" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_P1" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_WALL_REV" has no config!
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] packageLoader.get_config(): "VALVE_HAZARDS:items/fizzler.cfg" not in zip!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_80S" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_P1" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_WALL_REV" has no config!
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] packageLoader.get_config(): "VALVE_HAZARDS:items/fizzler.cfg" not in zip!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_80S" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_P1" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_WALL_REV" has no `config!

**Comment by ZombiePwner1** [comment]
Is preserve game directories on? If so then un-tick it. You can access it by bee2/options/preserve game directories.

**Comment by Jaxinator03** [comment]
Nope wasn't ticked, and still isn't ticked

**Comment by Jaxinator03** [comment]
Wait I solved it! 
I had to manually put the vpbs.exe in my portal2 bin folder, after that the rest went fine.
