### ISSUE TITLE
Turret Dropper BUG

### ISSUE THREAD

**Issue by EmirhanBudak** [BEEmod/BEE2-items#2296]
http://steamcommunity.com/sharedfiles/filedetails/?id=1175174738   you must luk it

**Comment by IceTudor** [comment]
You can also place it on the floor and glitch it so that it loads the turret, desintegrates it and then deploys it, weird stuff.

**Comment by EmirhanBudak** [comment]
I really dont remember. Its been 4 years

**Comment by LautaroL20** [comment]
LOL.  I think that this issue is absolutely useless at this time...
