### ISSUE TITLE
Request ,New İtems!!!!!!!!!!!!

### ISSUE THREAD

**Issue by EmirhanBudak** [BEEmod/BEE2-items#2297]
-Vertical door (half opening and full opening)
-Broken doors (not opening but its half opened you can portal to pass it)
-Office İtems
-Pushable Doors (Handle Doors)
-Wheatley On Rail and Rail.
-Skybox (Like you on overgrown map and when you looking up you see sun and sky)
-Tree
-Catwalk Elevators (When Opening Hatch in Chapter 7 Comes Elevator
-Catwalk Door (İts can see on Opening Hatch in Chapter 7
-Broken Glass (You can shoot portal or just becomes a broken glass)
-Turnable-Off Lights 
-Gel Pumkin Lever
-Burn Things (Like Burning Pannel or Burning parts)
-Fire Pit
-Broken Catwalk 
-Starting locations-End Locations (you know you woke up and you start playing)
-Bomb
-Servers
-Aperture Science Sign
-Roads
-Vent Textures
-Logs
-Elevators (Chamber ending elevators)
-Dying end (you die and map ends)
-Portal Stories Mel Things 
-Virgil
-AEGİS
-Portal:Prelude Voicelines
-Cube Button Test Machine (You can see on Portal Stories Mel Chapter 4 Ending)
This is my request eks dee

**Comment by Endermage77** [comment]
I am sad to be the one to bring the news, but

Almost every single one of these has already been suggested/is completely unnecessary.
The one item I'd pick out of this list to look at would be the Gel Pump Lever, but it'd only really be a fancy and bulky button-lever for use an an Old Aperture BTS.

**Comment by LautaroL20** [comment]
Almost every single one of these has already been suggested/is completely unnecessary.

**Comment by TeamSpen210** [comment]
Additionally many of these sound like you just want an easy Hammer.
