### ISSUE TITLE
Cores?

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2299]
You could probably make cores placeable, like the Infinite HEP.
Could work with gel type
P1 Style would make them the P1 cores.
Bounce - Intelligence Dampening core, P1 - Morality core
Speed - Space core, P1 - Curiosity core
Conversion - Adventure core, P1 - Poisonous Cake Recipe core
Clean - <s>Plain darn lies</s> Factual core, P1 - Anger core
Of course, the P1 cores have to be put into the game, the P2 ones are already in.

**Comment by Byzarru** [comment]
Duplicate of #917.
