### ISSUE TITLE
Aperture tag fizzlers are missing their frames in a mysterious way.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2300]
![20171022104555_1](https://user-images.githubusercontent.com/18079316/31857665-6ff040b2-b716-11e7-9560-fa3693fff25a.jpg)

**Comment by LautaroL20** [comment]
This bug is only pressent on Checkpoints?

**Comment by ZombiePwner1** [comment]
@LautaroL20 No you wheely this bug is present when you convert a fizzler into a paint gun field.

**Comment by LautaroL20** [comment]
Lol

**Comment by ZombiePwner1** [comment]
@LautaroL20 Come online in steam wheels.

**Comment by TeamSpen210** [comment]
This would have been fixed a some point.
