### ISSUE TITLE
R.T. Fix?

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2302]
I looked into the code for the rocket turret and I saw "rocket_turret_projectile". Wasn't it just "rocket_projectile"?

**Comment by TeamSpen210** [comment]
It's not, just checked.

**Comment by IceTudor** [comment]
Huh, that's what I use to create the entity when I'm doing misc console things in P2
ent_fire rocket_projectile
I think.
Eh.

**Comment by TeamSpen210** [comment]
To shoot one, the command is indeed `fire_rocket_projectile`.

**Comment by IceTudor** [comment]
Huh, sorry by the way, I really have no idea how to do even the simplest brush in hammer, let alone entity or scripting. PeTI is the only valve editor I use.
By the way, is it possible to add more scripting to reflection gel? So that you can use different button types as values for the gel? Or is it just hardcoded?

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to add the "Invalid" label.
