### ISSUE TITLE
Weighted Cylinder?

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2303]
Is it possible to make a """cube""" that only works on weighted buttons? Such as a weighted cylinder?

**Comment by ZombiePwner1** [comment]
I'm afraid this probably isn't possible it would most likely require editing the source code and adding a new entity.

**Comment by Endermage77** [comment]
I'm not a coder, but maybe it could be an Aperture Science Edgeless Safety Drum or something that activates things as if it was a player?

**Comment by IceTudor** [comment]
That's what i was thinking of, i even made the design.
