### ISSUE TITLE
Prelude Rocket Turrets

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2304]
In Portal Prelude, Rocket Turrets are on the walls and ceiling, could you make it so that the Rocket Turret can be placed on walls and ceilings?

**Comment by Luke18033** [comment]
How about first we just get it to work correctly when on the floor?

**Comment by Endermage77** [comment]
Indeed.

**Comment by IceTudor** [comment]
Yeah, still though, the only problem is the rocket is more of an invisible death ray with no actual explosion. Could be implemented later.

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment]
Please people, before start suggesting on making new Rocket Turrets, we first need to having the original one working as it should be, since it is ridiculously bugged. This issue should be closed to be re-open once we have a fix for the original item.......

**Comment by LautaroL20** [comment]
Indeed, we should first have the Rocket Turret working as it should be.

**Comment by Luke18033** [comment]
It's not invalid, it just won't be implemented anytime soon.

**Comment by LautaroL20** [comment]
But we should apply a label to let people who checks the closed issues tab to understand why it has been closed.

**Comment by Luke18033** [comment]
Since this is something that's rarely going to happen, we should just edit the title instead of creating a new label.

**Comment by IceTudor** [comment]
@HelloIamaPersonThatIsAliveAndHealthily Not a new item, just a new feature, and yes I agree it should be closed until the rocket turret is fixed.

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment]
Whoops, i missed the description.
