### ISSUE TITLE
Vital Apparatus Replacement Vent

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2306]
A dropper which respawns any cubes/""cubes"" that have an infinite timer.
I've been trying to replicate this with vactubes and droppers but it's so damn hard and time-wasting to create, you should also be able to colorize the dropper's cubes/""cubes""/wheatleystein monsters just like regular droppers
Anyway, thought it'd be useful.
You could also add the GLaDOS "Please go to the vital apparatus vent for a replacement" line, that's optional.

**Comment by Endermage77** [comment]
What, the Global Cube Dropper?

**Comment by BETTEREXTENEDEDITORMOD** [comment]
you could just place a button and hook it up to all the droppers in the map then your done

**Comment by Luke18033** [comment]
I think you mean the Global Cube Dropper, included on the list at #95.

**Comment by TeamSpen210** [comment]
Duplicate of #95

**Comment by Endermage77** [comment]
Oh, you can mark specific duplicates now?
That's rather handy.

**Comment by LautaroL20** [comment]
@Luke18033 - Do not forget to add the duplicate label when closing an issue.
