### ISSUE TITLE
Endothermal encouragement beam

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2310]
A laser which fizzles objects instead of hurting you, blocks portals and cleanses them too, free for you to pass.
Simple as that.
Possibly impossible.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
so a fizzler?

**Comment by IceTudor** [comment]
No, it's a LASER which acts as a fizzler. That's the point.

**Comment by TeamSpen210** [comment]
We can't really make our own lasers. Or we might be able to, but it's a lot of work. BEE isn't a place for suggesting test elements really, it'd be better if you've implemented and published them yourself.

**Comment by Endermage77** [comment]
I'd personally be fine with a beam that just fizzles things on contact.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
all this is just a stylish fizzler there's no need for this

**Comment by IceTudor** [comment]
@TeamSpen210 Don't have any item creation experience or knowledge, eehhh...
@BETTEREXTENEDEDITORMOD Again, not a fizzler, its a fizzler beam, you can use portals to redirect it,

**Comment by BETTEREXTENEDEDITORMOD** [comment]
why would you want to redirect it exactly besides fizzling cubes?

**Comment by IceTudor** [comment]
Think about it, If you had to fizzle a cube on a button to complete a test, you'd do it easily like this, it would work.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
you could do the same thing with a normal fizzler or a button that fizzles the cube or a funnel or a light bridge seriously you could do that exact thing with so many other methods this item is useless

**Comment by Endermage77** [comment]
Yes, but those methods of destruction are bulky and most of them often require some sort of goo pit or fizzler on hand to discard the cube into.

This, on the other hand? Point and fizzle, no problem.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
dose a button require a fizzler or a goo pit that's the best option out of all of them the point is you could do that exact same thing with other items

**Comment by Luke18033** [comment]
We can't implement this anyway, custom lasers are pretty much impossible.
