### ISSUE TITLE
Dropper Head

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2312]
An item/option to let you place a dropper head on the end/start of a vactube, you would need to power it to open it.

**Comment by Endermage77** [comment]
Sounds like you'd just have to connect it at the end of a tube line.
I like.

**Comment by IceTudor** [comment]
Yep, and connect it to something else
Start enabled is exactly what it does.
Start reversed could just auto drop cubes/turrets/players/"""cubes""" when they get near, like a trigger.

**Comment by Luke18033** [comment]
Duplicate of #1597.
