### ISSUE TITLE
Fields That Allow Portals Should Have Gridded or Laserfield Texture.

### ISSUE THREAD

**Issue by WhoozYerBuddy** [BEEmod/BEE2-items#2315]
I think that the fields allowing portal shots would be more easily understood by players if the appearance of the texture followed some sort of convention.  The Force Deflection Field allows portal shots and has a 'gridded appearance' to its texture - which makes sense.  I think that the Physics Repulsion Field should have the same gridded appearance because it also allows portal shots.  Alternatively you could make the fields that allow portal shots all have the lines of the laserfields or make them a more pronounced grid like grating.  That change would give the 'at-a-glance' knowledge that a custom field allowed portal shots.  
![20171027084143_2](https://user-images.githubusercontent.com/29020282/32112961-a0fcabba-baf3-11e7-9c89-9856f6fc86b2.jpg)

On a similar note, a custom fizzler that allows portal shots, allows players to pass but fizzles cubes and resets portals if the player passes through it would be a nice addition.  It would have the same color as the default fizzler, but gridded appearance because it allows portal shots.

**Comment by awesomedoctorx3** [comment]
I really like this idea, however I'm not sure how possible it would be. also, a few people kinda know what fizzler does what by now, and it'd be confusing if it suddenly switched.

**Comment by WhoozYerBuddy** [comment]
If the green field texture was changed to a more gridded appearance like the orange one, I think players who have already learned what the green field does would adjust quickly to the new appearance.  The color would not change after all.  It is also currently the only field other than the orange one that allows portal shots.  Players new to the custom fields would adjust more quickly if the texture was implemented as suggested.  When the green field was first implemented I was downright surprised to see that the texture was not that of the other field that allows portal shots and instead was the texture of the fields that block and reset portals.

**Comment by awesomedoctorx3** [comment]
okay, that would work. sounds good, I want this.

**Comment by Byzarru** [comment]
It's not just BEE users that use these fields, but also Hammer mappers. And these fizzlers have been used in countless maps before for a few years, so making this new variant would arguably make the functions more confusing, or at least agitating. Changing their appearance is wholly unnecessary; anyone who has been through the workshop long enough should know their functions by now, and mappers worried about players not knowing how a fizzler functions should use antechambers in their designs, or at the very least, mention the item in their descriptions.

**Comment by WhoozYerBuddy** [comment]
> It's not just BEE users that use these fields, but also Hammer mappers.

I have not found that to be the case AT ALL.  Sure hammer mappers use custom fields, but the appearance and properties are at the whim of the mapper and usually completely inconsistent with BEE.  I recently played a hammer map that had a purple field I could walk through.  A few months ago I played a map that had an orange field that I could walk through also.  In fact, the first time I saw a "Physics Repulsion Field" (or rather one with the same properties) in a Hammer map it DID have a gridded texture - thus my surprise when the BEE version came out with the normal fizzler texture.

**Comment by WhoozYerBuddy** [comment]
Last green field I saw that looked like the physics repulsion field, changed the direction of gravity...

**Comment by WhoozYerBuddy** [comment]
Consistency IS king.  Having a consistent visual aid in the interpretation of the properties of the fields is the whole point.  Arguing to keep the inconsistent visual texture is anti-consistency.

**Comment by TeamSpen210** [comment]
This is indeed possible, and is a very good idea!

**Comment by Endermage77** [comment]
Hear hear!

**Comment by IceTudor** [comment]
I say that they kinda fit. A transparent watery look works for portals too, however, the CSF, CSFI, MIF, Death fizzler and Emancipation grid all have opaque-ish forms, so I choose transparency over style, fits better.

**Comment by TeamSpen210** [comment]
As to your suggested new fizzler type, unfortunately we can't do that. Annoyingly it's coded into the fizzler entity that it always blocks portal shots. For the two fizzlers you show, they're actually fake fizzlers (which is why turning them off uses a different animation). It would be possible to mimic the physical effects of the fizzler (fizzling portals and cubes), but we can't replicate the visuals - the glow when moving cubes nearby and the shake of the portal gun.

**Comment by IceTudor** [comment]
Who are you responding to? I only said I agree with opaque fields blocking shots and transparent fields not doing that. Nothing else.

**Comment by WhoozYerBuddy** [comment]
@TeamSpen210 Even without the glow and portalgun shake, I think that a field with those properties would be useful.  

As far as the optimal display for fields that allow portal shots, I would probably go with a more pronounced gridded display than the current orange field - more like the size of the grating mesh.  I think that would give the obvious and logical impression that the field had 'holes' in it that allow the portal shots through.  Consistency would probably lean towards the laser field lines but of a different color, but I think they're ugly.

**Comment by Endermage77** [comment]
I'd probably make the portal-passable fizzlers look like light bridge patterns, because in essence that is what the MIF is, right?
