### ISSUE TITLE
Portal 1 Style: Portal Gun bug

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2316]
Original post by @Fazbear189: https://github.com/BEEmod/BEE2.4/issues/765

"When I have the P1 portal gun on the thing that holds it(it may happen when you spawn with the gun too) once I grab the gun and die when I grab the gun again it uses the portal 2 model and portal 2 sounds."

**Comment by Fazbear189** [comment]
Um is anyone going to respond or say they are going to fix it?

**Comment by Luke18033** [comment]
Appears to have been fixed.
