### ISSUE TITLE
P1 elevator glitch

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2317]
Original post by@IceTudor: https://github.com/BEEmod/BEE2.4/issues/764

"If you place a portal right next to the elevator worldportal, while being in the tiny elevator room, you can walk slowly enough by walking into the wall at an angle, then glitch the worldportal."

"By portal I also mean, MANUAL portal, as in, the player places one, not an autoportal"

**Comment by IceTudor** [comment]
By portal I also mean, MANUAL portal, as in, the player places one, not an autoportal

**Comment by LautaroL20** [comment]
@IceTudor - Added your sentence to the post´s description.

**Comment by Luke18033** [comment]
I don't think this is really fixable
