### ISSUE TITLE
New Portal 1 Funnel Model

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2-items#2318]
You probably can't do this but I'd like this to be the Portal 1 funnel model:
![image](https://user-images.githubusercontent.com/29339358/32116334-1f8172d8-bb42-11e7-9b01-1b5741c02dfa.png)

**Comment by Luke18033** [comment]
I'm not sure exactly what you're referring to, the emitter isn't visible there and we can't change the funnel effects.

**Comment by PorTalZ101** [comment]
ok, you can close this now

**Comment by LautaroL20** [comment]
@Luke18033 - Do not forget to add the "invalid" label when closing the issue.

**Comment by TeamSpen210** [comment]
Additionally we can't actually change the funnel model.
