### ISSUE TITLE
Dropper Colorizer

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2319]
Ideally, if you color a cube, it should also color the dropper of the same number with an identical tint.
If that can't happen, I feel that being able to affect the droppers at all with the Colorizer would help a great deal when distinguishing which dropper drops what cube, when paired with colored cubes.

**Comment by awesomedoctorx3** [comment]
it does already, and it's ugly.

**Comment by Endermage77** [comment]
Oh, it does?
I should probably have paid more attention to the colorizer, then.

**Comment by WhoozYerBuddy** [comment]
I think the colored rings look good.

**Comment by Byzarru** [comment]
Stylevar to deactivate the rings, please.

**Comment by LautaroL20** [comment]
Well, seems this is already implemented acording to some people here.
