### ISSUE TITLE
Panel Lights

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2320]
The warm lights in P1 Style give off the same light as the panels do, so why not make a panel/hot light separate from it, It could work as gel type. <s>You could also make them powerable, as to turn on and off the lights, they would just appear darker in texture and emit no light when off, and normal when on 
</s>
Bounce = Panel/Hot
Speed = Warm
Conversion = Neutral/Cool
Cleansing = Cold

**Comment by TeamSpen210** [comment]
I have no idea what a "panel light" is. Additionally I've explained several times why switching lights isn't possible / won't be added.

**Comment by IceTudor** [comment]
Huh, let me remove that then, by panel light I mean the red light in portal 1, it should be placeable in other styles as it looks actually surprisingly good.

**Comment by Endermage77** [comment]
When I read this, I read it as "One entire panel worth light item," that would be the same size as all the other panel items.

**Comment by LautaroL20** [comment]
1. ButtonType / CubeType / Gel Type would break collisions on the light item, since this is coded into the editor.

2. A hole light for other styles would look pretty bad, mixing up items from other styles between them does not fit well, each item must match their respective style.

**Comment by IceTudor** [comment]
@Endermage77 It's like the portal 1 warm square light, but in other styles, still as red as it is, same with the light strip.

**Comment by IceTudor** [comment]
Think of it as this, a set of 4 square lights in clean style, you have warm, cold and cool/neutral, you would also have a RED light similar to the red light found in warm lights in p1 style.
