### ISSUE TITLE
Lava / Molten Metal Goo Pit

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#2321]
just thought of this, Lava / Molten Metal goo Pit, it should be a new item that could show up in every style if it was used as a test element...

idea's i got for this is

- custom glowing liquid that looks like molten metal / lava that replaces goo pit...
- anything that falls into it SLOWLY SINKS (real molten metal physics) and catches fire and is destroyed when it submerges completely under.

general challenges with creating this @BenVlodgi and @TeamSpen210 

it modifies the goo pit physics and makes the liquid emit light which those properties are hard coded into the pti goo pit by valve

the easiest and most time consuming method to create this would be to create and code your own version of custom goo pits into bee2.4, this would allow creation of things like water etc and if the pit hurt the player or not...

**Comment by Luke18033** [comment]
`General Similarity across all Styles`? Seriously? Please stop creating random useless labels...

**Comment by Endermage77** [comment]
I'm fairly certain it's already been said that custom goo pits are impossible, according to @TeamSpen210.
I do believe it was also said that it might be theoretically can would have been done using modifier items that you submerge in the default goo pit.

**Comment by Enterpise** [comment]
@ellingtonvengaboysmuseum Wheren't you the one who claimed having an internal source about Portal 3 like a year ago? Please, make our week by posting it again. That fake was actually funny.

**Comment by IceTudor** [comment]
Isn't this a duplicate? The incinerator theme is gonna have lava as goo, if I remember correctly.

**Comment by ellingtonvengaboysmuseum** [comment]
not a duplicate, this would be a new goo pit type found across all styles, explanation of where it would come from for each style would be there would be a metal furnace somewhere nearby fueling the pit with molten metal... for example in clean glados would say she has a furnace melting metal and it's flowing into pits for a new deadly test element...

**Comment by Luke18033** [comment]
> for example in clean glados would say she has a furnace melting metal and it's flowing into pits for a new deadly test element...

You realize we can't add custom GLaDOS lines, right? Also, why do you always put "..." randomly at the end of sentences?

**Comment by ellingtonvengaboysmuseum** [comment]
the glados line used for any new test elements would be the fascinating new test element / lump of coal failure one...

**Comment by Endermage77** [comment]
Wait a minute...
Why is this labeled "New Goopit Type"?

That seems oddly specific to need a new label for when "New Item" or "New Item Variant" would work just as well or better.

**Comment by Luke18033** [comment]
For some reason, @ellingtonvengaboysmuseum likes creating very specific labels which are only going to be used on like one issue. In fact we already have a few very specific labels which we should also get rid of.
