### ISSUE TITLE
Neurotoxin Variants

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#2322]
more variants of the nero toxin timer and kill item and what the timer is counting down on.

- [ ] heat source (incinerator, lava pit, lava pit sky box, more smoke particles, ashes, sparks, show up near end)
- [ ] oxygen removal (similar to final boss in Mel)
- [ ] cold source (room is a freezer and temp drops to lethal levels over a time limit, ice particles, snow fog shows up etc)
- [ ] custom kill timer (would have no special effects, would kill player at end)

**Comment by Endermage77** [comment]
I would think that the type of death it's counting down to would not really be an element of the timer itself, but of what kind of death vent you stick in your map, wouldn't it?

**Comment by Luke18033** [comment]
I also had an idea for an Explosion Timer which would be used when there were no vents in the map:
> ...an Explosion Timer which makes everything explode when the time runs out. This would work good for Co-op maps, because robots [wouldn't be] affected by poisons... - @Luke18033 in #547

**Comment by IceTudor** [comment]
Was thinking of hemotoxin if the vents are on the floor, y'know, since one inhale and your blood cells die, along with some other stuff I think, since filling up would take more time to kill than you instantly inhaling it from above.

**Comment by IceTudor** [comment]
Or maybe a vactube for toxin to enter? That would be neat actually.

**Comment by Endermage77** [comment]
Perhaps you could add neurotoxin particles at the end of any vactubes "submerged" in the neurotoxin environment?

**Comment by TeamSpen210** [comment]
There is no Neurotoxin environment. It used to have a range, but that was far too confusing, so it now assumes you've placed enough to cover the whole map

**Comment by Endermage77** [comment]
@Luke18033: 
Say, we could simply do a recolored variant of the Nuerotoxin to represent some other gas being vented that would be capable of reacting explosively when added in high enough amounts.

That would make the gas deadly to both humans and robots alike.

**Comment by TeamSpen210** [comment]
Unfortunately we can't pack particles.

**Comment by Luke18033** [comment]
Maybe you could use an `env_steam`, configured in a way that it looks kinda like the neurotoxin particles?

**Comment by Luke18033** [comment]
We can now pack particles, but since Neurotoxin is a rarely-used item to begin with I'm not sure how useful these really are.

**Comment by Luke18033** [comment]
Not to mention it'd be a little confusing having different-colored neurotoxin or whatever which does exactly the same thing. I think I'll just close this.
