### ISSUE TITLE
Label Updates and Grammar Corrections (Will be Closed in 24 Hours)

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2323]
@TeamSpen210 and @BenVlodgi - This Issue will be Closed automatically within 24 hours...

I've made some Updates and Grammar Corrections to a few of the Labels, they are as follows

all of the labels now have proper capitalization and grammar

All of the Most Critical labels have been color changed to Black to look more critical than red

Crash has been corrected to "game crash" be more defined on what crashed

Bee2 Crash and Game Freeze have been added because i have experienced both bee2 crashes and game freezes (that forced me to reset the computer) in the past when working with making new custom items in bee2.4

Some Corrections to Current and New Style Labels have been added, mostly Underground BTS, Custom Style etc.

Some missing labels have been added such as Missing Resource etc.

Some new labels have been added such as 3D Skybox, Label Update, Valve Code etc.

**Comment by TeamSpen210** [comment]
BEE2 crashes are for the BEE2.4/ repro. For game freezes, they might as well be crashes, we can't do too much.

**Comment by Luke18033** [comment]
This is another thing you should probably use [Discord](https://discord.me/beemod) for, that way we don't need to open an issue just to have it immediately closed.

**Comment by Luke18033** [comment]
A few notes about the labels:
* I already had a coloring system set up which you've kind of broken. For example, all of the `New...` labels were purple to match the original `New Item`. I'm changing some of them back but I'm keeping the new colors for most of them.
* `Dev Version` should be `Development Version`. 
* As usual, most of the new labels you've created are useless.
* Aren't `Irrelevant` and `Off Topic` kinda the same thing?
* (More things may be added to this list...)

**Comment by ellingtonvengaboysmuseum** [comment]
all changes reverted to 3 hours ago...
