### ISSUE TITLE
Low Energy Positronic Pellet

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2324]
Like the HEPs, but annihilate Green and Yellow HEPs along with themselves on contact, would also pass right through/bounce off of the positron orb and deactivate catchers, they could have a catcher of their own. They would be purple

**Comment by Luke18033** [comment]
I'm not sure if we can make custom HEPs.

**Comment by TeamSpen210** [comment]
I don't think we could change the appearance, but we are able to control the interactions with other items.

**Comment by awesomedoctorx3** [comment]
But didn't Rexaura have differently colored pellets? surely we could do something like that.

**Comment by awesomedoctorx3** [comment]
speaking of, have pellet colorizers been suggested?

**Comment by BETTEREXTENEDEDITORMOD** [comment]
1. rexura did not have colored pellets the green pellet is already in portal 1 in chamber 19
2. nobody suggested that but it don't think it would be possible without source code

**Comment by awesomedoctorx3** [comment]
Rexaura did have colored pellets, actually.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
where? it only had yellow and green both already in p1

**Comment by awesomedoctorx3** [comment]
it had red ones in some chambers,

**Comment by BETTEREXTENEDEDITORMOD** [comment]
show me a screenshot i played all of rexura and i never saw a red pellet

**Comment by awesomedoctorx3** [comment]
Oh, there were red catchers, not red pellets. sorry, my mistake.
