### ISSUE TITLE
Help needed with custom fizzler code

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2327]
@TeamSpen210 - I need Help with custom fizzler code. to prevent my golden idea from being stolen before i finish this new fizzler, i will not say what it is or what it does too much.

here are some details i need to know

has fizzler trigger outputs been implemented yet? if they have put some sample code below to make a fizzler output when a player steps within the trigger

also i need code for the trigger width if the fizzler code has majorly been changed since the last update.

**Comment by Luke18033** [comment]
The Flux Field has a trigger output that activates when a HEP passes through. I'd imagine it wouldn't be too hard to implement that for players instead. Are you adding the Lifeform Sensor?

**Comment by Luke18033** [comment]
This is also the kind of thing you should post on [Discord](https://discord.me/beemod), that way we don't have to open an issue just to have it immediately closed once the question is answered.

**Comment by ellingtonvengaboysmuseum** [comment]
@Luke18033 - when i have a look at the code later, or in a few days, i will let you know what code i need etc.

**Comment by Luke18033** [comment]
I don't really know too much about how BEE fizzlers work, you'll need @TeamSpen210 to help with that.

**Comment by ellingtonvengaboysmuseum** [comment]
@Luke18033 - also i need it to trigger and play back a custom sound 

i have given this fizzler the nick name "the troll fizzler" because just about anything can pass through it and set it off!

**Comment by Luke18033** [comment]
[This](https://github.com/BEEmod/BEE2-items/wiki/vbsp_config_fizzler) might also help with making custom fizzlers.

**Comment by ellingtonvengaboysmuseum** [comment]
most of this stuff is done now - closed...
