### ISSUE TITLE
BTS 3D Skybox Missing from Skybox List in bee2.4 

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2328]
the BTS 3D Skybox is Missing from Skybox List in bee2.4 

but when you select suggested test elements for style, it shows up by default.

is this on purpose because i heard rumors @TeamSpen210 is completely redesigning 3D skyboxes to be better and more like how valve makes them...

**Comment by Luke18033** [comment]
It appears perfectly fine for me. Maybe you have the 3D Skyboxes category collapsed?

**Comment by ellingtonvengaboysmuseum** [comment]
yep. figured it out, collapsed, case closed!
