### ISSUE TITLE
Closed Solid Field Missing Field Texture (Shows Wireframe)

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2329]
The Closed Solid Field is Missing the Field Texture on all styles (Shows only a white Wireframe)

this weirdness shows up in all styles

![preview0003](https://user-images.githubusercontent.com/11165643/32148203-b245c212-bcc9-11e7-89cf-ea260ae675a1.jpg)

**Comment by Luke18033** [comment]
Duplicate of #1918.
