### ISSUE TITLE
Bottomless Pit Instance Collision

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#233]
instance collision in corner of bottomless pit, i will release this pit to you for the next pre release when i am done with it

![preview0227](https://cloud.githubusercontent.com/assets/11165643/12226461/73ce32b6-b7ea-11e5-9da5-86e58e9e5f6a.jpg)

**Comment by Konclan** [comment]
This still happens its just not as frequent
![20190828203017_1](https://user-images.githubusercontent.com/16567080/63903349-bfd17080-c9d2-11e9-94a2-70d39809ae08.jpg)
![20190828203034_1](https://user-images.githubusercontent.com/16567080/63903350-bfd17080-c9d2-11e9-9165-94dbb9d544a1.jpg)
![20190828203043_1](https://user-images.githubusercontent.com/16567080/63903351-bfd17080-c9d2-11e9-8e23-b8b57e636f9a.jpg)

**Comment by Konclan** [comment]
#3891
