### ISSUE TITLE
BTS 3D Skybox Leak

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2331]
The BTS 3D Skybox has a Leak seen at the test chamber entry door frame of all current entry corridors...

![preview0014](https://user-images.githubusercontent.com/11165643/32148314-53db7c7e-bccb-11e7-8a4d-b450f54b72c1.jpg)

**Comment by Luke18033** [comment]
Duplicate of #1222.

**Comment by ellingtonvengaboysmuseum** [comment]
@Luke18033 - Also do you know about the Bts 3D Skybox Texture Mismatch (Pit is using Modern Metal BTS Textures, area above is using Cement textures)

**Comment by Luke18033** [comment]
Yes, #1451.

**Comment by IceTudor** [comment]
God, in the version I'm using, the BTS style exit/entry is broken completely
