### ISSUE TITLE
Add "Broken Down" style

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2333]
Like overgrown, but random panels are missing/hanging on the black tiles (just to not screw up solutions by getting rid of portal areas) and most of the plates are cracked too, the ceiling would be completely broken and sunlight would be revealing with plants hanging. panels such as the glass panel and glass door would be like black panels and black half doors with some panel tiles missing.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
like this?
<img width="465" alt="capture 59" src="https://user-images.githubusercontent.com/31172185/32161521-1a79f80a-bd13-11e7-94ba-0e9e040126d3.PNG">
<img width="440" alt="capture 58" src="https://user-images.githubusercontent.com/31172185/32161515-15e7ffc6-bd13-11e7-9d5f-15bc2113c00e.PNG">

**Comment by IceTudor** [comment]
Yeah, like a mix of that and overgrown.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
so.. reconstructing but more dead and some plants?

**Comment by BETTEREXTENEDEDITORMOD** [comment]
this could take place where the facility is still decaying glados is still shut off but it's not that far into the future there the facility is riddled with plants this is not that bad but there's dead panels a lot of rubble due to decay and a little plant life

**Comment by TeamSpen210** [comment]
This is pretty much Overgrown style.

**Comment by IceTudor** [comment]
Overgrown is too tidy to be similar to this, I was thinking it could have broken walls and hanging panels from the ceiling and stuff. Not just rusty moldy walls.

**Comment by TeamSpen210** [comment]
No, Overgrown should be like this.
