### ISSUE TITLE
Interesting unintended feature...

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2334]
You CAN place flat blocks below goo, if you make a 1 high goo floor and put half flat blocks under it, this is what you get.
https://prnt.sc/h3yzh5
As we can see, the turret deactivated as soon as it landed in the shallow goo, even if not on its side, it's still dead. You can also put cubes and stand on it, you will however die if you enter the goo. Turrets placed on those cubes will also live, and not die, only when submerged even partially will die.
This could be useful in some companion cube levels, requiring you to place the cube into the water to cross.

**Comment by IceTudor** [comment]
You could've just put in BUG, since it is kinda one.

**Comment by TeamSpen210** [comment]
It's not really a bug, just how goo works. Objects are only destroyed when they pass into the bottom ¼, so you don't see them disappear.

**Comment by IceTudor** [comment]
Still though, interesting, perhaps you could make a shallow water item? so that you can place an object with 1/2 sticking out, while you still die? Would be interesting to use in companion cube maps, in fact, i just made one using this concept.
