### ISSUE TITLE
Left-Middle-Right Ped buttons pallete icons are beind displayed as a "mysterious" purple & black checkered textures

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2336]
![20171030145055_1](https://user-images.githubusercontent.com/12244376/32187986-4aa430be-bd85-11e7-9047-b04e9aac4004.jpg)

**Comment by Fazbear189** [comment]
Why is this "mysterious"? It's just a missing texture!

**Comment by LautaroL20** [comment]
I seriously wondrer who is playing with the labels here at changing their colour....

> Why is this "mysterious"? It's just a missing texture!

It seems you are totally newcomer here. There were a few bee´s memes here generated by me a long time ago. They´re two in total: 

- "It becomes stagnant forever!"
- "In a mysterious way!"

For the first meme, someone even made a wiki page, this is it (very recomendable), http://knowyourmeme.com/memes/stagnant-forever

For the second meme, it was once when i reported a bug where a BTS Light strip was floating like a 1/4 of a block, so i entitled the post: "A BTS Light is floating in a mysterious way".

**Comment by Fazbear189** [comment]
Oh I get it now!
