### ISSUE TITLE
Bee2 Crash after trying to implement custom fizzler

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2338]
@TeamSpen210 or @Luke18033 - can someone tell me what is causing this error, i am trying to implement a new custom fizzler

![photo 800 - copy](https://user-images.githubusercontent.com/11165643/32191522-c7eea4a8-bd87-11e7-9992-aedaddf8597e.jpg)

**Comment by LautaroL20** [comment]
This issue must go on the BEE2.4 Application repository.

The issue was moved to: https://github.com/BEEmod/BEE2.4/issues/768
