### ISSUE TITLE
Static piston platform / Deployed panel

### ISSUE THREAD

**Issue by MisterSakamoto** [BEEmod/BEE2-items#2339]
I had this idea for an item looks like a platform with a white/black panel on top. In clean, overgrown, and BTS, it would look like the platform in Chapter 2's chamber 3. In portal 1 style it would look like the various piston platforms seen throughout the facility. It would have it's colour changeable.

There would be two versions. A simple one for style, raisable to quarter, half, 3 quarter, and full hight. The second would function similar to the victory lifts, but it is colourable.

**Comment by IceTudor** [comment]
This is basically the flat blocks and the still in development platform-lift. Am I right?

**Comment by Endermage77** [comment]
If you disabled Auto-Drop and Start Enabled and not wire any inputs into a normal piston,
it basically becomes this.

**Comment by MisterSakamoto** [comment]
It works kind like a quarter/half block, but it's just aesthetics.

The piston version would have a portalable surface though, so not the exact same
