### ISSUE TITLE
clump together textures in bottomless pit

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#234]
if this is even possible, there needs to be a way to override the textures applied to the walls of certain bottomless pits to clump together diffrent textures to match the area's above

![preview0229](https://cloud.githubusercontent.com/assets/11165643/12226473/971a9aac-b7ea-11e5-9d98-4fe5ca4775c5.jpg)

**Comment by Nick2007Portal** [comment]
How did you make pit THAT huge?

**Comment by Konclan** [comment]
This is still a problem
![20190828203557_1](https://user-images.githubusercontent.com/16567080/63903560-877e6200-c9d3-11e9-8469-d62eca14800e.jpg)

**Comment by Konclan** [comment]
#3891
