### ISSUE TITLE
Enhancements/Suggestions

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2341]
- [ ] There is an unused crusher icon in the files, you could use that instead as it looks more PeTI-like.
- [ ] There is also a quarter glass panel icon too, you could try to make 4 of those using photoshop or something to make the half glass door icon.
- [ ] The observation room was intended to be scaled, could be added, perhaps as a new item?
- [ ] P1 Style faith plates should have the old, panel version.

**Comment by LautaroL20** [comment]
You must split each suggestion into separated post, otherwise a good part of them, may never be implemented since its what happens to most of the piled-up suggestions here. Having a single suggestion per post will help developers treating it by separate and close it when it's finally done.

**Comment by Luke18033** [comment]
> There is an unused crusher icon in the files, you could use that instead as it looks more PeTI-like.

From what I remember that icon shows the crusher as being completely white, which it isn't. The current icon is better.
> There is also a quarter glass panel icon too, you could try to make 4 of those using photoshop or something to make the half glass door icon.

What's the filename? I've never seen this.
> The observation room was intended to be scaled, could be added, perhaps as a new item?

See #1165.
> P1 Style faith plates should have the old, panel version.

This has been suggested a few times before, but it's not going to be added, I don't remember why. What it'll probably be is just the Clean version with an orange glow below it.

**Comment by IceTudor** [comment]
> > There is an unused crusher icon in the files, you could use that instead as it looks more PeTI-like.

> From what I remember that icon shows the crusher as being completely white, which it isn't. The current icon is better.

I know, you could perhaps color it in to make it better, after all, the crusher is color-less, you could just tinker with contrast and brightness

> > There is also a quarter glass panel icon too, you could try to make 4 of those using photoshop or something to make the half glass door icon.

> What's the filename? I've never seen this.

C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2_dlc2\materials\puzzlemaker\palette\panel_door.png, again you could color it in, this time you really need colors. Not just contrast and brightness

> > The observation room was intended to be scaled, could be added, perhaps as a new item?

> See #1165.

Sorry, didn't see that post.

> > P1 Style faith plates should have the old, panel version.

> This has been suggested a few times before, but it's not going to be added, I don't remember why. 

> What it'll probably be is just the Clean version with an orange glow below it.

Oh, my mistake, though the orange glow items do look a bit bad, they kinda need proper styling.

**Comment by Luke18033** [comment]
Stop closing it...

**Comment by Luke18033** [comment]
> I know, you could perhaps color it in to make it better, after all, the crusher is color-less, you could just tinker with contrast and brightness

In that case wouldn't it be just like to the current icon?

**Comment by IceTudor** [comment]
https://prnt.sc/h4iein
There, it's edited in brightness and contrast, there's a difference, it looks MUCH more like PeTI style, those shots are incredibly high FoV and are a bit distorted, this looks preety good actually. Soo... is that a good crusher image or no?

**Comment by LautaroL20** [comment]
Stop reopening it....

**Comment by Luke18033** [comment]
Why? It's a perfectly valid issue. If you're going to close it because it's a bunch of suggestions combined into one, you should at least open new separate issues for them.

**Comment by LautaroL20** [comment]
> Why? If you're going to close it because it's a bunch of suggestions combined into one, you should at least open new separate issues for them.

I did this several times but it reaches a point where it starts to be somewhat strenuous, you should do it this time and find out how stressfulis it is. I never close any issue without exposing the reason for it, so its not my fault that you did not bother reading my comment.

However, TeamSpen210 has said on this subject long before you even did your first post at the Bee´s repositories: "Please, split up your suggestions into individual posts, so each one can be closed separately once imlemented."

We have already hundreds of suggestions, many of them probably never gonna be implemented, so if the author really cares about their suggestions, he will be agree at splitting them up into individual posts. This even helps the developer / collaborators or whoever who sees them to implement them at some point.

**Comment by Luke18033** [comment]
I added a note about posting issues separately to the [contributing guidelines file](../blob/master/docs/contributing.md), so hopefully this will happen less in the future

**Comment by Luke18033** [comment]
And it's still a suggestion, even if it's invalid.
