### ISSUE TITLE
Cake.

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2342]
A cake, delete the exit and place the cake, would act as an end to the map. Simple as that.

**Comment by Luke18033** [comment]
No, randomly ending the map isn't a good idea.

**Comment by IceTudor** [comment]
I was thinking you would have to get to the middle of the map to finish instead of getting to a side of it, basically an inside exit, without the elevator or any large parts.

**Comment by Endermage77** [comment]
This is more or less what I intended to solve with the Teleporter Entry/Exit, in that they would let you start in the middle of the floor instead of from a wall.
