### ISSUE TITLE
Upcoming Voluntary Contrib: Liquid Coloring Excision Field

### ISSUE THREAD

**Issue by Electricianfromhell** [BEEmod/BEE2-items#2344]
due to a idea from @Luke18033's suggestion when he confused my new Light Compacting Something Something with the Liquid Coloring Excision Field, i threw together the original pink liquid coloring excision field in a few minutes too and am in the process of finishing it up preparing a custom website called Ellington's hornet nest for the files to be released from...

this could be released in bee as a alternative to the paint fizzler, similar to the underground faith plate which can be selected as a repulsion blob and a mechanical plate...

![preview0033](https://user-images.githubusercontent.com/11165643/32247566-16f4d334-be59-11e7-8b1a-d04957068370.jpg)

**Comment by Luke18033** [comment]
Also see #2037, it needs to block portal shots and should be the laserfield variant of the Paint Fizzler.

**Comment by ellingtonvengaboysmuseum** [comment]
it already blocks portals and fizzles paint, i will let you guys do the laser field coding when you receive the files because that is a bit tricky...
