### ISSUE TITLE
Unable to pick up cube after activating portal gun ON OFF button + more

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2348]
found a bug: i am Unable to pick up any cubes after activating the new portal gun control button 

![preview0068](https://user-images.githubusercontent.com/11165643/32253547-e18d2a0c-be71-11e7-9c55-6eb2c65dad04.jpg)

also i can walk through cubes...

![preview0075](https://user-images.githubusercontent.com/11165643/32253551-e5093680-be71-11e7-916c-7584c2b9077f.jpg)

**Comment by Luke18033** [comment]
Now fixed. (I think...)
