### ISSUE TITLE
New Style: Dark BTS

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2352]
New Style; Dark BTS

It't the pitch black area's of BTS where wheatley guides you around with his flashlight...

**Comment by Endermage77** [comment]
It could just simply be a new fog that is really really foggy.

**Comment by ellingtonvengaboysmuseum** [comment]
can't be a fog, would have to be a copy of the style, it would have many changes, especially to the lighting...

**Comment by Endermage77** [comment]
If it's foggy enough, surely it could replicate darkness?
That way you could use it in any style.

**Comment by ellingtonvengaboysmuseum** [comment]
using too much fog would take a toll on the CPU

**Comment by IceTudor** [comment]
It would be hilarious if light squares were the core with its flashlight on from pre final-boss

**Comment by Luke18033** [comment]
How exactly would this be useful?

**Comment by Luke18033** [comment]
I'm going to close this, since it doesn't seem very useful.
