### ISSUE TITLE
new test element: god cube

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2353]
see it here

https://www.youtube.com/watch?v=quUu_xu6lNA

**Comment by Luke18033** [comment]
So, the Paint Gun?

**Comment by LautaroL20** [comment]
Well, when i saw the title i thought of a cube indestructible to emanzipation grids / deadly goo...

**Comment by HugoBDesigner** [comment]
Cube that's immune to fizzler... Wouldn't that just come with the Blue Portals elements? Considering they're even getting added.

**Comment by Luke18033** [comment]
That would be the Unfizzlable Cube included on the list at #2139.

**Comment by HugoBDesigner** [comment]
Yup, that's what I thought

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment]
Here we go again with these dummy suggestions.... If you want the Paint Gun, or an Unfizzleable Cube just suggest it. Since the item that shows the video is really messy, and therefore it could confuse players at some point.

**Comment by Luke18033** [comment]
Well the paint gun already exists in Tag, so I guess this would just be invalid.

**Comment by maxdevgithub** [comment]
Oh reepblue had gel cubes too https://youtu.be/YBcLffvQRs0
