### ISSUE TITLE
New Animations

### ISSUE THREAD

**Issue by EmirhanBudak** [BEEmod/BEE2-items#2354]
-Waking up animations
-Beds
-When you sleep in the bed map finish if you want
-Dying on map ending finish maps

**Comment by TeamSpen210** [comment]
These have been suggested several times before. It's not happening for several reasons. One is that these really require Hammer work to make it make sense (designing the surrounding environment), which is not possible in PeTI. Two, you'd need it to match across the level transition, implying some sort of storyline - which is not suitable for PeTI either. Third, it's going to be nonsensical in many cases, without particular environmental work (for waking up, where did you come from?).
