### ISSUE TITLE
Help needed with fizzler

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2356]
What triggers/brushes can you use for fizzlers? I want to make one but I don't know how to make it fizzle cubes and turrets. Or block portal bullets and turret bullets.

**Comment by TeamSpen210** [comment]
Any that actually exist? This is really more of a Hammer question.

**Comment by ZombiePwner1** [comment]
@IceTudor Please use this tutorial in order to know how to make fizzlers in hammers this is where i learn't my hammer skills from. https://www.youtube.com/watch?v=12tcxImSpcs
