### ISSUE TITLE
add clip inside 50's diversity vents on windows

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2360]
add clip inside 50's diversity vents on windows, player and cubes can get stuck on the edge of the window frame

![preview0102](https://user-images.githubusercontent.com/11165643/32296729-5e14148a-bf23-11e7-870f-97c8d50fd239.jpg)

**Comment by TeamSpen210** [comment]
Since cubes can rotate they generally shouldn't get stuck.
