### ISSUE TITLE
Radiative Flux Rectangle unable to be connected to any inputs

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2362]
The Radiative Flux Rectangle unable to be connected to any inputs in PTI

i don't know if this is on purpose, but i am unable to connect it to a button etc to turn it on and off...

**Comment by Luke18033** [comment]
Read the description, you need to use the Fizzler Output Relay.

**Comment by TeamSpen210** [comment]
Unfortunately fizzler items don't allow outputs that work correctly.
