### ISSUE TITLE
hard to see visible no draw in clean exit elevator

### ISSUE THREAD

**Issue by mario2582** [BEEmod/BEE2-items#2364]
hard to see visible no draw in clean exit elevator found, it's up high in the ceiling of the elevator

![preview0114](https://user-images.githubusercontent.com/11165643/32304052-ce1b01c0-bf42-11e7-893e-6ee8e0080494.jpg)

![preview0109](https://user-images.githubusercontent.com/11165643/32304055-d2aac874-bf42-11e7-9188-23eb0b7d7553.jpg)

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Spencer pls.

**Comment by TeamSpen210** [comment]
This is fixed.
