### ISSUE TITLE
Voluntary Contrib: PeTI Crusher Icon

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2365]
The regular crusher icon looks a bit too "Ingame" unlike PeTI's flat colors, so I took the time to make (well, modify an old unused image for) a PeTI-like crusher icon.
![ur_face](https://image.prntscr.com/image/yVya0NQbSQCM416V4z7iGA.png)

**Comment by ZombiePwner1** [comment]
@IceTudor Yes the crusher wasn't mean't to appear in the PeTI but was scrapped for unknown reasons.

**Comment by IceTudor** [comment]
I know, I took the old image, tinkered with contrast and brightness, then finally readded the background, good as new!

**Comment by Luke18033** [comment]
You might want to change the colors a bit, but other than that it looks good. Here's the current icon for reference:
![crusher](https://raw.githubusercontent.com/BEEmod/BEE2-items/master/packages/bee1/beemod/resources/BEE2/items/clean/crusher.png)

**Comment by ZombiePwner1** [comment]
@Luke18033 Now that i think about it alot of the beemod icons need a PeTI cartoonish icon like what @IceTudor was saying since they look too similar to the in-game models.

**Comment by TeamSpen210** [comment]
Just to note, the image should be 256x256. I do think the colour of your version is a bit off, we'd really want the original file.

**Comment by IceTudor** [comment]
The original file is small aswell. It's in portal2_dlc2/materials/puzzlemaker/pallete. There are lots of things there, including some left over old BEE2 items that are still there.

**Comment by IceTudor** [comment]
I also tried making a drawbridge icon. It's horrifically crude and just garbage. Unusable

**Comment by Luke18033** [comment]
We'll want to just remake this icon entirely.
