### ISSUE TITLE
Portal Fizzler?

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2366]
Is it possible to make a fizzler which you can place portals through? Cubes, turret bullets and players, along with gel could go through it, but portals would simply be placed on it.

**Comment by TeamSpen210** [comment]
No.

**Comment by IceTudor** [comment]
Darn. Is it possible to make the closed solid field reversable so that you can place portals on it? some sort of white wall or something?

**Comment by TeamSpen210** [comment]
Maybe, but it's not a good idea. Since it's transparent, you can see tha back side of a portal, and they aren't designed to work correctly for that - it doesn't look sensible.

**Comment by Endermage77** [comment]
I could see this as a sort of opaque fizzler that would, instead of a field, emit jets of conversion from the emitters, creating an opaque white field that acts as a portalable CSF.

**Comment by ellingtonvengaboysmuseum** [comment]
this is a item i will be making eventually and it will be VERY Challenging, it will be completely opaque and use the conversion gel texture...
