### ISSUE TITLE
Rotating Light Bridge (Bridge on Rotating Panel)

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#2368]
New Item - Rotating Light Bridge, it's a bridge on a Rotating Panel

see video to see it work!

https://www.youtube.com/watch?v=Mqd_Gabew6o

**Comment by TeamSpen210** [comment]
I'd probably build it differently (rotate a smaller part so it doesn't collide with neighbouring items), but this would be a good thing to have.

**Comment by Konclan** [comment]
#3889
