### ISSUE TITLE
some modder has created working sticky gel and a NEW GEL

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2369]
some modder has created working sticky gel and ELECTRIC GEL, take a look, lets see if we can reverse engineer this map and implement our own variant of gels...

https://www.youtube.com/watch?v=tWlEyD3cNFg

**Comment by LautaroL20** [comment]
Not possible for Puzzlemaker. This has been discussed several times already.

**Comment by TeamSpen210** [comment]
I have his Adhesion gel instances. They aren't possible to use in PeTI, additionally the two gels there was only possible AFAIK before Peer Review.
