### ISSUE TITLE
Itemvar to swap Light Bridge between 6-way and 8-way handle

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2370]
Title says it all.

**Comment by Luke18033** [comment]
Why didn't you just add this to #2332?

**Comment by LautaroL20** [comment]
@Luke18033 - We must prevent combining multiple suggestions into one post, but for this particlar case where they are somewhat related to each other, we could do an exception.

**Comment by Luke18033** [comment]
Yeah, I'd say it's fine in this case since they're both about swapping items with a 6-way handle to have an 8-way handle. Another case would be reporting multiple bugs with the same item.
