### ISSUE TITLE
New Item: Mid Air Portals

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2371]
How did he even create this one?! how did he get the portal gun to fire a HEP...

https://www.youtube.com/watch?v=LOO3zHCfGxU

**Comment by TeamSpen210** [comment]
Worldportals.

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 - how did he get the portal gun to fire a HEP...

**Comment by Luke18033** [comment]
Should this be closed? I don't think it's going to be implemented.
