### ISSUE TITLE
Franken Spheres?

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2373]
Franken cubes are simple really, 2 turrets merged into a cube, they can walk and stuff
What about a franken sphere?
A rocket turret in a sphere, they would hide inside the sphere using a hole, and roll around towards players when their tripwire is triggered, instead of walking.
This would be a great addition for a sphere in the wheatley era.
It could also be a stylevar.

**Comment by TeamSpen210** [comment]
Can't be done really.

**Comment by IceTudor** [comment]
Darn.
