### ISSUE TITLE
Upright horizontal lift

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2375]
Some form of piston lift that would be placed on walls and extend horizontally, while still having a surface to stand on for the player

**Comment by Endermage77** [comment]
A panel-track variant of the Unstationary Scaffolds, perhaps?
I feel like I've suggested that somewhere, but I can't remember precisely where.

**Comment by IceTudor** [comment]
I was thinking of a victory lift that, instead of moving on a track or raising on a piston, it moves closer or farther away from the piston horizontally, kinda like just putting a lift on the wall and having the platform and ONLY the platform upright.

**Comment by IceTudor** [comment]
Dunno about other styles

**Comment by Endermage77** [comment]
Ah, sideways-panel pistons.
I don't know why nobody thought of this earlier.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
this is basically a extendable version of my rotating panel idea  #2204

**Comment by Konclan** [comment]
#3889
