### ISSUE TITLE
new item: cube dropper that drops more than 1 cube at once

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2376]
got a idea, a cube dropper that drops more than 1 cube at once

it would work like so, it the cube dropper should be colored blue to make it so players know its diffrent

- you would use the timer value to set the number of cubes it would drop
- if one got fizzled, they all would
- so if the timer was set to 5 it would drop 5 cubes that could be used in a test, but if one of those five got destroyed (fizzled, fell into a goo/bottomless pit etc.) they would all self fizzle...

i may create this item - @TeamSpen210 or @Luke18033 

1. how do i add a timer to the cube dropper and make it determine how many cube the dropper makes at once.
2. how do i make the dropper produce more than 1 cube
3. how do i make all the dropped cubes, fizzle at once if one is destroyed?

**Comment by TeamSpen210** [comment]
Timer values are already used for something different.

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 - then what do you suggest we use to determine the number of cubes dropped?

**Comment by Endermage77** [comment]
Maybe some sort of counter item that you stick on the same space as a dropper, like the colorizer, that affects how many things it drops?

**Comment by WhoozYerBuddy** [comment]
I don't see why that would be beneficial.  You can add more droppers if you want more cubes to drop.  Seems like it would just add confusion with no benefit.

**Comment by ellingtonvengaboysmuseum** [comment]
@WhoozYerBuddy - did you pay any attention to what i said, say it drops 4 cubes, if one of those 4 gets fizzled, they all do.. this could create some interesting puzzles where you couldn't let any cubes be destroyed...

**Comment by WhoozYerBuddy** [comment]
Yup, still don't see the benefit.  That's logically no different from 4 droppers connected to 1 button and 4 cubes required for exit.

**Comment by Luke18033** [comment]
Indeed, this isn't too useful.
