### ISSUE TITLE
50's 3x3 vactube corner is wrong style

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2377]
i don't know if anyone knows this, but the 50's 3x3 vactube corner is the wrong style, it's the 3x3 clean vactube instead of the old one...

**Comment by Luke18033** [comment]
Duplicate of #1356.

**Comment by LautaroL20** [comment]
@Luke18033 - Do not forget to apply the "duplicate" label when closing the issue.
