### ISSUE TITLE
BumbleBall causes the map to leak

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2381]
When one or more BumbleBalls are present, a few filter entities are added outside the map as shown below, causing a leak.
![image](https://user-images.githubusercontent.com/19228201/32400855-eca1a6fe-c0c2-11e7-81a4-c14577dc6ae3.png)
It looks like the entities are supposed to be appearing in the nodraw box on the right, but for some reason they're showing up outside instead. Only tested on Clean style.

**Comment by TeamSpen210** [comment]
Yep, I noticed and fixed that yesterday.

**Comment by Luke18033** [comment]
Oh, I must need to sync my GitHub.

**Comment by IceTudor** [comment]
What's a bumbleball?

**Comment by Endermage77** [comment]
It's essentially an edgeless safety cube (ball) that bumbles around when you're not directly looking at it.

**Comment by IceTudor** [comment]
Oh, seems like an odd idea.

**Comment by TeamSpen210** [comment]
It's an interesting device, because that allows you to remotely control it in a sense - blocking lasers for example, or having it move through an area.
