### ISSUE TITLE
Large crusher

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2382]
A 4x4 crusher that extends 3 or 4 voxels. As seen in the panels trailer.

**Comment by TeamSpen210** [comment]
This is the "Slow Crusher" in issue #95.

**Comment by TeamSpen210** [comment]
Duplicate of #95

**Comment by IceTudor** [comment]
It's not slow, it's just as fast as the regular crusher.

**Comment by TeamSpen210** [comment]
There's only actually one size of crusher in the game.

**Comment by IceTudor** [comment]
Really?
