### ISSUE TITLE
mel music not listed in bee2

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2383]
the mel music package is found in the packages folder, but the music is not listed in bee2... also mel doesn't have PTI...

the music should be ported from Mel right into the package itself, so Mel doesn't have to be installed just to get the music...

**Comment by Luke18033** [comment]
Is Mel installed on the same drive as Portal 2?

**Comment by ellingtonvengaboysmuseum** [comment]
see the more advanced issue related to this... closed
