### ISSUE TITLE
Old Aperture On/Off Buttons and Bomb Cubes are missing their models

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2384]
The items are styled and fully functional, but the models just aren't included, even in dev.
![20171104185544_1](https://user-images.githubusercontent.com/19228201/32411185-0f1fffe4-c192-11e7-9576-397c17bf2cd8.jpg)

**Comment by ZombiePwner1** [comment]
F***ing lol

**Comment by ZombiePwner1** [comment]
@Luke18033 BTW it seems your a fan of portal 2's beta.

**Comment by Luke18033** [comment]
I'd assume the buttons are supposed to look like this?
![stuff](https://steamuserimages-a.akamaihd.net/ugc/843713288760956016/09EEBE2CFDBB7F4D35FB965C2A5570D80726C25F/)
