### ISSUE TITLE
how will the new bottomless pit generator work with something like this

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2385]
how will @TeamSpen210 go about creating a bottomless pit with the new code eventually with this (fan) in it

also how did they get the cubes in those pipes because i thought their was only a handful of animations for cubes in pipes...

![sp_a3_concepts0010](https://user-images.githubusercontent.com/11165643/32411648-98fe4124-c1b7-11e7-84f7-0dd87c4f1611.jpg)

**Comment by ZombiePwner1** [comment]
@ellingtonvengaboysmuseum They most likely used some custom models with custom animations or they edited the original models and added some more animations.

**Comment by TeamSpen210** [comment]
Or used tracktrains.
