### ISSUE TITLE
Voluntary Contrib: Bee2 OST

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2388]
This is part of an OST series of mine, it works well for an excursion funnel type song (hence the name) but for now I gotta find a way to at least upload it somewhere here

**Comment by IceTudor** [comment]
P.S. The OST series is called Bee2 Original Soundtrack, as I'm developing it for Bee2.4 as default music that anyone can use.

**Comment by Endermage77** [comment]
Neato!

Er...
This is a music track, right?
May want to add a New Music tag.

Would you like to provide a sample if you have one available?

**Comment by IceTudor** [comment]
Dunno how to upload music onto here, I'm also currently making it for the Light Bridges and Faith Plates.

**Comment by TeamSpen210** [comment]
Note that ingame audio needs to be WAV files.

**Comment by IceTudor** [comment]
Darn. Have to change them then.

**Comment by IceTudor** [comment]
I mean, you could have it as a separate folder so that people can test it
Just saying.

**Comment by IceTudor** [comment]
... Darn, I can't upload even 2 of my songs in a zip file. It's more than 10 MB. Anyone know how to upload music here?

**Comment by TeamSpen210** [comment]
That's not what comments are for. GitHub is expecting you use it for what it's designed for - clone the repro and make Pull Requests.

**Comment by IceTudor** [comment]
Ok, gonna see what I can do then.

**Comment by Luke18033** [comment]
This didn't really go anywhere.
