### ISSUE TITLE
new item: partial block item mover

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2390]
new item: partial block item mover

we need something like this when you are placing partial blocks on a wall or ceiling or anywhere etc and want to place a light strip or button or something in the same wall, we need a item that if it's placed on another item you want to move outwards. whether it's a light strip, observation room, laser or tractor beam, paint tube or vent tube, or entry or exit door, the partial wall item mover will move the item it is placed on out 1/4, 1/2, or 3/4th of a voxel to make it match the position of a partial block wall for example...

**Comment by BETTEREXTENEDEDITORMOD** [comment]
when i installed bee2 i thought it did this but when i tested it it did not

**Comment by IceTudor** [comment]
Actually this flaw gives some interesting features if used with goo (See https://github.com/BEEmod/BEE2-items/issues/2334). It should be a stylevar/enhancement/variation of the partial block item instead. Maybe, start open?

**Comment by Luke18033** [comment]
See #1485.
