### ISSUE TITLE
Fizzler PeTI don't close/open when active/désactive, why ?

### ISSUE THREAD

**Issue by YUKI67000** [BEEmod/BEE2-items#2391]
https://www.youtube.com/watch?v=TBehc9L-U3s   Hi, I would like to fix the fizzler bug for PeTI. I know that with hammer we can achieve it. and that BEE2 to also fix the bug. But what I would like is to fix this bug in PeTI (for people who do not want to use BEE2!). I read your article on the page "editoritems.txt" (which said: The instance is named target123_modelStart123 or fizzler123_modelEnd123. Due to a bug, inputs are sent to target123_modelStart. This is fixed by the BEE2, setting names to fizzler123_modelEnd.) For several days with friends we seek the solution, but we do not find it. My question is: How to fix the fizzler bug for PeTI WITHOUT using BEE2 or Hammer?

**Comment by TeamSpen210** [comment]
You cannot without a compiler like BEE2's or Hammer. If you really want to use the vanilla items, you could use the Stylechanger compiler which also fixes the issue.
