### ISSUE TITLE
mel music not working with portal 2 (with mel installed)

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#2394]
@TeamSpen210 or @Luke18033 - Mel music is not playing in portal 2 when selecting it in bee, even if you have portal stories Mel installed...

best bet is to extract the music files from Mel and pack them in a zip like the p1 music and pack them in the map when they are used...

**Comment by Tjmcnee** [comment]
This happened to me too, but all I did is just uninstall bee from portal 2then reinstall it back.

**Comment by seagemgames** [comment]
This should probably be tagged as invalid now.
