### ISSUE TITLE
Change Name of Bumbleball to something else to protect Bee2.4 Repositories from Trademark Reports

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2395]
Just thought of this when researching a interesting Digital Millennium "Controlfreak" Act case... You should change the name of the Bumbleball to something else to protect this project (Bee2.4) from a DMCA Takedown Notice from Trademark Trolls

Ertl toys is known to have trademark trolls file DMCA notices when their "bumbleball" toy name is mentioned in pretty much anything without them receiving royalties for the usage of the trademarked name...

i have a suggested alternate name for this to protect this project from Ertl. Call it the "Aperture Motorized 'Living' Ball"

**Comment by ZombiePwner1** [comment]
@ellingtonvengaboysmuseum DMCA can just go kill themselves if they ask why we stole a name we'll just make an excuse and say. Oh we just came up with that name we aren't aware that you had a toy named bumble ball.

**Comment by LautaroL20** [comment]
This is just a mod, i doubt any copyright law would affect this tool. Different scenario would be if this were a paid software.

**Comment by IceTudor** [comment]
What about:
The Aperture Science *Quantum Mechanical Hop Ball
*We'd use that as the ingame and bee2 Name

**Comment by ellingtonvengaboysmuseum** [comment]
@LautaroL20 and @TeamSpen210 -

Reopen this, i asked a few lawyers some questions on legal zoom and they basically all said the same thing. they said it wouldn't matter if this was a mod or not or if this was free or not, the plain usage of the trademarked name "bumble ball" is still trademark infringement of ertl's trademark. and trademark law is even more draconian than copyright. usage of a trademarked name in pretty much anything affects trademark laws no matter what and ertl could still file a trademark infringement notice against this project and have it removed and you would not be able to file a counter notice because they would sue... so Change the name of the bumble ball as i first suggested...

**Comment by LautaroL20** [comment]
@ellingtonvengaboysmuseum - I still doubt they could affect Bee2.4, worst senario i could imagine is they sending a report to GitHub to remove all the repositories. Well, ill re-open this just in case then....

**Comment by ncrecc** [comment]
The Aperture Science Compulsive Attention Seeker.

**Comment by Luke18033** [comment]
I don't think this is really going to be a problem.
