### ISSUE TITLE
Stylevar for BTS - Floor button changer

### ISSUE THREAD

**Issue by Reiid** [BEEmod/BEE2-items#2396]
I think there should be a stylevar for BTS that changes the floor buttons to regular clean buttons (or maybe old aperture ones), instead of the quality control devices we have currently. The pedestal buttons, however, should stay the same.

**Comment by LautaroL20** [comment]
Having an option to changing them to the Clean version would be acceptable, since BTS style may be a little bit related with Clean Style.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
