### ISSUE TITLE
fog customizer 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2398]
[when you go into the skybox options and you click a skybox there's boxes with colors in them but when you click on them nothing happens there should be three options fog density fog color and 3d skybox]

1st [fog density this will change how foggy the chamber is when set to max you could barely see anything but when set to the lowest setting fog is turned off]

2nd [fog color you could change the color of the fog from bright pink to blood red 
you could also make a color sequencer this changes the color of the fog for a set amount of time 
 it could be for 3 seconds or 10 and you could change the intervals you could change how fast it happens it could slowly turn to another color or spike like an explosion happened]

3rd [3d skybox there's not much to say here so i'll make it quick 
this option will make any goo pit into a 3d skybox you could change the color of the pit with a color wheel it has the same options as fog color]

**Comment by TeamSpen210** [comment]
For 1, this isn't really needed - it's not something you should worry about. For 2 fog colours are based on the style, it's not an arbitrary thing. It might be possible to alter the colours like that, but that's also not useful - it needs matching sound effects, visuals, and other things to make it mean anything. For 3, the 3D skybox choice is nowhere near as basic as a pit colour. This is not something you need control over, probably I should just move fog settings back into the styles. BEE2 is not an 'easy hammer'.
