### ISSUE TITLE
Make screen monitors stop becoming smaller?

### ISSUE THREAD

**Issue by KickitBack** [BEEmod/BEE2-items#2399]
Is it possible to make the screen monitors at the beginning of the test not become smaller? It's a minor problem I have, but I still want to know if it's possible to remove this feature.

**Comment by TeamSpen210** [comment]
Could you take a screenshot or clarify? I'm not sure what you mean.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the "invalid" label when closing the issue.
