### ISSUE TITLE
Wall Faithplate

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2400]
A 1/4 centered glass panel on the wall that would act exactly as a faith plate would, only that you can trigger it by touching the panel, the panel would be extended into the middle of the voxel it is facing and would be diagonal.
You could have the handle 4 rotations on this.
This could also be a sort of variation of the far panel

**Comment by TeamSpen210** [comment]
What’s the difference between this and a large plate? Also I don’t really think we should use regular panels as faith plates, it’s not as clear.

**Comment by IceTudor** [comment]
Well, this one has an EVEN LARGER trigger area, which is exactly 1 voxel thick, it's supposed to be used on walls, as a way to launch you if you are close or touching the wall, you could use a 30 degree angled block with a 
regular faithplate on it if you want

**Comment by TeamSpen210** [comment]
I don't think this is necessary.
