### ISSUE TITLE
1/8th wall item

### ISSUE THREAD

**Issue by awesomedoctorx3** [BEEmod/BEE2-items#2403]
a variant on the 1/4th wall, except it's thinner, being 1/8th of a block. This will be much less obtuse, as it'll  look better with glass and fizzlers side by side. 
Also, a window item variant will have to be made, if this is made to match the 1/4th wall and its window item.

**Comment by TeamSpen210** [comment]
Generally speaking we don't have walls that thin - 1/4 is the smallest tile size.

**Comment by awesomedoctorx3** [comment]
Oh. If I knew how to make new textures, I would.

**Comment by TeamSpen210** [comment]
It's moreso that they aren't ever used, so it's probably not that useful.

**Comment by awesomedoctorx3** [comment]
aw, okay. :(
