### ISSUE TITLE
Rocket Turret

### ISSUE THREAD

**Issue by Fazbear189** [BEEmod/BEE2-items#2404]
Are you ever going to fix the rocket turret? If you are not you might as well remove it.
I am sure you are aware that is is really broken.

**Comment by Byzarru** [comment]
The Rocket Turret is broken in the following issues: #2284, #2062, #1986, #1984, #1909, #1761, #1238, and many more I didn't bother to look up. It's definitely on the to-do list, but not a high priority considering the other items that are being developed.

**Comment by LautaroL20** [comment]
@Byzarru - Awesome duplicates compilation, Byzarru. I could only find one duplicate as much to provide...
