### ISSUE TITLE
Franken Cube is unusable in most styles

### ISSUE THREAD

**Issue by AlmisuiFR** [BEEmod/BEE2-items#2405]
As you can see, it gets stuck in the dropper:

![20171118134913_1](https://user-images.githubusercontent.com/33737167/32980726-43eb34c0-cc6c-11e7-9264-12303ba7448a.jpg)

Franken doesn't spawn and dropper remains open. Even when not activated, there are continuous "bouncing" sounds inside : franken is stuck and bouncing at the bottom of the dropper since the map starts.

![20171118135011_1](https://user-images.githubusercontent.com/33737167/32980749-a8bdecbc-cc6c-11e7-83b8-cdac5181a96f.jpg)

**Comment by Luke18033** [comment]
Stop, you don't need to edit every single post to have "mysterious way" in the title.

**Comment by ZombiePwner1** [comment]
@LautaroL20 You should probably stop doing that because it is actually starting to get annoying.

**Comment by LautaroL20** [comment]
Error 404: sense of humor not found.

**Comment by AlmisuiFR** [comment]
Now I see. I was curious about the "mysterious way" Lautaro modified my words!

**Comment by AlmisuiFR** [comment]
Title edited: same issue in "clean" style.

**Comment by TeamSpen210** [comment]
Clean and Original Clean use the same items.

**Comment by TheTored** [comment]
Also happens in Overgrown.

**Comment by LautaroL20** [comment]
I can confirm this bug is not related to old resources from past releases. It is a true bug report.

**Comment by Luke18033** [comment]
Does this still happen?
