### ISSUE TITLE
Add Contraption Cube from Portal 2 Educational Version?

### ISSUE THREAD

**Issue by KickitBack** [BEEmod/BEE2-items#2408]
If it's possible, adding the contraption cube and button from the educational version of portal 2 would be great!
https://www.youtube.com/watch?v=uHYSW92pjWU shows the contraption cubes in action.

**Comment by ZombiePwner1** [comment]
We can add the cube and the button but the cube's functionality will not work since that is part of the educational version's code the only way to get it to work in portal 2 would be to bring the code over which we can't do unfortunately.
