### ISSUE TITLE
Missing overgrown signage textures

### ISSUE THREAD

**Issue by Cellolide** [BEEmod/BEE2-items#2410]
If I choose the overgrown style and then test my chamber including the signs with the dots 1-4 I do just have white fields (see screenshot).

Am I doing something wrong?
![20171122182552_1](https://user-images.githubusercontent.com/33907318/33141182-a145bba6-cfb2-11e7-9b33-047c0f851e2a.jpg)

Thx for help.

**Comment by LautaroL20** [comment]
Are you using the Item Signage, or these are just the glass panel´s symbol connections?

**Comment by Hotten66** [comment]
I am using the item signage. Disabled the symbol connection of the glass panels. However only the "dots" indicating 1-4 don't work. As you can see the exit symbol and any other work fine

**Comment by Konclan** [comment]
I've already fixed this and sent the fix to TeamSpen; apparently, the info.txt had some spelling mistakes in the texture names. This was also the case for the box dropper signage; however, the cube hurt signage is completely missing. Still working on fixing that one.
