### ISSUE TITLE
Failed to Build

### ISSUE THREAD

**Issue by Fazbear189** [BEEmod/BEE2-items#2411]
Every time I place a Unstationary Scaffold Wall Emitter into a map it fails to build. In the console it says an error that says something about bee and vbsp.

**Comment by Luke18033** [comment]
Can you post the actual error message?

**Comment by Fazbear189** [comment]
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr27 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'fizz_visiblity': '0', 'voice_pack': 'BEE2_GLADOS_P1'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[INFO] cond.cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[INFO] fizzler.read_configs(): Loaded 12 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Using random SP Entry (6)
[INFO] vbsp.mod_entryexit(): Using random SP Exit (3)
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (17 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] brushes.res_import_template(): IDS: set()
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: N, Orange: N
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['orangeportal', 'orangeportalspawner', 'orangeportalgun', 'singleportalgun', 'blueportal', 'blueportalspawner', 'autoportal', 'pack_p1_radio_clean', 'pelletcatcher', 'pellet', 'pelletlauncher', 'spawn_nogun']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=4320, misses=358, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'doorcameras': False, 'p1_ported_pgun': True, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': True, 'unlockdefault': True, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/p1/set_portalgun.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding global ents...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/p1_pgun_sounds.txt"
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/p1_physics_sounds.txt"
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/pellet_sounds.txt"
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/portal_sounds.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_physics.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_player_portal2.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_weapons_portal.txt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_blue.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_blue.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_exponent.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_glass.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_glass.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_normal.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_orange.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_orange.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/coffee_mug.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/coffee_mug.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/door_01.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/door_01.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/light_recessedcool_glow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metal_lift001.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metal_lift001_gradient.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metal_lift001_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metal_lift_cube.hdr.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metal_lift_cube.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metal_lift_grad_mask.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/modular_wall_light.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/overlay_light_gradient.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/physring.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/physring.vtf"
[INFO] vbsp.make_packlist(): "materials/effects/comball/comball.vtf"
[INFO] vbsp.make_packlist(): "materials/effects/eball_finite_life.vmt"
[INFO] vbsp.make_packlist(): "materials/effects/eball_infinite_life.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow1.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow1.vtf"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow2.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow2.vtf"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_sphere.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_sphere.vtf"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_tape.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_tape.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props/autoportal_frame/autoportal_frame.vmt"
[INFO] vbsp.make_packlist(): "materials/models/props/autoportal_frame/autoportal_frame.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props/autoportal_frame/autoportal_frame_exp.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props/autoportal_frame/autoportal_frame_n.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props/ball_catcher_clean.vmt"
[INFO] vbsp.make_packlist(): "materials/models/props/c_ball_launcher_clean.vmt"
[INFO] vbsp.make_packlist(): "materials/models/props/combine_ball_catcher_clean.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props/combine_ball_launcher_clean.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props/light_rail_wall_emitter.vmt"
[INFO] vbsp.make_packlist(): "materials/models/props/light_rail_wall_emitter.vtf"
[INFO] vbsp.make_packlist(): "models/BEE2/p1_pgun.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/pgun_pedestal.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/coffee_mug.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/coffee_mug_chunk1.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/coffee_mug_chunk2.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/coffee_mug_chunk3.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_frame_thick.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_left.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_right.mdl"
[INFO] vbsp.make_packlist(): "models/effects/combineball.mdl"
[INFO] vbsp.make_packlist(): "models/props/Light_Rail_wall_emitter.mdl"
[INFO] vbsp.make_packlist(): "models/props/autoportal_frame/autoportal_frame.mdl"
[INFO] vbsp.make_packlist(): "models/props/clean/combine_ball_catcher.mdl"
[INFO] vbsp.make_packlist(): "models/props/clean/combine_ball_launcher.mdl"
[INFO] vbsp.make_packlist(): "models/props/light_rail_wall_emitter.mdl"
[INFO] vbsp.make_packlist(): "precache_sound:physics/metal/metal_box_scrape_rough_loop1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:physics/metal/metal_box_scrape_smooth_loop1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete2.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete3.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete4.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal2.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal3.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal4.wav"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/set_p1_pgun.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/bee2/portal_man.nut"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/alyx_stunner2.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/charge_pgun.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/doorstop1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/garage_stop1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/ambient.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_enter1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_enter2.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_exit1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_exit2.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/wall_move5.wav"
[INFO] vbsp.make_packlist(): "sound/bee2/p1/scaffold_loop.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_bounce1.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_bounce2.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_disintegrate4.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_disintegrate5.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_explosion2.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_flyby1.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_flyby2.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_loop4.wav"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Jun 28 2017)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/BEE2/clean/items/scaffold/wall.vmf
 | 
 |_

[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

**Comment by Luke18033** [comment]
Do you have any Unstationary Scaffold Wall Emitters in the map?

**Comment by LautaroL20** [comment]
`Could not open instance file instances/BEE2/clean/items/scaffold/wall.vmf`

**Comment by Fazbear189** [comment]
Yes I have those in the map. But if I remove them I still get the error.

**Comment by Fazbear189** [comment]
I also get it with any custom fizzler.

**Comment by Fazbear189** [comment]
The Unstationary Scaffold Wall Emitters were working before but when I added auto portals everything stopped working. I am using the portal 1 style.

**Comment by Luke18033** [comment]
Do you have the unstationary scaffold items connected in a loop? That doesn't work currently and causes a compile error.

**Comment by Fazbear189** [comment]
I have Start Enabled and Start Reversed on and I just want it to move to the exit door and back. It was working before then once I changed the items then I left the game then came back and it would not work anymore.

**Comment by Fazbear189** [comment]
I just noticed, I meant to say if I remove them I don't get the error.

**Comment by Fazbear189** [comment]
I just placed the item again and it works now. But now I have another item issue.
