### ISSUE TITLE
Portal gun appears floating next to the pedestal

### ISSUE THREAD

**Issue by John2027** [BEEmod/BEE2-items#2412]
When I use the portal gun pedestal this happens.
![20171124162132_1](https://user-images.githubusercontent.com/33005627/33224101-ecbeb1b4-d133-11e7-85d9-fde74add515a.jpg)

**Comment by LautaroL20** [comment]
Wow, that is really mysterious....

**Comment by Fazbear189** [comment]
This is really annoying.

**Comment by LautaroL20** [comment]
@Luke18033 - Ill respect other´s people issues. However ill keep doing this on mines.

**Comment by Luke18033** [comment]
It's fine if you do it on your issues, I just find it kinda annoying how you do it with everyone else's as well.

**Comment by Luke18033** [comment]
Now fixed
