### ISSUE TITLE
New Item: Drained Cube

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#2415]
A cube that cannot trigger buttons; it's main idea is to be able to jump on it and use it as a platform, a turret blocker, etc. Most likely would be found in groups to create stairs or some similar fashion to get up to a higher place. Good for puzzles, since they don't trigger anything.

EDIT: If wanted, they could also not have gel on it, which probably means it has to change a bit more with appearance if this feature is added.

Appearance: Looks just like your normal cube, but the blue ring around the Aperture logo is instead grey, like it's out of power, or, drained.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
how i imagine it would look is a normal cube but the inside is hollowed and replaced with a rollcage all sides would be covered up by circular grating pieces to prevent you from you falling inside the only things that would be left of the original cube would be the vertexes and the edges 
<img width="282" alt="capture 65" src="https://user-images.githubusercontent.com/31172185/33537840-b696a344-d872-11e7-8e28-4d6eb6ae9639.PNG">
something like this

**Comment by Endermage77** [comment]
I'd say that looks like a redirection cube, not a weighted cube.

**Comment by Konclan** [comment]
I don't see the absolute purpose of this cube, It'd be better if it fit with another test element but otherwise this just seems like a wasted use of model space.

**Comment by TeamSpen210** [comment]
Not being able to press buttons requires it to not be paintable also.

**Comment by CaliMari** [comment]
This is useless really. :/

**Comment by BETTEREXTENEDEDITORMOD** [comment]
maybe if a laser hit it it would be so light that the laser would push it. that would make for some interesting puzzles

**Comment by Endermage77** [comment]
Hmmm...
