### ISSUE TITLE
TDB Closed Solid Field - still the same error as version 25

### ISSUE THREAD

**Issue by tulebyCZ** [BEEmod/BEE2-items#2416]
all VMT files have been copied to version 27, but there is still the same error in the path to place the texture.

"include" "materials\\BEE2\\fizz	hedarkbomber\\texture.vmt"

need to fix it everywhere ... "include" "materials\\BEE2\\fizz\\thedarkbomber\\texture.vmt"

**Comment by LautaroL20** [comment]
This is probably related to: https://github.com/BEEmod/BEE2-items/issues/2264

Beemod had a bug where some exported VMT files gets corrupted once exported to the Portal 2 folder. However this is fixed for next release.

**Comment by ZombiePwner1** [comment]
This is fixed. pre release 28 is already out and the textures now show up properly.
