### ISSUE TITLE
Liquid cleansing field.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2419]
This is a fizzler that is combined with the paint gun field + the regular fizzler.

It blocks paint and deactivates your paint gun in aperture tag however it also blocks portal shots erases your portals and blocks cubes aswell. This fizzler would be essential in coop mode for aperture tag.

**Comment by Luke18033** [comment]
Doesn't the normal Paint Gun Activation Field already have the effects of a normal fizzler in co-op?

**Comment by TeamSpen210** [comment]
Yes, it does in both, but it doesn't fizzle cubes.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Oh well I'm just trying to come up with another custom fizzler idea.
