### ISSUE TITLE
PRL27 BUG: Light Bridge is a prop_dynamic when is put in upside arrow position

### ISSUE THREAD

**Issue by SpyyZ158** [BEEmod/BEE2-items#2420]
I don't know if it's just me or even anyone else , was using it in **overgrown style**

**Comment by SpyyZ158** [comment]
I mean that it's prop_dynamic

**Comment by TeamSpen210** [comment]
What is a "Lightning Bridge"? A light bridge? Try adding an input to it.

**Comment by SpyyZ158** [comment]
well .. when its in downside position , it's working properly , only when it's upside arrow or however to call it position , it's disabled and in hammer it's prop_dynamic
