### ISSUE TITLE
Laser bug

### ISSUE THREAD

**Issue by SpyyZ158** [BEEmod/BEE2-items#2421]
I have no clue if it is intended or not but my laser kills in few hits but player"character" doesn't die in one hit , same for death fizzler

**Comment by ZombiePwner1** [comment]
Can you be abit more specific?

**Comment by SpyyZ158** [comment]
My lasers doesn't kill in one hit either death fizzler

**Comment by ZombiePwner1** [comment]
@SpyyZ158 Do you mean like that laser fields and death fizzlers do not kill with 1 hit it takes multiple hits?

**Comment by SpyyZ158** [comment]
@ZombiePwner1 yes

**Comment by Luke18033** [comment]
Not a bug, the Forgiving Laserfields itemvar (which I think is on by default) does exactly this.

**Comment by SpyyZ158** [comment]
if it is default like that , how do I turn that off

**Comment by Luke18033** [comment]
It's in the Items section of the Style Properies window. I wouldn't recommend turning it off though - having it on doesn't affect the puzzle in any way, players are still killed if they try to force themselves through. It's mainly there to stop you from accidenally walking into a laserfield you didn't see and having to restart.

**Comment by SpyyZ158** [comment]
ah thanks @Luke18033
