### ISSUE TITLE
Mel's story soundtrack seems buggy + stutter happening PRL 27

### ISSUE THREAD

**Issue by SpyyZ158** [BEEmod/BEE2-items#2422]

**Comment by Luke18033** [comment]
Is this the music played on the Overgrown title screen? Because I had this issue once in a Hammer map with that track.

**Comment by SpyyZ158** [comment]
what do you mean by overgrown title screen , I used like multiple styles but music stopped and then I was lagging or if I say it correctly stuttering

**Comment by Luke18033** [comment]
This was caused by Mel's Story, which I removed in the latest version.
