### ISSUE TITLE
Add a stylevar to make underground catwalks more rusted.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2423]
![20171220111949_1](https://user-images.githubusercontent.com/18079316/34189912-d8b4f7ba-e578-11e7-91b1-dc814c27f523.jpg)

I've retextured mine with a rusted texture and it looks pretty good.

**Comment by LautaroL20** [comment]
Ok.

**Comment by ZombiePwner1** [comment]
@LautaroL20 What do you think of them?

**Comment by LautaroL20** [comment]
Too much of an overgrown style i think.

**Comment by ZombiePwner1** [comment]
@LautaroL20 It's not overgrown style you wheely I did reduce the amount of rust on them to make it less messy. Reason why I made them rusted is because the underground catwalks as they are now aren't really rusted just a plain brown texture.

**Comment by LautaroL20** [comment]
Too much of an overgrown feeling i meant.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Come on steam wheels.

**Comment by Luke18033** [comment]
There's a limit of 1024 models loaded at once, we don't want to waste it on something that doesn't really matter like this.
