### ISSUE TITLE
Rexaura cube deflectors having problems/changed dynamics after pr27

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#2425]
Since pr27 was released, the Rexaura cube deflectors have been having two problems:

1. You cannot remove a cube from the deflector after inserting it using the grab key. This has broken some tests that I've made based around this mechanic.
2. Putting the cube in from a certain angle makes it fly into the air instead of sitting in the deflector, without fizzling.

**Comment by Luke18033** [comment]
For 1, is the cube colorised or using a custom model? Because that's been known to cause issues with not being able to pick it up.

**Comment by snorepion** [comment]
Nope, it's a standard unmodded cube.

**Comment by CaliMari** [comment]
By the way with the cubes.In overgrown tests i put a Reflection Cube in a laser and i can't get them out normally.One time it was transformed in a Phantom cube.I could go through it the portal gun did not recognized any entity and it maked that sound when something is not usable.The reflected laser was still hurting the player.

**Comment by HugoBDesigner** [comment]
In Portal 1 style it works fine, but on first use it doesn't emit sounds or show its bottom particles
![cubedeflectorportal1](https://user-images.githubusercontent.com/6296061/38769942-768c7da6-3fe1-11e8-8938-71c532a1019e.gif)

**Comment by Jinx133** [comment]
This problem still happens to me today (while using versipn pr31), so I'll bump this.
On top of the issues that were reported, while the map is using the clean portal 2 style, the cube deflector makes a really bad noise when you put a cube on it.

**Comment by TheLoafLord** [comment]
Still does it for me. It's incredibly annoying because I've literally built my chamber around the style of Clean.
