### ISSUE TITLE
Overgrown rusted pipes are not being packed into the map

### ISSUE THREAD

**Issue by SpyyZ158** [BEEmod/BEE2-items#2429]
Without Bee2
![20171230161215_1](https://user-images.githubusercontent.com/16452792/34455330-26acb140-ed7d-11e7-82cf-9cfc29dc3bca.jpg)
With Bee2
![20171230161724_1](https://user-images.githubusercontent.com/16452792/34455331-38429e4c-ed7d-11e7-8cf9-9b772a442f3e.jpg)

**Comment by Luke18033** [comment]
The models aren't getting packed into the map.

**Comment by LautaroL20** [comment]
@SpyyZ158 - Can you tell us which corridor is it? So i can save some time at finding it for testing and then fixing the problem.

**Comment by SpyyZ158** [comment]
@LautaroL20 Entrance 5 SP , you can see right from changed title =)

**Comment by LautaroL20** [comment]
Fixed for next pre-release 29.

**Comment by LautaroL20** [comment]
This is already fixed in the current prl28 already...
