### ISSUE TITLE
Fields show a white strand on the sides

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#2430]
I have yet to determine if this is style-based or if it happens in every field/fizzler, but they'll show up a white texture (presumably missing texture) on their sides, even when deactivated:
![image](https://user-images.githubusercontent.com/6296061/34470840-92514384-ef21-11e7-83dc-068d40a4f7a6.png)

**Comment by TeamSpen210** [comment]
These are specially generated during export. Check `Portal 2/bee2/materials/bee2/fizz_sides/`, there should be a bunch of files.

**Comment by TeamSpen210** [comment]
Just realised why. They're probably being exported, then immediately deleted by the extract-resources step.

**Comment by HugoBDesigner** [comment]
Problem fixed, thanks TeamSpen!
