### ISSUE TITLE
Wheatley Monitor Is Very Ugly, Please make it look better!

### ISSUE THREAD

**Issue by RyanGamingXbox** [BEEmod/BEE2-items#2431]
I wanted to put Wheatley in since he has such a comforting voice and it's awesome, but the face looks bad, and my friends did not like my test for that reason. Please make it look better!

**Comment by LautaroL20** [comment]
I never used this item though. I should check out to see if its indeed ugly or not.

**Comment by TeamSpen210** [comment]
How is it ugly exactly? Could you be more specific?

**Comment by MisterSakamoto** [comment]
I think he means that it does not look like the singleplayer's scene through the screen. In singleplayer, Wheatley's face was huge on a black background. In BEE, he's smaller and has decorations in the back.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i don't like it very much either

**Comment by Cellolide** [comment]
I would also prefer the way MisterSakamoto described it.

**Comment by TeamSpen210** [comment]
It is intentional that I added the Central AI Chamber background around him. Maybe he should be larger/closer though.
