### ISSUE TITLE
Transparent area around a SP chamber lock

### ISSUE THREAD

**Issue by Cellolide** [BEEmod/BEE2-items#2434]
![20180105225043_1](https://user-images.githubusercontent.com/33907318/34630228-96f7efe4-f26b-11e7-9f10-f98aa55a3a8d.jpg)

**Comment by ZombiePwner1** [comment]
That's actually a nodraw issue.

**Comment by Hotten66** [comment]
Well I am not much experienced with that but I was using the chmber locks since this chamber and it was just a weird sight
