### ISSUE TITLE
Entrance Paint Gun Activation Field

### ISSUE THREAD

**Issue by Fazbear189** [BEEmod/BEE2-items#2439]
Add the option to have a Paint Gun Activation Field at the enterance of an Aperture Tag test chamber, just like in the original game.

**Comment by TeamSpen210** [comment]
Just put it in the chamber itself. This would require modifying every entry corridor, figuring out a way to link the activator item to said door, and a bunch of other changes that really aren't necessary.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the "invalid" label when closing the issue.
