### ISSUE TITLE
"Rexaura - Three" description typo

### ISSUE THREAD

**Issue by TheManOfGan** [BEEmod/BEE2-items#2442]
It says second instead of third.
![typo](https://user-images.githubusercontent.com/24685304/34903015-c9a3422e-f7dc-11e7-900f-c868383b1deb.PNG)

**Comment by CaliMari** [comment]
@LautaroL20 this is not a bug its a typo.

**Comment by LautaroL20** [comment]
It is a mistake that needs to be fixed.
