### ISSUE TITLE
Glass with a hole

### ISSUE THREAD

**Issue by Cellolide** [BEEmod/BEE2-items#2444]
![maxresdefault](https://user-images.githubusercontent.com/33907318/34908625-0b60d058-f893-11e7-8101-38ca1307e01d.jpg)

No clue if someone already asked for it, but if not it would be nice to have.

**Comment by LautaroL20** [comment]
This is implemented for next release.

**Comment by Cellolide** [comment]
You are better than I even expected :D

**Comment by Endermage77** [comment]
Wasn't this already a thing since BEE2.5 Alpha?

**Comment by awesomedoctorx3** [comment]
huh? why would you ever need to place a hole in grating?

**Comment by TeamSpen210** [comment]
It naturally follows from the item design.
