### ISSUE TITLE
Force deflection field fizzler frame does not generate properly when placed under an observation room.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2447]
![20180116150415_1](https://user-images.githubusercontent.com/18079316/34975936-15c02d30-facf-11e7-9601-288d08d8db52.jpg)

**Comment by LautaroL20** [comment]
That is really mysterious...

**Comment by TeamSpen210** [comment]
Do you actually have the correct instances? That shouldn't really be possible.

**Comment by ZombiePwner1** [comment]
Trust me I have the correct instances but I do not understand why I'm receiving this error.

**Comment by Luke18033** [comment]
And it appears fine when it's not below an observation room?

**Comment by Luke18033** [comment]
This should now be fixed.

**Comment by LautaroL20** [comment]
@Luke18033  - Do not forget to apply the corresponding label after closing an issue.
