### ISSUE TITLE
Luke please... Large glass panel packs as a mysterious blue error.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2448]
![20180122100140_1](https://user-images.githubusercontent.com/18079316/35202378-5b3e46c0-ff5d-11e7-8300-e9ba024f0c0b.jpg)

Luke pls.

**Comment by LautaroL20** [comment]
It is weird since the model should still be in vanilla P2, unless Luke edited the model in Blender for some reason.

**Comment by Luke18033** [comment]
I haven't done anything with that model...

**Comment by ZombiePwner1** [comment]
@Luke18033 Well luke it's your item so you need to find out why it packs as a mysterious blue error.

**Comment by Luke18033** [comment]
Oh, the LARGE Glass Panel, I thought you were talking about the regular glass panel (which I think also uses a modified model as of the latest release).
I know why this is happening. The single-block panel uses a rescaled model which doesn't cause texture conflicts, but it isn't actually set to pack.

**Comment by ZombiePwner1** [comment]
@Luke18033 lol you wheely I put your name in the title for a reason.

**Comment by ZombiePwner1** [comment]
@Luke18033 Also I think this only happens on clean style since the map in the screenshot was previously overgrown and the glass panels packed fine.

**Comment by LautaroL20** [comment]
> I haven't done anything with that model...  

Who rescaled the model then?

**Comment by Luke18033** [comment]
I thought he was talking about the regular Glass Panel, not the large one I made. (I actually didn't rescale it though, the model is reused from the BTS Large Faith Plate.)

**Comment by Luke18033** [comment]
Stuff like this is now packed automatically, right?

**Comment by LautaroL20** [comment]
Hope so. However, giving it a test to make sure its also covering your would not be bad. Mostly because Spencer mentioned that their new packing system only has an 80% of efficiency, so it could be failing on some items.

**Comment by TeamSpen210** [comment]
Yes, it'll be packed automatically.
