### ISSUE TITLE
Atlas mysteriously doesn't respawn in portal 1 style after being killed

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2453]
![20180123150811_1](https://user-images.githubusercontent.com/18079316/35262381-5cbc93ba-004f-11e8-9ca3-80af8dfd510d.jpg)

**Comment by ZombiePwner1** [comment]
Well it does respawn but he gets stuck outside the map with a black screen.

Here i've teleported atlas into the map via console commands and he is still stuck with a mysterious black screen.

![20180123151056_1](https://user-images.githubusercontent.com/18079316/35262440-aac0b654-004f-11e8-9385-0c549ea2d284.jpg)

**Comment by HTiago** [comment]
I am not sure, but a similar bug happens on BTS. One of players get stuck on entry dropper.

**Comment by LautaroL20** [comment]
I can confirm that this bug report really happens and its extremely annoying.

**Comment by Luke18033** [comment]
I think this is actually intentional, P-Body needs to leave the spawn room before Atlas can respawn (and vice-versa).

**Comment by CaliMari** [comment]
If it is intentional,i really do not like it :(

**Comment by Endermage77** [comment]
It's not intentional. This is what is known in dev circles as a "bug."

**Comment by Luke18033** [comment]
He was responding to my comment, where I said that it might be intentional because of the way the P1 coop spawn works. Only one player can be respawned at a time, if the other player tries to respawn before the first player has left the spawn room they'll be view-controlled into a black box.

**Comment by LautaroL20** [comment]
The problem here is that independently from that P-Body needs to leave the spawn room before Atlas can respawn, the character gets permanently stuck in a mysterious black area and can´t be controlled.

**Comment by TeamSpen210** [comment]
That part of it is intentional, if no player is inside and it still breaks that's a bug.

**Comment by TeamSpen210** [comment]
This seems to work fine right now.
