### ISSUE TITLE
BTS Standing Fizzler X1 Editor Model is invisible in a "Mysterious Way"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2456]
Please, insert the x files theme song here: 
![Half Life 3 Confirmed](https://user-images.githubusercontent.com/12244376/35289592-862a8a9e-0046-11e8-9a82-729b627bd9d2.jpg)

**Comment by HTiago** [comment]
Oh boi, the mystery continues

**Comment by LautaroL20** [comment]
Well, it is my bug report so if i can call it wahetever as long as the title also descrives the bug.

**Comment by LautaroL20** [comment]
I am sure this model worked well... most likely the upload from PRL28 corrupted some files and it affected mine, well ive recompiled the model now.
