### ISSUE TITLE
The Working Coop Grates does not allow a white wall behind it to be portaled at all

### ISSUE THREAD

**Issue by cartman1337** [BEEmod/BEE2-items#2463]
First off, a problem that applies to both Wall/Reclined Grates and Working Coop Grates; they are not two-way. I.e. a light bridge, funnel, etc. pointed directly at one of these grates just in front of a white wall, will not let the bridge/funnel/etc through a portal on the white wall behind it, but a bridge/funnel/etc coming from a different source, into a portal behind the grate, allows the bridge/funnel/etc through. They need to be two-way. I've tried with "start reversed", but that didn't seem to do anything.
![Stuff pointed directly at it not getting through](https://i.imgur.com/7lCCK9G.jpg)
![Stuff portaled through gets through](https://i.imgur.com/3b564FJ.jpg)

The images above are from Overgrown style, but it's the same in Clean too. Not tested in other styles.

Second, a problem with Working Coop Grates; a grate in "cube" style does not allow a white wall behind it to be portaled at all; it's impossible to get a portal through.

Third, and now it's getting really weird; Wall/Reclined Grates seems to be prone to causing map bleed, however it's not 100%. An hour ago when I was testing, I didn't get any bleed. Then I introduced a cube into the map, and suddenly it bled. However, even after removing the cube, exiting the game and even applying different styles (going from Overgrown to Clean), bleed still occurs. Setting it to "Weighted" in the editor seems to cause bleed, if there's also goo, almost no matter what, while "Cube" does it most of the time and "Sphere" almost never. There's no doubt, however, that the Wall/Reclined Grate is the main culprit, as removing it immediately also removes the bleed. I'm getting bleed both in Overgrown and Clean, not tested in other styles.

"Weighted" grate causing bleed in Clean:
![Weighted grate in Clean](https://i.imgur.com/wB8Ntut.jpg)

"Cube" grate (top left corner) causing bleed in Overgrown:
![Cube grate in Overgrown](https://i.imgur.com/gLZOU1y.jpg)

**Comment by Luke18033** [comment]
It's called a leak, not a bleed, and I think I know what's causing it. Try moving the grate away from any other surfaces, see if that fixes it.

**Comment by cartman1337** [comment]
Leak, bleed; something's flowing where it shouldn't, whatever you call it. Anyway, moving the grate away from any types of corners does indeed make the leak end. Still, whatever you think is causing it when it's next to a wall corner, floor and/or roof should be addressed, otherwise the uses of these grates are pretty limited, furthered by the other issue I mentioned that it only lets funnels and stuff through from behind, which logically doesn't even make sense; if there are holes it in, particles that are either small or floaty enough to go through, would go through either way.

**Comment by LautaroL20** [comment]
The item´s description is pretty clear about something that you mentioned, it seems you did not read it entirely: 
![description](https://user-images.githubusercontent.com/12244376/35478271-85fc85a8-03b7-11e8-904c-56761b1ce665.png)

_________________________________________________________________________________

Respect to the leaks, they must be causing by something else, see how i applied my item everywhere in corner of goo and it doesnt leak: 
![Image](https://user-images.githubusercontent.com/12244376/35478304-195d47c4-03b8-11e8-9705-f0ba9e27cd71.jpg)

______________________________________________________________________________________________________

Respect to that Working Coop Grates does not allow portals over withe surfaces, thats a bug and i will take care of it, it will be fixed for next release for sure.

**Comment by cartman1337** [comment]
Yes, I've read the item description many times, and again now, and I have no idea which part you think is "pretty clear" about "something that I mentioned". It does say, however, that if it's facing a white wall (and they all were, when I tested) then funnels, light bridges, lasers, fizzlers and gels can go through without problems, but it does not say that they can only go through without problems in ONE direction, and as such it is FAR from understood...

As to leaks; there's nothing else ON the map, except a funnel, a light bridge, a button and some goo. Introducing one of those grates introduces a leak, taking it away makes the leak go away. You do the math. It may be that only some positions causes the leak, but it is most certainly connected to that item.

**Comment by TeamSpen210** [comment]
@LautaroL20, check the orientations of your frame models, make sure they aren't in the edge of the item voxel. If it ends up where the edges of two diagonal voxels meet, it'll leak.

**Comment by LautaroL20** [comment]
I have fixed this for next release. This taked me so long to fix since i had to move brush per brush in each instance for all the styled versions, and it is something pretty much tedious.
