### ISSUE TITLE
PRL28: Connected Angled Panels compiles into undeployed, nonworking panels in 1980s style

### ISSUE THREAD

**Issue by cartman1337** [BEEmod/BEE2-items#2465]
Noticed this while testing a chamber in 1980s style after PRL28.

Simple editor test; 4 angled panels, 2 connected to a pedestal button, 2 unconnected:
![Angled panels editor](https://i.imgur.com/MfSbERO.jpg)

When compiled, the 2 connected panels are simply gone, while the 2 unconnected ones are still there:
![Angled panels gone in compiled map](https://i.imgur.com/fGhckS7.jpg)

Tested across all styles, seems to be limited to 1980s style.

**Comment by TeamSpen210** [comment]
Does pressing the button do anything?

**Comment by cartman1337** [comment]
Not really, except lighting up the antlines. To effectively test this I changed the configuration of that test room to start the panes undeployed, and have the button deploy them. In other words it would start with a hole and a flat panel, and pressing the button should make the hole covered (rise to 90 degrees), and the flat panel rise into a 45 degree configuration.
![Editor](https://i.imgur.com/NRSgutu.jpg)

Here's what happens when pressing the button in the compiled version:
![From behind](https://i.imgur.com/SUsfrKo.jpg)
![From the front](https://i.imgur.com/Jy4nTjI.jpg)
The hole is still a hole, and the floor is still flat.

Like I said in the title, the panels simply disappear as soon as they are connected to an input, and while the input still apparently "feels" connected to something, and correctly applies antlines/signage, an item that isn't there, can't really do anything either.

**Comment by cartman1337** [comment]
A couple more pictures; I placed a portal on the one that's supposed to rise to a 45 degree position when activated. We all know that portals on flip panels disappear when the position changes. When clicking the button, the portal stays in place.
![Before](https://i.imgur.com/Q4mCiG6.jpg)
![After](https://i.imgur.com/BMbSY5F.jpg)

**Comment by cartman1337** [comment]
Just came to think about that I could be wrong about the bug, that the item doesn't disappear, simply that it is converted to an undeployed, nonworking entity, even if told to start deployed and connected to an input. And that seems to be the case. Going into non-clip mode, I can clearly see that the mechanism for the one on the floor, that should rise to 45 degrees when activated, is there, and going further out it is also clear the the mechanism box for the other one that doesn't work is also there, just like it is for the one without a connection.
![Mechanism is there](https://i.imgur.com/SEfk2Zb.jpg)
![Mechanism boxes are there](https://i.imgur.com/5rxuHQm.jpg)
![More boxes](https://i.imgur.com/jeH9Quk.jpg)

So I stand corrected; they don't disappear, but when compiled any panel connected to any type of input gets converted to an undeployed, nonworking panel, regardless of programmed configuration in the editor.
