### ISSUE TITLE
better piston background 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2468]
this 
![capture 1](https://user-images.githubusercontent.com/31172185/35486030-f67c94de-041c-11e8-8ac8-a3bc70ed6006.PNG)
looks better than this [note fullbright is on so you can see the back]
![capture 2](https://user-images.githubusercontent.com/31172185/35486038-0b50a42c-041d-11e8-8419-52e61edcff2e.PNG)

**Comment by TeamSpen210** [comment]
We can't do this.
