### ISSUE TITLE
Add placement hints to Glass Hole description

### ISSUE THREAD

**Issue by cartman1337** [BEEmod/BEE2-items#2469]
The description for Small Glass Hole reads

> Allows cutting circular holes into Glass or Grating.
> Place on top of an existing glass/grating surface. (Place onto wall to rotate, then drag onto the glass.) For large holes, glass must also be present above, below, left and right. Small holes allow portal shots, bullets, lasers and paint splatter. Large holes allow anything through. This also works with grating, although it is less useful.

However, there's no way in the editor to actually drag the hole onto an existing glass/grating surface. The only way I've found that works so far, is to first place the hole on a wall, then select the wall piece with the hole and remove it (leaves the hole hanging red and "angry" in the sky), then place a glass/grating onto that square, facing the hole. That works. However, dragging the hole around in the editor, it will only stick to normal walls, floors and roofs, there's no way of dragging it onto a glass/grating.

Either the description should be updated, to explain this roundabout way of making it work, or - preferably - the editor model should be fixed so that it is actually possible to drag it onto an existing glass/grating surface, like the description says it can.

**Comment by TeamSpen210** [comment]
You can drag it onto surfaces, but it won't rotate. So you need it to be in the correct orientation beforehand, or do the voxel swap. I can't change the editor behaviour, we're lucky that we can make an item that attaches like this.

**Comment by cartman1337** [comment]
What do you mean by "correct orientation"? It is a hole in the middle of a square, I can't see any orientations. And dragging it around, it only sticks to the main surfaces, nothing sticking up/out/down from them. As such, I tried many times to place the hole on the same square as the glass, making the square look like a hole with a glass sticking out next to it, hoping it would "infest" it that way, but that didn't work.

**Comment by TeamSpen210** [comment]
It has an orientation, the side of the block it's attached to. It's annoying that it 'prefers' the walls if there's one in the same block as the glass.

**Comment by cartman1337** [comment]
Maybe something's different in your editor for this item.

Here's what the hole looks like in my editor:
![Hole](https://i.imgur.com/kT7OP70.jpg)
It's selected, so if there were an orientation adjuster attached to it, it should show, but I sure can't see any.

Dragging it to a window allows me to place it next to the windows, like so, but that's about it:
![Hole by a window](https://i.imgur.com/wwbIWZA.jpg)

**Comment by TeamSpen210** [comment]
No, the orientation. Here it's oriented vertically to the upper-left, and then downward. Place it back on the wall, widen the glass, then drag it to a middle block which does not have a wall neighbouring it.

**Comment by cartman1337** [comment]
That comment is in English, I understand the words, but I have absolutely no idea what you meant by any of that...

**Comment by TeamSpen210** [comment]
On the left are the 6 orientations the item has, and on the right shows where to drag to correctly place it on the glass. 
![capture](https://user-images.githubusercontent.com/8453732/35490007-4487bbfa-0494-11e8-9896-385489652bbb.png)
The square you drag to must not be adjacent to a wall, or it'll snap to that.

**Comment by cartman1337** [comment]
OK, I see now. So you can only get holes above ground level that way. To get a hole on ground level, which is what I intended, I'll have to use the more cumbersome way of first making a block, put the hole on that block, then remove the block, then put the glass there.

**Comment by cartman1337** [comment]
Since this Enhancement request is already open, I'd like to suggest: how about adding other hole form options to this item? Right now you can only get a round hole, but it could be fun with a hole that is square, and exactly the size to put a cube in too.

**Comment by TeamSpen210** [comment]
There's already a second type - a larger hole a bit bigger than a 1x1 block.

**Comment by cartman1337** [comment]
Yes I know, but I feel that one's too large.
