### ISSUE TITLE
Portal stories VR music

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2472]
Add please Portal stories VR music
![header](https://user-images.githubusercontent.com/35931028/35583382-700a1356-05fa-11e8-92d7-a6e45e9655d3.jpg)

**Comment by xGARDYx** [comment]
i dont know how it the song sound,but i want it too cuz u want it ;3

**Comment by SCIENTIST2004** [comment]
https://www.youtube.com/watch?v=HZHNK0RzvCo

**Comment by SCIENTIST2004** [comment]
^
|
|
|
portal stories vr music

**Comment by Luke18033** [comment]
Duplicate of #1237.
