### ISSUE TITLE
1x2 thick slope that stands on its bottom face

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2473]
Currently, the thick part of the 1x2 slope pieces rests on its back face, which means it must be placed on a wall perpendicular to the tip of the slope. Which is nice, except you can't lay 1x2 slopes on flat ground with such a placement. Having a variant that rests on its bottom face would help for placing 1x2 slopes flush onto a surface.

**Comment by Konclan** [comment]
Moving to #3885
