### ISSUE TITLE
New items and style: items and style from "the trap 2 mindlock"

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2478]
http://store.steampowered.com/app/638800/The_Trap_2_Mindlock_beta/

**Comment by SCIENTIST2004** [comment]
^
|

**Comment by TeamSpen210** [comment]
How is this related at all to Portal?

**Comment by ZombiePwner1** [comment]
@SCIENTIST2004 All items must be related to portal if not then invalid.

**Comment by SCIENTIST2004** [comment]
(((
