### ISSUE TITLE
PRL28: BTS exit corridors 3 and 4 slams shut

### ISSUE THREAD

**Issue by cartman1337** [BEEmod/BEE2-items#2481]
BTS exit corridors 3 and 4 accept inputs, but when they receive the required inputs, they open quickly, then slams shut just as quick (all so quick that it's impossible to cross, even if you're standing right in front of it), and, depending on input, might not be possible to open again (and even if you manage, the same happens again).

Depending on input, it also acts differently as to the status light. Here the exit door has been opened by a Trigger Once event; the status light stays green, saying that it has gotten the required input, but it is clearly closed all the same:
![Opened by Trigger Once](https://i.imgur.com/FCcKwwM.jpg)

Here it has been opened by a pedestal button; the pedestal button displays a green light, saying it has passed on what it was set to do, but the exit (which still opened and slammed shut when the input was received) has gone back to a red status light, as if it's waiting for further input:
![Opened by Pedestal Button](https://i.imgur.com/CCPERdn.jpg)
![Editor setting for Pedestal Button](https://i.imgur.com/a1EEF6Q.jpg)

Exit corridors 1 and 2 work correctly. In those, the door opens slowly, and stays open.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
