### ISSUE TITLE
Suggestion for underground faith plates.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2482]
![20180203155808_1](https://user-images.githubusercontent.com/18079316/35765273-28446bda-08fb-11e8-94bf-bf3c2263559d.jpg)

While playing on some community maps I saw this and thought it would be a good suggestion for beemod.

**Comment by TeamSpen210** [comment]
Have you tried the existing mechanical plates? (Item tab).
