### ISSUE TITLE
Portal 1 2-block and 3-block Standing Fizzlers only generate particles at the bottom

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2484]
![20180203161428_1](https://user-images.githubusercontent.com/19228201/35773117-9da8c374-08fd-11e8-8efa-baef29f9bf00.jpg)

**Comment by LautaroL20** [comment]
Now fixed. Looks like the only thing i forgot when i were doing the P1 variants, was to copying the particle systems for each level.
