### ISSUE TITLE
Suggestion: Make light strips one pallete item

### ISSUE THREAD

**Issue by Cellolide** [BEEmod/BEE2-items#2485]
Like the "Square Neutral Light" all three variants of the light strip could be merged into one single pallete element. In the editor you can choose the type with the "Cube type" property like using the "Square Neutral Light" or many other elements.

**Luke18033 said:** [...] couldn't we use Cube Type since that works with any item class? We'd just need to figure out what the fourth and fifth variants would be.

**Comment by HugoBDesigner** [comment]
Pretty sure it's never been done because it'd mess with maps that already contained default light strips

**Comment by Endermage77** [comment]
For some reason, TSpen refuses to do this because it breaks the light's collision.
I'm not sure why it's a serious enough issue to warrant refusal on the topic, but that is where he stands.

**Comment by LautaroL20** [comment]
If @Luke18033 would ever see this issue, he would probably get annoying of how many times this has been suggested, and i understand him.

**Comment by TeamSpen210** [comment]
Indeed. We'd want to 'shadow' the old versions, so they still work but you can't place new ones of those. One option would be Antline Routers, the other I'm not sure about. Maybe it would invert the tiles in that spot? (That requires `tiling` though.)

**Comment by Endermage77** [comment]
The fourth and fifth variants could be colored lights of the user's choice, selected through the ICP.

**Comment by HTiago** [comment]
![687474703a2f2f6d656469612e6d6f6464622e636f6d2f696d616765732f61727469636c65732f312f3131302f3130393534352f6175746f2f313335343937393338362e6a7067](https://user-images.githubusercontent.com/29435727/36055354-4593e48c-0dd2-11e8-851f-36d592f03abb.jpg)
Found here #1610

**Comment by Blacksilver42** [comment]
Could make a *seperate item* which is the three combined; leaving the current ones as-is.
