### ISSUE TITLE
PRL28: The system can't find vbsp.exe and I don't know why it's gone and how to get it back

### ISSUE THREAD

**Issue by Querez** [BEEmod/BEE2-items#2488]
When I add BEEmod elements to my test, it first succesfully compiles, but shows the version that was before the BEEmod elements. I then go out to the editor, and then try to compile again, and then it instantly fails. This is the whole developer console:

NET_GetBindAddresses found 192.168.1.13: 'Broadcom NetXtreme Gigabit Ethernet'
Opened Steam Socket NS_SERVER ( socket 1472 )
Opened Steam Socket NS_CLIENT ( socket 1468 )
Network: IP 192.168.1.13, mode MP, dedicated No, ports 27015 SV / 27005 CL
Parent cvar in client.dll not allowed (movement_anim_playback_minrate)
Game supporting (2) split screen players
maxplayers set to 1
Steam config directory: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2.exe\platform\config
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/change_this
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/gesture_smallwave
Unknown command "cl_thirdperson"
Unknown command "joy_no_accel_scale"
Didn't find Active Steam Controller to Load Menu Controls
Unknown command "cl_thirdperson"
Unable to initialize DirectSoundCapture. You won't be able to speak to other players.C_GameInstructor::ReadSaveData failed to read GI.lesson.Swap_Split_Screen_Control
[PORTAL2 PUZZLEMAKER]  Loaded puzzle puzzles\76561198117683129\1517685544.p2c
Unknown command "cl_puzzlemaker_activate"
CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.1.13, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 1480 )
Opened Steam Socket NS_CLIENT ( socket 1468 )
Network: IP 192.168.1.13, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\1517685544/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\1517685544/c-1904_2096_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1517685544/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\1517685544/c-2032_-2032_-31'
Failed, using default cubemap 'engine/defaultcubemap'
r_rootlod is temporarily unsupported: bugbait#70052r_rootlod is temporarily unsupported: bugbait#70052r_rootlod is temporarily unsupported: bugbait#70052r_rootlod is temporarily unsupported: bugbait#70052r_rootlod is temporarily unsupported: bugbait#70052Host_NewGame on map puzzlemaker\76561198117683129\1517685544
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
PrecacheScriptSound 'music.puzzlemaker\76561198117683129\1517685544_tbout' failed, no such sound script entry
prop_monster_box at (1600.000, 1088.000, 1178.000) has no model name!
prop_weighted_cube at (1600.000, 1088.000, 1180.000) has no model name!
prop_monster_box at (1600.000, 64.000, 922.000) has no model name!
prop_weighted_cube at (1600.000, 64.000, 924.000) has no model name!
prop_monster_box at (2112.000, 1728.000, 922.000) has no model name!
prop_weighted_cube at (2112.000, 1728.000, 924.000) has no model name!
prop_monster_box at (64.000, 1984.000, 1306.000) has no model name!
prop_weighted_cube at (64.000, 1984.000, 1308.000) has no model name!
Commentary: Could not find commentary data file 'maps/puzzlemaker\76561198117683129\1517685544_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198117683129\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
Connection to Steam servers successful.
   VAC secure mode is activated.
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (19,20,10)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 265 (ms)
Could not execute the command:
   "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
Windows gave the error message:
   "Systemet finner ikke angitt fil."     <-- That's my language for "The system can't find the designated file"

VBSP failed.

Failed to start process ("C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf") with working dir (C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/)

Querez unpaused the game
Unknown command "cl_puzzlemaker_deactivate"
Didn't find Active Steam Controller to Load Menu Controls
Dropped Querez from server (Server shutting down)
failed processing
 Dumping messages for channel CLIENT(loopback) 0x0AE319B0
Header bits 96, flags == 1
1 messages
0 -----------------------
svc_TempEntities: type( 27 ) group ( 6 ) size ( 84 bytes ), startbit 6 end bit 305
   svc_TempEntities: number 0, bytes 35
RAW(svc_TempEntities) start
svc_TempEntities  >>  ��lS....�.�.0�.......... ecee6c53 00000000 b019e30a 30a58f08 01000000 12010000   
svc_TempEntities  >>  .....�{.�...~...�7...... 00000000 00877b03 f0030000 7e000000 b3370000 0f000000   
svc_TempEntities  >>  �.�.�.�...�.........���� 86058303 fe058303 80058303 00000000 00000000 ffffffff   
svc_TempEntities  >>  ............             00000000 00010000 00000000                              
RAW(svc_TempEntities) end
Raw
PKT  >>  g...U....��.....@".��m.. 67030000 550b0000 01e3fb00 881f800d 402280b3 b76d0b00   
PKT  >>  ..........�.........�.-. 00020000 08100002 0000fe04 03121080 00000000 83902d01   
PKT  >>  . .��..D.go�....... .... 102000fc ff1b8044 00676fdb 16000004 00001020 00040000   
PKT  >>  �..$ ......�_. @.��7.�.� fc090624 20000100 000002e0 5f022040 00f8ff37 008900ce   
PKT  >>  ޶-..... @....�..H@..... deb62d00 00080000 20400008 0000f813 0c484000 02000000   
PKT  >>  .@�.@..��gI.#W6G.&G.`    0440db04 408000f0 ff674910 23573647 17264707 60         
Didn't find Active Steam Controller to Load Menu Controls

**Comment by LautaroL20** [comment]
Try doing the following and please, after following each step let me know if it worked:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by Querez** [comment]
I've already tried this after looking through other issues, and it doesn't work. And yes I'm on Windows, and yes, the Item's Packages and the Application are from the same pre-release. Any other tips?

**Comment by LautaroL20** [comment]
Well, if all the previous did not help, then ll start to make some conclusions first. Does this also happens with an empty puzzle too? Maybe your map is fully of items. If this is not the case then, start a new map, open the developer console and type in "developer 2" (this command gives more presise info), then type "clear" and build the puzzle. Once it fails paste the updated log, here.

**Comment by TeamSpen210** [comment]
```
Could not execute the command:
"C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe"
```
This suggests the compilers are missing. Is this file present, and if so does it have a BEE2 icon?

**Comment by Querez** [comment]
Well, it shouldn't be missing, but I'll check anyway, when I get the time.

**Comment by Querez** [comment]
I checked, and there is no vbsp.exe. There is a vbsp_original.exe but I don't think that's it. Should I copy the vbsp.exe with a BEE2 icon over to the bin folder?

**Comment by mm2wood** [comment]
You could possibly have an antivirus messing up things, I had a similar issue where the vbsp and another file were detained to the Avast "virus chest".

**Comment by Querez** [comment]
Nope, I just scanned the computer with AVG and it says no threats found.

**Comment by TeamSpen210** [comment]
The other way around, sometimes antivirus thinks BEE stuff is one (even 
though it's not, it can do kinda similar things). Check AVG's history. 
This would explain why the file's missing.

**Comment by Querez** [comment]
I'm not sure how to check the history. I've tried searching on Google, but it didn't work out. I have no time left today, since I'm going to bed (night where I live). So I won't be active the next 7 hours

**Comment by Querez** [comment]
Bump. Why has no one commented back? I still have the issue and have no idea how to fix it.

**Comment by TeamSpen210** [comment]
The error is saying exactly that VBSP.exe is missing, and Windows can't find it.

**Comment by Querez** [comment]
Yes I know that now, the problem is how do I get it? And why is it even gone in the first place? Any ideas?

**Comment by TeamSpen210** [comment]
Exporting will copy it, verify your game cache first. As I said before, it's probably your antivirus.

**Comment by Querez** [comment]
Exporting what? The .zip file? And I've verified the game cache files alot but it always goes to one problem: Portal 2 refuses to start unless I restart the pc. But I'll try verifying them again juat in case. Will let you know what happened.

**Comment by TeamSpen210** [comment]
Open up AVG, and whitelist the `bin/` folder. It's going to be the one deleting it. For 'export', I mean the button in BEE2 which copies stuff to the game.

**Comment by Querez** [comment]
Oh yeah sorry I misunderstood you. When you said "export will copy it" I thought you meant exporting something to copy the vbsp.exe because I asked how to get it. Well now I know what you meant, and I will try later today. Thanks.

**Comment by Nikita74RU** [comment]
Antivirus. That was one of reasons why my chambers won't work.

**Comment by Nikita74RU** [comment]
P.S Just add the VBSP.exe and VRAD.exe in exceptions.
