### ISSUE TITLE
Friendly laser fields still kill the player with one hit if the player jumps in the middle from above or under.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2490]
https://gyazo.com/4149e953ac6d4a20c7a1acef4e181373

**Comment by TeamSpen210** [comment]
That's intentional. It's not a "friendly" option. It just makes it non-deadly if you try casually walking into it. Vertically it'll still kill. Regardless it's still deadly, and will kill you if you move faster.
