### ISSUE TITLE
BTS buttons cause the player to get stuck when jumping on their sides.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#2491]
![20180209183001_1](https://user-images.githubusercontent.com/18079316/36024035-6b740d66-0dc9-11e8-83f1-e9a4f91c511a.jpg)

![20180209182943_1](https://user-images.githubusercontent.com/18079316/36024083-8fae32ec-0dc9-11e8-816e-8875be98cc7d.jpg)

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
