### ISSUE TITLE
BTS non-portable cube cleaner's textures do not fit together.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#2492]
![20180209183036_1](https://user-images.githubusercontent.com/18079316/36024116-aaa05e9a-0dc9-11e8-8751-799dc49c9ad7.jpg)

**Comment by xGARDYx** [comment]
!Off-Topic! Are you using custom textures for the yellow back panels?They look really smooth ._.

**Comment by ZombiePwner1** [comment]
@xGARDYx I'm using custom made beta versions since this is how they looked during the beta.

**Comment by Luke18033** [comment]
BTS style is being removed, this should be fixed now anyway.
