### ISSUE TITLE
New item variant: human button (reacts on humans only)

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2493]
![portal_button_bendy](https://user-images.githubusercontent.com/35931028/36042325-2476efae-0dd4-11e8-81ed-fbc3dab74554.png)

**Comment by Luke18033** [comment]
Duplicate of #457

**Comment by SCIENTIST2004** [comment]
oh...

**Comment by xGARDYx** [comment]
tho this icon looks better than the one on that issue
