### ISSUE TITLE
Missing Model for Portal Gun On/Off Button

### ISSUE THREAD

**Issue by HankyMueller** [BEEmod/BEE2-items#2496]
I've been getting many comments on my recent map mentioning that the portal gun on/off button's model is replaced with the "ERROR" model.
![image](https://user-images.githubusercontent.com/28546169/36083081-cfd5c720-0f74-11e8-8ec2-69cc9ae91b83.png)

It seems to only occur for non-beemod users as well. Thought it would be good to bring this up here so it could be addressed.

**Comment by TeamSpen210** [comment]
It would help if I told the item to actually pack things.

**Comment by LautaroL20** [comment]
One day i should place all existing beemod items in a map, and do it per each style then publish it, play them thru a clean install of Portal 2 to find out all mysterious blue errors....

**Comment by TeamSpen210** [comment]
One day I should finish my packing code that automatically finds 99% of the packed content, so we can get rid of the commands.

**Comment by LautaroL20** [comment]
That sounds good.
