### ISSUE TITLE
Cubes doesn't prevent door from closing (BTS)

### ISSUE THREAD

**Issue by helderbarboza** [BEEmod/BEE2-items#2498]
![image](https://user-images.githubusercontent.com/29435727/36118034-11bd2e56-1012-11e8-9048-e2146241ca4b.png)
Tested blocking it with player and worked as well.

**Comment by LautaroL20** [comment]
I doubt that this is fixeable.

**Comment by TeamSpen210** [comment]
The door should have triggers to prevent this, not sure why I didn't add those.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
