### ISSUE TITLE
Franken Cube too big for portal 1 Dropper.

### ISSUE THREAD

**Issue by benjaminpants** [BEEmod/BEE2-items#2499]
I am using the portal 1 theme using the Franken cube, but the Franken cube is too big! So it gets stuck.
![image](https://user-images.githubusercontent.com/27522994/36121241-6b1a4ef6-0ffa-11e8-9490-7c4a2d63d60a.png)
I would really want a solution! Because this makes it so you can't use those cute little Franken cubes.

**Comment by ZombiePwner1** [comment]
@benjaminpants The main problem is with the model we can't edit the model since it will break the animations so we will need to find a work around for this without editing the model.

**Comment by Endermage77** [comment]
Slightly bigger vent, maybe?

**Comment by benjaminpants** [comment]
@ZombiePwner1 Wait, my hammer skills are a bit rusty, but aren't each dropper type a different instance?
If so, create a copy of the models and remove the collisions. And use invisible brushes to manually make the collision so the franken cube can squeeze in.

**Comment by TeamSpen210** [comment]
The problem here is actually that for some reason it's popped into the extended pose, before exiting the dropper.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 I think the game is specifically coded to make them start like that and if that's the case we can't fix it.

**Comment by TeamSpen210** [comment]
Um, no it doesn't.

**Comment by benjaminpants** [comment]
@ZombiePwner1 um, I think that you can put the Franken turrets into their cube form. Im not sure if this resets if you pick it up

**Comment by Nikita74RU** [comment]
Remove the bug and add fixed label, works fine now.

**Comment by Nikita74RU** [comment]
Once my WCC was stuck in Overgrown dropper, lol

**Comment by Luke18033** [comment]
Now fixed.
