### ISSUE TITLE
Konclan´s ceilling observation displays a "mysterious blue error" inside it

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2500]
![Half-Life 3 Unconfirmed](https://user-images.githubusercontent.com/12244376/36173660-804b1f28-10e8-11e8-9073-abc0e6ae5964.jpg)

**Comment by Luke18033** [comment]
I think this is the same issue as #2429, the rusted pipe models aren't being packed.

**Comment by LautaroL20** [comment]
Not exactly, since the required commands to tell the compiler to pack the rusted pipes are located in different configuration files. And in the other hand, that issue is probably using a different wallpipe variant than the one used for the Konclan´s observation.

**Comment by LautaroL20** [comment]
Fixed for next pre-release.
