### ISSUE TITLE
Overgrown SP Entry Corridor N°1 displays a "mysterious blue error" inside it

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2501]
![Half-Life 3 Unconfirmed](https://user-images.githubusercontent.com/12244376/36173878-391c792a-10e9-11e8-9223-8407b9a73115.jpg)

**Comment by ZombiePwner1** [comment]
That's the vactube with glass on the insides clearly it's not packing.

**Comment by LautaroL20** [comment]
Indeed, i will have to add aditional commands inside the config and info file to make this thing to get packed......

**Comment by LautaroL20** [comment]
Fixed for next pre-release 29.
