### ISSUE TITLE
Wall/Floor Droppers - NEW ITEM IDEA

### ISSUE THREAD

**Issue by benjaminpants** [BEEmod/BEE2-items#2502]
I have a idea for a element you can implement.
Its a dropper you put on the floor, and when you press the button.
It opens then creates a cube flings the cube up out of the dropper and then when it
hits a trigger that is slightly above the end of the dropper it will close.
I can make a rough hammer version if you want.

**Comment by SCIENTIST2004** [comment]
good idea!

**Comment by benjaminpants** [comment]
They added "Enhancement", which I disagree with. I think it should be a different object. Because just putting it on the wall is not going to work.

**Comment by TeamSpen210** [comment]
Actually, we can make the dropper placeable on walls, and convert it to a different item.

**Comment by benjaminpants** [comment]
Oh cool. Hope to see this in the next update

**Comment by LautaroL20** [comment]
Well, i have added the "Enhancement" label for a reason, since we can use the actual vanilla dropper to do this, the same way as the Small Observation Room which also works on floor and ceilling too. We do not need to have tons of items of the same type in the Bee´s Palette just for a variant if we can re-use original one.

**Comment by Querez** [comment]
I'm guessing you got the idea from the Portal 2 mod "Thinking with Time Machine"? The "droppers" there are on the floor and extends out, builds the cube, and flings it away before retracting. Very similar, or basically identical to what you suggested. Yes though, it would be a nice feature.

**Comment by HeimlichLaboratories** [comment]
I suggest that for Wall droppers there could be a Start Reversed or Stylevar that chooses if the dropper simply drops the cube or if it flings it

**Comment by Konclan** [comment]
#1305
