### ISSUE TITLE
Mysterious behaviour of the 'Sendificator'

### ISSUE THREAD

**Issue by Cellolide** [BEEmod/BEE2-items#2503]
I have really no clue why the following happens, especially because it already worked. But no matter what I am trying to do (adding timer, switching blue with orange portals, add pedestal button for activation)... everything leads to the following result.

1. Cube is stored on the Sendificator:
![20180216215126_1](https://user-images.githubusercontent.com/33907318/36328754-b2330e10-1363-11e8-9bf2-861221cf5f87.jpg)

2. The laser receiver activates the Sendificator:
![20180216215132_1](https://user-images.githubusercontent.com/33907318/36328755-b36c8176-1363-11e8-9580-1de1e9ad74ca.jpg)

3. This laser is the laser that teleports (connected with white/black antline):
![20180216215142_1](https://user-images.githubusercontent.com/33907318/36328761-b8b1fde6-1363-11e8-86a3-4574a42da59f.jpg)

4. However, after the laser hits the laser receiver (also where the cube should get teleported to) the cube drops out of the first portal....: WHY?
![20180216215150_1](https://user-images.githubusercontent.com/33907318/36328763-ba4c57f0-1363-11e8-9192-5757ff9504c7.jpg)

**Comment by TeamSpen210** [comment]
I must have messed up the logic somewhere, so it isn't recognizing the portals. I think I know why though. Make a room somewhere, and place an Absolute Fizzler in it. Does that fix the problem?

**Comment by Cellolide** [comment]
So you mean just an empty room with a standalone Absolute Fizzler without any connections?

**Comment by TeamSpen210** [comment]
Yeah, I think it's not including the logic, and that item also requires it so it should force it to be included.

**Comment by Cellolide** [comment]
Oh alright, I am trying that.

**Comment by Cellolide** [comment]
Yeah that actually worked! Thank you for the temporarily solution :)

**Comment by toncica2** [comment]
Same issue as #2462. I used the sendificator script from prl27 as a workaround.
