### ISSUE TITLE
No Clean Style Package

### ISSUE THREAD

**Issue by PieCreeper13** [BEEmod/BEE2-items#2504]
No Clean Style Package! This is required for some essential resources and objects.
Get the packages from "http://github.com/BEEmod/BEE2-items" and place them in "C:\Program Files(x86)\Steam\BEE2\BEE2.4_pr28_win\packages\".

**Comment by TeamSpen210** [comment]
Do what it says. You haven't installed the actual items.

**Comment by LautaroL20** [comment]
@PieCreeper13 - Get the item packages, otherwise beemod will not magically work without them. Link: https://github.com/BEEmod/BEE2-items/releases

**Comment by PieCreeper13** [comment]
I don't know where to find the Clean Style Package.

**Comment by cartman1337** [comment]
The packages you download include what Beemod needs to make Clean chambers, even if it doesn't have its own file. I'd imagine it uses many of the same instances as Original Clean, since the two styles are very similar.
