### ISSUE TITLE
New item! triangle/piramid cube

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2505]
![pc](https://user-images.githubusercontent.com/35931028/36343861-4b0b8048-141a-11e8-84fc-40e0909bd2f8.png)
![pc2](https://user-images.githubusercontent.com/35931028/36343862-4e23fbfc-141a-11e8-8103-ccb8343a107c.png)
and button:
![pc_socket](https://user-images.githubusercontent.com/35931028/36343891-f7e4cb44-141a-11e8-8863-7128f98ae028.png)

**Comment by Endermage77** [comment]
Wouldn't such a button be triangular rather than square?

**Comment by ZombiePwner1** [comment]
This is not possible since it would involve adding new entities which requires editing the source code.

**Comment by Endermage77** [comment]
It would? Well, I suppose the pyramid-only button would be a little complicated, but pyramid-shaped cubes would be really handy to discourage cube-stacking as a cheat method.

**Comment by ZombiePwner1** [comment]
@Endermage77 If you want to add new entities into the game that would require editing the source code which only valve can do.

**Comment by Luke18033** [comment]
We don't need to add any new entities. For the cube, we can just use a normal `prop_weighted_cube` set to the custom model type. For the button, we can use a prop_dynamic with a trigger filtered to only accept the pyramid cube model. The main problem is that somebody would need to actually make the models for this.
