### ISSUE TITLE
Overgrown laser fields pack as mysterious blue errors for people who don't have BEE installed.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2506]
![20180218084050_1](https://user-images.githubusercontent.com/18079316/36347037-e2943cda-1487-11e8-8428-8ca245f48337.jpg)

![20180218084059_1](https://user-images.githubusercontent.com/18079316/36347038-e6bdcbe6-1487-11e8-9a8c-42b9f33a93eb.jpg)

**Comment by cartman1337** [comment]
That looks suspiciously like one of my chambers. :D Thanks for playing! :)

**Comment by LautaroL20** [comment]
I have fixed this for next release, and it is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1887
