### ISSUE TITLE
BTS entrance fizzlers need rescaled models.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#2507]
![20180218082500_1](https://user-images.githubusercontent.com/18079316/36347042-03553dc0-1488-11e8-9ebc-b245d55144e5.jpg)

That fizzler is sticking out in a mysterious way.

**Comment by LautaroL20** [comment]
Maybe you mean that it requires a rescaled model, not "reclined". We could just use the rescaled model that i made for my Standing Fizzler item.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
