### ISSUE TITLE
No Texture on Goo in Coop Puzzles

### ISSUE THREAD

**Issue by Neightro** [BEEmod/BEE2-items#2508]
Hello! This is my first time posting both here and on Github in general ,so I apologize for any mistakes I may have made.

I have discovered that when creating Coop puzzles with BEE2.4, some item placements will cause deadly goo to appear without a texture, resulting in a pretty interesting light-show. See the image below. My testing has shown that this can be caused by:
-having a two-voxel deep goo pit.
-placing goo at different heights.
-placing gel over the pit. 

![portal 2 water glitch comparison](https://user-images.githubusercontent.com/23202923/36347589-ca6e8da4-140f-11e8-9056-61664e5890d0.png)

The workaround is to make them only one block deep, which to me is less preferable because it's possible to see the floor of it while dying; I don't believe this was ever possible in official chambers.

I apologize if this is a bug of the vanilla puzzle maker; I downloaded BEE2.4 as soon as I got the game, so I cannot say.

This bug has occurred for me with both pre-27 and pre-28.

**Comment by Endermage77** [comment]
As far as I know, this "leaky goo" bug usually happens when you switch to the 80's style. But when you do that, _all_ goo pits are leaky, and not just the 2+ deep ones.

**Comment by Neightro** [comment]
@Endermage77 Coop apparently can cause it to happen as well. This is just the Clean style.

**Comment by Neightro** [comment]
UPDATE: Testing has revealed that having goo on different levels and placing gels over it can also cause this problem. I am currently testing with pre-28.

**Comment by Neightro** [comment]
UPDATE: It also seems that it's possible to trigger this bug under some condition with angled panels and possibly antline routers. I saw this once, but after undoing and retracing my actions, I was unable to reproduce it or nail down the exact cause.

**Comment by Luke18033** [comment]
No idea what would cause this leak.
