### ISSUE TITLE
Suggestion: A check box to completely disable the Portal Gun.

### ISSUE THREAD

**Issue by Firepal** [BEEmod/BEE2-items#2509]
Please add a checkbox to disable giving the Portal gun to the player on map start.
i t ' s  f o r  a  p o r t a l  1  m a p

**Comment by ZombiePwner1** [comment]
@Firepal Just put auto portals outside of the map somewhere then they will disable your portal gun.

**Comment by Luke18033** [comment]
This happens automatically if both colors of Autoportals or Portal Gun Pedestals are placed in the map. If that's not happening, it's a bug. If you aren't using those and still need the player to spawn without the gun, you can do what @ZombiePwner1 said, although I'm not sure why you'd ever want or need that.

**Comment by ZombiePwner1** [comment]
@Luke18033 Well it is one way that can work.

**Comment by Firepal** [comment]
Well... how do i put this... when placing two autoportals ANYWHERE it appears i can't build the map.
By the way, i'm remaking Portal 1 in Portal 2. I know, i'm so original. /s
