### ISSUE TITLE
Non-portalable Piston Platform is missing its editor model

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2510]
![20180219122413_1](https://user-images.githubusercontent.com/19228201/36395833-0c183a64-1570-11e8-9d24-e58ba46f33f2.jpg)

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the label when closing the issue.

Heh, ill probably make this as a pre-made reply now.

**Comment by TeamSpen210** [comment]
It doesn't really matter too much for closed issues really, it's only really useful for when the issue is staying open.

**Comment by LautaroL20** [comment]
Although it seems unlikely, there are some people who checks in the "closed issues" tab, to see which issues were solvied/closed, so having them shorted with the proper label helps them to understand the real cause of its closure.
