### ISSUE TITLE
Non-static Piston Platforms cause a compile error

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2511]
This seems to be the problem:
```
ValueError: Unknown visgroup "pist_4" for "bee2_piston_platform_modern"! (valid: '', 'pist_brush_static', 'pist_brush', 'pist_1', 'pist_3', 'pist_glass', 'pist_2')
```
This applies to all three types of platforms (glass/black/white). Static platforms don't cause the error.

**Comment by TeamSpen210** [comment]
Sorta, actually `pist_4` is a default I didn't override in one config file. Which style?

**Comment by Luke18033** [comment]
Clean, Overgrown and Portal 1. I haven't tested Old Aperture.

**Comment by TeamSpen210** [comment]
Oh, maybe you haven't rebuilt the compiler?

**Comment by Luke18033** [comment]
Tried that, same error.

**Comment by LautaroL20** [comment]
So, did this got fixed?

**Comment by TeamSpen210** [comment]
Should be.
