### ISSUE TITLE
Chamberlock support for Tuleby's items

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/BEE2-items#2515]
The chamberlock should have an absolute fizzler, and fizzle cubes on orange buttons when entered.

**Comment by SCIENTIST2004** [comment]
I think so too

**Comment by Neightro** [comment]
I'm not sure I like the idea of an absolute fizzler; I could see that breaking puzzles. I wouldn't add it unless chamberlocks were changed to allow both coop players to enter.

**Comment by TeamSpen210** [comment]
Chamberlocks are for singleplayer only.

**Comment by Neightro** [comment]
Unless it has been changed in a newer build, the item description does not make that clear, and unless code is implemented that __prevents__ their use in coop maps, they will be used for them. Doesn't it make sense to make items as versatile as possible? I feel like this would be a limitation of the item's versatility.

**Comment by Neightro** [comment]
Maybe it would be better to split the item and create an absolute chamberlock instead?

**Comment by Endermage77** [comment]
Chamberlocks can still have use for co-op maps. For instance, locking one player into a room and keeping the other one out, if its done correctly.

**Comment by Neightro** [comment]
Precisely my point! I did that in a chamber I worked on; I would hate to see the item lose that potential.
