### ISSUE TITLE
Autosave multiple

### ISSUE THREAD

**Issue by Hottentotten** [BEEmod/BEE2-items#2517]
There are already the "Trigger Autosave" and the "Save Point" (btw i still don't know the difference between them). However, if you have something like a big chamber with one central point which the player is passing more often it would be good to have a trigger that quicksaves each time the player enters, and not only once.

An alternative would also be something like a pedestal button (maybe with different color or an extra signage) which the player can manually press in order to autosave.

**Comment by LautaroL20** [comment]
Interesting suggestion.

**Comment by HTiago** [comment]
_[off]_
> There are already the "Trigger Autosave" and the "Save Point" (btw i still don't know the difference between them).

The difference is that "trigger autosave" can be extensible to larger areas, while "save point" only uses a 1x1x1 area. Correct me if I'm wrong.

**Comment by LautaroL20** [comment]
Actually, there is no difference between trigger autosave and save point, they takes the exactly same space in the boxel. Its just a waste of space in the beemod palette catalogue in my opinion.

**Comment by Luke18033** [comment]
This would be possible with #1077.

**Comment by Konclan** [comment]
Moving to #3886
