### ISSUE TITLE
is there any condition in bee2 that detects if another instance occupies a voxel depending which face that item is on 

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#252]
is there any condition in bee2 that detects if a another specified item occupies a voxel depending which face that instance is on that could return a change instance condition or change offset condition on true.

and what do the "offset" values do such as "offset" "64 64 64"

if such a condition exists it will allow the creation of instances that will allow placement of lights and other things on half blocks etc.

**Comment by TeamSpen210** [comment]
The offset options shift the location that an instance is added at. It's mostly used so I can reuse an instance. Ther isn't a condition like that, but I'll go add one.
