### ISSUE TITLE
Sound Emitter

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2520]
An item, possibly with a physical representation such as a loudspeaker, that emits a sound of the creator's choice when activated. It would be useful for implementing aural cues into a chamber and suchlike, as right now the PTI/BEE2 is rather limited in how you can shape the soundscape.

The sounds would be selected using a timer option, and the timer options would be determined with the ICP, rather like the current color changer item.

One obvious use would be to trigger voicelines on demand, of course.

Some ideas for useful sounds to add to the bank:
- Activated
- Deactivated
- Explosion
- Gel Splatter
- Cube Collision
- Alarm
- Portal Placed
- Portal Erased
- Item Fizzled

**Comment by TeamSpen210** [comment]
This would make no sense, it really requires some actual visual component. Use Hammer for storylines.
