### ISSUE TITLE
(BTS) Standing Fizzler Not Visible in Editor

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2522]
When I place down a standing fizzler, it works fine, and it displays a manipulation gizmo until I deselect it, and it loads perfectly in-game, but the model in the editor is invisible, and it cannot be selected or moved at all once it's put down.

The item's icon also turns into a question mark thingy in the editor.

**Comment by LautaroL20** [comment]
I have fixed this for next release. However, this is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2456
