### ISSUE TITLE
Portaling through angled panels over bottomless pit kills you if you walk through it

### ISSUE THREAD

**Issue by cartman1337** [BEEmod/BEE2-items#2526]
Is this intended? If so, it doesn't make much sense to me, since the panel in its deployed form is safe ground in all other scenarios. In any case; here you see an angled panel placed deployed on a spot that is otherwise submerged in a bottomless pit. If I walk through the portal, either way, I'll die.
![Angled panel over goo kills you](https://i.imgur.com/xWH5xRx.jpg)

Not tested across all styles, but I first discovered it testing my new chamber in 70s style, and it's the same in Original Clean, so I would imagine it is the same for all styles.

EDIT: It's the same with 1/4 black/white walls, which makes even less sense, since those can't even be undeployed to kill you...

EDIT 2: Further testing makes it clear that angled panels over regular goo are safe, but when goo pits are converted to bottomless pits they become death traps. The bug might be that bottomless pits then initiate "hurt", or whatever the Hammer command is called, too soon, which seems consistent with falling into one; you don't fall very far before you're killed...

**Comment by LautaroL20** [comment]
The big problem is that the Bee´s Bottomless Pit version has a trigger kill that covers almost the whole part from the top of the boxel, which causes the player to be killed if they crosses portals the way you did. This is the cause of another thing ive reported, you can see it here: https://github.com/BEEmod/BEE2-items/issues/651

**Comment by LautaroL20** [comment]
I am really surprised you are the only person in the whole community that reported this tremendous bug, it really needs to be fixed soon since its terrific. Thanks for posting it.

**Comment by cartman1337** [comment]
Yes, about the kill trigger zone, I'd suggest that it be changed to only the very bottom of the boxel, not only to address this problem, but also the problem (maybe not raised either?) about catwalks into goo/bottomless pits.

Example; catwalks does not give crash in editor when lowered into goo, so with regular goo you can do this:
![Catwalk into goo](https://i.imgur.com/ExKufpJ.jpg)
For any player, however, it is clear that walking down the steps would be lethal, so they wouldn't try. However, if you try, you can actually walk 4-5 steps, and even hear yourself stepping in liquid for a couple of steps, before it actually kills you.

Convert the goo into a bottomless pit, and the same catwalk looks like this:
[Catwalk into bottomless pit](https://i.imgur.com/Pzjt1qK.jpg)
For a player, this looks completely safe, especially since the wall the catwalk is anchored to looks normal and not BTS. But if you try, you're killed on the second step (quite a bit higher than regular goo), which visually does not make sense.

In fact, the whole boxel looks quite normal and safe, but beneath it it looks dangerous. As such, it makes very little sense to trigger kill in those boxels until the very bottom of it.

**Comment by TeamSpen210** [comment]
I did this intentionally, but it's probably not a good idea. The reason is to make the player die as soon as possible, so they don't see that the bottom of the pit doesn't actually exist - there's a floor at the point where the normal goo is. To fix though, you can just not submerge stuff in the goo. I'll change it so it returns to how the original goo triggers behave.

**Comment by ZombiePwner1** [comment]
@cartman1337 @TeamSpen210 Placing catwalks in goo should stay since it makes for nice visuals in overgrown maps but I definitely see why this shouldn't be possible for bottomless pits.

**Comment by TeamSpen210** [comment]
Maybe I should detect catwalks dropping into either, and add a destroyed end.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 :) Even better.

**Comment by cartman1337** [comment]
Yeah, that sounds good. For the record, it was never my intention to actually use stairs in a bottomless pit, but I stumbled upon that scenario by accident when making a test. The finished test will have catwalks in only safe positions. ;)

**Comment by ZombiePwner1** [comment]
@cartman1337 Don't forget you can still use this in overgrown maps as a visual decoration like parts of a test chamber have been flooded. with catwalks in the goo.

**Comment by Luke18033** [comment]
Non-skybox pits will have the trigger in the normal location.
