### ISSUE TITLE
Illegal Quarter-Wide Wall

### ISSUE THREAD

**Issue by Neightro** [BEEmod/BEE2-items#2528]
While I was building a test chamber, I was attempting to place a quarter-wide wall. I think I did some funny movement with the camera, and somehow it snapped to a 45-degree angle. I was curious to know what the compiler would do with it, but testing that ended up being a mistake because the map would no longer compile after that.

Here is a screenshot of the item as seen in the puzzle maker.
![created an ilegal bee2 item](https://user-images.githubusercontent.com/23202923/36814471-78691e18-1c8c-11e8-9826-0b496f5dd8d3.png)

Despite it breaking a map for me, this is probably a minor issue because of how rare it seems to be. Once again, I apologize if this is an issue with the vanilla puzzle maker.

**Comment by SpyyZ158** [comment]
I think tt happend to me once too...

**Comment by ZombiePwner1** [comment]
@Neightro I've encountered this issue myself which unfortunately can't be fixed without editing the source code. And while glass like this looks cool unfortunately I don't think we'll beable to tell the compiler to generate it properly like that.

**Comment by Endermage77** [comment]
Can we make diagonal glass like this an actual thing?

**Comment by ZombiePwner1** [comment]
@Endermage77 No like I said the compiler will most likely be unable to generate the frames properly.

**Comment by Neightro** [comment]
That's unfortunate. It would be nice if Valve supported their stuff better; portal-bumping and CFG, for instance, should have been fixed a long time ago. 
@ZombiePwner1 Thank you for your speedy support!

**Comment by Neightro** [comment]
@Endermage77 We don't need this glitch item to be implemented; this is why we have 45-degree blocks. :smiley:

**Comment by SCIENTIST2004** [comment]
I also saw it

**Comment by Nikita74Russian** [comment]
I did this once.

**Comment by Nikita74Russian** [comment]
I somehow played my map with 45 angled glass, by the way, This should be a item in bee!

**Comment by SW50000** [comment]
@Nikita74Russian Why are you posting useless comments everywhere you go?

**Comment by McReenZRo** [comment]
His comment is NOT useless.

**Comment by Konclan** [comment]
Hmmm
