### ISSUE TITLE
Signage Additions

### ISSUE THREAD

**Issue by Neightro** [BEEmod/BEE2-items#2529]
The signage is one of my favorite features of the BEEmod. However, a few times when I've hoped for an appropriate sign, I've noticed that it isn't available. Here is a list of some of some signs I feel like should be implemented:

- **Gel dropper**. This is probably the biggest one; I always find myself thinking how nice it would be to have.

- Aerial Faith Plate. This already exists on the item itself, but being able to place signs for it manually might be helpful.

- Many people might appreciate a companion cube sign. Or they might not; red herrings sound entertaining.

- Signs for jumping in and out of portals. I think these appear on entry signs.

- Signs for floor buttons (place cube on button, stand on button).

I don't know if there is any room left to code these on the current sign item, but I would love to have them. Either way, thank you for your support!

**Comment by Cellolide** [comment]
I was thinking the same and would have some additions (still if it is even possible).
Note that these are obviously screenshots so the icons would still need to be done:
* **Laserfield and Emancipation field**
<img width="60" alt="laserfield" src="https://user-images.githubusercontent.com/33907318/36875535-a2f4f61e-1db0-11e8-901c-9f0697456e21.png">

* **Cube and Ball recepticle**
<img width="60" alt="recepticle" src="https://user-images.githubusercontent.com/33907318/36875520-8f1d4da8-1db0-11e8-8f43-02cc1049b2c9.png">

* **Jump through portal**
<img width="61" alt="portaljump" src="https://user-images.githubusercontent.com/33907318/36875512-8bbbe7dc-1db0-11e8-9a08-2544bcf69549.png">

* **Crushers**
<img width="62" alt="crushers" src="https://user-images.githubusercontent.com/33907318/36875498-7da425f6-1db0-11e8-9986-03e7301fd7d1.png">

* **Hand the cube**
<img width="61" alt="handthecube" src="https://user-images.githubusercontent.com/33907318/36875501-82250db6-1db0-11e8-9a56-5ed93dfc4528.png">

**Comment by SCIENTIST2004** [comment]
and shredder

**Comment by Neightro** [comment]
@Cellolide I agree with all of these! The jump-through-portal sign is one I was thinking about; I should edit my post. I just misinterpreted it as a momentum fling for some reason. It does look like that.

**Comment by Neightro** [comment]
@SCIENTIST2004 I'm pretty sure shredders aren't available yet, so I'm not sure why we would need a sign for it. Maybe the shredders could be added via a skybox?

**Comment by villager103** [comment]
Can we also get signages for custom elements, like positron orbs or sendificators?

**Comment by CreepiX987** [comment]
The Reflection Cube signage is also missing.

**Comment by Neightro** [comment]
@villager103 I believe that is currently being worked on at #1504.
@CreepiX987 There is a sign for using the redirection cube. Do you mean with a dropper?
