### ISSUE TITLE
New item: Shredder

### ISSUE THREAD

**Issue by Cellolide** [BEEmod/BEE2-items#2531]
As always: no clue if it's possible to implement:
![shredder](https://user-images.githubusercontent.com/33907318/36875821-1a7b4ebc-1db2-11e8-93b8-9522dfa9820c.jpg)

**Comment by ZombiePwner1** [comment]
This is already going to be re-implemented like all the other items from the old beemod.

**Comment by SCIENTIST2004** [comment]
this item was in the old bee mod (2.2.5)
