### ISSUE TITLE
[New Item] Skybox Overlay

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2533]
An overlay which when placed on a block will display the selected skybox (not goo). **Deadly.** Useful to make decoration like bottomless pits/holes in the chamber's ceiling which lead into the sky/space and so on.

**Comment by Neightro** [comment]
Actually, if we could use it to make open ceilings, that would be great, especially for the '70s style! 
It doesn't have to kill players; the goo pit already works as a bottomless pit if you choose a "3D" skybox.

**Comment by Endermage77** [comment]
This used to exist in BEE2.5. I don't think it worked. All it really did was be a black texture.

I imagine it's in the #95 list somewhere, though it's so long I can't even tell. It's also quite difficult to tell when things on that thing get ticked.

**Comment by ZombiePwner1** [comment]
Yes this was on the old beemod but it didn't work like it's supposed to.

**Comment by WafflesAndSyrup** [comment]
Is there the chance of it ever coming back though?
