### ISSUE TITLE
"Cubes fizzle on pellet contact" and Flux Rectangles are buggy and behave weird.

### ISSUE THREAD

**Issue by villager103** [BEEmod/BEE2-items#2535]
The "cubes fizzle on pellet contact" option: This behaviour only seems to apply to the first cube that comes out of the dropper. All the other ones after it don't fizzle. (tested with regular cubes in P1 style, should also apply to companion cubes)

In the Clean Style, a weird bug occurred when I put a cube in the cube holder, it bounced out(which should only happen to reflector cubes and spheres, to my knowledge) and kept making a noise over and over. It also lagged the game.

Flux Rectangles: The emitters on the side that fizzlers normally have don't appear(only tested in Portal 1 style) so it's just an aura coming out of the walls. This happens with and without the output relay.

**Comment by ZombiePwner1** [comment]
@villager103 Please provide us screenshots so we can understand what issues your talking about.

**Comment by TeamSpen210** [comment]
No screenshots, that makes sense.
