### ISSUE TITLE
BTS pedestal and protuding buttons are missing their textures.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2538]
![20180304154334_1](https://user-images.githubusercontent.com/18079316/36943944-553f5ba2-1fcd-11e8-9a3a-2c95880f805f.jpg)

**Comment by Nikita74RU** [comment]
Same portal gun dude.

**Comment by Luke18033** [comment]
Should be fixed with auto-packing.
