### ISSUE TITLE
Vactube Improvements

### ISSUE THREAD

**Issue by Neightro** [BEEmod/BEE2-items#2542]
I have a few suggestions for the vactubes that I would love to see implemented:

- The ability to transport gel; this would have some tremendous potential for coop. Maybe the paint blobs can be converted to be like when they travel through an excursion funnel? The last pipe in a series could just act like a gel dropper; an animation of gel flying through pipes (while pleasing) isn't necessary.

- If vactubes could suck items through portals, then it would be possible to remove the pneumatic diversity vent. Pipes could destroy items when directed at a chamber wall. The vent would also have to stop sucking in players in this situation, because using the vent to destroy items would be difficult if it sucked you in too.

**Comment by CreepiX987** [comment]
Also a little less of these awful pumps. Making at least N blocks of vactubes without them inbetween two of them would help.

**Comment by Neightro** [comment]
@CreepiX987 You're probably not hooking them up right. If you just place the start and end of a straight or curved segment and connect them, there will be fewer pumps.

**Comment by TeamSpen210** [comment]
I had a typo which meant all the variants are equally likely to occur. They should be more rare than they were - every 10 or so positions.

**Comment by TeamSpen210** [comment]
Unfortunately we won't be able to actually suck in gels - there's no way to identify what gel is used. What I will implement however is a gel dropper you can attach to the input, so the entire pipe becomes a gel dropper.

**Comment by Neightro** [comment]
That would be neat! Then with the right textures it would be possible to recreate the "Gel Flow" pipes in Old Aperture. I can't say whether or not they already look like that in the Old Aperture style, but that would look great.

**Comment by TeamSpen210** [comment]
They do not look like that, but the gel versions will.

**Comment by King0191** [comment]
Can I suggest that it will automatically put you in crotch position during Vertical Movement? (Mainly when you don't go up and turn, more so just going straight forward So we can have something like Aperture Tag where you can move to a different puzzle via Vactube?

**Comment by King0191** [comment]
Also heres a better idea for destroying items. to get rid of the Pneumatic Diversity Vent, Just make the pipe lead into an incinerator. (When they come back out. Until then just have it stored there

**Comment by Neightro** [comment]
@King0191 An incinerator seems like a bit too much work. Only the player would be able to see it, and if Diversity Vents sucked in players, it would make them very hard to use.

**Comment by Neightro** [comment]
@TeamSpen210 Sounds great! Can we also have those pressure releases, like when you see gel leaking out of a pipe?

**Comment by BETTEREXTENEDEDITORMOD** [comment]
Maybe, this could be for the drip setting. Or, this could be an attachment to the vac-tube via an' intersecting vac-tube facing down

**Comment by Neightro** [comment]
@BETTEREXTENEDEDITORMOD An intersection seems like the proper way to do it to me.  A generalized vactube intersection item would be very useful in general; I could see having multiple vactubes meet at one point as being useful.

**Comment by TeamSpen210** [comment]
Oh, that's a good idea for the drips. The only problem is that needs it to continue further...

**Comment by BETTEREXTENEDEDITORMOD** [comment]
That's why i said to make the dripping mechanic as an intersecting vac-tube. Just place it over the vac-tube and it'll add a drip hole

**Comment by Neightro** [comment]
Maybe a separate issue should be opened about this? The conversation here seems to have digressed from my suggestions about transporting gel and replacing the Diversity Vent item to Old Aperture gel tubes.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
Yeah, that would-be a good idea

**Comment by TeamSpen210** [comment]
There's already several issues open for vactube variants.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
Additionally there's a-lot of possibilities with intersecting tubes. For example, you could have a player only' vac-tube by adding an intersecting vac-tube that only sucks in cubes that takes them in-to an incinerator'
Or you could have a puzzle where a vac tube lead leads to the exit but there's an intersecting vac-tube' that takes you somewhere else so you have to deactivate it to solve the puzzle
