### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2-items#2543]
Well, developers are odd fellows. But! I must say, you made great mod for all of history of these improved editor mods.

P.S BenVlodgi is my steam friend

P.S You should re-implement all items from Old bee mod.

**Comment by Endermage77** [comment]
About your second point there, yes, there are plans to implement (mostly) all of the old items back into the mod. Eventually. Except for the Animal King turret, because nobody really knew what that was for. See #95 for the ongoing checklist to see what has and has not been put back in yet.

**Comment by LautaroL20** [comment]
Oh, not again... this is one of the most trite posts, alongside the ones that asks about the adhesion gel. Both are the most trite posts fom the whole beemod´s forums. It really buggs me when people open issues like this without get up-to date at reading the ones that are open, see: 

https://github.com/BEEmod/BEE2-items/issues/95
