### ISSUE TITLE
New Triggers

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2547]
1. View Trigger 
Fires its outputs when the player can see it (at least a half of it is on the screen).

2. Look Trigger 
Fires its outputs when the player looks directly at it (the crosshair is pointing at it).

Both can have a only-once version and a multiple-trigger version.

**Comment by TeamSpen210** [comment]
We can't actually do this easily, there's a lot of issues. And triggers aren't the right thing for this, they're invisible. I'm not adding a "find the invisible target" feature. What would they be useful for?

**Comment by CreepiX987** [comment]
@TeamSpen210 this could beused for decoration purposes - like in the main game panels go back into walls when you look at them.
