### ISSUE TITLE
Edgeless Safety Cubes get their own old aperture-style model for the Old Aperture 50's, 60's and 70's styles

### ISSUE THREAD

**Issue by villager103** [BEEmod/BEE2-items#2548]
The current one looks kinda crappy in the Old Aperture setting, because it has the blue/yellow glowy circle pattern on it.

There's already an Old Aperture Sphere Button, so I don't see why they couldn't make a metal ball to go with it.

Perhaps someone could make an actual model for this at some point?

I'll make a crappy MSPaint drawing of one if you want.

**Comment by TeamSpen210** [comment]
Ideed, but someone needs to make the model for it.

**Comment by Neightro** [comment]
I recall in the Developer Commentary that mentioned inventing a fictional character named Janitor Jim who built the Old Aperture test chambers; he could make almost anything, but he would make it with duct tape, etc. I can picture him maybe making the Edgeless Safety Cube with multiple pieces of bent metal bolted together. Barrel ties might look neat.

**Comment by TeamSpen210** [comment]
I've had a mental idea about what it would look like for a while - something like this:
![0fa3e465-205d-4629-beca-d97d4f7164f3](https://user-images.githubusercontent.com/8453732/37321352-da0150e6-26c3-11e8-97ba-1b03c3c69c56.jpeg)

**Comment by Endermage77** [comment]
That looks like a crossover between American/European footballs to me.

**Comment by villager103** [comment]
I was thinking more like a large, hollow metal orb built out of 2 halves that have been haphazardly bolted and taped together, with the Aperture Science Innovators logo(the same one that is on the cubes) stenciled onto it. It would fit in with the Old Aperture aesthetic more than a leather ball. Although Neightro's idea of having pieces of metal that have been bent and bolted into a crappy-looking sphere shape would also fit with the aesthetic.
