### ISSUE TITLE
3D skyboxes with fans and underground skybox suggestion

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#255]
we need some 3D skyboxes that have a option to have a giant fan in them like this and like the one in the one test in portal stories mel...

i just thought of something, where do those diversity vents get their suction from? maybe having a pneumatic diversity vent in the map should trigger a condition to put a giant fan in the skybox. i have another idea, maybe put some vac tubes in behind the fan in the tube part and use a point push to pull cubes etc into the fan blades and fizzle them. make sure you figure out which way to make the blades spin to make it look like it's trying to blow the cubes out of it from the inside.

do it in all styles if possible...

![mp_coop_fan0000](https://cloud.githubusercontent.com/assets/11165643/12540787/f1becc16-c2db-11e5-87b6-e0445f858091.jpg)

this gave me a idea, look at this second photo to get the idea for new type of underground bottomless pit and a test style outside the enrichment spheres

![mp_coop_fan0001](https://cloud.githubusercontent.com/assets/11165643/12540789/f69d73ea-c2db-11e5-858d-da10c556558e.jpg)

**Comment by TeamSpen210** [comment]
Diversity vents get their suction from the grey cylinder devices (seen in the lower-left of your second picture), not fans. See the pipe at the beginning of the [trailer](https://www.youtube.com/watch?v=DOH6BprN9FI).

**Comment by ellingtonvengaboysmuseum** [comment]
the grey cylinder devices are merely some type of valves that control the direction of the airflow in the tubes, the suction comes from some other unexplained place, which would be good to have a fan as a idea to explain the source of the suction in some tests that had open walls etc.

**Comment by IceTudor** [comment]
The "Grey Cylinder Devices" are actually a sensor that identifies what is sucked through, put an object into the Pneumatic Diversity Vent, it will show you on it's screen. It also works as a separable joint and as a way to rotate the tube as in Chapter 9 where you break a conversion gel tube with bombs before the final battle

**Comment by TeamSpen210** [comment]
Additionally in Old Aperture they already have the air ducting that appears if you use vents. When I get around to making 3D skyboxes though we could indeed have this.

**Comment by Luke18033** [comment]
This could be done once the new bottomless pits are implemented. It'd probably just be a random variant specific to Clean (and maybe a broken version in Overgrown).

**Comment by Konclan** [comment]
#3891
