### ISSUE TITLE
Some minor Portal 1 bugs

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#2550]
![portal2_2018-03-10_19-53-38](https://user-images.githubusercontent.com/6296061/37247710-54860582-249e-11e8-9533-19debee9e0ea.png)

- ~~Flip panels clip ever so slightly when rotating~~

![portal2_2018-03-10_19-54-04](https://user-images.githubusercontent.com/6296061/37247718-6343767c-249e-11e8-932c-59c11eca0f64.png)

- [ ] Extruded surfaces (disabled angled panels) are missing the portal placement helper (intended behavior?)

![portal2_2018-03-10_19-54-56](https://user-images.githubusercontent.com/6296061/37247726-78cf3b2a-249e-11e8-9cbd-7d6576ee238a.png)
![image](https://user-images.githubusercontent.com/6296061/37247835-8d7fb1b0-24a0-11e8-9d46-91d6b35034e8.png)

- ~~If a pellet is deflected by a cube deflector, they will still produce particles where they would have hit a wall if there was no cube there.~~

![image](https://user-images.githubusercontent.com/6296061/37247839-9adc1ff6-24a0-11e8-9dca-7d6c93552ffd.png)

- [x] Cubes that get respawned will no longer get fizzled by pellets

![image](https://user-images.githubusercontent.com/6296061/37249952-7e5a697a-24d0-11e8-9e72-2fc092844227.png)

- [x] Setting "Cube Type" to companion in editor gives us the error model

![image](https://user-images.githubusercontent.com/6296061/37257692-c4440e98-254b-11e8-9d7e-61a88e9840c4.png)

- [x] Radiative Flux field is missing its emitter, ~~its texture doesn't extend all the way through the field, and emits a particle when in contact with a pellet~~ (intended behavior?)

 - [x] Cube deflector no longer emits sounds when grabbing/releasing a cube (not consistent, they played the sounds after a rebuild).

**Comment by TeamSpen210** [comment]
The flip panel thing exists in all styles, it's a function of the geometry of the item. It's not really possible I think to fix the cube deflector problem, that just happens sometimes - after it impacts, it does a raycast to find the surface to draw the effect on which may in fact be wrong. Flux fields only extend a short distane on either side, and are supposed to make that effect.

**Comment by Luke18033** [comment]
Disabled angled panels are still missing a placement helper
