### ISSUE TITLE
'50s Style: Cool and Warm Light Strips Swapped

### ISSUE THREAD

**Issue by Neightro** [BEEmod/BEE2-items#2555]
After having worked on a map in the Clean Style, I switched over to the '50s style and noticed that the warm lights and cool (not cold) lights were swapped. I have yet to investigate what happens when I switch back. I would swear that while toying around I pulled out a cool light I got a warm light instead, but when I went back to check it was no longer happening.

I am happy to provide any files necessary; I wasn't sure what would be useful, so I didn't add any here. Just let me know.

**Comment by TeamSpen210** [comment]
This is intentional. The 50s style uses warm lighting by default, with cool lights as accents. All other styles are reversed, with default cool lighting but warm accents. We swap the items to maintain that relationship. (50s obs rooms also emit warm light for example.)

**Comment by Neightro** [comment]
Thank you! I saw on the '50s style page that the style primarily used warm lighting, but I had no idea that it would switch existing light strips. I assume that they will switch back as well?
