### ISSUE TITLE
Make Trigger Blocks Placeable Like Gratings

### ISSUE THREAD

**Issue by Neightro** [BEEmod/BEE2-items#2558]
I have had a few occasions lately where I have wanted to ensure that a trigger will be properly activated in a large corridor (3x3), and have found it either tedious (involving connecting multiple blocks with an OR gate) or impossible (where the player could bypass the triggers by taking an excursion funnel through the middle where I can't place one). The best solution I could think of to both these problems was to make the triggers resizable like a grating. I'm not sure if this is possible with the triggers' output, textures, and button type property, but it would be extremely convenient if it's possible. If not, I would appreciate at least being able to place trigger blocks in the air to stop issues with them being crossed over with puzzle elements.

**Comment by TeamSpen210** [comment]
There's already a more powerful version of this - take two of the same type and linknthem with antlines. They'll be treated as two corners, and the rectangular space between them will be filled.

**Comment by Neightro** [comment]
Thank you! I did not know that was possible.
