### ISSUE TITLE
Old Aperture Office Observation Room Unloading Incorrectly

### ISSUE THREAD

**Issue by Neightro** [BEEmod/BEE2-items#2559]
I realize that I posted a very similar issue just a day or so ago and it was closed as invalid. I respect the development team's opinions, since after all it is up to them what is fixed. However, I have encountered a rendering issue with the observation room that _is_ visible from the exterior and hope that they will look into it. I noticed the room's interior would be replaced with no render data as I moved about. While still a minor issue, I hope that this will be looked into.
![preview0022](https://user-images.githubusercontent.com/23202923/37438097-cc987228-27ad-11e8-8371-044ad880bfd7.jpg)
If it's any help to know, I use maximum graphics settings. I noticed this on a map preview just after respawning with an autosave.

**Comment by Neightro** [comment]
If anyone from the dev team reads this, I want them to understand that I have been active on the issues page here not because I think that this mod is broken or badly made, but because I care about it and hope that reporting these issues helps; I want to see it be the greatest that it can be. As well of course, I am interested in simply making note of these issues; I do not see it as urgent for them to be resolved.

**Comment by ZombiePwner1** [comment]
@Neightro It's either there is a leak in the map or the observation world portal is not loading correctly.

**Comment by Neightro** [comment]
@ZombiePwner1 It only disappears at some angles, mostly when I looked at it from a very sharp one. Would that make any difference as to what might be happening?

**Comment by Luke18033** [comment]
There's an areaportal there, usually areaportals closing incorrectly like this indicates a leak. But I don't think we'll get the VMF for this map at this point so I'll just close this.
