### ISSUE TITLE
[New Item] Singular Coop Checkpoint

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#256]
Co-op Separated Checkpoint Variant:

I remember when ive start on the Portal 2 mapping, my first map was cooperative. Well, it is still on friends view only because of the improperly respawns, it was a special map in wich each player must go separated on a diferent way that the current separated co-op checkpoint does not meet.

I consider if this Variant of checkpoint is maded, the co-op checkpoint odds, will be 100% supplied.
I would love to know if there is any issue with the idea i wil going to expose here.

---

This screen is taken from my early co-op map. Its an example of a situation in which this variant of separated co-op chckpoint would fit well:

![2016-01-25_00001](https://cloud.githubusercontent.com/assets/12244376/12565605/f4286c56-c393-11e5-8dc1-ed3297bc0729.jpg)

---

So, I suggest to make the: "Standalone and Small Triggeable Tube Checkpoint"
It basically consist when one of the players walks through a trigger, that player will respawn from here:

![2016-01-25_00002](https://cloud.githubusercontent.com/assets/12244376/12565695/7e4e018e-c394-11e5-95eb-08fb8d6f5e56.jpg)
![2016-01-25_00003](https://cloud.githubusercontent.com/assets/12244376/12565722/9ace61dc-c394-11e5-9aa5-8cfc817ba08a.jpg)

If its not possible to get it work through trigger blocks, it could be with the camera eye.

**Comment by TeamSpen210** [comment]
I definitely want to add this.The trigger would be inbuilt into the item - I need to be able to detect which player activated it to activate the correct spawn type.

**Comment by LautaroL20** [comment]
@TeamSpen210 - I was checking between the files from your Addons pack of Bee2.2.5, and ive noticed there is a file called "coop_dropper_multi.vmf", i have tried to get it work into a builded co-op map with some improvised editoritem code, but it didnt work. The actual file is located at: 

"Portal 2\sdk_content\maps\instances\p2editor\tSpen\clean"

Was this a kind of Singular Co-op checkpoint you were making, or what is this file for?

**Comment by TeamSpen210** [comment]
No actually, it's used as part of the 'separation coop checkpoints'. It's a respawn dropper which can be set to drop either player, since the checkpoint can have either player on each side (but not in the same playthrough).

**Comment by BenVlodgi** [comment]
I don't think the trigger should be built into the item.

Co-op Checkpoint should have these variations
- ~~Atlas only~~ (Use Player Specific triggers to do these types of implementations)
- ~~Peabody only~~ (Use Player Specific triggers to do these types of implementations)
- Both (when re-spawning), wait until the tube does not have the other player in it)
- Whoever activated it.

**Comment by LautaroL20** [comment]
Remember this item is focused to be used for one of the players only. It could be arranged to be used for "Both" players though, but primary funtion should always be one player, in order to provide each player a totally independent respawn point at different places (Something i tried to illustrate in the Paint pictures from the post).

**Comment by BenVlodgi** [comment]
You could use it just for Atlas if you have it set to **Whoever activated it** and only trigger it with an **Atlas Trigger**

**Comment by LautaroL20** [comment]
Ive found an interesting video from the DLC Campaing map, this will be the definitive "illustration" for the "Singular Co-op Checkpoint".

It doesn´t matter wich player will use this checkpont, be Atlas or Pbody, but only a player will be able to trigger it, this is exactly what i am suggesting:

https://youtu.be/r4Kwx_2aEaE?t=56s

**Comment by Luke18033** [comment]
@LautaroL20 Are you going to publish that map now?

**Comment by LautaroL20** [comment]
Unfortunately, no. Heres why: https://github.com/BEEmod/BEE2-items/issues/1439

**Comment by Luke18033** [comment]
That's fixed in the dev version, have you published it yet now?

**Comment by LautaroL20** [comment]
Well, i didn´t touch this map in a while, but ill probably get back on it.
