### ISSUE TITLE
Old Aperture Emancipation Grids Ignore Inputs

### ISSUE THREAD

**Issue by Neightro** [BEEmod/BEE2-items#2566]
Updated thanks to something that Villager103 pointed out; they just don't listen to inputs.

This seems to only apply to the vanilla emancipation grid; matter inquisition fields work fine. It is also impossible to have emancipation grids start disabled.

**Comment by villager103** [comment]
If i'm not mistaken, the Old Aperture fizzlers are completely broken, to the point where they don't even react to inputs at all.

**Comment by Neightro** [comment]
@villager103 I don't know. Matter inquisition fields seem to react properly, at least with one input. I need to do some more testing.

**Comment by atomic-cherry** [comment]
Noticed this too, the hard way, after I spent 2 hours trying different things to get the fizzler in my map to work.

A workaround until it's fixed is to have a Death Fizzler with start reversed disabled, and controlled by only Input A.

**Comment by Neightro** [comment]
Thank you, guys! Glad to see this fixed.
