### ISSUE TITLE
Portal 1 Style Major Problem

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2568]
So a Map I'm making is meant to be in Portal 1 style. But (even on a map with NOTHING) It cannot build. Help?

CONSOLE RESULTS:
VRAD failed.

[INFO] vrad.main(): BEE2 VRAD hook started!
[INFO] vrad.main(): Map path is C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[INFO] vrad.load_config(): Loading Settings...
[INFO] vrad.load_config(): Config Loaded!
[INFO] vrad.main(): Final status: is_peti=True, edit_args=False
[INFO] vrad.main(): Reading BSP
[INFO] vrad.main(): Done!
[INFO] vrad.gen_sound_manifest(): Written new soundscripts_manifest..
[INFO] vrad.pack_content(): Files to pack:
[INFO] vrad.pack_content():  # "materials/bee2/models/p1_pgun/v_portalgun.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/p1_pgun/v_portalgun.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/p1_pgun/v_portalgun_blue.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/p1_pgun/v_portalgun_blue.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/p1_pgun/v_portalgun_exponent.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/p1_pgun/v_portalgun_glass.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/p1_pgun/v_portalgun_glass.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/p1_pgun/v_portalgun_normal.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/p1_pgun/v_portalgun_orange.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/p1_pgun/v_portalgun_orange.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_metal_box/box_paint_blue.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_metal_box/box_paint_orange.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_metal_box/metal_box.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_metal_box/metal_box.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_metal_box/metal_box_bounce.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_metal_box/metal_box_comp.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_metal_box/metal_box_comp.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_metal_box/metal_box_comp_bounce.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_metal_box/metal_box_comp_speed.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_metal_box/metal_box_exponent.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_metal_box/metal_box_normal.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_metal_box/metal_box_speed.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_p1/door_01.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_p1/door_01.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_p1/kb_mouse.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_p1/kb_mouse.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_p1/lab_shelf.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_p1/lab_shelf.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_p1/walllight_sheet.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_p1/walllight_sheet.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/light_recessedcool_glow.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/metalwall048b_lrg.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/metalwall048b_lrg.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/metalwall048b_lrg_height-ssbump.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/metalwall048b_med.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/metalwall048b_med.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/metalwall048b_med_height-ssbump.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/modular_wall_light.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/detail_concrete_03.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/metaldoor028a.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/metaldoor028a.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observation_tilefloor001a.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observation_tilefloor001a.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observationwall_001a.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observationwall_001a.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observationwall_001b.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observationwall_001b.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observationwall_001b_height-ssbump.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/overlay_light_gradient.vtf"
[INFO] vrad.pack_content():  # "models/bee2/p1_pgun.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_ingame/p1_metal_box.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/door_frame_thick.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/door_left.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/door_right.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/keyboard.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/lab_shelf.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/lab_shelf_small.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/mouse.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/obs_light.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/security_camera.mdl"
[INFO] vrad.pack_content():  # "scripts/bee2_snd/p1_pgun_sounds.txt"
[INFO] vrad.pack_content():  # "scripts/bee2_snd/p1_physics_sounds.txt"
[INFO] vrad.pack_content():  # "scripts/bee2_snd/portal_sounds.txt"
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/change_models.nut"
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/set_p1_pgun.nut"
[INFO] vrad.pack_content():  # "sound/bee2/music/p1/taste_of_blood.mp3"
[INFO] vrad.pack_content():  # "sound/bee2/p1/doorstop1.wav"
[INFO] vrad.pack_content():  # "sound/bee2/p1/garage_stop1.wav"
[INFO] vrad.pack_content():  # "sound/bee2/p1/pgun/ambient.wav"
[INFO] vrad.pack_content():  # "sound/bee2/p1/pgun/portal_enter1.wav"
[INFO] vrad.pack_content():  # "sound/bee2/p1/pgun/portal_enter2.wav"
[INFO] vrad.pack_content():  # "sound/bee2/p1/pgun/portal_exit1.wav"
[INFO] vrad.pack_content():  # "sound/bee2/p1/pgun/portal_exit2.wav"
[INFO] vrad.pack_content():  # "sound/bee2/p1/wall_move5.wav"
[INFO] vrad.pack_content():  # "sound/music/sp_a4_finale4_z2.wav"
[INFO] vrad.pack_content(): Potential additional files:
[INFO] vrad.pack_content(): Injected files:
[INFO] vrad.pack_content():  # "scripts/game_sounds_manifest.txt"
[INFO] vrad.pack_content():  # "scripts/BEE2_generated_music.txt"
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/auto_run.nut"
[INFO] vrad.pack_content():  # "scripts/vscripts/BEE2/cube_setmodel.nut"
[INFO] vrad.pack_content(): Packing Files!
[WARNING] vrad.pack_file(): "bee2/sound/music/sp_a4_finale4_z2.wav" not found! (May be OK if not custom)
[INFO] vrad.pack_content(): Injecting "scripts/game_sounds_manifest.txt" into packfile.
[INFO] vrad.pack_content(): Injecting "scripts/BEE2_generated_music.txt" into packfile.
[INFO] vrad.pack_content(): Injecting "scripts/vscripts/bee2/auto_run.nut" into packfile.
[INFO] vrad.pack_content(): Injecting "scripts/vscripts/BEE2/cube_setmodel.nut" into packfile.
[INFO] vrad.pack_content(): Packing complete!
[INFO] vrad.mod_screenshots(): Using automatic screenshot!
[INFO] vrad.mod_screenshots(): No Auto Screenshot found!
[INFO] vrad.mod_screenshots(): Cleaning up screenshots...
[INFO] vrad.mod_screenshots(): Done!
[INFO] vrad.mod_screenshots(): Using PeTI screenshot!
[INFO] vrad.mod_screenshots(): Making "..\portal2\puzzles\76561198209103051\untitled.jpg" replaceable...
[INFO] vrad.main(): Publishing - Full lighting enabled! (or forced to do so)
[INFO] vrad.run_vrad(): Calling original VRAD...
[INFO] vrad.run_vrad(): "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vrad_original.exe" -final -staticproppolys -staticproplighting -textureshadows -hdr -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.bsp"
Valve Software - vrad.exe SSE (Mar  1 2018)

      Valve Radiosity Simulator     
8 threads
[Reading texlights from 'lights.rad']
[59 texlights parsed from 'lights.rad']

Loading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
Loaded alpha texture materials\Tools\toolsinvisible.vtf
Setting up ray-trace acceleration structure... Done (2.30 seconds)
1468 faces
62175 square feet [8953238.00 square inches]
0 Displacements
0 Square Feet [0.00 Square Inches]
1468 patches before subdivision
13732 patches after subdivision
429 direct lights
BuildFacelights:     0...1...2...3...4...5...6...7...8...9...10 (3)
BuildVisLeafs:       0...1...2...3...4...5...6...7...8...9...10 (1)
transfers 1097542, max 331
transfer lists:   8.4 megs
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #1 added RGB(21813, 28048, 32783)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #2 added RGB(6110, 8443, 9867)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #3 added RGB(957, 1264, 1403)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #4 added RGB(275, 371, 401)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #5 added RGB(62, 80, 81)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #6 added RGB(18, 23, 23)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #7 added RGB(5, 6, 6)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #8 added RGB(1, 2, 2)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #9 added RGB(0, 1, 0)
Build Patch/Sample Hash Table(s).....Done<0.0028 sec>
FinalLightFace:      0...1...2...3...4...5...6...7...8...9...10 (1)
FinalLightFace Done
364 of 396 (91% of) surface lights went in leaf ambient cubes.
ThreadComputeLeafAmbient: 0...1...2...3...4...5...6...7...8...9...10 (3)
Writing leaf ambient...done
Computing static prop lighting : 0ThreadComputeStaticPropLighting: 0...1...2...3...4...5...6...7...8...9...10 (3)

Ready to Finish

Object names       Objects/Maxobjs  Memory / Maxmem  Fullness 
------------       ---------------  ---------------  -------- 
models                  37/1024         1776/49152    ( 3.6%) 
brushes               1080/8192        12960/98304    (13.2%) 
brushsides            8405/65536       67240/524288   (12.8%) 
planes                4176/65536       83520/1310720  ( 6.4%) 
vertexes              3303/65536       39636/786432   ( 5.0%) 
nodes                  776/65536       24832/2097152  ( 1.2%) 
texinfos               450/12288       32400/884736   ( 3.7%) 
texdata                 56/2048         1792/65536    ( 2.7%) 
dispinfos                0/0               0/0        ( 0.0%) 
disp_verts               0/0               0/0        ( 0.0%) 
disp_tris                0/0               0/0        ( 0.0%) 
disp_multiblend          0/0               0/0        ( 0.0%) 
disp_lmsamples           0/0               0/0        ( 0.0%) 
faces                 1468/65536       82208/3670016  ( 2.2%) 
hdr faces             1468/65536       82208/3670016  ( 2.2%) 
origfaces             1246/65536       69776/3670016  ( 1.9%) 
facebrushes            401/0             802/0        ( 0.0%) 
facebrushlists        1468/0            5872/0        ( 0.0%) 
leaves                 814/65536       26048/2097152  ( 1.2%) 
leaffaces             1944/65536        3888/131072   ( 3.0%) 
leafbrushes           1830/65536        3660/131072   ( 2.8%) 
areas                   13/256           104/2048     ( 5.1%) 
surfedges            12582/512000      50328/2048000  ( 2.5%) 
edges                 8979/256000      35916/1024000  ( 3.5%) 
LDR worldlights          0/8192            0/819200   ( 0.0%) 
HDR worldlights        429/8192        42900/819200   ( 5.2%) 
leafwaterdata            0/32768           0/393216   ( 0.0%) 
waterstrips            236/32768        2360/327680   ( 0.7%) 
waterverts               0/65536           0/786432   ( 0.0%) 
waterindices          4539/65536        9078/131072   ( 6.9%) 
cubemapsamples           2/1024           32/16384    ( 0.2%) 
overlays                 7/512          2464/180224   ( 1.4%) 
LDR lightdata         [variable]           0/0        ( 0.0%) 
HDR lightdata         [variable]     1110260/0        ( 0.0%) 
visdata               [variable]        4760/16777216 ( 0.0%) 
entdata               [variable]       86356/393216   (22.0%) 
LDR ambient table      814/65536        3256/262144   ( 1.2%) 
HDR ambient table      814/65536        3256/262144   ( 1.2%) 
LDR leaf ambient       814/65536       22792/1835008  ( 1.2%) 
HDR leaf ambient      2748/65536       76944/1835008  ( 4.2%) 
occluders                0/0               0/0        ( 0.0%) 
occluder polygons        0/0               0/0        ( 0.0%) 
occluder vert ind        0/0               0/0        ( 0.0%) 
detail props          [variable]           1/12       ( 8.3%) 
static props          [variable]           1/5446     ( 0.0%) 
pakfile               [variable]    18834163/0        ( 0.0%) 
physics               [variable]      389493/4194304  ( 9.3%) 
physics terrain       [variable]           2/1048576  ( 0.0%) 

Level flags = 2

Total triangle count: 4670
Writing c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
Error opening c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp! (Check for write enable)

[WARNING] vrad.run_vrad(): VRAD failed! (1)

**Comment by CreepiX987** [comment]
It seems like file access permissions are messed up. Check for write enable in C:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp.

**Comment by King0191** [comment]
How would I check for write enable? I'm not good with that kind of stuff

**Comment by Endermage77** [comment]
Have you tried verifying Portal 2's game cache?
Instructions:
Right click on Portal 2 --> Properties ---> Local Files ---> Click on "Verify Integrity of  Game Cache" button.

That might fix something, who knows.

**Comment by LautaroL20** [comment]
When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. Your issue clearly seems te be related to this, so in order to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by TeamSpen210** [comment]
The error is totally unrelated to that. Delete `C:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp`.
