### ISSUE TITLE
Standing Fizzlers

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#257]
A Standing Fizzler that can be placed in 8 positions:

![Image](https://cloud.githubusercontent.com/assets/12244376/24085759/58ff7f16-0ce0-11e7-9197-635219288706.jpg)

**Comment by jccreszMinecraft** [comment]
An item like this is in development.

**Comment by LautaroL20** [comment]
@jccreszMinecraft, Im aware that there is something similar but its not the same. Do not get confused with the panel recessed into the wall with a fizzler covering it. This is a screen of the current "Recessed fizzler" in development:

![2016-01-28_00001](https://cloud.githubusercontent.com/assets/12244376/12635521/f403646c-c562-11e5-8a8c-c0f88a4c6255.jpg)

Like the title says, i suggest to make a variant of it for a standing position.

**Comment by jccreszMinecraft** [comment]
I mean exactly what you're suggesting. A standing fizzler is in the works. Also you appear to have somehow migrated the dinosaur Beemod's recessed fizzler into the new one, or that's the old Beemod anyways. Don't worry. We got this.

**Comment by LautaroL20** [comment]
Alright, if so, then i will close this post. But I would have liked if @TeamSpen210 could clarify on this.

**Comment by ellingtonvengaboysmuseum** [comment]
i agree, this would be a useful item, maybe use connection logic like the cutout tile to determine the width and the piston platform logic to determine height of it.

**Comment by TheReviewers** [comment]
I Need This ;-;

**Comment by TheReviewers** [comment]
Teamspen Already Said : ''I can't really add modifications to fizzlers, it's hard coded the way that the resizable ones work..''

**Comment by LautaroL20** [comment]
@TheReviewers - TeamSpen was referring to the In-Game models. Not the instance file. If it were the case, then there would never exist all the custom Fizzlers.

**Comment by Luke18033** [comment]
I would suggest to also merge Paint Fizzler into this item, with button type to choose the three.

**Comment by Byzarru** [comment]
Or all fizzlers. I'd love to see a variant of this for all of the fizzlers,

**Comment by Luke18033** [comment]
Yes, this would be three different items:

- Standing Fizzler/Laserfield/Paint Fizzler
- Standing CSF/FDF/MIF
- Standing Death Fizzler

Plus more for any future custom fizzlers.

**Comment by TheDarkBomber** [comment]
- [ ] Standing Fizzler/Laserfield/Paint Fizzler
- [ ] Standing CSF/FDF/MIF
- [ ] Standing DF/CSFi/PRF
- [ ] Standing Flux Field.

**Comment by TeamSpen210** [comment]
The problem is that I do not want to have 500 different fizzler items for every combination of item type, and positioning variant. So you need to figure out a eay for this item to work, so it can use the existing fizzler type.

**Comment by Endermage77** [comment]
This could be an opportunity to use that seldom-used Variations box...

**Comment by Luke18033** [comment]
How about use the timer to choose which Fizzler to use?

**Comment by TeamSpen210** [comment]
My idea for these kind of items is to give them an output, and have you connect it to the regular fizzler item. Then the regular fizzler will be deleted, and it'll reproduce that field.

**Comment by hop193** [comment]
Quote from TeamSpen210:
"My idea for these kind of items is to give them an output, and have you connect it to the regular fizzler item. Then the regular fizzler will be deleted, and it'll reproduce that field."

That's a good idea. It could work.

**Comment by TeamSpen210** [comment]
I just need to rewrite how fizzler items work.

**Comment by Konclan** [comment]
Wouldn't fizzlers get in the way then? Even if they are being deleted in place of the other one it still another object obstructing the editor view + it will still create errors with overlaping items, I mean I guess I could make a box far away from the map. But this doesn't sound very intuitive.

**Comment by TeamSpen210** [comment]
You can put it anywhere, so you could shove it anywhere there's room.

**Comment by Luke18033** [comment]
If there aren't any connected it should just become a normal fizzler.

**Comment by LautaroL20** [comment]
Indeed.

**Comment by LautaroL20** [comment]
Im starting to build the editor model for it:
![standing_fizzler model](https://cloud.githubusercontent.com/assets/12244376/24074103/127559e4-0be1-11e7-82b6-ed781b54f558.jpg)

**Comment by LautaroL20** [comment]
![Image](https://cloud.githubusercontent.com/assets/12244376/24085759/58ff7f16-0ce0-11e7-9197-635219288706.jpg)

**Comment by TeamSpen210** [comment]
Nice looking!

**Comment by LautaroL20** [comment]
Well, we will soon start to work on this since i have the In-Game fizzler rescaled now.

![gif](https://cloud.githubusercontent.com/assets/12244376/24686905/0f628efc-198d-11e7-8817-dbd304c78c79.gif)

**Comment by LautaroL20** [comment]
Ok, post description is now updated.

**Comment by LautaroL20** [comment]
This is now implemented.
