### ISSUE TITLE
Please, make the "High Energy Pellet Launcher/Catcher" One Item

### ISSUE THREAD

**Issue by LeoTheBrony** [BEEmod/BEE2-items#2570]
The same way that the Glass With Hole adchive the two hole sizes in the same menu, have it so you only need one and when you are ingame you can just switch it by right clicking (like the buttons) 
![image](https://user-images.githubusercontent.com/23579757/37559312-93f541c4-2a1b-11e8-8ce0-e50fe40d437f.png)

**Comment by Neightro** [comment]
So you mean that it's going to be a two-in-one catcher and launcher?

**Comment by Endermage77** [comment]
I'm pretty sure the two behave too differently to be able to combine with eachother.

**Comment by TeamSpen210** [comment]
Indeed, they behave very differently, with different inputs and outputs. We can't merge them.
