### ISSUE TITLE
Portal 1 Laser Emitters use incorrect (old) model when connected to a Sendificator

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2573]
Found this while looking through the P1 instances folder. The laser emitter instance used when connected to a Sendificator is still using the old model, instead of the custom one with the extended pipes.
![20180318101031_1](https://user-images.githubusercontent.com/19228201/37568606-ab3de1a0-2a94-11e8-848d-0b785ccff786.jpg)
(The left two are each connected to a Sendificator, the right ones aren't.)

**Comment by TeamSpen210** [comment]
`connections` branch fixes this by eliminating these variant instances.
