### ISSUE TITLE
Non-Pit Goo For BTS Should Be a Shredder

### ISSUE THREAD

**Issue by Reiid** [BEEmod/BEE2-items#2574]
In BTS, when you place two goo pits, with one being raised, the non-raised one will become a pit and the raised one will stay goo. A stylevar should be implemented that allows the raised pit to become a shredder, to fit the BTS style more.

**Comment by TeamSpen210** [comment]
That would be interesting indeed. First I have to implement shredders though....

**Comment by Neightro** [comment]
It would be great to have shredders in Clean or the upcoming Art Therapy as well; there are coop chambers that have them as a pit hazard.

**Comment by TeamSpen210** [comment]
Shredders are planned as an item in their own right. They function essentially as a goo pool that can be placed on walls and ceilings as well as the floor, and turned off to make them safe.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Overgrown chambers will feature a rusted model however if i'm not wrong.

**Comment by Luke18033** [comment]
BTS is being removed and shredders as an item are already on the list at #95
