### ISSUE TITLE
Turret Droppers Are Easily Neutralized

### ISSUE THREAD

**Issue by Neightro** [BEEmod/BEE2-items#2577]
It's possible to completely neutralize them by grabbing their turrets and facing them harmlessly toward a wall. This feels a bit too easy for me; I would rather see the turrets auto-fizzle three seconds after being picked up and put down. Or, maybe the timer setting could control this?

**Comment by TeamSpen210** [comment]
It's not supposed to be hard to do that. The intended use for the dropper isn't really for that, it's to provide a continuous amount of turrets for use elsewhere - for example with breakable glass, or to temporarily block lasers.

**Comment by Neightro** [comment]
@TeamSpen210 If there was a timer property, then we would have the best of both worlds. I won't open a new issue about it, but that is the purpose of this issue, and I hope that you would give it greater consideration.

**Comment by Neightro** [comment]
By the way, I think that the turret dropper should be focused on as a hazard rather than a test element for the player to use. Cubes—particularly the bomb cube—can be used in place of turrets in any role they would otherwise fulfill, and they are more friendly to the player.

**Comment by Endermage77** [comment]
I think also that the main situation creators would use turret droppers for would be a continuous hazard rather than simply as a tool like the cubes.

However, a respawning turret does have its uses, such as temporarily blocking lasers.
