### ISSUE TITLE
Glass with hole

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#258]
Introduction:

Its an item that probably many of us have seen in the first map from the co-op mode of Portal 2.
So, it would be interesting being able to have this as an item for Bee 2.4. 

Since it its not possible to resize "custom glass" because it will always form edges at their ends (TeamSpen210 knows what I mean with this). I highly recommend to make this item in way that do not interfere with ANY other item when placing it.

---

How it works:

The item is a glass with a square on it. Its primary function is to allow a cube to be passed from a player to another through its hole. The players can't go to other side, although they can shoot portals through it on portalable walls in both sides. I think is recommended for mappers to only introduce one cube per chamber for this item, otherwise people might pull tricks to pass through the hole.  

Here is some screenshots:

![asf](https://cloud.githubusercontent.com/assets/12244376/12686553/00a38f70-c6a9-11e5-9215-6844654837e8.png)
![co-op glass with square](https://cloud.githubusercontent.com/assets/12244376/12686617/641519a2-c6a9-11e5-9d82-e25234894354.png)
![sin titulo](https://cloud.githubusercontent.com/assets/12244376/12686602/54e1a64e-c6a9-11e5-8c09-ef268f8f93e3.png)

**Comment by TeamSpen210** [comment]
What do you mean by different sizes? There really only should be 1 (big enough to fit a cube). I'll probably merge this with the circular glass hole, using the 'button type' property.

**Comment by LautaroL20** [comment]
For some reason i said different sizes, but i dont remember right now. I think you are right, there should be 1, and merging with the circular glass hole would be useful. So, ill edit this post and remove that part of "Sizes".

**Comment by MicroElf** [comment]
Glass with a hole is a very useful element for Coop. Probably one of the items I really want to have available in BEEmod 2.4 as a priority

**Comment by TeamSpen210** [comment]
Unfortunately, it's not very reliable in Coop. If you are able to interact with an object (through the hole), the object will be teleported into your hands through all barriers. I'll block interaction like this though, which would make glass with holes act slightly differently to regular grating.

**Comment by BenVlodgi** [comment]
Would that mean you couldn't grab a falling cube through a glass hole?

**Comment by TeamSpen210** [comment]
It would - I was thinking about putting a `func_button` inside the hole, to absorb the `+USE` key. There isn't really a way to get around the coop issue - once a cube is picked up, it turns into a viewmodel and is non-solid to everything basically.

**Comment by Enterpise** [comment]
@TeamSpen210 I think he mentioned different sizes because this:

![2016-01-22_00001](https://cloud.githubusercontent.com/assets/15699236/12915473/5096ff9e-cf0a-11e5-8a86-c71f383cf603.jpg)
