### ISSUE TITLE
Portal 1 BTS Idea

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2580]
Everyone who played Portal 1 fully knows that you go behind the scenes into the observation rooms. So I was thinking. What if we had that as a Style? Essentially it would require a item and new Door variant. A door you press E to enter. And the item would be a Observation Room that has a door in the back so you can connect a corridor to it and then be able to enter the observation Room. 
Would any of this be Possible? 
Also this might be a duplicate idk I'm not goin through 890 issues.

**Comment by xDadiKx** [comment]
To be honest, it would be better to use Hammer and do this, with the Portal 2 In-game Puzzle creator, you are very limited on how much details you can put. Not to mention the size you have available in the Puzzle creator.

**Comment by Endermage77** [comment]
Already suggested, I'm afraid. See #553.

**Comment by King0191** [comment]
Well hey. At least theres the possibility of it being implemented. @TeamSpen210 Did say that they might try to implement it 😄

**Comment by LautaroL20** [comment]
Portal 1 BTS Style will come out with Half-Life 3.

**Comment by ZombiePwner1** [comment]
@LautaroL20 lol Half life 3 will never come.
