### ISSUE TITLE
Implement an intelligent system to prevent Retro Mandatory Observations from showing nodraw when duplicated

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2583]
The duplicated Mandatory Observations should still be included in the builded map, but with an intelligent system to prevent them from showing nodraw by using another skybox as HugoBDesigner suggested, or other type of geometry design inside them.

![20180322105601_1](https://user-images.githubusercontent.com/37309250/37778346-1953884c-2dc0-11e8-8c14-62f2ee25a6f0.jpg)
![20180322105610_1](https://user-images.githubusercontent.com/37309250/37778349-1bf8b572-2dc0-11e8-9de2-138ac40743eb.jpg)
![20180322105619_1](https://user-images.githubusercontent.com/37309250/37778351-1df7a194-2dc0-11e8-96c6-6b2cdb5cbaad.jpg)
![20180322105623_1](https://user-images.githubusercontent.com/37309250/37778353-20621a86-2dc0-11e8-8e08-0333976de6c9.jpg)

**Comment by King0191** [comment]
Nvm. Had to change styles. Sorry for wasting time

**Comment by HugoBDesigner** [comment]
The changing of styles doesn't really stop the bug from happening.

**Comment by villager103** [comment]
If i'm not mistaken, using multiple of those grated observation rooms causes issues because they use worldportals to show the enrichment sphere. There's a stylevar that changes them to normal observation rooms, or you could use regular rooms instead.

**Comment by ZombiePwner1** [comment]
@King0191 Yes do not use multiple large observation rooms in underground since they all use world portals and multiple of them can cause leaks perhaps switch to the other ones like @villager103 said.

**Comment by Luke18033** [comment]
That wouldn't cause any leaks, although it would cause nodraw to appear behind the grating.

**Comment by HTiago** [comment]
>do not use multiple large observation rooms in underground since they all use world portals and multiple of them can cause leaks 

There should be an alert on BEE2, if it does not exists already.
Maybe causing map editor to fail during compilation?

**Comment by HugoBDesigner** [comment]
> There should be an alert on BEE2, if it does not exists already.
> Maybe causing map editor to fail during compilation?

Perhaps, instead, it'd be better to have the compiler detect those and only make one (or none) of the worldportals actually work. Or perhaps replace them with a skybox?

**Comment by LautaroL20** [comment]
The duplicated Mandatory Observations should still be included in the builded map, but with an intelligent system to prevent them from leaking by using another skybox as HugoBDesigner suggested, or other type of geometry design inside them. 

Respect to other mandatory duplicated items in the map such as entry and exit doors i am totally agree that these should be excluded from appearing since otherwise would not make any sense asides from look messy.

I will open an issue containing the first exposed on the mandatory observation.

**Comment by LautaroL20** [comment]
I think its perfectly fine to merge the idea directly here.

**Comment by LautaroL20** [comment]
Nice, this has been implemented.
