### ISSUE TITLE
Item request

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2-items#2584]
Plain Crusher Panel
(Techical name: Aperture Science Authomized Crusher Panel)
Seen in Portal Prelude, just a panel moving down, acts like a slow crusher.
(can be used on walls too)

**Comment by HugoBDesigner** [comment]
https://github.com/BEEmod/BEE2.4/issues/876#issuecomment-375532803

>It’s already been suggested (and I've mostly finished reimplementing) under the name Slow Crusher.

**Comment by Nikita74RU** [comment]
It should be a other item than the slow crusher.
It should work in all styles.
(Let it be a separate item)
