### ISSUE TITLE
New entrance if a map has gel droppers

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2-items#2585]
The map will start with turning on the gel, in the chamber.
It will end up like this
![image](https://user-images.githubusercontent.com/35829557/37849638-48735054-2efa-11e8-9ce1-a30c304bbc15.png)
Basically a room with levers that you have to pull, and then the entry opens.

**Comment by Nikita74RU** [comment]
(This is not old aperture, it works with all styles.)

**Comment by TeamSpen210** [comment]
No it doesn't, those are only present in Old Aperture. And it'd be annoying for players who play lots of maps, since they'd need to go through the exact same room every time.

**Comment by villager103** [comment]
These switches are also only present in the pump stations, they are never inside the enrichment spheres. It wouldn't make any sense to give the spheres their own pump controls, given that they never have them in the official Portal 2 campaign.

**Comment by Endermage77** [comment]
This might be an interesting variant for Old Aperture BTS entries/exits.

**Comment by Luke18033** [comment]
This probably isn't going to be added.

**Comment by Nikita74RU** [comment]
May i fix you a bit?

This probalby is going to be added

Luke didn't close this 4 days ago

Luke added valid label 4 days ago

**Comment by Nikita74RU** [comment]
I dont care tho, i want this to be added.
