### ISSUE TITLE
Sendificator slim doesn't send through portals

### ISSUE THREAD

**Issue by HTiago** [BEEmod/BEE2-items#2588]
Cubes always appears on front of portal, instead of appearing at the end of laser beam. 
(or is it an expected behaviour?)
![image](https://user-images.githubusercontent.com/29435727/37868887-83758d54-2f84-11e8-8d02-fd049bde94ef.png)
Only tested with sendificator slim.

**Comment by HTiago** [comment]
Ew, maybe a duplicate from #2462 ?

**Comment by TeamSpen210** [comment]
I might have done the same thing, so it doesn't include the logic.

**Comment by TeamSpen210** [comment]
This would be fixed by the other commit.
