### ISSUE TITLE
4x1x1 Pillars

### ISSUE THREAD

**Issue by mariovct** [BEEmod/BEE2-items#2589]
<img width="400" alt="capture 78" src="https://user-images.githubusercontent.com/31172185/37881603-a86de78e-304f-11e8-890d-c6b6d2c6934c.PNG">

**Comment by Neightro** [comment]
YES! So this can look like the metal beam in BTS and the wood beam in Old Aperture.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
But the metal beam is hollow. It wouldn't connect to glass all that well not like in the picture.

**Comment by HTiago** [comment]
Seems a nice idea. Any other (better) pic?

**Comment by BETTEREXTENEDEDITORMOD** [comment]
But, i clearly highlighted it

**Comment by villager103** [comment]
Nice, there could also be a "Button Type" setting to make a 2x2 or 3x3 version. Maybe they could also implement a way to make it extend higher, similarly to the Standing Fizzler?

**Comment by LautaroL20** [comment]
1x1 Poles? Huh.... terrible word for describing it, that is a column, or pillar. And also, the size you are showing in that picture is 4x1x1, not 1x1.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
but it takes up one tile of space 
<img width="236" alt="capture 79" src="https://user-images.githubusercontent.com/31172185/37950139-4c429326-314c-11e8-8868-c7459e1811ba.PNG">

**Comment by BETTEREXTENEDEDITORMOD** [comment]
@villager103 That would be the half wall. But' i would like there to be an option to make it taller

**Comment by LautaroL20** [comment]
The image you posted is terrible in the first place, but if you see it carefully, it takes 4 tiles of height and 1 tile on the surface, so its a standing 4x1x1 block.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
Ohhh ok, now i get it

**Comment by Konclan** [comment]
Moving to #3885
