### ISSUE TITLE
The Refurbished style should be an Old Aperture stylevar instead of a separate style.

### ISSUE THREAD

**Issue by villager103** [BEEmod/BEE2-items#2592]
This would allow for more control over smaller details, namely the time period that the chamber takes place in, which is locked to 1950's in the original Refurbished style, allowing for 60's, 70's and 80's Refurbished chambers. This also allows the player to add things like Propulsion and Conversion Gels within their respective time periods, instead of just the 50's one.

**Comment by Neightro** [comment]
Given the presence of propulsion gel but not conversion gel, '70s era signage on the ground, and fairly open chamber design, we can be fairly sure that the official Refurbished chambers are from the '70s, not the '50s. Still though, making it a stylevar is a good idea.

**Comment by LautaroL20** [comment]
Considering that there are two clean styles available in Beemod that the only difference is that it changes some of the tiles, i do not see the point of why this would have to be an exception. Also, making this a stylevar would be pretty much inconsistent, people may even end up not seeing it.
