### ISSUE TITLE
Trigger Button Editor Model is showing as a "Mysterious White Texture"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2597]
This is probably the fault of the QC File being wrongly configured at the time of compiling the model:

![Image](https://user-images.githubusercontent.com/12244376/38084555-bd4a1656-3323-11e8-931c-5164edba88e9.jpg)

**Comment by Luke18033** [comment]
That's supposed to show a trigger texture, it must be missing for some reason.

**Comment by LautaroL20** [comment]
I fixed this.
