### ISSUE TITLE
¿How close are you to release Art Therapy?

### ISSUE THREAD

**Issue by wimklaver** [BEEmod/BEE2-items#2599]
im just curious how close Art Therapy is to completion

**Comment by LautaroL20** [comment]
Wheatly style will come out with the release of the Linux version of Beemod.

**Comment by wimklaver** [comment]
cool thanks

**Comment by LautaroL20** [comment]
No problem.

**Comment by Nikita74Russian** [comment]
It will come with Half Life 3 which means never
