### ISSUE TITLE
Music not working

### ISSUE THREAD

**Issue by Onemario1234** [BEEmod/BEE2-items#2601]
Alright, so I've been making a chamber using the Portal 1 style, and for some reason, the music itself has stopped playing. I've tried "I'm Different", "I Saw A Deer Today", and "Subject Name Here". All three of which didn't work. Changing entrance corridors, as TeamSpen suggested in the Discord server, didn't work, and no errors related to the music appeared in the console.

If you need any more info, I'll try and provide it if I can.

EDIT: Updating to Pre-release 29 fixed the issue.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
Why close it?

**Comment by Onemario1234** [comment]
As I said in the edit, updating BEE2.4 to Pre-release 29 fixed the issue, so it's no longer a problem.
