### ISSUE TITLE
Make some "Arm Variants" for each degree of the Angled Panel (See some examples)

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2602]
![capture 5](https://user-images.githubusercontent.com/31172185/38120203-07a3b0ec-337c-11e8-9213-0457c2cdc4f0.PNG)

![capture 6](https://user-images.githubusercontent.com/31172185/38120208-12f9c26a-337c-11e8-953a-61a203502188.PNG)
Regular PTI

![capture 7](https://user-images.githubusercontent.com/31172185/38120215-187dc998-337c-11e8-99e8-3e7b8320acc7.PNG)

**Comment by LautaroL20** [comment]
Nice suggestion!

**Comment by BETTEREXTENEDEDITORMOD** [comment]
Will all these panels need seperate animations?

**Comment by LautaroL20** [comment]
Not sure, but if it does then we have it complicated since i do not know how experienced is Spencer at making animated modes in Blender.

**Comment by TeamSpen210** [comment]
The problem with existing animations is they don't align to any specific angle. The PeTI ones are exactly 30 degrees, 45 degrees, 60 degrees, and 90 degrees. Those are not, and are not hinged around a corner. So we'd need to animate it all ourselves. If I was to do it I'd probably only do some static poses.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
I've heard you can animate things easy and fast in SFM. Maybe this could be used to animate the angled panels?

**Comment by Blacksilver42** [comment]
Here's how I'd do the UI for this:

* Timer-selector on the panel's context menu to choose the variant. Forever means random.
    * Checkboxes in compiler settings, enabling and disabling each variant for the random selection.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
I think the timer selection goes all the way up to 60, so that means 60 different arm formations, i would lower that down to 10, or 30 max

**Comment by TeamSpen210** [comment]
Why do you need to be able to choose the variant? Any other variants I have are all random.

**Comment by Endermage77** [comment]
@BETTEREXTENEDEDITORMOD The timer goes up to 30, from 3, so essentially 27.
