### ISSUE TITLE
Lifeform Sensor and Radiative Flux Rectangle are using the same name in the in-game palette.............

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2603]
IN GAME!
![2](https://user-images.githubusercontent.com/35931028/38141661-db10cbca-3441-11e8-81f8-420100e6484f.png)
![default](https://user-images.githubusercontent.com/35931028/38141664-dfad5752-3441-11e8-82d5-57d15c4b9697.png)

**Comment by LautaroL20** [comment]
That is weird...

**Comment by SCIENTIST2004** [comment]
agreed

**Comment by Nikita74RU** [comment]
Not fixed for me.

**Comment by Luke18033** [comment]
It is indeed fixed, but you won't receive the fix until the next update comes out (unless you use dev).

**Comment by LautaroL20** [comment]
This needs a closing commit...

**Comment by LautaroL20** [comment]
Closing commit added.
