### ISSUE TITLE
New style: Block chamber

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2604]
pedestal button
![20180331160012_1](https://user-images.githubusercontent.com/35931028/38163636-242989b4-3500-11e8-840c-4ad41e6f37bb.jpg)
![20180331160015_1](https://user-images.githubusercontent.com/35931028/38163638-27360858-3500-11e8-8815-3ab1d1065f45.jpg)
floor button
![20180331160026_1](https://user-images.githubusercontent.com/35931028/38163647-461ca164-3500-11e8-926c-3873148ee7d0.jpg)
![20180331160028_1](https://user-images.githubusercontent.com/35931028/38163648-47d093a8-3500-11e8-90c1-e88b112c9d88.jpg)
Vertical Security Door
![20180331160050_1](https://user-images.githubusercontent.com/35931028/38163665-8f0b0956-3500-11e8-81a1-2470e643b1da.jpg)
cube dropper
![20180331160204_1](https://user-images.githubusercontent.com/35931028/38163666-99965a56-3500-11e8-9670-e9761e43c2c4.jpg)
![20180331161214_1](https://user-images.githubusercontent.com/35931028/38163673-b2aac478-3500-11e8-92b3-a8eb209ede72.jpg)
chamber lock
![20180331160256_1](https://user-images.githubusercontent.com/35931028/38163669-a3ac35d8-3500-11e8-806b-a5c76f1b5b04.jpg)
black walls
![20180331160356_1](https://user-images.githubusercontent.com/35931028/38163674-be3ea476-3500-11e8-898c-65be21059374.jpg)
rail platform
![20180331160439_1](https://user-images.githubusercontent.com/35931028/38163681-d9749976-3500-11e8-9575-23b1872e7ae3.jpg)
http://steamcommunity.com/sharedfiles/filedetails/?id=1347892634

**Comment by Luke18033** [comment]
This might be implemented eventually, but new styles aren't really the top priority right now, so it won't happen any time soon.

**Comment by TeamSpen210** [comment]
Additionally I don't want to steal someone's style without asking them first.

**Comment by SCIENTIST2004** [comment]
the developer of "Block chamber" 
http://steamcommunity.com/profiles/76561198080817373

**Comment by Luke18033** [comment]
Custom styles like this would be better for UCPs to implement
