### ISSUE TITLE
"Planned to fail" Door

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2-items#2607]
A door that will force itself to fail, malfunction.
Otherwise, fizzle the cube.
You connect the door to the dispenser to fizzle.
Now you open the door, the cube fizzles. Dispenser shuts off.
Door explodes and opens.

**Comment by TeamSpen210** [comment]
BEEmod is not for adding incredibly specific things for a particular map. Use Hammer if you want to tell a story. Additionally, I don't usually want to add such malfunctioning stuff - if the map wasn't malfunctioning, why does the alternate solution exist?

**Comment by Nikita74RU** [comment]
I dont care dude. I cant use hammer so i did download this.
