### ISSUE TITLE
A blue long pit (PORTAL 1 STYLE ONLY!!!!)

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2-items#2610]
Basically a kinda blue portal 1 pit, just a texture of orange pit. But use blue instead.
This is a actually a bottomless pit for p1.
https://youtu.be/rfJMZdasZiA?t=254

**Comment by villager103** [comment]
There can't be items for specific styles only, there has to be equivalents of it for every other style. How would this be placed? We can't place it like deadly goo, only replace the existing goo, like the existing Bottomless Pits, but they're a separate skybox, which uses the same pit for every style.

**Comment by Endermage77** [comment]
This could be a stylevar bottomless pit for Portal 1.

**Comment by TeamSpen210** [comment]
I'm fairly sure this never existed in any actual Portal 1 level.

**Comment by Nikita74RU** [comment]
Well 60s style didnt exist so?

**Comment by Endermage77** [comment]
60's style did exist. It was the first part of Chapter 6. It';s simply that we never go in any test chambers from that era.

**Comment by Nikita74RU** [comment]
Flamethrowers in Portal 2 is not existant, so?
