### ISSUE TITLE
ONCE gate

### ISSUE THREAD

**Issue by Blacksilver42** [BEEmod/BEE2-items#2611]
Like a SR latch, but can't be unset; a trigger once, but for logic.

Advantages over a SR latch with no B input:
* Doesn't require the input A/B items.
* Less entities probably

Put together with the Toggle latch so I don't have to give it it's own palette slot.
Start enabled makes it start on then turn off when triggered.

Equivalent in ye olde laser logic:

![image](https://user-images.githubusercontent.com/14184826/38177449-c91bc282-35cf-11e8-8436-4676cc42db1b.png)

**Comment by Endermage77** [comment]
So, essentially a Trigger Once as a logic gate.

**Comment by TeamSpen210** [comment]
My plan is to make the default input to SR latches do whatever it isn't currently doing - so you can just use that.

**Comment by Blacksilver42** [comment]
What do you mean by that?

**Comment by TeamSpen210** [comment]
An input to an SR latch without an A/B would turn it on if it starts disabled, or off if it starts enabled.

**Comment by TeamSpen210** [comment]
Actually, why don't you use an SR latch? It's the same item as A/B, so it only takes up one palette slot regardless. It's not going to use up many entities.

**Comment by Blacksilver42** [comment]
I can already do that.

![image](https://user-images.githubusercontent.com/14184826/38213640-1162c700-3690-11e8-9931-8e4fa8b80d61.png)


But I don't have the patience to place TWO WHOLE ITEMS!

**Comment by TeamSpen210** [comment]
Then I don't think this mod is good for you.
