### ISSUE TITLE
Snow Palette for Beemod?

### ISSUE THREAD

**Issue by offbrandbiscuit** [BEEmod/BEE2-items#2614]
I'm not exactly sure where to post this, so I'm posting it here. If there is an actual forum I SHOULD be submitting it to, please leave it in a comment.

Now, I don't know if this is true, but I heard there was a snow palette for Beemod that was being developed. So I just wanted to share some ideas I had for it.

Crushers would be frozen, so they looked like they had sharp icicles stuck to them

Laser emitters would have some ice melted around them, because they're obviously generating heat. 

When a laser is put in a catcher, it melts the ice around it.

The cubes would be slightly covered in ice.

The goo would be frozen, and when falling into it, the goo would crack, and you'd fall into it and die. (obviously)

If you chose a skybox overlay that precluded a roof, (for example using Open Enrichment Sphere, etc) there would be snow coming in. A bit like the sprinklers in Wheatley's fight, but just slower, and with snowflakes.

Warm lights would melt ice in close proximity to it, and cold lights would be frozen over completely.

Basically just imagine some test elements that are slightly frozen or make cracking sounds when activated (for example a piston platform) because the ice is breaking. 

The portal gun's triple prongs (aka the weak zero-point energy field manipulator that picks up items) would have a bit of ice on them.

Observation rooms' glass would be cracked (because apparently glass can crack if the temperature drops very suddenly) 

I don't know if this is true, but I heard that the devs were considering allowing the players to change the light coming out of observation rooms to be neutral, cold, or warm. The light strip effects I listed would not apply to observation rooms.

You could set the skybox overlay to be gentle snow, or a blizzard. This would decrease visibility and most likely increase visibility checking times in the PeTI editor.

The elevator video could be a modified Aperture logo that had the words "Antarctic Division" underneath them, (a bit like the logo in the elevator room of the Penrose chambers)

I know a lot of these ideas are probably not feasible or wouldn't work, I just wanted to share a couple of them.

Thanks for reading.

**Comment by ZombiePwner1** [comment]
@offbrandbiscuit This is most likely the freezer style someone came up with.

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.

**Comment by offbrandbiscuit** [comment]
Understood. Thanks, though.

**Comment by peefTube** [comment]
I've had a similar idea to this before, myself, although the idea was different in that it'd be in some sort of icy cave with surfaces being built as needed around the cave walls. Goo would be liquid nitrogen and lasers would be "cold lasers" which wouldn't affect the chamber around them.

Interesting to see I'm not the only one who's had this idea before lol

**Comment by offbrandbiscuit** [comment]
Liquid nitrogen haha

Yeah, it is interesting. Apparently somebody had a "Freezer" style they offered, (basically inside a freezer), but my idea was more centered around an Arctic/Antarctic Aperture division. 

I actually had concept ideas for introducing melting ice, a staple element in the chambers. Basically, there's a laser emitter, and a catcher on the opposite wall. So, you have to melt the ice on the wall that the emitter is hitting, and then you'll be able to portal on the wall. It doesn't matter what type of surface it is, non-portalable or portalable, it has to be melted or the portal won't work.

Your idea kinda makes me think of the "Stage" style from Aperture Tag. But arctic.
