### ISSUE TITLE
Surface Marker Variations

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2616]
- Just a different texture, which we have now

- A piston platform which is very slightly sticking out of the wall, like in Portal 1 

- A line around the surface, like if you put a flip panel (may come together with a different texture)

**Comment by the8bitMoon** [comment]
You can already create a slightly stuck out panel by using an angled panel with no inputs and "start enabled" unchecked.

**Comment by CreepiX987** [comment]
@the8bitMoon it's just a wall, I mean an actual piston platform like in P1.

**Comment by TeamSpen210** [comment]
You can now do this with a piston platform. The line around Flip Panels really only applies to Clean.
