### ISSUE TITLE
Door with Fizzler

### ISSUE THREAD

**Issue by xDadiKx** [BEEmod/BEE2-items#2617]
Simple concept. A door that acts like a normal regular one but with an embedded fizzler in it, this fixes the awkward fizzler in front or behind the door. 
![20180404215227_1](https://user-images.githubusercontent.com/13087761/38331265-16a6eed4-3853-11e8-82f9-25ca958e258d.jpg)
A door with no outputs being sent to it.
![20180404215239_1](https://user-images.githubusercontent.com/13087761/38331278-2267ef84-3853-11e8-9f6e-dd3207093d6d.jpg)
A button that opens or closes the door
![20180404215249_1](https://user-images.githubusercontent.com/13087761/38331297-2ca4b072-3853-11e8-8086-86ffdab36309.jpg)
A button that disables or enables the fizzler.

**Comment by HugoBDesigner** [comment]
Perhaps the [Standing Fizzler](https://github.com/BEEmod/BEE2-items/tree/master/packages/Lautaro/standing_reclined_fizzlers) can be placed inside the door?
