### ISSUE TITLE
Turret Detector

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#2620]
Closest issue I found was #1683, but it's not quite what I had in mind.
I was thinking of something more like the turret detector in Lego Dimensions, where if you place a turret in front of it, the turret will target it. So as long as the turret is firing it, the item outputs.

![image](https://user-images.githubusercontent.com/6296061/38368226-1e6de36c-38bb-11e8-887c-3624b7bad081.png)

Key aspects of it:
 - Not just a turret detector, as you have to keep the turret alive;
 - If possible, make the target the main target, so that players passing by the turret won't get shot;
 - If the turret's line of sight to the target is blocked (by a light bridge, for instance), the target stops outputting.

**Comment by CreepiX987** [comment]
Beautiful.

**Comment by Endermage77** [comment]
I have not even heard of something like this before. Well found.

**Comment by CreepiX987** [comment]
@Endermage77 exactly.

**Comment by atomic-cherry** [comment]
I actually had this idea the second I saw it used in Lego Dimensions.
Would certainly be an interesting puzzle mechanic, having to carry a turret around to get through. Reminds me of the Portal Stories Mel finale.

**Comment by TeamSpen210** [comment]
This sort of thing is the reason I added Turret Droppers in originally, where you need an alive turret. You can make turrets fire at specific things fairly easily (by making them 'hate' an NPC at the location). However, they prioritise the player, not sure if I can override that. The only real difficulty would be designing the sensor, so players recognise they should shoot it with a turret.

**Comment by Endermage77** [comment]
If it was BTS you could use the target board from the turret assembly area.

**Comment by Nikita74RU** [comment]
In Portal 1 It's a Human Portrait pinned to the piston panel

**Comment by CTB33391** [comment]
In underground it could just be a target board. Clean and Overgrown would look similar to Dimensions (but not made of lego) and BTS would just be a dummy in a hole in the wall.

**Comment by ZipZoptheCat** [comment]
I like the mannequin idea and the plywood cut-out both. The light up target might not be obvious though unless it's bullseye shaped like the landing pad for the faith plate? Concentric circles I mean.

@Luke18033 
@HugoBDesigner 
Is there a way to get alerts for threads? I usually just use sort by new which appears to not show closed threads. Sorry for duplicating this thread twice, didn't realize this was already here.

**Comment by ZipZoptheCat** [comment]
I'm going to try to at least skim through all ~3k threads so I know what ideas are already out there.

**Comment by HugoBDesigner** [comment]
@ZipZoptheCat You can just use the search bar before opening a new issue, like so:
![image](https://user-images.githubusercontent.com/6296061/43689765-8760bfd2-98d5-11e8-9b62-b77f20d265a5.png)

**Comment by ZipZoptheCat** [comment]
All the same I should probably get a first hand look at all the threads.

**Comment by ZipZoptheCat** [comment]
I decided to only go through the issues that were still open. Took nearly 24 hours but I did it.
