### ISSUE TITLE
Texture Changer

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2622]
You select one of 27 textures using the timer and put the item on a surface. The texture on that surface will be replaced with the one you selected. You can change the textures used for each timer variant using the ICP. This will make you able to use your own textures. This item won't conflict with anything becuase it just changes the texture on the wall/floor/ceiling.

**Comment by Konclan** [comment]
Whoops, didn’t mean to hit the button. Apperently its super easy to accidentally close issues on mobile...

**Comment by ZombiePwner1** [comment]
This is not possible to do it'd require adjustments for all styles and would take too much time.

**Comment by Endermage77** [comment]
I think you're confusing "Impossible" with "Highly Improbable" there.
