### ISSUE TITLE
Implement styled versions for the ceilling and floor BTS Small Observation

### ISSUE THREAD

**Issue by the8bitMoon** [BEEmod/BEE2-items#2625]
In the current implementation, BTS observation rooms can only be placed on walls, not ceilings or floors. The current model would support both orientations so it should be a simple fix.

**Comment by LautaroL20** [comment]
This is because currently we haven´t any styled variants for the ceilling or floor, they were using an unstyled version.

**Comment by the8bitMoon** [comment]
Simply removing the "FORBIDDEN_PLACEMENT" line in editoritems.txt allows the wall model to me placed on the floor and ceiling. It's not perfect of course but imo it's better than disallowing floor and ceiling placement for one particular style and none others.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
