### ISSUE TITLE
Entry Door Editor Model is invisible in all the Old Aperture Styles

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2626]
![20180405225420_1](https://user-images.githubusercontent.com/35931028/38415002-cf67cfe2-3998-11e8-8672-7593c6521d89.jpg)

**Comment by ZipZoptheCat** [comment]
The entry door door also frequently has invisible side panels on either side of the door.

**Comment by HugoBDesigner** [comment]
Already reported in #2725
