### ISSUE TITLE
Ghrime 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2631]
I don't think it would be too hard to generate random ghrime and dirt on walls' floors' and ceiling 
<img width="210" alt="capture 86" src="https://user-images.githubusercontent.com/31172185/38532846-79e99916-3c2b-11e8-8bbe-436ccad30872.PNG">
<img width="402" alt="capture 85" src="https://user-images.githubusercontent.com/31172185/38532851-7f1a0038-3c2b-11e8-9183-e2a2d64aef9a.PNG">

**Comment by Luke18033** [comment]
This would be a part of BEEmod/BEE2.4#414.
