### ISSUE TITLE
Random question

### ISSUE THREAD

**Issue by WafflesAndSyrup** [BEEmod/BEE2-items#2634]
What is this GLaDOS item in the old version of bee2?
![screenshot 36](https://user-images.githubusercontent.com/36249695/38712280-27886d12-3efd-11e8-8ec1-6d9dc332098a.png)

**Comment by TeamSpen210** [comment]
When activated, it'd play one of a few GLaDOS lines. However it doesn't really make much sense with other voice lines, since there aren't really substitutes in most cases.
