### ISSUE TITLE
Need help with coop checkpoints!

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2-items#2640]
Can't place them, they are showing error.

**Comment by villager103** [comment]
They need to have an open space on each doorway.

**Comment by LautaroL20** [comment]
@Nikita74RU - Coop Checkpoint Editor Models displays perfectly fine using PRL29, if it displays as "Blue Error", that obviously means something is really worng with your Beemod install / export. Make sure it is doing a full export, to do that, open Beemod and click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

**Comment by Nikita74RU** [comment]
I mean, i can't place it. It says Incorrect Placement. Not a model bug.

**Comment by LautaroL20** [comment]
They are only placeable on Ceilling. Otherwise the robots could not respawn in horizontal position (walls) or from the floor because that would be really a mysterious way...

**Comment by TeamSpen210** [comment]
You probably have placed it incorrectly, it needs open space for the exit door.

**Comment by Nikita74RU** [comment]
Lautaro, I MEAN NOT THE COOP DROPPERS YOU FOOL! I mean the CHECKPOINT
