### ISSUE TITLE
Portal 1 Bottomless Pit

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2-items#2643]
Just a black void infinite pit, like if you dag a huge pit in test chamber, it will be a long, dark pit. So, why not make it a sequence that kills you if you jump down? Note, this discussion can be closed, if Death Trigger will be added. So, a HUGE, LONG, PIT. While you fall, you stay alive for some seconds, then if you hit bottom, you will be killed by trigger_hurt, you will fade out.

**Comment by Nikita74RU** [comment]
I dont like goo in that case, because you CAN notice the goo.

**Comment by Endermage77** [comment]
The 3D Factory skybox does this.

**Comment by Nikita74RU** [comment]
How is it a duplicate?
