### ISSUE TITLE
Portal 1 pistons and panels missing selection meshes

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#2647]
Picking and moving/editing pistons and angled panels in the Portal 1 theme has been difficult because they seem to be missing selection meshes (and thus default to a cube at the item's origin, which doesn't match the item's geometry):
![chrome_2018-04-15_22-51-51](https://user-images.githubusercontent.com/6296061/38786642-9a5ef1f4-40ff-11e8-9160-ad6379dcaf21.png)
![applicationframehost_2018-04-15_22-53-05](https://user-images.githubusercontent.com/6296061/38786678-c8af830c-40ff-11e8-8bf4-84d5f6954040.png)
![portal2_2019-08-24_17-31-33](https://user-images.githubusercontent.com/19228201/63644109-e66f6e80-c695-11e9-8050-4dcd56ecb0b5.png)

**Comment by LautaroL20** [comment]
Ill probably going to fix this for this month in Blender.

**Comment by Konclan** [comment]
Just use normal piston and angled panel selection meshes. I don't see much use in creating another one by hand or something like that.

**Comment by LautaroL20** [comment]
I will not made them from scratch but ill re-use some of the current meshes and do some arrangements to fit with the silhouette.

**Comment by Nikita74RU** [comment]
Where the hell did you find the pistons? I can't find a piston that retracts, while it's not a platform

**Comment by HugoBDesigner** [comment]
They are regular pistons. You can make them retract if you set the starting point (the ball in the selection) to be above the destination point (the arrow in the selection)

**Comment by Luke18033** [comment]
Has this still not been fixed?

**Comment by LautaroL20** [comment]
Nope i guess.

**Comment by HugoBDesigner** [comment]
It has not, unfortunately

**Comment by Luke18033** [comment]
Can someone please fix this already? This is stupid, these models have been in the game for years and should have been given selection meshes long ago.

**Comment by Luke18033** [comment]
Here's a screenshot of every affected model, just for reference...
![portal2_2019-08-24_17-31-33](https://user-images.githubusercontent.com/19228201/63644109-e66f6e80-c695-11e9-8050-4dcd56ecb0b5.png)
- Extended half panels do have proper selection meshes, which could probably be modified into the 90 degree versions.
- Do we need P1-specific retracted panel models? Half panels don't have them and I never noticed until just now.
- The piston is using the wrong texture, and glass panels don't have a styled model at all.

**Comment by TeamSpen210** [comment]
Basically I need to remake all those models aside from the half panels, since they were made with Propper originally and are fairly terrible.

**Comment by Luke18033** [comment]
P1 panels themselves are all brushes anyway, what's wrong with that?

**Comment by Luke18033** [comment]
Even if the visible models are remade, I don't think they'd be that drastically different, so any selection meshes made now would still probably match. It'd really be nice if someone could add these, they've been missing for far too long.

**Comment by LautaroL20** [comment]
I will. I am going to be posting the final result pictures here once i finish making these meshes thru Blender.

**Comment by LautaroL20** [comment]
I have finished doing the selection meshes for the P1 Deployed Angled Panels, P1 Contracted Angled Panels and the P1 Piston Platform editor models. Here are some screenshots showing the result:

* P1 Deployed Angled Panel Selection Meshes:
![P1 Angled Panel Selection Meshes](https://user-images.githubusercontent.com/12244376/83002853-ecf39380-9fe3-11ea-96ac-b69ae535dea6.jpg)
* P1 Contracted Angled Panel Selection Meshes:
![P1 Contracted Angled Panel Selection Meshes](https://user-images.githubusercontent.com/12244376/83002915-fbda4600-9fe3-11ea-9ab9-ab5649a3d890.jpg)
* P1 Piston Platform Selection Mesh:
![P1 Piston Platform Selection Mesh](https://user-images.githubusercontent.com/12244376/83002955-098fcb80-9fe4-11ea-8c8d-ae5f5f14ff51.jpg)

**Comment by Luke18033** [comment]
Nice! You didn't need to do the ones for the retracted panels though, I was probably going to replace those with copies of the Clean versions anyway, they're not that different.
