### ISSUE TITLE
1980's Sphere's Goo is invisible, Causing "nodraw" (i think thats what it is)

### ISSUE THREAD

**Issue by The-Queen55142** [BEEmod/BEE2-items#2650]
So I'm just making my map right. and i build it and look down. I see that the goop isn't there. so originally i was gonna make a issue of it not being there. But i flew down and died. So the goop is there... But its not visible... Has anyone else experienced this?

**Comment by LautaroL20** [comment]
What the hell is "Goop"?

**Comment by HugoBDesigner** [comment]
Goo. His map leaked and the goo is nodraw.

**Comment by Luke18033** [comment]
Not enough info.
