### ISSUE TITLE
Portal 1 Fizzlers/Old Fizzlers in Clean, and other styles.

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2-items#2653]
Would be very cool to see them as a other item, if Old Aperture or Portal 1 style chosen, these items will dissapear, but if you have Portal 1 style the Old fizzler item will not dissapear, while same with Old aperture,  old fizzler item (separate) removes from the pallete, while P1 version stays. Would be very cool to see Clean style & old fizzler or P1 in it.

**Comment by villager103** [comment]
There is literally no need for this, having Old Aperture fizzlers in Clean or Portal 1 fizzlers in Old Aperture would look ugly. That's why they're styled in the first place.

**Comment by ZombiePwner1** [comment]
I understand that this is a suggestion but we just can't have that in beemod. It would just look out of place.

**Comment by Nikita74RU** [comment]
You're so dumb... Dude, if people want them in the level? They download this mod because they do not understand hammer. YOu just basically told me USe hammer! in other words.

**Comment by King0191** [comment]
This mod isn't about what people WANT. It's about what makes sense and is logical to have in said mod.

**Comment by Endermage77** [comment]
This mod is not a hammer replacment. It is a tool set for expanding on a basic editor.

**Comment by LautaroL20** [comment]
Stop posting useless suggestions that the only thing they do is fill up the "closed issues" section with more of invalid ones...

**Comment by ZombiePwner1** [comment]
@Nikita74RU Do not insult me with what you said there is no need for hate here.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Do not resist, because knowing your personality in Steam, you´re probably willing to giving him the same you got. However, to prevent this to become into a pissing contest you can take my example or the one from "HelloIamapersonthatisalive" where we reply to insults with mature and well argued answers.
