### ISSUE TITLE
Chamberlock is vulnerable to portal placements in a "Mysterious Way"

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2654]
![20180421124852_1](https://user-images.githubusercontent.com/37309250/39086784-b80cb4d8-4565-11e8-9a42-8eb8ac2ff299.jpg)
![20180421124905_1](https://user-images.githubusercontent.com/37309250/39086791-ce4bdb3e-4565-11e8-8c1b-1384cb819ebb.jpg)
The Console picture is to prove i didn't use cheats

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 - Valid Bug Report Confirmed!

**Comment by LautaroL20** [comment]
This is kinda mysterious...

**Comment by King0191** [comment]
I literally found this out when i messed up on a puzzle i was making and i was rage-clicking
