### ISSUE TITLE
Stylevar/Itemvar Play Taste Of Blood near Blue Portal Pedestal and Subject Name Here at Duel Pedestal and at Orange one.

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2-items#2663]

**Comment by LautaroL20** [comment]
Stop posting useless suggestions that the only thing they do is fill up the "closed issues" section with more of invalid ones...

**Comment by Nikita74RU** [comment]
Shut up, this is not invalid. If it is, tell me the reason.

**Comment by ZombiePwner1** [comment]
Here:
https://github.com/BEEmod/BEE2-items/issues/2664#issuecomment-384642104
