### ISSUE TITLE
Compile Error when compiling a chamber in P1 style.

### ISSUE THREAD

**Issue by Nikita74Russian** [BEEmod/BEE2-items#2668]
Suddenly. Compile errors started. I reinstalled bee mod. Did with the way Lautaro told. But error still happens.

**Comment by LautaroL20** [comment]
#PrayForNikita74Russian

**Comment by Nikita74Russian** [comment]
Reason for closing the issue?

**Comment by Nikita74Russian** [comment]
Instead of helping me, this jerk closes the issue and marks it as INVALID

**Comment by LautaroL20** [comment]
#PrayForNikita74Russian
