### ISSUE TITLE
Rotating turret.

### ISSUE THREAD

**Issue by Nikita74Russian** [BEEmod/BEE2-items#2669]
Can rotate 360 degrees, making it deadly so much. If you're silent a standing at back of it, it wont turn. If you ever jump it turns, then starts firing. Can't be destroyed by lasers. Can be disabled/enabled. Turret will be flamed. But will turn into a skeleton turret and will not shoot. Perhaps this is a consequences from laser.
Can't be knocked over.

**Comment by villager103** [comment]
You can do a pretty similar thing by putting 4 turrets pointing outwards, then enclosing them in grating.

**Comment by LautaroL20** [comment]
Unfortunately, turrets and crushers has made the prestige of Beemod to decrease in the P2 community thanks to rookies like you that do not care about doing a logical puzzle, instead they fill up their maps with these items everywhere then to publish them in the Workshop. 

Sadly, the most ironically part of the story is that on these maps, rookies tends to giving "credit" to Beemod by putting things on their description such as "#Made With Beemod" - But most part of good skilled users, almost never gives credit to Beemod on their map´s description which is a pity.

So, what is the point of keep suggesting to making annoying items for Beemod to facilitate rookies to do their job at decreasing the limited prestige of this modding tool in the P2 Workshop Community?
