### ISSUE TITLE
compile error on P1 style 

### ISSUE THREAD

**Issue by Nikita74Russian** [BEEmod/BEE2-items#2670]
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr29 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'fizz_visiblity': '0', 'voice_pack': 'BEE2_GLADOS_P1'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[INFO] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[WARNING] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[INFO] fizzler.read_configs(): Loaded 13 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 7
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 3
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['pack_p1_radio_clean', 'spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3274, misses=350, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'doorcameras': True, 'p1_ported_pgun': True, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/p1/set_portalgun.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding global ents...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] barriers.make_barriers(): Adding Glass floor beams...
[INFO] barriers.make_barriers(): Done!
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/p1_pgun_sounds.txt"
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/p1_physics_sounds.txt"
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/portal_sounds.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_physics.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_player_portal2.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_weapons_portal.txt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_blue.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_blue.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_exponent.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_glass.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_glass.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_normal.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_orange.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_orange.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/door_01.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/door_01.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/walllight_sheet.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/walllight_sheet.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/light_recessedcool_glow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/modular_wall_light.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/detail_concrete_03.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/metaldoor028a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/metaldoor028a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observation_tilefloor001a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observation_tilefloor001a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001b.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001b.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001b_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/overlay_light_gradient.vtf"
[INFO] vbsp.make_packlist(): "models/BEE2/p1_pgun.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_frame_thick.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_left.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_right.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/obs_light.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/security_camera.mdl"
[INFO] vbsp.make_packlist(): "precache_sound:physics/metal/metal_box_scrape_rough_loop1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:physics/metal/metal_box_scrape_smooth_loop1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete2.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete3.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete4.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal2.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal3.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal4.wav"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/change_models.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/set_p1_pgun.nut"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/doorstop1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/garage_stop1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/ambient.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_enter1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_enter2.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_exit1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_exit2.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/wall_move5.wav"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] .run_vbsp():
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

OTA.PRIME.ELS unpaused the game
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!

**Comment by SW50000** [comment]
That looks like the exact same Compile error you posted on issue #2668 and it's closed.
What makes you think you're right most of the time?

**Comment by LautaroL20** [comment]
That console log shows not the problem at all, also, nobody is having issues at compiling a test chamber in P1 Style. I have noting more to say rather than #PrayForNikita74Russian.

**Comment by Nikita74Russian** [comment]
i need to reinstall again?

**Comment by HugoBDesigner** [comment]
It's worth following the following instructions when you get compiling errors:
https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod

**Comment by Nikita74Russian** [comment]
I DID the same things.

**Comment by keifersisawesome** [comment]
I have actually also has compiling issues in the Portal 1 style. This is something that needs fixed i think.

**Comment by LautaroL20** [comment]
@keifersisawesome - Open up the developer console, writte on it `developer 2` press enter then build your puzzle and once u get the build error, paste the the log you got into a new issue.

**Comment by Nikita74Russian** [comment]
@HugoBDesigner Welp, i just reinstalled bee and still, A FUCKING THERE WAS AN A ERROR BUILDING PUZZLE APPEARS

**Comment by Nikita74Russian** [comment]
Instead of helping me, this jerk closes the issue and marks it as INVALID

**Comment by ZombiePwner1** [comment]
@Nikita74Russian Do not swear on the forums and do you not know how to open up the console?

**Comment by LautaroL20** [comment]
Heh, i would not get surprised if this kid would get banned soon once again.

**Comment by King0191** [comment]
If i may cut in here for a second to talk to Nikita... @Nikita74Russian I'm NOT an expert with this stuff. I have plenty of ingame errors and mistakes like this. My advice is to rebuild your puzzle. and remove, simplify, or change shapes, puzzles, and objects. This can help reduce complexity and could possibly help the puzzle work. If none of this works you might have to change styles until you can get Portal 1 Style working.

**Comment by Nikita74Russian** [comment]
I just changed onto Overgrown and it did not change same error still happens

**Comment by TeamSpen210** [comment]
Your compilers are missing. Delete vbsp, vrad, vbsp_original, vrad_original from Portal 2/bin, verify cache, then export again.

**Comment by keifersisawesome** [comment]
This did not help my problem. @TeamSpen210

**Comment by HugoBDesigner** [comment]
Not really, you're still responsible for how you use Beemod. TeamSpen's only responsibility is that Beemod doesn't mess with anything wrong in your computer.

**Comment by Nikita74Russian** [comment]
welp it did, i broke a very important file, i had to reinstall my windows. Because i installed beemod in the wrong place. Guess where? System32.. How dumb was i...

**Comment by Nikita74Russian** [comment]
So he kinda has the half of the fault.

**Comment by HugoBDesigner** [comment]
He's not responsible for you installing Beemod in the wrong folder. That is completely your responsibility. He can't personally supervise every user to make sure none of them is doing something silly.

**Comment by Nikita74Russian** [comment]
No hope, No help, No possibilities to fix a problem that maybe so easy to fix..... I want to use bee mod, i DO NOT wanna learn hammer.

**Comment by keifersisawesome** [comment]
Would you stop? You deleted the file, you chose to use beemod, and you made the mistake. They are not even remotely at fault.

**Comment by keifersisawesome** [comment]
Stop trying to foist the blame onto the people who are only trying to help you.

**Comment by Nikita74Russian** [comment]
oh my f**** god i don't believe i see this it worked i wanna hug you teamspen thanks so much dude you're my life saviour you must be the god

**Comment by Nikita74Russian** [comment]
god exists

**Comment by Nikita74Russian** [comment]
it compiles even faster that before! You can close all of my duplicates. Why didn't i knew that my compilers broke...

**Comment by Nikita74Russian** [comment]
I guess i need to figure out what caused to compilers to break..

**Comment by Nikita74Russian** [comment]
Funny to see, it gets more comments than my greatest idea with Incinerator skybox that is (maybe) incoming in pre-release 32. What a bad difference.
