### ISSUE TITLE
Standing Flip Panel

### ISSUE THREAD

**Issue by Flametusk** [BEEmod/BEE2-items#2674]
Exactly as it sounds. It's a flip panel that stands, instead of being recessed inside the voxel. It would be in the middle of the voxel, and be able  to be rotated similar to an angled panel. It could still take up space inside the voxel. As long as you can always shoot the portal surface, flipping it just flips the portal surface 180 degrees. I... don't really know what else needs to be said, to be honest.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
this would work great in conjunction with the autoportal

**Comment by villager103** [comment]
It should have an 8-way adjustment handle, like light strips, so you can position it on the edge of blocks.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
What about clipping? What if you place two flip panels right next to eachother? It should just have a rotation handle

**Comment by Flametusk** [comment]
Not just flip panels would clip with each other, but anything if it was on the edge of the vocal. It needs to be in the middle to not collide.

**Comment by LautaroL20** [comment]
@villager103 - No, it should not. An item like this must always stay in the middle of a boxel, otherwise when rotating it would cross the boxel limit in a mysterious way. If this should have a rotating handle, it must be `handle_4_directions` which would not make the item go crazy.

**Comment by Konclan** [comment]
#3889
