### ISSUE TITLE
HELP REQUIRED!!

### ISSUE THREAD

**Issue by Nikita74Russian** [BEEmod/BEE2-items#2677]
I want to ask, how even does the Conductive Plate work, what it does. And the purpose for it?
And how to use?

**Comment by King0191** [comment]
Not particularly... Here let me explain this like this

CP = Conductive Plate
B= Button
D= Door

CP (No Cube) ---> D (Closed)
CP (Cube) ----> D (open)
B (not pressed) ---> CP (Cube)---> D (closed)
B (Activated) -----> CP (No cube) ----> D (closed)
B (Activated) -----> CP (Cube is there.) ----> D (open)

**Comment by Nikita74Russian** [comment]
A cube and ball button that accepts inputs to activate, and outputs to activate the thing that recieves the output.

**Comment by Nikita74Russian** [comment]
Thanks for providing me a good tip.
