### ISSUE TITLE
BTS Co-op Player Dropper & Both Checkpoints strange error?

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2679]
While i cannot find the picture (will update this when i find it) The get-together Checkpoint Levers give an error for the lever. 

However the Exit is the weirdest of all...
![20180501213451_1](https://user-images.githubusercontent.com/37309250/39501293-0b0e1fda-4d88-11e8-957d-5f56ee16767d.jpg)
![20180501213549_1](https://user-images.githubusercontent.com/37309250/39501294-0d0889ce-4d88-11e8-8d61-a5306d50443a.jpg)
![20180501214742_1](https://user-images.githubusercontent.com/37309250/39501538-872f25a4-4d89-11e8-9f00-7a69825f82de.jpg)
![20180501214810_1](https://user-images.githubusercontent.com/37309250/39501539-873ecc3e-4d89-11e8-8499-a156965f2cd4.jpg)
![20180501214827_1](https://user-images.githubusercontent.com/37309250/39501540-874cad40-4d89-11e8-8a26-9d678647fba1.jpg)

![20180501214810_1](https://user-images.githubusercontent.com/37309250/39501543-89205bf8-4d89-11e8-9ac1-ebc2c1602da8.jpg)
![20180501214827_1](https://user-images.githubusercontent.com/37309250/39501544-89360156-4d89-11e8-922b-342737b31a42.jpg)
![20180501214742_1](https://user-images.githubusercontent.com/37309250/39501545-89432be2-4d89-11e8-967d-9ecc71accd7e.jpg)

![20180501214827_1](https://user-images.githubusercontent.com/37309250/39501546-8aed542c-4d89-11e8-870b-52fb59959530.jpg)
![20180501214742_1](https://user-images.githubusercontent.com/37309250/39501547-8affdcf0-4d89-11e8-8a84-fd91fd9974ce.jpg)
![20180501214810_1](https://user-images.githubusercontent.com/37309250/39501548-8b0eea7e-4d89-11e8-8b4c-ab8d1ab31436.jpg)

**NOTE:** **This exit error doesn't exist when these items aren't present**

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.

**Comment by ZombiePwner1** [comment]
Also duplicate of this https://github.com/BEEmod/BEE2-items/issues/694
