### ISSUE TITLE
Portal 1 Style Compile Error

### ISSUE THREAD

**Issue by keifersisawesome** [BEEmod/BEE2-items#2681]
Here is the error I get. @LautaroL20 

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr29 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'fizz_visiblity': '0', 'voice_pack': 'BEE2_GLADOS_P1'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[INFO] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[WARNING] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[INFO] fizzler.read_configs(): Loaded 13 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 2
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (14 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['pack_p1_radio_clean', 'spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3508, misses=350, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'doorcameras': True, 'p1_ported_pgun': True, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/p1/set_portalgun.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding global ents...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[WARNING] template.retexture_template(): Realign face in template "bee2_static_pan_angled_p1" (209 in final) is not on grid!
[INFO] barriers.make_barriers(): Adding Glass floor beams...
[INFO] barriers.make_barriers(): Done!
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/p1_pgun_sounds.txt"
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/p1_physics_sounds.txt"
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/portal_sounds.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_physics.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_player_portal2.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_weapons_portal.txt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_blue.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_blue.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_exponent.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_glass.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_glass.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_normal.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_orange.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_orange.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/door_01.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/door_01.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/metalwall_bts_6.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/plasticwall_1.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/plasticwall_4.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/walllight_sheet.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/walllight_sheet.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/light_recessedcool_glow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall_bts_006a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/modular_wall_light.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/detail_concrete_03.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/metaldoor028a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/metaldoor028a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observation_tilefloor001a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observation_tilefloor001a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001b.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001b.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001b_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/overlay_light_gradient.vtf"
[INFO] vbsp.make_packlist(): "models/BEE2/p1_pgun.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_frame_thick.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_left.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_right.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/obs_light.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/panel_cylinder.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/security_camera.mdl"
[INFO] vbsp.make_packlist(): "precache_sound:physics/metal/metal_box_scrape_rough_loop1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:physics/metal/metal_box_scrape_smooth_loop1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete2.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete3.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete4.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal2.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal3.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal4.wav"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/change_models.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/set_p1_pgun.nut"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/doorstop1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/garage_stop1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/ambient.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_enter1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_enter2.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_exit1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_exit2.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/wall_move5.wav"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Mar  1 2018)
 | 8 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | fixing up env_cubemap materials on brush sides...
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | Processing areas...done (0)
 | Building Faces...done (0)
 | Chop Details...done (0)
 | Find Visible Detail Sides...
 | Merged 170 detail faces...done (0)
 | Merging details...done (0)
 | FixTjuncs...
 | PruneNodes...
 | WriteBSP...
 | done (0)
 | writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.prt...Building visibility clusters...
 | done (0)
 | Finding displacement neighbors...
 | Finding lightmap sample positions...
 | Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
 | material "decals/overlay_light_gradient" not found.
 | Building Physics collision data...
 | done (1) (341615 bytes)
 | Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
 | Compacting texture/material tables...
 | Reduced 1517 texinfos to 383
 | Reduced 62 texdatas to 50 (1905 bytes to 1585)
 | Writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.bsp
 | 
 | nummapplanes:     (  3732 / 65536 )
 | nummapbrushes:    (   951 /  8192 )
 | nummapbrushsides: (  7640 / 65536 )
 | num_map_overlays: (     7 /   512 )
 | nummodels:        (    29 /  1024 )
 | num_entities:     (   177 / 16384 )
 | 
 | 1 second elapsed
 | CDynamicFunction: Loading library 'Kernel32.dll' (74790000)
 | CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 774B4140
 | CDynamicFunction: Closing library 'Kernel32.dll' (74790000)
 |_

[INFO] vbsp.run_vbsp(): VBSP Done!
[INFO] vbsp.process_vbsp_log(): Retrieved counts: {'brush': ('951', '8192'), 'overlay': ('7', '512'), 'entity': ('177', '16384')}
[INFO] BEE2_config.save(): Saving changes in config "C:\Program Files (x86)\BEEmod 2.4\config/compile.cfg"!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3524, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3268, in run_vbsp
  File "F:\Git\BEE2.4\src\vbsp.py", line 3329, in process_vbsp_log
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 54, in save
  File "F:\Git\srctools\srctools\__init__.py", line 273, in __enter__
  File "F:\Git\srctools\srctools\__init__.py", line 268, in make_tempfile
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\BEEmod 2.4\\config/compile.cfg'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3524, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3268, in run_vbsp
  File "F:\Git\BEE2.4\src\vbsp.py", line 3329, in process_vbsp_log
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 54, in save
  File "F:\Git\srctools\srctools\__init__.py", line 273, in __enter__
  File "F:\Git\srctools\srctools\__init__.py", line 268, in make_tempfile
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\BEEmod 2.4\\config/compile.cfg'

**Comment by LautaroL20** [comment]
This console log seems useful, i can see a failure at `PermissionError: [Errno 13] Permission denied: 'C:\Program Files (x86)\BEEmod 2.4\config/compile.cfg'`

@TeamSpen210 - ¿What could be causing this?

**Comment by Nikita74Russian** [comment]
i have same problem but even when i compile a empty room it happens

**Comment by keifersisawesome** [comment]
@TeamSpen210 a similar issue seems to have been fixed for @Nikita84Russian, however when I tried the fix you told him my problem did not go away, and I am still unable to even compile an empty room.

**Comment by TeamSpen210** [comment]
Delete the config it is mentioning, and close BEE before compiling. Maybe something else is touching it?
