### ISSUE TITLE
.bsp error?

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2683]
So. I've done everything. I've deleted the .bsp file. like i was once told a while ago with pr28. and i've even gotten rid of and reinstalled BEEMod. and No matter WHAT i do. It gives me a .BSP error. just to PLAYTEST the map.

**Comment by King0191** [comment]
VRAD failed.

[INFO] vrad.main(): BEE2 VRAD hook started!
[INFO] vrad.main(): Map path is C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[INFO] vrad.load_config(): Loading Settings...
[INFO] vrad.load_config(): Config Loaded!
[INFO] vrad.main(): Final status: is_peti=True, edit_args=True
[INFO] vrad.main(): Reading BSP
[INFO] vrad.main(): Done!
[INFO] vrad.gen_sound_manifest(): Written new soundscripts_manifest..
[INFO] vrad.pack_content(): Files to pack:
[INFO] vrad.pack_content():  # "materials/bee2/fizz/fizz_side.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/fizz_sides/side_color_06141a.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/fizz_sides/side_color_ff0000.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/josepezdj/signage_wasted/base.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/cust_fizz/effect.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/cust_fizz/fizzler_dirty_danger.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/cust_fizz/fizzler_dirty_danger.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/triple_wallpipe_nocull.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_overgrown/catwalk_rusty.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_overgrown/triple_wallpipe_nocull_rusty.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_overgrown/triple_wallpipe_rusty.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_overgrown/truss_rusty.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/overgrown/broken_indicator.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/overgrown/broken_indicator_corner.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/overgrown/screens/elevator_video_overlay2.vmt" as "materials/bee2/overgrown/lightboard_overlay.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/overgrown/tile/white_floor_tile005a.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/overgrown/tile/white_floor_tile005a.vtf"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_a_overgrown.vmt"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_a_overgrown.vtf"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_a_overgrown_off.vmt"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_a_overgrown_off.vtf"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_aoff.vmt"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_aoff.vtf"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_b_overgrown.vmt"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_b_overgrown.vtf"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_b_overgrown_off.vmt"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_boff.vmt"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_c_overgrown.vmt"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_c_overgrown.vtf"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_c_overgrown_off.vmt"
[INFO] vrad.pack_content():  # "materials/models/elevator/elevator_main_coff.vmt"
[INFO] vrad.pack_content():  # "models/bee2/catwalk/overgrown/hanging_stair_128.mdl"
[INFO] vrad.pack_content():  # "models/bee2/catwalk/overgrown/hanging_walkway_32b.mdl"
[INFO] vrad.pack_content():  # "models/bee2/catwalk/overgrown/hanging_walkway_end_cap.mdl"
[INFO] vrad.pack_content():  # "models/bee2/catwalk/overgrown/hanging_walkway_support_a.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_ingame/cust_fizz.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_ingame/cust_fizz_static.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_overgrown/truss_1024.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_overgrown/truss_512.mdl"
[INFO] vrad.pack_content():  # "models/bee2/triple_wallpipe/entrance_a.mdl"
[INFO] vrad.pack_content():  # "models/bee2/triple_wallpipe/straight_a.mdl"
[INFO] vrad.pack_content():  # "models/bee2/triple_wallpipe/straight_c.mdl"
[INFO] vrad.pack_content():  # "models/bee2/triple_wallpipe/straight_d.mdl"
[INFO] vrad.pack_content():  # "models/elevator/elevator_b_skins.mdl"
[INFO] vrad.pack_content():  # "models/props_bts/vactube_glass_bothsides/vactube_128_straight_glass.mdl"
[INFO] vrad.pack_content():  # "models/props_bts/vactube_glass_bothsides/vactube_90deg_01_glass.mdl"
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/video_splitter_specific.nut"
[INFO] vrad.pack_content():  # "sound/bee2/music/sp_a1_intro5_b1_looped.wav"
[INFO] vrad.pack_content():  # "sound/music/sp_a3_bomb_flings_z2.wav"
[INFO] vrad.pack_content():  # "sound/music/sp_a3_bomb_flings_z2b.wav"
[INFO] vrad.pack_content():  # "sound/music/sp_a3_bomb_flings_z2c.wav"
[INFO] vrad.pack_content(): Potential additional files:
[INFO] vrad.pack_content(): Injected files:
[INFO] vrad.pack_content():  # "scripts/game_sounds_manifest.txt"
[INFO] vrad.pack_content():  # "scripts/BEE2_generated_music.txt"
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/auto_run.nut"
[INFO] vrad.pack_content(): Packing Files!
[WARNING] vrad.pack_file(): "bee2/sound/music/sp_a3_bomb_flings_z2c.wav" not found! (May be OK if not custom)
[WARNING] vrad.pack_file(): "bee2/sound/music/sp_a3_bomb_flings_z2b.wav" not found! (May be OK if not custom)
[WARNING] vrad.pack_file(): "bee2/sound/music/sp_a3_bomb_flings_z2.wav" not found! (May be OK if not custom)
[INFO] vrad.pack_content(): Injecting "scripts/game_sounds_manifest.txt" into packfile.
[INFO] vrad.pack_content(): Injecting "scripts/BEE2_generated_music.txt" into packfile.
[INFO] vrad.pack_content(): Injecting "scripts/vscripts/bee2/auto_run.nut" into packfile.
[INFO] vrad.pack_content(): Packing complete!
[INFO] vrad.mod_screenshots(): Using automatic screenshot!
[INFO] vrad.mod_screenshots(): No Auto Screenshot found!
[INFO] vrad.mod_screenshots(): Cleaning up screenshots...
[INFO] vrad.mod_screenshots(): Done!
[INFO] vrad.mod_screenshots(): Using PeTI screenshot!
[INFO] vrad.mod_screenshots(): Making "..\portal2\puzzles\76561198209103051\untitled.jpg" replaceable...
[INFO] vrad.main(): Forcing Cheap Lighting!
[INFO] vrad.run_vrad(): Calling original VRAD...
[INFO] vrad.run_vrad(): "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vrad_original.exe" -bounce 2 -noextra -hdr -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp"
Valve Software - vrad.exe SSE (Mar  1 2018)

      Valve Radiosity Simulator     
8 threads
[Reading texlights from 'lights.rad']
[59 texlights parsed from 'lights.rad']

Loading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
Setting up ray-trace acceleration structure... Done (2.25 seconds)
2898 faces
1 degenerate faces
227840 square feet [32809096.00 square inches]
0 Displacements
0 Square Feet [0.00 Square Inches]
2897 patches before subdivision
22065 patches after subdivision
76 direct lights
BuildFacelights:     0...1...2...3...4...5...6...7...8...9...10 (0)
BuildVisLeafs:       0...1...2...3...4...5...6...7...8...9...10 (2)
transfers 1198507, max 366
transfer lists:   9.1 megs
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #1 added RGB(46334, 43572, 32411)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #2 added RGB(16934, 15659, 10944)
Build Patch/Sample Hash Table(s).....Done<0.0065 sec>
FinalLightFace:      0...1...2...3...4...5...6...7...8...9...10 (2)
FinalLightFace Done
16 of 16 (100% of) surface lights went in leaf ambient cubes.
ThreadComputeLeafAmbient: 0...1...2...3...4...5...6...7...8...9...10 (2)
Writing leaf ambient...done
Ready to Finish

Object names       Objects/Maxobjs  Memory / Maxmem  Fullness 
------------       ---------------  ---------------  -------- 
models                  76/1024         3648/49152    ( 7.4%) 
brushes               1864/8192        22368/98304    (22.8%) 
brushsides           16302/65536      130416/524288   (24.9%) 
planes               11392/65536      227840/1310720  (17.4%) 
vertexes              5855/65536       70260/786432   ( 8.9%) 
nodes                 1812/65536       57984/2097152  ( 2.8%) 
texinfos              1038/12288       74736/884736   ( 8.4%) 
texdata                 71/2048         2272/65536    ( 3.5%) 
dispinfos                0/0               0/0        ( 0.0%) 
disp_verts               0/0               0/0        ( 0.0%) 
disp_tris                0/0               0/0        ( 0.0%) 
disp_multiblend          0/0               0/0        ( 0.0%) 
disp_lmsamples           0/0               0/0        ( 0.0%) 
faces                 2898/65536      162288/3670016  ( 4.4%) 
hdr faces             2898/65536      162288/3670016  ( 4.4%) 
origfaces             2467/65536      138152/3670016  ( 3.8%) 
facebrushes            362/0             724/0        ( 0.0%) 
facebrushlists        2898/0           11592/0        ( 0.0%) 
leaves                1889/65536       60448/2097152  ( 2.9%) 
leaffaces             3531/65536        7062/131072   ( 5.4%) 
leafbrushes           3260/65536        6520/131072   ( 5.0%) 
areas                   13/256           104/2048     ( 5.1%) 
surfedges            23315/512000      93260/2048000  ( 4.6%) 
edges                14338/256000      57352/1024000  ( 5.6%) 
LDR worldlights          0/8192            0/819200   ( 0.0%) 
HDR worldlights         76/8192         7600/819200   ( 0.9%) 
leafwaterdata            1/32768          12/393216   ( 0.0%) 
waterstrips            321/32768        3210/327680   ( 1.0%) 
waterverts               0/65536           0/786432   ( 0.0%) 
waterindices          5712/65536       11424/131072   ( 8.7%) 
cubemapsamples           3/1024           48/16384    ( 0.3%) 
overlays                41/512         14432/180224   ( 8.0%) 
LDR lightdata         [variable]           0/0        ( 0.0%) 
HDR lightdata         [variable]     2005124/0        ( 0.0%) 
visdata               [variable]       30403/16777216 ( 0.2%) 
entdata               [variable]      123659/393216   (31.4%) 
LDR ambient table     1889/65536        7556/262144   ( 2.9%) 
HDR ambient table     1889/65536        7556/262144   ( 2.9%) 
LDR leaf ambient      1889/65536       52892/1835008  ( 2.9%) 
HDR leaf ambient      3631/65536      101668/1835008  ( 5.5%) 
occluders                0/0               0/0        ( 0.0%) 
occluder polygons        0/0               0/0        ( 0.0%) 
occluder vert ind        0/0               0/0        ( 0.0%) 
detail props          [variable]           1/12       ( 8.3%) 
static props          [variable]           1/40220    ( 0.0%) 
pakfile               [variable]    26817768/0        ( 0.0%) 
physics               [variable]      714913/4194304  (17.0%) 
physics terrain       [variable]           2/1048576  ( 0.0%) 

Level flags = 0

Total triangle count: 7588
Writing c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
Error opening c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp! (Check for write enable)

[WARNING] vrad.run_vrad(): VRAD failed! (1)


[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198209103051\autosave.p2c
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
King unpaused the game
Error: Operator stop_entry, unknown sound operator attribute input_start
Unknown command "cl_puzzlemaker_start_previewing"
=======================Trying to GivePlayerPortalgun
=======================Trying to UpgradePlayerPortalgun
*************************************************************************************************
*** ERROR: logic_relay InstanceAuto1-global_ents-environment_testchamber has been triggered but is awaiting refire. OUTPUTS WILL NOT BE FIRED!!!
*************************************************************************************************

An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!

**Comment by Nikita74Russian** [comment]
Looks like you are using overgrown style, since i can see "wasted" and "overgrown"

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
