### ISSUE TITLE
Improve Palette Icons #3 - Implement a little of aditional brightness in the Sendificator icon

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2688]

**Comment by Flash4433** [comment]
I added about 15 of brightness and made the background the same color again. Is it good enough or does it need less brightness?

![sendtor](https://user-images.githubusercontent.com/38331230/75116991-959cfa80-5665-11ea-8b07-07e966d31f61.png)

**Comment by LautaroL20** [comment]
Nice, i will commit it among with your combined cube icon as soon as i can. By the way, do you think that remaking the Single-Player Grates icons would be hard to do?

**Comment by Flash4433** [comment]
Hum, you're talking about these right?
![image](https://user-images.githubusercontent.com/38331230/75117743-19f27c00-566c-11ea-84d2-d1727e430d9f.png)
I think the angle of the single floor ones is about right. The wall grate isn't that right, but it works. The grouped one is way too far from the normal angle. I think just removing the background for the floor ones is enough, but for the others, it probably needs a new reference photo. Yeah, I'm willing to do them.

**Comment by LautaroL20** [comment]
Yes, those are the Single-Player Grates. I had the source images of those icons in another hard device and i will try recovering them for you.

**Comment by Flash4433** [comment]
Also, @SCIENTIST2004 managed to make a better version of the single player grate's palette icons, in #2470 .

**Comment by LautaroL20** [comment]
I´ve commited your improved Sendificator icon. Also, seeing that you got better image versions of the SP Grates, i will no longer need to recover my own ones since i am totally sure yours will be much better :)
