### ISSUE TITLE
New Style Idea

### ISSUE THREAD

**Issue by ConnorT05** [BEEmod/BEE2-items#2689]
In the descriptions for the songs: Comity=T+T, Rattman, I saw a dear, I'm different, and Love as Construct it mentions the reconstruction tests. I think that the reconstruction tests should have there own style.

**Comment by ZombiePwner1** [comment]
@ConnorT05 Reconstructing style will be added into the mod in the future but for now there are no plans.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Hey wheels, do not forget to apply the "invalid" label after closing an issue...
