### ISSUE TITLE
Aperture Tag "Gas" Things 

### ISSUE THREAD

**Issue by Nikita74Russian** [BEEmod/BEE2-items#2692]
![1](https://user-images.githubusercontent.com/38806976/39710105-4b153e72-5235-11e8-9f1e-5a2199bf1999.jpg)
Look at the bottom, you can see "freezing gas" thing. 

Another "gas" thingy 
![2](https://user-images.githubusercontent.com/38806976/39710157-6c06b516-5235-11e8-8507-b8cf18d32a03.jpg)

**Comment by LautaroL20** [comment]
Beemod is not an exclusive tool for "Aperture Tag", so all existing bee´s items are shared throughout the P2 Puzzlemaker and all supported mods (PS:Mel, AT, and probably TWTM). This means that your suggestion will not be consistent with the rest of the games at all.

**Comment by HugoBDesigner** [comment]
Actually, isn't the paint activation field Tag-exclusive?

**Comment by LautaroL20** [comment]
I thought that bee´s item were usable in P2 too, clearly i did not try it in a while. If that is Tag-exclusive, even for people who purchased the mod, then its a big error in my opinion...

**Comment by TeamSpen210** [comment]
It's exclusive, in that it does nothing in normal Portal 2. Same way many fizzlers behave identically. This gas would be part of a specific skybox style, if I ever bother making it for Tag.

**Comment by Nikita74Russian** [comment]
This should be a good thing to do. As a skybox.
