### ISSUE TITLE
Compile Error, Requiring help.

### ISSUE THREAD

**Issue by Nikita74Russian** [BEEmod/BEE2-items#2693]
Redownloading all lightmaps
] sv_cheats 1

] developer 2
OTA.PRIME.ELS unpaused the game
] developer 2
OTA.PRIME.ELS unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 167 (ms)

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr29 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'fizz_visiblity': '0'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[INFO] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[WARNING] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[INFO] fizzler.read_configs(): Loaded 13 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.anti_fizz_bump(): Adding Portal Bumpers to fizzlers...
[INFO] vbsp.anti_fizz_bump(): Done!
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['pack_p1_radio_clean', 'spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3280, misses=350, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'doorcameras': True, 'p1_ported_pgun': True, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': True, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/p1/set_portalgun.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding global ents...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] barriers.make_barriers(): Adding Glass floor beams...
[INFO] barriers.make_barriers(): Done!
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/p1_pgun_sounds.txt"
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/p1_physics_sounds.txt"
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/portal_sounds.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_physics.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_player_portal2.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_weapons_portal.txt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_blue.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_blue.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_exponent.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_glass.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_glass.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_normal.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_orange.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_orange.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/door_01.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/door_01.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/walllight_sheet.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/walllight_sheet.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/light_recessedcool_glow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/modular_wall_light.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/detail_concrete_03.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/metaldoor028a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/metaldoor028a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observation_tilefloor001a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observation_tilefloor001a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001b.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001b.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001b_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/overlay_light_gradient.vtf"
[INFO] vbsp.make_packlist(): "models/BEE2/p1_pgun.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_frame_thick.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_left.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_right.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/obs_light.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/security_camera.mdl"
[INFO] vbsp.make_packlist(): "precache_sound:physics/metal/metal_box_scrape_rough_loop1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:physics/metal/metal_box_scrape_smooth_loop1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete2.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete3.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete4.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal2.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal3.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal4.wav"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/change_models.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/set_p1_pgun.nut"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/doorstop1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/garage_stop1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/ambient.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_enter1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_enter2.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_exit1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_exit2.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/wall_move5.wav"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): 
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

OTA.PRIME.ELS unpaused the game
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
Since i do not know what is causing this error, your duty is to figure out.

**Comment by Nikita74Russian** [comment]
as you can see i entered developer 2, but guys. Stop bugging bee mod, i love it and stupid bugs ruin it

**Comment by Nikita74Russian** [comment]
i do not want to downgrade to pre28

**Comment by Nikita74Russian** [comment]
i am not waiting 50 centuries for 30th pre release cmon make it faster we need bug fixes god help us

**Comment by Nikita74Russian** [comment]
i really love beemod stop ruining it #FixBeeMod!!!

**Comment by HugoBDesigner** [comment]
The only thing that needs to stop is your spam. Nobody's "bugging" Beemod, do you even understand what a bug is and how it happens? And if you want the next pre-release faster, go on and make it come out faster. Beemod is a community-driven project, so you (the community) can help make it better - while currently you're making it worse.

**Comment by Nikita74Russian** [comment]
how i am doing it i just want it to be better #FixBeeMod!!!

**Comment by HugoBDesigner** [comment]
I literally just said spamming. Also would help if you tried to avoid swearing at others, posting on every other issue, and bypassing bans by creating alt accounts. The time it takes to clean your mess could have been used making Beemod better, ironically.

**Comment by Nikita74Russian** [comment]
i don't want to learn hammer i want to use bee mod but it is bugged as hell for me, only thing that is sad to know that only i have this issue and i currently can't figure out what is causing it.

**Comment by Nikita74Russian** [comment]
so i am supposed to stay permabanned? No way

**Comment by Nikita74Russian** [comment]
Just fixed. Case closed. My compilers was missing, just delete all VBSP VRAD files you see, verify the cache of game, then re-export in BeeMod, Happy mapmaking!

**Comment by HugoBDesigner** [comment]
Funny that this is exactly what you've been told to do, only you decided to spam an awful lot before actually trying it. Congratulations, kid!

**Comment by Nikita74Russian** [comment]
My fault i did not check the duplicates...

**Comment by Nikita74Russian** [comment]
I just made a puzzle. Incoming in workshop. Link coming soon here.

**Comment by Nikita74Russian** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1381172877
Try the whole series. Only 4 Chapters. I have lots of work to develop.

**Comment by TeamSpen210** [comment]
This is not a place for advertising maps.
