### ISSUE TITLE
Style Variations: Ice Blue Clean and Fire Orange Clean

### ISSUE THREAD

**Issue by peefTube** [BEEmod/BEE2-items#2695]
Alternate versions of the Clean style stylized to replace several textures with blue/orange versions, like black walls and goo, perhaps alt. laser textures if the devs feel like it.

Just a suggestion, not expecting this to get implemented.

**Comment by Nikita74Russian** [comment]
So Winter and Hottest Summer Aperture Styles? I like it.

**Comment by Nikita74Russian** [comment]
by the way, it should have a bit sand cripple on it.

**Comment by Nikita74Russian** [comment]
as Fire Orange Clean, it would be renamed into Aperture Artifical Summer Conditions. and Snow textures for Aperture Artifical Winter Condition style. Ice = AAWC Style, Hot Water/Lava = AASC Style.

**Comment by Nikita74Russian** [comment]
I think its a better idea to do.

**Comment by Nikita74Russian** [comment]
I am agree with it.

**Comment by Luke18033** [comment]
This probably isn't going to be implemented.
