### ISSUE TITLE
Suggestion: Style unstationary scaffold for BTS.

### ISSUE THREAD

**Issue by Nikita74Russian** [BEEmod/BEE2-items#2698]
Should be a platform ridden on rails, touching the rails would kill you. Just like in the Alpha Version of Portal, in 2005. 
![maxresdefault](https://user-images.githubusercontent.com/38806976/39815831-b94d6418-53b2-11e8-9266-f9e910de9d44.jpg) Look down a bit, you can see rail platform with electricity beams, they would kill you if you stand on it.

**Comment by TeamSpen210** [comment]
Styles don't change functionality.

**Comment by Konclan** [comment]
It would also be extremely difficult to do physical rails in a map compared to 2 points

**Comment by Nikita74Russian** [comment]
Then you can do 2 beams connected with each other and they don't kill you.
