### ISSUE TITLE
Make Piston Platforms use the same textures as the walls do

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2700]
That's just plain ugly.
![620_20180510160242_1](https://user-images.githubusercontent.com/28140988/39872075-7543b4f8-546f-11e8-88d1-ad523080e440.png)

**Comment by Konclan** [comment]
its nice that its distinctive so you know what can move like how stairs work

**Comment by Nikita74Russian** [comment]
@LautaroL20, when applying any of black tags, close the issue.

**Comment by TeamSpen210** [comment]
That's the same texture, it's due to lots of complex things with how lighting works.
