### ISSUE TITLE
Catwalks w/ Gel Itemvar?

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2706]
During the second BTS section. (Escaping "Wheatley Laboratories") a Gel pipe falls and the gel stays on a part of the catwalk. Could it be possible to make an Itemvar allowing you to put gel on Catwalks? This would make for interesting ways of traversing the map.

**Comment by ZombiePwner1** [comment]
@King0191 The trick they did during that sequence was that they put a brush on the catwalk so the gel stays since models can't be coated in gel.

**Comment by King0191** [comment]
Oh. I see. Well I think that would just be nice. Y'know?

**Comment by ZombiePwner1** [comment]
@King0191 It should be possible if @TeamSpen210 knows how to generate it.

**Comment by King0191** [comment]
Awesome

**Comment by Konclan** [comment]
Something like this would be easy to accomplish probably but I don’t really see the application in a normal test.

**Comment by ZombiePwner1** [comment]
@Konclan I do understand your point and this really wouldn't go for many styles except BTS.

**Comment by TeamSpen210** [comment]
I don't really think this is needed, it only appears once in the campaign for story reasons. You could just use a regular block. And you'll need to do that anyway, since you can't make catwalks ending in thin air.
