### ISSUE TITLE
Stasis Field

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2707]
An item of similar design to things such as the Positronic Energy Orb, the stasis field will suspend any items placed inside it (e.g. turrets, cubes, futbols) in zero-gravity as well as reduce all general momentum to zero.

This would be most handy for maps using Futbols as it would be a place where one can put a futbol down without having to insert it into a socket.

**Comment by ZombiePwner1** [comment]
@Endermage77 I don't think futbols can actually be placed on the ground without editing the source code for it @TeamSpen210 Might know.

**Comment by McReenZRo** [comment]
How EXACTLY would it work?

**Comment by Endermage77** [comment]
The stasis field looks similar to a Positronic Orb in design as it is a claw on an arm extended around an energy field.

If you drop or throw objects into that field, like turrets or cubes or futbols, they get locked in a hover state, not unlike what would happen with an excursion funnel if it were set to zero speed. Grabbing items out of it would be just fine, though, and the field would be disableable so you can, perhaps, block a futbol socket with a few stasis fields and you have to turn them off to be able to throw the futbol over there.

But mainly, its purpose is to have stuff held within itself safely without breaking (i.e. futbols) and then have it easily retrievable by grabbing it again.

**Comment by CTB33391** [comment]
Just yes

**Comment by Konclan** [comment]
UCP
