### ISSUE TITLE
Portal 1 Flamethrower Holes

### ISSUE THREAD

**Issue by Nikita74Russian** [BEEmod/BEE2-items#2709]
Why not!
![20180521220323_1](https://user-images.githubusercontent.com/38806976/40319814-e6a3af64-5d42-11e8-89fd-8bedfc0ea912.jpg)
I currently used Orange Hole to simulate the model
It's a Hole with a hatch, opens when input(s) get active. And releases stream of fire permanently until deactivated. (If set timer to infinite.) and it also can periodically turn on or off. Start Enabled helps this feature be real.
We should have FIRE HAZARD!! Signage near it or perhaps create a custom one
Start Reversed to make signage appear.
It's a mini-flamethrower from 60s in other styles. It can be placed on ANY surface.

**Comment by peefTube** [comment]
This would really only be useful if you were recreating Chamber 19 tbh, and even then, it would be preferable to actually have a placeable fire pit
Fire pits could be useful as test hazards, though, as well as for decorations
However, once you start getting into items like these it becomes more useful to learn Hammer and map utilizing that; and honestly, maps will tend to look better when made in Hammer

**Comment by Nikita74Russian** [comment]
It's a Hole with a hatch, opens when input(s) get active. And releases stream of fire permanently until deactivated. (If set timer to infinite.) and it also can periodically turn on or off. Start Enabled helps this feature be real.

**Comment by Nikita74Russian** [comment]
We should have FIRE HAZARD!! Signage near it or perhaps create a custom one

**Comment by Nikita74Russian** [comment]
Start Reversed to make signage appear.

**Comment by King0191** [comment]
I believe Firepits are already planned and meant to work to work in ALL styles. Besides only Portal 1 is just bad design

**Comment by Nikita74Russian** [comment]
This is not planned to be used only Portal 1 style, perhaps how about a hole with a ignited gasoline spraying out in Old Aperture?

**Comment by King0191** [comment]
Why a hole? That's the most random thing i've ever heard. We would want it to work on walls, roofs, etc

**Comment by Nikita74Russian** [comment]
and a neurotoxin vent embended into a wall, with a hatch in Clean Style.

**Comment by Nikita74Russian** [comment]
It's a mini-flamtethrower from 60s in other styles. It can be placed on ANY surface.

**Comment by King0191** [comment]
You're contradicting yourself, first a hole. then Neurotoxin vent, then Mini-flamethrower. What do you want? Make up your mind or else this idea might as well be invalid

**Comment by Nikita74Russian** [comment]
It's a hole, it has a vent inside of it. it sprays stream of fire when active. (In clean style) In Portal 1 Style, its a hole, closed by a hatch. It has a fire-hazard signage near it, so players aren't confused. (BTS) same as clean style, but retextured to fit the aesthetic. (Old Aperture) Mini-flamethrower like holes with a hatch. Functions above. Has fire-sprayers inside of it. like 60s crusher. (Overgrown) A hole with hatch that glitches and tries to close-open and spprays a little little spray of fire that damages a bit. If deactivated, hatch stops glitching, but starts trying to close. Then it shuts and doesn't move until activated again. Vents are still used. Fire-stream fizzles every object that emancipation grid can emancipate.

**Comment by TeamSpen210** [comment]
No.

**Comment by Nikita74Russian** [comment]
Why not?

**Comment by Nikita74Russian** [comment]
How about you tell me why no? That's jerky and without a reason.

**Comment by Nikita74Russian** [comment]
https://github.com/BEEmod/BEE2-items/issues/2708

**Comment by ZombiePwner1** [comment]
@Nikita74Russian Stop being disrespectful to admins.

**Comment by TeamSpen210** [comment]
I have no clue why this is useful, it'd effectively be a minuscule death fizzler or crusher, which can easily be bypassed. It's not really relevant to any style, has never appeared in maps, and otherwise isn't very useful.

**Comment by HugoBDesigner** [comment]
You misunderstand. It's not being closed _because_ it doesn't show up anywhere else. It's being closed in its own terms, but if it _had_ been used elsewhere, then that could have been a reason to keep it.

**Comment by Nikita74Russian** [comment]
*insert facepalm here*

**Comment by Endermage77** [comment]
#2707 is a thing that I suggested because I felt that there was a gap for such an item in the mod as there currently no way to safely put down a futbol without sticking it in a slot or breaking it, so a stasis field is a logical hypothetical solution.
