### ISSUE TITLE
Toxic-Greeny Environment (skybox)

### ISSUE THREAD

**Issue by Nikita74Russian** [BEEmod/BEE2-items#2711]
Makes the chamber glow like... Toxically green. Basically a bit of green filter, and lighting of dark-green a bit. Would be great for overgrown maps, where are goo-pits are used as the main threat to your life.

**Comment by Konclan** [comment]
Stop suggesting stuff like this, BEEmod isn’t your dream list for everything ever. Styles like this belong in hammer. If you really want stuff like this I suggest you learn how hard it is to actually createand maintain styles.
