### ISSUE TITLE
Blast Doors

### ISSUE THREAD

**Issue by McReenZRo** [BEEmod/BEE2-items#2713]
![images](https://user-images.githubusercontent.com/39560410/40428795-8acda590-5eba-11e8-8911-19f0fe9d6a3f.jpg)
See a little above... You can see a huge door. This is how it would look like.
Opens slowly, shuts a bit slower.

**Comment by TeamSpen210** [comment]
Ok, new rule. No beta content.

**Comment by McReenZRo** [comment]
Blast Doors are NOT beta content.
