### ISSUE TITLE
Hover Turret

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2714]
(I know about #1641)
it seems that the A.I. is intact, Just missing model and voice-lines. It doesn't fire a Thermal Discouragement Beam, Seems to be the same beam as the Stalker NPC in HL2. However would it be possible to recreate the Hover Turret (with a model, Possibly the placeholder Curiosity Core for Portal 1 style. I like the Curiosity Core model) except it fires a Discouragement Beam?
This would allow for an interesting test mechanic where you temporarily activate a Relay or Catcher, and it drops a cube or some other item. It could either shoot it from its eye, or have a little emitter on the bottom of it. 
![800px-portal_2_hover_turret_action](https://user-images.githubusercontent.com/37309250/40435257-418d3972-5e7e-11e8-89dc-cb9a1267227b.png)

**Comment by HugoBDesigner** [comment]
If you know of #1641 then why repost instead of commenting there?

**Comment by Endermage77** [comment]
@HugoBDesigner This suggestion seems to be asking that the hover turret instead shoot a Discouragement Beam, of the variety that can activate laser receptors, which would be an interesting test idea (As well as still being, eventually, deadly).
