### ISSUE TITLE
Walking Turret

### ISSUE THREAD

**Issue by McReenZRo** [BEEmod/BEE2-items#2715]
Was cut from Portal 2. Walks toward players, fires bullets. Can go through portals to chase the players. Can be destroyed by Discouragement Beam
![270px-portal_walking_turret_front](https://user-images.githubusercontent.com/39560410/40438748-462a5222-5ed2-11e8-9b45-8ce0c48a9973.png)

**Comment by Konclan** [comment]
It was cut for a reason...

**Comment by HugoBDesigner** [comment]
I don't think there's any code left for it, so it'd be impossible to reproduce them.

**Comment by LautaroL20** [comment]
Dummy turret suggestions...

**Comment by ZombiePwner1** [comment]
Even then prop_dynamic's wouldn't work either since valve removed most of the NPC code in portal 2.
