### ISSUE TITLE
Panel Cube

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2716]
I saw this in a map once and thought it looked interesting. I looked but didnt see a duplicate. So if there is one. Im sorry.

Essentially it is a normal cube (Would probably only be a normal cube, others wouldn't make sense for how it functions) and on the front it has either a Portal surface or a non portal surface. It can get covered in gel. and can be picked up. This would allow for some interesting tests. Carrying around your second portal surface to help complete the test. Stuff like that.

Map I saw this in: https://steamcommunity.com/sharedfiles/filedetails/?id=353880028

**Comment by BETTEREXTENEDEDITORMOD** [comment]
I feel this would better if the cube wasn't there and it would just be a panel that you could pickup and drop.
And no hidden gyroscope that turns the panel upright when you try to lay it down

**Comment by Konclan** [comment]
I’ve seen a moving panel item, portable versions don’t work well at all and the idea of a movable gel surface isn’t that interesting. This item is way too gimmicky and would not make a great addition.
