### ISSUE TITLE
Here a suggestion list

### ISSUE THREAD

**Issue by UncleEle** [BEEmod/BEE2-items#2718]
Custom start position
Custom map end position
Cutout wall
Cutout Ceiling
Skin chooser (something like an antique cube skin in a clean theme)
Mid-chamber dialogue activator
Make an option that you can choose the old aperture's elevator entrance (apart corridor or somethng...)
Change the death fizzler's skin like Portal Stories: Mel's one (Red solid normal fizzler)
Change Infinite pit model
Add more sign to Signage object
Make an option for change the co-op starting/ending lobby
Add a changing degrees platform (like 35° to 45° or something)
Add Virgil and/or nigel voice lines from Portal Stories: Mel's
Add custom color lights
Angled Pneumatic Piston
Change clean style's floor/ceiling texture (like the coop track one)
Add death trigger

I hope I write only new thing

**Comment by HugoBDesigner** [comment]
Custom start position
Custom map end position
Cutout wall
Cutout Ceiling
Skin chooser (something like an antique cube skin in a clean theme)
Mid-chamber dialogue activator
Make an option that you can choose the old aperture's elevator entrance (apart corridor or somethng...)
Change the death fizzler's skin like Portal Stories: Mel's one (Red solid normal fizzler)
Change Infinite pit model
Add more sign to Signage object
Make an option for change the co-op starting/ending lobby
Add a changing degrees platform (like 35° to 45° or something)
Add Virgil and/or nigel voice lines from Portal Stories: Mel's
Add custom color lights
Angled Pneumatic Piston
Change clean style's floor/ceiling texture (like the coop track one)
Add death trigger

I hope I write only new thing

**Comment by HugoBDesigner** [comment]
`Custom start position`   
`Custom map end position`
[Not possible](https://github.com/BEEmod/BEE2-items/issues/605)  
  
`Cutout wall`  
`Cutout Ceiling`
[Duplicate](https://github.com/BEEmod/BEE2-items/issues/908)  
  
`Skin chooser (something like an antique cube skin in a clean theme)`  
`Make an option that you can choose the old aperture's elevator entrance (apart corridor or somethng...)` 
`Make an option for change the co-op starting/ending lobby `
[Closely related issue](https://github.com/BEEmod/BEE2-items/issues/2076)  
  
`Mid-chamber dialogue activator`
[Again](https://github.com/BEEmod/BEE2-items/issues/760)  

`Change the death fizzler's skin like Portal Stories: Mel's one (Red solid normal fizzler)`  
Not sure what you mean but it's unlikely either death fizzlers or laserfields will get their texture replaced.  
  
`Change Infinite pit model`  
Bottomless pit? What changes?  
  
`Add more sign to Signage object`  
What signages? [This issue](https://github.com/BEEmod/BEE2-items/issues/2529) and [this issue](https://github.com/BEEmod/BEE2-items/issues/1504) make some suggestions for designs.

`Add a changing degrees platform (like 35° to 45° or something)`
Unlikely to happen, unless you're willing to animate the transition between any two distinct angles in the arms model.  
  
`Add Virgil and/or nigel voice lines from Portal Stories: Mel's`
[Virgil](https://github.com/BEEmod/BEE2-items/issues/14). Nigel is already in.  
  
`Add custom color lights`  
[Duplicate](https://github.com/BEEmod/BEE2-items/issues/1414)  
  
`Angled Pneumatic Piston`  
`Change clean style's floor/ceiling texture (like the coop track one)`  
Unlikely these will happen but still valid suggestions.
  
`Add death trigger`
Consensus on Beemod Discord server was "no".

`I hope I write only new thing`  
Excerpt from Lautaro's message:

> If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them**. This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.
