### ISSUE TITLE
BTS Angled Panel with an open portal on shows the texture behind the panel

### ISSUE THREAD

**Issue by Firepal** [BEEmod/BEE2-items#2721]
![20180605202201_1](https://user-images.githubusercontent.com/29317321/40995247-dddfc35a-68fe-11e8-808d-115ab267c3e2.jpg)
I am in the blue portal, and the orange portal is on the panel.

Notice that thing in the blue portal ? Need a closer look ?

![20180605204617_1](https://user-images.githubusercontent.com/29317321/40996540-59135b7e-6902-11e8-9a0e-695247e84553.jpg)

**Here's a closer look !**

As you can see in the blue portal,
there's a strange... texture that warps when you move the camera. And it's this:

![20180605200533_1](https://user-images.githubusercontent.com/29317321/40995596-bf1daa08-68ff-11e8-940e-0bb9314a905e.jpg)
This is the back of the panel, and it's what shows up in the blue portal.
And i'm not sure about this, but i think the panel surface isn't thick enough, and that's why
the texture shows through ? Eh.

Hope you can fix this ?

Thanks, and have fun.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
