### ISSUE TITLE
Aperture Tag paint gun activator fields not turning off

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#2726]
Weird thing is, when they're deactivated, they're still visible, still make sounds when passing through, still clean cubes and block gel, but they don't activate/deactivate the paint gun.

**Comment by ZombiePwner1** [comment]
Send a screenshot.

**Comment by Konclan** [comment]
I already fixed this, it was a logic and name issue

**Comment by HugoBDesigner** [comment]
Recorded a short video of the problem:
https://www.youtube.com/watch?v=xOgtwSPwyVo

**Comment by HugoBDesigner** [comment]
@Konclan could you perhaps share that fix, or maybe commit it? That'd be swell 👍
