### ISSUE TITLE
Retracted glass panel has missing clips

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#2730]
With a retracted, disconnected glass panel, both the player and cubes get lowered into the block with a glass panel (in the screenshot, I'm crouching to show how I'm closer to the ground than usual):

![image](https://user-images.githubusercontent.com/6296061/41829633-3e21ee4c-7812-11e8-96ec-98ff2e9c53c5.png)

**Comment by Overwatch-C-17** [comment]
Still exist in PR.31
