### ISSUE TITLE
Standing on the underside of an upside-down Victory Lift kills you instantly when it starts retracting

### ISSUE THREAD

**Issue by bubbyboytoo** [BEEmod/BEE2-items#2731]
If a Complementary Victory Lift is placed on the ceiling, you can stand on its underside while it's extended, but it'll kill you immediately if it starts retracting while you're standing on it. Tested and confirmed in the Portal 1, Clean, BTS and 1950s styles, so it seems to be a universal bug. Also applies to Positronic Energy Orbs in the Portal 1 style.

**Comment by ZombiePwner1** [comment]
Definitely a bug since it should only kill you when it's fully retracted and ur inside it.

**Comment by TeamSpen210** [comment]
It's difficult to actually detect when a platform should be killing the player, since we can't actually detect it being blocked. Maybe I should try and do that, so it can enable them only after the platform stops moving?

**Comment by Konclan** [comment]
Can’t you use a door’s blocking damage feature?
