### ISSUE TITLE
Portal 1 Victory Lift not working properly

### ISSUE THREAD

**Issue by PSIGuy** [BEEmod/BEE2-items#2732]
I've put a victory lift connected to a high energy pellet catcher in my Portal 1 styled chamber (the time is set to infinite), and for some reason the lift won't retract when the catcher activates.  I unchecked the Auto Drop option and I've tried other things to get it to function properly, but nothing's worked thus far.  I should also mention that the lift is surrounded by walls on all sides.

**Comment by TeamSpen210** [comment]
Currently it doesn't work properly if you set it to move downward when activated. Put a NOT gate in.

**Comment by PSIGuy** [comment]
Alright I reversed the lift's positioning (I set it to go up rather than down) and added the not gate in and it seems to be working properly.  Thanks for the help!

**Comment by TeamSpen210** [comment]
Fixed a while ago.
