### ISSUE TITLE
Triggered Faith Plates?

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2734]
These would be probably a Wall-Only version of the faith plates. It's a faithplate with a trigger a bit infront of it and then it extends. Like the panel Faith Plate that Wheatley uses to send you to the platform surrounded with crushers during his "Surprise"

**Comment by TeamSpen210** [comment]
This isn't really comprehensible. How is it different in functionality to the existing two faithplates?

**Comment by King0191** [comment]
In the idea. Its like a wall panel that shoots out towards you and flings you across to the end point. This  would be useful in an Exursion Funnel part, so they dont have to worry about strafing midair to hit the faithplate on the wall because it would shoot out of the wall and hit them rather than them hitting IT.

**Comment by TeamSpen210** [comment]
Just move the faith plate below, alter the map layout, or use a large plate to give a larger trigger radius.

**Comment by King0191** [comment]
Yes, essentially @Endermage77
