### ISSUE TITLE
Nodraw/Leak Issue, Clean Style

### ISSUE THREAD

**Issue by Determinated888** [BEEmod/BEE2-items#2737]
I don't know how to add labels to issues so if someone could do that for me it would help. The zip file below me has an 8 second video of the issue. There is a leak issue with the door and there is a leak issue with the goo pits. This problem only recently, and I am not sure what is causing the issue. I also checked a map I made a while back to see if it was just one test or all of them. I found that the goo in that test was fine but the textures for the elevator and the faith plates were not right. They had a brown murky look to them. I would really appreciate any help I can get. Thanks!
[Bee Error.zip](https://github.com/BEEmod/BEE2-items/files/2161159/Bee.Error.zip)

**Comment by HugoBDesigner** [comment]
The leak effects are normal (for a leak). The thing we should be looking for is the cause. Do you happen to have a large observation room one block away from a wall indentation like this?
![image](https://user-images.githubusercontent.com/6296061/42246926-e946bd0a-7ef4-11e8-81fb-c7674de20c56.png)

If not, check to see if you have cutout tiles on the edge/corner of a wall, those have caused leaks before.

If possible, open up the console, type in `developer 2`, and try to recompile the map. See if you find any error messages that might indicate where the leak is happening.

**Comment by Determinated888** [comment]
This is a stupid question but what are cutout tiles? I think I know what you mean but I am not sure. Also thank you for the help, I will try the dev console to recompile it.

**Comment by Determinated888** [comment]
So I just did the developer 2 command, and there are a LOT of error messages relating to the elevator. If I were to copy and paste all of them it would take up most of the page. I had a Observation Room but I deleted it. With the BTS Skybox, the bottomless pit is actually okay. The door is still broken though.

**Comment by ZombiePwner1** [comment]
@Determinated888 You don't have permission to add labels only the members are allowed to do this.

**Comment by Determinated888** [comment]
@ZombiePwner1 Ok thanks for letting me know.

**Comment by LautaroL20** [comment]
Be careful at using the Cutout Tile item since it tends to cause leaks.

**Comment by Determinated888** [comment]
I was able to fix the problem! Turns out my entrance was in a spot where it was overlapping a walk in the chamber, so to speak. Thank you to all who helped!

**Comment by HugoBDesigner** [comment]
It's not really a problem with the entrance, it's just the door's areaportal leaking. It's normal behavior for leaks, much like goo

**Comment by LautaroL20** [comment]
@HugoBDesigner - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
