### ISSUE TITLE
Play Wheatley Science near a bottomless pit

### ISSUE THREAD

**Issue by SomePeople27** [BEEmod/BEE2-items#2738]
If you would stand near a bottomless pit, a soundtrack with a name Wheatley Science would silently play, but must be able to be heard. 
If you don't know the soundtrack, here it is.
https://youtu.be/wcud2Km2iwM?list=PLhHcMbVmbwCcwvWVo-RJX_NOlRDarwJN6
It would play also when you fly over a bottomless pit, with a faith plate, or other velocity things.
Background music would become silent, if added in level, as you get far away from the pit, it starts playing again.

**Comment by TeamSpen210** [comment]
Indeed, music should be specific to the track.
