### ISSUE TITLE
Chamber Lock & Door

### ISSUE THREAD

**Issue by Overwatch-C-17** [BEEmod/BEE2-items#2743]
Can those items changed their parameter to "Start Open" instead of "Start Enabled"?

**Comment by HugoBDesigner** [comment]
No, it's hardcoded. We can't change anything that comes with puzzlemaker or with the Portal 2 engine, including, but not limited to: adding more items to the palette, renaming option labels, creating new labels, changing the behavior of items in-editor, or adding new elements not present in the game or constructible with existing elements. For more information, please consult our FAQ page:
https://github.com/BEEmod/BEE2-items/wiki/FAQ

**Comment by TeamSpen210** [comment]
Well actually, I could swap those items to use "start open". But that'd make any existing ones in saved maps not update, so they'd reset to the default.
