### ISSUE TITLE
BTS Underground Ideas

### ISSUE THREAD

**Issue by CTB33391** [BEEmod/BEE2-items#2744]
- Entrance and exits are corridors or external catwalks. Sometimes exit can approach an enrichment sphere, or entrance be a lobby
- The beginning area would see the player turn on the pump stations for that era's gel. Other gel is piped in from above
- Buttons would be circuit breakers
- Floor buttons would be placed on a raised bit of floor, as if they were to be added to a sphere
- Gel comes out from either normal droppers or (preferably) a broken pipe
- Bottomless pit would - of course - be looking down at the bedrock with spheres visible. Height depends on era
- Doors set to start enabled and with no connection would be replaced with pushbar doors; otherwise use the same as modern BTS
- Observation rooms are bits of framed piping with a glow behind them
- Square lights would not take up the voxel, but instead be a lamp

**Comment by ZombiePwner1** [comment]
@CTB33391 BTS underground is already a planned style but currently it will not be implemented at this stage.

**Comment by CTB33391** [comment]
I knew that, just putting it out there for when you get round to it lol

**Comment by Luke18033** [comment]
This isn't a style that would work very well in the puzzlemaker, I don't really see it being added.

**Comment by ThatOneRetro** [comment]
That's a shame
