### ISSUE TITLE
Half-blocks cause weird behavior when embedded in goo with 3D factory skybox

### ISSUE THREAD

**Issue by ReikaKalseki** [BEEmod/BEE2-items#2747]
The goo becomes a pit with that skybox, and while sideways slopes work fine, sideways half-blocks cause the "floor" under that block to render:

In PeTI: ![https://i.imgur.com/e2yxPUM.png](https://i.imgur.com/e2yxPUM.png)

Ingame: ![https://i.imgur.com/ITSFbAh.jpg](https://i.imgur.com/ITSFbAh.jpg)

**Comment by Luke18033** [comment]
Skybox-based bottomless pits have been removed

**Comment by ReikaKalseki** [comment]
How is it accomplished now?
