### ISSUE TITLE
Suggestion: BTS Voicelines

### ISSUE THREAD

**Issue by The-Queen55142** [BEEmod/BEE2-items#2748]
If this is planned already then oh well. But I was wondering if we're ever going to get lines for BTS Styled maps for Wheatley, Announcer, and GLaDOS. Announcer having the turret redemption lines and such. GLaDOS and Wheatley having their mid-escape lines. It would be useful when I want to have GLaDOS in a BTS chamber im making without her saying something like "Please proceed into the next Test Chamber, Which involves deadly lasers and how test subjects react when locked in a room with deadly lasers"

**Comment by CTB33391** [comment]
AFAIK BTS is in early stages of development so I think this could be likely. They probably have it planned to be honest though.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
