### ISSUE TITLE
Sphere and Cube Button Models Too Clean

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#275]
This is already maded for the "Big pressure button", but its still missing for the "Shpere" and "Cube" buttons.

On the "Big Pressure button", you can appreciate how damage it is:

![2016-02-09_00003](https://cloud.githubusercontent.com/assets/12244376/12912264/1ff224f4-cef6-11e5-8ad3-3ef0309e05fe.jpg)

---

This "Damaged" Style is still missing for the "Shpere" and "Cube" buttons:

![2016-02-09_00005](https://cloud.githubusercontent.com/assets/12244376/12912298/526dddec-cef6-11e5-82cf-7246603620a4.jpg)
![2016-02-09_00004](https://cloud.githubusercontent.com/assets/12244376/12912310/655a7096-cef6-11e5-8779-26e4485b4070.jpg)

**Comment by TeamSpen210** [comment]
That's because Valve only made destroyed models for the normal buttons. We'd need to remake the button models and create new textures to make them destroyed properly. I'll see if I can retexture them to look more damaged, but I'm not really a modeller.

**Comment by LautaroL20** [comment]
This style is almost perfect exept for these "Missing damaged details", i think if you get these missing damaged styles back for the "Overgrown", this style would be 100% polished and complete.

**Comment by TeamSpen210** [comment]
It's not exactly missing - there isn't a damaged version of these models. I'll have to try making a custom one.

**Comment by LautaroL20** [comment]
Also, there isn't a damaged version of "Gel Droppers" for this style:

![2016-02-09_00006](https://cloud.githubusercontent.com/assets/12244376/12915105/8fe4eb96-cf07-11e5-8907-a8980880c6ab.jpg)

If damaged versions are going be maded, this will make of "Bee 2.4" a very special and unique tool.

**Comment by BenVlodgi** [comment]
This will increase the size of the file, because the BEE2 will have to pack this additional resource for every map with it. But might be worth.

**Comment by TeamSpen210** [comment]
The reflection gel dropper here is actually a custom model.

**Comment by BenVlodgi** [comment]
well I guess in that case, it really wouldn't take up much more space for the paint droppers

**Comment by LautaroL20** [comment]
Hey guys, i have a friend on Steam wich was involved as a Modeller for the mod "Black Mesa", i think he could be actually a nice help to modeller these items to an overgrown version. What do you say?

**Comment by TeamSpen210** [comment]
Any contributions at all would be lovely :).

**Comment by BenVlodgi** [comment]
@LautaroL20 that would be nice, its always good to get more portal 2 resources in circulation

**Comment by LautaroL20** [comment]
His name on Steam is "MichaelTannock", please add him to get in contact, direct link:

http://steamcommunity.com/profiles/76561197970958081/

**Comment by LautaroL20** [comment]
@TeamSpen210 - Did you had the chance to chat with Michael Tannok via Steam? Is he willing to collaborate in any aspect?

**Comment by LautaroL20** [comment]
Added overgrown gel dropper? That would be pretty interesting to see! Let's hope cube and sphere buttons are coming out in the near future too.

**Comment by TeamSpen210** [comment]
I just applied a rusty overlay to the clean model:
![gel_dropper](https://cloud.githubusercontent.com/assets/8453732/18858105/09258262-84ad-11e6-86c0-a5e5924e5cb4.PNG)

**Comment by LautaroL20** [comment]
Nice :)

**Comment by Luke18033** [comment]
Bump

**Comment by Konclan** [comment]
Bump
