### ISSUE TITLE
Factum Solus Turbine

### ISSUE THREAD

**Issue by The-Queen55142** [BEEmod/BEE2-items#2755]
There is a Mod called Factum Solus for Portal 1. And it has some unique elements (honestly like one... But still). as well as its own version of other elements. Could these possibly be added?

**Comment by Konclan** [comment]
I don't recall any new elements from that mod, and they might be technically inferior duplicates of Portal 2 elements. You'll have to be more specific and provide examples.

**Comment by CTB33391** [comment]
Turbine is literally Pneumatic Diversity Vent's job. Perhaps as a stylevar for Portal 1 style. The spring sounds kinda cool, perhaps it could be changed to activate on ANY signal deactivation, not just a pedestal button. Would work great for co-op maps.
Otherwise no.

**Comment by somedoodest** [comment]
The Turbine is actually pretty different, it also affects the player. You literally get thrown to the roof or where-ever the Turbine is placed. It also affects a bigger area.

**Comment by Konclan** [comment]
I think the turbine is the only interesting item here

**Comment by LautaroL20** [comment]
Ive never played Factum Solus, but what logical function is supposed to meet the "turbine" anyways?

**Comment by Konclan** [comment]
Area denial and mobility

**Comment by Luke18033** [comment]
See #3884
