### ISSUE TITLE
Laser Destroyer (Idea)

### ISSUE THREAD

**Issue by UncleEle** [BEEmod/BEE2-items#2757]
It would be an object like the Positronic Energy Orb (Red i suppose) which destroy the laser that pass through it , obviously more low than the original .

**Comment by King0191** [comment]
So... It's just like a round wall that blocks lasers...? Just use Arm Panels... Same end result. Blocks the Laser... I don't personally see why we'd need a new item for this

**Comment by UncleEle** [comment]
i know but is ugly to see
no more

**Comment by CTB33391** [comment]
I'd see it as a red Positronic Energy Orb (like you) placed like a laser relay but it stops the laser as well as emitting a signal, by redirecting it into a receptacle. Perhaps could accept an input to turn it off. You don't have to give it an output so it could be a laser void.

**Comment by Endermage77** [comment]
So @CTB33391 is basically describing a Laser Catcher that would work like the HEP catcher, yes?

**Comment by TeamSpen210** [comment]
I don't see the advantage of this over a pillar or something.

**Comment by Endermage77** [comment]
Hmm.... I think I might reform the Laser Catcher idea into a separate issue.
