### ISSUE TITLE
New Item: 2x2x2 Static panel

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2759]
![20180718014945_1](https://user-images.githubusercontent.com/35931028/42850269-768c451e-8a2f-11e8-8baf-c46c20269c80.jpg)
![20180718014952_1](https://user-images.githubusercontent.com/35931028/42850273-78c7b192-8a2f-11e8-87e0-85b3f5432ee7.jpg)

**Comment by SCIENTIST2004** [comment]
8 Directions

**Comment by Endermage77** [comment]
This might have some interesting applications in edge cases where you need a portal on there for some reason.

**Comment by SomePeople27** [comment]
Hmm... You should make NON-Static version of this, a single panel.

**Comment by UncleEle** [comment]
![cattura8](https://user-images.githubusercontent.com/38593922/43152162-16eaf382-8f6e-11e8-9351-9de6830028f7.PNG)
as a static panel you can already use this

**Comment by Konclan** [comment]
UCP
