### ISSUE TITLE
Infinite pedestal button reset

### ISSUE THREAD

**Issue by TheRedMelon** [BEEmod/BEE2-items#2760]
I think when the pedestal button is in infinite mode, it should come back up and be available again when given a signal.  This would give a way for it to be used multiple times without having to set a time for it as that currently ticks at you.

Also, the pedestal button cannot go below 3s as it is set to 3s by default.

**Comment by SCIENTIST2004** [comment]
you are not right
it is set to 1s by default.

**Comment by Luke18033** [comment]
It's set to 3 by default in vanilla, and you can change the default value in the BEE2 application.

**Comment by SCIENTIST2004** [comment]
I mean in BEE2

**Comment by TheRedMelon** [comment]
I've tried this but it doesn't work.
Also, I think it'd still tick if it was set to 1s wouldn't it?

**Comment by ZipZoptheCat** [comment]
Remember the Portal 2 version of the test chamber from portal 1 where you push the button to activate a different orange auto-portal? How do you even get that to work without this feature in place?

**Comment by TeamSpen210** [comment]
You connect buttons to autoportals, and it happens automatically.

**Comment by TeamSpen210** [comment]
This is already implemented for a number of items.
