### ISSUE TITLE
Missing player model

### ISSUE THREAD

**Issue by Overwatch-C-17** [BEEmod/BEE2-items#2761]
I set a compile option for SP mode to use model (Example: ATLAS or P-Body). But the resulted map not including those required models. I'm still see myself as Bendy and missing portal gun (World Model). Same case as my friend playing my map (Not Installing BEE Mod yet)

**Comment by Overwatch-C-17** [comment]
Is someone encountering the same case as mine?

**Comment by Konclan** [comment]
I've never heard of this happening

**Comment by Luke18033** [comment]
Closing due to lack of info.
