### ISSUE TITLE
Visible delayer 

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2762]
![signage_indicator_timer](https://user-images.githubusercontent.com/35931028/43022432-f394b9fa-8c6f-11e8-81d1-40ad37e6a5c2.png)
That will be a common delayer but visible and it will have that a.m. image but 2x2 and it will have 4 directions

**Comment by TeamSpen210** [comment]
It's already visible, via the antline. I might want to make the antline display blue variants when off, but that's difficult to do so I doubt I'd make that.

**Comment by SCIENTIST2004** [comment]
But antline timer is small andBut the antline timer is small and there is only at the end of the antline, and the visible delayer can be put there where the player sees it well
