### ISSUE TITLE
map error

### ISSUE THREAD

**Issue by Slapsfaceonkeyboard** [BEEmod/BEE2-items#2764]
i started a BTS map a while ago, and i was trying to figure out a problem i was having with the cat walks, but it decided to have an error building the chamber after i finally figured the catwalk problem out, so i exited and discarded the test and started making a new one, but the it still had the error, so i just gave up and figured it was a problem with just that style and started a overgrown test but when i tried to build that test it popped me in the first test and then had the error every time after that, i don't know how to fix it or what might be causing it. I would love to know how to fix it or to see if it can be fixed in the next update.

**Comment by Slapsfaceonkeyboard** [comment]
where is the cache located?

**Comment by Endermage77** [comment]
Right click on Portal 2, then go to ---> Properties ---> Local Files and click on "VERIFY INTEGRITY OF GAME FILES"
This will basically fix up any bits in the Portal 2 files that it detects are missing/broken. Then try running BEE2 again.

**Comment by Slapsfaceonkeyboard** [comment]
the first map still shows up every time i try to make a new one

**Comment by Endermage77** [comment]
Does it compile properly after you've verified the game cache?

**Comment by Slapsfaceonkeyboard** [comment]
does anyone have an easy to understand version before i close this and just stop using BEE2 for good?
