### ISSUE TITLE
portal 1 ending elevator

### ISSUE THREAD

**Issue by Gamther** [BEEmod/BEE2-items#2766]
Its a never ending elevator
[2018-07-21 23-29-17.zip](https://github.com/BEEmod/BEE2-items/files/2216707/2018-07-21.23-29-17.zip)
mp4 In the Zip

**Comment by Konclan** [comment]
Upload to any video streaming site please

**Comment by King0191** [comment]
This only affects the preview. And this happens in all the P1 elevators. 
In published maps this issue does not occur. I personally dont see it as a big deal tbh

**Comment by ZombiePwner1** [comment]
@King0191 Preview maps usually do restart but bee has an option to disable this.

**Comment by TeamSpen210** [comment]
Regardless of that option (which triggers the restart after going through the exit door), it should restart after going in the elevator.

**Comment by Konclan** [comment]
Duplicate of BEEmod/BEE2.4#1119
