### ISSUE TITLE
 New Item: fizzler Blocking Funnel

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2769]
![fizzlerblockfunnel](https://user-images.githubusercontent.com/35931028/43092623-70045e8a-8eb6-11e8-81a2-96873c5aec60.png)

**Comment by King0191** [comment]
This would be better named Funnel Blocking Fizzler. The current name implies that it's a funnel that blocks Fizzlers. Which is 
1. Impossible
2. Not what you meant

**Comment by HugoBDesigner** [comment]
It is not possible to make a fizzler that blocks a funnel exclusively. Funnels are blocked by solid brushes, which also block other entities.

**Comment by ZombiePwner1** [comment]
@SCIENTIST2004 We'll have to edit the source code to allow this and we don't have access to the source code unfortunately :(
