### ISSUE TITLE
Test chamber doesn't load

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2770]
When I choose my test chamber (I named it "Resonance")
Portal 2 starts loading and after few seconds loading fails and bugged main menu appears
![20180724223621_1](https://user-images.githubusercontent.com/35931028/43161957-4140d9a2-8f92-11e8-984f-7af7c688487f.jpg)
Please HELP

Console log:
Failed to init 'maps/soundcache/_master_russian.cache'
Didn't find Active Steam Controller to Load Menu Controls
resource/closecaption_dfd_English.txt not found
resource/closecaption_russian.txt will be used
Unknown command "cl_thirdperson"
Unknown command "|"
An error occurred while attempting to download a file from the UGC server!
Didn't find Active Steam Controller to Load Menu Controls
[PORTAL2 PUZZLEMAKER]  Loaded puzzle puzzles\76561198165502222\1532345945.p2c
Unknown command "cl_puzzlemaker_activate"
[PORTAL2 PUZZLEMAKER]  Loaded puzzle puzzles\76561198165502222\1532345945.p2c
CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.0.103, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 1668 )
Opened Steam Socket NS_CLIENT ( socket 2032 )
Network: IP 192.168.0.103, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\1532345945/c-2400_0_0.hdr' -- Trying non HDR 'maps\1532345945/c-2400_0_0'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1532345945/c-6376_-220_-1395.hdr' -- Trying non HDR 'maps\1532345945/c-6376_-220_-1395'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1532345945/c-6376_-220_-979.hdr' -- Trying non HDR 'maps\1532345945/c-6376_-220_-979'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1532345945/c-6192_-16_16.hdr' -- Trying non HDR 'maps\1532345945/c-6192_-16_16'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1532345945/c-6138_1560_-596.hdr' -- Trying non HDR 'maps\1532345945/c-6138_1560_-596'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1532345945/c-6138_1560_-228.hdr' -- Trying non HDR 'maps\1532345945/c-6138_1560_-228'
Failed, using default cubemap 'engine/defaultcubemap'
Host_EndGame: Map coordinate extents are too large!!
Check for errors!

**Comment by SCIENTIST2004** [comment]
Any help?

**Comment by Endermage77** [comment]
I'm not an expert but by the looks of it your map is too big for the game to be able to parse.
Source:
"Host_EndGame: Map coordinate extents are too large!!"

**Comment by Nick2007Portal** [comment]
Why this is still open?
