### ISSUE TITLE
Portal magnet doesn't work correctly

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2775]
![exp7 1](https://user-images.githubusercontent.com/35931028/43360382-000a1a6a-92bd-11e8-9233-684fc6b57167.png)
![exp7 2](https://user-images.githubusercontent.com/35931028/43360384-02308806-92bd-11e8-9e38-c2e736964657.png)

**Comment by SCIENTIST2004** [comment]
ok

**Comment by SCIENTIST2004** [comment]
@HugoBDesigner: When you adjust the position gismo, does it work properly?

-No

**Comment by Nick2007Portal** [comment]
Now, i won't make levels with this. This is a complete mess. 
Btw, i think info_placement_helper is not aligned right. 
Try placing it at different angle.

**Comment by joric** [comment]
4.36.1 still doesn't work. Those portal magnets don't force the desired position and allow any conceivable placement and even two portals side by side. There should no be any wiggle room at all. Please fix the damn thing!

**Comment by Luke18033** [comment]
See [this] (https://www.youtube.com/watch?v=ivyseNMVt-4&t=2624s). Placement helpers (aka portal magnets) are supposed to help with alignment, not forcibly lock portals to a specific location. Use a centered half wall if you want to do that, it's much clearer to the player.

**Comment by Luke18033** [comment]
This issue is totally unrelated to that anyway, it's been fixed now.
