### ISSUE TITLE
Old Aperture Door missing editor model

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2776]
1980s Old Aperture
![20180729000423_1](https://user-images.githubusercontent.com/35931028/43360717-5e619a0a-92c4-11e8-9f3e-72e5c66f24a8.jpg)

**Comment by Luke18033** [comment]
The editor model is just missing, it's not really "mysterious"...

**Comment by SomePeople27** [comment]
Try re-exporting? If it won't help, then it is a bug, or a missing resource.

**Comment by Nick2007Portal** [comment]
Welp, this may be something i would NOT want to see.
