### ISSUE TITLE
How to use Logic Gates? OR, AND, NOT.

### ISSUE THREAD

**Issue by revaru** [BEEmod/BEE2-items#2777]
I put 2 buttons and want them both to be able to open the door, but not when both are pressed, but one by one. How do I connect logic_or and where do I place it to work?

**Comment by King0191** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=150558007

I use this for my logic gate knowledge when I was confused

**Comment by revaru** [comment]
I'm don't understand this guide. 
![image](https://user-images.githubusercontent.com/41899094/43398493-aaa0e4b2-9421-11e8-9597-c5d8dc669c59.png)
connect your trigger(s) to the logic gate, and connect the logic gate to the object.
What is trigger in this guide?!?

**Comment by revaru** [comment]
Thanks! I understand after reading second time! Thanks.

**Comment by Endermage77** [comment]
@LautaroL20 Wouldn't this technically classify as a Question that has been Answered?

**Comment by LautaroL20** [comment]
The problem is that someone between the owner and collaborators (i bet its Luke18033) wrongly keeps deleting the "Question" label each time i restore it back and i already got bored from brindning it back...

**Comment by Luke18033** [comment]
It specifically says in the contributing guidelines not to open issues to ask questions. Why should we have a label for it? It should just be "invalid", if anything.
