### ISSUE TITLE
moniter camera texture leaking through glass texture.

### ISSUE THREAD

**Issue by ZipZoptheCat** [BEEmod/BEE2-items#2780]
![camera leak](https://user-images.githubusercontent.com/41752266/43440607-d094ddba-944c-11e8-823f-f84b5ff2a030.png)
It appears to happen on the striped section and the smooth section.

Style: Overgrown
Skybox 2d BTS (not sure if relevent)

**Comment by TeamSpen210** [comment]
We can't fix this unfortunately, it's a general source bug.

**Comment by ZombiePwner1** [comment]
@ZipZoptheCat This will happen with certain models regardless of what glass texture is used and like @TeamSpen210 said we can't fix it due to it being hard coded in the engine.
