### ISSUE TITLE
New item: Skybox

### ISSUE THREAD

**Issue by revaru** [BEEmod/BEE2-items#2781]
I am offering a **new item** in BEEmod. This item will be a _**Skybox**_. It will have the same mechanics as the _"cutout tile"_ and the _"catwalk"_. Place **one in one corner**, the **other in the other corner** and **connect them with antlines**.

**Comment by revaru** [comment]
Texture 270x270
![image](https://user-images.githubusercontent.com/41899094/43471623-dab37f96-9504-11e8-8fac-057c14c3c57b.png)

**Comment by LautaroL20** [comment]
So, i assume this will going to be a voluntary contribution.

**Comment by CTB33391** [comment]
They are already thinking of adding that sort of thing from what I can gather.

**Comment by Endermage77** [comment]
@CTB33391 Lautaro isn't a native English speaker either.

**Comment by LautaroL20** [comment]
Well, if this is not a voluntary contribution then i doubt that Spencer will consider this to be done.

**Comment by Nick2007Portal** [comment]
It is.
