### ISSUE TITLE
Bottomless Pit Customization Style Vars

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#2783]
Before someone gets the idea this is invalid or duplicate or this will be too hard to pull off (yes this will take some time) or something and closes this immediately, this is a new idea for when bottomless pits are redesigned by teamspen210 in the future so bee2 generates them like the real bottomless pits in the original game (no skybox, actual pit and hole in the floor that a laser, or paint could fall down into and not hit a invisible floor)... 

Hey @TeamSpen210 and @BenVlodgi - When ever the bottomless pit bee2 generation coding is redesigned We need a menu full of Bottomless Pit Customization Style Vars... the style vars would be checkboxes and dropdown menus to fully and utterly customize the pit generation and the options i thought of are explained below, if you or someone else thinks of any more that should be added, let me know in a reply and i will add them to the list

Depending on test chamber style chosen

- [ ] Depth of pit (a dial from 1 - 100 that would determine pit depth from top to bottom, 1 would be a shallow pit probably no more than twice to 5 times the players height, 50 would be normal, and 100 would be the deepest)
- [ ] Depth of Kill Floor, a dial from 1 - 30 that would set how far your player would have to fall before hitting the kill trigger, 1 being it would be very close to the test chamber, 15 would be normal, and 30 would be the farthest down in the pit)
- [ ] Number of support beams (a dial from 1 - 30, besides beams supporting pillars, this would set the amount of steel beams generated in your pit, 1 being a vertical support beam at only the 4 corners of the test chamber and no horizontal beams, 15 being normal, and 30 being many vertical support beams and horizontal beams)
- [ ] Number of other test chambers (a dial from 0 - 30, number determines the number of other test chambers you can see the outsides of in the pit, 0 being nothing, 1 being maybe 1 or 2, 15, being normal and 30 being many)
- [ ] Number of Wires (a dial from 0 - 30 that would determine the number of hanging wires you would see in the pit, 0 being nothing, 1 being one or two, 15 being normal, and 30 being many)
- [ ] Number of Vac Tubes (a dial from 0 - 15, 0 being nothing, 1 being 1 or 2, 5 being normal, 15 being many)
- [ ] Generate Paint in vactubes (a checkbox that would set a flag to generate paint flowing through some vactubes
- [ ] Paint colors (four checkboxes that would be the four gel types, selecting more than one would mean you would see vactubes carrying more than one type of paint in the pit)
- [ ] Generate Physics in Vactubes (a checkbox that would make cubes etc flow through vactubes in bottomless pit)
- [ ] types of physics in vactubes (checkboxes for cubes, turrets, boxes etc. selecting more than one means random vactubes will carry physics through them)
- [ ] Number of catwalks (a dial from 0 - 30, 0 being none, 1 being 1 or 2, 15 being normal, 30 being many)
- [ ] Number of metal air ducts (a dial of 0 - 30, 0 being none, 1 being 1 or 2, 5 being normal, `15 being more than usual, and 30 being many)
- [ ] Number of square beams in pit (a dial of 0 - 30, 0 being no square beams and a clean cut hole, 1 being very few, 15 being normal, and 30 being many)
- [ ] number of tiles on square beams (number of tiles on square beams in pit, a dial 0 - 30, 0 being none, 1 being few, 15 being normal, and 30 being no holes at all)
- [ ] Amount of decoration items like wires, lights, square beams, tiles, etc generated in pit (a dial of 1 - 30, 1 being very few, 15 being normal, and 30 being many)
- [ ] amount of destruction to pit (a dial of 0 - 30 to make the pit destroyed in other styles like in wheatley style, 0 being a normal pit, 1 being a few tiles cracked etc, 15 being a wheatley pit, and 30 being really destroyed)

Example checking a lot of these and setting all these values around 15 might generate a pit like this one in the image... 

![2013-03-21_00004](https://user-images.githubusercontent.com/11165643/43553886-3ff0f7a2-95bf-11e8-8c91-baed19c317c1.jpg)

**Comment by ZombiePwner1** [comment]
@ellingtonvengaboysmuseum that picture is from PS:M and yes they have great bottomless pits ideas problem is I don't think we can generate them atleast detailed as far as this due to PeTi's restrictions.

**Comment by LautaroL20** [comment]
@ellingtonvengaboysmuseum - Peti´s restrictions doesn´t have anything to do with this, wheels. The implementation of the exposed here depends entirely from the TeamSpen210´s skills and their decision to make it happen.

**Comment by ZipZoptheCat** [comment]
Would it streamline the work for this sort of thing if the skybox and the bottomless pit were unified?

**Comment by ellingtonvengaboysmuseum** [comment]
@LautaroL20 and @ZombiePwner1 - Lautaro is right, it will take the work of @TeamSpen210, @BenVlodgi and many others to pull this one off since this will be the hardest thing period to code in bee2...

**Comment by LautaroL20** [comment]
@ellingtonvengaboysmuseum - Sorry, i must have some neurons burned because i wanted to adress my previous message to ZombiePwner1, and by a mental mistake i mentioned you instead, seems i got a brain crash...

@ZombiePwner1 - Peti´s restrictions doesn´t have anything to do with this, wheels. The implementation of the exposed here depends entirely from the TeamSpen210´s skills and their decision to make it happen.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Oh wheels when will you stop being a wheely.

**Comment by Nick2007Portal** [comment]
Heck, he wants bottomless pits better... LET'S DO IT!

**Comment by Nick2007Portal** [comment]
Ellington is addicted to bottomless void holes like me!

**Comment by CreepiX987** [comment]
I'd love that.

**Comment by BenVlodgi** [comment]
I don't think this is likely to happen.

**Comment by Konclan** [comment]
I don’t think thats the point of the issue. Its a goal to work towards even if it doesn’t end as described.

**Comment by Luke18033** [comment]
Is manually customizing all of these things really necessary? It'd really clutter up Style Properties (or wherever the options are put). Most of these could just be randomized, and things like vactube objects would be based on the items in the map.

**Comment by TttGames** [comment]
So is this still an eventual possibility?

**Comment by Luke18033** [comment]
Maybe? The improved bottomless pits are planned, but as I said earlier I don't think we need to have this many different options in the UI, they'd probably just be chosen randomly or based on the map.

**Comment by Konclan** [comment]
#3891
