### ISSUE TITLE
Turret Switch Suggestion

### ISSUE THREAD

**Issue by ZipZoptheCat** [BEEmod/BEE2-items#2790]
A switch that can only be activated by being shot at with a turret. It could use the manequin model from the turret firing range sequence. You pick up a turret and point it at the mannequin. The turret shoots at the mannequin activating the input. I got this idea watching a youtube video of the Lego Dimensions Apperture Science Levels. One possible issue I foresee is if the turret constantly firing uses up too many resources?
![turret switch](https://user-images.githubusercontent.com/41752266/43689508-828d2f2e-98b0-11e8-856c-eabd4340b5eb.jpg)

**Comment by HugoBDesigner** [comment]
Still a duplicate of #2620
