### ISSUE TITLE
High Stairs Suggestion

### ISSUE THREAD

**Issue by ZipZoptheCat** [BEEmod/BEE2-items#2792]
If there was a staircase that was two voxels high but otherwise the same as the normal stairs you could place them right after the normal stairs to climb up two voxels over a 4 voxel run.

Retracted: _   _ | Wall
  Stairs one^ ^Stair two

Effectively letting you build a 4x1x2 staircase

**Comment by TeamSpen210** [comment]
The shape of panels doesn't allow them to rise that far, and we'd need to remake the animation as well. If you need really tall stairs, use a Piston Platform.
