### ISSUE TITLE
Stair blocks suggestion

### ISSUE THREAD

**Issue by ZipZoptheCat** [BEEmod/BEE2-items#2793]
Blocks much like the static ramp blocks but shaped like steps. Or a setting that let's you swap ramps between mayan style pyramids and egyption style pyramids.

**Comment by Nick2007Portal** [comment]
Use stairs without connections.

**Comment by ZipZoptheCat** [comment]
I'm talking about a stair shaped decorative item. Corner Steps, single voxel staircases and really steep steps. Like, imagine the ramp and pyramid objects we have now but as a series of 90 degree angles.

**Comment by TeamSpen210** [comment]
It's bad to have steps that steep.

**Comment by ZipZoptheCat** [comment]
The really steep ones wouldn't be for walking on probably.

**Comment by ZipZoptheCat** [comment]
I made a rough example for visualization purposes.
![example43876](https://user-images.githubusercontent.com/41752266/43881311-a1edaddc-9b60-11e8-8bd1-01762910b36d.png)

**Comment by TeamSpen210** [comment]
Thirds are a bad idea, you may have noticed that panels use a 1/4 tile system.

**Comment by ZipZoptheCat** [comment]
alright, by forths then. (How tall are unjumpable railings btw? Like the catwalk ones)
![example43877](https://user-images.githubusercontent.com/41752266/43882075-38e86180-9b63-11e8-9172-c3065630fcb2.png)

**Comment by Endermage77** [comment]
Railings? Railings I think are roughly as tall as one-and-one-fifths of a storage cube, if memory serves.

**Comment by ZipZoptheCat** [comment]
I meant in proportion to a voxel.

**Comment by Endermage77** [comment]
In voxels, I dunno.
But I do know that the storage cube is, roughly speaking, the limit, as every player in a Valve game can jump on them with crouch-jumping but can't seem to make it over anything placed on top of them.
In portal, crouch-jumping doesn't work but as a tradeoff you jump more or less the same height as a crouch-jump anyway.

**Comment by TeamSpen210** [comment]
It's about that, you can jump up a ¼ block (32 units), but not a half block (64 units). A voxel is 128 units for context, and a cube is about halfway between those two - 40 units.

**Comment by ZipZoptheCat** [comment]
So either way the 60 degree steps would be cleanly unjumpable without gel or something since each step would be half a voxel high?

**Comment by ZipZoptheCat** [comment]
You could use a cube to get up them I suppose.

**Comment by ZipZoptheCat** [comment]
So I did some rough in game checking and the players eyeline is exactly half a voxel high as near I can tell. When jumping your eyeline comes to ~7/8ths of a voxel. (Interestingly this is also the height of an upright portal at floor level.) So this means that the player can jump ~3/8ths of a voxel.

**Comment by TeamSpen210** [comment]
Indeed, player eye height is exactly ½ a voxel.

**Comment by Endermage77** [comment]
So that means a player can jump roughly 48 units high?

**Comment by ZipZoptheCat** [comment]
Mind you that's based purely on eyeballing and rough math. it might be a slightly different number.

**Comment by Endermage77** [comment]
And when you compare Chell's model size to everybody else in the source engine and realize they're all about the same height...

Raises some odd questions.

**Comment by ZipZoptheCat** [comment]
I looked into it and read a theory that a hammer unit is actually supposed to be a 12th of a foot rather than a 16th. Or in other words a hammer unit is an inch.

**Comment by ZipZoptheCat** [comment]
Oh and also corner pieces; like how angle decorative blocks have corner pieces.

**Comment by ZipZoptheCat** [comment]
I made a mock up of the 45 degree angle stairs in khed. If anyone wants the files or can tell me how to finish them please let me know.
![stairs](https://user-images.githubusercontent.com/41752266/44306287-29d72480-a340-11e8-9b74-b67fe3b93809.png)

**Comment by ZipZoptheCat** [comment]
Here are the .smd files for all the variety of stairs I made.
[smd files.zip](https://github.com/BEEmod/BEE2-items/files/2300703/smd.files.zip)

**Comment by Konclan** [comment]
Moving to #3885
