### ISSUE TITLE
Stylevar to replace mechanical elements with arms.

### ISSUE THREAD

**Issue by ZipZoptheCat** [BEEmod/BEE2-items#2794]
Since the living panel items don't fit in most styles, much the same way the gel based faith plate only shows up in old aperture, It could simply be an alt style on several items.

The following items seem most suited to this:
1: Angled Panels/Drawbridge
2: Stairs
3: Piston Platform (Only renders if traveling a short distance otherwise it becomes a piston)
4: Faith Plates (only if the faith plates are intended to be hidden I suppose)
5: Flip Panels (Maybe?)

**Comment by TeamSpen210** [comment]
I have no idea what you're suggesting. Do you mean making stuff panel arms instead of their unique appearance? That'd just make items less intuitive. There's a reason Faith Plates look different - it lets you easily identify what they will do, well before activating them.
