### ISSUE TITLE
Organic Material Crate

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2797]
Basically serves the same function as the regular storage cube, except it can trigger Lifeform Sensors.

**Comment by ZipZoptheCat** [comment]
Can it be a birdcage?

**Comment by atomic-cherry** [comment]
Well, according to Game Theory, all Companion Cubes would trigger Lifeform Sensors.

**Comment by SCIENTIST2004** [comment]
humans in Companion Cubes are DEAD

**Comment by ZipZoptheCat** [comment]
It occurs to me that if you have a cubenwith living things in it; players will try to kill it with the laser.

**Comment by King0191** [comment]
I sincerely hope you don't believe that theory... The Companion Cubes are made for you to feel bad for incinerating them (or fizzling... etc. etc.) 

The pictures of the cubes over the peoples heads... He was schizophrenic. 

But thats not part of this issue.
In my personal opinion. I don't see where this would be useful.

**Comment by TeamSpen210** [comment]
Additionally someone would need to make the models for this in all the styles, and somehow design it so the behaviour is rather obvious. And it'll only be useful with one specific other item. I don't really think this is sufficiently useful to be worth the effort.
