### ISSUE TITLE
Enrichment Sphere "bottomless" pit skybox

### ISSUE THREAD

**Issue by ZipZoptheCat** [BEEmod/BEE2-items#2798]
Is it possible to use the bottomless pit set up to replace the goo pits in the enrichment sphere with the long drop into the sphere's goo filled bottom?

**Comment by ZipZoptheCat** [comment]
Looking up while falling wouldn't match?

**Comment by Endermage77** [comment]
I think in the case of bottomless pits you'd probably have to limit it to one pit per level so there'd be enough space.

And even then it wouldn't be able to be larger than the bottom of the placeholder chamber in the sphere.

**Comment by ZipZoptheCat** [comment]
The max size is 25 by 25 voxels i think. So what if multiple pit led to the same 25 by 25 hole in the placeholder chamber? Is the placeholder 25 by 25?

**Comment by Endermage77** [comment]
Multiple pits sharing the same hole?
That'd look weird.
Besides, what would you see if you looked up after falling down?

**Comment by ZipZoptheCat** [comment]
I mean a hole as wide as the map and the actual holes all face into it bit are side by side

**Comment by Luke18033** [comment]
This will be replaced by proper chamber generation inside the sphere.
