### ISSUE TITLE
lower laser emitter and lower laser catcher

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2799]
the option "start reversed"can be applied
![20180809212039_1](https://user-images.githubusercontent.com/35931028/43956858-5fbef76e-9cae-11e8-9a8c-c5c2af349004.jpg)
![20180809212029_1](https://user-images.githubusercontent.com/35931028/43956862-630bb9d4-9cae-11e8-9b10-4aa162455cd4.jpg)

**Comment by ZipZoptheCat** [comment]
Presumably this is going to be closer to the edge of the voxel in other positions rather than strictly lower?

**Comment by Luke18033** [comment]
I already suggested this in #1499.
