### ISSUE TITLE
New Item: New Tubes! Toxic Tubes, Gel tubes + Combine in one item (read all issue)

### ISSUE THREAD

**Issue by revaru** [BEEmod/BEE2-items#2800]
**Toxic (Neurotoxin):**
![image](https://user-images.githubusercontent.com/41899094/43957014-ab1c11fe-9cbf-11e8-8ece-da7ebc20cdd3.png)
![image](https://user-images.githubusercontent.com/41899094/43957399-2678ef10-9cc1-11e8-889c-93d269bceb4e.png)
![image](https://user-images.githubusercontent.com/41899094/43957414-3504cb8a-9cc1-11e8-822c-3f586660a3b3.png)
**Gel:**
![image](https://user-images.githubusercontent.com/41899094/43957473-5d469d1c-9cc1-11e8-9edb-de195e71eb28.png)
![image](https://user-images.githubusercontent.com/41899094/43957478-62d41822-9cc1-11e8-9575-f19ebccd5fa6.png)
![image](https://user-images.githubusercontent.com/41899094/43957530-9367477a-9cc1-11e8-9cc6-bf655a7382b9.png)
You can also combine them into a **single** object, and put it so that it can be changed the look of the button as well as by the type of cube. The pipe Type _(ToxicTube, GelTube, VacTube)_ button and the cube type are the connection Type _(1x1, 2x2,3x3)_, or _Vice versa_.
_The Sphere and the monster are not used._
**(I'm almost 99% sure you'll say it's impossible, but I don't understand it, so I suggested. If this is not possible, simply create 2 new items, toxic tubes and gel tubes.)**

**Comment by ZombiePwner1** [comment]
@revaru Do not think this is easy to do we aren't going to add these items more like decorations instead.

**Comment by TeamSpen210** [comment]
We can't have cube and button type both on the same item. Also those pipes are from totally different eras, and wouldn't appear together. I already have a solution for gel tubes - a Vactube Gel Emitter which spews gel into a tube network. It'll then convert all the attached tubes to gel tubes, as appropriate for the style. I don't know what the point of neurotoxin is.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 I can really only see the point of neurotoxin fitting for BTS style but meh.
