### ISSUE TITLE
I found easter egg

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2801]
This is Sonic
on BumbleBall
![20180810232237_1](https://user-images.githubusercontent.com/35931028/43983479-5f973be8-9d03-11e8-9696-1404b1f84cb9.jpg)

**Comment by SCIENTIST2004** [comment]
![sonic-the-hedgehog-silhouette-3](https://user-images.githubusercontent.com/35931028/43983543-b80e5e96-9d03-11e8-8c6a-eb27ae2fef8e.png)

**Comment by HugoBDesigner** [comment]
Interesting but hardly issue-worthy

**Comment by SCIENTIST2004** [comment]
i don't think so
