### ISSUE TITLE
Cubes falling through Overgrown floor Observation Rooms

### ISSUE THREAD

**Issue by atomic-cherry** [BEEmod/BEE2-items#2804]
![one](https://i.imgur.com/IQjTsuM.jpg)
![two](https://i.imgur.com/ftEkvUi.jpg)

You _can_ still fish them out by crouching and activating them, but it's still just really weird.

**Comment by ZombiePwner1** [comment]
@atomic-cherry That's actually quite funny lmao but definitely will be fixed for next release.

**Comment by UncleEle** [comment]
Yes, it need to be fixed but... Who use the observation on the ceiling??

**Comment by atomic-cherry** [comment]
> Who use the observation on the floor??

Me, obviously. It can add something to break up a plain white floor, especially in a darker area.

**Comment by benjaminpants** [comment]
I think it would be funny if a cube randomly spawns in there as a joke to this glitch.
