### ISSUE TITLE
Glass panel not “packed” / blue errors for players without BEEmod installed

### ISSUE THREAD

**Issue by philhzss** [BEEmod/BEE2-items#2805]
![20180827215542_1](https://user-images.githubusercontent.com/12244376/44694510-3ba57f80-aa44-11e8-9d67-d45b35c6fc1d.jpg)

I recently published a test chamber in the overgrown style. For some reason, people who downloaded it without having BEEmod installed report “blue errors” everywhere. Someone even posted a video, it seems like it’s the glass panel that’s the issue. 

As per the FAQ, players downloading levels from the workshop shouldn’t need BEEmod 2.4 installed to play them, right? Everything should be “packed”? I had tested my map on 2 different computers before publishing and it worked fine, but both had BEEmod installed. 

Link to my map: https://steamcommunity.com/sharedfiles/filedetails/?id=1478516334

Video someone posted of my map’s errors: https://youtu.be/Quga8mPHT5g

Any idea what’s causing this? Did I not export it properly or something?

Thanks!!

**Comment by philhzss** [comment]
I did a bit more research and it seems that [issue 370](https://github.com/BEEmod/BEE2-items/issues/370) is the exact same problem I'm having. Glass panels and overgrown style. Which is weird because I have the latest release of both BEEmod and BEEmod items (pr29). Issue #370 is from 2 years ago. [Issue 168](https://github.com/BEEmod/BEE2-items/issues/168) also seems somewhat related but I'm not getting a compile error.

**Comment by philhzss** [comment]
Sorry for the triple post, but I just did some testing and hopefully it helps you identify what's going on. What I did:

- To make sure I had a "clean" setup, uninstalled BEEmod from Portal, verified integrity of game cache files in Steam, reinstalled latest pr29 BEEmod. Then:
- Created a new test chamber, overgrown style. Stuck a few glass panels at various angles, some connected to a button, some not, just to test.
- Compiled and published (as hidden, of course). Played the map, it worked fine. Everything looked good. I had one glass panel that was set as disable (unchecked "start deployed") and unconnected to a button, and it looked good. The item description says "If set to Start Disabled without any inputs connected, this will transform into a glass surface.", so all good.
- Uninstalled BEEmod from my game again. Reopened Portal 2 and played my test map (which was on the workshop, as hidden.

Result was that the "start as disabled" glass panel looked weird, and all the others were blue errors. Here's the Portal 2 console log. I've highlighted what I think could help you:


```
---- Host_NewGame ----
Network: IP 192.168.0.102, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 3092 )
Opened Steam Socket NS_CLIENT ( socket 3100 )
Network: IP 192.168.0.102, mode MP, dedicated No, ports 27015 SV / 27005 CL
Failed to load $include VMT file ((YIrials/BEE2/OVERGROWN/GLASS.vmt)
Error: Material "maps/1534366071/bee2/overgrown/glass_-2400_0_0" uses unknown shader "patch"
Host_NewGame on map workshop\964220916266480333\1534366071
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Preching movie: media\bluescreen.bik

AN ERROR HAS OCCURED [the index 'movieName' does not exist]

CALLSTACK
*FUNCTION [Call()] unnamed line [360]

LOCALS
[result] NULL
[func] CLOSURE
[args] ARRAY
[i] 0
[this] INSTANCE
Dynamic prop prop_dynamic: no sequence named:ramp_60_deg_open
Dynamic prop cp3294-model_arms: no sequence named:ramp_45_deg_open
Commentary: Could not find commentary data file 'maps/workshop\964220916266480333\1534366071_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
SignalXWriteOpportunity(3)
SignalXWriteOpportunity(3)
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
=======================Trying to GivePlayerPortalgun
=======================Trying to UpgradePlayerPortalgun
CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'
Updating sound cache [8786 entries]
Found 8626 sound files on disk
Updated 0 out of 8626 cached files [205.271 msec]
Connection to Steam servers successful.
   VAC secure mode is activated.
Redownloading all lightmaps
Setting arrival movie to media\bluescreen.bik
-------
Scaling type: 14
-------
```


As you can see, I had a few lines that seem to refer to the glass:
**Failed to load $include VMT file ((YIrials/BEE2/OVERGROWN/GLASS.vmt)
Error: Material "maps/1534366071/bee2/overgrown/glass_-2400_0_0" uses unknown shader "patch"
Dynamic prop prop_dynamic: no sequence named:ramp_60_deg_open
Dynamic prop cp3294-model_arms: no sequence named:ramp_45_deg_open**

Sorry again for all the posts and I hope this is useful. Thank you!

**Comment by LautaroL20** [comment]
I will do some self playtesting to see if it also happens to me too, because i really dislike missing model issues. Stay tunned.

**Comment by TeamSpen210** [comment]
Well, my dev version should make that impossible in future.

**Comment by philhzss** [comment]
Thanks for your hard work, both of you. And cool for the dev version making this impossible! Is it already impossible in the current dev version? I've always just used the stable pre-releases, but I'll read the guide and install the dev version later, just for fun.

**Comment by LautaroL20** [comment]
No, it is not possible in the current dev. So, installing it would just be a time waster for you because the "dev version" which is talking Spencer is about their personal computer files that were not uploaded to Github yet.

**Comment by philhzss** [comment]
Oh ok, I thought he meant the “dev” branch on GitHub. No worries, I’ll wait!

**Comment by TeamSpen210** [comment]
Yes, I have actually pushed the required stuff.

**Comment by LautaroL20** [comment]
![20180827215542_1](https://user-images.githubusercontent.com/12244376/44694510-3ba57f80-aa44-11e8-9d67-d45b35c6fc1d.jpg)
