### ISSUE TITLE
In clean style futbol spawners uses texture from original clean style

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2809]
![default](https://user-images.githubusercontent.com/35931028/44299727-448ba800-a304-11e8-86db-7b6346a90229.png)

![20180818160541_1](https://user-images.githubusercontent.com/35931028/44299726-36d62280-a304-11e8-8c30-8d8eda0d870d.jpg)

**Comment by ZombiePwner1** [comment]
@SCIENTIST2004 This is how the model always was and it never did have another texture this was the texture used for the model originally..
