### ISSUE TITLE
Beemod causes "Failure To Compile" - Help plox!!!

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2810]
console:
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr29 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "D:/steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "D:/steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'glass_scale': '0.15', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[INFO] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[WARNING] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[INFO] fizzler.read_configs(): Loaded 14 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: FORCE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 1/15 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_UPCOMING_TRIAL"
 | 	"Choreo" "scenes/npc/glados/sp_paint_jump_trampoline_completion01.vcd"
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_MEANINGLESS"
 | 	"Choreo" "scenes/npc/glados/mp_coop_radarroomend.vcd"
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 0/9 quotes..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3226, misses=360, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'doorcameras': True, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': True, 'unlockdefault': True, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[INFO] cond.core.check_all(): Global instances: set()
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding global ents...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.clump_walls(): Clumping: 240 clumps (+ 0 special)
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/tile_noise.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/tile_noise_2x1.vtf"
[INFO] vbsp.make_packlist(): "materials/bee2/clean/black_1x1.vmt"
[INFO] vbsp.make_packlist(): "materials/bee2/clean/black_1x2.vmt"
[INFO] vbsp.make_packlist(): "materials/bee2/clean/black_ceil.vmt"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_specific.nut"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "D:\steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "D:/steam/steamapps/common/Portal 2/portal2/" "D:/steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): 
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

![2](https://user-images.githubusercontent.com/35931028/44303744-79721c00-a351-11e8-913f-36fcf2a6b240.png)
![20180819015506_1](https://user-images.githubusercontent.com/35931028/44303804-07023b80-a353-11e8-8be0-4614913845a2.jpg)
![20180819013551_1](https://user-images.githubusercontent.com/35931028/44303794-8cd1b700-a352-11e8-8ef2-c0269430d953.jpg)

 maybe it's because I used old bee mod

**Comment by ZipZoptheCat** [comment]
I had a similar issue from trying to use 2.2 and 2.4 alternating.  I emded up having to do a clean install of portal and beemod.

**Comment by LautaroL20** [comment]
Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the "bin" folder inside the Portal 2 game´s directory (i'd suggest to add the whole folder in the exception´s list) because this is also the cause of certain ammount of "building error" issues...

Once you solved any possible conflicts between your antivirus and the game files, then make sure to follow the steps from below:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by LautaroL20** [comment]
That is weird...

**Comment by SCIENTIST2004** [comment]
@ZipZoptheCat how you did it.

**Comment by ZipZoptheCat** [comment]
I just erased all three programs and reinstalled them from a new download.

**Comment by SCIENTIST2004** [comment]
you mean old bee mod, new bee mod and potal 2?

**Comment by SCIENTIST2004** [comment]
does anybody know where folder with my own test chambers is?

**Comment by SCIENTIST2004** [comment]
I KNOW HOW TO FIX IT

**Comment by SCIENTIST2004** [comment]
![how to fix](https://user-images.githubusercontent.com/35931028/44313094-d1208e00-a40a-11e8-8c31-5eb0125a926b.png)
![properties](https://user-images.githubusercontent.com/35931028/44313095-d67dd880-a40a-11e8-95d2-2691c69bb676.png)
![steam 222222](https://user-images.githubusercontent.com/35931028/44313096-daa9f600-a40a-11e8-8b8c-d16e50523ba9.png)

**Comment by HugoBDesigner** [comment]
Yes, step 3 of what Lautaro told you to do:
`3 - Verify the Game Cache Files.`

**Comment by SCIENTIST2004** [comment]
Ooops...

**Comment by SCIENTIST2004** [comment]
THIS DOES NOT WORK

**Comment by SCIENTIST2004** [comment]
re open please

**Comment by SCIENTIST2004** [comment]
does anybody know where folder with my own test chambers is?

**Comment by ZipZoptheCat** [comment]
try deleting the actual folders the programs are in before installing.
