### ISSUE TITLE
Suggestion: Extra track platform features.

### ISSUE THREAD

**Issue by MacheTheFerret** [BEEmod/BEE2-items#2811]
I was attempting to make a (non-oscillating) track platform that moves when the player touches it, and reverses to its starting position when the player is no longer touching it, similar to how certain elevator platforms work. Apparently, however, that's not a feature of the current track platforms (that I'm aware of).

Perhaps there could be an "Auto-drop first cube" box on track platform items similar to the one that was added to elevator platforms a while back. If oscillating, the platform would move on player touch, and stop completely if the player is no longer touching it. If non oscillating, the platform reverses to its starting position when the player is no longer touching it.

**Comment by HugoBDesigner** [comment]
My idea is that Oscillate + Autodrop make the platform go one way when the player steps in and out, then go the other way if they return to the platform. Without oscillate, the platform only moves if powered and the player is standing on it (like with pistons)

**Comment by TeamSpen210** [comment]
Other way around for oscillate, Hugo.

**Comment by JavierNovellon** [comment]
@HugoBDesigner 

"My idea is that Oscillate + Autodrop make the platform go one way when the player steps in and out, then go the other way if they return to the platform."

Bit too late to the party, perhaps, but that can be done using Toggle Latches, XOR Gates and Trigger Multiples. I'll see if I can summarize it here but I'll also post some diagrams I made.

Suppose we have a Track Platform from Point A to Point B (horizontally or vertically doesn't matter). This Track Platform should be completely deactivated, with "Start Oscillate" and "Start Enabled" unchecked.

1. Put Trigger Multiples in Points A & B, and connect them to Toggle Latches.
2. Connect those Toggle Latches to an XOR Gate.
3. Connect that XOR Gate to another Toggle Latch.
4. Connect that final Toggle Latch to the Track Platform.

Now, Activation and Shutdown Timers, along with OR & NOT Gates, can be involved to activate doors, to prevent the player from exiting the Track Platform prematurely. This makes it behave like a somewhat realistic "lift" or "elevator" that you'd find in an apartment building or a shopping mall.

Again though, here are the diagrams I made in PowerPoint (cutting-edge technology, I know)

![Lift Figure 1](https://user-images.githubusercontent.com/47536167/64125206-2bd02200-cda1-11e9-9984-65e3e7713850.png)
![Lift Figure 2](https://user-images.githubusercontent.com/47536167/64125208-2c68b880-cda1-11e9-9536-7d5ccf689ecf.png)
![Lift Figure 3](https://user-images.githubusercontent.com/47536167/64125210-2c68b880-cda1-11e9-8e92-fa60a147d043.png)

But yes, it'd be fantastic if the Track Platform itself had an option to save everyone the headache that is building this contraption (and coming up with it in the first place)

**Comment by Libbybapa** [comment]
There's no need for any of the complicated circuits or the added auto-drop property.  Just add a trigger multiple at each of the extremes of the platform, connect one to the other and then to the platform.  It then behaves exactly as suggested.  With oscillate checked, it will oscillate whenever the player is on it.  Without it checked it will travel one direction when the player is on it and return to start when the player gets off.

**Comment by Luke18033** [comment]
Except that will trigger if the player is anywhere in that area, rather than just when they're on the platform itself.

**Comment by Libbybapa** [comment]
I see what you are saying.  Carry on.

**Comment by JavierNovellon** [comment]
@Libbybapa

@Luke18033 is referring to the exact problem I encountered when trying to build the "realistic elevator" depicted in the diagrams.

The Triggers take the space of one block (cube? Voxel? Is there a name for it?) So even if only the player's head is within that space, the Trigger will be activated. If you put one at the bottom and one at the top, the platform will oscillate between you slightly touching the Triggers.

While complicated, my contraption is the only way I know of getting around the problem. Although as @PaperPlayerX is suggesting, it would be much nicer if the Track Platform had a built-in option to solve it.

**Comment by Libbybapa** [comment]
I understand.  I do not think it would be difficult to add the trigger to the platform and add the 'auto-drop' option.
