### ISSUE TITLE
Bug: My maps will never load

### ISSUE THREAD

**Issue by Fupicat** [BEEmod/BEE2-items#2814]
I'm using BEEMOD 2.4.0pr29. Have been using it for a bit and this is the first time this has happened to me. None of the test chambers I create load, in any style. I've recorded a video to show what happened. In it, I was using the Portal 1 style with Wheatley's lines:

https://drive.google.com/file/d/1hfBnsmo4L8JzJ2y6gFm_R4kXN4RKyrHp/view

Basically what happens is, Wheatley stops talking, but the door never opens. This also happens in every other style. This started happening today, and if there's no fix, I want to know how to reverse the palette changes so I can have the default editor back.

Also, this is my first time posting. Sorry if I'm in the wrong place.

Thank you for reading.

**Comment by Konclan** [comment]
Is this still happening in pr35?

**Comment by LautaroL20** [comment]
No, i think this is a pretty much outdated issue which its real cause may not even had related to Beemod.
