### ISSUE TITLE
There should be a item that you place on a wall and it will reveal the BTS or the testing sphere on old aperture styles.

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#2816]
There should be a item that you place on a wall and it will reveal the BTS or the testing sphere on old aperture styles. It can also be made by placing 2 corners and connecting them.

**Comment by ZipZoptheCat** [comment]
yes

**Comment by ZombiePwner1** [comment]
@coolmax10 The BTS side of this should be added in the decorations that will come soon. As for the testing sphere that's abit of a hard one to do.

**Comment by coolmax10** [comment]
Instead of revealing BTS on new styles it could just be a skybox and the BTS is made through decorations. Old aperture stays the same though.

**Comment by Konclan** [comment]
#3891
