### ISSUE TITLE
portal 2 is broken?

### ISSUE THREAD

**Issue by ashtonSeantipping** [BEEmod/BEE2-items#2819]
ok...so i am testing my level before i post it and when i am loading when its done my game crashes and leaves no error

**Comment by ashtonSeantipping** [comment]
now my game also crashes when i try to try it at all

**Comment by ashtonSeantipping** [comment]
i will try to screenshot

**Comment by ashtonSeantipping** [comment]
![image](https://user-images.githubusercontent.com/43624126/46113293-ca302c80-c1bb-11e8-8ef6-a5e3dbab215f.png)

**Comment by ashtonSeantipping** [comment]
so i am using the testing arrow at the top to test it and when its done it crashes

**Comment by TeamSpen210** [comment]
Attach `Portal 2/bin/bee2/vbsp.log` and `Portal 2/bin/bee2/vrad.log`.

**Comment by LautaroL20** [comment]
If the author of this thread doesn´t reply in the upcoming days, the issue will be turn invalida then to be closed.

**Comment by ashtonSeantipping** [comment]
oh uh ok ill try it real quick

**Comment by ashtonSeantipping** [comment]
[VRAD.log](https://github.com/BEEmod/BEE2-items/files/2425897/VRAD.log)

**Comment by ashtonSeantipping** [comment]
this?

**Comment by TeamSpen210** [comment]
OH right. You can't use cameras in coop.

**Comment by ashtonSeantipping** [comment]
![image](https://user-images.githubusercontent.com/43624126/46174578-6ec37480-c277-11e8-8b20-0f0f0618f066.png)

**Comment by ashtonSeantipping** [comment]
oh pfft

**Comment by ashtonSeantipping** [comment]
close this issue
