### ISSUE TITLE
Bug found.

### ISSUE THREAD

**Issue by Nick20072008** [BEEmod/BEE2-items#2822]
If you try to inspect a light strip, bee mod EXPLODES! with a traceback error. and crashes you

**Comment by LautaroL20** [comment]
I hitted right click on all three light strips in the bee´s interface and that does not happens at all...

**Comment by Nick20072008** [comment]
Happens to me.

**Comment by LautaroL20** [comment]
Send screenshots of the interface when that issue happens, add aditional details like which one of the three light is causing it, because your current post description is really insufficient to identify the issue.
