### ISSUE TITLE
[Missing Resource] Missing preview pictures for entrances/exits

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#2830]
Portal 1 entrance:
![image](https://user-images.githubusercontent.com/6296061/46577883-6e3d8300-c9c7-11e8-8692-e5bd9387f5d0.png)
Portal 1 exit:
![image](https://user-images.githubusercontent.com/6296061/46577884-74cbfa80-c9c7-11e8-8a46-b79c98621ca7.png)
Portal 1 exit (coop):
![image](https://user-images.githubusercontent.com/6296061/46577887-7e556280-c9c7-11e8-99e6-90b012d10866.png)

BTS exit:
![image](https://user-images.githubusercontent.com/6296061/46577868-1a329e80-c9c7-11e8-813f-b24507dcef24.png)
BTS exit (coop):
![image](https://user-images.githubusercontent.com/6296061/46577871-24549d00-c9c7-11e8-950b-84434cee552c.png)

**Comment by TeamSpen210** [comment]
The BTS ones are because those corridors haven't been implemented.

**Comment by HugoBDesigner** [comment]
Shouldn't they have the "(Not present)" tag like the entrances, then?
![image](https://user-images.githubusercontent.com/6296061/46584176-6f59c900-ca36-11e8-930b-b1c24e8afe1c.png)
