### ISSUE TITLE
[Bug] Radiative Flux Rectangle not working

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#2831]
Instead of the regular field, we get what I assume is the lifeform sensor. Except it doesn't work with either pellets or the player:
![portal2_2018-10-07_01-57-44](https://user-images.githubusercontent.com/6296061/46578363-2291d600-c9d5-11e8-92ab-065fdab343eb.png)

In-editor (yes, it has the fizzler output entity on top)
![image](https://user-images.githubusercontent.com/6296061/46578360-1c9bf500-c9d5-11e8-9f63-859f2a880ccc.png)

(Only tested with Portal 1's style)

**Comment by TeamSpen210** [comment]
That is the flux rectangle. Check what timer setting you're using, it behaves differently with timer/infinite.

**Comment by HugoBDesigner** [comment]
Neither option seems to work
