### ISSUE TITLE
Fullbright Problem

### ISSUE THREAD

**Issue by benjaminpants** [BEEmod/BEE2-items#2834]
Beemod Pr30, Pr29 did not work at all, now it works slightly, it goes into fullbright. I cant disable it. Trust me I tried. No elements are placed, default settings.
![image](https://user-images.githubusercontent.com/6296061/46586023-d1262d00-ca4e-11e8-8609-895850d83374.png)

**Comment by benjaminpants** [comment]
Any, help?

**Comment by benjaminpants** [comment]
Got the log! https://pastebin.com/Cvesh6Di

**Comment by benjaminpants** [comment]
Still, I tried hammer, but it just crashes when beemod is installed

**Comment by Nick20082009** [comment]
Your chamber failed to use HDR lighting, it also failed using original lights, so RAD forced it into fullbright, reinstall BEEmod.

**Comment by Konclan** [comment]
Don't think this is an issue anymore whatever was causing it
