### ISSUE TITLE
Not gates act as Or gates

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#2835]
If I connect a Trigger Once -> Not Gate -> Entity (for instance, a door, or an autoportal), the latter will only activate when I get through the fizzler, instead of being active *until* I get through the trigger.

**Comment by ZombiePwner1** [comment]
@HugoBDesigner No need for the [Bug] Title we stopped putting it in issues a long time ago since it was annoying.

**Comment by HugoBDesigner** [comment]
It might not be strictly necessary, but I don't see how that's a bad thing. Makes it easier to identify the nature of the issue, especially if seen from Discord's embeds, where there is no room for tags.
