### ISSUE TITLE
Portal 1/70´s Old Aperture: It does not pack "Cubemaps" when publishing maps on CO-OP Mode

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#284]
70´s Old Aperture: 

![buildcubemaps mode disabled in co-op mode of 70 s old aperture](https://cloud.githubusercontent.com/assets/12244376/12938053/a955594a-cf8d-11e5-8a9b-ec261ddf7aaf.jpg)

**Comment by BenVlodgi** [comment]
lol, does give it more of a p1 feel :)

**Comment by Luke18033** [comment]
@BenVlodgi No it doesn't...

**Comment by ZombiePwner1** [comment]
Honestly atlas and p-body themselves look horrible without env_cubemaps

**Comment by LautaroL20** [comment]
Edited: It seems that env_cubemaps is not packed even when the map is published on 70´s old.

**Comment by ZombiePwner1** [comment]
Funny enough my escape map doesn't even have any envcube maps in it and things still rendered properly.

**Comment by Konclan** [comment]
Is this fixed?

**Comment by TeamSpen210** [comment]
No, I have no idea why it happens.

**Comment by Luke18033** [comment]
I saw something about fixed cubemaps in the "pushed commits" email notification, so maybe it's fixed now?

**Comment by TeamSpen210** [comment]
It should be, but coop seems to be broken for me so I can't check.

**Comment by Luke18033** [comment]
It's not fixed on P1.

**Comment by LautaroL20** [comment]
Well, that commit doesn´t solve this issue at all, idk what that commit fixes.

**Comment by Luke18033** [comment]
For whatever reason, after making an actual map (as opposed to just compiling the default chamber), it's fixed now. Strange.

**Comment by TeamSpen210** [comment]
This appears to be fixed now. It's to do with a map missing any `env_cubemap`s in it. If you placed items which happened to contain those, it fixed itself.

**Comment by TeamSpen210** [comment]
@LautaroL20 can you check if it's fixed for you?

**Comment by LautaroL20** [comment]
Alright, ill do it in a moment.

**Comment by LautaroL20** [comment]
I can confirm that the 70´s Old Aperture  Coop cubemaps is fixed now. However, it was impossible to check in the P1 Style since both robots becomes "Stagnant Forever" in a totally black screen :/
