### ISSUE TITLE
Loose Panel

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2843]
A 1-voxel wide panel which is loose and not attached to any particular object. Can be painted, moved, picked up, and (notwithstanding the developer's un/willingness to attempt despite bugginess) portaled on. However, the item itself is too large to fit through a portal.

An alternative version is a loose panel that is propped (read: forced to stay) upright by a stand of some sort.

A possible implementation of the stand variant is to make it an Angled Panel type in the game so one can set which way it faces and what angle its face is relative to the floor.

**Comment by Konclan** [comment]
UCP
