### ISSUE TITLE
[Compile Error] Chamber does not recompile in 2.4

### ISSUE THREAD

**Issue by Vladg24YT** [BEEmod/BEE2-items#2845]
DEV console log:
`Vladg24 unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (11,12,14)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 89 (ms)
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561197960496560\autosave.p2c

VBSP failed.

[I] vbsp.main(): BEE2.4.0pr30 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'fizz_visiblity': '0', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (293 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[W] connections.add_item_inputs(): Item "lg77" was not optimised out!
[I] connections.add_item_inputs(): LOGIC counter: lg77
[I] connections.add_item_inputs(): LOGIC counter: lg97
[I] connections.gen_item_outputs(): Item IO generated.
[I] brushes.res_import_template(): IDS: set()
[W] packing.pack_list(): Packlist "PACK_P1_DOOR" does not exist!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1426 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1464 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (69 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (86 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (225 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (242 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (382 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (399 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (531 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (548 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (698 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (715 in final) is not on grid!
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[W] barriers.test_hole_spot(): No center barrier at 960 576 1472, 0 1 -0
[W] barriers.test_hole_spot(): No center barrier at 960 704 1472, -0 -1 0
[W] packing.pack_list(): Packlist "PACK_P1_METAL_LIFT" does not exist!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] packing.pack_list(): Packlist "PACK_P1_DOOR" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_CONC_RECESSED_LIGHTS" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_CAMERA" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_CAMERA" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_CAMERA" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_OBS_ROOM" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_OBS_LIGHT" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_PANEL_SOUNDS" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_METAL_LIFT" does not exist!
[W] packing.pack_list(): Packlist "BEE2_P1_LIGHT_HOLE_MODEL" does not exist!
[W] packing.pack_list(): Packlist "BEE2_P1_LIGHT_HOLE_MODEL" does not exist!
[W] packing.pack_list(): Packlist "P1_TIM_SOUND" does not exist!
[W] packing.pack_list(): Packlist "P1_PED_BUTTON" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_BUTTON_SND" does not exist!
[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.
[I] vbsp.set_elev_videos(): Elevator type: NONE
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.find_group_quotes(): "ENTRY": 3/15 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "DEADLY_1"
 | 	"Choreo"
 | 		{
 | 		"1" "scenes/npc/glados/mp_coop_paint_redirect07.vcd"
 | 		"2" "scenes/npc/glados/mp_coop_paint_redirect08.vcd"
 | 		}
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "EXIT": 2/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "DEADLY_1"
 | 	"Choreo" "scenes/npc/glados/mp_coop_wall_block03.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 1/9 quotes..
[I] voiceLine.add_voice(): 1 Mid quotes
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"Name" "Cave Reactions"
 | 	"File" "clean/cave_reaction.vmf"
 | 	}
 | 
 |___

[I] voiceLine.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: N, Orange: N
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['fizzler', 'glass', 'cube', 'cubestandard', 'cubedropper', 'cubedropperstandard', 'cubenotcompanion', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'blueportal', 'blueportalspawner', 'blueportalgun', 'singleportalgun', 'orangeportal', 'orangeportalspawner', 'autoportal', 'pedestalbutton', 'pack_p1_radio_clean', 'deadly', 'neurotoxin', 'neurotoxintimer', 'spawn_nogun']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=42261, misses=359, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'doorcameras': True, 'p1_ported_pgun': True, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': True, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/p1/set_portalgun.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 0 <- Counter()
[I] vbsp.change_brush(): Adding Goo Mist...
[I] vbsp.change_brush(): Done!
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] barriers.make_barriers(): Adding Glass floor beams...
[I] barriers.make_barriers(): Done!
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Steam/steamapps/common/Portal 2/portal2/', 'C:/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <Valve>.run_compiler(): Valve Software - vbsp.exe (May 30 2013)
[I] <Valve>.run_compiler(): 2 threads
[I] <Valve>.run_compiler(): materialPath: C:\Steam\steamapps\common\Portal 2\portal2\materials
[I] <Valve>.run_compiler(): Loading C:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <Valve>.run_compiler(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <Valve>.run_compiler(): Could not open instance file instances/BEE2/logic/bee/logic_nor.vmf
[I] <Valve>.run_compiler(): `

I tried deleting and Re-exporting the pallete. I also checked my files, but the error still occures. 
I have modified some Export Options: I changed the music, changed to Portal 1 style.
The pallete and map screenshot is below. What shall I do? 
![image](https://user-images.githubusercontent.com/35247077/47252559-85f91a80-d44f-11e8-8328-8f4c2c3d1387.png)

**Comment by Vladg24YT** [comment]
_Note:_ I'm using the **Portal 2 SP + MP NSIS RePack** which uses the Luma Emulator instead of Steam, can it cause the error?

**Comment by LautaroL20** [comment]
Do not mix other mods while using Beemod. Once you unistalled any other mod, you will have to follow some steps carefully to ensure you will not get any building errors: 

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - Make sure to save these steps in a text file in case you get similar issues in the future.

9 - Happy mapmaking!
