### ISSUE TITLE
Laserfield causes "Failure To Compile"

### ISSUE THREAD

**Issue by Entity447** [BEEmod/BEE2-items#2846]
```
VBSP failed.

[I] vbsp.main(): BEE2.4.0pr30 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'use_screenshot': '1', 'glass_scale': '0.15'}
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Using random SP Entry (7)
[I] vbsp.mod_entryexit(): Using random SP Exit (4)
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (722 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (924 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1083 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1193 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1297 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1401 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1512 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[I] brushes.res_import_template(): IDS: set()
[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.
[I] vbsp.set_elev_videos(): Elevator type: RAND
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['goo', 'laserfield', 'laser', 'deadly', 'fizzler', 'glass', 'grating', 'cube', 'cubereflect', 'cubedropperlessreflect', 'cubenotcompanion', 'cubestandard', 'cubedropperlessstandard', 'SpeedGel', 'OrangeGel', 'Gel', 'cubesphere', 'cubedropper', 'cubedroppersphere', 'cubesphereshaped', 'funnel', 'excursionfunnel', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'cubebutton', 'ballbutton', 'gel', 'speedgel', 'orangegel', 'bouncegel', 'bluegel', 'lasercatcher', 'laserrelay', 'pistonplatform', 'piston', 'panel', 'turret', 'laseremitter', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=98697, misses=377, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'doorcameras': True, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: set()
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 96.0 <- Counter({96.0: 55})
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <Valve>.run_compiler(): Valve Software - vbsp.exe (Mar  1 2018)
[I] <Valve>.run_compiler(): 4 threads
[I] <Valve>.run_compiler(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <Valve>.run_compiler(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <Valve>.run_compiler(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <Valve>.run_compiler(): Could not open instance file instances/bee2/clean/items/fizzler/barrier_hazard_base.vmf
[I] <Valve>.run_compiler(): 
[I] <Valve>.run_compiler(): 
```

**Comment by HugoBDesigner** [comment]
Please try following the instructions from here:
https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod

And if you're still getting an error, follow the instructions from here:
https://github.com/BEEmod/BEE2-items/wiki/How-to-report-compiler-errors

**Comment by Entity447** [comment]
Thanks. I'll put the console error on my github issue page as well.

**Comment by Entity447** [comment]
The console error:

RTAL2 PUZZLEMAKER]  Compilation time (after export): 330 (ms)

VBSP failed.

[I] vbsp.main(): BEE2.4.0pr30 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'use_screenshot': '1', 'glass_scale': '0.15'}
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Using random SP Entry (7)
[I] vbsp.mod_entryexit(): Using random SP Exit (4)
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (722 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (924 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1083 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1193 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1297 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1401 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1512 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[I] brushes.res_import_template(): IDS: set()
[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.
[I] vbsp.set_elev_videos(): Elevator type: RAND
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['goo', 'laserfield', 'laser', 'deadly', 'fizzler', 'glass', 'grating', 'cube', 'cubereflect', 'cubedropperlessreflect', 'cubenotcompanion', 'cubestandard', 'cubedropperlessstandard', 'SpeedGel', 'OrangeGel', 'Gel', 'cubesphere', 'cubedropper', 'cubedroppersphere', 'cubesphereshaped', 'funnel', 'excursionfunnel', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'cubebutton', 'ballbutton', 'gel', 'speedgel', 'orangegel', 'bouncegel', 'bluegel', 'lasercatcher', 'laserrelay', 'pistonplatform', 'piston', 'panel', 'turret', 'laseremitter', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=98697, misses=377, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'doorcameras': True, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: set()
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 96.0 <- Counter({96.0: 55})
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <Valve>.run_compiler(): Valve Software - vbsp.exe (Mar  1 2018)
[I] <Valve>.run_compiler(): 4 threads
[I] <Valve>.run_compiler(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <Valve>.run_compiler(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <Valve>.run_compiler(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <Valve>.run_compiler(): Could not open instance file instances/bee2/clean/items/fizzler/barrier_hazard_base.vmf
[I] <Valve>.run_compiler(): 
[I] <Valve>.run_compiler():

**Comment by LautaroL20** [comment]
Your problem has to do with a fizzler type which is causing failure to compile, try removing the fizzlers from your map until PRL31 comes out. For more information, check this other issue where another user was having the same issue as you: https://github.com/BEEmod/BEE2.4/issues/1000

**Comment by Tekameikite** [comment]
@Entity447 how did you fix it?

**Comment by Entity447** [comment]
I'm not sure. I re-installed the mod and for some reason it was fixed.

**Comment by TeamSpen210** [comment]
These items have been remade for a long time, this error isn't possible anymore.
