### ISSUE TITLE
Portal1 Unstationary Scaffold texture issues

### ISSUE THREAD

**Issue by spygineer** [BEEmod/BEE2-items#2847]
I've noticed that the Portal1 Unstationary Scaffold have some texture issues.
Here is an image of the issue:
https://gyazo.com/3e7502f78a764c1b0d73f0b0c8e23304

**Comment by Overwatch-C-17** [comment]
This issue same as issue I already report before this one. It's emitting full bright

**Comment by LautaroL20** [comment]
@Overwatch-C-17 - "Full bright" is wrong described, because this is just about a missing texture.
