### ISSUE TITLE
deadly goo is invisible

### ISSUE THREAD

**Issue by t1211** [BEEmod/BEE2-items#2848]
when I place the deadly goo and build the map, in play mode its invisible and the floor is missing, so instead of the floor, it's just the skybox. I know its there though because it still kills me if I jump into it.

**Comment by LautaroL20** [comment]
Please, next time when you report an issue make sure to provide much more details because your current post does not help to find out where or what is causing the bug. We need to know the style you were using for it, items, etc. 

However to solve your issue you can try out the following:

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - Make sure to save these steps in a text file in case you get similar issues in the future.

9 - Happy mapmaking!

**Comment by t1211** [comment]
I will try all of those things. I apologize for not giving many details, I didn't have many that I could give. I couldn't find anything that could be causing the issue, online or in game. removing the goo would fix the floor but with it there it was like the goo texture was missing entirely. if the following fixes it I'll let you know so you guys can mark it as fixed

**Comment by t1211** [comment]
so far nothing has fixed the issue. my guess is bee2 has an enhanced version of the goo and is trying to replace portal 2's version, but instead of replacing its just deleting it, validating the cache puts it back but b2 deletes it again when i export. here is my console incase that will help anything
NET_GetBindAddresses found 192.168.2.22: 'Intel(R) Dual Band Wireless-AC 3168'
Opened Steam Socket NS_SERVER ( socket 2732 )
Opened Steam Socket NS_CLIENT ( socket 2728 )
Network: IP 192.168.2.22, mode MP, dedicated No, ports 27015 SV / 27005 CL
Parent cvar in client.dll not allowed (movement_anim_playback_minrate)
Game supporting (2) split screen players
maxplayers set to 1
Steam config directory: D:\steam2\steamapps\common\Portal 2\portal2.exe\platform\config
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/change_this
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/gesture_smallwave
Unknown command "cl_thirdperson"
Unknown command "joy_no_accel_scale"
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: lock_cmd
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: unlock_cmd
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_Activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_Deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Force
Didn't find Active Steam Controller to Load Menu Controls
Unknown command "cl_thirdperson"
C_GameInstructor::ReadSaveData failed to read GI.lesson.Swap_Split_Screen_Control
[PORTAL2 PUZZLEMAKER]  Loaded puzzle puzzles\76561198063297458\1540302776.p2c
Unknown command "cl_puzzlemaker_activate"
[PORTAL2 PUZZLEMAKER]  Loaded puzzle puzzles\76561198063297458\1540302776.p2c
CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.2.22, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 3552 )
Opened Steam Socket NS_CLIENT ( socket 3432 )
Network: IP 192.168.2.22, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\1540302776/c-2400_0_0.hdr' -- Trying non HDR 'maps\1540302776/c-2400_0_0'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1540302776/c-2000_2000_-48.hdr' -- Trying non HDR 'maps\1540302776/c-2000_2000_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1540302776/c-2032_-1968_-31.hdr' -- Trying non HDR 'maps\1540302776/c-2032_-1968_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\76561198063297458\1540302776
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named cd632626-cube_addon_*, which point_template cd632626-cube_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker\76561198063297458\1540302776_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Connection to Steam servers successful.
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
   VAC secure mode is activated.
Player 
Player 
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/steam2/steamapps/common/Portal 2/portal2/puzzles\76561198063297458\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/steam2/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (25,14,8)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 137 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 11887 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 12078 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VRAD): 25999 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (complete): 26158 (ms) ...launching map!
Error: Operator stop_entry, unknown sound operator attribute input_start
---- Host_Changelevel ----
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named cd20-cube_addon_*, which point_template cd20-cube_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker/preview_commentary.txt'. 
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Unknown command "cl_puzzlemaker_start_previewing"
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
=======================Trying to GivePlayerPortalgun
=======================Trying to UpgradePlayerPortalgun
Updating sound cache [8701 entries]
Found 8697 sound files on disk
Updated 0 out of 8697 cached files [372.315 msec]
Redownloading all lightmaps

AN ERROR HAS OCCURED [the index 'signName' does not exist]

CALLSTACK
*FUNCTION [StopVideo()] video_splitter_bsod.nut line [23]
*FUNCTION [StopArrivalVideo()] video_splitter_bsod.nut line [7]
*FUNCTION [main()] InputRunScript line [1]

LOCALS
[height] 2
[width] 23
[videoType] 0
[this] TABLE
[height] 2
[width] 23
[this] TABLE
[this] TABLE
SAVEGAME:  928.7kb,  361.1kb used by 827 entities (puzzlemaker/preview)
SAVEGAME:   58.4kb,   33.9kb used by 422 entities (puzzlemaker/preview)
SAVEGAME:    1.0kb,    0.0kb used by   0 entities (puzzlemaker/preview)
SAVEGAME:  929.0kb,  360.6kb used by 827 entities (puzzlemaker/preview)
SAVEGAME:   65.4kb,   38.3kb used by 475 entities (puzzlemaker/preview)
SAVEGAME:    1.0kb,    0.0kb used by   0 entities (puzzlemaker/preview)
Unknown command "cl_puzzlemaker_start_editing"
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/steam2/steamapps/common/Portal 2/portal2/puzzles\76561198063297458\autosave.p2c
完全にお尻に中毒 unpaused the game

**Comment by t1211** [comment]
it also turns out that the elevator doesnt restart the level in build and play mode, and im also noticing a bunch of purple highlights like there are errors. i noticed them when my brother was playing so it may be unrelated but i figured i'd mention it

**Comment by LautaroL20** [comment]
Just an observation, while installed and using Bee2.4 PRL30, do not use other mods that could get in conflict with the Portal 2´s files resulting in building errors and other issues. Don´t mix with other mods.

**Comment by t1211** [comment]
i dont have any other mods on there. its a fresh install on a new laptop, and the only thing i downloaded for the game was bee2.4 package and application.

**Comment by t1211** [comment]
the only other portal 2 mod i know of is beemod but im pretty sure thats just bee2 lite, and i only put that on my other computer, but i think i removed it when i found bee2 anyway

**Comment by t1211** [comment]
is...is that it or..?

**Comment by LautaroL20** [comment]
I will repeat it once more, when you open an issue you must have to provide as much information as possible such as which items, style you were using at the time you were experiencing the issue. Because your current is not useful at all to find out where or what is causing your trouble.

 If you are not willing to understand this, it would be better for you to save your time at open insubstantial reports, as well as for me to having to close them and causing it to continue fill up the "closed issues" section...

**Comment by t1211** [comment]
from what ive seen it happens on clean and original clean, i havent tested the others yet. thats the only other piece of information i have. i apologize for taking so long to mention it

**Comment by LautaroL20** [comment]
I'm starting to think that this is a joke of a bad taste... We also need to know which items did you place in your map, by only knowing the Style information is not enough. If you get a pair of glasses, i have written in more than one comment that not only the Style information is required, but also which items you used in your map at the time you have experienced your issue.

**Comment by t1211** [comment]
it's not a joke in bad taste, the map is on the workshop. I had my brother download it on his computer and it had the same problem on the map as well meaning the map itself compiled without the texture because for some reason beemod removed it when loading a custom pallet. . 
![image](https://user-images.githubusercontent.com/36489606/47642601-73fa3480-db3f-11e8-9d3c-251442e52f9b.png)  this was the pallet I had at the time of the error if memory serves correctly. 
![image](https://user-images.githubusercontent.com/36489606/47642737-c89daf80-db3f-11e8-8cde-705c4890a3a3.png) here is a picture of the map without the goo. the only time it actually showed up properly was if I launched the game without exporting a custom pallet.

**Comment by t1211** [comment]
![image](https://user-images.githubusercontent.com/36489606/47642995-8c1e8380-db40-11e8-92df-cf9009ddf044.png)
 here is the map on the steampage, you can see on the left that the file was supposed to have goo there but it isnt showing up on the actual map. https://steamcommunity.com/sharedfiles/filedetails/?id=1547262470 thats a link so you can run the map yourself, if you need that as well.

**Comment by LautaroL20** [comment]
In the first image you posted which is a picture of your palette items, there are missing some items that in your workshop image are like autoportals. However, my final guess for this is that the cause of your leak is due to an item placed somewhere which is causing the leak in the goo (Maybe autoportals?), it would be a matter to do a check item per item to see which one is causing it.

**Comment by t1211** [comment]
i'll make a map tonight and test out different items and report back which ones caused the errors

**Comment by LautaroL20** [comment]
@t1211 - The problem that is causing your issue is due that you are using a wrong skybox, just select the "Clean" in the skybox option from the Bee´s user interface and it should not happens anymore.
