### ISSUE TITLE
"Piston Platform" can't fully extended until triggering it 3-4x

### ISSUE THREAD

**Issue by Overwatch-C-17** [BEEmod/BEE2-items#2850]
This bug occur when you set the platform movement to "Lower -> Raise". Either player step on to the platform or trigger linked platform have same result.

**Comment by Luke18033** [comment]
Is this like #2636? That should have been fixed in Pr30, although you're saying it happens with platforms that start down...
Regardless, you'll probably want to follow [these steps](https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod) and see if it fixes your issue.

**Comment by LautaroL20** [comment]
Indeed, pretty sure it has to do with old resources from past releases not being overwritten by new ones from Prl30, resulting in bugs that were fixed still being present and some things not working correctly.

**Comment by Overwatch-C-17** [comment]
Ah I'll do re-install of BEE later or I probably just wait for PR 31.

**Comment by LautaroL20** [comment]
@Overwatch-C-17 Make sure to follow this guide https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod step by step and that'll sure will fix your issue if you do it correctly.

**Comment by LautaroL20** [comment]
If you decide to follow the guide, make sure to confirm us you solved the issue so we can close the report.

**Comment by Overwatch-C-17** [comment]
Issue fixed!
