### ISSUE TITLE
Make P1 style look more P1ish.

### ISSUE THREAD

**Issue by Nick20082009** [BEEmod/BEE2-items#2852]
I am literally able to different a BEE map with a hammer map.
So here we go.
1. Use proper tonemaps, colour correction, shadowcontrol to make a illusion of P1
2. Port EVERY SINGLE SOUND, from P1. (Done)
3. Use less lighting, but make it more bright, and make it a bit white. Because this makes the very much in chambers visual.
4. Ambient sounds, ambient, air, and once more, ambient sounds. Port them from P1, and etc. I liked those creepy slow sounds, and i liked the air ambients. Re-add them.
5. Finally, make orange holes emit more light (can be done with entities) and don't make a little borders between them, it looks ugly and they must combine together, this should be controlled by a alternative version.

Now my advices for making the chamber stylish are done.

**Comment by Nick2008200920102011** [comment]
> I am literally able to different a BEE map with a hammer map.
> So here we go.
> 
> 1. Use proper tonemaps, colour correction, shadowcontrol to make a illusion of P1
> 2. Port EVERY SINGLE SOUND, from P1. (Done)
> 3. Use less lighting, but make it more bright, and make it a bit white. Because this makes the very much in chambers visual.
> 4. Ambient sounds, ambient, air, and once more, ambient sounds. Port them from P1, and etc. I liked those creepy slow sounds, and i liked the air ambients. Re-add them.
> 5. Finally, make orange holes emit more light (can be done with entities) and don't make a little borders between them, it looks ugly and they must combine together, this should be controlled by a alternative version.
> 
> Now my advices for making the chamber stylish are done.

Forgot to say, that NEVER, EVER, EVER USE ENV_PROJECTEDTEXTURE. That ruins the effect of P1, in some places you can use it, but set quality to low. And disable shadows.

**Comment by Nick2008200920102011** [comment]
And, port EMP sounds from hl2 and the "electro ball" sprite from p1 and use them for catchers

**Comment by Nick2008200920102011** [comment]
Add some diversity to P1 corridors, doorless exits, entrances, fizzlerless entrances....

**Comment by TeamSpen210** [comment]
The catchers do use the original sounds...

**Comment by Nick2008200920102011** [comment]
Oh, i forgot. Do clean and others do too?

**Comment by Nick2008200920102011** [comment]
Well make them louder then.

**Comment by Nick2008200920102011** [comment]
And make the lighting a bit bluish brighty white

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.

**Comment by Luke18033** [comment]
@LautaroL20 If someone doesn't apply labels to a closed issue, can you please just apply them yourself and move on? I'd prefer not to get 5000 notification emails containing the same copy-pasted message.

**Comment by LautaroL20** [comment]
Alright, considering that @TeamSpen210 removed the label ive applied without a reason and he does not even changed it to "invalid", i can see that he does not care at all clarifying the reason of an issue closure, so i will not waste my time anymore at posting the message...
