### ISSUE TITLE
Franken cubes can activate wall cube buttons from  the bottom 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2853]
![capture 33](https://user-images.githubusercontent.com/31172185/47957131-bd96b500-df6d-11e8-9ab7-91cd9ab11d51.PNG)

**Comment by ZombiePwner1** [comment]
@BETTEREXTENEDEDITORMOD That is most likely a bug with the franken turrets hitbox which I don't think we can change.

**Comment by LautaroL20** [comment]
ZombiePwner1 - The collider box can be modified thru Blender wheels, but command to pack it in the map will be required.

**Comment by Luke18033** [comment]
I don't think there's much we can do about this. Changing the collision doesn't seem like it would really help, and frankenturrets can't have their models changed anyway.

**Comment by LautaroL20** [comment]
So, this is most likely a Valve´s bug.

**Comment by TeamSpen210** [comment]
Yeah, we can't do anything about this.
