### ISSUE TITLE
The reflections from the Piston of the P1 Stairs aren´t working.

### ISSUE THREAD

**Issue by Cookiejae** [BEEmod/BEE2-items#2854]
I've been having this issue for ever since when BEE2 contained Portal 1, the Pistons of the P1 Stairs does not reflect anything... see image:

![PISTON](https://user-images.githubusercontent.com/12244376/48055290-ff9e4180-e18d-11e8-9ad7-2dac729039d7.png)

Please fix this in the next release if possible.

**Comment by LautaroL20** [comment]
If their pistons are not a texture, but a model then it could be fixeable via a lighting origin or something else. However, if it is a brush texture then it´s irremediable.

**Comment by Cookiejae** [comment]
It's more than the stairs, 
![image](https://user-images.githubusercontent.com/44789701/48065505-86ecb480-e190-11e8-8394-d92be4703550.png)
I think I remembered fixing them, but I don't remember how.

**Comment by Cookiejae** [comment]
Oh yeah, and this too.
![image](https://user-images.githubusercontent.com/44789701/48077207-72b6b080-e1ac-11e8-9a4f-af20a82bfa4c.png)

**Comment by TeamSpen210** [comment]
This looks like the special cubemap file for the pistons isn't included.

**Comment by Cookiejae** [comment]
Is this gonna be fixed in the next release?

**Comment by ZombiePwner1** [comment]
@Cookiejae Well yes? We don't leave issues that can be fixed un-fixed.

**Comment by ZombiePwner1** [comment]
@Cookiejae Also I do have a custom made texture for this that replaces portal 2's default piston arms with this: https://steamcommunity.com/sharedfiles/filedetails/?id=1280692223

**Comment by Cookiejae** [comment]
Is it downloadable?

**Comment by Cookiejae** [comment]
Oh hey, I fixed it. It was due to the mat_specular being 0. Now, how do I make it 1 permanently?

**Comment by TeamSpen210** [comment]
I have no idea why you turned off reflections...

**Comment by Cookiejae** [comment]
@TeamSpen210 I didn't. It was like that when I played Portal 2.

**Comment by Cookiejae** [comment]
I didn't even know that it existed until now.

**Comment by Luke18033** [comment]
Not an actual issue
