### ISSUE TITLE
Wrong Stripes orientation on the "Middle / Low window" when they are attached on Walls

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#286]
The Middle and Low variants of the Window item doesn´t keep the horizontal stripes position when attached on Walls:

![Image](https://cloud.githubusercontent.com/assets/12244376/12938279/51dc5c92-cf90-11e5-925c-99b8e5f33646.jpg)

**Comment by Luke18033** [comment]
I think this is fixed now?

**Comment by LautaroL20** [comment]
Idk, i didn´t test this in a while.

**Comment by LautaroL20** [comment]
I know why this wasn´t fixed yet, it will require a special config to always keep the horizontal orientation when attached to each Wall´s Axis because otherwise, Stripes position go literally nuts.

**Comment by ZombiePwner1** [comment]
@LautaroL20 is this is an issue with the little glass windo item on walls?

**Comment by LautaroL20** [comment]
Yes.

**Comment by Konclan** [comment]
Still an issue in pr36
![20190828204250_1](https://user-images.githubusercontent.com/16567080/63903803-7124d600-c9d4-11e9-98c1-3295ac360b21.jpg)

**Comment by Luke18033** [comment]
Still an issue...
![image](https://user-images.githubusercontent.com/19228201/91225683-de973f80-e6d8-11ea-9e09-785389dec4b7.png)
...though the compiler does seem to be doing something with the texture, so maybe TeamSpen tried to fix this and it didn't work? I'll take a look.

**Comment by Luke18033** [comment]
Okay, looks like this is still using separate instances for the vertical and horizontal glass. It should definitely be switched to a template.

**Comment by LautaroL20** [comment]
> Okay, looks like this is still using separate instances for the vertical and horizontal glass. It should definitely be switched to a template.

Go ahead, i remember myself trying to fix this issue by early 2018 without sucess because the compiler and config file possibilities weren´t too robust as they are right now. I did not revisit this issue since a long time but i hope that this should be easier to fix than it was before.
