### ISSUE TITLE
White/Black Track Platform

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#2861]
Much like the pistons currently have the "Cube Type" property that defines its surface properties, oscillating rail platforms could have those as well. This idea is briefly mentioned in the comments of #2753 but isn't focused on much.
![image](https://user-images.githubusercontent.com/6296061/48586468-30614200-e917-11e8-9b30-68d96ca0e8f0.png)
The advantages are that you could carry gel with the black variant, and have a movable portal surface with the white one (essentially a more elegant way of having a pair of interchangeable flip panels).

**Comment by Nick2008200920102011** [comment]
where do you get these

**Comment by HugoBDesigner** [comment]
Nowhere. It's an item suggestion

**Comment by Nick2008200920102011** [comment]
so these are actually just models you edited?

**Comment by HugoBDesigner** [comment]
Edited image
