### ISSUE TITLE
New item suggestion 

### ISSUE THREAD

**Issue by DylanKTV** [BEEmod/BEE2-items#2869]
So recently I've been thinking BEE2 needs a prop item. The prop item works similarly to the sign item but instead you get chairs,desks,etc. Basically cosmetic props for BTS levels. If you can't or just don't want to thats okay but I feel as if it is a good idea.

**Comment by MarcusKubis9** [comment]
hey man hit me up on discord and we can start talking about this

**Comment by Konclan** [comment]
UCP
