### ISSUE TITLE
LIFEFORM SENSOR (HELP)

### ISSUE THREAD

**Issue by richter24** [BEEmod/BEE2-items#2873]
It can not connect to any fizzler.

or maybe I do not know how to use it

can somebody saaaaaave meeeee?

**Comment by Endermage77** [comment]
The Lifeform Sensor is a fizzler type, and thus can't output anything on its own.

You will need the Fizzler Output item (It may be called something slightly different) placed on the wall next to the fizzler, and take your output from _that_ in order for the Lifeform Sensor to work.
