### ISSUE TITLE
Portal Stories: Mel music not showing up.

### ISSUE THREAD

**Issue by TheLoafLord** [BEEmod/BEE2-items#2875]

**Comment by ZombiePwner1** [comment]
Do you have the game installed?

**Comment by LautaroL20** [comment]
Ill gonna test this when i wake up and ill confirm if this also happens to me too.

**Comment by Luke18033** [comment]
Shows up fine for me. Portal Stories: Mel (and Aperture Tag) need to be installed in the same Steam library folder as Portal 2 for it to show up.

**Comment by Luke18033** [comment]
Closing due to lack of response.
