### ISSUE TITLE
Pellet Catcher causes Build Error in Overgrown AND 80's style

### ISSUE THREAD

**Issue by galacticnerds** [BEEmod/BEE2-items#2879]
VRAD failed.

[I] vrad.main(): BEE2 VRAD hook started!
[I] vrad.main(): Map path is C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[I] vrad.load_config(): Loading Settings...
[I] vrad.load_config(): Config Loaded!
[I] vrad.main(): Final status: is_peti=True, edit_args=True
[I] vrad.main(): Reading BSP
[I] vrad.main(): Done!
[I] vrad.main(): Reading our FGD files...
[I] vrad.main(): Adding special packed files:
[I] vrad.main(): Run transformations...
[I] bsp_trans.run_transformations(): Running "P2 Coop Trigger"...
[I] bsp_trans.run_transformations(): Running "P2 Goo"...
[I] bsp_trans.run_transformations(): Running "Attachment Points"...
[I] bsp_trans.run_transformations(): Running "VScript Init Code"...
[I] bsp_trans.run_transformations(): Running "VScript RunScriptCode Strings"...
[I] bsp_trans.run_transformations(): Running "Optimise logic_auto"...
[I] bsp_trans.run_transformations(): Running "Fix Laser Catcher Skins"...
[I] bsp_trans.run_transformations(): Running "Force Paint in Map"...
[I] bsp_trans.run_transformations(): Running "Precache P2 Light Bridge"...
[I] bsp_trans.run_transformations(): Running "comp_choreo_sceneset"...
[I] bsp_trans.run_transformations(): Running "Proxy limits"...
[I] bsp_trans.run_transformations(): Running "comp_precache_model"...
[I] bsp_trans.run_transformations(): Running "comp_precache_sound"...
[I] bsp_trans.run_transformations(): Running "comp_pack_replace_soundscript"...
[I] bsp_trans.run_transformations(): Running "comp_pack"...
[I] bsp_trans.run_transformations(): Running "comp_pack_rename"...
[I] vrad.main(): Scanning map for files to pack:
[W] packlist.pack_fgd(): Unknown keyvalue "heightFogStart" for ent of type "env_fog_controller"!
[W] packlist.pack_fgd(): Unknown keyvalue "heightFogMaxDensity" for ent of type "env_fog_controller"!
[W] packlist.pack_fgd(): Unknown keyvalue "heightFogDensity" for ent of type "env_fog_controller"!
[W] packlist.pack_fgd(): Unknown keyvalue "defaultstyle" for ent of type "light_spot"!
[W] packlist.pack_fgd(): Unknown keyvalue "portalnumber" for ent of type "func_areaportal"!
[W] packlist.pack_fgd(): Unknown class "playtest_manager"!
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "vrad.py", line 861, in <module>
  File "vrad.py", line 790, in main
  File "F:\Git\srctools\srctools\packlist.py", line 633, in eval_dependencies
  File "F:\Git\srctools\srctools\packlist.py", line 699, in _get_material_files
  File "F:\Git\srctools\srctools\vmt.py", line 122, in parse
  File "srctools\_tokenizer.pyx", line 251, in srctools._tokenizer.Tokenizer.__call__
  File "srctools\_tokenizer.pyx", line 293, in srctools._tokenizer.Tokenizer.next_token
srctools.tokenizer.TokenSyntaxError: Single slash found, instead of two for a comment (//)!
Error occurred on line 4, with file "materials/models/props/ball_catcher_sheet.vmt".
WARNING: File "materials/maps/preview/metal/underground_wall_metal001b_280_-135_296.vmt" does not exist!
WARNING: File "materials/maps/preview/liquids/water_underground_cave_280_-328_296.vmt" does not exist!
WARNING: File "materials/maps/preview/liquids/water_underground_cave_-2400_0_0.vmt" does not exist!
WARNING: File "materials/maps/preview/wood/underground_plywood_01a_-2400_0_0.vmt" does not exist!
WARNING: File "materials/sprites/sprites/glow_test02.vmt" does not exist!
WARNING: File "materials/sprites/sprites/light_glow03.vmt" does not exist!

**Comment by Luke18033** [comment]
See BEEmod/BEE2.4#1064 for the cause of this error.

**Comment by galacticnerds** [comment]
I don't think I remember them using the overgrown skin.
