### ISSUE TITLE
Large Observation Room Doesn't Exist in 1960's Mode - Failure to Compile

### ISSUE THREAD

**Issue by calclover2514** [BEEmod/BEE2-items#2881]
Whenever I use 1960's mode, this happens and the map fails to compile:
![screenshot](https://user-images.githubusercontent.com/43104632/50494081-31de5980-09ef-11e9-8170-e5a1a66dea21.png)

**Comment by galacticnerds** [comment]
Found the issue in the log.

[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'D:/Games/steamapps/common/Portal 2/portal2/', 'D:/Games/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <Valve>.run_compiler(): Valve Software - vbsp.exe (Oct 26 2018)
[I] <Valve>.run_compiler(): 12 threads
[I] <Valve>.run_compiler(): materialPath: D:\Games\steamapps\common\Portal 2\portal2\materials
[I] <Valve>.run_compiler(): Loading D:/Games/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <Valve>.run_compiler(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <Valve>.run_compiler(): 
[I] <Valve>.run_compiler(): Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
[I] <Valve>.run_compiler(): Could not open instance file instances/BEE2/60s/items/observation_grate_256.vmf
[I] <Valve>.run_compiler():
