### ISSUE TITLE
End elevator not working properly (also look at the lighting)

### ISSUE THREAD

**Issue by Tekameikite** [BEEmod/BEE2-items#2882]
https://streamable.com/47ie3 - I don't know how to embed a video here so I'll just give you a link.
I don't know if it's normal when playing a map in Puzzle Creator but this happened at the end when entering the elevator.  Also look at the place where the videos should be playing and please fix the lighting (it looks so disguisting oml xdd)
edit: sorry for the quality (obs doesn't like me)

**Comment by Tekameikite** [comment]
**bump my dudes**

**Comment by LautaroL20** [comment]
It could be fixed for next release, which it can take another month.

**Comment by LautaroL20** [comment]
That video is no longer available unfortunately, so I can not see what was exactly wrong with the end elevator. Could you please re-upload it?

**Comment by Tekameikite** [comment]
I don’t have the video since it was taken 3 years ago and I don’t even remember what the issue was. Streamable seems to delete its videos, which sucks a bit :/
