### ISSUE TITLE
Bee mod has a bug

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2884]
![bug](https://user-images.githubusercontent.com/35931028/50528947-17dd6d80-0afa-11e9-86d2-3b4f253abd65.png)

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to the Bee´s Interface must be posted on the interface´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the items and styles, only.

For being the first time, ive posted your issue in the correct page, here: https://github.com/BEEmod/BEE2.4/issues/1048
