### ISSUE TITLE
Weird and probably impossible feature I thought of...

### ISSUE THREAD

**Issue by MeloettaRules28** [BEEmod/BEE2-items#2886]
Would it be possible to add a Start Enabled, Start Reversed or even a Timer to the actual geometry blocks?
For a much clearer example:

- In overgrown style, Start Enabled or Reversed, could make the block a clean version, as seen in Reconstruction styles.
- Or a timer for literally every style, which can choose the texture, for example;
  3 - Normal
  4 - Checkerboard (For Floor Blocks), like the Surface Marker Item (For Wall Blocks)

I am sure this isn't actually possible but you could try? I guess?

**Comment by LautaroL20** [comment]
- Mixing the textures from other styles in Overgrown will not fit at all with its atmosphere making it to look out of place.
- Each texture like checkerboard and others will get generated by the compiler depending on the situation or the item that was placed at a position. Changing this manually would turn this very inconsistent.
