### ISSUE TITLE
Aperture Tag Paint Gun not working properly.

### ISSUE THREAD

**Issue by sealovedmoon** [BEEmod/BEE2-items#2887]
I added the Paint Gun Activation Field by locating it beside the fizzler and connecting it to it. But the paint gun also makes portals not only shoot gel. Is there a way to fix that?

**Comment by MeloettaRules28** [comment]
So... any help on this subject? I saw some posts with this problem which weren't solved either, so... what's up with this item exactly?

I also tried reinstalling BEE2, but it still didn't fix it.

**Comment by Luke18033** [comment]
Try [this](https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod). The item might just be broken though, it's been a while since I last used BEEmod with Aperture Tag. I'll go test it myself.

**Comment by Luke18033** [comment]
![preview0003](https://user-images.githubusercontent.com/19228201/51651798-2c1e5a00-1f42-11e9-8276-9a5f3cfea0a0.png)
Can confirm that this is an actual issue.

**Comment by MeloettaRules28** [comment]
About that "Try this" I just said I tried reinstalling both the Program and Packages. The item is indeed broken.

**Comment by Luke18033** [comment]
Should be fixed by now

**Comment by TheProtoToaster** [comment]
You need Aperture tag bought and downloaded

**Comment by TheProtoToaster** [comment]
if using portal 2

**Comment by TheProtoToaster** [comment]
nvm
