### ISSUE TITLE
Separate entry doors for cooperative maps

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2893]
On cooperative maps, both Atlas and P-body starts spawning in the same place. What if i want the two robots to start separated in two different places once the map loads? I have an idea where if you place two entry doors in choosable places, Atlas and P-body will start from that two different places once the map loads.

**Comment by ZombiePwner1** [comment]
@LautaroL20 There is an item that allows this but I don't know if @TeamSpen210 Has fixed it or not.

**Comment by LautaroL20** [comment]
There is no such item in Bee2.4 wheels...

**Comment by ZombiePwner1** [comment]
@LautaroL20 It was a single player dropper or something wheels.

**Comment by ZombiePwner1** [comment]
@LautaroL20 It's this wheels https://github.com/BEEmod/BEE2-items/issues/1475 made for both games but still.

**Comment by TeamSpen210** [comment]
This is why the separation checkpoint exists - just place it immediately after the entrance. There's a good reason you *don't* want to actually spawn players seperately - this forces the host/ATLAS to be in one place, and the client/P-Body to be in another. Many technical reasons might prevent swapping that. The checkpoint is deliberately designed so players can choose what side they want to play. Note that Valve also actually does this in the Art Therapy puzzle that seperates the players.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 But is there any fixes for this https://github.com/BEEmod/BEE2-items/issues/1475
