### ISSUE TITLE
Frankens don't walk

### ISSUE THREAD

**Issue by AlmisuiFR** [BEEmod/BEE2-items#2895]
(Original clean style)
In the current packages version (4.33.0), frankens seem unable to walk.

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2828
