### ISSUE TITLE
Downward-elevator door bug

### ISSUE THREAD

**Issue by AlmisuiFR** [BEEmod/BEE2-items#2896]
In the randomly-choosen entrance where the elevator is coming downward (from the ceiling), the player is able to walk thought the bottom-stairs door. (Original clean style).
(hope my english is correct)

**Comment by AlmisuiFR** [comment]
Ok, sorry about that !

**Comment by Overwatch-C-17** [comment]
Is this bug really exist? I was tested it and I can't go under the stairs (Entrance and Exit Elevator Room [Downward version]). Everything works normal.

**Comment by TeamSpen210** [comment]
No, the problem is you can walk through the first door while it's still opening - probably because of the worldportal there.
