### ISSUE TITLE
Reflection Gel Color Code

### ISSUE THREAD

**Issue by PieCreeper12** [BEEmod/BEE2-items#2899]
So, I found a map that uses a console code that changes the color of adhension gel to be purple. When I then played a map that involves reflection gel, that gel was purple. So, the code was able to change the color of the reflection gel to be purple. My idea is that whenever a map contains reflection gel, the map could enter that code in the console before it starts so that reflection gel is purple instead of white. This way, people will not get confuse reflection gel for conversion gel and it would be possible to use the two gels together.

Adhesion map: https://steamcommunity.com/sharedfiles/filedetails/?id=860192232

**Comment by Luke18033** [comment]
Try spawning a blob of Conversion Gel in that map, see what happens.

**Comment by ZombiePwner1** [comment]
Not possible reflection gel uses both conversion gel for it's color and propulsion gel for it's blob color when it hits players.

**Comment by Luke18033** [comment]
> @Luke18033 said:
> Reflection Gel painted on a surface is hardcoded to use the same color as Conversion Gel (`portal_paint_color`). We can change the color of the blobs though, which has been done, making them a dark gray.

The way it's done in that map is by changing `portal_paint_color` (and `speed_paint_color` for the screen effects) to purple.

Also, Adhesion Gel is gr- forget it, I don't want to get into this argument again.

**Comment by TeamSpen210** [comment]
Also, it only works in the *next* map, so the map would need to restart immediately after you start it.
