### ISSUE TITLE
bottomless pit doesn't teleport player

### ISSUE THREAD

**Issue by mario2582** [BEEmod/BEE2-items#290]
bottomless pits doesn't currently teleport player

**Comment by LautaroL20** [comment]
What do you mean? It is players not respawning where the trigger autosave was triggered?

**Comment by TeamSpen210** [comment]
The issue is that bottomless pits don't cause the player to fall into them. Actually I can fix this a different way, after I do some other changes in the compiler - just have a very deep skybox brush area, and that will render over the background.

**Comment by Luke18033** [comment]
Why can't bottomless pits be generated directly into maps? Since the pit needs to be on the bottom-most voxel, you know there won't be anything below it could conflict with.

**Comment by TeamSpen210** [comment]
That's what I'm now planning on doing.

**Comment by Luke18033** [comment]
Ah, making this issue kind of irrelevant then.
