### ISSUE TITLE
compile error (please help)

### ISSUE THREAD

**Issue by L0L460** [BEEmod/BEE2-items#2902]
hi,  every time I tried to play the map it fail (sorry for my english) i tried to reinstall BeeMod that change nothing and i really want to use beemod 
console error : 
VBSP failed.

[I] vbsp.main(): BEE2v4.33.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/over/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/over/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/over/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/over/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/over/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/over/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/over/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/over/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/over/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/over/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/over/items/rex/pellet_dest/static_4.vmf'})
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/over/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/over/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/over/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/over/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/over/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/over/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/over/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/over/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/over/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/over/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/over/items/rex/pellet_dest/static_4.vmf'})
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Exit to 3
[I] vbsp.mod_entryexit(): Setting SP Entry to 2
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (57 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.core.res_goo_debris(): GooDebris: 6/20 locations
[I] brushes.res_import_template(): IDS: {'1', '2'}
[I] brushes.res_import_template(): IDS: {'1', '2'}
[I] brushes.res_import_template(): IDS: {'1', '2'}
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] packing.pack_list(): Packlist "PACK_BEE2_MODERN_DROPPER_WRECKED" does not exist!
[W] cond.core.resolve_value(): Invalid fixup ($color) in the "cd56888" instance:
 | <Entity>: 
 | {
 | 	 classname = "func_instance"
 | 	 targetname = "cd56888"
 | 	 file = "instances/BEE2/over/items/cube/dropper.vmf"
 | 	 origin = "192 576 448"
 | 	 angles = "0 180 180"
 | 	 $connectioncount = "1"
 | 	 $item_fall_straight_down = "1"
 | 	 $disable_autodrop = "0"
 | 	 $disable_autorespawn = "0"
 | }
 | 
 | {'connectioncount': FixupTuple(var='connectioncount', value='1', id=1), 'item_fall_straight_down': FixupTuple(var='item_fall_straight_down', value='1', id=5), 'disable_autodrop': FixupTuple(var='disable_autodrop', value='0', id=4), 'disable_autorespawn': FixupTuple(var='disable_autorespawn', value='0', id=3)}
 |___

[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_A" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_OVER_CATWALK_SP_ELEVATOR" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_RUSTY_TRUSS" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_C" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_ELEVATOR_DIRTY" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_OVER_CATWALK_DESTROYED_64" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_A" does not exist!
[I] vbsp.set_elev_videos(): Elevator type: FORCE
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2/voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2/mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.find_group_quotes(): "ENTRY": 1/6 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "ENTRY_GEN_ANIMAL_KING"
 | 	"Choreo" "npc/announcer/prehub46.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "EXIT_GEN_RESTART"
 | 	"Choreo" "npc/announcer/mp_hub_return06.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 2/4 quotes..
[I] voiceLine.add_voice(): 2 Mid quotes
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CUBE_BUTTON_TESTING"
 | 	"OnlyOnce" "1"
 | 	"Atomic" "1"
 | 	"Choreo_Name" "@voice_anycube_pickup"
 | 	"Choreo" "npc/announcer/prehub11.vcd"
 | 	"Choreo_Name" "@voice_franken_pickup"
 | 	"Choreo" "npc/announcer/prehub11.vcd"
 | 	}
 | 
 |___

[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CUBE_FIZZLE"
 | 	"OnlyOnce" "1"
 | 	"Atomic" "1"
 | 	"Choreo_Name" "@voice_cube_dest"
 | 	"Choreo" "npc/announcer/testchamber09.vcd"
 | 	"Choreo_Name" "@voice_ccube_dest"
 | 	"Choreo" "npc/announcer/testchamber09.vcd"
 | 	"Choreo_Name" "@voice_cube_redrop"
 | 	"Choreo" "npc/announcer/testchamber09.vcd"
 | 	"Choreo_Name" "@voice_ccube_redrop"
 | 	"Choreo" "npc/announcer/testchamber09.vcd"
 | 	}
 | 
 |___

[I] voiceLine.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['goo', 'cube', 'cubestandard', 'cubedropper', 'cubedropperstandard', 'cubenotcompanion', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'pedestalbutton', 'bridge', 'hardlight', 'collapsedexitstairs', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=6215, misses=402, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'bee2_goo_debris': True, 'overfunnelflicker': False, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/over/global_ents.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 96.0 <- Counter({96.0: 20})
[I] vbsp.change_brush(): Adding Goo Mist...
[I] vbsp.change_brush(): Done!
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <Valve>.run_compiler(): Valve Software - vbsp.exe (Oct 26 2018)
[I] <Valve>.run_compiler(): 8 threads
[I] <Valve>.run_compiler(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <Valve>.run_compiler(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <Valve>.run_compiler(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <Valve>.run_compiler(): Could not open instance file instances/BEE2/over/items/button/pedestal.vmf
[I] <Valve>.run_compiler(): 
[I] BEE2_config.save(): Saving changes in config "C:\Users\Cash\AppData\Roaming\BEEMOD2\config\compile.cfg"!

![20190201210131_1](https://user-images.githubusercontent.com/47254263/52146676-bcf0e600-2664-11e9-89f4-23adf0f32463.jpg)

**Comment by L0L460** [comment]
i've have the latest version of beemod

**Comment by LautaroL20** [comment]
Try following the 7 steps contained in the following link and see if it fixes your issue: https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod

**Comment by L0L460** [comment]
ok

**Comment by L0L460** [comment]
i follow the steps and that not working

**Comment by L0L460** [comment]
wait maybe that work

**Comment by LautaroL20** [comment]
> L0L460 Said: "the file is unfindable"

Wat

**Comment by L0L460** [comment]
here the console:
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (25,25,25)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 388 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 35143 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 35884 (ms)
Could not execute the command:
   "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vrad.exe" -final -staticproppolys -staticproplighting -textureshadows -hdr -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.bsp"
Windows gave the error message:
   "Le fichier spécifié est introuvable." (The specified file can not be found in french)

VRAD failed.

Failed to start process ("C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vrad.exe" -final -staticproppolys -staticproplighting -textureshadows -hdr -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.bsp") with working dir (C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/)

**Comment by L0L460** [comment]
and thx for "trying" to help me

**Comment by L0L460** [comment]
VBSP failed.

[I] vbsp.main(): BEE2v4.33.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/over/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/over/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/over/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/over/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/over/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/over/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/over/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/over/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/over/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/over/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/over/items/rex/pellet_dest/static_4.vmf'})
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/over/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/over/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/over/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/over/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/over/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/over/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/over/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/over/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/over/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/over/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/over/items/rex/pellet_dest/static_4.vmf'})
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.mod_entryexit(): Setting SP Entry to 5
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (61 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.core.res_goo_debris(): GooDebris: 6/20 locations
[I] brushes.res_import_template(): IDS: {'1', '2'}
[I] brushes.res_import_template(): IDS: {'1', '2'}
[I] brushes.res_import_template(): IDS: {'1', '2'}
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] packing.pack_list(): Packlist "PACK_BEE2_MODERN_DROPPER_WRECKED" does not exist!
[W] cond.core.resolve_value(): Invalid fixup ($color) in the "cd18" instance:
 | <Entity>: 
 | {
 | 	 classname = "func_instance"
 | 	 targetname = "cd18"
 | 	 file = "instances/BEE2/over/items/cube/dropper.vmf"
 | 	 origin = "192 576 448"
 | 	 angles = "0 180 180"
 | 	 $connectioncount = "1"
 | 	 $item_fall_straight_down = "1"
 | 	 $disable_autodrop = "0"
 | 	 $disable_autorespawn = "0"
 | }
 | 
 | {'connectioncount': FixupTuple(var='connectioncount', value='1', id=1), 'item_fall_straight_down': FixupTuple(var='item_fall_straight_down', value='1', id=5), 'disable_autodrop': FixupTuple(var='disable_autodrop', value='0', id=4), 'disable_autorespawn': FixupTuple(var='disable_autorespawn', value='0', id=3)}
 |___

[W] packing.pack_list(): Packlist "PACK_BEE2_OVER_CATWALK_SP_ELEVATOR" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_RUSTY_TRUSS" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_C" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_ELEVATOR_DIRTY" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_C" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_A" does not exist!
[I] vbsp.set_elev_videos(): Elevator type: RAND
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2/voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2/mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.find_group_quotes(): "ENTRY": 1/6 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "ENTRY_GEN_ANIMAL_KING"
 | 	"Choreo" "npc/announcer/prehub46.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "EXIT_GEN_TECH_DIFF"
 | 	"Choreo" "ann_apoc/exit_tech_diff.vmf"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 2/4 quotes..
[I] voiceLine.add_voice(): 2 Mid quotes
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CUBE_BUTTON_TESTING"
 | 	"OnlyOnce" "1"
 | 	"Atomic" "1"
 | 	"Choreo_Name" "@voice_anycube_pickup"
 | 	"Choreo" "npc/announcer/prehub11.vcd"
 | 	"Choreo_Name" "@voice_franken_pickup"
 | 	"Choreo" "npc/announcer/prehub11.vcd"
 | 	}
 | 
 |___

[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CUBE_FIZZLE"
 | 	"OnlyOnce" "1"
 | 	"Atomic" "1"
 | 	"Choreo_Name" "@voice_cube_dest"
 | 	"Choreo" "npc/announcer/testchamber09.vcd"
 | 	"Choreo_Name" "@voice_ccube_dest"
 | 	"Choreo" "npc/announcer/testchamber09.vcd"
 | 	"Choreo_Name" "@voice_cube_redrop"
 | 	"Choreo" "npc/announcer/testchamber09.vcd"
 | 	"Choreo_Name" "@voice_ccube_redrop"
 | 	"Choreo" "npc/announcer/testchamber09.vcd"
 | 	}
 | 
 |___

[I] voiceLine.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['goo', 'cube', 'cubestandard', 'cubedropper', 'cubedropperstandard', 'cubenotcompanion', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'pedestalbutton', 'bridge', 'hardlight', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=6923, misses=402, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'bee2_goo_debris': True, 'overfunnelflicker': False, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_3.vmf', 'instances/BEE2/over/global_ents.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 96.0 <- Counter({96.0: 20})
[I] vbsp.change_brush(): Adding Goo Mist...
[I] vbsp.change_brush(): Done!
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <Valve>.run_compiler(): Valve Software - vbsp.exe (Oct 26 2018)
[I] <Valve>.run_compiler(): 8 threads
[I] <Valve>.run_compiler(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <Valve>.run_compiler(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <Valve>.run_compiler(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <Valve>.run_compiler(): Could not open instance file instances/BEE2/over/items/button/pedestal.vmf
[I] <Valve>.run_compiler():

**Comment by TeamSpen210** [comment]
Apparently the pedestal button in Overgrown has some broken logic. Try using the alternate pedestal button?

**Comment by L0L460** [comment]
when i remove pedestal button the firt compilation was working 
but when i retry to compile that show an error message

**Comment by L0L460** [comment]
it is written that window gives the following message "The specified file can not be found"

**Comment by L0L460** [comment]
the file is preview.bsp

**Comment by TeamSpen210** [comment]
I can't replicate this.
