### ISSUE TITLE
Pellet Emitter always auto-respawn

### ISSUE THREAD

**Issue by camerson1313** [BEEmod/BEE2-items#2904]
There's an issue with the energy pellet emitters that is significantly game-breaking. As long as the pellet emitter is triggered on (via a button or any other input), it will continuously spawn new pellets whenever the current one is destroyed (even if auto-respawn is disabled). It needs to be set so that whenever you place a cube on a button to activate the emitter, an infinite energy pellet will be released, and whenever the pellet gets destroyed (or hits a catcher) it WON'T automatically spawn a new one. In other words, it should be only one pellet per "triggered on" input.

**Comment by Overwatch-C-17** [comment]
Not happen on my side

**Comment by TeamSpen210** [comment]
Infinite pellets should never autorespawn, but timed pellets get replaced like normal. The logic is totally different for these variants, which are you using?

**Comment by camerson1313** [comment]
I recorded a video to show what I mean: https://www.youtube.com/watch?v=L_NO5JPX3YI

Infinite pellet emitters just keep firing whenever it's turned on, and don't fire at all when turned off (and the current pellet just gets destroyed).

The problem also persists with pedestal buttons, because as soon as the timer ends the current pellet gets destroyed. There's no way to just press the button to spawn one and let it go on. I've tried every pedestal button variant (even 1 sec) and it's always the same problem. Using the toggle latch is also pointless because then it just keeps spawning over and over when toggled on.

I dunno, it could just be that my BEE2 is corrupted or something, seeing as it works for Overwatch-C-17. (I have version 4.33.1). I'll try to see if reinstalling helps.

**Comment by Overwatch-C-17** [comment]
Enegy Pellet Emitter (Setted up the pellet lifetime to infinite): Yes the spawned Energy Pellet (Infinite Lifetime) will not destroyed if the input keep on. Once the input to the Emitter is off, the Energy Pellet will explode. Same happen using Pedestal Button. I think it needs to be configured like once input is on Energy Pellet launched and stay and not destroyed when input goes off
