### ISSUE TITLE
Portal 1 stair steps are aligned weirdly

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2910]
The steps on the Portal 1 piston stairs don't seem to be aligned right, giving the stairs an almost curved appearance. I've placed a static stair item next to the dynamic one to show how they should be positioned. Going by this, only the second step is aligned properly.
![preview0001](https://user-images.githubusercontent.com/19228201/52908015-d592fb80-3221-11e9-8fc6-03f8b20f0066.jpg)
![preview0002](https://user-images.githubusercontent.com/19228201/52908054-5fdb5f80-3222-11e9-8d21-c361500c9c6c.jpg)
![preview0003](https://user-images.githubusercontent.com/19228201/52908055-623db980-3222-11e9-9826-8d99f73a6194.jpg)
The steps themselves also don't look right, and should probably be updated to use the same setup as piston platforms (8 units thick with slightly angled sides to prevent texture conflicts).

**Comment by ZombiePwner1** [comment]
Interesting find.

**Comment by TeamSpen210** [comment]
I probably aligned them to the shape of the Clean collisions, which is pretty silly.

**Comment by Luke18033** [comment]
Now fixed.
