### ISSUE TITLE
Portal 1 piston platform tops have angled sides even when static

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2911]
While this is necessary for dynamic platforms to prevent z-fighting when retracted, static piston platforms could never move into a position where this would occur. Additionally, the panel still generates as a dynamic entity even though it never moves (this can be seen by setting `r_drawbrushmodels` to 0, or in Hammer).
![preview0004](https://user-images.githubusercontent.com/19228201/52908108-88b02480-3223-11e9-96c2-1baa82bc8785.jpg)
With brush models disabled:
![preview0006](https://user-images.githubusercontent.com/19228201/52908126-1ab82d00-3224-11e9-8287-c7c62899116f.jpg)

**Comment by TeamSpen210** [comment]
I'm using a brush entity here for a reason, so the side surfaces are non-paintable. I should just use a custom material for that though.
