### ISSUE TITLE
"Coop End: Radar" elevator video has incorrect short name

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2912]
The short name is displayed as "Connecting Power", the actual name of the above video. The full name displayed when selected is correct.
![image](https://user-images.githubusercontent.com/19228201/52917781-3c58f900-32a4-11e9-83be-24ca466ff607.png)

**Comment by LautaroL20** [comment]
I think that this is the wrong section for this since it is an interface´s issue.

**Comment by TeamSpen210** [comment]
It's not an interface issue, the problem was with the package data.
