### ISSUE TITLE
Bee2 Music preview crashes Bee2

### ISSUE THREAD

**Issue by Eric718** [BEEmod/BEE2-items#2914]
When trying to preview music, the application crashes. https://gyazo.com/6266afcc99e1c6a9c60689f484407409
I have no clue why this happens. 
I have not tested the music in Portal 2 itself.
https://gyazo.com/f189e416b72eb81cdf36f835f4de446d

**Comment by Luke18033** [comment]
*sigh*
BEEmod/BEE2.4#1035
It's literally a pinned issue
