### ISSUE TITLE
button fizzler

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2918]
A new fizzler that would act like the FDF but if you put player or cubes [dictated by start reversed and start enabled] it would activate, im supposing it would need a fizzler output relay to work, so the timer widget would dictate how much entities should be on the fizzler before it would activate
and it would also be able to accept inputs, 

This can be used as a player only button, or as a simpler retractable button.

As for the color, i'm thinking it would be blue when off but when the desired
amount of entities is reached it would turn orange.

**Comment by TeamSpen210** [comment]
I don't think this would work very well or be useful. A horizontal fizzler would be difficult to have objects stay inside, and it's such a large radius. Just use a regular button.
