### ISSUE TITLE
HEP Catcher activation skin

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2919]
![default](https://user-images.githubusercontent.com/35931028/53420757-0ecb2880-39e5-11e9-9798-b2e019e5e464.png)
![ball_catcher_sheet](https://user-images.githubusercontent.com/35931028/53420763-12f74600-39e5-11e9-9805-84216f6ed094.jpg)
![catcher_timed_dirty](https://user-images.githubusercontent.com/35931028/53421144-d7a94700-39e5-11e9-9299-727da792cee5.jpg)

**Comment by LautaroL20** [comment]
Interesting.

**Comment by LautaroL20** [comment]
Are you able to make some overgrown skins of models that are currently unstyled?

**Comment by SCIENTIST2004** [comment]
I can try. But this overgrown texure is not mine. I found it in bee mod (this texture of overgown green HEP catcher) and I re-drawn it.

**Comment by Luke18033** [comment]
The HEP emitter/catcher models are dirty by default in Portal 2, since they only appear in Overgrown maps. The clean versions are custom models using the P1 skin. You'll want to link to the original VTFs on Google Drive or something, instead of converting them to low quality JPEGs.

**Comment by Luke18033** [comment]
Also, this shouldn't be used in Portal 1 style, since they didn't change skin in the original game.

**Comment by SCIENTIST2004** [comment]
If portal 1 style chosen HEP cathers won't change their skin, but if any other style chosen then they will do this. Like Portal 1 floor button and Portal 2 floor button.

**Comment by TeamSpen210** [comment]
I'm not sure how well this would work, since there's also the green skin that needs to be distinct.

**Comment by Luke18033** [comment]
@SCIENTIST2004 Can you upload the original textures?

**Comment by Luke18033** [comment]
Going to assume we aren't getting these, doesn't look like he's been online in a while.

**Comment by SCIENTIST2004** [comment]
![catcher_timed_dirty](https://user-images.githubusercontent.com/35931028/65462740-165d8d80-de5f-11e9-9fc8-95036b4741a6.jpg)
![catcher_timed_clean](https://user-images.githubusercontent.com/35931028/65462741-165d8d80-de5f-11e9-92ac-ca921bfb1434.jpg)
sorry for the delay. I had "a small break" but from now on you can see me more often here.

**Comment by Luke18033** [comment]
Those are the green versions, and they're still JPEGs...

**Comment by SCIENTIST2004** [comment]
Do you need a blue version in vtf format?

**Comment by Luke18033** [comment]
No, we already have all of those! We need the VTFs for the orange versions in your original post.

**Comment by SCIENTIST2004** [comment]
[HEP_activated.zip](https://github.com/BEEmod/BEE2-items/files/3665305/HEP_activated.zip)

**Comment by Luke18033** [comment]
I just looked at those, they still seem to have JPEG artifacting...I think we're just going to implement #4082 anyway.
