### ISSUE TITLE
make cutout tile generation logic better

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#292]
cutout tiles should be generated in spots and paths instead of like they currently are and have single panels near edges only and square beams missing in center sometimes. make them placeable on walls and ceilings too.

depending upon style 
- clean should look like how you see them in the entry corridors and exit sometimes
- overgrown should generate in a group/pattern and have more destruction as you get closer to the center with missing square beams etc and plants and debris in center. if on ceiling should generate skylight, if on wall, or between empty space generate frames only
- bts should be similar to clean
- underground should use wood or rusty square beams (make custom model if wood)

**Comment by LautaroL20** [comment]
These are nice suggestion. Yeah, Cutout tile needs to be improved. Respect to Clean Style, this item currently works terrible sometimes.
