### ISSUE TITLE
Cube Droppers with Gel applied don't work.

### ISSUE THREAD

**Issue by NeoKat75** [BEEmod/BEE2-items#2921]
The cubes are dispensed as normal but no gel is applied even though the dispenser model does contain gel sprinklers.

**Comment by TeamSpen210** [comment]
Which styles have this issue? It works fine for me.

**Comment by NeoKat75** [comment]
Clean!

**Comment by NeoKat75** [comment]
oops

**Comment by TeamSpen210** [comment]
And which cubes, if any?

**Comment by NeoKat75** [comment]
Just your average Weighted Storage Cube.

**Comment by TeamSpen210** [comment]
Which styles have this issue? It works fine for me.

**Comment by NeoKat75** [comment]
Clean...
