### ISSUE TITLE
[New Item] Gel bomb cube

### ISSUE THREAD

**Issue by MemeticGitHubUser** [BEEmod/BEE2-items#2933]
A cube which Has gel inside, which upon a press of a button that's connected to the dropper, the cube will burst, leaving a splat of gel

**Comment by galacticnerds** [comment]
Not sure what the purpose is considering you can just move gel using portals and funnels.

**Comment by kdabest2** [comment]
the purpose it so you can get it to areas that you CANT reach with portals and funnels

**Comment by OlieGamerTV** [comment]
It kinda makes no sense adding this as you can just place a gel funnel and link it to a button, so making a cube just for gel is confusing.

**Comment by Libbybapa** [comment]
Not quite the same, but this reminds me of Paintcan by Tuleby:

https://steamcommunity.com/sharedfiles/filedetails/?id=1233617523

**Comment by Konclan** [comment]
UCP
