### ISSUE TITLE
PRL33.1: 1960´s Old Aperture Causes "Failure To Compile"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2935]
1960´s Old Aperture causes failure to compile.

**Comment by TeamSpen210** [comment]
What's the compile error, and which Obs Room version are you using?

**Comment by LautaroL20** [comment]
I will going to test this with the latest release 4.34.1 and i will see what happens because im not too sure.

**Comment by LautaroL20** [comment]
This is fixed now.
