### ISSUE TITLE
Build Error in 70's Old Aperture with Pellet Emitter

### ISSUE THREAD

**Issue by galacticnerds** [BEEmod/BEE2-items#2939]
VRAD failed.

[I] vrad.main(): BEE2 VRAD hook started!
[I] vrad.main(): Map path is D:\Games\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[I] vrad.load_config(): Loading Settings...
[I] vrad.load_config(): Config Loaded!
[I] vrad.main(): Final status: is_peti=True, edit_args=True
[I] vrad.main(): Reading BSP
[I] vrad.main(): Done!
[I] vrad.main(): Reading our FGD files...
[I] vrad.main(): Adding special packed files:
[I] vrad.main(): Injecting "scripts/vscripts/bee2/mon_camera_args.nut" into packfile.
[I] vrad.main(): Run transformations...
[I] bsp_trans.run_transformations(): Running "P2 Coop Trigger"...
[I] bsp_trans.run_transformations(): Running "P2 Goo"...
[I] bsp_trans.run_transformations(): Running "Attachment Points"...
[I] bsp_trans.run_transformations(): Running "VScript Init Code"...
[I] bsp_trans.run_transformations(): Running "VScript RunScriptCode Strings"...
[I] bsp_trans.run_transformations(): Running "Optimise logic_auto"...
[I] bsp_trans.run_transformations(): Running "Fix Laser Catcher Skins"...
[I] bsp_trans.run_transformations(): Running "Force Paint in Map"...
[I] bsp_trans.run_transformations(): Running "Precache P2 Light Bridge"...
[I] bsp_trans.run_transformations(): Running "comp_choreo_sceneset"...
[I] bsp_trans.run_transformations(): Running "Proxy limits"...
[I] bsp_trans.run_transformations(): Running "comp_precache_model"...
[I] bsp_trans.run_transformations(): Running "comp_precache_sound"...
[I] bsp_trans.run_transformations(): Running "comp_pack_replace_soundscript"...
[I] bsp_trans.run_transformations(): Running "comp_pack"...
[I] bsp_trans.run_transformations(): Running "comp_pack_rename"...
[I] vrad.main(): Scanning map for files to pack:
[W] packlist.pack_fgd(): Unknown keyvalue "heightFogMaxDensity" for ent of type "env_fog_controller"!
[W] packlist.pack_fgd(): Unknown keyvalue "heightFogDensity" for ent of type "env_fog_controller"!
[W] packlist.pack_fgd(): Unknown keyvalue "heightFogStart" for ent of type "env_fog_controller"!
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\compiler_launch.py", line 16, in <module>
  File "F:\Git\BEE2.4\src\vrad.py", line 790, in main
  File "F:\Git\srctools\srctools\packlist.py", line 675, in eval_dependencies
  File "F:\Git\srctools\srctools\packlist.py", line 762, in _get_material_files
AttributeError: 'NoneType' object has no attribute 'casefold'
[9180] Failed to execute script compiler_launch

**Comment by galacticnerds** [comment]
Not sure why you need to edit the title like that.

**Comment by LautaroL20** [comment]
Just to make it as precise as possible.
