### ISSUE TITLE
Game crash when connecting Fizzler Output relay to Angled panel

### ISSUE THREAD

**Issue by MemeticRedditUser** [BEEmod/BEE2-items#2942]
im unable to collect any data for it, but it's a real pain in the ass for sure

**Comment by Luke18033** [comment]
Screenshot/video? If there's a light strip or other thin item on the same surface, it can sometimes cause a crash if that item would block the connection's antlines.

**Comment by kdabest2** [comment]
no, there is no light strip or anything on the same surface, and I don't have any software that can record a game crashing

**Comment by Luke18033** [comment]
Not sure what the problem was here.
