### ISSUE TITLE
Feature Suggestions, division fields, TNT Turrets, Destructible glass & Adhesion Gel

### ISSUE THREAD

**Issue by CS117** [BEEmod/BEE2-items#2943]
- It would be cool to see the surface division fields from the penrose puzzles, which would create portals to other rooms. I dunno if it would be possible due to how complicated linking 2 fields together could be, but it would be cool to have those bad-boys seen in the workshop more.

- TNT turrets & Destructible glass should also be implemented, considering that destructible glass is already present in P2's story modes, it would be very interesting to add puzzle elements that would require breaking glass.

- finally, adhesion gel would also be cool (i'm not good at adding explainations to lists that dont sound repetitive/vague)

**Comment by TeamSpen210** [comment]
These have been suggested before. For surface division fields, the main issue is that there’s a lot of rather arcane placement requirements that’d be difficult to explain to users. TNT turrets aren’t really that good an item, they defeat themselves. Breakable glass is something I’ve worked on on and off, my main problem is figuring out a visual design that’s distinct from existing glass. Adhesion Gel can’t be done.
