### ISSUE TITLE
NEW ITEM VARIANT

### ISSUE THREAD

**Issue by kdabest2** [BEEmod/BEE2-items#2945]
companion Spheres, companion Lasercubes,and companion frankenturrets

**Comment by xDadiKx** [comment]
Companion Spheres - Ok, a fine suggestion I guess.
Laser Cubes - Reflectives cubes? Or you mean cubes with lasers built in them? If you mean cubes that redirect lasers, those exist.
Frankenturrets - Those exist?

**Comment by Konclan** [comment]
What would be the point of these, there's no use for a reskinned cube since we have cube colorizers. AlsoI don't think its possible to add a frankenturret variant since they are NPCs

**Comment by TeamSpen210** [comment]
Actually the problem is that they swap between two models, so it'll revert if you try to override the model.
