### ISSUE TITLE
Object Sensor Field

### ISSUE THREAD

**Issue by MemeticGitHubUser** [BEEmod/BEE2-items#2946]
Like the Lifeform sensor but it detects physics objects (such as cubes and turrets) that pass through it instead of players

**Comment by kdabest2** [comment]
instead of players

**Comment by xDadiKx** [comment]
Pretty sure it wouldn't be called "lifeform sensor" since, obvious reasons.
I think this was suggested before although.

**Comment by Libbybapa** [comment]
I've seen that used to good effect before in a hammer map.

**Comment by Luke18033** [comment]
There was a cube sensor in BEE2.2, so sorta a duplicate of #95?

**Comment by Konclan** [comment]
I'd say so

**Comment by Libbybapa** [comment]
I couldn't fine a 'cube sensor' on the list.  If you're talking about cube triggers, this is not at all the same thing.  What is described is a field that when a cube or other physics object passes to one side of the field, it outputs a connection.  When an object passes back the other way it turns off the connection.  The resulting logic is VERY different from a cube trigger which activates when a cube is in a zone and deactivates when the cube leaves that zone.  The similarity is the same as the similarity between a player trigger and a lifeform sensor.

**Comment by Konclan** [comment]
No cube sensors are on the list which are fields as you described

**Comment by Libbybapa** [comment]
Ok, sounds good.
