### ISSUE TITLE
Being able to remove the targets from the faith plates

### ISSUE THREAD

**Issue by L89David** [BEEmod/BEE2-items#2947]
I don't know if this is possible, but it would be cool to remove the targets from the aerial faith plates...

**Comment by LautaroL20** [comment]
Interesting.

**Comment by TeamSpen210** [comment]
Why would you need this? One deliberate thing about the design of the various elements is transparency. Ideally you can tell what a thing is going to do before actually interacting with it. For example antlines connect things, the cube a dropper will produce is visible from the outside, faith plates have a target and orientation showing where it will go.
