### ISSUE TITLE
Restoring an old version

### ISSUE THREAD

**Issue by dnldrl** [BEEmod/BEE2-items#2949]
This particular issue is on me, but I uninstalled all my games from my Steam for a while (for reasons I choose not to share) and I recently reinstalled Portal 2 on the same PC. Luckily, all the content including the test chambers I had created before (with BEEMOD) were still available. I however did not have BEEMOD installed at the time and made the mistake of opening one of my test chambers. When I had opened it, I realized the mistake I made due to most test chamber elements missing. When I went into test chamber view, though, it was still the older version but it wasn't current. 

Is there a way I can retrieve the old version? I hope it's possible since I still have the in-game version of it. Also, I'd consider rebuilding everything from scratch if the test chamber weren't so huge and the BEEMOD test elements making about 75% of the whole thing.

**Comment by TeamSpen210** [comment]
If you didn’t press “save”, I think it won’t have edited the files so the map should still be intact if you install BEE2 and open it. If that doesn’t do anything, you’re mostly out of luck - it’s not really possible to reverse the compilation process, it’d basically involve placing items manually matching the positioning of the items visible in the compiled version.
