### ISSUE TITLE
Sendificator Slim is missing textures 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2952]
This issue only affects three styles: Clean, Portal 1 and BTS:
![Clean](https://user-images.githubusercontent.com/12244376/55093940-235a1980-5094-11e9-892c-ddb254d25b10.jpg)
![BTS](https://user-images.githubusercontent.com/12244376/55093941-235a1980-5094-11e9-9987-34e8eff7af62.jpg)
![Portal 1](https://user-images.githubusercontent.com/12244376/55093942-23f2b000-5094-11e9-9743-3498b6613eb5.jpg)

**Comment by dunkler-schatten** [comment]
Not right. 
missing textures is also not available if you have the BeeMod installed. :-(

**Comment by LautaroL20** [comment]
Yes, i am 100% right.
The Beemod for Windows OS shows their textures as long as you have it installed. It could be your Mac version who may have that issue.

**Comment by dunkler-schatten** [comment]
oh than is it a Mac Version Problem... mhmmm... :/ Thanks
