### ISSUE TITLE
Discord link out-dated

### ISSUE THREAD

**Issue by RoyaleCookie6** [BEEmod/BEE2-items#2954]
This isn't an application issue, more so just an issue with the "wiki" page. the discord link doesn't work, it takes you to a discord.me 404 page.

**Comment by Luke18033** [comment]
Oh, weird. That should be the right link...

**Comment by Luke18033** [comment]
Alright, [here's](https://discord.gg/hnGFJrz) a link you can use for now. Discord.Me removed the invite for some reason.

**Comment by Konclan** [comment]
I believe it was changed a long time ago when we had a massive spam problem on all discords

**Comment by Luke18033** [comment]
No, that happened a while ago because the server was set to "public" mode, which I later disabled. This is totally separate, discord.me completely removed the link without any prior warning or notification, and now wants me to add their bot to the server to continue using it (which I'm not doing).

**Comment by Konclan** [comment]
Oh ew
