### ISSUE TITLE
Chamberlock causes "Failure To Compile" in Overgrown Style

### ISSUE THREAD

**Issue by KabanFriends** [BEEmod/BEE2-items#2962]
`Could not open instance file instances/BEE2/clean/items/tSpen/chamberlock_white.vmf`
`Could not open instance file instances/BEE2/clean/items/tSpen/chamberlock_black.vmf`

**Comment by LautaroL20** [comment]
Yep, i confirm that this is true.

**Comment by LautaroL20** [comment]
Interesting, Spencer will need to optimise this messed up configuration then.
