### ISSUE TITLE
Electrified Grating

### ISSUE THREAD

**Issue by mario2582** [BEEmod/BEE2-items#297]
i thought of a new item based upon the glass grating template, a form a grating that hurts or kills the player upon contact

call it a electric fence, all you would need to do is place a hurt trigger on grating and add electrical arc and spark particles to the grating surface.

**Comment by BenVlodgi** [comment]
So, a laser field?

**Comment by Enterpise** [comment]
@BenVlodgi Ah, i thought the same.

**Comment by CrashingScience** [comment]
Not really, because it could be placeable like glass, laserfield needs to
be attached to a block at the edges. Also, if turned off it would just be
regular grating. It also blocks cubes

**Comment by BenVlodgi** [comment]
In what situation would you need this?
In most of the puzzles I'm thinking of with this element, the electric fence could be replaced with other items.

**Comment by CrashingScience** [comment]
It could be used to make a laserfeild with holes in it, or for the a floor half way up a room whick could be deadly or not.

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 and @BenVlodgi - the electric fence would be like a combo of a laser field and grating and it would be a form of electrified grating that could be turned on and off and so and it could be placed like grating having more placement options than a laser field.

**Comment by ellingtonvengaboysmuseum** [comment]
@teamspen210 - is there a way to create a item yet with the glass/grating base that could be toggled with inputs and outputs, also we would need to generate the electrical arc particles.

**Comment by BenVlodgi** [comment]
puzzlewise this item would be really easy to create, maybe more polish would be needed.
I'd like to see someone create a puzzle using this concept first. Because right now, it doesn't seem like this item is necessary.

**Comment by LautaroL20** [comment]
@BenVlodgi - You want to see a puzzle concept using this element? I have something in mind for this, i just only need this item to be done, and then youll see concepts, if thats you are looking for.

**Comment by LautaroL20** [comment]
@ellingtonvengaboysmuseum - Let me make you a little suggestion to your idea, i would recommend to have 3 Different sizes of this item, and having the option to choose them through "Button Type". These could be useful prefabs sizes:

![2016-02-24_00002](https://cloud.githubusercontent.com/assets/12244376/13296627/37ce14ac-db0d-11e5-92f9-a2efe2d27e48.jpg)

**Comment by BenVlodgi** [comment]
The item could be used like normal grating, either as a new class, or with a flag on top

Try creating the puzzle but replace where you would have the electric grating with grating and a laser field

**Comment by TeamSpen210** [comment]
I'm not really sure what this would be useful for, other than making impassible floors. As a wall-surface, you still couldm't pass through it even if it's turned off.

**Comment by LautaroL20** [comment]
Would you prefer to play the puzzle, or, watch the gameplay showing this? Gameplay could take two hours between rendering and uploading to YT. I think i'll gonna record the gameplay.

**Comment by LautaroL20** [comment]
@ellingtonvengaboysmuseum - @BenVlodgi - @TeamSpen210 

The puzzle concept is here. You can go for the video first if you want, BUT i highly recommend to play the map concept first and then to watch the illustrative video later, in order to understand how this item could work In-Game on a puzzle environment. 

----------------------------------------------------------------------------------------------------------

Map Link: http://steamcommunity.com/sharedfiles/filedetails/?id=632050611

The video (Map editor concept + gameplay) https://youtu.be/hIu0UXkI8ag

Aditional Note: The workshop map has been published on my secondary Steam account.

**Comment by ellingtonvengaboysmuseum** [comment]
@BenVlodgi, @TeamSpen210, @LautaroL20 - this kind of item could be useful for creating some unique puzzles, especially with the other item i had in mind too which was electrified walls, floors, and ceilings based off the electrified walls from the portal flash version. the other variant of this i had was a glass variant that has metal bus bars running across it to electrify it, the glass variant would make puzzles where there was a electrified platform you had to get across that you couldn't fire portals through.

**Comment by Luke18033** [comment]
This doesn't seem particularly useful.
