### ISSUE TITLE
The Laser Splitter

### ISSUE THREAD

**Issue by OmGCHOOCHOOTRAIN** [BEEmod/BEE2-items#2972]
DESCRIPTION: Splits Lasers into a pair. It accepts inputs(to activate the splitter) and does not output. The splitter can be pointed in 4 directions. It does not take space inside the surface it's on. The splitter can only be placed on the floor.

Here's the blueprint!

![splitter_blueprint](https://user-images.githubusercontent.com/49824042/56473388-d1a97280-6438-11e9-9ac3-ede4bbb8b271.png)
       
There are 2 variants of this: the fixed version and portable version. The portable variant is just the reflection cube, but with 2 mirroring sides instead of 1.

**Comment by Endermage77** [comment]
I would envision that a Laser Splitter would look more like a Laser Relay with the Reflection Cube's laser pointer mirror thingies on the side.

**Comment by Libbybapa** [comment]
How is the fixed version functionally different from a voxel with a catcher on one side connected to two laser emitters on two of the other sides?

I believe HugoBDesigner created the portable version and found it to be so limited in its uses and hard to use effectively that it was never released.

**Comment by TeamSpen210** [comment]
I'm not sure honestly.
