### ISSUE TITLE
Make deadly goo not deadly, or just add an itemvar option to turn it into water.

### ISSUE THREAD

**Issue by WowThatsCowtastic** [BEEmod/BEE2-items#2973]
Title.

**Comment by LautaroL20** [comment]
Currently, we can not make deadly goo undangerous, but this could be turned into a suggestion to make it possible.

**Comment by Konclan** [comment]
Basically a duplicate of #2139 since the mod features non deadly water

**Comment by Luke18033** [comment]
Yeah, and non-deadly normal goo would be confusing.
