### ISSUE TITLE
[Suggestion] Custom Textured Tile

### ISSUE THREAD

**Issue by KabanFriends** [BEEmod/BEE2-items#2975]
The item that can have a custom texture (Changeable in BEE2 tool)
It can be placed anywhere (floors, walls or ceiling)
It has a timer to allow having multiple textures in one item
Whether it blocks portals or not is toggleable.

Useful if you have custom textures for custom chamber signage, decoration or something else.
In the BEE2 tool, you select a PNG or JPG file and the tool converts it to the texture file. (It should just allow VTF too)

**Comment by TeamSpen210** [comment]
This is really outside of BEE's scope. If you want to be adding specific custom textures you've made, you should do it in Hammer.
