### ISSUE TITLE
Allow Cube droppers to output

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2977]
this would work by only sending an output when a cube is present 
AKA it outputs if the cube is there, and it doesn't when it isn't.
 It would
probably work best with Cube respawn turned off.

Example
<img width="582" alt="Capture 55" src="https://user-images.githubusercontent.com/31172185/57344520-6c25d900-70fc-11e9-8ebb-ea4e03caca77.PNG">
<img width="582" alt="Capture PNG 56" src="https://user-images.githubusercontent.com/31172185/57344528-7516aa80-70fc-11e9-8067-246cacf1477c.PNG">

**Comment by TeamSpen210** [comment]
What purpose would this serve, really. Keep in mind we can only add one output to an item, so we've gotta choose what it does wisely. I doubt this is obvious to someone looking at a dropper.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
@TeamSpen210 
1.  First of all, i can think of puzzles that use this feature i'm suggesting.
 2. secondly. Well, good point i'm not actually sure how to resolve this problem, 
maybe add a unique model for when this feature is used?
