### ISSUE TITLE
Custom Funnel, Speed, and Bounce Music Not Working - Same Format as Default Packages

### ISSUE THREAD

**Issue by calclover2514** [BEEmod/BEE2-items#2979]
I have tried every workaround.
I have looked through every music package.
No matter what I do, every time I go in a funnel with custom music enabled, the music shuts off, and nothing happens when I use speed/bounce gel.
I am pretty sure I am doing nothing wrong.
Here is the package (for reference):
https://drive.google.com/uc?id=106e-r6EdsVRYruVBRA4yMJPcmatlXi9_&export=download

**Comment by TeamSpen210** [comment]
Can't check your files, but do you have loop points in your sounds?

**Comment by calclover2514** [comment]
What is a loop point?

**Comment by TeamSpen210** [comment]
See here: https://developer.valvesoftware.com/wiki/Looping_a_Sound

**Comment by calclover2514** [comment]
Thank you. This worked.
