### ISSUE TITLE
Absolute Fizzlers crash in Coop

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/BEE2-items#2982]
According to Narkodes, Absolute Fizzlers can crash the game in Coop if the following occurs: 

1. P-Body places portals.
2. ATLAS crosses fizzler.
3. P-Body tries placing portals again.

**Comment by LautaroL20** [comment]
Is this issue even fixeable?

**Comment by TeamSpen210** [comment]
No idea.

**Comment by Zerarath** [comment]
This bug makes the absolute fizzler an unusable item in co-op at the moment :/

**Comment by Luke18033** [comment]
I can't reproduce this anymore, might have been fixed
