### ISSUE TITLE
Vactubes Don't Connect Properly (4.34.1)

### ISSUE THREAD

**Issue by Entity447** [BEEmod/BEE2-items#2984]
When there's a chain of connected vactubes, the first vactube piece and the ones after it get deleted during map compiling.

**Comment by Entity447** [comment]
Don't mind the pause menu, Portal 2 doesn't let Steam take screenshots in the editor.
![newchamber0001](https://user-images.githubusercontent.com/42386391/57943284-484f5980-7899-11e9-8e68-da3343b2baab.jpg)
![preview0002](https://user-images.githubusercontent.com/42386391/57943289-4c7b7700-7899-11e9-8793-d326f8d15ef9.jpg)

**Comment by Entity447** [comment]
Also, this happens in all styles.

**Comment by Luke18033** [comment]
This is a known issue. You should be able to take Steam screenshots in the puzzlemaker, I've never had a problem with it.

**Comment by Entity447** [comment]
I've also had problems with quick saving as well, I don't think Portal 2 likes my keyboard too much.

**Comment by TeamSpen210** [comment]
Fixed in BEEmod/BEE2.4@15cd4b8d2a3464c0090725c16dd1538e4e7afed3.
