### ISSUE TITLE
Turret Dropper Bug

### ISSUE THREAD

**Issue by OfficerPuncake** [BEEmod/BEE2-items#2985]
I have auto-respawn DISABLED yet when the turret is knocked over it still fizzles the turret.

I have two turret droppers over a conveyor belt going into a crusher.
(I'm making a sort of android hell level)

**Comment by OfficerPuncake** [comment]
Screenshots:
![PORTAL 2 5_18_2019 4_02_51 AM](https://user-images.githubusercontent.com/42854059/57966577-f1da2d80-7921-11e9-9282-219b80c07e03.png)
![PORTAL 2 5_18_2019 4_02_52 AM](https://user-images.githubusercontent.com/42854059/57966578-f1da2d80-7921-11e9-83a3-43272cbb5278.png)
![PORTAL 2 5_18_2019 4_03_05 AM](https://user-images.githubusercontent.com/42854059/57966579-f1da2d80-7921-11e9-8a0b-6dc755ffbc8a.png)
![PORTAL 2 5_18_2019 4_03_10 AM](https://user-images.githubusercontent.com/42854059/57966580-f1da2d80-7921-11e9-98d0-2ba7c3f3a714.png)

**Comment by TeamSpen210** [comment]
This has nothing to do with it's actual use, replacing turrets. What valid use does a dead turret have?
