### ISSUE TITLE
Overgrown Goo displays nodraw texture

### ISSUE THREAD

**Issue by Fragmentation123** [BEEmod/BEE2-items#2986]
I recreated the flinging cube puzzle from the Portal 2 campaign, with the goo and everything, but the [goo had a nodraw texture](http://prntscr.com/nqba6n) .                          [Here](http://prntscr.com/nqgxjh) is a screenshot of the map in the editor.

**Comment by LautaroL20** [comment]
Remove all the cutout tile items then rebuild your puzzle and see if it fixes your issue. Let us know if it worked.

**Comment by Fragmentation123** [comment]
There are no cutout tile items in my map, they are just drawbridges which of course, in overgrown have missing tiles.

**Comment by Fragmentation123** [comment]
[Here](http://prntscr.com/nqgxjh) is a screenshot of the map in the editor.

**Comment by King0191** [comment]
Personally I don't see this as Invalid. I've been having this issue in more then Overgrown.

I have had this weird Goo issue in clean, too. And its unclear to me as to w h y
![image](https://user-images.githubusercontent.com/37309250/70101692-c0962600-1603-11ea-85da-b49455a8e773.png)

**Comment by Luke18033** [comment]
Something in the map is causing a leak, can you upload `sdk_content/maps/styled/preview.vmf`?

**Comment by King0191** [comment]
oop- wait. Found it, Grav Gun from one of the User Packages... Never caused issues before tho, peculiar. Though you can't fix it, I'll report this issue to the creator. 

Sorry. though I am curious what the issue here was

**Comment by LautaroL20** [comment]
I will only apply the "invalid" label when we discover that the real cause of the problem was at the side of the author´s issue. Also, when the issue gets closed by the author itself in a mysterious way without giving any reason for it, as it was in this case.

**Comment by Flash4433** [comment]
Try putting the gravity gun next to a wall, with free space in its left and right side. The Guns from Radelite's Package use a model that's bigger than an editor panel. I'm still working on new versions that use the Portal gun pedestal, hopefully they'll be ready soon. Thanks!

**Comment by TeamSpen210** [comment]
If it needs to spread out, you want to define OccupiedVoxels or EmbeddedVoxels appropriately so it takes up more than one grid space.

**Comment by Flash4433** [comment]
I finally found this issue. Just wanted to say that that issue with the gravity gun has been fixed for some time now. @King0191 

Quick heads up, next time please open an issue on our GitHub. Thank you.
