### ISSUE TITLE
Coop Exit with connections does not open in non-Clean styles

### ISSUE THREAD

**Issue by TuAmigoFiel** [BEEmod/BEE2-items#2989]
Overgrown:
![Overgrown](https://user-images.githubusercontent.com/12244376/72204821-e14f6800-345a-11ea-86ef-aad855b91e0f.png)

P1 Style:
![P1 Style](https://user-images.githubusercontent.com/12244376/72204255-b3ffbb80-3454-11ea-9b42-b684eb70a553.jpg)

Old Aperture:
![Old Aperture](https://user-images.githubusercontent.com/12244376/72204263-b9f59c80-3454-11ea-9ecb-575646035dc3.jpg)

The problem persist from the last update but to a lesser extent. My theory is that they fix it but only the doors reported as broken, the clean and original clean (the prove: https://github.com/BEEmod/BEE2-items/issues/2880), for that reason are the only ones working beacuse the rest dosen't (overgrown, underground, and portal 1; bts crash directly ). I test it. Please Fix it! =)

**Comment by TeamSpen210** [comment]
I did actually fix Overgrown in 0605a42fe70bb495bb49ec4b1c1a45108a55fc09, so I'll need to figure out why it's not working. What exactly do you mean by "it's broken"? Not opening? Errors in the console?

**Comment by TuAmigoFiel** [comment]
> I did actually fix Overgrown in [0605a42](https://github.com/BEEmod/BEE2-items/commit/0605a42fe70bb495bb49ec4b1c1a45108a55fc09), so I'll need to figure out why it's not working. What exactly do you mean by "it's broken"? Not opening? Errors in the console?

The exit door don't open with anything, such connected to something as not

**Comment by TuAmigoFiel** [comment]
I see you tagged overgrown, my map is specifically overgrown but the bug appear in all others styles except from the title

**Comment by TeamSpen210** [comment]
Did you stand in front of it? Toggled the input?

**Comment by TuAmigoFiel** [comment]
Yes, and all in the styles tagged the door doesn't open. Why? i don't know

**Comment by TuAmigoFiel** [comment]
i check the console and didn't appear anything

**Comment by TuAmigoFiel** [comment]
anybody check it?

**Comment by LautaroL20** [comment]
Indeed, the Coop Exit Door does not open in Overgrown, P1, and Old Aperture. Screenshots showing the bug:

Overgrown:
![OVERGROWN](https://user-images.githubusercontent.com/59677445/72137521-ac013680-33d6-11ea-83bf-145eca184aa1.png)

P1 Style:
![P1 Style](https://user-images.githubusercontent.com/12244376/72204255-b3ffbb80-3454-11ea-9b42-b684eb70a553.jpg)

Old Aperture:
![Old Aperture](https://user-images.githubusercontent.com/12244376/72204263-b9f59c80-3454-11ea-9ecb-575646035dc3.jpg)

**Comment by LautaroL20** [comment]
By the way, i think that this is an issue which deserves to be pinged as it affects most of the styles.

**Comment by Luke18033** [comment]
@LautaroL20 Did you also test Clean, to make sure it's working correctly there? It'd probably be a good idea to double-check.

**Comment by LautaroL20** [comment]
Yes. In both Clean of wall varieties and Original Clean respectively, the Coop Exit works well with or without imputs. Picts:

Original Clean:
![Original Clean](https://user-images.githubusercontent.com/12244376/73131065-24751380-3fe3-11ea-8a4d-91c7b1314c63.jpg)

Clean of wall varieties:
![Clean of wall varieties](https://user-images.githubusercontent.com/12244376/73131093-79b12500-3fe3-11ea-985d-412ef3b190d6.jpg)

**Comment by Luke18033** [comment]
For Art Therapy, this was caused by the fact that the instance had new connection logic, but EditorItems was still using `CONNECTION_STANDARD`. You might want to check that in all the other styles, see if it's the source of the issue.

**Comment by LautaroL20** [comment]
This is weird... now the Coop Exit seems working well in all Styles for no reason for me. The big question would be what triggers it to make the door not opening. I do not have a remote idea what is going on with this, but what i will do is sending your commited fix to @TuAmigoFiel, so he can put it in their Beemod files so that he can playtest it and give a true and conclusive verdict.

We need more playtesters on this subject though...

**Comment by Luke18033** [comment]
It works fine when nothing is connected to it, and I just fixed the issue in dev.

**Comment by LautaroL20** [comment]
TuAmigoFiel Said that the fix solved his issue. However to make even sure, i did a double check on this and the problem was indeed related that Editoritems was still using `CONNECTION_STANDARD`. Now we all can confirm that this issue finally got solved!
