### ISSUE TITLE
Futboxes

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2990]
These would function exactly like the Weighted Cubes, with a few additional properties inherited from Futbols that make them shatter and break if:
1. Colliding with objects and surfaces too quickly (optional).
2. Hit with a laser/HEP.
3. Shot with bullets.
4. Crushed inside a door/crusher.

Ideally, the structural integrity of the Futbox should be able to hold it together against breaking at speeds such as funnels or slow conveyor belts.

This idea was conceived as a potential solution to puzzles that could be cheesed by using boxes as damage sponges (e.g. in Portal 1 against turrets and HEP's).

**Comment by TeamSpen210** [comment]
What would the appearance be like? Keep in mind I'm not the best modeller.

**Comment by Endermage77** [comment]
It would be the same size and shaped as a Weighted Cube but designed like the Futbol: Mostly glass with plastic edges.

**Comment by Libbybapa** [comment]
I think this item would be very useful if it broke if the player jumped on it.

**Comment by Konclan** [comment]
Better left to a UCP
