### ISSUE TITLE
New Item: Connection Multiplier

### ISSUE THREAD

**Issue by calclover2514** [BEEmod/BEE2-items#2992]
I have noticed that certain items (Buttons, Triggers, etc.) can only have up to 8 outputs.
If I connect 8 Delayers, however, it ups the maximum connection rate to 64 outputs.
This item would basically be exactly the same as the Delayer, except with no delay.

**Comment by UberFartz** [comment]
Just use 'OR' gates

**Comment by LautaroL20** [comment]
If you want to amplify the ammount of outputs in an item´s connection, you will have to use the logic gates AND or the OR depending of your purpose.

**Comment by TeamSpen210** [comment]
Note that BEE2 can detect this situation (either gate with a single input), and optimises out the gate itself.
