### ISSUE TITLE
Monitor

### ISSUE THREAD

**Issue by Danimob** [BEEmod/BEE2-items#2993]
Give monitors inputs to make them come out of the wall when input is active, and then go back in again if the input deactivates.  Also, allow a start enabled to make them already be out without looking at them.  If the monitor is set to not start enabled and has no inputs it should act like the current monitor and  come out of the wall when looked at.  This would be very useful.

Also, Please give monitors outputs which activate when the monitor is smashed. This would be a very interesting element. =)

**Comment by TeamSpen210** [comment]
I'm not sure what the use of this would be. Not all variations of the monitors come out of the wall or are smashable anyway.

**Comment by Danimob** [comment]
I dislike how the monitors only come out of the wall when you look at it, I think it is unrealistic and I also wish to be able to retract them afterwards.

For the breaking trigger, it could be used to make a variety of things.  You could make some form of physical reaction, like how Wheatley has all those lines about the breaking screens, but with it triggering some form of anger action.  It could be used in maps by making some complex puzzle where you have to hit the monitors.

I had completely forgotten about how it was different in different styles, because in the current version (I think) the only style with a difference to the monitor is overgrown, which I don't use much.  Sorry for the long message, or comment, or whatever this is XD

**Comment by Danimob** [comment]
Just remembered something: I saw somewhere about you making a monitors screen for all voices.  (Not sure if this was someone asking or if it was a team member saying.)  If this is the case I would like a start reversed option, or a tick box in the BEE2 application to choose whether a character is  viewed on the monitor, or if only camera feed is sent to the monitor

**Comment by TeamSpen210** [comment]
If caneras are enabled, they generally override the character.

**Comment by Danimob** [comment]
Do they?  I thought it just cycled through all the cameras and the character.  I will check later, on my phone right now.

**Comment by Danimob** [comment]
> Do they? I thought it just cycled through all the cameras and the character. I will check later, on my phone right now.

Just checked, when there is a screenable character and a camera, the monitor cycles through them.

**Comment by TeamSpen210** [comment]
Wheatley is an exception, though he's the only character I think right now... He constantly "interrupts" the monitor cycle. Other characters like GLaDOS would just appear when all cameras are off.

**Comment by Danimob** [comment]
GLaDOS is already on monitors, will test what happens with here now

**Comment by Danimob** [comment]
You are right, the camera completely overrides GLaDOS.
