### ISSUE TITLE
Another monitor idea

### ISSUE THREAD

**Issue by Danimob** [BEEmod/BEE2-items#2994]
Give monitors outputs which activate when the monitor is smashed.  This would be a very interesting element. =)

**Comment by ZombiePwner1** [comment]
Please do not make a separate post for an idea if you've already made one post.

**Comment by Danimob** [comment]
@ZombiePwner1 This was a separate idea to the other one I posted

**Comment by Danimob** [comment]
Separate idea = Separate post

**Comment by LautaroL20** [comment]
If the idea is related to something you´ve already suggested, then merge it in that original post.

**Comment by Danimob** [comment]
Oh, okay.  Sorry for the inconvenience.
