### ISSUE TITLE
Overgrown Floor Goo exit - visible nodraw

### ISSUE THREAD

**Issue by alqeotu** [BEEmod/BEE2-items#2995]
Style: overgrown
Skybox: 3d factory
Exit: floor goo
Bug: In chamber exit have no textures
Level: https://steamcommunity.com/sharedfiles/filedetails/?id=1757958242
![20190601183218_1](https://user-images.githubusercontent.com/51268440/58750509-25799380-849c-11e9-8905-9d9615357796.jpg)

**Comment by Konclan** [comment]
I believe this is a bug with overgrown and bottomless pits

**Comment by Luke18033** [comment]
Shouldn't be a problem anymore with the removal of skybox pits.
