### ISSUE TITLE
Trigger Blocks Variants: 1/4 block-sized triggers with "Handle_8_directions" feature

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#300]
This new item must meet at least three fundamental features:

1 - Handle 8 Directions
2 - Make it possible to be connectables between them, as the default triggers do.

---

We can appreciate just an example of an specific circunstance:

![half width triggers with handling directions2](https://cloud.githubusercontent.com/assets/12244376/13232888/cdc7a178-d98f-11e5-97d7-a64954b0d3a6.jpg)

![half width triggers with handling directions3](https://cloud.githubusercontent.com/assets/12244376/13232784/67186a16-d98f-11e5-8bdc-92e2c604e5c1.jpg)

![half width triggers with handling directions4](https://cloud.githubusercontent.com/assets/12244376/13232870/bd05bf32-d98f-11e5-83a2-330bb19c8898.jpg)

**Comment by Enterpise** [comment]
I can say you likes drawing ;) Interesting suggestion anyways!

**Comment by LautaroL20** [comment]
Well, i heard somewhere "A picture is worth a thousand words". I enjoy making illustrative posts, instead of making lots of boring text. Thats just my point of view.

**Comment by LautaroL20** [comment]
I feel kinda dissapointed that no one saw my post when it was maded, but ill be doing this myself.

**Comment by Endermage77** [comment]
What is the 8-Direction handle used for in this case?

**Comment by LautaroL20** [comment]
Considering tha the Trigger will have a similar dimensions to a 4x2x2 Kenner´s block, it will be good to having this type of handling feature.

**Comment by Endermage77** [comment]
Is it actually standing on edge or did you somehow manage to place it against a thin wall there?

**Comment by LautaroL20** [comment]
> Did you somehow manage to place it against a thin wall there?

Triggers are using the `CanAnchoorOnBarriers` feature, wich allows you to placing them on `BarrierType` items.

**Comment by Endermage77** [comment]
I didn't know that let you put stuff on the inside face. Neat.

**Comment by LautaroL20** [comment]
Then, this Wiki section is for you! We maded it since a time ago: https://github.com/BEEmod/BEE2-items/wiki/editoritems.txt

Here is the specific part though:

* `CanAnchorOnBarriers`: If enabled, several surfaces will be treated as attchment points: the side of Glass/Grating, tops of 90° Angled/Glass Panels, the top of Track Platforms, and the surface of Piston Platforms. Eligability for placement is defined by the relavant item classes (`ItemBarrier`, `ItemAngledPanel`, `ItemRailLift` and `ItemPistonPlatform`).

**Comment by Endermage77** [comment]
I guess I knew about those, I just thought that you could only mount items on the outside of barriers for some reason.

**Comment by Luke18033** [comment]
These should be 1/4-block-sized instead. You could place two of them next to each other and connect them for a half-block.

**Comment by LautaroL20** [comment]
Yes, that would be better. When ive made this suggestion in 2016, i think i was kinda rookie at thinking about an item´s structure and how it would bring the best possible performance. I´ve updated the title and a bit of the post´s description with your suggestion. Everyone is pretty much welcome here to keep bringing additional ideas for it.

**Comment by Konclan** [comment]
From @TeamSpen210

"What I might want to add is an 'invisible' light bridge instead. That also allows you to place things on it, but doesn't take up as much space and can be more easily removed."

**Comment by Luke18033** [comment]
We can't use `CanAnchorOnBarriers` for this, it breaks with a 8-position handle.

**Comment by LautaroL20** [comment]
Yep, i will remove that point from the description.

**Comment by LautaroL20** [comment]
Also, i will add the mention of the 2/4 and 3/4 variant sizes in the title, i do not know how i missed those.

**Comment by LautaroL20** [comment]
I think that the 2/4 and 3/4 variants can perfectly be merged/replaced by adding the ability of connecting 1/4´s variants between them making one trigger block.

**Comment by Luke18033** [comment]
Yeah, plus Button Type is already used to select the type of trigger

**Comment by Konclan** [comment]
#3886
