### ISSUE TITLE
New items

### ISSUE THREAD

**Issue by Kalail** [BEEmod/BEE2-items#3002]
Hello can you add things from Blue portals? And can you make it so that we can voice the test camera itself? And you can put another texture for any surface. And we could add any kind of music and change it at any time. And you can make a core, for example the boss battle will be, and so you can change the textures-present the dirt of the core, its eyes and body. Thanks in advance

**Comment by Luke18033** [comment]
Please don't combine suggestions like this. There's a pinned issue for BP items. There aren't going to be built-in options for custom music or voice lines, although [BMMC](https://github.com/BEEmod/BEE2-items/wiki/BEEmod-Music-Changer) can be used for custom music. Cores aren't going to be added.

**Comment by Kalail** [comment]
> Пожалуйста, не объединяйте такие предложения. Существует проблема с закреплением для элементов BP. Там не будет встроенных опций для пользовательской музыки или голосовых линий, хотя [BMMC ](https://github.com/BEEmod/BEE2-items/wiki/BEEmod-Music-Changer)может использоваться для пользовательской музыки. Ядра не будут добавлены.

Thank you
