### ISSUE TITLE
Gridded wall ignored by offset laser emitter/catcher

### ISSUE THREAD

**Issue by Libbybapa** [BEEmod/BEE2-items#3005]
The offset laser and catcher currently ignore the gridded wall item.  It would be great if they respected it if possible.  

https://youtu.be/w1N7fGybFxI

**Comment by Libbybapa** [comment]
I see there is a "Won't Fix" label added.  Could you please explain why it won't be fixed?

**Comment by LautaroL20** [comment]
This is not possible to fix, because the compiler seems to have a prefference in the internal configuration where i do not have any control.

**Comment by LautaroL20** [comment]
@Libbybapa - By the way, how did you see the label ive applied just a few seconds ago over an issue that was made about 2 hours ago? Unless you were pending looking this issue in an insane way, i do not get it how you catched a label that ive applied just a seconds ago...

**Comment by TeamSpen210** [comment]
It will be fixed, but it requires me to finish a rewrite of the texturing/tiling system. That is mostly done though.

**Comment by Libbybapa** [comment]
> @Libbybapa - By the way, how did you see the label ive applied just a few seconds ago over an issue that was made about 2 hours ago? Unless you were pending looking this issue in an insane way, i do not get it how you catched a label that ive applied just a seconds ago, something that makes me feel scared...

I'm not sure why you feel it is any of your business what I do with my time and I'm also not sure why you would be so rude and insulting.

But, to answer your question, no I have been "looking at this issue in an insane way".  I have been perusing the site looking at the various threads, out of interest in what other people have posted as ideas, bugs, etc...  In one of the times when I was looking at the index of items I noticed the  BIG GRAY BOX that said "won't fix" next to the title of this thread.  It must have been quite a coincidence as I see you have consequently closed it and it no longer appears in the list of threads. 

I would certainly appreciate it in the future, if you would treat me and everyone else with a modicum of respect and kindness.  We all deserve that.  Thanks!

**Comment by Libbybapa** [comment]
> It will be fixed, but it requires me to finish a rewrite of the texturing/tiling system. That is mostly done though.

Sounds good.  Thanks, TeamSpen.

**Comment by LautaroL20** [comment]
> Libbybapa said: " I'm not sure why you feel it is any of your business what I do with my time and I'm also not sure why you would be so rude and insulting"

> Libbybapa said: "I would certainly appreciate it in the future, if you would treat me and everyone else with a modicum of respect and kindness.  We all deserve that.  Thanks!"  

It looks like you have a persecutory delirium as i have rarely seen on the Beemod community, only just for having asked you a pretty normal question that would draw the attention of any normal person.

Ive never disrespect people in the Beemod community... I really do not have idea where you came from, and honestly i do not care. But if you will stay here, be respectful with the author of Beemod and their collaborators and try be a mentally balanced person who doesn´t react like that when someone makes a you a simple and logic question. If you don´t want to reply to someone´s question, instead just ignore it.

**Comment by Libbybapa** [comment]
Why are you making any personal comments about me at all?  The only reason I see for this post of yours and the last one is solely to be unkind.  Please stop.  Thanks!
