### ISSUE TITLE
New Items and triggers

### ISSUE THREAD

**Issue by Kalail** [BEEmod/BEE2-items#3007]
**_Hello_** can you add scenery for test chambers and for BPS for example chair, computer, test counter. Is it possible to add a trigger which will shake the room and collapses. There's an Elevator we can take to the next test, but it's really just a lift.

**Comment by TeamSpen210** [comment]
No.

**Comment by Kalail** [comment]
> No.

Why?

**Comment by Luke18033** [comment]
BEE2 isn't meant to be a Hammer replacement. Generally, things which don't add to puzzles in any way won't be added, which none of your suggestions do. Read the [contributing guidelines](https://github.com/BEEmod/BEE2-items/blob/master/.github/contributing.md).
