### ISSUE TITLE
Add Open to Center Option to 1/2 Panel

### ISSUE THREAD

**Issue by Libbybapa** [BEEmod/BEE2-items#3009]
Add the option to the half-panel to so that it can open to the center of the voxel it is mounted on rather than only being able to open to the outside edge of the voxel.

**Comment by Luke18033** [comment]
What do you mean, doesn't this already exist with the Angle property?

**Comment by TeamSpen210** [comment]
Indeed, use the angle option to move it around. Unless you mean the panel arms centred into the voxel, with the surface ¼ from the end... I haven't implemented that since it'd not be as useful.

**Comment by Libbybapa** [comment]
I guess I missed the angle property.  That was what I was wanting.  Thanks!
