### ISSUE TITLE
Field relay crashes when it has to draw or redraw ant lines

### ISSUE THREAD

**Issue by FierceThundr** [BEEmod/BEE2-items#3012]
I have found a way to crash the editor by trying to take a second connection out of a field relay.

**Comment by Luke18033** [comment]
Disable antline visibility, does it still crash?

**Comment by Luke18033** [comment]
Closing this issue due to lack of response from author

**Comment by FierceThundr** [comment]
Sorry, for the lack of response, I have not been on github in the past good while when I really should have due to my posts here. I will be testing this bug a bit right now. I imagine it could be very helpful. Additionally, this was not a compile error. It is an instant crash upon making a second outbound connection from a field relay.

**Comment by FierceThundr** [comment]
@Luke18033 I have taken some time to test the crash a bit to try and find consistency, or a specific cause of the crash. I have done tests separately between whether ant lines were enabled or disabled completely.

   **Enabled** Inconsistent crashes caused by unknown reasons...
   **Disabled** No crashes even after doing many of the things that previously crashed the editor...

While I do not believe this issue post still stands up, I have tried to edit the original post to follow this test I've done.

**Comment by Luke18033** [comment]
What does the area around the field relay look like, can you post a screenshot? There's a crash that can be caused by antlines being blocked within the same voxel as the item.

**Comment by FierceThundr** [comment]
@Luke18033 I'll test it when I'm back online

**Comment by Konclan** [comment]
I think this is to due with the relay antline colliding with something in the same voxel, that tends to crash with laser items.

**Comment by FierceThundr** [comment]
@Luke18033 I've run another test akin to ones I did initially. Going off of the ant line idea, I tried to move the stuff in such a way to aggravate some ant line bug. Also I recorded it so you can see what I was doing and how the editor was acting. The ending is an immediate crash that has nothing else to see outside of the video... [https://drive.google.com/file/d/1vXvKA3f0PiQMmpVWxvaDmswAsxBrlFIJ/view?usp=sharing](url)

**Comment by Luke18033** [comment]
This is the general arrangement that's known to cause a crash (when antlines are enabled, and exiting the voxel out the top):
![image](https://user-images.githubusercontent.com/19228201/59620209-25ef6c80-90e1-11e9-85a3-9dbb67554d44.png)
Fizzlers can also be used in place of the light strip...
![image](https://user-images.githubusercontent.com/19228201/59620360-7f579b80-90e1-11e9-844c-e9b60500589f.png)
Which is likely the cause of your crash, since there would be a fizzler near the relay. Try replicating the setup in my screenshot with an output relay where the laser catcher is, see if the game crashes.

**Comment by FierceThundr** [comment]
I've done this test and the catcher does cause an immediate crash, but I'm still a bit confused...

**Comment by Luke18033** [comment]
Does it also crash when you use a field relay in place of the catcher?

**Comment by Luke18033** [comment]
Closing again due to lack of response
