### ISSUE TITLE
Add in-game models for items

### ISSUE THREAD

**Issue by xDadiKx** [BEEmod/BEE2-items#302]
Items are missing in-game editor models like Chamberlock or the Portal Gun Pedestal

![2016-02-24_00004](https://cloud.githubusercontent.com/assets/13087761/13297988/f10b04d8-db2c-11e5-9499-7f654e7f2431.jpg)

**Comment by LautaroL20** [comment]
Well, there are several missing models to be honest, (Co-op checkpoint, reflection gel dropper, for example). But Teamspen210 will include them progressively in each future Pre-release.

**Comment by xDadiKx** [comment]
Yea I know, I just showed some examples.

**Comment by ZombiePwner1** [comment]
The portal gun stand has a model since it's fixed.

**Comment by Luke18033** [comment]
Both of those items now have proper models.
