### ISSUE TITLE
Signage (and connection signage) no longer display the image showing "which number is what sign) in 4.35

### ISSUE THREAD

**Issue by philhzss** [BEEmod/BEE2-items#3020]
Hi,

If you launch BEE2 4.34, and select the "signage" item, there is an image underneath the description showing you what "number" to enter in the timer in-game to get what sign. 

Doing the same thing in the latest, 4.35, there is no image. Therefore the only way to tell what "number" yields what sign is to try to guess. Is this a bug / can the image-chart be added back??

Thanks for all your hard work!!

Edit: oops, in the title I opened a quotation mark and closed a bracket.. sorry

**Comment by Luke18033** [comment]
There's now a "customize signage" button in the item configuration window, which shows this information and includes additional signs you can select.

**Comment by philhzss** [comment]
Oh wow, I must've missed that in the release notes. Very cool!! Thanks for the quick response and sorry
