### ISSUE TITLE
Several "SP entrances" in 1960's Aperture have visible nodraw around entrance door

### ISSUE THREAD

**Issue by philhzss** [BEEmod/BEE2-items#3022]
Hi,

Just did some testing, and even with a blank empty test chamber, this occurs. Here's what it looks like:
![20190615122024_1](https://user-images.githubusercontent.com/41757256/59553831-f4539580-8f68-11e9-94e6-331fe9cd054c.jpg)

Once you move forward and approach the door, the white light turns into a smear of whatever colour is around it (which is what you call a leak I think) and then when the door opens, all is good.

This occurs using SP entry 2, 3, 4, 5, 6 and 7. Basically in all the corridors, but doesn't affect entry 1 (lobby). It seems that it's because there is "empty space" next to the door, that only loads in when the level loads in (when you enter the pre-made entry).

Obviously this is not a severe bug at all, especially since it only affects "before the level", and maybe it's something that can't be fixed. But I thought I'd report it. I have not tested other styles yet.

Using current release (BEE 4.35)

Thank you for your hard work!!

Phil

**Comment by Luke18033** [comment]
Does the goo in the sphere render? If it does, then this isn't an actual leak, just a visible nodraw.

**Comment by philhzss** [comment]
The goo does indeed render. You're right, I had a leak once and the goo was not there. It must just be a visible nodraw then. Thank you!!

**Comment by TeamSpen210** [comment]
It’s actually that the two sections of wall on either side are missing. When the door is closed the chamber itself is blocked from being rendered.

**Comment by philhzss** [comment]
True. Is this just the way it is (in the base game) or are those entries custom made and part of BEEMod?

**Comment by Luke18033** [comment]
They're a part of the mod

**Comment by Luke18033** [comment]
If this wasn't alreay fixed, I'd assume it's been now after Critfish updated all the corridors?

**Comment by Luke18033** [comment]
Actually yeah this looks like the "lazy" corridor which was literally just a Clean one with its textures swapped, so this has almost certainly been fixed.

**Comment by TeamSpen210** [comment]
1-6 yes, 7 no.

**Comment by Luke18033** [comment]
Does 7 have this issue?
