### ISSUE TITLE
Linked Dropperless Cubes are Broken

### ISSUE THREAD

**Issue by Libbybapa** [BEEmod/BEE2-items#3027]
When you have a connection to the dropper to spawn the cube, the dropperless cube no longer fizzles.  This used to work but is now broken. 

 https://youtu.be/Gq6PoJxsdS4

**Comment by TeamSpen210** [comment]
This on the latest version? I fixed a bug which would have made this broken in 4.34.0.

**Comment by Libbybapa** [comment]
I'm using 4.35.0.

**Comment by TeamSpen210** [comment]
This seems to now be fixed.
