### ISSUE TITLE
Antlines and Timer Icon do not Stay Lit 

### ISSUE THREAD

**Issue by Libbybapa** [BEEmod/BEE2-items#3028]
Antlines that are made using logic gates and the timer icons they show when connected to pedestal buttons do not stay lit up for the correct amount of time.  Instead they turn off after a second or so while the pedestal is still ticking away and both antline and icon should still be lit. 

https://youtu.be/_MMd-H-7rCM

**Comment by TeamSpen210** [comment]
Interesting. What's happening here is that one or more of these gates is being optimised out (since it has only 1 input), which as you can see caused the checkmark to convert to a timer. But the timer delay didn't transfer with it, or wasn't applied to the timer "item".

**Comment by Libbybapa** [comment]
Interesting.  I'm happy to see the 'Fixed' label.  Thanks!
