### ISSUE TITLE
New for Turrets

### ISSUE THREAD

**Issue by Kalail** [BEEmod/BEE2-items#3029]
how about that? A new piece which will be painted turrets, for example on a timer to put the turret 9 will be black, but you can still add DEFECTIVE TURRETS?

**Comment by ZombiePwner1** [comment]
What is the use for this? Turrets with paints will serve no purpose other than being decorative + the defective turret will not be added. This mod is designed solely for making puzzles not making a story map. Use the hammer editor for that.
