### ISSUE TITLE
New item: Antigravity panel

### ISSUE THREAD

**Issue by Kalail** [BEEmod/BEE2-items#3033]
**_New item Antigravity panel_**

**Antigravity panel**: 1 piece panel must be placed on the floor and 2 piece on the ceiling or on the wall when the player comes to the first part then it hits the ceiling or on the wall where the second part and the player goes on the wall or on the ceiling. To the player to get to the floor he needs to be back on the 2 part. This panel works the same way on cubes and turrets. Below is how it will look like 

![Flip flop](https://user-images.githubusercontent.com/51409156/60163716-27363d00-9837-11e9-8c56-41a4a0dd328f.png)

**Comment by Luke18033** [comment]
What map is this from? It's probably not possible for the same reason as Adhesion Gel.

**Comment by Kalail** [comment]
> С какой это карты? Вероятно, это невозможно по той же причине, что и адгезионный гель.
This is from the Flip-Flop card there is this element. It would be nice if it is in the new version of Bee mod

**Comment by Zerarath** [comment]
@Luke18033 How did Prototype implement the Adhesion gel in his two Adhesion maps? I'm wondering..

**Comment by ZombiePwner1** [comment]
@Zerarath It's because prototype use very clever map scripts to make the map rotate when the player touched reflection gel as it's re-skinned to look like adhesion gel.

**Comment by Luke18033** [comment]
Decided to take a look at that map to see how it worked. There are two copies of each room, which use worldportals to teleport you between them when you launch off the gravity panels. So this isn't really possible in BEEmod.
