### ISSUE TITLE
Vactube curving not working as intented

### ISSUE THREAD

**Issue by mets11rap** [BEEmod/BEE2-items#3034]
My layout for my vactubes is this:
![](https://i.imgur.com/Uz03vfQ.png)
(Yes, it's all linked properly)
But it turns out like this with no curved entrance:
![](https://i.imgur.com/vE3JwK4.jpg)

**Comment by Konclan** [comment]
Is it possible you connected them backward, the direction of the connection matters I believe?

**Comment by Konclan** [comment]
My Belief was correct, the order in which you connect Vactubes matters. Here is a video demonstrating what I mean.
https://youtu.be/xnSoM1R6fTk

**Comment by mets11rap** [comment]
@Konclan I made a point of connecting them the right way

**Comment by mets11rap** [comment]
It doesn't seem like this issue will get any more attention so I'll close it.
