### ISSUE TITLE
Implement the Paint Gun from AT to be also available in Portal 2

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3036]

**Comment by ZombiePwner1** [comment]
@LautaroL20 Who came up with this idea?

**Comment by LautaroL20** [comment]
It was suggested by an user called "Bruno Machado (brunobmmachado)" from the Bee´s Discord Server.

**Comment by ZombiePwner1** [comment]
This would be pointless I remember @TeamSpen210 saying that the paint gun won't be in portal 2. + We can't change the portal gun model to AT's paintgun.

**Comment by LautaroL20** [comment]
That is not what he said in the Discord server, it seems you do not check the Discord channel at all...

**Comment by machadobsm** [comment]
Thanks, LautaroL20. I hope this can be done! It would be nice!

**Comment by LautaroL20** [comment]
Indeed, @machadobsm I am as enthusiastic as you regard to this possibility!

**Comment by Luke18033** [comment]
Replaced by #4296
