### ISSUE TITLE
Voiceline´s Trigger

### ISSUE THREAD

**Issue by Kalail** [BEEmod/BEE2-items#3041]
why not add a voice trigger, for example, if the player sees a new element so that the map Creator can voice as the element works

**Comment by Luke18033** [comment]
What?

**Comment by Kalail** [comment]
Sorry, I'm from Russia, I don't know English well

**Comment by LautaroL20** [comment]
I think he means a voiceline trigger that when walked thru, it plays a specific voiceline.

**Comment by Kalail** [comment]
I mean, you can record your voice in the program or download a ready-made record and then this audio track is presented in the game. You can also write how the subtitles will look like

**Comment by Konclan** [comment]
This is something left for Hammer. I already suggested #531 which would be better in a puzzle where the author needs to leave notes, not to tell stories.

**Comment by LautaroL20** [comment]
Yep, true.
