### ISSUE TITLE
Rocket Turret not working

### ISSUE THREAD

**Issue by SocialTag** [BEEmod/BEE2-items#3052]
Cmon, fix this. im making a portal 1 style level and im using rocket turrets in my level, i tried to do it , its supposed to send a rocket to break glass, like it did in portal 1. but, it didn't even shoot, it should have the things it had from Portal 1:
1. Rockets can break glass, like in Portal 1
2. They actually shoot
3. The rocket is visible, you can't actually see the rocket

**Comment by LautaroL20** [comment]
Spencer mentioned once that he has no plans on fixing it anytime soon, and having in count the fact that the code of the item itself was removed, makes me think that the Rocket Turret should be directly removed from Beemd as it is currently an useless item.

**Comment by Luke18033** [comment]
Okay, what is the deal with this "invisible rockets" issue? It works perfectly fine for me and always has.

**Comment by ZombiePwner1** [comment]
@Luke18033 Does the rocket properly fire from the turret in the direction it's facing?

**Comment by Luke18033** [comment]
Everything works fine for me, besides the targeting laser being inaccurate. I've also started having some issues with the rockets randomly fizzling, but those seem to be related to the geometry branch and should be easily fixable.

**Comment by Luke18033** [comment]
Oh and there's the turret being invisible in OldAp, which I figured out the cause of.

**Comment by ZombiePwner1** [comment]
@Luke18033 That's weird. Wonder why the rocket turret works for you. Are you using a modified instance at all?

**Comment by Luke18033** [comment]
Nope, completely unmodified instance. They're even visible when fired from a standalone `npc_rocket_turret` placed in a Hammer map (without the fixes added by the BEE version).

**Comment by ZombiePwner1** [comment]
@Luke18033 The hell? That's weird.
