### ISSUE TITLE
Reflection gel bomb gel type doesn't work.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3053]
The bomb type doesn't seem to work regardless of the settings.

**Comment by FrozenDragon0** [comment]
Still an issue.

**Comment by Luke18033** [comment]
It shouldn't be, unless...OH MY GOD DID MY CHANGES GET REVERTED AGAIN?

**Comment by Luke18033** [comment]
This seems to be working correctly? What style are you on?

**Comment by FrozenDragon0** [comment]
Haven't test yet. Last I recall clean style was having issues with it.
