### ISSUE TITLE
Shutdown delayer and trigger once not working together

### ISSUE THREAD

**Issue by SpaceYoshi** [BEEmod/BEE2-items#3057]
Title says it all. Using BEE2 4.35.1 application with BEE2 4.35.0 packages.

Trigger Once is connected to a shutdown delayer. Shutdown delayer is connected to stairs (I've also tried half panels).
It works fine with Trigger Multiple. 

The problem only seems to be related to the shutdown delayer, the activation delayer is working as intended.

**Comment by SpaceYoshi** [comment]
To anyone with the same problem: I worked around this by using a Set/Reset Latch in combination with the Input A/B items. A Trigger Once is hooked up to both an Input A and an activation delayer. The activation delayer is hooked up to an Input B. Both inputs lead into the S/R Latch, which is hooked up to two half panels.

Situation: player enters into a room, panels close and the player is stuck there for a set amount of time, after which the panels open again.

It uses more entities but it gets the same job done.

**Comment by TeamSpen210** [comment]
Actually, I don't think this is a problem. A Trigger once provides a permanent output, which means the delayer will be kept on forever since the input never turns off.
