### ISSUE TITLE
Luke please fix your large glass panels from being placed like this.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#3059]
![20190714215800_1](https://user-images.githubusercontent.com/18079316/61184624-8d69ef00-a682-11e9-90cc-56a2fa3c00e1.jpg)

![20190714215808_1](https://user-images.githubusercontent.com/18079316/61184633-ac688100-a682-11e9-85b4-98313959615b.jpg)

![20190714215813_1](https://user-images.githubusercontent.com/18079316/61184635-b0949e80-a682-11e9-8a7a-97016dc79519.jpg)

**Comment by Luke18033** [comment]
Not my fault, normal glass/angled panels can be placed this way as well, at least on Clean. No real good reason not to allow it, it's not like it really causes problems...

**Comment by LautaroL20** [comment]
I really doubt that a reasonable mapper would want to publish a puzzle with an item overlapping each other anyways...

**Comment by Konclan** [comment]
Rogan wants to know your location

**Comment by Fragmentation123** [comment]
Will the glass panels eventually be added in a release?

**Comment by LautaroL20** [comment]
> Rogan wants to know your location

Wat.

> Will the glass panels eventually be added in a release?

Yes.

**Comment by Konclan** [comment]
A joke.

**Comment by Alfe5** [comment]
Rogan REALLY wants to know your location
