### ISSUE TITLE
Closed solid field is still using clean frames in overgrown style.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3060]
![20190714220652_1](https://user-images.githubusercontent.com/18079316/61184720-b474f080-a683-11e9-8d00-1a65df8098ae.jpg)

**Comment by Konclan** [comment]
That frame doesn't look clean?

**Comment by Konclan** [comment]
Nvm it is the clean model, I never noticed or just forgot how dirty the clean fizzler model actually is lmao

**Comment by FrozenDragon0** [comment]
Just realized this a duplicate of another issue I made that's the same problem: https://github.com/BEEmod/BEE2-items/issues/2454
