### ISSUE TITLE
Pellet emitter ignores unmarked "Start Enabled"

### ISSUE THREAD

**Issue by underlineGalaxy** [BEEmod/BEE2-items#3066]
https://drive.google.com/file/d/1E6hV1keSaX8hAz5TqFBtfsMzNKVvqnGL/view?usp=sharing

Wether or not "Start Enabled" is marked, the pellet emitter ignores all my inputs. I can't use a button to let it drop a pellet.

In theory I could use the infinite pellet, but since my puzzle revolves around the refresh mechanic this workaround isn't possible here. Maybe I am doing something wrong? I tried using A/B inputs to no avail.

**Comment by JavierNovellon** [comment]
I had this problem too. The "Toggle" item does not seem to do it either. The Pellet emitter seems to only respond correctly when the input is a floor button.

**Comment by underlineGalaxy** [comment]
@JavierNovellon not even that works for me!

https://drive.google.com/file/d/1YZbU0rvqIcUs_qR5SSIYz5_deHP_ijca/view?usp=sharing

**Comment by Konclan** [comment]
The logic for pellet emitters seems completely broken rn

**Comment by JavierNovellon** [comment]
> @JavierNovellon not even that works for me!
> 
> https://drive.google.com/file/d/1YZbU0rvqIcUs_qR5SSIYz5_deHP_ijca/view?usp=sharing

Try disabling the Timer. This will make the Pellet Emitter behave exactly like in Rexaura:
Button is pressed = Pellet shoots, travels
Button is unpressed = Pellet explodes
Button is pressed = Pellet shoots, travels
ditto.

Figure 1 (use a cube instead of a player if required)
https://drive.google.com/open?id=1Rka6eeWVeFpNNtnXHAd3Je-7ZTNp3IQS

Figure 2
https://drive.google.com/open?id=10sj96XNSSmTUZIA5cqoPuQV5CVj1dqqr
(please do tell me if the video says "we're still processing" I seem to be having some tech difficulties)

**Comment by underlineGalaxy** [comment]
@JavierNovellon yup watched both videos, I get what you are saying.

However, my puzzle depends on the "refresh" mechanic, whereas if a pellet passes through a portal it's lifespan is extended, therefore I can't use those unfortunately.

It seems to me however that the green pellet emitter and normal pellet emitter are the same entity? Maybe this is what making it behave like this?

**Comment by JavierNovellon** [comment]
@underlineGalaxy Wait you CAN see my videos? Am I the only one who's getting the "we're still processing this video check back later" message??

Anyway. Yes, they are the same item within Portal 2's editor. Kinda like a cube can be set to a sphere. That may actually have something to do with it. I've had problems in the past while trying the unused versions of the Piston Platform (you get the standard, then the black panel, then the white, and the other two types are unused). Maybe if they were different items the problem could be solved.

**Comment by underlineGalaxy** [comment]
@JavierNovellon well it does take a while to process so I just downloaded it, the first one was up but the second was processing.

Well if that's the case then it seems we have to await dev input :/

**Comment by JavierNovellon** [comment]
@underlineGalaxy oh ok then. Yep, we might just have to wait.

**Comment by TeamSpen210** [comment]
I must have broken something with the emitter. Additionally I really need to decide how pedestal buttons should work with them, it should probably use the locking behaviour.

**Comment by underlineGalaxy** [comment]
@teamspen210 thanks for fixing it. Is there a way I can download the fix without you having to merge all the new fixes?
