### ISSUE TITLE
What Are The Timer Numbers For Signage? 

### ISSUE THREAD

**Issue by C00lest** [BEEmod/BEE2-items#3067]
Just Let me Know I need To Use Signage.

**Comment by Konclan** [comment]
In the Style/Item Properties window you go to the Items tab and click the Configure Signage button. On the left side are the selected signages your currently using, hover over one with you cursor to see what time its assigned to in the editor. You can also rearrange, add, and remove signages.

**Comment by LautaroL20** [comment]
Question has been answered, closing.
