### ISSUE TITLE
Add Cube Triggers

### ISSUE THREAD

**Issue by Libbybapa** [BEEmod/BEE2-items#3072]
As the title suggests, I have had quite a few situations where each of the triggers would be useful if they could be used to detect cubes rather than players.  Those situations include but are not limited to adding autosave points to the times that the player acquires cubes (in well designed maps that makes more sense than autosaves when the player reaches a location) and definitively preventing the grating glitch.  The cube triggers could be a separate item or a setting within the existing trigger item so the the options of detecting player or detecting cubes could be individually toggled.

**Comment by Libbybapa** [comment]
A working package of a cube trigger can be found here:  https://drive.google.com/open?id=1f40wiatCbz5jvIaPlkM9WOka0i195S79  It is not really a finished work, though, as I didn't know what I was doing when I made it up.  I stole from various existing packages and modified as necessary with a lot of trial and error.  I'm sure some of it is not done in the ideal way but hey, it works.  :)  I have no idea if it would properly pack into a map.  It would be useful to have the cube version of the trigger once and the trigger autosave also, but I don't know how to make those.

https://www.youtube.com/watch?v=fczRyTALq3I

**Comment by Neshiro** [comment]
How I have wished for someone to make this one day ! Thanks ! 👍

**Comment by Libbybapa** [comment]
You're welcome.  I'm glad to hear someone else will finds it useful.

**Comment by Libbybapa** [comment]
I have learned a lot since I posted that package.  I spent a little time today cleaning it up a bit.  Functionally it is the same except it no longer makes any noise on activation/deactivation.

**Comment by Neshiro** [comment]
I can't find it in the items list, even after re-extracting the packages. Do you know how I can make it appear ?

**Comment by Libbybapa** [comment]
You downloaded the above linked folder named cube_trigger?  Inside that main folder is the info.txt and folders: resources, and items.  That main folder (cube_trigger) needs to be placed in the BEE packages folder.  Once it is placed there and BEE is restarted, it should appear in your items.

**Comment by Libbybapa** [comment]
Let me know if you have success or encounter other issues.

**Comment by Neshiro** [comment]
It's solved now. The issue was that there was another "cube_trigger" folder inside the archive and inside it, the other files. I think you should zip the package on your drive so that it's ready to go immediately and you know it works. Anyway, thanks for your time.

**Comment by Libbybapa** [comment]
Good ideal.  Here is a link to another much more refined package:  https://drive.google.com/open?id=1KGqOslYRo6Q8-_V2AZvrINeKW6uVrOeh  This version can be downloaded as a zipped archive and will work if placed in the packages folder.  It is updated to include three items:  cube_trigger_once, cube_trigger_multiple, and connection_save.  All three accept connections.  The connection_save item accepts input connections and if all connections are ON it will perform an autosave.  The two cube triggers also accept connections.  If all connections are ON, and a cube is int he trigger area the output is activated.  Enjoy!

**Comment by Neshiro** [comment]
Does it also detect turrets ? It would be useful to me for a new chamber I'm making.

**Comment by Luke18033** [comment]
That's definitely possible, although it would probably be a specific option you'd have to turn on. That would get kind of confusing though, having 3 separate checkboxes for players, cubes, and turrets. Either way, Radelite's addons for BEE2.2 had a visible turret sensor item which might work for your purpose.

**Comment by Neshiro** [comment]
I wasn't asking for a whole new item, just to make this one able to detect by default every physical object (cubes, spheres and turrets). It would just need to be renamed "Objects trigger" instead of "Cube trigger".

**Comment by Libbybapa** [comment]
When I set up the item it actually took some effort to make it not activate due to turrets.  IIRC you would need to open the specific instance in hammer and change the filter for the trigger.  That is not a change I would want, though you could certainly do so on your end if you want it that way.

**Comment by Luke18033** [comment]
I've always thought that this would just be a "detect cubes" property on the existing triggers, not an entirely new item. In that case having it detect turrets would be as simple as adding an additional property. We don't want it to detect all physics objects, that would mean you could also use things like cameras or Overgrown broken tiles to activate them.

**Comment by Neshiro** [comment]
You're right, if every physic item is detected it could break puzzles. What I meant originally was every "useful" physic item only (cubes, spheres and turrets).
I'll look into it and see if I can tweak it. I wonder if this will be packed properly when publishing though.
Thank you two for your answers.

**Comment by Libbybapa** [comment]
IMO one of the most significant benefits to these triggers vs. the existing ones is that they accept inputs.  An added checkbox on the existing triggers in order to detect cubes (or other physics objects) would lose that most beneficial property.

**Comment by Libbybapa** [comment]
> I wonder if this will be packed properly when publishing though.

They pack without issue.

**Comment by Luke18033** [comment]
Those inputs can just be added to normal triggers as well. For the connection save, that's already been suggested in #1077 as a separate item with additional functionality.

**Comment by Libbybapa** [comment]
I asked for the current triggers to accept inputs several years ago.  My understanding is that they currently use the connections to define the activation area either precludes normal input connections or at least makes it difficult to implement.  I'd be all for it if it worked.

**Comment by Luke18033** [comment]
Can't you use an AND gate to replicate that functionality?

**Comment by Libbybapa** [comment]
I see how a trigger multiple that accepts inputs could be replicated with an AND gate, but I do not see how a trigger once or trigger autosave that accepts connections can be replicated in the same manner.

**Comment by Libbybapa** [comment]
...actually using logic gates I could replicate use a trigger multiple to replicate a trigger once that accepts connections but it is not very straightforward.

**Comment by TeamSpen210** [comment]
When I said that adding the inputs would cause issues, it probably did. But not anymore since I did the connections system. Not sure about turret detecting, is it really that useful?

**Comment by Libbybapa** [comment]
I can think of a couple ways that detecting turrets might be useful.  I think that a check box for detecting the player, a checkbox for detecting turrets, and a checkbox for detecting cubes/sphere along with accepting inputs would be excellent improvements to the current trigger items.

**Comment by Neshiro** [comment]
It would certainly be handy. To me, the more possibilities you allow, the more creative the players can be.
Even if some functionnalities can appear useless to some, there will statistically always be people who will use them someday in a puzzle and will be thankful to you developers for having allowed them.

**Comment by King0191** [comment]
Once this is all said and done, will a _Pull Request_ be done to officially add these? Not that adding User Packages is hard, but it would be more preferable (In the long run) to have items built in.

**Comment by Konclan** [comment]
Moving to #3886
