### ISSUE TITLE
Add Death Fizzler Options

### ISSUE THREAD

**Issue by Libbybapa** [BEEmod/BEE2-items#3073]
I have had quite a few times where a field that allowed portal shots but fizzled cubes and fizzled portals if you passed through it would be useful.  I was thinking about the death fizzler item and I think it would be very effective to either add the option to the current death fizzler item (auto-drop?) or add another death fizzler item that had alternating red and light blue bars.  All states would allow portal shots but the blue/red would fizzle objects and kill the player and the solid blue would allow portal shots but fizzle objects and fizzle existing portals if the player passed through it.  
![deathred](https://user-images.githubusercontent.com/33527465/61649312-19bd7880-ac66-11e9-80c4-f613ff76f8c3.png)
![deathblue](https://user-images.githubusercontent.com/33527465/61649326-1f1ac300-ac66-11e9-83f0-af4eacd25a39.png)
![deathboth](https://user-images.githubusercontent.com/33527465/61649336-22ae4a00-ac66-11e9-8864-cb0266b8d7d3.png)

I think the properties would be intuitively obvious given the visual.
It would have the same options as the normal death fizzler of Red/Blue, All Red, All Blue, and OFF.

One particularly effective use for this item would be the Red/Blue state instead of grating.  In 99% of cases it could be used to definitively prevent the grating glitch by fizzling any cube that passed through the surface behind it and killing the player if they tried to pass through it.

**Comment by Libbybapa** [comment]
I have also seen a couple of maps that used fast on/off switching of a normal fizzler to create the field that allowed portal shots but fizzled objects that passed through them or fizzled existing portals if the player passed through.  The logic was quite interesting but the noise of the fast switching fizzler was horrible.

**Comment by Konclan** [comment]
UCP
