### ISSUE TITLE
Custom Signage Repository

### ISSUE THREAD

**Issue by Libbybapa** [BEEmod/BEE2-items#3075]
I have been working on making some custom signage items.  Some are my own design and some made by friends but turned into signage by me.  They might not need to be added to BEE packages but it might be good to have a repository where individuals can post up their custom signs for sharing.  Is there something like that already set up?  If so, then info on where that is located would be great.  If not, then maybe this thread could be left open and exist as such.  So far I have made up the following:
![angled](https://user-images.githubusercontent.com/33527465/61889014-8a100800-aeb9-11e9-8a29-b2c627d0ed65.png)
![cubeclimb](https://user-images.githubusercontent.com/33527465/61889015-8a100800-aeb9-11e9-9f01-a7cc01a28ac8.png)
![death](https://user-images.githubusercontent.com/33527465/61888403-4ec10980-aeb8-11e9-970f-b72075f48cc0.png)
![funnelblock](https://user-images.githubusercontent.com/33527465/61888404-4ec10980-aeb8-11e9-8090-7ed3dab3d6b0.png)
![norespawn](https://user-images.githubusercontent.com/33527465/61888405-4ec10980-aeb8-11e9-9108-872a78499e77.png)
![respawn](https://user-images.githubusercontent.com/33527465/61888406-4ec10980-aeb8-11e9-98be-163a480db264.png)
![sendificator2](https://user-images.githubusercontent.com/33527465/61888408-4ec10980-aeb8-11e9-87ce-6423cc9659ec.png)
![sendslim](https://user-images.githubusercontent.com/33527465/61888409-4f59a000-aeb8-11e9-8908-249b57e08e58.png)

The respawn/norespawn signs are higher resolution than previously.

The current package can be downloaded here:  https://drive.google.com/open?id=173STAvwdKgZuxuIAPjtlKIWgLObm0Gub

I will continue to add signs to that package.  I currently plan on including:
flip panel
track oscillate
track start/stop
piston platform
piston platform auto-drop
gel drip
gel bomb
cube through grating
button through grating
portalgun

If anyone else wants to contribute custom signs to this thread, they are welcome to.  Please include an image so others can see what they will be downloading.

**Comment by Endermage77** [comment]
About half of these are either unclear in what they are supposed to represent or unnecessarily specific.

I mean, what purpose would the Laser Redirection Cube at Cube on Button sign serve that wouldn't be either a) immediately obvious or b) intended to be part of the solution to be discovered?

**Comment by Libbybapa** [comment]
Your comment was enough to inspire me to delete the file hosting.

**Comment by TeamSpen210** [comment]
The last two are for Sendificators.

**Comment by Libbybapa** [comment]
The only other sign that seems at all unclear to me would be the grating blocking the funnel.  Coop grates and protruding grates block the funnel and that effect could be logically significant in a map and worth noting.  I can't imagine anyone being unable to understand the meaning and purpose behind the rest of the signs.  Regardless I opened the thread with the thought that people sharing custom signs might be a good thing.  It wasn't meant as a thread for critiquing what signs were worth having, sharing, or using.  I figured people would make up their own minds about what they wanted to use and might be appreciative of the effort that went into creating them.  I was wholly surprised to be wrong about that.

**Comment by Endermage77** [comment]
I'm a big proponent of espousing tutorial by visual design.

That is, setting up the level so that the player can automatically connect the dots for themselves about weird mechanics. For example, in the above example about coop grates blocking funnels, the level should open up with that interaction being one of the first things the player sees.

If a level is constructed properly, there few if any situations that need signs for such a very specific interaction.

**Comment by Libbybapa** [comment]
Your the guy at the free buffet complaining that there are Greek olives.  "WHY ARE THERE GREEK OLIVES AT THIS BUFFET!  I DON'T LIKE GREEK OLIVES!  A PROPERLY CONSTRUCTED BUFFET WOULD NOT HAVE GREEK OLIVES!"  Dude, you can just not eat the Greek olives and kindly shut up about it.  Maybe you can even appreciate the other things at the buffet or at least other people might enjoy the buffet more if you're not being a douche.  Post up a link to your workshop so I can play a few of your masterpieces and learn how maps are properly constructed...

**Comment by Libbybapa** [comment]
Is this you?  https://steamcommunity.com/profiles/76561198374875359/myworkshopfiles/

**Comment by Konclan** [comment]
While I understand your point Libby that if you don't like it don't use it. The signage can use some and a bunch of it is super confusing what it's trying to represent. That said I do really like some of the ideas here and I think they could work. First of all the angled panel and cube climbing signages I really like and think they are fine, I'd use these. The skull and crossbones are a little too generic and we have a load of signages that clearly indicate the danger the player should be avoiding. The grating blocking funnel is extremely specific and also doesn't really represent what you're trying to show. Maybe a funnel colliding with the grating but you kinda just have the grating floating near the funnel. Also, aren't there already sendificator signages? There is also issue #1093 that has a load of signage ideas that could be expanded upon.

Lastly Libby please stop being so aggressive to criticism. I find it a bit extreme to just close the whole issue because of 1 person's opinion. I think these look good, they just need to represent clearer what you're trying to tell the player.

**Comment by Libbybapa** [comment]
There is no specific sign indicating death.  The closest is either with a fizzler or with the player in goo, neither of which are applicable in quite a few situations.  The point to that sign is specifically to be generic. 
 
I agree that the grating blocking the funnel is extremely specific.  A friend made the design for a very specific situation in a map of his and asked me to make up the sign due to wanting to alert the player of the specific situation in his map.  He ended up not using that in the map.

Nope, as far as I know there are not any current sendificator signs.  Again, I made both of those per request for the same friend.  He did end up using the simpler version in his map.

In this thread I included each of the custom signs that I made up, not because I thought they were likely to be used, but rather because they were already made and MIGHT be beneficial to someone.  

There seems to be quite a bit of confusion about my initial purpose to starting this thread.  I was not looking to add signs to BEE.  I was not looking for ideas on signs to make or for pointers on how to improve the signs I have already made.  I started this thread solely as a potential location for individuals like myself who have made custom signage items to share them and for people who wanted to use those signs to be able to access them.  When it immediately veered off course from that purpose it was clear that it was pointless and closed it.  Your comment only confirms that assessment.

I am not 'aggressive to criticism'.  I actually really appreciate constructive input.  I'm aggressive to individuals being douchebags for no constructive purpose.  There's a huge difference.

**Comment by Konclan** [comment]
Alrighty, maybe in the future just post this to the BEEmod discord as opening an issue usually implies you would like it added to the application. Maybe we should open a channel just for custom signage packages.

**Comment by Libbybapa** [comment]
If you read my initial post, you will see that I was specifically asking if this was the appropriate location and if not, then I was asking for input where the appropriate location would be.

**Comment by Konclan** [comment]
Yeah my bad, I'm pretty bad when it comes to reading everything in an issue. I need to work on that, sorry.

**Comment by Libbybapa** [comment]
Discord might be workable but not as the current way the server is currently set up.  The specific shared instances would just get lost in the mindless chatter.
