### ISSUE TITLE
Place Autoportals on Piston Platforms

### ISSUE THREAD

**Issue by V0pT** [BEEmod/BEE2-items#3083]
Exactly what is says, I think that you should be able to place autoportals on Piston Platforms. It would be useful in puzzles where you don't what to have several autoportals littered around. 
Maybe the portal could fizzle out until the piston is done moving, then reopen.

One thing you could do is have a piston with an autoportal be one of the unused settings on the pistons, have one be blue and the other orange.

**Comment by JavierNovellon** [comment]
According to the Devs, this is already planned, and will be implemented at some point. Hold on I'll grab the link.

**Comment by TeamSpen210** [comment]
Indeed. Those two slots are intended for something else.

**Comment by Luke18033** [comment]
What are they intended for?

**Comment by TeamSpen210** [comment]
I was planning on using them for anti-gel surfaces, though I should actually just let you place the tile colour altering items on the bottom of the platform.
