### ISSUE TITLE
Some voice lines share the same IDs, causing them to toggle each other

### ISSUE THREAD

**Issue by JavierNovellon** [BEEmod/BEE2-items#3087]
I've had some problems in the past where some voice lines would be checked/unchecked if another, completely separate voice line was too.

The best example, which I've managed to fix, was the two bottom voices for GLaDOS (Clean) on Entry. These are the "Nobel Prize Winner" and the "Found A Subject" voices. If you uncheck either, the other one will be unchecked next time you open the dialog, and vice versa.

As I said before, I managed to fix this. Inside the "clean_style.zip" package, in the folder "voice" there's a configuration file, in which, the voice lines mentioned above have the same ID of "GENERIC_NOBEL_PRIZE". Changing the latter to "GENERIC_FOUND_SUBJECT" seemed to work for me. The Announcer also had some lines 'stuck' together but I cannot remember which, and I don't know if there's any other characters that have this same problem.

Overall, I think this originated from a copy-and-paste type of issue and simply no-one noticed. Can't blame anyone for it. Anyway thanks in advance.

**Comment by Luke18033** [comment]
I had a similar issue way back in BEEmod/BEE2.4#328. It might be a good idea to make the app produce a warning if there are multiple things like this with the same ID, to prevent stuff like this from happening in the future.

**Comment by JavierNovellon** [comment]
@Luke18033 
I think it would be a great idea, however, I think the warning shouldn't prevent you from using the app itself. I prefer to have some options or voice lines stuck together than not being able to use BEEmod until the following release.

**Comment by TeamSpen210** [comment]
In most other places duplicates do raise an error, I need to do that for these.

**Comment by JavierNovellon** [comment]
I see the issue was marked as "Fixed" almost a week ago. Well, I guess I'll close it until we need it again.

**Comment by Konclan** [comment]
The issue will close when the update with the fix is released

**Comment by JavierNovellon** [comment]
@Konclan Oh sorry for the inconvenience then. Didn't know that was required.
