### ISSUE TITLE
Retracted half panel models missing selection meshes

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3089]
![image](https://user-images.githubusercontent.com/19228201/63643321-ec0f8900-c682-11e9-9d01-b080221345c3.png)

**Comment by JavierNovellon** [comment]
Oh is this why it's so hard to move them?

**Comment by LautaroL20** [comment]
JavierNovellon - Yes, the selection meshes is what gives you the required precision at the time of grabbing the model in the puzzlemaker.
