### ISSUE TITLE
Static retracted half panels appear extended in-game

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3090]
In the editor, I've placed the panels like this, with no inputs.
![portal2_2019-08-24_15-21-45](https://user-images.githubusercontent.com/19228201/63643370-bc14b580-c683-11e9-9d7e-a3b4e4a7fc7c.png)
But in-game...
![image](https://user-images.githubusercontent.com/19228201/63643368-b3bc7a80-c683-11e9-9797-1a94d802a3e0.png)
I'd imagine this variant would be a 8u extended surface like normal angled panels, taking up half the block.

**Comment by TeamSpen210** [comment]
Yeah, a few times I've just ignored combinations like this when doing the logic, since an always retracted surface is pretty useless.
