### ISSUE TITLE
Missing Resources in Portal 1 Style

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#3094]
A few models such as the pellet catcher, Parts of the PEO, and the Autoportal are not packing properly.

![20190828004825_1](https://user-images.githubusercontent.com/16567080/63829074-15077680-c92e-11e9-8bf0-6314f608e0c4.jpg)
![20190828004832_1](https://user-images.githubusercontent.com/16567080/63829076-16d13a00-c92e-11e9-97bc-71a6719ba1af.jpg)
![20190828004847_1](https://user-images.githubusercontent.com/16567080/63829080-18026700-c92e-11e9-8c71-3e6647f2d05a.jpg)

**Comment by TeamSpen210** [comment]
That is *bizzare*.

**Comment by LautaroL20** [comment]
LOL. I wonder why the automatic model-packing system that was recently implemented, could have failed so hard as it is showin in those pictures...

**Comment by EterSky** [comment]
Same for vactubes. (In clean style but i guess it's the same for every other styles)

**Comment by TeamSpen210** [comment]
Version 4.36.0 fixed this bug.
