### ISSUE TITLE
3D BTS skybox leaks

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#3099]
Not sure exactly when or why but the ceiling of the skybox instances is too high causing it to leak
![Capture](https://user-images.githubusercontent.com/16567080/64074199-ef4fd980-cc6d-11e9-92be-ac0d3d5be819.PNG)

**Comment by Luke18033** [comment]
Wait, you mean the 3D skybox? The 2D one should just be using goo.

**Comment by Konclan** [comment]
That's another issue actually, pretty sure someone already reported the 2d skybox uses the 3d factory. But yeah, this issue is to due with the 3d skybox.

**Comment by Luke18033** [comment]
Now fixed, though 3D skybox support has been removed for now.
