### ISSUE TITLE
Multiverse Cave only plays in Clean and Original Clean

### ISSUE THREAD

**Issue by JavierNovellon** [BEEmod/BEE2-items#3101]
Out of curiosity, I tired selecting Multiverse Cave as my voice for an Old Aperture chamber. Uploaded the chamber as hidden, and I couldn't hear Multiverse Cave. Not after the elevator opened, nor after entering the chamber. I then tried it in the Overgrown Style, and same results. Again with Behind The Scenes, and Cave's nowhere to be heard.

I am assuming this was not intended. Maybe it can be fixed. If it cannot be fixed, then perhaps the 'Multiverse Cave' checkbox should be kept within the Clean and Original Clean styles, instead of in the generic options.

I would, however, much rather have Multiverse Cave be heard through all styles.

**Comment by Konclan** [comment]
Multiverse Cave depends on your situation. If you've heard all the voicelines then you will not hear Multiverse Cave.

**Comment by JavierNovellon** [comment]
@Konclan 
You're factually accurate, it's just, my Portal 2 doesn't agree with you.
https://youtu.be/QkC3LemYYBY

PS: Please excuse me using my first-ever test chamber... I rated it up because... Well I don't know why I did that.

**Comment by TeamSpen210** [comment]
That's actually why. The game remembers which chambers you originally played when listening to the lines, so if you replay those they'll repeat. If you want to reset the line history so they start at the beginning, use the console command `cm_reset_vo_progress`.
