### ISSUE TITLE
Set Overgrown "block stairs" to Portal 1-ish piston stairs.

### ISSUE THREAD

**Issue by jalapeno-github** [BEEmod/BEE2-items#3102]
In Overgrown style, the new, Portal 2 styled angled panels are used as stairs. I think this is great for stairs that move when activated, because it follows the moving panels style.

![20190904175226_1](https://user-images.githubusercontent.com/47536167/64276089-fb25ef00-cf3e-11e9-81b9-16113b527e37.jpg)

However, I think static stairs (that option of "Allow Block Stairs") should be styled like old, piston-powered stairs from Portal 1. These stairs can be seen in Portal 2, Chapter One, Test Chamber 07 (see screenshots). For a variant with missing tiles, I think the broken stairs seen in Portal Stories: MEL, Chapter Four, Test Chamber 03 (again, see screenshots) should be used.

![20190904175552_1](https://user-images.githubusercontent.com/47536167/64276116-0d079200-cf3f-11e9-8a34-750fa2934dba.jpg)
![20190904180237_1](https://user-images.githubusercontent.com/47536167/64276124-1133af80-cf3f-11e9-85b0-0ed2b99e6628.jpg)

I thought I'd find a slightly more broken set of stairs, but I didn't. These are the examples I have anyway.

Just thought it'd be a nice touch to have Portal 1 looking, non-functional stairs. Like they've been stuck there since the battle against GLaDOS.

**Comment by TeamSpen210** [comment]
That's a good idea, yes!
