### ISSUE TITLE
Just interest.

### ISSUE THREAD

**Issue by jotmo** [BEEmod/BEE2-items#3103]
When will the next update come out?
How many new things will you add in the next update?
P.S.The second question is optional. But if you answer I will be very grateful.

**Comment by Konclan** [comment]
As the [FAQ](https://github.com/BEEmod/BEE2-items/wiki/FAQ) says "Do not open an issue to ask a question." Go to the [Discord](https://discord.gg/hnGFJrz) to ask a question.
