### ISSUE TITLE
Signage not rendering in Editor 

### ISSUE THREAD

**Issue by MemeticRedditUser** [BEEmod/BEE2-items#3104]
Instead of the normal signage model, it shows the blue “ERROR” model. This happens with both the placeable connection signage and the normal signage

**Comment by Konclan** [comment]
What style, also what BEEmod version. This sounds like an old error.

**Comment by MemeticRedditUser** [comment]
Happens in clean, and in the latest version

**Comment by Konclan** [comment]
Try resetting package cache in the BEEmod app options and re-exporting. Also, make sure the preserve game directory option is unchecked.

**Comment by Luke18033** [comment]
Not sure what the issue is here.

**Comment by LautaroL20** [comment]
Most likely, the solution given by Konclan was the appropriate and the author did not care at confirming if that solve or not his issue, which is annoying.
