### ISSUE TITLE
Switch Old Aperture stairs to use Auto-Respawn to force a solid surface

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3109]
Overgrown uses a per-item Auto-Respawn property to make stairs solid, while Old Aperture uses an alternate variant. This is inconsistent, and the Old Aperture method has the disadvantage of only allowing one variant across the entire map, as opposed to only using the solid version when necessary. It should be changed to use Auto-Respawn, like in Overgrown.

**Comment by TeamSpen210** [comment]
No longer relevant.

**Comment by Luke18033** [comment]
Why not, are they solid by default now?

**Comment by TeamSpen210** [comment]
Yeah, I removed the grate version. I think that was originally to simulate catwalks.
