### ISSUE TITLE
replace centerted half wall and cross wall with 1/4 and 3/4 variants

### ISSUE THREAD

**Issue by mariovct** [BEEmod/BEE2-items#3113]
im suggesting to replace these 
![Capture wall](https://user-images.githubusercontent.com/31172185/64982073-30e9a280-d872-11e9-9256-dc9d2606117d.JPG)
with more variants of the half wall

**Comment by Luke18033** [comment]
These could be added pretty easily, they wouldn't replace the existing variants though. Maybe we could switch to using Cube Type for that item, to select between the existing three variants and these two new ones.

**Comment by JavierNovellon** [comment]
I guess you only need a 1/4 variant, since you could invert portalability to change the colour.

My only problem with the item (and not the suggestion) is that the middle item should be inverted. I'll make a separate issue for that.

**Comment by Konclan** [comment]
We've already discussed multiple times about additional wall variants. Most likely there's gonna be a tool that allows you to make your own wall type, I don't know if this has already been mentioned in an issue or not though.

**Comment by TeamSpen210** [comment]
It's not in an issue, mainly because I just directly implemented it. I basically need to go through and check every item in every style to see if they're broken.

**Comment by Luke18033** [comment]
Here's a better idea that will allow all of these combinations: An "invert tile" item, which inverts the surface color of a specific 32x32 tile. It would have an 8-way handle to position it within the block, and use the Angle property to set which tile would be replaced.

**Comment by TeamSpen210** [comment]
Indeed, that's what I made.

**Comment by Luke18033** [comment]
As an item, or just the compiler functionality?

**Comment by TeamSpen210** [comment]
![image](https://user-images.githubusercontent.com/8453732/65012800-08d66e00-d95c-11e9-8ff1-a0c14753a83c.png)
As an item.

**Comment by Libbybapa** [comment]
Is this implemented in the current release?

**Comment by Luke18033** [comment]
No
