### ISSUE TITLE
standing partial blocks

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#3115]
I personally think that adding standing partial block's would be a good addition to BEE2. and would allow to make geometry such as this without the use of hammer.
![4555555555555](https://user-images.githubusercontent.com/31172185/65379371-ad69f000-dc7b-11e9-8742-5d19d86be81d.JPG)

**Comment by Luke18033** [comment]
This is already possible with the 1/4 wall, and would also be included in #1958.
