### ISSUE TITLE
Portal 1 covered panel top model has a floating gray strip near the bottom

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3119]
This is only visible when the panels are open.
![image](https://user-images.githubusercontent.com/19228201/65559241-c0d0c180-deee-11e9-9644-c196d08df8ff.png)
And here's a screenshot from HLMV:
![image](https://user-images.githubusercontent.com/19228201/65559337-2e7ced80-deef-11e9-83a7-fafcf8874269.png)
According to the mode dropdown this is "bad vertex data" (it appears red on this mode, while everything else is black). I'm not sure what that means, but it sounds like an error in the SMD or something.

**Comment by Luke18033** [comment]
@TeamSpen210 Have you figured out what this is yet?

**Comment by TeamSpen210** [comment]
An extra bit of the model or something. I recompiled the model, seems fixed once I push that.
