### ISSUE TITLE
Portalable fizzler

### ISSUE THREAD

**Issue by MemeticRedditUser** [BEEmod/BEE2-items#3120]
It’s basically the closed solid field, but you can place portals on it. The opposite side of the portal would render as a closed portal of that color

**Comment by MemeticRedditUser** [comment]
![7CB4615E-810E-4327-8906-EA5AA03E536E](https://user-images.githubusercontent.com/40185397/65637321-fa1e3580-dfb1-11e9-8a29-3eb17457cfea.jpeg)
![1A52FE0A-8D75-4474-A442-0C4A0D28E0E0](https://user-images.githubusercontent.com/40185397/65637322-fa1e3580-dfb1-11e9-9e9c-093fcc08c814.jpeg)

**Comment by TeamSpen210** [comment]
We have enough fizzler variants, I think.

**Comment by Konclan** [comment]
This was also already suggested but whatever the name of the issue is I absolutely can't find it
