### ISSUE TITLE
Custom Fizzler Editor Model Tweak

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#3121]
I'm not sure if this has been suggested somewhere already, however, I think custom fizzlers need more of an indicator they are custom in the editor model. Sometimes it's hard to spot the small colored strip. There are many ways to fix this such as a little bit of the colored field sticking out like how pellet detector fields look but maybe smaller to avoid rendering issues.

**Comment by Luke18033** [comment]
I was going to suggest this the other day, this is definitely needed. Some of the custom fizzlers also reuse existing models, which definitely doesn't help.

**Comment by Konclan** [comment]
![Capture](https://user-images.githubusercontent.com/16567080/65639618-14eeab00-dfae-11e9-8ba0-7144bfe5514d.PNG)
Here is a small concept, either this or something else or both would help

**Comment by TeamSpen210** [comment]
That is a good idea indeed. Note that the models are all intentionally using the same SMD and a tinted material, so it should be easy to apply that to all of them. Actually what we should so is take those icons of yours and add them to the model as well so you can see what the fizzler does.

**Comment by Luke18033** [comment]
Not sure why this wasn't closed automatically
