### ISSUE TITLE
Conductive Plate inputs cause a compile error

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3122]
Tested in Old Aperture, but this appears to be an issue in all styles based on the fact that this is a Clean instance.
```
Could not open instance file instances/bee2/clean/items/cond_plate/plate_input.vmf
```

**Comment by TeamSpen210** [comment]
Actually it's from updating the Clean version but not the Old Ap and P1 versions.

**Comment by Luke18033** [comment]
Ah, thought it might be that
