### ISSUE TITLE
Use Portal: Still Alive skull button/cube in Portal 1 style

### ISSUE THREAD

**Issue by GalexTEMYT** [BEEmod/BEE2-items#3125]

**Comment by Luke18033** [comment]
I don't think these will be added, for several reasons:
- The reason these originally existed in Still Alive was to explain the behavior of cube respawn buttons, since they were never used in P1's campaign. Portal 2 does use this mechanic, so adding an explanation like this in custom maps is kind of unnecessary.
- They only come in P1 variants, so we'd need to remake the skin for the P2 button/cube models.
- How would this work with other cube types? That would mean each cube would need to have 4 variants, for coloriser+skull.

**Comment by GalexTEMYT** [comment]
what if the skull cube was a hidden coloriser variant and could only be used in the p1 style instead of being fully implemented, perhaps like an easter egg, but if you think other wise just reply.

**Comment by GalexTEMYT** [comment]
I do not find this invalid

**Comment by Luke18033** [comment]
Well you're the one who opened it, so of course you don't. I guess this could maybe be added as a P1-specific variant of the pedestal button used when connected to a cube dropper. The cube skin probably wouldn't be used, or would only appear on standard cubes.

**Comment by GalexTEMYT** [comment]
thank you, and in all honesty there is probably a work around for the skull cube, of course you probabably will have to talk about it with the team whom devolops the items and, and not saying that you arnt apart of it, its just that how bout instead of the button the cube it self can be added kinda like the bomb cube but not fully implemented, what im saying is maybe trying to add it as a onther color for p1 style of cube coloriser, that way only the red lines and red skull have to be added.

**Comment by GalexTEMYT** [comment]
and i do agree with you it would be compleatly redundent to add the skull button becuase yeah in portal auto respawn cube is a thing, but anyways, like i said about that work a round bcuase ik its not garenteed to work but just adding a single color to the coloriser well wouldnt really be the hard part however the hard part be adding the skull cube, but then again seeing that in the coloriser the color red is already added then a p1 style of it wouldnt probably be too dificult and i do get it things like this do take time and are not easy.

**Comment by Luke18033** [comment]
The skull cube/button would be used automatically, for standard cube droppers connected to pedestal buttons. It wouldn't actually conflict with a custom color, P1 colorizers affect the ring around the center of the cube, rather than the lights like the skull cube does.

**Comment by GalexTEMYT** [comment]
oh, well if it works.

**Comment by TeamSpen210** [comment]
I don't really think these are good to use.
