### ISSUE TITLE
Added a music page to the wiki

### ISSUE THREAD

**Issue by underlineGalaxy** [BEEmod/BEE2-items#3130]
https://github.com/BEEmod/BEE2-items/wiki/Music

Actually planned to use this for hacktober, but you can't pull request wiki pages (grrrr).

Anyway, it was on the to-do but now it exists. I actually don't know how to put it on the main wiki so I've decided to open a issue here.

**Comment by Luke18033** [comment]
Thanks! I've updated the page a bit to fix a few errors. What do you mean by "put on the main wiki"? It's already there.

**Comment by Konclan** [comment]
Maybe there's no direct link to the music wiki page?
![Capture](https://user-images.githubusercontent.com/16567080/66710153-777ad180-ed38-11e9-8ca7-ff03ed8136bf.PNG)

**Comment by underlineGalaxy** [comment]
> 
> 
> Maybe there's no direct link to the music wiki page?
> ![Capture](https://user-images.githubusercontent.com/16567080/66710153-777ad180-ed38-11e9-8ca7-ff03ed8136bf.PNG)

Yes that

**Comment by Luke18033** [comment]
Now done.
