### ISSUE TITLE
Beemod Error N13 Permission denied

### ISSUE THREAD

**Issue by eeeee48** [BEEmod/BEE2-items#3131]
![image](https://user-images.githubusercontent.com/32681975/66726954-83e85280-ee3c-11e9-99fa-9ca8820e52f4.png)

Every time I try to export my chosen palette, I'm given this error. I've tried updating my Beemod but it doesn't help. This error happens no matter what items I choose.

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to the Bee´s interface behavior, must be posted on the interface´s page, here: https://github.com/BEEmod/BEE2.4/issues

This section is for post things related to the items, only.
