### ISSUE TITLE
Port original P1 floor/ceiling textures

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3133]
In Portal 2, the Portal 1 white floor textures look like this:
![portal2_2019-10-16_18-38-37](https://user-images.githubusercontent.com/19228201/66971025-7d2c2c00-f044-11e9-8119-b52533e2a1f7.png)
This, the special floor, and ceilings are different than in the original game; the original floor texture (which I've applied in place of the P2 version) looks like this:
![portal2_2019-10-16_18-40-13](https://user-images.githubusercontent.com/19228201/66971018-700f3d00-f044-11e9-92ff-8cb5dc3ceefc.png)
While the new texture does appear to be higher quality, said increased quality is not present in any other P1 textures, making these ones seem inconsistent and out of place. Since many other P1 assets have already been ported for use in the BEE2, including things with only minor differences such as the portal gun, I don't see why these textures shouldn't be ported as well.

**Comment by ZombiePwner1** [comment]
Wow I'm surprised as to how I didn't notice this.

**Comment by Luke18033** [comment]
The editor textures are probably also based on the P2 versions, and would need to be changed as well.

**Comment by TeamSpen210** [comment]
Most are copy-pastes of those, which probably should be fixed.

**Comment by Luke18033** [comment]
Is there any sort of special configuration that needs to be done for the packing or will it happen automatically?

**Comment by TeamSpen210** [comment]
Should be automatic.
