### ISSUE TITLE
chambers no longer load

### ISSUE THREAD

**Issue by Invad3rBron7** [BEEmod/BEE2-items#3138]
Chambers no longer load anymore. Everything worked fine before using this, and I even used the first BeeEditor. I can design them but I cannot test play or upload them for some reason.

**Comment by LautaroL20** [comment]
It is that the loading process of the map get stuck forever in a certaing point?

**Comment by Luke18033** [comment]
I think it's a compile error. Post the console log, that generic error message is useless on its own.

**Comment by Invad3rBron7** [comment]
It starts to load the map but then cuts to the error saying map cannot be
loaded.

**Comment by Invad3rBron7** [comment]
That's what I thought and I tried verifying the integrity of game files but
it still wouldn't work. And I'm not sure how to get to those commands.

**Comment by Invad3rBron7** [comment]
oh i gotcha. This is what i got.

NET_GetBindAddresses found 192.168.1.125: 'Intel(R) Dual Band Wireless-AC
3168'
NET_GetBindAddresses found 192.168.137.1: 'Microsoft Wi-Fi Direct Virtual
Adapter #2'
Opened Steam Socket NS_SERVER ( socket 2800 )
Opened Steam Socket NS_CLIENT ( socket 2588 )
Network: IP 192.168.137.1, mode MP, dedicated No, ports 27015 SV / 27005 CL
Parent cvar in client.dll not allowed (movement_anim_playback_minrate)
Game supporting (2) split screen players
maxplayers set to 1
Steam config directory: C:\Program Files
(x86)\Steam\steamapps\common\Portal 2\portal2.exe\platform\config
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in
scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in
scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in
scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in
scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/change_this
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in
scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in
scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in
scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in
scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/gesture_smallwave
Unknown command "cl_thirdperson"
Unknown command "joy_no_accel_scale"
Using joystick 'Xbox360 controller' configuration
Advanced joystick settings initialized for joystick 1
------------
joy1 x axis:  strafe (absolute)
joy1 y axis:  forward (absolute)
joy1 z axis:  unmapped
joy1 r axis:  pitch (absolute)
joy1 u axis:  yaw (absolute)
joy1 v axis:  unmapped
Advanced joystick settings initialized for joystick 2
------------
joy2 x axis:  strafe (absolute)
joy2 y axis:  forward (absolute)
joy2 z axis:  unmapped
joy2 r axis:  pitch (absolute)
joy2 u axis:  yaw (absolute)
joy2 v axis:  unmapped
Didn't find Active Steam Controller to Load Menu Controls
Unknown command "cl_thirdperson"
C_GameInstructor::ReadSaveData failed to read
GI.lesson.Swap_Split_Screen_Control
[PORTAL2 PUZZLEMAKER]  Loaded puzzle
puzzles\76561198170376286\1573251792.p2c
Unknown command "cl_puzzlemaker_activate"
CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.137.1, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 2800 )
Opened Steam Socket NS_CLIENT ( socket 2804 )
Network: IP 192.168.137.1, mode MP, dedicated No, ports 27015 SV / 27005 CL
Failed, using default cubemap 'engine/defaultcubemap'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\76561198170376286\1573251792
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which
point_template @player_start_template is specifying.
prop_portal_linked_door '@upgrade_room_exit' failed to link to partner
named: ''
Commentary: Could not find commentary data file
'maps/puzzlemaker\76561198170376286\1573251792_commentary.txt'.
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Connection to Steam servers successful.
   VAC secure mode is activated.
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in
file materials/models/props_map_editor/door_frame.vmt
patch, (*insert*),
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist
models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh:
models/puzzlemaker/selection_bee2_fizz_error.3ds
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in
file materials/models/props_map_editor/crusher_back.vmt
patch, (*insert*),
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist
models/puzzlemaker/selection_tspen_checkpoint.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh:
models/puzzlemaker/selection_tspen_checkpoint.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files
(x86)/Steam/steamapps/common/Portal
2/portal2/puzzles\76561198170376286\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files
(x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size:
(7,8,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 23 (ms)

VBSP failed.

[I] vbsp.main(): BEE2.35.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files
(x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files
(x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'bottomless_pit': '0',
'use_screenshot': '1', 'glass_scale': '0.15', 'voice_pack':
'BEE2_ANNOUNCER_APOC'}
[W] instanceLocs.get_subitems(): Invalid custom instance name -
"piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head':
'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common':
'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0':
'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1':
'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2':
'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3':
'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0':
'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf',
'piston_static_1':
'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf',
'piston_static_2':
'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf',
'piston_static_3':
'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf',
'piston_static_4':
'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf',
'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf',
'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf',
'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf',
'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[W] instanceLocs.get_subitems(): Invalid custom instance name -
"piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head':
'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common':
'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0':
'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1':
'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2':
'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3':
'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0':
'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf',
'piston_static_1':
'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf',
'piston_static_2':
'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf',
'piston_static_3':
'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf',
'piston_static_4':
'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf',
'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf',
'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf',
'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf',
'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[I] cubes.parse_conf(): Parsed 0 cube types, 0 dropper types and 0 addons.
[W] cubes.parse_conf(): Valve Cube type "VALVE_CUBE_STANDARD" is missing!
[W] cubes.parse_conf(): Valve Cube type "VALVE_CUBE_COMPANION" is missing!
[W] cubes.parse_conf(): Valve Cube type "VALVE_CUBE_REFLECTION" is missing!
[W] cubes.parse_conf(): Valve Cube type "VALVE_CUBE_SPHERE" is missing!
[W] cubes.parse_conf(): Valve Cube type "VALVE_CUBE_FRANKEN" is missing!
[I] fizzler.read_configs(): Loaded 0 fizzlers.
[W] cond.sendtor.load_signs(): No ARROW signage type!
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (14 starting
positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[W] template.retexture_template(): Realign face in template
"bee_door_cowl_clean" (1426 in final) is not on grid!
[W] template.retexture_template(): Realign face in template
"bee_door_cowl_clean" (1464 in final) is not on grid!
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator
(BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] template.retexture_template(): Realign face in template
"bee2_static_stairs_clean_extended" (731 in final) is not on grid!
[W] template.get_scaling_template(): Template
"BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not
really one!
[W] template.retexture_template(): Realign face in template
"bee2_static_stairs_clean_extended" (90 in final) is not on grid!
[W] template.get_scaling_template(): Template
"BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not
really one!
[W] template.retexture_template(): Realign face in template
"bee2_static_stairs_clean_extended" (196 in final) is not on grid!
[W] template.get_scaling_template(): Template
"BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not
really one!
[I] vbsp.set_elev_videos(): Elevator type: RAND
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2/voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2/mid_voice.cfg" not found! Using
defaults...
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.find_group_quotes(): "ENTRY": 3/6 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line_SP"
 | {
 | "ID" "TURR_ENTRY_SP"
 | "Choreo" "npc/announcer/testchamber05.vcd"
 | }
 |
 |___

[I] voiceLine.find_group_quotes(): "EXIT": 2/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line_SP"
 | {
 | "ID" "EXIT_ANIMAL_KING"
 | "File" "ann_apoc/exit_turret_coop.vmf"
 | }
 |
 |___

[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 1/4 quotes..
[I] voiceLine.add_voice(): 1 Mid quotes
[I] voiceLine.add_quote(): Adding quote: "Line"
 | {
 | "Name" "Avoid Being Shot"
 | "Target" "@voice_turret_activate"
 | "Choreo" "npc/announcer/sabotage_factory17.vcd"
 | }
 |
 |___

[I] voiceLine.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['rocketturret', 'turret',
'deadly', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=4051,
misses=325, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'blockplayergelbomb': True,
'doorcameras': True, 'restartonexit': True, 'multiversecave': True,
'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False,
'allowgoomist': True, 'funnelallowswitchedlights': True,
'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances:
{'instances/bee2/clean/items/rocket_turret/logic.vmf',
'instances/BEE2/logic/goo_fade.vmf', 'instances/BEE2/clean/global_ents.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: True
[I] vbsp.change_brush(): Goo heights: 0 <- Counter()
[I] vbsp.change_brush(): Creating Bottomless Pits...
[I] bottomlessPit.make_bottomless_pit(): Pit instances: {<CONN_TYPES.side:
1>: ['instances/BEE2/bts/sky/side_1.vmf',
'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf',
'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'],
<CONN_TYPES.corner: 3>: ['instances/BEE2/bts/sky/corner_1.vmf',
'instances/BEE2/bts/sky/corner_1.vmf',
'instances/BEE2/bts/sky/corner_2.vmf',
'instances/BEE2/bts/sky/corner_3.vmf'], <CONN_TYPES.straight: 2>:
['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf',
'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf',
'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.triple: 4>:
['instances/BEE2/bts/sky/triple_1.vmf',
'instances/BEE2/bts/sky/triple_2.vmf'], <CONN_TYPES.all: 5>:
['instances/BEE2/bts/sky/pillar_1.vmf',
'instances/BEE2/bts/sky/pillar_2.vmf',
'instances/BEE2/bts/sky/pillar_2.vmf',
'instances/BEE2/bts/sky/pillar_3.vmf',
'instances/BEE2/bts/sky/pillar_3.vmf']}
[I] vbsp.change_brush(): Done!
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\compiler_launch.py", line 13, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3188, in main
  File "F:\Git\BEE2.4\src\barriers.py", line 153, in make_barriers
  File "F:\Git\BEE2.4\src\template_brush.py", line 574, in
get_scaling_template
template_brush.InvalidTemplateName: Template not found:
"bee2_glass_template"
Valid templates:
 * "__TILING_TEMPLATE__"
 * "BEE2_ANGLED_BLOCK_30"
 * "BEE2_ANGLED_BLOCK_45"
 * "BEE2_ANGLED_BLOCK_60"
 * "BEE2_ANGLED_BLOCK_CORNER_30"
 * "BEE2_ANGLED_BLOCK_CORNER_45"
 * "BEE2_ANGLED_BLOCK_CORNER_60"
 * "BEE2_BALL_BUTTON_BASE_BTS"
 * "BEE2_BALL_BUTTON_BASE_P1_WHITE"
 * "BEE2_BLOCK_128_32_32"
 * "BEE2_BLOCK_128_64_64"
 * "BEE2_BLOCK_64_64_64"
 * "BEE2_BLOCK_WINDOW_FULL"
 * "BEE2_BLOCK_WINDOW_LOW"
 * "BEE2_BLOCK_WINDOW_MID"
 * "BEE2_BTS_GRATING_TEMPLATE"
 * "BEE2_CONVEYOR_COVER_BOTTOM_CLEAN"
 * "BEE2_CONVEYOR_COVER_BOTTOM_OVER"
 * "BEE2_CONVEYOR_COVER_BOTTOM_PORTAL_1"
 * "BEE2_CONVEYOR_COVER_RETRO"
 * "BEE2_CONVEYOR_COVER_TOP_CLEAN"
 * "BEE2_CONVEYOR_COVER_TOP_OVER"
 * "BEE2_CONVEYOR_COVER_TOP_PORTAL_1"
 * "BEE2_CONVEYOR_RAIL_RETRO"
 * "BEE2_CONVEYOR_TUNNEL_TILE_CLEAN"
 * "BEE2_CUBE_BUTTON_BASE_BTS"
 * "BEE2_CUBE_DROPPER_CLEAN_CAP"
 * "BEE2_CUTOUT_TILE_FLOOR_PILLAR"
 * "BEE2_CUTOUT_TILE_FLOOR_SIDE_DETAIL"
 * "BEE2_CUTOUT_TILE_FLOOR_SIDE_WORLD"
 * "BEE2_DYNAMIC_PAN_ANGLED_P1"
 * "BEE2_EMBEDDED_VOXEL"
 * "BEE2_FLAT_HALF"
 * "BEE2_FLAT_QUARTER"
 * "BEE2_FLAT_THREE_QUARTER"
 * "BEE2_FLOOR_BUTTON_BASE_BTS"
 * "BEE2_FLOOR_BUTTON_BASE_CLEAN_BALL"
 * "BEE2_FLOOR_BUTTON_BASE_CLEAN_CUBE"
 * "BEE2_FLOOR_BUTTON_BASE_CLEAN_WEIGHTED"
 * "BEE2_FLOOR_BUTTON_BASE_P1_WHITE"
 * "BEE2_FUTBOL_SURF_BACK"
 * "BEE2_FUTBOL_SURF_BACK_50S"
 * "BEE2_FUTBOL_SURF_BACK_P1"
 * "BEE2_GLASS_DOOR_CLEAN"
 * "BEE2_GLASS_DOOR_RETRO"
 * "BEE2_HALF_PANEL_TOP_50S"
 * "BEE2_HALF_PANEL_TOP_80S"
 * "BEE2_HALF_PANEL_TOP_CLEAN"
 * "BEE2_HALF_PANEL_TOP_P1"
 * "BEE2_HMW_SENDTOR_BASE_SLAB"
 * "BEE2_HMW_SENDTOR_BASE_SLAB_OVER"
 * "BEE2_HMW_SENDTOR_TOP_SLAB_P1"
 * "BEE2_MONITOR_COVER_CLEAN"
 * "BEE2_MONITOR_COVER_P1"
 * "BEE2_NEUROTOXIN_TIMER_COVER_CLEAN"
 * "BEE2_NEUROTOXIN_TIMER_COVER_OVER_LEFT"
 * "BEE2_NEUROTOXIN_TIMER_COVER_OVER_RIGHT"
 * "BEE2_NEUROTOXIN_TIMER_COVER_P1"
 * "BEE2_NEUROTOXIN_VENT_50S"
 * "BEE2_NEUROTOXIN_VENT_CLEAN"
 * "BEE2_NEUROTOXIN_VENT_P1"
 * "BEE2_OVER_BALL_BUTTON_BASE"
 * "BEE2_OVER_CUBE_BUTTON_BASE"
 * "BEE2_OVER_FLOOR_BUTTON_BASE"
 * "BEE2_OVER_PED_BASE"
 * "BEE2_OVER_STAIRS_TOP_1"
 * "BEE2_OVER_STAIRS_TOP_2"
 * "BEE2_OVER_STAIRS_TOP_3"
 * "BEE2_OVER_STAIRS_TOP_4"
 * "BEE2_P1_DRAWBRIDGE_DOWN"
 * "BEE2_P1_DRAWBRIDGE_UP"
 * "BEE2_P1_GLASS_BEAM"
 * "BEE2_P1_GLASS_TEMPLATE"
 * "BEE2_P1_GRATING_TEMPLATE"
 * "BEE2_RETRO_MECH_PLATE_ANGLED"
 * "BEE2_RETRO_MECH_PLATE_STRAIGHT"
 * "BEE2_ROCKET_TURRET_CAP_CLEAN"
 * "BEE2_SIGNAGE_50S_ARROW"
 * "BEE2_SIGNAGE_50S_ARROW_REV"
 * "BEE2_SIGNAGE_50S_EXIT"
 * "BEE2_SIGNAGE_50S_EXIT_REV"
 * "BEE2_SIGNAGE_50S_EXIT_WALL"
 * "BEE2_SIGNAGE_50S_NUM"
 * "BEE2_SIGNAGE_50S_NUM_REV"
 * "BEE2_SIGNAGE_50S_NUM_WALL"
 * "BEE2_SIGNAGE_50S_SIGN"
 * "BEE2_SIGNAGE_50S_SIGN_REV"
 * "BEE2_SIGNAGE_50S_SIGN_WALL"
 * "BEE2_SIGNAGE_70S_ARROW"
 * "BEE2_SIGNAGE_70S_ARROW_REV"
 * "BEE2_SIGNAGE_70S_ARROW_WALL_REV"
 * "BEE2_SIGNAGE_70S_SIGN2_FLOOR"
 * "BEE2_SIGNAGE_70S_SIGN2_FLOOR_REV"
 * "BEE2_SIGNAGE_70S_SIGN_FLOOR"
 * "BEE2_SIGNAGE_70S_SIGN_REV"
 * "BEE2_SIGNAGE_70S_SIGN_WALL"
 * "BEE2_SIGNAGE_BTS_ARROW"
 * "BEE2_SIGNAGE_BTS_ARROW_REV"
 * "BEE2_SIGNAGE_BTS_LONG"
 * "BEE2_SIGNAGE_BTS_LONG_REV"
 * "BEE2_SIGNAGE_BTS_NUM"
 * "BEE2_SIGNAGE_BTS_NUM_REV"
 * "BEE2_SIGNAGE_BTS_RECT"
 * "BEE2_SIGNAGE_BTS_RECT_REV"
 * "BEE2_SIGNAGE_CLEAN_ARROW"
 * "BEE2_SIGNAGE_CLEAN_ARROW_REV"
 * "BEE2_SIGNAGE_CLEAN_ARROW_WALL_REV"
 * "BEE2_SIGNAGE_CLEAN_SIGN2_FLOOR"
 * "BEE2_SIGNAGE_CLEAN_SIGN2_FLOOR_REV"
 * "BEE2_SIGNAGE_CLEAN_SIGN_FLOOR"
 * "BEE2_SIGNAGE_CLEAN_SIGN_REV"
 * "BEE2_SIGNAGE_CLEAN_SIGN_WALL"
 * "BEE2_STAIRS_TOP"
 * "BEE2_STATIC_PAN_ANGLED"
 * "BEE2_STATIC_PAN_ANGLED_BLACK_50S"
 * "BEE2_STATIC_PAN_ANGLED_BLACK_70S"
 * "BEE2_STATIC_PAN_ANGLED_BLACK_80S"
 * "BEE2_STATIC_PAN_ANGLED_BTS"
 * "BEE2_STATIC_PAN_ANGLED_P1"
 * "BEE2_STATIC_PAN_ANGLED_WHITE_50S"
 * "BEE2_STATIC_PAN_ANGLED_WHITE_80S"
 * "BEE2_STATIC_PAN_FLAT"
 * "BEE2_STATIC_PAN_FLAT_P1"
 * "BEE2_STATIC_PAN_FLAT_RETRO"
 * "BEE2_STATIC_STAIRS_CLEAN_EXTENDED"
 * "BEE2_STATIC_STAIRS_CLEAN_RETRACTED"
 * "BEE2_STATIC_STAIRS_STATIC_BEAMS_OVER"
 * "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP"
 * "BEE2_TBEAM_FRAME"
 * "BEE2_TRACK_PLAT_BOTTOM"
 * "BEE2_TRACK_PLAT_MIDDLE"
 * "BEE2_TRACK_PLAT_SINGLE"
 * "BEE2_TRACK_PLAT_TOP"
 * "BEE2_TURRET_DROPPER_50S_CAP"
 * "BEE2_TURRET_DROPPER_P1_CAP"
 * "BEE2_VACTUBE_CORNER_CLEAN_LARGE"
 * "BEE2_VACTUBE_CORNER_CLEAN_MEDIUM"
 * "BEE2_VACTUBE_CORNER_CLEAN_SMALL"
 * "BEE2_VACTUBE_CORNER_RETRO_MEDIUM"
 * "BEE2_WALL_HALF"
 * "BEE2_WALL_HALF_CENTER"
 * "BEE2_WALL_PLUS"
 * "BEE_DOOR_COWL_CLEAN"
 * "BEE_DRAW_BRIDGE_CLEAN"
 * "BEE_DRAW_BRIDGE_OVER"
 * "BEE_HEP_CATCHER_BASE_CLEAN"
 * "BEE_HEP_CATCHER_BASE_P1_EXTENDED"
 * "BEE_HEP_CATCHER_BASE_P1_FLAT"
 * "BEE_HEP_CATCHER_BASE_P1_PISTON"
 * "BEE_HEP_EMITTER_BASE_CLEAN"
 * "BEE_HEP_EMITTER_BASE_P1"
 * "BEE_HEP_EMITTER_BASE_P1_SIGN"
 * "BEE_PGUN_BASE"
 * "BEE_VENT_BASE_50S"
 * "BEE_VENT_BASE_CLEAN"
 * "LAUTARO_PROTRUDING_PED_BASE_80S"
 * "LAUTARO_PROTRUDING_PED_BASE_BTS_BLACK"
 * "LAUTARO_PROTRUDING_PED_BASE_BTS_BLACK_REV"
 * "LAUTARO_PROTRUDING_PED_BASE_BTS_WHITE"
 * "LAUTARO_PROTRUDING_PED_BASE_BTS_WHITE_REV"
 * "LAUTARO_PROTRUDING_PED_BASE_CLEAN"
 * "LAUTARO_PROTRUDING_PED_BASE_OVER"
 * "LAUTARO_PROTRUDING_PED_BASE_P1"
 * "LAUTARO_PROTRUDING_PED_BASE_RETRO"
 * "REX_CUBE_DEFLECTOR_TEMP_CLEAN"
 * "REX_CUBE_DEFLECTOR_TEMP_P1"
 * "REX_CUBE_DEFLECTOR_TEMP_RETRO_METAL"
 * "REX_CUBE_DEFLECTOR_TEMP_RETRO_WOOD"
 * "REX_PELLET_FIELD_TEMP"
 * "REX_PELLET_FIELD_TEMP_RETRO"
 * "TSPEN_BTN_PED_CLEAN_BASE"
 * "TSPEN_BTN_PED_P1_BASE"
 * "TSPEN_CHAMBERLOCK_CLEAN"
 * "TSPEN_CHAMBERLOCK_P1"
 * "TSPEN_LARGE_FAITH_RETRO_BORDER"
 * "TSPEN_LARGE_FAITH_RETRO_MECH_BACK"
 * "TSPEN_LARGE_FAITH_TRIG"
 * "TSPEN_LARGE_FAITH_TRIG_SQUARE"
 * "WOM_CONDUCTOR_50S_BLACK"
 * "WOM_CONDUCTOR_50S_WHITE"
 * "WOM_CONDUCTOR_CLEAN"
 * "WOM_CONDUCTOR_P1"
[26276] Failed to execute script compiler_launch

**Comment by Luke18033** [comment]
There's a template missing, not sure why that would happen. Does this effect every map, including the default chamber?

**Comment by Invad3rBron7** [comment]
Yea, it effects every map, even the default one. I've tried reinstalling as
well but it still doesn't work.

**Comment by Luke18033** [comment]
Okay, so there's an actual problem with your files. Try [this](https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod), see if it helps.

**Comment by LautaroL20** [comment]
You can also try resetting the package cache:
![Beemod options](https://user-images.githubusercontent.com/12244376/68562202-656b7c00-0427-11ea-83dc-b975e72b6f60.png)

**Comment by LautaroL20** [comment]
@Invad3rBron7 - Do not forget to confirm if the solution given has worked or not.

**Comment by Invad3rBron7** [comment]
I tried both of those solutions but neither worked for me. And I apologize
I just got home from work so I couldn’t try sooner.

**Comment by ZombiePwner1** [comment]
@Invad3rBron7 Have you tried Verifying the game files and then re-installing Beemod?

**Comment by Invad3rBron7** [comment]
Yeah that was one of the first things I tried.

**Comment by TeamSpen210** [comment]
Which style are you using? Try a different one.

**Comment by Luke18033** [comment]
Closing due to lack of response

**Comment by Invad3rBron7** [comment]
Sorry i didn't get a chance to reply. i was using the clean layout but
trying another layout had the same problem.
