### ISSUE TITLE
Dropper for Bomb Cubes

### ISSUE THREAD

**Issue by PieCreeper12** [BEEmod/BEE2-items#3141]
There is no option to add a dropper for bomb cubes. This means that once a bomb cube explodes, the player cannot receive another one. This may force them to restart the test chamber if they do not use it correctly. My suggestion is to add an option to add a dropper for bomb cubes so that they can be obtained again after one explodes.

**Comment by TeamSpen210** [comment]
All the custom cube types do have a dropper, I need to find a good spot to document it though. Just place it underneath the default cube dropper item and it'll override what's dispensed from that.

**Comment by SCIENTIST2004** [comment]
And for bumpleball too...
