### ISSUE TITLE
Compressed Smoke Field editor preview is not translucent (Its .SMD file is missing the association with the file fr_csf_field)

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3147]
Its .SMD file is missing the association with the file: `fr_csf_field`

![Compressed Smoke Field](https://user-images.githubusercontent.com/12244376/69404454-13a2db80-0cdc-11ea-9345-208cd9b7b063.jpg)

**Comment by ZombiePwner1** [comment]
LOL.

**Comment by LautaroL20** [comment]
I tested this to see whats going on, i decompiling to observe to its .smd and it is missing the association with the file: `fr_csf_field`

**Comment by Luke18033** [comment]
You don't need to decompile, the original source files are on [resource-src](https://github.com/beemod/resource-src).
