### ISSUE TITLE
Question. With new version 4.36.0

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#3149]
What packages should I download if there are none available?
![Безымянный](https://user-images.githubusercontent.com/35931028/69446275-b56a0d00-0d5c-11ea-861f-ec397f7f1c1d.png)

**Comment by Flash4433** [comment]
I also noticed he forgot to link the new packages. Here.

https://github.com/BEEmod/BEE2-items/releases/tag/v4.36.0

**Comment by SCIENTIST2004** [comment]
Thanks

**Comment by LautaroL20** [comment]
I´ve added the missing link in the release´s description, now it is there: https://github.com/BEEmod/BEE2.4/releases
