### ISSUE TITLE
Cold Light Strip

### ISSUE THREAD

**Issue by Enterpise** [BEEmod/BEE2-items#315]
There is one left "variation" to implement from light strips on Bee2.4, wich was always absent
since the creation of beemod 1, and would be great to have it:

![52b58bfa-3ee2-11e5-8b64-173003d799f4](https://cloud.githubusercontent.com/assets/15699236/13545317/789f284e-e266-11e5-8346-0c13f9e74f09.jpg)

**Comment by LautaroL20** [comment]
Is the fact that these wouldn´t have the colliding feature that stops you from implement it? Users still would be able to using Router Strips if thats the reason.

**Comment by TeamSpen210** [comment]
No, that mainly means it has to be a separate item. That's fine, but the slight issue is that many models don't have a cold skin, which means they need a custom model.

**Comment by LautaroL20** [comment]
As for clean model, i have done a texture for it, as well as a nice "light_panel_cold" PeTi Icon:

![light_panel_cold](https://cloud.githubusercontent.com/assets/12244376/19752409/8c7f633e-9bd3-11e6-9daa-3a0c554a4a8a.png)

![colddw](https://cloud.githubusercontent.com/assets/12244376/16542073/828bb1ee-406f-11e6-8dee-b378cc9b0add.jpg)

**Comment by LautaroL20** [comment]
Ill do this one, although im having some problems arranging the glow effect from the P1 Hole light.

**Comment by LautaroL20** [comment]
Implemented for next release? @TeamSpen210 Don´t forget to take a look at my item, ill want it to be included on next release.
