### ISSUE TITLE
Placeable Door editor model is missing a texture in Old Aperture

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3152]
![DOOR](https://user-images.githubusercontent.com/12244376/69484760-e5c1b200-0e15-11ea-91ca-720a2fad6e81.png)

**Comment by Luke18033** [comment]
Has this not been reported yet? I'm sure it was but I can't find an existing issue for it.

**Comment by LautaroL20** [comment]
I do not think so, however if you have the enough patience required to find a previous person who could have originally reported it, close this.

**Comment by TeamSpen210** [comment]
I rebuilt this mode using the original geometry, so I must have missed out including the material.

**Comment by Luke18033** [comment]
Still missing for me, I'm on the dev version
![image](https://user-images.githubusercontent.com/19228201/71391497-38c78a00-25b9-11ea-8afe-9362deafcac8.png)

**Comment by LautaroL20** [comment]
The commited fix should be revised then, since this issue would get wrongly closed automatically when PRL37 comes out.

**Comment by Luke18033** [comment]
Never mind, I exported with the wrong version.

**Comment by LautaroL20** [comment]
How does it look the updated model now?

**Comment by Luke18033** [comment]
Exactly the same, but with the actual texture there.
