### ISSUE TITLE
Add a faint red glow to buttons as an option

### ISSUE THREAD

**Issue by mariovct** [BEEmod/BEE2-items#3154]
i've seen a lot of maps add a faint red glow to buttons and i dont see why it couldn't be implemented into beemod as an itemvar:

![Capture red](https://user-images.githubusercontent.com/31172185/69904140-f911d780-1357-11ea-9c30-164b56f774d2.JPG)

**Comment by LautaroL20** [comment]
Nice suggestion, it should be implemented as an itemvar.

**Comment by TeamSpen210** [comment]
All floor buttons actually have a faint glow already. It’s very dim (⅒ of a light strip), so you’d need to block off other light sources to see it clearly. You can also place a cube on the button and see the glow affect it.
