### ISSUE TITLE
Make the field of the custom fizzlers to moving alongside with their frame´s animation

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3159]
This was already implemented on the Radiative Flux Rectangle and Lifeform Sensor. However, it would be really nice having this implemented in all the custom fizzlers, see screenshot:

### **Before this gets implemented, issue #3158 should be solved first**

![Custom Fizzlers editor models - Make the field to moving alongside with the frame´s animations](https://user-images.githubusercontent.com/12244376/70303403-51285e00-17de-11ea-8fb5-0ccb57dff17f.jpg)

**Comment by TeamSpen210** [comment]
It's a bit of a question which part it should be anchored to. The original fizzler effect doesn't move...

**Comment by LautaroL20** [comment]
Here is a GIF showing exactly what i am trying to suggest to implement if the original post is confused to understand due to my english limitations:

In one case, Radiative Flux Rectange will move its field along with the frame, and it the other fizzler it doesn´t due to not be anchored yet.
![GIF](https://user-images.githubusercontent.com/12244376/70355953-13651d00-1852-11ea-9396-9383f2996602.gif)

**Comment by LautaroL20** [comment]
However, the problem here is that the default blue field that is hardcoded is already overlapping with the custom colored fields in some cases, so, implementing this suggestion would get kinda ruined by the vanilla hardcoded field regardless...
