### ISSUE TITLE
PotatOS concept

### ISSUE THREAD

**Issue by magicdog2013games** [BEEmod/BEE2-items#3161]
PotatOS has been denied because of continuity errors, I came up with an idea, specific voices allow PotatOS they would be Cave (PotatOS) Wheatley (PotatOS) and announcer (PotatOS) It shouldn't be too hard since you can make monitors play Wheatley and GLaDOS so why not PotatOS?

**Comment by Konclan** [comment]
Personally I dislike voice lines in general, PotatOS in old bee just seemed to cause a lot of noise when the map started and would talk over other voice lines. This could probably be fixed but IMO PotatOS should just be left out of BEE since it doesn't add much

**Comment by Luke18033** [comment]
The problem with those was that they were supposed to be responses to Multiverse Cave dialogue. Except that broke when you'd already gotten through all the lines, or had other characters in the map. PoTaToS also wasn't actually on the gun (it was supposed to be normal GLaDOS saying the line), which made it seem out of place.

**Comment by magicdog2013games** [comment]
> PotatOS should just be left out of BEE since it doesn't add much

Just because you don't like the idea doesn't mean others don't plus the addition of cameras and screen monitors have no functionality apart from decoration.

**Comment by TeamSpen210** [comment]
They do - showing another area of the test chamber.

**Comment by Luke18033** [comment]
See #3339 with specific quote suggestions.
