### ISSUE TITLE
Create new editor model for Fizzler Output Relay

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3162]
The Fizzler Output Relay uses the same editor model as Compressed Smoke Fields. This was fine before 4.36.0, but with the new protruding effects it looks really weird, since there's no field preview:
![image](https://user-images.githubusercontent.com/19228201/70369523-cbed8980-186f-11ea-8c73-c281181243fe.png)
A custom model should be created that removes this, or swaps it for a graphic representing outputs (an indicator panel?)

**Comment by King0191** [comment]
For the new Protruding Effect, perhaps replace it with a transparent blue X or yellow check?
