### ISSUE TITLE
Fizzler edge textures not being packed into maps

### ISSUE THREAD

**Issue by Emma-Walker** [BEEmod/BEE2-items#3167]
This issue will only affect people who play Beemod maps without having it installed, and it happens to all fizzlers with edge textures.

Screenshot (make sure to view it in full resolution to understand where the issue is):
![Custom Fizzlers Issue](https://user-images.githubusercontent.com/12244376/70306338-65bc2480-17e5-11ea-88db-e7d4c9a7f7fd.jpg)

**Comment by Luke18033** [comment]
The fact that the color is still present would I think indicate that the VTF is failing to pack, rather than the VMTs. I'm not sure why that would happen, since every other texture packs fine. Although since packing happens automatically now I think this would actually be a compiler issue...

**Comment by ZombiePwner1** [comment]
Yes the VMT's are packing if they weren't then this would just be a white texture.

**Comment by Luke18033** [comment]
It would appear purple, instead of matching the color of the fizzler.

**Comment by LautaroL20** [comment]
This was fixed for the next release.
