### ISSUE TITLE
Old Aperture Stylevar - Use Clean-style models and textures for modern test elements, rather than prototype Old Aperture ones

### ISSUE THREAD

**Issue by Critfish** [BEEmod/BEE2-items#3169]
This proposed stylevar would:

-Change the models and textures for all modern test elements(Light Bridges, Turrets, Funnels, 
etc.) to match their Clean counterparts
-Mount all modern test elements on Clean-style wall panelling, extended into the chamber 
slightly
-Add a Clean test chamber sign mounted on modern panel arms in the corridor leading into the 
chamber, similar to the ones seen in the Mobility Gels co-op course

"But wait, Critfish, this just sounds like the upcoming Refurbished style", you might say.

This proposed stylevar could potentially have a number of advantages over having a separate Refurbished style. Such advantages could include:

-Allowing ALL Old Aperture time periods(50's, 60's, 70's and 80's) to have a refurbished look, 
rather than just having only 50's refurbished chambers, as seen in the Refurbished style.
-Refurbished can be essentially rolled into the existing Old Aperture styles, without having to go 
all the way and create a new style for it.
-Allows a more conservative approach to making Refurbished-style chambers, more akin to the 
ones seen in Mobility Gels. The upcoming Refurbished style has things like vactubes running 
down into the chamber, and has the player jump out of a chute into the sphere. I, and possibly 
many other users, think that it's a little overkill, and would prefer something more simple.
-Some of the "prototype" models for Old Aperture variants of modern test elements look kind of 
ugly. Some of them look like they're made of brushes, like something you'd see in a Goldsrc game, 50's funnel emitters just look like gel pipes embedded into the wall, some of the models look like they've been pieced together from a mishmash of existing vanilla Portal 2 models, just to name a few. As a result, many people just don't use the Old Aperture styles because of it. Allowing modern test elements to just look like their modern counterparts, set up in a manner similar to the existing Mobility Gels levels, would entice quite a few people to take a look at the Old Aperture style and try making something with it, rather than just sticking to Clean style 99% of the time.
-Some test elements flat out can't be changed for Old Aperture. For instance, Frankencubes. 
They'll always have to look the way they do, and will never properly fit with the Old Aperture look. 
They'll always look modern. Allowing modern-style models for modern test elements would allow for a real explanation for why they're there - they were added after the original chamber was built.

I feel that this would provide all of the advantages of the Refurbished style, plus additional benefits, without having to go through the effort of adding a completely new style.

**Comment by King0191** [comment]
I like this, however the W.I.P. Refurbished Style has certain attributes like the vactubes running into the chamber. That would give it it's own charm

While i'd LOVE to see this as a stylevar. I would still like to see a Refurbished style, as, in the long run. Having as many options as possible to give a chamber a certain feel/aesthetic, is one of the best routes to go (in my opinion)

**Comment by Critfish** [comment]
Issue with having Refurbished as a separate style, is that it'll only be refurbished 50's chambers, the other three decades don't get anything, which I think is a net loss in terms of potential themes. Plus, it doesn't properly solve the problem of "chronologically mismatched elements", particularly  when you include things like Propulsion and Conversion Gels, which wouldn't chronologically exist in a 50's chamber.

**Comment by King0191** [comment]
Neither would Exursion Funnels. or Light Bridges. Or Lasers. 
I don't see that point. And if anything, since they aren't super BIG or serious changes (just some textures, excluding a certain few) I could see a Custom-made Refurbished style for each Era not being TOO difficult to do. (Once they have normal Refurbished done. It can be used as a base for the rest of the eras)

I could see a 60's Refurbished having a modernized Flamethrower while the others have modernized crushers. However it is ultimately up to the devs. 

I would love to see this added. Don't get me wrong.

But we cannot deny that the main Refurbished style has a special charms that this Stylevar simply wouldn't provide

**Comment by Critfish** [comment]
Oh, of course, the Refurbished style itself does have its own properties that make it special. But, it kind of goes off and does its own thing, unlike anything seen in Portal 1 and 2. Mobility Gels chambers in Portal 2 were more or less unmodified, with modern testing elements inserted when needed. Refurbished looks as if the entire chamber is being reworked, Mobility Gels implies that they're simply being modified. If I'm honest, I feel as if the idea of having "prototype" models for modern elements in Old Aperture was a bad idea to begin with, but I think it's too late to change it now. This stylevar would satisfy both parties.

**Comment by TeamSpen210** [comment]
If I ever get around to doing the Refurbished style, it'd be as a seperate style and not merged into a stylevar.

**Comment by TeamSpen210** [comment]
Maybe I'd do four of them, but it's a lotta work...
