### ISSUE TITLE
Bomb-type reflection gel droppers only dispense one bomb

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3174]
Each time the dropper is activated, only a single bomb will be dispensed. This does not apply to the standard gel types. Only tested on Clean.

**Comment by Luke18033** [comment]
Why do reflection gel droppers need their own instance? Can't you just use the normal dropper instance with `$paint_type` set to `1`? For the model in Clean/Old Aperture, you could just make a custom version with Reflection Gel as skin 1.

**Comment by Luke18033** [comment]
Or you could have the dropper model as a separate instance that gets overlaid on top of the logic, then swap them out based on the gel type.

**Comment by TeamSpen210** [comment]
They don't really, I just built them a long time ago before I figured out those sorts of tricks and assumed I did need to use a seperate instance. I think there might have been some other additional logic in them as well, but that's not used anymore.

**Comment by Luke18033** [comment]
Checked the instances, this specifically affects Clean, though the separate instance for reflection gel is also in use in Old Aperture.
