### ISSUE TITLE
Angled blocks use old icons in-game

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3176]
In-game, the blocks show these icons (for all variants):
![image](https://user-images.githubusercontent.com/19228201/71383589-ecb51f00-2591-11ea-8386-b15001d33cae.png)
These are the versions that should be used, as seen in the app:
![image](https://user-images.githubusercontent.com/19228201/71383634-0e160b00-2592-11ea-816a-64b8facff7ff.png)
This doesn't apply to the corner blocks, or any other block items.

**Comment by Luke18033** [comment]
Did you even read my post? I specifically said "all variants", it's not just the combined one, that's just what I happened to have in my palette.

**Comment by Flash4433** [comment]
Here's a simple fix, I just grabbed the correct icons, converted them and swapped them. The .zip file has the correct .vtf icons.

[blocks.zip](https://github.com/BEEmod/BEE2-items/files/4242000/blocks.zip)
