### ISSUE TITLE
Cube Dropper´s tiles does not match the attached surface color

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3178]
Editor:
![20191223185741_1](https://user-images.githubusercontent.com/12244376/71383745-81347700-25bc-11ea-8902-09213f375ecd.jpg)

In-game result:
![20191223185806_1](https://user-images.githubusercontent.com/12244376/71382496-f7ce7600-25b6-11ea-9a28-72b13bca1dc0.jpg)

**Comment by Luke18033** [comment]
Fixed with the new tiling system
