### ISSUE TITLE
Prioritise pre-painted gel on the same surface over opposing side

### ISSUE THREAD

**Issue by Critfish** [BEEmod/BEE2-items#3182]
In BEE2, placing a gel splat underneath a cube dropper will cause the dropper to drop cubes pre-painted with the gel. However, this can cause issues, because you can't put pre-placed gel splats underneath droppers anymore, because it applies the gel to the dropper. There should be an option to disable this functionality, or change the way you apply gel, like putting the gel on the same tile as the dropper itself.

**Comment by TeamSpen210** [comment]
What I should do is make a paint splat placed on the ceiling disable the one below from taking effect.

**Comment by Luke18033** [comment]
So then I guess you'd put Cleansing Gel up there, to cancel out the gel below?

**Comment by TeamSpen210** [comment]
Yeah. Note that currently if you were to place two splats below (of different colours) one will be used for the dropper and the other to paint the surface. But there's no reliable way to decide which will be first.
