### ISSUE TITLE
Entrances regardless of style

### ISSUE THREAD

**Issue by magicdog2013games** [BEEmod/BEE2-items#3188]
An example would be having a Portal 1 Elevator area to go to the next test which is a portal 1 test but leave that area in a portal 2 elevator, If people want to create custom stories for the steam workshop this would be a great idea, I've tried doing it myself but its too complicated so I gave up. regardless this would be a good idea and would simply be toggled using something like 'generic exits' or having any exit/entrance available as long as you have the style

**Comment by Critfish** [comment]
This just seems like pointless style mixing. Not only are Portal 1 and Portal 2 stylistically different from an artstyle perspective and would clash as a result, how would you do this for BTS or Old Aperture? A test chamber elevator wouldn't lead directly to a manufacturing plant, for example. And to be honest, if you're making a custom story for the workshop, you might as well just use Hammer.

**Comment by magicdog2013games** [comment]
> This just seems like pointless style mixing. Not only are Portal 1 and Portal 2 stylistically different from an artstyle perspective and would clash as a result, how would you do this for BTS or Old Aperture? A test chamber elevator wouldn't lead directly to a manufacturing plant, for example. And to be honest, if you're making a custom story for the workshop, you might as well just use Hammer.

There reason i'm saying this on here is because hammer is way too hard to use

**Comment by Critfish** [comment]
It's really not that hard, actually. I used to be in the same boat as you, until I actually started using it.

But besides that, this, again, just seems like pointless style mixing. You end up with stuff like Clean elevators going to BTS areas, Old Aperture elevators going to Overgrown test chambers, it's kind of a mess.

**Comment by King0191** [comment]
If this had been like the other “All entrances/exits for all styles” issue made, where the entrance/exit changes to fit the style. To add more variety (example: that one Old Aperture Office Entrance, in BTS, would be more of a modern Aperture version) then I would agree. 

But this just makes no sense to me, style mixing should never be a thing, really.

**Comment by TeamSpen210** [comment]
No style mixing.
