### ISSUE TITLE
High Energy Pellet launcher/catcher have oversized selection meshes

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3192]
One of the few BEE1 items that still hasn't has this issue fixed. A large portion of what is supposed to be the base ends up below the surface, and the "arms" don't match up.
![image](https://user-images.githubusercontent.com/19228201/72212266-b599a580-348d-11ea-9193-4997d7fe49bf.png)

**Comment by LautaroL20** [comment]
Not only i´ve fixed the meshes to the correct size, but i also remake them in the following cases:
* High Energy Pellet launcher/catcher ( #3192)
* Savepoint (#3194)
* Placeable Door (#3193

Final result: 
![I´ve remake selection meshes](https://user-images.githubusercontent.com/12244376/72362217-85424900-36d1-11ea-92c0-e93ef69f3309.jpg)

**Comment by TeamSpen210** [comment]
Nice!

**Comment by LautaroL20** [comment]
Thank you.
