### ISSUE TITLE
BEE1 Doors have oversized selection meshes

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3193]
Title says it all.
![image](https://user-images.githubusercontent.com/19228201/72212311-7ae43d00-348e-11ea-8dd0-da353b3c7f0d.png)

**Comment by LautaroL20** [comment]
With the remake mesh i´ve commit, now it should be easier to grab its gyzmo in the editor:
![I´ve remake the door selection mesh](https://user-images.githubusercontent.com/12244376/72362177-73f93c80-36d1-11ea-9a02-2c8e63ec7464.jpg)

**Comment by TeamSpen210** [comment]
For selection meshes, they don't need to be made of concave bits or anything - those sides can just be two triangles.

**Comment by LautaroL20** [comment]
Alright, will revise the number of polygons again, i´ve already reduced them for optimization but i will give it an aditional revision like in this case and will try implementing what you´re suggesting.
