### ISSUE TITLE
Leaks on 1960s style

### ISSUE THREAD

**Issue by Anus95** [BEEmod/BEE2-items#3195]
I have already made an issue about it before with overgrown but ive noticed same has happened on the 1960s. The sp entry is 2 and sp exit 4. I will try to reinstall the mod to see if that helps as someone already told me before it might.

![PORTAL 2 12 01 2020 17_08_16](https://user-images.githubusercontent.com/59677445/72215502-00372280-355f-11ea-9c0a-d68d245ace0b.png)

![PORTAL 2 12 01 2020 17_08_20](https://user-images.githubusercontent.com/59677445/72215504-03321300-355f-11ea-8be0-e08e9d9460b9.png)

**Comment by Anus95** [comment]
I have completely reinstalled the game and the issue has dissapeared

**Comment by ZombiePwner1** [comment]
Consider this issue fixed then.
