### ISSUE TITLE
HEP Sendificator

### ISSUE THREAD

**Issue by The-Queen55142** [BEEmod/BEE2-items#3199]
Seen in the (mildly confusing and basic) mod of [Portal 2: Displacement](https://www.moddb.com/mods/portal-2-displacement). There's a gun where you shoot a green HEP, Right click, and teleport to it. 

This gave me the idea of creating a High Energy Pellet version of the Sendificator! 
When you hit the button, the pellet explodes and the item is teleported where the pellet once was! This can allow for more specific Sendificating puzzles, and combining the two could be REALLY fun!

This would follow the same guidelines as the current Sendificator. You connect the Sendificator to the HEP Launcher, you connect a button to the Sendificator, add any inputs to the Launcher if necessary (Example: a floor button, to limit your movement but you still have to maneuver the pellet correctly!

EDIT: I jokingly suggested this in #1537 but that was a while ago and I've changed my thoughts on the aspects of it. No grabbing, just use a normal HEP and it sends.

**Comment by mariovct** [comment]
I like this Idea is a simple, it’s Clever, it has a-lot of puzzle potential, and it solidify’s the HEP as A Major element. I’m just wondering how hard I’d be to implement

**Comment by Konclan** [comment]
I think as a concept this is a pretty bad idea, heps in general are just annoying to work with which is why lasers replaced them in Portal 2 to begin with. Now add the waiting for heps to move to their destination with a stress of trying to time when you press the sendificator button so the cube lands in a spot which map makers can make as small as a cube button or something and you have yourself an obnoxious puzzle mechanic. Lasers are literally point A to point B in an instant which is why the sendificator works well. This idea seems like a downgrade to the sendificator and would be too niche to work well for a puzzle like the futbol.

**Comment by The-Queen55142** [comment]
I agree but also disagree. Lasers are nice and neat and all that happy stuff, but like you said. They're point A to B. There's no way to go inbetween without putting panels, reflector cubes, or whatever into your map. A HEP Sendificator would fix this issue as you can be much more specific. 

And yes. there's always the bad map makers. But that shouldn't be our reason for not adding it. Bad map makers can find a way to use ANYTHING incorrectly (see: Turrets and Lighting Up A Test Chamber) So what does that mean? Should we remove turrets? Should we remove light sources and just have the tests at a constant brightness? Every mechanic can be made obnoxious. That shouldn't deter us from adding something.

I also tend to disagree with the "niche" description. This would add more functionality to the HEP, and give more uses for items like the Pellet Deflector from rexaura. And its not like the cube would maintain the momentum of the HEP. It wouldn't go nyooming into the stratosphere. 

Timing a press of a button is something that isn't new to Portal,
A timing based challenge is technically a puzzle, you have to figure out how to time something to get it where you need. This also gives more functionality to the Pellet Speeds you can choose from on the interface of the BEE application.

**Comment by TeamSpen210** [comment]
Timing on its own isn't a puzzle. Where it works is when you have two possible ways to do a task - one which is clearly too slow to complete in time, and the solution which gives you plenty of time.

And your argument in the second paragraph is rather backwards. This is a suggestion for a new thing, not a request to remove something. I do agree with Konclan that the timing involved in triggering it is pretty bad.

It'd probably be better if people first build these new test elements in Hammer, see if they actually have promise.
