### ISSUE TITLE
Leaks on 1980s

### ISSUE THREAD

**Issue by Anus95** [BEEmod/BEE2-items#3200]
Leaks on 1980s style. SP entry is lobby. SP exit is presentation. skybox is sphere exterior and has open enrichment sphere toggled on.

**Comment by Flash4433** [comment]
Are there any logs/screenshots that you could send?

**Comment by Luke18033** [comment]
Those generally aren't helpful for leaks. You'll want to upload a copy of `Portal 2/sdk_content/maps/styled/preview.vmf` (make sure you grab the version in `styled/` and **not** `maps/`).

**Comment by Anus95** [comment]
Do I just send you a copy of my portal 2 files?

**Comment by Luke18033** [comment]
No, send that specific file.

**Comment by Anus95** [comment]
It says it doesnt support that file so i cant send it through a comment

**Comment by Flash4433** [comment]
Try putting it on a .zip file or upload it somewhere, like Google Drive or Mega, and send the link here.

**Comment by Anus95** [comment]
this should do

https://mega.nz/#!KCoCFIBL!WVzh2Fsq6uD9jgVsPey0uycafUEZh3U50BqHYrtfPD8

**Comment by Luke18033** [comment]
Seems to be fixed in the geometry branch.
