### ISSUE TITLE
separated co op checkpoint looks clean in different styles.

### ISSUE THREAD

**Issue by Anus95** [BEEmod/BEE2-items#3203]

**Comment by ZombiePwner1** [comment]
There is already a duplicate issue of this hidden around somewhere I can't remember.

**Comment by Anus95** [comment]
Idk if its a bug its just that the seperated co op checkpoint doesnt change its looks while in different styles.

**Comment by ZombiePwner1** [comment]
It is a bug this has beene around since PRL 21 and earlier. None has offered to fix it.
