### ISSUE TITLE
exit co-op not open with all ✅

### ISSUE THREAD

**Issue by MischaGer** [BEEmod/BEE2-items#3205]
have bind my exit with
1x cube_button
1x Ball button
2x laser catcher
and 3 x laser relay

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2989

**Comment by MischaGer** [comment]
how fix it?

**Comment by LautaroL20** [comment]
Only Spencer could fix it via VScript. However, i have been pinged this issue so people can see it is already reported and is in high priority.

**Comment by MischaGer** [comment]
have fix that with another door
