### ISSUE TITLE
Something is generating clipping through the 80s Co-op exit

### ISSUE THREAD

**Issue by MischaGer** [BEEmod/BEE2-items#3207]
![Screenshot](https://user-images.githubusercontent.com/12244376/72866107-f927b700-3cb8-11ea-88bc-5be564cb74d0.jpg)

**Comment by Luke18033** [comment]
This isn't a lighting problem, if you look closely you can see that there's a huge black brush extending through the elevators and stairs. Something is generating that isn't supposed to, maybe co-op doesn't work correctly with the open sphere? This needs investigation.

**Comment by Luke18033** [comment]
This doesn't happen for me...

**Comment by Luke18033** [comment]
@MischaGer Could you upload the map file that had the issue, so one of us can look at it in Hammer?

**Comment by Luke18033** [comment]
Closing due to lack of info
