### ISSUE TITLE
2-high Positronic Energy Orbs have a white backing

### ISSUE THREAD

**Issue by quat1024** [BEEmod/BEE2-items#3210]
If you make a Positronic Energy Orb start two voxels up, like these highlighted ones:

![image](https://user-images.githubusercontent.com/2068021/72886560-02744c00-3cd8-11ea-99ab-54d6c618b84a.png)

you get this:

![image](https://user-images.githubusercontent.com/2068021/72886480-e07ac980-3cd7-11ea-80f5-106cd2225525.png)

Packages version 4.36.0, bee 4.36.1.

**Comment by Luke18033** [comment]
Does this apply to the dynamic versions as well (if you connect something to it)?

**Comment by Luke18033** [comment]
It's a missing texture, no idea why it appears white for you. I'm not sure what texture that would actually be, I'll take a look.

**Comment by Luke18033** [comment]
`anim_wp/fra0`, apparently. No idea how that would have happened.

**Comment by quat1024** [comment]
Thank you!
