### ISSUE TITLE
New Variant: Cracked High Energy Pellet

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#3211]
This is a new item, A Cracked High Energy Pellet. This CHEP will have a cracked version of the shell containing the condensed energy.

This pellet is only shot through a launcher, if it hits anything that isn’t the catcher. It will explode, 

I.e. Walls, Pistons, Panels, Light Bridges, Glass, Grating (if set to not go through it)

Lasers and Fizzlers will also break it, If possible

This makes it easier to have multiple puzzles in the same room without them interfering as much.

 This may also be used to avoid the annoying on and off of the Radiative Flux Field, as you could turn off the HEP once it hits the field. Then it hits a wall and breaks.

The choice on whether or not they should have a timed and infinite or only one is the only thing I’d like opinions on!

**Comment by TeamSpen210** [comment]
I'm not sure it'd be necessarily possible or easy to make something like this. BEEmod isn't a "implement every test element idea" mod, I'd far prefer if the item is already present in some Hammer maps or otherwise before adding it here.
