### ISSUE TITLE
Issue with "More Info" Tab on Death Fizzler Item

### ISSUE THREAD

**Issue by Determinated888** [BEEmod/BEE2-items#3219]
![unknown-2](https://user-images.githubusercontent.com/40443625/74756181-cd590c00-5239-11ea-94da-e79d43156e07.png)
On the "More Info" tab of the Death Fizzler, the link provided leads to the old TWP website. This website is no longer related to Portal 2 and is supposedly a virus haven. If there are viruses on this page this is a major issue.

**Comment by Flash4433** [comment]
And this might be the case for more items too. I guess I can look into it and see what items need to be changed...

**Comment by Determinated888** [comment]
That would be good. A lot of new people don't realize that this is the wrong website.

**Comment by Luke18033** [comment]
It should go to https://thinking.withportals.com, the new site.

**Comment by Flash4433** [comment]
It seems as it's the only item that still uses `thinkingwithportals`. The other item that's also from TWP, the Bumbleball, has the correct link, `thinking.withportals`.

**Comment by Flash4433** [comment]
Also, fixed in https://github.com/BEEmod/BEE2-items/commit/f9b4cbaf97b5bb3fa2a237be41faa1314202ebd6 .
