### ISSUE TITLE
Memories soundtrack

### ISSUE THREAD

**Issue by GeneticLifeform** [BEEmod/BEE2-items#3221]
Could you add the soundtrack to the Portal 2 mod 'Memories'? If you have permission.

**Comment by Flash4433** [comment]
The creator seems to no longer be working on this mod. The only info I found about the permission is this.

> If you are going to edit my creation / use for advertisement or add into it; you must give me credit and ask for my permission.
If you are going to make videos / movies of these maps (e.g. make a speed run / play through of the map) feel free but if you are using it in a trailer of some sort, again, please ask for permission and give credit to me for the map.

The Facebook link and Steam link the creator gave seems to have been deleted, so the only way to contact him seems to be through mod.db. He was online last month.

So yeah, guess they'll have to ask for permission. Also, the music is great! :)
