### ISSUE TITLE
BTS pedestal button to be a lever

### ISSUE THREAD

**Issue by GeneticLifeform** [BEEmod/BEE2-items#3222]
Could you create an option for making the BTS pedestal button a lever, as shown in Chapter 5 & 6? If there is a timer, the lever would flip back up again, and if there is no timer then it would just stay down.

**Comment by Flash4433** [comment]
That's a nice idea... I think it's the perfect use for an "Alternate Version" of the pedestal, maybe even a new item altogether.

**Comment by TeamSpen210** [comment]
It is a lever, if set to infinite.

**Comment by Flash4433** [comment]
Wow, that's a pretty nice detail!
