### ISSUE TITLE
White pistons in P1 style.

### ISSUE THREAD

**Issue by LogicDeLuxe** [BEEmod/BEE2-items#3229]
In P1 style, pistons on pretty much anything appear shiny white instead of the metallic look.

**Comment by Luke18033** [comment]
Can you send a screenshot? I'm not sure what you're referring to.

**Comment by TeamSpen210** [comment]
The metallic look comes from them reflecting the area around them. I can't build the cubemaps required for that in puzzlemaker, so instead I created a generic version.

**Comment by Luke18033** [comment]
It looks like you can use `$envmaplightscale` to make the reflection darken based on lighting? It seems to be supported on LightmappedGeneric in P2.

**Comment by Luke18033** [comment]
I added that parameter. It now looks much more reasonable, even if it still isn't perfect.
![portal2_DN49eTpxvG](https://user-images.githubusercontent.com/19228201/93153782-d9655900-f6b6-11ea-94fc-6d18684fd970.png)
![portal2_7rbL8xSWuW](https://user-images.githubusercontent.com/19228201/93153786-da968600-f6b6-11ea-8a92-f9b3e81eca44.png)

Here's the second area with the old material, for reference:
![image](https://user-images.githubusercontent.com/19228201/93153943-47118500-f6b7-11ea-9d8e-6bb818db1fb8.png)

**Comment by TeamSpen210** [comment]
That is much better indeed!
