### ISSUE TITLE
Cut tiles are completely broken

### ISSUE THREAD

**Issue by seagemgames** [BEEmod/BEE2-items#3232]
I had some cut tiles in my level, causing a huge headache. They make a broken solid, break the map completely and also add a visible Nodraw. Happens in Clean and BTS (afaik).

**Comment by Flash4433** [comment]
Cutout tiles are really buggy for some reason... For example, #2675, #2593 and #2441.

**Comment by seagemgames** [comment]
At this point, remove them completely. They serve barely any purpose and just destroy the entire map when placed. Remake 'em from scratch

**Comment by ZombiePwner1** [comment]
I do agree that they need to be re-made entirely. Last time I used them placing them in certain spots actually caused my game to crash which is quite unusual.

**Comment by Flash4433** [comment]
Now it seems to crash pretty much anywhere... :upside_down_face:

**Comment by TeamSpen210** [comment]
I am planning on rebuilding them from scratch actually. The tiling upgrade (BEEmod/BEE2.4#1181) means the old code won't even work actually.

**Comment by seagemgames** [comment]
Next release, remove it please as it can completely break your map with no reason

**Comment by Luke18033** [comment]
Not really anything new here
