### ISSUE TITLE
Paint Can

### ISSUE THREAD

**Issue by Flash4433** [BEEmod/BEE2-items#3234]
This is a really requested item in BEEmod's Discord Server, so I was surprised to not find it here. The Paint Can is an item created by Prototype and enhanced by tuleby (CZ). [Here's tuleby's map](https://steamcommunity.com/sharedfiles/filedetails/?id=1233617523).

The Paint Can is a very simple item. It's a can with paint (gel) that, when heated with a laser, explodes (simply destroying the can, doesn't affect anything else), leaving gel around the place it exploded. (People are talking about a second way to explode the can in the comments of the original map, but I'm not sure what it is.)

It can have any type of gel, it uses a dropper and, its most important feature, works with the Sendificator. In BEE2.4, it could have `cube_type` to choose between the 5 gel types (jump, speed, clean, portal, reflection), and the normal properties to work with the dropper. It seems that tuleby was working on its package with the paint cans, but that was back in 2018 and there doesn't seem to be any updates on that.

I decompiled the map I linked and changed some stuff.
[paintcan.zip](https://github.com/BEEmod/BEE2-items/files/4258007/paintcan.zip)

In this .zip file, I included all of the models, materials, scripts and the .vmf itself of the map. There is some other stuff mixed, like the normal sendificator model and material.

 The paint can's model uses `skins` to switch between textures. The textures have different versions for each gel type and, since I added a reflection gel material, the model will probably need some changes to allow this extra texture. The script of the sendificator has been modified to allow paint cans to be transported too, and that's why I'm posting this here, as I do not (yet) understand Squirrel coding. And since there's no instance for the paint can, I included the .vmf of tuleby's map. Thank you, and good luck! :D

P.S. Forgot to say, but there's also a custom Paint Can dropper model. Not sure if it's just a normal gel dropper model, as I can't find the corresponding textures in the map's files :P

**Comment by Konclan** [comment]
UCP
