### ISSUE TITLE
Standing fizzler placement is wrong

### ISSUE THREAD

**Issue by seagemgames** [BEEmod/BEE2-items#3235]
When placing the standing fizzler initally, it is in this state.
![image](https://user-images.githubusercontent.com/32136200/75598359-cc03cb00-5ae6-11ea-8773-979bfe0f5442.png)

Problem is, this isn't a state it can be in, when using the little widget/gizmo thingy. Therefore, it cannot be rotated to be centred facing the other direction. It's texture also mis-aligns when placed off-centre like this.

The correct placement when the square is like this would be here.
![image](https://user-images.githubusercontent.com/32136200/75598438-5fd59700-5ae7-11ea-9f28-cfcdef52db0a.png)

**Comment by LautaroL20** [comment]
My Standing Fizzler is mounted over two pillars made of 4x4 thin blocks. It would not make sense if their pillars would be attached to the center of a gridded boxel where their tiles would not match with the ones of the pillars. Basically, the pillars of the Standing Fizzler must give the feeling that they are coming from a gridded surface and placing it in the center like the vanilla fizzler would harm this feeling.

**Comment by seagemgames** [comment]
I'm not sure if you understood, when placing it by default, it doesn't line up to the grid. its off by 0.5 tiles, breaking the grid.

**Comment by LautaroL20** [comment]
In that case, that is a thing that can not be fixed unless i use the lightstrip item class with it (this class makes an item with the size of a light strip to prevent appearing in the center when placed). However, using this class would cause to this item collision issues that will limit the chances of placing it on certain areas and other troubles.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Should leave the hardcoded label as this cannot be changed.
