### ISSUE TITLE
Support intersecting seperate Catwalk items

### ISSUE THREAD

**Issue by Meltinglce** [BEEmod/BEE2-items#3238]
If you create a xatwalk, just as the title says, there is a lot of z-fighting on the catwalk.
https://youtu.be/sRgROWcq2kU

**Comment by TeamSpen210** [comment]
I haven't implemented cross-intersections.

**Comment by TeamSpen210** [comment]
Or, well, multiple catwalks intersecting isn't currently detected so it'll just generate two straight models.

**Comment by CoolStuff08** [comment]
It's a single catwalk, no duplications or anything
