### ISSUE TITLE
Turn on-able lights/squares.

### ISSUE THREAD

**Issue by jamser40** [BEEmod/BEE2-items#3240]
this would just be cool for atheistic reasons for when you walk into a room. this could work the same way the observation room does but it would be cooler if you could just connect an input to the lights.

**Comment by Luke18033** [comment]
See the [FAQ](https://github.com/BEEmod/BEE2-items/wiki/FAQ#can-you-add-lights-that-are-toggled-by-an-input) for why this isn't possible.
