### ISSUE TITLE
Portal 1 coop checkpoint camera using non-animated model

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3245]
![image](https://user-images.githubusercontent.com/18079316/77224314-53e96c00-6b9f-11ea-9f59-f637ec302f69.png)

**Comment by CheezyPig** [comment]
I don't believe the camera model can move.

**Comment by ZombiePwner1** [comment]
@CheezyPig It can lol

![image](https://user-images.githubusercontent.com/18079316/77224472-f81fe280-6ba0-11ea-80c0-f2c5d845cf7f.png)

**Comment by Luke18033** [comment]
That's actually partially correct - the version of the P1 camera included in default Portal 2 indeed does not animate. That was used in BEE2.2 where it wasn't always possible to pack stuff, but most of them have now been replaced by a proper animated version. Guess not this one though.

**Comment by Luke18033** [comment]
Surprise surprise, changes inexplicably got reverted!
