### ISSUE TITLE
Portal 1 coop exit door doesn't open.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#3249]
![image](https://user-images.githubusercontent.com/18079316/77240188-10821280-6c1e-11ea-9004-1005b617ab94.png)

**Comment by ZombiePwner1** [comment]
Happens in 1980's old aperture aswell.

**Comment by Luke18033** [comment]
Duplicate of #2989. It's a pinned issue, can you please pay more attention to that?
