### ISSUE TITLE
P1 Reclined fizzler doesn't block paint in aperture tag because it still uses the old logic generation.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3252]
![image](https://user-images.githubusercontent.com/18079316/77240414-753e6c80-6c20-11ea-8cf1-153d6d478cda.png)

**Comment by Luke18033** [comment]
This will be fixed when TeamSpen switches those items to use normal fizzler generation, instead of specific instances.

**Comment by LautaroL20** [comment]
Standing/Reclined Fizzlers have been switched to use normal generation in the latest public release, so this issue is now fixed.

**Comment by LautaroL20** [comment]
Although this should be fixed, it still happens in P1. This would not happen in Clean style though.

**Comment by Luke18033** [comment]
It's fixed for standing fizzlers.
