### ISSUE TITLE
Cause of science music doesn't play.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3253]
PrecacheScriptSound 'music.BEE2' failed, no such sound script entry

**Comment by Luke18033** [comment]
What specific combination of variant tracks are you using? I don't have any problems with this.

**Comment by Luke18033** [comment]
Closing due to lack of info

**Comment by FrozenDragon0** [comment]
Wasn't using any combination just the music on it's own.

**Comment by Luke18033** [comment]
So just Cause of Science as the base track, with no variant tracks?

**Comment by FrozenDragon0** [comment]
Yes

**Comment by Luke18033** [comment]
I can't reproduce this.
