### ISSUE TITLE
Old aperture standing fizzler isn't using fizzler edge texture

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3256]
![image](https://user-images.githubusercontent.com/18079316/77245028-5b1f8100-6c56-11ea-8191-f28d1b6b73c2.png)

**Comment by Luke18033** [comment]
It should be using the unique fizzler side textures. Also, you should set `ss_force_primary_fullscreen 1` before you take screenshots in Co-op, that way it won't show the splitscreen.

**Comment by Luke18033** [comment]
This would be fixed with the new tiling system.
