### ISSUE TITLE
I want to play intro and main separately

### ISSUE THREAD

**Issue by Shinkibus** [BEEmod/BEE2-items#3257]
How do I separate the custom music `intro` from the `main`, play the `intro` first, then loop the `main`?

**Comment by TeamSpen210** [comment]
I assume you mean your own custom track, but the way you do it is to add [loop cue points](https://developer.valvesoftware.com/wiki/Looping_a_Sound) to your WAV. Put the start point between the intro and main part, which will make it restart there when looped.

**Comment by Shinkibus** [comment]
Thank you.
I'll try
