### ISSUE TITLE
3D factory skybox not working

### ISSUE THREAD

**Issue by owlman5126** [BEEmod/BEE2-items#3258]
So a little bit a go I made a level with the 3D factory skybox selected and I had put the goo in the level and when I built the level it worked but a little bit later when I rebuilt the level is was just goo on the ground not the bottomless pit that it was before. Thanks in advance

**Comment by CheezyPig** [comment]
If you put more than one goo item in, only one becomes a bottomless pit.

**Comment by Luke18033** [comment]
Not quite right, the goo needs to be placed in the lowest block of the map (since otherwise the pit could clip through stuff below)

**Comment by owlman5126** [comment]
Ok, thanks @Luke18033 that fixed it 👍
