### ISSUE TITLE
Portal 1 small obs room should fill entire block (128x128)

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3260]
Adding onto the ancient issue of #459, standard small observation rooms in Portal 1 should be made 128x128, filling the entire block. That suggested item could then be used for the half-block size, which is consistent across all styles and would allow the rest of the block to match the surface color.

**Comment by TeamSpen210** [comment]
I probably am going to do this.

**Comment by maxdevgithub** [comment]
As we are going to have half block obs. room separately, this would be nice

**Comment by Luke18033** [comment]
I already implemented it.
![portal2_3vvpbbX4pG](https://user-images.githubusercontent.com/19228201/94347270-89a45d00-ffe7-11ea-8002-2e61464a8b20.png)

**Comment by maxdevgithub** [comment]
> I already implemented it.
> ![portal2_3vvpbbX4pG](https://user-images.githubusercontent.com/19228201/94347270-89a45d00-ffe7-11ea-8002-2e61464a8b20.png)

That crosshair, where did you get it?

**Comment by Luke18033** [comment]
It was originally the HL2 quickinfo, which was used in Blue Portals, then I updated it to work in P2.
