### ISSUE TITLE
Life form sensor + Fizzler Output Relay not triggering

### ISSUE THREAD

**Issue by micheledicosmo** [BEEmod/BEE2-items#3262]
Hi, maybe I don't understand how to connect the items, but the following isn't triggering the Relay even tho the Sensor makes the noise and changes colour when I pass through it. Am I missing something?

I tried both with "3 seconds" and "inifinite" activation, doesn't change. As well as "fizzler" and "laser".
The only connection here is between the Relay and the Laser beam.
The puzzle is set to co-op.

Does "place on top" mean to put the Relay in the box just above the Sensor? And is that it or does it require something else to work?

![image](https://user-images.githubusercontent.com/701157/78401302-55c81c00-75f0-11ea-8bcc-4ed65eddbe61.png)

Thanks!

**Comment by Luke18033** [comment]
The relay needs to be placed in the same position as one of the fizzler emitters. You can do it on the opposite end to make it easier to select.

**Comment by micheledicosmo** [comment]
Alright, after writing this post I realised that "on-top" means exactly in the same box of the sensor. I would vote this ticket to become an improvement for the description of the item.

**Comment by micheledicosmo** [comment]
Amazing, Luke, that's a good hint. I'll open a pull request for a description change
