### ISSUE TITLE
Monitor Screen in Old Aperture Causes Build Error

### ISSUE THREAD

**Issue by Ten2O** [BEEmod/BEE2-items#3269]
If you try and use a monitor screen in Old Aperture, it gets a build error. I also checked the error in console and it said that it couldn't open monitor.vmf. After further investigation, I found out that monitor.vmf is not present in the old aperture styles. I don't know if this is because it's not finished or anything but it says that it's supposed to work with Old Aperture so I would assume that it wasn't on purpose.
(monitor.vmf is missing in "packages\monitors.zip\resources\instances\50s\items\screen"
and 
"C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\instances\bee2\50s\items\screen")
The fact that these are missing are causing a build error I'm pretty sure.

**Comment by TeamSpen210** [comment]
I must have forgotten to copy over the instance from my local folders.

**Comment by Luke18033** [comment]
Can this monitor variant be broken, what happens in that case?

**Comment by TeamSpen210** [comment]
Currently no.
