### ISSUE TITLE
Obs Room leaks on specific place

### ISSUE THREAD

**Issue by Flash4433** [BEEmod/BEE2-items#3270]
![Leak](https://cdn.discordapp.com/attachments/293435914598744064/699250232679989258/unknown.png)
Discussion in the #beemod channel in the Discord Server.
Upon moving the Obs Room it fixes the leak and putting it back there puts the leak back. Removing the button and the block under it did not fix the issue too. Clean style.

Upon inspection of the .vmf and .lin files, it seems there was a leak in the EmbeddedVoxels of the Obs Room, despite the line passing through a solid wall...
![Hammer pointfile](https://media.discordapp.net/attachments/293435914598744064/699284635104051230/unknown.png)

Here are the .vmf and .lin files.
[leakymap.zip](https://github.com/BEEmod/BEE2-items/files/4470448/leakymap.zip)

Here are the coordinates of the brush in question since it's a big map.
![image](https://user-images.githubusercontent.com/38331230/79137991-a804fc00-7dab-11ea-82e5-baee7ffbdabe.png)

**Comment by Luke18033** [comment]
There used to be a bug with the large observation room, where it would leak when placed near a corner. Maybe this is related?

**Comment by Luke18033** [comment]
This should be fixed in the geometry branch.

**Comment by maxdevgithub** [comment]
![preview0002](https://user-images.githubusercontent.com/58821795/97084530-6ee1fa00-1620-11eb-92c2-d769c11b7b2f.jpg)
I have a similar issue on P1 style
