### ISSUE TITLE
Exposed Nodraw in all Clean SP entrances

### ISSUE THREAD

**Issue by DrMeepster** [BEEmod/BEE2-items#3271]
![image](https://user-images.githubusercontent.com/19316085/79496995-d537f100-7fdb-11ea-89e7-ae52ea201725.png)
As seen in the image, there is visible nodraw in the doorway from the elevator to the hallway.

Goo is visible so it is not a leak.

![hammernodraw](https://user-images.githubusercontent.com/19316085/79498250-d66a1d80-7fdd-11ea-8417-7f8b00b0763d.png)

In Hammer, the nodraw is clipping through the doorway.

I have seen the exact same problem in Hammer and in-game for ALL Clean SP entrances.

**Comment by TeamSpen210** [comment]
That's the worldportal being misaligned, not the nodraw.

**Comment by Overwatch-C-17** [comment]
Wait, I ever reported this issue before, it's a dupe

**Comment by ZombiePwner1** [comment]
@Overwatch-C-17 Can you provide the link to the original post?

**Comment by Overwatch-C-17** [comment]
#3123
