### ISSUE TITLE
Art Therapy: Backpanel textures can appear on fronts of panels

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3274]
![image](https://user-images.githubusercontent.com/19228201/79677848-28f83500-81aa-11ea-8d54-c5370040abd7.png)
I'm not sure if there's any way to control this (without removing those textures entirely), but it doesn't make much sense, so a system should be implemented for this in that case.

**Comment by ZombiePwner1** [comment]
@Luke18033 The plastic wall textures are alright but I can definitely see these backpanels looking out of place.

**Comment by supersean08-pro** [comment]
how do you get that hl2 crosshair, because i want to make my portal 2 as beta looking as possible

**Comment by Luke18033** [comment]
I just took the HL2 quickinfo graphics, and modified them to work as the portal crosshair. It's not specifically supposed to be "beta", I just prefer that design.

**Comment by supersean08-pro** [comment]
> I just took the HL2 quickinfo graphics, and modified them to work as the portal crosshair. It's not specifically supposed to be "beta", I just prefer that design.

yea it looks like blue portals, and the new portal 1 texture looks like the wall from the portal 1 mod deep chambers, if you remember it, your basically a legend, if you dont you are basically a legend

**Comment by Luke18033** [comment]
The plan is to remove backpanels from the randomly picked textures, and have them as decorations instead.

**Comment by supersean08-pro** [comment]
> The plan is to remove backpanels from the randomly picked textures, and have them as decorations instead.
i tried to do it but to no avail, tried looking into the resources and script's from the garrys mod and portal 2 folder to try and change it

**Comment by supersean08-pro** [comment]
> The plan is to remove backpanels from the randomly picked textures, and have them as decorations instead.

i tried to do it but to no avail, tried looking into the resources and script's from the garrys mod and portal 2 folder to try and change it

**Comment by Luke18033** [comment]
This has nothing to do with Gmod????

**Comment by supersean08-pro** [comment]
> This has nothing to do with Gmod????

it has source engine, its half-life but with lua, what i mean by gmod, is that it was all half life 2 elements, but i cant figure out how to get the half life 2 hud quickinfo

**Comment by Konclan** [comment]
[This is not a forum.](https://github.com/BEEmod/.github/blob/master/contributing.md#this-is-not-a-forum)
