### ISSUE TITLE
Suggestion: Angled glass blocks 

### ISSUE THREAD

**Issue by Emma-Walker** [BEEmod/BEE2-items#3277]
I suggest a new item variant: Angled blocks but with a glass surface.

**Comment by TeamSpen210** [comment]
Which sides would be glass? I'm not exactly sure.

**Comment by Emma-Walker** [comment]
The angled side would be covered in glass.

**Comment by Endermage77** [comment]
Having a set of glass blocks would actually be really handy for building unpaintable platforms.

**Comment by ZombiePwner1** [comment]
@Endermage77  We would need a nice looking model for that to work though. Diagonal glass brushes would look hideous.

**Comment by Luke18033** [comment]
I think it would look fine?

**Comment by Konclan** [comment]
Why cant we just use the laminated tile system with angled blocks instead of creating a new item which would be redundant

**Comment by Emma-Walker** [comment]
> Why cant we just use the laminated tile system 
Laminated tile system?

**Comment by Luke18033** [comment]
TeamSpen is planning on adding a nonpaintable surface item, which would appear as a sort of laminated tile. It'd be better to allow placing that on top of angled blocks instead of adding an entirely new item.

**Comment by Emma-Walker** [comment]
Oh, that sounds brilliant, would be fantastic!

**Comment by Konclan** [comment]
Obsolete with surface lacquer

**Comment by Luke18033** [comment]
Can surface lacquer actually apply to items like partial blocks and flip panels?

**Comment by Konclan** [comment]
If it doesn't that should be considered a bug because they should based on the item description
