### ISSUE TITLE
New Gel suggestion

### ISSUE THREAD

**Issue by RmxMi** [BEEmod/BEE2-items#3278]
I suggest adding the unused purple gel found in portal's files which lets you stick to walls as it is inside portal 2 files maybe it would be easier to just add it just with better textures than the missing texture ones and  #I think it would benefit some gel tests greatly.

**Comment by Flash4433** [comment]
See https://github.com/BEEmod/BEE2-items/wiki/FAQ#can-you-add-adhesion-gelsome-other-custom-gel-to-bee24

**Comment by ZombiePwner1** [comment]
Not possible.
