### ISSUE TITLE
Art therapy backpanel textures should not generate if there is a lightstrip.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#3279]
![image](https://user-images.githubusercontent.com/18079316/79960802-6e717680-84b8-11ea-9d1d-ad7baa1665a1.png)

You can see that the backstage panel texture looks very out of place with a light strip on it.

**Comment by Luke18033** [comment]
IIRC issues like this are caused by the fact that the compiler assumes all floor/ceiling textures are 4x4. This *might* be fixed by the tiling system, but I'm not sure.

**Comment by Luke18033** [comment]
Also you don't need to add `Development Version` to all of these issues, the `Art Therapy` label kind of implies that already.

**Comment by TeamSpen210** [comment]
It is, now stuff is properly specifiable as multiple sizes. So I can make those only 1x1 and 2x2.
