### ISSUE TITLE
Art therapy flip panel wheel clips through the panel in a mysterious way.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#3280]
![image](https://user-images.githubusercontent.com/18079316/79980675-0cc00500-84d6-11ea-8b39-3be99a80d933.png)

**Comment by Luke18033** [comment]
Not really fixable, there isn't any room up there. We could shrink down the panel, but then it might not work correctly with the new tiling system (which allows you to color each tile individually).
