### ISSUE TITLE
Physics Repulsion Field has incorrect protruding effect

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2-items#3283]
It looks like this:
![image](https://user-images.githubusercontent.com/19228201/80298438-3cbf1080-8741-11ea-9f49-82fc02862216.png)
Similarly to #3282, this is another VMT issue: The material is set to use `fizzler_bounds`, instead of the correct `fizzler_bounds_fade`. Should be another easy fix.

**Comment by Luke18033** [comment]
Oh look it broke for a third time
![image](https://user-images.githubusercontent.com/19228201/159383194-622ad04a-77a4-4fc1-bcda-57d5ccf511ef.png)
