### ISSUE TITLE
P1 Custom Fizzler model has bad smoothing groups

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3285]
Compare the shading on the emitter model in these two screenshots:
![portal2_O2Sp4A3xGI](https://user-images.githubusercontent.com/19228201/80315157-ab848400-87aa-11ea-9451-4644c071c065.jpg)
![portal2_NybedGbxUD](https://user-images.githubusercontent.com/19228201/80315158-acb5b100-87aa-11ea-951b-385ec30a42b8.jpg)
The custom fizzler model has a sort of rounded appearance on the edges, which isn't present on the normal model. Applying an "edge split" modifier in Blender seemed to fix the problem, which is something I've seen Lautaro mention a few times before, but I'm not sure if that's the best way to fix this so I'll let someone else take a look.

**Comment by TeamSpen210** [comment]
That's likely the problem, bad smoothing groups. The SMD import used to mess those up annoyingly.
