### ISSUE TITLE
AT+Geometry: Flip Panels are always non-portalable on the back

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3292]
![image](https://user-images.githubusercontent.com/19228201/80419804-a39e1000-888e-11ea-922c-1f6eed3b8fd5.png)
![portal2_a16W6169U8](https://user-images.githubusercontent.com/19228201/80419813-a7ca2d80-888e-11ea-8254-2d48b956839c.png)
Normally it should use the opposite tile pattern, unless Start Reversed is checked.

**Comment by TeamSpen210** [comment]
This would need to have the new logic copied over.
