### ISSUE TITLE
Suggestion: Toggleable walls

### ISSUE THREAD

**Issue by Emma-Walker** [BEEmod/BEE2-items#3293]
I suggest togglable walls .

I don't know how hard this is to code. But maybe it's possible to make walls that can be toggled on on (= look like normal walls) and toggled off (= are gone completely). 

Since the Angled Surfaces and Partial Blocks can intersect freely, maybe they can be turned off freely, too?

**Comment by Critfish** [comment]
Closed Solid Fields do this, except they look like fizzlers. There's no reason for there to be toggleable walls that look exactly the same as regular ones. People would just make "puzzles" with random hidden doors that you have to spend 30 minutes trying to find. Closed Solid Fields work far better for puzzles.

**Comment by CheezyPig** [comment]
Plus, you could just use an angled panel and toggle it. It makes far more sense as well than a vanishing wall.

**Comment by Emma-Walker** [comment]
> Closed Solid Fields do this

But closed solid fields are transparent. Also, they allow goo through when they are close to the ground. Also they are never leveled with the wall/ground.

**Comment by TeamSpen210** [comment]
Yes, because walls don't randomly vanish. Aperture has all kinds of inventions, but they at least make some weird sense.

**Comment by ZombiePwner1** [comment]
@Emma-Walker That's what the closed solid field is for. As @TeamSpen210 walls randomly vanishing would make no sense.
