### ISSUE TITLE
Physics Repulsion Field overlapping some objects in editor

### ISSUE THREAD

**Issue by Elaztril** [BEEmod/BEE2-items#3300]
In the PeTI editor the Physics Repulsion Field overlaps certain things, like antlines or extended fizzler parts. This could be the case with other custom fizzlers but I haven't tested. Sorry if the image isn't clear enough, but it should provide enough info to help recreate this if at all possible. Using clean style.
![image](https://user-images.githubusercontent.com/9942278/80921656-8ad9a280-8d45-11ea-86a1-a0ebee574e6b.png)

**Comment by Luke18033** [comment]
This is a well-known bug in the engine, translucent texture sorting is a pretty hard thing to do. You'd need source code access to try and fix it.
