### ISSUE TITLE
Double Glass

### ISSUE THREAD

**Issue by Emma-Walker** [BEEmod/BEE2-items#3301]
There's a portal glitch (Gel on glass glitch) which makes glass on wall useless in preventing gelification:
![N7ltzlgKTyNCXXoISkUaLpgekseLIskQOv26cxS8lPI](https://user-images.githubusercontent.com/8507237/81016636-80b0c480-8e69-11ea-9bcb-bdadfaf92b64.png)
https://www.youtube.com/watch?v=Z-MZyOr4lqw

If you have a wall and directly on top of it glass, then a gel dropper can still paint the wall and make it portalable. And although the player can't enter the portal, cubes can.

If the glass is further away from the wall then it stops the gel (as it should be).

Even Closed Solid Field has this bug, note the blue portal behind it:
![20200505073647_1](https://user-images.githubusercontent.com/8507237/81035391-67c50500-8ea3-11ea-924e-cf203cd0e1bb.jpg)

As soon as Glass (or the Closed Solid Field) is further away, the walls don't get gelificated.

Now my theory is that thicker glass (two glass panels slightly apart) may fix  that portal glitch. Has anyone of the Bee2 item creators tried that out? If not, then it's a suggestion for a new item: "Double Glass".

**Comment by Luke18033** [comment]
I think it'd be better to add an "offset inward" option with Start Reversed, like quarter walls currently have. Alternatively, you can put the glass in front of a 3/4 block which pretty much does the same thing (and actually looks a bit nicer IMO)

**Comment by Emma-Walker** [comment]
> I think it'd be better to add an "offset inward" option with Start Reversed, like quarter walls currently have. Alternatively, you can put the glass in front of a 3/4 block which pretty much does the same thing (and actually looks a bit nicer IMO)

Unfortunately, this also doesn't work. Serious portal glitch is serious.

![20200507025921_1](https://user-images.githubusercontent.com/8507237/81240172-5b5dbb00-900f-11ea-90c7-f2506a88510a.jpg)

**Comment by Luke18033** [comment]
In that case then I don't think double glass would help either, if the gel application is that inaccurate.

**Comment by TeamSpen210** [comment]
The "proper" solution would really be to locate these surfaces, and swap them to use a no-paint material.

**Comment by Emma-Walker** [comment]
> In that case then I don't think double glass would help either, if the gel application is that inaccurate.

My assumption that double glass would help is based on the observation that Closed Solid Field shows this glitch, too, but when I move the Closed Solid Field fizzler slightly away then it blocks the gel as it should

>The "proper" solution would really be to locate these surfaces, and swap them to use a no-paint material.

I hope this would solve it. Double Glass is my layman's suggestion to solve that glitch. If the glitch is fixable or hotfixable in any other way then that would be even better.

**Comment by Emma-Walker** [comment]
Follow up question: Is it possible to make glass fizzle the goo?

**Comment by Luke18033** [comment]
Uh, what?

**Comment by Emma-Walker** [comment]
I mean, to make glass behave like glass+fizzler. That would solve all the goo problems. It would still look like glass but would fizzle any goo that comes near.

**Comment by koerismo** [comment]
an easy fix would be for someone to make an invisible no-paint item that can be placed on any surface to prevent paint being applied to it

**Comment by Luke18033** [comment]
There are already plans to add an unpaintable tile item, which would basically solve this problem.

**Comment by Luke18033** [comment]
Being able to pass cubes through portals behind glass would be caused by #3264.
