### ISSUE TITLE
Retractable Pedestal Button: 1 second, 2 seconds

### ISSUE THREAD

**Issue by Emma-Walker** [BEEmod/BEE2-items#3302]
Is it possible to make the countdown of the Retractable Pedestal Button include "1 second" and "2 seconds"?

That way I could use it to drop a cube without ticking for 3 seconds.

The normal Pedestal Button also has "One second" and "Two seconds".

**Comment by TeamSpen210** [comment]
Right click on the item in BEE2, then select "Change Defaults...". You can then set the default timer delay to 1 or 2.
