### ISSUE TITLE
The "Porta-Portal"

### ISSUE THREAD

**Issue by zep-excpoint** [BEEmod/BEE2-items#3304]
Introducing the _Aperture Science Portable Intra-dimensional Gate Generator,_ or for short, the Porta-Portal!

![costume1 (5)](https://user-images.githubusercontent.com/30127909/81879550-1aa6fa00-9559-11ea-84a9-8633bed75569.png)

This item can be picked up like a cube, and, when set down for more than a second, spawns a portal that is either blue or orange, depending on if you selected _Start Reversed._

Here is a video of someone messing around with one: https://www.youtube.com/watch?v=GPr3FuPp3Z0

**Comment by FrozenDragon0** [comment]
Interesting idea. I could see this being pretty useful in aperture tag. You'd have access to a auto-portal + this item whilst using a paintgun, so this might be a good idea.

**Comment by Luke18033** [comment]
For P2, I'd imagine this would behave like an autoportal, removing the corresponding color from your gun and permanently deactivating if that color is later picked up from a pedestal.

**Comment by DrMeepster** [comment]
I've kind of implemented this. Only problems are lack of custom models and the portal surface clips through walls. The portaportal will open if it stops moving and will close if if it moves more than a single hammer unit from where it opened.
[portaportal.zip](https://github.com/BEEmod/BEE2-items/files/4706928/portaportal.zip)
The zip has a .vmf, a .nut and a compiled map with the script packed in.

**Comment by Konclan** [comment]
UCP
