### ISSUE TITLE
Flip Panel´s selection mesh is facing a wrong orientation

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3306]
![Selection Mesh](https://user-images.githubusercontent.com/12244376/82108756-2fc18b80-9707-11ea-988e-e7b2720495ee.jpg)

**Comment by LautaroL20** [comment]
i´ve improved the mesh entirely, screenshot:

![Flip Panel selection mesh remake](https://user-images.githubusercontent.com/12244376/82109456-68179880-970c-11ea-8ba1-03f0052cc48c.png)

**Comment by Luke18033** [comment]
I'm not sure it really needs to include all that geometry, you're probably only ever going to be grabbing it from the center. Can we even override Valve meshes?

**Comment by LautaroL20** [comment]
> Luke18033 Said: Can we even override Valve meshes?

This is not a model converted to a mesh, also i guess almost all meshes were made by Valve? 
I will only keep with the arrow and delete the rest of the polygons if that is better.

**Comment by Luke18033** [comment]
I mean that the Flip Panel is a default Valve item, so I don't think we can really replace the selection mesh for it without duplicating the entire model - which, *I guess* would work, but is it really worth it?

**Comment by CheezyPig** [comment]
Doesn't BEEmod remake every Valve item?

**Comment by Luke18033** [comment]
The instances yes, but we reuse the original editor models in Clean.

**Comment by LautaroL20** [comment]
> Luke18033 Said: I mean that the Flip Panel is a default Valve item, so I don't think we can really replace the selection mesh for it without duplicating the entire model - which, _I guess_ would work, but is it really worth it?

I have tested this right now and it seems that unfortunately, selection meshes from `Portal 2\bee2\models\puzzlemaker` do not overrides the ones located at `portal2_dlc2` so yes, at this point i am not sure if fixing Valve´s mesh mistake would worth it...

**Comment by Luke18033** [comment]
We could maybe put it in the DLC3, but I really don't think this matters too much.
