### ISSUE TITLE
Sendificator will cause "Failure To Compile" 

### ISSUE THREAD

**Issue by rebelderp127** [BEEmod/BEE2-items#3307]
`````
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\compiler_launch.py", line 13, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 2101, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 1754, in make_vrad_config
  File "F:\Git\BEE2.4\src\cubes.py", line 637, in write_vscripts
FileNotFoundError: [Errno 2] No such file or directory: 'bee2/inject/cube_vscript_01.nut'
[4502300] Failed to execute script compiler_launch
`````
_____________________________________________________________________

The sendificator wont work. When I press the button, the blue particle effect appears, but the cube isn't sent. I don't know what I'm doing wrong because I tried the same thing in the same level and it worked fine. If you need more details let me know.
<img width="156" alt="egggggggggggggg" src="https://user-images.githubusercontent.com/58536777/82291215-37cf3480-996e-11ea-8d61-6a50cc33f60d.PNG">

**Comment by The-Queen55142** [comment]
Right click the laser and set it to Start Enabled. It auto turns off due to gaining a connection. Unless you plan to turn it on later in the level. It needs to start on

**Comment by rebelderp127** [comment]
I tried that and it still doesn't work.

**Comment by Luke18033** [comment]
Any errors in the console?

**Comment by rebelderp127** [comment]
I didn't think about that earlier. This shows up when I press the button:

AN ERROR HAS OCCURED [the index 'GetOrigin' does not exist]

CALLSTACK
*FUNCTION [trace()] sendificator.nut line [441]
*FUNCTION [main()] InputRunScript line [1]

LOCALS
[this] TABLE
[this] TABLE

**Comment by TeamSpen210** [comment]
A fix you can use is to create the folder `Portal 2/bin/inject/`.

**Comment by BigUpBoris2024** [comment]
Just saying, since I'm (apparently) having the same issue, the fix above did not work.

**Comment by BigUpBoris2024** [comment]
do we have a fix for this yet?

**Comment by LautaroL20** [comment]
Yes, this is the fix: https://github.com/BEEmod/BEE2.4/commit/1ceb125f00b345613211632800c40e1b20c49030

**Comment by BigUpBoris2024** [comment]
thank you

**Comment by Notsoartificialintelligence** [comment]
I'm having this problem, I've made the inject folder but nothing still works

**Comment by BigUpBoris2024** [comment]
you need to install the developer version which has the fix above

**Comment by Notsoartificialintelligence** [comment]
thanks

**Comment by Notsoartificialintelligence** [comment]
where do i get the dev version

**Comment by BigUpBoris2024** [comment]
ive honestly no clue ive been trying to install for a couple days now

**Comment by Notsoartificialintelligence** [comment]
oh

**Comment by BigUpBoris2024** [comment]
i raised an issue another issue about this but no reply yet
