### ISSUE TITLE
45° and 30° P1 Angled Panel editor models are slightly raised up from the floor surface

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3314]
![Image](https://user-images.githubusercontent.com/12244376/82748272-ef9d8100-9d76-11ea-96f3-f1a1cb84d7e0.jpg)
![Image](https://user-images.githubusercontent.com/12244376/82748279-f62bf880-9d76-11ea-97db-f449cabb2089.jpg)

**Comment by Luke18033** [comment]
It might be a good idea to just remake these models entirely, like TeamSpen said he originally wanted to do.

**Comment by LautaroL20** [comment]
> Luke18033 Said: "It might be a good idea to just remake these models entirely, like TeamSpen said he originally wanted to do."

The P1 Angled Panel editor models looks good, it is just that they have some minor issues like this one and its wrong piston texture. You asked me to do their selection meshes and i have gladly accepted the task. However, if TeamSpen ends up modifying the geometry of these models, then someone will must to remake the selection meshes that i am almost to finish because making them for these models is not easy and i will not be remaking these meshes again...
