### ISSUE TITLE
Rail panel

### ISSUE THREAD

**Issue by mariovct** [BEEmod/BEE2-items#3321]
This panel would be directly attached to a track platform, and when activated would slide from the start to the end of the track similar to how a piston platform functions.
![7955D4C7-8CA6-4CEF-9167-96DB4FB9A73F](https://user-images.githubusercontent.com/31172185/83955516-90288200-a808-11ea-8ab1-5ae5ba93bd2c.png)

**Comment by DrMeepster** [comment]
I think this should be a variant of the existing track platform, just like how the piston platform has solid variants

**Comment by Luke18033** [comment]
You can already do this? Use one of the panel track platform variants and set it to non-oscillating mode.

**Comment by mariovct** [comment]
I said it would function like a piston platform. Ie; returning to the start when deactivated.

**Comment by Luke18033** [comment]
That's what non-oscillating mode does.
