### ISSUE TITLE
Laser Catcher and Standing Fizzler issue

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#3323]
Style: Clean
![temp1](https://user-images.githubusercontent.com/35931028/84568821-c2972980-ad8a-11ea-9c68-a2270214cfa3.png)

**Comment by SCIENTIST2004** [comment]
djhyyarhg

**Comment by Luke18033** [comment]
Huh, that's weird. Does it happen without the standing fizzler there?

**Comment by SCIENTIST2004** [comment]
this only happens if the laser catcher is near the standing fizzler
![20200613215048_1](https://user-images.githubusercontent.com/35931028/84576850-6949ed00-adc0-11ea-9443-3faa51cb460a.jpg)

**Comment by Luke18033** [comment]
@TeamSpen210 Would this be fixed with the new tiling system?

**Comment by SCIENTIST2004** [comment]
console log:
NET_GetBindAddresses found 192.168.0.103: 'Realtek PCIe GbE Family Controller'
NET_GetBindAddresses found 169.254.57.70: 'NordLynx Tunnel'
Opened Steam Socket NS_SERVER ( socket 3520 )
Opened Steam Socket NS_CLIENT ( socket 3076 )
Network: IP 192.168.0.103, mode MP, dedicated No, ports 27015 SV / 27005 CL
Parent cvar in client.dll not allowed (movement_anim_playback_minrate)
Game supporting (2) split screen players
maxplayers set to 1
Steam config directory: D:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2.exe\platform\config
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/change_this
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/gesture_smallwave
resource/closecaption_dfd_English.txt not found
resource/closecaption_russian.txt will be used
Unknown command "cl_thirdperson"
Unknown command "joy_no_accel_scale"
Using joystick 'Xbox360 controller' configuration
Advanced joystick settings initialized for joystick 1
------------
joy1 x axis:  strafe (absolute)
joy1 y axis:  forward (absolute)
joy1 z axis:  unmapped
joy1 r axis:  pitch (absolute)
joy1 u axis:  yaw (absolute)
joy1 v axis:  unmapped
Advanced joystick settings initialized for joystick 2
------------
joy2 x axis:  strafe (absolute)
joy2 y axis:  forward (absolute)
joy2 z axis:  unmapped
joy2 r axis:  pitch (absolute)
joy2 u axis:  yaw (absolute)
joy2 v axis:  unmapped
Failed to init 'maps/soundcache/_master_russian.cache'
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: lock_cmd
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: unlock_cmd
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_Activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_Deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Force
resource/closecaption_dfd_English.txt not found
resource/closecaption_russian.txt will be used
Unknown command "cl_thirdperson"
[PORTAL2 PUZZLEMAKER]  New chamber!
Unknown command "cl_puzzlemaker_activate"
[PORTAL2 PUZZLEMAKER]  New chamber!
CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.0.103, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 3520 )
Opened Steam Socket NS_CLIENT ( socket 3080 )
Network: IP 192.168.0.103, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\newchamber/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\newchamber/c-1904_2096_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\newchamber/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\newchamber/c-2032_-2032_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\newchamber
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker\newchamber_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Connection to Steam servers successful.
   VAC secure mode is activated.
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198165502222\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 39 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 10606 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 11272 (ms)
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198165502222\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Compilation time (after VRAD): 46320 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (complete): 46391 (ms) ...launching map!
Error: Operator stop_entry, unknown sound operator attribute input_start
---- Host_Changelevel ----
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
PrecacheScriptSound 'music.BEE2' failed, no such sound script entry
Commentary: Could not find commentary data file 'maps/puzzlemaker/preview_commentary.txt'. 
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Unknown command "cl_puzzlemaker_start_previewing"
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
=======================Trying to GivePlayerPortalgun
=======================Trying to UpgradePlayerPortalgun
Updating sound cache [9504 entries]
Found 9441 sound files on disk
Updated 0 out of 9441 cached files [996.288 msec]
Redownloading all lightmaps
Setting arrival movie to media\faithplate.bik
-------
Scaling type: 11
-------
]

**Comment by Luke18033** [comment]
That's only really helpful for compile errors.
