### ISSUE TITLE
vactubes 1950's old aperture style compile error

### ISSUE THREAD

**Issue by natanael8284** [BEEmod/BEE2-items#3326]
In old aperture Alone vactubes don't make any errors but when I connect them It fails to compile.
I've only tested this in old aperture 1950's
I would add more information about it but there isn't anything else to say

**Comment by SCIENTIST2004** [comment]
Console log needed

**Comment by portal5555** [comment]
This also occurs in the 1970s style.

Console log: https://pastebin.com/BipFCa4E

**Comment by BlueskyFR** [comment]
can reproduce

**Comment by Konclan** [comment]
Can no longer reproduce, marking as fixed
