### ISSUE TITLE
Texture overlaping 

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#3327]
![20200612155416_1](https://user-images.githubusercontent.com/35931028/84604550-7d185080-ae9f-11ea-8cf1-cbbf3fc1479e.jpg)
![20200614181908_1](https://user-images.githubusercontent.com/35931028/84604553-7e497d80-ae9f-11ea-9e4b-842e9ed61c3e.jpg)
can you do something to prevent such problems?

**Comment by somedoodest** [comment]
is that manually placed Signage or automatically generated Signage? i know i've had similar issues with manually placed Signage, but i don't know if it applies to automatically generated Signage. if it bothers you, you can always place the Antline Router Strip to prevent Antlines from generating on the Signage.

**Comment by TeamSpen210** [comment]
I don't know which is the correct result here - the exit sign, or the checkmark? In the `tiling` branch, this is naturally resolved since the checkmark will prevent the sign from appearing.

**Comment by SCIENTIST2004** [comment]
@somedoodest 
Manually placed and automatically generated

**Comment by somedoodest** [comment]
Huh. Didn't know automatically generated signage could have this problem too..
