### ISSUE TITLE
Reflection/Adhesion Gel's slot makes no sense.

### ISSUE THREAD

**Issue by xXOCsonicLeEpicMemeXx** [BEEmod/BEE2-items#3329]
Why have it separate from the rest of the gels when they are gels all the same.)
![image](https://user-images.githubusercontent.com/50123826/84615784-c1dfbf80-ae7e-11ea-9d22-9a43fb4f491f.png)

**Comment by Luke18033** [comment]
It technically is the same item, set to invalid gel type 5. But we can't change the number of options in the Gel Type dropdown, so it has to take up a separate slot.
