### ISSUE TITLE
Button Pistons

### ISSUE THREAD

**Issue by somedoodest** [BEEmod/BEE2-items#3330]
A simple item, which is a combination of a Piston Platform and a Button.

- Inputs move the Piston Platform
- The Button emits outputs
- Button Type selects the Button used (use standard Button variants)
- Cube Type selects the Piston Platform variant (use standard Piston Platform variants)

**Comment by Flash4433** [comment]
Or, if you put a button at the bottom of a piston, the piston would have the button parented to it. Wasn't the tiling system supposed to do this too?

**Comment by Konclan** [comment]
#3882
