### ISSUE TITLE
Portal Gun Pedestal Not Activating An Output When The Portal Gun Is Picked Up

### ISSUE THREAD

**Issue by 34535-a** [BEEmod/BEE2-items#3335]
When I pick up the portal gun off the pedestal in Portal 2 PeTI, it does not activate it's output(sometimes it does, but it keeps turning on the not activating the output bug, please fix it okay? #1311 It is not the needed portal gun pedestal, it's causing an output bug. If you fix that bug, I will be happy again.

**Comment by Luke18033** [comment]
It worked fine last time I checked, maybe it broke again? This would be a duplicate of that issue either way.
