### ISSUE TITLE
Error while trying to edit a coop map.

### ISSUE THREAD

**Issue by TheEnderek0** [BEEmod/BEE2-items#3336]
Title, please help me.
![Error](https://user-images.githubusercontent.com/67070613/84932985-72df9780-b0d5-11ea-8736-d6d1a3532325.png)

**Comment by TheEnderek0** [comment]
It worked fine, then after I restarted the game, cause I needed an item from BEE2, which I didn't have then, It's showing me this error.

When I build a new chamber and test it, it shows Error texture where exit door camera should be.

I tried reinstalling BEEMOD, selecting diffrent style and unchecking "Door Cameras" Checkmark.

**Comment by Luke18033** [comment]
Should be fixed.
