### ISSUE TITLE
Geometry: Portal 1 Cube Droppers cause a compile error

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3337]
```
Could not open instance file instances/bee2/p1/items/cube/dropper_shaft_long.vmf
```
Removing the block above the dropper changes this to `dropper_shaft_short`.

**Comment by TeamSpen210** [comment]
Mustn't have committed these files.

**Comment by TeamSpen210** [comment]
For both Clean and Portal 1 I now do a check to see if I can extend the dropper shaft up a few more blocks to look better.

**Comment by Luke18033** [comment]
Yeah, I noticed. Couldn't do it before because of the embed space generation I assume?
