### ISSUE TITLE
portable laser receiver 

### ISSUE THREAD

**Issue by mariovct** [BEEmod/BEE2-items#3345]
this would look similar to the laser cube. But when receiving lasers it would not redirect, and instead, activate whatever object it was connected to.

**Comment by mariovct** [comment]
wow, I'm dumb, it was actually in the item's repository

**Comment by Luke18033** [comment]
I just transferred it.

**Comment by ThatOneRetro** [comment]
But, doesn’t that make the puzzle pointless tho?

**Comment by Luke18033** [comment]
It'd be its own item that you specifically design puzzles with, you wouldn't just be able to pull any laser catcher out of the wall and move it around.

**Comment by ThatOneRetro** [comment]
I know thats not what I was saying

**Comment by Konclan** [comment]
I feel as though it would be confusing as to what connects where and I don't really see puzzle applications for this. Would be better as a UCP
