### ISSUE TITLE
There was a error building puzzle

### ISSUE THREAD

**Issue by SametKayaTr** [BEEmod/BEE2-items#3347]
I have this issue IDK how to fix it:

''There Was a error building puzzle''

When ı open the console says this':

''VBSP failed.

Valve Software - vbsp.exe (Nov 12 2019)
12 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
Could not open instance file instances/BEE2/80s/items/cube/standard.vmf''

**Comment by TeamSpen210** [comment]
You might need to export again, it looks like the compilers got overwritten.
