### ISSUE TITLE
Geometry: Piston platforms surfaces not generating correctly

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#3352]
![20200704155147_1](https://user-images.githubusercontent.com/16567080/86521768-83547980-be1a-11ea-82d5-79ae298cb41f.jpg)

**Comment by Luke18033** [comment]
This looks like an issue with the flat variant specifically, which is supposed to produce a panel protruding 32 units from the wall.

**Comment by TeamSpen210** [comment]
The panel is in the right spot, it's the model that isn't...
