### ISSUE TITLE
Geometry: Ring for Colored Cube Droppers offset

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#3354]
![20200705124810_1](https://user-images.githubusercontent.com/16567080/86538866-3aee9780-bebe-11ea-83b5-74fb5145ab69.jpg)

**Comment by Konclan** [comment]
![20200705125734_1](https://user-images.githubusercontent.com/16567080/86539004-26f76580-bebf-11ea-8ea6-ff2d1ccd233b.jpg)
It seems to be a problem with the model, this breaks maps on the workshop as well

**Comment by TeamSpen210** [comment]
I changed where it shows up, I might want to change the origin instead of fixing the instance.
