### ISSUE TITLE
Allow Paint Gun Activation Field to work with standing/reclined fizzler

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3358]
We could just make it work like the default fizzler all we need is compiler logic to detect when a paintgun is connected to such fizzler and change it.

**Comment by Luke18033** [comment]
It's now possible to change the type of the Reclined Fizzler, by connecting its output to that fizzler type. I'm not sure if that works with the paint gun field yet though. What you'd do (if it did work) is connect the paint gun field item to a normal fizzler, then connect that to the standing/reclined fizzler.

**Comment by Luke18033** [comment]
Works currently, or you'll implement that?

**Comment by TeamSpen210** [comment]
It just works fine right now. The fizzler runs its logic first, fails to find a target fizzler on the output and so generates a normal fizzler to place. Then the paint gun finds that and swaps its type.

**Comment by Luke18033** [comment]
Ah, so this should be closed then?

**Comment by LautaroL20** [comment]
Nice!

**Comment by Luke18033** [comment]
I think this is in 4.37.
