### ISSUE TITLE
BEE Logic AND/OR cause a compile error

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3359]
**To fix this issue, open Hammer and save empty maps at the two locations specified below. You will need to do this every time after you re-export.**
```
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/logic/bee/logic_or.vmf
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/logic/bee/logic_and.vmf
```
This error indicates that an instance is missing, but these items aren't actually supposed to use instances anymore. In fact, the entities are being added automatically by the compiler and are still fully functional without the instance, so I'm not sure why it isn't being removed. I'm assuming this is specific to the geometry branch, given that nobody else has reported it. It may also be specific to Overgrown.

**Comment by TeamSpen210** [comment]
What input configuration do you have? My code is pretty complicated, I might have missed some case.

**Comment by Luke18033** [comment]
What do you mean, like the connected items? I first ran into the bug with a few Trigger Multiples, though it also happened with floor buttons. Note that the logic is being added to the map, and if I create a blank VMF at that path it works fine.

**Comment by Luke18033** [comment]
@TeamSpen210 Should probably release a patch that fixes this
