### ISSUE TITLE
Rocket turrets on ceilings don't make any sounds.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3361]
Pretty simple there is no lock on sound if the turret is placed on the ceiling.

**Comment by Luke18033** [comment]
They use the exact same entities on both floors and ceilings, so I don't know how this could happen? It'd be a Valve bug, if anything.

**Comment by Luke18033** [comment]
I can't reproduce this anymore, no idea when or how it would have gotten fixed
