### ISSUE TITLE
Placement Helper model overridden by older versions

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3365]
Editor model is misplaced and is also missing the arrow entirely. The in-game results are bugged too.

![Placement Helper editor model](https://user-images.githubusercontent.com/12244376/86906120-7325ee00-c0e9-11ea-89b9-c1ffe63e43d3.png)

 In-game the portal is supposed to be placed on the side but gets placed like this instead:

![In-game results](https://user-images.githubusercontent.com/12244376/86905472-7a98c780-c0e8-11ea-82d4-dc4342e68cc2.png)

**Comment by Luke18033** [comment]
Ugh, why are people still having this issue?! TeamSpen renamed the model, there is literally 0 reason that old one should be overriding it still.

**Comment by Luke18033** [comment]
Okay, apparently it didn't get renamed? I could have sworn TeamSpen said he did that when he added the arrow. I'll just move the model into a subfolder.
