### ISSUE TITLE
Tag Paint Gun Activation Field Not Working

### ISSUE THREAD

**Issue by arandomgamer8** [BEEmod/BEE2-items#3367]
the apature tag fizzler wont work on any maps i make

**Comment by Konclan** [comment]
Can you provide more information? Screenshots, game, version?

**Comment by Luke18033** [comment]
How exactly is it "not working"?

**Comment by arandomgamer8** [comment]
So i link the paint gun block to the fizzler and when i walk through
nothing happens

I have all tge settings turned off

**Comment by FrozenDragon0** [comment]
@arandomgamer8 Do you mean all the settings on the paintgun item are turned off?

**Comment by arandomgamer8** [comment]
Every tick box is on and ive also tried having them all offSent from Mail for Windows 10 From: >:FrozenDragon:<Sent: 09 July 2020 01:49To: BEEmod/BEE2-itemsCc: arandomgamer8; MentionSubject: Re: [BEEmod/BEE2-items] Tag Paint Gun Activation Field Not Working (#3367) @arandomgamer8 Do you mean all the settings on the paintgun item are turned off?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by FrozenDragon0** [comment]
You didn't have to copy your email message in here lol. Are you running portal 2 or tag?

**Comment by arandomgamer8** [comment]
Portal 2 and when i clicked to reapond it just put it in automatically

**Comment by FrozenDragon0** [comment]
Well there's your problem the paint gun activation field only works on aperture tag.
