### ISSUE TITLE
Recompiled Crusher model has bad smoothing groups

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3371]
Notice how every edge appears to be smoothed-out.
![image](https://user-images.githubusercontent.com/19228201/87105450-e4f85780-c20f-11ea-9b0e-ad99b3df4e24.png)
This is also visible from in front, though it's more subtle.
![image](https://user-images.githubusercontent.com/19228201/87105534-1e30c780-c210-11ea-99d4-c64abe6b13f7.png)

**Comment by FrozenDragon0** [comment]
Is it just me or is the crusher using a slightly lower quality texture. I swear the texture is lower quality than normal.

**Comment by Luke18033** [comment]
The texture is unmodified I'm pretty sure.
