### ISSUE TITLE
Set cl_portal_use_new_dissolve 0 to get portal 1 fizzler effects

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#3377]
In Portal 1 fizzlers destroys objects without any sounds and they use another particles.
In Portal 1 Style fizzlers don't do that. They destroy objects like portal 2 fizzler. 
This effect can be reached by using trigger_physics_trap.

Dissolve Type: Energy

**Comment by SCIENTIST2004** [comment]
![20200715171249_1](https://user-images.githubusercontent.com/35931028/87555703-7c512500-c6be-11ea-88cf-902cdd842c35.jpg)

**Comment by SCIENTIST2004** [comment]
Nevermind!
trigger_physics_trap and trigger_portal_cleanser have same effects.
Closing.

**Comment by FrozenDragon0** [comment]
I don't think we can change this anyway it's most likely hardcoded to play that sound.

**Comment by Luke18033** [comment]
Actually, the hidden cvar `cl_portal_use_new_dissolve 0` can be used to enable the old fizzle effects. It's not possible to pack the plugin that enables those, but we could set it at the start of P1 maps anyway so people who already had the plugin would get the old effect. As for the sounds, those can be removed in vanilla by just replacing the soundscript with one that doesn't play anything. (We'd want to fix #1636 first though, to ensure the sounds return in later maps)

**Comment by Luke18033** [comment]
Okay, `cl_portal_use_new_dissolve` isn't actually hidden apparently. That's good to know, we can just change it and it'll apply for everyone.
