### ISSUE TITLE
Light bridges play a mysterious fiddlesticks sound when turning off.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3381]
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error

This is all the console spews out.

**Comment by Luke18033** [comment]
That's not helpful at all, what sound is actually missing?

**Comment by FrozenDragon0** [comment]
Console doesn't say it just gives out that error whenever a light bridge is turned off/on

**Comment by Luke18033** [comment]
What style?

**Comment by FrozenDragon0** [comment]
Clean.

**Comment by LautaroL20** [comment]
Did you test this issue in other styles as well?

**Comment by FrozenDragon0** [comment]
Not atm.

**Comment by Luke18033** [comment]
I can't reproduce this. Clean light bridges aren't really modified in any way, this is likely caused by some sort of custom content you have installed.
