### ISSUE TITLE
Rocket Turret Laser Becomes More Inaccurate From Further Away

### ISSUE THREAD

**Issue by The-Queen55142** [BEEmod/BEE2-items#3385]
As you get farther away from the Rocket Turret. It will still shoot directly at you, but the beam will be off by quite a substantial amount. Unsure if this can be fixed. But it's worth looking into. It's pretty accurate when up-close though, for clarification

![image](https://user-images.githubusercontent.com/37309250/87881819-d22d1200-c9c9-11ea-88c1-cc362ad7218b.png)

**Comment by Luke18033** [comment]
Known issue, it's not really fixable. (The original laser actually bends slightly to match the rocket's path, which we can't replicate.)

**Comment by Luke18033** [comment]
The rockets themselves should be accurate, so it's not really an issue.
