### ISSUE TITLE
Protruding Pedestal Buttons are now floating in a "Mysterious Way"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3388]
![20200719132429_1](https://user-images.githubusercontent.com/12244376/87882972-55566400-c9da-11ea-882a-c2d7d57929d3.jpg)

**Comment by Luke18033** [comment]
Is the base generating a block too low, or is the button generating a block too high?

**Comment by LautaroL20** [comment]
It is the button´s instance, the brush template seems fine.
