### ISSUE TITLE
Quarter tile doesn´t block portal shots 

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#3389]
![20200719195644_1](https://user-images.githubusercontent.com/35931028/87883029-11c91d80-ca0d-11ea-99a1-5cee7bb15239.jpg)
![20200719195656_1](https://user-images.githubusercontent.com/35931028/87883030-142b7780-ca0d-11ea-9aa8-151bbe49b3b5.jpg)

**Comment by Luke18033** [comment]
This is a known bug in the game, portals only check for a valid surface in the center and in all 4 corners. It's not easily fixable.

**Comment by SCIENTIST2004** [comment]
sadly

**Comment by SCIENTIST2004** [comment]
signage can perfectly block portal shots and quarter tile can't?

**Comment by TeamSpen210** [comment]
Each signage has a portal placement blocking entity placed on top. That'd get really expensive if I did that here, plus it would prevent Conversion Gel from functioning.
