### ISSUE TITLE
Protruding Pedestal Buttons causes "Failure To Compile" in P1 Style

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3390]
`Could not open instance file instances/BEE2/clean/items/lautaro/protrude_ped_mid_black.vmf`
`Could not open instance file instances/BEE2/clean/items/lautaro/protrude_ped_mid_white.vmf`

**Comment by Luke18033** [comment]
Seems like it's not properly switching the white/black versions to use the same instance.

**Comment by TeamSpen210** [comment]
I mixed up `info.txt`, so it wasn't actually using any config file.
