### ISSUE TITLE
Reclined fizzler x4 and x5 has icons only in clean style 

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#3392]
![template](https://user-images.githubusercontent.com/35931028/87883445-18a55f80-ca10-11ea-9bb1-86cdb1ebc069.png)

**Comment by SCIENTIST2004** [comment]
also standing fizzler has only x1 icon
I do not know whether to create an issue for this

**Comment by LautaroL20** [comment]
> also standing fizzler has only x1 variant x2 x3 x4 and x5 are missing
> I don't know whether to create an issue for this

Yeah, i have been reported it here: https://github.com/BEEmod/BEE2-items/issues/3394

**Comment by seagemgames** [comment]
Fixed in #3610
