### ISSUE TITLE
Beemod shows only the X1 version of the Standing Fizzler in the user interface

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3394]
![Standing Fizzler](https://user-images.githubusercontent.com/12244376/87883693-6786d100-c9df-11ea-84e8-eb5c392dea57.png)

**Comment by Luke18033** [comment]
I don't think the other variants really need to be shown since they're just the same thing but resized. That'd be like showing every possible glass size as a separate palette item.

**Comment by LautaroL20** [comment]
For some reason, when i were making the icons for the Standing & Reclined Fizzler, i thought that if items such as Vactuves that are actually using a repeated icon but with a text that says X1, X2 and X3 on it, the most reasonable thing to do for me was to follow that same logic for the Standing & Reclined Fizzler Palette icons.

What you´re suggesting is not a bad idea, however why not also applying this to the Vactuves icons as well?

**Comment by TeamSpen210** [comment]
That would be a good idea as well.

**Comment by LautaroL20** [comment]
This is now fixed thanks to Spencer who made it to only have 1 icon, here is the commit that unfortunately did not add a closing parameter: https://github.com/BEEmod/BEE2-items/commit/1c9decb30809a9a78906bbd3279442f84e94e736
