### ISSUE TITLE
BTS Cube Cleaner/Sink doesn't actually clean them off.

### ISSUE THREAD

**Issue by The-Queen55142** [BEEmod/BEE2-items#3396]
Title is self explanatory. 

![image](https://user-images.githubusercontent.com/37309250/87884153-63a48000-c9da-11ea-9202-d8f2801eb733.png)

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
