### ISSUE TITLE
Portal 1 gel droppers don't work if they have input

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#3399]
start enabled unchecked
![20200720123705_1](https://user-images.githubusercontent.com/35931028/87925272-b2a8ee80-ca88-11ea-9ced-d4228d8da4d1.jpg)
Reflection gel dropper too

**Comment by Luke18033** [comment]
This seems like a connection system mismatch

**Comment by Luke18033** [comment]
Yep
