### ISSUE TITLE
Antline Magnet will cause "Failure To Compile" when more than one input are connected to it

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3406]
`Could not open instance file instances/BEE2/logic/tspen/magnet.vmf`

**Comment by TeamSpen210** [comment]
This is actually itself a duplicate of #3359, in that it's the same underlying cause. Magnets are just AND gates really.

**Comment by LautaroL20** [comment]
Interesting. Yep, both items would basically meet the same function although i opened this issue because i thought that both items would use a different base config or so.
