### ISSUE TITLE
Deadly Goo Bug

### ISSUE THREAD

**Issue by veyzz1** [BEEmod/BEE2-items#3409]
Deadly Goo appears buggy, visually it has no texture.
![20200720174856_1](https://user-images.githubusercontent.com/68553120/87951520-59a18080-cab1-11ea-9787-c77e8ddc9647.jpg)

**Comment by LautaroL20** [comment]
@veyzz1 - Which items did u have in your map and which spots do you placed them? It would be good if you can take a screenshot from the puzzlemaker to see these details so we can figure out what is causing your issue.

**Comment by Luke18033** [comment]
There's a [leak](https://developer.valvesoftware.com/wiki/Leak) in your map. Upload a copy of `Portal 2/sdk_content/maps/styled/preview.vmf` (make sure you get the one in `styled/`) so I can take a look at it in Hammer.

**Comment by veyzz1** [comment]
I couldn't attach the file here, so i contacted Luke18033 through steam, i sent him a friend request, my nickname is veyzz and i have a robot in a jacket on the dark purple background (i did it through steam because i couldn't find any onther way of communication)

**Comment by Luke18033** [comment]
Ah, that's who that was. You can just put it in a ZIP and upload that, or send it to me in a Discord DM.

**Comment by veyzz1** [comment]
[preview.zip](https://github.com/BEEmod/BEE2-items/files/4951606/preview.zip)
There you go.

**Comment by Luke18033** [comment]
Seems to be fixed in v4.37.
