### ISSUE TITLE
BTS CO-OP Exit Door is being leaked

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#341]
CO-OP Exit Door is being leaked, and their frames render over the floor.

![GIF](https://cloud.githubusercontent.com/assets/12244376/13730154/53ecd69c-e926-11e5-8b8d-71b62035a6c0.gif)

**Comment by galacticnerds** [comment]
Still happening, isn't this a simple fix?

**Comment by Luke18033** [comment]
This would be fixed with #530 (implementing the corridors)
