### ISSUE TITLE
Explosive cube droppers?

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [BEEmod/BEE2-items#3410]
Explosive cubes are really cool, but the problem is, they're one-use. Would it be possible to add a dropper so that you could use explosive cubes more than once? Thanks!

**Comment by Flash4433** [comment]
It already is, just put a normal weighted cube dropper on top of it. BEE2 will detect this and swap the weighted cube for the dropperless item, in this case, the bomb cube. This mechanic is really useful, shame it isn't explained that well.

**Comment by MoonstreamJustNotInSpace** [comment]
Thanks!

**Comment by Luke18033** [comment]
This really needs to be documented better.

**Comment by TeamSpen210** [comment]
I've updated the description on the [default items page](https://github.com/BEEmod/BEE2-items/wiki/Default-PeTI-Items#cubes), explaining how this can be done. I should add something to all the cube item descriptions.
