### ISSUE TITLE
Left/Middle/Right and Protruding Pedestal Buttons should match attached surface color

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3411]
If you compare the Valve´s Pedestal base with mines, you will notice that Valve´s one has a different size which do not exactly fit with the surface´s tiles where it is attached to, and therefore it doesn´t give a feel that is being raised up from those floor tiles, so in this case, making it to look always black would be understable. However, in the case of the pedestal base from my buttons, you can notice how their pedestal base are actually correctly sized in order to perfectly match with the surface´s tiles where they are attached to, giving a real feeling that the base is being raised up from those tiles. 

With this, i mean that in the case of my Pedestal Buttons, they actually makes sense to make them follow the surface´s colour where it is attached to. Here is a comparison to let me understand better:

![Image](https://user-images.githubusercontent.com/12244376/87992342-71333600-cabe-11ea-97fc-60142cafd765.jpg)

**Comment by TeamSpen210** [comment]
This is intentional. I had a look back at Valve's maps, and noticed that they're actually always black even on white surfaces.

**Comment by LautaroL20** [comment]
@TeamSpen210 - If you compare the Valve´s Pedestal base with this, you will notice that Valve´s one has a different size which do not exactly fit with the surface´s tiles where it is attached to, and therefore it doesn´t give a feel that is being raised up from the floor, so in this case, making it to look always black would be understable. However, in the case of the pedestal base from my buttons, you can notice how their pedestal base are actually correctly sized in order to perfectly match with the surface´s tiles where they are attached to, giving a real feeling that the base is being raised up from those tiles. 

With this, i mean that in the case of my Pedestal Buttons, they actually makes sense to make them follow the surface´s colour where it is attached to. Here is a comparison to let me understand better:

![Image](https://user-images.githubusercontent.com/12244376/87992342-71333600-cabe-11ea-97fc-60142cafd765.jpg)

**Comment by TeamSpen210** [comment]
It's not that it's offset really. I had a look through all of Valve's maps, and here's the results:

|             Map          | Total | N/A | B on B | B on W | W on B | W on W | On Grid? | Notes |
| --------------------------- | -- | --- | ------ | ------ | ------ | ------ | -------- | ----- |
| sp_a1_intro2                |  3 |  0  |   0    |   0    |   0    |   3    |   Yes    |       |
| sp_a1_intro5                |  3 |  0  |   3    |   0    |   0    |   0    |   Yes    |       |
| sp_a2_bridge_intro          |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    |       |
| sp_a2_bridge_the_gap        |  1 |  0  |   0    |   1    |   0    |   0    |   Yes    |       |
| sp_a2_bts1                  |  2 |  2  |   0    |   0    |   0    |   0    |   No     | No platform |
| sp_a2_catapult_intro        |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    | Platform part of catapault target |
| sp_a2_column_blocker        |  1 |  0  |   1    |   0    |   0    |   0    |   No     | Oversized |
| sp_a2_core                  |  1 |  0  |   1    |   0    |   0    |   0    |   No     | Stalemate Button is special... |
| sp_a2_fizzler_intro         |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    |       |
| sp_a2_laser_over_goo        |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    |       |
| sp_a2_laser_stairs          |  1 |  0  |   0    |   1    |   0    |   0    |   Yes    |
| sp_a2_ricochet              |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    | Oversized |
| sp_a2_sphere_peek           |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    | Too low down |
| sp_a2_trust_fling           |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    | Oversized |
| sp_a4_intro                 |  1 |  1  |   0    |   0    |   0    |   0    |   No     | No platform, but is TEST - incorrect |
| sp_a4_jump_polarity         |  2 |  2  |   0    |   0    |   0    |   0    |   No     | No platforms |
| sp_a4_laser_platform        |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    |       |
| sp_a4_speed_tb_catch        |  1 |  1  |   0    |   0    |   0    |   0    |   Yes    | No platform
| sp_a4_stop_the_box          |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    | Oversized |
| sp_a4_tb_catch              |  1 |  1  |   0    |   0    |   0    |   0    |   No     | On plasticwall |
| sp_a4_tb_trust_drop         |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    |       |
| sp_a4_tb_wall_button        |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    | Oversized |
| mp_coop_catapult_catch      |  1 |  1  |   0    |   0    |   0    |   0    |   Yes    | No platform, retractable button |
| mp_coop_catapult_wall_intro |  1 |  0  |   0    |   0    |   1    |   0    |   Yes    |       |
| mp_coop_come_along          |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    |       |
| mp_coop_fan                 |  1 |  1  |   0    |   0    |   0    |   0    |   No     | Random button inside wall \
| mp_coop_fling_1             |  2 |  0  |   2    |   0    |   0    |   0    |   Yes    |       |
| mp_coop_fling_crushers      |  3 |  3  |   0    |   0    |   0    |   0    |   No     | Timer sounds only |
| mp_coop_infinifling_train   |  2 |  2  |   0    |   0    |   0    |   0    |   Yes    | No platforms |
| mp_coop_laser_2             |  1 |  1  |   0    |   0    |   0    |   0    |   Yes    | Oversized |
| mp_coop_laser_crusher       |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    | No platform |
| mp_coop_multifling_1        |  2 |  0  |   1    |   0    |   1    |   0    |   Yes    | Badly textured |
| mp_coop_paint_crazy_box     |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    |       |
| mp_coop_race_2              |  5 |  0  |   5    |   0    |   0    |   0    |   Yes    | Oversized |
| mp_coop_start               |  4 |  0  |   4    |   0    |   0    |   0    |   Yes    | Oversized |
| mp_coop_tbeam_drill         |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    |       |
| mp_coop_tbeam_laser_1       |  1 |  0  |   0    |   1    |   0    |   0    |   No     | P1 textures... |
| mp_coop_turret_ball         |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    |       |
| mp_coop_turret_walls        |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    | Oversized |
| mp_coop_wall_intro          |  1 |  0  |   1    |   0    |   0    |   0    |   Yes    | Oversized |

The vast majority are black platforms on black surfaces. Of the 3 chambers with white floors, in two Valve uses black tiles. Two times in Coop they use white tiles on a black floor, which is probably just rushed mapping. The only chamber with white tiles on white surfaces is Test Chamber 01, where there are three. However, that chamber is entirely white - in the analogous Portal 1 chambers, black panels are only introduced in Test Chamber 06, and Portal 2 seems to keep to that rule.

So I reckon that the rule seems to be that they should in general always be black.

**Comment by LautaroL20** [comment]
That information look interesting, however the feature of matching the surface´s colour has been present on this item since i create it on it´s day. So, changing this feature just right now could be disruptive for a lot of people who even may like how it was before this recent update. For example, even a Beemod contributor like Luke18033 wanted the pedestal base being able to match the surface´s colour, see issue https://github.com/BEEmod/BEE2-items/issues/1218

I personally would like to keep the marching color feature before the update, but why don't we submit the final veredict of this to the opinion of the community from here and at Discord? I really would like to listen the people´s opinion on this, ff the community likes the pedestal base to be always black as you suggest, i promise i will totally respect their desision.

**Comment by Luke18033** [comment]
Honestly I've got to agree with Lautaro on this. Matching the surface color looks a lot nicer IMO, even if it may not be what Valve did in most of their maps.

**Comment by FrozenDragon0** [comment]
I'll also support the idea of allow the base of the Protrude and Left/Middle/Right Ped Buttons to match attached surface color.
