### ISSUE TITLE
1950's old aperture exit door still has Z-fighting issues.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3416]
![image](https://user-images.githubusercontent.com/18079316/88150957-a5c8fe00-cc34-11ea-828d-5c8ddb6fd8cb.png)

**Comment by Luke18033** [comment]
Yeah, because you put a light strip up there...

**Comment by FrozenDragon0** [comment]
@Luke18033 It's not my map lol it was a workshop one.

**Comment by Luke18033** [comment]
Still just caused by the light strip, there isn't really any good way to deal with this.
