### ISSUE TITLE
[Bug] Co-op spawn room from "BTS Style" is using a Clean version.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#342]
![20160313040722_1](https://cloud.githubusercontent.com/assets/12244376/13730172/eb4c0d0a-e926-11e5-8de6-fff03d756800.jpg)

**Comment by Luke18033** [comment]
Fixed now I think?

**Comment by LautaroL20** [comment]
Yep. But i think it will be for next release.
