### ISSUE TITLE
There is visible nodraw on the Light Strips

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3422]
![image](https://user-images.githubusercontent.com/12244376/88754111-3a02fb80-d134-11ea-935b-92301ce6c10a.jpg)

**Comment by Luke18033** [comment]
The tiling system now allows making these flush with the wall, instead of having to place them `0.0001` units in front. But it looks like they never actually got moved back...

**Comment by FrozenDragon0** [comment]
@Luke18033 I actually noticed the light strips were the same in the version you gave me but I presumed it was a bug with that version that would be fixed on the actual release, Seems not however.

**Comment by LautaroL20** [comment]
Fixed by align them to the surface.
