### ISSUE TITLE
Failing to build map when publishing

### ISSUE THREAD

**Issue by bostonlondon** [BEEmod/BEE2-items#3423]
it builds it just fine when playtesting, but when I go to publish it bring up the build error. 
![image](https://user-images.githubusercontent.com/62776270/88878274-28315f00-d1ed-11ea-903b-44991ee9f428.png)

**Comment by Luke18033** [comment]
There's a [leak](https://developer.valvesoftware.com/wiki/Leak) in your map. Go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.

**Comment by bostonlondon** [comment]
[Preview.zip](https://github.com/BEEmod/BEE2-items/files/5009404/Preview.zip)

**Comment by LautaroL20** [comment]
@bostonlondon - Why did you close the issue?
