### ISSUE TITLE
Whenever I try to download a file, it pauses then at 64mb it says: Forbidden File

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2-items#3426]
Says it all in the title.

**Comment by Luke18033** [comment]
It sounds like your browser is blocking it. Try going to the download manager page, see if you can unblock the file? Either way this is unrelated to BEE itself.

**Comment by PorTalZ101** [comment]
> It sounds like your browser is blocking it. Try going to the download manager page, see if you can unblock the file? Either way this is unrelated to BEE itself.

No option to unblock, just says file forbidden then a button saying ok.

**Comment by Luke18033** [comment]
Again, that's not something we control. Try using another browser maybe.
