### ISSUE TITLE
There is visible nodraw on the indicator panels

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3427]
![image](https://user-images.githubusercontent.com/12244376/89156857-d583da00-d541-11ea-8be9-85d4ef75e187.jpg)

**Comment by LautaroL20** [comment]
I want to fix this but i can´t seem to find where these indicator panels are, anyone knows what´s the name of the instance that has them?

**Comment by Luke18033** [comment]
`instances/bee2/clean/indicator_panel.vmf`, though it looks like this has already been fixed in the dev branch.

**Comment by LautaroL20** [comment]
I do not have idea who could have fixed it and when, but has been fixed indeed. There is not even a commit referecne to this but but i´ll apply the corresponding label regardless.
