### ISSUE TITLE
BTS Large Observation Room Missing Instance

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#343]
![20160313123508_1](https://cloud.githubusercontent.com/assets/12244376/13730185/33acba5e-e927-11e5-8f78-5e63157fa101.jpg)

**Comment by LautaroL20** [comment]
Not sure, but i think that the clean large observation room is also used in BTS Style.

**Comment by TeamSpen210** [comment]
Actually, it's not intended really, I need to implement the observation room.

**Comment by Konclan** [comment]
This is still very much an issue
![20190828205456_1](https://user-images.githubusercontent.com/16567080/63904303-1be9c400-c9d6-11e9-8630-edb9bc4f5a1f.jpg)

**Comment by Luke18033** [comment]
See #1673
