### ISSUE TITLE
Portal 1 coop checkpoint has area_portal problems.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3431]
![image](https://user-images.githubusercontent.com/18079316/89281717-103e5d00-d67d-11ea-868a-1e0c8135d86b.png)

![image](https://user-images.githubusercontent.com/18079316/89281764-23512d00-d67d-11ea-9fe5-28a5f5627cb6.png)

**Comment by Luke18033** [comment]
I can't reproduce this, there might be a leak somewhere else in your map. Go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.

**Comment by FrozenDragon0** [comment]
@Luke18033 I'm still using the dev version, Not the public one due how much of a mess it is. Are you using the public release? If so then I'll close this as it's a dev version problem.

**Comment by Luke18033** [comment]
I'm on the dev version as well, I just fixed a bunch of bugs with the P1 checkpoint and wasn't able to find any issues with this. Can you check for a leak somewhere else in the map, or send me those files so I can?

**Comment by FrozenDragon0** [comment]
No leak. Checkpoint was all that was placed in the map. Checking the checkpoint instance there is a func_areaportal in the entrace/exit door.

**Comment by FrozenDragon0** [comment]
Fixed. Just deleted the area_portal brushes.

**Comment by Luke18033** [comment]
Okay yeah, this was caused by #3444.
