### ISSUE TITLE
Portal 1 cube is slightly floating in the air.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3432]
![image](https://user-images.githubusercontent.com/18079316/89282473-2e588d00-d67e-11ea-9ae1-5217ba03b669.png)

**Comment by Luke18033** [comment]
P2 cubes have this problem as well. It's barely noticeable (we both had to noclip into the floor to see it), not really worth fixing.
![image](https://user-images.githubusercontent.com/19228201/89694802-a5806200-d8c6-11ea-9fd4-84fdaed10e8f.png)

**Comment by FrozenDragon0** [comment]
Eh true I guess BTW @Luke18033 Is that a beta light strip in your screenshot?

**Comment by Luke18033** [comment]
Possibly? I put a bunch of Betapack stuff in my test map back in like 2017.
