### ISSUE TITLE
Vanilla static fizzlers have visible nodraw on the top/bottom

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3433]
![image](https://user-images.githubusercontent.com/12244376/89283004-c9237e00-d622-11ea-8894-748c212741be.jpg)

**Comment by Luke18033** [comment]
I can't reproduce this (#3434 happens instead)

**Comment by LautaroL20** [comment]
> I can't reproduce this

Well, i do. However, for being this the first time, i will prove with solid evidence that my reported issue is correct. Next time, you will be the one that must will prove with evidence that any of my reported issue are wrong before closing it, otherwise, it will remain open.

Here we go... if you open in Hammer the following instances: `fizzler_model.vmf` and `fizzler_model_static.vmf`, you will notice a difference on the appearance between the dynamic and static version of the fizzler model, i made a pair of screenshot which explains all this in detail:

![1 - Fizzler instances](https://user-images.githubusercontent.com/12244376/89713143-2e9da480-d96c-11ea-8833-a23a975e5317.png)

In-game result:

![2 - in-game](https://user-images.githubusercontent.com/12244376/89713146-34938580-d96c-11ea-9b28-c5d0ae3e48d5.jpg)

_____________________________________________________________________________________________________________________

So, the possible reasons of why you were not being able to reproduce this, could be due to:

1 - You still has the "black backing" issue (#3434) which will prevent you from seeing the fizzler void on the static model which is missing the "cover" texture seeing in the first image.
2 - When you were trying to reproducing this, you tested with at least one input connected to the fizzler which will use the dynamic model where it does not have the missing "cover" texture issue. 
3 - You are using "Betapack stuff" and not the vanilla model that has this issue.

_____________________________________

I have figure out the solution for this though. It would be, instead of using `models/props/fizzler.mdl` which has that missing cover texture, use instead `models/bee2/props_ingame/cust_fizz_static.mdl`.

**Comment by Luke18033** [comment]
All of the fizzlers that I tested this with (in normal, standing, and reclined forms) were static with no inputs. They showed the black backing as described in your other issue, and not nodraw as shown here. There's no way this could have happened before your latest commit.

There isn't a Betapack fizzler model, and even if there was it wouldn't replace the vanilla version, so not sure where you're getting that from.

**Comment by LautaroL20** [comment]
Fixing this will cause a new issue, see https://github.com/BEEmod/BEE2-items/issues/3450
