### ISSUE TITLE
Clean/Overgrown vanilla fizzlers still include black backing

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3434]
This also affects the Standing & Reclined fizzlers, screenshot:

![image](https://user-images.githubusercontent.com/12244376/89283785-223fe180-d624-11ea-9435-cded0441a550.jpg)

**Comment by Luke18033** [comment]
Uh, this conflicts with #3433 (which would only happen if that backing didn't generate).

**Comment by Luke18033** [comment]
Doesn't seem to happen with laserfields

**Comment by LautaroL20** [comment]
This only happens with the vanilla fizzler which also affects the reclined & standing fizzlers. Rest of the custom fizzlers does not seems to have this problem.
