### ISSUE TITLE
Reclined Fizzler using old model names in P1, Overgrown, and Old Aperture

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3437]
![Image](https://user-images.githubusercontent.com/12244376/89288743-8666a380-d62c-11ea-9773-a08d1f550c95.jpg)

**Comment by Luke18033** [comment]
The models were moved into a subfolder, the paths must not have been updated on these styles.

**Comment by SCIENTIST2004** [comment]
Duplicate of #3391 ?

**Comment by Luke18033** [comment]
No, but #3438 would be.

**Comment by LautaroL20** [comment]
Now that issue #3391 has a more accurate title, i can consider this to be a duplicate of it.
