### ISSUE TITLE
BTS Ditch Unstyled

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#344]
![ditch](https://cloud.githubusercontent.com/assets/12244376/13730206/9c6be998-e927-11e5-9bfb-f73421e0c694.jpg)

**Comment by Konclan** [comment]
![20190828205853_1](https://user-images.githubusercontent.com/16567080/63904462-ac280900-c9d6-11e9-8337-aabbabf51817.jpg)
