### ISSUE TITLE
Allow placing items on the tiles around Crushers

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3441]
Thin items like light strips, as well as antlines, should be able to be placed on the outer tiles surrounding Crushers. This currently is not possible.
![image](https://user-images.githubusercontent.com/19228201/89356914-ecc2e480-d673-11ea-9b4c-baefe3771b88.png)

**Comment by TeamSpen210** [comment]
We're making them a little bigger, which will make this impossible in the future.
