### ISSUE TITLE
Portal 1 coop exit 4 is missing it's floor.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3444]
![image](https://user-images.githubusercontent.com/18079316/89384298-7801b000-d730-11ea-8d07-8d7eaecbb434.png)

**Comment by Luke18033** [comment]
Well this explains your leak. There's an areaportal there, which wouldn't be getting sealed properly. Might be specific to Tag since I didn't have this issue.

**Comment by Luke18033** [comment]
Ah, it's specific to corridor 4.

**Comment by maxdevgithub** [comment]
even on SP this happens

**Comment by Luke18033** [comment]
That's an entirely unrelated issue.
