### ISSUE TITLE
Portal 1 coop exit 4 radio is using a overgrown radio.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3445]
![image](https://user-images.githubusercontent.com/18079316/89384418-a8494e80-d730-11ea-9cfb-ec1159d6c960.png)

**Comment by Luke18033** [comment]
These radios should really be removed, they don't serve a purpose and are generally just annoying.

**Comment by Luke18033** [comment]
In fact this is made irrelevant by #1338.
