### ISSUE TITLE
Custom Fizzlers: when no input is connected to them, their model frame will look colored

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3449]
Maybe this has been happening since a long time ago and it could even be "intentional", but that is not the point. The point is, in case that this could be intentional, why not make the model frame also look colored when an input is connected to them, too?

![Image](https://user-images.githubusercontent.com/12244376/89727138-87b31a00-d9f8-11ea-9662-3a35c8d2fb5d.jpg)

_____________________________________________________________________________________________

Note: this behavior will happen in almost all fizzlers, except on the Closed Solid Field, Death Fizzler and vanilla Fizzler/Laserfield.

**Comment by Luke18033** [comment]
This doesn't happen for me. I'm not sure how it even could, both of these models use the same material.
![image](https://user-images.githubusercontent.com/19228201/89740247-e64db780-da3b-11ea-896d-1953e8f12b9f.png)

**Comment by LautaroL20** [comment]
Today i have re-tested this issue and it has mysteriously fixed itself. Honestly, i can´t guess what happened but if the issue gets back again, ill re-open it with more information if i can.
