### ISSUE TITLE
P1, 50s, 60s and 80s Ditch causes "Failure To Compile"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3451]
Portal 1:
`Could not open instance file instances/bee2/p1/items/tspen/ditch.vmf`

50s Old Aperture:
`Could not open instance file instances/bee2/50s/items/tspen/ditch/white.vmf`
`Could not open instance file instances/bee2/50s/items/tspen/ditch/black.vmf`

80s Old Aperture:
`Could not open instance file instances/bee2/80s/items/tspen/ditch/common.vmf`

**Comment by LautaroL20** [comment]
This also happens in 50s, 60s and 80s. However, it surprisingly works fine in 70s Old Ap.

**Comment by GiovanH** [comment]
For the majority of these cases, this is a simple issue of the configuration file pointing to the wrong resource. 

The 80s case is interesting, through: there's a configuration template `ditch_80s.cfg` that describes an elaborate system of ditches, but the files (named things like `instances/BEE2/80s/items/tspen/ditch/black_sunk_upper_left.vmf`) are missing.

**Comment by Luke18033** [comment]
TeamSpen probably forgot to include them. Though it sounds like that still needs to be updated for the new tiling system anyway.

**Comment by GiovanH** [comment]
In the meantime, https://github.com/BEEmod/BEE2-items/pull/3471 makes the ditch work in all styles.

**Comment by TeamSpen210** [comment]
Thanks by the way for doing all this work to fix various things I messed up. In all of these the problem is that I didn't push the new copies of the instances - those files are the old versions. A specific white/black instance doesn't make sense now since it could be any combination of those colours.

**Comment by GiovanH** [comment]
I'm just glad I found a handful of issues I knew how to fix, as opposed to the complicated connection issues w/ #3465 & #3467, or even BEE2 geometry stuff like https://github.com/BEEmod/BEE2-items/issues/3452 and #3476. Now hammer instances, that I can fix.
