### ISSUE TITLE
Flip Panels don't respect "Start Reversed" setting.

### ISSUE THREAD

**Issue by RedstoneParadox** [BEEmod/BEE2-items#3453]
In the BEE2 clean style, at least, Flip panels on white walls always start on white even if "Start Reversed" is checked. Flip Panels on black walls also always start on white; after being deactivated for the first time, however, they will always flip from black to white when activated.

**Comment by TeamSpen210** [comment]
Start reversed does something different actually, but it being stuck on white is a bug.
