### ISSUE TITLE
Clean, Overgrown and P1 Faith Plate will render as a "Mysterious white rectangle" when inputs are connected to it

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3455]
![image](https://user-images.githubusercontent.com/12244376/90294212-4b4e4680-de5c-11ea-9948-f60297a60f2c.jpg)

**Comment by Luke18033** [comment]
What *is* that?

**Comment by Luke18033** [comment]
Also why are those signages not self-illuminating...

**Comment by Luke18033** [comment]
Okay, it's the missing texture `bee2/nodraw_glass`. No idea why it's white for you.

**Comment by Luke18033** [comment]
Are you on the dev version? This seems to already be fixed.

**Comment by LautaroL20** [comment]
I am using the public release V 4.37.0 and i did a 100% correct and clean install. I am not sure why this bug would not occur to you too, maybe you are using the dev version? However, even the dev version should still have this issue as i don´t see any commit that fixed it except yours, but your commits were 4 hours ago, so idk.

**Comment by Luke18033** [comment]
I'm on dev, yeah. The release version was missing that texture.

**Comment by RedstoneParadox** [comment]
The white seems to be considered a portalable surface as well.

**Comment by Luke18033** [comment]
That would make sense, materials need to specify that they shouldn't be portalable, which wouldn't happen if the material is missing.
