### ISSUE TITLE
P1, Overgrown and Clean Faith Plates have lighting issues: it looks too dark compared to the large faith plate

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3457]
P1 Faith Plate lighting issue:
![Image](https://user-images.githubusercontent.com/12244376/90295613-d715a200-de5f-11ea-94ec-f7973bdbfdb6.jpg)

Overgrown Faith Plate lighting issue:
![Image](https://user-images.githubusercontent.com/12244376/90295720-1217d580-de60-11ea-8576-7a61e9e9e5c1.jpg)

Clean Faith Plate lighting issue:
![Image](https://user-images.githubusercontent.com/12244376/90295744-1fcd5b00-de60-11ea-9c29-3785375e3a4c.jpg)

**Comment by Luke18033** [comment]
These all use the same custom version of the model, it's probably a bad lighting origin.

@TeamSpen210 Does the custom model change anything besides adding the new skins? If not, it might be a good idea to remake this using Skin Editor so it doesn't have to be recompiled.
