### ISSUE TITLE
Idea: Add a placeable Aperture logo

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2-items#3458]
A placeable Aperture logo, for decoration. It would be two blocks tall and 3 or 4 blocks long.
STYLES
1950s: Aperture Science Innovators logo as seen in chapter 6
1960s: The same
1970s: dirty orange logo, as seen at the end of chapter 6
1980s: Dirty, light grey Aperture Laboratories logo
Clean: Clean, light blue aperture labs logo
Overgrown: Same as clean but dirty and damaged
Portal 1: Clean, light grey aperture labs logo, maybe a little dirty
BTS: Same as Portal 1 but more dirty

It can be hanging from the ceiling, placed in walls and in the floor, but not mid-air.

**Comment by TeamSpen210** [comment]
Why would you want to have an Aperture logo inside a chamber?

**Comment by HeimlichLaboratories** [comment]
Decoration, lol. At least in BTS or "story" levels in that you attempt to make a small storyline you can pretend that the chamber isn't actually a chamber but an outside area. It was just an idea.

**Comment by FrozenDragon0** [comment]
@HeimlichLaboratories If you want Decoration use hammer for that. Puzzlemaker/beemod isn't for story based maps.
