### ISSUE TITLE
Could not open instance file instances/BEE2/50s/sphere_sp/door_frame_black.vmf

### ISSUE THREAD

**Issue by GiovanH** [BEEmod/BEE2-items#3459]
Using Style: 1960s old aperture w/ skybox Sphere interior.

For some reason, the preview.vmf file the puzzlemaker generates has an exit door `func_instance` that points to `instances/BEE2/50s/sphere_sp/door_frame_black.vmf`, which does not exist. 

Running the map from the puzzlemaker seems to work (somehow?), but hammer throws the error.

**Comment by Luke18033** [comment]
Are you using `puzzlemaker_export`? That doesn't work with BEE, that instance is supposed to be swapped out for compiler-generates tiles. Read the FAQ.

**Comment by GiovanH** [comment]
I wasn't using `puzzlemaker_export`, but I *was* accidentally using the `preview.vmf` file that wasn't in `styled/`, my mistake.
