### ISSUE TITLE
Large clean observation room projectedtexture flickers forever

### ISSUE THREAD

**Issue by GiovanH** [BEEmod/BEE2-items#3466]

**Comment by Luke18033** [comment]
Not sure what you're referring to? It should just instantly turn on.

**Comment by GiovanH** [comment]
It turns on, but the "on" state on the directional light source is set to "fluorescent flicker", which can be distracting.

**Comment by Luke18033** [comment]
That would be a bug then, though I'm not sure why I wouldn't have noticed this. Which observation room does it apply to, the small one or the large one?

**Comment by GiovanH** [comment]
If this is definitely a bug I can just make a pull request with a fixed version.

**Comment by TeamSpen210** [comment]
It should be set to that, then be swapped back to normal after a second or so. That gives a flickering effect as it turns on.

**Comment by GiovanH** [comment]
Well that's definitely not happening. Let me take a closer look.

**Comment by GiovanH** [comment]
Okay, https://github.com/BEEmod/BEE2-items/pull/3468 now produces the desired effect and turns the flicker off correctly.

**Comment by Luke18033** [comment]
No, now you're just deleting the projected texture...

**Comment by Luke18033** [comment]
I just set it to start on Normal appearance, the Clean observation room probably shouldn't flicker on.

**Comment by GiovanH** [comment]
> What does the flicker look like? There's a bug that causes a static effect on certain materials hit by projected textures with Nvidia graphics cards, it's not really fixable.

I've done some cursory googling and I can't find what you're referring to here. Can you point me towards what you're talking about?

**Comment by FrozenDragon0** [comment]
@GiovanH This:

![image](https://user-images.githubusercontent.com/18079316/91013392-3753d300-e61a-11ea-9056-b5cc53a3790f.png)

**Comment by GiovanH** [comment]
Oh, yeah, I remember that bug. But that's *very* different from what I'm experiencing. There's no graininess or visual artifacting, just smooth light flickering.
