### ISSUE TITLE
Flip panels always default to white

### ISSUE THREAD

**Issue by GiovanH** [BEEmod/BEE2-items#3467]
Clean flip panels always start as portable and switch "on" to non-portable no matter how the "start reversed" option is set or whether or not the wall they're on is portalable.

**Comment by GiovanH** [comment]
This may be a duplicate of a sub-issue mentioned in https://github.com/BEEmod/BEE2-items/issues/3453, but this isn't specific to the "start reversed" setting.

**Comment by GiovanH** [comment]
When was this fixed? I'm using items from the dev branch.

**Comment by Luke18033** [comment]
It was probably an error in the compiler, so having the updated packages on their own won't do anything.

**Comment by GiovanH** [comment]
You mean https://github.com/BEEmod/BEE2.4? Let me build a fresh copy from dev and see if that fixes it.

**Comment by GiovanH** [comment]
With freshly compiled dev branch BEE and dev branch BEE-items this bug is still present. I don't think it's fixed.

**Comment by GMeister1130** [comment]
This has happened with me as well. I've even tried reinstalling both P2 and BEE2 completely and removing presaved palettes in .appdata folder to no avail.

**Comment by McBaldwins** [comment]
I as well cannot get flip panels to work with a button.  They always start in white "flipped" mode and when you first step on the button it does nothing.  When you walk off the button it will then switch to black and work when on it but on map start it's always flipped.

**Comment by Luke18033** [comment]
Yes, it's a known issue, you don't need to keep saying "it happens for me too" because it'll happen for everyone until 4.38 is out.
