### ISSUE TITLE
Buggy white rectangle around entry door in 60s style

### ISSUE THREAD

**Issue by GiovanH** [BEEmod/BEE2-items#3470]
Possibly an areaportal issue

**Comment by GiovanH** [comment]
On closer inspection, it looks like the 60s `entrance_corridor_6.vmf` is just missing some necessary geometry around the door.

**Comment by LautaroL20** [comment]
If you have some Hammer skills, feel free to fix it via a pull request and we will merge it.

**Comment by LautaroL20** [comment]
Ideally, would be good if Github would create a "closing commit" just after a pull request is merged...

**Comment by LautaroL20** [comment]
This is a duplicate of #747

**Comment by GiovanH** [comment]
> Ideally, would be good if Github would create a "closing commit" just after a pull request is merged...

Pull requests that are marked "Resolves #ISSUE" should automatically close that issue when merged.

**Comment by LautaroL20** [comment]
> Pull requests that are marked "Resolves #ISSUE" should automatically close that issue when merged, so it's odd that it didn't. Maybe it waits until dev is merged into master?

Hope so, although closing a solved issue manually once the next Bee´s update is released, is not be a big problem. However, it is really comfortable when Github closes fixed issues automatically when dev gets merged into master.
