### ISSUE TITLE
Static flat P1 piston platforms do not generate correctly

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3478]
The piston abruptly changes size right where the grating is.
![image](https://user-images.githubusercontent.com/19228201/90442998-630e1080-e090-11ea-94f3-5efe9025f6f9.png)

**Comment by Luke18033** [comment]
Okay, I looked in Hammer and here's what's actually happening:
![image](https://user-images.githubusercontent.com/19228201/116934749-39931600-ac1a-11eb-8b1e-b3e07ffaa717.png)
The instance for the static flat platform is generating at floor level, then a second template-based piston is being added on top? So in the above screenshot you're actually seeing through the nodraw top of the instance piston, the bugged generation is visible from behind:
![image](https://user-images.githubusercontent.com/19228201/116935035-a1e1f780-ac1a-11eb-9b8c-1d678c6911a1.png)
Combined with the other issues that have been reported related to P1 piston panel generation (#3165, #2909, #3611, and now #3774), the whole system seems really messed up. I'm almost tempted to just rip out the entire config for these and replace it with a copy of the Clean config, that seems to work a lot better.

**Comment by TeamSpen210** [comment]
This seems fixed.
