### ISSUE TITLE
Piston platforms with attached faith plate targets do not function correctly

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2-items#3482]
When starting at the lower level, the platform will extend to 1 block below its target position before stopping. It will not retract or move at all after that. ([Video](https://cdn.discordapp.com/attachments/293443637214183424/745150781178642502/DxagGUYmXA.mp4)) Platforms that start at the upper level will also move to 1 block away from the target position, but will then move back to their start position before getting stuck.

**Comment by Luke18033** [comment]
Okay, looks like this is caused by the top piston segment being renamed for some reason. On a 3-block high platform with no target, the top piston segment is named `pist3`. But when a target is added it gets renamed to just `pist`, causing the script to fail detecting it.

**Comment by TeamSpen210** [comment]
Huh, turns out this was a srctools bug: https://github.com/TeamSpen210/srctools/commit/a175d2609438afda02cf56a6feb36ce00ddcffd1
