### ISSUE TITLE
Old 70s stairs are broken/missing

### ISSUE THREAD

**Issue by GiovanH** [BEEmod/BEE2-items#3487]
Editor model shows up as ERROR, compilation fails with `<valve>.vbsp(): Could not open instance file instances/BEE2/70s/items/stairs.vmf`.

**Comment by LautaroL20** [comment]
> Editor model shows up as ERROR, compilation fails with `<valve>.vbsp(): Could not open instance file instances/BEE2/70s/items/stairs.vmf`.

If you have multiple bug reports, please create separate issues instead of combining them. This allows us to individually label the issues, and close them once they are fixed/implemented.

**Comment by GiovanH** [comment]
> > Editor model shows up as ERROR, compilation fails with `<valve>.vbsp(): Could not open instance file instances/BEE2/70s/items/stairs.vmf`.
> 
> If you have multiple bug reports, please create separate issues instead of combining them. This allows us to individually label the issues, and close them once they are fixed/implemented.

I'm not sure what you mean. The issue here was "the 70s stair item isn't configured correctly." Did you want a separate issue for the individual files?

**Comment by Luke18033** [comment]
I'm not really sure what he was referring to either, I guess that you reported both the model being broken and the instance being missing? I think in this case they're related enough that it's fine.

**Comment by LautaroL20** [comment]
> I'm not sure what you mean. The issue here was "the 70s stair item isn't configured correctly." I only put the slash because I wasn't sure which it was. Did you want a separate issue for the individual files?

I mean that for example, you mentioned an editor model issue and a building error, they could be considered to be related but still having them separated would have been also ok.

**Comment by TeamSpen210** [comment]
It’s the same problem really.
