### ISSUE TITLE
Old 70s button doesn't activate outputs

### ISSUE THREAD

**Issue by GiovanH** [BEEmod/BEE2-items#3488]
(The Supercolliding Superbutton, not the pedestal.)

Should there be a tag for issues like this, #3467, and #3465 that are completely game-breaking, to differentiate them from minor bugs?

**Comment by FrozenDragon0** [comment]
Label made enjoy :)

**Comment by GiovanH** [comment]
Beautiful. Can you tag those other issues I mentioned too?

I'd work on them myself, but I still don't understand how BEE/puzzlemaker's IO system works.

**Comment by Luke18033** [comment]
Can you please define "game breaking"? I would consider a game-breaking bug in BEE to be something that makes a style completely unusable, like players not spawning correctly or the exit door not opening. These bugs are not that.

**Comment by Luke18033** [comment]
We have way too many labels already, I'd rather not add even more.

**Comment by GiovanH** [comment]
Well, one of the most basic testing elements is completely non-functional. What would you call it?

**Comment by TeamSpen210** [comment]
This is actually just the weighted variant.
