### ISSUE TITLE
Old Aperture entry and exit doors generate speaker prop outside map

### ISSUE THREAD

**Issue by GiovanH** [BEEmod/BEE2-items#3495]
This issue affects all the Old Aperture styles.

![20200821183739_1](https://user-images.githubusercontent.com/6759280/90942952-692c2600-e3dd-11ea-804d-daa50b7a6b49.jpg)
![2020-08-21 18_36_20-Hammer -  D__SteamLibrary_steamapps_common_Portal 2_sdk_content_maps_styled_prev](https://user-images.githubusercontent.com/6759280/90942957-6c271680-e3dd-11ea-9852-82663443e2fe.png)

**Comment by GiovanH** [comment]
This doesn't seem to apply to other old ap rooms

**Comment by FrozenDragon0** [comment]
Was there only 1 main observation room or did you copy n paste more?

**Comment by TeamSpen210** [comment]
The observation room is unaffected by having multiple copies, it doesn’t use worldportals.

**Comment by GiovanH** [comment]
Just the one, standard test chamber.

**Comment by Luke18033** [comment]
Possibly a compiler issue? The conditions to check for an open space are there.

**Comment by seagemgames** [comment]
Also applies to 70s entry and exit.

**Comment by seagemgames** [comment]
This somewhat duplicates #969
