### ISSUE TITLE
Overgrown coop exit has world portal issues.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3499]
The world portal between the exit door into the exit room has rendering issues depending if the players are on either side of the door.

![image](https://user-images.githubusercontent.com/18079316/91042057-ba3d5380-e643-11ea-835a-8e868fb40805.png)

![image](https://user-images.githubusercontent.com/18079316/91042275-143e1900-e644-11ea-8287-629e65d7bff7.png)

Also the main exit door does not close even though both bots went through to the corridor.

![image](https://user-images.githubusercontent.com/18079316/91042173-ed7fe280-e643-11ea-8e11-c513107fce01.png)

**Comment by Luke18033** [comment]
That first issue would indicate that you have a leak in your map. Try loading the pointfile in Hammer, see what it points to. I've seen that second issue before, it's caused by the trigger being too small I think (it's designed for a corridor that goes straight back, like in Clean).

**Comment by FrozenDragon0** [comment]
Map wasn't mine lol. Was one of my friends.

**Comment by GiovanH** [comment]
Seems to be working correctly on a fresh overgrown map. Is there a specific exit that's causing trouble?

**Comment by Luke18033** [comment]
It's likely caused by another item in the map, not the exit itself. You really need the original map file to debug leaks.
