### ISSUE TITLE
White Faith Plates

### ISSUE THREAD

**Issue by SpaceCore12090** [BEEmod/BEE2-items#3503]
I made a small test chamber with some faith plates and they're appearing white for some odd reason.
![White Faith Plates 1](https://user-images.githubusercontent.com/69298795/91509859-c57fd000-e91e-11ea-9bba-347834eccfb7.jpg)
![White Faith Plates 2](https://user-images.githubusercontent.com/69298795/91509867-ca448400-e91e-11ea-849d-23c4360e9c0e.jpg)

**Comment by Luke18033** [comment]
@LautaroL20 You know you can transfer issues without closing them, right?

**Comment by Luke18033** [comment]
But this is a duplicate of #3455
