### ISSUE TITLE
New Item Idea: Catwalk Fence

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2-items#3507]
The "Fence" item would basically be a catwalk fence, and would change in the different styles. For example, in old aperture, the fence would be brown and rusty. In BTS, it would be a normal metallic fence. This would help a lot in levels with bottomless pits as a decorative item. The fence would occupy one block and its position could be configured like light strips. Fences can only be placed in the floor. Player wouldn't be able to jump over them.
Fences would have a connect feature like catwalks, and could have a diagonal variant. Here is how the connecting system would work:
![PORTAL 2 31_08_2020 13_46_28](https://user-images.githubusercontent.com/68685620/91716691-6c1ed780-eb90-11ea-8640-555d9eb54810.png)
Imagine the catwalks as the fence item. The gap between the two fences would create a diagonal fence.
![PORTAL 2 31_08_2020 13_46_08](https://user-images.githubusercontent.com/68685620/91716798-98d2ef00-eb90-11ea-98e7-3aa0cd99acf5.png)
This would create a 5 block long fence.

**Comment by FrozenDragon0** [comment]
I've suggested this a few years ago and I think the issue is still open.

**Comment by HeimlichLaboratories** [comment]
Damn! I didn't find anything when I searched!

**Comment by Flash4433** [comment]
#1274 ?

**Comment by FrozenDragon0** [comment]
@Flash4433 Yes.

**Comment by HeimlichLaboratories** [comment]
Is this gonna be added though? #1274 was opened in 2016 and we still don't have it.

**Comment by FrozenDragon0** [comment]
@HeimlichLaboratories Yes.. Plenty of issues that were open in 2016 are going to be added, It just takes time.

**Comment by HeimlichLaboratories** [comment]
Hmm. Okay.
