### ISSUE TITLE
Chamberlock is totally broken in all the Old Aperture styles

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3508]
![Image](https://user-images.githubusercontent.com/12244376/91716932-ed617480-eb66-11ea-8868-ed79164107c8.jpg)

**Comment by Luke18033** [comment]
Huh. Seems like the surface tiles aren't being properly removed.

**Comment by Luke18033** [comment]
See #3520, this hasn't been updated for the tiling system yet.
