### ISSUE TITLE
Half Observation Room: A chair is crossing the surface a bit, in a mysterious way.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3510]
![Image](https://user-images.githubusercontent.com/12244376/91872266-0d1f9800-ec4e-11ea-8230-6a9943641582.jpg)
![Image](https://user-images.githubusercontent.com/12244376/91872272-101a8880-ec4e-11ea-9834-4d5bb57bb37b.jpg)

**Comment by Luke18033** [comment]
Not sure how this happened, pretty sure I originally placed it flush with the surface. But does it really matter? You can barely see this without noclipping, 99% of players will never notice.

**Comment by LautaroL20** [comment]
I did not noclip and noticed it fairly easily and without having to force my eyes on that chair. If it would not really matter, i would have not bottered posting it, i think that this should be fixed because otherwise it would unreal in my opinion.
