### ISSUE TITLE
1980s Open observation grate floats in front of the chamber

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3512]
In the 1980s Open enrichment sphere, the worldportal observation grate floats off the side of the chamber slightly. This screenshot is from P2CE, but the map was compiled with BEEmod in the base game so it would happen there as well.
![image](https://user-images.githubusercontent.com/19228201/91908470-73adb180-ec60-11ea-8c96-2f9318f50e6b.png)

**Comment by SCIENTIST2004** [comment]
Portal 2 Community Edition ?
