### ISSUE TITLE
Some Old Aperture issues

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2-items#3516]
Stairs in 80's don't work.
[Photo of screen (just blue error)](https://cdn.discordapp.com/attachments/293435914598744064/752290601986424914/20200906_133403.jpg)

Old Aperture pellet receptors don't send output when activated.
[Another "screenshot"](https://cdn.discordapp.com/attachments/293435914598744064/752291622930219050/20200906_134822.jpg)

And I had some troubles with High Light bridge, but didn't do ss

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will be closed.
