### ISSUE TITLE
Reflection Gel dropper "Bomb" flow is broken

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2-items#3517]
If setting a reflection gel dropper to "Bomb" flow, it will drop the first bomb but won't keep dropping. If you connect a button to it and place a cube, the drop will come out, but you need to take it out and place it again so another bomb will drop.

**Comment by Luke18033** [comment]
This was also fixed in the latest release. Please stop opening issues for things that have already been fixed, this is the third time now.
