### ISSUE TITLE
Alternative Laser Catcher

### ISSUE THREAD

**Issue by Enternamehere1** [BEEmod/BEE2-items#3518]
Add an option or itemvar to the laser catcher to show the alternative model, similar to this picture.
![Prop_laser_catcher](https://user-images.githubusercontent.com/61427943/92409955-6437d800-f13a-11ea-9b1e-c46ff63b69c1.jpg)

**Comment by Luke18033** [comment]
Duplicate of #1499

**Comment by LautaroL20** [comment]
Don't forget to apply the corresponding label after closing an issue.
