### ISSUE TITLE
Finish Tiling System item upgrades

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/BEE2-items#3520]
Big project: rebuild geometry building to occur inside the compiler.

This requires checking every item for compatibility:

**First Valve items:**

- <ITEM_BUTTON_FLOOR:VER_DEFAULT>
    - [x] BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <VALVE_BUTTONS>/items/floor
    - [ ] BEE2_BTS:
      <BEE2_BTS>/items/floor_button
    - [x] BEE2_1950s, BEE2_1960s:
      <BEE2_OLD_AP>/items/floor_recessed
    - [x] BEE2_1970s:
      <BEE2_OLD_AP>/items/floor_flat
    - [x] BEE2_1980s:
      <BEE2_OLD_AP>/items/floor_prototype
    - [x] BEE2_OVERGROWN:
      <BEE2_OVERGROWN>/items/button
    - [x] BEE2_PORTAL_1:
      <BEE2_PORTAL_1>/items/floor_button
- <ITEM_BUTTON_PEDESTAL>
    - [x] BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <VALVE_BUTTONS>/items/ped
    - [ ] BEE2_BTS:
      <BEE2_BTS>/items/ped_button
    - [x] BEE2_1950s, BEE2_1960s:
      <BEE2_OLD_AP>/items/pedestal/50s
    - [x] BEE2_1970s:
      <BEE2_OLD_AP>/items/pedestal/70s
    - [x] BEE2_1980s:
      <BEE2_OLD_AP>/items/pedestal/80s
    - [x] BEE2_OVERGROWN:
      <BEE2_OVERGROWN>/items/ped_button
    - [x] BEE2_PORTAL_1:
      <BEE2_PORTAL_1>/items/ped_button
- <ITEM_COOP_ENTRY_DOOR>
    - [x] BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <BEE2_CLEAN_STYLE>/items/coop_spawn
    - [ ] BEE2_BTS:
      <ITEM_COOP_ENTRY_DOOR:VER_DEFAULT.BEE2_BTS> from <BEE2_CLEAN_STYLE>/items/coop_spawn
    - [x] BEE2_1950s:
      <BEE2_OLD_AP>/items/mandatory/50s/coop_spawn
    - [x] BEE2_1960s:
      <BEE2_OLD_AP>/items/mandatory/60s/coop_spawn
    - [x] BEE2_1970s:
      <BEE2_OLD_AP>/items/mandatory/70s/coop_spawn
    - [x] BEE2_1980s:
      <BEE2_OLD_AP>/items/mandatory/80s/coop_spawn
    - [x] BEE2_OVERGROWN:
      <BEE2_OVERGROWN>/items/mandatory/coop_spawn
    - [x] BEE2_PORTAL_1:
      <BEE2_PORTAL_1>/items/coop_spawn
- <ITEM_COOP_EXIT_DOOR>
    - [x] BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <BEE2_CLEAN_STYLE>/items/coop_exit
    - [ ] BEE2_BTS:
      <BEE2_BTS>/items/mandatory/coop_exit
    - [x] BEE2_1950s:
      <BEE2_OLD_AP>/items/mandatory/50s/coop_exit
    - [x] BEE2_1960s:
      <BEE2_OLD_AP>/items/mandatory/60s/coop_exit
    - [x] BEE2_1970s:
      <BEE2_OLD_AP>/items/mandatory/70s/coop_exit
    - [x] BEE2_1980s:
      <BEE2_OLD_AP>/items/mandatory/80s/coop_exit
    - [x] BEE2_OVERGROWN:
      <BEE2_OVERGROWN>/items/mandatory/coop_exit
    - [x] BEE2_PORTAL_1:
      <BEE2_PORTAL_1>/items/coop_exit

**Then all others**:

- <ITEM_BEE2_CONVEYOR>
    - [x] BEE2_BTS, BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <BEE2_CONVEYOR>/items/conveyor_clean
    - [x] BEE2_PORTAL_1:
      <BEE2_CONVEYOR>/items/conveyor_p1
    - [x] BEE2_OVERGROWN:
      <BEE2_CONVEYOR>/items/conveyor_over
    - [ ] BEE2_1950s, BEE2_1960s, BEE2_1970s, BEE2_1980s:
      <BEE2_CONVEYOR>/items/conveyor_50s
- <ITEM_BEE2_COVERED_ANGLED_PANEL>
    - [x] BEE2_BTS, BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <BEE2_EXTRA_PANELS>/items/covered_pan
    - [x] BEE2_1950s, BEE2_1960s:
      <ITEM_BEE2_COVERED_ANGLED_PANEL:VER_DEFAULT.BEE2_1950s> from <BEE2_EXTRA_PANELS>/items/covered_pan
    - [x] BEE2_1970s:
      <ITEM_BEE2_COVERED_ANGLED_PANEL:VER_DEFAULT.BEE2_1970s> from <ITEM_BEE2_COVERED_ANGLED_PANEL:VER_DEFAULT.BEE2_1950s> from <BEE2_EXTRA_PANELS>/items/covered_pan
    - [x] BEE2_1980s:
      <ITEM_BEE2_COVERED_ANGLED_PANEL:VER_DEFAULT.BEE2_1980s> from <ITEM_BEE2_COVERED_ANGLED_PANEL:VER_DEFAULT.BEE2_1950s> from <BEE2_EXTRA_PANELS>/items/covered_pan
    - [ ] BEE2_OVERGROWN:
      <ITEM_BEE2_COVERED_ANGLED_PANEL:VER_DEFAULT.BEE2_OVERGROWN> from <BEE2_EXTRA_PANELS>/items/covered_pan
    - [x] BEE2_PORTAL_1:
      <ITEM_BEE2_COVERED_ANGLED_PANEL:VER_DEFAULT.BEE2_PORTAL_1> from <BEE2_EXTRA_PANELS>/items/covered_pan
- <ITEM_BEE2_CUTOUT_TILE>
    - [ ] BEE2_1950s, BEE2_1960s, BEE2_1970s, BEE2_1980s, BEE2_BTS, BEE2_CLEAN, BEE2_CLEAN_ORIGINAL, BEE2_PORTAL_1:
      <BEE2_BLOCKS>/items/tile_clean
    - [ ] BEE2_OVERGROWN:
      <BEE2_BLOCKS>/items/tile_over
- <ITEM_BEE2_SCAFFOLD_PIST>
    - [x] BEE2_BTS, BEE2_CLEAN, BEE2_CLEAN_ORIGINAL, BEE2_OVERGROWN:
      <BEE2_UNST_SCAFFOLD>/items/pist_clean
    - [x] BEE2_PORTAL_1:
      <BEE2_UNST_SCAFFOLD>/items/pist_p1
    - [ ] BEE2_1950s, BEE2_1960s:
      <BEE2_UNST_SCAFFOLD>/items/pist_50s
    - [ ] BEE2_1970s, BEE2_1980s:
      <BEE2_UNST_SCAFFOLD>/items/pist_70s
- <ITEM_BEE2_SCAFFOLD_SLOT>
    - [x] BEE2_BTS, BEE2_CLEAN, BEE2_CLEAN_ORIGINAL, BEE2_OVERGROWN:
      <BEE2_UNST_SCAFFOLD>/items/slot_clean
    - [x] BEE2_PORTAL_1:
      <BEE2_UNST_SCAFFOLD>/items/slot_p1
    - [ ] BEE2_1950s, BEE2_1960s, BEE2_1970s, BEE2_1980s:
      <BEE2_UNST_SCAFFOLD>/items/slot_50s
- <ITEM_BEE2_SCAFFOLD_WALL>
    - [x] BEE2_BTS, BEE2_CLEAN, BEE2_CLEAN_ORIGINAL, BEE2_OVERGROWN:
      <BEE2_UNST_SCAFFOLD>/items/wall_clean
    - [x] BEE2_PORTAL_1:
      <BEE2_UNST_SCAFFOLD>/items/wall_p1
    - [ ] BEE2_1950s, BEE2_1960s, BEE2_1970s, BEE2_1980s:
      <BEE2_UNST_SCAFFOLD>/items/wall_50s
- <ITEM_BEE2_SPECIAL_MARKER>
    - [ ] ANY, BEE2_1950s, BEE2_1960s, BEE2_1970s, BEE2_1980s, BEE2_BTS, BEE2_CLEAN, BEE2_CLEAN_ORIGINAL, BEE2_OVERGROWN, BEE2_PORTAL_1:
      <BEE2_BLOCKS>/items/special_marker
- <ITEM_DRAW_BRIDGE>
    - [ ] BEE2_BTS, BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <BEEMOD_1>/items/drawbridge
    - [ ] BEE2_1950s, BEE2_1960s:
      <ITEM_DRAW_BRIDGE:VER_DEFAULT.BEE2_1950s> from <BEEMOD_1>/items/drawbridge
    - [ ] BEE2_1970s:
      <ITEM_DRAW_BRIDGE:VER_DEFAULT.BEE2_1970s> from <ITEM_DRAW_BRIDGE:VER_DEFAULT.BEE2_1950s> from <BEEMOD_1>/items/drawbridge
    - [ ] BEE2_1980s:
      <ITEM_DRAW_BRIDGE:VER_DEFAULT.BEE2_1980s> from <ITEM_DRAW_BRIDGE:VER_DEFAULT.BEE2_1950s> from <BEEMOD_1>/items/drawbridge
    - [ ] BEE2_PORTAL_1:
      <ITEM_DRAW_BRIDGE:VER_DEFAULT.BEE2_PORTAL_1> from <BEEMOD_1>/items/drawbridge
    - [ ] BEE2_OVERGROWN:
      <ITEM_DRAW_BRIDGE:VER_DEFAULT.BEE2_OVERGROWN> from <BEEMOD_1>/items/drawbridge
- <ITEM_LAUTARO_PEDESTAL_BUTTONS>
    - [x] BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <LAUTARO_MODIFIED_PED_BTNS>/items/ped_buttons_clean
    - [x] BEE2_OVERGROWN:
      <ITEM_LAUTARO_PEDESTAL_BUTTONS:VER_DEFAULT.BEE2_OVERGROWN> from <LAUTARO_MODIFIED_PED_BTNS>/items/ped_buttons_clean
    - [x] BEE2_PORTAL_1:
      <ITEM_LAUTARO_PEDESTAL_BUTTONS:VER_DEFAULT.BEE2_PORTAL_1> from <LAUTARO_MODIFIED_PED_BTNS>/items/ped_buttons_clean
    - [x] BEE2_1950s, BEE2_1960s:
      <ITEM_LAUTARO_PEDESTAL_BUTTONS:VER_DEFAULT.BEE2_1950s> from <LAUTARO_MODIFIED_PED_BTNS>/items/ped_buttons_clean
    - [x] BEE2_1970s:
      <ITEM_LAUTARO_PEDESTAL_BUTTONS:VER_DEFAULT.BEE2_1970s> from <LAUTARO_MODIFIED_PED_BTNS>/items/ped_buttons_clean
    - [x] BEE2_1980s:
      <ITEM_LAUTARO_PEDESTAL_BUTTONS:VER_DEFAULT.BEE2_1980s> from <LAUTARO_MODIFIED_PED_BTNS>/items/ped_buttons_clean
    - [ ] BEE2_BTS:
      <ITEM_LAUTARO_PEDESTAL_BUTTONS:VER_DEFAULT.BEE2_BTS> from <LAUTARO_MODIFIED_PED_BTNS>/items/ped_buttons_clean
- <ITEM_LAUTARO_PROTRUDING_PEDESTAL>
    - [x] BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <LAUTARO_MODIFIED_PED_BTN>/items/protruding_clean
    - [x] BEE2_OVERGROWN:
      <ITEM_LAUTARO_PROTRUDING_PEDESTAL:VER_DEFAULT.BEE2_OVERGROWN> from <LAUTARO_MODIFIED_PED_BTN>/items/protruding_clean
    - [x] BEE2_PORTAL_1:
      <ITEM_LAUTARO_PROTRUDING_PEDESTAL:VER_DEFAULT.BEE2_PORTAL_1> from <LAUTARO_MODIFIED_PED_BTN>/items/protruding_clean
    - [x] BEE2_1950s, BEE2_1960s:
      <ITEM_LAUTARO_PROTRUDING_PEDESTAL:VER_DEFAULT.BEE2_1950s> from <LAUTARO_MODIFIED_PED_BTN>/items/protruding_clean
    - [x] BEE2_1970s:
      <ITEM_LAUTARO_PROTRUDING_PEDESTAL:VER_DEFAULT.BEE2_1970s> from <LAUTARO_MODIFIED_PED_BTN>/items/protruding_clean
    - [x] BEE2_1980s:
      <ITEM_LAUTARO_PROTRUDING_PEDESTAL:VER_DEFAULT.BEE2_1980s> from <LAUTARO_MODIFIED_PED_BTN>/items/protruding_clean
    - [ ] BEE2_BTS:
      <ITEM_LAUTARO_PROTRUDING_PEDESTAL:VER_DEFAULT.BEE2_BTS> from <LAUTARO_MODIFIED_PED_BTN>/items/protruding_clean
- <ITEM_LAUTARO_RECLINED_FIZZLER>
    - [x] BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <LAUTARO_STANDING_RECLINED_FIZZLERS>/items/reclined_fizzler
    - [ ] BEE2_OVERGROWN:
      <LAUTARO_STANDING_RECLINED_FIZZLERS>/items/reclined_fizzler_over
    - [ ] BEE2_PORTAL_1:
      <LAUTARO_STANDING_RECLINED_FIZZLERS>/items/reclined_fizzler_p1
    - [ ] BEE2_1950s, BEE2_1960s, BEE2_1970s:
      <LAUTARO_STANDING_RECLINED_FIZZLERS>/items/reclined_fizzler_50s
    - [ ] BEE2_1980s:
      <LAUTARO_STANDING_RECLINED_FIZZLERS>/items/reclined_fizzler_80s
    - [ ] BEE2_BTS:
      <LAUTARO_STANDING_RECLINED_FIZZLERS>/items/reclined_fizzler_bts
- <ITEM_LAUTARO_STANDING_FIZZLER>
    - [x] BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <LAUTARO_STANDING_RECLINED_FIZZLERS>/items/standing_fizzler
    - [ ] BEE2_OVERGROWN:
      <LAUTARO_STANDING_RECLINED_FIZZLERS>/items/standing_fizzler_over
    - [ ] BEE2_PORTAL_1:
      <LAUTARO_STANDING_RECLINED_FIZZLERS>/items/standing_fizzler_p1
    - [ ] BEE2_1950s, BEE2_1960s, BEE2_1970s:
      <LAUTARO_STANDING_RECLINED_FIZZLERS>/items/standing_fizzler_50s
    - [ ] BEE2_1980s:
      <LAUTARO_STANDING_RECLINED_FIZZLERS>/items/standing_fizzler_80s
    - [ ] BEE2_BTS:
      <LAUTARO_STANDING_RECLINED_FIZZLERS>/items/standing_fizzler_bts
- <ITEM_TSPEN_BUTTON_PEDESTAL_RETRACT>
    - [x] BEE2_BTS, BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <TSPEN_RET_BUTTON>/items/ped_clean
    - [x] BEE2_OVERGROWN:
      <TSPEN_RET_BUTTON>/items/ped_over
    - [x] BEE2_PORTAL_1:
      <TSPEN_RET_BUTTON>/items/ped_p1
    - [ ] BEE2_1950s, BEE2_1960s, BEE2_1970s, BEE2_1980s:
      <TSPEN_RET_BUTTON>/items/ped_50s
- <ITEM_TSPEN_DITCH>
    - [x] BEE2_BTS, BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <TSPEN_DITCH>/items/clean
    - [ ] BEE2_OVERGROWN:
      <ITEM_TSPEN_DITCH:VER_DEFAULT.BEE2_OVERGROWN> from <TSPEN_DITCH>/items/clean
    - [x] BEE2_1950s, BEE2_1960s:
      <TSPEN_DITCH>/items/50s
    - [x] BEE2_1970s:
      <TSPEN_DITCH>/items/70s
    - [x] BEE2_1980s:
      <TSPEN_DITCH>/items/80s
    - [x] BEE2_PORTAL_1:
      <TSPEN_DITCH>/items/p1
- <ITEM_TSPEN_SP_CHECKPOINT>
    - [x] BEE2_BTS, BEE2_CLEAN, BEE2_CLEAN_ORIGINAL:
      <ITEM_TSPEN_SP_CHECKPOINT:VER_DEFAULT.BEE2_CLEAN> from <TSPEN_CHECKPOINT>/items/sp_check
    - [x] BEE2_PORTAL_1:
      <ITEM_TSPEN_SP_CHECKPOINT:VER_DEFAULT.BEE2_PORTAL_1> from <TSPEN_CHECKPOINT>/items/sp_check
    - [ ] BEE2_1950s, BEE2_1960s:
      <ITEM_TSPEN_SP_CHECKPOINT:VER_DEFAULT.BEE2_1950s> from <TSPEN_CHECKPOINT>/items/sp_check
    - [ ] BEE2_1970s:
      <ITEM_TSPEN_SP_CHECKPOINT:VER_DEFAULT.BEE2_1970s> from <ITEM_TSPEN_SP_CHECKPOINT:VER_DEFAULT.BEE2_1950s> from <TSPEN_CHECKPOINT>/items/sp_check
    - [ ] BEE2_1980s:
      <ITEM_TSPEN_SP_CHECKPOINT:VER_DEFAULT.BEE2_1980s> from <TSPEN_CHECKPOINT>/items/sp_check
    - [x] BEE2_OVERGROWN:
      <ITEM_TSPEN_SP_CHECKPOINT:VER_DEFAULT.BEE2_OVERGROWN> from <TSPEN_CHECKPOINT>/items/sp_check
- <ITEM_VENT>
    - [ ] BEE2_BTS, BEE2_CLEAN, BEE2_CLEAN_ORIGINAL, BEE2_OVERGROWN, BEE2_PORTAL_1:
      <BEEMOD_1>/items/vent
    - [ ] BEE2_1950s, BEE2_1960s, BEE2_1970s, BEE2_1980s:
      <BEEMOD_1>/items/vent_50s

*Luke: Trimmed this down to remove items that were updated in every style as of 4.37.0. Pre-edited version can be found [here](https://github.com/BEEmod/BEE2.4/files/5086780/ts_geometry_system.txt)*

**Comment by Luke18033** [comment]
Doesn't seem like this issue is really being used anymore, I think a lot of these things have now been updated. If anything is still broken a separate issue can be opened for it.
