### ISSUE TITLE
Standing Fizzler shows the outdated combined name on the in-game palette of when it were still using button_type

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3526]
![image](https://user-images.githubusercontent.com/12244376/93447748-2446c280-f8a9-11ea-887c-85be19ff04c3.jpg)

**Comment by Luke18033** [comment]
I don't think it really needs to show the sizes in the combined name at all... Just make it "standing fizzler", that should be fine.

**Comment by LautaroL20** [comment]
I never suggested that it must show the sizes in the combined name, just pointed out that it were still using the same combined name as it was before the item got the cubetype upgrade, thats all. Respect to using "Standing Fizzler" as the new combined name, i am fine with that.

**Comment by Luke18033** [comment]
Seems fixed
