### ISSUE TITLE
Corrupted zip file

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2-items#3527]
The _BEE2_4.37.0_packages.zip_ file is badly compressed. In result, custom items don't show in the editor.

**Comment by Luke18033** [comment]
It is not corrupted, it works perfectly fine for everyone else. Do people ever consider that?

**Comment by Luke18033** [comment]
How did you install it?

**Comment by Flash4433** [comment]
You might want to follow this guide. https://github.com/BEEmod/BEE2.4/wiki/How-to-Install-BEE2.4

**Comment by Thedoczek** [comment]
I downloaded this, and unpack to the main folder (BEE2-version-win.zip).
First unpacked with WinRAR or MS File Explorer. It worked, and now doesn't. I installed 7Zip to fix that, but don't work too.

**Comment by Thedoczek** [comment]
![Screenshot](https://user-images.githubusercontent.com/69758777/93685946-50ce2a80-fab3-11ea-8047-a8ffd13eca85.png)

> Windows cannot complete the extraction.
> Cannot open the target file

Everything works fine with folder from `BEEmod/BEE2.4`

**Comment by Luke18033** [comment]
What exactly are you trying to do? You don't need to extract the individual package zips.

**Comment by Luke18033** [comment]
We really need an auto-install system for these...

**Comment by Thedoczek** [comment]
> What exactly are you trying to do? You don't need to extract the individual package zips.

I installed this before, so I know how to do that.
I want to extract `BEE2-4.37.0-packages.zip`

**Comment by Luke18033** [comment]
Yes, and it looks like you already did that? I don't see `.zip` anywhere in this path.
![image](https://user-images.githubusercontent.com/19228201/93686583-04133100-fa6c-11ea-80ff-5bb2382f5f96.png)

**Comment by Thedoczek** [comment]
![obraz](https://user-images.githubusercontent.com/69758777/93686682-1ca93880-fab8-11ea-8712-e7c326195c87.png)

**Comment by Luke18033** [comment]
Oh, you have file extensions disabled. Assuming `BEE2_4.37.0_win` isn't a ZIP, that should work fine. What exactly happens when you try to launch it?

**Comment by Thedoczek** [comment]
Bee mod app works fine, the problem is here:
![obraz](https://user-images.githubusercontent.com/69758777/93686973-3186cb80-faba-11ea-8b1f-7b4625454459.png)

**Comment by Luke18033** [comment]
That's completely unrelated to the packages zip. Go to `File > Options > Development` in BEE, make sure `Preserve Game Directories` is off, then export again.

**Comment by Thedoczek** [comment]
Yes, I was turning it on... Thanks and sorry!

**Comment by Luke18033** [comment]
I need to change the description of that option, the current one is kind of misleading.
