### ISSUE TITLE
Suggestion: Adding possiblity to angle the lightbridge

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2-items#3529]
Like in portal Stories: Mel.
Using inf time property would be normal bridge.
Using 3s would be 30deg, 4s would be 40deg etc, up to 8.
Using Start Reversed would be angling in different way.
![obraz](https://user-images.githubusercontent.com/69758777/93707967-068c8e00-fb33-11ea-9dd6-83ea0920dcdb.png)

**Comment by FrozenDragon0** [comment]
https://github.com/BEEmod/BEE2-items/issues/95 Already going to be reimplemented.

**Comment by FrozenDragon0** [comment]
https://github.com/BEEmod/BEE2-items/issues/95
