### ISSUE TITLE
Portal 1 door has a glitchy bottom

### ISSUE THREAD

**Issue by maxdevgithub** [BEEmod/BEE2-items#3530]
![glich](https://user-images.githubusercontent.com/58821795/93760971-a9b5d400-fc15-11ea-9a38-da9bcfaceb00.PNG)
Bottom of P1 door is glitchy and i just noticed

**Comment by FrozenDragon0** [comment]
Already reported: https://github.com/BEEmod/BEE2-items/issues/3444

**Comment by LautaroL20** [comment]
This is fixed in the next release.

**Comment by Luke18033** [comment]
Uh no, this is referring to the BEE Door item which nodraws the floor tiles below it, so this is a duplicate of #3448.
