### ISSUE TITLE
Reclined fizzler goes missing when two of them are connected to the same fizzler

### ISSUE THREAD

**Issue by NeoKat75** [BEEmod/BEE2-items#3533]
Reclined fizzler sometimes goes missing, seems to be random. A death laserfield is connected to this one. [Picture.](https://imgur.com/a/SoPEDuB)

**EDIT:** This happens when you connect the same laserfield to multiple reclined fizzlers.

**Comment by Thedoczek** [comment]
Because one fizzler is one fizzler

Just create two laserfields and clost this ticket

**Comment by Luke18033** [comment]
Duplicate of BEEmod/BEE2.4#1343
