### ISSUE TITLE
Pin this to pinned issues: How to fix "missing textures":

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2-items#3536]
In order to solve this issue, you will have to do the following:

1. First, click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.
2. Make sure any antivirus software is not blocking the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Otherwise, this can cause a compile error when building your puzzle.
3. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.
4. Wait 1 minute while BEEmod resources are removed from Portal 2.
5. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.
6. Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4.
   Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).
7. Again, uncheck `Preserve Game Directories` if it is checked.
8. Select a palette and style, and export it to the game as normal.
9. Make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.
10. Happy mapmaking!

**Comment by Thedoczek** [comment]
Please pin this so they will be able to not ask.

**Comment by Luke18033** [comment]
This is not what issues are for. There's already a wiki page for this, which is linked in the FAQ among other places.
