### ISSUE TITLE
Adhesive Gel

### ISSUE THREAD

**Issue by CMSEv7** [BEEmod/BEE2-items#3537]
I think we can add the adhesive gel to the game. It was an ancient project of Valve. The project was abandoned because it was causing nausea to testers.

**Comment by FrozenDragon0** [comment]
Not possible in the puzzlemaker with the way people have remade it.

**Comment by Luke18033** [comment]
Adhesion Gel was never fully implemented in any released version of the game, and the tricks used to make it functional don't work in the Puzzlemaker. See the [FAQ question](https://github.com/BEEmod/BEE2-items/wiki/FAQ#can-you-add-adhesion-gelsome-other-custom-gel-to-bee24).

**Comment by CMSEv7** [comment]
Ah.
