### ISSUE TITLE
Portal 1 Style: A "Mysterious" Dr.Kleiner voice line starts playing when previeweing the map

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#354]
CSoundEmitterSystemBase::GetParametersForSound:  No such sound BEE2.P1.elev_stop
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound BEE2.p1.panel_turn
CSoundEmitterSystemBase::GetParametersForSound:  No such sound BEE2.p1.panel_turn
Updating sound cache [9174 entries]
Found 8789 sound files on disk
Updated 0 out of 8789 cached files [1928.820 msec]
Redownloading all lightmaps
[Sound] S_StartSound(): Failed to load sound 'doors\doormove1.wav'. File is missing from disk/repository.
SV_StartSound: BEE2/p1/panel_turn.wav not precached (0)
SV_StartSound: BEE2/p1/panel_turn.wav not precached (0)
EmitAmbientSound:  sound not precached: BEE2/p1/wall_move5.wav
EmitAmbientSound:  sound not precached: BEE2/p1/wall_move5.wav
EmitAmbientSound:  sound not precached: BEE2/p1/wall_move5.wav

**Comment by MrKrunk** [comment]
What you're referring to isn't Wheatley's voice. It's the error sound for when another sound is missing. It's Kleiner saying, "Oh fiddlesticks, what now?"

**Comment by LautaroL20** [comment]
@TeamSpen210 - I forgot to add a detail to the bug report, this happens in SP mode having or not having ennabled the "Add voice lines" option from the Bee 2.4 "Exporting options". This was my configuration when ive experienced this bug:

![gta](https://cloud.githubusercontent.com/assets/12244376/13737306/e6aa1fca-e99a-11e5-9a55-7cced399a82a.png)

**Comment by LautaroL20** [comment]
Edited: Changed the title from "A mysterious Wheatly voice line" to "A Mysterious DR. Kleiner voice line".

**Comment by TeamSpen210** [comment]
This is probably caused by a missing copoy of a ported Portal 1 elevator sound. Dr Kleiner's "fiddlesticks" line plays if a sound file is not found, it's nothing to do with actual voicelines.

**Comment by ZombiePwner1** [comment]
This only sometimes happens I play tested a map 2 times and the 1st one I heard the voice but the 2nd time I didn't hear it.

**Comment by Byzarru** [comment]
Bump bump, this still needs to be fixed.

**Comment by Luke18033** [comment]
Console error from @Byzarru:

```
CSoundEmitterSystemBase::GetParametersForSound:  No such sound BEE2.P1.elev_stop
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound BEE2.p1.panel_turn
CSoundEmitterSystemBase::GetParametersForSound:  No such sound BEE2.p1.panel_turn
Updating sound cache [9174 entries]
Found 8789 sound files on disk
Updated 0 out of 8789 cached files [1928.820 msec]
Redownloading all lightmaps
[Sound] S_StartSound(): Failed to load sound 'doors\doormove1.wav'. File is missing from disk/repository.
SV_StartSound: BEE2/p1/panel_turn.wav not precached (0)
SV_StartSound: BEE2/p1/panel_turn.wav not precached (0)
EmitAmbientSound:  sound not precached: BEE2/p1/wall_move5.wav
EmitAmbientSound:  sound not precached: BEE2/p1/wall_move5.wav
EmitAmbientSound:  sound not precached: BEE2/p1/wall_move5.wav
```

**Comment by LautaroL20** [comment]
Just a small info on this is that it only happens when previeweing the map. The final Workshop publish doesn´t have this bug.

**Comment by Byzarru** [comment]
I may be wrong, but I've had this issue when publishing, too. You hear "oh fiddlesticks" one time and every subsequent time there is no problem.

**Comment by Byzarru** [comment]
This is still a problem in PR25, after an export.

**Comment by Byzarru** [comment]
So this should be closed, then, yeah?

**Comment by LautaroL20** [comment]
@Byzarru - Well, i don´t see the commit anywere so, not.

**Comment by TeamSpen210** [comment]
I figured out the issue for this.

**Comment by hop193** [comment]
Wait, if it's fixed for next release, shouldn't this be closed?

**Comment by Luke18033** [comment]
It'll be closed automatically.

**Comment by LautaroL20** [comment]
Issues would only close automatically if a "Commit" was associated to the issue, wich is clearly not the case here. So, once PRL25 comes out, someone would have to close this manually.

**Comment by Luke18033** [comment]
This is the first issue with "mysterious" in the title I think.

**Comment by Konclan** [comment]
neat

**Comment by LautaroL20** [comment]
@Luke18033 - What is the purpose on commenting into an already closed issue? I don´t see the point unless you have something important to contribute with the original issue itself...

**Comment by Luke18033** [comment]
I don't know, why do you care? I was just pointing out that this is the origin of the "mysterious" joke.

**Comment by LautaroL20** [comment]
I thought you were trying to being sarcastic with your first comment and i´ve reacted kinda negatively, but now i think i misunderstood your comment, sorry. So, yeah, this was probably the first issue with the "mysterious" word in the title.
