### ISSUE TITLE
P1 Signage frame is rotated 90 degrees.

### ISSUE THREAD

**Issue by maxdevgithub** [BEEmod/BEE2-items#3540]
**BEE2 version:** 4.37.0

**Description of the bug:** P1 Signage frame is rotated 90 degrees. Related to the signage item

**Expected behavior:** Something like this
![Portal-large-51](https://user-images.githubusercontent.com/58821795/95653904-b20e7a00-0b04-11eb-88ab-15f6f7a0df74.jpg)

**Steps to reproduce:** Place the signage item in editor and play the level

**Additional information:**
![Inkedpreview0000_LI](https://user-images.githubusercontent.com/58821795/95653753-b9815380-0b03-11eb-8c31-6bd00ede89ad.jpg)

**Comment by maxdevgithub** [comment]
As i cannot add labels i can say only P1 Style has signage frames

**Comment by Luke18033** [comment]
That's broken. Really though I don't think the frames should even be there, the original P1 really only uses them for the exit signs.

**Comment by maxdevgithub** [comment]
I remember you said that unstyled connection signage looked styled in P1 so maybe possibly remove the frame

**Comment by maxdevgithub** [comment]
> I remember you said that unstyled connection signage looked styled in P1 so maybe remove the frame

https://github.com/BEEmod/BEE2-items/issues/1460

**Comment by TeamSpen210** [comment]
I did remove them from the sign items, though. Why are they reappearing?

**Comment by maxdevgithub** [comment]
> I did remove them from the sign items, though. Why are they reappearing?

You did remove? That's weird

**Comment by maxdevgithub** [comment]
I guess there is a single signage frame therefore you possibly used 2 signage frames
