### ISSUE TITLE
1980's cubes in funells are passing trough grates

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2-items#3541]
**BEE2 version:** 4.37.0

**Description of the bug:** Self explaination. Seen on screenshots

**Expected behavior:** Fix that

**Additional information:**
- Screenshots:
![2020-10-10 (3)](https://user-images.githubusercontent.com/69758777/95663672-852c8800-0b41-11eb-849b-537944dbd1ad.png)
![2020-10-10 (5)](https://user-images.githubusercontent.com/69758777/95663674-88277880-0b41-11eb-9b33-bffe308ade4f.png)

**Comment by maxdevgithub** [comment]
That sure is weird

**Comment by Luke18033** [comment]
Duplicate of #3264
