### ISSUE TITLE
Icons in old aperture when changing faith plates to mechanical

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2-items#3542]
**Description of the feature:** That's not a bug, not a feature... When you change faith plates to mechanical, the small FP changes its icon from gel to plate. But big faith plate is still a gel (only on icons, I think). Just a simple oversight.

**Comment by TeamSpen210** [comment]
Did you change the item version on the big plate too? They're not linked together, both can be changed independently.

**Comment by Thedoczek** [comment]
I see only one button:
![obraz](https://user-images.githubusercontent.com/69758777/95674992-37049c80-0bb4-11eb-80d1-be19849a107c.png)

**Comment by TeamSpen210** [comment]
Rightclick on the large plate item.

**Comment by Thedoczek** [comment]
Lol, nice

**Comment by Thedoczek** [comment]
Are there alternate versions of more things?
