### ISSUE TITLE
Angled Angled Panel

### ISSUE THREAD

**Issue by CMSEv7** [BEEmod/BEE2-items#3543]
I had a problem in one of my maps, it was about angled panels. I wanted to add something to the game. It will be an angled panel for angles like in this  
![20201009205845_1](https://user-images.githubusercontent.com/72353799/95665990-5e5f5900-0b23-11eb-9a15-018a9efff5f1.jpg)

**Comment by TeamSpen210** [comment]
That's not really easily doable, since it'd require panel surfaces that are triangular and otherwise strangely intersecting. You can use angled block items for that though.
