### ISSUE TITLE
Maybe add a way to expand the pallette?

### ISSUE THREAD

**Issue by freedomtalesans** [BEEmod/BEE2-items#3545]
It would be useful for creating maps.

**Comment by Luke18033** [comment]
The palette size is hardcoded into the game. If we could change this, TeamSpen would have done so long ago.

**Comment by freedomtalesans** [comment]
Okay sry.
But, you could add a way to compress mutiple items into one, maybe.

**Comment by Luke18033** [comment]
Please read the FAQ...that ability is extremely limited, items need to share the exact same properties and editor collisions to be able to be combined.

**Comment by freedomtalesans** [comment]
well, the light strips can easily be combined, and maybe the portal pedistals could be combined as well? they're really similar to each other.

**Comment by Luke18033** [comment]
Those items already are combined.

**Comment by freedomtalesans** [comment]
well, not their images.

**Comment by freedomtalesans** [comment]
if im wrong im sorry for wasting your time.

**Comment by maxdevgithub** [comment]
> well, not their images.

Indeed, Light Strips should have a combined image

**Comment by freedomtalesans** [comment]
Also, maybe you could potentially combine all the logic gates? im not sure though. the visible ones, though, should have a combined image.

**Comment by Luke18033** [comment]
What are you talking about? All of the things you have suggested are already combined. You just put one of them on the palette, then it has a type dropdown that can be used to switch to the other variants.

**Comment by freedomtalesans** [comment]
i mean the images.

**Comment by freedomtalesans** [comment]
also, the pedistals?

**Comment by freedomtalesans** [comment]
also, i thought of an idea that may allow pallet "expansion"

**Comment by freedomtalesans** [comment]
the first slot would be the page number, the second a <--, and the third a -->

**Comment by Luke18033** [comment]
That's not how it works, we can't change the palette items in each slot without restarting the game. Again, if there were any sort of way to do this it would have been implemented long ago.

**Comment by freedomtalesans** [comment]
the doors!

**Comment by freedomtalesans** [comment]
cOMBINE the doors!

**Comment by FrozenDragon0** [comment]
What do you mean combine the doors?

**Comment by maxdevgithub** [comment]
> What do you mean combine the doors?

Exactly, there is only 1 door

**Comment by maxdevgithub** [comment]
And a chamberlock

**Comment by freedomtalesans** [comment]
No, you could add different themed doors.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Konclan** [comment]
Different doors is a different issue. Also make sure to read the [FAQ](https://github.com/BEEmod/BEE2-items/wiki/FAQ)
