### ISSUE TITLE
Idea for two new Funnels

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2-items#3547]
### Description of the items:
* **Physics Funnel** (_Aperture Science Physics Excursion Funnel_):
  * Can transport only cubes, turrets etc., but can't transport test subjects
  * When going normal way, it's gray. When it's reversed, it's dark red
* **Lifeform Funnel** (_Aperture Sciense Lifeform Excursion Funnel_):
  * Can transport only test sublects, but can't transport cubes, turrets etc.
  * When going normal way, it's green. When it's reversed, it's purple

### Item options:
Same as in normal Funnel.

### Additional information:
You may put it into one item. It would then be selected by _Button type_ variable.

**Comment by Luke18033** [comment]
We can't really modify the functionality of funnels, and I'm not sure how useful these would be anyway.
