### ISSUE TITLE
Cube Dropper Bug

### ISSUE THREAD

**Issue by GamerXD54Labs** [BEEmod/BEE2-items#3549]
### (Bee2.4 ver 37)
There is a bug (Promptly with the reflection cube dropper) where the cube would get stuck on the iris hatch of the dropper. Is there a potential fix for this ?  
![Portal 2 Beemod cube dropper error](https://user-images.githubusercontent.com/73716416/97744497-b9022a00-1abd-11eb-8716-8430a6836181.png)

**Comment by Luke18033** [comment]
Yeah, it's a known bug. We really need to put a fix out.
