### ISSUE TITLE
[Suggestion] Remove the background texture behind Portal 1 antlines

### ISSUE THREAD

**Issue by NeoKat75** [BEEmod/BEE2-items#3550]
The result will end up looking a bit closer to the Portal 2 antlines, with no background, but small dots and different Aperture logo texture. Sacrificing a little bit of faithfulness for making these antlines look ten million times better sounds like a fair trade to me. Possibly could be an optional styleVar?
![image](https://user-images.githubusercontent.com/48127893/97914842-92641d80-1d61-11eb-80aa-3bf1e8d45687.png)

**Comment by TeamSpen210** [comment]
I can't do that, for technical reasons.
