### ISSUE TITLE
[New Item] Magnetic Cube

### ISSUE THREAD

**Issue by maxdevgithub** [BEEmod/BEE2-items#3552]
**Description of the item:** Cube can pull objects towards it. You can also make a repulsion cube which is opposite of magnetic cube. Basically a portable BP Magnet

**Item options:** Start reversed will make it repulsive

**Source:** https://steamcommunity.com/sharedfiles/filedetails/?id=2273439552

**Additional information:** Maybe ask the creator before making it, if creator does not want it on BEEMOD then close this issue

**Comment by maxdevgithub** [comment]
I could make concept art for P1, Old. Ap., BTS

**Comment by maxdevgithub** [comment]
Although P1 style could be same as P2

**Comment by Thedoczek** [comment]
If there is Magnetic Cube, maybe also add Magnetic Panels, Magnetic Buttons and No Gravity switchers?

**Comment by FrozenDragon0** [comment]
@Thedoczek Make separate issues for those.

**Comment by maxdevgithub** [comment]
> If there is Magnetic Cube, maybe also add Magnetic Panels, Magnetic Buttons and No Gravity switchers?

All Magnetic demo items are interesting but some may be recreated with other items such as BP Magnet and Weighted Button

**Comment by Konclan** [comment]
UCP
