### ISSUE TITLE
Standing Fizzler does not react to inputs at all

### ISSUE THREAD

**Issue by NeoKat75** [BEEmod/BEE2-items#3553]
Might be exclusive to Portal 1 style? No idea.
![image](https://user-images.githubusercontent.com/48127893/98234498-9a92a780-1f71-11eb-99f2-87a45159c258.png)
![image](https://user-images.githubusercontent.com/48127893/98234581-b7c77600-1f71-11eb-9475-65418d7cd93f.png)
(Also: particles from fields like P1 fizzlers and paint fizzlers go through thin walls. Dunno if fixable, just thought I'd point it out.)

**Comment by FrozenDragon0** [comment]
The particles I don't think can be fixed since packing custom particles into maps is not possible.

**Comment by TeamSpen210** [comment]
Indeed, the particles stick out.

**Comment by FrozenDragon0** [comment]
@TeamSpen210 Is there any way to fix the particle issue?

**Comment by TeamSpen210** [comment]
Not really no.

**Comment by seagemgames** [comment]
This is only limited to P1.
