### ISSUE TITLE
Physics repulsion fields are invisible for those without BEE2.

### ISSUE THREAD

**Issue by PieCreeper12** [BEEmod/BEE2-items#3555]
I had somebody do a blind playthrough of my test chamber involving the physics repulsion field and they got confused because it appeared invisible. This is weird because nobody has had this issue before. Is this a bug with the new version of BEE2 or what?

Playthrough: https://www.youtube.com/watch?v=xnIFfIU0mTE

**Edit:** The player actually had BEE2 installed. Not sure why this occurred.

**Comment by Luke18033** [comment]
Seems like an issue with the `material_modify_control`s used for the animations on these. Not sure why they wouldn't work, are you able to reproduce the bug?

**Comment by Luke18033** [comment]
OH, did the person playing the map have BEE2 v4.36.1 or earlier installed? The way the animations work was changed in 4.37 and might break if you have the old materials.

**Comment by Luke18033** [comment]
Closing for lack of info
