### ISSUE TITLE
Pneumatic Diversity Vent Selection is Bugged

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#356]
it becomes hard to delete this item through the right-click menu, and also has terrible inverted levitation position when the map is builded:

![pneumatic](https://cloud.githubusercontent.com/assets/12244376/13730710/62ed3b46-e935-11e5-873a-0f3cd9887b4c.jpg)

**Comment by TeamSpen210** [comment]
The selection is a bug, the positioning is not. Making the anchors on the tube part ensures that the tube is attached to something, as well as allowing it to take up space in the wall for cubes to get sucked up into.

**Comment by LautaroL20** [comment]
This was fixed since a long time ago already.
