### ISSUE TITLE
Debris Item

### ISSUE THREAD

**Issue by GrayGravity** [BEEmod/BEE2-items#3560]
I was wondering if an item that has a debris or foliage model to go along with the overgrown style could be added.

It would work like this:
It is an item similar to cutout tiles, but when placed it has a debris or foliage model. The models would vary, so it wouldn't be the same model every time you place it. Maybe add a cube/button type option where you can choose if you want a foliage model or a trash model.

This would help a lot with overgrown styles, as right now it does not look very good.
Sorry if this suggestion is bad or my writing is trash, I'm not that good at making suggestions.

**Comment by maxdevgithub** [comment]
Wasn't decoration feature coming soon (hopefully) feature just that? You can also use QQL by Baguettery ( https://github.com/koerismo/QOL-BEE/releases/latest )

**Comment by FrozenDragon0** [comment]
A decoration feature has already been talked about. The idea is to have it automatically generate debris/vegetation. https://github.com/BEEmod/BEE2-items/issues/468
