### ISSUE TITLE
Gravity Cubes

### ISSUE THREAD

**Issue by PieCreeper12** [BEEmod/BEE2-items#3564]
A gravity cube is a cube that can invert its gravity. It can either go up or down. There would be a way to switch its gravity. A button attached to the cube dropper can change its polarity to alter its gravity. Starting the cube dropper on reverse will make it start with inverted gravity. Cube droppers can be placed on the floor so that it can release cubes with inverted gravity.

**Comment by DrMeepster** [comment]
Seems possible to implement. Gravity trigger around the cube that only effects the cube should work

**Comment by Thedoczek** [comment]
Maybe also cubes which will go to the side?
I mean gravity will be on the wall
And then dropper is on the opposite wall

**Comment by DrMeepster** [comment]
That I think is impossible.

**Comment by Luke18033** [comment]
No, you can rotate physics objects' gravity in any direction using `trigger_vphysics_motion`.

**Comment by Konclan** [comment]
UCP
