### ISSUE TITLE
Wheatley Window

### ISSUE THREAD

**Issue by MR-Z-BRAINZ** [BEEmod/BEE2-items#3565]
**Description of the item:** An inaccessible area behind opened panels, where Wheatley watches on his management rail. This would have no effect on the puzzle, it's only a decorative item that would go well with levels where Wheatley is "helping" you (the only thing he does is watch, it's not a story-focused item). If possible, Wheatley's voicelines would be emitted from the window.

**Item options:** Different cores, if possible. (Disregard these options if adding different cores are hardcoded or something)

Weighted - Wheatley
Companion - Space Core
Reflective - Adventure Core
Edgeless - Fact Core
Franken - Nigel (only if Ap Tag is installed, blank if otherwise)

**Source:** Base game (when Wheatley breaks you out of the test chamber)

**Additional information:** Style variants -

Clean - Wheatley on a management rail behind opened up panels. The lower panels would be closed, blocking the player from entering

Overgrown - Wheatley on a management rail behind a collapsed section of wall, with debris blocking the player from entering

Portal 1 - I'm not really sure what this one would be, sorry

Old Aperture - Wheatley on a prototype management rail behind a grated off section of wall. The 1980s one would be more modern looking than the others.

BTS - Wheatley on a management rail behind a railing.

**Comment by FrozenDragon0** [comment]
This is an interesting item however, the monitor item sort of already does this.

**Comment by MR-Z-BRAINZ** [comment]
True, but only for GLaDOS and Mainframe-Wheatley.

**Comment by CMSEv7** [comment]
For Portal 1, it may be a P1 Style Wheatley.

**Comment by Cosmiscient** [comment]
I love this concept, I'd be happy to have this tool available in base beemod

**Comment by KaziPlays** [comment]
Put the Cake core as Wheatley on the Portal 1 style

**Comment by Konclan** [comment]
Better left as a UCP
