### ISSUE TITLE
Cube droppers stay open after dropping a cube (Portal 1)

### ISSUE THREAD

**Issue by PixelHUN** [BEEmod/BEE2-items#3569]
As in the title: The droppers will stay open, and will not drop another cube if the cube is destroyed.
![image](https://user-images.githubusercontent.com/59181913/100766063-84ed9200-33f8-11eb-85b9-8020678fc1ce.png)

**Comment by maxdevgithub** [comment]
I saw a similar issue in a P1 mod Portal Prelude where the vent stayed open
