### ISSUE TITLE
bug with bee2

### ISSUE THREAD

**Issue by lucasfelez** [BEEmod/BEE2-items#3570]
when i want export it jump 2 step and the 2 down i want to say,you can fix that pls

**Comment by FrozenDragon0** [comment]
Uhmmm what? Can you explain what you're talking about?

**Comment by lucasfelez** [comment]
> Uhmmm what? Can you explain what you're talking about?

when i export it jump the copy resources and copy music and when i play the game the object dont work the map too and even the style dont work

**Comment by LautaroL20** [comment]
Make sure that you have unchecked the option "Preserve Game Directories" in the Beemod options. Let us know if this solves your issue.

**Comment by lucasfelez** [comment]
> Make sure that you have unchecked the option "Preserve Game Directories" in the Beemod options. Let us know if this solves your issue.

thx very very much now if it dont work i will know we need to uncheck that
