### ISSUE TITLE
Placing Light Bridges on ceilling/floor at their corners causes leaks in the 80´s Old Aperture Style

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3572]
Not sure if this issue also occurs with previous versions, but while using Beemod 4.37.0 if you place Light Bridges on ceilling/floor at their corners, that will cause leaks in the 80´s Old Aperture Style. 

Puzzlemaker:
![20201203201142_1](https://user-images.githubusercontent.com/12244376/101099677-e69e2f80-35a3-11eb-9e0f-da402b89fe99.jpg)
In-Game results: 
![20201203201119_1](https://user-images.githubusercontent.com/12244376/101099688-ed2ca700-35a3-11eb-972b-a16c27e1a9f6.jpg)

**Comment by Luke18033** [comment]
There's a stain decal floating out there. Not sure what the point of it is.
![image](https://user-images.githubusercontent.com/19228201/101100180-e9385f00-357a-11eb-813e-173485f597b0.png)

**Comment by LautaroL20** [comment]
Thats weird, but seeing how that pointless thingy is located a bit distant at the side of the model it is definitely the reason of the leaks.
