### ISSUE TITLE
Drawbridges with inputs cause leaks in all the Old Aperture styles

### ISSUE THREAD

**Issue by MR-Z-BRAINZ** [BEEmod/BEE2-items#3574]
Drawbridges that have been connected to an input causes leaks in all the Old Aperture styles.

**Comment by LautaroL20** [comment]
> MR-Z-BRAINZ said: "This could possibly apply to other Old Aperture styles, but I haven't tried."

I will test it in the rest of the retro styles then, so this item can be fixed also in all the retros.

**Comment by LautaroL20** [comment]
I can confirm that Drawbridges causes leaks in all the retro styles.
