### ISSUE TITLE
One Way Field

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#3575]
The field allows the player and/or physical objects to go one way, but blocks them from the other way

**Comment by SCIENTIST2004** [comment]
example map:
coming soon

**Comment by Sombrero64** [comment]
Can be useful in some ways, but you can host yourself a repo for your objects.

**Comment by Thedoczek** [comment]
How to play the map?

**Comment by SCIENTIST2004** [comment]
Great idea but I don't know how to do it or can it be done at all

**Comment by SCIENTIST2004** [comment]
Palette Icon:
V1
![one_way_field_v1](https://user-images.githubusercontent.com/35931028/104753984-61d93080-5761-11eb-97c3-4faa549616b1.png)
V2
![one_way_field_v2](https://user-images.githubusercontent.com/35931028/104754008-67cf1180-5761-11eb-9b54-55f00fd78064.png)
V3
![one_way_field_v3](https://user-images.githubusercontent.com/35931028/104754038-73223d00-5761-11eb-9ef3-5021e09a7091.png)

**Comment by Thedoczek** [comment]
Make this the first version but with arrow

________________________________
Od: Andrushka <notifications@github.com>
Wysłane: piątek, 15 stycznia 2021 17:43
Do: BEEmod/BEE2-items <BEE2-items@noreply.github.com>
DW: Thedoczek <dokmiada@gmail.com>; Comment <comment@noreply.github.com>
Temat: Re: [BEEmod/BEE2-items] One Way Field (#3575)


Palette Icon:
V1
[one_way_field_v1]<https://user-images.githubusercontent.com/35931028/104753984-61d93080-5761-11eb-97c3-4faa549616b1.png>
V2
[one_way_field_v2]<https://user-images.githubusercontent.com/35931028/104754008-67cf1180-5761-11eb-9b54-55f00fd78064.png>
V3
[one_way_field_v3]<https://user-images.githubusercontent.com/35931028/104754038-73223d00-5761-11eb-9ef3-5021e09a7091.png>

**Comment by SCIENTIST2004** [comment]
@Thedoczek 
I also thought about that 
![one_way_field_v1_new](https://user-images.githubusercontent.com/35931028/104851826-faa5b280-58ff-11eb-9995-1868040a6372.png)

**Comment by SCIENTIST2004** [comment]
I could try to create an item but I don't know how to do it

**Comment by TeamSpen210** [comment]
One issue here is that this design won't work in coop, or if multiple objects are brought near it. I've considered this sort of thing, but haven't came up with a good and reliable solution to that.

**Comment by Electricianfromhell** [comment]
@TeamSpen210 @LautaroL20 @BenVlodgi 

The solution to build a fizzler like this is simple

place a trigger multiple that would be on one side of the fizzler, a noclip in the middle main part of it and another trigger multiple on the backside.

the first trigger multiple would disable the no clip when a player or cube entered it, then the trigger multiple on the back side would enable the no clip when a player or cube touched it.

**Comment by TeamSpen210** [comment]
Nope. What happens if one player approaches it from the correct side, walks halfway through, then picks up a cube and pulls it back across?

**Comment by Thedoczek** [comment]
And noclip won't work on cubes.
________________________________
Od: Spencer Brown <notifications@github.com>
Wysłane: niedziela, 31 stycznia 2021 02:36
Do: BEEmod/BEE2-items <BEE2-items@noreply.github.com>
DW: Thedoczek <dokmiada@gmail.com>; Mention <mention@noreply.github.com>
Temat: Re: [BEEmod/BEE2-items] One Way Field (#3575)


Nope. What happens if one player approaches it from the correct side, walks halfway through, then picks up a cube and pulls it back across?

**Comment by Konclan** [comment]
We don't need more fields, there are simple ways to do one way setups in puzzle design
