### ISSUE TITLE
Laser Emitter Cube

### ISSUE THREAD

**Issue by MR-Z-BRAINZ** [BEEmod/BEE2-items#3576]
A cube, similar to a Reflection Cube, but constantly emits a laser and does not need to be touching an already existing laser. It would be able to press buttons and do other cube things. Maybe it would have a special receptacle that would toggle the laser if touched? Or use regular inputs, but I'm not sure how you would wire inputs to a cube.

**Comment by seagemgames** [comment]
Already made with a UCP. Should be here https://github.com/ENDERZOMBI102/Radelite_BEE2_package/issues
or possibly retro station.

**Comment by MR-Z-BRAINZ** [comment]
Ah ok, I'll look into that then. Thanks for telling me about it
