### ISSUE TITLE
Error with beemod

### ISSUE THREAD

**Issue by 102182123** [BEEmod/BEE2-items#3580]
![image](https://user-images.githubusercontent.com/61122724/102501906-a0a69880-4086-11eb-9c27-286573a2f81c.png)
What i need to do?

**Comment by seagemgames** [comment]
What version of BEEmod are you using, and what version of the packages? This seems like the packages may be the wrong version. Make sure that you use the same version of packages as your version of BEEmod.

**Comment by 102182123** [comment]
I got an another error
![image](https://user-images.githubusercontent.com/61122724/102512047-35fb5a00-4092-11eb-8b4b-b0d4451115ab.png)

**Comment by seagemgames** [comment]
That means that it does not have permissions to access your Portal 2 directory.

**Comment by 102182123** [comment]
How to get the permissions?

**Comment by seagemgames** [comment]
is Portal 2 located at `e:\\r.g. catalyst\\portal 2\\`? because that seems wrong

**Comment by 102182123** [comment]
When i want to Rebuild level, it stops at building geometry

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to the Beemod user interface, must be posted on the interface´s page, here: https://github.com/BEEmod/BEE2.4/issues

The section where you have posted is for things related to the items & styles, only.
