### ISSUE TITLE
Protruding white surface

### ISSUE THREAD

**Issue by ThatOneRetro** [BEEmod/BEE2-items#3582]
Maybe just as a decorative item, you could add a protruding white surface.
In clean or portal 1 it would slightly stick out similar to to the funnel+lazar+fling wheatly chamber.
In styles like overgrown, old ap and bts, the wall would look like it wasn't meant to be there. Maybe it would look like it was taken
out and oriented slightly or just thrown onto the surface as if it was being moved.

If you wanted to make a wall version, you could probably make it so it had to be on a 90 degree angle as if it were propped up.
I think this would look really cool in overgrown and just add a bit more dimension to certain parts of the test chamber.

**Comment by ThatOneRetro** [comment]
![image](https://user-images.githubusercontent.com/63503250/102921315-172b0800-4484-11eb-87fc-df29264009f0.png)

**Comment by Konclan** [comment]
You can already do this with angled panels set to not open.
