### ISSUE TITLE
Iron bars (BTS suggestion)

### ISSUE THREAD

**Issue by ThatOneRetro** [BEEmod/BEE2-items#3583]
To make BTS look closer to the original, you could add iron bars as if it was holding up objects.
This would be a decorative item and you could use glass in puzzle editor to make it stretch a certain length.
It would add more stuff in general to the look of bts.
![image](https://user-images.githubusercontent.com/63503250/102906553-b3491500-446c-11eb-8ec4-d506d675d52b.png)

**Comment by FrozenDragon0** [comment]
I can't see this being a main item being added but it could be something made for a UCP though.

**Comment by Konclan** [comment]
This should be left in the bottomless pit
