### ISSUE TITLE
Pedestal Button variants connected to a cube dropper with timer emit a ticking sound

### ISSUE THREAD

**Issue by Nente520** [BEEmod/BEE2-items#3584]
When connected to a cube dropper with a timed output, custom pedestal buttons (any of them: left/middle/right, protruding, retractable) emit a ticking sound, like when connected to any other item. However, original Portal 2 pedestal buttons do not emit this sound when connected to cube droppers, so I beliebe that is unintented.
I've tried it with a few different styles, it persists in (at least) Clean, Original Clean, 50s and 70s styles, I did not test this in Overgrown style yet, while in Portal 1 it works correctly.

**Comment by LautaroL20** [comment]
Does this issue also happens in Overgrown too?
