### ISSUE TITLE
Allow Entry Doors and Exit Doors to be placed on floors and ceilings

### ISSUE THREAD

**Issue by MR-Z-BRAINZ** [BEEmod/BEE2-items#3586]
Sounds weird, but hear me out:

1. Entry Doors on the floor would have an extra room past the Entry Corridor where a Piston Platform would raise the player into the chamber.
2. Entry Doors on the ceiling would have an extra room past the Entry Corridor where a hatch opens and drops the player into the chamber.
3. Exit Doors on the floor would have a hatch that drops into a small room that leads into the Exit Corridor.
4. Exit Doors on the ceiling would be a hatch that closes after the player launches in, then leading into the Exit Corridor. This door would naturally be hard to enter, but it would work well for momentum and gel puzzles.

I feel like these additions would work well for style and extra challenge in getting into the exit door, and in areas where a normal entry door wouldn't fit (eg: "cage" in the middle of the chamber)

Technically these can be made already with existing items and a normal Entry-Exit door, but it'd just save on space in the chamber to make it possible to place these on the floor and ceiling.

**Comment by CassieCatYT** [comment]
i like this idea, however it would be hard to implement in all styles
