### ISSUE TITLE
Pedestal buttons do not work in 50's 60's styles 

### ISSUE THREAD

**Issue by Koiree2275** [BEEmod/BEE2-items#3589]
BEE2 version 4.37.0:

The pedestal buttons do not interact with anything, they don't even light up the antline.

When I connect a button to a cube dropper, light bridge, etc and press it, it should turn the item on,

Place a pedestal button in any chamber and this will happen, with any item.

https://user-images.githubusercontent.com/77248987/104136105-c1969c80-5359-11eb-81d3-90444d9bf913.mp4

**Comment by LautaroL20** [comment]
This is fixed with the release of Beemod version 38, you can get it below:

https://github.com/BEEmod/BEE2-items/releases/tag/v4.38.0 (Packages)
https://github.com/BEEmod/BEE2.4/releases/tag/2.4.38.0 (User Interface)
