### ISSUE TITLE
Problem with compile all of fizzlers in Horizontal rotation

### ISSUE THREAD

**Issue by THS2121966** [BEEmod/BEE2-items#3593]
Problem with compile all of fizzlers in Horizontal rotation.
[BEEMOD_FAILED.txt](https://github.com/BEEmod/BEE2.4/files/5813521/BEEMOD_FAILED.txt)

**Comment by THS2121966** [comment]
LautaroL20, Okay. Sorry.

**Comment by LautaroL20** [comment]
No problem.
