### ISSUE TITLE
1970's - Entrance trigger is inside the door

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2-items#3597]
**BEE2 version:** 4.38.1

**Description of the bug:** Door trigger is located inside the door, I used noc

**Expected behavior:** I wanted the door to open!

**Steps to reproduce:** Just spawn at 1970 map. I used entrance _7. Corridor_, but I think it will be on others too

**Additional information:**
https://youtu.be/7J5ASjVe7lM This is the film to this bug and next 2 ones

**Comment by LautaroL20** [comment]
Could you please re-upload the video? I do not get why videos from some issues gets down for no reason even when they are in Youtube... I do not really understand what do you mean with "entrance trigger is inside the door" and if this would be a bad thing or not.
