### ISSUE TITLE
1970's - Chamberlock doesn't remove tiles

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2-items#3598]
**BEE2 version:** 4.38.1

**Description of the bug:** The "Chamberlock" item in Old Ap does not delete wall.

**Expected behavior:** Well nobody wants the door to be just a wall.

**Steps to reproduce:** Just spawn at old ap map. (Use noclip - #3597). Make a chamberlock and you'll see

**Additional information:**
https://youtu.be/7J5ASjVe7lM This is the film to this bug, previous one and next one.

**Comment by FrozenDragon0** [comment]
Area portal there that is either a left over or is not opening correctly.

**Comment by Thedoczek** [comment]
> 
> 
> Area portal there that is either a left over or is not opening correctly.

What are you talking about? I mean the middle one. There is no Wprld Portal there

**Comment by FrozenDragon0** [comment]
@Thedoczek At the exit door you showed the nodraw there.

**Comment by Thedoczek** [comment]
> 
> 
> @Thedoczek At the exit door you showed the nodraw there.

1. That's issue #3599, I made 3 separate for that
2. Idk in that things
