### ISSUE TITLE
Player/Object Fields

### ISSUE THREAD

**Issue by iwantpizza10** [BEEmod/BEE2-items#3600]
**__Player Fields__**
Basically a fizzler but it will only let the player go through,
Color: Orange or Green

**__Object Fields__**
Again, a fizzler that only lets some stuff through. This time, it's letting cubes, turrets, and stuff line that through.
Color: Orange or Green (but not the one for the player field)

**Comment by LautaroL20** [comment]
> ****Player Fields****
> Basically a fizzler but it will only let the player go through,
> Color: Orange or Green

You need to be more specific because that is exactly what the vanilla fizzler does. Also, the Orange colour is already being used on the Force Deflection Field and green is used on the Physics Repulsion Field.

> ****Object Fields****
> Again, a fizzler that only lets some stuff through. This time, it's letting cubes, turrets, and stuff line that through.
> Color: Orange or Green (but not the one for the player field)

That is what the Physics Repulsion Field does.

**Comment by iwantpizza10** [comment]
Actually i didnt see the items lel

**Comment by LautaroL20** [comment]
> iwantpizza10 said: Actually i didnt see the items lel

Here are the full list of the current existing fizzler variants available in the Beemod palette:

Standing Fizzler
Death Fizzler
Matter Inquisition Field
Force Deflection Field
Compressed Smoke Field
Closed Solid Field
Physics Repulsion Field
Radiative Flux Field
Absolute Fizzler
Paint Fizzler
Lifeform Sensor

**Comment by seagemgames** [comment]
And if you want, here's a little chart showing what each does 
![image](https://user-images.githubusercontent.com/32136200/104854761-7f90cc00-5900-11eb-9f45-5bdeba68cc54.png)
