### ISSUE TITLE
Cube Colorizer should mention on the description where to find what color is each number

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3606]
The Colorizer should mention on the description where to find what color is each number, because not everyone will going to be aware that an "itemvar" exist somewhere on the interface and if they do, not enough attention could be paid on it.

So, adding something like this to the item´s description will help all users: "You can find what color is each number on the itemvar panel."

**Comment by seagemgames** [comment]
This has been added in #3610

**Comment by LautaroL20** [comment]
Once Beemod version 4.39.0 is relased, ill going to close this issue manually. Meantwhile, ill add the "done" label.
