### ISSUE TITLE
Placing a monitor in a black wall makes the wall float

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3607]
If I place a monitor in a black wall, when the monitor appears, the wall will appear floating.

It happens on all styles, and I don't know why.

**Comment by KaziPlays** [comment]
I've put compile error by accident, please disregard.

**Comment by LautaroL20** [comment]
No problem, i´ve corrected it.

**Comment by TeamSpen210** [comment]
This is a duplicate of #3568.
