### ISSUE TITLE
Aperture Science Emergency Intelligence Incinerator

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3608]
The Aperture Science Emergency Intelligence Incinerator (Also known as "Incinerator") is the same Incinerator from Test Chamber 16 & GLaDOS's chamber (Portal 1) And GLaDOS's Overgrown chamber (Portal 2).

The Incinerator could work like this:

Start Activated: It starts open.

Cube type: Will be the type of cube that needs to be Incinerated

The Clean/BTS style Incinerator could be this:

https://gamebanana.com/skins/169785

A Portal 2 fixed Incinerator.

The Portal 1 themed Incinerator would be the normal texture & model from Portal 1

The Overgrown/Old Aperture Incinerator would be the Incinerator on GLaDOS's Overgrown chamber.

This is all I have in mind for a new item.

**Comment by seagemgames** [comment]
This is already planned. See #95

**Comment by KaziPlays** [comment]
Okay sorry
