### ISSUE TITLE
Themed BTS Styles

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3609]
I know styles take a lot of effort and work, but i thought: "Why Isn't there Themed BTS Styles?"

Like, A Portal 1 Themed BTS, An Overgrown Themed BTS,  An Old Aperture Themed BTS.

Not a BTS BTS Theme, It would be funny.

**Comment by seagemgames** [comment]
BTS is pretty bad in PeTI, though P1BTS could work, as it's a lot more boxy. It doesn't really work though still, as the puzzlemaker is for... well, making puzzles.

**Comment by DeliWasTaken** [comment]
In all honesty we're just luck the normal BTS theme hasn't been retired yet. We're not getting more BTS themes, most likely.

**Comment by Konclan** [comment]
Portal 1 bts and old aperture bts has already been suggested I believe, I don't think new themes are ever gonna be developed by the team though. Can't say for certain.

**Comment by HeimlichLaboratories** [comment]
Even the normal BTS is gone now
