### ISSUE TITLE
suggestions for 3D skybox code

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#361]
i have some suggestions for the 3D skybox code

move the pit_blend_light and goo_wall variables from the vbsp config to the skybox block in the style info file

for example

```
"SkyBox"
{
"ID"            "VALVE_3D_INCINERATOR"
"Name"          "3D - Incinerator"
"Group"         "3D"
"Icon"          "skies/p1_incinerator.png"
"Material"      "sky_black"
"Config"        "p1_incinerator"
"Authors"       "VengaboysMuseum"
"Description"   "A Burning Incinerator."
"pit_blend_light"    "245 157 57 2"
"goo_wall"      "metal/metalwall048e" 
"Fog"
{
"start"     "0"
"end"       "5000"
"density"   "0.95"
"primaryColor"      "245 157 57"
"secondaryColor"    "245 157 57"
        "direction"         "90 0 0" 
"tonemap_rate"          "0.25"
"tonemap_brightpixels"  "5"
"tonemap_exposure_min"  "1"
"tonemap_exposure_max"  "5"
}
}
```

make it so you can add more than 1 goo_wall variable to create varied wall textures.

make it so style specific skyboxes only show up in the selection list for the test style selected in bee2. this is to prevent a Wheatley 3D skybox and bottomless pit from being used in a overgrown test or so and so. for example code adding on to the previous code

```
"SkyBox"
{
"ID"            "VALVE_3D_INCINERATOR"
"Name"          "3D - Incinerator"
"Group"         "3D"
"Style"     "Portal 1"
"Icon"          "skies/p1_incinerator.png"
"Material"      "sky_black"
"Config"        "p1_incinerator"
"Authors"       "VengaboysMuseum"
"Description"   "A Burning Incinerator."
"pit_blend_light"    "245 157 57 2"
"goo_wall"      "metal/metalwall048e" 
"Fog"
{
"start"     "0"
"end"       "5000"
"density"   "0.95"
"primaryColor"      "245 157 57"
"secondaryColor"    "245 157 57"
        "direction"         "90 0 0" 
"tonemap_rate"          "0.25"
"tonemap_brightpixels"  "5"
"tonemap_exposure_min"  "1"
"tonemap_exposure_max"  "5"
}
}
```

**Comment by TeamSpen210** [comment]
`GooWall` has nothing to do with skybox - I'm going to make it not apply to bottomless pits. `pit_blend_light` should be the ambient light colour used in the style, not that of the skybox. I'll add an additional override for glowing skyboxes (P1 pits for example).

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 and @BenVlodgi 

update to this - see photo's for reference

behold my early Incinerator 3D skybox for P1, you will not believe what i had to go through to get this to work properly...

![preview0060](https://cloud.githubusercontent.com/assets/11165643/13792227/42fb3016-eac7-11e5-8f09-9fc4d6e3d704.jpg)

we need some override that changes this texture for the specific 3D skybox (the texture the red arrow points to).

![preview0063](https://cloud.githubusercontent.com/assets/11165643/13792311/a5dcdb12-eac7-11e5-8efe-e279c7dc0789.jpg)

also what do the support instances do in the skybox instance directory? are they placed behind every wall and corner instance in the test chamber for the skybox?

**Comment by TeamSpen210** [comment]
The support instances are somewhat randomly placed at the same point as the side instances. They're always placed under 4-side or 3-side instances - the intention is that they're used for the truss supports you have.
