### ISSUE TITLE
P1 Piston Panel generates in "mysterious way"

### ISSUE THREAD

**Issue by saismeesaimonsaimes** [BEEmod/BEE2-items#3611]
**BEE2 version:** 4.38.1

**Description of the bug:** P1 piston panel has a weird segment jutting out

**Expected behavior:** Not having this segment

**Steps to reproduce:**
1: Export with a piston panel and in P1 theme.
2: Place the piston panel specifically like this. It must be facing north, with a white tile to the right (marked red). The piston must be *specifically* two voxels up.
3: Build chamber. It has weird geometry.

Notes:
The tile under the platform does not affect it.
Connections do not affect it.

I will upload preview.vmf soon.
![image](https://user-images.githubusercontent.com/32136200/106015956-e65b7580-60b6-11eb-910a-a40444f90f58.png)
![image](https://user-images.githubusercontent.com/32136200/106016008-f2473780-60b6-11eb-82ed-10ab327bb372.png)

**Comment by seagemgames** [comment]
Reproduction:
https://youtu.be/r1alG-Hciqs
[preview.zip](https://github.com/BEEmod/BEE2-items/files/5881376/preview.zip)

**Comment by seagemgames** [comment]
Only in this specific grid does this happen. It's something weird with the geometry as these func_movelinears are the only entities in the map other than my spawn.
![image](https://user-images.githubusercontent.com/32136200/106020268-7bf90400-60bb-11eb-852b-13ee298e38ef.png)

**Comment by Luke18033** [comment]
We need to convert these to models, that should fix these issues. Brushes are weird.

**Comment by TeamSpen210** [comment]
This is a bug in the tiling generator itself somehow...
