### ISSUE TITLE
 Block Stairs cause a compile error

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3613]
I've never seen this error before.

TypeError: unsupported operand type(s) for @: 'srctools._math.Vec' and 'src

Help?

**Comment by seagemgames** [comment]
That error is cut off... I'm assuming the rest says `tools._math.Vec`. I believe spen knows about this one, but I don't believe an issue was made for it.

**Comment by KaziPlays** [comment]
oh it was cut
lemme see...

yeah it's the same thing.

**Comment by TeamSpen210** [comment]
Can you give me the full error, not a fragment? I need to know where it occured.

**Comment by KaziPlays** [comment]
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198999677945\autosave.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (15,22,7)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 549 (ms)

VBSP failed.

[I] vbsp.main(): BEE2 v4.38.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] options.load(): Extra config options: {'staticpan': 'instances/BEE2/over/static_panel/', 'voice_pack': 'BEE2_GLADOS_APOC'}
[I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 61 embeds!
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (1 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 6
[I] vbsp.mod_entryexit(): Setting SP Exit to 4
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (145 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[I] cond.core.res_goo_debris(): GooDebris: 0/18 locations
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[E] cond.core.check_all(): Error in <VALVE_GEOMETRY>/items/stairs:
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 523, in check_all
  File "precomp\conditions\__init__.py", line 312, in test
  File "precomp\conditions\__init__.py", line 301, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1139, in res_sub_condition
  File "precomp\conditions\__init__.py", line 312, in test
  File "precomp\conditions\__init__.py", line 301, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1139, in res_sub_condition
  File "precomp\conditions\__init__.py", line 312, in test
  File "precomp\conditions\__init__.py", line 301, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1139, in res_sub_condition
  File "precomp\conditions\__init__.py", line 312, in test
  File "precomp\conditions\__init__.py", line 301, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1139, in res_sub_condition
  File "precomp\conditions\__init__.py", line 312, in test
  File "precomp\conditions\__init__.py", line 301, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\brushes.py", line 239, in res_set_texture
  File "precomp\template_brush.py", line 384, in rotate
  File "srctools\vmf.py", line 1275, in localise
TypeError: unsupported operand type(s) for @: 'srctools._math.Vec' and 'srctools._math.Vec'

**Comment by Maniac0bra** [comment]
I have the exact same problem. Looks like this error is triggered by a specific element because it doesn't crash on all my levels, guess we have to find manually what is this element ¯\_(ツ)_/¯ (despite the word "stairs" in the crash report, it's not that)

**Comment by Maniac0bra** [comment]
I have this error too, just 1 hour ago, looks like it's triggered by a specific element because my other levels don't crash despite the same configurations

**Comment by TeamSpen210** [comment]
It's to do with the block stairs. Turn those off in the item settings.

**Comment by KaziPlays** [comment]
Okay thank you

**Comment by KaziPlays** [comment]
Why did you re-open this if it's already fixed?

**Comment by Luke18033** [comment]
The issue should stay open until an update with the fix is released.

**Comment by KaziPlays** [comment]
Oh, that makes sense

**Comment by KaziPlays** [comment]
I think the reason the compile error happened cause the stairs was surrounded with walls, then, when generating solid stairs, it may have caused the error there

**Comment by Konclan** [comment]
No the error is just with block stairs, having stairs without connections and with the block stairs item option enabled will cause the item to make the compiler fail.

**Comment by TeamSpen210** [comment]
I rewrote some internal code, and missed updating the "SetTexture" command which applies the squarebeams material to the wall the stair almost covers. So it would just break.

**Comment by TacticalMeme** [comment]
How do you change the "Block Stairs" setting?

**Comment by Luke18033** [comment]
It's in the Style/Item Properties window.

**Comment by Blaztix** [comment]
I can't use stairs in version 4.39.0

I try disabling "Block Stairs" but does not change the error.

The error is when I try compile with a stair connect to something. (button)

### This compiles
I can compile with or without "Block Stairs"  
![image](https://user-images.githubusercontent.com/4962591/109375123-fb374e80-7898-11eb-99e4-26edd46c9a4f.png)

### This **does not** compile
I can't compile if some stair it's conneted to something.

![image](https://user-images.githubusercontent.com/4962591/109375107-cc20dd00-7898-11eb-974c-38c4c618206d.png)


```
VBSP failed.

[I] vbsp.main(): BEE2 v4.39.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "D:/Juegos/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "D:/Juegos/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): Could not parse texture generator type "bullsye.white.floor"!
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (11 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Using random SP Entry (1)
[I] vbsp.mod_entryexit(): Using random SP Exit (3)
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (325 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.catwalks.res_make_catwalk(): Connections: {<srctools.vmf.Entity object at 0x0718A268>: <precomp.conditions.catwalks.Link object at 0x04AEE428>, <srctools.vmf.Entity object at 0x0718A298>: <precomp.conditions.catwalks.Link object at 0x04AD30A8>, <srctools.vmf.Entity object at 0x0718A2C8>: <precomp.conditions.catwalks.Link object at 0x04AEF808>, <srctools.vmf.Entity object at 0x0718AC40>: <precomp.conditions.catwalks.Link object at 0x07CE2A68>, <srctools.vmf.Entity object at 0x0718AC70>: <precomp.conditions.catwalks.Link object at 0x07CE20A8>, <srctools.vmf.Entity object at 0x0718ADD8>: <precomp.conditions.catwalks.Link object at 0x07CE2DC8>}
[I] cond.catwalks.res_make_catwalk(): Markers: {'catw100': <srctools.vmf.Entity object at 0x0718A268>, 'catw101': <srctools.vmf.Entity object at 0x0718A298>, 'catw102': <srctools.vmf.Entity object at 0x0718A2C8>, 'catw137': <srctools.vmf.Entity object at 0x0718AC40>, 'catw138': <srctools.vmf.Entity object at 0x0718AC70>, 'catw144': <srctools.vmf.Entity object at 0x0718ADD8>}
[I] cond.catwalks.res_make_catwalk(): Finished catwalk generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] instanceLocs.get_subitems(): Invalid custom instance name - "tim_start" for <item_bee2_scaffold_slot> (Valid: {'bee2_tim_start': 'instances/BEE2/clean/items/scaffold/tim_start.vmf'})
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:small" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:medium" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:large" for vactube group BEE2_VACTUBES!
[I] connections.gen_item_outputs(): Generating item IO...
[E] cond.core.check_all(): Error in MetaCondition "gen_item_outputs":
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 511, in check_all
  File "precomp\conditions\__init__.py", line 300, in test
  File "precomp\conditions\__init__.py", line 289, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\connections.py", line 862, in gen_item_outputs
  File "precomp\connections.py", line 1079, in add_item_inputs
AttributeError: 'tuple' object has no attribute 'input'
```

**Comment by Konclan** [comment]
This error is unrelated
