### ISSUE TITLE
Chamberlock causes Leak

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#3615]
Placing a 1x1x1 voxel wide corridor behind the Chamberlock causes Leak in ALL Styles.

![20210131130939_2](https://user-images.githubusercontent.com/11165643/106394060-8d4a5500-63c8-11eb-8ed4-7861c52fd760.jpg)

![20210131132014_1](https://user-images.githubusercontent.com/11165643/106394061-8f141880-63c8-11eb-81b1-04c14e53951f.jpg)

**Comment by seagemgames** [comment]
More accurately, the chamberlock causes a leak 100% of the time.

**Comment by HeimlichLaboratories** [comment]
Actually, placing a chamberlock with a corridor wider than 1x1x1 fixes the leak. And it's Overgrown style I'm talking about so that's pretty impressive.
