### ISSUE TITLE
Chamber lock Door visible through P1 Light Strip

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#3616]
Chamber Lock Door visible through P1 Light Strip

![20210131134036_1](https://user-images.githubusercontent.com/11165643/106394334-24fc7300-63ca-11eb-9e7d-4be3752635b1.jpg)

suggested fix, make the Portal 1 chamber lock occoupie 1 x 3 voxels so nothing can be placed on the 2 sides where the door opens where the lightstrip is in the image.

or make the p1 lightstrip use a dedicated world portal for the light source.

**Comment by Luke18033** [comment]
P1 light strips used to use world portals, it didn't work that well. Just don't place light strips this way, we're not going to give items massive collisions just because there's one weird item placement you can make with the current collisions.
