### ISSUE TITLE
covered angle panel cube game crash bug

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#3618]
letting a standard cube touch the front of a covered angled panel (the one that retracts covered by glass panels) on a pedestal button timer (using the portal gun to hold the cube against the panel) has a chance to crash game as soon as the panel retracts. It only happened one time when i did this and i haven't been able to make it do it again. the image is how i held the cube against it when it randomly crashed when the panel retracted.

![20210131182240_1](https://user-images.githubusercontent.com/11165643/106401453-2d68a400-63f2-11eb-9bba-a2f5f72c65b4.jpg)

**Comment by Luke18033** [comment]
Not sure if this would be fixable.

**Comment by FrozenDragon0** [comment]
Any word on this if it can be fixed?

**Comment by Luke18033** [comment]
Has anyone even been able to reproduce it?

**Comment by Luke18033** [comment]
Not sure how to reproduce this.
