### ISSUE TITLE
Covered Angled Auto Portal

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#3620]
A Covered Angled Auto Portal similar to the covered angled panel. The angled panel with the autoportal would default to being white, set reversed should make the panels that cover it glass instead of black or white depending upon the color of the surface it is placed upon.

**Comment by seagemgames** [comment]
At this point, this seems super niche. It'd be better if the auto portal just stuck to the panel with the tiling system, with an option to swap between glass and a black cover. White cover would be useless as you can use a regular panel for that.
