### ISSUE TITLE
fizzlers only place in 6 positions instead of 8 on 4.38.1

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#3621]
all fizzlers only place in 6 positions instead of the original 8 like a lightstrip does on bee2 version 4.38.1

![20210131185414_2](https://user-images.githubusercontent.com/11165643/106402130-1d52c380-63f6-11eb-8916-f2a9158443ae.jpg)

**Comment by Luke18033** [comment]
This is how they are in vanilla and have always been in BEE. You've also [duplicated your own issue again](https://github.com/BEEmod/BEE2-items/issues/189). Please do a search first.

**Comment by Luke18033** [comment]
There's also [this issue](https://github.com/BEEmod/BEE2.4/issues/1229) which is what will actually be implemented. It's also by you, meaning you've now opened an issue for the same thing 3 times.

**Comment by EllingtonElectrician** [comment]
oops my bad, migrating idea to fix issue to original post
