### ISSUE TITLE
New Style: Cave Therapy

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#3622]
Idea for a New Style i like to call Cave Therapy

it's not exactly art therapy because that looks different from this and art therapy is built higher up in the facility.

it is basically underground with a massive cave for a bottomless pit and it uses clean textures for the walls etc. it mixes old 50's air ducts and stuff etc with modern equipment randomly built into the cave walls etc.

example Image of it

![clean retrofit](https://user-images.githubusercontent.com/11165643/106410194-4b450180-6410-11eb-9fd5-2fc72ff6956e.jpg)

you can see a good example of it in this video.

https://youtu.be/p3CGfizQZmE?t=20

**Comment by TeamSpen210** [comment]
If you're going to suggest adding Desolation's Industrial style, please at least find its actual name. And it wouldn't work well, it requires a lot of displacement work, unique detail everywhere around the chamber, redesigns of all the panels, and also Desolation's various engine changes to get the full look. And huge amounts of custom/ported assets.

**Comment by EllingtonElectrician** [comment]
@TeamSpen210 - no i just was suggestion a clean underground combination style that uses panels from the clean style as the main portal surfaces.

**Comment by Luke18033** [comment]
And regardless of editor and engine limitations, Desolation isn't released and won't be for several more years, so it's kind of pointless to suggest this now.

**Comment by Luke18033** [comment]
> no i just was suggestion a clean underground combination style that uses panels from the clean style as the main portal surfaces.

That's basically just what Art Therapy is.

**Comment by EllingtonElectrician** [comment]
> > no i just was suggestion a clean underground combination style that uses panels from the clean style as the main portal surfaces.
> 
> That's basically just what Art Therapy is.

except the main difference is a cave as a bottomless pit instead of the reservoir from art therapy.

**Comment by Luke18033** [comment]
That could maybe work, there actually is [a map like that](https://theportalwiki.com/wiki/Portal_2_Co-op_Course_6_Chamber_5) in the original Art Therapy course. The chamber would be a bit more enclosed because Puzzlemaker, but the surrounding environment could be the same. That of course relies on the surrounding-chamber-environment system actually being implemented, which isn't happening for a while.

**Comment by EllingtonElectrician** [comment]
@Luke18033 @TeamSpen210 - 

Luke is partially right on the one map from art therapy, let me try to verbally paint a description and show you a better idea of what i was trying to initially describe to you.

the idea i have for the style is it has a cave as the bottomless pit instead of modern aperture with open walls and a ceiling and uses clean textures for the main textures used by walls in the test chamber. it would look similar to what you see in the image, except the yellow and brown bts texture would be replaced by panels and square frames like what you see on the walls of a typical clean bottomless pit like in the second image.

![20210201124913_1](https://user-images.githubusercontent.com/11165643/106497617-46be2e80-648c-11eb-8de4-1d4a44881be2.jpg)

![20210201134938_1](https://user-images.githubusercontent.com/11165643/106504154-90ab1280-6494-11eb-9611-c5664645f17e.jpg)

**Comment by Luke18033** [comment]
Once the surrounding environment system is implemented and Art Therapy style is in a mostly finished state, I'll consider adding this as a variant, but it definitely isn't happening now with limited (and as of 4.37, nonexistent) 3D skyboxes.
