### ISSUE TITLE
Large Observation Room no longer able to be placed on floor / ceilings

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#3623]
Bug happens on Bee version 4.38.1

Large Observation Room is no longer able to be placed on floor / ceilings in the peti editor.

if you unlock the default items and put the large observation room into your peti editor item list, if you zoom way in on the map floor your able to place it in the floor with some quick mouse movements, as soon as you move it to a wall it becomes unplaceable on floor and ceiling.

![20210201140548_2](https://user-images.githubusercontent.com/11165643/106505974-0912d300-6497-11eb-8e01-d54af528aeef.jpg)

here is a photo showing you can place the thing in the floor with some tricks by making the floor massive so it doesn't hit any walls when you bring it into the editor. as soon as it touches a wall it becomes unable to be placed on a floor or ceiling again. 

![20210201141626_1](https://user-images.githubusercontent.com/11165643/106507577-40827f00-6499-11eb-981e-a7ce6afc4f96.jpg)

here is a photo of the wrong observation room instance generating in the map

![20210201142156_1](https://user-images.githubusercontent.com/11165643/106507609-4d9f6e00-6499-11eb-9d8f-1d740e4757dc.jpg)

**Comment by Luke18033** [comment]
Large observation rooms have never been placeable on floors without that trick, and don't have a proper variant for it. Small ones do though.

**Comment by Luke18033** [comment]
As for adding those variants, that's already been suggested in #1118.

**Comment by EllingtonElectrician** [comment]
@Luke18033 they used to be able to be placed on the floor and ceiling in a earlier version of bee2

**Comment by Luke18033** [comment]
What earlier version? That was never the case as far as I am aware.

**Comment by FrozenDragon0** [comment]
They never were placable on floors/ceilings to begin with.
