### ISSUE TITLE
Characters not talking when picking GLaDOS, Wheatley, Apocalypse Announcer, ETC

### ISSUE THREAD

**Issue by Bloodstrike2003** [BEEmod/BEE2-items#3624]
There's a problem that I don't know if people experienced this or not, or it's just me. So I picked a voice (GLaDOS for example) for who's gonna talk during testing from beginning to end. But all I hear is silence from said voice. so is this issue gonna be fixed or I just don't know how to turn it on or off and wasted time on this. (also will art therapy and refurbished styles become available when bee2 is updated? dumb question but.. will it?) that is all I have to say.

**Comment by DeliWasTaken** [comment]
This is a known issue, voice lines aren't working in .38

**Comment by Bloodstrike2003** [comment]
oh ok

**Comment by FrozenDragon0** [comment]
In regards to Art Therapy and Refurbished style, no they will not come in the next update. Styles take alot of effort to make and while Art therapy is in development there is no known date as to when it'll be available. Refurbished has not had any development started on it and it will not be coming out for quite awhile.

**Comment by Bloodstrike2003** [comment]
oh

**Comment by Bloodstrike2003** [comment]
that's a shame

**Comment by Luke18033** [comment]
Art Therapy is on hold until the ability to properly generate the reservoir around chambers is implemented.

**Comment by Bloodstrike2003** [comment]
alright

**Comment by Bloodstrike2003** [comment]
though.. refurbished would be pretty interesting and cool, but if it's not gonna be included then I understand if it's not gonna be added.
