### ISSUE TITLE
Make all partial block textures default to 4x4 texture when in contact with goo.

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#3625]
Make all partial block textures default to 4x4 texture when in contact with goo.

the image shows the issue, you can see the texture of the wall above the goo on the right as a 4x4 texture and on the left where i placed the 1/2 partial blocks it's the 1x1 texture

![20210201220305_1](https://user-images.githubusercontent.com/11165643/106546804-fbcb0800-64d9-11eb-8565-0002c4fe0a9e.jpg)

**Comment by LautaroL20** [comment]
It depends if Spencer finds a way to detect when a partial block is placed in a goo pit, hope it is possible though.

**Comment by TeamSpen210** [comment]
This is doable actually.
