### ISSUE TITLE
Hover Turret

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3628]
The Hover Turret was an unused turret that would be hanging up on the ceiling.
It would shoot a laser to damage you.

The entity class of this turret is still present in the game files, and this guy decided to fix it.

https://www.moddb.com/games/portal-2/addons/hover-turret-fix

PS: Please read the description of the fix because some things don't work.

![hoverturret_demo0000](https://user-images.githubusercontent.com/72144613/107120920-5499f800-686e-11eb-9209-7d7fcc126dc4.jpg)

**Comment by seagemgames** [comment]
Duplicates #1641, and doesn't really fit in BEEmod.
