### ISSUE TITLE
There Was An Error While Building The Puzzle.

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3629]
I'm just tired of explaining.

Portal 1 Style, Using UCPs.

SoundEmitterSystemBase::GetParametersForSound:  No such sound Error
Unknown command "cl_puzzlemaker_start_editing"
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198999677945\autosave.p2c
Kazi unpaused the game
[PORTAL2 PUZZLEMAKER]  Saved puzzle: puzzles\76561198999677945\1612638608.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps/1612638608.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (15,17,7)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 376 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 36259 (ms)

VVIS failed.

Valve Software - vvis.exe (Nov 12 2019)
2 threads
reading c:\program files\steam\steamapps\common\portal 2\sdk_content\maps\1612638608.bsp
reading c:\program files\steam\steamapps\common\portal 2\sdk_content\maps\1612638608.prt
LoadPortals: couldn't read c:\program files\steam\steamapps\common\portal 2\sdk_content\maps\1612638608.prt

**Comment by DeliWasTaken** [comment]
What version and what UCPs?

**Comment by KaziPlays** [comment]
v4.38.1

The UCPs are:

Ben's Slightly Odd Additions, Radelite's Package, and Vertical Doors.

**Comment by FrozenDragon0** [comment]
The UCP's haven't been updated for v4.38.1 as far as I recall. Remove all the UCP items and compile the map.

**Comment by KaziPlays** [comment]
Okay.
