### ISSUE TITLE
Too many objects cause memory leak and/or "unrefreshed voids" only within goo pits. Nowhere else.

### ISSUE THREAD

**Issue by RepellentSpy** [BEEmod/BEE2-items#3630]
Hello,
I'm gonna start off by saying I almost don't understand memory leaks. Not even sure if I used the right term here.

Basically, if I place a bit too many objects with a custom style, this happens.
It works fine otherwise. It only affects the goo pits. Nothing else looks weird.
![image](https://user-images.githubusercontent.com/37275455/107147784-2d1b5c00-6950-11eb-86d9-997b0e6c52a0.png)

The level always builds just fine, but does this.
No clue what to do with it.

**Comment by Luke18033** [comment]
There's a [leak](https://developer.valvesoftware.com/wiki/Leak) in your map. Try removing any items from custom packages to see if they're the cause of the leak. If the issue persists, go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.

Also note that BTS style is very buggy and partially unsupported, so you should probably just avoid using it.
