### ISSUE TITLE
Lifeform Sensor not activating.

### ISSUE THREAD

**Issue by XtraXD1** [BEEmod/BEE2-items#3631]
When I pass through a Lifeform Sensor it beeps, but in the Console, the next error appears:

CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
VScript error: DoEntFire was passed an invalid entity instance.

I was using BEE2 4.38.1 when the bug ocurred.

**Comment by Luke18033** [comment]
Duplicate of #3463
