### ISSUE TITLE
Portal Gun Activation Fields

### ISSUE THREAD

**Issue by MarcusKubis9** [BEEmod/BEE2-items#3636]
the portal gun deactivator/activator would be like the paint gun deactivator/activator but for portals

you could make it so you have a blue portal gun then it switches to an orange portal gun

now for the new portal gun pedestal items

The first one: fake portal gun pedestal it would be like the portal gun pedestal but it has no portal gun in it

The second one: no portal gun it would be like the portal gun but with no portals so it would act like a troll portal gun

**Comment by Konclan** [comment]
Duplicate of #2561
