### ISSUE TITLE
New Announcers: Mike and Eric from Portal Prelude and virgil and AEGIS from portal stories mel

### ISSUE THREAD

**Issue by Bloodstrike2003** [BEEmod/BEE2-items#3637]
I don't know why but I think that there should be more announcers than just.. you know. so yeah. [you may delete this if you want or I'll delete it if not a good idea.]

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#can-you-add-custom-voicelines--voicelines-from-mod-x-to-bee24

**Comment by seagemgames** [comment]
Mike and Eric are just TTS anyway, and Virgil/AEGIS go against the PS:M developers' wishes of not using those characters...

**Comment by Bloodstrike2003** [comment]
understood
________________________________
