### ISSUE TITLE
Stairs and Vactubes doesn't work.

### ISSUE THREAD

**Issue by Bloodstrike2003** [BEEmod/BEE2-items#3639]
So when I place the stairs down I get an error that says Build Error. And not only that, Vactubes does the same thing when I tried to put them in an angle or something. but appearently they work when they're in a straight line.

**Comment by LautaroL20** [comment]
Both issues are fixed in the next release.

**Comment by seagemgames** [comment]
For the stairs, Uncheck Style/Item Properties > Items > Default Test Elements > Allow Block Stairs.

**Comment by Bloodstrike2003** [comment]
oh

**Comment by Bloodstrike2003** [comment]
sorry

**Comment by Bloodstrike2003** [comment]
god i'm stupid
