### ISSUE TITLE
Fizzlers causing a compile error since the latest portal 2 update

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3641]
Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 2052, in main
  File "connections.py", line 905, in calc_connections
ValueError: "dfizz89_modelStart89" is not a known instance!
[12156] Failed to execute script compiler_launch

**Comment by Luke18033** [comment]
The new Portal 2 update fixed fizzler emitters not animating in Puzzlemaker maps, by giving the instances the correct names. But that now causes BEE2 compiles to fail since the compiler can't find the broken instance name to apply the fix itself.

**Comment by TheRedStar95** [comment]
You guys have the same problem like me, with the Modded Fields ? (The Purple, Orange, Yellow, Green & Gray ?).

**Comment by Lolbinhos** [comment]
How we solve this problem?

**Comment by Lolbinhos** [comment]
> You guys have the same problem like me, with the Modded Fields ? (The Purple, Orange, Yellow, Green & Gray ?).

Yes

**Comment by TheRedStar95** [comment]
> > You guys have the same problem like me, with the Modded Fields ? (The Purple, Orange, Yellow, Green & Gray ?).
> 
> Yes

We need to wait a updated version, don't worry. It's in Works in progress.
