### ISSUE TITLE
enable able and disable able lights

### ISSUE THREAD

**Issue by MarcusKubis9** [BEEmod/BEE2-items#3642]
the enable able and disable able light item would have 4 versions for the lights one of them is invisible lights and maybe the person that made the ucp with the rainbow light could add the input and maybe an invisible version? or you could add this in

description: it does what it sounds like it would have an input

options: color changer (if you add the rainbow light)

map: these are probably really easy to make or find,

**Comment by Luke18033** [comment]
I am honestly out of ideas for where to put the FAQ to get people to read it.
