### ISSUE TITLE
Cube Button is invisible in Overgrown Style

### ISSUE THREAD

**Issue by TheRedStar95** [BEEmod/BEE2-items#3645]
![image](https://user-images.githubusercontent.com/79364424/108598232-c3a63f00-738c-11eb-8ca8-9bdecce66907.png)

**Comment by lillabofinken** [comment]
Is like that with the default theme as well

**Comment by KaziPlays** [comment]
a fix for this is to get the model and the texture from the package and replace the broken ones with it

**Comment by Luke18033** [comment]
Does the same happen with the sphere button?

**Comment by KaziPlays** [comment]
Nop

**Comment by KaziPlays** [comment]
> Is like that with the default theme as well

Nop

**Comment by KaziPlays** [comment]
I know It's a problem with the exported, because replacing them manually fixes the problem.

**Comment by CardsAndGamesYT** [comment]
this was 6 months ago XD, when is it going to be fixed

**Comment by Luke18033** [comment]
I'm not really sure why it happens...

**Comment by CardsAndGamesYT** [comment]
makes sense

**Comment by Luke18033** [comment]
Sphere buttons are apparently invisible as well, not sure why it took this long to get reported...
![image](https://user-images.githubusercontent.com/19228201/141886488-b54432fb-c81b-48c3-adae-2c789d9c152b.png)
It's probably the same underlying issue as this.

**Comment by Luke18033** [comment]
The faith plate model is also invisible? That seems to be a new one.
![image](https://user-images.githubusercontent.com/19228201/141886689-9a631a66-2bd4-4242-bdbc-50864c64b0ec.png)

**Comment by KaziPlays** [comment]
The sphere button was working

**Comment by KaziPlays** [comment]
Now It's not

**Comment by Luke18033** [comment]
........

There are old versions of these models in the Old Aperture package.....

**Comment by reubos** [comment]
> a fix for this is to get the model and the texture from the package and replace the broken ones with it

Do you have a guide for how to do this? I'm not very tech savvy but I want to be able to use the cube button in Overgrown maps

**Comment by TheGuard18** [comment]
I still have the issue with the button. I can't find a fix for it, pleas help me.

**Comment by CardsAndGamesYT** [comment]
> I still have the issue with the button. I can't find a fix for it, please help me.

the models are broken, you'll have to wait for one of the BEE Devs to fix it in a future update

**Comment by CardsAndGamesYT** [comment]
Seeing as Luke moved the issue from To Do to Done for the 4.42 update, I'm guessing it should be fixed in the next update
