### ISSUE TITLE
Item request - milky field

### ISSUE THREAD

**Issue by Godohwar** [BEEmod/BEE2-items#3648]
The milk field seen in the map Milky Ways is similar to the closed solid field but portals can be placed on its surface. it has been implemented in base p2 before and is just a nodraw_portable 1 unit above the fizzler texture brush. the fizzler has been seen here 
https://steamcommunity.com/sharedfiles/filedetails/?id=1208846904

**Comment by TeamSpen210** [comment]
As discussed on Discord, this fizzler is almost identical to the existing Closed Solid Field, and would be far more clear as a set of panel/pistons. We don't really need even more fizzlers.
