### ISSUE TITLE
"Show Triggers In-game" does not meets its funtion

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#365]
![show triggers ingame does not meet its funtion](https://cloud.githubusercontent.com/assets/12244376/13760479/2646f2da-ea12-11e5-981e-60b6980e7eb1.png)

**Comment by TeamSpen210** [comment]
What this should do is make triggers visible in-game, while in preview mode (set to spawn in corridors on the compile pane).

**Comment by Luke18033** [comment]
@TeamSpen210 It needs to be set to start in corridor and not elevator?

**Comment by TeamSpen210** [comment]
Yes.

**Comment by Luke18033** [comment]
@TeamSpen210 It needs to work when starting in the elevator.

**Comment by LautaroL20** [comment]
It looks like you fixed it, i was working during my latest playtest.
