### ISSUE TITLE
LMR/Normal Pedestal buttons are broken

### ISSUE THREAD

**Issue by seagemgames** [BEEmod/BEE2-items#3650]
**BEE2 version:** 4.39.0

**Description of the bug:**
Lautaro L/M/R and the default pedestal buttons do not accept inputs. This does not affect retractable buttons.

**Expected behavior:**
They accept connections

**Comment by Luke18033** [comment]
Possibly related to #3652 if data is being removed from EditorItems during export

**Comment by Krypt0nC0R3** [comment]
on version 4.39.1 is still relevant
