### ISSUE TITLE
Buoyant Cube

### ISSUE THREAD

**Issue by Notsoartificialintelligence** [BEEmod/BEE2-items#3651]
This would be dispensed like a normal cube and functions like a normal cube, but floats on Water and Goo. The player will be able to stand on the floating cube to use as a platform, and behaves lighter than a normal cube (i.e. farther fling distance and falls slower)

A puzzle example centred around this concept could be a series of mini-puzzles where the player has to obtain Buoyant Cubes to reach other cubes and puzzles before passing a goo moat to reach the exit door.

In terms of design, the cube would appear similar to a regular cube, but the Aperture logo has been replaced with arrows that point upwards. (from dropper release)

**Comment by seagemgames** [comment]
That'd be a pain to implement, require goo to be changed and also be janky to jump on...

**Comment by Notsoartificialintelligence** [comment]
I'll try learning how to make UCPs and prototype it.
