### ISSUE TITLE
Items produce errors with any other item in the voxel

### ISSUE THREAD

**Issue by RustyNova016** [BEEmod/BEE2-items#3652]
**BEE2 version: 4.39.0**

**Description of the bug:**
Placing multiple objects in the same voxel is invalid
![image](https://user-images.githubusercontent.com/50844553/108626719-eea69680-7451-11eb-802c-41bc0a69a2a6.png)

**Expected behavior:**
The placement shouldn't be invalid

**Steps to reproduce:**
Just place two items in the same voxel

**Comment by seagemgames** [comment]
This is a puzzlemaker limitation.

**Comment by FrozenDragon0** [comment]
![image](https://user-images.githubusercontent.com/18079316/108626967-f71cc280-748d-11eb-837a-da33d7817f2a.png)

This is definitely a issue with the new version. Using my dev version and I can place these just fine without error.

**Comment by seagemgames** [comment]
Possibly an overgrown issue?

**Comment by FrozenDragon0** [comment]
@RustyNova016 Can you try clean style and see if the same issue persists?

**Comment by seagemgames** [comment]
Occurs in clean too.

**Comment by seagemgames** [comment]
Does not occur in 4.38.1, definitely a BEEmod issue

**Comment by RustyNova016** [comment]
Does not occur in vanilla too. I tried it while I was reinstalling BEE mod. It's not an installation bug

**Comment by Luke18033** [comment]
Weird, the `OccupiedVoxels` must be getting messed up during export.

**Comment by LautaroL20** [comment]
I think that this might be the commit that fixes this issue: https://github.com/BEEmod/BEE2.4/commit/27645d0e2774a4755534bde2a749bfc953ec54d0, so, this is now fixed in next release.
