### ISSUE TITLE
Portals/Portal Gun stylevars

### ISSUE THREAD

**Issue by CMSEv7** [BEEmod/BEE2-items#3653]
It will be interesting to have portal gun/portals stylevars, depending of the style of the map.
![800px-Scott_swirl_portals](https://user-images.githubusercontent.com/72353799/108639236-6a710500-748b-11eb-9040-ee3c3efda29d.jpg)
![800px-Cyan_and_purple_portals](https://user-images.githubusercontent.com/72353799/108639238-6d6bf580-748b-11eb-8fa2-79693fcd9378.jpg)
![800px-Vine_portals](https://user-images.githubusercontent.com/72353799/108639243-72c94000-748b-11eb-8de1-7a924571701f.jpg)

**Comment by Luke18033** [comment]
We can't override the portals in maps, and those designs don't work anymore in P2 anyway. Also see "no beta content" rule in the contributing guidelines.
