### ISSUE TITLE
Coop Checkpoints

### ISSUE THREAD

**Issue by Greypilgrim228** [BEEmod/BEE2-items#3656]
BEE2 version: 4.39.0

Similar to #3650 Coop Checkpoint and Separated Coop Checkpoint are encountering errors.

*Separated Coop Checkpoint won't allow any connection to it, and won't toggle "Start open/closed"
*Coop Checkpoint being placed anywhere stops the map being rebuilt and won't allow it to load past the "Building Geometry" stage before an error is reported. It will allow you to connect things to it however.

**Comment by Greypilgrim228** [comment]
Is this being ignored because I've lumped 2 co-op problems together?

**Comment by FrozenDragon0** [comment]
Just because none else has commented on here doesn't mean it's being ignored.

**Comment by Greypilgrim228** [comment]
oh ok, thanks. I was worried I'd violated one of the rules about reporting bugs.

**Comment by LautaroL20** [comment]
Actually, yes you had commited a combined issue post. It is like trying to report an issue about a Protruding Pedestal Button and another about the vanilla Pedestal Button and since they´re similar items, you just decide to combine them in one issue which is wrong.
