### ISSUE TITLE
specific cube triggers and buttons

### ISSUE THREAD

**Issue by MarcusKubis9** [BEEmod/BEE2-items#3658]
this would be a thing for the cube colorizer where if you put it under a button/cube trigger you would need a specific type of colored cube to activate it.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#can-you-add-the-ability-to-colorize-buttons-so-that-they-can-only-be-activated-by-a-matching-cube
