### ISSUE TITLE
Clean Style: Bad squarebeams shadows in  Co-op Exit corridor

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#366]
![screenshot](https://cloud.githubusercontent.com/assets/12244376/13754583/54825a5c-e9f6-11e5-83dd-51d932b9dec6.jpg)

**Comment by Konclan** [comment]
This seems like a very simple fix of just turning off the shadows of the square beams or adding a very dim light
![20190828211710_1](https://user-images.githubusercontent.com/16567080/63905225-370a0300-c9d9-11e9-83b6-e44ed6f5602c.jpg)

**Comment by Konclan** [comment]
Merging with #530
