### ISSUE TITLE
Coop Checkpoint being placed anywhere stops the map being rebuilt and won't allow it to load past the "Building Geometry" stage before an error is caused

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3662]
Original post by @Greypilgrim228 (https://github.com/BEEmod/BEE2-items/issues/3656) "Coop Checkpoint being placed anywhere stops the map being rebuilt and won't allow it to load past the "Building Geometry" stage before an error is caused. It will allow you to connect things to it however."

**Comment by Greypilgrim228** [comment]
Issue not present in 4.39.2 with 4.39.1 packages.

**Comment by LautaroL20** [comment]
Alright then.
