### ISSUE TITLE
Wheatley/Inferno Style

### ISSUE THREAD

**Issue by Bloodstrike2003** [BEEmod/BEE2-items#3664]
So, this style will have fire surrounding the test chamber, and instead of the pool of acid, It's fire. And the elevators are.. well fire surrounding it.

![1666877682_preview_620_20181108222128_1](https://user-images.githubusercontent.com/78393178/109405583-da1d3f00-7926-11eb-9800-11e6f5f4eee3.png)

and That is all. (Picture from Wheatley's Unscientific Tests part 3)

**Comment by Bloodstrike2003** [comment]
what have I done

**Comment by FrozenDragon0** [comment]
I can't see this being added. The fire would be too distracting due to the brightness, even then Wheatley style isn't in the works right now.

**Comment by Bloodstrike2003** [comment]
i knew this would happen

**Comment by Bloodstrike2003** [comment]
the things i tryed and failed

**Comment by Konclan** [comment]
This style is too complex and very unique to the hammer space. Wouldn't translate well to PeTI and the particles would probably cause performance issues. Stuff like this isn't easy to replicate and also I don't see many people using this style as it is a very one note deal.
