### ISSUE TITLE
Portalgun pedestal will cause "Failure To Compile" if an input is connected to it, or if it is set to Start Enabled

### ISSUE THREAD

**Issue by sf3d-dk** [BEEmod/BEE2-items#3667]
**BEE2 Version:** 4.39.1

vbsp.error.log :

[WARNING] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[WARNING] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "tim_start" for <item_bee2_scaffold_slot> (Valid: {'bee2_tim_start': 'instances/BEE2/clean/items/scaffold/tim_start.vmf'})
[WARNING] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:small" for vactube group BEE2_VACTUBES!
[WARNING] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:medium" for vactube group BEE2_VACTUBES!
[WARNING] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:large" for vactube group BEE2_VACTUBES!
[WARNING] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[WARNING] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[ERROR] cond.core.check_all(): Error in <Item ITEM_BEE2_PORTALGUN all_conf>:
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 511, in check_all
  File "precomp\conditions\__init__.py", line 300, in test
  File "precomp\conditions\__init__.py", line 289, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1092, in res_sub_condition
  File "precomp\conditions\__init__.py", line 300, in test
  File "precomp\conditions\__init__.py", line 289, in test_result
  File "precomp\conditions\brushes.py", line 108, in res_fix_rotation_axis
TypeError: type srctools._math.Matrix doesn't define __round__ method

video
https://youtu.be/edDs-gfpKPc

**Comment by Luke18033** [comment]
Seems to compile properly now, but the pedestal doesn't actually work.

**Comment by Luke18033** [comment]
Never mind, it works if set to one of the monoportal modes. Seems like that's a separate issue then.
