### ISSUE TITLE
Signage item doesn't have an overgrown texture in the in-game palette

### ISSUE THREAD

**Issue by RustyNova016** [BEEmod/BEE2-items#3671]
**BEE2 version: 3.9.2**

**Description of the bug:** In the in-game palette, the signage item doesn't have an overgrown texture in the overgrown theme

**Expected behavior:** In the app, the item has an overgrown texture, but not in game

**Steps to reproduce:** Add the signage item to the item list, and use the overgrown theme

**Additional information:** 

In app:
![image](https://user-images.githubusercontent.com/50844553/109433009-5179ce00-7a0e-11eb-9813-e5ba1b67b04b.png)

In game:
![image](https://user-images.githubusercontent.com/50844553/109433003-44f57580-7a0e-11eb-8e67-0fb8b5f4a52f.png)

**Comment by seagemgames** [comment]
That's odd, the file is there, but the connection one is missing.

**Comment by RustyNova016** [comment]
The connection signage is working thought. Only the regular signage doesn't have a texture.
