### ISSUE TITLE
Mel player model and custom portal gun model

### ISSUE THREAD

**Issue by MarcusKubis9** [BEEmod/BEE2-items#3675]
I think it's time we mix it up a bit how about the scraped Mel player model? and a custom portal gun modeled by one of you or the beemod fandom could model it in blender!

**Comment by seagemgames** [comment]
Read the [FAQ](https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md). Story related assets cannot be used from PS:M. Also, I don't think anyone's going to go out of their way to make a random custom portal gun for BEEmod.

**Comment by FrozenDragon0** [comment]
I don't see this happening. No point in either of these.

**Comment by Luke18033** [comment]
They were referring to Mel from the P2 beta I think, but that then falls under "no beta content".

**Comment by seagemgames** [comment]
Ah, they probably were.
