### ISSUE TITLE
randomly orientated 2x1 observation rooms 

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2-items#3677]
and they can compile with no problem

![20210304132337_1](https://user-images.githubusercontent.com/63530071/109901746-ac9d1080-7ced-11eb-88ee-f925484fee11.jpg)
![20210304132334_1](https://user-images.githubusercontent.com/63530071/109901770-b292f180-7ced-11eb-9ec4-ec3d2e6aec7e.jpg)
![20210304133236_1](https://user-images.githubusercontent.com/63530071/109902231-48c71780-7cee-11eb-8323-a630701706e9.jpg)
![20210304133240_1](https://user-images.githubusercontent.com/63530071/109902251-4e246200-7cee-11eb-908e-1234aff32952.jpg)
![20210304133249_1](https://user-images.githubusercontent.com/63530071/109902261-51b7e900-7cee-11eb-8a31-bdddff6e1c75.jpg)

**Comment by supersean08-pro** [comment]
yes they were placed
ᶦ ᵃᶜᵗᵘᵃˡˡʸ ˡᶦᵏᵉ ᵗʰᵉ ᵍˡᶦᵗᶜʰ

**Comment by supersean08-pro** [comment]
i have a strong feeling that this will be good and a great improvement for old aperture test chambers

**Comment by supersean08-pro** [comment]
> I'd assume these were placed using Unlock Default Items? We'll want to set `DesiredFacing` so they automatically orient the right way.

yes but now when i place them, they are still on 90. degree angles and no longer becoming random on a 0. 90. 180. 270. angles, and were they delete-able, because i cant delete placed ones

**Comment by supersean08-pro** [comment]
> I'd assume these were placed using Unlock Default Items? We'll want to set `DesiredFacing` so they automatically orient the right way.

![20210305102036_1](https://user-images.githubusercontent.com/63530071/110044108-ae71dd00-7d9c-11eb-8d19-0ecacff6429a.jpg)
![20210305102347_1](https://user-images.githubusercontent.com/63530071/110044252-ec6f0100-7d9c-11eb-8bb0-13eff6514e4c.jpg)
![20210305102355_1](https://user-images.githubusercontent.com/63530071/110044257-eed15b00-7d9c-11eb-93cb-3602e52bfae0.jpg)

**Comment by Luke18033** [comment]
What are you trying to show? We know what the bug is. Putting observation rooms on the floor is a Valve bug, you can do it with the small room in the vanilla puzzlemaker.

**Comment by supersean08-pro** [comment]
yes but a 1x2 on the floor

> What are you trying to show? We know what the bug is. Putting observation rooms on the floor is a Valve bug, you can do it with the small room in the vanilla puzzlemaker.

**Comment by Luke18033** [comment]
Yes, that is a Valve bug. Although BEE might add proper support for that variant at some point.

**Comment by supersean08-pro** [comment]
> Yes, that is a Valve bug. Although BEE might add proper support for that variant at some point.

okay

**Comment by TeamSpen210** [comment]
I've made variations for most styles for this, except for Overgrown I think. I need to release that.

**Comment by supersean08-pro** [comment]
> I've made variations for most styles for this, except for Overgrown I think. I need to release that.

oh cool, would the ones that are on the floor going to be holes for over grown and vertical ones on the wall would be holes showing the "behind the scenes"
