### ISSUE TITLE
Unstationary Scaffold Wall Emitters & Slots Can't Connect

### ISSUE THREAD

**Issue by H2ofiremaster** [BEEmod/BEE2-items#3678]
**BEE2 version:**
4.39.1

**Description of the bug:**
 When "Unstationary Scaffold Wall Emitters" and/or "Unstationary Scaffold Slots" are attached to "Unstationary Scaffold Piston Emitters" only the Piston Emitters will function, leaving separate platforms oscillating between the sets of connected Piston Emitters, with the slots and wall emitters only connected via Antlines.

**Expected behavior:**
The Wall Emitters/Slots to connect properly.

**Steps to reproduce:**

1. Have at least these items in your palette: 

- Unstationary Scaffold Slot
- Unstationary Scaffold Piston Emitter
- Unstationary Scaffold Wall Emitter

2. Place down and connect them in this order: 

- Slot
- Piston Emitter
- Piston Emitter
- Wall Emitter
- Piston Emitter
- Piston Emitter
- Slot

3. Compile and run the level

**Comment by BathWizard** [comment]
I did some testing and its the slots that don't work. The piston and wall emitters work fine. I just hope this is fixed soon.

**Comment by H2ofiremaster** [comment]
Strange, the wall emitters didn't work for me.

**Comment by Greypilgrim228** [comment]
Same, I can only get the pistons to work.
