### ISSUE TITLE
solid stairs use hd textures

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2-items#3681]
![20210303183517_1](https://user-images.githubusercontent.com/63530071/110098087-e6f0d580-7df3-11eb-995f-dc1ed06f8f9c.jpg)

**Comment by Luke18033** [comment]
Do piston stairs also have this problem, or just block stairs? I really hope my changes to this didn't get reverted again.

**Comment by supersean08-pro** [comment]
> Do piston stairs also have this problem, or just block stairs? I really hope my changes to this didn't get reverted again.

nope
![20210306074336_1](https://user-images.githubusercontent.com/63530071/110171578-09184100-7e50-11eb-9740-1def7b15f6c4.jpg)

so im guessing making items take so long cuz i gotta make a new issue that the glass panel in portal 1
