### ISSUE TITLE
toxic goo/gel do not render

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2-items#3682]
![20210305181750_1](https://user-images.githubusercontent.com/63530071/110099190-23710100-7df5-11eb-8ef4-f7d34b11e4f0.jpg)

**Comment by seagemgames** [comment]
You have a leak. You should ask on the Discord for help with this.

**Comment by supersean08-pro** [comment]
> You have a leak. You should ask on the Discord for help with this.

mk

**Comment by FrozenDragon0** [comment]
Have you solved this problem?

**Comment by supersean08-pro** [comment]
> Have you solved this problem?

not yet, just busy doing portal particles, after than, ill try fix this

**Comment by FrozenDragon0** [comment]
Closing this due to lack of response whether this problem was fixed.

**Comment by supersean08-pro** [comment]
> Closing this due to lack of response to whether this problem was fixed.

sorry i just use blender for quite some time, making a galaxy creator, and the reason why is because i was playing gmod, making addons and i could publish one right now.
![4kGalaxy](https://user-images.githubusercontent.com/63530071/139493916-4a42dfff-335b-42cd-9c02-2a73c5757dec.png)
outdated galaxy
and successfully making the crab nebula by using particles (accidentally)

**Comment by Luke18033** [comment]
That has nothing to do with BEE, this isn't a forum... Assuming you still have this map, open it in the Puzzlemaker and recompile it, then go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.
