### ISSUE TITLE
Angled Panels Details Offset

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2-items#3683]
Details that should be below the angled panel are floating above it.

![20210303185727_1](https://user-images.githubusercontent.com/63530071/110100053-17397380-7df6-11eb-94bd-e3dfb86f93c4.jpg)

**Comment by Konclan** [comment]
Duplicate #3679

**Comment by Konclan** [comment]
Wait shit its not

**Comment by Luke18033** [comment]
I think this is fixed?

**Comment by supersean08-pro** [comment]
> I think this is fixed?

i had no space on my laptop, that amount of time i created a galaxy creator

**Comment by Luke18033** [comment]
*What are you even saying?!*
