### ISSUE TITLE
fizzler that blocks lasers, bullets, and portals

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2-items#3684]
what it wont fizzle, portal projectile, human cubes turrets (after turret passes through, it would have no bullets), funnels, and all other things that I mention that can be fizzled

**Comment by Critfish** [comment]
We do not need any more new fizzlers. It's already confusing with all the fizzlers we have now.

**Comment by seagemgames** [comment]
I highly doubt they're going to add any new fizzlers. They just become more and more confusing. I'd suggest you make a UCP if you want more fizzlers.
Also, you should follow the template when you create an issue. It makes it much easier to read.

**Comment by FrozenDragon0** [comment]
There are plenty of custom fizzlers as it is, adding more is just going to make them more and more confusing.

**Comment by supersean08-pro** [comment]
> We do not need any more new fizzlers. It's already confusing with all the fizzlers we have now.



> I highly doubt they're going to add any new fizzlers. They just become more and more confusing. I'd suggest you make a UCP if you want more fizzlers.
> Also, you should follow the template when you create an issue. It makes it much easier to read.



> There are plenty of custom fizzlers as it is, adding more is just going to make them more and more confusing.

okay
