### ISSUE TITLE
New Item: Texture Selector

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3685]
It's kinda self-explanatory but I will explain what is this.

It's an item that you put on a wall, ceiling, floor or connect to an item that will change its texture;

But, how exactly will you choose the texture? Simple answer, Beemod will have a selection menu like the signage one in which you can choose any texture that is in the game. Not only textures can be selected, but you can also select decals and overlays as well.

To select a texture, use the timer to select in between 30 (I think that's correct) textures.

It is supposed to work like the cutouts in Beemod, and if you connect it to an item with textures like Panels, Door Frames, Blocks, etc, it will change to the desired texture

This will serve a purpose in many different ways, like:

1-Creating Rattman dens

2-Creating custom styles

3-Fixing the BTS Style Map Textures

and more.

**Comment by TeamSpen210** [comment]
BEEmod is not intended to be an "easier Hammer", this would be really awkward. A Rattman den really needs to be unique to offer any reward to the player, and needs more complex detailing. Similarly a "custom style" is a lot more than just swapping textures.
