### ISSUE TITLE
GLaDOS (Item Request)

### ISSUE THREAD

**Issue by lazytspo** [BEEmod/BEE2-items#3686]
**Description of the feature:**
Based on the Central AI GLaDOS.

**This should be implemented because:**
She wants you to make sure to add it to its custom chamber.

**Additional information:**

**Comment by LautaroL20** [comment]
It is a shame that the labels wouldn't get transfer among the issue when I move it.

**Comment by lazytspo** [comment]
and i don't have hammer editor

**Comment by LautaroL20** [comment]
LOL. 

You get it by downloading Portal 2: Authoring Tools - Beta. It is located in Steam Library/Tools.
