### ISSUE TITLE
Glass Panels in Portal 1 causes "Failure To Compile"

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2-items#3689]
VBSP failed.

[I] vbsp.main(): BEE2 v4.39.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] options.load(): Extra config options: {'remove_pedestal_plat': '1', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[I] vbsp.mod_entryexit(): Setting SP Exit to 2
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: True
[I] brushLoc.read_from_map(): Analysed map, filling air... (18 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] instanceLocs.get_subitems(): Invalid custom instance name - "tim_start" for <item_bee2_scaffold_slot> (Valid: {'bee2_tim_start': 'instances/BEE2/clean/items/scaffold/tim_start.vmf'})
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:small" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:medium" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:large" for vactube group BEE2_VACTUBES!
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[W] packing.pack_list(): Packlist "PACK_BEE2_P1_PLASTIC_NOPAINT" does not exist!
[I] vbsp.set_elev_videos(): Elevator type: NONE
[I] voice_line.add_voice(): Adding Voice Lines!
[I] voice_line.add_voice(): Adding Base instance!
[I] voice_line.add_voice(): Quote events: []
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): "ENTRY": 1/15 quotes..
[I] voice_line.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_1"
 | 	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
 | 	}
 | 
 |___

[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): Line "??" is disabled..
[I] voice_line.find_group_quotes(): "EXIT": 1/5 quotes..
[I] voice_line.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_WADDLE"
 | 	"Choreo" "scenes/npc/glados/testchambermisc12.vcd"
 | 	}
 | 
 |___

[I] voice_line.find_group_quotes(): "MIDCHAMBER": 0/9 quotes..
[I] voice_line.add_voice(): 0 Mid quotes
[I] voice_line.add_voice(): Done!
[I] vbsp.anti_fizz_bump(): Adding Portal Bumpers to fizzlers...
[I] vbsp.anti_fizz_bump(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): ---------------------
[I] cond.core.check_all(): Conditions executed!
[I] cond.core.check_all(): Map has attributes: ['spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3995, misses=329, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'doorcameras': False, 'p1_doorless_entry': True, 'p1_old_dissolve': True, 'p1_ported_pgun': True, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': True, 'nomidvoices': True, 'unlockdefault': True, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/bee2/p1/color_correction.vmf', 'instances/BEE2/p1/set_portalgun.vmf', 'instances/BEE2/p1/set_dissolve.vmf'}
[I] music.add(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] tiling.generate_brushes(): Generating tiles...
[I] tiling.generate_brushes(): Generating goop...
[I] vbsp.change_overlays(): Editing Overlays...
[I] barriers.make_barriers(): Adding Glass floor beams...
[I] barriers.make_barriers(): Done!
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Feb  9 2021)
[I] <valve>.vbsp(): 8 threads
[I] <valve>.vbsp(): Using shader api: shaderapiempty.dll
[I] <valve>.vbsp(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/p1/items/angled_pan/glass_panel.vmf
[I] <valve>.vbsp(): 
[I] BEE2_config.save(): Saving changes in config "C:\Users\super\AppData\Roaming\BEEMOD2\config\compile.cfg"!

**Comment by Luke18033** [comment]
Seems to be fixed, but now they leak.
