### ISSUE TITLE
Dirty props for the Overgrown Observation Rooms

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2-items#3691]
https://gamebanana.com/skins/176441
the skin is not mine
![530-90_5e978f868dd58](https://user-images.githubusercontent.com/63530071/110232130-0280eb00-7f70-11eb-9d03-473917489e24.jpg)

**Comment by Konclan** [comment]
Nobody would see these, where would they go?

**Comment by supersean08-pro** [comment]
> Nobody would see these, where would they go?

observation rooms, and people would see them when a 1x1 observation rooms are on the floor

**Comment by DeliWasTaken** [comment]
Observation rooms look terrible on the floor, and these are such a small detail that it really doesn't add much to anything.

**Comment by supersean08-pro** [comment]
> Observation rooms look terrible on the floor, and these are such a small detail that it really doesn't add much to anything.

i just think its a nice little addition

**Comment by LautaroL20** [comment]
Yep, these would look good in the overgrown observation rooms.

**Comment by Luke18033** [comment]
I don't think this is really necessary, who is actually going to notice these? Packed content increases the map's file size, we shouldn't waste that on tiny details that most people won't notice.

**Comment by supersean08-pro** [comment]
> I don't think this is really necessary, who is actually going to notice these? Packed content increases the map's file size, we shouldn't waste that on tiny details that most people won't notice.

noclipers

**Comment by FrozenDragon0** [comment]
@supersean08-pro And why would people waste their time noclipping into observation rooms just for tiny details like these?
