### ISSUE TITLE
Portal 1: Empty chamber won't build

### ISSUE THREAD

**Issue by NeoKat75** [BEEmod/BEE2-items#3692]
**BEE2 Version:** 4.39.2

<details>
<summary>Error Log</summary>

VBSP failed.

Valve Software - vbsp.exe (Mar  2 2021)
4 threads
Using shader api: shaderapiempty.dll
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/p1/elevator_sp/door_frame_black.vmf
</details>

**Comment by Luke18033** [comment]
Have you exported since the last P2 update? That instance isn't used anymore, so this would indicate that you're missing the BEE compilers.

**Comment by NeoKat75** [comment]
Could've sworn I did that. But it works now, Thank you!
