### ISSUE TITLE
More fizzlers

### ISSUE THREAD

**Issue by DigitexStudios** [BEEmod/BEE2-items#3693]
**Description of the item:**

**Matter Destruction Field**
- Destroys: Cubes, turrets, cameras, other objects.
- Allows: Lasers, light bridges, tractor beams, energy pellets, portal shots.
- Blocks: Gels, some gels may get past if allow streaks is enabled.
- Configurable for players.

**Energy Absorption Field**
- Destroys: Energy pellets.
- Allows: Cubes, turrets, cameras, gels, other objects, players.
- Blocks: Lasers, light bridges, tractor beams.
- Configurable for portals

**Portal Blocker**
- Destroys: Portals.
- Allows: Everything else.
- Blocks: Portal shots.
- Acts like a normal fizzler, but does not destroy physics objects, only affects portals.

**Invisible Fizzler**
- Destroys: Same as normal fizzler.
- Allows: Same as normal fizzler.
- Blocks: Same as normal fizzler.
- Acts exactly like a normal fizzler.
- Configurable for appearance

**Switchable Fizzler**
- Acts like a normal fizzler, but an input switches it to a laserfield, and vice versa

**Item options:**

**All**
- Start Enabled - whether the fizzler starts active.
- When placing, size can be changed like normal fizzlers.

**Matter Destruction Field**
- Hazard Type - Player behavior (Fizzler by default, Fizzler = Allow, Laserfield = Kill)

**Energy Absorption Field**
- Cube Type - Portal behavior (Cube by default, Cube = Allow portal shots and portals, Reflection = Block portal shots only, Companion = Block portal shots and erase portals, Sphere = Erase portals only, Franken = Unused)

**Invisible Fizzler**
- Cube Type - Appearance (Weighted by default, Weighted = Completely invisible, Cube = Field visible and emitters invisible, Sphere = Emitters visible and field invisible)

**Switchable Fizzler**
- Hazard Type - Initial state (Fizzler by default, Fizzler = Starts as fizzler, Laserfield = Starts as laserfield)

**Source:**
Invisible fizzler - Companion Cube chamber of SP in Portal 2, when you try to bring the cube with you

**Additional information:**

**Comment by FrozenDragon0** [comment]
We do not need more fizzlers they will just get more confusing.

**Comment by DigitexStudios** [comment]
Clarification:
The matter destruction field acts similarly to the fizzler, but allows portal shots and does not erase portals.

The switchable fizzler is intended for use with a regular input instead of the A/B input in BEE.

And you’re right, looking back the invisible fizzler seems kind of useless.

**Comment by FrozenDragon0** [comment]
@DigitexStudios In that case the Matter destruction field is essentially the same as the Matter Inquisition field just with a laser field option.

Switchable fizzler still can't be done with regular inputs, If I recall the Death fizzler was meant to use the regular connections but it broke if using regular connections hence the reason why it uses A/B inputs.

Eitherway I still don't see the other fizzlers being added as stated we have too many fizzlers as it is.

**Comment by DigitexStudios** [comment]
Alternatively, is there a way I could make them just on my side? Maybe copy FourthReaper's fizzlers and make my own with custom properties?

If so, how could I do this?

**Comment by DigitexStudios** [comment]
OK, my own addon is here: https://github.com/DigitexStudios/BEE2-Addons
