### ISSUE TITLE
Crusher Replacement (1950)

### ISSUE THREAD

**Issue by DutchBaller** [BEEmod/BEE2-items#3695]
**Replace The Crusher With Flamethrowers In 1950 Like in 1960**

**_Provide a clear and concise description of what you want to happen._**
I want the crusher in the 1950 style to be replaced with a flamethrower instead like 1960.

**_Explain what problems this feature would solve, or otherwise why it should be implemented._**
This will solve I guess some timeline problem because 1950 (Crusher) 1960 (Flamethrower) 1970 (Crusher) 1980 (Crusher)
it just doesn't make sense for it to switch from crusher to flamethrower then crusher. Making 1950 also a flamethrower like 1960 would just make sense.

**_Provide any additional information that might be helpful._**
_No Additional information_

**Comment by Luke18033** [comment]
The plan is to eventually make flamethrowers a separate item, instead of having them as a crusher style variant.
