### ISSUE TITLE
Make Triggers Place able Anywhere

### ISSUE THREAD

**Issue by DutchBaller** [BEEmod/BEE2-items#3696]
Make Triggers Able To Be Placed Anywhere

**_Provide a clear and concise description of what you want to happen._**
Currently triggers can't float in the air when you remove the ground below them or the ceiling or wall etc. I want them to be able to be placed anywhere basically ignore all collision or requirements for them to be a specific way.

**_Explain what problems this feature would solve, or otherwise why it should be implemented._**
This should help people with map making because you can now place triggers on top of panels and make floor traps and other things.

**_Provide any additional information that might be helpful._**
_No Additional information_

**Comment by Critfish** [comment]
This is most likely a puzzlemaker limitation. They can't modify the puzzlemaker interface itself.

**Comment by Luke18033** [comment]
Yeah, every item is hardcoded to require an attachment surface (annoyingly). There are some plans for things that would allow you to work around this like an "intangible scaffold" item, but those aren't being worked on yet.

**Comment by seagemgames** [comment]
This is indeed a puzzlemaker limitation. If you'd like, you can place two triggers across the area you want, and connect them. this extends the trigger to a bigger box and allows you to place a trigger across it.

On the other hand, it's possible to make an item that removes a surface using SetTile, and placing those over a voxel supporting the trigger.
