### ISSUE TITLE
Make Floor Pits a Item

### ISSUE THREAD

**Issue by DutchBaller** [BEEmod/BEE2-items#3697]
Make floor pits a item

**_Provide a clear and concise description of what you want to happen._**
Make a separate version of toxic goo that is a floor pit probably will only be able to be used on the bts and clean styles.

**_Explain what problems this feature would solve, or otherwise why it should be implemented._**
This will make maps a lot more interesting and fun to play and make.

**_Provide any additional information that might be helpful._**
_Additional information:_ Choose the size of floor pits in the items tab on style/item properties.

**Comment by seagemgames** [comment]
This is planned. Bottomless pits were removed as of 4.37 (?) and are due for a rework.

**Comment by Luke18033** [comment]
They'd likely still replace goo though, I'm not sure why you'd want both?

**Comment by seagemgames** [comment]
> They'd likely still replace goo though, I'm not sure why you'd want both?

Also, custom goo items are impossible as it's hardcoded anyway.

**Comment by FrozenDragon0** [comment]
@seagemgames Bottomless pits aren't removed, they are simply disabled.

**Comment by seagemgames** [comment]
Eh "removed and due for a rework" is about the same.

**Comment by Luke18033** [comment]
They're basically removed, the redesigned pits will be totally rewritten and have a completely different configuration.

**Comment by DutchBaller** [comment]
Well I can't wait for that rework

**Comment by seagemgames** [comment]
Well, you'll have to... there's not much choice, unless you were to rewrite parts of the compiler to generate these new pits.

**Comment by DutchBaller** [comment]
> Well, you'll have to... there's not much choice, unless you were to rewrite parts of the compiler to generate these new pits.

I was saying it like that cause that's what people say when they are really excited for something

**Comment by seagemgames** [comment]
Ah, the "well" made it seem like you were impatient, haha.

**Comment by DutchBaller** [comment]
yea

**Comment by Konclan** [comment]
There are plans to make an exterior chamber generator which will have a lot of style options but I don't think it will need its own item

**Comment by Luke18033** [comment]
Yeah, as I said above, goo will probably just become an open hole similarly to how it did with 3D skyboxes.
