### ISSUE TITLE
2 New Items: Magnetic items from Magnetic Demo (1 and 4)

### ISSUE THREAD

**Issue by Bloodstrike2003** [BEEmod/BEE2-items#3698]
1. Magnetic Panel: A panel that attracts all the physical objects nearby. May turn on or off.
2. Magnetcubes: This cube generates a magnetic field around itself, thanks to which the cube is able to attract other objects to itself at a distance. (those descriptions borrowed from the maps, I'm so sorry for that, plz forgive me.)

But zero gravity and global gravitational field I don't think they can work cuz... how?

(and I know it's 2 items and not just 1 but... y'know. So that is all)

![mymaps_magnetic_demo1_thumb](https://user-images.githubusercontent.com/78393178/110903245-fec8cd80-82bb-11eb-9399-32db985c3ddb.jpg)
![mymaps_magnetic_demo4_thumb](https://user-images.githubusercontent.com/78393178/110903246-ff616400-82bb-11eb-9177-8cc8af6af2d3.jpg)

**Comment by SCIENTIST2004** [comment]
dublicate of #3552 ?

**Comment by FrozenDragon0** [comment]
Yes it is a duplicate. Also do not suggest multiple items/features in one issue.

**Comment by Bloodstrike2003** [comment]
What is wrong with me.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
