### ISSUE TITLE
Use Aperture: Salt Mines assets for Old Aperture Lasers

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#3699]
Reflection Cube:
![20210312130738_1](https://user-images.githubusercontent.com/35931028/110962878-1f476500-835a-11eb-96ed-d64c8eeb2866.jpg)
Laser Catcher:
![20210312130746_1](https://user-images.githubusercontent.com/35931028/110962917-29696380-835a-11eb-8b1c-e7313b4f95d3.jpg)
Laser Emitter:
![20210312130723_1](https://user-images.githubusercontent.com/35931028/110962983-38501600-835a-11eb-814e-5d3ec0c706e4.jpg)
I saw them here:
 https://steamcommunity.com/sharedfiles/filedetails/?id=2418919385

**Comment by LautaroL20** [comment]
Nice!

**Comment by Luke18033** [comment]
I was going to ask if we could use these, they definitely look a lot nicer than the current models.

**Comment by Bloodstrike2003** [comment]
cool

**Comment by supersean08-pro** [comment]
> I was going to ask if we could use these, they definitely look a lot nicer than the current models.

i could try to do the laser particle if you want

**Comment by Luke18033** [comment]
We don't really need to change the particles, and I'm not even sure if it's possible to override vanilla particles in maps.

**Comment by FrozenDragon0** [comment]
The laser particle I'm sure can be changed and packed into the map but the issue is the laser itself we cannot change that.

**Comment by Luke18033** [comment]
We can now pack particles into maps (supposedly - I still haven't seen anyone actually do it yet). But we probably can't *replace vanilla particles*, only add new ones, just like how it is with materials and models. Again, I don't think custom particles are really even necessary here.

**Comment by Konclan** [comment]
We cannot use these models until A:SM is released since the models were made specifically for that mod.

**Comment by Luke18033** [comment]
We have different old aperture laser models now, so we no longer need these
