### ISSUE TITLE
Energy Storage Cube

### ISSUE THREAD

**Issue by Bloodstrike2003** [BEEmod/BEE2-items#3700]
Like the normal cubes it can be set down on a button. but it can also be charged up for a limited time. (and will require a charging station and a slot thing)
![20210312234619_1](https://user-images.githubusercontent.com/78393178/111023339-57b46680-838d-11eb-9284-c9c32357cf0d.jpg)
![20210312234657_1](https://user-images.githubusercontent.com/78393178/111023341-584cfd00-838d-11eb-985c-6781911011dd.jpg)

(and that is all)

(Item from Portal: Skylines)
https://gamebanana.com/maps/178892

**Comment by Bloodstrike2003** [comment]
i am somewhat suprised nobody even commented on this

**Comment by supersean08-pro** [comment]
> i am somewhat suprised nobody even commented on this

i know man

**Comment by Bloodstrike2003** [comment]
> > i am somewhat suprised nobody even commented on this
> 
> i know man

like... why?

**Comment by Bloodstrike2003** [comment]
> > > i am somewhat suprised nobody even commented on this
> > 
> > 
> > i know man
> 
> like... why?

but i'd like to hear your thoughts on this

**Comment by FrozenDragon0** [comment]
@Bloodstrike2003 Just because none comments on an issue but it's still open doesn't mean that it's being ignored.

**Comment by Bloodstrike2003** [comment]
oh

**Comment by Konclan** [comment]
This is not a forum, unless people have something important to say about the issue small discussion is left to the discord.

**Comment by Bloodstrike2003** [comment]
i know

**Comment by Bloodstrike2003** [comment]
and what about the Energy Storage Cube?

**Comment by Bloodstrike2003** [comment]
i'll just close it down then..

**Comment by seagemgames** [comment]
It's still possible to be added, and maybe a UCP maker might come along and add it. If your idea isn't closed within a few days, or said to be impossible/unreasonable, it's better to keep it open, since it may be added *sometime* in the future.

**Comment by Bloodstrike2003** [comment]
alright

**Comment by Konclan** [comment]
Its a neat concept but their function is kind of similar to bomb cubes but slightly less versatile? Maybe better as a UCP item.
