### ISSUE TITLE
Asking some questions and suggesting some features & items.

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3702]
Note: I know that here isn't the place for questions, but I wanted to ask here for that more people see.

First, I'm gonna ask the questions.

1- Why did you guys remove the breakable glass from BEE2? (I've heard it was in BEE2 but was removed, not sure if it's true); (ANSWERED)

2- Is there another item you guys removed from BEE2?;
(ANSWERED)

3- Are you ever going to add stuff from the Blue Portals mod for Portal 1 to BEE2?;
(ANSWERED)

4- I've checked the "Reimplement Items" Issue and I didn't see one thing someone said they were going to add, the Electric Zones from Portal: Still Alive and Portal: The Flash Version. Are you guys going to add it?. (ANSWERED)

Features:

1- A thing I saw on Rexaura is that the Positronic Energy Orb had a moving feature, it moved forward and backwards, so, I want that in BEE2; (ANSWERED)

2- Add an option to choose as player: Portal 1 Chell and Mel (Unused, Portal 1); (ANSWERED)

3- Add a option to Vactubes that makes they move cubes through them, as decoration or (read 4th);

4- This one connects to the 3rd one. Add a "Breakable" option to Vactubes, like in the Portal 1 Escape where you find a broken Vactube and ride it, and where you break a Vactube using a Rocket Turret to get a cube;

5- Add a Cave Johnson picture to the Monitor item when chosen his voice. The picture varies with the time it's in. On the Old Aperture style, the picture varies with the time it's in, same as before;

6- Add a separate item for Portal 1 wall lights or add more options for Portal 1 wall lights, like a move option for the big square lights, not being in the middle all the time.

And finally: Items.

It's only one.

1- Skull Box: It's the Skull Box from Portal: Still Alive, it works similar as the Bumble Ball, it follows you by not looking at it, but if it catches up to you, you instantly die. It follows you by teleporting (If you are far away.) and by rolling normally. It works just as a normal cube, it can activate floor buttons.

**Comment by SCIENTIST2004** [comment]
Answers:
1. They didn't remove it. It will be implemented later
2. will not be implemented: Animal King; Wall Feature; Torch; Choreo Box; Portal 1 Wall 
3. Yes they are
4. I think yes

**Comment by SCIENTIST2004** [comment]
Features:
1. it's already implemented 
2. as I know PSM developers don't want their conent in workshop maps

**Comment by KaziPlays** [comment]
I changed it to Portal 1 Mel

**Comment by KaziPlays** [comment]
I Changed it into Portal 1 Chell & Mel

Mel: 
![Mel](https://user-images.githubusercontent.com/72144613/111206299-f4058580-85a6-11eb-9602-577cd616e1d6.png)

**Comment by SCIENTIST2004** [comment]
perhabs not, but it's not exactly

**Comment by KaziPlays** [comment]
Cool beans.

**Comment by SCIENTIST2004** [comment]
I'm a little messed up with 3 and 4 answers but now it's fixed

**Comment by Luke18033** [comment]
**This is not a forum**, wanting more people to see your questions is not a valid excuse.
