### ISSUE TITLE
Portal 1 Chell as a playable character

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3703]
Self-explanatory.

**Comment by supersean08-pro** [comment]
Duplicate of #536

**Comment by supersean08-pro** [comment]
im sure this was a duplicate of something

**Comment by supersean08-pro** [comment]
https://github.com/BEEmod/BEE2.4/issues/536

**Comment by KaziPlays** [comment]
I'm pretty sure I can find something that can help do this.

**Comment by KaziPlays** [comment]
https://gamebanana.com/skins/180693

**Comment by KaziPlays** [comment]
Just put that onto BEE2 and call it Portal 1 Chell

**Comment by KaziPlays** [comment]
I've actually seen somewhere a Portal 1 chell skin For Portal 2 but I can't find it.

**Comment by seagemgames** [comment]
It's still a duplicate.
