### ISSUE TITLE
Enhancements for Vactubes.

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3704]
1- A option to Vactubes that makes they move cubes through them, as decoration or (Read 2nd);

2- This one connects to the 1st one. Add a "Breakable" option to Vactubes, like in the Portal 1 Escape where you find a broken Vactube and ride it, and where you break a Vactube using a Rocket Turret to get a cube.

**Comment by KaziPlays** [comment]
I made an Oopsie

**Comment by KaziPlays** [comment]
It's fixed.

**Comment by Konclan** [comment]
These have most certainly been suggested already

**Comment by Konclan** [comment]
Duplicate of #1988 and #1
