### ISSUE TITLE
Cave Johnson on Monitor

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3705]
Add a Cave Johnson painting to the Monitor item when chosen his voice. The painting varies with the time it's in. On the Old Aperture style, the painting varies with the time the style is in, same as before.
Multiverse Cave is random.

**Comment by supersean08-pro** [comment]
isnt he dead and just a computer

**Comment by KaziPlays** [comment]
The picture is the painting from each decade.

**Comment by FrozenDragon0** [comment]
This wouldn't make much sense having a painting watching you through monitors.
