### ISSUE TITLE
Portal 1 Light strips bug

### ISSUE THREAD

**Issue by lillabofinken** [BEEmod/BEE2-items#3709]
instead of getting the portal 1 lighting holes I get the normal lightstrips and they have the weird flickering effect that happens when 2 textures are in the exact same place

sorry about the last post.

![20210317003000_1](https://user-images.githubusercontent.com/80794755/111393127-6f0a9100-86b8-11eb-85dd-6450cbe035ea.jpg)

**Comment by supersean08-pro** [comment]
i do remember posting this issue but its closed so what gives

**Comment by FrozenDragon0** [comment]
@supersean08-pro Because one you posted that issue in the wrong section.

Two.  It was multiple issues in one post which we don't allow. That just makes it confusing for people to tell which problem is fixed and what isn't.

**Comment by megascatterbomb** [comment]
I am having this issue as well. Using BEEMod 4.39.2 with the 4.39.1 packages on Windows 10 64 bit, Portal 1 styling. Can reproduce with new and existing chambers. The visual bug does not affect the Franken-type light strip (used to invisibly route antlines).

**Comment by thefurrywolf** [comment]
> instead of getting the portal 1 lighting holes I get the normal lightstrips and they have the weird flickering effect that happens when 2 textures are in the exact same place
> 
> sorry about the last post.
> 
> ![20210317003000_1](https://user-images.githubusercontent.com/80794755/111393127-6f0a9100-86b8-11eb-85dd-6450cbe035ea.jpg)

its called z-fighting
and I am having the same problem with the hole lights

**Comment by thefurrywolf** [comment]
also i have a video of this




https://user-images.githubusercontent.com/81545837/114495546-1ce35f80-9bd3-11eb-95f2-f99b512eaf5e.mp4
