### ISSUE TITLE
Autportal not working

### ISSUE THREAD

**Issue by lillabofinken** [BEEmod/BEE2-items#3710]
Auto portals does not work, I have tried having it enabled and disabled and rotated differently but they won't turn on.
I have tried it in portal 1 theme, overgrown theme and in the default theme

![20210317002555_1](https://user-images.githubusercontent.com/80794755/111393656-72eae300-86b9-11eb-916b-8e0201386a27.jpg)

**Comment by deli73** [comment]
Also experiencing this issue, autoportals refuse to acitvate under any conditions we've tried

**Comment by supersean08-pro** [comment]
using any options with the auto portal, will still make it disabled

**Comment by FrozenDragon0** [comment]
Duplicate of: https://github.com/BEEmod/BEE2-items/issues/3672#issuecomment-800723455
