### ISSUE TITLE
some models don't load

### ISSUE THREAD

**Issue by covermode** [BEEmod/BEE2-items#3711]
i use the latest release version of bee and bee packages

this issue seems to occure in every version of bee >= 4.37. what should i do to prevent it from happening?
![изображение](https://user-images.githubusercontent.com/46962144/111434002-d3f9d180-8720-11eb-9812-7d7b41dae940.png)
![изображение](https://user-images.githubusercontent.com/46962144/111434024-de1bd000-8720-11eb-8c56-4e7948fda226.png)

**Comment by FrozenDragon0** [comment]
Looks like you have a leak. Also I really do not recommend version 4.37 it's really buggy. Either use V39.1 or V36.

**Comment by covermode** [comment]
i used v39.1 
also i figured out that that leak was caused by chamberlock item when it was leading to small 1x1 area that was supposed to be the next part of the chamber. expanding that area and placing light strips in it fixed that issue. and everything was ok.
thx anyway

**Comment by FrozenDragon0** [comment]
Ah well in that case I believe the chamberlock bug is already been reported.
