### ISSUE TITLE
Underground Chamberlock Doors are Broken

### ISSUE THREAD

**Issue by Devteam35** [BEEmod/BEE2-items#3712]
Whenever I use the chamberlock door in any of the the Underground Apeture themes, It just opens into the wall it is placed on. There is no way through, and the only way I found to get around this is to use two regular doors and a fizzler.
![20210317090342_1](https://user-images.githubusercontent.com/80826885/111480248-2b3f7800-8708-11eb-86fe-e07e24258d4f.jpg)
![20210317090354_1](https://user-images.githubusercontent.com/80826885/111480261-2da1d200-8708-11eb-8b42-7d12860e6663.jpg)

**Comment by Devteam35** [comment]
This is in the wrong issues category.

**Comment by seagemgames** [comment]
Not a compile error, that was why they closed this. It should be removed.

**Comment by LautaroL20** [comment]
It seems that this happens again... (see https://github.com/BEEmod/BEE2-items/issues/4052)

**Comment by FrozenDragon0** [comment]
@LautaroL20 Safe to say that this issue isn't fixed.
