### ISSUE TITLE
The Underground Chamberlock Doors are Broken

### ISSUE THREAD

**Issue by Devteam35** [BEEmod/BEE2-items#3713]
This is in Bee2 version 4.39.2.
Any chamberlock doors I use in the underground themes open into the wall they're placed on, and become impassable.
I expected the chamberlock door to act exactly how it says it should: "An exit door combined with a fizzler and some triggers, so it will lock closed after the player walks through."
I set the map's theme to the 80's and 50's, set up the chamberlock door exactly how I should, then ran the map. When I get to the door, I see this:
![20210317090342_1](https://user-images.githubusercontent.com/80826885/111482572-6773d800-870a-11eb-815f-39d4b5cc6c0d.jpg)
I deleted it, replaced it, and reset the map. It gave me the same result.
The map doesn't report this as an error for some reason,
![20210317090354_1](https://user-images.githubusercontent.com/80826885/111482758-98eca380-870a-11eb-8ee9-97f4eabacdde.jpg)

**Comment by FrozenDragon0** [comment]
What was wrong with this: https://github.com/BEEmod/BEE2-items/issues/3712 ? This issue is a duplicate.
