### ISSUE TITLE
Antimatter Absorption Field

### ISSUE THREAD

**Issue by H2ofiremaster** [BEEmod/BEE2-items#3716]
**Description of the item:**
A custom fizzler with the following properties:

- Players - Fizzles the player's portals when they pass through but allows the player itself
- Portal shots - Blocks
- Physics Objects - Allows

(Basically, a fizzler that only affects portals)

**Item options:**
Connect To... - To toggle the field on and off
Hazard Type - Does nothing, but it's required to be there on custom fizzlers to prevent crashes (at least I think so)

**Source:**
None

**Additional information:**

**Comment by Luke18033** [comment]
We're not adding any more fizzlers that just block or allow certain things.

**Comment by H2ofiremaster** [comment]
Ok
