### ISSUE TITLE
3d-factory skybox error

### ISSUE THREAD

**Issue by ebartaus** [BEEmod/BEE2-items#3717]
hello. sorry for my french, i use yandex. translate. i'm using bee2 version 4.39.1, and I have a 3d factory skybox and clean style installed. however, after the build, the skybox is displayed as a normal clean. strange....,,.,.,,.,,.,,...,,,,.,.,...

![image](https://user-images.githubusercontent.com/72306717/111955367-71c31700-8afa-11eb-8e8e-714aaf6241b9.png)

**Comment by LautaroL20** [comment]
If you are referring that that skybox is not producing the bottomless pit when using deadlygoo, thats on purpose because that feature is disabled, awaiting for a rework.

**Comment by FrozenDragon0** [comment]
Bottomless pits are currently disabled for the time being.
