### ISSUE TITLE
Portal 2 doesn't like me putting stuff that makes portals 

### ISSUE THREAD

**Issue by ZenyX64** [BEEmod/BEE2-items#3718]
Not sure how else to explain it, so sorry for the weird title. Anyway, I found an issue with the portal gun pedestal and the autoportal. While the autoportal just wouldn't activate no matter what I did, trying to build a test chamber where the portal gun pedestal started activated or was connected to something that activated it, it would just say there was an error building the chamber. Everything else seems to be working fine.

**Comment by ZenyX64** [comment]
i'm sorry, i'm new, and i don't know how to get to the "items section" that you're talking about.

**Comment by FrozenDragon0** [comment]
@ZenyX64 I have already transferred the issue to the correct repository.
