### ISSUE TITLE
New Style: Above Aperture

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3719]
Note: This has nothing to do with the Above Aperture mod for Portal 2, I didn't have any other name for it.

The style is clean but with a touch of overgrown. Some of the walls, floor, and ceiling are dirty, while others are clean.

It has nature, like the Overgrown style.

It has its own skybox, it can be used in other styles, the skybox is a sunny sky.

The light strips are holes in the wall, like Portal 1, except that instead of white, cold, or warm light, it is a hole that goes to the skybox, passing sunlight through it.

The observation rooms are grating windows like Old Aperture, but they have sunlight just like the light strips.

If the skybox is different, like BTS or Testing Sphere, it will show the selected thing instead. Lights through the holes and windows too.

If you choose Clean or Portal 1 Skybox, the windows and light strips will be BTS or Portal 1 BTS outside.

The items are a mixture of Overgrown and Clean, you choose which ones are dirty and clean when creating the style.

Place vines, leaves, nature, coming out of the windows and holes in the wall as decoration.

The entrance and exit corridors can be catwalks outside, you can see the sunny sky, some other parts of Aperture Science, other Test Chambers, etc.

The elevator is inside, so it's not too difficult to do.

I had this idea and wanted to share, I hope you put this style on BEE.

Hope it's not too difficult!

**Comment by seagemgames** [comment]
So it'd essentially be less-overgrown overgrown? Seems pretty redundant...

**Comment by KaziPlays** [comment]
It's tests on the surface basically

**Comment by KaziPlays** [comment]
@seagemgames As Cave Johnson Said "Science isn't about "why?", it's about "why not?"" Why wouldn't you have Test Chambers on the Surface?

**Comment by Luke18033** [comment]
> @seagemgames As Cave Johnson Said "Science isn't about "why?", it's about "why not?"" Why wouldn't you have Test Chambers on the Surface?

![gordon](https://media.discordapp.net/attachments/263051316073332736/786958136979882014/freeman-speaks.png)

**Comment by Luke18033** [comment]
This sounds really similar to Overgrown, and I think we should work on making the existing styles look nicer before adding new ones.

**Comment by Godohwar** [comment]
> @seagemgames As Cave Johnson Said "Science isn't about "why?", it's about "why not?"" Why wouldn't you have Test Chambers on the Surface?
> 
> Edit: There are no Johnsons in my family.

cave quote ):
