### ISSUE TITLE
Reflection gel interaction with light bridges

### ISSUE THREAD

**Issue by ZenyX64** [BEEmod/BEE2-items#3723]
I think it would be really nice if light bridges covered by reflection gel would reflect lasers, instead of the lasers just going through the bridges. It is a very niche interaction which isn't very commonly used, but it is just such a missed oppurtunity.

**Comment by LautaroL20** [comment]
Unfortunately, making light bridges to reflect lasers once they are coated by this gel would imply having access to the Valve´s source code.

**Comment by ZenyX64** [comment]
I see, thanks for the lightning fast clear response.
