### ISSUE TITLE
P1 Track Platform Rendering

### ISSUE THREAD

**Issue by Cosmiscient** [BEEmod/BEE2-items#3724]
**BEE2 version:** 4.39.1

**Description of the bug:** The portal 1 unstationary scaffold doesn't render right. It moves back and forth and functions just fine, but the arm under the lift is bugged.

**Steps to reproduce:** Place the unstationary scaffold ( portal 1 style ) in a chamber and change the "Cube Type" to "Companion" or "Reflective," all other types seem to work.

**Additional [information:**]
![Screenshot (217)](https://user-images.githubusercontent.com/42079031/113087539-d6910800-91b1-11eb-85c3-2eb481fc2c58.png)
![Screenshot (218)](https://user-images.githubusercontent.com/42079031/113087541-d7c23500-91b1-11eb-8719-df24e47b68e5.png)
![Screenshot (219)](https://user-images.githubusercontent.com/42079031/113087543-d8f36200-91b1-11eb-9aa2-bccf82eb2cbe.png)
![Screenshot (220)](https://user-images.githubusercontent.com/42079031/113087546-d98bf880-91b1-11eb-8654-073e837d0ab0.png)

**Comment by Cosmiscient** [comment]
I'm so sorry- this is my first post on github, how do I give it the "portal 1" label?

**Comment by Luke18033** [comment]
Not directly related to this issue but we should probably rename this variant to not be called "unstationary scaffold", given that that's an entirely unrelated item.
