### ISSUE TITLE
music trigger

### ISSUE THREAD

**Issue by ebartaus** [BEEmod/BEE2-items#3725]
hi, sorry again for my german, i use yandex.translate. i have an idea for a new item - a music change trigger. it will, based on the name, change the music. in it, you can select music by timer, the music itself will change when the player enters the trigger area, or when activated using triggers, buttons, laser receivers, and so on. my vision of the interface is shown in the picture:
![Аннотация 2021-03-31 152944](https://user-images.githubusercontent.com/72306717/113144534-041f9500-9236-11eb-8d19-1071172ecd19.png)
as you can see, there are four music slots for each tick. when the trigger is activated, one of the songs will be randomly selected and played. if the user has added only one song, only that song will be played on this tick.

the item, in addition to selecting the tick, will have the option "enabled from the beginning". if it is enabled, the song will not loop, but only overlap with the previous music, and will stop after the end of the song.

that's all, thank you for your attention

**Comment by FrozenDragon0** [comment]
This is somewhat similar to what the old beemod had in regards to using the timer option and changing the music with it. It didn't work quite well.
