### ISSUE TITLE
Pedestal Button Placement Variability

### ISSUE THREAD

**Issue by Cosmiscient** [BEEmod/BEE2-items#3726]
**Description of the feature:** As of right now, it's impossible to let a pedestal button sit on the same objects turrets are able to sit on. I feel like pedestal buttons should be able to sit on top of half-block gratings ( since they can't move ) but also, victory lifts, unstationary scaffolds, and half/full 90 degree angled panels. The pedestal button wouldn't move with them of course, I feel like that'd be a different item, or a ton of work to just automatically attach the pedestal button's movement to whatever it's sitting on. If the button sits awkwardly in the air at some point during the test, I think that would be on the test creator for not using the feature correctly. I also think if pedestal buttons could just sit on top of nothing without a compile error it would fix the issue since then anything could be under it.

**This should be implemented because:** It would add a lot more freedom and variability to the look and feel of tests using pedestal buttons.

**Additional information:** If I could have it my way, every object would count certain walls and items as a floor, just like turrets do now, but I believe pedestal buttons are variable enough to be a good place to start.
![Screenshot (226)](https://user-images.githubusercontent.com/42079031/113201237-472e3800-9237-11eb-9c67-aa879d96068f.png)

**Comment by SCIENTIST2004** [comment]
Also Floor Buttons and Conductive Plates would be very good to put on pistons

**Comment by SCIENTIST2004** [comment]
And also would be very nice to have this option on all block items with all items

**Comment by Cosmiscient** [comment]
I'm assuming that #3241 would be the solution to most situations like this. After TeamSpen said "We don't have any way to control which items can mount onto others" I may as well close this one myself.

**Comment by TeamSpen210** [comment]
There's two options you can set: `canAnchorOnGoo`, and `canAnchorOnBarriers` (everything else). Both fail for any items other than cubes/turrets that have collisions, and they can cause crashes if the item has antlines and isn't next to a wall.
