### ISSUE TITLE
Block Placement on 1/4 Walls

### ISSUE THREAD

**Issue by Cosmiscient** [BEEmod/BEE2-items#3727]
**Description of the feature:** Blocks would be able to recognize the "1/4 black/white wall" as an anchor, just like the glass hole item can sit on top of glass.

**This should be implemented because:** This would allow anyone to change the width and thickness of the wall at any point. I believe it would work better than giving the "1/4 black/white wall" more types since it would allow for more creative freedom and always prevent blocks from being placed in midair since there would always be a minimum width. If it's all placed on a 1/4 wall, it would have to be attached to something solid and extend from there. It would allow anyone to get creative with their walls.

**Additional information:**
- I would also love all items with "block" in the name to be able to recognize victory lifts, unstationary scaffolds, and half/full 90 degree angled panels as a floor, but I don't care about that feature nearly as much since it's very specific. Just having block placement on 1/4 walls alone would fix a ton of issues.
- 1/4 Wall name / description may have to be changed to fit this. Maybe "solid wall" to highlight it can be more than just 1/4? And in the description it notes the default is 1/4 width?

![Screenshot (229)](https://user-images.githubusercontent.com/42079031/113203311-e81df280-9239-11eb-992b-a80b9399fe91.png)
![Screenshot (230)](https://user-images.githubusercontent.com/42079031/113203327-ea804c80-9239-11eb-9d25-07223a605435.png)
![Screenshot (231)](https://user-images.githubusercontent.com/42079031/113203332-ebb17980-9239-11eb-9eda-504860ce81ed.png)
![Screenshot (233)](https://user-images.githubusercontent.com/42079031/113203341-ed7b3d00-9239-11eb-96c1-bedf8d838548.png)

![Screenshot (235)](https://user-images.githubusercontent.com/42079031/113203608-3f23c780-923a-11eb-8fab-80349f343e5e.png)
![Screenshot (234)](https://user-images.githubusercontent.com/42079031/113203615-4054f480-923a-11eb-9e59-c0c26dfec4d3.png)

**Comment by TeamSpen210** [comment]
We don't have any way to control which items can mount on others, it's hardcoded into the editor.
