### ISSUE TITLE
Old Portal Gun (SUGGESTION)

### ISSUE THREAD

**Issue by ThatOneRetro** [BEEmod/BEE2-items#3729]
Perhaps for Old Aperture style, you could allow the test chamber to change your portal gun to the old backpack 1950s portal gun or the Portal Stories Mel portal gun to match with the style (as if it actually is 1950s and not abandoned).

**Comment by ThatOneRetro** [comment]
On second thought, limiting this to only old aperture wouldn't be a great idea

**Comment by Critfish** [comment]
This wouldn't serve any real purpose for puzzles or visuals. The only way I can see this being useful for maps is for "story maps" - something that BEEMod, and the puzzlemaker in general, isn't built for.

The Mel devs don't want other modders to use a select few of their assets, one of which being the 1970's Portal Gun.

**Comment by ThatOneRetro** [comment]
I know, it would just fit the vibe. It doesn't matter, it's just an extra thing to go with the style

**Comment by FrozenDragon0** [comment]
We are not allowed to use Mel's portal gun as the developers have specifically stated they do not want Virgil/Aegis + voicelines or the mel gun to be used at all. Please read the Beemod FAQ.
