### ISSUE TITLE
The Turret Target Cube

### ISSUE THREAD

**Issue by Cosmiscient** [BEEmod/BEE2-items#3732]
**Description of the item:** The Turret Target Cube would have a tiny target icon on every side in place of the aperture logo, and force turrets ( within its line of sight ) to fire at it constantly. Turrets would prioritize the cube over the player. It will explode after too much sustained fire.

**Item options:** It would have a pedestal button timer, which would determine how long it would take in seconds for a single turret to destroy it. Multiple turrets will speed up how long this takes, as it'll affect how quickly damage is being dealt to the cube. If set to infinite, it can never be destroyed.

**Additional information:** For readability purposes, the front of the cube ( the side facing the player when it's picked up ), and only the front of the cube, will reflect the setting. This being the infinity symbol, 1, 2, 7, 14, and so on.
If a turret has to decide between a turret target and a turret target cube, it'll prioritize the turret target. I believe this would allow for far more possibilities for test solutions.

It would also be wonderful to apply this same concept to all other cube variants of this item, to have turret target reflection cubes, and turret target spheres. Both could lead to some pretty incredible test solutions, but in terms of the workload, I understand this is wishful thinking.

**Comment by Konclan** [comment]
UCP
