### ISSUE TITLE
Portal 1 GLaDOS on monitor.

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3733]
Self explanatory.

Description:

When Portal 1 GLaDOS voicelines selected, add her on the monitor screen.

I think this is already planned but I wanted to confirm.

**Comment by KaziPlays** [comment]
If this is planned but not done yet, I'll contribute by making it myself, then sharing it on here

**Comment by FrozenDragon0** [comment]
This would be a duplicate of https://github.com/BEEmod/BEE2-items/issues/2021

**Comment by KaziPlays** [comment]
Actually this is mot a duplicate, this one only makes p1 glados appear if the P1 glados lines are selected.
