### ISSUE TITLE
Compile error in BTS style (TypeError: Expected unicode, got special) (4.39.0)

### ISSUE THREAD

**Issue by seagemgames** [BEEmod/BEE2-items#3739]
Version: 4.39.0

Used Style: BTS
Used Items: Entry door, Exit door and Large Observation room in the default chamber

Log: https://pastebin.com/sBMGrGCn

I couldn't find any other issues with a similar log.

**Comment by AeroGas** [comment]
So someone know how to solve it?

**Comment by LautaroL20** [comment]
Nope.

**Comment by AeroGas** [comment]
> 
> 
> Nope.

Oh. So we can't use BTS style for now?

**Comment by LautaroL20** [comment]
You will need to wait for the next beemod update.

**Comment by FrozenDragon0** [comment]
Isn't this issue a duplicate of https://github.com/BEEmod/BEE2-items/issues/3720 ?

**Comment by LautaroL20** [comment]
Yep, but that issue is closed and should be re-open.

**Comment by FrozenDragon0** [comment]
This would be a duplicate of https://github.com/BEEmod/BEE2-items/issues/3720

**Comment by seagemgames** [comment]
That's a duplicate of this...

**Comment by FrozenDragon0** [comment]
Yes but the issue I mentioned has a lower number.
