### ISSUE TITLE
Autoportal bug!!!!

### ISSUE THREAD

**Issue by AeroGas** [BEEmod/BEE2-items#3740]
Hi,
I was making a map and it seems the autoportal dosen't work.
There are the screenshots:

![1](https://user-images.githubusercontent.com/82058507/113886553-11ea9280-97c1-11eb-914a-b2671d30ba4e.png)

![2](https://user-images.githubusercontent.com/82058507/113886560-131bbf80-97c1-11eb-9196-664f9d504655.png)

Please help! PS: I don't know how this bug is happening.

**Comment by FrozenDragon0** [comment]
Duplicate of: https://github.com/BEEmod/BEE2-items/issues/3672
