### ISSUE TITLE
P1 Styled Surface Marker.

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3743]
The Portal 1 Style Surface Marker could be an X.

It's used only on Portal 1's Test Chamber 16 (I think)

Here are some photos of them:

![X 01](https://user-images.githubusercontent.com/72144613/114281586-8453b080-9a15-11eb-9ccb-0e6d1ed64ee6.PNG)

![X 02](https://user-images.githubusercontent.com/72144613/114281590-887fce00-9a15-11eb-8a82-2ed8fa702142.PNG)

![X 03](https://user-images.githubusercontent.com/72144613/114281593-8d448200-9a15-11eb-8bed-f1c6a9de4a65.PNG)

Just to have a Marker in P1 Style.

**Comment by seagemgames** [comment]
It could probably be done with Konclan's 1/4 tile texture.

**Comment by Konclan** [comment]
#1096
