### ISSUE TITLE
Old Aperture left-middle-right pedestal buttons are modern

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2-items#3745]
**BEE2 version:** 4.39.2 with 4.39.1 packages

**Description of the bug:** Pedestal buttons in Old Aperture styles use the model from New Aperture buttons

**Expected behavior:** The buttons should use the Old Aperture model

**Steps to reproduce:** Choose any Old Aperture style, place a pedestal button and compile the map

**Additional information:** Tested on 1980s and 1970s
![PORTAL 2 - Direct3D 9 11_04_2021 17_53_51](https://user-images.githubusercontent.com/68685620/114311964-3613df80-9af1-11eb-9183-70ab4e31b36e.png)

**Comment by FrozenDragon0** [comment]
1970's is definitely a bug, but as for 1980's I believe it's intentional as 1980's was starting to move over to the modern facility.

**Comment by HeimlichLaboratories** [comment]
Ok, here's a theory: maybe this only happens with left-middle-right buttons, as I currently use them as my default pedestal buttons.

**Comment by FrozenDragon0** [comment]
@HeimlichLaboratories Can you please place all 3 of those pedestal buttons and see if they are the problem? Also place down a regular pedestal button.

**Comment by TeamSpen210** [comment]
It'll be specific to those, I found another bit of wrong code in the styled instance logic.

**Comment by HeimlichLaboratories** [comment]
I tested it - only happens with left-middle-right pedestal buttons. All other types of pedestal buttons (even custom ones) work fine. Additionally, regarding your comment about 1980s, in the 1980s style description it says: "...according to signs, prototypes of cubes, buttons *except pedestal buttons* are used". So I think it's also a bug

**Comment by LautaroL20** [comment]
Unfortunately, I can no longer give support to any of my items until @TeamSpen210 finds a solution for the application crash on Windows 7 (see issue: https://github.com/BEEmod/BEE2.4/issues/1520).
