### ISSUE TITLE
Idea: Portal Gun Pedestal voicelines

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2-items#3748]
**Description of the feature:** It would be nice if new voicelines related to the Portal Gun pedestal were implemented.

**This should be implemented because:** It would add extra detail to chambers and would fit in Overgrown style, like when Wheatley guides you.

**Additional information:** These are the voicelines I had in mind:

Wheatley:

Level Entry:

"There should be a portal device on that podium over there"

"There should be a portal device on that podium over there. I can't see it, though. Maybe it fell off... Do you want to go and have a quick look?"

"Hello? Can you see the portal gun?"

On Portal Gun pickup:

"Hello? Can you see the portal gun? Also, are you alive?"

"Oh, brilliant" You DID find a portal gun!"

Level Exit: 

"Oh, brilliant! You DID find a portal gun! You know what? It just goes to show: people with brain damage are the real heroes in the end aren't they?"

"I'm -- do you know what I'm gonna do? I'm going to work on the assumption that you're still alive and I'm just going to wait for you up ahead"

GLaDOS:

Level Entry:

"The dual portal device should be around here somewhere. Once you find it, we can start testing. Just like old times."

On Portal Gun pickup:

"Good. You have a dual portal device. There should be a way back to the testing area up ahead."

NOTE: The GLaDOS lines would only work with the Dual portal gun pedestal, not the blue only or the orange only.

**Comment by HeimlichLaboratories** [comment]
I'm perfectly fine with my issue being closed, but please give an explanation when you do so.

**Comment by Konclan** [comment]
We're not really looking to add too many more voicelines.

**Comment by HeimlichLaboratories** [comment]
Really? Because someone just made an issue with a ton of extra glados voicelines and nobody said anything.

**Comment by Luke18033** [comment]
It's mainly mid-chamber lines that we don't want to add more of, they usually end up being pretty repetitive.
