### ISSUE TITLE
Allow Surface Marker to apply to piston platforms

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2-items#3749]
**Description of the feature:** Since the Sphere and Franken types of the lift are unused, it would be helpful if you could use them to choose between the surface marker and the checkered tiles texture.

**This should be implemented because:** The portalable lift chooses betweent the two textures randomly and sometimes is annoying because it makes it look ugly. Since there's 2 unused variants, it's perfect to give the creator more options to avoid ugly design.

**Additional information:**

**Comment by Luke18033** [comment]
You'd just get those by putting the surface marker item at the base of the platform.

**Comment by HeimlichLaboratories** [comment]
Still though, it's random whether it chooses the surface marker or checkered tile texture. I was creating a map just today and I placed three portalable pistons on a row and they all had the Surface Marker texture. Which looked bad. The point of this is to allow players to be able to choose the standard portal surface, with the additional ability to use alternate textures to highlight areas.

**Comment by Luke18033** [comment]
Yeah, just the way that would be done is by placing the existing surface marker item on top of the existing portalable piston platform, rather than adding two entirely new variants.

**Comment by HeimlichLaboratories** [comment]
Yeah, yeah, I misunderstood your reply the first time. Well, I thought that the variants idea was more practical; but if it can't be done, it can't be done. Tbh, as long as the portalable lift has the standard white texture I will be happy.
