### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by anymaker3333** [BEEmod/BEE2-items#3752]
in the ver 4.39.2 & packages 4.39.1 :    1.portal magnet crush the game     2.autoportal dont open.     3. portal gun cannot be activated to spin around.         4.if conveyor belt is on the map,it crushes textures and sounds of surroundings.    its all i know for now about this ver

**Comment by FrozenDragon0** [comment]
1. Do not post multiple problems in one issue, that just makes it harder to tell what issues are fixed.

2. Do not just name a issue "issue" Explain what the actual issue is.

3. These issues you have posted have already been reported.

**Comment by anymaker3333** [comment]
ok


пт, 23 апр. 2021 г. в 15:30, >:FrozenDragon:< ***@***.***>:
