### ISSUE TITLE
 another bugs in 4.39.2

### ISSUE THREAD

**Issue by anymaker3333** [BEEmod/BEE2-items#3754]
1.conveyor belt crush textures of water and crush the sound if surroundings
2.portal gun stand cannot be spinning. if you connect,=issue=error building
3.autoportals dont open
4.catwalk will crush the game if try to pull surface under it
5.button cube has no texture in overgrown style

**Comment by anymaker3333** [comment]
ok


пт, 23 апр. 2021 г. в 16:38, Lautaro ***@***.***>:

**Comment by FrozenDragon0** [comment]
@anymaker3333 You literally posted 3 issues from your previous post into this one making this also a duplicate.

**Comment by anymaker3333** [comment]
Sorry for that. i'll try to republish each other


сб, 24 апр. 2021 г. в 02:05, >:FrozenDragon:< ***@***.***>:
