### ISSUE TITLE
Portal Gun Upgrade Station

### ISSUE THREAD

**Issue by somedoodest** [BEEmod/BEE2-items#3755]
**Description of the item:** A half-grid-wide recession in the wall it's placed on containing a Portal Gun Pedestal with a unique, yellow skin and text which reads "Upgrade Station". Grabbing the Portal Gun on the pedestal will switch your Portal Gun to the Upgrade Station's Button Type, regardless of which Portal Gun type you have. Can be enabled and disabled, controlling whether the gun can be grabbed or not.
![image](https://user-images.githubusercontent.com/34423155/115906573-fab9cf00-a467-11eb-89d2-886aba94fdc9.png)

**Item options:** Start Enabled (controls if it can be grabbed immediatly or if it needs to be activated, checked by default), Button Type (controls which type of Portal Gun is in the Pedestal, use regular Pedestal variants, uses Weighted by default).

**Source:** Factum Solus: Episode 2, link: https://www.moddb.com/mods/factum-solus

**Additional information:** The "Forces your gun to be this item's Button Type even if you have a different type" part of this could be implemented into the regular Pedestal, but the "Control whether the gun can be grabbed" part can't be, since Start Enabled already controls whether the Pedestal shoots portals.

**Comment by TheEnderek0** [comment]
Just saying that this will be available in my UCP soon.

**Comment by Konclan** [comment]
UCP
