### ISSUE TITLE
Portal 1 Autoportal Model for Clean

### ISSUE THREAD

**Issue by somedoodest** [BEEmod/BEE2-items#3763]
**Description of the feature:** Switch the Clean style's Autoportal Emitter model to the Portal 1 model, perhaps with a modified "cleaner" texture.
![image](https://user-images.githubusercontent.com/34423155/116467207-b9625e80-a86f-11eb-9340-1d95f045fdcc.png)

**This should be implemented because:** The currently-used Clean style Autoportal Emitter model is from Portal 2's first chapter, which takes place in an Overgrown setting where everything is in a destroyed, dirty state. It makes sense for this model to be in a destroyed, barebones state - it fits the setting. However, the Clean style is meant to be cleaned up and repaired, so it makes no sense for the autoportals to be in this barebones, destroyed state in that style. The Portal 1 model would fit for Clean, as it is in a  undamaged / repaired state. Additionally, the original, unused PeTI icon for it uses a P1-style model.
![image](https://user-images.githubusercontent.com/34423155/116469177-15c67d80-a872-11eb-8d4c-06f9928d2670.png)

**Additional information:** If this gets added, add a Stylevar to revert it to the Portal 2 model, for people who like it more. Maybe add an "on" skin for it aswell, like Blue Portals does.
(example for Blue Portals' "on" skin)
![image](https://user-images.githubusercontent.com/34423155/116467756-5624fc00-a870-11eb-80ee-91269d2fd322.png)

**Comment by seagemgames** [comment]
Doesn't the clean autoportal use a P2 style autoportal emitter?

**Comment by somedoodest** [comment]
Yeah it does, and i'm saying it should be switched to the Portal 1 model.

**Comment by HeimlichLaboratories** [comment]
The P2 autoportal model has nothing to do with the fact that it's overgrown. It should be a stylevar, or the model should just be kept.

**Comment by Luke18033** [comment]
Yeah, it's not meant to be the internals of the emitter or anything, they just changed the design like other things in P2. The texture is slightly dirty, but that's not really noticeable unless you specifically look for it.

**Comment by HeimlichLaboratories** [comment]
By the way, about Portal 1, what about the beta autoportal frames? I read somewhere that beta content couldn't be added, but I thought I'd ask.

**Comment by FrozenDragon0** [comment]
Some Beta content can be added but we're not going to do that.

**Comment by Luke18033** [comment]
The early autoportal frame texture is in the final game (and even survived into P2), so they'd be easy to recreate, but they don't really belong in a style which is otherwise entirely based on final P1.
