### ISSUE TITLE
Retractable Floor Button has an unremoved Areaportal within Overgrown causing Void Clipping

### ISSUE THREAD

**Issue by Shards-Box** [BEEmod/BEE2-items#3766]
Pictured below is the Retractable Floor Button causing Void Clipping within the level, this bug only occurs within the closed state and will be removed as soon as the RFB so as long as the button is not within the ground, the Void Clipping won't occur.

![20210501102545_1](https://user-images.githubusercontent.com/83502177/116783332-c39b7d00-aa68-11eb-8262-5df6918e1ba1.jpg)

**Comment by seagemgames** [comment]
Does this cause a leak or just a visible nodraw? (Does goo fail to render?)

**Comment by Shards-Box** [comment]
> 
> 
> Does this cause a leak or just a visible nodraw? (Does goo fail to render?)
Not sure the difference but it I think its Visible No-Draw as the goo does fail to render but if removed, can view the floor below though said No-Draws

**Comment by Luke18033** [comment]
There's probably an areaportal there which is closing, not taking into account the missing tiles.

**Comment by TeamSpen210** [comment]
Yeah it has an areaportal, I need to remove that for Overgrown.
