### ISSUE TITLE
Weighted Cube Dropper Connections Error

### ISSUE THREAD

**Issue by Shards-Box** [BEEmod/BEE2-items#3771]
**BEE2 Version:** 4.39.1 (Latest as of 05-03-2021)

<details>
<summary>Error Log</summary>
VBSP failed.

[I] vbsp.main(): BEE2 v4.39.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] options.load(): Extra config options: {'remove_pedestal_plat': '1', 'voice_pack': 'BEE2_GLADOS_P1'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "precomp\connections.py", line 591, in calc_connections
KeyError: 'cd101849'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 1868, in main
  File "precomp\connections.py", line 593, in calc_connections
ValueError: "cd101849" is not a known instance!
[18884] Failed to execute script compiler_launch
</details>

**Additional information:** This error only occurs when a dropper within the level has a connection of power while also having auto-drop enabled, unsure if this is a BEE2 mod bug or is just something Portal 2 does when a dropper has auto-start enabled while also having a connection, but I'll report it here anyways just in-case this is something BEE2 is breaking

**Comment by Konclan** [comment]
I believe this has been fixed in recent versions, if not let me know
