### ISSUE TITLE
Panel piston platforms always generate with 4x4 textures

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2-items#3774]
**BEE2 version:** Dev

**Description of the bug:** Horizontal P1 piston platforms always generate with 4x4 textures. For black walls this looks okay, but on white walls the 4x4 texture is only meant to be used in special cases when it's needed, so this looks pretty bad:
![image](https://user-images.githubusercontent.com/19228201/116935585-6562cb80-ac1b-11eb-8dea-2ee69acfd702.png)
I'm not sure if/how this applies to other styles.

**Expected behavior:** Horizontal P1 piston platforms should use normal wall textures.

**Steps to reproduce:** Just place a P1 piston platform on a wall and switch it to one of the panel variants.

**Comment by thesamfizz** [comment]
I believe this isn't exclusive to the P1 style in 4.39.2, happens in clean and overgrown too.
