### ISSUE TITLE
Unstationary Scaffold Items cause compile error

### ISSUE THREAD

**Issue by LonelyPortalFan** [BEEmod/BEE2-items#3777]
I was using the Unstationary Scaffold, and when i tried to compile, It gave a compile error, i got this bug in Every single theme.

**Comment by FrozenDragon0** [comment]
You need to provide a console log aswell. We cannot fix a compile error without a console log.

**Comment by LonelyPortalFan** [comment]
Ok, this was the console log :
 [I] vbsp.main(): BEE2 v4.39.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] options.load(): Extra config options: {'glass_scale': '0.05', 'voice_pack': 'BEE2_WHEATLEY'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (5 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 4
[I] vbsp.mod_entryexit(): Setting SP Exit to 3
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (118 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 1897, in main
  File "precomp\texturing.py", line 706, in setup
  File "srctools\vmt.py", line 120, in parse
  File "srctools\_tokenizer.pyx", line 151, in srctools._tokenizer.Tokenizer.__init__
TypeError: Expected unicode, got Special
[7592] Failed to execute script compiler_launch
