### ISSUE TITLE
New Style: Modernized Old Aperture

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2-items#3781]
This style would take place in old aperture chambers that have been modernized; the textures would be black BTS concrete for non portalable walls and dirty white chamber walls for portalable surfaces. Test elements would be a mix of old and new aperture; for instance, cubes would be modern but buttons and pedestal buttons would be old. Light strips would be old aperture fluorescent lights, white colored by default. Here are some ideas for entrances and exits. I recreated two of these in Hammer. (Disregard my terrible Hammer skills, I'm new at it)

Entrances:
-A short corridor with BTS fluorescent lights and a yellow arrow on the floor, leading to the testchamber door.
![PORTAL 2 - Direct3D 9 08_05_2021 18_30_07](https://user-images.githubusercontent.com/68685620/117546591-7781a700-b02b-11eb-8b3e-a543b6263b4e.png)

-A catwalk above a BTS corridor with rubble, and the ceiling would be destroyed, with sunlight streaming in.
-A BTS maintenance area with a hole leading to a corridor that leads to the test chamber.
![PORTAL 2 - Direct3D 9 08_05_2021 18_58_47](https://user-images.githubusercontent.com/68685620/117547356-794d6980-b02f-11eb-94ef-a26cde8b834e.png)

Exits:
-A regular corridor like the 1st entrance suggestion.
-A collapsed corridor, with a BTS area under the floor, leading to a BTS automatic door.

Here's some concept pictures, made in Hammer:
![PORTAL 2 - Direct3D 9 08_05_2021 18_22_50](https://user-images.githubusercontent.com/68685620/117547390-a437bd80-b02f-11eb-8202-90280c78acd8.png)
![PORTAL 2 - Direct3D 9 08_05_2021 19_10_28](https://user-images.githubusercontent.com/68685620/117547686-1957c280-b031-11eb-88e4-b5c60dc84387.png)

This style was slightly inspired by the Above Aperture series.

**Comment by Critfish** [comment]
This doesn't look very good. I think any effort put into maintaining styles should be put towards making the ones we already have look better, and implementing the remaining missing styles(eg. wheatley, art therapy, etc.), rather than adding gimmicky custom styles.

**Comment by HeimlichLaboratories** [comment]
Sorry then. Note that it looks bad cause I'm not very good at complicated map building. However I can see your point.

**Comment by Luke18033** [comment]
There's that, and this just looks like a worse version of Refurbished style.
