### ISSUE TITLE
Aperture Science Spinning Antline Panel

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3782]
A Panel that spins to connect antlines.

More explained on it on my sketch:

![IMG_20210511_154026662](https://user-images.githubusercontent.com/72144613/117868130-9c665c00-b26f-11eb-8934-c7fe8a968a00.jpg)

As you can see, It spins to connect antlines together.

It's only a sketch right now, I've not started working on it yet.

I would love to get some help creating it.

**Comment by ThatOneRetro** [comment]
but why

**Comment by HeimlichLaboratories** [comment]
Not saying it's a bad idea but I'm not sure how would this work. I think what we really need is a magnet that joins antlines in a specific voxel then being able to connect the magnet itself to an item, sending the output from the original input (button, etc).

**Comment by Endermage77** [comment]
That seems like a highly specific gimmick to include in a level, even for something cooked up in Hammer rather than the Portal 2 editor itself.

**Comment by KaziPlays** [comment]
I'm planning on adding this to my mod

**Comment by Konclan** [comment]
This is too niche and complicated. Wouldn't really work as a puzzlemaker item. Same function can be achieved through logic gates.
