### ISSUE TITLE
Сломанный редактор карт (точнее тестирование карт)

### ISSUE THREAD

**Issue by MikeAvtone** [BEEmod/BEE2-items#3783]
![20210512192809_1](https://user-images.githubusercontent.com/84069529/117944445-f02b8080-b315-11eb-86cc-f8f04343c5dc.jpg)
![20210512192813_1](https://user-images.githubusercontent.com/84069529/117944459-f28dda80-b315-11eb-9b5c-ae2850a2c0b8.jpg)
![20210512192815_1](https://user-images.githubusercontent.com/84069529/117944462-f3267100-b315-11eb-803d-2767844eef97.jpg)
Что в этом случае делать? Сначала все поля не работали, а теперь это.

**Comment by LautaroL20** [comment]
Closing because the author doesn't respond.
