### ISSUE TITLE
Protruding Panel

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3785]
It's a Panel/Piston that is used for fling or as a platform.

It's used a lot in Portal 1.

Here it's used for fling.

![mqdefault](https://user-images.githubusercontent.com/72144613/118308091-ed6d8e80-b4c1-11eb-8c94-09315b993e6e.jpg)

Here it's used for fling, but on the floor.

![images (6)](https://user-images.githubusercontent.com/72144613/118308156-037b4f00-b4c2-11eb-85da-d792e4f22ff7.jpeg)

And here It's used as platform.

![images (7)](https://user-images.githubusercontent.com/72144613/118308264-20178700-b4c2-11eb-8382-3c215e73922f.jpeg)

**Comment by somedoodest** [comment]
...This is already in BEE2. It's the Piston Platform, as you can change it's portalability and put it on walls.

**Comment by HeimlichLaboratories** [comment]
It would be nice to have it being longer like in chamber 18 tho
