### ISSUE TITLE
The Auto-portal and Portal Gun do not work.

### ISSUE THREAD

**Issue by MikeAvtone** [BEEmod/BEE2-items#3786]
I do not have an Auto-portal and Portal gun, although I can put them on the surface and attach activators to them, but after pressing nothing will work. What should I do in this case?
Style: Clean
Items: 
![bandicam 2021-05-15 22-46-21-943](https://user-images.githubusercontent.com/84069529/118359572-c4fe9680-b58c-11eb-82c9-bb061111cedd.jpg)

**Comment by HeimlichLaboratories** [comment]
Already reported. This is a duplicate
