### ISSUE TITLE
black door frame

### ISSUE THREAD

**Issue by ivehadit** [BEEmod/BEE2-items#3791]

**Comment by LautaroL20** [comment]
WAT.

**Comment by HeimlichLaboratories** [comment]
Nobody can really help you without more info - what item or style are you using?

**Comment by LautaroL20** [comment]
> HeimlichLaboratories said: "What item or style are you using?"

Well, the author did not even determined what he is talking about, so asking for which item/style he was using without first knowing the reason for the issue´s title, would not help that much.

**Comment by HeimlichLaboratories** [comment]
> > HeimlichLaboratories said: "What item or style are you using?"
> 
> Well, the author did not even determined what he is talking about, so asking for which item/style he was using without first knowing the reason for the issue´s title, would not help that much.

I guess. Maybe he's talking about the door item?

**Comment by FrozenDragon0** [comment]
@ivehadit Can you like explain what your talking about? Providing nothing in the description does not help us and will not allow you to get any help because we have no info to help you with your issue.

**Comment by LautaroL20** [comment]
> > > HeimlichLaboratories said: "What item or style are you using?"
> > 
> > 
> > Well, the author did not even determined what he is talking about, so asking for which item/style he was using without first knowing the reason for the issue´s title, would not help that much.
> 
> I guess. Maybe he's talking about the door item?

Yeah, but a "black door frame" in the title without any kind of description would not help to determine anything.

**Comment by FrozenDragon0** [comment]
Closing due to lack of info.
