### ISSUE TITLE
Launch Problem

### ISSUE THREAD

**Issue by Limeony** [BEEmod/BEE2-items#3795]
Crash on startup
[bee2.log](https://github.com/BEEmod/BEE2-items/files/6525459/bee2.log)

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to the Beemod user interface, must be posted on the interface´s page, here: https://github.com/BEEmod/BEE2.4/issues

The section where you have posted is for things related to the items & styles, only.
