### ISSUE TITLE
Water wont work on any style

### ISSUE THREAD

**Issue by NocoReal** [BEEmod/BEE2-items#3798]
![image](https://user-images.githubusercontent.com/84647255/119243827-08e83180-bb73-11eb-9897-8610493cf539.png)
the water wont render

**Comment by LautaroL20** [comment]
Looks like you have a leak in the map, which items did you use to make that map?

**Comment by NocoReal** [comment]
not many, besides from the ones in normal portal 2 just the door with the fizzler
but i tried on an older version f bee and it worked

**Comment by SCIENTIST2004** [comment]
you mean Chamberlock?
Do you have a 1x1 corridor on the other side of the chamberlock?

**Comment by HeimlichLaboratories** [comment]
If you mean the Chamberlock it causes a leak if there's a 1x1  corridor on the other side. I recommend making it a 3x3 and placing stairs

**Comment by KaziPlays** [comment]
It's not water, It's Deadly Goo

**Comment by Luke18033** [comment]
There's a [leak](https://developer.valvesoftware.com/wiki/Leak) in your map. Try removing any items from custom packages to see if they're the cause of the leak. If the issue persists, go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.

**Comment by Konclan** [comment]
No reply
