### ISSUE TITLE
The Chamberlock in the Old aperture styles are broken!

### ISSUE THREAD

**Issue by Ponklu** [BEEmod/BEE2-items#3807]
BEE2 version:4.39.2

Description of the bug:The chamberlock is blocking you because the wall is blocking the inside of the chamberlock with an old aperture Style.

Expected behavior:The chamberlock does not block you.

Steps to reproduce:Be in a Old Aperture Style. Put a wall with a chamberlock. Then make it start enabled or put a button and a cube. Build and Play the test chamber and you cant get through the chamberlock you placed.

Additional information:Same problem as #3598.
![20210530164730_1](https://user-images.githubusercontent.com/37371046/120109565-e3a28700-c161-11eb-9dca-b0307aaa2066.jpg)

**Comment by HeimlichLaboratories** [comment]
This has been reported already
