### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by Egorrich9001** [BEEmod/BEE2-items#3809]
I installed this using the instruction: Unzip BEE2 anywhere (i did it in the same hard drive my steam games are in + created a folder) and unzip BEE tools inside. When i launch it it goes:
 "Traceback (most recent call last):
  File "app\sound.py", line 136, in ticker
  File "pyglet\media\__init__.py", line 140, in load
  File "pyglet\media\__init__.py", line 130, in load
  File "pyglet\media\codecs\wmf.py", line 882, in decode
  File "pyglet\media\codecs\wmf.py", line 498, in __init__
pyglet.media.exceptions.MediaDecodeException: [WinError -2147024891] Access denied"
as i understood, this is an issue with items. I tried out both the current and the previous releases. They give the same error message.

**Comment by FrozenDragon0** [comment]
Looks like Windows is blocking the app from launching for some reason.

**Comment by Egorrich9001** [comment]
> 
> 
> Looks like Windows is blocking the app from launching for some reason.

Any idea how to fix? i have a nice prototype for a test chamber, but it doesnt work without some tweaking with this mod.

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to the Beemod user interface, must be posted on the interface´s page, here: https://github.com/BEEmod/BEE2.4/issues

The section where you have posted is for things related to the items & styles, only.
