### ISSUE TITLE
The Auto Portal does not activate

### ISSUE THREAD

**Issue by IDy8I** [BEEmod/BEE2-items#3817]
**BEE2 version:4.39.2**

**Description of the bug:The auto portal doesn't activate with any input or I'm putting it wrong**

**Steps to reproduce:Connect Auto Portal with any input**

**Additional information:
![image](https://user-images.githubusercontent.com/78465012/120875556-01148e00-c572-11eb-993c-e22c043278e3.png)
![image](https://user-images.githubusercontent.com/78465012/120875579-21444d00-c572-11eb-8c3f-2ab664b249d5.png)
![image](https://user-images.githubusercontent.com/78465012/120876505-a0d41b00-c576-11eb-8152-2cbceeb83a59.png)

Sorry i speak Spanish and it is my native language
**

**Comment by FrozenDragon0** [comment]
Please browse github issues before posting one of your own to make sure that you don't have any duplicates...

https://github.com/BEEmod/BEE2-items/issues/3672
