### ISSUE TITLE
Coat the Closed Solid Field with Conversion Gel

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3822]
I don't know if this would be possible but, with this we wouldn't need a portalable fizzler, Just put conversion gel on It.

The other gels work as intended, repulsion bounces, propulsion speeds up, cleansing does absolutely nothing, reflection reflects.

**Comment by Konclan** [comment]
Not possible

**Comment by Luke18033** [comment]
It actually is I think.

**Comment by TeamSpen210** [comment]
It doesn't look very good, since the gel is only visible on one side.

**Comment by Luke18033** [comment]
I mean you can already put gel on the field, this is just a suggestion to make Conversion Gel work. The reason it doesn't is because of the `trigger_portal_cleanser`, if that's removed then it should hit the gel brush instead. Then the material modify method would be used to fade in/out the field.

**Comment by seagemgames** [comment]
Portals placed on a func_brush that can be disabled break collisions with VPhysics objects if turned off. It's a big pain

**Comment by EllingtonElectrician** [comment]
The closed solid field was Originally based off my idea of a force field before someone stole it, The closed solid field is not supposed to have gel or anything on it at all.

**Comment by Konclan** [comment]
Possible but not needed really
