### ISSUE TITLE
Lightstrips light color are switched in-game: Warm Light emits neutral light and Cool Light emits warm light.

### ISSUE THREAD

**Issue by Pokemanic33** [BEEmod/BEE2-items#3824]
**BEE2 version:** 4.39.1

**Description of the bug:**
When using an old Aperture theme, the warm (orange) lightstrips are supposed to be the default, as opposed to the cool (white) ones. The textures are switched, but the light emitted from them is not; if you place an orange light, the light emitted will be cool, and if you place a white light, the light emitted will be orange.

**Expected behavior:**
The light should change to reflect the change in texture, and to follow with the text in the Beemod UI.

**Steps to reproduce:**
1. Select an old Aperture theme
2. Place a lightstrip
3. Build the map

**Additional information:**
For the sake of clarity, here are screenshots showing a room with lightstrips in it, as seen in the editor and in-game. The lightstrips themselves are invisible, per #3744
![image](https://user-images.githubusercontent.com/10733217/122151772-1f11a680-ce2e-11eb-925d-3cbd07504898.png)
![image](https://user-images.githubusercontent.com/10733217/122151851-45cfdd00-ce2e-11eb-9a6d-20f8e42914dd.png)

**Comment by TeamSpen210** [comment]
#3744 also caused this, so it appears to be fixed.
