### ISSUE TITLE
Shaped Repulsion Gel causes compile error in Old Aperture

### ISSUE THREAD

**Issue by FierceThundr** [BEEmod/BEE2-items#3825]
**BEE2 Version:**4.39.1

<details>
<summary>Error Log</summary>

VBSP failed.

[I] vbsp.main(): BEE2 v4.39.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "F:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "F:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): special: Unknown texture names black_gap, white_gap
[W] texturing.load_config(): normal.white.wall: Unknown texture names 1x2
[W] options.load(): Extra config options: {'remove_pedestal_plat': '1'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (7 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting Coop Exit to 4
[I] vbsp.get_map_info(): Game Mode: COOP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (966 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:small" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_RETRO:medium" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:large" for vactube group BEE2_VACTUBES!
[I] connections.gen_item_outputs(): Generating item IO...
[I] antlines.export(): Collapsed 2 antline corners
[I] antlines.export(): Collapsed 2 antline corners
[I] antlines.export(): Collapsed 3 antline corners
[I] antlines.export(): Collapsed 3 antline corners
[I] antlines.export(): Collapsed 3 antline corners
[I] antlines.export(): Collapsed 3 antline corners
[I] antlines.export(): Collapsed 2 antline corners
[I] connections.gen_item_outputs(): Item IO generated.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] cond.positioning.flag_brush_at_loc(): Using type=same in posIsSolid is deprecated, put this in mode!
[W] cond.positioning.flag_brush_at_loc(): Using type=different in posIsSolid is deprecated, put this in mode!
[W] cond.positioning.flag_brush_at_loc(): Using type=same in posIsSolid is deprecated, put this in mode!
[W] cond.positioning.flag_brush_at_loc(): Using type=different in posIsSolid is deprecated, put this in mode!
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] instanceLocs.get_subitems(): Invalid custom instance name - "toggle" for <item_catapult> (Valid: {'bee2_toggle': 'instances/BEE2/80s/items/gel_plate/dynamic.vmf'})
[W] cond.addInstance.res_add_overlay_inst(): Bad filename for "<ITEM_CATAPULT:bee2_toggle>" when adding overlay!
[E] cond.core.check_all(): Error in <BEE2_OLD_AP>/items/gel_plate:
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 511, in check_all
  File "precomp\conditions\__init__.py", line 300, in test
  File "precomp\conditions\__init__.py", line 289, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1092, in res_sub_condition
  File "precomp\conditions\__init__.py", line 300, in test
  File "precomp\conditions\__init__.py", line 289, in test_result
  File "precomp\conditions\brushes.py", line 108, in res_fix_rotation_axis
TypeError: type srctools._math.Matrix doesn't define __round__ method
</details>

**Additional information:**I have not spent excessive time testing this issue, but it is present in the Old aperture styles and appears to be caused by the Shaped Repulsion Gel, the large gel is unaffected

**Comment by HeimlichLaboratories** [comment]
Have you tried switching to the mechanical plate in the stylevars settings?

**Comment by FierceThundr** [comment]
I wasn't aware that was an option, but I will use that in the meantime
