### ISSUE TITLE
Futbol Spawner/Socket - make futbol able to carry paint

### ISSUE THREAD

**Issue by marKiiu** [BEEmod/BEE2-items#3827]
I think it would be a great idea if the futbol would be able to carry a blob of gel. 
It can already be painted like cubes but since it breaks on contact with any surface there is no way this would be usefull.

Maybe its possible to spawn a blob of its own color at the exact coordinates of its destruction to paint the closest surface. Like a large blob does when it pops.
The neutral futbol would always carry a blob of water which could be used to wash away paint. Sadly white and reflector gel do not offer a visible indicator but you would always know its content if its painted blue, orange or neutral.  Im afraid that changing the color inside the futbol would require hardcoding?

This could be a great addition to the gel section and the futbol itself since it feels pretty useless in its current state. Let me know what you think about the idea :)

**Comment by Konclan** [comment]
UCP
