### ISSUE TITLE
Cold square light and neutral square light are reversed in old aperture

### ISSUE THREAD

**Issue by FierceThundr** [BEEmod/BEE2-items#3828]
**BEE2 version:** 4.49.1

**Description of the bug:** The cold square light appears to produce neutral light in 1950s aperture and vice versa
Additionally upon testing other old aperture styles it appears many light strips have incorrect styles. (In 1970s Aperture, the warm light strip and neutral light strip are reversed)

**Expected behavior:** The cold square light should produce cold light; The neutral square light should produce neutral light

**Steps to reproduce:**
Place cold and neutral square lights 
Build Chamber

**Additional information:**

![20210620193544_1](https://user-images.githubusercontent.com/51411635/122691626-e0e5ff80-d1fe-11eb-8254-470970e02fb7.jpg)

**Comment by Luke18033** [comment]
This may be intentional, some of the Old Aperture styles swap the light colors around to reflect the most common light colors used in that era. I don't think cold lights are ever supposed to be changed though.

**Comment by Luke18033** [comment]
The vanilla light strips are internally called `cool` while the blue-tinted ones are called `cold`, which is pretty confusing and possibly the cause of this issue...

**Comment by FierceThundr** [comment]
Possibly, though it still is confusing how the styles of the light strips vs square lights don't match. It may not be a bug, but it is definitely confusing.

**Comment by Luke18033** [comment]
The was indeed caused by the cool/cold mixup, I really wish they weren't named that way...
