### ISSUE TITLE
Old Aperture light bars have a missing asset

### ISSUE THREAD

**Issue by FierceThundr** [BEEmod/BEE2-items#3829]
**BEE2 version:** 4.39.1

**Description of the bug:** Old aperture light strips have bugged texture without the actual light strip

**Expected behavior:** In the old aperture styles, the lights strips appear as a board on the wall without the light bar that should be there

**Steps to reproduce:** Place a light bar in the old aperture style

**Additional information:**
![20210620195406_1](https://user-images.githubusercontent.com/51411635/122692200-a9c51d80-d201-11eb-8bff-2e942c5246f3.jpg)

**Comment by HeimlichLaboratories** [comment]
#3744
