### ISSUE TITLE
Fix 4 missing voicelines in the game

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3830]
https://drive.google.com/drive/u/0/mobile/folders/1rOnKcFRvIF2eqmqVhi3WooulmByZ4gCX/1s7DW7GmT9iMFVzPRwwx5VjB57Dqfuoi7/13KjMeMI7bE42l9Y_V3RdetNiKWVAi5xo/1Tspag3wvWa2QW3M1TBqZxzo4AC6uq7nN?usp=sharing&sort=13&direction=a

On this link there is 4 unused voicelines that could be re-added to the game to make the scene files work.

The First one: pressdemo01, could be used for portal 1 GLaDOS and Apocalypse GLaDOS, the rest can be used on Apocalypse GLaDOS.

**Comment by TheEnderek0** [comment]
Again, voice lines can be added as sounds, but subtitles cannot be added. 
If that's what  you mean by "re-added".

**Comment by KaziPlays** [comment]
No, I mean that I think It already has the subtitles, Just the audio is missing

**Comment by KaziPlays** [comment]
Nope, the vcds didn't read the sound and I checked the subtitles and I didn't find them.
