### ISSUE TITLE
Auto-Portals don't work in Portal 1 style

### ISSUE THREAD

**Issue by benjaminpants** [BEEmod/BEE2-items#3835]
**BEE2 version:**
4.40.1

**Description of the bug:**
Same as title, Auto-Portals don't work in the Portal 1 style

**Expected behavior:**
Auto-Portals should open, however they don't.

**Steps to reproduce:**
1. Place an auto-portal
2. Give it an input
3. Build and watch as the auto portal refuses to open.

**Additional information(screenshots in this case.:**
![image](https://user-images.githubusercontent.com/27522994/124250976-4331e080-dada-11eb-8018-d6720d3b642f.png)

**Comment by FrozenDragon0** [comment]
Are they fixed for all other styles though?

**Comment by SCIENTIST2004** [comment]
It works in clean style

**Comment by TimmyBuildar** [comment]
Good catch, I was about to report that.
