### ISSUE TITLE
Signage legend texture removed by resource export

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#3836]
![20210702144324_1](https://user-images.githubusercontent.com/35931028/124273121-4e235a00-db48-11eb-89da-56c5205da63f.jpg)
![20210702144327_1](https://user-images.githubusercontent.com/35931028/124273125-4ebbf080-db48-11eb-9f9f-c58d9c8b87c3.jpg)

**Comment by jalapeno-github** [comment]
Oh I actually encoutered this issue as well. The way I fixed it, and it was completely by accident, was by loading a palette with the signage item. The moment you load your chamber back up the textures will be restored, and you can go back to whatever palette you were using before.

**Comment by TeamSpen210** [comment]
The problem I think is that you need to export again, if it copies resources - because that deletes the file when it deletes the whole folder at the start.

**Comment by jalapeno-github** [comment]
I remember the editor model showing the correct textures just by having the Signage item on the menu. Of course I re-exported the chamber.

I don't see how this is much of an issue, it's not exactly game-breaking, but I guess it's better if it can be fixed.
