### ISSUE TITLE
Antlines are broken in Portal 1 style

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#3837]
![20210702153627_1](https://user-images.githubusercontent.com/35931028/124275932-da834c00-db4b-11eb-89b6-7654ea444681.jpg)

**Comment by Luke18033** [comment]
Whoops. The floor antline texture should probably be remade as well, it's got some very obvious DXT tint.

**Comment by Luke18033** [comment]
Seems to be fixed now.
