### ISSUE TITLE
Toggle Latch causes Compile Error

### ISSUE THREAD

**Issue by jalapeno-github** [BEEmod/BEE2-items#3839]
**BEE2 version:** 2.4.40.1 with 2.4.40.0 packages

**Description of the bug:** Toggle Latches cause a compile error when present

**Expected behavior:** Toggle Latches should not cause a compile error

**Steps to reproduce:** Place Toggle Latch anywhere in the chamber. Does not need to have inputs/outputs from and to anything.

**Additional information:**
Here's a very simple chamber that causes a Compile Error. Yes, there's Neurotoxin Vents, they cause an error too, I'll make a different issue
![editor](https://user-images.githubusercontent.com/47536167/124336909-f4e31700-db97-11eb-89f3-3ecdce2def52.png)

Here's the console log, I think I copied everything you need to know:

VBSP failed.

[I] cond.core._get_cond_group(): No name for module "precomp.faithplate"!
[I] cond.core._get_cond_group(): No name for module "precomp.fizzler"!
[I] vbsp.main(): BEE2 v4.40.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "J:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "J:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (2 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Exit to 4
[I] vbsp.mod_entryexit(): Setting SP Entry to 6
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (40 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.FLOOR.BLACK: 18 Clumps for 410 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.CEILING.WHITE: 14 Clumps for 410 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.CEILING.BLACK: 14 Clumps for 410 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.WALL.WHITE: 37 Clumps for 410 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.WALL.BLACK: 37 Clumps for 410 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.FLOOR.BLACK: 18 Clumps for 410 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.CEILING.BLACK: 14 Clumps for 410 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.WALL.WHITE: 37 Clumps for 410 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.WALL.BLACK: 37 Clumps for 410 tiles
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] (MetaCondition "link_cubes") cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] (<BEE2_CATWALK>/items/factory) cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] (<BEE2_UNST_SCAFFOLD>/items/pist_clean) cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] (<BEE2_UNST_SCAFFOLD>/items/pist_clean) cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] (<BEE2_UNST_SCAFFOLD>/items/slot_clean) cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] (<BEE2_UNST_SCAFFOLD>/items/slot_clean) cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] (<BEE2_UNST_SCAFFOLD>/items/wall_clean) cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] (<BEE2_UNST_SCAFFOLD>/items/wall_clean) cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] (MetaCondition "gen_item_outputs") connections.gen_item_outputs(): Generating item IO...
[I] (MetaCondition "gen_item_outputs") connections.gen_item_outputs(): Item IO generated.
[E] () cond.core.check_all(): Error in condition:
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 618, in check_all
  File "precomp\conditions\__init__.py", line 273, in test
  File "precomp\conditions\__init__.py", line 262, in test_result
  File "precomp\conditions\__init__.py", line 475, in __call__
  File "precomp\conditions\entities.py", line 87, in insert_over
  File "random.py", line 346, in choice
IndexError: list index out of range

**Comment by Luke18033** [comment]
So it actually works fine?

**Comment by jalapeno-github** [comment]
> So it actually works fine?

Well, it does now, TeamSpen210 added the "Done" label to #3840. I re-posted the issue because, as LautaroL20 has correctly tagged, this issue is invalid. I just forgot to post a comment on here, sorry about that.

If you want the lengthy, actual explanation:
I loaded one of my chambers and found out the Signage item was missing its editor texture, I started the issue as a "generic bug" but wanted to make sure the texture was actually broken, so I reopened Portal 2 with a different BEEMod palette and the textures just came back (no idea). I then found out about the Toggle Latch and finished the issue, and it was only after I posted it that I realised I had posted the wrong type of issue.

Sorry again for not adding a comment or somehting.

**Comment by Luke18033** [comment]
It doesn't really make a difference, they're just templates. This issue is only invalid now because you opened another one and that became the main issue for this.

**Comment by jalapeno-github** [comment]
Well, now I kinda feel bad for wasting everybody's time. Is there not any way I could delete this one or are we just gonna leave it here?

**Comment by Luke18033** [comment]
Admins have an option to delete issues but it really doesn't matter, just keep that in mind for the future.

**Comment by jalapeno-github** [comment]
Ah, okay. Thanks a lot anyway.
