### ISSUE TITLE
BEEmod 4.40.1 Crash after reset package cache and then press export button: UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-12: ordinal not in range(128)

### ISSUE THREAD

**Issue by THS2121966** [BEEmod/BEE2-items#3842]
**BEE2 version: 4.40.1 BEE2 Items Version is 4.40.0**

**Description of the bug: When i press "export to Portal 2" button and export is beginning after exporting compilers i see this error in picture below...**

**Expected behavior: Complete export scenario.**

**Steps to reproduce: Reset package cache and press export button.**

**Additional information:**
![123](https://user-images.githubusercontent.com/56027883/124345741-78365400-dbfc-11eb-8cab-f6e9fd3dd353.PNG)

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to the Beemod user interface, must be posted on the interface´s page, here: https://github.com/BEEmod/BEE2.4/issues

The section where you have posted is for things related to the items & styles, only.
