### ISSUE TITLE
Add a sensor or trigger for co-op...

### ISSUE THREAD

**Issue by ZeroNikcol** [BEEmod/BEE2-items#3843]
And so, after you read the title, you may not understand what is at stake, but I wanted to add a sensor for cooperative mode or a trigger that is triggered only when two partners enter this trigger, if one partner leaves the trigger, then this trigger will turn off, and here is the picture you saw in co-op:
![300px-Portal2CoopDoorFromMp_Coop_Doors](https://user-images.githubusercontent.com/57002697/124406314-b4c39600-dd49-11eb-9e01-85185a708594.jpg)

Sorry for the small resolution, I was just looking for this picture on the Internet. 
This sensor can be contacted with ** door, half glass door, camera lock ** and other devices that open, can also be built from rail platforms into an elevator, for co-op, can only be done with a sensor or trigger for cooperative.

Sorry for my English, I'm Russian))

**Comment by FrozenDragon0** [comment]
The exit door for coop should already have this by default.

**Comment by LautaroL20** [comment]
Indeed.

**Comment by seagemgames** [comment]
The signage still could generate, and they suggested it being used with other door items (ones which don't have this)
