### ISSUE TITLE
Cube BOMB timer setting  won't work

### ISSUE THREAD

**Issue by sf3d-dk** [BEEmod/BEE2-items#3845]
BEEMOD 4.40.2
ORIGINAL CLEAN

Timer setings on Cube BOMB won't work CUBE EXPLODE immediately when dropped.  No matter what delay time is set, it will always explode immediately when placed down

EDIT:

OK, i just replace content of this file:  _tuleby_cube_bomb.nut_ 
packed in _cube_bomb.bee_pack_ (folder: resources\scripts\vscripts\BEE2\) with the old script (v 4.39.1 (copy/paste) ) and now it works fine.

EDIT:
Well, not quite...  now cube will explode after 8 seconds, cannot set any delay time. So its a partial solution, but still, i use this to finish my map.

**Comment by CardsAndGamesYT** [comment]
You should prob lose this if it's fixed
