### ISSUE TITLE
Lazer Ball Blocker

### ISSUE THREAD

**Issue by CardsAndGamesYT** [BEEmod/BEE2-items#3848]
What It Does:
In the portal 2 co-op maps in the bts area some maps have this. What it does is when you put in a ball it will block the lazer and activate an output. This item should be placed on walls only. When the ball is inserted it will get locked in place and taken out of the player hands.

Abilities: 
This item wont have any abilities because its basically a glorified ball button. (but its cool)

Source:
Its from the Portal 2 co-op campaign mode. idk what i should do about links for that.

Additional Info:
Regarding styles it would probably be only Clean and BTS.  Although it would be cool to see an Overgrown style of it.
![Lazer Ball Blocker](https://user-images.githubusercontent.com/74144694/125721765-173977ac-56ff-46f7-936f-815363f9b497.jpg)

**Comment by Konclan** [comment]
Niche and doesn't really fit styles outside of BTS, better left to a UCP
