### ISSUE TITLE
Item Suggestion: Glass/Grating Holes

### ISSUE THREAD

**Issue by MrKrunk** [BEEmod/BEE2-items#385]
![20160315202235_1](https://cloud.githubusercontent.com/assets/17092818/13766925/4353d8e6-ea23-11e5-9790-1723ba77af27.jpg)
Something like this would be nice. The type selection would be the cut out shape, and reversed/disabled is to select type of material. (Grating or glass.)

**Comment by Luke18033** [comment]
@MrKrunk Is that Portal Prelude? I seem to remember it had something like this.

**Comment by MrKrunk** [comment]
No, it's just a chamber I found on the workshop. I was playing it when I thought this grating thing would be a good idea.

**Comment by Luke18033** [comment]
This should be placeable on walls, floor, or ceiling, and generate a hole to the next open area behind it automatically. If another item's embed space was in the way, it simply wouldn't generate, or appear as a gray square (using the texture found around the edges).

**Comment by IceTudor** [comment]
I think it's also in TFV Mappack

**Comment by Endermage77** [comment]
You could even place this directly on grating/glass, yes?

**Comment by Luke18033** [comment]
Why is this closed? I guess it's been replaced by glass holes?

**Comment by TeamSpen210** [comment]
Yes, since those also work on grating.
