### ISSUE TITLE
my map fails to compile when it get to the lighting

### ISSUE THREAD

**Issue by CardsAndGamesYT** [BEEmod/BEE2-items#3850]
BeeMOD Version:
4.20.2

Console Log:
(It's In The Attached File)

More Info:
I'm using the bts style (if that has anything to do with it), my map isn't huge but its not small, and there are not many ant lines because I'm not finished yet. most of the connections don't have any visibility. The attached image is a picture of my map so you can get a sense of the size. (again if that matters)
![PORTAL 2 - Direct3D 9 7_16_2021 12_44_56 AM](https://user-images.githubusercontent.com/74144694/125893196-7b95dd99-7cb8-4b59-9d3a-b064b187069a.png)

[Log.txt](https://github.com/BEEmod/BEE2.4/files/6827876/Log.txt)

**Comment by CardsAndGamesYT** [comment]
ok i will try that (also i thought it would go under beemod because i thought it was an application problem not a item problem sorry)

**Comment by CardsAndGamesYT** [comment]
ok so i tried deleting every item (2 times) and its still broken. it started to break when i added the room with the orange gel dropper. but removing that room completely didn't work. so I'm kinda out of things i can do. one more thing I'm going to try tho it verifying the game files. so ill do that now. ill let you know what happens.

**Comment by CardsAndGamesYT** [comment]
um my whole map is gone, so if what I'm about to do does not fix this then I'm just gona close this and remake it because the map is still there but that's it all the test elements are gone. are if it happens again when i remake it (if i have to) ill prob reopen this because i would still like to know what the problem is

**Comment by CardsAndGamesYT** [comment]
k i have good news and bad news, good news, everything is still there! bad news it that everything including the bug is still there, so im open to any ideas! :\

**Comment by CardsAndGamesYT** [comment]
ok I'm going to close the issue now because I made a new map and it fails to build even when I don't change anything. so ima stop using bts until the new beemod update.

**Comment by CardsAndGamesYT** [comment]
im sorry... WHAT

![image](https://user-images.githubusercontent.com/74144694/125925750-105b9eac-890f-4528-a55b-3e405083fa19.png)

**Comment by CardsAndGamesYT** [comment]
different map, different style, different pallet. my portal is fucked

**Comment by CardsAndGamesYT** [comment]
and different skybox

**Comment by FrozenDragon0** [comment]
What's the console error for this one?

**Comment by CardsAndGamesYT** [comment]
it was at the lighting again
[Log.txt](https://github.com/BEEmod/BEE2-items/files/6831328/Log.txt)

**Comment by CardsAndGamesYT** [comment]
also sorry for the late response i just woke up like an hour or 2 ago lol

**Comment by CardsAndGamesYT** [comment]
hey i fixed the issue so im going to close now. turns out it was because of a messed up .wav file. XD
