### ISSUE TITLE
Failed to publish (portal 1 style)

### ISSUE THREAD

**Issue by Scottiegithub** [BEEmod/BEE2-items#3856]
**BEE2 Version:** 4.40.2

I was making a portal 1 styled map, but during the publishing process (which i've done before with portal 1 styled maps) it fails just after building geometry with this error message
<details>
<summary>Error Log</summary>

VVIS failed.
Valve Software - vvis.exe (May 19 2021)
16 threads
reading d:\steamlibrary\steamapps\common\portal 2\sdk_content\maps\1627060155.bsp
reading d:\steamlibrary\steamapps\common\portal 2\sdk_content\maps\1627060155.prt
LoadPortals: couldn't read d:\steamlibrary\steamapps\common\portal 2\sdk_content\maps\1627060155.prt

</details>

**Comment by Luke18033** [comment]
There's a [leak](https://developer.valvesoftware.com/wiki/Leak) in your map. Try removing any items from custom packages to see if they're the cause of the leak. If the issue persists, go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.

**Comment by Konclan** [comment]
No reply
