### ISSUE TITLE
High Energy Pellet Catcher In Old Aperture Style Doesn't work

### ISSUE THREAD

**Issue by Ponklu** [BEEmod/BEE2-items#3858]
**BEE2 version:** 2.40.2

**Description of the bug:** The High Energy Pellet Catcher Catches A High Energy Pellet And Doesn't Activate Anything That Is Linked To It.

**Expected behavior:** The High Energy Pellet Catcher Should Activate What is Linked To It.

**Steps to reproduce:** Be in The Old Aperture Style Place A High Energy Pellet Catcher And A High Energy Pellet. Link Something To The High Energy Pellet Catcher. Build And Play Your Level, Your Test Chamber Is Unsolvable/Broken.

**Additional information:**
![20210725131545_1](https://user-images.githubusercontent.com/37371046/127373128-8a5c2b15-0194-46f8-a627-1120a210bbcd.jpg)
![20210725131530_1](https://user-images.githubusercontent.com/37371046/127373135-87a3295a-7cdb-48fe-919d-8592e5d7db78.jpg)

**Comment by FrozenDragon0** [comment]
What is that 2nd check mark on the right side of the door connected to?

**Comment by Ponklu** [comment]
Its Connecting To A Button.

**Comment by FrozenDragon0** [comment]
Does the door open when the button is pressed along with the catcher being activated?

**Comment by Ponklu** [comment]
Yes It Needs The Catcher And The Button To Open Because The Catcher Doesn't Activate It Doesn't Open.

**Comment by FrozenDragon0** [comment]
Well I'd suggest changing the screenshot to only show the catcher connection as having that 2nd connection is just going to cause confusion.

**Comment by Ponklu** [comment]
For Some Reason The Water In The Sphere Is Also Missing.
![PORTAL 2 - Direct3D 9 29_07_2021 13_19_25](https://user-images.githubusercontent.com/37371046/127483623-bf2a1c09-22cc-4667-abfc-d96e360745c4.png)
Here Is The Cather And An Exit Door.
![PORTAL 2 - Direct3D 9 29_07_2021 13_19_51](https://user-images.githubusercontent.com/37371046/127483690-44d2d887-08d6-4fe6-acde-f0e3557138cb.png)
![PORTAL 2 - Direct3D 9 29_07_2021 13_20_03](https://user-images.githubusercontent.com/37371046/127483695-b513845a-059e-4d5f-82fa-5d0f01b03566.png)

**Comment by FrozenDragon0** [comment]
Now you have a leak in the map. Try moving the catcher so it's not on top of the exit door.

**Comment by Ponklu** [comment]
Its At A Corner Of The Entry Door

**Comment by Ponklu** [comment]
I Made A New Test Chamber.
![PORTAL 2 - Direct3D 9 29_07_2021 13_50_48](https://user-images.githubusercontent.com/37371046/127487205-bb15be3f-b245-4762-8ddc-e27d6a23c828.png)
![PORTAL 2 - Direct3D 9 29_07_2021 13_50_54](https://user-images.githubusercontent.com/37371046/127487209-e373381c-428d-43ad-b7b6-81d6cbe542f0.png)

**Comment by Ponklu** [comment]
I Think Its A Compiler Bug Because Even When I Used An Older Version Of The pellets.bee_pack. This Bug Is Only Present On Bee2.40.2 So I Think That Something In The Compiler Could Cause The Catcher Not Working...

**Comment by FrozenDragon0** [comment]
@Ponklu A lot of stuff has been getting re-written, hence why these newest versions have been bugged filled, seems for this version something must've screwed up regarding pellets for Old Aperture.

Off-topic: You don't need to have capital letters for every word in your sentence, only the beginning word.

**Comment by Luke18033** [comment]
Probably a connection system mismatch
