### ISSUE TITLE
P1 exit sign doesn't block portals

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3863]
**BEE2 version:** Dev

**Description of the bug:** The title says it all.
![image](https://user-images.githubusercontent.com/19228201/127785599-257a408d-603e-49c3-813e-8c4e07e977c2.png)

**Expected behavior:** The sign should block portals.

**Steps to reproduce:** Turn the surface above the exit door portalable, then place a portal there.

**Comment by TeamSpen210** [comment]
It'm not sure what I should do here, since the original doesn't block portals at all - signage is rather inconsistent.

**Comment by Luke18033** [comment]
Ah, it's a style compatibility thing. Considering that before this point, the P1 sign had blocked portals for about 5 years and nobody complained, I think having it do that is fine. Especially now that it can dynamically adjust, which means if you need that surface you can just put an antline router or something up there to force it to the side.
