### ISSUE TITLE
Futbol Spawner/Socket - make exploding futbol (bomb) variant.

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3870]
It's basically a bomb that you throw.

**Comment by Luke18033** [comment]
Exploding futbols were replaced by the bombs used at the end of the game, which can't be picked up.

**Comment by Luke18033** [comment]
And I'm not sure what purpose exploding futbols would really serve anyway?

**Comment by KaziPlays** [comment]
Breakable Glass and Bomb targets

**Comment by FrozenDragon0** [comment]
Still no purpose for that. Bomb droppers already take that role.
