### ISSUE TITLE
Auto Portals Don't Work In The P1 Style

### ISSUE THREAD

**Issue by CardsAndGamesYT** [BEEmod/BEE2-items#3877]
BEE2 version: 4.20.2

Description of the bug: auto portals don't open.

Expected behavior: auto portal open when and input is active.

Steps to reproduce: place and auto portal in the p1 style, that's it, it does not open.

Additional information: I know that there was another post about this on the page but i wanted to just check and see if it was fixed yet or not because the issue (#3835) has the "Done" tag but it's still open.

**Comment by Luke18033** [comment]
Please don't intentionally open duplicate issues, comments exist for a reason. "Done" means it's fixed for the next version.
