### ISSUE TITLE
Cube Button Causes Leak In Overgrown Style

### ISSUE THREAD

**Issue by CardsAndGamesYT** [BEEmod/BEE2-items#3881]
BEE2 version: 4.39 --> 4.40.2

Description of the bug: When the cube button is placed in the Overgrown Style the texture does not load in and causes a leek, however the coalition and functionality is still there. This bug applies to Single Player and Multiplayer

Expected behavior: The overgrown cube button show up in the editor

Steps to reproduce: Go in to the overgrown style, place a floor button, change the type to cube, and play the map.

Additional information: (Attached Image)

![PORTAL 2 - Direct3D 9 8_12_2021 1_53_53 PM](https://user-images.githubusercontent.com/74144694/129246930-94c5f62d-75d9-473b-baf1-37b81a70d1a2.jpg)
![PORTAL 2 - Direct3D 9 8_12_2021 1_54_44 PM](https://user-images.githubusercontent.com/74144694/129246941-ca9b5ba6-42c8-43da-932f-7913c5bac807.jpg)
![Engine Error 8_12_2021 1_57_50 PM](https://user-images.githubusercontent.com/74144694/129246477-56f171b5-95d8-482d-8259-261414bb8e51.png)

**Comment by TheEnderek0** [comment]
Seems like an issue with exporting. Do you have any antivirus programs installed?
Try to exclude the BEE2 folder in your antivirus if you have it, and export again.

If you don't have any antivirus programs, maybe try re-downloading BEE2

**Comment by CardsAndGamesYT** [comment]
I'm surprised I was not reported earlier because my friend has the same issue and he does not have any anti virus besides the built in windows fire wall

**Comment by Luke18033** [comment]
Duplicate of #3645
