### ISSUE TITLE
Junk Dropper

### ISSUE THREAD

**Issue by CardsAndGamesYT** [BEEmod/BEE2-items#3883]
Description of the item: this is a new dropper that when activated, it will drop junk items the first time it's activated, but after that it will drop the cube type specified in the puzzle maker 

Item options: 

   Inputs: Activate dropper

   Auto Respawn Cube: It's self explanatory.

   Start Enabled: Weather it starts enabled or not.

   Cube Type: changes the cube dropped after the first activation

   Styles: All

Source: Portal 2 single player campaign. Arial faith plate testing tracks.

Additional information: None

**Comment by Konclan** [comment]
Doesn't have any puzzle application, better left as a UCP

**Comment by CardsAndGamesYT** [comment]
Makes sense
