### ISSUE TITLE
Missing Voice Lines

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#389]
- [ ] Caroline
- [ ] Glados Apoc
- [ ] Portal 1 Glados
- [ ] ~~BTS Announcer~~ (Removed)
- [ ] Cave Johnson (60s)
- [ ] Cave Johnson (70s)
- [ ] Cave Johnson (80s)
- [ ] Cave Johnson (All)

**Comment by TheReviewers** [comment]
@TeamSpen210 That was a question btw

**Comment by TeamSpen210** [comment]
Yes, I haven't actually implemented them yet...

**Comment by TheReviewers** [comment]
@TeamSpen210 Ok

**Comment by Konclan** [comment]
Was BTS Announcer removed? I can't even get a recommended voice line in BTS

**Comment by Luke18033** [comment]
Yeah.
