### ISSUE TITLE
Alternate player spawn and end trigger

### ISSUE THREAD

**Issue by Dragunov37** [BEEmod/BEE2-items#3893]
**Description of the feature:**

I would like to suggest two new elements that are not related to puzzles. 

The first element is the Spawner player - this is an element that has the model of a green Freeman from Hammer. The name of the item speaks for itself, it will spawn the player where it was located, but only if there is no entrance in the test chamber, it can only be placed on the floor.
Possible functions:

- Choice of animation of appearance: no animation (the player simply appears at the specified point), with animation of awakening (you can make the same for all styles, "eyes open and the character gets up", or you can stylize sweat for each style, for example, in P1, awakening from a capsule)
- Laser Emitter cross for more detailed positioning on the panel and indicating the direction of the player's gaze when spawning
- Switch to invert the direction of gaze when spawning
- Or add, like turrets, the ability to direct the player's gaze when spawning at any angle

The second item is End Trigger - the usual trigger of the player, which is already in the mod, but when it is triggered, the level ends.

**This should be implemented because:**

I understand that these elements are needed more for decoration, but sometimes it is not convenient to arrange the entrance / exit, which takes up a lot of space.

**Comment by Dragunov37** [comment]
explain at least what is UCP?

**Comment by seagemgames** [comment]
User Created Package. It is a third party package of items, styles and other things. If you join the [Discord](https://discord.gg/hnGFJrz), you can view them in the UCP channels.

**Comment by Dragunov37** [comment]
thank you
