### ISSUE TITLE
Portal magnets don't work

### ISSUE THREAD

**Issue by Krypt0nC0R3** [BEEmod/BEE2-items#3894]
**BEE2 version:** 4.40.2

**Description of the bug:** Portal magnets doesnt work in Overgrown style

**Expected behavior:**
The magnet will attract portals

**Steps to reproduce:**
(https://youtu.be/K9xlXrB9x_0)
1. Select Overgrown style
2. Place portal magnet

**Additional information:**
Everything works OK in Clean style

**Comment by Luke18033** [comment]
The placement helpers are being added but they're rotated wrong so they don't work:
![image](https://user-images.githubusercontent.com/19228201/135735690-aa635d90-f765-47d6-af5e-c37329b6644d.png)
This also happens on every style.
