### ISSUE TITLE
 Trimmed tiles do not load

### ISSUE THREAD

**Issue by CN1o2** [BEEmod/BEE2-items#3905]
![Beemod3](https://user-images.githubusercontent.com/88097966/131571596-e90282f5-1479-4ed8-9732-c5c3480b0111.png)
I put cutout tiles on the map.

![Beemod3 - 1](https://user-images.githubusercontent.com/88097966/131571646-91818e03-0917-42d0-8ad0-9461280d6953.png)
But they don't appear on the map

I've been playing other maps and I see they can use them, but for some reason it doesn't work for me!

**Comment by Luke18033** [comment]
Cutout tiles are removed for now, they'll come back at some point in the future.

**Comment by CN1o2** [comment]
But then why are other players able to use it?

**Comment by Luke18033** [comment]
The maps were probably made back when they still worked.

**Comment by CN1o2** [comment]
I took a look at these maps, and I don't rule out that possibility.

**Comment by PixelPerfectGitHub** [comment]
When do you think they'll be added back? I've been making an overgrown level and have been struggling to decorate it.
