### ISSUE TITLE
Right Stairs Entrance gel does not appear in the tube, instead it curves out.

### ISSUE THREAD

**Issue by benjaminpants** [BEEmod/BEE2-items#3911]
### BEE2 Application Version

4.41-beta1

### BEE2 Package Version

4.41-beta1

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Placing any gel into a chamber with the Right Stairs entrance selected will cause the gel to not appear properly in the tube, as shown in the screenshot.
![image](https://user-images.githubusercontent.com/27522994/132041969-ccf42c19-0471-4042-8f6f-8f1b82c13da8.png)

### Expected behavior

The gel should stay in the tube and not clip through the wall.

### Steps to reproduce

Step 1. Switch to Portal 1 style, and switch to the Right Stairs entrance corridor
Step 2. Create a new chamber and place gel.
Step 3. Build and notice the gel is in the wrong place.

**Comment by Luke18033** [comment]
Not sure why this would happen, the target is set to always transmit to client, and it worked fine in my testing.

**Comment by Luke18033** [comment]
Can you open `instances/bee2/p1/elevator_sp/entrance_2/gel.vmf` and check the info_target's flags?

**Comment by benjaminpants** [comment]
![image](https://user-images.githubusercontent.com/27522994/132055785-7af20711-4db7-4c58-9066-f845dac30a9f.png)

**Comment by Luke18033** [comment]
I wasn't able to reproduce this, but I turned on "always transmit to client" on the target so hopefully it fixes the issue?
