### ISSUE TITLE
BEEmod 4.41-beta3: Antline Corner acts as an "OR" gate instead of behaving as an "AND" for when more than 1 button is connected

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3918]
### BEE2 Application Version:

4.41-beta3 32-bit

### BEE2 Package Version:

4.41-beta3

### What operating system are you running on?

Windows 7 (64bit)

### Showing how I made the connections between the items in Puzzlemaker: 

![Antline Corner acts as an OR gate instead of behave as an AND](https://user-images.githubusercontent.com/12244376/132545015-8fbe7e46-ec16-4c83-8d95-b0eadfa6d64a.png)

**Comment by Luke18033** [comment]
Possibly intentional?

**Comment by Konclan** [comment]
The reason for this is because the antline corners act like antlasers so there is nothing to handle joint antlines, its working as intentional. This could be improved, though I’m not sure why you wouldn’t just use two different antlines like how you would with normal connections.

**Comment by LautaroL20** [comment]
I’m not sure why you wouldn’t just use two different antlines like how you would with normal connections.

To reduce the ammount of antlines by merging them into one piece which may look more prolix, but if it´s currently working as intended then is fine.

**Comment by Luke18033** [comment]
Not sure if this applies for everyone, but when I see two antlines converge into one like this I interpret it as an OR gate, whereas multiple separate antlines going to the same item would indicate an AND gate. So going by that logic this makes sense.
