### ISSUE TITLE
Let Energy pellets break turrets.

### ISSUE THREAD

**Issue by Ducc6** [BEEmod/BEE2-items#3919]
### Description of the feature

When a energy pellet comes in contact with a turret, it should blow it up

### Why should this be implemented

If the player gets a turrets corpse and picks it up, they can make a pellet go randomly around the room and possibly hit a energy pellet catcher. When the pellet would break a turret, it would just keep going and the test wouldn't mess up due to a dead turret.

**Comment by Luke18033** [comment]
The one problem I have with adding all these pellet options is that it becomes really hard for players to tell how pellets behave at a glance; they could have different portal refresh times, destroy cubes, *be* destroyed by cubes, or pass through grating, and none of these things are indicated to the player. Adding another option like this would just make the problem worse.

**Comment by Konclan** [comment]
What I suggest is a turret type that is destroyed when moved away from its spawning space.

**Comment by Luke18033** [comment]
In that case see #1612.
