### ISSUE TITLE
Resizable Triggers

### ISSUE THREAD

**Issue by LonelyPortalFan** [BEEmod/BEE2-items#3920]
### Description of the feature

Triggers should have the option to resizable
them.

### Why should this be implemented

Some puzzle ideas can get destroyed because of this.

**Comment by seagemgames** [comment]
You can connect two triggers together to make a bigger trigger.

**Comment by HeimlichLaboratories** [comment]
What about half block triggers

**Comment by LautaroL20** [comment]
This would be similar to the suggested "Standing 1/4 Block Triggers" which will be able to connect between them. See: https://github.com/BEEmod/BEE2-items/issues/3886
