### ISSUE TITLE
rockets from rocket turrets somehow kill faster while being fizzled

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#3921]
### BEE2 Application Version

4.40.2

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

rockets dont ALWAYS instantly kill the player on impact, but rockets that are being fizzled (which should probably deal NO damage) always instantly kill

### Expected behavior

i expect the rocket to just bounce off me while being fizzled and the regular rocket to always kill me

### Steps to reproduce

put a fizzler between you and the rocket turret

### Additional information

works regardless of style

**Comment by Luke18033** [comment]
Ah, this probably has to do with the fact that the rockets don't actually kill you on your own, they have a trigger attached which does it. I'll want to have it deactivate that when fizzled.
