### ISSUE TITLE
Bee2 Ignores Cave Johnson (Workshop) Voice.

### ISSUE THREAD

**Issue by LonelyPortalFan** [BEEmod/BEE2-items#3922]
### BEE2 Application Version

BEE2 4.40.2

### BEE2 Package Version

2.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

BEE2 doesn't enable nor disables Cave Johnson (Workshop) Voice.

### Expected behavior

To actually activate or deactivate.

### Steps to reproduce

Clicking on the option doesn't enable the Voice.

### Additional information

Every single style

**Comment by Konclan** [comment]
The Cave Johnson workshop voicelines only play through one time, BEEmod doesn’t reset this so if you’ve already listen to them you won’t be able to hear them unless you reset them yourself. They also only play in published workshop levels. The only thing the BEEmod option changes are the entities that play the lines so the player wont have their Cave Johnson lines play if they could.
