### ISSUE TITLE
This is still happing with me even tho i put the bee.pack in it

### ISSUE THREAD

**Issue by ZoraFNaFAfton** [BEEmod/BEE2-items#3923]
![image](https://user-images.githubusercontent.com/70824760/132928912-6c8f62f7-c203-4fe1-ada2-592b2493036f.png)
It saying (just for people who cant see sent one of my monitors is a bit big xD)

[ERROR] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 74, in <module>
  File "packages\__init__.py", line 505, in load_packages
  File "packages\item.py", line 495, in parse
  File "packages\item.py", line 789, in parse_item_folder
  File "editoritems.py", line 985, in parse_one
  File "editoritems.py", line 1106, in _parse_export_block
  File "editoritems.py", line 1343, in _parse_occupied_voxels
  File "srctools\_tokenizer.pyx", line 901, in srctools._tokenizer.BlockIter.__next__
srctools.tokenizer.TokenSyntaxError: Unexpected token BRACE_OPEN!
Error occurred on line 90, with file "BEE2_UNST_SCAFFOLD:items/slot_clean/editoritems.txt".

**Comment by CardsAndGamesYT** [comment]
Something is wrong with the unsationary scaffolding editoritems.txt   I would recommend attaching the editoritems.txt for that item here so someone can look through it and find the issue. It also says that th error is occurring on line 90.

**Comment by CardsAndGamesYT** [comment]
To get the editoritems you will need to convert the unstaionary scaffolding's .beepack to a .zip    From there open it, go to I believe "items" then keep going through the folder until you find "editoritems.txt" and attach it

**Comment by CardsAndGamesYT** [comment]
Also what version of bee are you using and what I packages version are using?

**Comment by ZoraFNaFAfton** [comment]
@CardsAndGamesYT the newer version

**Comment by ZoraFNaFAfton** [comment]
> Something is wrong with the unsationary scaffolding editoritems.txt I would recommend attaching the editoritems.txt for that item here so someone can look through it and find the issue. It also says that th error is occurring on line 90.

and where will that bee at?

**Comment by CardsAndGamesYT** [comment]
> @CardsAndGamesYT the newer version

4.40.2 application and 4.40 packages?

**Comment by CardsAndGamesYT** [comment]
> > Something is wrong with the unsationary scaffolding editoritems.txt I would recommend attaching the editoritems.txt for that item here so someone can look through it and find the issue. It also says that th error is occurring on line 90.
> 
> and where will that bee at?

the packages folder where all the .bee_packs are

**Comment by TeamSpen210** [comment]
This error occurred with earlier versions of the packages in a newer app, are you sure you have the current version?

**Comment by ZoraFNaFAfton** [comment]
Yes I have 4.42.1 Spen I just don't know how one of the items is being bugged or making the app no to open and it's the seem issue like I had in July or June

**Comment by seagemgames** [comment]
Have you tried deleting the packages and reinstalling?

**Comment by ZoraFNaFAfton** [comment]
Yes al;ot still not leting on

**Comment by CardsAndGamesYT** [comment]
> Yes, I have version 4.40.2 Spen I just don't know how one of the items is being bugged or making the app no to open and it's the seem issue like I had in July or June

are you using the 4.40 packages?

**Comment by ZoraFNaFAfton** [comment]
They are only bee.pack

**Comment by CardsAndGamesYT** [comment]
uh, what?

**Comment by Konclan** [comment]
I have no idea what bee.pack is. Follow this installation tutorial and head over to our discord if you're still having problems after that
https://youtu.be/Tn5s-UAnQcg
https://github.com/BEEmod/.github/blob/master/contributing.md#this-is-not-a-forum
