### ISSUE TITLE
Unstationary scaffold piston emitters don't remove antlines

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3929]
### BEE2 Application Version

Dev

### BEE2 Package Version

Dev

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Antlines which connect *from* a scaffold piston emitter will not be removed, regardless of style. Wall emitters and slots work correctly.
![image](https://user-images.githubusercontent.com/19228201/132960538-268be795-90d6-471b-89cb-1b4b1b053f57.png)
![image](https://user-images.githubusercontent.com/19228201/132960561-4bc4c05e-7903-4945-bf62-954e5265b2c9.png)

### Expected behavior

The antlines should be automatically removed.

### Steps to reproduce

1. Place two piston emitters
2. Connect them
3. The antlines are not removed

**Comment by CardsAndGamesYT** [comment]
not sure this is a bug, it happens with the vac tube and the cat walk as well. all you have to do is set them to have no antlines

**Comment by Luke18033** [comment]
If it happens with vactubes and catwalks as well, then that's also a bug. These aren't "real" connections, they're not supposed to show antlines/signage.

**Comment by CardsAndGamesYT** [comment]
huh, i thought is was just one of those things where you cant change that in the code.

**Comment by Luke18033** [comment]
If you actually bothered to read the issue, you'd see that slots and wall emitters are able to remove their antlines fine.

**Comment by CardsAndGamesYT** [comment]
> If you actually bothered to read the issue, you'd see that slots and wall emitters are able to remove their antlines fine.

but you see i did read it and i did say that you could just set the antline to none
