### ISSUE TITLE
Single coop checkpoints have unnecessarily big editor collisions

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3930]
The occupied and embedded voxel spaces for single checkpoints are way larger than they seemingly need to be, when compared to the droppers in the spawn room and combined checkpoints.
- The embed space is 4 blocks deep, while the droppers in normal checkpoints only embed about 2 blocks up.
- The dropper requires 2 blocks of free space below it, despite the fact that the droppers in the separated checkpoint only have 1 block of free space below and it works fine.

These should be shrunken down to more reasonable sizes.

**Comment by TeamSpen210** [comment]
The embed space is tall for a reason, so the both-checkpoint has room for both players to spawn simultaneously, and has distance for lighting to fade out so it seems taller. I also extend regular cube droppers to this distance anyway if there's room.

**Comment by Luke18033** [comment]
I did check that that works fine, both players can spawn at the same time, and there's room below for them to both drop out and for Atlas to get pushed off of P-Body. But yeah it would be a good idea to extend the tube to the original height when there's room.

**Comment by TeamSpen210** [comment]
The reason I check for room is that I want to keep compatibility by preserving the original embed size for regular cube droppers, but that's not a concern for these. You shouldn't be putting items on top anyway, since it doesn't logically make sense. The main reason I didn't add taller pipes in the big checkpoint is probably because it's already a massive item.

**Comment by Luke18033** [comment]
The other thing to keep in mind here is what people actually care about, I highly doubt most people will notice or care if a single checkpoint is placed with another room unrealistically above it, or if they can just barely see one of the players spawning in. This is a game about quantum space holes (Aperture could put a portal at the top of the tube and drop the bots in through that), I don't think we should constrain ourselves to these arbitrary restrictions regarding realism if it limits the item's usage in other ways. ([And I'm clearly not the only one who thinks this.](https://github.com/BEEmod/BEE2-items/issues/1440))
