### ISSUE TITLE
Static Angled Panel has bad lighting behind them in Clean Style

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3937]
### BEE2 Application Version

4.41-beta4 32bit

### BEE2 Package Version

4.41-beta4

### What operating system are you running on?

Windows 7 (64bit)

### Description of the bug

If we compare the inside part of a dynamic Angled Panel vs the Static one, we can clearly see that the inside of the Static version is having some kind of lighting problem where the Light Strips do not manage to illumine the same way as it does with the dynamic version:

![20210914194534_1](https://user-images.githubusercontent.com/12244376/133352370-e0350dd2-93f5-46c5-8152-f884cf387e1c.jpg)

### Expected behavior

I expect the inside of the Static Angled Panel to get illumined with the same intensity as it does with the inside of the dynamic version when lighting items are near to them as shown in the screenshot of above.

### Steps to reproduce

Pull two blocks in the surface and place 2 Angled Pannels in front of each other, connect only one of them to an input and add some light strips and then you will see the difference in the light amount on their inside parts.

### Additional information

This issue happens with all degrees of a Static Angled Panel in Clean Style.

**Comment by Luke18033** [comment]
Probably forgot to disable shadows on the clip
