### ISSUE TITLE
[Bug] 60´s Old Aperture: Co-op Exit "Starts to Closing" when a player has enter and walks to the end, leaving the mate "Stuck in puzzle area"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#394]
GIF:
![gif](https://cloud.githubusercontent.com/assets/12244376/13783448/48045fd2-eaaa-11e5-90d7-2d05e1906b00.gif)

**Comment by ZombiePwner1** [comment]
Walk back into the trigger and the door will most likely open.

**Comment by TeamSpen210** [comment]
Yes. This is actually an annoying problem to solve, since teleporting takes you out of the trigger.

**Comment by Luke18033** [comment]
Why not add another trigger in the sphere area outside?
