### ISSUE TITLE
Old Aperture catwalk wall ends cause leaks

### ISSUE THREAD

**Issue by skyv1111** [BEEmod/BEE2-items#3941]
### BEE2 Application Version

4.40.0 64bit

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Additional information

Hello! I'm making a map in the 1950's style and, as the title says, the goo isn't being rendered correctly.

Here are my compile options (rendering mode is on Fast):
![image](https://user-images.githubusercontent.com/91033422/133943890-a261e6a3-6e8f-4ee3-89d3-64f2d68cffb5.png)
![image](https://user-images.githubusercontent.com/91033422/133943895-a4240f87-6931-486a-a87c-cd2efef2d98a.png)
![image](https://user-images.githubusercontent.com/91033422/133943909-f4a68bf4-f4a0-4481-8c56-f9d5b6bdd3e4.png)

..and here are the photos of the problem:

![20210919222846_1](https://user-images.githubusercontent.com/91033422/133943960-1bcd76ca-cb90-439c-8919-37e72a88eb4d.jpg)
![20210919222832_1](https://user-images.githubusercontent.com/91033422/133943967-6d749cea-2d54-4405-9cef-f0c50a81114b.jpg)

If you need anything else, let me know

**Comment by Luke18033** [comment]
There's a [leak](https://developer.valvesoftware.com/wiki/Leak) in your map. Try removing any items from user created packages to see if they're the cause of the leak. If the issue persists, go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.

**Comment by skylane-cs** [comment]
[map.ZIP](https://github.com/BEEmod/BEE2-items/files/7192989/map.ZIP)

There, should be good

**Comment by Luke18033** [comment]
It's caused by the catwalk wall ends:
![image](https://user-images.githubusercontent.com/19228201/133944578-1ecf7969-51c3-441e-aa6a-6383dfb2d952.png)

**Comment by Luke18033** [comment]
What you'll probably want to do is move the wall where the catwalk ends are placed 1 block back, then put them on the floor there.

**Comment by skylane-cs** [comment]
Ah, thanks a ton. Could perhaps be an issue in some locations considering the catwalks are on the very last part of wall but I'll give it a spin.
