### ISSUE TITLE
BEEmod 4.41-beta4: Open enrichment spheres use non-BEE2 instance

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3943]
### BEE2 Application Version

4.41-beta4 32bit

### BEE2 Package Version

4.41-beta4

### What operating system are you running on?

Windows 7 (64bit)

### Description of the bug

The only Old Aperture style which will compile fine regardless if the option opened enrichment sphere is checked or unchecked is the 60´s one. In the other cases, here is the result:

80´s Old Aperture with the option opened enrichment sphere **unchecked** will throw the following compile error:

````
Could not open instance file instances/test_chambers/sp_a3_speed_ramp_column.vmf
````

50´s Old Aperture with the option opened enrichment sphere **checked** will throw the following compile error:
````
Could not open instance file instances/lights/underground_lightarray_broken_01.vmf
````

70´s Old Aperture with the option opened enrichment sphere **checked** and **unchecked** will throw the following compile error:
````
 Could not open instance file instances/lights/underground_light_wall01_warm.vmf
````

### Expected behavior

All the Old Aperture styles must compile regardless if the option "Opened Enrichment Sphere" is checked or unchecked.

**Comment by Luke18033** [comment]
This has nothing to do with catwalks, not sure where you got that from. It's part of the open enrichment spheres.

**Comment by Luke18033** [comment]
Can you go through all the other Old Aperture styles with and without open enrichment sphere on and make sure there aren't any other errors like this? The error would only occur for people who don't have the authoring tools installed, so I can't test it easily.

**Comment by LautaroL20** [comment]
> Luke18033 said: "Can you go through all the other Old Aperture styles with and without open enrichment sphere on and make sure there aren't any other errors like this?"

Here is the result of the full testing through all the Old Aperture styles done with **4.41-beta4**.  The only Old Ap style which will compile fine regardless if the option opened enrichment sphere is checked or unchecked is the 60´s one. 

80´s Old Aperture with the option opened enrichment sphere **unchecked** will throw the following compile error:

````
Could not open instance file instances/test_chambers/sp_a3_speed_ramp_column.vmf
````

50´s Old Aperture with the option opened enrichment sphere **checked** will throw the following compile error:
````
Could not open instance file instances/lights/underground_lightarray_broken_01.vmf
````

70´s Old Aperture with the option opened enrichment sphere **checked** and **unchecked** will throw the following compile error:
````
 Could not open instance file instances/lights/underground_light_wall01_warm.vmf
````

I will edit the original issue´s description including all this new info.

**Comment by Luke18033** [comment]
Yep, I actually already did a search through the whole repo for these and fixed them. Thanks for checking though!
