### ISSUE TITLE
BEEmod 4.41-beta4: Portal 1 ceiling/floor observation room uses the wall observation room.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3947]
### BEE2 Application Version

4.41-beta4

### BEE2 Package Version

4.41-beta4

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Self-explanatory:

![image](https://user-images.githubusercontent.com/18079316/133983299-a3ea37aa-944a-47a2-9cdf-93725510c842.png)

![image](https://user-images.githubusercontent.com/18079316/133984298-ca631a17-8b47-4a85-add7-b187a71b4846.png)

Ceiling/floor observation room is using the wall instance instead of using it's ceiling/floor instance depending what surface you placed it on.

### Expected behavior

Ceiling/floor Observation room is meant to be using it's ceiling variant and not a wall variant.

### Steps to reproduce

Using Portal 1 style place a observation room on the ceiling and compile the map and you'll see the room on the ceiling using it's wall variant. Same goes for floor observation rooms.

**Comment by Luke18033** [comment]
Doesn't happen anymore, probably the same cause as the other floor/ceiling obs room issues.
