### ISSUE TITLE
BTS transition (Behind the scenes transition)

### ISSUE THREAD

**Issue by Ponklu** [BEEmod/BEE2-items#3948]
### Description of the feature

This transition to the style behind the scenes would make it better to know that the next map/level is behind the scenes.(This replaces the end elevator).

### Why should this be implemented

I Think that this would improve the behind the scenes style for making it easier to comprehend the situation.

**Comment by FrozenDragon0** [comment]
I don't believe this has much use now that BTS style is removed.
