### ISSUE TITLE
P1 Sendificator antlines still have the green DXT tint

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3960]
The title says it all. It's not as bad for the wall ones, but it's still there.
![image](https://user-images.githubusercontent.com/19228201/135773623-0f2ad564-01c8-4a07-afdf-90df08f9e266.png)

**Comment by Luke18033** [comment]
The design of the corners is also inconsistent:
![image](https://user-images.githubusercontent.com/19228201/135773737-23250068-4e9e-4ada-a495-d3ddf9fddaf1.png)

**Comment by TeamSpen210** [comment]
Really the regular corners are the ones that are wrong.
