### ISSUE TITLE
BEEmod 4.41-beta5: Clean and Overgrown Observation can be portalled

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3966]
### BEE2 Application Version

4.41-beta5 32-bit

### BEE2 Package Version

4.41-beta5

### What operating system are you running on?

Windows 7 (64bit)

### Description of the bug

![Clean and Overgrown observation can be portalled](https://user-images.githubusercontent.com/12244376/136445545-eb8e4632-3a23-4444-9c23-7cdc810f03a2.jpg)

### Expected behavior

Observation room must not allow portal placements.

### Steps to reproduce

Place a portal near the Observation and then try to shoot it with the other portal until you manage to do portal bump.

### Logs and Reports

```shell
None.
```

### Additional information

Clean and Overgrown styles.

**Comment by Luke18033** [comment]
This probably happens in the public release as well, nothing about these has really been changed in 4.41...I'm not sure what surface the portal would be on though, a playerclip should be the only thing there?

**Comment by LautaroL20** [comment]
It is probably just missing a `noportal_volume` surrounding the Observation.

**Comment by Luke18033** [comment]
That's not the issue, there shouldn't be a surface there which supports portals to begin with...

**Comment by slambo312** [comment]
working on a fix right now. overgrown was easy, but I can't find the clean one.
