### ISSUE TITLE
Slide Panel (My idea)

### ISSUE THREAD

**Issue by DatPerkYT** [BEEmod/BEE2-items#3967]
### Description of the feature

Slide Panels, take up a 2x1 area. they are Panels that slide from 1 end to another. yes, you can do this with a scaffold IF there is blocks OVER it. this only needs Ground or Wall blocks. Place it on a surface, activate it, and it moves to the other end of the rail. Also, the side the panel STARTS on should be able to float.

### Why should this be implemented

I think doing this would be cool/ a new way to open a hole in the ground, reveal a VacTube, and possibly even the exit! 

### Additional information

Here is a picture i made:
![SlidePanel](https://user-images.githubusercontent.com/90533282/136634086-6d0318f4-8b17-46fd-a907-3d9d26de86e3.png)
now this problably will be a waste of time reading this... but i need SOMEONE to hear my ideas. i might demonstrate this on my YT but like its even gonna get added. Again, just an idea i got last night.

**Comment by TeamSpen210** [comment]
Wait, wouldn't this just be a track platform really?

**Comment by Luke18033** [comment]
Uh, I don't think automatically rejecting all item suggestions was something we agreed on. Regardless, this can basically already be done with a non-portalable track platform or just a normal door.
