### ISSUE TITLE
Overgrown Funnel

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3974]
I just discovered that it's possible to have a custom funnel model which properly animates using the `prop_dynamic_ornament` entity. The limitation is that the animations have to be exactly the same as the vanilla model, but this should work fine to add a damaged variant for Overgrown. We'll need someone to make that model/texture though.

The current modified particles would still be present, along with the flickering option (does anyone actually use that?)

**Comment by SCIENTIST2004** [comment]
@Luke18033 Don't you remember? I did overgrown texture in #3413

**Comment by SCIENTIST2004** [comment]
btw I know tool which can add skins to the models, its caled Skin Editor. With this tool you can simply add new skin to the model.
Skin Editor: https://cloud.mail.ru/public/fqhc/5nY...

**Comment by Luke18033** [comment]
That would work for a mod, but workshop maps can't override the model to add any additional skins.

**Comment by Luke18033** [comment]
Notice that I said "model", I'd prefer if it wasn't just a reskin. The funnel emitter is a big device with lots of moving parts, realistically some bits would probably be damaged or missing after it's been sitting unused for who knows how many years.

**Comment by TeamSpen210** [comment]
By turning on/off bodygroups, we could perhaps do a number of variations.

**Comment by Luke18033** [comment]
Good idea!

**Comment by ErinRoseWebs** [comment]
[overgrown_funnel.zip](https://github.com/BEEmod/BEE2-items/files/7674168/overgrown_funnel.zip)
overgrown funnel model i finished at 2:30 in the morning lol. should follow the BEE2 directories. if it doesn't, lemme know and ill fix it.
