### ISSUE TITLE
Vactube is missing the in-game palette icon in all the Old Aperture styles

### ISSUE THREAD

**Issue by NimsayRamsey** [BEEmod/BEE2-items#3976]
### BEE2 Application Version

4.40.2

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Vactube icon in Old aperture 1980s is missing its icon in the puzzle maker, using the "missing" checkerboard texture instead:
![Image](https://user-images.githubusercontent.com/12244376/140444123-95cdfeec-8371-4956-b2fa-0bf9ef4098ac.png)

### Expected behavior

Should have an icon

### Steps to reproduce

1. add vactube to palette
2. set theme to Old Aperture 1980s
3. load the puzzle maker

**Comment by LautaroL20** [comment]
This not only happens in the 80´s old, but all the Old Aperture styles as well. I have fixed this though.
