### ISSUE TITLE
[Suggestion] Relaxation Vault

### ISSUE THREAD

**Issue by MrKrunk** [BEEmod/BEE2-items#398]
I was wondering if it would be possible to include the relaxation vault as a spawn location. Why I'm saying spawn location is because it wouldn't make much sense to enter a chamber through other means if a vault is present.

**Comment by towergame** [comment]
Yeah but what if it's a BTS section. It would be really nice if you could place a section with relaxation vaults.

**Comment by ZipZoptheCat** [comment]
Relaxation Vault could be a setting where it's simply an entrance type. Downside is you can't really build around it.

BTS could be an employee break room?

**Comment by Konclan** [comment]
Duplicate of #1245
