### ISSUE TITLE
Old AP Outer Sphere Has Odd Collision Allowing You To Walk On The Water

### ISSUE THREAD

**Issue by CardsAndGamesYT** [BEEmod/BEE2-items#3980]
### BEE2 Application Version

4.40.2

### BEE2 Package Version

4.40

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

The enrichment spheres have strange collision witch is allowing me to walk on the goo at the bottom. and if its important, this was at the exit of the test.
![PORTAL 2 - Direct3D 9 11_4_2021 11_09_13 PM](https://user-images.githubusercontent.com/74144694/140452687-19087ef9-5055-4462-927f-85e1f7910b84.png)

### Expected behavior

i die

### Steps to reproduce

play/make and old ap test
jump in to the goo around the edge of the sphere

### Logs and Reports

```shell
None
```

### Additional information

Im not 100% sure witch version of old ap this was, i was playing my friends map when this happened and he left before i could ask him.

**Comment by Konclan** [comment]
I don't believe this is necessarily item related, but it does fit better here.

**Comment by LautaroL20** [comment]
Well, I mentioned items and also styles, these stuff should go in the items repro.

**Comment by CardsAndGamesYT** [comment]
> You have posted in the wrong section, anything related to items or styles must be posted on the items repository, here: https://github.com/BEEmod/BEE2-items/issues
> 
> The section where you have posted is for things related to the BEEmod user interface, only.

ah didn't know that, thanks. i figured it would go under Bee2.4 because it didn't have anything to do with an item lol.
