### ISSUE TITLE
atomic signage

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2-items#3982]
### Description of the feature

![atomicSign](https://user-images.githubusercontent.com/63530071/140604098-3e54daee-1533-4988-b1c4-fbd9e31b5c5b.png)

![fractalSign](https://user-images.githubusercontent.com/63530071/140604100-7d812010-e856-42ba-9d66-cde58ff755e3.png)
infinite
![LazerwavelengthSign](https://user-images.githubusercontent.com/63530071/140604101-64a020fd-0a44-47be-9cc8-241b62c02ecf.png)
wavelength (of red laser)
![LazerredwavelengthSign](https://user-images.githubusercontent.com/63530071/140604103-f1e6cfe1-0e0d-4791-997c-7cdbc5b79a3a.png)
red
![ironSign](https://user-images.githubusercontent.com/63530071/140604104-9ae9baaf-b164-45cc-b3fe-0b6fc4c751f6.png)
iron atom (for explaining the physics shield)
![atomSign](https://user-images.githubusercontent.com/63530071/140604106-1ca424d6-5dd9-4840-925f-baed257e1bc2.png)
atom (for explaining the solid field)
![reflectionSign](https://user-images.githubusercontent.com/63530071/140604107-9f4ef528-0933-4a2e-8409-a8a18e071969.png)
reflecting electrons
![hdrogenSign](https://user-images.githubusercontent.com/63530071/140604108-1bf4285e-0705-4307-8c4d-286409ddcf24.png)
hydrogen atom (for explaining compression smoke field)
![hexagonSign](https://user-images.githubusercontent.com/63530071/140604109-03dca536-703a-40f1-ada6-13fe915c4496.png)
hexagons (order)
![electronSign](https://user-images.githubusercontent.com/63530071/140604110-b38fa0f9-1d00-4ecd-ab3e-784cf567f4d6.png)
Electron (lasers are electrons)

### Why should this be implemented

they are cool and explains the extra field

**Comment by supersean08-pro** [comment]
![rainbowSign](https://user-images.githubusercontent.com/63530071/140605290-1039ca57-f668-4a32-a536-6903b1c99d20.png)
Spectrum
![reversefunnelspeedSign](https://user-images.githubusercontent.com/63530071/140605291-9ddbe397-bc2a-4255-90c7-0f91de70926b.png)
reverse funnel speed
![funnelspeedSign](https://user-images.githubusercontent.com/63530071/140605292-ce4a596f-31ff-43d8-849d-7f939735d4d1.png)
funnel speed
![gravitySign](https://user-images.githubusercontent.com/63530071/140605293-344b3779-3b65-4528-b0ae-ab679d646727.png)
gravity sign
![nogravitySign](https://user-images.githubusercontent.com/63530071/140605295-814443a8-b4f4-4125-be80-afa22e3cc3e4.png)
no gravity sign

**Comment by TeamSpen210** [comment]
These icons are cool, but they're far from clear as to their meaning. Signage also doesn't tend to include text of any kind, with the exception of a 1 and 2 in the corner on some (which isn't critical anyway).

**Comment by TeamSpen210** [comment]
For instance, to explain the physics shield, you could have a horizontal line, with a cube sitting on top and a bendy depicted falling through it.

**Comment by supersean08-pro** [comment]
![physicsshieldfieldSign](https://user-images.githubusercontent.com/63530071/140605921-8497a193-eb7b-4e1e-98b6-c12c125cf8c6.png)

**Comment by supersean08-pro** [comment]
> For instance, to explain the physics shield, you could have a horizontal line, with a cube sitting on top and a bendy depicted falling through it.
![physicsshieldfieldSign](https://user-images.githubusercontent.com/63530071/140605935-1bf539a2-7837-490f-a103-d55cb6d6c0c0.png)

**Comment by FrozenDragon0** [comment]
![image](https://user-images.githubusercontent.com/18079316/140605976-b1d5960f-282c-4a39-b541-14ce354d6f2f.png)

Exactly what is this signage going to be used? I really don't see any use for this signage at all.

**Comment by supersean08-pro** [comment]
another way of saying infinite               ᶦ ᵈᵒⁿᵗ ᵏⁿᵒʷ ʷʰᵃᵗ ᶦ ʷᵃˢ ᵗʰᶦⁿᵏᶦⁿᵍ

**Comment by FrozenDragon0** [comment]
That really does not look like an infinite signage, also a infinite signage is not really needed as a button that is permanently pressed down can be easily identified as a infinite button.

**Comment by supersean08-pro** [comment]
![infiniteSign](https://user-images.githubusercontent.com/63530071/140606400-d0b56be6-8ac6-41a3-a4a5-2385ab586ab5.png)
infinite
![obsoleteSign](https://user-images.githubusercontent.com/63530071/140606401-6b612133-b45a-42bc-97a1-92d9c69a8565.png)
Ǫ̸͕̱̖͙̫̗̺̥́B̴̼̝̘͇̲̥̮̣͓̣͙͍̉̍͌̃̀̃́̐̿͊̊͘̚͝S̷̢͙̰̤̠͓͉̱̣̠͌͊͑͛̒̕Ơ̵̖̼͇̯͔̙̦̹͔͈̖͌̐͆͌̀̾̉̇̀̈́́̔ͅͅL̴̤͕͎̭̙̘͓͈͂E̴̡͍̜͍̽̊͝T̷͎̄̀̀̃̽̉̋̓Ȩ̸̠̥̲̟̂̉̍̽̌̉̉̌!̶̱̹̮͗͛̉́̓̀̌͗́̃̌͘!̴̡̥͎̠̪̜͖̹̞̮̬̦̜̇͆̒̉͐̍̽͝ͅ!̸̛͉̳͎͙̻̰̩͔̼͈͈̀̈̏̔̈͊̓̌͛̿͜ͅͅͅ!̶̡͎͓̭͍̜̺̲̀̎̍̅̇̋̽͜!̶̨̲̺̭͈̥̘̹̱̘͕̆̒͠!̵̣̦̹͕̘͎͍̎̈̀͛̂̋̀̒̈͂̆̽̎͝͝
![omicronSign](https://user-images.githubusercontent.com/63530071/140606402-b4f845b3-00bc-4218-bc7f-d5aabe7ac438.png)
off
![omegaSign](https://user-images.githubusercontent.com/63530071/140606403-b3181eb6-4765-4a1d-92e1-31b7d39ca297.png)
end

**Comment by HeimlichLaboratories** [comment]
Not a dev but IMO a most of these aren't clear in their meaning and nobody would really use these. Would work as a UCP maybe.

**Comment by supersean08-pro** [comment]
omega means end the omicron means off




SYMBOLS!

**Comment by supersean08-pro** [comment]
![wide](https://user-images.githubusercontent.com/63530071/140606963-17e009f7-9a49-4234-8074-e33c31d7c92c.png)

**Comment by supersean08-pro** [comment]
![wallpaper](https://user-images.githubusercontent.com/63530071/140607041-32c06a5b-93d6-4234-82cc-139c62f132c6.png)
4k wallpaper

**Comment by TeamSpen210** [comment]
Okay this is getting a bit ridiculous. I don't think any of these are going to be added.

**Comment by supersean08-pro** [comment]
> Okay this is getting a bit ridiculous. I don't think any of these are going to be added.

okay, but how do i make my own beemod 2 package that adds these, because i want to ad them as a custom package

**Comment by LautaroL20** [comment]
> supersean08-pro said: okay, but how do i make my own beemod 2 package that adds these, because i want to ad them as a custom package

Well, you could just take the Custom Signage Package made by someone who is called "Libbybapa", as an structure example on how to do your own one. This package is available in the **#ucp-releases** from the [BEEmod Discord server](https://discord.gg/EvC8Fku)

**Comment by supersean08-pro** [comment]
> > supersean08-pro said: okay, but how do i make my own beemod 2 package that adds these, because i want to ad them as a custom package
> 
> Well, you could just take the Custom Signage Package made by someone who is called "Libbybapa", as an structure example on how to do your own one. This package is available in the **#ucp-releases** from the [BEEmod Discord server](https://discord.gg/EvC8Fku)

Libbybapa's pack was deleted

**Comment by CardsAndGamesYT** [comment]
> > > supersean08-pro said: okay, but how do i make my own beemod 2 package that adds these, because i want to ad them as a custom package
> > 
> > 
> > Well, you could just take the Custom Signage Package made by someone who is called "Libbybapa", as an structure example on how to do your own one. This package is available in the **#ucp-releases** from the [BEEmod Discord server](https://discord.gg/EvC8Fku)
> 
> Libbybapa's pack was deleted

its not, its literally the first message sent in #ucp-releases
