### ISSUE TITLE
"Test Complete, Restarting" text does not show up

### ISSUE THREAD

**Issue by TheTinkerer256** [BEEmod/BEE2-items#3984]
### BEE2 Application Version

4.40.2 64bit

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Pretty self-explanatory. When I complete my level, the "Test Complete, Restarting" text does not show up.

### Expected behavior

Usually, every PeTI test ends with text appearing saying "Test Complete, Restarting". This is not the case.

### Steps to reproduce

- Started out on BEE2 v 4.36.1, the message still did not show up.
- Stuff would not build, so I futzed around, verified the game files 
- When I verified, it said that 6-7 of the files were messed up, it fixed them
- Bee2 editor stuff still showed up, but the built test was the same
- Futzed around more, scratched head
- Realized the version was outdated, facepalmed :P
- Updated it, build errors fixed, but "Test Complete, Restarting" text still missing

### Additional information

The style is BTS, the player model is Atlas, the skybox is 3d - Factory. 
Maybe worth noting: I have a custom portal gun skin in portal2_dlc4

**Comment by CardsAndGamesYT** [comment]
This tends to happen to me a lot as well. from past experiences it doesn't matter what style, player model, or sky box, it just happens a lot. and it almost always happens wile playtesting portal 1 co-op chambers. however I have seen it happen to me most on overgrown chambers.

**Comment by CardsAndGamesYT** [comment]
I am aware about the check box in beemod (and I'm sure you are too) that disables the auto restart but i always leave it on.

**Comment by TheTinkerer256** [comment]
I don't actually! 😆 Maybe I accidentally turned it on at one point? Can you please tell me where it is?

**Comment by CardsAndGamesYT** [comment]
its in `Item/Style Properties` under `Selected Style`

**Comment by TheTinkerer256** [comment]
I'm afraid I don't see it, it just says "No Options!"

**Comment by CardsAndGamesYT** [comment]
hmm, check under `Other Styles`

**Comment by slambo311** [comment]
Plus, this should probably be in BEE2.4, not BEE2-Items

**Comment by Luke18033** [comment]
This stylevar was never properly implemented for BTS

**Comment by LautaroL20** [comment]
Well, it worths to mention that BTS Style will no longer be available in any future BEEmod release.

**Comment by TheTinkerer256** [comment]
@slambo311 Good to know, both comments
@LautaroL20 That's a bummer, I really like the style
Thank you all!

**Comment by slambo311** [comment]
> That's a bummer, I really like the style

Yeah, I like it too. Don't worry, I'm sure it'll make a comeback someday. But in the meantime, 80s' Aperture could be a good replacement.

**Comment by LautaroL20** [comment]
> slambo311 said: "I'm sure it'll make a comeback someday."

I do not think so, actually the chances of BTS coming back to BEEmod are almost the same as Half-Life 3 being released someday.

**Comment by slambo311** [comment]
I disagree with you but alright.
