### ISSUE TITLE
[dev] Fix Surface marker (special marker)

### ISSUE THREAD

**Issue by Laudanum-dev** [BEEmod/BEE2-items#3985]
as of latest build, they do not work. 
all it takes for them to start working is to change `"Dir" "0 0 -1"` to `"Dir" "0 0 1"` 
(and probably the texture in `Tex`) 
![image](https://user-images.githubusercontent.com/86309764/141169554-12f73c6c-9ea8-45f8-bfa9-1f2847a3f677.png)

the fixed vbsp config shown above produces correct surface markers 
![image](https://user-images.githubusercontent.com/86309764/141166715-e35d8e25-0d99-4a42-9c53-edc29de10267.png)

**Comment by LautaroL20** [comment]
If you open a pull request with your fix, we could merge it for the next BEEmod release that will probably come out in a few days.

**Comment by Laudanum-dev** [comment]
hmm ok i can
