### ISSUE TITLE
Unable to play coop

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2-items#3988]
### BEE2 Application Version

4.40.2

### BEE2 Package Version

4.40.0

### Logs and Reports

```shell
VBSP failed.

[I] cond.core._get_cond_group(): No name for module "precomp.faithplate"!
[I] cond.core._get_cond_group(): No name for module "precomp.fizzler"!
[I] vbsp.main(): BEE2 v4.40.2 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] options.load(): Extra config options: {'staticpan': 'instances/BEE2/over/static_panel/', 'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[I] cubes.parse_conf(): Parsed 9 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 17 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[I] vbsp.mod_entryexit(): Setting Coop Exit to 3
[I] vbsp.get_map_info(): Game Mode: COOP
[I] vbsp.get_map_info(): Is Preview: True
[I] brushLoc.read_from_map(): Analysed map, filling air... (8 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 1938, in main
  File "precomp\tiling.py", line 1608, in gen_tile_temp
  File "precomp\template_brush.py", line 632, in get_template
  File "precomp\template_brush.py", line 447, in _parse_template
  File "srctools\filesys.py", line 155, in __enter__
  File "srctools\filesys.py", line 115, in open_ref
  File "srctools\filesys.py", line 625, in _create_ref
  File "zipfile.py", line 1239, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/super/AppData/Local/Temp/Rar$EXa16524.31471/packages/clean_style.bee_pack'
[12852] Failed to execute script compiler_launch
```

### Additional information

any

portal 1 is a different story

**Comment by supersean08-pro** [comment]
i just need to see my beta coop effect

**Comment by TeamSpen210** [comment]
Where did you put the BEE2.4 app? It looks like a temporary directory for some reason, you can't just delete it after it's installed.

**Comment by supersean08-pro** [comment]
> Where did you put the BEE2.4 app? It looks like a temporary directory for some reason, you can't just delete it after it's installed.

i never deleted it, i have only installed mods, i only deleted it if i play gmod to get more space, but i am now playing with portal 2 and gmod

**Comment by supersean08-pro** [comment]
![20211112112631_1](https://user-images.githubusercontent.com/63530071/141387934-ea1299f8-2c6b-4555-b2a3-7bff98512917.jpg)
WHAT IS THIS BLACK MAGIC

**Comment by slambo311** [comment]
> ![20211112112631_1](https://user-images.githubusercontent.com/63530071/141387934-ea1299f8-2c6b-4555-b2a3-7bff98512917.jpg) WHAT IS THIS BLACK MAGIC

How the hell do you play Garry's Mod but not know what a missing texture is?

Counter-Strike: Source aside, are you using BTS style? Because the Aperture logo is changed depending on the style, in the screenshot it's missing, and BTS is buggy as hell and is getting removed soon.
Either way, you should list the style you're using, OS (Windows, Linux, A Big Mac, etc.)

**Comment by Luke18033** [comment]
Doesn't look like BTS, but that wouldn't cause this anyway, the logo replacement works exactly the same in every style. I'm really not sure what would cause this, besides a very messed up BEE2 install... Try installing it somewhere else, I don't think there's much more help we can give you.

**Comment by Luke18033** [comment]
Also in the future please use Discord or the discussions tab to report hardware-specific issues like this.

**Comment by slambo311** [comment]
Just realized the log shows overgrown stuff being loaded in.

**Comment by supersean08-pro** [comment]
> Doesn't look like BTS, but that wouldn't cause this anyway, the logo replacement works exactly the same in every style. I'm really not sure what would cause this, besides a very messed up BEE2 install... Try installing it somewhere else, I don't think there's much more help we can give you.

it still happens even with the new packages ill try installing it some where else
