### ISSUE TITLE
Connection Signage help

### ISSUE THREAD

**Issue by LazyPlaying** [BEEmod/BEE2-items#3990]
### BEE2 Application Version

4.39.1

### BEE2 Package Version

4.39.1

### Description of the bug

It's not bug but I need some help about that thing
![Скриншот_2021_11_14_18_12_42_181](https://user-images.githubusercontent.com/94288255/141682630-1a70d62d-49a3-4244-b0f5-5b40e048304b.jpg)
I need to make steps sign for my chamber. Steps signs are first in my icons table like that
![Скриншот_2021_11_14_18_17_46_309](https://user-images.githubusercontent.com/94288255/141682687-44b5a03c-095a-4a9e-8c9e-d43513681dc7.jpg)
Then when I started to edit chamber I did that:
![Скриншот_2021_11_14_18_13_19_369](https://user-images.githubusercontent.com/94288255/141682702-a08214d0-3fc8-423b-a923-bb95f38c4430.jpg)
Next step, I tested it. But there were only squares.

### Expected behavior

I thought what that icons will be like this
![Скриншот_2021_11_14_18_17_46_309](https://user-images.githubusercontent.com/94288255/141682780-2f996d52-8031-4493-9285-3d8ec7d382b8.jpg)

### Steps to reproduce

In description

### Logs and Reports

```shell
Nothing
```

### Additional information

![Скриншот_2021_11_14_18_20_54_167](https://user-images.githubusercontent.com/94288255/141682816-18078977-7ab7-4c39-8eea-d7d248b1eec6.jpg)
I added only items. It's clear style (not original textures) and no extra items and addons

**Comment by FrozenDragon0** [comment]
The number indicates what signage is going to be used. Right on the signage item in the Beemod app and it'll tell you some more information.

**Comment by LazyPlaying** [comment]
> The number indicates what signage is going to be used. Right click on the signage item in the Beemod app and it'll tell you some more information.

I need to use sign with 1 point and another with 2 points. I choosed 03 (1 point sign) but when I test the chamber
I see only square (when I use number 3), (not that sign what i indicated in timer option)

**Comment by FrozenDragon0** [comment]
You need to set the number dial to if you want the signage with 1 dot, the way it works is how you placed the signages in the app, when customizing signages it'll tell you which number indicates what signage and you have to set the number dial to the specific number of the signage that you want to use which is indicated in app.

**Comment by LazyPlaying** [comment]
> You need to set the number dial to 00 if you want the signage with 1 dot, the way it works is how you placed the signages in the app, when customizing signages it'll tell you which number indicates what signage and you have to set the number dial to the specific number of the signage that you want to use which is indicated in app.

I didn't understand. Can you help me in discord using video?

**Comment by FrozenDragon0** [comment]
> > You need to set the number dial to 00 if you want the signage with 1 dot, the way it works is how you placed the signages in the app, when customizing signages it'll tell you which number indicates what signage and you have to set the number dial to the specific number of the signage that you want to use which is indicated in app.
> 
> I didn't understand. Can you help me in discord using video?

Oh wait, hang on let me double check if this is a problem in the dev version.

**Comment by FrozenDragon0** [comment]
Okay, looks like this is a bug. Just tested this on the developer version and it shows the signage properly. Could you try changing the number to 04 and 05 and see if it shows other signages? Send a screenshot so I can see in-game.

**Comment by LazyPlaying** [comment]
> Okay, looks like this is a bug. Just tested this on the developer version and it shows the signage properly. Could you try changing the number to 04 and 05 and see if it shows other signages? Send a screenshot so I can see in-game.

This is 04
![Скриншот_2021_11_14_19_19_09_805](https://user-images.githubusercontent.com/94288255/141685097-44200765-abc1-4244-ac98-5f811ed3d9ca.jpg)

This is 05
![Скриншот_2021_11_14_19_20_05_596](https://user-images.githubusercontent.com/94288255/141685111-b6bb76d8-f96b-4bb2-9900-c7ce1443a55f.jpg)

**Comment by LazyPlaying** [comment]
This is 06
![Скриншот_2021_11_14_19_23_13_544](https://user-images.githubusercontent.com/94288255/141685193-86ce8cf0-b4af-4939-b738-bef60ffb9a49.jpg)

**Comment by FrozenDragon0** [comment]
Okay that's weird, the normal signages aren't even available in the signage item to begin with. I have tested this on the developer version and this issue does not occur so it would seem this problem is fixed for the next release.

**Comment by FrozenDragon0** [comment]
Ah, now I see. I think the item you want to use is the normal signage item. You're currently using the connection signage item.

**Comment by LazyPlaying** [comment]
> Ah, now I see. I think the item you want to use is the normal signage item. You're currently using the connection signage item.

I will reintstall BEE2 to the last release and check. If everything will be normal, I will close it

**Comment by HeimlichLaboratories** [comment]
You're using the wrong item. The Connection Signage only has shapes, you want to use the Signage item. This isn't a bug.

**Comment by LazyPlaying** [comment]
> You're using the wrong item. The **Connection** Signage only has shapes, you want to use the Signage item.

![image](https://user-images.githubusercontent.com/94288255/141685727-c29f13c1-8132-4706-ac52-7ad08dab3951.png)
This item is right?

**Comment by FrozenDragon0** [comment]
> > You're using the wrong item. The **Connection** Signage only has shapes, you want to use the Signage item.
> 
> ![image](https://user-images.githubusercontent.com/94288255/141685727-c29f13c1-8132-4706-ac52-7ad08dab3951.png) This item is right?

Yes.

**Comment by LazyPlaying** [comment]
Oh yes! Thank you. I thought that was a bug.
