### ISSUE TITLE
BEEmod RC3: Flip Panel frames are having z-fighting issues in all styles.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3992]
### BEE2 Application Version

RC3 32bit

### BEE2 Package Version

RC3

### What operating system are you running on?

Windows 7 (64bit)

### Description of the bug

As you can see, this issue happens in all styles: 

![Flip Panel frames is having z-fighting issues in all styles](https://user-images.githubusercontent.com/12244376/141690303-e5396f2c-d789-410f-9bc4-8f6531f518d7.jpg)

### Expected behavior

Flip Panels must not produce any z-fighting issues.

### Steps to reproduce

Place a Flip Panel and then build the puzzle, you will see that it will produce z-fighting issues.

### Additional information

This issue happens using any style.

**Comment by TeamSpen210** [comment]
Forgot an `abs()`, whoops.
