### ISSUE TITLE
[dev] Angled panel's backside flickers through portals 

### ISSUE THREAD

**Issue by Laudanum-dev** [BEEmod/BEE2-items#3993]
### BEE2 Application Version

dev

### BEE2 Package Version

dev

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

if you shoot portal on Angled panel and second on somewhere else, from certain areas you can see the panel's back texture flickering in second portal. this happens regardless of panel having or not having inputs. see video for demonstration of it

https://user-images.githubusercontent.com/86309764/141692452-7c7889c9-74a5-44ae-9aa9-38dd89bc3ed3.mp4

### Expected behavior

no such flickering regardless of player position whatsoever

### Steps to reproduce

1. place angled panel
2. enter the chamber
3. place portal on panel and second somewhere else
4. try to walk around until you notice the aforementioned flickering
5. you can try to even locate the area of flickering this way (as i did in video) 

### Additional information

i'm using original clean style. also, i don't know when i noticed this issue exactly, looks not like it was reported before.

**Comment by Luke18033** [comment]
This is a Valve bug, caused by the panels being so thin. It's not really fixable without changing the design of the panels (which we're not doing).
