### ISSUE TITLE
Claw-arm turret dispenser

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/BEE2-items#4]
A different version of the turret dispenser which uses a claw-arm on cables to dispense turrets. It looks normal, but with a turret on claw-arm inside the dispenser. When triggered, the iris opens and lowers a turret down to the floor (distance fed in via Condition instance vars). When it reaches (close to) the floor, the turret is released and can shoot. Once it retracts fully, it retracts further above the iris (as that closes), getting a new turret.

**Comment by BarbarianKabbage** [comment]
Sounds like a great addtion.

**Comment by Konclan** [comment]
This could be in a small room like how an observation room is

**Comment by Luke18033** [comment]
Don't you usually keep issues open until the update is out?
