### ISSUE TITLE
Reflection Gel causes a compile error

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#4003]
### BEE2 Application Version

Dev/4.41.0

### BEE2 Package Version

Dev

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
Traceback (most recent call last):
  File "compiler_launch.py", line 16, in <module>
  File "vrad.py", line 236, in main
  File "srctools\packlist.py", line 852, in pack_fgd
  File "srctools\packlist.py", line 475, in pack_particle
  File "srctools\packlist.py", line 210, in pack_and_get
KeyError: 'CPropPaintBomb'
```

### Additional information

Seems to be an issue with autopacking. I'm using a dev build, but it's on the same commit as 4.41 so it would be identical.

**Comment by LautaroL20** [comment]
This does not happen in the latest BEEmod version nor with RC3, so this is only a dev issue.

**Comment by Luke18033** [comment]
That's weird, it should be the exact same build?

**Comment by LautaroL20** [comment]
Should be, but for some reason (luckily) this issue is not present in the latest release. The thing is, yesterday I was almost to comment "Oh whoops, I have forgot to give a test at the Reflection Gel in RC3", but then today I decided to do a quick test with this in both RC3 and latest release but surprisingly, this issue did not happen.

**Comment by TeamSpen210** [comment]
I pushed a bunch of srctools updates, one fixing this issue - unknown particles shouldn't crash, just warn.

**Comment by Luke18033** [comment]
I have the latest commits pulled, maybe I didn't when I compiled this build?

**Comment by Luke18033** [comment]
Turns out it was using the wrong version of srctools.
