### ISSUE TITLE
Make triggers to have an inbuilt delay option

### ISSUE THREAD

**Issue by MarcusKubis9** [BEEmod/BEE2-items#4008]
### Description of the feature

It would be an option to set the delay time of triggers

### Why should this be implemented

It would be so useful because you wouldn't need to set up some weird thing you could just change it in the ITEMVAR settings

**Comment by Luke18033** [comment]
It'd be an in-editor property, an itemvar would apply to every trigger. This is what the delayer items were created for, though I could see it being useful for triggers to have an inbuilt delay option.

**Comment by HeimlichLaboratories** [comment]
I think this would be pretty useless, since we have the delayer already. IMO

**Comment by Luke18033** [comment]
Yeah probably, I don't think delaying trigger outputs is something you need to do much anyway.
