### ISSUE TITLE
Entrance Corridor N°1 will cause "Failure To Compile" in 70´s Old Aperture 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#4009]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 7 (64bit)

### Description of the bug

Compiling a chamber with or without items in the map will cause a building error in 70´s Old Aperture 

### Expected behavior

Chambers must compile.

### Steps to reproduce

Select the 70´s Old Aperture in BEEmod and export the style to the game and then compile the chamber, it will not.

### Logs and Reports

```shell
[I] <valve>.vbsp(): Could not open instance file instances/bee2/50s/sphere_sp/entry_corridor_1/portrait.vmf
```

### Additional information

I am surprised because this issue did not happen in RC3, so something got mysteriously busted in the public release version, sadly...

**Comment by Luke18033** [comment]
Looks like it might be a bug with corridor 1 specifically, try switching to a different one.

**Comment by LautaroL20** [comment]
Yep, the entrance corridor N°1 is the issue.
