### ISSUE TITLE
70´s Old Aperture Floor Buttons editor models have inconsistencies.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#4010]
In the following image I described the inconsistencies:

![Image](https://user-images.githubusercontent.com/12244376/142298665-74d90b01-ee26-4f8b-8ff9-96341ea85538.jpg)

**Comment by Luke18033** [comment]
The black square is meant to represent the buttons being embedded, but IMO it just looks bad, and doesn't need to be there now that the embed is optional.

**Comment by Luke18033** [comment]
The grating texture in the cube/sphere buttons is also nearly invisible.
