### ISSUE TITLE
Changing the SP entrance or SP Exit corridors while the game is open it will crash if using Overgrown Style

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#4012]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 7 (64bit)

### Description of the bug

Once the game crashes, this is the message:

![Image](https://user-images.githubusercontent.com/12244376/142714942-6d6c5947-2a9d-461c-9fb3-818068525798.png)

### Expected behavior

Game must not crash if I want to change corridors while the game is open when using Overgrown Style.

### Steps to reproduce

Export the Overgrown Style and launch the game, open the puzzlemaker and then minimize the game. Now try changing the SP entrance or SP exit corridors and export it to the game, maximize the game and the crash will happen.

**Comment by Luke18033** [comment]
That's the cube button model, which makes this seem related to #3645...

**Comment by Luke18033** [comment]
#3645 is fixed, so I'm going to mark this as fixed as well. Let me know if it still happens.

**Comment by LautaroL20** [comment]
> Luke18033 said: "Let me know if it still happens."

I will as soon as the BEEmod 4.42 beta build for testers is made, which I think it may take a while.

**Comment by Luke18033** [comment]
Have you tried using dev builds anytime recently? It shouldn't be too hard to build them anymore, there's a guide in the readme.

**Comment by LautaroL20** [comment]
> Luke18033 said: "It shouldn't be too hard to build them anymore, there's a guide in the readme."

That is interesting, last time I tried building the dev version myself a few years ago it was overcomplicated, but if that is not so anymore, I might give it a try then.
