### ISSUE TITLE
P1 maps leak and fail to publish

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#4017]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
VVIS failed.

Valve Software - vvis.exe (May 19 2021)
16 threads
reading d:\steam\steamapps\common\portal 2\sdk_content\maps\1637614769.bsp
reading d:\steam\steamapps\common\portal 2\sdk_content\maps\1637614769.prt
LoadPortals: couldn't read d:\steam\steamapps\common\portal 2\sdk_content\maps\1637614769.prt
```

### Additional information

When building a chamber for playtesting, it will compile fine. However, the problem will come for when I want to publish the chamber becuase a building error will occur if using P1 Style.

### Workaround

Open `Portal 2/bin/portal2.fgd`, and add the following at the top:
```c
@PointClass = hammer_notes: "Fake entity to store notes and comments inside. Won`t spawn."
    [
    ]
```

**Comment by Luke18033** [comment]
It's a leak, check the pointfile in Hammer to see what item is causing it.

**Comment by LautaroL20** [comment]
Alright, Ill do it after reporting 2 more P1 Style issues.

**Comment by LautaroL20** [comment]
This is the pointfile from the P1 map that is supposed to having a leak, but as you can see, there is no entity or something else at neither end of the red line:

![Portal 1 Style map pointfile](https://user-images.githubusercontent.com/12244376/144306527-1a51c2db-aa2c-48c4-8a85-b9cf68026cf7.png)

**Comment by Luke18033** [comment]
That's the wrong file, you want to open `maps/styled/preview.vmf`.

**Comment by LautaroL20** [comment]
Alright, I opened `maps/styled/preview.vmf` with their corresponding pointfile but unfortunately, result was the same as before. There is no entity or something else at neither end of the red line: 

![Image](https://user-images.githubusercontent.com/12244376/144309996-55dc085c-cf57-4934-8eb8-0464b19d60f4.png)

**Comment by Luke18033** [comment]
There's probably a brush entity origin out there, check any that are nearby. If you recompile the map and look for the `***** leaked! *****` warning in the log, it should tell you the classname of the entity that leaked.

**Comment by LautaroL20** [comment]
This is probably the most relevant part of the log but still, it look like that the classname of the entity is not being mentioned:

````
[I] .vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] .vbsp(): fixing up env_cubemap materials on brush sides...
[I] .vbsp(): ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
[I] .vbsp(): **** leaked ****
[I] .vbsp(): Entity hammer_notes (-416.00 64.00 64.00) leaked!
[I] .vbsp():
[I] .vbsp(): FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (1536.0 3072.0 -248.0)
[I] .vbsp(): Leaf 0 contents:
[I] .vbsp(): Leaf 1 contents: CONTENTS_SOLID
[I] .vbsp(): viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
[I] .vbsp(): This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
[I] .vbsp(): Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
[I] .vbsp(): Candidate brush IDs:
[I] <valve>.vbsp(): 
[I] <valve>.vbsp(): [I] <valve>.vbsp(): FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (2048.0 2560.0 -248.0)
`````

**Comment by Luke18033** [comment]
Weird, it says it's a `hammer_notes`, but there isn't one appearing there... Is it not being added to the FGD?

**Comment by TeamSpen210** [comment]
It's not being added to the fgd no, I forgot that entity existed - everything else has a `comp` prefix so I just looked for that.

**Comment by TeamSpen210** [comment]
In the meantime you can fix this by opening up `Portal 2/bin/portal2.fgd`, and adding the following at the top:
```c
@PointClass = hammer_notes: "Fake entity to store notes and comments inside. Won`t spawn."
    [
    ]
```
