### ISSUE TITLE
There is a wall surrounding the SP Entrance which is not properly sealed in P1 Style

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#4019]
This at least happens with the SP Entrance: 2 Right Stairs from P1 Style: 

![Image](https://user-images.githubusercontent.com/12244376/142950674-4abe0cb5-0b2a-4ddf-9d8c-39204df6b81b.jpg)

**Comment by Luke18033** [comment]
I think this is an engine bug which wouldn't be fixable, that wall is a single brush with no gap in the middle.

**Comment by TeamSpen210** [comment]
Is there a brush sticking out from the corridor? If there is the nodraw can replace the real surface in front

**Comment by Luke18033** [comment]
Could check, I don't think so though?

**Comment by Luke18033** [comment]
It's not splitting up the brush but the effect is still there if you look closely, this is just a weird rendering bug
![image](https://user-images.githubusercontent.com/19228201/145659062-7eb5b89d-b7c3-44e3-a404-dd9d272ba776.png)
