### ISSUE TITLE
bottomless pit supports need way to detect pillars, 3 sided walls, and corners

### ISSUE THREAD

**Issue by mario2582** [BEEmod/BEE2-items#402]
@TeamSpen210 and @BenVlodgi - bottomless pit support generation code needs some way to detect pillars, 3 sided walls, and corners and apply a pillar no matter what.

![preview0121](https://cloud.githubusercontent.com/assets/11165643/13820181/8e8e81c6-eb72-11e5-99c5-d5a0b5a8be4d.jpg)

**Comment by TheReviewers** [comment]
What Exactly Are 3 Sided Walls

**Comment by Konclan** [comment]
Duplicate of #229
