### ISSUE TITLE
Less objects work

### ISSUE THREAD

**Issue by CassieCatYT** [BEEmod/BEE2-items#4023]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### Description of the bug

Not sure if this is a problem with beemod, but I appear to be able to use less assets in my chambers before I can't publish them than when I was using an older version

### Expected behavior

I am hoping that something can be done to allow you to put more stuff in your chamber and still be able to publish them

### Steps to reproduce

Put lots of assets (cubes, panels, etc.) in a chamber and try to publish it

### Logs and Reports

"there was an error building the puzzle"

**Comment by FrozenDragon0** [comment]
You need to give us the console log so we can find out what the error is, we cannot provide help without a console log.

**Comment by CassieCatYT** [comment]
not sure if that is the correct error log, but I think it is

**Comment by Luke18033** [comment]
Doesn't look like the right log, there's no actual error in there... Those warnings shouldn't be appearing either though, have you tried re-exporting?

**Comment by CassieCatYT** [comment]
I did try re exporting, didnt change anything until I removed stuff from the map

**Comment by HeimlichLaboratories** [comment]
If you mean PeTI's entity limit idk if they can fix this

**Comment by CassieCatYT** [comment]
Not sure, all I know is that I used to be able to use less entities before it would stop working than now

**Comment by TeamSpen210** [comment]
What errors are you getting? Could you give an example?

**Comment by CassieCatYT** [comment]
it just tells me that there was an issue

**Comment by TeamSpen210** [comment]
Open the developer console, copy out the log there.

**Comment by CassieCatYT** [comment]
didn't show any log related to it, I had the log posted before but I was told it wasn't related to it

**Comment by Luke18033** [comment]
That's because you didn't copy the actual error message. Open the console immediately after the compile fails, you want to copy the big block of red text, and paste it here.

**Comment by CassieCatYT** [comment]
Idk why
but it works now
