### ISSUE TITLE
Unable to connect the Flux Rectangle to other elements

### ISSUE THREAD

**Issue by des7ser3** [BEEmod/BEE2-items#4029]
### BEE2 Application Version

4.40.0 64bit

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

This has gone for multiple versions for me.  The Radiative Flux Rectangle can't connect to anything in the editor.

### Expected behavior

It should connect to other elements.

### Steps to reproduce

Add Flux Rectangle
Press "K" and try to connect it to any object.

**Comment by Luke18033** [comment]
You need the Fizzler Output Relay, fizzler-type items can't properly output so this is used as a workaround.
