### ISSUE TITLE
[Suggestion] Co-op Triggers (Useful for a co-op version of the "Placeable Door")

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#403]
I must to admit ive seen this from an original post from TeamSpen210, and ive found this as a MAGNIFICENT idea (Since im a co-op mapper than SP), and these are some of the parameters for this item:

"Use a trigger_playerteam and logic_coop_manager to correctly handle both players."
"1: Trigger once (when both players touch simutanously)"
"2: Multiple AND"
"3: Multiple OR"
"Perhaps make it 3x3x2 blocks large, so it's easier to trigger"

Link from the original post by TeamSpen210:
https://github.com/TeamSpen210/tspenAddons/issues/18

**Comment by Luke18033** [comment]
This has been implemented via Start Enabled (or maybe it's Reversed, can't remember).
