### ISSUE TITLE
Compiling chamber error with nothing in chamber. VBSP: "access denied"

### ISSUE THREAD

**Issue by Pluto2077** [BEEmod/BEE2-items#4030]
### BEE2 Application Version

4.41.1

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit), Other

### Logs and Reports

```shell
Could not execute the command:
   "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
Windows gave the error message:
   "Access is denied."

VBSP failed.

Failed to start process ("C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf") with working dir (C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/)
```

### Additional information

This happens with all styles, from 1950 to 1980, clean and original clean, and overgrown as well
 as the P1 style this happens even with a brand new test chamber with nothing in it but an observation room, entry door, and exit door. upon pressing build or F9 it immediately pops out "Error building chamber".

**Comment by Luke18033** [comment]
Check Windows Defender's protection history, that's the only thing I can figure would cause this error?

**Comment by LautaroL20** [comment]
Yes, an antivirus interfering with BEEmod must be the most likely reason for your building error. So, in order to solve this issue, you will have to do the following: Make sure any antivirus software is not blocking the executable of BEEmod (BEE2.exe) and add it in your antivirus exception list. Also, you'll have do the same with the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Not doing this may cause a compile error when building your puzzle.

**Comment by LautaroL20** [comment]
After doing that, make sure to export the full BEEmod resources to the game by doing click on: `File > Options`, then go to the Development tab, and uncheck the option `Preserve Game Directories` then export the palette and style to the game and should work. If it doesn´t, then let us know and we will re-open this issue.

**Comment by Pluto2077** [comment]
ok so I only have one true AV software and I whitelisted BEE and vbsp, same for windows defender, all whitelisted
to add to the problem my one AV has turned off anyway so it wouldn't interfere.

**Comment by Pluto2077** [comment]
this is still a very valid issue and if I have still not done it right please let me know because I've been starting world war III with my computer over this for the past 2 months trying to get this to work.

**Comment by Pluto2077** [comment]
> Check Windows Defender's protection history, that's the only thing I can figure would cause this error?

also i checked that it has no history of denying bee or vbsp

**Comment by LautaroL20** [comment]
> Pluto2077 said: "I whitelisted BEE and vbsp, same for windows defender"

You also need to add `vrad.exe` to your antivirus whitelist as well, because otherwise it won't work.
