### ISSUE TITLE
Random Power Outages

### ISSUE THREAD

**Issue by DutchBaller** [BEEmod/BEE2-items#4035]
### Description of the feature

Random power outages similar to the power outage in sp_a2_fizzler_intro where the lights flicker. The power outages would have variables to change how common they occur or whether they occur once and how much dust and screen shaking there is.

### Why should this be implemented

It would improve the collapsed and destroyed feeling the overgrown test chambers have or like in old aperture or Wheatley's tests where he is destroying the facility. It could also be interpreted as earthquakes which could even more give the feeling that you are underground.

**Comment by DutchBaller** [comment]
Similar too the random explosions suggestion in https://github.com/BEEmod/BEE2-items/issues/2053

**Comment by Luke18033** [comment]
Overgrown used to have a feature where observation rooms would shut off randomly, it was pretty annoying so it was removed. Things like that only work in the campaign because they're specially scripted to occur after specific dialogue in a single map, not randomly in basically every map.

**Comment by DutchBaller** [comment]
It could be a optional at least but oh well I guess
