### ISSUE TITLE
Custom Entry/Exit Corridors Not Applying

### ISSUE THREAD

**Issue by Wheatley1723** [BEEmod/BEE2-items#4036]
### BEE2 Application Version

4.41.0 64bit

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

After selecting my corridors in the Beemod application, they do not apply themselves in the actual level nor the published version, instead showing the first corridor selection after random every time.
![Settings](https://user-images.githubusercontent.com/61215449/147314915-d91eae22-12d9-4a88-a7f1-7ea7df454d8a.png)
![Screenshot 1](https://user-images.githubusercontent.com/61215449/147314955-a0f22240-90fa-4c49-8aca-1653991826fe.png)
![Screenshot 2](https://user-images.githubusercontent.com/61215449/147314962-0c43d13d-fe5f-42dc-a633-da6fcb89b40a.png)

### Expected behavior

Selecting a said corridor should make it appear in-game.

### Steps to reproduce

1. Launch Beemod
2. Select any single-player corridors
3. Export to Portal 2
4. Build test chamber
5. Enter the corridor

### Additional information

This seems to affect every style as I have attempted it with each.

**Comment by Luke18033** [comment]
The corridor system was rebuilt in 4.42 so I'd imagine this isn't an issue anymore
