### ISSUE TITLE
Add "High Energy Pellet Collision" option

### ISSUE THREAD

**Issue by The-Brickler** [BEEmod/BEE2-items#4039]
### Description of the feature

Add an option in the Items Properties box that disables player collision with High Energy Pellets, similar to the "Laser Collision" option.

### Why should this be implemented

Energy Pellets instantly killing the player can be really annoying sometimes, especially when you make a small mistake and have to restart from the last save. Having the option to disable collision with Pellets would be really useful for level designers who don't want to worry about that, or for tests that are really tight and have the player getting really close to Pellets.

**Comment by Luke18033** [comment]
This is hardcoded, frustratingly.
