### ISSUE TITLE
Antline Lasers do not produce an output

### ISSUE THREAD

**Issue by meawplex-plus** [BEEmod/BEE2-items#4044]
* Version BEE2 4.41.0
* On Windows 11
* Clean style
* Portal 2 Editor

Title says it all. I tried placing two of them, one on a wall and one on the floor, and connected them with antlines (floor->wall).

Then I connected the floor to a button as input; the wall to an angled panel as output. However, when I tested ingame and powered the button, while the laser went yellow and powered(?), **the wall laser did not produce an output.**
Am I doing it wrong? Or is this a bug?

**Comment by TeamSpen210** [comment]
That should work yes.

**Comment by LautaroL20** [comment]
Well, if TeamSpen said that that should work, but the laser did not produce an output as expected then this is a bug.

**Comment by mohindertalafuse** [comment]
Thank you so much.
