### ISSUE TITLE
Add the Option to Apply Reflection Gel to Cubes

### ISSUE THREAD

**Issue by Wheatley1723** [BEEmod/BEE2-items#4046]
### Description of the feature

You should make it so that you can apply reflection gel to cubes.

### Why should this be implemented

1. It creates another option for those who do not want to use reflection cubes in certain styles.
2. It creates more puzzle options such as needing to create the correct angle in order to direct the laser, rather than always have the laser point where you want it to.
3. The cube is able to stop being reflective, unlike reflection cubes, by washing off the gel wish with cleansing gel. Useful for deactivating certain items such as laser catchers without having direct access with the cube, and even staying in-theme if you're making a gel related level.
![Screenshot 2022-01-04 185041](https://user-images.githubusercontent.com/61215449/148148214-ab6df5df-5854-4f27-b657-61363c9375a4.png)

### Additional information

![Screenshot 2022-01-04 185118](https://user-images.githubusercontent.com/61215449/148148274-78779a9d-2b30-46e2-a615-44e29587152f.png)

**Comment by Luke18033** [comment]
We can't modify the gel system like this.

**Comment by FrozenDragon0** [comment]
This is not possible to do without source code access.
