### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 4ikan** [BEEmod/BEE2-items#4049]
Hello! How i do install custom music like from portal reloaded to beemod?

**Comment by LautaroL20** [comment]
Luckily, a user called "|ScientisT|RU|" has made an "user-created-package" which has the music from Portal: Reloaded that you can install in BEEmod. You just need to join the [BEEmod Discord Server](https://discord.gg/hnGFJrz) and then go to the "ucp-releases" section and you will find this package there.

**Comment by LautaroL20** [comment]
I just forgot to mention that in order to install a UCP (user-created-package), first you should have a `package` folder in your BEEmod folder, then you follow these easy steps:

1. Find that `package` folder in your BEEmod folder.
2. Yet/put in the UCP in that folder.
3. Be happy.
