### ISSUE TITLE
No sound effect (or too low) on the "Laser Catcher" in all the "Old Apertures".

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#406]
This bug only affects Laser Catchers.

**Comment by Luke18033** [comment]
I haven't noticed this, so it might be fixed now? I don't use Old Aperture much though.

**Comment by LautaroL20** [comment]
Well, i don´t see any commit reference to it so i guess its not fixed yet, but i might give it a test.

**Comment by Konclan** [comment]
The Laser Catcher makes a sound in old aperture so I think this was fixed
