### ISSUE TITLE
ability to customize fog

### ISSUE THREAD

**Issue by CassieCatYT** [BEEmod/BEE2-items#4060]
### Description of the feature

i think it would be nice to be able to customize the color and density of the fog

### Why should this be implemented

I think this could help make areas look bigger or smaller as well as changing the mood

**Comment by HeimlichLaboratories** [comment]
I agree, skyboxes and fog really should be customizable apart.

**Comment by slambo312** [comment]
Yeah, maybe even items that change the fog distance when enabled.

**Comment by TeamSpen210** [comment]
This already exists, the "skybox" option changes the fog settings.

**Comment by Luke18033** [comment]
I think this was a suggestion to add custom fog options (without having to make a new package)

**Comment by HeimlichLaboratories** [comment]
> This already exists, the "skybox" option changes the fog settings.

No, this person is suggesting to customize fog apart.

**Comment by CassieCatYT** [comment]
What I am suggesting is that you have the ability to customize the color and density of fog individually.
