### ISSUE TITLE
add old aperture version rocket turret

### ISSUE THREAD

**Issue by 1209-57238032** [BEEmod/BEE2-items#4063]
### Description of the feature

alternate for rocket turret in old aperture

### Why should this be implemented

i think add old aperture version rocket turret

### Additional information

add old aperture version rocket turret

**Comment by Luke18033** [comment]
We do need an Old Aperture rocket turret, someone will need to make the model for it though.

**Comment by HeimlichLaboratories** [comment]
I think I read in an old issue that it was supposed to be a cannon

**Comment by 1209-57238032** [comment]
or maybe was a bazooka

**Comment by ErinRoseWebs** [comment]
coming back to this, yee yee! im thinking of some ideas for the design of this Old Aperture rocket turret, but its kinda hard finding good references i could expand upon that could fit in the Portal universe.

**Comment by Konclan** [comment]
It would be helpful if you provided concept art or ideas.
Rocket turrets are extremely low priority anyways so I'm closing this unless someone has some valuable input.
