### ISSUE TITLE
portal 1 pellets are Green

### ISSUE THREAD

**Issue by epicGamingA** [BEEmod/BEE2-items#4069]
why is it green I don't know let me get the flies Done
[Green_Pellet_Bug.zip](https://github.com/BEEmod/BEE2-items/files/7919586/Green_Pellet_Bug.zip)
oh and the goo is green too but I think that is normal oh and I cant find the Lin file

**Comment by FrozenDragon0** [comment]
Can you post a screenshot of the goo please?

Also green energy pellets are a thing, are you sure you didn't select the incorrect pellet item by mistake?

**Comment by epicGamingA** [comment]
i can look

**Comment by epicGamingA** [comment]
i picked the right one right the High Energy Pellet Emitter Right?

**Comment by FrozenDragon0** [comment]
> i picked the right one right the High Energy Pellet Emitter Right?

Yes, if it's set to infinite then it'll become a green energy pellet which is the option you have selected.

**Comment by epicGamingA** [comment]
inf

**Comment by epicGamingA** [comment]
just updated it

**Comment by FrozenDragon0** [comment]
Okay, now can you send a screenshot of the goo please?

**Comment by epicGamingA** [comment]
i did the command Screenshot but i cant find it

**Comment by FrozenDragon0** [comment]
> i did the command Screenshot but i cant find it

That's not how you screenshot... Press Shift + Printscreen then CTRL + V onto here.

**Comment by epicGamingA** [comment]
![image](https://user-images.githubusercontent.com/84932495/150661834-c76bfff7-d20a-4d85-acf9-7a2c366b709e.png)

**Comment by epicGamingA** [comment]
this is what it looks like in side goo

**Comment by epicGamingA** [comment]
![image](https://user-images.githubusercontent.com/84932495/150661848-66cdb3f9-a0d2-43b3-8e9a-f22442586b19.png)
outSide

**Comment by epicGamingA** [comment]
and the inside goo was showing in my maingame

**Comment by epicGamingA** [comment]
wait i think its normal

**Comment by epicGamingA** [comment]
why is the goo in my mind more yellow

**Comment by FrozenDragon0** [comment]
That's how Portal 1's goo is meant to look, it's Portal 1 style.

**Comment by epicGamingA** [comment]
oh
