### ISSUE TITLE
Add a timer option to Auto-Portals and Portal Gun Pedestals

### ISSUE THREAD

**Issue by RobinRattus** [BEEmod/BEE2-items#4072]
### Description of the feature

Portal gun pedestals and Auto-Portals should get a timer option to allow choosing different Portal Linkage ID's. (Use change_portalgun_linkage_id when picking up a portal gun with a changed ID.)

### Why should this be implemented

I think adding this would improve Auto-Portals and Portal gun Pedestals because you can have more than 2 Portals active at once.

### Additional information

Automatically set r_portal_fastpath to 0 when using any of these 2 items and change it back to 1 after completing the chamber.
![20220127144435_1](https://user-images.githubusercontent.com/78902172/151371018-3a36c518-3591-43a3-a506-2d0494bfbffa.jpg)

(Used the normal portalgun and change_portalgun_linkage_id command to show what it would look like ingame)

**Comment by Luke18033** [comment]
We can't use `change_portalgun_linkage_id` since it requires cheats to be enabled, we can add this to autoportals though since they have a keyvalue for it.

**Comment by HeimlichLaboratories** [comment]
Honestly I think this would be very confusing and very easy to use wrong. Unless the different pairs had different colors (which I don't know it's possible) I don't think this would work. I'm not a developer though.

**Comment by TeamSpen210** [comment]
It would be confusing yeah, and as far as I know the colours are very hardcoded.

**Comment by Luke18033** [comment]
There are ways I know of to customize the colors but they're only really usable with the ability to override default materials (i.e. in a mod).
