### ISSUE TITLE
error in deatly goo in underground in updated BEE2.4 v4.41.0

### ISSUE THREAD

**Issue by werdkindom** [BEEmod/BEE2-items#4073]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.1

### Description of the bug

the deatly goo is a bug in underground because not pops up i chosse other style from underground and not pops up 
a glitch appears

### Expected behavior

help

### Steps to reproduce

help

### Logs and Reports

```shell
help from this bug in deatly goo in underground plz
```

### Additional information

help

**Comment by FrozenDragon0** [comment]
Closing due to a lack of a response.
