### ISSUE TITLE
An option to allow floating parts and parts inside each other

### ISSUE THREAD

**Issue by DogeisCut** [BEEmod/BEE2-items#4074]
### Description of the feature

Simple suggestion, allow situations like this:
![image](https://user-images.githubusercontent.com/23178844/151696043-297ab84b-aa6d-4cdc-8cf3-afed9e9774d8.png)
and this:
![image](https://user-images.githubusercontent.com/23178844/151696065-2710a397-d439-4434-b90f-fa58d105fca9.png)

### Why should this be implemented

I think that allowing this would give so much more freedom to the editor especially when it comes to adding structures with flat blocks, slopes, and partial blocks. Sure some people would abuse this feature but I think it's necessary.

### Additional information

If this is a hardcoded limitation that cannot be added or something, I apologize. Maybe instead of removing the error, just force the puzzlemaker to build anyways?

**Comment by FrozenDragon0** [comment]
Not possible, and you can't force the puzzlemaker to build if there is an error.
