### ISSUE TITLE
Add Button Type and remove Gel Type from Gels

### ISSUE THREAD

**Issue by RobinRattus** [BEEmod/BEE2-items#4075]
### Description of the feature

Gels should get a button type option and remove the gel type option so that it's possible to have all 5 gels (Normal ones and reflection) in 1 palette slot.
![20220130194739_1](https://user-images.githubusercontent.com/78902172/151713171-486ee770-3e53-4f45-90ba-3c66375593d9.jpg)

### Why should this be implemented

I think doing this would save one palette slot in the editor.

**Comment by Luke18033** [comment]
That's Cube Type, and I don't think this is possible, I think a bunch of things are hardcoded to assume it uses Gel Type. This would also break backwards compatibility with existing maps.
