### ISSUE TITLE
how do i use the paint gun?

### ISSUE THREAD

**Issue by epicGamingA** [BEEmod/BEE2-items#4080]
i have the aperture tag preset on but I cant find the paint gun help

**Comment by CardsAndGamesYT** [comment]
Are you in ap tag?

**Comment by epicGamingA** [comment]
?

**Comment by FrozenDragon0** [comment]
Do you actually own Aperture Tag? The paint gun only works in that game at the moment.

**Comment by epicGamingA** [comment]
ohhhhh no i do not own apeture tag

**Comment by epicGamingA** [comment]
i will close it now
