### ISSUE TITLE
Disable r_portal_fastpath in P1 maps

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#4083]
With P1 now having doorless entry mode, it's possible in rare cases for more than 4 portals to be visible onscreen - if the entrance and exit worldportals, corridor 4 obs room worldportal, and both player portals are all visible at once. This is only made worse by the world portal item UCP (and #574 if we ever make up our mind on that). We've had fastpath disabled by default for a little while in P2CE and it hasn't caused any problems, so it'd probably be good to do that in BEE P1 maps. Perhaps Old Aperture as well since it has the large obs room worldportal, and I might add a doorless entry to 70s later on.

**Comment by ErinRoseWebs** [comment]
maybe just disable it entirely via the arrival logic, and re-enable it via the departure logic? would be better, especially with the World Portals UCP.

**Comment by Luke18033** [comment]
Actually yeah, not sure why we need to limit it to P1. Probably won't re-enable it at the end of maps, there's no way to make sure that happens if the player quits the map early and as I said keeping it off hasn't caused any issues. It doesn't persist across game restarts, so it'll eventually get turned back on anyway unless you've got it in your autoexec.

**Comment by ErinRoseWebs** [comment]
fair. but yeah, turning it off via the arrival elevator logic would definitely help.

**Comment by ErinRoseWebs** [comment]
hell, this lil thing could be added to the transition ents thats included in all maps. means i only need to edit one instance.

**Comment by ErinRoseWebs** [comment]
oh i just now noticed this got the Done label. nice.
