### ISSUE TITLE
Combine Laser items using cube type

### ISSUE THREAD

**Issue by RobinRattus** [BEEmod/BEE2-items#4084]
### Description of the feature

Laser Emitters/Receivers/Relays/Sendificators/Sendificator Slims should be improved by adding a cube type option to them in order to save 4 Pallette slots.

### Why should this be implemented

I think doing this would save a few Pallette slots.

### Additional information

![CubeTypeLaser](https://user-images.githubusercontent.com/78902172/153908410-641ed91f-3b11-4afc-8750-73ee7560aa40.png)

This saves 4 Pallette slots by only needing to add 1 item to your pallette to get all 5.

**Comment by RobinRattus** [comment]
oh wait i just noticed sendificators use 2 spaces but all the others only 1
and they all have different hitboxes this prob wont work ig

**Comment by Luke18033** [comment]
Yeah that's the problem, also they have different properties, and only the laser emitter should have the beam preview. The ability to combine items is very limited.

**Comment by Luke18033** [comment]
The sendificators have different collisions, so they can't be combined. Laser catchers and relays could maybe be combined actually, though since they're default items we still need to figure out the problem of what to do with the other one...

**Comment by LonelySauce** [comment]
Well this fucking sucks, here I was about to make an issue suggesting this exact thing and it turns out it's hardcoded into the game.

WHY VALVE WHY??!?!
