### ISSUE TITLE
Old Aperture monitors still play shatter sounds/effects

### ISSUE THREAD

**Issue by IggyHopKoopa** [BEEmod/BEE2-items#4085]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

As of BEE2.4's 4.41.0 version, the monitors in 1950 through 80 Old Ap chambers have replaced with grayscale CRT screens, which is a nice touch. However, these new monitors lack a smashed/cracked variants like the ones used in Clean style chambers, shown below. I'm not sure if this is a hardcoded issue, but it would be really nice to see it fixed.
![oldapsmashedmonitors](https://user-images.githubusercontent.com/68620059/153969310-5d95b463-36c1-4b91-97ae-2977381b3b05.png)

### Expected behavior

The monitor should show a cracked/smashed version when it gets hit.

### Steps to reproduce

Step 1. Switch to any of the Old Ap styles in BEE2.4
Step 2. Place the Monitor in the palette and export.
Step 3 . Open the Puzzlemaker, place the Monitor, then compile.
Step 4. Enter the chamber and destroy said Monitor.
Step 5. Observe that it is not cracked.

**Comment by Luke18033** [comment]
If it still plays the smash sound this would be a bug, but otherwise it's intentional - the inside of a CRT needs to be a vacuum, if the screen shatters it fills with air and stops working. For BEE2 monitors, that would be pretty bad if the screen was displaying vital information, so we avoid the issue by just not having the screens be breakable.

**Comment by IggyHopKoopa** [comment]
If that's the case, you may want to remove their smashing functionality entirely for the Old Ap. variants. There are still some things that can break them in rare cases like stray Energy Pellets or cubes.

**Comment by Luke18033** [comment]
What do you mean things can break them, there literally isn't a broken version for it to use...does it just play the sounds?

**Comment by Luke18033** [comment]
Ah alright
