### ISSUE TITLE
Add a spotlight

### ISSUE THREAD

**Issue by CassieCatYT** [BEEmod/BEE2-items#4087]
### Description of the feature

Add an adjustable spotlight that has dynamic shadows like the large observation room

### Why should this be implemented

would work for more dramatic lighting and visuals

**Comment by Luke18033** [comment]
Please provide more details, how would this look, how would you aim it? Also note that there's a limit of a single projected texture (fancy large obs room light) enabled at one time, so this would need to override that and you'd only be able to have one.

**Comment by HeimlichLaboratories** [comment]
There can only be a projected texture on at a time in a Source map. Besides, how would this work? you would need a prop to emit that light, and a random dynamic light emitting prop wouldn't fit in a clean test chamber. This is the kind of thing you should use Hammer for. Also the devs have said that darkness shouldn't be a puzzle element.

**Comment by Luke18033** [comment]
It wouldn't be a test element, basically just an aimable projected texture (probably using the faith plate target similar to cameras). We would need a model for it though.

**Comment by HeimlichLaboratories** [comment]
Though it would need a light prop to come with it, since a projected texture coming from nowhere would look kinda weird

**Comment by HeimlichLaboratories** [comment]
> It wouldn't be a test element, basically just an aimable projected texture (probably using the faith plate target similar to cameras). We would need a model for it though.

theoretically you could use the projected texture helper model, it's in the game files

**Comment by Luke18033** [comment]
We're not using the Hammer model, that would look really out of place in a test chamber.

**Comment by HeimlichLaboratories** [comment]
I meant as an editor model. Idk what would you use in game

**Comment by Luke18033** [comment]
Closing for now, I'll reopen this if someone makes a model for it
