### ISSUE TITLE
Stylevar to use the black beta textures

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2-items#4088]
### Description of the feature

While the current black tiles are dark gray, the beta ones are actually black, which in my opinion look better. I suggest adding a stylevar so the black tiles are replaced by the beta ones. White textures wouldn't be replaced as the beta white textures lack detail. This is NOT a beta style suggestion.

### Why should this be implemented

I think it would be a nice little aesthetic change, and the beta tiles give a better contrast with the white walls, imo. It wouldn't be an issue since the black beta tiles are in the game files.

**Comment by Luke18033** [comment]
If you want the darker tiles everywhere you can override the textures yourself, we're not adding an option for this
