### ISSUE TITLE
The editor thinks that the lifeform Sensor is a signal output, not an input.

### ISSUE THREAD

**Issue by Artemvar41** [BEEmod/BEE2-items#4089]
I can't set up the lifeform detector. For example: it is not possible to connect a lifeform sensor to a door. And if you connect to input A or B, then the editor thinks that this is an output and not an input. If connected to a button, the field will simply turn on / off.

**Comment by TeamSpen210** [comment]
Due to a bug in the editor, fizzlers can't have actual outputs. So you need to place a Fizzler Output Relay on top, and add an output from that.
