### ISSUE TITLE
problem with BEEmod

### ISSUE THREAD

**Issue by Baldi132** [BEEmod/BEE2-items#4098]
I'm having errors with my current BEE2. for instance, incinerators won't work correctly. and every time I load the map the game crashes. if anyone knows how to fix this problem contact me ASAP
![20220305082544_1](https://user-images.githubusercontent.com/101011453/156891359-1e35cdbf-fec7-4196-9f1c-b64f5eb44c7c.jpg)
.

**Comment by Luke18033** [comment]
There are no incinerators in the default pack, please bring this up with the author of the UCP they're from
