### ISSUE TITLE
Suggestion for Gel Droppers

### ISSUE THREAD

**Issue by Baldi132** [BEEmod/BEE2-items#4099]
### Description of the feature

as for the gel droppers, we only got the plain old gel droppers we used to have. now I wanted to make a Suggestion to see if we could get Normal Cube Droppers that look like Gel Droppers like a stylevar cube dropper as a gel dropper. I also know that Adhesion Gel was Discontinued like to see it in the Future.

### Why should this be implemented

I think this should be Implemented because it would be a cool test element to add.

**Comment by Luke18033** [comment]
[We can't add Adhesion Gel.](https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#can-you-add-adhesion-gelsome-other-custom-gel-to-bee24) Gel droppers that look like cube droppers would just be confusing, Valve gave them a unique model in the Puzzlemaker for a reason.

**Comment by Baldi132** [comment]
bruh

**Comment by FrozenDragon0** [comment]
> bruh

If we had gel droppers use the cube dropper model people would most likely complain that they won't know which one is which, as Luke stated, Valve them their own model for a reason.

**Comment by Areng14** [comment]
I was actually hoping for it to happen but I kinda understand it now. Its still possible to make them with a UCP

**Comment by FrozenDragon0** [comment]
> I was actually hoping for it to happen but I kinda understand it now. Its still possible to make them with a UCP

Droppers you can, just not adhesion gel.

**Comment by Baldi132** [comment]
can it be an a UCP package then?
it isnt confusing to me

**Comment by Luke18033** [comment]
Someone can make it if they want
