### ISSUE TITLE
Add an option for cube droppers to drop painted cubes

### ISSUE THREAD

**Issue by RobinRattus** [BEEmod/BEE2-items#4100]
### Description of the feature

Cube droppers should be improved by adding a gel type option (defaults to clean which means no gel). If this is set to repulsion or propulsion it'll lower the cubes kind of like the turret droppers but it wont drop them, you can only remove them by grabbing them (This is to prevent repulsion gel cubes to just bounce around the chamber).

### Why should this be implemented

I think adding this would improve cube droppers because you won't need a gel dropper to get painted cubes.

### Additional information

Maybe you could also add something like having the cube dropper be a different color depending on what gels it has.

**Comment by Critfish** [comment]
This already exists, just place a corresponding gel splat below a cube dropper.

**Comment by FrozenDragon0** [comment]
Already exists as @Critfish has said.

**Comment by HeimlichLaboratories** [comment]
This would be better separate tbh. The splat option is actually very annoying since sometimes you want a cube to drop in a pit of gel and you find out it's already painted.

**Comment by RobinRattus** [comment]
oh sry i didnt know that
