### ISSUE TITLE
Allow rocket turrets to be placed on walls

### ISSUE THREAD

**Issue by RobinRattus** [BEEmod/BEE2-items#4103]
### Description of the feature

Rocket turrets should be improved by letting them be placed on the walls of the chamber.

### Why should this be implemented

I think doing this would improve rocket turrets, because you could use them while riding a funnel.

### Additional information

![grafik](https://user-images.githubusercontent.com/78902172/158228208-ee17a01e-be4d-4d1c-b2ed-de172a9c3861.png)

**Comment by Critfish** [comment]
Could be a neat addition, though I'm struggling to think of a puzzle application for these that isn't already fulfilled by just placing them on the floor. It'd be a pain to align the rockets with your portals as the turrets would pretty much always be pointing at you from odd angles.

**Comment by Luke18033** [comment]
Maybe there's some sort of hack I could do by swapping out the actual rocket turret entity for a dynamic prop when extending and retracting

**Comment by Critfish** [comment]
Honestly, the more I think about this, the more I think it probably wouldn't be useful for puzzles anyway. Rocket turrets are most useful when mounted on floors, as its easier to aim their rockets through your portals. The most likely thing people will do with wall and ceiling-mounted ones is placing them down everywhere to add "challenge" which is obviously a no-no.

**Comment by TeamSpen210** [comment]
It does seem awkward and buggy on other surfaces.
