### ISSUE TITLE
how does third party works

### ISSUE THREAD

**Issue by epicGamingA** [BEEmod/BEE2-items#4104]
I just got some third-party items off the discord but do the player needs to get the items too?

**Comment by Areng14** [comment]
Nope they do not need to get the item

**Comment by Areng14** [comment]
Also by third party do you mean UCPs?

**Comment by epicGamingA** [comment]
yea i think

**Comment by Luke18033** [comment]
Please don't open issues to ask questions, this isn't a discussion forum

**Comment by epicGamingA** [comment]
sorry
