### ISSUE TITLE
Make the Signage item like the Quarter Tiles 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#4127]
### Description of the feature

A suggestion made by "Critfish": "Make the Signages like quarter tiles, with light strip handle and "cube type" for four individual orientations, then have "start reversed" to make the signage face the other way." 

### Why should this be implemented

"This way you can effectively (unfortunately with some finagling, but this is the best we can do) position any signage in any position on a surface facing any direction you want. With this method, it'll be easier to do certain signage combinations and would generally be an improvement over the current system."

### Additional information

This is an interesting suggestion that I saw in the BEEmod discord from an user called "Critifish" and I wanted to post it here so it does not get lost in a channel chat.

**Comment by Critfish** [comment]
Forgot to post this myself, thanks for doing it for me.

I feel like it's also worth mentioning that this can greatly help as the selection of signages increases with new additions, and more specific signage combinations crop up (eg. pairing fling signages together) where just pairing them with a generic arrow signage would be less helpful.

**Comment by TeamSpen210** [comment]
This is a bit of a duplicate/variation of #3940.
