### ISSUE TITLE
Inputs on Conductive Plate not working

### ISSUE THREAD

**Issue by EuroSzymon** [BEEmod/BEE2-items#4147]
![image](https://user-images.githubusercontent.com/104522234/169108098-43d1fa5e-c90d-4e0b-898b-6f7741a3a048.png)

**Comment by TeamSpen210** [comment]
That looks correct, it'll illuminate, but the output doesn't activate until the inputs are on also.

**Comment by EuroSzymon** [comment]
> That looks correct, it'll illuminate, but the output doesn't activate until the inputs are on also.

I unchecked the output (door) activation option on startup and the door (output) would not open even though the **conductive plate was connected to the door**

**Comment by vrad-exe** [comment]
Seems to work fine in v4.44

**Comment by EuroSzymon** [comment]
A issue which has been here for "ages" - in other words it took 2 years just to make sure and fix it.
Anyway, congrats for a very long-awaited fix
