### ISSUE TITLE
Paint Fizzlers not Cleaning Gel Cube Droppers

### ISSUE THREAD

**Issue by BigSmartBear** [BEEmod/BEE2-items#4150]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

So, as you know, when you put a paint splat on a cube dropper, it will drop a cube with the paint already on it (I will reference to it as a gel cube dropper). And you also know how paint fizzlers remove gel from cubes, spheres, etc. I have done some testing, and I have found that cubes dropped from gel cube droppers are not cleaned by paint fizzlers. As a side note, I also found that Franken cubes are never cleaned either way (even though they don't bounce anyway). I have only tested this with 1950's Old Aperture Style- but I doubt changing any of that would make a difference.

### Expected behavior

I expected cubes dropped from cube gel droppers to be cleaned by paint fizzlers.

### Steps to reproduce

1. Place a cube dropper in your test.
2. Put a paint splat on said dropper.
3. Place a paint fizzler is your test next to the dropper.
4. Play your test chamber.
5. Grab the cube that is covered in gel that has been dropped by the dropper.
6. Go through the paint fizzler with the cube.
7. The cube is not cleaned.

### Logs and Reports

```shell
N/A
```

### Additional information

Settings:
https://user-images.githubusercontent.com/101303364/170885328-fbc2c976-8a8f-44dc-b6d3-85e1660bce3e.mp4

Footage:
https://user-images.githubusercontent.com/101303364/170885817-9fe167c2-326a-412d-8c96-23ebe81b1b62.mp4

**Comment by BigSmartBear** [comment]
Is this being looked at anymore?

**Comment by Luke18033** [comment]
It was never really being looked at to begin with, there are hundreds of other issues on here we have to worry about and we also have lives outside of BEE. Be patient, it will be looked at eventually.

**Comment by BigSmartBear** [comment]
I understand, I'm sorry for my impatience. I'm just anxious.
