### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Diamond-Thing** [BEEmod/BEE2-items#4153]
So recently i installed Beemod 2.4, but i am experiencing an issue, after playtesting a level, i decided to go to the editor, when i did go to the editor, the game crashed, when i booted it up and tried to open the editor, it crashed again, do you know how to fix this? (also if this problem has been reported before, sorry for reporting an issue that is already known by the devs)
EDIT: This issue has been solved

**Comment by Diamond-Thing** [comment]
the specific items i used were: Overgrown Style, Grates, Cubes, Cube Botton, a Pedidistal Button, and many fizzlers

**Comment by Luke18033** [comment]
When does it crash, is it when you open the map or when you click "create test chambers"? If it's the latter, try deleting `Portal 2/portal2/puzzles/autosave.p2c` (and any copies of that file in the randomly numbered folders).

**Comment by Diamond-Thing** [comment]
> When does it crash, is it when you open the map or when you click "create test chambers"? If it's the latter, try deleting `Portal 2/portal2/puzzles/autosave.p2c` (and any copies of that file in the randomly numbered folders).

yep, when i press Create Test chamber, now where do i find that string?

**Comment by Diamond-Thing** [comment]
> When does it crash, is it when you open the map or when you click "create test chambers"? If it's the latter, try deleting `Portal 2/portal2/puzzles/autosave.p2c` (and any copies of that file in the randomly numbered folders).

thank you so much
