### ISSUE TITLE
Old Aperture Flip Panels leak

### ISSUE THREAD

**Issue by SonicMaster519** [BEEmod/BEE2-items#4154]
### BEE2 Application Version

4.41.0 64bit

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

I did a quick search related to this bug and while many had the same issue I am having, the solutions provided did not work and they were in older versions, too.
My problem is whenever I try to publish my test chamber, it begins building it, but it seems like it stops once the Visibility bar is almost full, saying "Build Error: There was an error building the puzzle." My console pulls up with this:

SonicMaster519 unpaused the game
[PORTAL2 PUZZLEMAKER]  Saved puzzle: puzzles\76561198854030905\1655179900.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/1655179900.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (20,15,9)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 59 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 23298 (ms)

VVIS failed.

Valve Software - vvis.exe (Nov 14 2021)
20 threads
reading d:\steamlibrary\steamapps\common\portal 2\sdk_content\maps\1655179900.bsp
reading d:\steamlibrary\steamapps\common\portal 2\sdk_content\maps\1655179900.prt
LoadPortals: couldn't read d:\steamlibrary\steamapps\common\portal 2\sdk_content\maps\1655179900.prt

I've noticed that this "vvis.exe" has a date of November 14, 2021, when the last version was released. I have not experienced any crashing or issues like this before installing BEE2.4. Any help would be appreciated!

### Expected behavior

I expect that my test chamber would build properly and I would be able to publish it.

### Steps to reproduce

Step 1: Make a test chamber in the 1950s Aperture style.
Step 2: Press Publish.
Step 3: There it is, a build error.

### Additional information

This seems to only happen on the 1950s Aperture style, as other styles do not glitch like this. It's also worth noting that Rebuild works fine and I can playtest it, but pressing Publish is when issues arise.

**Comment by SonicMaster519** [comment]
Ah, so that explains why I just noticed the outside of the test chamber seems to have the Hall of Mirrors effect. Also, thanks for the quick response! Here's the ZIP file you asked for, and I do not have any User Created Packages installed.
[Previews.zip](https://github.com/BEEmod/BEE2-items/files/8903597/Previews.zip)

**Comment by SonicMaster519** [comment]
Ok, sweet, thanks, I will try this out and let you know if this works or not!
Sorry for having to make you look at my horrible map design.

**Comment by SonicMaster519** [comment]
Thanks for the help, it worked! Just want to add that this mod is fantastic and I was not expecting a response that early. I didn't even think I would get a response! Once again, thanks.

**Comment by Luke18033** [comment]
Keep it open, we need to fix the issue properly

**Comment by Luke18033** [comment]
If everything is working properly, it shouldn't be possible to get leaks in the puzzlemaker, so if you can we consider it a bug.

**Comment by SonicMaster519** [comment]
Oh, sorry, my bad. If needed I will test all other styles I haven't tested yet to check for leaks and update you. Is that good with you? I will use the flip panels and try to replicate the bug.

**Comment by Luke18033** [comment]
You can if you want, but you probably won't find anything. The reason it happens in Old Aperture is because of the wheel model added at the top of the panel, which is accidentally sticking out into the void.

**Comment by TeamSpen210** [comment]
This is amusing, it's from debugging `info_target` entities, which I didn't actually hide so VBSP was trying to compile them. And if you open it in Hammer it reads the visgroup settings and makes them hidden, hiding the bug.
