### ISSUE TITLE
Prospekt Theme

### ISSUE THREAD

**Issue by oldalx2020** [BEEmod/BEE2-items#4158]
### Description of the feature

I think there should be a portal beta theme.

### Why should this be implemented

This would be great for very weird and strange items.

### Additional information

![image](https://user-images.githubusercontent.com/108958771/178076007-fa62ea50-b700-47e2-85b8-6a7baa490f4f.png)

**Comment by Konclan** [comment]
[Please read the FAQ before posting](https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#can-you-add-new-style-x)
