### ISSUE TITLE
Piston platform is unable to be activated by buttons if it starts in an extended or partially extended position

### ISSUE THREAD

**Issue by XenonZed** [BEEmod/BEE2-items#4162]
### BEE2 Application Version

4.41.0 64-bit

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

If the piston platform object is placed in a level, its starting position (indicated by the ball handle in the editor) is set to be at least one block above the floor it is placed on, and then it is connected to an input, it will fail to extend or retract when the input is activated. It will however function correctly if its starting position is flush with the floor, or if there is no input connected to it. This means it is impossible to use a button to retract a piston platform.

### Expected behavior

The piston should extend/retract when an input is activated regardless of its starting position.

### Steps to reproduce

1. Place a piston platform.
2. Change its starting position to be at least one block above the floor.
3. Connect the piston platform to an input. (i.e. a weighted button)
4. Compile the level.
5. Step on the button. The piston platform will fail to activate.

### Additional information

I'm using the "Orginal Clean" style, in case this issue is somehow related to the theme.

**Comment by TeamSpen210** [comment]
Perhaps you didn't turn off the "auto-drop" checkbox? Piston behaviour was changed slightly in BEE, to allow you to have additional operating modes. Before, with no connections it would automatically move when the player stood on it. Now the player presense requirement is controlled by the aforementioned checkbox, allowing you to additionally have platforms which require both players and an input (like in Portal 1), and platforms that never move.

**Comment by Konclan** [comment]
Closing due to lack of response
