### ISSUE TITLE
Cannot change skybox to anything other than the 2D collection

### ISSUE THREAD

**Issue by Boxie98** [BEEmod/BEE2-items#4163]
### BEE2 Application Version

2.4.41.0 64bit

### BEE2 Package Version

2.4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When I try to choose a different skybox, none of the other skyboxes appear.
![2022-07-20 16_38_04-](https://user-images.githubusercontent.com/109649867/179913810-6757244c-42b4-4d35-acd6-e721b74ded57.png)
 

### Expected behavior

I would expect that it would show all the different gallaries.galleries

### Steps to reproduce

Step 1. Click on the Skybox field to open the selector.
Step 2. There's no other step, they're missing.

### Additional information

I'm using the clean skybox.

**Comment by Luke18033** [comment]
There aren't any other skyboxes, the 3D ones were removed for now because they didn't really work that well.
