### ISSUE TITLE
50s cube/dropper timer linkage causes compilation error

### ISSUE THREAD

**Issue by ZeynAlex** [BEEmod/BEE2-items#4165]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0 + ucp's

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Making cube and a dropper having same timer number causes error

### Expected behavior

I expect to preplace cube in one part of the level and then, after fizzling, it will appear in dropper in the other place.

### Steps to reproduce

Step 1. Create cube without dropper and dropper in 50s style map
Step 2. Put their timers to numbers other than 3 or infinity (example - 4 or 5 or 23)
Step 3. Compile the map
Step 4. Error - here it is!

### Logs and Reports

```shell
//will add later
```

### Additional information

50s style

**Comment by FrozenDragon0** [comment]
@ZeynAlex Any logs/reports regarding this error?

**Comment by Luke18033** [comment]
This is pretty useless without a log
