### ISSUE TITLE
How to create a .bee_pack file?

### ISSUE THREAD

**Issue by Aether2099** [BEEmod/BEE2-items#4167]
I'm currently attempting to port over a previous version of a pack I like, and I'm looking into making my own custom assets to be integrated into the interface but I can't seem to figure out how to **open and create** a .bee_pack file. Any help would be greatly appreciated, those are the two main issues I'm facing.

Thanks a ton!

**Comment by Areng14** [comment]
Its just a renamed .zip compress a folder to a zip and change the extension to be a .bee_pack

**Comment by seagemgames** [comment]
You should generally ask questions like this in the Discord server. The GitHub is only for tracking issues.
