### ISSUE TITLE
Strange Conversion gel behavior

### ISSUE THREAD

**Issue by ZeynAlex** [BEEmod/BEE2-items#4211]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0 + ucp's

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

![2022-08-09 (6)](https://user-images.githubusercontent.com/100288527/184526427-4eff7997-f303-4f7f-b6b7-e8864d68e277.png)
![2022-08-09 (7)](https://user-images.githubusercontent.com/100288527/184526432-dc3de9dc-c0ef-4242-9b11-713b3853c5bc.png)
![2022-08-09](https://user-images.githubusercontent.com/100288527/184526438-19573395-b4a7-4630-b35b-4b5d52f0df1d.png)
![2022-08-09 (1)](https://user-images.githubusercontent.com/100288527/184526441-ea34d56d-b8e2-4c23-bcdb-83c2815c4b10.png)
![2022-08-09 (2)](https://user-images.githubusercontent.com/100288527/184526448-13b7e2ec-8cb1-4fbd-ad2f-cf943872f4f5.png)
![2022-08-09 (3)](https://user-images.githubusercontent.com/100288527/184526453-7bdb434e-06b5-44e0-8786-eb3aebf2865f.png)
![2022-08-09 (4)](https://user-images.githubusercontent.com/100288527/184526459-31884195-6263-47bd-93a1-dbc7f25a4d98.png)
![2022-08-09 (5)](https://user-images.githubusercontent.com/100288527/184526461-1553e2f6-f169-489b-ac11-39de8b153158.png)

### Expected behavior

I expect Conversion gel to flow normally.

### Steps to reproduce

Step 1. Put Conversion gel dropper
Step 2. Put angled panel
Step 3. Run map and put portals like I did

### Logs and Reports

```shell
-
```

### Additional information

I use gel button from ucp

**Comment by FrozenDragon0** [comment]
I've had this occur a few times and It's not something I don't think we can fix without source code access.

**Comment by ZeynAlex** [comment]
Ok, thank you

**Comment by FrozenDragon0** [comment]
The best temporary fix is to move the portals further apart from each other as in this case the game thinks the gel hasn't teleported through the portal which results in this stretch like behaviour.
