### ISSUE TITLE
Colorable Standing Doors

### ISSUE THREAD

**Issue by Chee5eman** [BEEmod/BEE2-items#4215]
### Description of the feature

I think adding custom standing doors could be a cool edition to Portal 2 maps using **Bee2**.

**What do I mean by "Custom standing doors"?**

_well_ what I'm talking about is the texture of the standing door... and how you can change the color of the door "it will use the same color picker as the cube color selector in the (style/item properties menu)" or be able to fully change the texture of the door _"but I know that's a stretch"_

### Why should this be implemented

i think it could be add some extra customization of **bee2** amazing tools... and give maps using **bee2** mod some added life...

### Additional information

Here are some examples of what I mean...

![colorable doors](https://user-images.githubusercontent.com/111412878/185050001-121bae7e-1b6f-4619-b19b-c37bb817324d.png)

**Comment by FrozenDragon0** [comment]
Closing due to the lack of a response.
