### ISSUE TITLE
Suggesting for single panels

### ISSUE THREAD

**Issue by SomeRabbitFan** [BEEmod/BEE2-items#4216]
I have a suggestion about a small pannel like portal 2 maps uses the small panel would be able to extend and rotate and mya e there be a little block for the panel a mix of a normal panel and a piston platform

**Comment by TPEcool** [comment]
Uhh, excuse me @LautaroL20, this IS the BEE2-Items repo

**Comment by LautaroL20** [comment]
@TPEcool - I am sure that what you say I have already answered to another person in the past, unfortunately it would be somewhat complicated to find that answer, so I will not be able to copy paste my answer this time. If you had paid a little more attention to the following, you wouldn't have asked that question:

![Github comment](https://user-images.githubusercontent.com/12244376/188238237-c8b5e73e-843d-4c7d-8b70-29dc60bb0109.png)

**Comment by Luke18033** [comment]
Not explained very well, we probably won't be adding a single panel item because there's no good way to implement it in puzzlemaker and it doesn't translate across styles.
