### ISSUE TITLE
Portal 1 Style: wrong particle used above elevators

### ISSUE THREAD

**Issue by BenVlodgi** [BEEmod/BEE2-items#4221]
### BEE2 Application Version
4.41.1

### BEE2 Package Version
4.41.0

Portal 1 Style. Gun Particle spawns outside the gun. I can see it at the top of the elevator.
This should either be properly attached, or hidden. And/or attach a new particle that is appropriate.

**Comment by TeamSpen210** [comment]
There's an intentional blue particle at the top of the elevator, which is in P1 too - it's like a tractor beam moving the lift. Is that what you're seeing?

**Comment by Luke18033** [comment]
In the current release I think it's using the portalgun projectile particle there since we couldn't pack the real one originally, but now that we can I swapped that out for the proper version.

**Comment by BenVlodgi** [comment]
> There's an intentional blue particle at the top of the elevator, which is in P1 too - it's like a tractor beam moving the lift. Is that what you're seeing?

Ah, I see. I assumed it was a bug since the gun doesn't have a particle. and I could see a particle on the ceiling.
I was surprised to see it in the exit room too much later. Which confused me more.

> In the current release I think it's using the portalgun projectile particle there since we couldn't pack the real one originally, but now that we can I swapped that out for the proper version.

Great!

**Comment by Luke18033** [comment]
Should be fixed in 4.42
