### ISSUE TITLE
Lower vactube speed and airflow particles hide options (+boxed turret item)

### ISSUE THREAD

**Issue by TPEcool** [BEEmod/BEE2-items#4224]
### Description of the feature

I think there should be a stylevar to make vactubes slower. Also, that should probably disable the airflow particles. Actually, i think disabling the airflow particles should be a separate stylevar. For decorative vactubes that just move items around, there should probably be a boxed turret item (either always off, starts on but turns off or configurable inapp or with editor itemvars, e.g. "Start enabled" = initial activity state.

### Why should this be implemented

This would give users the ability to make "cinematic" tube rides (like in Aperture Tag after you pick the paint gun up). Plus, i think the airflow particles aren't really "fitting" for vactubes.

### Additional information

![20220902211514_1](https://user-images.githubusercontent.com/75689188/188214142-68b738a7-e77d-4097-8893-46ee2613a674.jpg)
The dust-like particles, generated by vactubes.

**Comment by FrozenDragon0** [comment]
If your referring to Vactubes moving items around as a decorative item then that's what you should be using hammer for. And Cinematic tube rides are also meant to be for hammer, Puzzlemaker isn't designed around for that sort of stuff.

**Comment by TPEcool** [comment]
Oh, alright then, but there's another issue: sometimes, especially in horizontal vactubes, you can get stuck. I suppose modifying the speed or adding some kind of course correction measure (e.g. collision triggers) would fix this.

**Comment by FrozenDragon0** [comment]
Getting stuck from what I remember is a bit of a tricky problem to fix, doesn't help that the collision for the tube models is already pretty tight, also regarding removing the particle effects this would lead to a problem of players seeing that no particles would mean that the tube is off, when really it's still on, It'd just cause confusion removing the particles.

**Comment by TPEcool** [comment]
oh, alright

**Comment by TPEcool** [comment]
well at least they could make the sounds, perhaps?

**Comment by TPEcool** [comment]
like, the game already has vactube noises

**Comment by TPEcool** [comment]
so maybe they could be used

**Comment by TPEcool** [comment]
although EVEN I often dont play with the headphones on my head, so it will be probably pretty hard to hear

**Comment by Konclan** [comment]
As FrozenDragon0 said, BEEmod really isn't for cinematic stuff and we're not going to add an option for something as trivial as dust particles especially when its used to indicate if its going through portals

**Comment by TPEcool** [comment]
I didnt really mean through portals, i thought that would just make it easier to see them
