### ISSUE TITLE
Turret variation: Defective turret.

### ISSUE THREAD

**Issue by CharlesHere0** [BEEmod/BEE2-items#4238]
### Description of the feature

This turret is defective. Does have any ammo, can be used to press buttons and scare the player sometimes.

### Why should this be implemented

A defective turret could make a great addition as a good enviremental storytelling feature.

**Comment by Areng14** [comment]
You can make that as a ucp (user created package)

**Comment by CharlesHere0** [comment]
> You can make that as a ucp (user created package)

I have no idea how to do that

**Comment by FrozenDragon0** [comment]
This is something you really should be using hammer for, Puzzlemaker isn't designed to make story test chambers.
