### ISSUE TITLE
Funnel emitter missing in overgrown

### ISSUE THREAD

**Issue by weirdofromdiscord** [BEEmod/BEE2-items#4241]
### BEE2 Application Version

4.42.0 64BIT

### BEE2 Package Version

4.42.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When trying to load the funnel in the overgrown style, the model of the funnel emitter will not appear.
![20221018152713_1](https://user-images.githubusercontent.com/82258107/196447531-2cbf8070-45f0-4c84-a539-6b97c277d3cf.jpg)

### Expected behavior

It is expected that the model of the funnel appears.

### Steps to reproduce

Step 1. place a funnel item in overgrown style
Step 2. enter the test chamber to a missing funnel

**Comment by TeamSpen210** [comment]
This seems to work fine for me. What settings did you set it to, was it connected to anything?

**Comment by FrozenDragon0** [comment]
Would seem this is also a problem in Portal 1 according to this: https://github.com/BEEmod/BEE2-items/issues/4256

**Comment by Luke18033** [comment]
The problem is with the FGDs, the keyvalue is set as `string` type, but it needs to be `target_destination` to work in instances properly. HammerAddons fixes that so it would work fine for anyone who has that installed.
