### ISSUE TITLE
Floating Cameras

### ISSUE THREAD

**Issue by TabTray** [BEEmod/BEE2-items#4244]
### BEE2 Application Version

Latest 64bit

### BEE2 Package Version

Latest

### What operating system are you running on?

Windows 11

### Description of the bug

A camera on the floor and a floating one in front of a door are placed automatically in the same spot every time when the map is run. More precisely, approximately 2 panels away from the front of the entrance door and 1 panel away from the front of the exit door.
Also, no cameras are placed in those spots in the editor. Attempting to delete the cameras through the editor by randomly clicking in the same spots and praying didn't work, as they probably didn't exist in the editor in the first place.
![image](https://user-images.githubusercontent.com/81453312/198851577-82d7307a-9ba6-468f-99a0-bfcc4913e060.png)
![image](https://user-images.githubusercontent.com/81453312/198851591-43675a81-d706-4a64-9688-6005f40804a7.png)

### Expected behavior

Cameras... not floating? Also have never seen cameras on the floor so I don't think that's intended either.

### Steps to reproduce

Step 1. Create a map
Step 2. Watch the laws of physics get bypassed

### Additional information

-Clean style
-Random elevator video
-Bendy player model
-Singleplayer map

**Comment by TeamSpen210** [comment]
Turn off the "Door Cameras" style option, I forgot to update this instance.
