### ISSUE TITLE
Portals can be bumped onto P1 small observation room on ceiling

### ISSUE THREAD

**Issue by HyperAnimates** [BEEmod/BEE2-items#4247]
### BEE2 Application Version

4.42.0 64Bit

### BEE2 Package Version

4.42.0

### What operating system are you running on?

Windows 11

### Description of the bug

This is for portal 1, I don't know about all the other styles but placing a obs room on the ceiling results in a skylight and that's fine  but when you portal bump next to it, it places a portal on the skylight acting like a invisible white wall. It only works if you portal bump it.

### Expected behavior

I expected this to not happen and it came as a surprise to me.

### Steps to reproduce

Step .
Step .

**Comment by FrozenDragon0** [comment]
Can you give a screenshot?

**Comment by HyperAnimates** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/117326702/199634197-93a770fc-3920-4329-bd6e-258117c1fc07.png)


Sorry I'm new to git hub

**Comment by FrozenDragon0** [comment]
> ![Screenshot (1)](https://user-images.githubusercontent.com/117326702/199634197-93a770fc-3920-4329-bd6e-258117c1fc07.png)
> 
> Sorry I'm new to github

All good.

**Comment by HyperAnimates** [comment]
cool
