### ISSUE TITLE
Portals and sky lights

### ISSUE THREAD

**Issue by HyperAnimates** [BEEmod/BEE2-items#4248]
### BEE2 Application Version

4.42.0 64Bit

### BEE2 Package Version

4.42.0

### What operating system are you running on?

Windows 11

### Description of the bug

This is for portal 1, I don't know about all the other styles but placing a obs room on the ceiling results in a skylight and that's fine  but when you portal bump next to it, it places a portal on the skylight acting like a invisible white wall. It only works if you portal bump it.

### Expected behavior

I expected this to not happen and it came as a surprise to me.

### Steps to reproduce

Step 1. Place the skylight
Step 2. place a portal right next to the skylight on either side
Step 3. Portal bump a portal to the direction of the skylight
Step 4. Now you have a broken floating portal

### Additional information

None so far, just a floating portal.

**Comment by FrozenDragon0** [comment]
Why did you open 2 issues?
