### ISSUE TITLE
SR Latch works incorretly

### ISSUE THREAD

**Issue by AShu7SPb** [BEEmod/BEE2-items#4251]
### BEE2 Application Version

4,42,0 64bit

### BEE2 Package Version

4.42.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

All SR latches are turned on when A and B is 1.
When I press the “A” or “B” button separately, nothing happens. When I press the “A” and “B” button, the trigger is turned on until one of the input signals is 0
default SR works almost the same. But it does not turn off

### Expected behavior

Set(A input) | Reset(B input) | Q(out)
0                  | 0                      | 0
0                  | 1                      | 0
1                  | 0                      | 1
1                  | 1                      | -

or

Set(A input) | Reset(B input) | ~Q(out)
0                  | 0                      | 1
0                  | 1                      | 1
1                  | 0                      | 0
1                  | 1                      | -

### Steps to reproduce

use SR Latch

### Additional information

i'm use clean style

**Comment by TeamSpen210** [comment]
How exactly did you connect these together? With logic items, the order of connection is important, the first sends a signal to the second. You want your buttons to each connect to an Input A or B, then those connect to the SR latch.
![image](https://user-images.githubusercontent.com/8453732/208329614-9d0181aa-136f-4875-915c-17b69e08761f.png)

**Comment by AShu7SPb** [comment]
Okay, I did not read the instructions very carefully... It works
