### ISSUE TITLE
There is no more bottomless pit

### ISSUE THREAD

**Issue by ApetureScience-Helpsystem** [BEEmod/BEE2-items#4253]
### BEE2 Application Version

BEE2.42.0

### BEE2 Package Version

bottomless pit

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

there is no more bottomless pit 

### Expected behavior

i was searching for the pit but there is nothing

### Steps to reproduce

no more bottomless pit

**Comment by Areng14** [comment]
Bottomless pits were removed

**Comment by ApetureScience-Helpsystem** [comment]
oh thanks

**Comment by FrozenDragon0** [comment]
Bottomless pits are disabled currently.
