### ISSUE TITLE
Add Bottomless pit

### ISSUE THREAD

**Issue by ApetureScience-Helpsystem** [BEEmod/BEE2-items#4254]
### Description of the feature

It can be like the goo (deadly water) placing and there it is

### Why should this be implemented

would be nice and cool (Hammer to HARD)

**Comment by FrozenDragon0** [comment]
1. You did not need to add open 2 issues.
2. Hammer isn't that hard to learn.
3. Bottomless pits are currently disabled.
4. Duplicate of https://github.com/BEEmod/BEE2-items/issues/4253
