### ISSUE TITLE
1970 map not building

### ISSUE THREAD

**Issue by Beathlefun** [BEEmod/BEE2-items#4258]
### BEE2 Application Version

4.42.0

### BEE2 Package Version

 4.42.0

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
[I] <valve>.vbsp(): Could not open instance file instances/lights/underground_light_wall01_warm.vmf
[
```

### Additional information

i am using 1970 map

**Comment by Beathlefun** [comment]
HELP

**Comment by Beathlefun** [comment]
this is the full error:


[I] (MetaCondition "add_voice") voice_line.add_voice(): Using microphones...
[I] (MetaCondition "add_voice") voice_line.add_voice(): 0 Mid quotes
[I] (MetaCondition "add_voice") voice_line.add_voice(): Done!
[I] (MetaCondition "anti_fizz_bump") vbsp.anti_fizz_bump(): Adding Portal Bumpers to fizzlers...
[I] (MetaCondition "anti_fizz_bump") vbsp.anti_fizz_bump(): Done!
[I] (MetaCondition "set_player_portalgun") vbsp.set_player_portalgun(): Setting Portalgun:
[I] (MetaCondition "set_player_portalgun") vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] (MetaCondition "set_player_portalgun") vbsp.set_player_portalgun(): Done!
[I] (MetaCondition "add_screenshot_logic") vbsp.add_screenshot_logic(): Added Screenshot Logic
[I] cond.core.check_all(): ---------------------
[I] cond.core.check_all(): Conditions executed, 198/237 (84%) skipped!
[I] cond.core.check_all(): Map has attributes: ['obsworldportal', 'observationgrate', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=35, misses=232, maxsize=100, currsize=100)
[I] cond.core.check_all(): Style Vars: {'doorcameras': True, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': True, 'nomidvoices': True, 'unlockdefault': True, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True, 'opensphere': False, 'retro_voice_pre_line': False}
[I] cond.core.check_all(): Global instances: set()
[I] music.add(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] tiling.generate_brushes(): Generating tiles...
[I] tiling.generate_brushes(): Generating goop...
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 17 2022)
[I] <valve>.vbsp(): 2 threads
[I] <valve>.vbsp(): Using shader api: shaderapiempty.dll
[I] <valve>.vbsp(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
[I] <valve>.vbsp(): Could not open instance file instances/lights/underground_light_wall01_warm.vmf
[I] <valve>.vbsp(): 
[I] BEE2_config.save(): Saving changes in config "C:\Users\ma2onpc\AppData\Roaming\BEEMOD2\config\compile.cfg"!


[

**Comment by FrozenDragon0** [comment]
Well there's your error: [I] <valve>.vbsp(): Could not open instance file instances/lights/underground_light_wall01_warm.vmf
[

Try changing that to a different light.

**Comment by Beathlefun** [comment]
FrozenDragon0

i cant
