### ISSUE TITLE
Set DesiredFacing on doors

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#4260]
When doors are moved onto floors or ceilings then back to walls, they can end up sideways:
![image](https://user-images.githubusercontent.com/19228201/206841473-a922ada0-4d95-46eb-87b6-f6393454507a.png)
This has no effect in-game, but still looks dumb. `DesiredFacing` should be used so doors on walls always orient upright.

**Comment by Luke18033** [comment]
@TeamSpen210 You got it backwards, they rotate upside down now

**Comment by TeamSpen210** [comment]
Ahh, if "unlock default items" is enabled it also forces the desired facing, setting it correctly there which is why I didn't notice this was wrong.

**Comment by Luke18033** [comment]
Ah. Why not just add it always?
