### ISSUE TITLE
Adhesion Gel

### ISSUE THREAD

**Issue by Akkorokami** [BEEmod/BEE2-items#4261]
### Description of the feature

The adhesion gel is a purple like gel that was originally implemented into the vanilla game but was scrapped. The unique characteristics about the gel is the ability to stick to surfaces that were otherwise unreachable.  This was valve's way of allowing the change of gravity without needing to do so. In addition, covering cubes with said gel could allow them to stick to walls just as the player would. 

### Why should this be implemented

By implementing the adhesion gel into the beemod editor, it could allow for more advanced puzzles to built that need "outside of the box" thinking. For example, using the gel to reach a wall linked pedestal button or flinging a adhesion covered cube so it stick to a button on the ceiling.

**Comment by HeimlichLaboratories** [comment]
no need to be a dick lol, i didn't even know the issue tracker has a faq at first. they should've looked for duplicates tho

**Comment by FrozenDragon0** [comment]
> no need to be a dick lol, I didn't even know the issue tracker has a faq at first. they should've looked for duplicates tho

Not trying to be a dick, it just gets frustrating when people don't bother to read the FAQ or search for duplicates for something obvious.

**Comment by LautaroL20** [comment]
> FrozenDragon0 Said: I'm sure @LautaroL20 isn't trying be a dick, it just gets frustrating when people don't bother to read the FAQ or search for duplicates for something obvious.

Thanks for understanding the reason for my frustration, the Adhesion Gel suggestion was posted so many times that at this point, I thought that everyone were very well aware that this gel is not possible to implement...
