### ISSUE TITLE
BEEmod 2.4.43 Release candidate N°1: If you build a Coop map with a separated checkpoint on it, the player characters will spawn in a totally mysterious dark place.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#4265]
Also, a mysterious red message will appear asking to joining an unknown wesbite as you can see in the screenshot below. All this in a mysterious way...

![20221216005053_1](https://user-images.githubusercontent.com/12244376/208025048-ee1ada06-0fcd-4470-a45a-f80b23d2a71a.jpg)

This happens in all the Old Aperture styles.

**Comment by TeamSpen210** [comment]
That's the error display system, in Coop I can't make it open automatically, so instead it just shows the URL to enter.

**Comment by Luke18033** [comment]
Might be good to strip the players' portalguns, and set `ss_force_primary_fullscreen 1` so it's not splitscreen (it'll reset when loading another map).

**Comment by TeamSpen210** [comment]
There's probably another error here, probably because I forgot `coop_checkpoint_sep_logic.vmf`: 0a522b349eb7f3a4f4cb73c01571ae10aa0ce3f6
