### ISSUE TITLE
Styled workshop UI tiles

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#4274]
The dark UI background tiles used when in a puzzlemaker/workshop map should change based on the selected style. This would have the side effect of also changing them for any workshop map that's played, but a few other things like the employee badge already do that, so I don't think it's a huge problem. It also wouldn't affect anything outside the workshop since those use separate white tiles.

**Comment by Luke18033** [comment]
I don't think we should do this anymore, I've actually been thinking we might want to remove the Aperture logo and employee badge replacements too, since those will also appear outside the editor itself

**Comment by TeamSpen210** [comment]
Agreed.
