### ISSUE TITLE
Portal: still alive light bridges and portal 1 bombs

### ISSUE THREAD

**Issue by GLaDOS2003** [BEEmod/BEE2-items#4276]
### Description of the feature

P2 light bridges don’t look great in portal 1 and should be retextured as seen in still alive and p2 co-op trailer.

Bombs in p1 style should have the p1 edgeless safety cube look but with the glow seen at the ending scene

### Why should this be implemented

This will improve the visual style of the p1 chambers which have them as elements.

**Comment by FrozenDragon0** [comment]
Not possible to change the bridge texture as you can't pack VPK files.

**Comment by HeimlichLaboratories** [comment]
Aren't the "light bridges" in still alive just fields with the combine forcefield texture?

**Comment by GLaDOS2003** [comment]
They are indeed just like the fields but they look different to the combine forcefields.
They are the same as the force deflection fields so maybe change their textures in p1 style?

**Comment by GLaDOS2003** [comment]
I assume they cannot change funnel textures either.

**Comment by FrozenDragon0** [comment]
> I assume they cannot change funnel textures either.

Correct, they are the same deal as Light bridges, along with lasers.

**Comment by TeamSpen210** [comment]
For the bombs, we don't have a bomb item right now, and it'd be quite strange anyway to imply that either edgeless safety cubes or personality cores are also bombs.
