### ISSUE TITLE
Chamberlock isn't working in 80s stile and the "Lobby" enterance isn't working in 70s style

### ISSUE THREAD

**Issue by cringe587** [BEEmod/BEE2-items#4279]
1)Chamberlock isn't working in 80s stile
2)"Lobby" enterance isn't working in 70s stile
![Снимок экрана (501)](https://user-images.githubusercontent.com/122199448/211186147-359454b6-2c0c-465c-8560-d195323feb6e.png)

**Comment by TeamSpen210** [comment]
Hmm, both these are working fine for me.
