### ISSUE TITLE
where to get a hammeraddons.fgd

### ISSUE THREAD

**Issue by bangbangyouall** [BEEmod/BEE2-items#4284]
### BEE2 Application Version

4.43.0 64bit

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

hammeraddons.fgd was not included in beemod

### Expected behavior

i expected it to work

### Steps to reproduce

i did compile again but it still shows it

### Logs and Reports

```shell
Traceback (most recent call last):
  File "trio\_core\_run.py", line 850, in __aexit__
  File "app\UI.py", line 757, in export_editoritems
  File "app\gameMan.py", line 847, in export
  File "app\gameMan.py", line 530, in edit_fgd
  File "pathlib.py", line 1252, in open
  File "pathlib.py", line 1120, in _opener
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dontwanttoshowanythingthisaintmyrealusername\\Downloads\\BEE2_v4.43.0_win64\\hammeraddons.fgd'
```

**Comment by TeamSpen210** [comment]
It's included in the app download, I'm not sure why it wouldn't be there.

**Comment by bangbangyouall** [comment]
yeah it is weird how my copy of bee24 does not have hammeraddons.fgd. i guess i will reinstall.

**Comment by TeamSpen210** [comment]
Is this fixed now @bangbangyouall?
