### ISSUE TITLE
Fizzlers and Discouragement Fields

### ISSUE THREAD

**Issue by Crostal00** [BEEmod/BEE2-items#4286]
If I put the two items in the game map, it will fail to compile.
(I'm a Chinese. I use the translator to report errors. The title refers to the blue and red fileds of the game.)

**Comment by TeamSpen210** [comment]
Could you provide the log files? They should be at `Portal 2/sdk_content/maps/preview.log`.

**Comment by FrozenDragon0** [comment]
Closing due to the lack of a response.
