### ISSUE TITLE
Portalable P1 victory lifts aren't portalable

### ISSUE THREAD

**Issue by sparrowdragon** [BEEmod/BEE2-items#4287]
### BEE2 Application Version

2.4.43.0

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

In Portal 1 style, when I fire a portal at a piston platform, the portal placement always gets denied, regardless of its position. But when use sv_portal_placement_never_fail 1, the portal always fits perfectly. The same problem applies in an older version of the mod (but I don't remember the versions, though they were quite recent). I've tried it with the cube type at Reflective.

### Expected behavior

The lift is supposed to be portalable since it has the Reflective setting active in Cube type.

### Steps to reproduce

1. Open BEE2, wait for it to load.
2. Be sure Export Options dialog is open a on top of other dialogs
3. Open the picker next to "Style" and choose P1. Close the dialog once chosen.
4. Be sure Victory Lift item is on the Items list on the left of the dialog in the main window of the application. Search for "lift" on the Search bar and when you find it, drag it to the list on the left.
5. If there were any modifications you've just made in the program, look for any option that says **Export to "PORTAL 2"...**
6. If you're saving new application parameters from step(s) 3, 4 and/or 5, wait for the progress dialog to disappear by itself. After that, a confirmation dialog will appear, asking you if you want to open Portal 2 and minimize BEE2. Click "Yes" and wait until the game brings you to the Main Menu; If you made no changes, just open Portal 2 and wait for the Main Menu.
7. Once you see the Main Menu, choose the community testing option. Then go to the test chamber creator, pick an existing chamber or create a new one by clicking on your choice. If you're making a "New" one, click "NEW" below. If you want to use an existing project, click "EDIT" instead.
8. Make sure the chamber does not display placement errors or that there are no compiler errors (e.g. "leaked" bug, particlarly on antique styles). Add a Victory Lift item from the in-game item distributor that pops up to the map where a player would be able to access it. Make sure that the editor is not highlighting anything in red after this.
9. Right click on the lift, making sure its contour is highlighted, and place your cursor over the Cube types option. A sub menu will show. Select Reflective.
10. Click the ► button at the top of the screen to compile and play the map. Wait for the level to be loaded. Head over to the "portalable" victory lift. It looks grey on the map.
11. Don't get too close to the lift to activate it. Just shoot at it with your portal gun. If you don't have a portal gun yet, then either find and collect it in the level, or open the Developer Console and type the command "give_portalgun". After typing that, press Enter to send the command, then press ESC to resume the game.
12. If you haven't already, shoot the Portal at the lift. If sv_portal_placement_never_fail is kept at 0 (default parameter), the portal will be **DENIED** even though the lift seems portalable.

### Additional information

Portalable victory lifts work on all other styles.

**Comment by dsagfa** [comment]
This gives me a thought: TROLL MAP. You have just awakened the inner troller inside me, OP.
Imagine desperately trying to escape a pit of turrets by portalling to the only portallable surface, before realising IT DOESN'T WORK. MUAHAHAHHAA

**Comment by sparrowdragon** [comment]
Uh oh stinky!...
