### ISSUE TITLE
Breakable Glass and Bomb Droppers

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#429]

**Comment by Enterpise** [comment]
Good idea!! It would be AMAZING to have the breakable glass as a test element!

**Comment by Enterpise** [comment]
A version that is breakable by Cubes and turret hits

**Comment by ZombiePwner1** [comment]
Yes indeed would be a great idea.

**Comment by ZombiePwner1** [comment]
.

**Comment by TheReviewers** [comment]
Bomb Droppers Were Mentioned By Me Already ;)

**Comment by Konclan** [comment]
This is included in #95
