### ISSUE TITLE
1970's Exit leaks

### ISSUE THREAD

**Issue by pompousspaniard** [BEEmod/BEE2-items#4290]
### BEE2 Application Version

4.43.0 64bit

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

1970s chambers leak near the exit. This happens regardless of whether the exit has any connections (feel like this needs to be specified since the 1970s style has two distinct "doors")

On a default chamber (without moving any item) it leaks at  (512 512 -2397.98) (832 640 -192) according to the interactive window. Seems to be the voxel below the exit, interestingly enough.

Here's a screenshot (note that the entry door is furthest away from the viewpoint, with the exit door nearest to the viewpoint)
![Screenshot (271)](https://user-images.githubusercontent.com/47536167/215324105-c6261d0d-8d33-4e79-990a-5c0523fdb420.png)

### Expected behavior

The exit door should not leak

### Steps to reproduce

- Create a new chamber in the 1970s style
- Export

Alternatively:
- Create a new chamber in the 1970s style
- Connect any item's output to the exit door
- Export

### Logs and Reports

```shell
alapeño unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF J:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 28 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 4131 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 4300 (ms)
[PORTAL2 PUZZLEMAKER]  Saved puzzle: J:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198255778873\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Compilation time (after VRAD): 6497 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (complete): 6501 (ms) ...launching map!
Error: Operator stop_entry, unknown sound operator attribute input_start
---- Host_Changelevel ----
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Commentary: Could not find commentary data file 'maps/puzzlemaker/preview_commentary.txt'. 
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_under_laserfield.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_under_laserfield.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------
```

### Additional information

Not entirely sure what section of the log is useful in this situation

**Comment by Luke18033** [comment]
Can you try and compile this map again, go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here?

**Comment by tim-burget** [comment]
> Can you try and compile this map again, go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here?

I'm having this same issue, so I can do that, but there's no `preview.lin`. Do you want `preview.error.vmf` and `preview.error.lin` instead?

**Comment by vrad-exe** [comment]
Yes

**Comment by tim-burget** [comment]
Here: [styled.zip](https://github.com/BEEmod/BEE2-items/files/14813756/styled.zip)

**Comment by vrad-exe** [comment]
Seems like the issue is with the `instances/BEE2/clean/elevator_sp/exit_door_preview.vmf` instance still being in the floor orientation

![image](https://github.com/BEEmod/BEE2-items/assets/19228201/eed972ec-60e4-4078-b57b-061195499841)
