### ISSUE TITLE
4.43 continues to have the 4.42 floor door issue

### ISSUE THREAD

**Issue by joethegamer100** [BEEmod/BEE2-items#4291]
### BEE2 Application Version

4.43 

### BEE2 Package Version

4.43 (excluding the 4.41 clean style i used to try and fix the problem which didnt work)

### What operating system are you running on?

Windows 11

### Description of the bug

when loading a map the entry and exit doors will both be generated in the wrong direction. mostly up and down, I have attempted to fix this by reverting back to 4.41 clean style. although that presented the problem of no hole appearing, not allowing me the access the chamber.

### Expected behavior

i expect the hallway to be on the ground like a normal entryway

### Steps to reproduce

step 1. load in 4.43
step 2. suffer over doors

### Additional information

clean style (4.43 and 4.41)

**Comment by TeamSpen210** [comment]
Which exact corridors are you using?

**Comment by joethegamer100** [comment]
corridor 1 and cool #1 but ive been changing them around

**Comment by Luke18033** [comment]
Click "reset package cache" in the BEE2 app settings
