### ISSUE TITLE
Chamberlock locks itself completely before going trough it

### ISSUE THREAD

**Issue by psyklon-project** [BEEmod/BEE2-items#4294]
### BEE2 Application Version

4.41.1

### BEE2 Package Version

4.41.1

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

If you place a chamberlock in a way that it's possible to reach its backside, it will never open after you did that.

### Expected behavior

I think it should still open upon activation as long as you not activated AND not walked trough it before. It seems like there's a trigger attached where, but it does not check if the chamberlock was ever activated.

### Steps to reproduce

Step 1: Place a chamberlock so that it's possible to see and reach its backside.
Step 2: Walk to the chamberlock.
Step 3: Try to open it from the front side. You can't!

Here's a simple configuration on the attached screenshots (the trigger area is marked with a portalable surface).
![20230210093250_1](https://user-images.githubusercontent.com/35834994/218043408-06bd730f-4670-4c0e-982d-b211689cb7db.jpg)
![20230210091051_1](https://user-images.githubusercontent.com/35834994/218043411-9e9e7b8c-880f-4fe5-98f5-b731d59f8ed5.jpg)

**Comment by TeamSpen210** [comment]
Nothing would have changed with this. The chamberlock is intended to be one way, if you're able to access the exit side it'll break yeah. Not sure how useful this would be.

**Comment by psyklon-project** [comment]
In my opinion, we could easily find real use cases, like me experimenting with a 4 chamber setup where the player must go trough every chamber 2 times, while the tests are constantly change their shape and evolving trough the "storyline". I also understand if that's not part of the intended behaviour, but then we should state somewhere that it's working like this to avoid bugged chanbers published not counting this (entirely undocumented) behaviour into account. I mean, I was building my third chamber around an idea like this when I realized that this bug(?) is the reason why I can't always complete my chambers even if I did exactly what I supposed to do. Sometimes the doors opened normally, and some other times (as it turned out, when I walked up to another door before going back from it) they not. No problem if it's hard to implement or it's something you don't worry about, but please at least make it 100% clear to avoid further misunderstanding of the concept of this - anyways really awesome - test element.

**Comment by HeimlichLaboratories** [comment]
The whole point of the chamberlock is really to signal the end of a chamber. Just use a door and a fizzler. (though I agree that door antlines suck, you can use an antline magnet)
