### ISSUE TITLE
Impossible to make first install of bee mod

### ISSUE THREAD

**Issue by Maselia464** [BEEmod/BEE2-items#4298]
### BEE2 Application Version

4.43.0

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

I keep having this error when I try to launch bee mod it is not normal because I download everything and unzip it: https://prnt.sc/tAtv9u8Txdpv

### Expected behavior

To launch bee mod 

### Steps to reproduce

1: download all require file:
https://github.com/BEEmod/BEE2.4/releases/tag/2.4.43.0
https://github.com/BEEmod/BEE2-items/releases/tag/v4.43.0
2: create a repertory

3: unzip both file in the repertory I created

4: launch beemod.exe and find portal2.exe

5: find portal 2.exe and validate the pop up

6: error happen here where it suposse to launch bee mod the error appear

### Logs and Reports

```shell
I cannot provide log because valve console can't check this
```

### Additional information

I use this tutorial as reference: https://www.youtube.com/watch?v=Tn5s-UAnQcg

Maybe use youtube copyright to strike it since it's not working

**Comment by LautaroL20** [comment]
It looks like you did not play attention to what the error message is telling you................ You can clearly read that it´s saying you did not make the "packages" folder required to make BEE2.4 work:
![Packages](https://user-images.githubusercontent.com/12244376/222920505-76eefb83-7288-46d8-a4a8-466d6f901611.png)

**Comment by Maselia464** [comment]
Hello,

I already got that from the both file I got from the link.
