### ISSUE TITLE
Grating have incorrect sound effect when jumping on it.

### ISSUE THREAD

**Issue by Enterpise** [BEEmod/BEE2-items#430]
We were testing a coop map maded with the Pre-release 19 in Clean Style, and grating has an incorrect sound effect, wich is from a glass when jumping on it.

**Comment by TeamSpen210** [comment]
Unfortunately this can't be fixed - due to an issue in how Valve's compiler builds maps.

**Comment by LautaroL20** [comment]
Since this issue was solved, lets leave this open until PRL25 comes out.

**Comment by Luke18033** [comment]
Didn't @TeamSpen210 just say it's unfixable?

**Comment by TeamSpen210** [comment]
I figured out how to fix it.

**Comment by LautaroL20** [comment]
Well, aparently Spencer figured out the cause for it, check out the comments here for more info: https://github.com/BEEmod/BEE2-items/issues/1337
