### ISSUE TITLE
(Probably not a bug, just a question) Why is the High Energy Pellet Launcher Green?

### ISSUE THREAD

**Issue by Gmv-2000** [BEEmod/BEE2-items#4301]
### BEE2 Application Version

4.43.0 (64bit)

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

The Energy Pellets and Pellet Launchers are green in color. The icons show them as blue.
![Screenshot 2023-03-17 173803](https://user-images.githubusercontent.com/126981240/226058157-3971bf2e-4c81-4f48-b59c-e1a2732f1df9.png)
![Screenshot 2023-03-17 173431](https://user-images.githubusercontent.com/126981240/226058159-5d85d1e1-1f8b-44aa-884e-1e0454ce66e0.png)

### Expected behavior

I expect the energy pellets to be yellow and the launchers blue.

### Steps to reproduce

Spawn the High Energy Pellet and see if it's green or not.

### Additional information

I believe the Clean and Overgrown ones have this problem. I also have the original BEEmod installed, but I doubt that's the problem.

**Comment by saismee** [comment]
Green pellets are permanent. They will only despawn when the connection is lost.

**Comment by Gmv-2000** [comment]
> Green pellets are permanent. They will only despawn when the connection is lost.

**Comment by Gmv-2000** [comment]
> Green pellets are permanent. They will only despawn when the connection is lost.

That's actually pretty clever. Thank you!

**Comment by TeamSpen210** [comment]
As to why the emitter is green specifically, it's based on the appearance and behaviour of these in the P1 mod Rexaura.

**Comment by LincoCompany00** [comment]
In portal 1 there's a green one too
