### ISSUE TITLE
Custom LightStrip lights

### ISSUE THREAD

**Issue by Komos63** [BEEmod/BEE2-items#4307]
### Description of the feature

The sphere type of the LightStrip item could get a timer which lets you select from up to 27 different custom light colors. For the texture, you could make it invisible similarly to the antline routing light or just use a white one, the white might get overwritten by the colored light. This would give mappers more freedom for which kinds of light they want to use in their map.

### Why should this be implemented

This would get rid of the duplicated standard light and allow for more light colors, such as green, blue, red, purple etc.

### Additional information

You could also use the same colors as the cube coloriser for this. For showing which colors are available in the editor, you could do something similar to the cube coloriser.

**Comment by RobinRattus** [comment]
Just keep the default texture or make it invisible

**Comment by HeimlichLaboratories** [comment]
That would look terrible. Colored light isn't necessary anyway, just get a UCP if you really want it

**Comment by RobinRattus** [comment]
The cube coloriser already generates a texture for when it's edited, maybe something similar to that could be used

**Comment by HeimlichLaboratories** [comment]
They already explained why that's not possible with the FAQ...

**Comment by PedroLucas201441** [comment]
make a Addon for this :D

**Comment by unfunny1** [comment]
There's a ucp with it...

**Comment by Luke18033** [comment]
Have you actually read the FAQ? It is possible, just difficult... Regardless I think this is a duplicate

**Comment by Luke18033** [comment]
See #1414 (Konclan randomly closed it with "UCP" which is weird and I don't really agree with it)
