### ISSUE TITLE
PuzzleMaker can't find "hammeraddons.bsp_transform" (Linux)

### ISSUE THREAD

**Issue by Denisredmans** [BEEmod/BEE2-items#4313]
### BEE2 Application Version

4.43.0 64bit

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Linux

### Logs and Reports

```shell
#Shown on the picture
```

### Additional information

![error](https://user-images.githubusercontent.com/88984260/233469017-fd84045c-babd-4a50-b557-94c04368eca5.png)

**Comment by TeamSpen210** [comment]
When building the app, did you clone the `hammeraddons` submodule?

**Comment by Denisredmans** [comment]
Yes, when building app I copied the folder from HammerAddons/src into hammeraddons, in BEE2 folder.

**Comment by TeamSpen210** [comment]
I need to merge the instructions into master, you want to do `git submodule update --init` instead. It's expecting the full repo to be there, and is also pinned to a specific version.

**Comment by Denisredmans** [comment]
@TeamSpen210 Thanks for help! I do what you said, it fixed this error from appearing. But still PuzzleMaker can't compile map, it gives another error.
[https://github.com/BEEmod/BEE2-items/issues/4314](url)
