### ISSUE TITLE
Allow Track Platform Speed Control

### ISSUE THREAD

**Issue by Aneonen** [BEEmod/BEE2-items#4315]
### Description of the feature

An option to allow the manipulation of a track platform's speed.

### Why should this be implemented

Though it is not incredibly significant, there are often situations in which designing a layout around a track platform can be made easier by changing the speed of the platform. I have vaguely picked up that allowing a moving platform like this to move too quickly can have unfortunate consequences, but one moving slowly seems fine.
It would also be unfortunate that a player would not be able to expect the speed of a track platform before seeing it move, but I don't think that this blindness is too harmful. 

### Additional information

I have personally altered my track platform to use a timer value to set a speed. It seems a bit unfortunate that the $speed fixup is available and goes unused. 
I found that speeds of powers of two allow for very nice manipulation of a track platform's position with respect to delayers as well. 

I apologize if this suggestion is redundant with the very old #1100 , but it seems to have gone untouched for a long time and I wanted to highlight the (presumably) readily available fixup. (This is also why I did not generalize to other items like the piston platform.)

**Comment by AxoLabs** [comment]
I think this would be a nice feature to have. Often while playing maps involving track platforms I found them to be somewhat difficult/annoying to get on due to their speed.
