### ISSUE TITLE
Only item editor window is showing

### ISSUE THREAD

**Issue by doodleshep14** [BEEmod/BEE2-items#4317]
### BEE2 Application Version

Version 4.43.0

### BEE2 Package Version

Version 4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When I open the BEE2 app, the Palette Selector, Pallette Style & Music Editor, and the Compile Setting windows vanish. The item  select sound also plays for a brief second.

### Expected behavior

I expect the BEE2 app to run as normal.

### Steps to reproduce

Now, I did try to add it as a Non-Steam game, and it worked normally. However when I closed BEE2 via the STOP button on the Steam PLAY/STOP thing (I don't know the name), I got an error. I tried to paste the error via the automatic clipboard feature, but it  didn't work. I closed the error windows and unknowingly started this bug.

### Additional information

I have a lot of saved palletes. 

Additionally, the loading screen of the mod (when you boot the BEE2.exe file up) just hangs at unknown.
Here's what I mean.
![image](https://user-images.githubusercontent.com/119131991/234373768-afd8c031-ecd3-486e-99c8-005456db851c.png)

**Comment by TeamSpen210** [comment]
The windows can be shown again from the `View` menu, have you tried that? Clicking the Stop button in Steam is just going to try terminating the application, which probably isn't going to correctly exit.
