### ISSUE TITLE
Standing/reclined fizzlers connected to lifeform sensor don't auto remove antlines

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2-items#4324]
### BEE2 Application Version

Dev branch

### BEE2 Package Version

Dev branch

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Standing and reclined fizzlers remove their output antlines when hooked up to any fizzler, except for the lifeform sensor. Presumably, this would apply to any fizzlers with outputs ([flux fields aren't currently compatible](https://github.com/BEEmod/BEE2-items/issues/3524)).

![image](https://user-images.githubusercontent.com/19228201/236592852-020ff457-ef42-4d6c-ac1f-dd22670d99e6.png)

### Expected behavior

The antlines should be removed

### Steps to reproduce

1. Place standing fizzler and connect it to a lifeform sensor
2. Compile the map
3. There is an antline pointing to where the lifeform sensor was

**Comment by TeamSpen210** [comment]
Actually looking back at this, it's intentional. If the fizzler has outputs, instead of using the output relay item you can just use the output from the standing/reclined fizzler. Unfortunately we can't tell the different antlines apart, so it has to preserve all existing ones.
