### ISSUE TITLE
Objects being able to get covered in reflection gel

### ISSUE THREAD

**Issue by jb0lt** [BEEmod/BEE2-items#4330]
### Description of the feature

Cube should be able to get covered in reflection gel, causing lasers to get bounced off, just like reflection gel on a wall

### Why should this be implemented

I was thinking, "What if you covered a cube in reflection gel and put in a rexaura cube holder thing, or placed it on the ground and bounced the laser into a catcher, removing the need for a reflection cube"

### Additional information

Current existence:
![20230518191308_1](https://github.com/BEEmod/BEE2-items/assets/110001767/31d29c74-a029-4fa2-9eb4-5fc8fb2e8aee)
![20230518191304_1](https://github.com/BEEmod/BEE2-items/assets/110001767/86d8957b-7229-4698-94c4-10ba6ba5fc33)

**Comment by FrozenDragon0** [comment]
This is not possible to implement without source code access.
