### ISSUE TITLE
Multiple item Variants for the glass hole item.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#4331]
### Description of the feature

So as of right now the Glass hole item only has the small and big hole variants, these new variants discussed in the Discord are as follows.
A cube slot which is a hole big enough to fit cubes through but still small enough to prevent players from going through, a invisible clip can be added in place of this if need be to ensure you can't crouch through the hole.

A light bridge hole variant which is a small rectangular hole that's just big enough to fit light bridges through but nothing else, this would be the low variant which is low to the ground for light bridges that are placed low to the ground.
The second variant is a middle hole which would be useful for light bridges that are placed in the center.

All these variants could be used by the cube type system as there is 5 variants to use which is perfect for cube type, the light bridge hole variants could also use the 4-way rotation handle to change the position of where the hole for the bridge in the event that the chamber uses a light bridge in such a way.

### Why should this be implemented

Implementing this would improve the usefulness of the glass hole item by giving it more of a use for some other elements rather than just being a circle hole in glass.

In the event of the glass hole variants, some people may want to design chambers in a way to have a light bridge pass through under glass but don't want to use a full size grating which could potentially be abused to fire portal shots through whereas a small little hole for light bridges would ensure that portals would almost never beable to be shot through it.

**Comment by asd417** [comment]
Cube hole seems reasonable as it was seen in the coop campaign. Also if the holes can be grated, it would help a lot.

**Comment by TeamSpen210** [comment]
Unfortunately I don't think a cube hole would actually work properly. I just did some measuring, a hole that would fit cubes has to be 40 units wide, and a player actually can fit through such a hole. Of course I could block that with a clip, but it'd still be rather unexpected/odd looking. This particular barrier can mostly be accomplished via laserfield, so it's not as necessary. A light bridge hole on the other hand is quite reasonable.

**Comment by jb0lt** [comment]
What would a light bridge hole be useful for, last I checked, light bridges can go through both glass and grating

**Comment by TeamSpen210** [comment]
Light bridges can't go through glass.

**Comment by jb0lt** [comment]
Why valve why

**Comment by Luke18033** [comment]
Because it's a game mechanic? They could have made light bridges go through glass, but given that there are maps in the campaign with both of those things, they probably deliberately chose not to.

In-universe, you could probably explain it as the "hard light" no longer being capable of passing through more dense matter that light otherwise could get through.

**Comment by Luke18033** [comment]
Also I think a square cube sized hole could still be useful, just that players would also be able to fit through unless you raised it up off the ground or the like.
