### ISSUE TITLE
Make Laser Cubes redirect pellets

### ISSUE THREAD

**Issue by jb0lt** [BEEmod/BEE2-items#4332]
### Description of the feature

A Stylevar or something should be added to allow reflection cubes to redirect HEPs

### Why should this be implemented

Adding this functionality would make it so that puzzle makers can help the player easily aim pellets, cubes could also be placed in Rexaura cube deflectors to allow for exact 45 degree aiming

**Comment by TeamSpen210** [comment]
I'm not sure what this means. Do you mean that the cube when hit would make the pellet come out the front? This would be pretty complicated, requiring a rework of how all the pellet items work.

**Comment by jb0lt** [comment]
Yes

**Comment by TeamSpen210** [comment]
The tricky part is correctly overriding the velocity to move forwards.

**Comment by jb0lt** [comment]
Do you think this will become a feature at some point or not

**Comment by HeimlichLaboratories** [comment]
I think this would just be gimmicky and annoying since energy pellets kill you in one hit.

**Comment by jb0lt** [comment]
@HeimlichLaboratories to me this would be less annoying then aligning a normal cube, dying repeatedly and it still not going in the catcher, pellets kill you in one hit whether this is a feature or not

**Comment by HeimlichLaboratories** [comment]
> @HeimlichLaboratories to me this would be less annoying then aligning a normal cube, dying repeatedly and it still not going in the catcher, pellets kill you in one hit whether this is a feature or not

Then use the Rexaura cube holder... redirecting pellets with cubes without using helpers shouldn't be used at all, it's a shit mechanic.

**Comment by jb0lt** [comment]
Will keep in mind

**Comment by TeamSpen210** [comment]
I don't really think this would be that good, freeform redirection from cubes is liable to just cause the pellet to go haywire.
