### ISSUE TITLE
Dropper linked to multiple cubes

### ISSUE THREAD

**Issue by jb0lt** [BEEmod/BEE2-items#4335]
### Description of the feature

Dropper should be able to have multiple cubes linked, and when activated, droppers drop all the cubes at once (the cubes are stacked on top of each other).

### Why should this be implemented

I think it would allow for have a single button to respawn multiple cubes, which could allow for more complex respawning-puzzles and save on space.

### Additional information

A screenshot using cheats:
![20230529151146_1](https://github.com/BEEmod/BEE2-items/assets/110001767/a1e57aeb-a58c-428d-8622-af219d7df090)

**Comment by TeamSpen210** [comment]
I'm not so sure this would be a good idea. Firstly there's only so much space inside the dropper shaft, and doing this seems quite likely to me to cause the dropper to jam especially with different types shoved in. But more importantly it might not be the best to encourage having lots of cubes spawning from the same location. The really good puzzles tend to have very few cubes, perhaps three at most. You'd most likely want them to spawn at different locations, so getting to them is part of the puzzle. 

For replacing cubes found elsewhere in the chamber, my old addons (#95) had an item I should ressurrect at some point - the Global Cube Dropper. It would just replace any dropperless cubes that were destroyed.

**Comment by jb0lt** [comment]
Firstly dropper shaft not fitting cubes, the amount could be limited to like 5, also getting dropperless cubes (that aren't in danger of being destroyed) could be a part of a puzzle. I was also thinking that reflection cubes would be the best type for this.

**Comment by Luke18033** [comment]
The global dropper allows you to switch which one is currently active, so multi chamber maps can just use triggers to switch it depending on what room you're in.

The other problem with multi cube droppers is it's not exactly clear how they behave at a glance, you have to activate it to see exactly how many cubes it drops. Having the stacked cubes visible inside the dropper does partially solve that problem, but it's such a small space you'd still have to go closely examine it to see how many cubes it would drop and what types. And of course you also have styles like Old Aperture where droppers don't have windows, so you'd have to add number decals to the dropper model or something and it just becomes very messy.

**Comment by jb0lt** [comment]
Sorry for late response, but I meant if 2 cubes from a dropper into a reclined fizzler or something and the player is in another chamber of the map with a multi-cube dropper then it solves a problem with the global dropper, although the indication of multiple cubes is a problem
