### ISSUE TITLE
Leak with large observe room

### ISSUE THREAD

**Issue by Steveth3cat** [BEEmod/BEE2-items#4341]
### BEE2 Application Version

4.43.0 64bit

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 11

### Logs and Reports

```shell
This map has "leaked". This is a bug in an item or style, which should be fixed. The displayed line indicates the location of the leak, you may be able to resolve it by removing/modifying items in that area. Please submit a bug report to the author of the item so this can be resolved. Leak coordinates:
(-514 512 -1328)
(-24 0 -56)
```

**Comment by Luke18033** [comment]
If you're using any items from user created packages, try removing them from the map to see if they're the cause of the leak. If the issue persists or you were only using default items, try rebuilding the map again and then go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.

**Comment by Konclan** [comment]
Closing due to lack of response
