### ISSUE TITLE
teamspen addon

### ISSUE THREAD

**Issue by hoja28** [BEEmod/BEE2-items#4345]
Hello how do i add the items from team spen addons to bee mod so i can use the items.

**Comment by MarcusKubis9** [comment]
Teamspens add-ons are not compatible with the latest version or any bee2.4 version

They are currently in the process of attempting to reimplement everything from teamspens add-ons into beemod

**Comment by hoja28** [comment]
sO WHAT VERSION IS COMPATIBLE

**Comment by LautaroL20** [comment]
> sO WHAT VERSION IS COMPATIBLE

BEE2.4 v4.43.0, links: 

https://github.com/BEEmod/BEE2.4/releases/tag/2.4.43.0
https://github.com/BEEmod/BEE2-items/releases/tag/v4.43.0
