### ISSUE TITLE
Disable energy pellet collision itemvar

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2-items#4346]
Add an itemvar to disable player collision with energy pellets. TeamSpen found you can use VScript to set the player as the pellet's "owner", which turns off collisions between them, allowing non-deadly pellets to be possible. 

The only problem is that only one player can be the owner at a time, so in co-op we'd need to dynamically switch it to whoever is closer and one player could still die if both touched the pellet at once. That shouldn't be a huge issue though because the players usually won't be standing that close together, and death isn't as big of a deal in co-op anyway.

**Comment by jb0lt** [comment]
I don't know anything about the source engine, but I do know general programming, could you set the pellets to own both players, instead of the other way around

**Comment by Luke18033** [comment]
Assuming that works at all, it would have the opposite problem, where if multiple pellets hit the same player one would still kill them.

**Comment by jb0lt** [comment]
I see
