### ISSUE TITLE
Overgrown green pellet launcher/catcher still have phong shading

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2-items#4348]
The Overgrown infinite launcher/timed catcher models have phong shading enabled still (along with possibly other shader effects), which are not present on the base P2 versions.
![portal2_hi90gYEpSZ](https://github.com/BEEmod/BEE2-items/assets/19228201/a5627512-9dbe-4428-98b4-0b77a26e4e72)

**Comment by dsagfa** [comment]
whats a phong shading

**Comment by Luke18033** [comment]
It's the shiny effect you can see on the upper models in my screenshot, that shouldn't really be there for the dirty overgrown versions

**Comment by TeamSpen210** [comment]
It should probably still have `$selfillum` though.

**Comment by Luke18033** [comment]
Valve's dirty catchers don't, I just copied those. I think that's consistent with the other overgrown elements too
