### ISSUE TITLE
P1 laser catchers missing instance

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#4350]
P1 offset laser catchers cause a compile error on the dev branch because of the missing instance `instances/bee2/clean/items/laser/catcher_targpos.vmf`. (Since this is a Clean instance, the error might not be specific to P1)

**Comment by TeamSpen210** [comment]
Looks like this is [in the repo](https://github.com/BEEmod/BEE2-items/blob/dev/packages/valve/dis_beams/resources/instances/clean/items/laser/catcher_targpos.vmf)?

**Comment by Luke18033** [comment]
Oh I think I just forgot to export with preserve game directories off
