### ISSUE TITLE
Remove laser effect from P1 pellet launchers

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2-items#4353]
P1 pellet launchers currently produce a P2 laser effect inside, which is carried over from Clean. This should not be present,
![image](https://github.com/BEEmod/BEE2-items/assets/19228201/3a301633-d815-43a1-94f0-f2f8a17437c3)

**Comment by Luke18033** [comment]
I just decided to remove this from all the pellet launchers, it looks kind of weird. Maybe we should make a custom particle effect for this instead?
