### ISSUE TITLE
P1 ticktock sound has infinite range

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2-items#4354]
The P1 timer ticktock sound appears to have infinite range, being audible from the opposite side of a maximum size map.

**Comment by TeamSpen210** [comment]
This is somewhat intentional, since it's important for gameplay and all, you want players to hear it.

**Comment by Luke18033** [comment]
Maybe it should be quieter than, or at least fade somewhat with distance and be affected by stereo. How does the P2 one behave, is it also global?
