### ISSUE TITLE
[Suggestion] Add better Lighting on the catwalk exit from some Old Apertures

### ISSUE THREAD

**Issue by Enterpise** [BEEmod/BEE2-items#436]
This is how actually the exit catwalks looks in some Old Apertures from the single-player mode:

![20160313103449_1](https://cloud.githubusercontent.com/assets/15699236/14091937/96622fdc-f519-11e5-80c7-2cff6ca4e16e.jpg)

![20160313093729_1](https://cloud.githubusercontent.com/assets/15699236/14091957/b732ea8a-f519-11e5-8158-0e96e7ada3c4.jpg)

And this is the Light i suggest to add:

![20160313092706_1](https://cloud.githubusercontent.com/assets/15699236/14091969/d57b9230-f519-11e5-8f5a-db7f9041e937.jpg)

**Comment by Konclan** [comment]
It doesn't seem as bad but I think the lighting of the old aperture could use a tiny improvement in the back
![20190828222726_1](https://user-images.githubusercontent.com/16567080/63907971-0c24ac80-c9e3-11e9-8fbd-1c1596b5684c.jpg)

**Comment by Konclan** [comment]
Merging with #530
