### ISSUE TITLE
SP exit corridors missing

### ISSUE THREAD

**Issue by Theheffaboy** [BEEmod/BEE2-items#4360]
### BEE2 Application Version

4.43.0 64bit

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Whenever i try to run the map from hammer editor it says Could not open instance file istances/bee2_corridor/sp/exit/corr_1.vmf and i checked my p2 directory and the folder wasnt even there,How did this happen?

### Expected behavior

To compile and run the map

### Steps to reproduce

1:Export map to hammer editor
2:Hit F9 and compile/run the map

### Logs and Reports

```shell
[I] <valve>.vbps(): Could not open instance file instances/bee2_corridor/sp/exit/corr_1.vmf
```

**Comment by TeamSpen210** [comment]
Sounds like you're trying to compile the wrong map file. You cannot use `puzzlemaker_export`, it doesn't run BEE's compiler to edit the map. Instead you need to edit `maps/styled/preview.vmf`.
