### ISSUE TITLE
BTS style added back (READ THE MESSAGE FIRST)

### ISSUE THREAD

**Issue by unfunny1** [BEEmod/BEE2-items#4362]
### Description of the feature

Basically if u click on it you will be redirected to portal 2 authoring tools steam page

### Why should this be implemented

cuz why not? or atleast make this a april fools joke.

**Comment by FrozenDragon0** [comment]
BTS is not being added back and that's final.

**Comment by unfunny1** [comment]
you forgot to read the message i said that if u click on it you will be redirected to portal 2 authoring tools page

**Comment by HeimlichLaboratories** [comment]
That's stupid and unnecessary. No, it wasn't a haha funny joke.
