### ISSUE TITLE
Powerup panels

### ISSUE THREAD

**Issue by lolqeeeeee** [BEEmod/BEE2-items#4364]
### Description of the feature

My idea is to add recoverable panels (sorry for bad English)

### Why should this be implemented

The problem with the map editor is that there is no sense of any activity or signs of life on the map, so to speak. The panels would give it a different feel.

### Additional information

I want to apologize for basically suggesting this, but... I hope that you will notice this and give at least a minimal answer :3

**Comment by dsagfa** [comment]
This is an AWESOME idea! I love the overgrown style and reconstructing, so this would warm my testing-obsessed heart, but they said they weren't adding any more items, so if you've got an idea for an item, sorry bub..
![cello hhat](https://github.com/BEEmod/BEE2-items/assets/85970384/e302c6be-b83b-4298-be46-32a416fee526)

**Comment by Luke18033** [comment]
This would be a part of the auto decorations system BEEmod/BEE2.4#414
