### ISSUE TITLE
All custom elements are missing textures in the pallete, and are displayed as error in the chamber

### ISSUE THREAD

**Issue by AppleiLev5s** [BEEmod/BEE2-items#4367]
### BEE2 Application Version

4.43.0 64bit

### BEE2 Package Version

i forgot, but its the latest for 4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Everything worked fine before, then I decided to export to aperture tag, then to portal 2 again, and it bugged out. I tried reinstalling and deleting the bee folder in the game directory. There is no aperture tag elements.
![20230922093208_1](https://github.com/BEEmod/BEE2-items/assets/89356845/de82f270-dd07-43bf-92d8-c2d16135a378)

### Expected behavior

It was supposed to just work, but it doesn't as stated above.

### Steps to reproduce

Step 1. Export to aperture tag
Step 2. Export to Portal 2
Step 3. Watch the glory of missing textures and models

**Comment by TeamSpen210** [comment]
Go to BEE options, press "Reset Package Caches", then export again.
