### ISSUE TITLE
Panels 'combination'?

### ISSUE THREAD

**Issue by dsagfa** [BEEmod/BEE2-items#4371]
### Description of the feature

It would do the same thing as the paints and vanilla fizzlers by compiling them into one item.

### Why should this be implemented

It would save lots of space and make room for more items to be put in the item bar.

### Additional information

:)

**Comment by TeamSpen210** [comment]
We can't arbitrarily combine different items, only under specific circumstances is it possible. Panel items already use panel-type as their subtype, so we can't add another.
