### ISSUE TITLE
sneak 100

### ISSUE THREAD

**Issue by dsagfa** [BEEmod/BEE2-items#4373]
### Description of the feature

Sneaking near turrets makes them 'less aware' of you. It doesn't mean they can't detect you, though.

### Why should this be implemented

It would make for an interesting chamber idea, where you have to stay super sneaky and try not to set off any turrets.

**Comment by Areng14** [comment]
I think this would be better as a UCP

**Comment by Critfish** [comment]
Portal isn't a stealth game though, this doesn't really do a whole lot for puzzles.

Not to mention, how would you even implement this?

**Comment by FrozenDragon0** [comment]
This would really serve no purpose, Portal isn't designed to be based around stealth in the first place.

**Comment by dsagfa** [comment]
Yeah I kinda saw this getting scrungobungloed even before I posted it, still would be a fun idea tho
