### ISSUE TITLE
[Leak] Lautaro's Adjustable Pedestal Button creates relay outside of chamber

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#4379]
### BEE2 Application Version

4.43.0

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

The adjustable pedestal button item is creating a logic_relay outside the map, causing a leak. Unsure if this is a problem with the item itself or the compiler, but supposedly this does not happen in clean style.

![image](https://github.com/BEEmod/BEE2-items/assets/16567080/bb1124b0-90d1-4c23-aef2-c837b1fc76df)

![image](https://github.com/BEEmod/BEE2-items/assets/16567080/64a48a13-2d34-4897-8418-eb1dcf310f06)

### Expected behavior

Don't leak

### Steps to reproduce

Place an APB on the north wall in Portal 1 style and compile

**Comment by LautaroL20** [comment]
> Konclan said: "Unsure if this is a problem with the item itself or the compiler."

I can confirm that this is not a problem with my item, is caused by the compiler if P1 Style is used. It is a mysterious bug...

**Comment by TeamSpen210** [comment]
I adjusted the item to only need one instance, rotating instead of having a reversed instance. But didn't correct the relay location to match.
