### ISSUE TITLE
[Suggestion] New Item: Pedesal Button Variant: Placeable in 3 up corners (Very Useful to use into DeadlyGoo Hazards)

### ISSUE THREAD

**Issue by Enterpise** [BEEmod/BEE2-items#438]
A new pedestal button that is placeable in Left- UP Corner, Centered- UP Corner and Right- UP Corner. It could be an AMAZING helpful for this:
![pedestal button](https://cloud.githubusercontent.com/assets/15699236/14092760/8f661b20-f51f-11e5-947b-01bce74b3786.jpg)

**Comment by Enterpise** [comment]
Edited. Fix description post.

**Comment by LautaroL20** [comment]
I really wish this item to be maded, it is extremely useful for Co-op, or SP Lightbridges puzzles into deadly hazards.

I would suggest to make it in a way that does not interfere with others items so you can place it into glass or something else. And center this item in the three up corners by Button Type menu.

**Comment by TeamSpen210** [comment]
What I think I'd like to do is make it placable as a piston platform, so you can set the distance from the ground.

**Comment by Luke18033** [comment]
This has been implemented to `dev`.
