### ISSUE TITLE
No packages found!

### ISSUE THREAD

**Issue by A2W31** [BEEmod/BEE2-items#4385]
### BEE2 Application Version

 Version 4.43.0

### BEE2 Package Version

 Version 4.43.0

### What operating system are you running on?

Windows 11

### Description of the bug

It won't let me start it because it thinks my packages are there but I extracted them to the same folder I extracted beemod too.

### Expected behavior

I expected the thing to start because that's what it;s meant to do.

### Steps to reproduce

Just install the game and extract the folders to the same folder

**Comment by TeamSpen210** [comment]
Where exactly did you put the packages, where is BEE?

**Comment by vrad-exe** [comment]
Closing, not enough information
