### ISSUE TITLE
Having issues exporting

### ISSUE THREAD

**Issue by Frostice2013** [BEEmod/BEE2-items#4386]
### BEE2 Application Version

4.43.0 64bit

### BEE2 Package Version

4.43.0

### Description of the bug

Cannot export a palette to Portal 2.

### Expected behavior

Being able to export a palette to Portal 2, however an error is given. 

### Steps to reproduce

No known way to reproduce the bug, however I do remember clicking the "Uninstall from Selected Game" button.

### Logs and Reports

```shell
Traceback (most recent call last):
  File "app\UI.py", line 1526, in <lambda>
  File "app\UI.py", line 782, in export_editoritems
  File "app\gameMan.py", line 894, in export
  File "app\gameMan.py", line 578, in refresh_cache
OSError: [Errno 22] Invalid argument: 'd:\\steamlibrary\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\p1\\items\\lautaro\\half_grate.vmf'
```

### Additional information

I am using the Clean style, with the GLaDOS (Clean) voice, and other default properties. I am currently using the readonly Portal 2 Collapsed palette.

**Comment by LautaroL20** [comment]
Well, this bug could be happening in more styles, but everything seems to be indicating that it only affects the P1 style.

**Comment by vrad-exe** [comment]
Does this still happen?

**Comment by LautaroL20** [comment]
> vrad-exe said: "Does this still happen?"

No idea, unfortunately I cannot test anything because of the situación which I already explained in the other issue.

**Comment by vrad-exe** [comment]
The question was moreso directed at the issue author

**Comment by LautaroL20** [comment]
I thought this issue was made by me because for the time of the artifact builds I opened many of these. I think that I will need a pair of glassess...

**Comment by vrad-exe** [comment]
Closing due to no response
