### ISSUE TITLE
BEE1 door incorrectly nodraws below itself

### ISSUE THREAD

**Issue by marvin1099** [BEEmod/BEE2-items#4392]
### BEE2 Application Version

2.4.43.0.dev+a2e7311d 64-bit

### BEE2 Package Version

BEE2_v4.43.0

### Description of the bug

Placing the door item is showing a strange void texture when playing the game (might be a Linux only thing)

### Expected behavior

I don't expect any void textures

### Steps to reproduce

1. Place a door in the puzzle maker
2. Play the level
3. The door has a void texture to the right of it
![Screenshot_20231206_220605](https://github.com/BEEmod/BEE2-items/assets/40715852/6b9942d6-d8c1-4745-8348-e4f39809b2cc)

### Logs and Reports

```shell
I don't think this would be very helpful but i will add it if someone asks
```

### Additional information

Im on Arch Linux (Garuda Linux), so i had to compile bee but i think this problem is related to the item itself.

**Comment by TeamSpen210** [comment]
Very weird, this should be applying to underneath the door (since those tiles aren't visible).

**Comment by marvin1099** [comment]
So did a bit more testing and yes the void texture is always on the right, from the front side of corse.
Here are 2 more screenshots.
![Screenshot_20231207_190512](https://github.com/BEEmod/BEE2-items/assets/40715852/e0d0b404-753e-4c5c-9313-a5e224abc41e)
![Screenshot_20231207_190431](https://github.com/BEEmod/BEE2-items/assets/40715852/5204782d-8b1d-4f00-a88a-3e2641b46d52)
