### ISSUE TITLE
Clean doesn't restart when reaching the elevator

### ISSUE THREAD

**Issue by marvin1099** [BEEmod/BEE2-items#4393]
### BEE2 Application Version

2.4.43.0.dev+a2e7311d 64-bit

### BEE2 Package Version

BEE2_v4.43.0

### What operating system are you running on?

Linux

### Description of the bug

No matter if i have "Restart When Reaching Exit" enabled or not, inside the puzzle maker it lets me go to the elevator, goes up and than stops at the top.
So now the elevator is stuck at the top no reloading of the test chamber or publish dialog I'm just stuck there.

### Expected behavior

I Expect it to restart, open a publish dialog, get me back to the editor or do something else of that nature.
I don't expect to get stuck there.

### Steps to reproduce

1. Play Puzzle maker (possibly on Linux).
2. Exit the chamber and go into the elevator 

### Logs and Reports

```shell
If needed I will paste some.
```

### Additional information

Im using Arch Linux (Graruda Linux), not sure if its relevant,
but I think the windows version might work fine (I haven't tested this),
therefore it can't hurt to include this.

**Comment by marvin1099** [comment]
I was using the clean style, i have tested the overgrown style and there it restarts the level on map finish (Seams as it also make no difference if i select "Restart When Reaching Exit"). 
So yes it seems to be a problem of the item, but also might be something else in addition since "Restart When Reaching Exit" changes nothing.
Since this seems to be part of the item i guess i leave the issue open for now.

**Comment by marvin1099** [comment]
Update: Now "Restart When Reaching Exit" works just fine not sure what happened but now it works (at least on aperture 70's and clean. These I tested, the rest probably works to)

**Comment by vrad-exe** [comment]
The intended behavior is if you have that option enabled it should restart when entering the exit corridor, otherwise it should restart when entering the elevator. In Clean though it currently doesn't restart when you reach the elevator and instead gets stuck in a weird buggy elevator loop. That needs to be implemented.
