### ISSUE TITLE
Catwalk

### ISSUE THREAD

**Issue by Superrd02** [BEEmod/BEE2-items#4395]
### BEE2 Application Version

4.43.0

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 11

### Description of the bug

Catwalk does NOT form an enclosed platform when placed on a wall, it doesn't appear.

(https://github.com/BEEmod/BEE2-items/assets/153864698/8a45c2be-93f2-4f7c-bdf2-0d1b0ac8ff53)

### Expected behavior

There is suppose to be a catwalk on the walls.

(https://github.com/BEEmod/BEE2-items/assets/153864698/b38c388e-e7e1-4cfe-95ed-8d06f99c4215)

### Steps to reproduce

I don't know.

**Comment by TeamSpen210** [comment]
This was mentioned in #4336, but anyway it'll be fixed in the next release.
