### ISSUE TITLE
Crusher should be changed to hydraulics in the portal 1 style

### ISSUE THREAD

**Issue by RcsEnigma** [BEEmod/BEE2-items#4398]
### Description of the feature

You know the cylindrical hydraulics from the BTS parts of chamber 19? I think using those instead of the current pyramid-shaped spikes on a plate would work better for the style.

### Why should this be implemented

This would be better for the P1 style because the mashy spike plates don't exist in P1, and the hydraulics _do_ kill you in P1 (via crushing).
The only issue is the hydraulics would instantly kill, rather than push because it's a spike plate in disguise. But if the hydraulics move at the same speed and rates as the normal crusher, it'll probably get the point across.

### Additional information

I say four hydraulics because the spike plate occupies four units, but the P1 hydraulics only takes up one unit.
Each option (current and proposed) has its tradeoffs, but maybe the "style/item properties" could let the user pick which kind they want to have for the chamber.

**Comment by Critfish** [comment]
The hydraulics are clearly BTS themed, though. The current P1 crushers are modeled after the ones from the Portal 1 trailer, with the fire pit.

**Comment by TeamSpen210** [comment]
We do actually have piston-crushers, in the 1980s style.

**Comment by vrad-exe** [comment]
The current design based on the trailer/Still Alive crushers makes more sense
