### ISSUE TITLE
1970's Style Map Leak

### ISSUE THREAD

**Issue by pog2867** [BEEmod/BEE2-items#4409]
### BEE2 Application Version

BEE2.exe

### BEE2 Package Version

Portal Packages And Music

### Logs and Reports

```shell
This map has "leaked". This is a bug in an item or style, which should be fixed. The displayed line indicates the location of the leak, you may be able to resolve it by removing/modifying items in that area. Please submit a bug report to the author of the item so this can be resolved. Leak coordinates:
```

### Additional information

I'm Using 1970's Style

**Comment by vrad-exe** [comment]
Can you show a screenshot of the chamber? What items were near the leak location?

**Comment by vrad-exe** [comment]
Closing due to not enough info
