### ISSUE TITLE
Entrance and exit doors are blocked off

### ISSUE THREAD

**Issue by Madeline69a** [BEEmod/BEE2-items#4410]
### BEE2 Application Version

4.44.1 64bit

### BEE2 Package Version

4.44.0

### What operating system are you running on?

_No response_ (I put Windows 10 here but it ignored that)

### Description of the bug

You can't get into the puzzle area/out of the starting area.

### Expected behavior

I expect to be able to leave the starting area and get to the actual puzzle itself.

### Steps to reproduce

Step 1: enter the puzzle creator
Step 2: build the puzzle
Step 3: try to walk out of the starting area

### Logs and Reports

```shell
https://cdn.discordapp.com/attachments/882493616554123295/1206002247457046648/message.txt?ex=65da6c1e&is=65c7f71e&hm=73015afad26110b1a8f1c119a5c22cf97013f9f903e0f8dba4f3b7ebf37562ae&
```

### Additional information

I'm using overgrown style.

**Comment by vrad-exe** [comment]
I looked at your log, seems like you might have an older version of the packages. Try completely emptying out the packages folder, then redownloading the latest version. You also might want to try clicking "reset package cache" in the BEE2 settings, then re-exporting.

**Comment by vrad-exe** [comment]
Closing due to not enough info
