### ISSUE TITLE
No textures for certain objects.

### ISSUE THREAD

**Issue by v0rtex-2002** [BEEmod/BEE2-items#4413]
### BEE2 Application Version

2.4.44.1

### BEE2 Package Version

4.44.0

### What operating system are you running on?

Windows 11

### Description of the bug

Several elements show up for certain players with no textures mapped to them. The objects are fully functional, but they appear bright white in the published map. I have seen it now from two different players. One who does not have BBEMod tools installed at all on his machine, the other who uses an older version (4.29). I have see it so far on the tractor beam and the faith plate.

Example screen shot (tractor beam):
https://steamuserimages-a.akamaihd.net/ugc/2470858270614942978/899FF3186D4FA17C66383A16D8583694B5D865D6/

### Expected behavior

Fully mapped textures.

### Steps to reproduce

Not sure if you will be able to reproduce. I cannot reproduce it on my machine. It has been reported to me (or I saw it in a Steam Broadcast) in the following maps:

https://steamcommunity.com/sharedfiles/filedetails/?id=3169726568
https://steamcommunity.com/sharedfiles/filedetails/?id=3131522789

It may be worth noting that both of these maps are using the Overgrown style. I have not heard any reports on this in any of my Clean style maps.

**Comment by Sirinchocolate** [comment]
These maps have most likely been uploaded using the hammer uploading tools. What is visable in the images, is a common mistake that happens while using it. The users just needs to create the cubelightmaps in their chambers. Before uploading their bsp file.

This has nothing to do with Bee2.

**Comment by v0rtex-2002** [comment]
Nope. These are my maps, and I have **never** used Hammer. I only create in P2 in-game editor using the Bee2 tools. But thanks for the quick reply.

**Comment by vrad-exe** [comment]
That does look like a missing texture - for some people missing textures appear white instead of the regular checkerboard, I'm not entirely sure why. Regardless, this would seem to indicate that auto packing isn't working for some reason. Do you have "enable packing" unchecked in the compile options window?

**Comment by LautaroL20** [comment]
You are using an outdated BEEmod version, get V. 4.45.2 and if the issue keeps happening, let us know.
