### ISSUE TITLE
Portalable Stairs Physics Object Collision Bug

### ISSUE THREAD

**Issue by tim-burget** [BEEmod/BEE2-items#4415]
### BEE2 Application Version

4.44.1 64bit

### BEE2 Package Version

4.44.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Physics objects can fall through portalable stairs when a portal is placed on the stairs.
![image](https://github.com/BEEmod/BEE2-items/assets/22843584/4f831780-75a2-4927-958c-43515e014c05)

### Expected behavior

Physics objects shouldn't be able to fall through stairs.

### Steps to reproduce

1. Download this ZIP file: [BEE2 Stair Collision.zip](https://github.com/BEEmod/BEE2-items/files/14812958/BEE2.Stair.Collision.zip)
2. Extract the ZIP file to your Portal 2 Puzzle Maker puzzles folder.
3. Set the lighting option in the BEE2 compile settings to **None** (not strictly required, but the P2C file in the provided ZIP doesn't have any extra lights added, so it's a bit dark otherwise).
4. Set the style to **Clean** (again, not strictly required, but that's the style I used to get the screenshot).
5. Export from BEE2, then open Portal 2.
6. Go to **Community Test Chambers** -> **Create Test Chambers**.
7. Open the puzzle **BEE2 Stair Collision**.
8. Build the test chamber.
9. Place one portal on the wall.
10. Place the other portal on the retracted portalable stairs (order matters here, as the portal must open *when placed* for the bug to happen).
11. Grab the Companion Cube.
12. Attempt to place it on the retracted portalable stairs near the portal that's there, and notice that the cube falls through the floor. (This may take a few tries. You need to place the cube close enough to the portal that it falls through the floor, but not so close that it falls through the portal.)
13. Look at your other portal to ensure the cube didn't fall through the floor.
14. Stand on the floor button and look at the stairs. You should observe that the cube is now stuck beneath the stairs.

### Additional information

Tested and confirmed to happen with all default types of cubes on clean style.

Tested and confirmed to happen with a Companion Cube on all other styles, except for 1970s Old Aperture, which leaked for me. (I will be reporting that as a separate issue shortly.)

**Comment by TeamSpen210** [comment]
Thanks for the detailed report! Adding an additional clip brush seems to fix the issue here.
