### ISSUE TITLE
Old Aperture - Extended Portalable Stairs Can Be Portaled

### ISSUE THREAD

**Issue by tim-burget** [BEEmod/BEE2-items#4417]
### BEE2 Application Version

4.44.1 64bit

### BEE2 Package Version

4.44.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

With a precise shot, you can place a portal on extended Old Aperture portalable stairs.
![image](https://github.com/BEEmod/BEE2-items/assets/22843584/7fab2238-bffc-4af7-88c4-3d54b18cd1b2)

### Expected behavior

It shouldn't be possible to place a portal on extended portalable stairs.

### Steps to reproduce

1. Download this ZIP file: [BEE2 Stair Portal.zip](https://github.com/BEEmod/BEE2-items/files/14814071/BEE2.Stair.Portal.zip)
2. Extract the contents to your Puzzle Maker puzzles folder.
3. Set the `Lighting` setting in the BEE2 `Compile Settings` to `Fast`, and the `Style` in `Export Options` to `1950s Old Aperture`. (It's necessary to use an Old Aperture style, but it doesn't have to be this specific one. That's just the one I used for my screenshots. Similarly, the `Lighting` setting doesn't matter, but I used fast lighting for my screenshots.)
4. Export from BEE2 to Portal 2.
5. Start Portal 2.
6. Go to `Community Test Chambers` -> `Create Test Chambers`.
7. Open the puzzle `BEE2 Portal Stairs Portal`.
8. Build the test chamber,
9. Stand here: ![image](https://github.com/BEEmod/BEE2-items/assets/22843584/d83ad73c-8cb0-45fd-b3c6-672ef983c855)
10. Shoot a portal here (precise shot): ![image](https://github.com/BEEmod/BEE2-items/assets/22843584/e2abb08c-4721-4871-bff7-3cf27bbcb84a)
11. Note that your portal shows up *on* the stairs, which shouldn't be possible when the stairs are extended.

### Additional information

I couldn't test this in the 1970s style due to a leak, but I've confirmed this bug happens in all other Old Aperture styles.

**Comment by TeamSpen210** [comment]
Thanks for the detail here too. Portal placement can be kinda dumb, it only checks the exact point you aim at and then the 4 corners to see if a surface is present. I didn't consider this when making this stair variant, them being all exactly in line with each other allows portalling.
