### ISSUE TITLE
Textures are missing

### ISSUE THREAD

**Issue by Tenht** [BEEmod/BEE2-items#4422]
### BEE2 Application Version

2.4.45.1

### BEE2 Package Version

2.4.45.1

### Description of the bug

Item textures are missing in the editor, The walls are glitched and some items show up as errors

### Expected behavior

The walls should be walls, the items should have textures in the editor and the items should also appear as normal

### Steps to reproduce

Step 1. Download BEEMOD 4.45.1 (including item packages) Step 2. Install as normal. Step 3. Go into a test chamber in the game.

### Additional information

![20240604120009_1](https://github.com/BEEmod/BEE2-items/assets/157294800/a381604f-aff0-47bf-b753-302efaf96035)
the texture thing
![20240604121225_1](https://github.com/BEEmod/BEE2-items/assets/157294800/c4050fbe-54a3-41ef-a6cb-b20dcfc583ff)
uhh
![20240604121936_1](https://github.com/BEEmod/BEE2-items/assets/157294800/69336e6b-bf5e-4e42-b241-0c456910b53b)
more things

**Comment by HalfLife3IsNotHappening2** [comment]
that's happening to me too.

**Comment by TeamSpen210** [comment]
App version 2.4.45.2 should fix this.

**Comment by LautaroL20** [comment]
When reporting a bug, first make sure you're on the latest version of BEE2 and item packages, as the issue may have already been fixed. You're using an outdated BEE2 / item packages version, so please get the latest version of the application & packages and then if the issue still exists, let us know and we will re-open the issue.
