### ISSUE TITLE
Buttons can connect to glass

### ISSUE THREAD

**Issue by BlueClouds11** [BEEmod/BEE2-items#4423]
### BEE2 Application Version

4.45.2 64bit

### BEE2 Package Version

4.45.0

### What operating system are you running on?

Windows 11

### Description of the bug

You can connect outputs to glass and grating. It doesn't appear to do anything in-game.
![image](https://github.com/BEEmod/BEE2-items/assets/106713807/b2dc7b0e-3e0e-412c-ac60-c7d8f252ab1c)

### Expected behavior

I don't think you should be able to connect outputs to glass and gratings.

### Steps to reproduce

Step 1. Open the puzzlemaker
Step 2. Place a button
Step 3. Place glass
Step 4. Press "Connect to..." on the button
Step 5. Click on the edges of the glass

### Additional information

I haven't tested with anything other than pedestal and regular buttons, and only in '70s style.

**Comment by FrozenDragon0** [comment]
Lmfao, that's a new one, but no you shouldn't beable to connect things to glass/grating.

**Comment by vrad-exe** [comment]
This is intentional I think, it's how glass variants like the tinted glass work

**Comment by vrad-exe** [comment]
@TeamSpen210 can you confirm? I haven't touched the latest version of BEE much yet

**Comment by TeamSpen210** [comment]
Yeah it's intentional for tinted glass. Also I was planning on making that the trigger to convert it to a sliding one.
