### ISSUE TITLE
Bring back bottomless pits 

### ISSUE THREAD

**Issue by Tenht** [BEEmod/BEE2-items#4425]
### Description of the feature

Please readd bottomless pits like in BTS, with them replacing goo.

### Why should this be implemented

This helps add more decoration to tests.

### Additional information

![20240610161851_1](https://github.com/BEEmod/BEE2-items/assets/157294800/2f23c1c7-74cc-401c-88a8-903a98ccfd84)

**Comment by Critfish** [comment]
Check the FAQ, these were removed because they didn't function like actual bottomless pits and generally looked ugly. They will come back alongside chamber exteriors at some point in the future.

**Comment by vrad-exe** [comment]
See #3891
