### ISSUE TITLE
all models in game is "ERROR"

### ISSUE THREAD

**Issue by svetik2024** [BEEmod/BEE2-items#4428]
### BEE2 Application Version

BEEMOD 2.3.45.2 64BIT

### BEE2 Package Version

BEE2_v4.45.0_packages

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
no logs
```

### Additional information

portal 1 style

**Comment by TeamSpen210** [comment]
Did you try pressing "reset package cache" in options, then exporting again?

**Comment by LautaroL20** [comment]
Closing because the issue's author doesn't respond.
