### ISSUE TITLE
Cubes clipping through light bridge

### ISSUE THREAD

**Issue by R3Ked** [BEEmod/BEE2-items#4433]
### BEE2 Application Version

4.45.2

### BEE2 Package Version

4.45.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

I don't know if you can do anything about this but uh
https://medal.tv/games/portal-2/clips/i7gvgVrJgV9aQb3yt/d13372wjFbPj?invite=cr-MSxXbWUsMjMzMDIzNjE1LA
When placing an orange laser cube on a slope which powers a laser that turns on a light bridge blocking the cube from falling off, the laser cube goes through the light bridge.

### Expected behavior

The laser cube stays on the light bridge and doesn't go through it.

### Steps to reproduce

Step 1: Recreate the setup shown in the video
Step 2: Place the orange cube onto the slope so it hits the laser relay
Step 3: Let go of it and watch the bug happen

### Additional information

I'm annoyed at this because this was going to be a cool way of bootstrapping a cube. I have another similar idea involving conveyor belts, but I still put a lot of time into this and seeing it all go to waste is annoying.

**Comment by TeamSpen210** [comment]
This isn't something we can fix, though maybe using an offset catcher would help. What is happening is that when the light bridge turns on, it teleports cubes and players if they intersect where the bridge would be to prevent them from being inside it. If you're able to position the cube so it powers the laser continually, this would work.
