### ISSUE TITLE
Exporting error

### ISSUE THREAD

**Issue by YellowCubey69Official** [BEEmod/BEE2-items#4437]
### BEE2 Application Version

4.45.2

### BEE2 Package Version

4.45.2

### Description of the bug

  + Exception Group Traceback (most recent call last):
  |   File "ui_tk\core.py", line 247, in app_main
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "app\UI.py", line 732, in export_editoritems
    |   File "exporting\__init__.py", line 150, in export
    |   File "<frozen os>", line 225, in makedirs
    | PermissionError: [WinError 5] Odmowa dostępu: 'c:\\program files\\portal 2\\bin\\bee2\\'
    +------------------------------------

### Expected behavior

It meant to succesfully export to Portal 2 game. (I'm using cracked portal 2 btw)

### Steps to reproduce

  + Exception Group Traceback (most recent call last):
  |   File "ui_tk\core.py", line 247, in app_main
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "app\UI.py", line 732, in export_editoritems
    |   File "exporting\__init__.py", line 150, in export
    |   File "<frozen os>", line 225, in makedirs
    | PermissionError: [WinError 5] Odmowa dostępu: 'c:\\program files\\portal 2\\bin\\bee2\\'
    +------------------------------------

### Logs and Reports

```shell
I don't know how to fix this. Pls someone tell me how to fix this exprting error.
```

**Comment by Eractive23** [comment]
You aren't going to get support with cracked Portal 2, buy the actual game. It's definitely worth it, especially on sale.

**Comment by YellowCubey69Official** [comment]
> You aren't going to get support with cracked Portal 2, buy the actual game. It's definitely worth it, especially on sale.

However I'm tryingto buy the actual game using fake information, but it denied. Is there a way to bypass paying or smt?

**Comment by TeamSpen210** [comment]
No.

**Comment by YellowCubey69Official** [comment]
> No.

Or fix it?
