### ISSUE TITLE
SFX Trigger

### ISSUE THREAD

**Issue by raspgamerr** [BEEmod/BEE2-items#4447]
### Description of the feature

A sfx trigger for cutscenes and etc.

### Why should this be implemented

I think people won't need to search for "BEE2 addon sfx trigger find for free and without log in" if you add this.

**Comment by CardsAndGamesYT** [comment]
Wdym by `people won't need to search for "BEE2 addon sfx trigger find for free and without registration"`

**Comment by raspgamerr** [comment]
lol i used translate

**Comment by TeamSpen210** [comment]
How would this make puzzles better? BEEmod is not for making cutscenes and story maps, you need the precision of Hammer to do that well.
