### ISSUE TITLE
group things

### ISSUE THREAD

**Issue by myStitch14** [BEEmod/BEE2-items#4452]
### Description of the feature

you can group at least 5 objects. to group something, you would add one thing into the items bar then stack another thing on top of it to make a group. when you group something it would be like the buttons in a group but instead of it just placing when you click on it, it would open the group and you can grab objects you want

### Why should this be implemented

this would allow people to add alot more things into the editor allowing better levels!

**Comment by vrad-exe** [comment]
Item grouping is really limited, they need to have a number of properties in common - you can't just group any arbitrary items together. If there was any way we could expand the palette, we would have done it a long time ago.
