### ISSUE TITLE
all my stuff is missing

### ISSUE THREAD

**Issue by GiraffeasGorilla** [BEEmod/BEE2-items#4456]
### BEE2 Application Version

4.45.2

### BEE2 Package Version

4.45.0

### What operating system are you running on?

Windows 11

### Description of the bug

all of the stuff/models are missing
![Screenshot 2024-11-08 172925](https://github.com/user-attachments/assets/f9d366ad-2ca9-43d9-9c76-3100d00fc598)

### Expected behavior

i just thought it would work how its supposed to

### Steps to reproduce

i put these items in the thing that you can see in the picture and it all broke
![Screenshot 2024-11-08 172944](https://github.com/user-attachments/assets/1c7cb674-370e-4fa4-be89-f97054fecf59)

### Additional information

it first happened in portal 1 style. then i tried original clean, same thing happened. then i tried clean... and same thing happened!

**Comment by TeamSpen210** [comment]
Try pressing "reset package cache" in options, then exporting.

**Comment by myStitch14** [comment]
> Try pressing "reset package cache" in options, then exporting.

thanks this actually worked!
