### ISSUE TITLE
P1 Fire Pit

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#446]
Add a Portal 1 styled Fire Pit that works like toxic goo.

**Comment by Konclan** [comment]
I already suggested the piston plateform github.com/BenVlodgi/BEE2.4/issues/266 but a fire pit would be neat

**Comment by TeamSpen210** [comment]
Can you be more specific about the fire pit? How would it be placed, how big, what does it do?

**Comment by Konclan** [comment]
I imagine the fire pit would work like the Toxic Goo, but I don't know how easy that would be or if it would look good

**Comment by TheReviewers** [comment]
Its Like Toxic Goo

**Comment by TheReviewers** [comment]
but not a skybox

**Comment by TheReviewers** [comment]
seriously i dont want a skybox

**Comment by Konclan** [comment]
I'm having issues editing this issue?

**Comment by Konclan** [comment]
Heres how the pit might look
![20190828224533_1](https://user-images.githubusercontent.com/16567080/63909989-93295300-c9ea-11e9-94cc-0a37d69c2df3.jpg)

**Comment by maxdevgithub** [comment]
https://github.com/BEEmod/BEE2-items/issues/2646 P1 Pit is here

**Comment by maxdevgithub** [comment]
https://github.com/BEEmod/BEE2-items/issues/2295 But Spen is looking forward as a shredder variant

**Comment by Konclan** [comment]
#3891
