### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by JonBae12** [BEEmod/BEE2-items#4463]
### BEE2 Application Version

4.45.2

### BEE2 Package Version

4.45.0

### What operating system are you running on?

Linux

### Logs and Reports

```shell
[DEBUG] localisation.setup(): Language codes: ['en']
[ERROR] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "BEE2_launch.py", line 88, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "app/backup.py", line 9, in <module>
ModuleNotFoundError: No module named 'tkinter'
```

### Additional information

I used the https://github.com/BEEmod/BEE2-items/wiki/Building-from-source Tutourial and when i was ready to execute The programm "BEE2" nothing happend

**Comment by TeamSpen210** [comment]
On Linux Tkinter often isn't part of the install, you'll need to install an additional package for it.

**Comment by JonBae12** [comment]
How do i do this?

**Comment by JonBae12** [comment]
I got it thanks!

**Comment by mrxbox1** [comment]
> I got it thanks!

how???
i'm on Linux Mint, made a venv and everything, even ran `sudo apt-get install python3-tk` both inside and outside the venv and still, regardless of how hard i try....nothing.

**Comment by mrxbox1** [comment]
reinstalled all the packages via pip3. still nothing.
guess i'm gonna have to use the normal puzzle editor.

> I got it thanks!

next time, please, for Peter's sake, explain how you solved this problem...

**Comment by snowandlights23** [comment]
> > I got it thanks!
> 
> how??? i'm on Linux Mint, made a venv and everything, even ran `sudo apt-get install python3-tk` both inside and outside the venv and still, regardless of how hard i try....nothing.

After bashing my head against this problem all day yesterday I finally fucking have something!!

I'm on Linux Mint 22.3

I deleted all my beemod files, and then in the terminal ran ``sudo pipx install pyinstaller``

And then it went and did that and as it then suggested to me I also ran ``pipx ensurepath``

I then again followed the Fully [Automate Building on Linux](https://github.com/BEEmod/BEE2-items/wiki/Building-from-source#11-fully-automate-building-on-linux) and beemod launched successfully.
