### ISSUE TITLE
Toggle Rotation for Pedestal Button

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#447]
A simple toggle for the pedestal button to make it face outwards (180*) instead of inwards

**Comment by Luke18033** [comment]
This could use Start Reversed.

**Comment by Luke18033** [comment]
Why hasn't this been implemented yet?

**Comment by LautaroL20** [comment]
@Luke18033 - Because we were focused on another things? Personally i was learning how to use Autodesk 3D Max in order to make models for my addons, and i think the results aren´t bad:

![protruding ped](https://cloud.githubusercontent.com/assets/12244376/21789585/e95a1ad8-d6b4-11e6-98ac-cf792d6f5d31.png)

**Comment by LautaroL20** [comment]
I was thinking on making something a bit more complete than just a simple toggle rotation on Valve´s pedestal, and we should also have the chance of positioning it in middle-right-left positions. Should it be a separate item?

![20170317152636_1](https://cloud.githubusercontent.com/assets/12244376/24057468/36132e5a-0b26-11e7-9ea8-8d1ec4e5749c.jpg)

**Comment by Luke18033** [comment]
Make it a separate item - Button Type defaults to Weighted if you load a .p2c where the property isn't present. That means that all pedestal buttons would be moved to the left position when converting old maps. Weighted could be made into the center position, but that would make it inconsistent with the protruding button.

**Comment by TeamSpen210** [comment]
The main reason this hasn't ben implemented is that I'm trying to do it generally, so we don't have lots of duplicate instances.

**Comment by Konclan** [comment]
Isn't this basically implemented with the other pedestal button item?

**Comment by LautaroL20** [comment]
Yes.

**Comment by Luke18033** [comment]
A variant of the pedestal button now exists with this functionality.

**Comment by LautaroL20** [comment]
Indeed. Both of my variants from the vanilla pedestal button brings the user the chance of doing so.
