### ISSUE TITLE
Overgrown Rocket Turret?

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#452]
@TeamSpen210  Ive Been Thinking, Maybe You Can Rig The Rocket Turret From Portal Stories Mel, Or Just Make a custom model, i do think that the ps mel one looks better : http://steamcommunity.com/profiles/76561198176665143/screenshot/359525594123529853

**Comment by TeamSpen210** [comment]
I didn't even know there was such a model.

**Comment by TheReviewers** [comment]
now you know :D

**Comment by TheReviewers** [comment]
rig it from portal stories mel with permission

**Comment by LautaroL20** [comment]
Nice find, i missed that Damaged Rocket Turret when i played Portal Stories Mel.

**Comment by TheReviewers** [comment]
@LautaroL20 I Think Me And You Are One Of The Most Active Ones Here

**Comment by TheReviewers** [comment]
@LautaroL20 Its In Chapter 3

**Comment by Konclan** [comment]
Oh yeah, I've seen that turret before, there are also other great models from Mel you can use but I think you want to credit the maker

**Comment by Luke18033** [comment]
In the [Mel FAQ](https://steamcommunity.com/app/317400/discussions/0/523890046870378127/), they say they're fine with people using everything except the characters and portal gun, as long as you credit them. That means this could be added, along with the Old Aperture turrets. I think it would be a good idea to fix some of the rocket turret's existing bugs first though.

**Comment by HeimlichLaboratories** [comment]
Old thread, but I think it should be a less dirty version, the mel one kinda looks too trashed to work

**Comment by Luke18033** [comment]
The rocket turret has an overgrown skin now but it's bad, the mel one isn't really better though
