### ISSUE TITLE
Love As Construct Companion Cube Doesnt Play Cara Mia Addio

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#455]
When Placing  A Companion Cube With The Song Love As Construct, The Cube Doesnt Sing :(

**Comment by Konclan** [comment]
Wait what? Can I get a reference video to when this happens?

**Comment by TheReviewers** [comment]
https://www.youtube.com/watch?v=H5TbaI9qTys

**Comment by TheReviewers** [comment]
@Konclan once he goes near it, you will hear

**Comment by Konclan** [comment]
Woah how have I never heard that before?
