### ISSUE TITLE
Half-block observation room with 3 positions

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#459]
A small half observation room which is placed in the middle of a 1/4 Wall:

Parameters suggested for this item by @TeamSpen210: "I'll probably make this an item with the ButtonType property, so you can position it to the left, center and right of the block."

---

![2015-11-22_00002](https://cloud.githubusercontent.com/assets/12244376/14378488/8ffe56a4-fd4b-11e5-974c-06ff0ea6c6aa.jpg)
![20160408051748_1](https://cloud.githubusercontent.com/assets/12244376/14378500/a5b97b22-fd4b-11e5-9211-6dfe0d3799fe.jpg)

**Comment by TheReviewers** [comment]
srsly wtf, i was in the middle of suggesting it right now, then i saw this!

**Comment by Konclan** [comment]
So a 1/2x1 observation window, would this be a random varient of the normal one or its own item

**Comment by LautaroL20** [comment]
Well, I think this should be an own item instead of a random varient of the normal one.

**Comment by TeamSpen210** [comment]
I'll probably make this an item with the ButtonType property, so you can position it to the left, center and right of the block.

**Comment by LautaroL20** [comment]
@TeamSpen210 +1 awesome idea, I will edit the post description by adding your parameters for this item, so it will be easier to remember in a future when re-checking the post.

**Comment by Konclan** [comment]
With this, we could replace the Portal 1 observation room altogether. Make the normal size an actual normal size observation room

**Comment by LautaroL20** [comment]
Yes, this item can perfectly be merged with the the P1´s observation room once i done it which will be as soon as i finish building my new PC. Currently using a Potato one after my main died.

**Comment by Luke18033** [comment]
I implemented this:
![image](https://user-images.githubusercontent.com/19228201/91630978-d108e080-e98a-11ea-9c79-c6417f531e12.png)
![image](https://user-images.githubusercontent.com/19228201/91631000-ea119180-e98a-11ea-939d-d09406f592b5.png)
It still needs editor models and style variants.

**Comment by LautaroL20** [comment]
Looks good. As for the editor models, i might contribute with them as i have some skills at Blender. However, for the style variants we could ask Spencer or someone else from the Discord community since my domain at Hammer is not too good.

**Comment by Luke18033** [comment]
I can do the style variants, I just haven't yet.

**Comment by LautaroL20** [comment]
I´ve implement the Editor Models + Selection Meshes:
![Editor Models](https://user-images.githubusercontent.com/12244376/91645381-fba27a00-ea1a-11ea-8512-a12770317ebc.jpg)
![Selection Meshes](https://user-images.githubusercontent.com/12244376/91645507-dfeba380-ea1b-11ea-9696-f09889f8f1ff.jpg)

**Comment by Luke18033** [comment]
That was fast. Thanks! Though it'd probably look better if Bendy wasn't visible in the center one.

**Comment by LautaroL20** [comment]
Export the `observation_window_01.vtf` to any image format and mark the parts which you would like to have on the centered model and i´ll redo it.

**Comment by Luke18033** [comment]
Actually it doesn't look like there's really a good part of the texture to use, just keep it like that I guess.

**Comment by Luke18033** [comment]
For the Old Aperture version of this, I guess I'll just make it a smaller observation grate? I'm not really sure of a better design.

**Comment by TeamSpen210** [comment]
It should probably be the existing one, but with the grate smaller.

**Comment by LautaroL20** [comment]
Yeah, however you could add a few additional details to it just to prevent causing a copy/paste feeling, maybe by putting some old aperture overlays somewhere inside the observation or other things.

**Comment by LautaroL20** [comment]
Once you implement the style variants, i compromise myself to do styled versions of the editor model although for Overgrown, i am not sure which texture should i use, maybe `glass_underground_dirty01a` or just make a totally new one?

**Comment by Luke18033** [comment]
Again, I don't think we really need to worry about styled editor models (except maybe in P1/OldAp which have completely different designs). But if you really want to make one, then I'd suggest using a custom texture based on the cracked glass models.

**Comment by LautaroL20** [comment]
> Again, I don't think we really need to worry about styled editor models (except maybe in P1/OldAp which have completely different designs)

I think you´re right, also it would be a waste of effort. I will focus on the P1-Retro variants, only.
