### ISSUE TITLE
A Very Long List Of Suggestions For Underground Old Aperture  BTS. Read Please.

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#467]
Firstly, Underground BTS Will Have Some New Entrance/Exit
Secondly, @BenVlodgi In The End Of This Issue, There Is A Story For You
Lastly, @TeamSpen210 Please Take Time To See All Pictures.

Alright.

Entrance/Exit To Chamber: ( Corridor 1 Is A Manual Entrance/Exit )

Corridor 1 : http://steamcommunity.com/sharedfiles/filedetails/?id=662893204

Lobby 2 : http://steamcommunity.com/sharedfiles/filedetails/?id=662894529

Corridor 3 : http://steamcommunity.com/sharedfiles/filedetails/?id=662895673

Surface Marker : http://steamcommunity.com/sharedfiles/filedetails/?id=662899090

Portable Wall : http://steamcommunity.com/sharedfiles/filedetails/?id=662900589

Non Portable Wall : http://steamcommunity.com/sharedfiles/filedetails/?id=662901702

Portable Floor : http://steamcommunity.com/sharedfiles/filedetails/?id=662904499

Non Portable Floor : http://steamcommunity.com/sharedfiles/filedetails/?id=662905468

Glass : http://steamcommunity.com/sharedfiles/filedetails/?id=662903147

Elevator To Surface ( Connected Directly To Sphere ) : 
http://steamcommunity.com/sharedfiles/filedetails/?id=662906453

Floor Surface Marker ( Couldnt Find Portable ) : http://steamcommunity.com/sharedfiles/filedetails/?id=662908373

Debris In Goo : http://steamcommunity.com/sharedfiles/filedetails/?id=662909920

Large Obs. Room : http://steamcommunity.com/sharedfiles/filedetails/?id=662910800

Track Platform : http://steamcommunity.com/sharedfiles/filedetails/?id=662913914

Signances : http://steamcommunity.com/sharedfiles/filedetails/?id=662919857

Crushers : http://steamcommunity.com/sharedfiles/filedetails/?id=662922366

Pedestal Buttons ( Without The Sign ) : http://steamcommunity.com/sharedfiles/filedetails/?id=662923633

Lightstrip : http://steamcommunity.com/sharedfiles/filedetails/?id=662925823

Gel Dropper : http://steamcommunity.com/sharedfiles/filedetails/?id=662927404

And Thats All I Have For Today, As A Promised For @BenVlodgi There Is a Story For You :3.

Story : The Scientists Were Developing An A.I Made To Make Children Happy, And Help The Community, After They Finally Developed It, They Wanted To Test Its Intelligence, The Asked It : ''Is There A God''.......It Replied, "There Is Now". 

@TeamSpen210 Please Let Me Know What You Think About The Old Aperture Bts Ideas :3

**Comment by Konclan** [comment]
Some of these would have to be closed off, I don't think that there could be a large cave area unless its not part of the chamber but rather part of the entry/exit like how the old aperture style does it now.

**Comment by TheReviewers** [comment]
@Konclan it is part of entry/exit only

**Comment by Konclan** [comment]
Also it would have to be a 80s bts so that all the gels could be present

**Comment by TheReviewers** [comment]
umm. no , 1950's style doesnt block use of other gels

**Comment by TheReviewers** [comment]
its just creativity you need <3

**Comment by Konclan** [comment]
Oh yeah duh, I'm dumb lol

**Comment by TheReviewers** [comment]
@Konclan Dude, Its Just A Style I Came Up With. I Hope Ben Reads The Story

**Comment by TheReviewers** [comment]
@Konclan We All Are A Big Bee2 Family, Noone Is Dumb. Everyone Are Friends!

**Comment by TheReviewers** [comment]
@TeamSpen210 I Spent 3 Hours Taking My Own Pictures, Can You Please Tell Me Your Opinion

**Comment by Konclan** [comment]
I like the ideas for old aperture bts, I just think that it may be a while before new themes are made

**Comment by TeamSpen210** [comment]
This is very comprehensive. I am planning on doing something like this for the four decades. The entrances and exits would be cave tunnels probably, not connected to Erichment Spheres. 

For the gel dropper and track platform, I can't really use those models without modification as they are now. (The platform track needs to be below the platform, and the gel dropper is a T-junction model.) Glass and signage will match the current decade styles, as well as the lightstrip colour.

**Comment by TheReviewers** [comment]
@TeamSpen210 3 Hours Of Hard Work , Well Repaid!

**Comment by Konclan** [comment]
Unfortunetly all of the images are gone, they should have been uploaded to git and not steam
