### ISSUE TITLE
3x2 Angled Panel

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#474]
A Drawbridge That Extends From Down To Straight, As An Actual Bridge :3

**Comment by TeamSpen210** [comment]
Um, the current drawbridge item does exactly this? In Old Aperture it even gets ropes to pull it around.

**Comment by Enterpise** [comment]
So, this should be closed?

**Comment by Konclan** [comment]
I think he is talking about a drawbridge that opens upwards instead of downwards

**Comment by Konclan** [comment]
So it would be inbedded in the wall a bit like a normal angled panel, but the size of 1x2

**Comment by TheReviewers** [comment]
@TeamSpen210 No, The Drawbridge Goes From Up To Down, If Placed Beneath A Door, It Would Block The Door.

**Comment by CrashingScience** [comment]
Set the normal drawbridge to start enabled?

**Comment by TeamSpen210** [comment]
What you want is a normal angles panel, but a 1½ block long top.

**Comment by TheReviewers** [comment]
@TeamSpen210 Just Like Drawbridge

**Comment by Konclan** [comment]
Honestly, this item is too big to be a test element and we already have #466 with 1x2 glass panels
