### ISSUE TITLE
Portal Displacement Field

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#475]
A fizzler that allows people and objects to go through, but clears portals and blocks portals

**Comment by TeamSpen210** [comment]
What colour should it be?

**Comment by Konclan** [comment]
Hmm, perhaps the green

**Comment by TeamSpen210** [comment]
That colour is actually in use for 3 different fizzlers already :(. Maybe I'll make it shift between blue and orange perhaps.

**Comment by Konclan** [comment]
Which fizzlers use green? Or are they not in the pack

**Comment by TeamSpen210** [comment]
* TAG fizzlers use green and purple, although they also have a different texture/line pattern.
* FourthReaper's Surface Division Fields are green, although they're not going to be in BEE maps.
* The original BEE2 had broken versions of FelixGriffin's "Physlers", which I might re-add in the future.

**Comment by Konclan** [comment]
Oh ok, I guess a mix of blue and orange would also make sense because it only affects portals

**Comment by ellingtonvengaboysmuseum** [comment]
my force field fizzler is green. but that blocks everything

**Comment by ZombiePwner1** [comment]
@ellingtonvengaboysmuseum your Fizzler is the same as the force deflection field with the exception of letting portal shots go through.

**Comment by Konclan** [comment]
No, It's actually the opposite, it doesn't allow portals but allows people and objects

**Comment by ZombiePwner1** [comment]
@Konclan i was talking to Ellington not you.

**Comment by Konclan** [comment]
Oh sorry, my bad :P

**Comment by Konclan** [comment]
Bump

**Comment by Konclan** [comment]
Bump

**Comment by Byzarru** [comment]
This should be the Teleportation Displacement Field. It serves the same purpose and has the bonus of having been featured in a mod already.

**Comment by Endermage77** [comment]
And how about the fizzler/laser swap determines whether stuff is blocked or fizzled?

**Comment by Byzarru** [comment]
There isn't a fizzler that blocks everything but the player, but the fizzler variant is the Material Emancipation Grill.

**Comment by Luke18033** [comment]
> Surface Division Fields are green, although they're not going to be in BEE maps.

@TeamSpen210 - Why not? You never actually provide a reason, you just say "it's not going to be in BEE".

**Comment by Konclan** [comment]
How about this is the Portal Displacement Field

**Comment by Konclan** [comment]
A pink version of the teleport displacement field

**Comment by Konclan** [comment]
Closing due to lack of development and no need for more fizzlers
