### ISSUE TITLE
Reconstructing Pit Suggestion

### ISSUE THREAD

**Issue by corrupt21** [BEEmod/BEE2-items#483]
Can the reconstructing pits look like this?
![untitled](https://cloud.githubusercontent.com/assets/17777059/14674127/ac9fc6c2-0745-11e6-942b-ed32a0aa6678.png)

**Comment by LautaroL20** [comment]
Wow man, it looks absolutely amazing, i really wish it isn much difficulty to make it for Bee2.

**Comment by TheReviewers** [comment]
@LautaroL20  The Portable Surface Doesnt Have A Pillar

**Comment by Konclan** [comment]
It's connected to the wall

**Comment by ellingtonvengaboysmuseum** [comment]
that would be mildly easy once @TeamSpen210 gets pillar and horizontal pillar generation and object generation working

**Comment by Konclan** [comment]
Merging with #87
