### ISSUE TITLE
Object Trigger

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#484]
Once An Object ( Cube, Gel Etc) Touches That, It Activates Something

**Comment by Konclan** [comment]
An improvement for this would be when the player is holding a specified object, then a trigger could auto-save

**Comment by Luke18033** [comment]
This item is actually in Radelite's addons for the old BEE2, so all TeamSPen210 would have to do is port it to BEE2.4.

**Comment by Luke18033** [comment]
What would actually be better is to have Start Enabled and Start Reversed to choose what gets detected (enabled for players, reversed for physics objects). You can't detect gel.

**Comment by Konclan** [comment]
FumblyBumbly made this but it has yet to be implemented

**Comment by Luke18033** [comment]
Still should be a property on normal triggers instead of a separate item.
