### ISSUE TITLE
Laser emitter on floor behind glass

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/BEE2-items#487]
_From @Konclan on April 21, 2016 21:59_

In the clean style, when placing a laser emitter on the floor and in the center, it should be placed under a small pane of glass so that you can more easily place cubes on top of it. Such as in Portal 2 Co-op Course 1 Chamber 5.
http://theportalwiki.com/wiki/Portal_2_Co-op_Course_1_Chamber_5

_Copied from original issue: BenVlodgi/BEE2.4#294_

**Comment by TeamSpen210** [comment]
Actually, the collision mesh for laser emitters doesn't include the protruding emitter portion, so cubes can be placed directly on it. This is much nicer visually though.

**Comment by LautaroL20** [comment]
Suggestion implemented a long time ago.

**Comment by TeamSpen210** [comment]
Not for all styles.

**Comment by LautaroL20** [comment]
Ok.

**Comment by Luke18033** [comment]
It's on Clean and Overgrown, and probably also Portal 1. Are you planning to implement this for other styles as well?
