### ISSUE TITLE
Double glass panel

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#488]
![double-glass](http://images.akamai.steamusercontent.com/ugc/447356124337041110/32FC80A5717A01533FFC7B1F5D5339745F58F137/)

**Comment by ZombiePwner1** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=670357869

**Comment by ZombiePwner1** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=670357928

**Comment by ZombiePwner1** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=670357973

**Comment by Endermage77** [comment]
Can we also have a regular variant of the double-long panel?

**Comment by Luke18033** [comment]
Also see #466.

**Comment by Luke18033** [comment]
![20170311185423_1](https://cloud.githubusercontent.com/assets/19228201/23828612/78414d32-068c-11e7-9826-395c31940e5f.jpg)

**Comment by TeamSpen210** [comment]
Make sure to check that they look good on the side walls of the embed block when retracted.

**Comment by Luke18033** [comment]
That's the problem, they clip through the sides. We'd need a custom model to fix it, which I can't do. (I haven't even made an editor model.)

**Comment by TeamSpen210** [comment]
For the square panel, use `BEE2/panels/panel_faith_large.mdl`. That's slightly resized to not clip.

**Comment by ZombiePwner1** [comment]
@Luke18033 May i perhaps have this so i can play around with it?

**Comment by Luke18033** [comment]
I'll commit it once the Clean versions are done, so you'll be able to get it in the dev version.

**Comment by TeamSpen210** [comment]
Commit to another branch until all the styled variations are done.

**Comment by Luke18033** [comment]
I used the faith panel model for the single one, but we'll need a custom model for the double one.

**Comment by Luke18033** [comment]
It's committed! You can try it out on the `glass_pan` branch.

**Comment by Luke18033** [comment]
Old Aperture:
![20170312183549_1](https://cloud.githubusercontent.com/assets/19228201/23838431/df30bade-0752-11e7-9427-187b4e9f24e2.jpg)

**Comment by Luke18033** [comment]
I've also made cracked Overgrown variants. I'll commit all of them once I make P1 versions.

**Comment by Konclan** [comment]
Excited for this item tbh, looks good

**Comment by Luke18033** [comment]
#466 is the main issue being used for these items now.
