### ISSUE TITLE
Rexaura Items

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/BEE2-items#490]
Add items and other things from Mevious' Rexaura mod:
- [x] Pellet Destroyer - a sphere on a piston platform which destroys pellets on contact.
- [X] Pellet Catcher/Emitter variants - integrated into BEE1 items
- [x] Pellet Detector - Fizzler field that enables outputs when pellets pass through
- [x] Cube reflection holder - holds cubes in position to reflect pellets orthogonally
- [x] Pellet cube fizzling mechanic - add Style Var to make pellets dissolve cubes on bounces
- [X] Rexaura Music tracks

**Comment by Konclan** [comment]
Will these be portal 1 style only or will you try to add style variants?

**Comment by TeamSpen210** [comment]
All styles. I deliberately wrote the BEE2 such that items have to work in all styles. If there aren't appropriate variants, it will just choose the first defined one.

**Comment by Konclan** [comment]
Cool

**Comment by Luke18033** [comment]
This isn't updated, destroyers and deflectors are in Pr21...

**Comment by Luke18033** [comment]
How about Rexaura voice lines?

**Comment by TheDarkBomber** [comment]
What about the Lifeform Sensor?

**Comment by Luke18033** [comment]
@TheDarkBomber That doesn't have anything to do with Rexaura.

**Comment by TheDarkBomber** [comment]
Wasn't that in BEE2.2 though? And a rexaura item?

**Comment by Luke18033** [comment]
It's from Portal Pro, I think.

**Comment by TeamSpen210** [comment]
I'd want to add those too.
