### ISSUE TITLE
Grating-placeable antline - on light-strip sized slab

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#494]
Ok, Firstly, I Would Like Antlines On Grating, Because it looks good 
http://steamcommunity.com/sharedfiles/filedetails/?id=671593780

Secondly, Maybe Buttons on grating too?

If buttons dont go on grating, code it to be like a turret, rotatable, but placeable on grating i guess?

**Comment by LautaroL20** [comment]
The idea of having an "Antline" on the grating looks very interesting, hope it is doable though.

**Comment by Konclan** [comment]
@TheReviewers @LautaroL20 I agree

**Comment by TeamSpen210** [comment]
It's not easily doable, since I can't change how antlines are generated. I could make a item with antlines on the surface of it, but you'd need to link it like an AND gate and other things.

**Comment by TheReviewers** [comment]
@TeamSpen210 Well, then there must be a good tutorial of how to use the logic gates though

**Comment by TheReviewers** [comment]
@TeamSpen210 Ive been thinking of an item, an antline in the middle, rotatable like a reflect cube, and connectable, ofcourse if you have alot of antlines you wont be able to connect them all :3

**Comment by TeamSpen210** [comment]
The reflection cube/turret rotation setting is nice, but the problem is that it doesn't work correctly if the item is placed on walls or the ceiling - the rotation gets all messed up.

**Comment by TheReviewers** [comment]
@LautaroL20 Do you think this will ever be added?

**Comment by LautaroL20** [comment]
If this is complicated to do, then i dont know how far is your suggestion to be implemented. There is currently an huge list of suggestions that is also to be implemented too.

**Comment by Luke18033** [comment]
@TheReviewers - This will probably be implemented, but it would only have 8-positioning, not 360 degree rotation. I was working on a 360 Degree Pedestal Button at one point, but I'm not working on that anymore. Had I finished it, I could have made it grating-placeable.

**Comment by Konclan** [comment]
Seems like a lot of effort for an item that wouldn't serve much purpose, plus we now have antlasers

**Comment by Luke18033** [comment]
Doesn't seem like it'd be that bad, the item would basically just be an AND gate strip set to anchor on grating with some tiles and an antline attached.
