### ISSUE TITLE
Collectable point markers

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#495]
a custom item should be added to bee2 that acts like a collectible item similar to the 8 red coins from the 3D mario games (super mario 64, super mario sunshine etc) that you have to figure out how to collect a certain number of this item in a test chamber to trigger something (a door opening or something) or should I say an item that creates an easter egg hunt

my idea is a custom glass cube that would rotate on its own and would have some glow effect on the inside of it. it would have a trigger that would be triggered when the player touched it and make it disappear

you would connect each one to another item that would calculate how many where in the map by number of connections and it would give a count of how many are left to collect

if possible see if we can design a custom texture that would briefly show and also a custom sound that would play when one was collected or triggered.

you could really create some complex challenging tests with a item like this.

another version of this item would be one that comes with a timer and once the player triggered the timer these items would appear and you would have to collect them all in the time limit. if this is even possible once the timer is triggered if you can have a custom texture or message pop up on the screen that says "Collect "#" of "Collectible item" before time runs out"

make it so their logic would work like a piston platform so you could make one float in mid air right in the path of a catapult.

**Comment by TeamSpen210** [comment]
Actually, there are some unused Portal 2 models for a collectable like this. It won't need any connections on the items, I can easily make the compiler calculate the number in the map. I'll probably make them have a few colours, so you can use them more than once in the map. The counter item would have a timer option on it, indicating how many must be collected before it activates (with infinite = all of them). It'll have a big digit display showing how many more must be collected.

**Comment by Luke18033** [comment]
@TeamSpen210 You should be able to have multiple "channels" using a timer option.

**Comment by TeamSpen210** [comment]
I can only have 1 of each property type, so I'll need to use something like 'Cube Type' for that.

**Comment by Luke18033** [comment]
@TeamSpen210 I knew that already, I just didn't realize that you would end up needing 2 timer properties on the counter, since one is already used for the amount.

**Comment by Luke18033** [comment]
Maybe instead use Button Type or Cube Type to choose the "channel"

**Comment by Konclan** [comment]
Actually these could be holograms with visible projectors, just so they don't look super out of place and they can still have antline and signage connections. They would be placed like Piston Platforms for varying hight

**Comment by TeamSpen210** [comment]
Erik Zeug made a nice model for that I could use.

**Comment by Konclan** [comment]
This can basically be achieved with triggers or pedestal buttons and doesn't really serve much purpose as a testing element. Probably a "better on paper" kind of deal and if someone wants this added they could easily make a ucp for it.
