### ISSUE TITLE
Antline Lasers

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#496]
An item that creates a rope-like antiline from one node to another. As seen in aperture tag.
![floating antiline](https://cloud.githubusercontent.com/assets/16567080/14769156/47d295c8-0a18-11e6-9cf0-61983bd7d6fd.jpg)

**Comment by TheReviewers** [comment]
And Batcature ( My Friends Map )

**Comment by Konclan** [comment]
I know there are other things that use this, aperture tag was just the one I knew had them.

**Comment by LautaroL20** [comment]
That looks as terrible as the Stretched long Light Strip is, to be honest.

**Comment by TheReviewers** [comment]
@LautaroL20 Better than signances

**Comment by TheReviewers** [comment]
@Konclan 2 Things

Why are turrets not old

What is that circular companion cube on the right lower corner

**Comment by TeamSpen210** [comment]
This would probably be the original Workshop version of Aperture Tag, which used just vanilla resources. The companion-cube is a [Coop hat](http://theportalwiki.com/wiki/Bionic_Beanie), which is being used as the "paint gun".

**Comment by TheReviewers** [comment]
HAHaHAHAHAH, A HAT!?

**Comment by Konclan** [comment]
Yeah I just grabbed the first tag screenshot I could find with these objects :P

**Comment by Endermage77** [comment]
Some ideas for Old Aperture variants:
50's 60's: Neon tubes that glow with its antline.
70's: Colored electric cable with lights along it.
80's: Small plastic laser emitter and reciever with colored laser line.

**Comment by ZipZoptheCat** [comment]
So christmas lights?
