### ISSUE TITLE
[PRL21.5 Bug] Original Clean Style: Chamberlock is missing a model

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#501]
The Chamberlock model does not have a model in the editor

**Comment by TheReviewers** [comment]
@Konclan What Style?

**Comment by Konclan** [comment]
Clean

**Comment by TheReviewers** [comment]
strange

**Comment by TheReviewers** [comment]
pre release?

**Comment by Konclan** [comment]
19

**Comment by TheReviewers** [comment]
Strange. it works for me

**Comment by Konclan** [comment]
Screenshot?

**Comment by TeamSpen210** [comment]
That'll likely be because TheReviewers has my original addons installed, which includes the chamberlock model.

**Comment by Konclan** [comment]
Ah ok, that makes more sense

**Comment by TheReviewers** [comment]
@TeamSpen210 Ofcourse i have the old beemod and your addons ;3

**Comment by Luke18033** [comment]
This is fixed now.
