### ISSUE TITLE
Special behaviour for infinite Pedestal Button + latching items (Autoportal, Global Cube Dropper)

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#503]
Some items will self-deactivate if another of the same type activates. If connected to a infinite pedestal button, switch to different logic which unlocks the button after the attached item is deactivated.

**Comment by TheReviewers** [comment]
Useful For Autoportals

**Comment by Konclan** [comment]
But a button on a not hate?

**Comment by Konclan** [comment]
Stupid mobile

**Comment by Konclan** [comment]
Put a button on a NOT gate

**Comment by TheReviewers** [comment]
@Konclan I Dont Know How To Use Logic Gates. And I Dont Want To Know... >:(

**Comment by TheReviewers** [comment]
@Konclan And logic gates crash game

**Comment by TeamSpen210** [comment]
How would this work? Pressing a button with infinite time turns on the output forever; what should pressing it again do?

**Comment by SpyyZ158** [comment]
Like when you play in first chapter of Portal 2 when you want to press button to open portal for Cube and Button 
![portal 2 button and cube](https://cloud.githubusercontent.com/assets/16452792/14831957/1eaaced6-0bf8-11e6-8e20-e4eef64d1e44.jpg)

**Comment by TheReviewers** [comment]
@SpyyZ158 Exactly 

@TeamSpen210

**Comment by TeamSpen210** [comment]
Instead of a new item, I think I'll make this behaviour appear when using pedestal buttons with autoportals. When the autoportal deactivates it will reset the pedestal button it's attached to automatically.

**Comment by LautaroL20** [comment]
I am sure what TheReviews wanted to suggest, is the ITEM_BUTTON_PEDESTAL_TOGGLE. Item wich meets this funtion: "Modified pedestal button which will toggle output. If a delay is set it will behave normally." 

This item is from the TeamSepn210 original addons pack V45.

**Comment by TheReviewers** [comment]
@LautaroL20 I Dont remmember an item like that

**Comment by LautaroL20** [comment]
@TheReviewers - This item is available on the TS Addons V4.5 pack, i guess it is an item pretty easy to port for Bee2.4.

**Comment by TeamSpen210** [comment]
Instead of adding that item directly, I added a flip-flop logic item, which has the same function when paired with a pedestal button.

**Comment by TheReviewers** [comment]
@TeamSpen210 No Teamspen, I Like The Behaviour Id

**Comment by TheReviewers** [comment]
Idea

**Comment by TeamSpen210** [comment]
The flip-flop is instead of a toggle button, not the latching version which resets when the attached autoportals does.

**Comment by TeamSpen210** [comment]
This also should apply to infinite Pellet Launchers.
