### ISSUE TITLE
Adjustable Unstationary Scaffold Speed

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#504]
The unstationary scaffolds are extremely slow and inconvenient, perhaps there could be a speed option

**Comment by TeamSpen210** [comment]
If you check Portal 1, you'll see that they travel the same speed as those ones. I'll add an option to increase the speed though.

**Comment by Konclan** [comment]
I know in the portal game they are slow, but they definitely need a speed option if they are to be useful for maps

**Comment by Konclan** [comment]
woops

**Comment by TheReviewers** [comment]
@TeamSpen210 Actually The Portal 1 Is Faster Than The Teamspen One...

**Comment by TeamSpen210** [comment]
Indeed, that makes it simple since it can be map-global.

**Comment by Luke18033** [comment]
I would have preferred it being separate, but that can't be done unfortunately.
