### ISSUE TITLE
Prl20 Bug: Angled Panel is not using "Styled Texture" when its placed on floor

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#517]
![20160502070443_1](https://cloud.githubusercontent.com/assets/12244376/14952204/e7dc316a-1034-11e6-83ce-066bedc4288e.jpg)

**Comment by TeamSpen210** [comment]
This is actually on purpose. If a surface is > 30°, it will use wall textures, otherwise floor textures. I might change that for this specific circumstance though.
