### ISSUE TITLE
All custom fizzlers are not generating 4x4 surfaces

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#518]
They´re not generating "Gridded Surfaces":

![Image](https://cloud.githubusercontent.com/assets/12244376/25389977/74c65b0e-29a8-11e7-9cfc-d6523297657c.jpg)

**Comment by TeamSpen210** [comment]
I don't think light bridges ever generate with 4x4 tiles - they only take up part of the grid shape, so I think I'll leave them with the normal values. I'll fix the fizzlers though.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - No, this is not fixed yet, wheels!

**Comment by LautaroL20** [comment]
![Image](https://cloud.githubusercontent.com/assets/12244376/25389977/74c65b0e-29a8-11e7-9cfc-d6523297657c.jpg)

**Comment by TeamSpen210** [comment]
I really should do this in code, automatically to all fizzler items.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Says wheels!

**Comment by LautaroL20** [comment]
Gridded surfaces are not being generated yer.

**Comment by Nikita74RU** [comment]
Death Fizzler in overgrown should be just a laser grid that jams open (turns itself off but trigger hurt does not) a bit, then closes (activates) again.

**Comment by Konclan** [comment]
Still not fixed!

**Comment by Konclan** [comment]
![20190828221648_1](https://user-images.githubusercontent.com/16567080/63907560-8f450300-c9e1-11e9-84b0-989a895dfc76.jpg)

**Comment by Konclan** [comment]
From @LautaroL20 Overgrown currently re not using checkered walls and ceilings

![20160820102502_1](https://cloud.githubusercontent.com/assets/12244376/17831538/d2a60738-66c1-11e6-95a5-b949b71f139c.jpg)

**Comment by Luke18033** [comment]
This will be fixed with the tiling overhaul I'd imagine?

**Comment by TeamSpen210** [comment]
Yep. Specifically side-offset ones will produce 4x4 tiles, centred  ones won't affect the tile size currently.
