### ISSUE TITLE
Text Item

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#531]
I saw in the portal 2 educational version there was a text item that allowed you to input text, is this possible?

https://www.youtube.com/watch?v=uHYSW92pjWU

**Comment by Konclan** [comment]
actually it looks like the educational version is completely different... dang

**Comment by TeamSpen210** [comment]
It's a different game engine version. I can't add those widgets, but I could make someting in the BEE2 itself - allow you to type a list of presets into the application, and then select with a timer-dial. I can use the editor model and palette icon though.

**Comment by TheReviewers** [comment]
@TeamSpen210 Didnt you just say its undoable...

**Comment by TeamSpen210** [comment]
I can add the textboxes into the BEE2 app itself, and then match that to the timer-dial.

**Comment by Luke18033** [comment]
This would use the Item Configuration Pane - BEEmod/BEE2.4#467.

**Comment by ZipZoptheCat** [comment]
So it would function the same as the custom cube colours and we'd have 28 messages to choose between?

**Comment by CheezyPig** [comment]
(Old post yada yada)... I have now added this to my package which you can find under my repos. It was actually really quite easy with ItemVars (which I don't think existed when this was made)
