### ISSUE TITLE
Separated Co-op Checkpoint: Players can break the checkpoint

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#533]
The condition from both players to be in the in front of the camera eyes doesn't work properly and this causes the player to be able to escape from the closing of the glass panel:

![separated](https://cloud.githubusercontent.com/assets/12244376/14981674/44af0638-1107-11e6-9d25-777919414999.gif)

There is no Player Clip under the glass panel floor from the entrance on the Separated Checkpoint, and this may cause players to fall in and getting stuck forever on it (in case the map has some kind of returning to original puzzle area)

![separated](https://cloud.githubusercontent.com/assets/12244376/14981520/269df902-1106-11e6-942f-aadadff2f8b3.png)

**Comment by TeamSpen210** [comment]
I'll fix the button-issue by adding some triggers like the Old Aperture ones. It won't actually switch unless both buttons are pressed, and both players are present.

**Comment by Luke18033** [comment]
I'm just wondering, why do you put random words in quotes?

**Comment by Konclan** [comment]
I have confirmed that this still happens

**Comment by Luke18033** [comment]
Seems like this should work correctly, the triggers are there and look like they're set up propery...

**Comment by Luke18033** [comment]
Triggers.

I think I might know what's causing this...

**Comment by Luke18033** [comment]
Okay no it's just been fixed.
