### ISSUE TITLE
[PRL22 Bug] Overgrown Style: Drawbridge is "Unstyled"

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#535]
The Drawbridge is missing a style variant for overgrown
![20160503170128_1](https://cloud.githubusercontent.com/assets/16567080/14999777/f6ef0f52-1150-11e6-8823-e7ed255aaa91.jpg)
I would recommend something like this
![20160503170905_1](https://cloud.githubusercontent.com/assets/16567080/14999952/fd51de32-1151-11e6-8218-8bb477e9bf2d.jpg)
![20160503170923_1](https://cloud.githubusercontent.com/assets/16567080/14999955/007eb86e-1152-11e6-83aa-cfa55100df5e.jpg)
![20160503171003_1](https://cloud.githubusercontent.com/assets/16567080/14999957/02be98c4-1152-11e6-9b2a-8970c42da1f3.jpg)

**Comment by TheReviewers** [comment]
But Gel Wont Work On Those...

**Comment by TeamSpen210** [comment]
In the original Overgrown style, the platform has a 'start reversed' option, which forces the tiles to all be present. That's what I'll do here. I'll also make the tiling actually totally random, so there'll end up being about 17 million combinations overall.

**Comment by TheReviewers** [comment]
@TeamSpen210 literal 17 million?
