### ISSUE TITLE
Remove plateform under Pneumatic Diversity Vent

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#538]
In the PeTI editor model, the pdv has a large plateform under it that is large and blocks a lot of vision

**Comment by TheReviewers** [comment]
*platform

**Comment by LautaroL20** [comment]
Pneumatic Diversity Vent is literally "Out of Control". It really needs a fix.

**Comment by TeamSpen210** [comment]
Other than the model, what's wrong with the original vents?

**Comment by LautaroL20** [comment]
@TeamSpen210 - This: https://github.com/TeamSpen210/BEE2-items/issues/356

**Comment by Luke18033** [comment]
The PDV editor model no longer includes the platform.
