### ISSUE TITLE
Jose's signage has slightly wrong selfillummask

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#542]
The Light/Dark Doesnt Affect The Signage

Light : ![20160429171422_2](https://cloud.githubusercontent.com/assets/17834689/15028964/b6655724-124b-11e6-98ff-62399fd940d8.jpg)

Dark : 
![20160429171422_1](https://cloud.githubusercontent.com/assets/17834689/15028982/c8e4402c-124b-11e6-9d00-20dc623b95c9.jpg)

**Comment by TheReviewers** [comment]
@TeamSpen210 I know you gon say that it has light inside and stuff.... it does look quite wierd to me, not to get darker..

**Comment by TeamSpen210** [comment]
It shouldn't get darker. The signs are lit up internally, the dirt on top is being brightly lit from the back. The black parts shouldn't actually be lit though. Perhaps I'll adjust the `$selfilummask` to make the dirt and black sections non-lit.

**Comment by TheReviewers** [comment]
@TeamSpen210 I Knew you Would Say That...

**Comment by Luke18033** [comment]
It does look a bit weird though that the sign is lit up but isn't lighting up the wall around it...

**Comment by TeamSpen210** [comment]
That's because they don't emit light, the texture is just always illuminated. I might add a dim light to them though.

**Comment by LautaroL20** [comment]
Joes signages bright is fine.

**Comment by Konclan** [comment]
Is this still an issue?
