### ISSUE TITLE
[Suggestion] Re-implement back the missing four "Wall Features"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#543]
There is 4 wall features left to implement on Bee2.4. It is very important to making these to not occupy space behind the wall, like the already implemented ones.

---

ORANGE = NON-IMPLEMENTED. 
GREEN = IMPLEMENTED.

![wall feature](https://cloud.githubusercontent.com/assets/12244376/15038296/e5168778-1278-11e6-8cf7-5dd1ec29d7ca.png)

**Comment by LautaroL20** [comment]
For this, i will want to make 2 aditional new decorative walls (They will be styled), so you can have 6 extra walls in one item, and by using portalable and non-portalable surfaces, they can be under "Button Type".

**Comment by Konclan** [comment]
We've already discussed that there should be a tile editor so you can make any combination of these

**Comment by TeamSpen210** [comment]
Yeah, that obseletes this.
