### ISSUE TITLE
Neurotoxin Timer Idea

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#547]
BEE2.2 had Neurotoxin Timers and Vents. ~~If these were added to the BEE2.4, the timer option should be in the BEE2 program itself, allowing you to type up to 99:59.~~ In the original, it could only be set by intervals of 30 seconds (because the pedestal button timer was being used). However, I want to make a test using Ap Tag's "Dead Test Subject" track, ~~which is (about) 50 seconds long, meaning the track would only play to 10 seconds before the end of the timer if the old option was used.~~ (It would actually work fine, the track is slightly longer than what's normally heard in-game.)

The old idea (sample numbers):
![bee2-idea](https://cloud.githubusercontent.com/assets/19228201/15082990/a70e8838-137f-11e6-9d81-78bec03378f9.PNG)
_The only small issue is that this limits you to only have one neurotoxin timer in the whole map. The original item allows mutiple independent timers._ - @TeamSpen210 

New idea:
The Item Configuration Pane would be used to set different timer values. See BEEmod/BEE2.4#467.

**Comment by TheReviewers** [comment]
Good idea!

**Comment by Konclan** [comment]
This is already going to implemented #95

**Comment by Luke18033** [comment]
@Konclan But nobody mentioned the new timer design.

**Comment by TheReviewers** [comment]
@Luke18033 Good job Luke!

**Comment by TeamSpen210** [comment]
That's a good idea! The only small issue is that this limits you to only have one neurotoxin timer in the whole map. The original item allows mutiple independent timers.

**Comment by Luke18033** [comment]
@TeamSpen210 Yeah, didn't think of that. Maybe there could be an option to switch between old and new timers.

**Comment by Luke18033** [comment]
Also, on vent sould kill the player no matter where they are in the map. More vents could just be added for effect.

**Comment by TeamSpen210** [comment]
I am going to change that, the original system was very confusing.

**Comment by Luke18033** [comment]
I just thought of a good idea. The timer from the screenshot would be replaced with an "Edit Neurotoxin" button. This would open a window where you could add neurotoxin times for the selected pallete, up to 28. Each one could go up to 99:59. Then, in the editor, you use the pedestal button timer to choose which time amount to run (Infinity=time amount 1, 30=time amount 28). This timer will then run in the game. This same idea could be used for a Music Switcher, where you would add music to the list, select one with the timer, and the music will switch when it is activated.

**Comment by TeamSpen210** [comment]
That's doable.

**Comment by Luke18033** [comment]
So, is this being added in the next release?

**Comment by Luke18033** [comment]
@TeamSpen210 So, is this going to be added?

**Comment by Luke18033** [comment]
@TeamSpen210 Another idea, if there are no vents in the map, it becomes and Explosion Timer which makes everything explode when the time runs out. This would work good for Co-op maps, because robots aren't affected by poisons but they are affected by explosions.

**Comment by gamerscruffy** [comment]
Or you could just simply make it use the same timer like the button has. That would be fricken cool.

**Comment by TeamSpen210** [comment]
That's what it normally does. But that one is limited to 30 seconds maximum, so it only let you set values in increments of 30 seconds. Adding it to the app makes it possible to set any value that you like.

**Comment by Luke18033** [comment]
@TeamSpen210 Should I open a separate issue for the edit widget itself on BenVlodgi/BEE2.4, or just leave it as this?

**Comment by TeamSpen210** [comment]
Leave it as is, it's fine.

**Comment by Luke18033** [comment]
The ICP is in BEE2.4 now. You can add this.

**Comment by Luke18033** [comment]
Looks like this is finally being added.

**Comment by Luke18033** [comment]
Turns out this isn't implemented yet, it's still on a separate branch. @TeamSpen210, is it almost ready to merge? I've been wanting this for a while.

**Comment by TeamSpen210** [comment]
It's implemented, but it's missing the 80s styled version, and the Overgrown emitter (not sure what to do with that).

**Comment by ZombiePwner1** [comment]
@TeamSpen210 just apply a rusty overlay to the overgrown emitter not sure how 80's emitter would look tho.

**Comment by Luke18033** [comment]
:D
![image](https://cloud.githubusercontent.com/assets/19228201/25786304/8a46099a-3347-11e7-8ee1-802e1b23218d.png)
