### ISSUE TITLE
Actual 1950s

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#549]
@TeamSpen210 I Think Its A Great Idea To Be Honest.. 1950's Clean Style
The Actual 1950's! The Aperture Sign Will Not Be Scratched.. And I've got some good posters from old aperture edited ( not by me ) to look good as new !

all you need is alot of custom textures :D

**Comment by TeamSpen210** [comment]
Portal Stories: Mel includes a bunch of clean versions of various materials, used for the early inro portions.

**Comment by TheReviewers** [comment]
@TeamSpen210 Please add that, its too epic, ( maybe make a 6 second tram (metro) ride to the map, just to add epicness :D 
Thanks for your efford Teamspen!!

**Comment by Konclan** [comment]
Does Mel have a clean sphere texture, a clean old aperture would be really cool.

**Comment by TheReviewers** [comment]
@TeamSpen210 @Konclan Im Gonna Look for clean spheres!

**Comment by Luke18033** [comment]
@TeamSpen210 New Item?

**Comment by Luke18033** [comment]
Maybe add a stylevar so that the sphere can be unfinished and you can see people building it up above.

**Comment by Konclan** [comment]
I think this is honestly too ambitious and would take way too much work
