### ISSUE TITLE
BTS P1 Style

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#553]
There should be two new P1 styles:

~~The first is Overgrown Portal 1. Most things would look pretty much the same, but more damaged. Some testing elements would spark when activated. Companion cubes would look burnt like in the ending of Portal 2. This style, although it wasn't in P1, would be good for people who liked how P1 looked.~~

The second is P1 BTS. This would look pretty much like the BTS areas from the original P1. Piston platforms would become P1's BTS pistons. I don't really know what else to say, just look at the final parts of P1.

**Comment by TeamSpen210** [comment]
Overgrown isn't really easy to make - there aren't any versions of the P1 textures which are moss/plant covered, so I'd need to make them myself. BTS though is something I'll definitely want to do - Portal 1's BTS is quite different to Portal 2's.

**Comment by Konclan** [comment]
Maybe in the portal bts you can change piston platforms to the portal 1 Pistons that can crush you

**Comment by Luke18033** [comment]
That was what I said!

**Comment by ellingtonvengaboysmuseum** [comment]
overgrown P1 will be hard and would take months of retexturing wall and model textures, good luck!

**Comment by TeamSpen210** [comment]
For that reason I'll probably only do BTS P1 style.

**Comment by Luke18033** [comment]
@TeamSpen210 At some point I might try making some Overgrown P1 textures myself and upload them here, but don't expect that to happen for a while.
