### ISSUE TITLE
Signage does not generate if placed on the same voxel as a laser item

### ISSUE THREAD

**Issue by ColibriP2** [BEEmod/BEE2-items#555]
-the signage 1 dot (time = 3) is not displayed because it is already used by a connection.
I reworked my connections to avoid this, but it disappears at the first opportunity.
In fact I would prefer a sign with figures instead of dice (from 1 to 6 shall be good).

**Comment by TeamSpen210** [comment]
It shouldn't be affected by connection signs at all. The dots do use numbers in Old Aperture and BTS styles, in test chambers though that's where the dot signs were actually used.

**Comment by ColibriP2** [comment]
Presently I have dots 2, 3 and 4 in my map but 1 is already a problem. If I move the item to an other tile, it can display or not. If I continue to play with position/orientation it lead to crash Portal (return to Windows). It was the same with Beemod 2.5 signage item.

**Comment by TeamSpen210** [comment]
Where does it crash? During compile, or in the editor? That'd be strange, Portal doesn't really know anything about the sign counts - it thinks it's just a time delay.

**Comment by ColibriP2** [comment]
It crash in the editor.
In the screen shot, the 1 is visible; put under the laser catcher is good also, but on the same tile as the catcher it not display.
![signagebug](https://cloud.githubusercontent.com/assets/19242607/15096988/2b494996-150e-11e6-96a0-de6dde0ce367.jpg)

**Comment by LautaroL20** [comment]
@ColibriP2 - I use "Gif Cam" when i need to show bugs wich requires in-movement demostration. And just screenshots when its about showing texture errors or such. You can download "Gif Cam", here:

www.bahraniapps.com/apps/gifcam/gifcam.php

**Comment by ColibriP2** [comment]
Thank for the tool LautaroL20.
I clean my Portal 2 cache, reload my BEE2 v4 palette, launch Portal 2, create a new map, put a laser catcher and a 1dot signage on its left and run the map. The signage is not visible. I move the catcher to an other tile, run, and it display. Can you reproduce that?

**Comment by TeamSpen210** [comment]
I know why this happens, I'll change how the logic works to make this work in this case.

**Comment by ColibriP2** [comment]
Thanks!
And what about the reflection cube problem?

**Comment by TeamSpen210** [comment]
I'll fix that.

**Comment by ColibriP2** [comment]
Reflection cube dropper work normally in pr21; but signage are displayed twice now !

**Comment by Luke18033** [comment]
Fixed now?

**Comment by TeamSpen210** [comment]
No.

**Comment by Luke18033** [comment]
Fixed now, with the new tiling system?

**Comment by Luke18033** [comment]
Whoops
