### ISSUE TITLE
Generate inside corners for glass/grating frames

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#558]
If this is something hard to do, close this. Here is a screenshot of what i mean:

![20160508090128_1](https://cloud.githubusercontent.com/assets/12244376/15097775/e2e9697a-14fd-11e6-8dfe-3fe6fc45155a.jpg)

**Comment by Konclan** [comment]
This seems like a bug actually

**Comment by TeamSpen210** [comment]
It's rather difficult to fix unfortunately, which might be why Valve didn't fix it. There are instances for it though.

**Comment by Luke18033** [comment]
Has this been fixed? Pretty sure I saw these appearing properly in a BEE2 map recently.

**Comment by LautaroL20** [comment]
Do you have the link to that BEE2 map? I would like to check it myself once i finish building my new PC and then replicate it in the puzzlemaker.

**Comment by Luke18033** [comment]
I don't remember what map it was.

**Comment by TeamSpen210** [comment]
I haven't fixed this, no.

**Comment by LautaroL20** [comment]
> Luke18033 Said: Has this been fixed? 

Yes, now it is. I thought this would be very complex to solve, but it was finally possible.
