### ISSUE TITLE
Glass panel that won't let lasers go through it

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#559]
A glass pane that won't let lasers go through it. This would be useful for maps with sendificators which want people to see something but not send something through it. I don't know what you would use to differentiate it from normal glass though

**Comment by TeamSpen210** [comment]
I'll probably make this thick, dark-tinted glass or something.

**Comment by LautaroL20** [comment]
This is invalid, since the actual PeTi glass panel don´t let lasers go through it:
![20161010013426_1](https://cloud.githubusercontent.com/assets/12244376/19227345/87f60360-8e8e-11e6-95de-93b68dae67c5.jpg)

**Comment by TeamSpen210** [comment]
This would be a resizable glass item, not the panel variant.

**Comment by LautaroL20** [comment]
Ok, looks like i misunderstood the description.

**Comment by ZipZoptheCat** [comment]
I've seen maps use this exact method with normal glass and rippled texture glass. You can't see through the rippled texture very well, tho. Maybe the blue glass of the panels can be adopted?
