### ISSUE TITLE
Pneumatic Cube Spawner

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2-items#560]
A tube that is placed on any surface that spawns a cube like a dropper, these would connect with the other tubes as well.

**Comment by TeamSpen210** [comment]
That's definitely something I want to do.

**Comment by TheReviewers** [comment]
@TeamSpen210 Isnt that the bts cube dropper?

**Comment by TheDarkBomber** [comment]
@ TheReviewers

No, it is a cube dropper that drops from the Vactube.

**Comment by TheReviewers** [comment]
@TheDarkBomber like in portal 1 when you vactube into a cube dropper?

**Comment by BenVlodgi** [comment]
How would it connect to other tubes?
Technically the regular cube spawner is pneumatic 
I do see the advantage to being able to present a cube to the player anywhere

**Comment by Luke18033** [comment]
@Konclan @TeamSpen210 You can already do this. Just have a cube dropper drop into a vactube and have the cube get spit out the other end.

**Comment by TeamSpen210** [comment]
True, but the item variant would get rid of the redundant dropper model, and allow placing it on walls or floors.

**Comment by Luke18033** [comment]
@TeamSpen210 Yes, that's what I mean, drop the cube into the vactube outside the main chamber, and dispense it out from a wall or floor (or ceiling, but there's not really a point in that).

**Comment by Luke18033** [comment]
How about instead just allow regular droppers to go on walls and floors?

**Comment by Konclan** [comment]
Merging with #662
