### ISSUE TITLE
Merge Vertical Security Door into original item

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#581]
Button Type could be used to change between a regular door and a vertical door.

**Comment by TheDarkBomber** [comment]
There is also an Old Aperture version of Vertical Security Doors as well. But there is already a start reversed toggle on the door item, it changes the orientation.

**Comment by TeamSpen210** [comment]
I'll just add these as a seperate item, or perhaps as a Button Type or something similar.

**Comment by Luke18033** [comment]
Although the first image would be a good BTS door.

**Comment by Luke18033** [comment]
@TheDarkBomber Isn't that what the rotation handle is for? Do you mean it makes the door face inwards instead of outwards?

**Comment by TheDarkBomber** [comment]
Yes.

**Comment by Luke18033** [comment]
You could use start reversed to make it face inwards and barrier type to change it between normal door and vertical security door. :octocat:

**Comment by TheDarkBomber** [comment]
@Luke18033 

Yeah!

**Comment by Luke18033** [comment]
Assuming that's possible anyway...
