### ISSUE TITLE
Merge Save Point and Trigger Autosave

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#592]
Save Point item is not needed as it serves the same function as Trigger Autosave, and just takes up an extra spot on the palette. Save Point should be removed, or merged with Trigger Autosave if it does have a special function that Trigger Autosave doesn't.

**Comment by LautaroL20** [comment]
Well, for some "misterious reason" developers still want to keep both instead of merging in one unique item, even when they works the exactly same. I have posted this before in the past, but they didn´t answered my latest comment, you can check the comments of the old post, here: 

https://github.com/TeamSpen210/BEE2-items/issues/273

**Comment by TheReviewers** [comment]
Spooky!

**Comment by TheDarkBomber** [comment]
@LautaroL20

didn't answered? Don't you mean didn't answer?

**Comment by TheReviewers** [comment]
@TheDarkBomber Does that really matter?

**Comment by LautaroL20** [comment]
@TheDarkBomber - Wops, I just forgot that i must not write two past tense verbs at the same time, thanks for the reminder.

**Comment by TeamSpen210** [comment]
Part of the reason I'm keeping HMW's item around is because of the neat model it has. Maybe I'll alter that autosave to have a differently-sized autosave brush in different orientations, and other things to ensure you're in a safe place before doing the autosave.

**Comment by Luke18033** [comment]
@TeamSpen210 Maybe the save point item could be re-purposed as a visible save point, which would appear as a flag or something.

**Comment by LautaroL20** [comment]
@Luke18033 - If you make it to become visible, I doubt that would fit into the game atmosphere, players will likely going to say "Oh fiddlesticks, what is this thingy?"

**Comment by Luke18033** [comment]
@LautaroL20 Okay then, maybe it could have it as a red circle on the ground, which would turn green when stepped on, and turn yellow when another save point has been activated.

**Comment by TheDarkBomber** [comment]
It should be invisible.

**Comment by Luke18033** [comment]
I'm going to continue to use Trigger Autosave when I use the BEE2 (which is rare now that I'm using hammer) as opposed to Save Point.
