### ISSUE TITLE
New item : Piston Mounted Angled Panel

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#593]
Its a panel on a piston, piston is movable by inputs, and you can choose what angle it is

(i am horrible at explaining)

**Comment by TeamSpen210** [comment]
Ok. When should the panel change angle? How should I interface the 4 panel arms with the single piston?

**Comment by TheReviewers** [comment]
You cant change the panel angle, only the piston platform

**Comment by TeamSpen210** [comment]
Ok, that'd work better - a surface permanently at a certain angle.

**Comment by TheReviewers** [comment]
but the piston can move

**Comment by Luke18033** [comment]
Why can't you also have the angle option from the normal panel item?

**Comment by TheReviewers** [comment]
@Luke18033 You can have the angle option, but you cant change it with connections

**Comment by TheDarkBomber** [comment]
The angle doesn't need to be changed ingame anyway. It can be changed in the editor though.

**Comment by Luke18033** [comment]
@TheReviewers Couldn't it use input A/B?

**Comment by Luke18033** [comment]
> The angle doesn't need to be changed ingame anyway. It can be changed in the editor though.

@TheDarkBomber In Portal 1 Test 18, there is a panel which extends out and then tilts up.

> How should I interface the 4 panel arms with the single piston?

@TeamSpen210 You could use P1 pistons with P2 textures (and unmodified P1 pistons in that style).

**Comment by Luke18033** [comment]
Actually, how about make a custom model which attaches the arm_64_rail models to the piston? You could probably even just make it out of brushes.

**Comment by Konclan** [comment]
Merging with #3882
