### ISSUE TITLE
Missing Icons on Mac

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#594]
On Mac, Dual Autoportal (when you only have one of the two on the palette), Blue Autoportal, Separated Co-op Checkpoint, and probably some other items are missing their icons in the BEE2 program, appearing as a white square.

**Comment by TheDarkBomber** [comment]
this is normal to have missing icons.

**Comment by Luke18033** [comment]
Except for that these icons aren't missing on Windows.

**Comment by Luke18033** [comment]
It's not normal, it is a bug.

**Comment by TheDarkBomber** [comment]
It will be fixed in Release 1 (not pre-release)

**Comment by Luke18033** [comment]
When is Release 1? Every update has been a pre-release!

**Comment by Luke18033** [comment]
Does this still happen? Unfortunately I don't have a Mac to test this on anymore.

**Comment by Luke18033** [comment]
Managed to get BEE2 running on a Mac again, this seems to be fixed.

**Comment by Luke18033** [comment]
This was probably caused by case-sensitive filenames.
