### ISSUE TITLE
Diagonal Faith Plate

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#597]
A Button Type on faith plates to allow 3 variations: Standard rotation, rotated 45 degrees clockwise, and rotated 45 degrees counterclockwise. This rotation would be relative to the direction the faith plate was rotated by the editor.

Currently, even with the BEE2, faith plates with a diagonal placed target will not actually face this way. I'm assuming there's no way for it to be detected automatically (once again a limit of the PeTI, ~something I will want in PMP~), so Button Type seems like the easiest way to do this.

**Comment by TheDarkBomber** [comment]
ok.

**Comment by Luke18033** [comment]
@TheDarkBomber Basically, you're saying that you like the idea.

**Comment by TheDarkBomber** [comment]
@Luke18033 It will make it easier to go diagonally as well if the trigger_catapult is tilted.

**Comment by Luke18033** [comment]
@TeamSpen210 No label?

**Comment by Enterpise** [comment]
If we are lucky, TeamSpen210 will fix most part of the Bee2.4 bugs.....I highly doubt he will have the time to implement all the suggestions we have maded so far for the mod.

**Comment by Sarcastic-Fantastic** [comment]
I mean you can make a faith plate that jumps you diagonally already can't you? Having the actual plate  face diagonal would mess with the whole even square aesthetic surely?

**Comment by Luke18033** [comment]
@Sarcastic-Fantastic But then you won't know if it launches you diagonally or forward...

**Comment by Luke18033** [comment]
@Sarcastic-Fantastic Actually you're right, a good reason for this to be optional (with Button Type).

**Comment by Luke18033** [comment]
And how did @ZombiePwner1 add a label?

**Comment by ZombiePwner1** [comment]
I,Ve got the perms to add labels luke

**Comment by Luke18033** [comment]
@ZombiePwner1 IK, TeamSpen210 told me on gitter.

**Comment by ZombiePwner1** [comment]
Well I am going to help teamspen out with BEEmod.

**Comment by Luke18033** [comment]
Oh okay.

**Comment by ZombiePwner1** [comment]
It's just abit hard since teamspen is moving house soon.

**Comment by Luke18033** [comment]
> Well I am going to help teamspen out with BEEmod

Why haven't you done that yet then?

**Comment by Luke18033** [comment]
We can't use Button Type for this. (I think.) Maybe Start Deployed and Start Reversed? If both were checked it would just face forward.

**Comment by Luke18033** [comment]
Or Cube Type might somehow work.

**Comment by Luke18033** [comment]
This isn't really that useful anyway, it's not too hard to just modify your puzzle to not require a diagonal faith plate.
