### ISSUE TITLE
BTS Transition Entry/Exit Corridors

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#607]
A entry/exit corridor which allows you to transition to/from BTS levels, for making a series of tests.

Exit: It is a hallway with a right turn. The door to the elevator room malfunctions and some wall panels open, across from the first door. There is then a catwalk leading to a set of Vertical Security Doors (like the start/end of BTS levels) and the map ends here.

Entry: Same as Exit, but in reverse. You start in a set of Vertical Security Doors, the one in front of you opening to a catwalk. You have to go up some stairs before reaching the entry corridor (which is also a right turn with the panels across from the door to the chamber) and the panels closing behind you.

Different versions of BTS (Portal 2, Portal 1, and Old Aperture, when they are added) will be used depending on the chosen style (a * means that this style has not been added yet).

P2 BTS: Clean, Original Clean, Overgrown, Reconstructing\*, Wheatley\*, Art Therapy\*

P1 BTS: Portal 1

Old Aperture BTS: 1950s, 1960s, 1970s, 1980s, Prime 1950s\* (#549), Refurbished\*

**Comment by TeamSpen210** [comment]
This is definitely doable. for Old Aperture there shouldn't be any changes, the BTS is usually outside the actual spheres. I'd implement this as two stylevars.

**Comment by Luke18033** [comment]
@TeamSpen210 Why stylevars? Why not entry/exit corridor options?

**Comment by Luke18033** [comment]
No response?

**Comment by TeamSpen210** [comment]
Oh. The corridor option is really for choosing between the 7 entry, and 4 exit corridors Valve selects from. Random means it keeps the originals, otherwise it switches to a certain one. This would be more a seperate option perhaps.
