### ISSUE TITLE
Overgrown Exit - Malfunctioning Fizzler

### ISSUE THREAD

**Issue by bloxxingblocks** [BEEmod/BEE2-items#608]
As seen at the end of the companion cube chamber during Reconstruction, it just opens and closes while leaving particles that quickly disappear. Good for overgrown but should also be available on Clean, BTS and Original Clean

(im not sure where to put requests)

**Comment by TeamSpen210** [comment]
I'm not sure what use this would have.

**Comment by Luke18033** [comment]
Maybe this would be better as a Reconstructing exit corridor option, when the style is added.

**Comment by ZombiePwner1** [comment]
A malfunctioning fizzler would be a nice feature but as TeamSpen said not sure what use it would have.

**Comment by Luke18033** [comment]
@ZombiePwner1 Probably as an exit corridor option on Overgrown
