### ISSUE TITLE
[PRL22 Bug] Cross-Wall, Centered, Half-Wall and Surface Marker Model does not "Remain in the same position" once it is moved to a different surface.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#610]
This does not affect the final map build result, only happens when using the PeTi Editor, its kinda annoying to not being able to set its model in the right position when its placed on walls. It remains "Horizontal" instead of "Vertical":

![20160710193540_1](https://cloud.githubusercontent.com/assets/12244376/16716621/2b26bbc8-46d8-11e6-9fd8-0103b87e8237.jpg)

**Comment by Luke18033** [comment]
lol

**Comment by LautaroL20** [comment]
Cross-Wall, Centered, Half-Wall and Surface Marker Model does not "Remain in the same position" once it is moved to a different surface.
