### ISSUE TITLE
 BTS Timed Pedestal Button is missing press sound

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#621]
When you hit a timerized button pedestal, its missing its push sound effect.

![20160717211227_1](https://cloud.githubusercontent.com/assets/12244376/16904415/1b1d02ca-4c6c-11e6-89eb-e159d87f28a1.jpg)

**Comment by Luke18033** [comment]
@LautaroL20 Why did you add an image? You should have added a video?

**Comment by Luke18033** [comment]
Wait, look at the button...

**Comment by LautaroL20** [comment]
@Luke18033 - On this case, the image is just entirely decorative, only to show wich pedestal button have the bug i am reoprting. Since there are 2 variants wich looks different. 1 wich is static, and the second wich is timed.

**Comment by ZombiePwner1** [comment]
Lautaro come online.

**Comment by Luke18033** [comment]
Fixed?

**Comment by LautaroL20** [comment]
Good question, i think we both should give a test to general Bee´s stuff soon thru all Styles. Last time i´ve tested Beemod was on december 2018. However, this seems to be a bug from 3 years old, but considering that the BTS Style obviously is not in the Spencer´s priorities, the issue could perfectly live up to this day.
