### ISSUE TITLE
Style suggestions.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#623]
These are suggestions for 2 styles I came up with. Let me know what you people think.

Overgrown + art therapy

Overgrown + BTS

**Comment by Luke18033** [comment]
There are only 2-3 overgrown BTS areas, but those resources might be enough for TeamSpen210 to add the style.

Art therapy overgrown wouldn't be much different from normal Overgrown, not sure how useful that would be.

**Comment by ZombiePwner1** [comment]
Well i figure it would be nice.

**Comment by Konclan** [comment]
I don't think mixing styles is a good idea, most styles are messy as they are but trying to do this would take more work than what it's worth IMO
