### ISSUE TITLE
Turret crates

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#624]
A crate which would have a turret inside it. They are found through out the BTS areas and the excursion funnel course in coop. It is like the caged turret but if you were to destroy the turret you would have to put the laser in front of the crate.

**Comment by Luke18033** [comment]
What do you mean?

**Comment by ZombiePwner1** [comment]
It's found through out the BTS areas of the single player mode and coop mode excursion funnel course. I'll show a screenshot. 
http://steamcommunity.com/sharedfiles/filedetails/?id=732147070

**Comment by Luke18033** [comment]
@ZombiePwner1 File does not exist.

**Comment by ZombiePwner1** [comment]
Oh that would be because i accidently put it on friends view.

**Comment by ZombiePwner1** [comment]
Okay there. Look at it now

**Comment by Luke18033** [comment]
Maybe instead just have an empty crate which a turret or another object can be placed in.

**Comment by ZombiePwner1** [comment]
That could work too. And these crates could be perhaps the cages for caged turrets in BTS style.

**Comment by Luke18033** [comment]
This isn't really any different than just placing a turret recessed one block into the wall, maybe these could be added as a BTS auto decoration used in that case, doesn't really need to be its own item though.
