### ISSUE TITLE
Use actual wires to connect items in BTS.

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#626]
Wires would still generate in straight(ish) lines, because of how antline generation works.

**Comment by TeamSpen210** [comment]
This would be nice! I'll need to do some analysis to figure out what order antlines are connected to each other though. That'd also be useful for fixing some bugs in the layout of P1 antlines (square straight sections are sometimes turned 90°).

**Comment by ZombiePwner1** [comment]
Wires are a good idea for BTS can't wait to see them.

**Comment by Luke18033** [comment]
Why are the current BTS antlines blue in the editor, even though they're yellow in-game?

**Comment by ZombiePwner1** [comment]
I didn't even see that idk how I could not have seen that.

**Comment by TeamSpen210** [comment]
I can't fix that, unfortunately. The texture is greyscale actually, then tinted blue by the game. That's used so it can turn orange when your choosing which connection to delete.

**Comment by Luke18033** [comment]
I actually saw it on #619 in the image.

**Comment by ZombiePwner1** [comment]
Makes sense.

**Comment by Luke18033** [comment]
@TeamSpen210 Why Portal 1?

**Comment by TeamSpen210** [comment]
Implementing this would allow fixing a bug with P1 antlines, or possibly replace those entirely with actually thin ones.

**Comment by Luke18033** [comment]
Ah okay.

**Comment by Luke18033** [comment]
@TeamSpen210 Why can't you use thin antlines in Portal 1 now?

**Comment by TeamSpen210** [comment]
Currently all the compiler does is find/replace to change the textures. To make them small it'd need to figure out where they touch, so it can resize them so they still connect to each other. That's especially tricky with the corners, since depending on the rotation it'll be offset wrong.
