### ISSUE TITLE
[New item] Piston mounted pellet launcher and catcher.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#627]
Lasers could be added to this as well but the pellet catcher and launcher would go well if the laser doesn't

**Comment by Luke18033** [comment]
Why enhancement? New item makes the most sense.

**Comment by ZombiePwner1** [comment]
Sorry kinda hard to add stuff on an iPad.

**Comment by TeamSpen210** [comment]
Which way would it face? Forwards, 90 degrees?

**Comment by ZombiePwner1** [comment]
It can face any direction on walls ceiling floor.

**Comment by ZombiePwner1** [comment]
Since a few Pistons in P1 have pellet launchers on them.

**Comment by TeamSpen210** [comment]
In relation to the piston arm.. Pointing away, or sideways?

**Comment by ZombiePwner1** [comment]
I guess it can point anywhere.

**Comment by ZombiePwner1** [comment]
This would fit extremely well for P1 style but I'm not sure about other styles.

**Comment by Luke18033** [comment]
I think you mean something like this:
![20160726073725_1](https://cloud.githubusercontent.com/assets/19228201/17142180/04decefa-5304-11e6-987e-9eca97996660.jpg)
Not sure how well that would work with catchers though.
Also maybe make it toggleable on/off by inputs, maybe A/B to separately control the pellet launcher and the rotation.

**Comment by ZombiePwner1** [comment]
Perhaps there can be like a special kind of piston for the catchers.

**Comment by ZombiePwner1** [comment]
I am planning to make this type of item my self but i would need to copy all of the catcher and launcher properties in since both items have a lot of properties.

**Comment by Luke18033** [comment]
This should be implemented as two separate items:
- A rotating pellet launcher, with input A/B to control rotation/firing pellets. See image above.
- A piston platform with a panel on the top, and a pellet launcher mounted on that. This would also use Input A/B, with Input A controlling movement between positions and Input B controlling firing of pellets.

**Comment by Konclan** [comment]
Merging with #3882

**Comment by Luke18033** [comment]
We'd probably actually still want to have this as a separate item, since the rotating variant needs dual inputs and a slightly different setup.

**Comment by Luke18033** [comment]
Unless we want to make it just a "rotating pellet launcher" item, then you can mount that on top of a piston platform to get the equivalent of this?

**Comment by Konclan** [comment]
Having a rotating pellet item like a rotating portal gun sounds better than having it exclusively piston mounted
