### ISSUE TITLE
Automatically parent Caged Turrets to piston platforms they are on top of

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#629]

**Comment by Luke18033** [comment]
How would the piston part be useful? Just put a caged turret on a static piston platform.

**Comment by ZombiePwner1** [comment]
The piston can either go up or down.

**Comment by ZombiePwner1** [comment]
Have a trigger connected to the pistons and once activated caged turrets will pop out.

**Comment by Luke18033** [comment]
@ZombiePwner1 But you can already do that, put a caged turret on a piston platform and change the position.

**Comment by TeamSpen210** [comment]
That's what I'd do, if anything.

**Comment by Konclan** [comment]
Merging with #3882
