### ISSUE TITLE
Piston platform mounted pedestal button

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#633]
Saw this in a custom map.

**Comment by Luke18033** [comment]
This would be nice to implement, as well as angled panel pedestal button.

**Comment by ZombiePwner1** [comment]
An angled panel pedestal button that will be interesting to see as well.

**Comment by Luke18033** [comment]
How about instead just give the pedestal button `CanAnchorOnBarriers`.

**Comment by Konclan** [comment]
Merging with #3882
