### ISSUE TITLE
[PRL21.5 Missing Variant] Portal 1 Coop Checkpoints are unstyled

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#640]
![20160729215713_1](https://cloud.githubusercontent.com/assets/12244376/17267111/75898786-55d8-11e6-9cbc-b1c95e4783e6.jpg)

**Comment by Luke18033** [comment]
Bump

**Comment by LautaroL20** [comment]
I think this is fixed. Let me give it a quick check.

**Comment by TeamSpen210** [comment]
It is.
