### ISSUE TITLE
[PRL21.5 Bug] Overgrown Style Co-Op : P-Body is missing its "Portal Gun"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#644]
![20160729223806_1](https://cloud.githubusercontent.com/assets/12244376/17267428/77503a86-55df-11e6-9862-02c73b6f0c2f.jpg)

**Comment by ZombiePwner1** [comment]
The portal gun is there it's just invisible.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Yes, wich is still a bug.

**Comment by Konclan** [comment]
Seems to be working now
![20190830130341_1](https://user-images.githubusercontent.com/16567080/64042029-9a557b80-cb26-11e9-8373-e61437ee737e.jpg)
