### ISSUE TITLE
[PRL21.5 Bug] CO-OP from Overgrown Style "Gets Visual Leaks" 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#645]
![20160729224415_1](https://cloud.githubusercontent.com/assets/12244376/17267503/6b0d4988-55e1-11e6-8bc8-c50f4e8a7212.jpg)

**Comment by ZombiePwner1** [comment]
Are the light strips the only thing that get leaked?

**Comment by LautaroL20** [comment]
No, other things gets leaked aswell when on CO-OP mode.

**Comment by Konclan** [comment]
Not sure whats going on here..

**Comment by LautaroL20** [comment]
This happened with Beemod in 2016, it was most likely an overgrown corridor leaking somewhere which is probably fixed now.

**Comment by Konclan** [comment]
If it's not we'll just open a new issue with better information
