### ISSUE TITLE
[PRL21.5 Bug] Original Clean Style CO-OP: P-Body Screen Gets "Totally Leaked" making it impossible to control her

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#646]
![20160802203005_1](https://cloud.githubusercontent.com/assets/12244376/17349090/76310706-58f1-11e6-937d-ebaabfa178dc.jpg)

![20160729225156_1](https://cloud.githubusercontent.com/assets/12244376/17267546/6c19a4b0-55e2-11e6-9167-38f71242038a.jpg)

**Comment by ZombiePwner1** [comment]
Note: p-body is a female.

**Comment by ZombiePwner1** [comment]
Ummmm i just tested this on original clean and i'm able to control P-body perfectly fine. This is probably due to a leak somewhere in ur map.

**Comment by LautaroL20** [comment]
For some reason, i have been experiencing some leaks when using CO-OP mode for Overgrown and Clean Styles. I dont know if it may be due to the newer fixed "Compiler.zip" that TeamSpen210 gave me.

**Comment by ZombiePwner1** [comment]
Maybe cause I'm using the prl21 fix and I can control her just fine.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - These leaks are happening with all the latest fixes for the current pre-release. I dont know why you don´t get leaks.

**Comment by LautaroL20** [comment]
I have been switching from Style to Style loading the same map file with Bee2.4, idk if this could break something causing those leaks...

**Comment by ZombiePwner1** [comment]
There is clearly something wrong with ur version then.

**Comment by ZombiePwner1** [comment]
Have you tried moving p-body around?

**Comment by LautaroL20** [comment]
@ZombiePwner1 - As the title says, it is impossible to get control over P-Body character.

**Comment by ZombiePwner1** [comment]
Does this happen at all in any other styles?

**Comment by TeamSpen210** [comment]
Try noclip. It looks kind of like P-Body spawned inside a wall.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Still impossible. It doesn´t have to do with a wrong respawn, it is a very weird leak that is affecting Clean as well as Overgrown Styles, and i am sure i have installed everything correct before report any of my bugs. I have taken a screenshot with the usage of "noclip", as you can see below:

P-Body character is only visible trhough the screen from Atlas:

![20160802203005_1](https://cloud.githubusercontent.com/assets/12244376/17349082/6c1fa8e4-58f1-11e6-8ea0-6783eb1318bf.jpg)
