### ISSUE TITLE
Separated Co-op checkpoint is missing style variants

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#647]
![20160729223911_1](https://cloud.githubusercontent.com/assets/12244376/17267616/146f02da-55e4-11e6-96ab-304f46a3f75d.jpg)

**Comment by Luke18033** [comment]
@LautaroL20 Are those cold light strips (in the test, not the checkpoint)? If so, how did you get them in BEE2.4?

**Comment by ZombiePwner1** [comment]
It's a custom add on lautaro has made I even have them for bee2.5.5

**Comment by LautaroL20** [comment]
@Luke18033 - I have managed to get the three Light Strips variations in one item on Bee2.2.5, and ive re-skin the PeTi editor model. Here is a screenshot. As for the Cold Light working on Bee2.4, i had to replace the Warm Light for the Cold Light since i am not familiarize with the txt codes manipulation inside the pakages. 

![cold light strip 2](https://cloud.githubusercontent.com/assets/12244376/17280690/6143d284-576a-11e6-8d81-8a267380e1ed.jpg)

**Comment by ZombiePwner1** [comment]
The custom cold light strip can be easily added to bee2.4 with the right stuff. I got lautaro to help me add them to aperture tag.

**Comment by TeamSpen210** [comment]
One problem is that the Button Type property you're using here is not compatible with the Light Strip item class. That means it won't get the correct collisions, so you can intersect lights or have antlines pass through them.

**Comment by ZombiePwner1** [comment]
Yeah lautaro made it so that doesn't happen.

**Comment by Luke18033** [comment]
Who cares about collisions? It's not like intersecting light strips will cause any major issues.

**Comment by TeamSpen210** [comment]
Antlines, and if I make them embed in Clean style it won't work....

**Comment by Luke18033** [comment]
I think BEE2.2 might already have an Overgrown separated checkpoint variant which can be ported over.

**Comment by ZombiePwner1** [comment]
@Luke18033 Yes but the problem is the overgrown checkpoint has no plants in it.

**Comment by Nikita74Russian** [comment]
@ZombiePwner1 There's no bee 2.5, there's only bee 2.2.5 and 2.4.

**Comment by LautaroL20** [comment]
@Nikita74Russian - Congratz, you have discovered America!

**Comment by Luke18033** [comment]
See #2263

**Comment by Luke18033** [comment]
Reverted it back to this, better than having a missing instance.

**Comment by LautaroL20** [comment]
Why did you delete a comment? I am almost sure it was not anything inapropiate, however since this issue is old, i can´t really remember. But if so, i would like to see evidence of it. 

Also, who or what is it causing on many comments to being hidden by marked as off-topic?

**Comment by Luke18033** [comment]
The deleted comment was a reply to a user who had been banned. It no longer made sense out of context, so I figured I might as well just delete it. I hid those other comments because we were just talking about the cold light strip, it wasn't really related to the actual bug.
