### ISSUE TITLE
Angled panel-mounted auto portal

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#650]

**Comment by TeamSpen210** [comment]
For this, I think I'll want to make it unmoving only.

**Comment by Luke18033** [comment]
Why just orange?

**Comment by ZombiePwner1** [comment]
It can be blue if there is a start reversed option or something but orange feels right for it unlike blue.

**Comment by Konclan** [comment]
Merging with #3882
