### ISSUE TITLE
[New item] Conveyor belt crusher

### ISSUE THREAD

**Issue by Shooba** [BEEmod/BEE2-items#653]
(My steam name is Maybe I am an Eevee Actually)

Alright, so it would be like the crusher from chapter 9, on the conveyer belt, it crushes about every second, and could be a nice touch. We could use this as a good gel thing to show how fast gel is etc.

**Comment by ZombiePwner1** [comment]
Interesting and if you want a defective turret item edit the turret instance and change it's model to skeleton and make sure allow defective models is yes.

**Comment by ellingtonvengaboysmuseum** [comment]
this type of crusher is the smaller model.

**Comment by TeamSpen210** [comment]
This is identical to normal crushers.
