### ISSUE TITLE
[Bug] Paint gun does not work in all styles in AT coop.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#654]
There is missing entities controlling the paint guns behaviour so therefore the paint gun will not work at all even if you pass through a activation fizzler.

**Comment by TeamSpen210** [comment]
Before adding the gun, I need to decide how some things should work in Coop (and their appearance):
* Fizzlers
* Gel Fields
* Exit Fizzlers (which need to deactivate the gun, and fizzle portals).

**Comment by ZombiePwner1** [comment]
If anyone else uses bee2 for aperture tag replace the clean coop spawn room with AT's one to get the paint gun working in clean styles.
