### ISSUE TITLE
[New item] Magnet field

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#656]
A custom fizzler that pulls any object to it in close range.

**Comment by TheDarkBomber** [comment]
This may not be possible, the closest thing to magnetism in Source, is the player picking objects up.

**Comment by ellingtonvengaboysmuseum** [comment]
this can't be done easily...

**Comment by TeamSpen210** [comment]
It could be done with two `trigger_push`es on either side of the field.

**Comment by ZombiePwner1** [comment]
There could be a reversed option aswell that pushes objects back when they try to get in contact with the field.

**Comment by TeamSpen210** [comment]
That would be actually quite interesting, especially if you can adjust the strength - so you'd need to fling through it to get past.

**Comment by ZombiePwner1** [comment]
Players wouldn't get affected by the field but objects will if the player got affected they would most likely get stuck since the trigger push would be too strong and portals would be impossible.

**Comment by ZombiePwner1** [comment]
This item would work similar to the magnetic repulsors in batcature laboratories custom maps.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 The reversed version color of of the field should be red and green mixed together.

**Comment by Konclan** [comment]
I don't see the use for this, funnels, faithplates, pistons, panels, etc all move objects.

**Comment by Luke18033** [comment]
There are a few different magnet implementations which I think could be interesting to add, but none of them are fizzlers.
