### ISSUE TITLE
Customisable observation rooms.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#659]
These types of observation rooms are seen throughout portal 1 and are a really nice touch.
Seeing them in portal 2 would be awesome. Chamber this observation room is seen in is test chamber 15

**Comment by TeamSpen210** [comment]
What I think I'd like to try and do is make a customization observation room, which would be a 1x1 section you place next to each other, then generating a random room design.

**Comment by Konclan** [comment]
#1165
