### ISSUE TITLE
Overgrown Track Platform unstyled

### ISSUE THREAD

**Issue by mario2582** [BEEmod/BEE2-items#66]
wrong type of track platform in overgrown

![preview0009](https://cloud.githubusercontent.com/assets/11165643/8559952/eb928222-24e0-11e5-9586-dfb4a0643589.jpg)
![20160821003845_1](https://cloud.githubusercontent.com/assets/12244376/17835233/da6ef67e-6738-11e6-9c0e-29bf8e2c3f6e.jpg)

**Comment by ellingtonisland** [comment]
will be fixed eventually

**Comment by ZombiePwner1** [comment]
This is a duplicate of https://github.com/TeamSpen210/BEE2-items/issues/715.

**Comment by Luke18033** [comment]
@ZombiePwner1 - Nope, other way around.

**Comment by Konclan** [comment]
Holy crap guys a little communication never hurt anybody, just stop closing and opening things without saying something first

**Comment by Luke18033** [comment]
Also note the Clean tiles around the track.

**Comment by ZombiePwner1** [comment]
@Luke18033 Actually this is a duplicate since @LautaroL20's post wa smade in 2016 this was in 2015 lmao.

**Comment by Konclan** [comment]
This has been fixed
![20190828200839_1](https://user-images.githubusercontent.com/16567080/63902526-af6bc680-c9cf-11e9-93ef-49fad35da05f.jpg)
