### ISSUE TITLE
Breakable Vactubes

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#661]
A tube that drops a cube when destroyed. Seen in one of the portal 1 BTS areas. This could be useful in maps with no cube droppers allowed and this would be the only source.

**Comment by TeamSpen210** [comment]
This would just be a breakable pipe, which then is connected to a tube line continually spawning cubes. One slight issue is that it can't be done the same way as Valve's breaking tubes (those are some premade for a particular area), so it won't look as good.

**Comment by TeamSpen210** [comment]
See #662.

**Comment by ZombiePwner1** [comment]
Alright well it's good enough a long as it's something breakable then it's good.

**Comment by ZombiePwner1** [comment]
I might beable to make my own tube that drops cubes once broken.

**Comment by Konclan** [comment]
Merging with #662
