### ISSUE TITLE
[New item] Speaker.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#669]
A speaker from aperture tag which can hold the music source. Wouldn't really have anything to do with gameplay could just be a music source item.

**Comment by LautaroL20** [comment]
For what styles would this new item be used? Music already plays as background when you are playing if you have choosen a song to build it, so this item would detract the background music feature....

**Comment by ZombiePwner1** [comment]
This item could remove the background music if compiled.

**Comment by Byzarru** [comment]
In Ap Tag, it makes the background music louder. It's a purely aesthetic item.
![20161230135535_1](https://cloud.githubusercontent.com/assets/22107242/21572929/a45fc454-cea4-11e6-8004-f897bd4b1bce.jpg)

**Comment by TeamSpen210** [comment]
It actually produces the music from the speakers, so it's loudest there.

**Comment by Luke18033** [comment]
I assume placing this item in the map would disable global music?

**Comment by Luke18033** [comment]
You'd need to make a custom Overgrown skin. In Old Aperture I think the music plays from the loudspeakers, so you could just make it an embedded loudspeaker covered by a grating. You'll also want to make a standing variant for use with partial blocks, and add a stylevar to play music out of the normal loudspeakers.
