### ISSUE TITLE
Portalable and Non-Portalable Track Platform

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#674]
This item would do a good usage from the "Conversion gel" and "Blue Gel".
![Image](http://p1.bpimg.com/4851/6e72bc55d20b5d7a.png)

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Bee 2.2.5 Never had this item, do not get confused with the "Piston Platafrom" wich is another thing.

**Comment by ZombiePwner1** [comment]
Oh whoops thought i was piston platform hehehe my bad :/

**Comment by LautaroL20** [comment]
It seems you didn´t read the post title then ;)

**Comment by TeamSpen210** [comment]
Now implemented
