### ISSUE TITLE
Use dirty elevator model in Overgrown

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#675]
This would look abit similar to the portal stories Mel elevator.

**Comment by TeamSpen210** [comment]
That's a model made by Camben I think, I'll probably add it as a random variant.

**Comment by LautaroL20** [comment]
I have the styled elevator files, but there is a small complaint with it. The MDL File is reading their materials from `portal2_dlc1\materials\models\elevator` so i was thinking you could recompile the model to make it read materials from `Portal 2\bee2\materials`, or add a new logic on the Beemod to send and pack models from other places too.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Remember i gave u the files.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Remember that the model was maded by the Portal Stories: Mel´s Team.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Yes i know that and i made sure to ask for permission to use it.

**Comment by TeamSpen210** [comment]
It's not actually from Mel, the author released it earlier (but I think he also worked on Mel itself). ThinkingWithPortals is dead, so we can't check that version.

**Comment by LautaroL20** [comment]
Now implemented for next release. But we still need to create the random variants for this...
