### ISSUE TITLE
[New item] Moving piston mounted energy pellet.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#678]
A energy pellet on a moving piston.

**Comment by TeamSpen210** [comment]
Can you be more specific?

**Comment by ZombiePwner1** [comment]
It's like the panels in in the neruotoxin level with those moving portable panels a high energy pellet could be placed on those.

**Comment by Endermage77** [comment]
I think he means the HEP from P1 Chamber 18.

**Comment by ZombiePwner1** [comment]
@Endermage77 This post is 2 years old lmao.

**Comment by Endermage77** [comment]
Whoops!
Oh dearie me
I really should be paying more attention to those dates before posting
(No sarcasm)

**Comment by Konclan** [comment]
Merging with #3882
