### ISSUE TITLE
[PRL21.5 Bug] 70´s Old Aperture: Random CO-OP Exit becomes "Nodraw" when it closes

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#680]
I was not able to record a GIF since the damned "Gforce Experience" is not working for some reason. But ive taked a screenshot:

![20160810234953_1](https://cloud.githubusercontent.com/assets/12244376/17577559/a4cc3512-5f55-11e6-9603-e66d4ad19662.jpg)

**Comment by ZombiePwner1** [comment]
A world portal bug most likely.

**Comment by Konclan** [comment]
This has been fixed
![20190830125639_1](https://user-images.githubusercontent.com/16567080/64041640-a4c34580-cb25-11e9-9b19-3378883a484a.jpg)

**Comment by LautaroL20** [comment]
Nice!
