### ISSUE TITLE
[PRL21.5 Bug] Portal 1 Style: Cubemaps are not being packed when building maps using CO-OP

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#684]
![20160811002211_1](https://cloud.githubusercontent.com/assets/12244376/17577941/b824bdb0-5f59-11e6-8626-3c3633fc4445.jpg)

**Comment by ZombiePwner1** [comment]
I've already reported this.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Link? I remember being the first one reporting that 70´s and P1 does not pack cubemaps.....

**Comment by ZombiePwner1** [comment]
Look at 622

**Comment by LautaroL20** [comment]
There is no 622 issue....

**Comment by ZombiePwner1** [comment]
https://github.com/TeamSpen210/BEE2-items/issues/622

**Comment by ZombiePwner1** [comment]
Check that.

**Comment by ZombiePwner1** [comment]
This is just a duplicate issue.

**Comment by LautaroL20** [comment]
That 622 issue is a duplicate of another bug report wich is #284. I just splitted it in two parts.

**Comment by ZombiePwner1** [comment]
Yes but it's the same with the env_cubemaps.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Even the user Luke18033 added the "Duplicate lavel" to your 622 issue.
