### ISSUE TITLE
Separated CO-OP Checkpoint´s Doors "Interfere with other items"

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#688]
http://steamcommunity.com/profiles/76561198227960928/screenshot/446240580942821523

**Comment by ZombiePwner1** [comment]
Fizzler on the edge of a block and checkpoint is on the other side how is that a error placement?

**Comment by LautaroL20** [comment]
It looks like the separated Co-op checkpoint´s doors are interfering with items. This may be easy to fix.

**Comment by TeamSpen210** [comment]
They might be set for the wrong side of the block, I'll have to check.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 This bug is extremely annoying in aperture tag since i want to place the paint gun fields at the edge but i can't due to this issue.

**Comment by LautaroL20** [comment]
Ill take a look into this as soon as i finish re-fixing retro static panels.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 This still hasn't been fixed?

**Comment by Luke18033** [comment]
Still an issue?

**Comment by LautaroL20** [comment]
No. And it even supports fizzlers being at the middle of the block now. Who knows when it got fixed though...
