### ISSUE TITLE
[Bug] Stairs using clean version in BTS.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#691]
![20160815174539_1](https://cloud.githubusercontent.com/assets/18079316/17661673/2a594c72-6313-11e6-831a-2fd1dc64f7e2.jpg)

**Comment by TeamSpen210** [comment]
I don't really have plans for this, I'd welcome suggestions for designs if anyone has them (static and non-static).

**Comment by Luke18033** [comment]
The static version is styled now. I don't know what the non-static version should be. Maybe just the static version, but with the ability to retract the individual steps into the ground. It's animations would be similar to P1 stairs.

**Comment by CaliMari** [comment]
What if you only changed the panel texture on the top of the stairs?

**Comment by ZombiePwner1** [comment]
The panels texture we can change easily but the stairs themselves however is going to be tricky.

**Comment by Luke18033** [comment]
We can change them both easily, the problem is what do we change them to?

**Comment by CreepiX987** [comment]
Maybe just one big panel which gets raised from the floor by a piston?

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
