### ISSUE TITLE
[Bug] Custom fizzlers are missing security line underneath them as well as missing their security line next to their model. BTS.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#698]
Use a normal fizzler as an example.

**Comment by TheDarkBomber** [comment]
It's a missing item variant.

**Comment by GiovanH** [comment]
Just pulled this up and it doesn't look like any of the fizzlers have security lines anymore. 

![2020-08-18 18_21_38-PORTAL 2](https://user-images.githubusercontent.com/6759280/90574908-b9a64800-e17f-11ea-918d-0eb1e4bcb559.png)

**Comment by FrozenDragon0** [comment]
Nice my old issue from 2016 which I thought was fixed but it seems not.

**Comment by GiovanH** [comment]
I mean, it's *consistent* now. I don't know whether removing the caution lines is a separate bug or a design decision.

**Comment by FrozenDragon0** [comment]
@GiovanH Pretty sure it's a bug. Besides I liked those caution lines, Adds some nice detail to the fizzlers.

**Comment by TeamSpen210** [comment]
It's a bug, I had to rewrite the code for them, but didn't do it properly. The rules for when overlays work seems really inconsistent.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
