### ISSUE TITLE
[Bug] Overlays are visible behind the exit door in 1980's coop.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#700]
![20160816192233_1](https://cloud.githubusercontent.com/assets/18079316/17697388/2dd62dfa-63e7-11e6-88ef-ff3bfc8e58b7.jpg)

Look on P-Body's screen.

**Comment by LautaroL20** [comment]
Ehmm could you be more specific, maybe making a "Red Circle" highlighting the bugged place on Paint?

**Comment by ZombiePwner1** [comment]
You can Cleary see the doors overlay on p-body's screen.

**Comment by LautaroL20** [comment]
You are talking about the red sphere that is in the metal door?

**Comment by ZombiePwner1** [comment]
No it's the 2nd door after the first look on the sides.

**Comment by TeamSpen210** [comment]
It's the door frame, for some reason it's not visible so you can see the door sides inside the wall.
