### ISSUE TITLE
Ping sensor

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#702]
This item would not be compatible with cubes, only ping tools will be able to activate it:

- With the use of **ButtonType**, we could implement three variants for different situations like: Orange for P-Body only, Blue for Atlas only and grey or a neutral colour for both players.

- An optative timer property would allow configuring the amount of time the output would stay active, being infinite, the way to disable this option.

- In SP, this would constantly blink between blue and orange, being unusable in that mode.

![20160817003342_1](https://cloud.githubusercontent.com/assets/12244376/17724090/8614c868-6415-11e6-842f-325743b8bc48.jpg)

**Comment by ZombiePwner1** [comment]
Good idea I didn't even bother thinking about this one. This would be useful for puzzle maker race maps.

**Comment by Luke18033** [comment]
*Copied from duplicate issue:*

This would be an item which would output when a Co-op player pinged it. It would appear as a 64x64 unit pad in the center of the voxel, with a blue0 target on it, which would turn orange when active. A timer property would allow configuring the amount of time the output would stay active. In SP, this would constantly blink between blue and orange, being unusable in that mode.

**Comment by Luke18033** [comment]
This should also have "fake 5-positioning" as I call it, using 8-positioning and special model/instance positions, so that it behaves like a 5-way handle.

**Comment by HelloIamapersonthatisalive** [comment]
I knew I wasn't the only one wanting this!

**Comment by LautaroL20** [comment]
I´ve got some ideas for this item. Instead of having this item working only for both players, with the use of ButtonType, we could implement three variants for different situations like: Orange for P-Body only, Blue for Atlas only and grey or a neutral colour for both players.

Added to the issue´s description.

**Comment by Endermage77** [comment]
It's just occurred to me that the single player is capable of pinging.

I don't know why you can, but that would mean it could be reasonable to give single-player compatibility to this item.

**Comment by LautaroL20** [comment]
As far as i know, the only mode that does have pinging tools is the cooperative. So, i don´t think this item would work in SP.

**Comment by ZombiePwner1** [comment]
@Luke18033 There is a hidden ping menu that was mean't for the PeTI maps and how they would be rated, This menu has been unused however and can be accessed both in coop and in SP. However it's unfinished as activating it in singleplayer leaves it on your screen with no way to get rid of it.

**Comment by Luke18033** [comment]
I know about that, that's not what we're talking about. Endermage was implying that the normal ping menu can be used without issue in SP.

**Comment by ZombiePwner1** [comment]
I doubt it I think he is misunderstanding.

**Comment by Konclan** [comment]
Gonna leave this item for UCPs to implement.
