### ISSUE TITLE
[PRL21.5 Bug] Overgrown Style: Chamberlock is "Unstyled" 

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#703]
![20160817151905_1](https://cloud.githubusercontent.com/assets/18079316/17727790/267d6990-648e-11e6-9f3e-3f0a25af638a.jpg)

![20160817152336_1](https://cloud.githubusercontent.com/assets/18079316/17727869/a068a09e-648e-11e6-8465-35c1897930dd.jpg)

**Comment by ZombiePwner1** [comment]
@LautaroL20 there's no need to add "and it uses clean tiles" in the title if it's unstyled then it's clean so no need to add that.

**Comment by LautaroL20** [comment]
The "Clean White Tile" you see in the first screenshot is being generated independently from the chamberlock item. You can have the Styled VMF file, but it will still generate the clean tile if the compiler is not fixed. 

As an example of this is the "Light Strip", wich the wall where it is placed is generated by the compiler and not for the item itelf.

**Comment by ZombiePwner1** [comment]
I will check the VMF instance once I get home from hell.

**Comment by TeamSpen210** [comment]
Actually, the door frame is an instance too. I should go convert it to a template though, so it randomly chooses different textures.

**Comment by Luke18033** [comment]
Fixed now?

**Comment by TeamSpen210** [comment]
It is now.
