### ISSUE TITLE
80´s Old Aperture´s Piston Platform is being packed as a "Mysterious Brown Texture" for people who do not have Bee2.4 Installed

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#705]
![20161122222113_1](https://cloud.githubusercontent.com/assets/12244376/20548484/92a50496-b102-11e6-8226-afcd90efd46c.jpg)

**Comment by LautaroL20** [comment]
Ill probably test into this to see if its already fixed.

**Comment by LautaroL20** [comment]
Nope, this still occurs. And now it looks as a brown texture:

![20161122222113_1](https://cloud.githubusercontent.com/assets/12244376/20548484/92a50496-b102-11e6-8226-afcd90efd46c.jpg)

**Comment by ZombiePwner1** [comment]
It's using the wooden texture but squeezed together.

**Comment by LautaroL20** [comment]
It's probably a bug related to the "info.txt" which is supposed to contains the coordinates to pack in the textures.

**Comment by TeamSpen210** [comment]
This would now be fixed, it uses a model now.
