### ISSUE TITLE
[PRL21.5 Bug] Overgrown Style:  The Signages Numbers: 10, 14, 15 and 18 are "Unstyled"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#713]
![20160820114236_1](https://cloud.githubusercontent.com/assets/12244376/17831876/33f56e02-66cc-11e6-9e73-7774ce94de38.jpg)

**Comment by TeamSpen210** [comment]
Josepezdj hasn't made the dirty variants for those icons. I'll need to ask him to do that.
