### ISSUE TITLE
[Prl21.5 Bug] Auto portals don't turn off once u have headed into the exit.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#733]
![20160826214443_1](https://cloud.githubusercontent.com/assets/18079316/18007373/61fbb2de-6bd6-11e6-9dfb-c3c2abe77f5c.jpg)

I can head back into the test chamber since the auto portal didn't turn off.

**Comment by Luke18033** [comment]
Fixed now?
