### ISSUE TITLE
[PRL21.5 Bug] 60´s Old Aperture: The "Easter Cube" from the CO-OP Exit dissapear in a "mysterious Way" when the door closes

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#745]
GIF:
![gif](https://cloud.githubusercontent.com/assets/12244376/18059487/86187d4e-6def-11e6-9e3c-c18bb44b76b3.gif)

**Comment by ZombiePwner1** [comment]
Seems the world portal is making the cube and fizzler disappear after the door closes.

**Comment by TeamSpen210** [comment]
It's likely a leak with areaportals. If the entry door frame is missing for example it'll leak, which causes all areaportals to sometimes make nearby props vanish.

**Comment by Luke18033** [comment]
Has this been fixed?

**Comment by LautaroL20** [comment]
I´ve checked this and it got fixed now. I do not know when this could have been fixed but it no longer happens right now.
