### ISSUE TITLE
Old Aperture: Flamethrower "Stops Working" if the player dies and then the map loads from a savepoint.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#746]

**Comment by ZombiePwner1** [comment]
You able to show a gif?

**Comment by LautaroL20** [comment]
Yes, i always like to providing screenshots / Gifs showing the in-game bug, but i think if i record a gif for this it would be too heavy and ghitub wouldn´t allow me to upload it. (10 MB is the limit here).

**Comment by Luke18033** [comment]
Fixed now. I actually duplicated this, and nobody noticed. Oops.

**Comment by Luke18033** [comment]
I guess this was fixed?

**Comment by LautaroL20** [comment]
Yes, and it may probably have been fixed since some pre-relases ago alrady, so i will close this.
