### ISSUE TITLE
[New item] Fizzler grating.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#749]
This type of grating has a fizzler flowing in it and prevents portal shots unless it's turned off.

**Comment by TheDarkBomber** [comment]
This seems unnecessary.

**Comment by LautaroL20** [comment]
You can get the exactly same by placing grating and a fizzler both closely to each other.

**Comment by Luke18033** [comment]
Yes, but combining them would look much nicer.

**Comment by libbybapa** [comment]
Whether or not it would look better is arguable.  It would definitely confuse players more, consume more developer time, and add zero additional functionality.

**Comment by ZombiePwner1** [comment]
Perhaps it could use a custom grating texture with fizzler effects on it.
