### ISSUE TITLE
50´s 60's 70's 80's Old Aperture: Drawbridges causes "Failure to compile" when they are static with no connects

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#750]

**Comment by LautaroL20** [comment]
Could you provide the console bug log?

**Comment by TeamSpen210** [comment]
@ZombiePwner1, what's the error in the console? I can't replicate this.

**Comment by ZombiePwner1** [comment]
@TheDarkBomber I swear to freaking god stop deleting my compile error label i'm starting to get pissed off because of u

**Comment by TeamSpen210** [comment]
A compile error isn't a crash.
