### ISSUE TITLE
[PRL21.5 Bug] BTS Style: A "Clean Corridor" comes in contact with the BTS one causing "Nodraw" on it

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#756]
![20160831175539_1](https://cloud.githubusercontent.com/assets/18079316/18124338/684f0ef2-6fa4-11e6-9f44-4a2cc46a58a5.jpg)

**Comment by corrupt21** [comment]
Just don't use a corridor higher than 2

**Comment by Luke18033** [comment]
This is actually a leak.

**Comment by Luke18033** [comment]
This would be fixed with #530 (implementing these corridors)
