### ISSUE TITLE
BTS Style: It "Crashes the game" giving a weird "Engine error" during the loading proccess of a builded map

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#758]
Engine error screen afther the game crash:

![BTS Crash](https://cloud.githubusercontent.com/assets/12244376/18222348/7ddea944-716b-11e6-851e-fd05f1ae0a94.png)

---

These are the settings i used from Bee2.4:

![beemod](https://cloud.githubusercontent.com/assets/12244376/18222359/d517116a-716b-11e6-8835-e54cc28e089c.png)

**Comment by TeamSpen210** [comment]
This would be from the various areaportal leaks in BTS - specifically the 6th entry corridor most likely.

**Comment by ZombiePwner1** [comment]
BTS is really broken :(

**Comment by TeamSpen210** [comment]
This would be fixed after implementing the other corridors.

**Comment by Luke18033** [comment]
Why don't you actually do that then?

**Comment by Luke18033** [comment]
Actually, to save you time, why don't I try implementing the other corridors?

**Comment by Luke18033** [comment]
Unless they've already been made, but not implemented.

**Comment by Luke18033** [comment]
Basically a duplicate of #530 (adding the missing corridors).
