### ISSUE TITLE
Congradulatory Voiceline Trigger

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#760]
The main objetive of this new item is to get some of the "Congratulations voiceline variants" of GlaDos / Cave / Announcer voicelines, so when the player walks trhough it afther reaching a hard puzzle, it will start playing, making the player to feel good. Of course, this item would have other interesting voicelines aswell.

This item would also have the "ButtonType" property, to choose between "GlaDos, Cave and Announcer".

Each button property would have a special Model editor like the signage item have, but a little bigger, so mappers can have an idea from what voiceline are selecting:

![Model](https://cloud.githubusercontent.com/assets/12244376/18234435/a0611148-72db-11e6-9d9b-8a2a4fe9a497.png)

**Comment by TeamSpen210** [comment]
There's no problem with using a timer item for this. I'd want to keep the descriptions somewhat generic though, so it's possible to find matching lines for all voice packs - have things like 'good job', 'trapped yourself', or 'failed the puzzle'.

**Comment by Kenkenkon** [comment]
Nice idea.

**Comment by TheDarkBomber** [comment]
This is actually part of TeamSpen210 Addons.

**Comment by LautaroL20** [comment]
@TheDarkBomber - If that were true, then i would never suggest it as a "New item".

**Comment by TheDarkBomber** [comment]
You've never heard of the item?

**Comment by LautaroL20** [comment]
I do not want to look like a "show off", but im pretty sure im one of the fews there who tested and knows very well all about the functionality of Bee2.2.5 Stuff PLUS the TeamSpen210 Addons.

**Comment by TheDarkBomber** [comment]
No, there was a GLaDOS Voice Line item.

**Comment by TeamSpen210** [comment]
It was actually a FGEMOD item.

**Comment by TheDarkBomber** [comment]
No, it was an Alpha BEE2.2.5 item.

http://steamcommunity.com/sharedfiles/filedetails/?id=502723626

**Comment by LautaroL20** [comment]
Well, all this time i was thinking that the icon was just a "Big GlaDos Monitor", thing that probably takes lots of entities, and that was the reason i always ignore it, now checking its description it says its a thing from "Felix Griffing" and TeamSpen gently included it in his pack.

Ok, let me say that this Felix item is buggy, if you want to get this item working on "Clean - Quiet" to prevent trite glados voicelines from playing it wount work unless you have the entirely voicelines ennabled and that sucks :(

![glados](https://cloud.githubusercontent.com/assets/12244376/18233930/de0a693c-72cb-11e6-9eff-5f7df3abac48.png)

**Comment by TheDarkBomber** [comment]
Which technically means, even though it has been implemented from FGEMOD, it is still a TeamSpen210 Addons item.

**Comment by LautaroL20** [comment]
@TheDarkBomber  
![glados](https://cloud.githubusercontent.com/assets/12244376/18234000/73b1abfc-72cd-11e6-9ead-33c98df315a3.png)

Like i said, id suggest you to get a pair of glasses.

**Comment by TheDarkBomber** [comment]
But it is in Alpha BEE2.2.5, so it will be re-implemented into BEE2.4.

**Comment by LautaroL20** [comment]
I guess that's explicit for the items that have been maded by TeamSpen210 only. As the "Sideways Light Bridge", "Diagonal Laser" "Half Static Panel" (wich i have a small sugggestion for this one), "Wall features"
"Global Cube dropper" "Glass with hole" Etc Etc.

**Comment by LautaroL20** [comment]
Updated description and title. This should have a special Model editor like the signage item have, but a little bigger, so mappers can have an idea from what voiceline are selecting:

![Model](https://cloud.githubusercontent.com/assets/12244376/18234435/a0611148-72db-11e6-9d9b-8a2a4fe9a497.png)

**Comment by Endermage77** [comment]
This looks like it could work well with the ICP to set what numbers play which lines.
