### ISSUE TITLE
Overgrown Style: The Complete List of Unstyled Icons

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#762]
Here is the current list of unstyled pallete icons from various Styles left to be styled:
- [x] Separated CO-OP Checkpoint
- [ ] Custom Fizzlers
- [ ] Glass Panel
- [ ] Angled Panel
- [x] Weighted Cube
- [ ] Catwalk 
- [x] Companion Cube
- [ ] Laser Cube
- [ ] Light Bridge
- [ ] Faith Platform
- [ ] Large Faith Platform
- [ ] Laser Emitter
- [ ] Laser Relay
- [ ] Track Platform
- [ ] Piston Platform
- [ ] PeTi Fizzler
- [ ] Laser Field
- [ ] Grating
- [ ] Glass
- [ ] Small Observation
- [ ] Mandatory Observation Room
- [ ] Weighted Floor Button
- [ ] Pedestal Button
- [ ] Draw Bridge
- [ ] Half Wall, Centered Wall and Cross Wall
- [ ] Blocks - 60, 45 and 30 Degresses
- [ ] Flat Blocks
- [ ] Black Wall
- [ ] The Three Little Placeable Windows
- [ ] Stairs
- [x] signage
- [ ] Partial Blocks
- [ ] Pneumatic Diversity Vent
- [ ] Retractable Pedestal Button
- [ ] Overgrown Rocket Turret ( In case that mel´s one gets shared)
- [x] Cube Cleaner

---

This list is to be expanded once TeamSpen210 reimplements the original addons to Bee2.4

**Comment by LautaroL20** [comment]
This has been expanded to the complete list of Overgrown unstyled icons, this is now a long-term post. I will be "Ticking" each test element on this list once each icon gets maked.

I might want to do this list also for the left Styles too.

**Comment by ZombiePwner1** [comment]
This will go to other styles as well since other styles have unstyled icons.

**Comment by LautaroL20** [comment]
Yep.

**Comment by Endermage77** [comment]
What about the Unstationary Scaffolds? They don't even have original icons, let alone styled ones.

**Comment by Byzarru** [comment]
The cubes should be re-done instead of using Radelite's icons. I volunteer as tribute.

**Comment by LautaroL20** [comment]
@Byzarru - If you want to make them id have no problem replacing the Radelite´s ones.

**Comment by Luke18033** [comment]
I really don't think we need to make styled versions of every icon. There are currently 180 items in the BEE2 and 9 styles, which means we'd need approximately 1600 icons to cover every variant. That's not completely accurate, since some icons could be reused between styles and other items (like logic gates) are unstyled entirely, but it'd still be a lot. We should put our time into making the styles look better in-game rather than making them look better in the editor.

**Comment by Luke18033** [comment]
We should only add styled icons for things that have a completely different design, like Old Aperture buttons. Overgrown items are mostly identical to the Clean versions, so I highly doubt that most people would care if the icons are the same.
