### ISSUE TITLE
[PRL21.5 Bug] 80´s Old Aperture: A "Mysterious Portal Gun" is again on the SP Entry´s Floor

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#769]
![20160904143527_1](https://cloud.githubusercontent.com/assets/12244376/18232782/9cfaf9ac-72ad-11e6-9abe-27960d4bb6b3.jpg)

**Comment by TheDarkBomber** [comment]
Duplicate of #748.

**Comment by LautaroL20** [comment]
Nope. One is from 60´s Old, and this is from 80´s.

**Comment by Luke18033** [comment]
It's still a duplicate.
