### ISSUE TITLE
[PRL21.5 Bug] Portal 1 Style: cameras Wire is really glitchy

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#774]
![20160905164656_1](https://cloud.githubusercontent.com/assets/18079316/18242467/080753fe-7389-11e6-8621-a8eca86d7120.jpg)

Wire is really buggy.

**Comment by Luke18033** [comment]
I don't think this happens anymore.

**Comment by LautaroL20** [comment]
Do not forget to apply the corresponding label after closing a solved issue.
