### ISSUE TITLE
Idea for new bottomless pit logic

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#787]
since your making the bts bottomless pit part of the map so lasers can enter it etc, I got an idea...

why not make something similar to what you did with the new bts pit with all the others such as the Wheatley style and texture the walls and sides below panel and frame instances etc with skybox texture and then you would see through it and it would look like an open pit etc and you could fall in and paint would also fall down it and not splash before it vanished...

**Comment by TeamSpen210** [comment]
That's actually a really good idea!

**Comment by Luke18033** [comment]
Not really needed once non-skybox pits are added
