### ISSUE TITLE
[PRL22 Bug]: Something "Mysterious" happens when placing a pillar that is under goo in deep Bottomless Pits

### ISSUE THREAD

**Issue by Electricianfromhell** [BEEmod/BEE2-items#788]
bug: this happens when placing a pillar that is under goo in deep bottomless pits

![preview0012](https://cloud.githubusercontent.com/assets/11165643/18412645/c051cfda-7761-11e6-81a3-a3ff7e800f87.jpg)

**Comment by TeamSpen210** [comment]
It's unfortunately pretty difficult to detect this, just ensure the surface is flat.

**Comment by Luke18033** [comment]
The original skybox pit system was removed, so this would be irrelevant.
