### ISSUE TITLE
[PRL22 Bug] Bottomless pit not rendered on linked camera panel

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#790]
bottomless pit not rendered on linked camera panel

![preview0003](https://cloud.githubusercontent.com/assets/11165643/18413738/ec7c72d6-777f-11e6-9381-f0592f4edeb6.jpg)

![preview0004](https://cloud.githubusercontent.com/assets/11165643/18413741/f82ee30c-777f-11e6-96ea-59d0421d031a.jpg)

**Comment by Kenkenkon** [comment]
Sorry, but I have a question and I'm using this post to ask it because it's about that I'm going to talk about. Do you have control in which "material" is going to be used in BTS style?

**Comment by TeamSpen210** [comment]
All the textures used are set by me, yes. They're randomly chosen though, you can't select a specific one for a location.

**Comment by ZombiePwner1** [comment]
Look at the plastic as well it's not centered correctly

**Comment by Luke18033** [comment]
This seems to be a Valve bug, a similar issue happens when looking through portals in Garry's Mod (the skybox disappears). Gmod uses a different engine version though so maybe that's a different issue.

**Comment by Luke18033** [comment]
This won't be an issue with non-skybox pits
