### ISSUE TITLE
[Prl22 Visual Bug] Overgrown Small Observation: Vine Cluster is "Crossing the floor" looking "Unprofessional" - Model requires a small "Re-scaling"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#791]
Vine cluster that is using small observation needs to be re-scaled a bit:

![overgrown](https://cloud.githubusercontent.com/assets/12244376/18414137/a31eae40-7795-11e6-83fb-aaebdf9de98b.png)

**Comment by Luke18033** [comment]
We're not rescaling the model, just shift it upwards a bit if you really think this looks that bad.

**Comment by Luke18033** [comment]
In fact I really don't think this matters, the vine models randomly sway around which can result in them clipping through walls/floors/props anyway. Plus the fact that, you know, *this is a tiny error in a small observation room which most people won't notice anyway*?
