### ISSUE TITLE
Enhancement for overgrown observation rooms.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#799]
Make a custom rusted model for chairs and the desk.

**Comment by Luke18033** [comment]
Valve didn't make this already?

**Comment by ZombiePwner1** [comment]
No they didn't

**Comment by Konclan** [comment]
There is absolutely no point to doing this, this would be a waste of model space

**Comment by Endermage77** [comment]
Stainless steel desks and chairs. Boo-yah.

**Comment by Konclan** [comment]
It's not lazy, the game has a certain amount of models we can load at one time, adding custom rusted models would be a pointless waste
