### ISSUE TITLE
[Bug] 50's 60's 70's 80's BTS camera item is unstyled.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#804]
![20160912175307_1](https://cloud.githubusercontent.com/assets/18079316/18431946/ffd34920-7911-11e6-92b3-8e785e84db41.jpg)

**Comment by TeamSpen210** [comment]
Yes, I still need to modify some models to allow this.

**Comment by ZombiePwner1** [comment]
If you can try making a CS:GO security camera or something.

**Comment by TeamSpen210** [comment]
There's a nice model in PS:Mel I'm planning on using.

**Comment by ZombiePwner1** [comment]
Send a picture through I wanna see it.

**Comment by TheDarkBomber** [comment]
BTS is also unstyled.

![alt](http://i.imgur.com/Q2b1MZ5.png)

**Comment by Luke18033** [comment]
@ZombiePwner1 No, "Missing Instance" is for "there was an error building the puzzle" because of a missing instance. It is NOT the same as "Missing Item Variant"

**Comment by TeamSpen210** [comment]
Implemented the Old Aperture ones.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Can we see a picture of them?
