### ISSUE TITLE
[Bug] What on earth is happening on 80's coop exit?

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#806]
![20160912182449_1](https://cloud.githubusercontent.com/assets/18079316/18432735/504b6d52-7916-11e6-984e-aa3d040b5e89.jpg)

**Comment by LautaroL20** [comment]
Stange...... I used the corridor 1 and that didnt happen. The only problem is that the Deadlygoo is not showing up on the speres.

**Comment by LautaroL20** [comment]
The report is invalid. This does not happens with any corridor, as you said, something wrong is with ur version.

**Comment by Luke18033** [comment]
I've seen someone else report this same bug, but I've never been able to reproduce it. Do you still have the map file which had this issue?

**Comment by Luke18033** [comment]
Going to close this again since nobody really has any idea what's happening here. If you're ever able to reproduce this again, send the VMF over.

**Comment by Luke18033** [comment]
Maybe this can happen as a result of one of the test element overlay instances, has anyone checked that?

**Comment by LautaroL20** [comment]
Not yet, but this issue seems to be hard to replicate as it might occur once between a lot of attempts. I remember trying to replicate it myself by the time this issue was reported but no success, unfortunately.
