### ISSUE TITLE
[Bug] P1 camera collision is really glitchy

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#808]
![20160912184004_1](https://cloud.githubusercontent.com/assets/18079316/18433162/a93bc6e4-7918-11e6-8541-59be0aadb0c2.jpg)

**Comment by Luke18033** [comment]
Related to #1461

**Comment by LautaroL20** [comment]
Yep, this issue can be perfectly merged with https://github.com/BEEmod/BEE2-items/issues/1461 since Spencer told that he would need to replace the camera entirely in order to fix all those issues.
