### ISSUE TITLE
[PRL22 Bug] 80´s Old Aperture: CO-OP "Enrichment Sphere´s DeadlyGoo" is not showing up

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#810]
![20160912074617_1](https://cloud.githubusercontent.com/assets/12244376/18433607/01662328-78bf-11e6-9511-ce8e21b26aa4.jpg)

**Comment by ZombiePwner1** [comment]
I had the same thing with my issue since I used no clip to get around this is probably due to a leak.

**Comment by Konclan** [comment]
Goo isn't missing, just very dark

**Comment by Luke18033** [comment]
This looks like the same issue as #806, just the instance is positioned differently so it appears lower. @LautaroL20 You wouldn't happen to still have the map where this happened, would you?

**Comment by Luke18033** [comment]
Wait @Konclan were you able to reproduce it with open sphere on?

**Comment by LautaroL20** [comment]
> Luke18033 said: This looks like the same issue as #806, just the instance is positioned differently so it appears lower. @LautaroL20 You wouldn't happen to still have the map where this happened, would you?"

Unfortunately no, as it was a random playtesting I was doing in 2016 but hey... it seems that Konclan figured the cause and fixed it, see commit: https://github.com/BEEmod/BEE2-items/commit/de3ead8da224d426fa894f1f1dec0a893a75789d

**Comment by Luke18033** [comment]
Yep, that was talked about on Discord. Unfortunately though it seems like #806 is an unrelated issue, this was just a lighting bug while that involved incorrect geometry generating.
