### ISSUE TITLE
[PRL22 Bug] Overgrown Style: the SP 4th corridor door is having two small "Visible nodraw" under floor´s cavity

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#818]
![20160913055336_1](https://cloud.githubusercontent.com/assets/12244376/18467585/ee7c16a6-7976-11e6-9783-6862c116427e.jpg)

**Comment by ZombiePwner1** [comment]
Lautaro come online i wanna chat :)

**Comment by TeamSpen210** [comment]
Send him a friend request, don't spam comments here.

**Comment by LautaroL20** [comment]
Fixed via: dcafa587117e59e2caa7066a0ca90dd61aab33f9
