### ISSUE TITLE
The cube from the Old aperture "Dropper" is unstyled and the dropper shows a mysterious dark model.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#819]
![20160913200005_1](https://cloud.githubusercontent.com/assets/18079316/18472940/cdf8d4de-79ec-11e6-8f2d-667ad71ac9e0.jpg)

**Comment by ellingtonvengaboysmuseum** [comment]
also shows modern cube underground

**Comment by ZombiePwner1** [comment]
The black model on the dropper is caused by the puzzlemakerbshadows

**Comment by ZombiePwner1** [comment]
The black model on the dropper is caused by shadows but I think teamspen can fix it.
