### ISSUE TITLE
[Bugs] BTS Corridor and Exit issues

### ISSUE THREAD

**Issue by cartman1337** [BEEmod/BEE2-items#820]
The chamber I was working on for Overgrown style didn't look to good there, because of the reported goo debris bug, when there's a lot of goo on the level. Testing the chamber in other styles I realized it looked awesome with bottomless pits instead, so I went behind the scenes. Also helped me name the chamber (check it out here: https://steamcommunity.com/sharedfiles/filedetails/?id=762753554)

In any case, when I went from Overgrown to BTS style, I believe I had corridor 4 pre-selected, along with exit 4. Then I noticed this bug with the exit; opening long before all inputs were active:
![Exit door open when it should be shut](http://i.imgur.com/SCm9dLT.jpg)

After finding a way around this problem, and publishing it with exit 4 still in use, I realized on my first playthrough of the published version, that the exit did not really work, when I reached the end I did not get the normal thumbs up/down, move to next chamber screen. So I quickly re-publishet it with corridor and exit 1 instead. Playing with exit 1, the exit opening out of turn did not seem to happen anymore, so I decided to test a bit further.

A tiny test with multiple inputs to one exit, testing all corridors and exits, resulted in these findings.

**Corridors**
No. 1: Works perfectly
No. 2: The skybox in the window in the office chamber does not work, and when reaching the door of the entry corridor, you'll see a skybox error instead of the actual chamber as the door to the chamber opens, see picture below
No. 3 through 6: The skybox in the window in the office chamber does not work, and after the office chamber there is a strange crossover from BTS to clean style, before entering the chamber
No. 7: The skybox in the window of the office chamber looks good, but the crossover to clean style has more visual bugs than 2 through 6

The entry door in corridor 2 shows this instead of the chamber:
![Door to the chamber showing weird things](http://i.imgur.com/Bbl2L5J.jpg)

**Exits**
No. 1: Works perfectly
No. 2: No skybox error, but you fall into a black hole, with no visible way out - impossible to finish level
No. 3 and 4: Skybox error looking into the exit + exit will open without all inputs active, walking into it crosses over to a clean exit, but does not finish the level. With corridor 7, exits 3 and 4 will not show the skybox error, but shows a clean exit instead, which still does not work, though.

![Example of skybox error looking through the exit](http://i.imgur.com/T3iH5R1.jpg)

Testing with the different corridors and exits, I've been unable to open the exit without all inputs active using exits 1 or 2, but both of exits 3 and 4 would open as soon as 4 or more of the inputs were activated, and upon opening once (they quickly close too), the can open and close with any number of inputs. Case in point:
![Exit open without all inputs active](http://i.imgur.com/5YEvwC3.jpg)

**Comment by ZombiePwner1** [comment]
BTS has alot of world portal and area portal leak issues.

**Comment by Luke18033** [comment]
This is mostly addressed in #530 (implementing the missing corridors would fix this issue)
