### ISSUE TITLE
[Visual Bug] BTS: Textures disappear when looking/walking through portals

### ISSUE THREAD

**Issue by cartman1337** [BEEmod/BEE2-items#821]
As I moved my latest chamber over from Overgrown to BTS style I noticed that BTS has some interesting visual flaws, particularly through portals. Not game breaking, but it should be looked at.

Here are some examples. If you want to check it out yourself, feel free to try my map: https://steamcommunity.com/sharedfiles/filedetails/?id=762753554

**Grating disappear** (but fortunately still blocks you, even if you can't see it)
![Portal to a square with grating in front](http://i.imgur.com/UeM893n.jpg)
The orange portal is on a square with grating in front, as you can see through the portal initially. But as you move up close to the portal, the grating looks to be gone, or at least it's invisible; you still can't walk through it:
![Standing directly in front of the grating in the portal](http://i.imgur.com/xOOt4kR.jpg)

Notice that also the lights in the roof, the catwalk and other textures, like the sendificator and its buttons for use, which should all be on the left platform, are gone as well.

**All test elements disappear**
A laser catcher disappears/reappears as you move relative to the portal:
![Laser catcher visible](http://i.imgur.com/sgLPdiY.jpg)
![Laser catcher gone](http://i.imgur.com/12sE3rI.jpg)

A light bridge, cube and turret (seen by its laser sight):
![Light bridge, cube and turret visible](http://i.imgur.com/9YLtNrP.jpg)
![Light bridge, cube and turret gone](http://i.imgur.com/3a3aI7M.jpg)

A sendificator, door, catwalk, monitors and pedestal button:
![Textures seen](http://i.imgur.com/3yvaFo2.jpg)
![Textures gone](http://i.imgur.com/owT4giL.jpg)

**Comment by ZombiePwner1** [comment]
The grating becoming invisible is a valve bug and most likely can't be fixed.

**Comment by TeamSpen210** [comment]
This is probably from the leaks in the corridors.

**Comment by cartman1337** [comment]
Does corridor and exit 1 have leaks? Because they look pretty complete and good in the game. The textures will disappear in the portals also with these corridors selected.

Talking of BTS texture bugs; I noticed yesterday that if you shoot portals in the corridor area of a BTS chamber, your avatar is changed to the little, black, flat character, even though Chell or one of the robots have been selected as the avatar. Right at the entrance, if you shoot one portal on both sides of the corridor, you'll also see the portal gun just hanging in the air by the door, when you look through one of the portals. If you do not use portals in the corridors, the Chell or robot avatar is correctly rendered in the chamber. Not a big issue, but certainly a curiosity.

**Comment by TeamSpen210** [comment]
Entry/exit 1 don't have leaks. That model bug doesn't make sense at all.

**Comment by Luke18033** [comment]
This is indeed caused by having leaks in the map.
