### ISSUE TITLE
[PRL22 Bug] Original Clean: Corridors aren´t using original PeTi ceilling texture 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#824]
![ghitub comment](https://cloud.githubusercontent.com/assets/12244376/16360721/c04ddddc-3b46-11e6-9eb3-ada28aa69d3a.png)

![20160914022214_1](https://cloud.githubusercontent.com/assets/12244376/18500889/591a72ea-7a22-11e6-801f-d0ac63b31577.jpg)

**Comment by ZombiePwner1** [comment]
I like that texture actually the original one is not really my type.

**Comment by TeamSpen210** [comment]
Indeed, I changed it to the actual ceiling texture.

**Comment by LautaroL20** [comment]
@TeamSpen210, The second screenshot from below is the actual PeTi original corridor roof texture ;)

![ghitub comment](https://cloud.githubusercontent.com/assets/12244376/16360721/c04ddddc-3b46-11e6-9eb3-ada28aa69d3a.png)

![20160914222953_1](https://cloud.githubusercontent.com/assets/12244376/18535623/2f9f9efe-7acc-11e6-8ed8-6ac62f522d0f.jpg)

It seems to be using the same checkered wall texture that usually light strips generates.

**Comment by ZombiePwner1** [comment]
That was the texture I was talking to @TeamSpen210 about @LautaroL20 and that texture fits perfectly well.

**Comment by LautaroL20** [comment]
But TeamSpen said in the past that "Original Clean" must ALWAYS use original textures no matter what. It os not about "Tastes".......
