### ISSUE TITLE
Add BTS wheatley voice lines

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#827]
Add Wheatley voice lines to fit with BTS theme using Wheatley.

_____________________________________________________________________________

Some suggestions by Luke18033:

"This would use a different set of lines where Wheatley is helping you get through BTS areas and reach GLaDOS, rather than trying to get you to test. On Monitors, Wheatley would be attached to his management rail, with BTS textures behind him."

**Comment by Luke18033** [comment]
Copied from duplicate issue:

This would use a different set of lines where Wheatley is helping you get through BTS areas and reach GLaDOS, rather than trying to get you to test. On Monitors, Wheatley would be attached to his management rail, with BTS textures behind him.

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
