### ISSUE TITLE
[PRL22 Bug] Installation bug in PRL22 for Mac.

### ISSUE THREAD

**Issue by Kenkenkon** [BEEmod/BEE2-items#832]
When I downloaded PRL22 and executed it after putting the necessary items, this appeared:
![bug](https://cloud.githubusercontent.com/assets/21965054/18590738/57cdae9e-7c06-11e6-8d50-e183bf099fc9.png)
PS: I'm using mac.

**Comment by TheDarkBomber** [comment]
See BenVlodgi/BEE2.4/issues/397

**Comment by Kenkenkon** [comment]
@TheDarkBomber Didn't get it, his english wasn't the great I've seen.

**Comment by TheDarkBomber** [comment]
@Kenkenkon Who's English?

**Comment by Luke18033** [comment]
No longer an issue since the switch to PyInstaller
