### ISSUE TITLE
[PRL22 Bug] The "Partial Blocks", when placed on "Ceilling", are not using "Checkered textures" 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#837]
During the fixing of the resetting bug, i noticed that the "Partial blocks" are almost not getting checkered textures when they´re placed on the roof:

![20160918161205_1](https://cloud.githubusercontent.com/assets/12244376/18618448/617a6fb4-7dbd-11e6-9f15-bb0ec5a4b181.jpg)

**Comment by TeamSpen210** [comment]
That's a bug with how I wrote the ceiling texturing... I need to redo that.

**Comment by LautaroL20** [comment]
Ah, i thought it was on purpose, ill change the title and labels then.

**Comment by ZombiePwner1** [comment]
@LautaroL20 I wanna chat @TeamSpen210 It would be really cool if you could make the ceilings in P1 like for example the ceiling in the chamber where you get both orange and blue portal gun.

**Comment by TeamSpen210** [comment]
I'm planning on making them all random sizes, as a 'decoration'.

**Comment by Luke18033** [comment]
Fixed in the geometry branch.

**Comment by LautaroL20** [comment]
> Luke18033 said: "Fixed in the geometry branch."

No, this bug was already fixed about a long time ago already when Spencer implemented the "TemplateBrush" thing.
