### ISSUE TITLE
Overgrown Laserfield and Custom fizzlers do not have "Phong" set

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#841]
There is only two scenarios for this bug, one is that the lighting position have set wrong, or they re using "Clean frames", idk. PICT:

![20160910230529_1](https://cloud.githubusercontent.com/assets/12244376/18626520/eb73940c-7e2b-11e6-9f57-1ccb358246a3.jpg)

**Comment by ZombiePwner1** [comment]
Picture of custom fizzlers?

**Comment by LautaroL20** [comment]
Ah, sorry. Well, they looks actually the exactly same, but ill be re-posting the custom fizzler one in some minutes, editing something on hammer right now.

**Comment by TeamSpen210** [comment]
The laserfield on the right is clean. I believe dirty ones don't have the same reflection/shine set, so they look more dull.

**Comment by TeamSpen210** [comment]
Indeed, the dirty ones don't have `phong` set, so they appear non-shiny and dull. That causes the white reflections you can sometimes see.

**Comment by LautaroL20** [comment]
Ok, but the title should goes for the "custom fizzlers" too, since custom ones are affecting by this phong not being setted.
