### ISSUE TITLE
[PRL22 Visual Bug] Overgrown Style: Large Observation Room have "Small visual leaks on Corners"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#844]
Feel free to call me the Second Great Bee2 bug finder.

---

![20160919084538_1](https://cloud.githubusercontent.com/assets/12244376/18630916/834676be-7e45-11e6-96bb-4f4f10ac624d.jpg)

**Comment by ZombiePwner1** [comment]
This was fixed i think.
