### ISSUE TITLE
[Bee2.4 PRL22 CRASH] PermissionError(13, "Access denied")

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#849]
![bee2 4 crash](https://cloud.githubusercontent.com/assets/12244376/18665728/ea3b1190-7efe-11e6-9a93-005340bb48de.png)

**Comment by ZombiePwner1** [comment]
How do u cause this?

**Comment by LautaroL20** [comment]
Idk, its a random crash wich happens from time to time, probably due to a custom package i maded....

**Comment by LautaroL20** [comment]
Well, aparently this happens (At least in my case) when you have an opened instance into hammer, then when you re-export, beemod will crash. The solution for this is to export ONLY when you have hammer closed.

**Comment by TheDarkBomber** [comment]
If this was from a custom package you made, this should be invalid, because it doesn't concern the main set of BEE2 items.

**Comment by LautaroL20** [comment]
No, this actually happened because i had an original bee2.4 instance opened on hammer, when you export the Bee2.4 pallete, beemod deletes ALL the things inside "sdk_content\maps\instances\bee2". But if you have opened a file, the program can not properly delete and the crash will happen. So it was the Bee2.4 fault that do not have the advise into the README.txt

I have suggest this, here: https://github.com/TeamSpen210/BEE2-items/issues/860
