### ISSUE TITLE
Implement Contraption Cube and button

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#850]

**Comment by TeamSpen210** [comment]
Yes and no. I have the model for it, and could fairly easily add it as a cube. However, the functionality is part of the custom code in the Education version, which isn't in the base game. It wouldn't be able to be configured like the item does.

**Comment by ZombiePwner1** [comment]
Okay so will you add it as a regular cube? And are you also able to bring the contraption cube button?

**Comment by TeamSpen210** [comment]
I'm probably not going to, since it doesn't serve any purpose like that. 

The button is reproducible, it's not too special.

**Comment by ZombiePwner1** [comment]
Make it as an unpaintable cube.

**Comment by LautaroL20** [comment]
Well, TeamSpen will not implement back it, case closed.

**Comment by ZombiePwner1** [comment]
He is might make it an unpaintable cube and come online.

**Comment by LautaroL20** [comment]
If you are suggesting an unpaintable cube, altough your post is a cuestion, it lends that this is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/585

**Comment by LautaroL20** [comment]
@ZombiePwner1 - I was being offline since im focus on releasing my first overgrown chamber into the workshop.

**Comment by ZombiePwner1** [comment]
Did u not read my comment about it being an unpaintable cube?

**Comment by LautaroL20** [comment]
Another user already suggested an "Unpaintable cube" as a new item.

**Comment by ZombiePwner1** [comment]
...

**Comment by ZombiePwner1** [comment]
seems u didn't read my comment

**Comment by TheDarkBomber** [comment]
TeamSpen210 didn't even say he was going to make it a regular cube.

**Comment by ZombiePwner1** [comment]
I talked with @TeamSpen210 on steam.

**Comment by TheDarkBomber** [comment]
Shouldn't this be closed then?

**Comment by LautaroL20** [comment]
@TheDarkBomber - Probably, closed it many times, but my friend ZombiePwner1 seems to be happy with it being open.

**Comment by Luke18033** [comment]
The contraption cube could be configured with my idea on #547.

**Comment by TeamSpen210** [comment]
That would work, to allow making different cube options. First I'd need to figure out how to configure the options that the cube can be configured by.

**Comment by TeamSpen210** [comment]
That would work, to allow making different cube options. First I'd need to figure out how to configure the options that the cube can be configured by.

**Comment by ZombiePwner1** [comment]
Ummm @TeamSpen210 Why do you have 2 of the same message?

**Comment by TeamSpen210** [comment]
Submitted it twice.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Heres an idea for the button it requires cubes to be painted for it to activate. Let me know what you think.

**Comment by TeamSpen210** [comment]
Contraption cubes have absolutely nothing to do with paint, that really doesn't make sense.

**Comment by ZombiePwner1** [comment]
okay then i will try to see if i can find another use for the button.

**Comment by Luke18033** [comment]
Just use it as a normal contraption cube button, maybe also add a #547 option to choose a certain weight for the cube to push it.

**Comment by Luke18033** [comment]
And make sure that the button actually works, unlike the original:
![ContraptionCubeError](http://i1.theportalwiki.net/img/5/59/ContraptionCube_Error.png)

**Comment by ZombiePwner1** [comment]
@Luke18033 the button could also only allow the contraption cube and nothing else.

**Comment by ZombiePwner1** [comment]
@Luke18033 Good news i actually got the button and cubes working in the main game.


![20170409111409_1](https://cloud.githubusercontent.com/assets/18079316/24835309/850f6bc8-1d31-11e7-81d7-dce621d6eee4.jpg)

**Comment by Endermage77** [comment]
This could use a timer to have a variety of Contraption Cube settings available ingame, set with the ICP.

**Comment by Luke18033** [comment]
I think it's possible to configure mass, friction, and elasticity on a per-prop basis using Override Parameters. That would work for this, if we could also figure out how to control the size of the metal sphere in the center (when I tried using the model, it seemed to just change size randomly as I moved around). It's possible we'd need a custom model which uses a different system to resize it.

**Comment by Luke18033** [comment]
We've talked about this a lot on Discord, it's not really possible to implement in the base game.
