### ISSUE TITLE
[PRL22 Visual Bug] A mysterious floating Companion Cube takes 2 seconds to start falling into the roof of the exit elevator

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#851]
It looks kinda Unprofessional / Unreal:

GIF (gif may takes some seconds to run properly, be patient):

![gif](https://cloud.githubusercontent.com/assets/12244376/18710237/81dd7a20-7fda-11e6-8c69-9fa8a76ccc81.gif)

**Comment by LautaroL20** [comment]
I wan´t able to fix it myself, so i might want to add some "Plants" to hidde the floating cube.

**Comment by Luke18033** [comment]
Does this actually still happen?

**Comment by LautaroL20** [comment]
Well, I think I will give this a test today to see if this still occurs.

**Comment by LautaroL20** [comment]
This Companion Cube has been removed from the Overgrown exit elevator and was replaced by a different Cube scene. However, this new scene has a another issue where the cubes will disappear in a mysterious way, here is a short video: https://www.youtube.com/watch?v=y9k9FUVl4EE

So, issue https://github.com/BEEmod/BEE2-items/issues/4011 happens instead.
