### ISSUE TITLE
Aditional Notes that should be added to the Readme.txt from Bee2.4

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#860]
-   If you are editing on Hammer, anything that is placed in the folder sdk_content\maps\instances\bee2 will be deleted if you export the BEE2.4 pallete without enabling the setting Preserve Game Directories. If you are editing any package, after you have finished, do not forget to save it inside the packages, by replacing the old files inside.
-    BEE2.4 will crash if you are exporting while another folder or file is open that is important to the BEE2.4 compilation process.
 -   If you are having problems using BEE2.4, make sure to verify the game cache files of Portal 2 before using a new BEE2.4 Default Pack release. The issue also could be from another BEE2.4 pack, not just the BEE2.4 Default Pack.
- It is recommended to have backups from the following Portal 2 folders: sdk_content, portal2_dlc2, and bin, just in case you need to restore your Portal 2 files.
- Check out the Ghitub Beemod Wiki for knowledge on how editoritems works, a package building, the application or items in general: https://github.com/TeamSpen210/BEE2-items/wiki

**Comment by TheDarkBomber** [comment]
To edit a BEE2.4 instance, edit it from the packages folder.

**Comment by LautaroL20** [comment]
Hammer editor can´t open zip files.....

**Comment by TeamSpen210** [comment]
For editing files, set 'Preserve Game Resources' in settings. That disables copying resources entirely.

**Comment by LautaroL20** [comment]
Ok, checked for it and it is "Preserve Game Directories", not "Resources", so i re-edited the post description with a more properly notes.

**Comment by TheDarkBomber** [comment]
@LautaroL20 

Edit the VMF inside the instance folders inside the package folders.

**Comment by LautaroL20** [comment]
Thats not a good idea, once you finish editing on hammer, you have to check the edited results during the In-Game preview and the only way is by having the VMF´s instances in the Portal 2 folders.

But having the "Preserve Game Directories" ennabled, it will not be a problem anymore.....But afther all, hope that TeamSpen add these aditional notes to the original readme because it may contribute to another unexperienced users.

**Comment by LautaroL20** [comment]
Updated the post description with:

- Check out the Ghitub Beemod Wiki for knowledge on how editoritems works, a package building, the application or items in general: https://github.com/TeamSpen210/BEE2-items/wiki

**Comment by LautaroL20** [comment]
Updated the post´s notes with: 

- If Bee2.4 unexpectedly closes after the loading panel finishes, try deleting or edit bee2/config/config.cfg then launch the aplication again.
