### ISSUE TITLE
Add command "$mostlyopaque" in the QC files on the "Square Light Skins"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#864]
Any chances to get back the cool and warm tinted skins for the Square Light? They seems to be there, and looks too beautiful, but why they aren´t being displayed in the map? It would be awesome to having these restored for Bee2.4:

![98bd7ff0-82a6-11e6-825c-a7fcfa8d62d8](https://cloud.githubusercontent.com/assets/12244376/20896150/23d87932-bafb-11e6-8152-3c7b6ab2de36.png)

**Comment by TeamSpen210** [comment]
What do you mean by 'pack'? I should add those via a Button Type property.

**Comment by LautaroL20** [comment]
I mean that these tinted glass are not being packed with the square light when the map is builded, and instead, they gets rendered without any glass, here is a screenshot:

![20160924234354_1](https://cloud.githubusercontent.com/assets/12244376/18812630/f095b850-82b0-11e6-8864-fe2482c7ca5f.jpg)

**Comment by ZombiePwner1** [comment]
lol the model must be bugged with the glass.

**Comment by cartman1337** [comment]
Actually, if you look close, the glass is there:
![Warm light 1](http://i.imgur.com/EWgCvDa.jpg)
![Warm light 2](http://i.imgur.com/VUlg8Ly.jpg)
![Warm light 3](http://i.imgur.com/5c5ftkV.jpg)

I doesn't really look like warm light, but the glass is definitely there. The light is so bright that from a distance, the glass isn't visible.

**Comment by LautaroL20** [comment]
@cartman1337 - No, will only happens when you try setting the glass skin to 1, 2 or 3 (Warm or Cool tinted) on the hammer´s properties. Those screenshots are actually from the non tinted glass...

**Comment by cartman1337** [comment]
I don't use Hammer, so I don't know what that means. The glass in Bee2.4 looks good enough for me, though.

**Comment by LautaroL20** [comment]
Well, actually the current square light does not have the glass bug, so it will shows properly. This post talks about the alternately tinted glass (Warm and Cool skins) wich for some unknown reason, its skins are bugged.

**Comment by LautaroL20** [comment]
Alright, i think the title was not very clear, i fixed it now.

**Comment by LautaroL20** [comment]
Well, i guess that the warm and cool skins for the square light not being dislayed in game its a Valve bug, maybe?

**Comment by LautaroL20** [comment]
Changed the title to the real descriptive fix.

**Comment by LautaroL20** [comment]
Note that for the Warm Skin, there are two versions of it: A very dimly warm glass colour (Value 2), and one wich looks vivid (Value 3). Id preffer the intensive colour, but in any case we can fix dimly one too.

**Comment by LautaroL20** [comment]
Ive arranged the Editor Models and Palette Icons, so you dont have to make them. But im having a weird bug where the editor does not display the "ButtonType" property, even when i make sure everything was correct on editoritems.txt. I will need your help on this.
![hmw_square_lights_grouped](https://cloud.githubusercontent.com/assets/12244376/20240184/e2c8c8d2-a8f0-11e6-9089-aecf316cb87b.png)
![palette](https://cloud.githubusercontent.com/assets/12244376/20240239/4509ab64-a8f2-11e6-915a-b782e705b222.png)

**Comment by TeamSpen210** [comment]
Kinda funny, since I actually made those models too yesterday. The screenshots are very helpful though. 

I'll be making the item have warm, cool and neutral colours.

**Comment by LautaroL20** [comment]
Tomorrow id like to test the warm and cold versions in case you already applied the fix to them, as for the "grouped icon" here it is:

![256x256_hmw_square_lights_grouped_2](https://cloud.githubusercontent.com/assets/12244376/20259157/1f49f28a-aa32-11e6-94f7-31965bd140e5.png)

**Comment by LautaroL20** [comment]
The clean instances for the skins item are still missing into the "square_cold_lights" branch.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Nope, do not close it yet. It still missing the old aperture variants.
