### ISSUE TITLE
[Enhancement] Overgrown Style: Make the observation room´s "Metal Table" to using some kind of "Overgrown Skin Colour" 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#866]
![20160926230457_1](https://cloud.githubusercontent.com/assets/12244376/18857872/d6c17f0c-843d-11e6-81ee-719fc3228fde.jpg)

**Comment by LautaroL20** [comment]
@Konclan - This is an ehnancement, not a bug!

**Comment by Konclan** [comment]
I didn't say it was a bug

**Comment by LautaroL20** [comment]
I will have to undo one of your fixes then, since it seems you touched this:
![Image](https://user-images.githubusercontent.com/12244376/33394366-dae4b966-d520-11e7-8fac-a07ece7607fb.png)

**Comment by Konclan** [comment]
Why would you undo it?

**Comment by Konclan** [comment]
I'm very confused as to what you meant by any of this. I changed the color of the table prop to normal.

**Comment by LautaroL20** [comment]
Before you changed the colour, it was brown which makes it blend with the damaged feeling of the small observation. However this would be temporal until someone makes an actual overgrown model/skin for it. 

The original table appearance does not fit at all with the damaged inside of the small observation, its way to much "clean".

**Comment by TeamSpen210** [comment]
I've recently discovered there's a limit of 1024 models that can be loaded at once. It's pretty large, but we don't want to waste it on things like ths. The glass obscures it anyway, and players normally can't stand right next to it.
