### ISSUE TITLE
[PRL22 Visual bug] Overgrown Style: The plants from the entrance next to the first door, are "Crossing the Wall" in a "Mysterious Way"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#867]
![20160926230404_1](https://cloud.githubusercontent.com/assets/12244376/18858033/563b4262-843f-11e6-8d2d-095e44d4bde2.jpg)

**Comment by ZombiePwner1** [comment]
That's caused by the wind you can't control that.

**Comment by TeamSpen210** [comment]
I'll need to tilt/move it slightly so it doesn't move into the wall.
