### ISSUE TITLE
Bottomless pit style variations

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#87]
The bottomless pit skybox should change depending on the selected style.

Portal 1 Style Concepts
![](https://user-images.githubusercontent.com/31172185/38771425-1843fd0e-3fd8-11e8-8538-4be5552a5896.PNG)
![](https://user-images.githubusercontent.com/31172185/38771427-1cc30d0c-3fd8-11e8-8502-85f34ae8fb8d.PNG)

Wheatley Style Concepts
![sp_a3_faith_plate0002](https://cloud.githubusercontent.com/assets/11165643/8895528/0686ff98-33ac-11e5-8ac7-5aa2bb190948.jpg)
  ![sp_a3_faith_plate0000](https://cloud.githubusercontent.com/assets/11165643/8895544/7e1f317e-33ac-11e5-833d-81778c34bcfb.jpg)

Edit: Original issue also suggested ideas for ceiling like pits but to keep the issue on topic I've condensed it to just pit style variations - Konclan

**Comment by TeamSpen210** [comment]
The skybox item would be probably be just predefined sizes, not adjustable. The wall holes are easily done, that's what the current system does. I do need to add logic to add realistic supports, and background decoration like the aperture logo building, pillars and tubing.

**Comment by ellingtonisland** [comment]
@TeamSpen210, how will you generate proper looking a hole in the ceiling for overgrown (like seen in image above) to let in sunlight from the surface. also how will you generate small bts area's for overgrown for "small" wall holes?

**Comment by TeamSpen210** [comment]
I think I have some ideas on how to generate a variable-sized ceiling hole. To generate the skybox itself, I'll be placing randomised instances in a 51-sized grid around the map.

**Comment by Luke18033** [comment]
Bottomless pits? I don't have any bottomless pits in BEE2.

**Comment by Konclan** [comment]
You can get bottomless pits in clean style using the 3d skybox I believe

**Comment by Konclan** [comment]
From @corrupt21

Can the reconstructing pits look like this?
![untitled](https://cloud.githubusercontent.com/assets/17777059/14674127/ac9fc6c2-0745-11e6-942b-ed32a0aa6678.png)

**Comment by Luke18033** [comment]
As I mentioned in that other issue, bottomless pits shouldn't be tied to the skybox anymore once the chamber exterior system is implemented. So Clean, Ovegrown, and P1 would probably have an option under Style Properties to use a bottomless pit. Whereas Art Therapy and Old Aperture would use their reservoir/sphere exteriors by default and have no option for regular goo.

**Comment by Konclan** [comment]
#3891

**Comment by DatPerkYT** [comment]
I still have NO IDEA how to do this, even after reading everything, nothing worked.
