### ISSUE TITLE
[Visual Bug] Player avatar not showing up on monitors

### ISSUE THREAD

**Issue by cartman1337** [BEEmod/BEE2-items#878]
I'm standing right in front of the door this camera is set to show on this monitor, but my player avatar is invisible on the screen. I believe this is the same in all styles, but at least it's true in P1 style:
![Invisible avatar](http://i.imgur.com/q4XVJnQ.jpg)

**Comment by Luke18033** [comment]
I think this is a Valve bug...

**Comment by Luke18033** [comment]
I don't think this is really fixable.
