### ISSUE TITLE
[PRL22 Bug] 80´s Old Aperture: The "Exit Doors" not getting closed Is maybe Johnson wanting to save some money ;)?

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#883]
![20161003073848_1](https://cloud.githubusercontent.com/assets/12244376/19035003/3833e50a-893d-11e6-9b8c-c697697190ab.jpg)

**Comment by TeamSpen210** [comment]
Nope, it's a bug. Doors would always close - there might be a turret that's shooting at you, so they need to protect you from that. (70s and P1 style have a clip which blocks turret visibility, so they stop shooting.)

**Comment by TheDarkBomber** [comment]
@LautaroL20 You don't need ¿ in English.

**Comment by LautaroL20** [comment]
@TheDarkBomber - Wut?

**Comment by TheDarkBomber** [comment]
@LautartoL20 There is an upside down question mark in the title.

**Comment by LautaroL20** [comment]
@TheDarkBomber - Oh, i know. But at same time isn´t my fault that english Keyboars do not includes "¿". I think its more acurate to using both signs (Personal opinion). Example, some people preffer to say just "ok" instead of the full word "Okay".

**Comment by ZombiePwner1** [comment]
@LautaroL20 you do know cave Johnson is dead right?

**Comment by LautaroL20** [comment]
You don´t say.....

**Comment by TeamSpen210** [comment]
Been fixed for a while.
