### ISSUE TITLE
70´s Old Aperture: Glass Panel causes the Funnel no not reach its full trajectory, in a "Mysterious Way"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#887]
![20161003203844_1](https://cloud.githubusercontent.com/assets/12244376/19057979/3fb1abba-89aa-11e6-94c0-d4577892bbe5.jpg)

**Comment by TeamSpen210** [comment]
That is very wrong...

**Comment by LautaroL20** [comment]
Yep, indeed.

**Comment by LautaroL20** [comment]
So, what was causing this weird bug?

**Comment by TeamSpen210** [comment]
I really don't know. Can you reliably reproduce it?

**Comment by LautaroL20** [comment]
Okay, ill record a small gameplay if this was not fixed yet.

**Comment by LautaroL20** [comment]
Nope, this isn´t fixed, the video should be uploaded in a few minutes.

**Comment by TeamSpen210** [comment]
I can reproduce this now.

**Comment by LautaroL20** [comment]
Anyways, here is the video: https://youtu.be/JKMm_G2GrT4
