### ISSUE TITLE
[PRL22 Bug] 70´s Old Aperture: The Exit door do not stops the Funnel´s trajectory, and it may causes players to getting stuck forever into the Catwalk

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#888]
This can cause on Non-Fast players to getting stuck forever into the Catwalk, and therefore this could induce in some players to give a "Thumbs down" to the creator:

![20161003205954_1](https://cloud.githubusercontent.com/assets/12244376/19058285/5ec34340-89ac-11e6-9550-0826fe5999cc.jpg)

**Comment by TeamSpen210** [comment]
I think I'll add a random sign to the catwalk, which happens to block elevators

**Comment by TeamSpen210** [comment]
A different exit corner is used, which allows you to walk off the platform.
