### ISSUE TITLE
[PRL22 Bug] 70´s Old Aperture: The SP Entry corridor N°6 is having "Nodraw and Missing Frames", as well as having a "Mysterious Portalgun" on floor

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#891]
![20161003223052_1](https://cloud.githubusercontent.com/assets/12244376/19059820/34d874a8-89b9-11e6-960d-86b70961cda6.jpg)

**Comment by cartman1337** [comment]
I've already opened a ticket on the portalgun on the floor in #861. It's also present in corridors 5 and 7.

**Comment by GiovanH** [comment]
This has been fixed. 
![2020-08-18 20_04_50-PORTAL 2](https://user-images.githubusercontent.com/6759280/90580296-1ad51800-e18e-11ea-92b6-d5b2eb0c859d.png)

**Comment by LautaroL20** [comment]
Alright, then ill close this. BTW, someone mysteriously renamed the "fixed" label to "done" and i don´t see why.

**Comment by Luke18033** [comment]
We merged "fixed" and "implemented", since they're basically the same thing.
