### ISSUE TITLE
Template Brushes don't get rotated

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#894]
![20161005065145_1](https://cloud.githubusercontent.com/assets/12244376/19112172/d4319964-8ad9-11e6-9f35-d8ca74ac9091.jpg)

**Comment by LautaroL20** [comment]
Maybe adding the `handle_4_directions` to set the position in the PeTi editor would fix this?

**Comment by TeamSpen210** [comment]
It'd be better for me to figure out exactly how U/V axes work for brushes, so this can be fixed for all surfaces.

**Comment by libbybapa** [comment]
I am very pleased to see this 'Fixed for next release'.  Thanks!
