### ISSUE TITLE
Resizeable Breakable Glass

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#898]
Probably one of my (And for many people) most wished Test element: Breakable Glass. (Breakable by Cubes, and other elements such as Grenades) with "Setteable fragility" trhough "Button Type".

![20161005105624_1](https://cloud.githubusercontent.com/assets/12244376/19116072/99537932-8aea-11e6-91c1-fb6f49f3ef82.jpg)

**Comment by TeamSpen210** [comment]
For those I'll want to use `func_breakable_surf`. That allows shattering the glass, and then punching holes in particular sections while leaving fragments. It only allows rectangular shapes though.

**Comment by Luke18033** [comment]
How about a breakable grating as well?

**Comment by LautaroL20** [comment]
Uhmm.... That kind of item would be only affected by powerful things such as grenades.

**Comment by Luke18033** [comment]
That would be fine.

**Comment by TeamSpen210** [comment]
I couldn't do that the same way, so it won't let you break specific parts. You need code access to allow `func_breakable_surf` to have a grate variant (co-existing with the originals).

**Comment by Konclan** [comment]
#95
