### ISSUE TITLE
"Stage Backdrop" Item and elements

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#902]
I'd like to recommend a "Stage" item for BEE2. It would be placed like a glass window/grating item and would display the 'exotic location' backgrounds from the Stage chapter of Aperture Tag. The timer would change the background in question, much like signage.

**Comment by LautaroL20** [comment]
It would be something like this, maybe? If so, it would be a good idea:
![20161007013609_1](https://cloud.githubusercontent.com/assets/12244376/19178957/cb9eb70e-8c2e-11e6-9b08-0fd89d4840d9.jpg)

**Comment by Byzarru** [comment]
More like this:
![image](https://cloud.githubusercontent.com/assets/22107242/19197799/7882d1ce-8c81-11e6-90e3-48b49b0bd6b3.png)

Although I like the pop-up signs too. I was going to suggest them along with a bunch of other ambient items.

**Comment by Luke18033** [comment]
This seems like a good idea. For Portal 2, the textures would need to be packed.

**Comment by TeamSpen210** [comment]
These would be skyboxes set, once I get around to implementing 3D skybox exteriors. The sign is also a good idea, like the flat one but on a pole. I might also give it an input, so you can have a check/cross on a pole to make it more visible.

**Comment by Byzarru** [comment]
Would the backdrop have its own independent skybox or will it need to use whatever skybox has been selected for the whole map?

**Comment by Luke18033** [comment]
This will really be its own style.
