### ISSUE TITLE
Overgrown ceiling observation room is unstyled.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#903]
![20161007142149_1](https://cloud.githubusercontent.com/assets/18079316/19180643/0bbc1f3c-8c9a-11e6-9ee3-8085918384d2.jpg)

**Comment by ZombiePwner1** [comment]
Overgrown variant should have sun light coming through and vegetation.

**Comment by LautaroL20** [comment]
I am styling the Overgrown Ceilling & Floor Observations >:D

**Comment by ZombiePwner1** [comment]
@TeamSpen210 the overgrown variant can have sunlight and plants coming through.

**Comment by LautaroL20** [comment]
If anyone wants to styling it go ahead, i didnt like the one i did so feel free to make it anyone....

**Comment by ZombiePwner1** [comment]
@LautaroL20 perhaps I may style it. Btw come online wheels

**Comment by ZombiePwner1** [comment]
@LautaroL20 I've already started work on this.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Sounds good, hope it will look with a nice overgrown feel.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Hope so but due to the size I can only add a small amount of plants.

**Comment by ZombiePwner1** [comment]
I hope @TeamSpen210 likes this when it's done I will also do the floor variant aswell.

**Comment by TeamSpen210** [comment]
For the ceiling room, you could have a couple different arrangements of plants we randomly choose between. Just put them in visgroups and I'll split it up properly.

**Comment by ZombiePwner1** [comment]
Okay I will do the ceiling then give it to you so you can split them up.

**Comment by ZombiePwner1** [comment]
Also @TeamSpen210 how should I do the floor variant?

**Comment by TeamSpen210** [comment]
Make a destroyed version of the Clean floor. Perhaps have holes in the floor tiles under it. (Note we can't actually break the glass ceiling, since you could get stuck in the room).

**Comment by ZombiePwner1** [comment]
Yes I will replace the glass with cracked glass. And as for the holes I will try my best to make it look destroyed.

**Comment by ZombiePwner1** [comment]
Also @TeamSpen210 which other styles have observation room variants that need styling? BTS large observation room could have a 3D skybox with test chambers in the distance.

**Comment by TeamSpen210** [comment]
See #1673 for the BTS obs room.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 @LautaroL20 Heres is the ceiling variant. 
![20170404201849_1](https://cloud.githubusercontent.com/assets/18079316/24656185/0d45f370-1974-11e7-8803-42ede769146e.jpg)

**Comment by LautaroL20** [comment]
Dat leak....

**Comment by ZombiePwner1** [comment]
@LautaroL20 It's not a leak it's the way the skybox has decided to go btw come onliene.

**Comment by TeamSpen210** [comment]
We can't have the giant truss sticking out, that could stop you from flinging or just pass into the floor.

**Comment by ZombiePwner1** [comment]
Okay i will remove that perhaps i could replace it with some plants.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Either way is the ceiling variant good?

**Comment by LautaroL20** [comment]
Nope, Spencer will have to give it a revision....

**Comment by ZombiePwner1** [comment]
@LautaroL20 Was i asking you for a comment? No.

**Comment by ZombiePwner1** [comment]
![20170405070005_1](https://cloud.githubusercontent.com/assets/18079316/24682685/96fe4f28-19cd-11e7-893a-ab2c64d84038.jpg)

See @LautaroL20 It's not leaked the goo appears properly.

**Comment by LautaroL20** [comment]
Anyways, leak or not it must be improved. The pict really doesn´t say much...

**Comment by ZombiePwner1** [comment]
@LautaroL20 I know i'm trying to get rid of the darkness inside the observation room.

**Comment by ZombiePwner1** [comment]
@LautaroL20 There we go i got rid of the darkness.


![20170405070935_1](https://cloud.githubusercontent.com/assets/18079316/24682937/e168272c-19ce-11e7-9990-5b88b18d6dfa.jpg)

**Comment by LautaroL20** [comment]
Uhm, its fine i guess, but still requires many aditional details. Btw where are the observation´s frames?

**Comment by ZombiePwner1** [comment]
@LautaroL20 I was in the top of the observation room so there was nodraw you wheely.

**Comment by LautaroL20** [comment]
Well, in the picture youre not crossing any wall and since the ceilling isn´t supposed to be a leak, thats why. 

> you wheely.

It looks like i am a Bike move now....

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Please let me know if this looks good.

**Comment by ZombiePwner1** [comment]
Heres some more improvements.


![20170405072512_1](https://cloud.githubusercontent.com/assets/18079316/24683338/15e08d44-19d1-11e7-9aef-21a9b0d40714.jpg)



![20170405072528_1](https://cloud.githubusercontent.com/assets/18079316/24683342/1dd5f85e-19d1-11e7-97b6-cc23f09d05f9.jpg)

**Comment by LautaroL20** [comment]
It would be better if that unnecesary skybox would gone entirely. It gives a leak feeling.

**Comment by ZombiePwner1** [comment]
I am going to put some frames there soon.

**Comment by ZombiePwner1** [comment]
But aside from the skybox what do you think of it.

**Comment by LautaroL20** [comment]
It seems to be getting improved a bit.

**Comment by ZombiePwner1** [comment]
![20170405074936_1](https://cloud.githubusercontent.com/assets/18079316/24683855/6fe0d094-19d4-11e7-868e-b1fbec0c53da.jpg)


How's this?

**Comment by LautaroL20** [comment]
Well, it reminds me of some Over Corridors that has the same ceilling wich requires some tunning touches.

**Comment by Luke18033** [comment]
Some of the original lights should still be there.

**Comment by ZombiePwner1** [comment]
@Luke18033 There is no point since the sun light already lights up the room and the original lights would be pointless.

**Comment by Luke18033** [comment]
It's not about whether or not it's useful, it's about whether it makes sense. It doesn't make much sense for every single light to just disappear.

**Comment by ZombiePwner1** [comment]
@Luke18033 Ruined chamber 7 from the original portal is missing the unstationary scaffold entirely.

**Comment by Luke18033** [comment]
But it's not missing the emitters, or the test chamber sign, the HEP items, the piston stairs...
Most of the lights would be missing, but a few would still be there, with some broken or sitting on the ground.

**Comment by TeamSpen210** [comment]
Indeed, otherwise you might not be able to even tell it was supposed to be light models.

**Comment by ZombiePwner1** [comment]
@Luke18033 It is missing the emitters last time I checked the emitters were gone aswell.

**Comment by LautaroL20** [comment]
I agree with @Luke18033 The Ceilling Observation should have some light strips inside, if not it woudn´t be an actual "Observation Room".

**Comment by ZombiePwner1** [comment]
Okay fine I will add some of the lights back but most of them will be broken 1 2 or 3 will remain on.

**Comment by Luke18033** [comment]
@ZombiePwner1 - Indeed, the emitters are gone.

**Comment by ZombiePwner1** [comment]
@Luke18033 See? Told you.

**Comment by hop193** [comment]
The hole looks a little odd when it's perfectly square like that...

**Comment by TeamSpen210** [comment]
Indeed, some partially attached light strips might help with that.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 I will get those light strips added soon.
