### ISSUE TITLE
50´s Old Aperture Light Bridge makes a pretty loud sound similar to an overgrown shut down observation 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#907]
It would be better to implement a low sound effect instead, even if it was on purpose, since it is pretty loud.

---

![20161007044806_1](https://cloud.githubusercontent.com/assets/12244376/19183296/081e4fe0-8c4e-11e6-97c4-d483efcf3caa.jpg)

**Comment by TeamSpen210** [comment]
It's intentional, but I should make it quieter.

**Comment by TeamSpen210** [comment]
This has been removed.
