### ISSUE TITLE
Make the Cutout Tile to work on walls

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#908]
![20160925141256_1](https://cloud.githubusercontent.com/assets/12244376/19184134/15512a58-8c52-11e6-9ea0-ab3b1e144754.jpg)

**Comment by Luke18033** [comment]
I think this is already going to be added as a separate item.

**Comment by Byzarru** [comment]
Why make it a separate item? Wouldn't it be more convenient to the mapmaker to use a) one item for cutout tiles on several orientations and b) use up less slots in the palette? Unless it's due to programming constraints, I don't see why vertical cutout tiles and horizontal tiles should be separate.

**Comment by TeamSpen210** [comment]
It'll probably be the same item, but appear slightly different on walls.

**Comment by LautaroL20** [comment]
This seems to be a duplicate of: https://github.com/BEEmod/BEE2-items/issues/449
