### ISSUE TITLE
BEE2 does not re-extract packages after update

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#910]
I am getting a Build Error from both Cameras and Monitors, because of missing `camera_base.vmf` and `monitor.vmf`. I probably just have a broken Portal 2 though, because it looks like everybody else can use monitors fine.

**Comment by LautaroL20** [comment]
Id suggest to verify game cache files, maybe you have files too mixed up. Other than that, it could be your Hard device being damaged.

**Comment by TeamSpen210** [comment]
Go to settings, and press the button marked 'reset package caches'. That will force the instances to be copied again. Also check that you don't have 'preserve resources' checked in the development tab.

**Comment by Luke18033** [comment]
@TeamSpen210 Nope, still won't work.

**Comment by Luke18033** [comment]
No, the folder `instances/bee2/XXX/items/monitor` doesn't even exist.

**Comment by TeamSpen210** [comment]
Whoops, actually it's [`screen/`](https://github.com/TeamSpen210/BEE2-items/tree/master/packages/monitors/resources/instances/clean/items/screen).

**Comment by Luke18033** [comment]
That doesn't exist either...

**Comment by TeamSpen210** [comment]
Strange. It's definitely in the resources folders, but not in your instances. Try deleting your `config/games.cfg`, and the `instances/bee2` folder. That should force it to extract the files again.

**Comment by Luke18033** [comment]
It wouldn't work though, since the game is looking for the `monitor` folder (I think).

**Comment by TeamSpen210** [comment]
I misread, the folder is called `screen/`.

**Comment by Luke18033** [comment]
It seems to be working (partially at least), because the camera has an icon now.

**Comment by Luke18033** [comment]
So, not a bug, I guess.

**Comment by Luke18033** [comment]
Actually, I think this is a bug, because BEE2 should be updating the `instances/bee2/` folder after an update.

**Comment by LautaroL20** [comment]
The sub-extracting process is now fixed, so i think that this will not be a problem anymore.

**Comment by Luke18033** [comment]
This isn't fixed, I'm still having the problem.

**Comment by Luke18033** [comment]
Fixed now.
