### ISSUE TITLE
Overgrown floor observation room isn't styled

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#917]
![20161013155751_1](https://cloud.githubusercontent.com/assets/18079316/19340969/08874a3a-915e-11e6-9d44-cc6874a57eae.jpg)

**Comment by Luke18033** [comment]
I don't think this is a bug.

**Comment by GiovanH** [comment]
![2020-08-18 21_37_43-PORTAL 2](https://user-images.githubusercontent.com/6759280/90585734-2418b180-e19b-11ea-8cbc-8f1b700d55c5.png)

This is no longer the case.
