### ISSUE TITLE
[PRL22] Light Strips have unordered positions into the Bee2.4 palette

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#925]
![palette](https://cloud.githubusercontent.com/assets/12244376/19412453/fe65192a-92ec-11e6-911c-a6cb2dd7c6e4.png)

**Comment by TeamSpen210** [comment]
Items on the list are sorted first by the package they belong to. The warm strip is with the BEEMOD items, and the cool one is with the Valve items.

**Comment by LautaroL20** [comment]
I think it should be actually with the Valve items, my point of view for this is because the warm light is already a valve-maded item, and since reflection gel is ordered with the rest of gels, the same should goes for the warm light.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Don't forget reflection was unavailable in the main game and warm lights were unavailable in the editor since valve is too lazy to make them.

**Comment by TeamSpen210** [comment]
Reflection gel is in the Valve packages since it requires the original item to support the functionality, so it might as well be there.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - You don´t say

**Comment by TeamSpen210** [comment]
This has been fixed as a consequence of merging the strip items.
