### ISSUE TITLE
Timer Intervals

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#929]
~~These droppers would function like the droppers in the breakable glass level where 1 dropper is active and the other isn't and the other would activate after the 1st one finishes and it would just keep doing that.~~

A logic item that fires on timed intervals. Timings could be changed with an item var so we can be slightly more precise than the 30s widget.

**Comment by Byzarru** [comment]
Couldn't this be achieved with clever use of timers and triggers?

**Comment by TeamSpen210** [comment]
I need to add a timer item, which pulses at intervals. Feed that into a toggle latch, and this would be doable easily.

**Comment by LautaroL20** [comment]
Then title should be renamed to "Timer Intervals".

**Comment by TeamSpen210** [comment]
Would any other variations of this be useful?

**Comment by Konclan** [comment]
Moving to #3886
