### ISSUE TITLE
Bee2.4 is not using the letter from the first word on its "Export Button", and that lends to confusion

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#950]
If all the other buttons does start with the letter from the first word, the same should goes for the Export button, wich must be using the "E" instead of "O". Personally, this had been confusing me many times.

![beemod wrong letter](https://cloud.githubusercontent.com/assets/12244376/19490208/ae997f62-9544-11e6-8f06-bd2c616b8b9f.png)

**Comment by ZombiePwner1** [comment]
I think that's on purpose since it's options.

**Comment by TheDarkBomber** [comment]
@ZombiePwner1 There is Compile Options and that's not the letter O.

**Comment by ZombiePwner1** [comment]
Ik that i'm not dumb

**Comment by LautaroL20** [comment]
For some "Mysterious reason" this fix is not present in the public PRL25, yet in the Dev version is.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Ur version is bugged since i've receiving this fix.

**Comment by LautaroL20** [comment]
This issue was moved to BEEmod/BEE2.4#606

**Comment by LautaroL20** [comment]
This issue was moved to BEEmod/BEE2.4#607

**Comment by LautaroL20** [comment]
@ZombiePwner1 - I may know why this happens, actually Spencer seems to changed the App download link for some reason, and now i have a slightly different build. Anyways i will always keep with the Development version, this was for help testing weird bugs.
