### ISSUE TITLE
Make all the gel droppers to not interfere with items, since they doesn't really occupy space behind wall

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#952]
Trying to placing a light strip under the dropper but its not possible....really, Valve?

![fliderstrix](https://cloud.githubusercontent.com/assets/12244376/19533980/5f0af1e0-9618-11e6-9403-0c2e8f5c2a58.png)

**Comment by TeamSpen210** [comment]
Ok, that's doable. However different styles can make them stick out further. The problem is that this would let you place items like Light Bridges in the block too.

**Comment by Luke18033** [comment]
Once again, Really, Valve. Except that this time I'm referring to the fact that they included these "invalid positions" at all...

**Comment by LautaroL20** [comment]
@TeamSpen210 - Thanks for this small fix!
