### ISSUE TITLE
Defective Turrets

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#954]
Skin 1 is normal. Skin 2 is defective. Skin 3 is boxed turret or another type of defective turret that shoots bullets.

**Comment by TeamSpen210** [comment]
I can't add `Button Type`, but I could another way. It'll probably be a separate item.

**Comment by ZombiePwner1** [comment]
Okay then

**Comment by TeamSpen210** [comment]
Well, I've actually added a few of those in one of the entrances..

**Comment by Luke18033** [comment]
Not sure why this is still open, we've said these won't be added.
