### ISSUE TITLE
Locking Pedestal Buttons

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/BEE2-items#968]
This is a new behaviour for Pedestal Buttons. When connected to certain items (AutoPortals currently), the timer setting will be ignored. They will instead behave like an infinite pedestal button, locking down. However, when the autoportal turns off (from another activating) the button will be reset. I'm thinking of also applying this to Cube Droppers, so they automatically effectively have a 2 second timer and match the lights on the dropper. The timer sign is also automatically removed (although this already happens for Cube Droppers).

If the item has multiple inputs, or the button has multiple outputs this doesn't take effect. (There the timer has an actual effect.)

**Comment by Luke18033** [comment]
Isn't this implemented now?

**Comment by TeamSpen210** [comment]
Wow, yes.
