### ISSUE TITLE
Stylevar to allow doorless entry rooms in Portal 1

### ISSUE THREAD

**Issue by LogicDeLuxe** [BEEmod/BEE2-items#970]
In Portal 1, test chambers usually have no entry door and fizzler after the elevator. Would it be possible to have that option in the P1 style?

---

Note that this needs to be a stylevar, since in some cases it can alter puzzles (such as by allowing the portal surfaces to be used)

**Comment by Luke18033** [comment]
It should already have this, when nothing is connected to the exit door.

**Comment by TeamSpen210** [comment]
That's the exit, not entry. The reason it isn't done is that it might alter puzzles - it might be problematic if the player can fizzle cubes, or close portals.

**Comment by Konclan** [comment]
well isn't that why its an option?

**Comment by Luke18033** [comment]
Oh, the *entry* door, not the exit. This would be good as a stylevar.

**Comment by Luke18033** [comment]
Maybe also have an option to disable the fizzler in the entrance.

**Comment by TeamSpen210** [comment]
There is another issue with this - where should the test sign go?

**Comment by BETTEREXTENEDEDITORMOD** [comment]
you could make a test sign item and place it wherever you want

**Comment by Luke18033** [comment]
This should also remove the entrance fizzler. As for the test sign, it would just go in the normal location? This was just suggesting to remove the door from the corridor, not to remove the corridor itself.

**Comment by Luke18033** [comment]
It still needs to be a stylevar, since having access to those portal surfaces could break the puzzle.
