### ISSUE TITLE
 P1 Stationary wall emitters cause a compile error saying it's from clean style? 

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#975]
This is very strange since it couldn't open the instance file from clean style yet i'm in P1 how does that work? compile log.

I] vbsp: Calling original VBSP...
[I] vbsp: Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[E] <Valve>: KeyValues Error: RecursiveLoadFromBuffer:  got } in key in file C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\GameInfo.txt
 | GameInfo, FileSystem, SearchPaths, 
 | Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/BEE2/clean/items/scaffold/wall.vmf
 | 
 |_

[I] BEE2_config: Saving changes in config "C:\Users\Josh\Desktop\File folder\prl22\config/compile.cfg"!
[E] vbsp: VBSP failed! (1)

**Comment by LautaroL20** [comment]
What happens there is that there is missing the item variant for it, and compiler its trying to using the instance from Clean Style. But you should still be able to using the unstyled item in P1.

**Comment by ZombiePwner1** [comment]
I know that but this is very strange since i was able to use wall emitters before.

**Comment by LautaroL20** [comment]
Thats weird then...

**Comment by ZombiePwner1** [comment]
Okay this only happens when you place the wall emitter without any connections.

**Comment by Luke18033** [comment]
Fixed now?

**Comment by Luke18033** [comment]
Now fixed
![image](https://user-images.githubusercontent.com/19228201/91385051-e2b08380-e7e4-11ea-9c06-8bbf63d04402.png)
