### ISSUE TITLE
P1 Relaxation Vault table is using the portal 2 version.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#980]
![20161104215913_1](https://cloud.githubusercontent.com/assets/18079316/20008071/0f67c25c-a2da-11e6-82fb-3cb2329d7bcd.jpg)

**Comment by Luke18033** [comment]
Fixed now?

**Comment by TeamSpen210** [comment]
Nope.

**Comment by Luke18033** [comment]
Fixed by removing these from the corridors.
