### ISSUE TITLE
"Cross-eyed" laserfields in various positions in 80s style

### ISSUE THREAD

**Issue by cartman1337** [BEEmod/BEE2-items#988]
Laserfields pointed upwards are crossed in some positions, but not all. See below.
![80s laserfields](http://i.imgur.com/y6yubIx.jpg)

**Comment by TeamSpen210** [comment]
Will be fixed by using totally different code, which can't have this problem.

**Comment by IceTudor** [comment]
Poor things, disabled laser fields, who would've known?

**Comment by Endermage77** [comment]
On the other hand, they'd be pretty cool on their own for manually setting death laser grids like you see in practically any spy movie.
