### ISSUE TITLE
Implement a "Cancel" button on the Loading and Exporting Panel 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#990]
For people who do not use Preserve Game Directories, having a "Cancel" button on the Exporting Panel to stop the process could be really useful. For example,  if we forgot to do something (Add an item, or things like that), we are not forced to wait until the process finish.

____________________________________________________________________________________________________

![palette](https://cloud.githubusercontent.com/assets/12244376/20174038/bb044f6a-a71a-11e6-8923-5ee9095bbd14.png)

**Comment by Luke18033** [comment]
This is a BEE2.4 issue.

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2.4#566
