### ISSUE TITLE
Make the Clean Small Observation to "Turn On Lighting" when walking outside the entry door

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#991]
It would be nice to have the same system of turn on lighitng when walking outside the entry door as the Overgrown Small Ovservation has.

**Comment by ZombiePwner1** [comment]
I'm pretty sure the clean observation room already has this.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Im pretty sure you still do not know much on the PeTi items. Clean Smal Observation is actually totally static.

**Comment by TeamSpen210** [comment]
This actually makes the lighting much lower quality, and is best when restricted as much as possible.
