### ISSUE TITLE
Panel cubes.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#994]
![20161112153909_1](https://cloud.githubusercontent.com/assets/18079316/20236405/f6ce2fd6-a8ee-11e6-9522-97e6781587e2.jpg)

if you pick up the cube attached to the panel the panel will also move. This can be tied to pretty much anything. Portals will also work with them but they will be abit buggy if you move the panel while it has a portal on it. NOTE: This will not work well with some elements like the tractor beam or gel droppers but it can be used for some. Link for the map: http://steamcommunity.com/sharedfiles/filedetails/?id=795268550

**Comment by LautaroL20** [comment]
I dont like magical items that moves in a mysterious way when you grab a cube. They looks a bit ridiculous.
I would use an Angled Panel instead...

**Comment by ZombiePwner1** [comment]
The panel is sticking to the cube so the panel moves when the cube moves

**Comment by Byzarru** [comment]
How about a panel on wooden stands? That would make more sense.

**Comment by Luke18033** [comment]
What would make more sense is a panel which can be picked up and moved around.

**Comment by Konclan** [comment]
Better left for UCPs
