### ISSUE TITLE
Protruding pedestal buttons getting "Out of the Platform" when they were set to "Infinite"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#998]
They works fine when uses timer function, however when are set to "Infinite" for some unknown reason these ends up out of the platform:

![20161106230252_1](https://cloud.githubusercontent.com/assets/12244376/20245638/680a3902-a984-11e6-8409-660e21729b4f.jpg)

**Comment by Luke18033** [comment]
How did you get this? Is it a custom item?

**Comment by LautaroL20** [comment]
Its a custom addon we were working on. Once its fixed, we will released it into the public version.

**Comment by LautaroL20** [comment]
Congratulations! They all works like a charm now:

![20161216115932_1](https://cloud.githubusercontent.com/assets/12244376/21269014/c63dae9e-c38f-11e6-84f8-8ff5dad59b65.jpg)

**Comment by TeamSpen210** [comment]
There actually seems to be an issue with different rotations.
